{"tax_id":"703306","names":[{"lang":"en","v":"DATA TRADING LIMITED"},{"lang":"hk","v":"德泰貿易有限公司"}],"company_since":"2000-02-02","company_dissolved":"2017-12-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703187","names":[{"lang":"en","v":"DIGITAL PACIFIC LIMITED (d2002-05-17)"},{"lang":"hk","v":"添科有限公司"}],"company_since":"2000-02-02","company_dissolved":"2002-05-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703165","names":[{"lang":"en","v":"DOMAIN NINE ENTERPRISES LIMITED"}],"company_since":"2000-02-02","company_dissolved":"2002-11-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"703311","names":[{"lang":"en","v":"CHINA FALCON INTERNATIONAL LIMITED (d2002-11-22)"},{"lang":"hk","v":"華福國際有限公司"}],"company_since":"2000-02-02","company_dissolved":"2002-11-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703226","names":[{"lang":"en","v":"CHINA CITY PROPERTIES COMPANY LIMITED"},{"lang":"hk","v":"中都置業有限公司"}],"company_since":"2000-02-02","company_dissolved":"2005-12-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703184","names":[{"lang":"en","v":"ELIT CONSULTING LIMITED"},{"lang":"hk","v":"才智精英顧問有限公司"}],"company_since":"2000-02-02","company_dissolved":"2009-06-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703160","names":[{"lang":"en","v":"E IN PROPERTIES LIMITED"},{"lang":"hk","v":"溢盈置業有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703286","names":[{"lang":"en","v":"EQUITY ENTERPRISES LIMITED (HK)"},{"lang":"hk","v":"群益企業有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703334","names":[{"lang":"en","v":"E-DOTCOM LIMITED"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703373","names":[{"lang":"en","v":"E-MEDICINE SERVICE LIMITED"}],"company_since":"2000-02-02","company_dissolved":"2010-05-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703348","names":[{"lang":"en","v":"EVERTECH INVESTMENTS OVERSEAS LIMITED"},{"lang":"hk","v":"永怡投資海外有限公司"}],"company_since":"2000-02-02","company_dissolved":"2008-07-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703192","names":[{"lang":"en","v":"EMPIRE TREND LIMITED (d2002-03-28)"},{"lang":"hk","v":"進鴻有限公司"}],"company_since":"2000-02-02","company_dissolved":"2002-03-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703337","names":[{"lang":"en","v":"ELECTEC (CHINA) LIMITED"}],"company_since":"2000-02-02","company_dissolved":"2009-12-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703272","names":[{"lang":"en","v":"CHINA INDUSTRIES LIMITED (d2004-04-16)"},{"lang":"hk","v":"華人實業有限公司"}],"company_since":"2000-02-02","company_dissolved":"2004-04-16","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703349","names":[{"lang":"en","v":"CHINA LEISURE TRAVEL &amp; CULTURE CO., LIMITED"},{"lang":"hk","v":"中國消閑旅遊文化事業有限公司"}],"company_since":"2000-02-02","company_dissolved":"2006-06-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703256","names":[{"lang":"en","v":"CHINA PROFIT HOLDINGS LIMITED (d2008-07-04)"},{"lang":"hk","v":"中溢集團有限公司"}],"company_since":"2000-02-02","company_dissolved":"2008-07-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703222","names":[{"lang":"en","v":"EARTH DEVELOPMENT LIMITED (d2009-06-26)"},{"lang":"hk","v":"啟耀發展有限公司"}],"company_since":"2000-02-02","company_dissolved":"2009-06-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703296","names":[{"lang":"en","v":"CHINA FIELD INTERNATIONAL LIMITED"},{"lang":"hk","v":"昌暉國際有限公司"}],"company_since":"2000-02-02","company_dissolved":"2019-08-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703223","names":[{"lang":"en","v":"FORTUNE HORSE TRADING LIMITED"},{"lang":"hk","v":"祿駿貿易有限公司"}],"company_since":"2000-02-02","company_dissolved":"2006-06-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703183","names":[{"lang":"en","v":"CHINA PROGRESS LIMITED (d2002-04-04)"},{"lang":"hk","v":"鋒城有限公司"}],"company_since":"2000-02-02","company_dissolved":"2002-04-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703309","names":[{"lang":"en","v":"FOXON INTERNATIONAL LIMITED"},{"lang":"hk","v":"福盛國際有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703378","names":[{"lang":"en","v":"FRANCE AUTASON (ASIA) LIMITED"},{"lang":"hk","v":"法國奧德臣(亞洲)有限公司"}],"company_since":"2000-02-02","company_dissolved":"2009-08-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703280","names":[{"lang":"en","v":"FUTATOMO COMPANY LIMITED"},{"lang":"hk","v":"二友商事有限公司"}],"company_since":"2000-02-02","company_dissolved":"2007-07-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703216","names":[{"lang":"en","v":"CHINACOM ENTERPRISES LIMITED"},{"lang":"hk","v":"長江企業有限公司"}],"company_since":"2000-02-02","company_dissolved":"2005-02-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703194","names":[{"lang":"en","v":"FUTURE TREND LIMITED (d2013-06-21)"},{"lang":"hk","v":"遠倡有限公司"}],"company_since":"2000-02-02","company_dissolved":"2013-06-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703375","names":[{"lang":"en","v":"GAINFORD SECRETARIAL SERVICES (HONG KONG) LIMITED"},{"lang":"hk","v":"福豪秘書(香港)有限公司"}],"company_since":"2000-02-02","company_dissolved":"2007-10-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703387","names":[{"lang":"en","v":"CHINAHOWFUN.COM CORPORATION LIMITED"},{"lang":"hk","v":"好玩網上行有限公司"}],"company_since":"2000-02-02","company_dissolved":"2006-06-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703109","names":[{"lang":"en","v":"GEN-TEX TRADING (H.K.) CO., LIMITED"},{"lang":"hk","v":"駿達時貿易有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703344","names":[{"lang":"en","v":"CHINASOFT VENTURES LIMITED"}],"company_since":"2000-02-02","company_dissolved":"2012-01-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703139","names":[{"lang":"en","v":"GLOBAL FISHERY (H.K.) LIMITED"}],"company_since":"2000-02-02","company_dissolved":"2017-12-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"703183","names":[{"lang":"en","v":"CHINA PROGRESS LIMITED (d2002-04-04)"},{"lang":"hk","v":"鋒城有限公司"}],"company_since":"2000-02-02","company_dissolved":"2002-04-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"703100","names":[{"lang":"en","v":"ComNet Telecom (HK) Limited"},{"lang":"hk","v":"信通電話(香港)有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"703222","names":[{"lang":"en","v":"EARTH DEVELOPMENT LIMITED (d2009-06-26)"},{"lang":"hk","v":"啟耀發展有限公司"}],"company_since":"2000-02-02","company_dissolved":"2009-06-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703114","names":[{"lang":"en","v":"EASTERN DRAGON SHIPPING CO., LIMITED"},{"lang":"hk","v":"華龍船務有限公司"}],"company_since":"2000-02-02","company_dissolved":"2006-09-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703309","names":[{"lang":"en","v":"FOXON INTERNATIONAL LIMITED"},{"lang":"hk","v":"福盛國際有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703378","names":[{"lang":"en","v":"FRANCE AUTASON (ASIA) LIMITED"},{"lang":"hk","v":"法國奧德臣(亞洲)有限公司"}],"company_since":"2000-02-02","company_dissolved":"2009-08-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703280","names":[{"lang":"en","v":"FUTATOMO COMPANY LIMITED"},{"lang":"hk","v":"二友商事有限公司"}],"company_since":"2000-02-02","company_dissolved":"2007-07-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703194","names":[{"lang":"en","v":"FUTURE TREND LIMITED (d2013-06-21)"},{"lang":"hk","v":"遠倡有限公司"}],"company_since":"2000-02-02","company_dissolved":"2013-06-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703375","names":[{"lang":"en","v":"GAINFORD SECRETARIAL SERVICES (HONG KONG) LIMITED"},{"lang":"hk","v":"福豪秘書(香港)有限公司"}],"company_since":"2000-02-02","company_dissolved":"2007-10-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"703205","names":[{"lang":"en","v":"GC STRUCTURED PRODUCTS LIMITED"}],"company_since":"2000-02-02","company_dissolved":"2015-08-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703192","names":[{"lang":"en","v":"EMPIRE TREND LIMITED (d2002-03-28)"},{"lang":"hk","v":"進鴻有限公司"}],"company_since":"2000-02-02","company_dissolved":"2002-03-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703286","names":[{"lang":"en","v":"EQUITY ENTERPRISES LIMITED (HK)"},{"lang":"hk","v":"群益企業有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703109","names":[{"lang":"en","v":"GEN-TEX TRADING (H.K.) CO., LIMITED"},{"lang":"hk","v":"駿達時貿易有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703139","names":[{"lang":"en","v":"GLOBAL FISHERY (H.K.) LIMITED"}],"company_since":"2000-02-02","company_dissolved":"2017-12-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703348","names":[{"lang":"en","v":"EVERTECH INVESTMENTS OVERSEAS LIMITED"},{"lang":"hk","v":"永怡投資海外有限公司"}],"company_since":"2000-02-02","company_dissolved":"2008-07-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703142","names":[{"lang":"en","v":"GLORY STEP INTERNATIONAL LIMITED (d2006-02-10)"},{"lang":"hk","v":"榮士國際有限公司"}],"company_since":"2000-02-02","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703198","names":[{"lang":"en","v":"EXCEL WISE DEVELOPMENT LIMITED"},{"lang":"hk","v":"盛宏發展有限公司"}],"company_since":"2000-02-02","company_dissolved":"2017-12-01","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703190","names":[{"lang":"en","v":"GOLDEN CASTLE MANAGEMENT LIMITED (d2011-07-08)"},{"lang":"hk","v":"金中堡管理有限公司"}],"company_since":"2000-02-02","company_dissolved":"2011-07-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703107","names":[{"lang":"en","v":"FASHION TREND LIMITED (d2007-06-15)"},{"lang":"hk","v":"興時配料有限公司"}],"company_since":"2000-02-02","company_dissolved":"2007-06-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703324","names":[{"lang":"en","v":"GOLDEN KING TECHNOLOGY LIMITED"},{"lang":"hk","v":"嘉僑科技有限公司"}],"company_since":"2000-02-02","company_dissolved":"2005-02-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703316","names":[{"lang":"en","v":"FILMAX LIMITED (d2012-06-01)"}],"company_since":"2000-02-02","company_dissolved":"2012-06-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703254","names":[{"lang":"en","v":"GOLDEN PROPERTIES (HOLDINGS) LIMITED"},{"lang":"hk","v":"高恆管理(控股)有限公司"}],"company_since":"2000-02-02","company_dissolved":"2005-12-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703219","names":[{"lang":"en","v":"GOLDLAND ENTERPRISES LIMITED (d2003-10-03)"},{"lang":"hk","v":"金亮企業有限公司"}],"company_since":"2000-02-02","company_dissolved":"2003-10-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703120","names":[{"lang":"en","v":"GOOD TRANS EXPRESS (HK) LIMITED"},{"lang":"hk","v":"佳航通運(香港)有限公司"}],"company_since":"2000-02-02","company_dissolved":"2002-11-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703108","names":[{"lang":"en","v":"GRANDMASS CYBER FACTORY (CHINA) LIMITED"},{"lang":"hk","v":"盛創數碼工廠(中國)有限公司"}],"company_since":"2000-02-02","company_dissolved":"2012-01-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703338","names":[{"lang":"en","v":"GREAT CHINA VACATION LIMITED"},{"lang":"hk","v":"大中華渡假有限公司"}],"company_since":"2000-02-02","company_dissolved":"2005-12-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703147","names":[{"lang":"en","v":"H. P. FRANCE (H.K.) INCORPORATION LIMITED"}],"company_since":"2000-02-02","company_dissolved":"2012-07-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"703291","names":[{"lang":"en","v":"HENRY TRADING LIMITED (d2006-06-16)"},{"lang":"hk","v":"興源貿易有限公司"}],"company_since":"2000-02-02","company_dissolved":"2006-06-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703124","names":[{"lang":"en","v":"GLORY GENERAL MOTOR SERVICES AND SCRAP METALS LIMITED"},{"lang":"hk","v":"燦記有限公司"}],"company_since":"2000-02-02","company_dissolved":"2010-03-05","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703214","names":[{"lang":"en","v":"HENWAY ENTERPRISES LIMITED"},{"lang":"hk","v":"興華企業有限公司"}],"company_since":"2000-02-02","company_dissolved":"2012-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703331","names":[{"lang":"en","v":"HI-TECH GREEN LIMITED"},{"lang":"hk","v":"科萌現代科技有限公司"}],"company_since":"2000-02-02","company_dissolved":"2001-09-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703379","names":[{"lang":"en","v":"HINNOK (ASIA) TRADING COMPANY LIMITED"},{"lang":"hk","v":"亨隆(亞洲)貿易有限公司"}],"company_since":"2000-02-02","company_dissolved":"2002-07-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703269","names":[{"lang":"en","v":"HOLLIES INTERNATIONAL COSMETIC PRODUCTS (HONG KONG) LIMITED"},{"lang":"hk","v":"活麗姿國際化妝品(香港)有限公司"}],"company_since":"2000-02-02","company_dissolved":"2003-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703365","names":[{"lang":"en","v":"HONG KONG KENTOP TRADING LIMITED"},{"lang":"hk","v":"香港佳拓貿易有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703218","names":[{"lang":"en","v":"HOWAY ENTERPRISES LIMITED"},{"lang":"hk","v":"豪威企業有限公司"}],"company_since":"2000-02-02","company_dissolved":"2018-12-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703117","names":[{"lang":"en","v":"HUGO INTERNATIONAL DEVELOPMENT LIMITED"}],"company_since":"2000-02-02","company_dissolved":"2002-10-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703384","names":[{"lang":"en","v":"I FOCUS COMPANY LIMITED"},{"lang":"hk","v":"資訊點有限公司"}],"company_since":"2000-02-02","company_dissolved":"2002-07-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703320","names":[{"lang":"en","v":"I-CONSTRUCTION LIMITED (d2003-06-20)"},{"lang":"hk","v":"建築網有限公司"}],"company_since":"2000-02-02","company_dissolved":"2003-06-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703193","names":[{"lang":"en","v":"HEALTHCARE PHARMACY CO LIMITED"},{"lang":"hk","v":"寶健大藥房有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703289","names":[{"lang":"en","v":"HENLY TRADING LIMITED"},{"lang":"hk","v":"恒利貿易有限公司"}],"company_since":"2000-02-02","company_dissolved":"2001-10-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703228","names":[{"lang":"en","v":"INTERNATIONAL DEVELOPMENT LIMITED (d2002-02-08)"},{"lang":"hk","v":"國際發展有限公司"}],"company_since":"2000-02-02","company_dissolved":"2002-02-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703230","names":[{"lang":"en","v":"HEXON DEVELOPMENT LIMITED"},{"lang":"hk","v":"興成發展有限公司"}],"company_since":"2000-02-02","company_dissolved":"2012-03-23","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703302","names":[{"lang":"en","v":"INTERNET ENTERPRISES LIMITED (d2005-07-08)"},{"lang":"hk","v":"英特網企業有限公司"}],"company_since":"2000-02-02","company_dissolved":"2005-07-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703253","names":[{"lang":"en","v":"HO &amp; PARTNERS (CHINA) ENGINEERS &amp; ARCHITECTS LIMITED"},{"lang":"hk","v":"何顯毅(中國)工程建築師樓有限公司"}],"company_since":"2000-02-02","company_dissolved":"2016-09-02","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703350","names":[{"lang":"en","v":"JAPAN COMMERCIAL HOTLINE LIMITED"},{"lang":"hk","v":"日本商情有限公司"}],"company_since":"2000-02-02","company_dissolved":"2001-09-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"703261","names":[{"lang":"en","v":"JENNEX (FAR EAST) LIMITED"},{"lang":"hk","v":"俊星(遠東)有限公司"}],"company_since":"2000-02-02","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703264","names":[{"lang":"en","v":"JENOX INVESTMENTS LIMITED"},{"lang":"hk","v":"正龍投資有限公司"}],"company_since":"2000-02-02","company_dissolved":"2011-02-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703301","names":[{"lang":"en","v":"HONG KONG SUCCESS INTERNATIONAL HOLDING LIMITED"},{"lang":"hk","v":"香港誠鴻國際集團有限公司"}],"company_since":"2000-02-02","company_dissolved":"2005-02-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703215","names":[{"lang":"en","v":"JETCOM ENTERPRISES LIMITED"},{"lang":"hk","v":"精工企業有限公司"}],"company_since":"2000-02-02","company_dissolved":"2009-06-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703298","names":[{"lang":"en","v":"JETCOM LIMITED (d2003-01-30)"}],"company_since":"2000-02-02","company_dissolved":"2003-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"703355","names":[{"lang":"en","v":"HONG KONG VACATION CLUB LIMITED"},{"lang":"hk","v":"香港渡假會所有限公司"}],"company_since":"2000-02-02","company_dissolved":"2005-12-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703342","names":[{"lang":"en","v":"HONG KONG VACATION LIMITED"},{"lang":"hk","v":"香港渡假有限公司"}],"company_since":"2000-02-02","company_dissolved":"2005-12-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703304","names":[{"lang":"en","v":"JEXON (FAR EAST) LIMITED"},{"lang":"hk","v":"捷誠(遠東)有限公司"}],"company_since":"2000-02-02","company_dissolved":"2009-06-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703249","names":[{"lang":"en","v":"JOINTEK BUSINESS CONSULTANTS LIMITED (HK)"},{"lang":"hk","v":"駿德商業顧問有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703167","names":[{"lang":"en","v":"KAM YAU LIMITED"},{"lang":"hk","v":"錦佑有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703382","names":[{"lang":"en","v":"KINGCOMICS.COM LIMITED"},{"lang":"hk","v":"漫畫帝國網域有限公司"}],"company_since":"2000-02-02","company_dissolved":"2013-10-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"703276","names":[{"lang":"en","v":"IECONSULTANTS LIMITED"}],"company_since":"2000-02-02","company_dissolved":"2002-07-05","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703217","names":[{"lang":"en","v":"LANTEX ENTERPRISES LIMITED"},{"lang":"hk","v":"樂俊企業有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703148","names":[{"lang":"en","v":"INTEGRATED CORPORATE SOLUTIONS LIMITED"}],"company_since":"2000-02-02","company_dissolved":"2015-09-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703368","names":[{"lang":"en","v":"LEESE LIMITED"},{"lang":"hk","v":"李氏有限公司"}],"company_since":"2000-02-02","company_dissolved":"2003-10-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"703213","names":[{"lang":"en","v":"LINKFORD ENTERPRISES LIMITED"},{"lang":"hk","v":"聯富企業有限公司"}],"company_since":"2000-02-02","company_dissolved":"2009-01-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703376","names":[{"lang":"en","v":"INTERNATIONAL EDUCATION FUND LIMITED (d2008-03-07)"},{"lang":"hk","v":"國際教育基金有限公司"}],"company_since":"2000-02-02","company_dissolved":"2008-03-07","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703233","names":[{"lang":"en","v":"INTRANESIS COMMUNICATIONS LIMITED"},{"lang":"hk","v":"網通科訊有限公司"}],"company_since":"2000-02-02","company_dissolved":"2003-12-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703323","names":[{"lang":"en","v":"I-HOME LIMITED (d2010-05-20)"},{"lang":"hk","v":"住宅網有限公司"}],"company_since":"2000-02-02","company_dissolved":"2010-05-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703345","names":[{"lang":"en","v":"LORENZO CRYSTAL CHINA LIMITED"}],"company_since":"2000-02-02","company_dissolved":"2017-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703246","names":[{"lang":"en","v":"J &amp; L TRADING DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"啓裕貿易發展有限公司"}],"company_since":"2000-02-02","company_dissolved":"2002-05-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703290","names":[{"lang":"en","v":"LS SynaLife Trading Company Limited"},{"lang":"hk","v":"新豐鏈貿易有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703377","names":[{"lang":"en","v":"JAPAN MOUSSE COMPANY LIMITED"},{"lang":"hk","v":"日本慕絲有限公司"}],"company_since":"2000-02-02","company_dissolved":"2005-12-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703138","names":[{"lang":"en","v":"LUNG YIP ENGINEERING LIMITED"},{"lang":"hk","v":"隆業工程有限公司"}],"company_since":"2000-02-02","company_dissolved":"2008-02-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703314","names":[{"lang":"en","v":"LUI DESIGN LIMITED"},{"lang":"hk","v":"雷怡設計有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703299","names":[{"lang":"en","v":"ITB TECHNOLOGY COMPANY LIMITED"},{"lang":"hk","v":"互聯創意科技有限公司"}],"company_since":"2000-02-02","company_dissolved":"2003-05-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703140","names":[{"lang":"en","v":"MANNA 2000 LIMITED"},{"lang":"hk","v":"瑪納二000年有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"703153","names":[{"lang":"en","v":"MASONS COMPANY LIMITED"}],"company_since":"2000-02-02","company_dissolved":"2006-06-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703294","names":[{"lang":"en","v":"JETMARK INTERNATIONAL LIMITED"},{"lang":"hk","v":"集明國際有限公司"}],"company_since":"2000-02-02","company_dissolved":"2014-01-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703179","names":[{"lang":"en","v":"JIANFENG PHARMACEUTICAL (HONG KONG) LIMITED"},{"lang":"hk","v":"香港尖峰葯業有限公司"}],"company_since":"2000-02-02","company_dissolved":"2006-06-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703164","names":[{"lang":"en","v":"MEDIA3WAY LIMITED"}],"company_since":"2000-02-02","company_dissolved":"2013-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703208","names":[{"lang":"en","v":"METROCON GROUP LIMITED"},{"lang":"hk","v":"萬建力集團有限公司"}],"company_since":"2000-02-02","company_dissolved":"2002-03-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703207","names":[{"lang":"en","v":"KEY FAITH TECHNOLOGY LIMITED"},{"lang":"hk","v":"其暉科技有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703308","names":[{"lang":"en","v":"MEXWAY TRADING LIMITED"},{"lang":"hk","v":"美滙貿易有限公司"}],"company_since":"2000-02-02","company_dissolved":"2009-10-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703134","names":[{"lang":"en","v":"MING-FOREVER HOLDINGS LIMITED"},{"lang":"hk","v":"明遠控股有限公司"}],"company_since":"2000-02-02","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703330","names":[{"lang":"en","v":"Mirum Hong Kong Limited"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703170","names":[{"lang":"en","v":"MIYOSHI ELECTRONICS LIMITED"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703146","names":[{"lang":"en","v":"MODERN UNIVERSAL ENGINEERING LIMITED"},{"lang":"hk","v":"現代世紀工程有限公司"}],"company_since":"2000-02-02","company_dissolved":"2006-06-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703166","names":[{"lang":"en","v":"MORE EASY INTERNATIONAL LIMITED"},{"lang":"hk","v":"多易事國際有限公司"}],"company_since":"2000-02-02","company_dissolved":"2006-06-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703155","names":[{"lang":"en","v":"MULTI-METRO LIMITED"},{"lang":"hk","v":"新城動力有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703128","names":[{"lang":"en","v":"NANFANG ALLOY-SHEET (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"南方合金板(香港)有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703177","names":[{"lang":"en","v":"NAVA POLYBAGS FTY. LIMITED"},{"lang":"hk","v":"立華膠袋廠有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703271","names":[{"lang":"en","v":"NEW EQUITY INDUSTRIES LIMITED"},{"lang":"hk","v":"龍嘉實業有限公司"}],"company_since":"2000-02-02","company_dissolved":"2005-04-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703224","names":[{"lang":"en","v":"NEW POWER INDUSTRIES LIMITED"},{"lang":"hk","v":"新强實業有限公司"}],"company_since":"2000-02-02","company_dissolved":"2009-04-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703257","names":[{"lang":"en","v":"NEW TRADE HOLDINGS LIMITED (d2002-03-01)"},{"lang":"hk","v":"利業集團有限公司"}],"company_since":"2000-02-02","company_dissolved":"2002-03-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703364","names":[{"lang":"en","v":"LORENZO JEWELRY CHINA LIMITED"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703328","names":[{"lang":"en","v":"Maunsell Consultants Asia Co. Limited"},{"lang":"hk","v":"茂盛(亞洲)工程顧問有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703251","names":[{"lang":"en","v":"OCEAN SKY DEVELOPMENT LIMITED (d2016-08-12)"},{"lang":"hk","v":"海陞發展有限公司"}],"company_since":"2000-02-02","company_dissolved":"2016-08-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703173","names":[{"lang":"en","v":"ORION FOODS H.K. LIMITED"},{"lang":"hk","v":"中貿食品香港有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703149","names":[{"lang":"en","v":"PMC CHINA TRADING COMPANY LIMITED"},{"lang":"hk","v":"合力洋行(中國)有限公司"}],"company_since":"2000-02-02","company_dissolved":"2013-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703204","names":[{"lang":"en","v":"POWERVIEW TECHNOLOGY INTERNATIONAL LIMITED"},{"lang":"hk","v":"宏遠科技國際有限公司"}],"company_since":"2000-02-02","company_dissolved":"2004-07-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703318","names":[{"lang":"en","v":"MICROXPERT NETWORK SYSTEM LIMITED"},{"lang":"hk","v":"兆科網絡系統有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703266","names":[{"lang":"en","v":"MILLION LINK INVESTMENTS LIMITED (d2006-05-19)"},{"lang":"hk","v":"萬利投資有限公司"}],"company_since":"2000-02-02","company_dissolved":"2006-05-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703176","names":[{"lang":"en","v":"OUJI CHEMICAL LIMITED"},{"lang":"hk","v":"歐技化學品有限公司"}],"company_since":"2000-02-02","company_dissolved":"2011-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703346","names":[{"lang":"en","v":"MING FAI PRINTING LIMITED"},{"lang":"hk","v":"明輝印刷有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703203","names":[{"lang":"en","v":"RAIN-FOREST CONSTRUCTION ENGINEERING LIMITED"},{"lang":"hk","v":"榮科工程營造有限公司"}],"company_since":"2000-02-02","company_dissolved":"2001-09-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703111","names":[{"lang":"en","v":"PROSPER ENTERPRISE INTERNATIONAL LIMITED"},{"lang":"hk","v":"宏茂企業國際有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703267","names":[{"lang":"en","v":"PRITRADE (HK) LIMITED"}],"company_since":"2000-02-02","company_dissolved":"2005-05-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703126","names":[{"lang":"en","v":"SCCT-STAR CHINA CONTAINER TECHNOLOGY LIMITED"}],"company_since":"2000-02-02","company_dissolved":"2011-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703143","names":[{"lang":"en","v":"MULTIFORTUNE HOLDINGS LIMITED"},{"lang":"hk","v":"翔盛集團有限公司"}],"company_since":"2000-02-02","company_dissolved":"2003-01-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703352","names":[{"lang":"en","v":"SEA CAMPUS ONLINE LIMITED"}],"company_since":"2000-02-02","company_dissolved":"2005-01-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703326","names":[{"lang":"en","v":"SENFORD TECHNOLOGY LIMITED"},{"lang":"hk","v":"盛豐科技有限公司"}],"company_since":"2000-02-02","company_dissolved":"2012-07-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703367","names":[{"lang":"en","v":"SHEN MO INDUSTRIES CO., LIMITED"},{"lang":"hk","v":"神模實業有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703275","names":[{"lang":"en","v":"NEW NATURE GOLF COURSE DESIGN &amp; PLANNING CO., LIMITED"},{"lang":"hk","v":"新自然高爾夫球場設計企劃有限公司"}],"company_since":"2000-02-02","company_dissolved":"2018-08-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703372","names":[{"lang":"en","v":"SHER CONSULTING LIMITED (d2007-06-15)"}],"company_since":"2000-02-02","company_dissolved":"2007-06-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703285","names":[{"lang":"en","v":"NEW SCORE ENTERPRISES LIMITED (d2002-03-01)"},{"lang":"hk","v":"新盛企業有限公司"}],"company_since":"2000-02-02","company_dissolved":"2002-03-01","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703381","names":[{"lang":"en","v":"MUST SUCCESS CO. LIMITED"}],"company_since":"2000-02-02","company_dissolved":"2011-12-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703250","names":[{"lang":"en","v":"SINO CASTLE DEVELOPMENT LIMITED (d2003-10-03)"},{"lang":"hk","v":"順強發展有限公司"}],"company_since":"2000-02-02","company_dissolved":"2003-10-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703221","names":[{"lang":"en","v":"SINOJET DEVELOPMENT LIMITED (d2006-09-08)"},{"lang":"hk","v":"兆智發展有限公司"}],"company_since":"2000-02-02","company_dissolved":"2006-09-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703239","names":[{"lang":"en","v":"SKY CITY ENGINEERING LIMITED"},{"lang":"hk","v":"天城工程有限公司"}],"company_since":"2000-02-02","company_dissolved":"2001-06-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703297","names":[{"lang":"en","v":"PACIFIC HOPE INVESTMENTS LIMITED (d2005-06-17)"},{"lang":"hk","v":"保亨投資有限公司"}],"company_since":"2000-02-02","company_dissolved":"2005-06-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703210","names":[{"lang":"en","v":"SKYNET ENTERPRISES LIMITED (d2011-12-09)"},{"lang":"hk","v":"智達企業有限公司"}],"company_since":"2000-02-02","company_dissolved":"2011-12-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703244","names":[{"lang":"en","v":"SNOW LION COMPANY LIMITED"},{"lang":"hk","v":"雪獅有限公司"}],"company_since":"2000-02-02","company_dissolved":"2002-12-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703361","names":[{"lang":"en","v":"SOFTTECH CHINA LIMITED"}],"company_since":"2000-02-02","company_dissolved":"2012-01-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703369","names":[{"lang":"en","v":"MEDSAL HONG KONG LIMITED"}],"company_since":"2000-02-02","company_dissolved":"2009-08-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703363","names":[{"lang":"en","v":"RAINBOW INTERNATIONAL ENTERPRISE LIMITED (d2004-03-19)"}],"company_since":"2000-02-02","company_dissolved":"2004-03-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703359","names":[{"lang":"en","v":"SOFTTECH STANDARD LIMITED"}],"company_since":"2000-02-02","company_dissolved":"2012-01-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703235","names":[{"lang":"en","v":"RUI FENG TRADING LIMITED"},{"lang":"hk","v":"瑞豐鑽石有限公司"}],"company_since":"2000-02-02","company_dissolved":"2014-05-02","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703343","names":[{"lang":"en","v":"SOFTTECH VENTURES LIMITED"}],"company_since":"2000-02-02","company_dissolved":"2012-01-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703150","names":[{"lang":"en","v":"S S SECURITIES LIMITED"},{"lang":"hk","v":"三山證券有限公司"}],"company_since":"2000-02-02","company_dissolved":"2002-05-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703333","names":[{"lang":"en","v":"SALMI INTERNATIONAL LIMITED"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703200","names":[{"lang":"en","v":"SPEEDY PACIFIC DEVELOPMENT LIMITED"},{"lang":"hk","v":"興捷發展有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703245","names":[{"lang":"en","v":"SEASIA P&amp;I SERVICES LIMITED"}],"company_since":"2000-02-02","company_dissolved":"2011-04-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703231","names":[{"lang":"en","v":"STARFORD DEVELOPMENT LIMITED (d2005-12-09)"},{"lang":"hk","v":"陞輝發展有限公司"}],"company_since":"2000-02-02","company_dissolved":"2005-12-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703322","names":[{"lang":"en","v":"STARLINK TECHNOLOGY LIMITED (d2006-06-16)"},{"lang":"hk","v":"天源科技有限公司"}],"company_since":"2000-02-02","company_dissolved":"2006-06-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703197","names":[{"lang":"en","v":"SUCCESS WEALTHY LIMITED (d2001-08-03)"},{"lang":"hk","v":"成遠有限公司"}],"company_since":"2000-02-02","company_dissolved":"2001-08-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703227","names":[{"lang":"en","v":"TAI KAM FLOORING &amp; BUILDING MATERIALS LIMITED"},{"lang":"hk","v":"大金地板木業有限公司"}],"company_since":"2000-02-02","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703281","names":[{"lang":"en","v":"TANWAY INDUSTRIES LIMITED"},{"lang":"hk","v":"泰華實業有限公司"}],"company_since":"2000-02-02","company_dissolved":"2012-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703360","names":[{"lang":"en","v":"SOFTTECH COMPANY LIMITED"}],"company_since":"2000-02-02","company_dissolved":"2012-01-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703122","names":[{"lang":"en","v":"SOGO FAR EAST (INTERNATIONAL) TRAVEL SERVICE CO., LIMITED"},{"lang":"hk","v":"崇光遠東(國際)旅遊有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703358","names":[{"lang":"en","v":"TOMITECH ENTERPRISES LIMITED"},{"lang":"hk","v":"恩達企業有限公司"}],"company_since":"2000-02-02","company_dissolved":"2004-06-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703129","names":[{"lang":"en","v":"SONG LAM INDUSTRIAL (HOLDINGS) LIMITED"},{"lang":"hk","v":"信寧實業控股有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703116","names":[{"lang":"en","v":"TOP WAY ELECTRONICS (H.K.) LIMITED"},{"lang":"hk","v":"拓普電子(香港)有限公司"}],"company_since":"2000-02-02","company_dissolved":"2005-12-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703131","names":[{"lang":"en","v":"TOP-ALITALIA (INT'L) LIMITED"},{"lang":"hk","v":"意上(國際)有限公司"}],"company_since":"2000-02-02","company_dissolved":"2019-12-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703220","names":[{"lang":"en","v":"TOPCOM ENTERPRISES LIMITED (d2009-04-30)"},{"lang":"hk","v":"泰安企業有限公司"}],"company_since":"2000-02-02","company_dissolved":"2009-04-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703388","names":[{"lang":"en","v":"TOYIDEA.COM LIMITED"},{"lang":"hk","v":"鵬高玩具有限公司"}],"company_since":"2000-02-02","company_dissolved":"2001-10-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703145","names":[{"lang":"en","v":"STRATUM COMPANY LIMITED"},{"lang":"hk","v":"翰基有限公司"}],"company_since":"2000-02-02","company_dissolved":"2008-07-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703357","names":[{"lang":"en","v":"TOYLINK INDUSTRIAL LIMITED"},{"lang":"hk","v":"泰利工業有限公司"}],"company_since":"2000-02-02","company_dissolved":"2004-06-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703229","names":[{"lang":"en","v":"SUCCESS CITY DEVELOPMENT LIMITED"},{"lang":"hk","v":"信城發展有限公司"}],"company_since":"2000-02-02","company_dissolved":"2018-12-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703169","names":[{"lang":"en","v":"TRUE SEA INT'L LIMITED"},{"lang":"hk","v":"眞洋國際有限公司"}],"company_since":"2000-02-02","company_dissolved":"2001-03-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703104","names":[{"lang":"en","v":"TUNG LEE PLASTIC MATERIAL TRANSPORTATION COMPANY LIMITED"},{"lang":"hk","v":"通利塑料貨運有限公司"}],"company_since":"2000-02-02","company_dissolved":"2004-10-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703238","names":[{"lang":"en","v":"U SIX HOLDINGS LIMITED"},{"lang":"hk","v":"裕陸控股有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703180","names":[{"lang":"en","v":"SUN TECHNOLOGY TELECOMMUNICATION LIMITED"},{"lang":"hk","v":"日發通訊股份有限公司"}],"company_since":"2000-02-02","company_dissolved":"2003-02-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703168","names":[{"lang":"en","v":"SUPERSTREET.NET (H.K.) LIMITED"}],"company_since":"2000-02-02","company_dissolved":"2005-09-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703209","names":[{"lang":"en","v":"SURE WIN CONSULTING COMPANY LIMITED"}],"company_since":"2000-02-02","company_dissolved":"2002-09-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703313","names":[{"lang":"en","v":"VICTORY WELL INVESTMENTS LIMITED (d2005-09-23)"},{"lang":"hk","v":"凱偉投資有限公司"}],"company_since":"2000-02-02","company_dissolved":"2005-09-23","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703102","names":[{"lang":"en","v":"TAIMING SLIDED METAL TRACKS MFG. LIMITED"},{"lang":"hk","v":"泰明金屬滑軌製造有限公司"}],"company_since":"2000-02-02","company_dissolved":"2002-10-25","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703132","names":[{"lang":"en","v":"WANTED (FAR EAST) LIMITED"},{"lang":"hk","v":"華特(遠東)有限公司"}],"company_since":"2000-02-02","company_dissolved":"2010-08-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"703161","names":[{"lang":"en","v":"WEIDA TECHNOLOGY HONG KONG LIMITED"},{"lang":"hk","v":"威達高科技集團香港有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703234","names":[{"lang":"en","v":"TEXON PROPERTIES LIMITED"},{"lang":"hk","v":"天誠置業有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703371","names":[{"lang":"en","v":"TIANHUI KNITTING PRODUCTS COMPANY LIMITED"},{"lang":"hk","v":"天輝毛織制品有限公司"}],"company_since":"2000-02-02","company_dissolved":"2004-07-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703212","names":[{"lang":"en","v":"WINEX ENTERPRISES LIMITED (d2001-10-05)"},{"lang":"hk","v":"榮龍企業有限公司"}],"company_since":"2000-02-02","company_dissolved":"2001-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"703172","names":[{"lang":"en","v":"WING HUNG HONG LIMITED"},{"lang":"hk","v":"永鴻行有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703265","names":[{"lang":"en","v":"UNITED OCEAN INVESTMENTS LIMITED (d2007-07-20)"},{"lang":"hk","v":"海洋投資有限公司"}],"company_since":"2000-02-02","company_dissolved":"2007-07-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703325","names":[{"lang":"en","v":"WINSTON TECHNOLOGY LIMITED (d2003-06-20)"},{"lang":"hk","v":"宏泰科技有限公司"}],"company_since":"2000-02-02","company_dissolved":"2003-06-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703237","names":[{"lang":"en","v":"TOPCOM HOLDINGS LIMITED"},{"lang":"hk","v":"天豪集團有限公司"}],"company_since":"2000-02-02","company_dissolved":"2005-02-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703242","names":[{"lang":"en","v":"WISE (FAR EAST) LIMITED"},{"lang":"hk","v":"偉泰(遠東)有限公司"}],"company_since":"2000-02-02","company_dissolved":"2009-10-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"703283","names":[{"lang":"en","v":"UNI INDUSTRIES LIMITED"},{"lang":"hk","v":"友聯實業有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703241","names":[{"lang":"en","v":"UNION BASE (HONG KONG) LIMITED"},{"lang":"hk","v":"聯邦(香港)有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703351","names":[{"lang":"en","v":"XIN ZHONG YA (HONGKONG) ENTERPRISES LIMITED"},{"lang":"hk","v":"新中亞(香港)企業有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"703279","names":[{"lang":"en","v":"SUNLITE INVESTMENT (H.K.) COMPANY LIMITED"},{"lang":"hk","v":"(香港)光華投資有限公司"}],"company_since":"2000-02-02","company_dissolved":"2001-08-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"703288","names":[{"lang":"en","v":"WINTOP (FAR EAST) LIMITED"},{"lang":"hk","v":"永德(遠東)有限公司"}],"company_since":"2000-02-02","company_dissolved":"2007-06-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"703175","names":[{"lang":"en","v":"WUHE HOLDINGS LIMITED"},{"lang":"hk","v":"五和控股有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703240","names":[{"lang":"en","v":"WORLD STAR (HONG KONG) LIMITED"},{"lang":"hk","v":"永勝(香港)有限公司"}],"company_since":"2000-02-02","company_dissolved":"2002-10-25","company_type_txt":"Private, ltd by shares"},
{"tax_id":"703171","names":[{"lang":"en","v":"Y.Z.R.Y. INTERNATIONAL LIMITED"},{"lang":"hk","v":"香港雙傑國際有限公司"}],"company_since":"2000-02-02","company_dissolved":"2005-12-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703115","names":[{"lang":"en","v":"YAOMA LIGHTINGS LIMITED"},{"lang":"hk","v":"沃爾瑪照明有限公司"}],"company_since":"2000-02-02","company_dissolved":"2009-06-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703248","names":[{"lang":"en","v":"YUEN FUNG REAL PROPERTIES COMPANY LIMITED"},{"lang":"hk","v":"源豐置業地產有限公司"}],"company_since":"2000-02-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"703353","names":[{"lang":"en","v":"YUNTINIC RESOURCES (HONG KONG) LIMITED"},{"lang":"hk","v":"雲天資源(香港)有限公司"}],"company_since":"2000-02-02","company_dissolved":"2003-06-13","company_type_txt":"Private, ltd by shares"},
