{"tax_id":"656996","names":[{"lang":"en","v":"D &amp; C GROUP (DECORATION &amp; CONSTRUCTION) LIMITED"},{"lang":"hk","v":"裝建集團有限公司"}],"company_since":"1998-10-16","company_dissolved":"2009-09-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"656966","names":[{"lang":"en","v":"GREEN STAR ASIA LIMITED"}],"company_since":"1998-10-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"656867","names":[{"lang":"en","v":"KWOK SHING DISPENSARY LIMITED"},{"lang":"hk","v":"國城參茸中西大藥房有限公司"}],"company_since":"1998-10-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"656871","names":[{"lang":"en","v":"ORIENT GATE LIMITED (d2001-08-10)"},{"lang":"hk","v":"廣偉有限公司"}],"company_since":"1998-10-16","company_dissolved":"2001-08-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"656981","names":[{"lang":"en","v":"PROFIT SKY INTERNATIONAL LIMITED (d2005-09-30)"},{"lang":"hk","v":"盛天國際有限公司"}],"company_since":"1998-10-16","company_dissolved":"2005-09-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"656964","names":[{"lang":"en","v":"PB CORPORATE SERVICES LIMITED"},{"lang":"hk","v":"普柏會計管理有限公司"}],"company_since":"1998-10-16","company_dissolved":"2008-04-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"656939","names":[{"lang":"en","v":"HONG KONG NATUROPA MEDICINE COMPANY LIMITED"},{"lang":"hk","v":"香港天然保藥業有限公司"}],"company_since":"1998-10-16","company_dissolved":"2015-09-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"657013","names":[{"lang":"en","v":"ROYAL PROFIT (HONG KONG) LIMITED"},{"lang":"hk","v":"耀富(香港)有限公司"}],"company_since":"1998-10-16","company_dissolved":"2007-02-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"656994","names":[{"lang":"en","v":"SEPT-GROW TRADING LIMITED"}],"company_since":"1998-10-16","company_dissolved":"2004-12-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"657023","names":[{"lang":"en","v":"INNOVA PACIFIC LIMITED"}],"company_since":"1998-10-16","company_dissolved":"2011-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"657022","names":[{"lang":"en","v":"TOP LEAF HOLDINGS LIMITED"},{"lang":"hk","v":"冠葉集團有限公司"}],"company_since":"1998-10-16","company_dissolved":"2004-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"656928","names":[{"lang":"en","v":"METRO BROADWAY LIMITED"},{"lang":"hk","v":"芷楊有限公司"}],"company_since":"1998-10-16","company_dissolved":"2018-06-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"656887","names":[{"lang":"en","v":"ZIANG KONG INTERNATIONAL TRADE LIMITED"},{"lang":"hk","v":"祥康國際貿易有限公司"}],"company_since":"1998-10-16","company_dissolved":"2000-12-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"656876","names":[{"lang":"en","v":"ROYAL CHANCE LIMITED (d2005-09-30)"},{"lang":"hk","v":"日基有限公司"}],"company_since":"1998-10-16","company_dissolved":"2005-09-30","company_type_txt":"Private, ltd by shares"},
undefined,
