undefined,
{"tax_id":"656543","names":[{"lang":"en","v":"FAVOUR TRADE LIMITED"},{"lang":"hk","v":"溢業有限公司"}],"company_since":"1998-10-09","company_dissolved":"2002-01-25","company_type_txt":"Private, ltd by shares"},
{"tax_id":"656346","names":[{"lang":"en","v":"GLOBAL BUSINESS LIMITED (d2007-02-16)"},{"lang":"hk","v":"博業有限公司"}],"company_since":"1998-10-09","company_dissolved":"2007-02-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"656476","names":[{"lang":"en","v":"DC PLANNING H.K. LIMITED"}],"company_since":"1998-10-09","company_dissolved":"2006-02-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"656424","names":[{"lang":"en","v":"HK PROFESSIONAL TRANSLATION LIMITED"},{"lang":"hk","v":"香港專業翻譯有限公司"}],"company_since":"1998-10-09","company_dissolved":"2008-07-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"656478","names":[{"lang":"en","v":"EVERWELL INSTRUMENTS LIMITED"},{"lang":"hk","v":"高威精密有限公司"}],"company_since":"1998-10-09","company_dissolved":"2011-08-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"656354","names":[{"lang":"en","v":"HOI SING &amp; PHILIP MOVERS COMPANY LIMITED"},{"lang":"hk","v":"海星搬運有限公司"}],"company_since":"1998-10-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"656540","names":[{"lang":"en","v":"HSIEH HSU MACHINERY (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"協旭機械(香港)有限公司"}],"company_since":"1998-10-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"656365","names":[{"lang":"en","v":"FULFIELD ENTERPRISE LIMITED"}],"company_since":"1998-10-09","company_dissolved":"2005-09-23","company_type_txt":"Private, ltd by shares"},
{"tax_id":"656536","names":[{"lang":"en","v":"ISOLUTION CONSULTANTS (H.K.) LIMITED"},{"lang":"hk","v":"創基顧問(香港)有限公司"}],"company_since":"1998-10-09","company_dissolved":"2000-12-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"656545","names":[{"lang":"en","v":"KEYRISE LIMITED (HK)"},{"lang":"hk","v":"啟旭有限公司"}],"company_since":"1998-10-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"656450","names":[{"lang":"en","v":"LA MARQUE LIMITED"}],"company_since":"1998-10-09","company_dissolved":"2000-12-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"656527","names":[{"lang":"en","v":"HUNING INDUSTRIES LIMITED"},{"lang":"hk","v":"顯興實業有限公司"}],"company_since":"1998-10-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"656509","names":[{"lang":"en","v":"EURO ASIA MANAGEMENT LIMITED"},{"lang":"hk","v":"歐亞管理有限公司"}],"company_since":"1998-10-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"656427","names":[{"lang":"en","v":"LINKWILL CONSULTANTS LIMITED"},{"lang":"hk","v":"溢豐顧問有限公司"}],"company_since":"1998-10-09","company_dissolved":"2006-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"656358","names":[{"lang":"en","v":"HENLEX TRADING LIMITED (d2005-11-25)"},{"lang":"hk","v":"軒南貿易有限公司"}],"company_since":"1998-10-09","company_dissolved":"2005-11-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"656351","names":[{"lang":"en","v":"GOLDWILL MANAGEMENT LIMITED"},{"lang":"hk","v":"金滙管理有限公司"}],"company_since":"1998-10-09","company_dissolved":"2001-12-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"656554","names":[{"lang":"en","v":"PROFESSIONAL CONSULTANCY SERVICES LIMITED (d2000-12-22)"},{"lang":"hk","v":"專業顧問有限公司"}],"company_since":"1998-10-09","company_dissolved":"2000-12-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"656362","names":[{"lang":"en","v":"WIN PROSPER INTERNATIONAL LIMITED"},{"lang":"hk","v":"勝隆國際有限公司"}],"company_since":"1998-10-09","company_dissolved":"2010-03-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"656363","names":[{"lang":"en","v":"TEAMBERG INVESTMENTS LIMITED (d2003-06-06)"},{"lang":"hk","v":"添堡投資有限公司"}],"company_since":"1998-10-09","company_dissolved":"2003-06-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"656453","names":[{"lang":"en","v":"SOUTHERN RICH INDUSTRIAL LIMITED"},{"lang":"hk","v":"粵發實業有限公司"}],"company_since":"1998-10-09","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"656533","names":[{"lang":"en","v":"TWENTY FIRST CENTURY TRAVEL COMPANY LIMITED"},{"lang":"hk","v":"廿一世紀旅遊有限公司"}],"company_since":"1998-10-09","company_dissolved":"2005-09-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"656341","names":[{"lang":"en","v":"WELTECH DEVELOPMENT LIMITED"},{"lang":"hk","v":"偉栢發展有限公司"}],"company_since":"1998-10-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
