undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"675496","names":[{"lang":"en","v":"HONG XING LAI INDUSTRIAL LIMITED"},{"lang":"hk","v":"鴻興來實業有限公司"}],"company_since":"1999-05-12","company_dissolved":"2017-12-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675455","names":[{"lang":"en","v":"HONGSMART ASIA LIMITED"},{"lang":"hk","v":"鴻銘亞洲有限公司"}],"company_since":"1999-05-12","company_dissolved":"2015-03-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675471","names":[{"lang":"en","v":"GRAND PIONEER HOLDINGS LIMITED"},{"lang":"hk","v":"順泰集團有限公司"}],"company_since":"1999-05-12","company_dissolved":"2000-09-29","company_type_txt":"Private, ltd by shares"},
{"tax_id":"675492","names":[{"lang":"en","v":"HOST COMPUTER COMPANY LIMITED"},{"lang":"hk","v":"中原電腦有限公司"}],"company_since":"1999-05-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675304","names":[{"lang":"en","v":"I.G.M. LIMITED"},{"lang":"hk","v":"聯生建材製品有限公司"}],"company_since":"1999-05-12","company_dissolved":"2007-08-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675330","names":[{"lang":"en","v":"GRACE CONCORD LIMITED"},{"lang":"hk","v":"儷成有限公司"}],"company_since":"1999-05-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675309","names":[{"lang":"en","v":"IMMUNOGEN BIOTECH COMPANY LIMITED"},{"lang":"hk","v":"抗體生物技術有限公司"}],"company_since":"1999-05-12","company_dissolved":"2004-10-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675490","names":[{"lang":"en","v":"IN OPTICAL COMPANY LIMITED"},{"lang":"hk","v":"時代焦點有限公司"}],"company_since":"1999-05-12","company_dissolved":"2009-04-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675501","names":[{"lang":"en","v":"INFINITY INDUSTRIAL (H.K.) LIMITED"},{"lang":"hk","v":"駿豐實業(香港)有限公司"}],"company_since":"1999-05-12","company_dissolved":"2002-03-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675366","names":[{"lang":"en","v":"INTELLIGENT MOTORS LIMITED"},{"lang":"hk","v":"智能動力有限公司"}],"company_since":"1999-05-12","company_dissolved":"2016-06-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675349","names":[{"lang":"en","v":"INTERNATIONAL PO FUNG INVESTMENT LIMITED"},{"lang":"hk","v":"國際寶峰投資有限公司"}],"company_since":"1999-05-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675345","names":[{"lang":"en","v":"GrandTao Company Limited"},{"lang":"hk","v":"形翺有限公司"}],"company_since":"1999-05-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"675394","names":[{"lang":"en","v":"INTERNET VEHICLES LIMITED"},{"lang":"hk","v":"互聯網汽車有限公司"}],"company_since":"1999-05-12","company_dissolved":"2016-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675438","names":[{"lang":"en","v":"JOIN BEST INDUSTRIAL LIMITED"},{"lang":"hk","v":"聯盛實業有限公司"}],"company_since":"1999-05-12","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"675495","names":[{"lang":"en","v":"H. K. SAN RUN CO. LIMITED"},{"lang":"hk","v":"香港泛悅有限公司"}],"company_since":"1999-05-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"675316","names":[{"lang":"en","v":"JOINCO HOLDINGS LIMITED"},{"lang":"hk","v":"晉港集團有限公司"}],"company_since":"1999-05-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675446","names":[{"lang":"en","v":"JUJU LIMITED"},{"lang":"hk","v":"月月有限公司"}],"company_since":"1999-05-12","company_dissolved":"2004-10-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675368","names":[{"lang":"en","v":"HEXA FUNA INVESTMENT COMPANY LIMITED"},{"lang":"hk","v":"六福投資有限公司"}],"company_since":"1999-05-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675327","names":[{"lang":"en","v":"HAI LONG WANG GROUP (H.K.) LIMITED"},{"lang":"hk","v":"海龍王集團(香港)有限公司"}],"company_since":"1999-05-12","company_dissolved":"2007-09-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"675403","names":[{"lang":"en","v":"KENT JOINT (HONG KONG) LIMITED"},{"lang":"hk","v":"建晉(香港)有限公司"}],"company_since":"1999-05-12","company_dissolved":"2001-09-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675375","names":[{"lang":"en","v":"KENT MOST HOLDINGS LIMITED"},{"lang":"hk","v":"建升集團有限公司"}],"company_since":"1999-05-12","company_dissolved":"2005-09-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675310","names":[{"lang":"en","v":"KENT VICTORY (HONG KONG) LIMITED"},{"lang":"hk","v":"建勝(香港)有限公司"}],"company_since":"1999-05-12","company_dissolved":"2001-02-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675488","names":[{"lang":"en","v":"KIN CHENG INT'L HIGH TECHNICAL LIMITED"},{"lang":"hk","v":"金城國際高科技有限公司"}],"company_since":"1999-05-12","company_dissolved":"2004-08-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675500","names":[{"lang":"en","v":"HONG KONG CHANG QING INTERNATIONAL LIMITED"},{"lang":"hk","v":"香港長青國際有限公司"}],"company_since":"1999-05-12","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"675482","names":[{"lang":"en","v":"KIT DYNAMICS LIMITED"}],"company_since":"1999-05-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675357","names":[{"lang":"en","v":"KU'S FUR COMPANY LIMITED"},{"lang":"hk","v":"顧氏皮草有限公司"}],"company_since":"1999-05-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675447","names":[{"lang":"en","v":"KWONG FUK ELDERLY CARE CENTRE LIMITED"},{"lang":"hk","v":"廣福護老院有限公司"}],"company_since":"1999-05-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675335","names":[{"lang":"en","v":"LANFIELD MARBLE COMPANY LIMITED"},{"lang":"hk","v":"聯發雲石有限公司"}],"company_since":"1999-05-12","company_dissolved":"2007-12-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675520","names":[{"lang":"en","v":"LEAP INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"利普國際有限公司"}],"company_since":"1999-05-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675503","names":[{"lang":"en","v":"LEE HING WATCHES CO., LIMITED"},{"lang":"hk","v":"利興錶業有限公司"}],"company_since":"1999-05-12","company_dissolved":"2009-08-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675454","names":[{"lang":"en","v":"HONG KONG QING TIAN INTERNATIONAL HOLDINGS INDUSTRIAL LIMITED"},{"lang":"hk","v":"香港擎天國際集團實業有限公司"}],"company_since":"1999-05-12","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"675326","names":[{"lang":"en","v":"LINCOLN ELECTRONICS COMPANY LIMITED"}],"company_since":"1999-05-12","company_dissolved":"2007-10-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675515","names":[{"lang":"en","v":"LONGWAY CREATION LIMITED (d2005-05-13)"},{"lang":"hk","v":"恒威基業有限公司"}],"company_since":"1999-05-12","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675483","names":[{"lang":"en","v":"HONG KONG ROLHACH INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"香港努爾哈赤國際集團有限公司"}],"company_since":"1999-05-12","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"675432","names":[{"lang":"en","v":"LUMAVISION LIMITED"}],"company_since":"1999-05-12","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675497","names":[{"lang":"en","v":"HONG KONG SHUANG JIA INTERNATIONAL FASHION ACCESSORIES LIMITED"},{"lang":"hk","v":"香港雙佳國際服飾有限公司"}],"company_since":"1999-05-12","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"675512","names":[{"lang":"en","v":"M.G.B. MARKETING LIMITED"},{"lang":"hk","v":"晶瑩國際發展有限公司"}],"company_since":"1999-05-12","company_dissolved":"2015-06-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675369","names":[{"lang":"en","v":"MATESON (HONG KONG) GARMENT LIMITED"},{"lang":"hk","v":"美善(香港)製衣有限公司"}],"company_since":"1999-05-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"675354","names":[{"lang":"en","v":"MAXX CONCEPT LIMITED"}],"company_since":"1999-05-12","company_dissolved":"2004-10-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675322","names":[{"lang":"en","v":"MICROFIGURE PRODUCTS LIMITED"}],"company_since":"1999-05-12","company_dissolved":"2008-10-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675433","names":[{"lang":"en","v":"MICROIT COMMUNICATION HOLDING LIMITED"},{"lang":"hk","v":"微網通訊有限公司"}],"company_since":"1999-05-12","company_dissolved":"2006-09-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675417","names":[{"lang":"en","v":"MILLION WEALTH (ASIA) LIMITED"},{"lang":"hk","v":"萬裕(亞洲)有限公司"}],"company_since":"1999-05-12","company_dissolved":"2006-09-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675400","names":[{"lang":"en","v":"HONG KONG SOCIETY OF AGING RESEARCH (THE)"},{"lang":"hk","v":"香港老年研究學會"}],"company_since":"1999-05-12","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
{"tax_id":"675461","names":[{"lang":"en","v":"MOUNTAIN ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"南山工程有限公司"}],"company_since":"1999-05-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675425","names":[{"lang":"en","v":"MUSIK COMPANY LIMITED"}],"company_since":"1999-05-12","company_dissolved":"2001-01-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675413","names":[{"lang":"en","v":"HONG KONG TAI YANG INVESTMENT HOLDINGS LIMITED"},{"lang":"hk","v":"香港泰陽投資集團有限公司"}],"company_since":"1999-05-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675525","names":[{"lang":"en","v":"MYWEB HONG KONG LIMITED"}],"company_since":"1999-05-12","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"675376","names":[{"lang":"en","v":"NEW MILLENNIUM FOUNDATION LIMITED"},{"lang":"hk","v":"新世紀基業有限公司"}],"company_since":"1999-05-12","company_dissolved":"2007-07-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675344","names":[{"lang":"en","v":"NEW TONIC CANTEEN LIMITED"},{"lang":"hk","v":"新同力食堂有限公司"}],"company_since":"1999-05-12","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675484","names":[{"lang":"en","v":"HONG KONG UNITEYOU HOLDINGS LIMITED"},{"lang":"hk","v":"香港合爾集團有限公司"}],"company_since":"1999-05-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"675361","names":[{"lang":"en","v":"NEXTEL COMMUNICATIONS LIMITED (d2011-01-28)"},{"lang":"hk","v":"凌志達通訊有限公司"}],"company_since":"1999-05-12","company_dissolved":"2011-01-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675514","names":[{"lang":"en","v":"ORIENTAL HILL LIMITED (d2005-05-13)"},{"lang":"hk","v":"華崚有限公司"}],"company_since":"1999-05-12","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675509","names":[{"lang":"en","v":"OUTSTANDING ADVERTISING COMPANY LIMITED"},{"lang":"hk","v":"滙萃廣告有限公司"}],"company_since":"1999-05-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675527","names":[{"lang":"en","v":"PACIFIC LINE DEVELOPMENT LIMITED"},{"lang":"hk","v":"志遠發展有限公司"}],"company_since":"1999-05-12","company_dissolved":"2006-01-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675526","names":[{"lang":"en","v":"PACIFIC LINE INVESTMENT LIMITED"},{"lang":"hk","v":"志遠投資有限公司"}],"company_since":"1999-05-12","company_dissolved":"2009-10-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675528","names":[{"lang":"en","v":"PACIFIC LUXE HOLDINGS LIMITED (d2005-05-13)"},{"lang":"hk","v":"恒立集團有限公司"}],"company_since":"1999-05-12","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"675380","names":[{"lang":"en","v":"PAN-ISLAND INVESTMENT LIMITED"},{"lang":"hk","v":"環島投資有限公司"}],"company_since":"1999-05-12","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675381","names":[{"lang":"en","v":"PLENTIFUL CHEMICAL LIMITED"},{"lang":"hk","v":"建豐行染料有限公司"}],"company_since":"1999-05-12","company_dissolved":"2017-01-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675373","names":[{"lang":"en","v":"POLY RISE (HONG KONG) LIMITED"},{"lang":"hk","v":"寶陞(香港)有限公司"}],"company_since":"1999-05-12","company_dissolved":"2006-09-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675445","names":[{"lang":"en","v":"POLY WINNER DEVELOPMENT LIMITED"},{"lang":"hk","v":"寶雅發展有限公司"}],"company_since":"1999-05-12","company_dissolved":"2006-09-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675389","names":[{"lang":"en","v":"MULTI CAPITAL HOLDINGS LIMITED (d2003-05-02)"},{"lang":"hk","v":"啓城集團有限公司"}],"company_since":"1999-05-12","company_dissolved":"2003-05-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"675466","names":[{"lang":"en","v":"JOIN LINK ENTERPRISES LIMITED"},{"lang":"hk","v":"豐隆企業有限公司"}],"company_since":"1999-05-12","company_dissolved":"2008-10-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"675360","names":[{"lang":"en","v":"PROFIT BILLION DEVELOPMENT LIMITED (d2004-03-26)"},{"lang":"hk","v":"潤億發展有限公司"}],"company_since":"1999-05-12","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675311","names":[{"lang":"en","v":"PROFIT MART (HONG KONG) LIMITED"},{"lang":"hk","v":"盈軒(香港)有限公司"}],"company_since":"1999-05-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675463","names":[{"lang":"en","v":"JOIN WELL TRADING LIMITED"},{"lang":"hk","v":"聯昌貿易有限公司"}],"company_since":"1999-05-12","company_dissolved":"2002-02-01","company_type_txt":"Private, ltd by shares"},
{"tax_id":"675370","names":[{"lang":"en","v":"PROFIT MEGA (HONG KONG) LIMITED"},{"lang":"hk","v":"盈展(香港)有限公司"}],"company_since":"1999-05-12","company_dissolved":"2016-02-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675318","names":[{"lang":"en","v":"PROSPER CHAMPION HOLDINGS LIMITED (d2005-05-13)"},{"lang":"hk","v":"昌旺集團有限公司"}],"company_since":"1999-05-12","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675409","names":[{"lang":"en","v":"QUANLOK TRADING LIMITED"},{"lang":"hk","v":"樂鈞貿易有限公司"}],"company_since":"1999-05-12","company_dissolved":"2009-10-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675406","names":[{"lang":"en","v":"KAM HUNG CONSTRUCTION (HOLDINGS) LIMITED"},{"lang":"hk","v":"錦鴻建築(集團)有限公司"}],"company_since":"1999-05-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675410","names":[{"lang":"en","v":"ROCKWAY INTERNATIONAL LIMITED (d2003-05-09)"},{"lang":"hk","v":"樂偉環球有限公司"}],"company_since":"1999-05-12","company_dissolved":"2003-05-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"675508","names":[{"lang":"en","v":"RONGFAN (HONG KONG) COMPANY LIMITED (d2010-02-19)"},{"lang":"hk","v":"融凡(香港)有限公司"}],"company_since":"1999-05-12","company_dissolved":"2010-02-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675404","names":[{"lang":"en","v":"SHEEN OCEAN (HONG KONG) LIMITED"},{"lang":"hk","v":"順洋(香港)有限公司"}],"company_since":"1999-05-12","company_dissolved":"2001-09-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675485","names":[{"lang":"en","v":"KIN ON ENGINEERING (FAR EAST) COMPANY LIMITED"},{"lang":"hk","v":"建安工程(遠東)有限公司"}],"company_since":"1999-05-12","company_dissolved":"2008-06-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"675434","names":[{"lang":"en","v":"SHUI FUNG JEWELLERY &amp; GOLD COMPANY LIMITED"},{"lang":"hk","v":"瑞豐珠寶黃金有限公司"}],"company_since":"1999-05-12","company_dissolved":"2006-05-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675312","names":[{"lang":"en","v":"SILVER RISE (HONG KONG) LIMITED"},{"lang":"hk","v":"銀駿(香港)有限公司"}],"company_since":"1999-05-12","company_dissolved":"2007-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675391","names":[{"lang":"en","v":"SINO GROW ENTERPRISES LIMITED"},{"lang":"hk","v":"華上企業有限公司"}],"company_since":"1999-05-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675384","names":[{"lang":"en","v":"LEADE TECH CO. LIMITED"},{"lang":"hk","v":"香港力佳有限公司"}],"company_since":"1999-05-12","company_dissolved":"2014-01-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"675325","names":[{"lang":"en","v":"SANTIAGO FOUNDATION OF CHINA LIMITED"},{"lang":"hk","v":"中國聖地亞哥基金會有限公司"}],"company_since":"1999-05-12","company_dissolved":"2009-10-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675437","names":[{"lang":"en","v":"SPEED WEALTHY LIMITED (d2006-10-27)"},{"lang":"hk","v":"迅佳行有限公司"}],"company_since":"1999-05-12","company_dissolved":"2006-10-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675342","names":[{"lang":"en","v":"SPEEDER INTERNATIONAL LIMITED"},{"lang":"hk","v":"福益紡織有限公司"}],"company_since":"1999-05-12","company_dissolved":"2008-11-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675308","names":[{"lang":"en","v":"LES FLEURS (INTERNATIONAL) COMPANY LIMITED"},{"lang":"hk","v":"花詩國際有限公司"}],"company_since":"1999-05-12","company_dissolved":"2008-10-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675306","names":[{"lang":"en","v":"LIBERTE LIMITED (d2001-02-16)"}],"company_since":"1999-05-12","company_dissolved":"2001-02-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675424","names":[{"lang":"en","v":"STAR AND SEA ELECTRONIC TECHNOLOGIES COMPANY LIMITED"},{"lang":"hk","v":"星海電子科技有限公司"}],"company_since":"1999-05-12","company_dissolved":"2014-09-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675473","names":[{"lang":"en","v":"LIENG SING COMPANY LIMITED"},{"lang":"hk","v":"聯星電子有限公司"}],"company_since":"1999-05-12","company_dissolved":"2019-02-01","company_type_txt":"Private, ltd by shares"},
{"tax_id":"675523","names":[{"lang":"en","v":"STAR RISE DEVELOPMENT LIMITED (d2004-11-19)"},{"lang":"hk","v":"旭星發展有限公司"}],"company_since":"1999-05-12","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675356","names":[{"lang":"en","v":"STRAX R&amp;D LIMITED"}],"company_since":"1999-05-12","company_dissolved":"2002-09-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675396","names":[{"lang":"en","v":"SUCCESS TIME TRADING LIMITED (d2010-07-09)"},{"lang":"hk","v":"成豐貿易有限公司"}],"company_since":"1999-05-12","company_dissolved":"2010-07-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"675491","names":[{"lang":"en","v":"SUNNY TELECOMMUNICATIONS CHINA LIMITED"},{"lang":"hk","v":"新利中國電訊有限公司"}],"company_since":"1999-05-12","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675328","names":[{"lang":"en","v":"SUNRISING INVESTMENTS LIMITED"},{"lang":"hk","v":"東佳榮投資有限公司"}],"company_since":"1999-05-12","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675487","names":[{"lang":"en","v":"SYNERTECH INDUSTRIAL LIMITED"},{"lang":"hk","v":"信利達實業有限公司"}],"company_since":"1999-05-12","company_dissolved":"2015-09-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"675480","names":[{"lang":"en","v":"SYTECH TECHNOLOGIES COMPANY LIMITED"},{"lang":"hk","v":"康盈科技有限公司"}],"company_since":"1999-05-12","company_dissolved":"2008-04-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675510","names":[{"lang":"en","v":"TARGET PRACTICE COMMUNICATIONS LIMITED"},{"lang":"hk","v":"天月策劃有限公司"}],"company_since":"1999-05-12","company_dissolved":"2011-07-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675449","names":[{"lang":"en","v":"TAYLOR ENTERPRISE LIMITED"},{"lang":"hk","v":"泰萊企業有限公司"}],"company_since":"1999-05-12","company_dissolved":"2015-06-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675378","names":[{"lang":"en","v":"TECHNICAL CREATION LIMITED"},{"lang":"hk","v":"德高創建有限公司"}],"company_since":"1999-05-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675435","names":[{"lang":"en","v":"TMC INVESTMENT H.K. LIMITED"}],"company_since":"1999-05-12","company_dissolved":"2012-03-09","company_type_txt":"Public, ltd by shares"},
undefined,
{"tax_id":"675399","names":[{"lang":"en","v":"TOP CREATIVE INVESTMENT LIMITED (d2006-01-13)"},{"lang":"hk","v":"創俊投資有限公司"}],"company_since":"1999-05-12","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"675456","names":[{"lang":"en","v":"TOP PROMOTION INDUSTRIAL COMPANY LIMITED"},{"lang":"hk","v":"第一港聯實業有限公司"}],"company_since":"1999-05-12","company_dissolved":"2006-09-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675427","names":[{"lang":"en","v":"R. J. MURRAY DESIGN LIMITED"}],"company_since":"1999-05-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675513","names":[{"lang":"en","v":"TRADE MASTER INDUSTRIAL LIMITED"},{"lang":"hk","v":"駿利工業有限公司"}],"company_since":"1999-05-12","company_dissolved":"2015-09-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675440","names":[{"lang":"en","v":"NEW WIN ENGINEERING LIMITED"},{"lang":"hk","v":"冠佳工程有限公司"}],"company_since":"1999-05-12","company_dissolved":"2006-11-26","company_type_txt":"Private, ltd by shares"},
{"tax_id":"675332","names":[{"lang":"en","v":"TREASURE HOPE ENTERPRISES LIMITED"},{"lang":"hk","v":"裕濠企業有限公司"}],"company_since":"1999-05-12","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675504","names":[{"lang":"en","v":"TYCHE INVESTMENT (HONG KONG) CO., LIMITED"},{"lang":"hk","v":"泰興投資(香港)有限公司"}],"company_since":"1999-05-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675428","names":[{"lang":"en","v":"UNICORN ASIA CAPITAL LIMITED"},{"lang":"hk","v":"麒麟亞洲資本有限公司"}],"company_since":"1999-05-12","company_dissolved":"2006-09-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675443","names":[{"lang":"en","v":"UNION CHINA DEVELOPMENT LIMITED (d2007-09-21)"},{"lang":"hk","v":"華協發展有限公司"}],"company_since":"1999-05-12","company_dissolved":"2007-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675444","names":[{"lang":"en","v":"PACIFIC TECH DEVELOPMENT LIMITED (d2001-09-28)"},{"lang":"hk","v":"新創發展有限公司"}],"company_since":"1999-05-12","company_dissolved":"2001-09-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"675333","names":[{"lang":"en","v":"UNIVERSAL TREND DEVELOPMENT LIMITED"},{"lang":"hk","v":"佳致發展有限公司"}],"company_since":"1999-05-12","company_dissolved":"2008-02-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675516","names":[{"lang":"en","v":"VICTOR CREATION LIMITED"},{"lang":"hk","v":"華達基業有限公司"}],"company_since":"1999-05-12","company_dissolved":"2002-06-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675524","names":[{"lang":"en","v":"W &amp; D JOINT VENTURE LIMITED"},{"lang":"hk","v":"榮迪聯營有限公司"}],"company_since":"1999-05-12","company_dissolved":"2008-12-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675367","names":[{"lang":"en","v":"PACIFICTECH IMAGING LIMITED"}],"company_since":"1999-05-12","company_dissolved":"2008-10-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"675474","names":[{"lang":"en","v":"WAH NAM ELECTRICAL MACHINERY LIMITED"},{"lang":"hk","v":"華南電機工程有限公司"}],"company_since":"1999-05-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675518","names":[{"lang":"en","v":"WELLSTAR PACIFIC LIMITED"},{"lang":"hk","v":"華達太平洋有限公司"}],"company_since":"1999-05-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675476","names":[{"lang":"en","v":"WELTEX MANUFACTURING (HONG KONG) LIMITED"},{"lang":"hk","v":"安生針織(香港)有限公司"}],"company_since":"1999-05-12","company_dissolved":"2009-11-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675415","names":[{"lang":"en","v":"WIN TOP INDUSTRIAL LIMITED"},{"lang":"hk","v":"萬盛實業有限公司"}],"company_since":"1999-05-12","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675408","names":[{"lang":"en","v":"WING KEI COMPANY LIMITED"},{"lang":"hk","v":"永基(中港)發展有限公司"}],"company_since":"1999-05-12","company_dissolved":"2019-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675352","names":[{"lang":"en","v":"WING TAK (GREATER CHINA) COMPANY LIMITED"},{"lang":"hk","v":"永達(大中華)有限公司"}],"company_since":"1999-05-12","company_dissolved":"2014-10-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675338","names":[{"lang":"en","v":"WING TAT ELECTRICAL MECHANICAL ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"永達機電工程有限公司"}],"company_since":"1999-05-12","company_dissolved":"2009-10-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675430","names":[{"lang":"en","v":"PROPERTY TECHNOLOGY LIMITED"},{"lang":"hk","v":"地產科技有限公司"}],"company_since":"1999-05-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"675519","names":[{"lang":"en","v":"WINLIGHT HOLDINGS LIMITED"},{"lang":"hk","v":"運輝集團有限公司"}],"company_since":"1999-05-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675402","names":[{"lang":"en","v":"WINTEL TECHNOLOGIES INTERNATIONAL LIMITED"},{"lang":"hk","v":"兆億科技有限公司"}],"company_since":"1999-05-12","company_dissolved":"2008-10-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675465","names":[{"lang":"en","v":"SPEEDY SUCCESS ENTERPRISES LIMITED (d2003-04-25)"},{"lang":"hk","v":"迅成企業有限公司"}],"company_since":"1999-05-12","company_dissolved":"2003-04-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675364","names":[{"lang":"en","v":"WIT STAR COMPANY LIMITED"},{"lang":"hk","v":"匯智星有限公司"}],"company_since":"1999-05-12","company_dissolved":"2009-10-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675481","names":[{"lang":"en","v":"Questex Asia Limited"}],"company_since":"1999-05-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"675426","names":[{"lang":"en","v":"XING TAI (HK) INDUSTRY CO., LIMITED"},{"lang":"hk","v":"興泰(香港)實業有限公司"}],"company_since":"1999-05-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"675505","names":[{"lang":"en","v":"ZENITH HOLDINGS (HK) LIMITED"},{"lang":"hk","v":"智聯集團(香港)有限公司"}],"company_since":"1999-05-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675506","names":[{"lang":"en","v":"YOO JYO LOUNGE LIMITED"}],"company_since":"1999-05-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675313","names":[{"lang":"en","v":"SMART GRACE (HONG KONG) LIMITED (d2005-05-13)"},{"lang":"hk","v":"駿悅(香港)有限公司"}],"company_since":"1999-05-12","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"675340","names":[{"lang":"en","v":"YUEN TAI ELECTRICAL COMPANY LIMITED"},{"lang":"hk","v":"元大電業有限公司"}],"company_since":"1999-05-12","company_dissolved":"2005-11-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675472","names":[{"lang":"en","v":"SPEEDY WELL (ASIA) LIMITED"},{"lang":"hk","v":"迅興(亞洲)有限公司"}],"company_since":"1999-05-12","company_dissolved":"2007-05-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"675421","names":[{"lang":"en","v":"SUNGREAT PRINTING MACHINERY LIMITED (d2002-12-27)"},{"lang":"hk","v":"新威印刷機械有限公司"}],"company_since":"1999-05-12","company_dissolved":"2002-12-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675442","names":[{"lang":"en","v":"TOP WEALTH (FAR EAST) LIMITED"},{"lang":"hk","v":"豐利(遠東)有限公司"}],"company_since":"1999-05-12","company_dissolved":"2009-01-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675494","names":[{"lang":"en","v":"TOP-TIE COMPANY LIMITED"}],"company_since":"1999-05-12","company_dissolved":"2019-01-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675321","names":[{"lang":"en","v":"TRIUMPH CREATION LIMITED"},{"lang":"hk","v":"長勝創建有限公司"}],"company_since":"1999-05-12","company_dissolved":"2009-05-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675351","names":[{"lang":"en","v":"UNITED DEVELOPMENT ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"發聯工程有限公司"}],"company_since":"1999-05-12","company_dissolved":"2001-03-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675517","names":[{"lang":"en","v":"WELLSTAR OVERSEAS LIMITED"},{"lang":"hk","v":"華星海外有限公司"}],"company_since":"1999-05-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675343","names":[{"lang":"en","v":"WING FAI WATER WORKS ENGINEERING LIMITED"},{"lang":"hk","v":"榮輝水務工程有限公司"}],"company_since":"1999-05-12","company_dissolved":"2017-08-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"675365","names":[{"lang":"en","v":"XDF FASHION LIMITED"}],"company_since":"1999-05-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"675397","names":[{"lang":"en","v":"WORLDWIDE TECH LIMITED (d2002-06-21)"},{"lang":"hk","v":"豪科有限公司"}],"company_since":"1999-05-12","company_dissolved":"2002-06-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"675346","names":[{"lang":"en","v":"WINTHESUM INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"永德深國際有限公司"}],"company_since":"1999-05-12","company_dissolved":"2002-11-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675314","names":[{"lang":"en","v":"POLY HONOUR (HONG KONG) LIMITED"},{"lang":"hk","v":"寶鴻(香港)有限公司"}],"company_since":"1999-05-12","company_dissolved":"2004-06-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"675307","names":[{"lang":"en","v":"WING SING TAI INVESTMENT LIMITED"},{"lang":"hk","v":"永成泰投資有限公司"}],"company_since":"1999-05-12","company_dissolved":"2003-09-11","company_type_txt":"Private, ltd by shares"},
undefined,
