{"tax_id":"615422","names":[{"lang":"en","v":"CHARTER CONCEPT DEVELOPMENT LIMITED"},{"lang":"hk","v":"志康發展有限公司"}],"company_since":"1997-06-27","company_dissolved":"2001-10-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615124","names":[{"lang":"en","v":"CHATEAUX MANAGEMENT GROUP LIMITED"}],"company_since":"1997-06-27","company_dissolved":"2018-10-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615376","names":[{"lang":"en","v":"CHIEF GAIN DEVELOPMENT LIMITED"},{"lang":"hk","v":"志溢發展有限公司"}],"company_since":"1997-06-27","company_dissolved":"2016-01-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615329","names":[{"lang":"en","v":"CHINA INFORMATION MAGAZINE LIMITED"},{"lang":"hk","v":"中信資訊有限公司"}],"company_since":"1997-06-27","company_dissolved":"2020-04-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615040","names":[{"lang":"en","v":"CHINA NATIONAL SAMKWONG FIREWORKS COMPANY LIMITED"},{"lang":"hk","v":"中華森光煙花有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615257","names":[{"lang":"en","v":"CHINA PACIFIC CRANES &amp; MACHINERY LIMITED"},{"lang":"hk","v":"中太吊機機械有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615133","names":[{"lang":"en","v":"CHINATEX INVESTMENTS LIMITED"},{"lang":"hk","v":"華紡投資有限公司"}],"company_since":"1997-06-27","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615345","names":[{"lang":"en","v":"CHUN FAT HONG (H.K.) LIMITED"},{"lang":"hk","v":"駿發行(香港)有限公司"}],"company_since":"1997-06-27","company_dissolved":"2001-07-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615367","names":[{"lang":"en","v":"CHUNG LUEN GROUP COMPANY LIMITED"},{"lang":"hk","v":"中聯集團股份有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615221","names":[{"lang":"en","v":"CHINA GEOLOGY (HONG KONG) INDUSTRY LIMITED"},{"lang":"hk","v":"中地(香港)實業有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615265","names":[{"lang":"en","v":"CII (TAIAN) LIMITED"},{"lang":"hk","v":"中國基礎建設(泰安)有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615070","names":[{"lang":"en","v":"CITIMATE TRADING LIMITED (d2004-02-27)"},{"lang":"hk","v":"信萬貿易有限公司"}],"company_since":"1997-06-27","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615105","names":[{"lang":"en","v":"CITIMAX (H.K.) LIMITED (d2004-12-10)"},{"lang":"hk","v":"萬達美(香港)有限公司"}],"company_since":"1997-06-27","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615364","names":[{"lang":"en","v":"CITY FORCE HOLDINGS LIMITED"},{"lang":"hk","v":"港峰集團有限公司"}],"company_since":"1997-06-27","company_dissolved":"2012-10-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615136","names":[{"lang":"en","v":"COMPORT OVERSEAS LIMITED"},{"lang":"hk","v":"新寶海外有限公司"}],"company_since":"1997-06-27","company_dissolved":"2003-11-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615415","names":[{"lang":"en","v":"CONCORD CARNIVAL HOLDINGS LIMITED"},{"lang":"hk","v":"和嘉集團有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615254","names":[{"lang":"en","v":"CRAFTWICK CONSTRUCTIONS LIMITED"},{"lang":"hk","v":"旭域營造有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615237","names":[{"lang":"en","v":"DIVA LIMITED (d2003-04-04)"}],"company_since":"1997-06-27","company_dissolved":"2003-04-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615350","names":[{"lang":"en","v":"DOOSAN ELECTRO-MATERIALS (HONG KONG) LIMITED"},{"lang":"hk","v":"斗山電子(香港)有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615377","names":[{"lang":"en","v":"DOUBLE FAITH INTERNATIONAL LIMITED"},{"lang":"hk","v":"雙輝國際有限公司"}],"company_since":"1997-06-27","company_dissolved":"2002-07-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"615206","names":[{"lang":"en","v":"CHENG DONG INTERNATIONAL LIMITED"},{"lang":"hk","v":"城東國際有限公司"}],"company_since":"1997-06-27","company_dissolved":"2003-04-25","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615391","names":[{"lang":"en","v":"CHE FUNG ENTERPRISE (GROUP) LIMITED"},{"lang":"hk","v":"志豐企業(集團)有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615199","names":[{"lang":"en","v":"EASTERN GATE ASSOCIATION LIMITED (THE)"},{"lang":"hk","v":"中華美門協會有限公司"}],"company_since":"1997-06-27","company_dissolved":"2002-02-15","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"615280","names":[{"lang":"en","v":"Effendi (Enterprises) Limited"},{"lang":"hk","v":"易發達(企業)有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"615157","names":[{"lang":"en","v":"CHIEN-GHI-CHEN-HO FOUNDATION LIMITED"},{"lang":"hk","v":"簡吉陳何慈善有限公司"}],"company_since":"1997-06-27","company_dissolved":"2003-12-16","company_type_txt":"Ltd by guarantee"},
{"tax_id":"615382","names":[{"lang":"en","v":"EMPEROR STAR INVESTMENTS LIMITED"},{"lang":"hk","v":"皇星投資有限公司"}],"company_since":"1997-06-27","company_dissolved":"2001-05-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615077","names":[{"lang":"en","v":"CHINA ACCENT (HK) LIMITED"},{"lang":"hk","v":"中國商社有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615293","names":[{"lang":"en","v":"EVER ASIA CONSULTANTS LIMITED"},{"lang":"hk","v":"永亞顧問有限公司"}],"company_since":"1997-06-27","company_dissolved":"2003-04-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615309","names":[{"lang":"en","v":"CHINA CLEVER DEVELOPMENT LIMITED"},{"lang":"hk","v":"漢慧發展有限公司"}],"company_since":"1997-06-27","company_dissolved":"2003-08-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615062","names":[{"lang":"en","v":"EVERGREEN INTERNATIONAL LIMITED (d2001-03-23)"},{"lang":"hk","v":"長青藤國際有限公司"}],"company_since":"1997-06-27","company_dissolved":"2001-03-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615398","names":[{"lang":"en","v":"EXCEL CHINA HOLDINGS LIMITED"},{"lang":"hk","v":"卓華集團有限公司"}],"company_since":"1997-06-27","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615426","names":[{"lang":"en","v":"EXCEL STONE PRODUCTS LIMITED"},{"lang":"hk","v":"昕麗石材有限公司"}],"company_since":"1997-06-27","company_dissolved":"1999-12-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615394","names":[{"lang":"en","v":"CHRISTIAN CENTRAL CHURCH (MONGKOK) LIMITED"},{"lang":"hk","v":"基督中心堂(旺角)有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
{"tax_id":"615385","names":[{"lang":"en","v":"FAN DE FA VIDEO MUSICAL PRODUCTION CO. LIMITED"},{"lang":"hk","v":"粉姿花音樂配音製作有限公司"}],"company_since":"1997-06-27","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"615158","names":[{"lang":"en","v":"CHRISTIAN CENTRAL CHURCH (JORDAN) LIMITED"},{"lang":"hk","v":"基督中心堂(佐敦)有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
{"tax_id":"615392","names":[{"lang":"en","v":"CHUNG YEH YUK TSOI EDUCATIONAL ORGANIZATION COMPANY LIMITED"},{"lang":"hk","v":"中業育才教育機構有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"615327","names":[{"lang":"en","v":"CII (CHENGDU QIONGMING) LIMITED"},{"lang":"hk","v":"中國基礎建設(成都邛名)有限公司"}],"company_since":"1997-06-27","company_dissolved":"2010-10-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615134","names":[{"lang":"en","v":"FINEMARK INVESTMENTS LIMITED"},{"lang":"hk","v":"華徽投資有限公司"}],"company_since":"1997-06-27","company_dissolved":"2003-03-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615282","names":[{"lang":"en","v":"FOKO ENTERPRISES LIMITED"},{"lang":"hk","v":"易達貿易發展有限公司"}],"company_since":"1997-06-27","company_dissolved":"2003-02-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615351","names":[{"lang":"en","v":"FONG YUEN KIT SING TRANSPORTATION LIMITED"},{"lang":"hk","v":"方圓傑誠貨運有限公司"}],"company_since":"1997-06-27","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"615171","names":[{"lang":"en","v":"FUHYUH INDUSTRIES COMPANY LIMITED"},{"lang":"hk","v":"富鈺工業股份有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615402","names":[{"lang":"en","v":"CITY CHANCE (ASIA) LIMITED"},{"lang":"hk","v":"港昌(亞洲)有限公司"}],"company_since":"1997-06-27","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615141","names":[{"lang":"en","v":"FUJI TSUSHO (HONG KONG) LIMITED"},{"lang":"hk","v":"富士通商(香港)有限公司"}],"company_since":"1997-06-27","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615290","names":[{"lang":"en","v":"CITY DRAGON INDUSTRIAL LIMITED"},{"lang":"hk","v":"泛龍實業有限公司"}],"company_since":"1997-06-27","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615287","names":[{"lang":"en","v":"FULLSIGHT LIMITED"},{"lang":"hk","v":"富賽特有限公司"}],"company_since":"1997-06-27","company_dissolved":"2018-07-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615361","names":[{"lang":"en","v":"CITY FOCUS TRADING LIMITED"},{"lang":"hk","v":"港峰貿易有限公司"}],"company_since":"1997-06-27","company_dissolved":"2006-03-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615116","names":[{"lang":"en","v":"GAIN PACIFIC ENTERPRISES LIMITED"},{"lang":"hk","v":"裕恒企業有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615397","names":[{"lang":"en","v":"CITY TREND HOLDINGS LIMITED (d2004-12-10)"},{"lang":"hk","v":"港昌集團有限公司"}],"company_since":"1997-06-27","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615137","names":[{"lang":"en","v":"GALLANT OVERSEAS LIMITED"},{"lang":"hk","v":"嘉恒海外有限公司"}],"company_since":"1997-06-27","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615301","names":[{"lang":"en","v":"GENERAL MARK INVESTMENT LIMITED"},{"lang":"hk","v":"廣誌投資有限公司"}],"company_since":"1997-06-27","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615299","names":[{"lang":"en","v":"GENERAL RAINBOW INVESTMENT LIMITED"},{"lang":"hk","v":"廣彩投資有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615140","names":[{"lang":"en","v":"GENMENT TRADING COMPANY LIMITED"},{"lang":"hk","v":"頴賢貿易有限公司"}],"company_since":"1997-06-27","company_dissolved":"2008-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615054","names":[{"lang":"en","v":"GLOBAL CHOICE ENTERPRISES LIMITED (d2018-07-09)"},{"lang":"hk","v":"寶彩企業有限公司"}],"company_since":"1997-06-27","company_dissolved":"2018-07-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615227","names":[{"lang":"en","v":"COMPUTER SUPPLIES CENTRE LIMITED"},{"lang":"hk","v":"電腦用品有限公司"}],"company_since":"1997-06-27","company_dissolved":"2002-10-11","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615097","names":[{"lang":"en","v":"GLOBAL LANE LIMITED"},{"lang":"hk","v":"寶良有限公司"}],"company_since":"1997-06-27","company_dissolved":"2013-09-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615098","names":[{"lang":"en","v":"GLOBAL SEA INVESTMENT LIMITED"},{"lang":"hk","v":"寶海投資有限公司"}],"company_since":"1997-06-27","company_dissolved":"2002-10-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615143","names":[{"lang":"en","v":"GMP AND TESTING CONSULTANCY SERVICES LIMITED"},{"lang":"hk","v":"優質產品及檢定顧問服務有限公司"}],"company_since":"1997-06-27","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615396","names":[{"lang":"en","v":"GOLD ACT INVESTMENT LIMITED"},{"lang":"hk","v":"金毅投資有限公司"}],"company_since":"1997-06-27","company_dissolved":"2011-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"615313","names":[{"lang":"en","v":"GOLD HAPPINESS LIMITED"}],"company_since":"1997-06-27","company_dissolved":"2006-08-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615300","names":[{"lang":"en","v":"CROSSLINK INVESTMENT LIMITED"},{"lang":"hk","v":"廣良投資有限公司"}],"company_since":"1997-06-27","company_dissolved":"2017-12-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615213","names":[{"lang":"en","v":"GOLD PATH DEVELOPMENTS LIMITED"}],"company_since":"1997-06-27","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615208","names":[{"lang":"en","v":"CV. EMPAT DUA (HONG KONG) LIMITED"},{"lang":"hk","v":"安柏杜亞(香港)有限公司"}],"company_since":"1997-06-27","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615178","names":[{"lang":"en","v":"GOLDEN FUTURE ENTERPRISES LIMITED"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615065","names":[{"lang":"en","v":"GOLDJET HOLDINGS LIMITED"},{"lang":"hk","v":"金智集團有限公司"}],"company_since":"1997-06-27","company_dissolved":"2002-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615321","names":[{"lang":"en","v":"DUNWELL HOLDINGS LIMITED"},{"lang":"hk","v":"敦華集團有限公司"}],"company_since":"1997-06-27","company_dissolved":"2008-11-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615099","names":[{"lang":"en","v":"GOOD HARVESTS (ASIA) TRADING COMPANY LIMITED (d2015-10-09)"},{"lang":"hk","v":"永豐(亞洲)貿易有限公司"}],"company_since":"1997-06-27","company_dissolved":"2015-10-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615039","names":[{"lang":"en","v":"E-RETAIL SYSTEM MANAGEMENT LIMITED"},{"lang":"hk","v":"宏智系統管理有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615269","names":[{"lang":"en","v":"GOOD WAY JEWELLERY MANUFACTORY LIMITED"},{"lang":"hk","v":"順利首飾廠有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615365","names":[{"lang":"en","v":"GOODERS H.K. INVESTMENT LIMITED"},{"lang":"hk","v":"佳益香港投資有限公司"}],"company_since":"1997-06-27","company_dissolved":"2001-11-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615074","names":[{"lang":"en","v":"GOODSTAR CONSULTANTS LIMITED"},{"lang":"hk","v":"高星顧問有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615371","names":[{"lang":"en","v":"EASTERN PROPERTY AGENCY (GROUP) LIMITED"},{"lang":"hk","v":"東方地產代理(集團)有限公司"}],"company_since":"1997-06-27","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615255","names":[{"lang":"en","v":"GREAT CROWN ENTERPRISE LIMITED (d2003-11-28)"},{"lang":"hk","v":"順利企業有限公司"}],"company_since":"1997-06-27","company_dissolved":"2003-11-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"615233","names":[{"lang":"en","v":"H &amp; L NOMINEES LIMITED"}],"company_since":"1997-06-27","company_dissolved":"2008-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615190","names":[{"lang":"en","v":"HANG FAI JEWELLRY LIMITED"},{"lang":"hk","v":"恒輝首飾有限公司"}],"company_since":"1997-06-27","company_dissolved":"2002-11-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615331","names":[{"lang":"en","v":"EVER RISING INDUSTRIAL LIMITED (d2009-11-20)"},{"lang":"hk","v":"駿昇實業(香港)有限公司"}],"company_since":"1997-06-27","company_dissolved":"2009-11-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615167","names":[{"lang":"en","v":"HANG TUNG DEVELOPMENT (H.K.) LIMITED"},{"lang":"hk","v":"恆通香港發展有限公司"}],"company_since":"1997-06-27","company_dissolved":"2014-10-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"615399","names":[{"lang":"en","v":"EXCEL CITY HOLDINGS LIMITED"},{"lang":"hk","v":"創城集團有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615152","names":[{"lang":"en","v":"HING TAT (HONG KONG) GROUP COMPANY LIMITED"},{"lang":"hk","v":"興達(香港)集團有限公司"}],"company_since":"1997-06-27","company_dissolved":"2006-09-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615211","names":[{"lang":"en","v":"F S L INTERNATIONAL (HONG KONG) LIMITED"}],"company_since":"1997-06-27","company_dissolved":"2005-01-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615082","names":[{"lang":"en","v":"HONESTY ELECTRONICS LIMITED (d2013-03-15)"},{"lang":"hk","v":"信誠電子有限公司"}],"company_since":"1997-06-27","company_dissolved":"2013-03-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615196","names":[{"lang":"en","v":"HONG KONG CHARITABLE EYE FOUNDATION LIMITED"},{"lang":"hk","v":"香港護眼工程基金會有限公司"}],"company_since":"1997-06-27","company_dissolved":"2015-04-06","company_type_txt":"Ltd by guarantee"},
undefined,
undefined,
{"tax_id":"615383","names":[{"lang":"en","v":"HONG KONG FAMILY EDUCATION ASSOCIATION LIMITED"},{"lang":"hk","v":"香港家庭教育協會有限公司"}],"company_since":"1997-06-27","company_dissolved":"2018-06-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615170","names":[{"lang":"en","v":"FONTANA (HUNGHOM) RESTAURANT LIMITED"},{"lang":"hk","v":"富麗雅(紅磡)海鮮酒家有限公司"}],"company_since":"1997-06-27","company_dissolved":"2019-03-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615347","names":[{"lang":"en","v":"FORTUNE WISE TRADING LIMITED"},{"lang":"hk","v":"和喜貿易有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615356","names":[{"lang":"en","v":"EAGLE I LIMITED"}],"company_since":"1997-06-27","company_dissolved":"2003-11-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615229","names":[{"lang":"en","v":"HONG KONG LI DA HOLDINGS LIMITED"},{"lang":"hk","v":"香港利達集團有限公司"}],"company_since":"1997-06-27","company_dissolved":"2006-01-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615195","names":[{"lang":"en","v":"Hong Kong Reformed Presbyterian Hon Wah Covenant Church Limited"},{"lang":"hk","v":"香港改革宗長老會韓華恩約教會有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"615259","names":[{"lang":"en","v":"HONOUR MAX HOLDINGS LIMITED"},{"lang":"hk","v":"安明集團有限公司"}],"company_since":"1997-06-27","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615306","names":[{"lang":"en","v":"HOOSEN DEVELOPMENT LIMITED"},{"lang":"hk","v":"漢琛發展有限公司"}],"company_since":"1997-06-27","company_dissolved":"2003-06-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615272","names":[{"lang":"en","v":"HONG YUAN PAPER PRODUCTS LIMITED"},{"lang":"hk","v":"鴻源紙業有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615326","names":[{"lang":"en","v":"HUA BAO WINES &amp; SPIRITS LIMITED"},{"lang":"hk","v":"華寶洋酒有限公司"}],"company_since":"1997-06-27","company_dissolved":"2002-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615132","names":[{"lang":"en","v":"HUAZI DECORATIVE ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"華姿裝飾工程有限公司"}],"company_since":"1997-06-27","company_dissolved":"2003-07-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615297","names":[{"lang":"en","v":"GOLD WAVE TRADING COMPANY LIMITED"},{"lang":"hk","v":"金濤貿易有限公司"}],"company_since":"1997-06-27","company_dissolved":"2003-01-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615223","names":[{"lang":"en","v":"IMPERIAL COMPUTER (HK) LIMITED"}],"company_since":"1997-06-27","company_dissolved":"2002-10-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615123","names":[{"lang":"en","v":"GOLDEN FIREBIRD FILM PRODUCTION LIMITED"},{"lang":"hk","v":"金火鳥影視娛樂制作有限公司"}],"company_since":"1997-06-27","company_dissolved":"2006-11-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615232","names":[{"lang":"en","v":"INNOVATIVE COMPANY LIMITED"}],"company_since":"1997-06-27","company_dissolved":"2016-08-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615261","names":[{"lang":"en","v":"INTER-PASSION INTERNATIONAL LIMITED"}],"company_since":"1997-06-27","company_dissolved":"2000-12-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"615294","names":[{"lang":"en","v":"GOLDEN SOURCE CONSULTANTS LIMITED"},{"lang":"hk","v":"金源顧問有限公司"}],"company_since":"1997-06-27","company_dissolved":"2007-11-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615159","names":[{"lang":"en","v":"JESSIN LIMITED"},{"lang":"hk","v":"怡昌盛有限公司"}],"company_since":"1997-06-27","company_dissolved":"2001-10-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615055","names":[{"lang":"en","v":"JET WINNER INTERNATIONAL LIMITED"},{"lang":"hk","v":"盛永國際有限公司"}],"company_since":"1997-06-27","company_dissolved":"2011-12-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615144","names":[{"lang":"en","v":"JEUNIQUE INTERNATIONAL (HONG KONG) LIMITED"}],"company_since":"1997-06-27","company_dissolved":"2006-01-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615349","names":[{"lang":"en","v":"JTI ASIA (EXPORTS) LIMITED"}],"company_since":"1997-06-27","company_dissolved":"2014-11-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615151","names":[{"lang":"en","v":"KADOORIE TELECOM LIMITED"},{"lang":"hk","v":"佳得利電訊有限公司"}],"company_since":"1997-06-27","company_dissolved":"2003-02-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615270","names":[{"lang":"en","v":"KAI CHEONG INTERNATIONAL INTERNET &amp; HI-TECH DEVELOPMENT LIMITED"},{"lang":"hk","v":"啓昌國際網絡科技發展有限公司"}],"company_since":"1997-06-27","company_dissolved":"2010-02-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"615117","names":[{"lang":"en","v":"HAIDIAN INVESTMENTS LIMITED"},{"lang":"hk","v":"海淀投資有限公司"}],"company_since":"1997-06-27","company_dissolved":"2005-11-11","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615242","names":[{"lang":"en","v":"KING SUN SEWING MACHINE COMPANY LIMITED"},{"lang":"hk","v":"景生衣車有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615405","names":[{"lang":"en","v":"KINGDOM HOLDINGS LIMITED (d2003-11-21)"},{"lang":"hk","v":"堯舜集團有限公司"}],"company_since":"1997-06-27","company_dissolved":"2003-11-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615122","names":[{"lang":"en","v":"KINMAN COMPUTER COMPANY LIMITED"},{"lang":"hk","v":"健民電腦有限公司"}],"company_since":"1997-06-27","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615189","names":[{"lang":"en","v":"KONG HING ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"港興工程有限公司"}],"company_since":"1997-06-27","company_dissolved":"2008-12-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615344","names":[{"lang":"en","v":"KWAN FUNG ENTERPRISES (H.K.) COMPANY LIMITED"},{"lang":"hk","v":"群豐企業(香港)有限公司"}],"company_since":"1997-06-27","company_dissolved":"2013-11-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"615366","names":[{"lang":"en","v":"HEAP SUCCESS INTERNATIONAL LIMITED"},{"lang":"hk","v":"協成國際發展有限公司"}],"company_since":"1997-06-27","company_dissolved":"2003-03-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615404","names":[{"lang":"en","v":"LASON (HONG KONG) LIMITED"},{"lang":"hk","v":"立盛(香港)有限公司"}],"company_since":"1997-06-27","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615425","names":[{"lang":"en","v":"HENREX INVESTMENT LIMITED"},{"lang":"hk","v":"亨宇投資有限公司"}],"company_since":"1997-06-27","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615308","names":[{"lang":"en","v":"HOME CAPITAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"漢資發展有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615081","names":[{"lang":"en","v":"LEIGHTON ENTERPRISES COMPANY LIMITED"},{"lang":"hk","v":"利登遠東有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"615162","names":[{"lang":"en","v":"LUCKY CONTACT LIMITED (d2001-04-06)"},{"lang":"hk","v":"幸運通有限公司"}],"company_since":"1997-06-27","company_dissolved":"2001-04-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"615424","names":[{"lang":"en","v":"HONG KONG FINE ART ASSOCIATION LIMITED"},{"lang":"hk","v":"香港藝術會有限公司"}],"company_since":"1997-06-27","company_dissolved":"2012-11-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615198","names":[{"lang":"en","v":"HONG KONG FOOD SCIENCE AND TECHNOLOGY ASSOCIATION LIMITED"},{"lang":"hk","v":"香港食品科技協會有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"615203","names":[{"lang":"en","v":"MANY WINS LIMITED"},{"lang":"hk","v":"桂田有限公司"}],"company_since":"1997-06-27","company_dissolved":"1999-02-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615231","names":[{"lang":"en","v":"HONG KONG FOUNDATION FOR SOCIAL DEMOCRACY LIMITED"},{"lang":"hk","v":"香港社會民主基金有限公司"}],"company_since":"1997-06-27","company_dissolved":"2008-08-14","company_type_txt":"Ltd by guarantee"},
{"tax_id":"615432","names":[{"lang":"en","v":"MEGA UNION INDUSTRIES LIMITED"},{"lang":"hk","v":"鉅聯實業有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615166","names":[{"lang":"en","v":"MEGA-X RESOURCES LIMITED"},{"lang":"hk","v":"創富無限有限公司"}],"company_since":"1997-06-27","company_dissolved":"2008-04-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615253","names":[{"lang":"en","v":"MEI TAK CHEMICAL CORPORATION LIMITED"},{"lang":"hk","v":"美德化工行有限公司"}],"company_since":"1997-06-27","company_dissolved":"2006-04-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"SO0000074","names":[{"lang":"en","v":"HONG KONG ST. JOHN AMBULANCE"},{"lang":"hk","v":"香港聖約翰救護機構"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Inc by ordinance"},
undefined,
{"tax_id":"615258","names":[{"lang":"en","v":"HONOUR FORTUNE HOLDINGS LIMITED"},{"lang":"hk","v":"安誠集團有限公司"}],"company_since":"1997-06-27","company_dissolved":"2008-12-05","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615332","names":[{"lang":"en","v":"MOBISHOP ASIA LIMITED"},{"lang":"hk","v":"移動店亞洲有限公司"}],"company_since":"1997-06-27","company_dissolved":"2016-02-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615153","names":[{"lang":"en","v":"MRST LIMITED"},{"lang":"hk","v":"海威科技有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615352","names":[{"lang":"en","v":"HONG KONG YUH HUA (CD) MATERIALS ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"香港昱華光盤材料工程有限公司"}],"company_since":"1997-06-27","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615100","names":[{"lang":"en","v":"MULTIMAX ENTERPRISES LIMITED"},{"lang":"hk","v":"萬達美企業有限公司"}],"company_since":"1997-06-27","company_dissolved":"2001-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615304","names":[{"lang":"en","v":"HOMYOUNG DEVELOPMENT LIMITED"},{"lang":"hk","v":"漢仁發展有限公司"}],"company_since":"1997-06-27","company_dissolved":"2007-11-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615305","names":[{"lang":"en","v":"HOPESMART DEVELOPMENT LIMITED"},{"lang":"hk","v":"漢俊發展有限公司"}],"company_since":"1997-06-27","company_dissolved":"2003-06-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615061","names":[{"lang":"en","v":"MULTIMAX INDUSTRIAL LIMITED (d2001-09-14)"},{"lang":"hk","v":"萬達美實業有限公司"}],"company_since":"1997-06-27","company_dissolved":"2001-09-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615401","names":[{"lang":"en","v":"IDEAWAVE INVESTMENT (H.K.) LIMITED"},{"lang":"hk","v":"睿丰投資(香港)有限公司"}],"company_since":"1997-06-27","company_dissolved":"2006-01-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615423","names":[{"lang":"en","v":"NET DEVELOPMENT LIMITED (d2004-12-10)"},{"lang":"hk","v":"立宇發展有限公司"}],"company_since":"1997-06-27","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615130","names":[{"lang":"en","v":"NETCOM TECHNOLOGIES LIMITED"},{"lang":"hk","v":"利訊科技有限公司"}],"company_since":"1997-06-27","company_dissolved":"2001-11-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615169","names":[{"lang":"en","v":"NEW CLASSIC ENTERPRISES LIMITED"},{"lang":"hk","v":"濠新企業有限公司"}],"company_since":"1997-06-27","company_dissolved":"2001-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"615173","names":[{"lang":"en","v":"NOKGISTICS CORPORATE MANAGEMENT LIMITED"},{"lang":"hk","v":"諾捷秘書管理有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615126","names":[{"lang":"en","v":"NORDTON INTERNATIONAL LIMITED"}],"company_since":"1997-06-27","company_dissolved":"2001-06-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615380","names":[{"lang":"en","v":"OCEAN BRILLIANT INTERNATIONAL LIMITED (d2004-12-10)"},{"lang":"hk","v":"海秀國際有限公司"}],"company_since":"1997-06-27","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615163","names":[{"lang":"en","v":"JOINT EFFORT INTERNATIONAL LIMITED (d2002-11-29)"},{"lang":"hk","v":"群策國際有限公司"}],"company_since":"1997-06-27","company_dissolved":"2002-11-29","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615150","names":[{"lang":"en","v":"ORIENTAL FORTUNE HOLDINGS (HONG KONG) LIMITED"},{"lang":"hk","v":"東祥集團(香港)有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"615388","names":[{"lang":"en","v":"KEENHOPE ENTERPRISE LIMITED"},{"lang":"hk","v":"建浩企業有限公司"}],"company_since":"1997-06-27","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615107","names":[{"lang":"en","v":"PACIFIC GOLD (H.K.) LIMITED (d2004-12-10)"},{"lang":"hk","v":"達金(香港)有限公司"}],"company_since":"1997-06-27","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615262","names":[{"lang":"en","v":"PACIFIC MARKETING (H.K.) LIMITED"},{"lang":"hk","v":"太平洋市場拓展(香港)有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615181","names":[{"lang":"en","v":"PEGASUS SEWING MACHINES (HONG KONG) LIMITED"},{"lang":"hk","v":"飛馬縫紉機(香港)有限公司"}],"company_since":"1997-06-27","company_dissolved":"2012-03-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615220","names":[{"lang":"en","v":"KWAN KEE ENGINEERING &amp; CONSTRUCTION COMPANY LIMITED"},{"lang":"hk","v":"坤記工程有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615252","names":[{"lang":"en","v":"PENFUL HOLDINGS LIMITED"},{"lang":"hk","v":"百利豐集團有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615225","names":[{"lang":"en","v":"KWAN LEE HYDRO-ELECTRIC ENGINEERING LIMITED"},{"lang":"hk","v":"昆利水電工程有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615235","names":[{"lang":"en","v":"PLATINUM ENTERPRISES LIMITED (d2003-04-25)"},{"lang":"hk","v":"白金企業有限公司"}],"company_since":"1997-06-27","company_dissolved":"2003-04-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615217","names":[{"lang":"en","v":"PLATINUM TECHNOLOGY CHINA, LIMITED"},{"lang":"hk","v":"百達靈科技中國有限公司"}],"company_since":"1997-06-27","company_dissolved":"2007-03-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615274","names":[{"lang":"en","v":"POLIC SECUFORCE LIMITED"},{"lang":"hk","v":"保力保安有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"615072","names":[{"lang":"en","v":"POLYGON MANAGEMENT LIMITED"},{"lang":"hk","v":"寶廣管理有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615315","names":[{"lang":"en","v":"LUCKY LION TRADING LIMITED"}],"company_since":"1997-06-27","company_dissolved":"2005-12-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615060","names":[{"lang":"en","v":"POLYGON TRADING LIMITED (d2003-03-21)"},{"lang":"hk","v":"寶廣貿易有限公司"}],"company_since":"1997-06-27","company_dissolved":"2003-03-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615318","names":[{"lang":"en","v":"POLYRIFE UNIVERSAL LIMITED"},{"lang":"hk","v":"百利豐環球有限公司"}],"company_since":"1997-06-27","company_dissolved":"2003-07-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615139","names":[{"lang":"en","v":"MAN YIN ENTERPRISES LIMITED"},{"lang":"hk","v":"文然企業有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615355","names":[{"lang":"en","v":"POSY FASHION COMPANY LIMITED"}],"company_since":"1997-06-27","company_dissolved":"2006-11-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615247","names":[{"lang":"en","v":"POLYTON HONG KONG LIMITED (d2003-03-21)"},{"lang":"hk","v":"百利通香港有限公司"}],"company_since":"1997-06-27","company_dissolved":"2003-03-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615428","names":[{"lang":"en","v":"MEGA PROSPER LIMITED (d2004-08-13)"},{"lang":"hk","v":"偉隆有限公司"}],"company_since":"1997-06-27","company_dissolved":"2004-08-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615115","names":[{"lang":"en","v":"POWER GAIN INTERNATIONAL LIMITED (d2006-11-17)"},{"lang":"hk","v":"柏盈國際有限公司"}],"company_since":"1997-06-27","company_dissolved":"2006-11-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615120","names":[{"lang":"en","v":"POWER GRAND TRADING LIMITED"},{"lang":"hk","v":"力嘉貿易有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615050","names":[{"lang":"en","v":"MILLION REGAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"萬奧發展有限公司"}],"company_since":"1997-06-27","company_dissolved":"2006-05-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615079","names":[{"lang":"en","v":"POWER TOP ENGINEERING LIMITED (d2012-01-27)"},{"lang":"hk","v":"豐泰機械有限公司"}],"company_since":"1997-06-27","company_dissolved":"2012-01-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615051","names":[{"lang":"en","v":"MILLION REGAL INVESTMENT LIMITED"},{"lang":"hk","v":"萬奧投資有限公司"}],"company_since":"1997-06-27","company_dissolved":"2011-03-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615146","names":[{"lang":"en","v":"PRECISION COMPONENTS (CHINA) LIMITED"},{"lang":"hk","v":"精密配件(中國)有限公司"}],"company_since":"1997-06-27","company_dissolved":"2007-11-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615335","names":[{"lang":"en","v":"PROFIT GROUP INVESTMENT LIMITED (d2002-10-11)"},{"lang":"hk","v":"潤興投資有限公司"}],"company_since":"1997-06-27","company_dissolved":"2002-10-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615180","names":[{"lang":"en","v":"PROSPEROUS FUTURE TRADING LIMITED"}],"company_since":"1997-06-27","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615284","names":[{"lang":"en","v":"MUSIC BOX OF SWITZERLAND LIMITED"}],"company_since":"1997-06-27","company_dissolved":"2013-09-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615058","names":[{"lang":"en","v":"QUANMAX DEVELOPMENT LIMITED"},{"lang":"hk","v":"僑萬發展有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615059","names":[{"lang":"en","v":"QUANMAX INTERNATIONAL LIMITED"},{"lang":"hk","v":"僑萬國際有限公司"}],"company_since":"1997-06-27","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615370","names":[{"lang":"en","v":"R&amp;M ASIA-PACIFIC BUILDING TECHNOLOGIES LIMITED"}],"company_since":"1997-06-27","company_dissolved":"2000-01-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615395","names":[{"lang":"en","v":"RAYSUN (H.K.) LIMITED"},{"lang":"hk","v":"隆鑫(香港)有限公司"}],"company_since":"1997-06-27","company_dissolved":"2003-01-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615256","names":[{"lang":"en","v":"REGAL CHAIN DEVELOPMENT LIMITED (d2010-06-11)"},{"lang":"hk","v":"力富發展有限公司"}],"company_since":"1997-06-27","company_dissolved":"2010-06-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615279","names":[{"lang":"en","v":"NEW HONG KONG COMIC &amp; MAGAZINE LIMITED"},{"lang":"hk","v":"新香港畫報社有限公司"}],"company_since":"1997-06-27","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615372","names":[{"lang":"en","v":"REGAL MIND LIMITED (d2001-12-21)"},{"lang":"hk","v":"豪思有限公司"}],"company_since":"1997-06-27","company_dissolved":"2001-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615390","names":[{"lang":"en","v":"REGEM ENTERPRISE COMPANY LIMITED"},{"lang":"hk","v":"采色企業有限公司"}],"company_since":"1997-06-27","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615403","names":[{"lang":"en","v":"NEW SUCCESS (ASIA) LIMITED"},{"lang":"hk","v":"冠成(亞洲)有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615071","names":[{"lang":"en","v":"RICHTOP HOLDINGS LIMITED (d2004-12-10)"},{"lang":"hk","v":"高冠集團有限公司"}],"company_since":"1997-06-27","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"615406","names":[{"lang":"en","v":"RIGHT FINE (HONG KONG) LIMITED"},{"lang":"hk","v":"正輝(香港)有限公司"}],"company_since":"1997-06-27","company_dissolved":"2002-08-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615209","names":[{"lang":"en","v":"MASSON INTERNATIONAL LIMITED"}],"company_since":"1997-06-27","company_dissolved":"2002-01-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615201","names":[{"lang":"en","v":"RIZHONGTIAN INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"日中天國際有限公司"}],"company_since":"1997-06-27","company_dissolved":"2002-04-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"615160","names":[{"lang":"en","v":"ORIENTAL AFFLUENCE LIMITED"},{"lang":"hk","v":"隆厚昌有限公司"}],"company_since":"1997-06-27","company_dissolved":"2002-12-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615286","names":[{"lang":"en","v":"SAL INTERNATIONAL (H.K.) LIMITED"},{"lang":"hk","v":"聖義隆國際有限公司"}],"company_since":"1997-06-27","company_dissolved":"2007-06-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615230","names":[{"lang":"en","v":"P.H.L. TRANSPORT CO., LIMITED"},{"lang":"hk","v":"鴻鋒速運有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615389","names":[{"lang":"en","v":"SANPSON ENTERPRISE LIMITED"},{"lang":"hk","v":"瑞琛企業有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615073","names":[{"lang":"en","v":"SCIENTIFIC RESEARCH AND PROMOTION CENTRE (CHINA) LIMITED"},{"lang":"hk","v":"實用科技(中國)有限公司"}],"company_since":"1997-06-27","company_dissolved":"2007-11-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615413","names":[{"lang":"en","v":"PACIFIC TRUMP HOLDINGS LIMITED"},{"lang":"hk","v":"太祥集團有限公司"}],"company_since":"1997-06-27","company_dissolved":"2002-10-11","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615277","names":[{"lang":"en","v":"SENSES GOOD LUCK INTERNATIONAL ADVERTISING COMPANY LIMITED"},{"lang":"hk","v":"意識時運國際廣告有限公司"}],"company_since":"1997-06-27","company_dissolved":"2000-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615408","names":[{"lang":"en","v":"SHEEN DYNAMIC (HONG KONG) LIMITED"},{"lang":"hk","v":"源達(香港)有限公司"}],"company_since":"1997-06-27","company_dissolved":"2005-09-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615103","names":[{"lang":"en","v":"SHEENKEY INVESTMENT LIMITED"},{"lang":"hk","v":"昌祺投資有限公司"}],"company_since":"1997-06-27","company_dissolved":"2001-11-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"615433","names":[{"lang":"en","v":"PINGAN.COM LIMITED"},{"lang":"hk","v":"平安網有限公司"}],"company_since":"1997-06-27","company_dissolved":"2017-08-25","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615283","names":[{"lang":"en","v":"SHUN HING (INTERNATIONAL) ZIPPERS LIMITED"},{"lang":"hk","v":"順興(國際)拉鍊有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615303","names":[{"lang":"en","v":"SINCERE GRACE DEVELOPMENT LIMITED"},{"lang":"hk","v":"瑞欣發展有限公司"}],"company_since":"1997-06-27","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615400","names":[{"lang":"en","v":"SINO BOND HOLDINGS LIMITED"},{"lang":"hk","v":"順邦集團有限公司"}],"company_since":"1997-06-27","company_dissolved":"2017-02-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615333","names":[{"lang":"en","v":"POLY POND INVESTMENT LIMITED"},{"lang":"hk","v":"嘉邦投資有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615248","names":[{"lang":"en","v":"POLYCOME TRADING LIMITED"},{"lang":"hk","v":"百利錦貿易有限公司"}],"company_since":"1997-06-27","company_dissolved":"2001-10-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615238","names":[{"lang":"en","v":"SINO ENTERPRISE HOLDINGS LIMITED"},{"lang":"hk","v":"華企集團有限公司"}],"company_since":"1997-06-27","company_dissolved":"2001-11-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615241","names":[{"lang":"en","v":"SINO INDUSTRIAL INVESTMENTS LIMITED"},{"lang":"hk","v":"華昌興業投資有限公司"}],"company_since":"1997-06-27","company_dissolved":"2000-05-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615430","names":[{"lang":"en","v":"SINO LEADER ENTERPRISES LIMITED (d2003-01-10)"},{"lang":"hk","v":"國領企業有限公司"}],"company_since":"1997-06-27","company_dissolved":"2003-01-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615373","names":[{"lang":"en","v":"SINO PATH LIMITED"},{"lang":"hk","v":"國柏有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615102","names":[{"lang":"en","v":"SINOYORK DEVELOPMENT LIMITED"},{"lang":"hk","v":"國益發展有限公司"}],"company_since":"1997-06-27","company_dissolved":"2003-12-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615119","names":[{"lang":"en","v":"POWER FORTUNE HOLDINGS LIMITED"},{"lang":"hk","v":"力通集團有限公司"}],"company_since":"1997-06-27","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615334","names":[{"lang":"en","v":"SMART FOND INVESTMENT LIMITED"},{"lang":"hk","v":"佳豐投資有限公司"}],"company_since":"1997-06-27","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615358","names":[{"lang":"en","v":"SMART GROUP DEVELOPMENT LIMITED"},{"lang":"hk","v":"佳盛發展有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615346","names":[{"lang":"en","v":"POWER SUN (HONG KONG) LIMITED"},{"lang":"hk","v":"裕陽(香港)有限公司"}],"company_since":"1997-06-27","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615360","names":[{"lang":"en","v":"SMART SINO ENTERPRISES LIMITED (d2005-12-16)"},{"lang":"hk","v":"泛中企業有限公司"}],"company_since":"1997-06-27","company_dissolved":"2005-12-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615302","names":[{"lang":"en","v":"SMARTAC INVESTMENT LIMITED"},{"lang":"hk","v":"群駿投資有限公司"}],"company_since":"1997-06-27","company_dissolved":"2008-09-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"615067","names":[{"lang":"en","v":"STARWELL (H.K.) LIMITED"},{"lang":"hk","v":"星富(香港)有限公司"}],"company_since":"1997-06-27","company_dissolved":"2013-05-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615125","names":[{"lang":"en","v":"SPLENDOR AIRCON SERVICES LIMITED"},{"lang":"hk","v":"威榮冷氣服務有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615091","names":[{"lang":"en","v":"SUMMIT KING LIMITED"},{"lang":"hk","v":"森基有限公司"}],"company_since":"1997-06-27","company_dissolved":"2008-03-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615219","names":[{"lang":"en","v":"J&amp;D INTERNATIONAL LIMITED (d2006-11-10)"},{"lang":"hk","v":"捷登寰宇有限公司"}],"company_since":"1997-06-27","company_dissolved":"2006-11-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615276","names":[{"lang":"en","v":"SUN BON INTERNATIONAL LIMITED"},{"lang":"hk","v":"鑫邦國際有限公司"}],"company_since":"1997-06-27","company_dissolved":"2002-07-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615384","names":[{"lang":"en","v":"SUN RISE MANAGEMENT LIMITED"},{"lang":"hk","v":"旭景管理有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615087","names":[{"lang":"en","v":"REXSON LIMITED (d2000-11-17)"}],"company_since":"1997-06-27","company_dissolved":"2000-11-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615049","names":[{"lang":"en","v":"SUNNEX DEVELOPMENT LIMITED"},{"lang":"hk","v":"信時發展有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615095","names":[{"lang":"en","v":"SUPER CENTRE LIMITED"},{"lang":"hk","v":"森中有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"615149","names":[{"lang":"en","v":"ROHDE &amp; SCHWARZ CHINA LIMITED"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615192","names":[{"lang":"en","v":"SUPER KING SEALING TAPE LIMITED"},{"lang":"hk","v":"特佳膠帶有限公司"}],"company_since":"1997-06-27","company_dissolved":"2001-10-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615096","names":[{"lang":"en","v":"SUPER PLANET LIMITED (d2003-04-25)"},{"lang":"hk","v":"森倍有限公司"}],"company_since":"1997-06-27","company_dissolved":"2003-04-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615207","names":[{"lang":"en","v":"SUPERB INTERNATIONAL (HONG KONG) COMPANY, LIMITED"},{"lang":"hk","v":"山珀(香港)有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615416","names":[{"lang":"en","v":"SUPERB SCORE HOLDINGS LIMITED"},{"lang":"hk","v":"宏志集團有限公司"}],"company_since":"1997-06-27","company_dissolved":"2002-12-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615387","names":[{"lang":"en","v":"SUPERGRACE INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"瑞欣國際發展有限公司"}],"company_since":"1997-06-27","company_dissolved":"2002-05-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"615298","names":[{"lang":"en","v":"SUPERIOR HERO INVESTMENT LIMITED"},{"lang":"hk","v":"廣勇投資有限公司"}],"company_since":"1997-06-27","company_dissolved":"2003-06-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615341","names":[{"lang":"en","v":"SUPERSTAR DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"鉅星國際發展有限公司"}],"company_since":"1997-06-27","company_dissolved":"2010-03-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615386","names":[{"lang":"en","v":"SUPERYIELD INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"瑞益國際發展有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615421","names":[{"lang":"en","v":"SHEEN SINO DEVELOPMENT LIMITED"},{"lang":"hk","v":"亨中發展有限公司"}],"company_since":"1997-06-27","company_dissolved":"2001-11-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615131","names":[{"lang":"en","v":"SUPREME ADVANCE GROUP LIMITED"},{"lang":"hk","v":"榮馳集團有限公司"}],"company_since":"1997-06-27","company_dissolved":"2006-01-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615041","names":[{"lang":"en","v":"SUPREME BENEFIT LIMITED (d2003-02-07)"},{"lang":"hk","v":"森億有限公司"}],"company_since":"1997-06-27","company_dissolved":"2003-02-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615038","names":[{"lang":"en","v":"SUPREME EMPIRE LIMITED (d2001-04-12)"},{"lang":"hk","v":"森邦有限公司"}],"company_since":"1997-06-27","company_dissolved":"2001-04-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615090","names":[{"lang":"en","v":"SUPREME TALENT LIMITED"},{"lang":"hk","v":"森雄有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615292","names":[{"lang":"en","v":"SINO CHAMPION INDUSTRIAL LIMITED"},{"lang":"hk","v":"創輝實業有限公司"}],"company_since":"1997-06-27","company_dissolved":"2006-11-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615273","names":[{"lang":"en","v":"TAIMIN GROUP LIMITED"},{"lang":"hk","v":"大明集團有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615175","names":[{"lang":"en","v":"TAK HING FAT (HOLDINGS) LIMITED"},{"lang":"hk","v":"德興發(集團)有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615226","names":[{"lang":"en","v":"THALGO (CHINA) LIMITED"},{"lang":"hk","v":"花都(中國)有限公司"}],"company_since":"1997-06-27","company_dissolved":"2003-11-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615296","names":[{"lang":"en","v":"THREE PROFIT COMPANY LIMITED"}],"company_since":"1997-06-27","company_dissolved":"2002-11-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615164","names":[{"lang":"en","v":"TIFFANY TRADING LIMITED (d2003-08-22)"},{"lang":"hk","v":"聯豐海外貿易有限公司"}],"company_since":"1997-06-27","company_dissolved":"2003-08-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615168","names":[{"lang":"en","v":"TIME SPIRIT CONSULTANTS LIMITED"},{"lang":"hk","v":"天神顧問有限公司"}],"company_since":"1997-06-27","company_dissolved":"2002-11-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615193","names":[{"lang":"en","v":"TOMAS (HK) COMPANY LIMITED"}],"company_since":"1997-06-27","company_dissolved":"2006-11-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615412","names":[{"lang":"en","v":"SKY KING ENTERPRISES LIMITED (d2003-10-10)"},{"lang":"hk","v":"天建企業有限公司"}],"company_since":"1997-06-27","company_dissolved":"2003-10-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615363","names":[{"lang":"en","v":"TOP FORCE TRADING LIMITED (d2005-07-15)"},{"lang":"hk","v":"宏峰貿易有限公司"}],"company_since":"1997-06-27","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615066","names":[{"lang":"en","v":"TOP GOLD (H.K.) LIMITED"},{"lang":"hk","v":"富金(香港)有限公司"}],"company_since":"1997-06-27","company_dissolved":"2011-03-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615374","names":[{"lang":"en","v":"SKY PONY LIMITED"},{"lang":"hk","v":"天騏有限公司"}],"company_since":"1997-06-27","company_dissolved":"2003-01-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615323","names":[{"lang":"en","v":"TOP LITE (HONG KONG) LIMITED"},{"lang":"hk","v":"永高(香港)有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615048","names":[{"lang":"en","v":"TOPGOLD PROPERTIES LIMITED (d2002-08-23)"},{"lang":"hk","v":"富金置業有限公司"}],"company_since":"1997-06-27","company_dissolved":"2002-08-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615114","names":[{"lang":"en","v":"TRILAND (H.K.) LIMITED"},{"lang":"hk","v":"彩隆(香港)有限公司"}],"company_since":"1997-06-27","company_dissolved":"2011-01-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615142","names":[{"lang":"en","v":"SOUTHERN ENGINEERING (H.K.) LIMITED"},{"lang":"hk","v":"南方工程(香港)有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615245","names":[{"lang":"en","v":"TRINITY PRINT &amp; PACK LIMITED"},{"lang":"hk","v":"雋藝印刷有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615084","names":[{"lang":"en","v":"STANDARD TOP ENTERPRISES LIMITED"},{"lang":"hk","v":"信時企業有限公司"}],"company_since":"1997-06-27","company_dissolved":"2002-02-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615342","names":[{"lang":"en","v":"TRUMP STANDARD DEVELOPMENT LIMITED"},{"lang":"hk","v":"仲達發展有限公司"}],"company_since":"1997-06-27","company_dissolved":"2002-04-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615104","names":[{"lang":"en","v":"TURBO LINK INVESTMENT LIMITED"},{"lang":"hk","v":"明僑投資有限公司"}],"company_since":"1997-06-27","company_dissolved":"2013-09-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615085","names":[{"lang":"en","v":"STAR GLORY PROPERTIES LIMITED"},{"lang":"hk","v":"星鴻置業有限公司"}],"company_since":"1997-06-27","company_dissolved":"2008-04-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615182","names":[{"lang":"en","v":"UNI-ASIA CAPITAL COMPANY LIMITED"},{"lang":"hk","v":"聯亞致富有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615216","names":[{"lang":"en","v":"UNI-ASIA FUND MANAGEMENT COMPANY LIMITED"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615089","names":[{"lang":"en","v":"STARWELL CONSULTANTS LIMITED (d2003-10-31)"},{"lang":"hk","v":"星華顧問有限公司"}],"company_since":"1997-06-27","company_dissolved":"2003-10-31","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615183","names":[{"lang":"en","v":"UNI-ASIA SERVICES AND AGENCY LIMITED"},{"lang":"hk","v":"聯亞控股有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615108","names":[{"lang":"en","v":"UNION GLORY CONSULTANTS LIMITED (d2004-12-10)"},{"lang":"hk","v":"盛聯顧問有限公司"}],"company_since":"1997-06-27","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615113","names":[{"lang":"en","v":"UNION GLORY TECHNOLOGIES LIMITED"},{"lang":"hk","v":"聯興科技有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615381","names":[{"lang":"en","v":"STYRICH INTERNATIONAL LIMITED"},{"lang":"hk","v":"富式國際有限公司"}],"company_since":"1997-06-27","company_dissolved":"2004-06-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615407","names":[{"lang":"en","v":"SUMMIT VICTORY (HONG KONG) LIMITED"},{"lang":"hk","v":"兆偉(香港)有限公司"}],"company_since":"1997-06-27","company_dissolved":"2009-11-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615069","names":[{"lang":"en","v":"UNION LOYAL INTERNATIONAL LIMITED"},{"lang":"hk","v":"皇悅國際有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615179","names":[{"lang":"en","v":"UNITED OVERSEAS CREDIT LIMITED"}],"company_since":"1997-06-27","company_dissolved":"2012-06-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615240","names":[{"lang":"en","v":"V &amp; T INVESTMENTS LIMITED (HK)"},{"lang":"hk","v":"永通行投資有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615414","names":[{"lang":"en","v":"V3 ENTERPRISES (H.K.) LIMITED"}],"company_since":"1997-06-27","company_dissolved":"2009-04-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615187","names":[{"lang":"en","v":"WAH LUNG INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"華龍國際投資有限公司"}],"company_since":"1997-06-27","company_dissolved":"2008-12-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615042","names":[{"lang":"en","v":"SUNDAY (CHINA) LIMITED"}],"company_since":"1997-06-27","company_dissolved":"2007-06-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"615310","names":[{"lang":"en","v":"WIMFIELD DEVELOPMENT LIMITED"},{"lang":"hk","v":"榮顯發展有限公司"}],"company_since":"1997-06-27","company_dissolved":"2001-08-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615094","names":[{"lang":"en","v":"SUPER SOLID LIMITED"},{"lang":"hk","v":"森力有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615135","names":[{"lang":"en","v":"WINFLOW PACIFIC LIMITED"},{"lang":"hk","v":"永富太平洋有限公司"}],"company_since":"1997-06-27","company_dissolved":"2012-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615194","names":[{"lang":"en","v":"WORLDWIDE FORESTRY CARING COMPANY LIMITED"},{"lang":"hk","v":"環球林務護理有限公司"}],"company_since":"1997-06-27","company_dissolved":"2001-02-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615186","names":[{"lang":"en","v":"XIANG CHUAN INTERNATIONAL DEVELOPMENT (H.K.) LIMITED"},{"lang":"hk","v":"香港湘泉國際發展有限公司"}],"company_since":"1997-06-27","company_dissolved":"2006-11-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615354","names":[{"lang":"en","v":"YUE FUNG INTERNATIONAL (CHINA) LIMITED"},{"lang":"hk","v":"裕豐國際(中國)有限公司"}],"company_since":"1997-06-27","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615078","names":[{"lang":"en","v":"ZILLION INDUSTRIAL (HK) LIMITED"},{"lang":"hk","v":"子能實業(香港)有限公司"}],"company_since":"1997-06-27","company_dissolved":"2007-01-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"615118","names":[{"lang":"en","v":"TEKO INTERNATIONAL FINANCIAL SERVICES LIMITED"},{"lang":"hk","v":"東澳國際理財顧問有限公司"}],"company_since":"1997-06-27","company_dissolved":"2007-06-01","company_type_txt":"Private, ltd by shares"},
{"tax_id":"615278","names":[{"lang":"en","v":"WINFAME INTERNATIONAL (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"勝輝國際(香港)有限公司"}],"company_since":"1997-06-27","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"615064","names":[{"lang":"en","v":"TRILAND HOLDINGS LIMITED (d2006-06-09)"},{"lang":"hk","v":"彩隆集團有限公司"}],"company_since":"1997-06-27","company_dissolved":"2006-06-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615263","names":[{"lang":"en","v":"TWIN'S INVESTMENT LIMITED"},{"lang":"hk","v":"比其投資有限公司"}],"company_since":"1997-06-27","company_dissolved":"2006-03-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615111","names":[{"lang":"en","v":"UNION LOYAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"皇悅發展有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615110","names":[{"lang":"en","v":"UNION LOYAL INVESTMENT LIMITED"},{"lang":"hk","v":"皇悅投資有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615246","names":[{"lang":"en","v":"UNIQUE PLUS LIMITED (d2000-07-07)"},{"lang":"hk","v":"宏易有限公司"}],"company_since":"1997-06-27","company_dissolved":"2000-07-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615267","names":[{"lang":"en","v":"VICTORY CAPS INDUSTRIAL COMPANY LIMITED"},{"lang":"hk","v":"晉盈實業有限公司"}],"company_since":"1997-06-27","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615145","names":[{"lang":"en","v":"WANG KWONG SAND AND QUARRY SUPPLIES LIMITED"},{"lang":"hk","v":"宏光沙石供應有限公司"}],"company_since":"1997-06-27","company_dissolved":"2002-05-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"615420","names":[{"lang":"en","v":"WORLD LANE HOLDINGS LIMITED"},{"lang":"hk","v":"世興集團有限公司"}],"company_since":"1997-06-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"615188","names":[{"lang":"en","v":"MACH ONE INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"迅邁國際有限公司"}],"company_since":"1997-06-27","company_dissolved":"2003-01-24","company_type_txt":"Private, ltd by shares"},
