{"tax_id":"619354","names":[{"lang":"en","v":"CHEERING YOUNG LIMITED"},{"lang":"hk","v":"祥潤有限公司"}],"company_since":"1997-08-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"619352","names":[{"lang":"en","v":"CHINA HOST HONG KONG LIMITED"},{"lang":"hk","v":"中薇香港有限公司"}],"company_since":"1997-08-04","company_dissolved":"2001-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"619397","names":[{"lang":"en","v":"CHINA OVERSEAS JEWELLERY LIMITED"},{"lang":"hk","v":"中國海外珠寶玉器有限公司"}],"company_since":"1997-08-04","company_dissolved":"2007-01-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"619390","names":[{"lang":"en","v":"CHUN HUA INDUSTRIAL LIMITED"},{"lang":"hk","v":"鎭華實業有限公司"}],"company_since":"1997-08-04","company_dissolved":"2003-02-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"619395","names":[{"lang":"en","v":"CHUN TAT TRANSPORTATION COMPANY LIMITED"},{"lang":"hk","v":"駿達貨運有限公司"}],"company_since":"1997-08-04","company_dissolved":"2003-04-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"619396","names":[{"lang":"en","v":"CHUN WUI FINANCE CO., LIMITED"},{"lang":"hk","v":"駿滙財務有限公司"}],"company_since":"1997-08-04","company_dissolved":"2002-05-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"619319","names":[{"lang":"en","v":"CLASSIC MARK LIMITED"},{"lang":"hk","v":"嘉標有限公司"}],"company_since":"1997-08-04","company_dissolved":"2004-12-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"619304","names":[{"lang":"en","v":"CPEC LIMITED (d2010-04-01)"},{"lang":"hk","v":"中鵬企業顧問有限公司"}],"company_since":"1997-08-04","company_dissolved":"2010-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"619386","names":[{"lang":"en","v":"D'S DONNA'S STUDIO CHAINSTORE LIMITED"},{"lang":"hk","v":"當娜設計室連鎖店有限公司"}],"company_since":"1997-08-04","company_dissolved":"2005-07-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"619375","names":[{"lang":"en","v":"DAIKIN CHEMICAL (HONG KONG) LIMITED"},{"lang":"hk","v":"大金化學(香港)有限公司"}],"company_since":"1997-08-04","company_dissolved":"2011-03-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"619360","names":[{"lang":"en","v":"EASTBORO DEVELOPMENT LIMITED"},{"lang":"hk","v":"憶寶發展有限公司"}],"company_since":"1997-08-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"619336","names":[{"lang":"en","v":"EASTPEARL INDUSTRIAL LIMITED"},{"lang":"hk","v":"東寶實業有限公司"}],"company_since":"1997-08-04","company_dissolved":"2006-04-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"619359","names":[{"lang":"en","v":"EASTFULL INVESTMENT LIMITED"},{"lang":"hk","v":"東豐投資有限公司"}],"company_since":"1997-08-04","company_dissolved":"2003-04-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"619337","names":[{"lang":"en","v":"GLORY TREASURE ENTERPRISE LIMITED"},{"lang":"hk","v":"榮創企業有限公司"}],"company_since":"1997-08-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"619288","names":[{"lang":"en","v":"GOLDEN FAME INSURANCE SERVICES LIMITED"},{"lang":"hk","v":"金信保險服務有限公司"}],"company_since":"1997-08-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"619362","names":[{"lang":"en","v":"GREAT WISDOM INDUSTRIAL LIMITED (d2005-07-29)"},{"lang":"hk","v":"偉智實業有限公司"}],"company_since":"1997-08-04","company_dissolved":"2005-07-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"619283","names":[{"lang":"en","v":"IMPERIAL INTERNATIONAL (H.K.) LIMITED"},{"lang":"hk","v":"中鉅國際(香港)有限公司"}],"company_since":"1997-08-04","company_dissolved":"2001-10-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"619327","names":[{"lang":"en","v":"PROGRESS STUDIO LIMITED"},{"lang":"hk","v":"毅進舞台燈光音響工程有限公司"}],"company_since":"1997-08-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"619295","names":[{"lang":"en","v":"SHINDO ENTERPRISE (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"新藤企業(香港)有限公司"}],"company_since":"1997-08-04","company_dissolved":"2004-12-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"619372","names":[{"lang":"en","v":"STATE STREET GLOBAL ADVISORS ASIA LIMITED"},{"lang":"hk","v":"道富環球投資管理亞洲有限公司"}],"company_since":"1997-08-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"619338","names":[{"lang":"en","v":"MARTECH (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"綽雄有限公司"}],"company_since":"1997-08-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"619353","names":[{"lang":"en","v":"UNITED POWER TRADING LIMITED (d2005-07-29)"},{"lang":"hk","v":"統力貿易有限公司"}],"company_since":"1997-08-04","company_dissolved":"2005-07-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"619293","names":[{"lang":"en","v":"WINSOUND INTERNATIONAL LIMITED"},{"lang":"hk","v":"榮新國際有限公司"}],"company_since":"1997-08-04","company_dissolved":"2003-08-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"619398","names":[{"lang":"en","v":"WAI SING PHOTO SUPPLIES COMPANY LIMITED"},{"lang":"hk","v":"偉成攝影器材有限公司"}],"company_since":"1997-08-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"619333","names":[{"lang":"en","v":"SILVER JUBILEE CORPORATION LIMITED"},{"lang":"hk","v":"銀禧物業有限公司"}],"company_since":"1997-08-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"619289","names":[{"lang":"en","v":"REVASCO COMPANY LIMITED"}],"company_since":"1997-08-04","company_dissolved":"2002-09-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"619358","names":[{"lang":"en","v":"SUNSTAR PROPERTY LIMITED"},{"lang":"hk","v":"新星置業有限公司"}],"company_since":"1997-08-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
