{"tax_id":"519072","names":[{"lang":"en","v":"COASTAL WUHAN BRIDGE INVESTMENT LIMITED"},{"lang":"hk","v":"沿海漢橋投資有限公司"}],"company_since":"1995-06-29","company_dissolved":"2011-03-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519123","names":[{"lang":"en","v":"COMING WEALTH LIMITED"},{"lang":"hk","v":"佳臨興業有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519116","names":[{"lang":"en","v":"COMING WORLD (H.K.) LIMITED"},{"lang":"hk","v":"恆世(香港)有限公司"}],"company_since":"1995-06-29","company_dissolved":"1997-09-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"518917","names":[{"lang":"en","v":"CONDELL COMPANY LIMITED"},{"lang":"hk","v":"幹達利有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519096","names":[{"lang":"en","v":"CONTO FABRIC LIMITED"},{"lang":"hk","v":"冠東布業有限公司"}],"company_since":"1995-06-29","company_dissolved":"2009-06-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519086","names":[{"lang":"en","v":"COPYRIGHT (DISCOVERY BAY) LIMITED"},{"lang":"hk","v":"卜卜齋(愉景灣)有限公司"}],"company_since":"1995-06-29","company_dissolved":"2003-06-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"518992","names":[{"lang":"en","v":"CRAFTERS LIMITED"},{"lang":"hk","v":"巧匠有限公司"}],"company_since":"1995-06-29","company_dissolved":"2011-07-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518927","names":[{"lang":"en","v":"CRBC RAILWAY HOLDINGS COMPANY LIMITED"},{"lang":"hk","v":"中國路橋軌道運營控股有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519143","names":[{"lang":"en","v":"DACA ENTERTAINMENT COMPANY LIMITED"},{"lang":"hk","v":"得心娛樂有限公司"}],"company_since":"1995-06-29","company_dissolved":"2001-12-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518951","names":[{"lang":"en","v":"DAH FAT CHEMICAL INTERNATIONAL LIMITED"},{"lang":"hk","v":"大發化工國際有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519019","names":[{"lang":"en","v":"DOTEX COMPANY LIMITED"},{"lang":"hk","v":"新多葆有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519064","names":[{"lang":"en","v":"EAST WIND TRADING LIMITED (d2014-10-31)"}],"company_since":"1995-06-29","company_dissolved":"2014-10-31","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519138","names":[{"lang":"en","v":"ETRADE (HK) LIMITED"},{"lang":"hk","v":"建圖科技集團有限公司"}],"company_since":"1995-06-29","company_dissolved":"2008-04-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519118","names":[{"lang":"en","v":"EVER FORCE (H.K.) LIMITED"},{"lang":"hk","v":"駿霸(香港)有限公司"}],"company_since":"1995-06-29","company_dissolved":"2006-05-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519036","names":[{"lang":"en","v":"EXCEL CLASSIC LIMITED"},{"lang":"hk","v":"優雅有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519095","names":[{"lang":"en","v":"EXPLORER INTERNATIONAL LIMITED (d2012-11-02)"},{"lang":"hk","v":"天子科技有限公司"}],"company_since":"1995-06-29","company_dissolved":"2012-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518908","names":[{"lang":"en","v":"FONEX DEVELOPMENT LIMITED"},{"lang":"hk","v":"旺力發展有限公司"}],"company_since":"1995-06-29","company_dissolved":"2005-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518958","names":[{"lang":"en","v":"FUHKANG INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"阜康貿易有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519063","names":[{"lang":"en","v":"G.S. JEWELLERY HOLDINGS LIMITED"},{"lang":"hk","v":"金盛珠寶集團有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519038","names":[{"lang":"en","v":"GAINFORT INVESTMENT LIMITED"},{"lang":"hk","v":"勁煌投資有限公司"}],"company_since":"1995-06-29","company_dissolved":"2001-12-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518926","names":[{"lang":"en","v":"DEFINE COMPANY LIMITED"}],"company_since":"1995-06-29","company_dissolved":"2016-02-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518923","names":[{"lang":"en","v":"GAINROW TRANSPORTATION COMPANY LIMITED"},{"lang":"hk","v":"全潤運輸有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519068","names":[{"lang":"en","v":"gemro services Limited"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519000","names":[{"lang":"en","v":"GLYKON TECHNOLOGIES GROUP LIMITED"}],"company_since":"1995-06-29","company_dissolved":"1999-01-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519071","names":[{"lang":"en","v":"GOLD CORNER LIMITED (d2001-06-15)"},{"lang":"hk","v":"金高樂有限公司"}],"company_since":"1995-06-29","company_dissolved":"2001-06-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519107","names":[{"lang":"en","v":"GOLD COSMOS INVESTMENTS LIMITED"},{"lang":"hk","v":"金宇投資有限公司"}],"company_since":"1995-06-29","company_dissolved":"2004-06-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519023","names":[{"lang":"en","v":"GOLDEN CONCEPT INTERNATIONAL LIMITED (d2000-12-22)"},{"lang":"hk","v":"永源國際有限公司"}],"company_since":"1995-06-29","company_dissolved":"2000-12-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519147","names":[{"lang":"en","v":"GLORY STATE COMPANY LIMITED"},{"lang":"hk","v":"正慧有限公司"}],"company_since":"1995-06-29","company_dissolved":"2001-02-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519115","names":[{"lang":"en","v":"GOLDNICE CHINA LIMITED"},{"lang":"hk","v":"金利中國有限公司"}],"company_since":"1995-06-29","company_dissolved":"2004-02-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519044","names":[{"lang":"en","v":"GRAND TECH ENTERPRISE COMPANY LIMITED"},{"lang":"hk","v":"佳盛企業發展有限公司"}],"company_since":"1995-06-29","company_dissolved":"2015-03-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519029","names":[{"lang":"en","v":"GREAT LAND LIMITED (d2004-02-06)"},{"lang":"hk","v":"發港有限公司"}],"company_since":"1995-06-29","company_dissolved":"2004-02-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"518964","names":[{"lang":"en","v":"GREAT SEA INTERNATIONAL TRADING LIMITED (THE)"},{"lang":"hk","v":"宏海國際貿易有限公司"}],"company_since":"1995-06-29","company_dissolved":"2003-05-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"519004","names":[{"lang":"en","v":"HEAD MACHINE LIMITED"}],"company_since":"1995-06-29","company_dissolved":"2004-02-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518965","names":[{"lang":"en","v":"HARRY INDUSTRIES COMPANY LIMITED"},{"lang":"hk","v":"恆威實業拓展有限公司"}],"company_since":"1995-06-29","company_dissolved":"1998-08-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518972","names":[{"lang":"en","v":"HIFORCE LIMITED"},{"lang":"hk","v":"樂沛有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518983","names":[{"lang":"en","v":"HIGHER WAY TECHNOLOGY (H.K.) LIMITED"},{"lang":"hk","v":"海德威科技(香港)有限公司"}],"company_since":"1995-06-29","company_dissolved":"2005-11-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519003","names":[{"lang":"en","v":"GREAT WEALTH COMMUNICATION LIMITED"},{"lang":"hk","v":"富大電訊有限公司"}],"company_since":"1995-06-29","company_dissolved":"2004-02-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519093","names":[{"lang":"en","v":"HONG KONG PROFESSIONAL COUNSELLING ASSOCIATION LIMITED (THE)"},{"lang":"hk","v":"香港專業輔導協會有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
{"tax_id":"518966","names":[{"lang":"en","v":"GELPERTY LIMITED"}],"company_since":"1995-06-29","company_dissolved":"2002-12-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518947","names":[{"lang":"en","v":"DELO (HK) COMPANY LIMITED"},{"lang":"hk","v":"迪諾(香港)有限公司"}],"company_since":"1995-06-29","company_dissolved":"2002-07-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519135","names":[{"lang":"en","v":"HOUSING LOGISTIC LIMITED"},{"lang":"hk","v":"屋宇物流有限公司"}],"company_since":"1995-06-29","company_dissolved":"2007-11-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519076","names":[{"lang":"en","v":"HUNG CHEUK GARMENT FACTORY LIMITED"},{"lang":"hk","v":"紅雀製衣有限公司"}],"company_since":"1995-06-29","company_dissolved":"1999-05-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519031","names":[{"lang":"en","v":"HYDRAULIC ENGINEERING (H.K.) COMPANY LIMITED"},{"lang":"hk","v":"機械工程有限公司"}],"company_since":"1995-06-29","company_dissolved":"2008-08-07","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519109","names":[{"lang":"en","v":"EASTERN LION INTERNATIONAL LIMITED"},{"lang":"hk","v":"東獅國際有限公司"}],"company_since":"1995-06-29","company_dissolved":"2016-01-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519059","names":[{"lang":"en","v":"HOP SING KNITTING FACTORY LIMITED (d1998-06-05)"},{"lang":"hk","v":"合盛針織布廠有限公司"}],"company_since":"1995-06-29","company_dissolved":"1998-06-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518970","names":[{"lang":"en","v":"JADE PLAN HOLDINGS LIMITED"},{"lang":"hk","v":"曉聯集團有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518921","names":[{"lang":"en","v":"HUI'S COMPANY LIMITED"},{"lang":"hk","v":"雙傑有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519053","names":[{"lang":"en","v":"HOVEY COMPANY LIMITED"},{"lang":"hk","v":"好富達有限公司"}],"company_since":"1995-06-29","company_dissolved":"2012-08-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519001","names":[{"lang":"en","v":"IRVINE PRODUCTS COMPANY LIMITED"},{"lang":"hk","v":"海運技術產品有限公司"}],"company_since":"1995-06-29","company_dissolved":"2014-08-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519142","names":[{"lang":"en","v":"IPG MARKETING LIMITED"}],"company_since":"1995-06-29","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518994","names":[{"lang":"en","v":"JENKING COMPANY LIMITED"},{"lang":"hk","v":"金益利有限公司"}],"company_since":"1995-06-29","company_dissolved":"2005-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518982","names":[{"lang":"en","v":"FOCUS IMAGING &amp; DIGITAL PRINTING LIMITED"},{"lang":"hk","v":"科傑影像及數碼印刷有限公司"}],"company_since":"1995-06-29","company_dissolved":"2011-01-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"518981","names":[{"lang":"en","v":"HOUSING MANAGEMENT (GREATER CHINA) LIMITED"},{"lang":"hk","v":"屋宇管理(大中華)有限公司"}],"company_since":"1995-06-29","company_dissolved":"2007-11-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"518984","names":[{"lang":"en","v":"JILUS COMPANY LIMITED"},{"lang":"hk","v":"吉美有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519108","names":[{"lang":"en","v":"KAM HENG INTERNATIONAL LIMITED"},{"lang":"hk","v":"金亨國際有限公司"}],"company_since":"1995-06-29","company_dissolved":"2003-09-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519144","names":[{"lang":"en","v":"HONG KONG WAH NGAI ADVERTISING COMPANY LIMITED"},{"lang":"hk","v":"香港華藝廣告有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519134","names":[{"lang":"en","v":"KAVEN TOWN LIMITED"},{"lang":"hk","v":"金運通有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518969","names":[{"lang":"en","v":"KENT FORCE (H.K.) LIMITED"},{"lang":"hk","v":"曉強(香港)有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518894","names":[{"lang":"en","v":"HILITE ADVERTISING LIMITED"}],"company_since":"1995-06-29","company_dissolved":"2003-04-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518961","names":[{"lang":"en","v":"KILO-PROSPER LIMITED"},{"lang":"hk","v":"騏盛有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518973","names":[{"lang":"en","v":"KAMDA LIMITED (HK)"},{"lang":"hk","v":"金運達有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519052","names":[{"lang":"en","v":"KEE WAH CONSTRUCTION MATERIALS COMPANY LIMITED"},{"lang":"hk","v":"祺華建築材料行有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519106","names":[{"lang":"en","v":"KINGS INVESTMENTS LIMITED (d2007-03-09)"},{"lang":"hk","v":"金仕投資有限公司"}],"company_since":"1995-06-29","company_dissolved":"2007-03-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519030","names":[{"lang":"en","v":"GLOBAL ACT LIMITED (d2001-09-14)"},{"lang":"hk","v":"峻浩有限公司"}],"company_since":"1995-06-29","company_dissolved":"2001-09-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519020","names":[{"lang":"en","v":"KINGSWIN REALTY LIMITED"},{"lang":"hk","v":"世界置業有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519133","names":[{"lang":"en","v":"KLENBAR LIMITED"},{"lang":"hk","v":"勁力通有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519153","names":[{"lang":"en","v":"KOMROWSKI ENGINEERING AND TRADING (HK) LIMITED"},{"lang":"hk","v":"康樂工程有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519088","names":[{"lang":"en","v":"GLORY INTERNATIONAL HOLDINGS LIMITED (d2000-09-29)"},{"lang":"hk","v":"光耀國際集團有限公司"}],"company_since":"1995-06-29","company_dissolved":"2000-09-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519080","names":[{"lang":"en","v":"KURHAUS HONG KONG LIMITED"},{"lang":"hk","v":"科爾曼(香港)有限公司"}],"company_since":"1995-06-29","company_dissolved":"2004-06-11","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519060","names":[{"lang":"en","v":"L &amp; N Architects Limited"},{"lang":"hk","v":"樑安建築師有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"518975","names":[{"lang":"en","v":"GOAHEAD KING LIMITED"},{"lang":"hk","v":"躍帝有限公司"}],"company_since":"1995-06-29","company_dissolved":"2001-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518978","names":[{"lang":"en","v":"LAND EXPLORER LIMITED"},{"lang":"hk","v":"衡展有限公司"}],"company_since":"1995-06-29","company_dissolved":"2004-02-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519105","names":[{"lang":"en","v":"KWONG SHING DEVELOPMENT LIMITED (d2006-01-20)"},{"lang":"hk","v":"廣城發展有限公司"}],"company_since":"1995-06-29","company_dissolved":"2006-01-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519148","names":[{"lang":"en","v":"LAND REGENT ENTERPRISES LIMITED"},{"lang":"hk","v":"連駿企業有限公司"}],"company_since":"1995-06-29","company_dissolved":"2002-11-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518962","names":[{"lang":"en","v":"LARK TELECOM SERVICES LIMITED"},{"lang":"hk","v":"立基電訊服務有限公司"}],"company_since":"1995-06-29","company_dissolved":"2004-11-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519011","names":[{"lang":"en","v":"LINDE MATERIAL HANDLING HONG KONG LIMITED"},{"lang":"hk","v":"林德香港有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519103","names":[{"lang":"en","v":"GREAT VALLEY INTERNATIONAL LIMITED"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"518953","names":[{"lang":"en","v":"LIONAPEX (HONG KONG) LIMITED"},{"lang":"hk","v":"寶獅機械有限公司"}],"company_since":"1995-06-29","company_dissolved":"2002-03-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"518906","names":[{"lang":"en","v":"NATIONAL SCORE DEVELOPMENT LIMITED"},{"lang":"hk","v":"訊高發展有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"518989","names":[{"lang":"en","v":"ORIENT TOWN INTERNATIONAL LIMITED"},{"lang":"hk","v":"遠城國際有限公司"}],"company_since":"1995-06-29","company_dissolved":"2005-08-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"519137","names":[{"lang":"en","v":"NATIONAL WELL (H.K.) LIMITED"},{"lang":"hk","v":"聯邦東方(香港)有限公司"}],"company_since":"1995-06-29","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519111","names":[{"lang":"en","v":"ORIENTAL SQUARE LIMITED"},{"lang":"hk","v":"東林有限公司"}],"company_since":"1995-06-29","company_dissolved":"2003-09-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"518946","names":[{"lang":"en","v":"ORCHID LIMITED (d2012-03-16)"}],"company_since":"1995-06-29","company_dissolved":"2012-03-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519146","names":[{"lang":"en","v":"PARK MASTER COMPANY LIMITED"},{"lang":"hk","v":"百升有限公司"}],"company_since":"1995-06-29","company_dissolved":"2019-02-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518967","names":[{"lang":"en","v":"PROFILES MEDIA CONSULTANTS, ASIA LIMITED"}],"company_since":"1995-06-29","company_dissolved":"2002-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518905","names":[{"lang":"en","v":"MASTER CENTURY DEVELOPMENT LIMITED"},{"lang":"hk","v":"文順發展有限公司"}],"company_since":"1995-06-29","company_dissolved":"2020-08-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519058","names":[{"lang":"en","v":"R T GROUP LIMITED"}],"company_since":"1995-06-29","company_dissolved":"2001-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519067","names":[{"lang":"en","v":"LA COCO (H.K.) LIMITED"}],"company_since":"1995-06-29","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519139","names":[{"lang":"en","v":"QINHUI MANAGEMENT LIMITED"},{"lang":"hk","v":"勤輝管理有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518955","names":[{"lang":"en","v":"LE CHAMP (HK) COMPANY LIMITED"},{"lang":"hk","v":"利昌電子(香港)有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519150","names":[{"lang":"en","v":"LAND OCEAN ENTERPRISES LIMITED"},{"lang":"hk","v":"連海企業有限公司"}],"company_since":"1995-06-29","company_dissolved":"1999-05-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519050","names":[{"lang":"en","v":"REGENCY INTERNATIONAL HOTEL ASIA PACIFIC LIMITED"}],"company_since":"1995-06-29","company_dissolved":"2008-12-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518936","names":[{"lang":"en","v":"RICH PLAN INVESTMENT LIMITED"},{"lang":"hk","v":"迅溢投資有限公司"}],"company_since":"1995-06-29","company_dissolved":"2002-11-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518932","names":[{"lang":"en","v":"S T &amp; T CORPORATION, LIMITED"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519099","names":[{"lang":"en","v":"SHANTOU INSURANCE AGENTS LIMITED"},{"lang":"hk","v":"汕頭保險代理有限公司"}],"company_since":"1995-06-29","company_dissolved":"2000-07-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519077","names":[{"lang":"en","v":"SERBOR ENTERPRISE COMPANY LIMITED"},{"lang":"hk","v":"世寶洋行有限公司"}],"company_since":"1995-06-29","company_dissolved":"2004-02-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518956","names":[{"lang":"en","v":"LUEN SHING DYEING COMPANY LIMITED"},{"lang":"hk","v":"聯盛洗染廠有限公司"}],"company_since":"1995-06-29","company_dissolved":"2002-12-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519112","names":[{"lang":"en","v":"ORIENTAL HINT LIMITED"},{"lang":"hk","v":"東慶有限公司"}],"company_since":"1995-06-29","company_dissolved":"2004-02-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519008","names":[{"lang":"en","v":"SANFITO LIMITED"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518930","names":[{"lang":"en","v":"SHUANGXI (CHINA) LIMITED"},{"lang":"hk","v":"雙璽(中國)有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518922","names":[{"lang":"en","v":"Schlegel Electronic Materials Asia Limited"},{"lang":"hk","v":"仕來高電子制品亞洲有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519075","names":[{"lang":"en","v":"OZIMA ELECTRONICS (H.K.) CO. LIMITED"},{"lang":"hk","v":"大島電機(香港)有限公司"}],"company_since":"1995-06-29","company_dissolved":"2002-03-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"518939","names":[{"lang":"en","v":"SPEEDY TRADE INVESTMENT LIMITED"},{"lang":"hk","v":"增暉投資有限公司"}],"company_since":"1995-06-29","company_dissolved":"2002-04-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519066","names":[{"lang":"en","v":"MONCO MARKETING CO., LIMITED"},{"lang":"hk","v":"盟禾(香港)有限公司"}],"company_since":"1995-06-29","company_dissolved":"2000-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519130","names":[{"lang":"en","v":"SINO RICH SUCCESS INVESTMENT LIMITED"},{"lang":"hk","v":"中泰盛大投資集團有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"518938","names":[{"lang":"en","v":"SUPER LINK INVESTMENT LIMITED (d2003-12-05)"},{"lang":"hk","v":"訊廣投資有限公司"}],"company_since":"1995-06-29","company_dissolved":"2003-12-05","company_type_txt":"Private, ltd by shares"},
{"tax_id":"518931","names":[{"lang":"en","v":"SHUANGXI (HONG KONG) LIMITED"},{"lang":"hk","v":"雙璽(香港)有限公司"}],"company_since":"1995-06-29","company_dissolved":"2003-01-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518998","names":[{"lang":"en","v":"SWITIME INDUSTRIAL LIMITED"},{"lang":"hk","v":"時美實業有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518950","names":[{"lang":"en","v":"RISING SUN HOLIDAYS LIMITED (d2001-12-21)"},{"lang":"hk","v":"旭日假期有限公司"}],"company_since":"1995-06-29","company_dissolved":"2001-12-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519091","names":[{"lang":"en","v":"TECHFIL COMPANY LIMITED"},{"lang":"hk","v":"德蜚有限公司"}],"company_since":"1995-06-29","company_dissolved":"2000-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518929","names":[{"lang":"en","v":"SUZHOU HUANQIU ACUPUNCTURE MEDICAL APPLIANCE (HK) LIMITED"},{"lang":"hk","v":"蘇州環球針灸醫療器械(香港)有限公司"}],"company_since":"1995-06-29","company_dissolved":"2010-02-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518914","names":[{"lang":"en","v":"SWISS INSURANCE AGENCY (HONG KONG) LIMITED"},{"lang":"hk","v":"瑞太保險代理(香港)有限公司"}],"company_since":"1995-06-29","company_dissolved":"2006-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519110","names":[{"lang":"en","v":"STANDVIEW LIMITED"},{"lang":"hk","v":"松景有限公司"}],"company_since":"1995-06-29","company_dissolved":"2006-12-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"518919","names":[{"lang":"en","v":"SUM KEE STEEL COMPANY LIMITED"},{"lang":"hk","v":"森記鋼鐵有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518911","names":[{"lang":"en","v":"PIONEER CONCORD INTERNATIONAL LIMITED"},{"lang":"hk","v":"領港國際有限公司"}],"company_since":"1995-06-29","company_dissolved":"2001-10-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519145","names":[{"lang":"en","v":"PARK LEADER COMPANY LIMITED"},{"lang":"hk","v":"栢程有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519114","names":[{"lang":"en","v":"TRADEWISE LIMITED"},{"lang":"hk","v":"易惠有限公司"}],"company_since":"1995-06-29","company_dissolved":"2020-04-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519027","names":[{"lang":"en","v":"TINS DECISION (HK) LIMITED"},{"lang":"hk","v":"鐵罐決定(香港)有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518907","names":[{"lang":"en","v":"SUN TALENT DEVELOPMENT LIMITED (d2000-10-20)"},{"lang":"hk","v":"日智發展有限公司"}],"company_since":"1995-06-29","company_dissolved":"2000-10-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519101","names":[{"lang":"en","v":"PROPONENT HONG KONG LIMITED"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519007","names":[{"lang":"en","v":"TRANSO-PHARM (HONG KONG) LIMITED"},{"lang":"hk","v":"豐盛醫葯(香港)有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519022","names":[{"lang":"en","v":"SKY FOCUS INTERNATIONAL LIMITED (d2000-02-18)"},{"lang":"hk","v":"創天國際有限公司"}],"company_since":"1995-06-29","company_dissolved":"2000-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519125","names":[{"lang":"en","v":"TRISTAR KING LIMITED"},{"lang":"hk","v":"普帝有限公司"}],"company_since":"1995-06-29","company_dissolved":"2001-10-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519084","names":[{"lang":"en","v":"SNAP ON HAIR LIMITED"}],"company_since":"1995-06-29","company_dissolved":"2011-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518900","names":[{"lang":"en","v":"MAN SHUN TRANSPORTATION COMPANY LIMITED"},{"lang":"hk","v":"文信運輸有限公司"}],"company_since":"1995-06-29","company_dissolved":"2004-02-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518920","names":[{"lang":"en","v":"REGAL CHELSEA COMPANY LIMITED"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519152","names":[{"lang":"en","v":"REGENT HARVEST COMPANY LIMITED"},{"lang":"hk","v":"駿祺有限公司"}],"company_since":"1995-06-29","company_dissolved":"2005-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518977","names":[{"lang":"en","v":"MANOR FORCE LIMITED"},{"lang":"hk","v":"能鋒有限公司"}],"company_since":"1995-06-29","company_dissolved":"1999-08-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519013","names":[{"lang":"en","v":"VP BUSINESS CENTRE LIMITED"},{"lang":"hk","v":"威彼商務中心有限公司"}],"company_since":"1995-06-29","company_dissolved":"2007-11-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518925","names":[{"lang":"en","v":"WAH CHEONG METAL COMPANY LIMITED"},{"lang":"hk","v":"華昌五金有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518904","names":[{"lang":"en","v":"PIONEER CONCORD DEVELOPMENT LIMITED"},{"lang":"hk","v":"領港發展有限公司"}],"company_since":"1995-06-29","company_dissolved":"2004-06-11","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519040","names":[{"lang":"en","v":"MAX CLASSIC LIMITED (d2000-02-18)"},{"lang":"hk","v":"名雅有限公司"}],"company_since":"1995-06-29","company_dissolved":"2000-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518980","names":[{"lang":"en","v":"Revenco International Limited"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519047","names":[{"lang":"en","v":"T &amp; L CHEMICAL (INTERNATIONAL) LIMITED"},{"lang":"hk","v":"德利化工(國際)有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"518937","names":[{"lang":"en","v":"WANG HING HONG GINSENG COMPANY LIMITED"},{"lang":"hk","v":"宏興行蔘茸有限公司"}],"company_since":"1995-06-29","company_dissolved":"2001-05-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519100","names":[{"lang":"en","v":"LUK FOOK INVESTMENT CO., LIMITED"},{"lang":"hk","v":"祿福置業有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518987","names":[{"lang":"en","v":"MANLEY TERRY LIMITED"},{"lang":"hk","v":"萬利泰來有限公司"}],"company_since":"1995-06-29","company_dissolved":"2014-05-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519017","names":[{"lang":"en","v":"HARBOUR INVESTMENT (FAR EAST) LIMITED"},{"lang":"hk","v":"建泰興業有限公司"}],"company_since":"1995-06-29","company_dissolved":"2011-02-25","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519061","names":[{"lang":"en","v":"WAYTON INTERNATIONAL MARKETING LIMITED"},{"lang":"hk","v":"偉田國際市塲策劃有限公司"}],"company_since":"1995-06-29","company_dissolved":"2002-11-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"518895","names":[{"lang":"en","v":"MAXTRON CORPORATION LIMITED"},{"lang":"hk","v":"麥仕通有限公司"}],"company_since":"1995-06-29","company_dissolved":"2001-03-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"519074","names":[{"lang":"en","v":"WAVETEK HONG KONG LIMITED"},{"lang":"hk","v":"韋夫特克香港有限公司"}],"company_since":"1995-06-29","company_dissolved":"2002-08-02","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519024","names":[{"lang":"en","v":"WELL FAME TRADING LIMITED (d2008-02-01)"},{"lang":"hk","v":"友邦貿易有限公司"}],"company_since":"1995-06-29","company_dissolved":"2008-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519102","names":[{"lang":"en","v":"MAXFINE SHIPPING (HK) LIMITED"},{"lang":"hk","v":"美輝船務(香港)有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518974","names":[{"lang":"en","v":"SITREND LIMITED"},{"lang":"hk","v":"思祥有限公司"}],"company_since":"1995-06-29","company_dissolved":"2004-08-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"518995","names":[{"lang":"en","v":"STARLIGHT FASHION LIMITED (d2006-01-20)"},{"lang":"hk","v":"星輝時裝有限公司"}],"company_since":"1995-06-29","company_dissolved":"2006-01-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"518952","names":[{"lang":"en","v":"NEW GRAND JEWELLERY &amp; WATCH COMPANY LIMITED"},{"lang":"hk","v":"新達利珠寶鐘錶有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519042","names":[{"lang":"en","v":"WIN &amp; WIN INVESTMENT LIMITED"},{"lang":"hk","v":"勝穎投資有限公司"}],"company_since":"1995-06-29","company_dissolved":"2002-09-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519094","names":[{"lang":"en","v":"ORIENT WAY (H.K.) LIMITED"},{"lang":"hk","v":"驊駿(香港)有限公司"}],"company_since":"1995-06-29","company_dissolved":"2009-11-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"518933","names":[{"lang":"en","v":"MENSCH-POSH LIMITED"},{"lang":"hk","v":"馬賽堡有限公司"}],"company_since":"1995-06-29","company_dissolved":"2001-01-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518993","names":[{"lang":"en","v":"WELL YUE LIMITED"},{"lang":"hk","v":"緯優有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"518935","names":[{"lang":"en","v":"NOBLE WORLD INVESTMENT LIMITED"},{"lang":"hk","v":"福倡投資有限公司"}],"company_since":"1995-06-29","company_dissolved":"2002-11-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518916","names":[{"lang":"en","v":"MINWA (SHENZHEN) INDUSTRIAL PARK COMPANY LIMITED"},{"lang":"hk","v":"明華(深圳)工業園有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518943","names":[{"lang":"en","v":"NOBLE FUND LIMITED"},{"lang":"hk","v":"樂寶財務有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519039","names":[{"lang":"en","v":"HILLSTON INVESTMENT LIMITED"},{"lang":"hk","v":"興田投資有限公司"}],"company_since":"1995-06-29","company_dissolved":"2004-02-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519069","names":[{"lang":"en","v":"MIXON LIMITED (d2012-11-30)"}],"company_since":"1995-06-29","company_dissolved":"2012-11-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518999","names":[{"lang":"en","v":"HILLFUL LIMITED (d2009-04-30)"}],"company_since":"1995-06-29","company_dissolved":"2009-04-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518899","names":[{"lang":"en","v":"WINLY AGENTS LIMITED"},{"lang":"hk","v":"永利代理有限公司"}],"company_since":"1995-06-29","company_dissolved":"2000-07-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"518897","names":[{"lang":"en","v":"WINLY OVERSEAS LIMITED"},{"lang":"hk","v":"永利海外有限公司"}],"company_since":"1995-06-29","company_dissolved":"2006-12-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519055","names":[{"lang":"en","v":"NANPLES ALUMINIUM LIMITED"},{"lang":"hk","v":"南泰鋁業有限公司"}],"company_since":"1995-06-29","company_dissolved":"2009-05-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518915","names":[{"lang":"en","v":"T.P. COMMUNICATIONS COMPANY LIMITED"},{"lang":"hk","v":"太平通有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519082","names":[{"lang":"en","v":"HING LOONG GINSENG HONG COMPANY LIMITED"},{"lang":"hk","v":"興隆參茸行有限公司"}],"company_since":"1995-06-29","company_dissolved":"2009-11-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519014","names":[{"lang":"en","v":"WISE PROFIT HOLDINGS LIMITED (d2004-02-06)"},{"lang":"hk","v":"智豪集團有限公司"}],"company_since":"1995-06-29","company_dissolved":"2004-02-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519131","names":[{"lang":"en","v":"KENHIGH LIMITED"},{"lang":"hk","v":"紀亨有限公司"}],"company_since":"1995-06-29","company_dissolved":"2004-02-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519119","names":[{"lang":"en","v":"WISE UNION (H.K.) LIMITED"},{"lang":"hk","v":"世群(香港)有限公司"}],"company_since":"1995-06-29","company_dissolved":"1998-11-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519015","names":[{"lang":"en","v":"ORIENT STYLE HOLDINGS LIMITED"},{"lang":"hk","v":"東彩集團有限公司"}],"company_since":"1995-06-29","company_dissolved":"2004-06-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518898","names":[{"lang":"en","v":"WINLY RESOURCES LIMITED"},{"lang":"hk","v":"永利資源有限公司"}],"company_since":"1995-06-29","company_dissolved":"2001-06-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519065","names":[{"lang":"en","v":"NIPPON GONDOLA (H.K.) LIMITED"}],"company_since":"1995-06-29","company_dissolved":"2001-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519025","names":[{"lang":"en","v":"SYMPHONIC NETWORKS (SHANGHAI) LIMITED"},{"lang":"hk","v":"滙訊網絡系統(上海)有限公司"}],"company_since":"1995-06-29","company_dissolved":"2001-06-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519087","names":[{"lang":"en","v":"XIAMEN KEEPTOPS ELECTRONICS (HK) CO., LIMITED"},{"lang":"hk","v":"富亞(香港)電子有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519073","names":[{"lang":"en","v":"XIANG LU (H.K.) TRADING COMPANY LIMITED"},{"lang":"hk","v":"翔鷺(香港)貿易有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519010","names":[{"lang":"en","v":"YOCORP LIMITED"}],"company_since":"1995-06-29","company_dissolved":"2012-12-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518949","names":[{"lang":"en","v":"YUN JIE INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"雲階國際發展有限公司"}],"company_since":"1995-06-29","company_dissolved":"2004-02-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"519132","names":[{"lang":"en","v":"PENYEAR LIMITED"},{"lang":"hk","v":"勁欣有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"519124","names":[{"lang":"en","v":"TRISTAR LEADER LIMITED"},{"lang":"hk","v":"普衡有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519049","names":[{"lang":"en","v":"RELIANCE SKY (GROUP) LIMITED"},{"lang":"hk","v":"力天(集團)有限公司"}],"company_since":"1995-06-29","company_dissolved":"2004-02-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519113","names":[{"lang":"en","v":"ORIENTAL SPIRIT LIMITED"},{"lang":"hk","v":"東靈有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"518990","names":[{"lang":"en","v":"WELL-KNOWN (INTERNATIONAL) SHIPPING LIMITED"},{"lang":"hk","v":"偉輪(國際)船務有限公司"}],"company_since":"1995-06-29","company_dissolved":"2002-07-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519046","names":[{"lang":"en","v":"PAK LEE TRADING COMPANY LIMITED"},{"lang":"hk","v":"百利貿易發展有限公司"}],"company_since":"1995-06-29","company_dissolved":"2016-01-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"518976","names":[{"lang":"en","v":"WIN SALES DEVELOPMENT LIMITED"},{"lang":"hk","v":"駿立發展有限公司"}],"company_since":"1995-06-29","company_dissolved":"2004-12-31","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519085","names":[{"lang":"en","v":"PATTERSON WORLDWIDE (HK) LIMITED"}],"company_since":"1995-06-29","company_dissolved":"2003-02-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519037","names":[{"lang":"en","v":"WEBSUITE LIMITED"}],"company_since":"1995-06-29","company_dissolved":"2002-12-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"518901","names":[{"lang":"en","v":"WINEX LIMITED"},{"lang":"hk","v":"旺力有限公司"}],"company_since":"1995-06-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519149","names":[{"lang":"en","v":"SHANGHAI POWER GLASSFIBER (HONG KONG) CO. LIMITED"},{"lang":"hk","v":"上海電力玻璃鋼(香港)有限公司"}],"company_since":"1995-06-29","company_dissolved":"2001-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519016","names":[{"lang":"en","v":"WORLD STEP DEVELOPMENT LIMITED (d2001-03-23)"},{"lang":"hk","v":"世鋒發展有限公司"}],"company_since":"1995-06-29","company_dissolved":"2001-03-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"518924","names":[{"lang":"en","v":"YUEN YUEN DECORATION LIMITED"},{"lang":"hk","v":"圓園裝飾有限公司"}],"company_since":"1995-06-29","company_dissolved":"2002-09-06","company_type_txt":"Private, ltd by shares"},
