undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"691610","names":[{"lang":"en","v":"EVER-RICH ENGINEERING HOLDINGS LIMITED"},{"lang":"hk","v":"永豐工程集團有限公司"}],"company_since":"1999-10-15","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"691456","names":[{"lang":"en","v":"D&amp;H GARMENT LIMITED"}],"company_since":"1999-10-15","company_dissolved":"2002-10-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"691639","names":[{"lang":"en","v":"FOUR SEASONS (H.K.) CO. LIMITED"},{"lang":"hk","v":"五達(香港)有限公司"}],"company_since":"1999-10-15","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"691678","names":[{"lang":"en","v":"FUKI PROPERTY MANAGEMENT LIMITED"},{"lang":"hk","v":"富基物業管理有限公司"}],"company_since":"1999-10-15","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"691436","names":[{"lang":"en","v":"EVER PACIFIC TRADING LIMITED"},{"lang":"hk","v":"利港貿易有限公司"}],"company_since":"1999-10-15","company_dissolved":"2019-03-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"691558","names":[{"lang":"en","v":"FULLY CHANCE GLOBAL LIMITED"}],"company_since":"1999-10-15","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"691706","names":[{"lang":"en","v":"FURNITURE CHINA LIMITED"}],"company_since":"1999-10-15","company_dissolved":"2003-12-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"691536","names":[{"lang":"en","v":"DRAGON LINK TECHNOLOGY LIMITED"},{"lang":"hk","v":"華訊科技有限公司"}],"company_since":"1999-10-15","company_dissolved":"2010-09-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"691443","names":[{"lang":"en","v":"GIORDANO MANAGEMENT SERVICES LIMITED"},{"lang":"hk","v":"佐丹奴管理服務有限公司"}],"company_since":"1999-10-15","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"691559","names":[{"lang":"en","v":"EAST BLESS LIMITED"},{"lang":"hk","v":"佑東有限公司"}],"company_since":"1999-10-15","company_dissolved":"2008-02-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"691728","names":[{"lang":"en","v":"GNK INTERNATIONAL FINANCE GROUP LIMITED"},{"lang":"hk","v":"海富國際融資集團有限公司"}],"company_since":"1999-10-15","company_dissolved":"2006-03-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"691492","names":[{"lang":"en","v":"ESSENCE TEXTILE (HK) LIMITED (THE)"},{"lang":"hk","v":"思匯紡織(香港)有限公司"}],"company_since":"1999-10-15","company_dissolved":"2011-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"691622","names":[{"lang":"en","v":"GOLDEN POWER TECHNOLOGY LIMITED (d2006-03-24)"},{"lang":"hk","v":"創威科技有限公司"}],"company_since":"1999-10-15","company_dissolved":"2006-03-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"691673","names":[{"lang":"en","v":"GOLDENLEO COMPANY LIMITED"},{"lang":"hk","v":"顯遠實業有限公司"}],"company_since":"1999-10-15","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"691474","names":[{"lang":"en","v":"EAST DRAGON DEVELOPMENT LIMITED"},{"lang":"hk","v":"華龍發展有限公司"}],"company_since":"1999-10-15","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"691429","names":[{"lang":"en","v":"GRAND ACE DEVELOPMENT LIMITED (d2007-06-15)"},{"lang":"hk","v":"嘉雅發展有限公司"}],"company_since":"1999-10-15","company_dissolved":"2007-06-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"691658","names":[{"lang":"en","v":"GRAND PORT TECHNOLOGY LIMITED"},{"lang":"hk","v":"宏港科技有限公司"}],"company_since":"1999-10-15","company_dissolved":"2004-08-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"691634","names":[{"lang":"en","v":"EVERTECH ELECTRONICS INDUSTRIES CO. LIMITED"},{"lang":"hk","v":"易達電子科技有限公司"}],"company_since":"1999-10-15","company_dissolved":"2019-05-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"691628","names":[{"lang":"en","v":"GREAT TECH (HONG KONG) ENTERPRISES LIMITED"},{"lang":"hk","v":"英科(香港)企業有限公司"}],"company_since":"1999-10-15","company_dissolved":"2013-06-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"691435","names":[{"lang":"en","v":"FORDLAND DEVELOPMENT LIMITED"},{"lang":"hk","v":"福嘉發展有限公司"}],"company_since":"1999-10-15","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"691441","names":[{"lang":"en","v":"FORDWIDE DEVELOPMENT LIMITED (d2010-08-06)"},{"lang":"hk","v":"科遠發展有限公司"}],"company_since":"1999-10-15","company_dissolved":"2010-08-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"691580","names":[{"lang":"en","v":"GOOD HILTON LIMITED"},{"lang":"hk","v":"亨達行有限公司"}],"company_since":"1999-10-15","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"691461","names":[{"lang":"en","v":"HK SKY ENTERTAINMENT HOLDINGS LIMITED"},{"lang":"hk","v":"天網娛樂集團有限公司"}],"company_since":"1999-10-15","company_dissolved":"2015-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"691496","names":[{"lang":"en","v":"FUNG SHING INDUSTRIES LIMITED"},{"lang":"hk","v":"豐盛工業有限公司"}],"company_since":"1999-10-15","company_dissolved":"2009-08-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"691654","names":[{"lang":"en","v":"HONEST (H.K.) LIMITED"},{"lang":"hk","v":"恒星(香港)有限公司"}],"company_since":"1999-10-15","company_dissolved":"2010-02-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"691683","names":[{"lang":"en","v":"GAIA ENERGY (HK) LIMITED"}],"company_since":"1999-10-15","company_dissolved":"2006-03-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"691561","names":[{"lang":"en","v":"Hongkong and Eastern Shipping Agencies Limited"},{"lang":"hk","v":"東方船務(中國)有限公司"}],"company_since":"1999-10-15","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"691611","names":[{"lang":"en","v":"GLORY SMART LIMITED (d2008-08-01)"},{"lang":"hk","v":"飛榮有限公司"}],"company_since":"1999-10-15","company_dissolved":"2008-08-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"691438","names":[{"lang":"en","v":"GOLD FAITH MANAGEMENT LIMITED (d2009-03-06)"},{"lang":"hk","v":"金信管理有限公司"}],"company_since":"1999-10-15","company_dissolved":"2009-03-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"691417","names":[{"lang":"en","v":"HUNTING (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"漢鼎(香港)有限公司"}],"company_since":"1999-10-15","company_dissolved":"2014-12-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"691482","names":[{"lang":"en","v":"INDEX GARMENT LIMITED"},{"lang":"hk","v":"興達製衣有限公司"}],"company_since":"1999-10-15","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"691567","names":[{"lang":"en","v":"GOOD SPREAD LIMITED (d2012-01-20)"},{"lang":"hk","v":"開業有限公司"}],"company_since":"1999-10-15","company_dissolved":"2012-01-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"691641","names":[{"lang":"en","v":"ISTEELASIA (HONG KONG) LIMITED"},{"lang":"hk","v":"亞洲鋼鐵電子交易所(香港)有限公司"}],"company_since":"1999-10-15","company_dissolved":"2011-09-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"691677","names":[{"lang":"en","v":"HAPPY FRIEND FOOD STORE LIMITED"},{"lang":"hk","v":"開心友餐廳有限公司"}],"company_since":"1999-10-15","company_dissolved":"2002-05-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"691490","names":[{"lang":"en","v":"JS CRESVALE NOMINEES LIMITED"}],"company_since":"1999-10-15","company_dissolved":"2002-10-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"691551","names":[{"lang":"en","v":"L'AIR COMPANY LIMITED"},{"lang":"hk","v":"雷亞有限公司"}],"company_since":"1999-10-15","company_dissolved":"2001-03-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"691503","names":[{"lang":"en","v":"HONG KONG EVERWINN ENTERPRISE LIMITED"},{"lang":"hk","v":"香港恆達企業有限公司"}],"company_since":"1999-10-15","company_dissolved":"2006-03-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"691633","names":[{"lang":"en","v":"MERRY LINK TEXTILES LIMITED"},{"lang":"hk","v":"美聯紡織(毛紡)有限公司"}],"company_since":"1999-10-15","company_dissolved":"2011-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"691451","names":[{"lang":"en","v":"I. DE-ZONE LIMITED"}],"company_since":"1999-10-15","company_dissolved":"2002-08-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"691428","names":[{"lang":"en","v":"JETTER ENTERPRISE LIMITED"},{"lang":"hk","v":"捷泰企業有限公司"}],"company_since":"1999-10-15","company_dissolved":"2013-08-16","company_type_txt":"Private, ltd by shares"},
{"tax_id":"691609","names":[{"lang":"en","v":"ON FAIR NOMINEES LIMITED"},{"lang":"hk","v":"安培代理人有限公司"}],"company_since":"1999-10-15","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"691721","names":[{"lang":"en","v":"ONE HUNDRED YEARS OF FILM COMPANY LIMITED"},{"lang":"hk","v":"一百年電影有限公司"}],"company_since":"1999-10-15","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"691493","names":[{"lang":"en","v":"ON-LINE SYSTEMS (HK) LIMITED"}],"company_since":"1999-10-15","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"691447","names":[{"lang":"en","v":"JOVIAN DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"縱橫貿易發展有限公司"}],"company_since":"1999-10-15","company_dissolved":"2010-03-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"691651","names":[{"lang":"en","v":"PACIFIC EXCELLENT LIMITED"},{"lang":"hk","v":"宏江有限公司"}],"company_since":"1999-10-15","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"691715","names":[{"lang":"en","v":"PACIFIC TRADING INTERNATIONAL LIMITED (d2009-03-27)"},{"lang":"hk","v":"太平洋國際商貿有限公司"}],"company_since":"1999-10-15","company_dissolved":"2009-03-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"691442","names":[{"lang":"en","v":"PACIFIC WIN (H.K.) LIMITED (d2002-06-07)"},{"lang":"hk","v":"恒添(香港)有限公司"}],"company_since":"1999-10-15","company_dissolved":"2002-06-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"691416","names":[{"lang":"en","v":"PHOTOSTOP CO., LIMITED"},{"lang":"hk","v":"冲晒站有限公司"}],"company_since":"1999-10-15","company_dissolved":"2018-09-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"691644","names":[{"lang":"en","v":"PIONEER (WONG'S) INDUSTRIES CO., LIMITED"},{"lang":"hk","v":"派安(黃氏)實業有限公司"}],"company_since":"1999-10-15","company_dissolved":"2008-08-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"691422","names":[{"lang":"en","v":"POINTER INVESTMENT LIMITED (d2006-03-24)"},{"lang":"hk","v":"邦達投資有限公司"}],"company_since":"1999-10-15","company_dissolved":"2006-03-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"691607","names":[{"lang":"en","v":"LTL INTERNATIONAL FINANCE LIMITED"},{"lang":"hk","v":"海匯金融國際有限公司"}],"company_since":"1999-10-15","company_dissolved":"2004-10-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"691653","names":[{"lang":"en","v":"PORTEAST HONG KONG LIMITED"}],"company_since":"1999-10-15","company_dissolved":"2003-04-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"691643","names":[{"lang":"en","v":"M3COM (HONG KONG) LIMITED"}],"company_since":"1999-10-15","company_dissolved":"2017-11-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"691672","names":[{"lang":"en","v":"POWER E-BIZ INTERNATIONAL LIMITED"}],"company_since":"1999-10-15","company_dissolved":"2001-11-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"691473","names":[{"lang":"en","v":"INTERNATIONAL CHINESE MEDICAL ANDROLOGY HOSPITAL LIMITED (THE)"},{"lang":"hk","v":"國際中醫男科醫院有限公司"}],"company_since":"1999-10-15","company_dissolved":"2011-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"691627","names":[{"lang":"en","v":"K.P.G. TEXTILE LIMITED"}],"company_since":"1999-10-15","company_dissolved":"2001-10-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"691604","names":[{"lang":"en","v":"MEESUN LIMITED"},{"lang":"hk","v":"美辰有限公司"}],"company_since":"1999-10-15","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"691587","names":[{"lang":"en","v":"RICHARD CHAN CLAIMS CONSULTANCY LIMITED"}],"company_since":"1999-10-15","company_dissolved":"2005-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"691709","names":[{"lang":"en","v":"SHEARMAN &amp; STERLING CHINA LIMITED"}],"company_since":"1999-10-15","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"691662","names":[{"lang":"en","v":"SINCERE LUCK TECHNOLOGY LIMITED"},{"lang":"hk","v":"瑞祥科技有限公司"}],"company_since":"1999-10-15","company_dissolved":"2003-05-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"691579","names":[{"lang":"en","v":"ORIENT INTERNATIONAL INVESTMENT LIMITED (d2003-01-10)"},{"lang":"hk","v":"東圖國際投資有限公司"}],"company_since":"1999-10-15","company_dissolved":"2003-01-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"691704","names":[{"lang":"en","v":"NEW CENTURY LAUNDRY LIMITED"},{"lang":"hk","v":"新世紀洗衣有限公司"}],"company_since":"1999-10-15","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"691578","names":[{"lang":"en","v":"SINO-HK INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"港京國際投資有限公司"}],"company_since":"1999-10-15","company_dissolved":"2001-03-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"691462","names":[{"lang":"en","v":"SMART CONNECTION LIMITED"},{"lang":"hk","v":"外來星有限公司"}],"company_since":"1999-10-15","company_dissolved":"2009-03-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"691574","names":[{"lang":"en","v":"SPEEDY VICTORY LIMITED (d2002-03-15)"},{"lang":"hk","v":"奔勝有限公司"}],"company_since":"1999-10-15","company_dissolved":"2002-03-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"691518","names":[{"lang":"en","v":"POWER CAPITAL LIMITED (d2004-07-23)"},{"lang":"hk","v":"權資有限公司"}],"company_since":"1999-10-15","company_dissolved":"2004-07-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"691469","names":[{"lang":"en","v":"PRCCHINA.COM LIMITED"},{"lang":"hk","v":"魅力大中華有限公司"}],"company_since":"1999-10-15","company_dissolved":"2006-03-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"691710","names":[{"lang":"en","v":"SILVATON LIMITED"},{"lang":"hk","v":"得弘有限公司"}],"company_since":"1999-10-15","company_dissolved":"2020-06-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"691597","names":[{"lang":"en","v":"PROFESSIONAL SPORTS DEVELOPMENT LIMITED"},{"lang":"hk","v":"體育發展有限公司"}],"company_since":"1999-10-15","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"691595","names":[{"lang":"en","v":"PUB CAPITAL LIMITED"}],"company_since":"1999-10-15","company_dissolved":"2004-12-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"691681","names":[{"lang":"en","v":"RAINBOW SHEEN LIMITED"},{"lang":"hk","v":"彩兆有限公司"}],"company_since":"1999-10-15","company_dissolved":"2019-07-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"691656","names":[{"lang":"en","v":"SYSTECH ON-LINE LIMITED"},{"lang":"hk","v":"盈創資訊科技有限公司"}],"company_since":"1999-10-15","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"691720","names":[{"lang":"en","v":"TEXTILE CREATION (HONG KONG) LIMITED"},{"lang":"hk","v":"明進紡(香港)有限公司"}],"company_since":"1999-10-15","company_dissolved":"2012-03-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"691577","names":[{"lang":"en","v":"TOP FAITH CONSULTANTS LIMITED"},{"lang":"hk","v":"高信顧問有限公司"}],"company_since":"1999-10-15","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"691517","names":[{"lang":"en","v":"RISE CAPITAL LIMITED (d2003-02-28)"},{"lang":"hk","v":"進資有限公司"}],"company_since":"1999-10-15","company_dissolved":"2003-02-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"691570","names":[{"lang":"en","v":"TOP SPREAD LIMITED (d2000-11-03)"},{"lang":"hk","v":"登盛有限公司"}],"company_since":"1999-10-15","company_dissolved":"2000-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"691523","names":[{"lang":"en","v":"TREASURE TRADE LIMITED (d2011-03-11)"},{"lang":"hk","v":"吉貿有限公司"}],"company_since":"1999-10-15","company_dissolved":"2011-03-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"691531","names":[{"lang":"en","v":"TRULY CORPORATION LIMITED (d2006-01-27)"},{"lang":"hk","v":"卓利行有限公司"}],"company_since":"1999-10-15","company_dissolved":"2006-01-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"691516","names":[{"lang":"en","v":"SILVER PARK LIMITED"},{"lang":"hk","v":"銀栢有限公司"}],"company_since":"1999-10-15","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"691606","names":[{"lang":"en","v":"VEEWET COMPANY LIMITED (d2006-03-24)"},{"lang":"hk","v":"浪人一族有限公司"}],"company_since":"1999-10-15","company_dissolved":"2006-03-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"691452","names":[{"lang":"en","v":"VIDEO &amp; ANIMATION COMPANY LIMITED"}],"company_since":"1999-10-15","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"691682","names":[{"lang":"en","v":"WEALTH LINE LIMITED (d2002-08-02)"},{"lang":"hk","v":"潤標有限公司"}],"company_since":"1999-10-15","company_dissolved":"2002-08-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"691596","names":[{"lang":"en","v":"WEIYU SHIPPING &amp; TRADING COMPANY LIMITED"},{"lang":"hk","v":"香港煒瑜船務貿易有限公司"}],"company_since":"1999-10-15","company_dissolved":"2006-03-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"691491","names":[{"lang":"en","v":"SOUTH CHINA MANAGEMENT LIMITED (d2004-03-12)"},{"lang":"hk","v":"南華管理有限公司"}],"company_since":"1999-10-15","company_dissolved":"2004-03-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"691522","names":[{"lang":"en","v":"WISDOM KIND LIMITED"},{"lang":"hk","v":"慧亨有限公司"}],"company_since":"1999-10-15","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"691546","names":[{"lang":"en","v":"SUN RISE (LAM'S) ENGINEERING LIMITED"},{"lang":"hk","v":"日昇(林氏)工程有限公司"}],"company_since":"1999-10-15","company_dissolved":"2011-04-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"691571","names":[{"lang":"en","v":"SUPERB BRIGHT LIMITED (d2006-02-24)"},{"lang":"hk","v":"敦煌有限公司"}],"company_since":"1999-10-15","company_dissolved":"2006-02-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"691468","names":[{"lang":"en","v":"WORLD-LINK (DOOR-2-DOOR) SERVICES LIMITED"}],"company_since":"1999-10-15","company_dissolved":"2002-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"691502","names":[{"lang":"en","v":"YAT KEUNG PRINTNG LIMITED"},{"lang":"hk","v":"日強印刷有限公司"}],"company_since":"1999-10-15","company_dissolved":"2003-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"691661","names":[{"lang":"en","v":"YELLOW FROG PRODUCTIONS LIMITED (d2006-03-24)"}],"company_since":"1999-10-15","company_dissolved":"2006-03-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"691686","names":[{"lang":"en","v":"ZHONGWEI MEDI-CHINA.COM LIMITED"},{"lang":"hk","v":"中緯醫藥科技有限公司"}],"company_since":"1999-10-15","company_dissolved":"2008-05-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"691568","names":[{"lang":"en","v":"TRIUMPH MASTER LIMITED (d2004-11-26)"},{"lang":"hk","v":"凱文有限公司"}],"company_since":"1999-10-15","company_dissolved":"2004-11-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"691427","names":[{"lang":"en","v":"TUBI P&amp;D SYSTEM LIMITED"}],"company_since":"1999-10-15","company_dissolved":"2008-09-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"691593","names":[{"lang":"en","v":"UFV LIMITED"},{"lang":"hk","v":"環球多媒體傳訊有限公司"}],"company_since":"1999-10-15","company_dissolved":"2016-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"691486","names":[{"lang":"en","v":"VIGOUR CREATION LIMITED"},{"lang":"hk","v":"偉高基業有限公司"}],"company_since":"1999-10-15","company_dissolved":"2003-03-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"691519","names":[{"lang":"en","v":"WETT LIMITED"}],"company_since":"1999-10-15","company_dissolved":"2018-01-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"691576","names":[{"lang":"en","v":"WINSMART CONSULTANTS LIMITED"},{"lang":"hk","v":"弘陞投資顧問有限公司"}],"company_since":"1999-10-15","company_dissolved":"2009-06-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"691439","names":[{"lang":"en","v":"WORLD GLORY (H.K.) LIMITED (d2007-08-24)"},{"lang":"hk","v":"匯協(香港)有限公司"}],"company_since":"1999-10-15","company_dissolved":"2007-08-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"691565","names":[{"lang":"en","v":"KA SHUN LIMITED (d2006-03-24)"},{"lang":"hk","v":"嘉信行有限公司"}],"company_since":"1999-10-15","company_dissolved":"2006-03-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"691657","names":[{"lang":"en","v":"WEBPLUS LIMITED (d2008-08-15)"}],"company_since":"1999-10-15","company_dissolved":"2008-08-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"691608","names":[{"lang":"en","v":"I SCAN RECORD MANAGEMENT LIMITED"},{"lang":"hk","v":"傲視科研有限公司"}],"company_since":"1999-10-15","company_dissolved":"2001-09-07","company_type_txt":"Private, ltd by shares"},
