{"tax_id":"819760","names":[{"lang":"en","v":"CHAMPION WELL HOLDINGS LIMITED"},{"lang":"hk","v":"冠威集團有限公司"}],"company_since":"2002-10-30","company_dissolved":"2004-11-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819545","names":[{"lang":"en","v":"CHARTER HOPE LIMITED"},{"lang":"hk","v":"捷恒有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819563","names":[{"lang":"en","v":"CHARTER OVERSEAS LIMITED"},{"lang":"hk","v":"香港晶海有限公司"}],"company_since":"2002-10-30","company_dissolved":"2015-10-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819595","names":[{"lang":"en","v":"CHARTER TREND LIMITED (d2010-07-23)"},{"lang":"hk","v":"祥多有限公司"}],"company_since":"2002-10-30","company_dissolved":"2010-07-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819736","names":[{"lang":"en","v":"CHEER LEADERS INTERNATIONAL LIMITED"},{"lang":"hk","v":"祥領國際有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819464","names":[{"lang":"en","v":"CHEERS ADVERTISING &amp; ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"毅采廣告工程有限公司"}],"company_since":"2002-10-30","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819643","names":[{"lang":"en","v":"CHINA EAST EDUCATION PUBLISHING PROPAGATION GROUP LIMITED"},{"lang":"hk","v":"中國東方教育出版傳播集團有限公司"}],"company_since":"2002-10-30","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819630","names":[{"lang":"en","v":"CHINA FU DA INTERNATIONAL FINANCIAL INVESTMENT GROUP LIMITED"},{"lang":"hk","v":"中國福達國際金融投資集團有限公司"}],"company_since":"2002-10-30","company_dissolved":"2005-04-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819602","names":[{"lang":"en","v":"CHINA HERBALIST-WESTERN MEDICINE CLINIC MEDICINE INSTITUTE LIMITED"},{"lang":"hk","v":"中華中西醫臨床醫學會有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819697","names":[{"lang":"en","v":"CHINA HONOUR INVESTMENT LIMITED"},{"lang":"hk","v":"盛信投資有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819793","names":[{"lang":"en","v":"CHINA INTELLIGENT HOLDINGS LIMITED"},{"lang":"hk","v":"華智集團有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819586","names":[{"lang":"en","v":"CHINA KINGDOM CONSULTANTS LIMITED (d2005-08-26)"},{"lang":"hk","v":"中僑顧問有限公司"}],"company_since":"2002-10-30","company_dissolved":"2005-08-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819728","names":[{"lang":"en","v":"CHINA TUNE TECHNOLOGIES LIMITED"},{"lang":"hk","v":"中聯通科技有限公司"}],"company_since":"2002-10-30","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819650","names":[{"lang":"en","v":"CHINA-STATE INTERNATIONAL (H.K.) LIMITED"},{"lang":"hk","v":"漢邦國際(香港)有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819590","names":[{"lang":"en","v":"CHINA UNION INTERNATIONAL HOLDINGS LIMITED (d2008-03-14)"},{"lang":"hk","v":"華源國際集團有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819626","names":[{"lang":"en","v":"CHINASTAR (FAR EAST) LIMITED"},{"lang":"hk","v":"中誠(遠東)有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819543","names":[{"lang":"en","v":"CHINAWHYS COMPANY LIMITED"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819577","names":[{"lang":"en","v":"CHIU WONG RESTAURANT LIMITED"},{"lang":"hk","v":"潮皇飲食集團有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819541","names":[{"lang":"en","v":"CHUN YIN COMPANY LIMITED"},{"lang":"hk","v":"真然有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819531","names":[{"lang":"en","v":"CITIHOPE LIMITED (d2006-09-08)"},{"lang":"hk","v":"合志有限公司"}],"company_since":"2002-10-30","company_dissolved":"2006-09-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819666","names":[{"lang":"en","v":"CLIPPER ENTERPRISE LIMITED"},{"lang":"hk","v":"飛剪企業有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819472","names":[{"lang":"en","v":"CHARISMA INVESTMENTS LIMITED"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819722","names":[{"lang":"en","v":"DATADOT TECHNOLOGY CHINA INCORPORATION LIMITED"},{"lang":"hk","v":"諾達科技(中國)有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-05-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819486","names":[{"lang":"en","v":"DATAINTERNET (HONG KONG) CO., LIMITED"},{"lang":"hk","v":"數碼國際(香港)有限公司"}],"company_since":"2002-10-30","company_dissolved":"2007-03-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819829","names":[{"lang":"en","v":"DEMING INT'L INVESTMENT GROUP LIMITED"},{"lang":"hk","v":"德明國際投資集團有限公司"}],"company_since":"2002-10-30","company_dissolved":"2006-09-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819635","names":[{"lang":"en","v":"DIFEI (HK) INT'L FASHION LIMITED"},{"lang":"hk","v":"蒂菲(香港)國際時裝有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819676","names":[{"lang":"en","v":"CHINA COMMERCE (HONG KONG) INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"中商(香港)國際有限公司"}],"company_since":"2002-10-30","company_dissolved":"2004-05-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819526","names":[{"lang":"en","v":"DOLPHIN CARTOON PUBLISHING (GROUP) LIMITED (THE)"},{"lang":"hk","v":"海豚卡通出版(集團)有限公司"}],"company_since":"2002-10-30","company_dissolved":"2009-07-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819797","names":[{"lang":"en","v":"DO-LITE TECHNOLOGY COMPANY LIMITED"},{"lang":"hk","v":"德萊科技股份有限公司"}],"company_since":"2002-10-30","company_dissolved":"2010-07-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819516","names":[{"lang":"en","v":"DRAGON HILL INTERNATIONAL INVESTMENT HOLDINGS LIMITED"},{"lang":"hk","v":"龍山國際投資集團有限公司"}],"company_since":"2002-10-30","company_dissolved":"2016-02-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819658","names":[{"lang":"en","v":"CHINA HEALTH INTERNATIONAL MEDICAL GROUP COMPANY LIMITED"},{"lang":"hk","v":"中健國際醫療集團有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819515","names":[{"lang":"en","v":"DRAGON HILL INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"龍山國際投資有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819758","names":[{"lang":"en","v":"DRAGON MEDIA DEVELOPMENT LIMITED"},{"lang":"hk","v":"龍貿發展有限公司"}],"company_since":"2002-10-30","company_dissolved":"2015-08-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819481","names":[{"lang":"en","v":"DREAM DIAMOND COMPANY LIMITED"},{"lang":"hk","v":"名鑽珠寶有限公司"}],"company_since":"2002-10-30","company_dissolved":"2009-06-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819591","names":[{"lang":"en","v":"EAGLE CAPITAL LIMITED (d2018-05-11)"},{"lang":"hk","v":"鷹嘉有限公司"}],"company_since":"2002-10-30","company_dissolved":"2018-05-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819821","names":[{"lang":"en","v":"EASCO INTERNATIONAL LIMITED"},{"lang":"hk","v":"旭高國際有限公司"}],"company_since":"2002-10-30","company_dissolved":"2009-08-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819573","names":[{"lang":"en","v":"EAST BASE LIMITED"},{"lang":"hk","v":"意博有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819631","names":[{"lang":"en","v":"EAST ASIA INTERNATIONAL CORPORATION LIMITED"},{"lang":"hk","v":"東雅國際集團有限公司"}],"company_since":"2002-10-30","company_dissolved":"2011-12-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819544","names":[{"lang":"en","v":"CHINAMART LIMITED"},{"lang":"hk","v":"捷貿有限公司"}],"company_since":"2002-10-30","company_dissolved":"2015-08-07","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819497","names":[{"lang":"en","v":"EAST WIN CATERING COMPANY LIMITED"},{"lang":"hk","v":"東成食品有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819654","names":[{"lang":"en","v":"EASTFAITH ENTERPRISES LIMITED"},{"lang":"hk","v":"怡信企業有限公司"}],"company_since":"2002-10-30","company_dissolved":"2020-03-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819594","names":[{"lang":"en","v":"EASTFUL LIMITED (d2005-07-08)"},{"lang":"hk","v":"悅勤有限公司"}],"company_since":"2002-10-30","company_dissolved":"2005-07-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819614","names":[{"lang":"en","v":"EASTWORLD HOLDINGS LIMITED"},{"lang":"hk","v":"東運集團有限公司"}],"company_since":"2002-10-30","company_dissolved":"2013-01-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819780","names":[{"lang":"en","v":"CLEANERS DEPOT LIMITED"},{"lang":"hk","v":"洗衣天地有限公司"}],"company_since":"2002-10-30","company_dissolved":"2005-11-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819450","names":[{"lang":"en","v":"ELTECH ENGINEERING CONSULTANT MANAGEMENT COMPANY LIMITED"},{"lang":"hk","v":"安泰工程諮詢管理有限公司"}],"company_since":"2002-10-30","company_dissolved":"2009-07-31","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819814","names":[{"lang":"en","v":"ESKIN INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"益膚國際有限公司"}],"company_since":"2002-10-30","company_dissolved":"2004-02-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819799","names":[{"lang":"en","v":"ETERNITY (ASIA) LIMITED (d2004-06-11)"},{"lang":"hk","v":"均恆(亞洲)有限公司"}],"company_since":"2002-10-30","company_dissolved":"2004-06-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819764","names":[{"lang":"en","v":"COFYLL DESIGN LIMITED"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819689","names":[{"lang":"en","v":"EUROMAX CORPORATION LIMITED"},{"lang":"hk","v":"歐美行有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819835","names":[{"lang":"en","v":"EVER MASTER INTERNATIONAL GROUP (HONG KONG) CO., LIMITED"},{"lang":"hk","v":"雄越國際集團(香港)有限公司"}],"company_since":"2002-10-30","company_dissolved":"2018-07-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819473","names":[{"lang":"en","v":"CULHK SERVICES CORPORATION, LIMITED"},{"lang":"hk","v":"新華投資集團理財有限公司"}],"company_since":"2002-10-30","company_dissolved":"2005-04-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819707","names":[{"lang":"en","v":"EVER REGENT HOLDINGS LIMITED (d2008-03-14)"},{"lang":"hk","v":"恒偉集團有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819716","names":[{"lang":"en","v":"EVEREACH TRADING LIMITED"},{"lang":"hk","v":"怡興貿易有限公司"}],"company_since":"2002-10-30","company_dissolved":"2015-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819779","names":[{"lang":"en","v":"EVERWINTEX LIMITED"},{"lang":"hk","v":"長豐中紡有限公司"}],"company_since":"2002-10-30","company_dissolved":"2014-01-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819538","names":[{"lang":"en","v":"EXOTIC SHADES INCORPORATED LIMITED"}],"company_since":"2002-10-30","company_dissolved":"2005-11-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819680","names":[{"lang":"en","v":"EXPRESS SOURCES ENTERPRISES LIMITED"},{"lang":"hk","v":"源迅企業有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819737","names":[{"lang":"en","v":"Fancy Rich Investment Holding Limited"},{"lang":"hk","v":"豐裕投資控股有限公司"}],"company_since":"2002-10-30","company_dissolved":"2010-08-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819678","names":[{"lang":"en","v":"FAR EAST RESEARCH INTERNATIONAL CO., LIMITED"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819571","names":[{"lang":"en","v":"FIRMAX LIMITED (d2006-09-08)"},{"lang":"hk","v":"輝懋有限公司"}],"company_since":"2002-10-30","company_dissolved":"2006-09-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819721","names":[{"lang":"en","v":"DRAGON JADE INTERNATIONAL LIMITED (d2005-05-20)"},{"lang":"hk","v":"龍浚國際有限公司"}],"company_since":"2002-10-30","company_dissolved":"2005-05-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819726","names":[{"lang":"en","v":"FORTUNE INTERNATIONAL PROPERTY MANAGEMENT CONSULTANTS LIMITED"},{"lang":"hk","v":"創富國際物業管理顧問有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819547","names":[{"lang":"en","v":"FORTUNE SENSE LIMITED (d2008-08-01)"},{"lang":"hk","v":"豐意有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-08-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819475","names":[{"lang":"en","v":"E'S MART ELECTRONIC APPLIANCES TRADING CO. LIMITED"},{"lang":"hk","v":"嘜價易電器貿易有限公司"}],"company_since":"2002-10-30","company_dissolved":"2005-10-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819633","names":[{"lang":"en","v":"FRANCE MOTILLITE (HK) INT'L DRESS LIMITED"},{"lang":"hk","v":"法國莫萊特(香港)國際服飾有限公司"}],"company_since":"2002-10-30","company_dissolved":"2015-08-07","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819778","names":[{"lang":"en","v":"FRANCE SHENGBAILUN HK (INT'L) APPAREL CO., LIMITED"},{"lang":"hk","v":"法國聖百倫香港(國際)服飾有限公司"}],"company_since":"2002-10-30","company_dissolved":"2010-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819549","names":[{"lang":"en","v":"EAST MART LIMITED"},{"lang":"hk","v":"祐明有限公司"}],"company_since":"2002-10-30","company_dissolved":"2007-02-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819510","names":[{"lang":"en","v":"FRANCE V.E.DELURE GARMENT (HK) DEVELOPMENT LIMITED"},{"lang":"hk","v":"法國迪萊服飾(香港)發展有限公司"}],"company_since":"2002-10-30","company_dissolved":"2009-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819739","names":[{"lang":"en","v":"FUTEBOL DE SALAO LIMITED"}],"company_since":"2002-10-30","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819592","names":[{"lang":"en","v":"EAST VANTAGE LIMITED"},{"lang":"hk","v":"誼滙有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819695","names":[{"lang":"en","v":"GAIN FORD (ASIA) LIMITED"},{"lang":"hk","v":"興盛(亞洲)有限公司"}],"company_since":"2002-10-30","company_dissolved":"2005-09-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819667","names":[{"lang":"en","v":"GO CLEAN SERVICES LIMITED (d2010-04-01)"},{"lang":"hk","v":"高見服務有限公司"}],"company_since":"2002-10-30","company_dissolved":"2010-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819819","names":[{"lang":"en","v":"GLOBALAND LIMITED"},{"lang":"hk","v":"彩南有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819787","names":[{"lang":"en","v":"GLORYWING INDUSTRIAL LIMITED"},{"lang":"hk","v":"向榮實業有限公司"}],"company_since":"2002-10-30","company_dissolved":"2006-01-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819620","names":[{"lang":"en","v":"GENWISE LIMITED (d2004-08-13)"},{"lang":"hk","v":"錦宏有限公司"}],"company_since":"2002-10-30","company_dissolved":"2004-08-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819506","names":[{"lang":"en","v":"GLOBAL-GATE (HOLDING) INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"高寶環球(集團)有限公司"}],"company_since":"2002-10-30","company_dissolved":"2011-07-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819462","names":[{"lang":"en","v":"GLOBAL PROFIT MOUNTAIN COMPANY LIMITED"},{"lang":"hk","v":"環球山盈有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-06-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819583","names":[{"lang":"en","v":"GOLD UNITED (HONG KONG) LIMITED"},{"lang":"hk","v":"高源(香港)有限公司"}],"company_since":"2002-10-30","company_dissolved":"2018-05-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819636","names":[{"lang":"en","v":"GIANT SUCCESS SHOE CO., LIMITED"},{"lang":"hk","v":"巨成鞋業有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819817","names":[{"lang":"en","v":"GLOBAL WIDE INTERNATIONAL LIMITED"},{"lang":"hk","v":"華英國際有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"819502","names":[{"lang":"en","v":"CONQUEROR GROUP HONG KONG LIMITED"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819473","names":[{"lang":"en","v":"CULHK SERVICES CORPORATION, LIMITED"},{"lang":"hk","v":"新華投資集團理財有限公司"}],"company_since":"2002-10-30","company_dissolved":"2005-04-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819590","names":[{"lang":"en","v":"CHINA UNION INTERNATIONAL HOLDINGS LIMITED (d2008-03-14)"},{"lang":"hk","v":"華源國際集團有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819643","names":[{"lang":"en","v":"CHINA EAST EDUCATION PUBLISHING PROPAGATION GROUP LIMITED"},{"lang":"hk","v":"中國東方教育出版傳播集團有限公司"}],"company_since":"2002-10-30","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819650","names":[{"lang":"en","v":"CHINA-STATE INTERNATIONAL (H.K.) LIMITED"},{"lang":"hk","v":"漢邦國際(香港)有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819637","names":[{"lang":"en","v":"DEA CORPORATION LIMITED"},{"lang":"hk","v":"原動力(香港)有限公司"}],"company_since":"2002-10-30","company_dissolved":"2006-11-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819829","names":[{"lang":"en","v":"DEMING INT'L INVESTMENT GROUP LIMITED"},{"lang":"hk","v":"德明國際投資集團有限公司"}],"company_since":"2002-10-30","company_dissolved":"2006-09-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819635","names":[{"lang":"en","v":"DIFEI (HK) INT'L FASHION LIMITED"},{"lang":"hk","v":"蒂菲(香港)國際時裝有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819797","names":[{"lang":"en","v":"DO-LITE TECHNOLOGY COMPANY LIMITED"},{"lang":"hk","v":"德萊科技股份有限公司"}],"company_since":"2002-10-30","company_dissolved":"2010-07-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819626","names":[{"lang":"en","v":"CHINASTAR (FAR EAST) LIMITED"},{"lang":"hk","v":"中誠(遠東)有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819516","names":[{"lang":"en","v":"DRAGON HILL INTERNATIONAL INVESTMENT HOLDINGS LIMITED"},{"lang":"hk","v":"龍山國際投資集團有限公司"}],"company_since":"2002-10-30","company_dissolved":"2016-02-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819543","names":[{"lang":"en","v":"CHINAWHYS COMPANY LIMITED"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819758","names":[{"lang":"en","v":"DRAGON MEDIA DEVELOPMENT LIMITED"},{"lang":"hk","v":"龍貿發展有限公司"}],"company_since":"2002-10-30","company_dissolved":"2015-08-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819475","names":[{"lang":"en","v":"E'S MART ELECTRONIC APPLIANCES TRADING CO. LIMITED"},{"lang":"hk","v":"嘜價易電器貿易有限公司"}],"company_since":"2002-10-30","company_dissolved":"2005-10-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819666","names":[{"lang":"en","v":"CLIPPER ENTERPRISE LIMITED"},{"lang":"hk","v":"飛剪企業有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819594","names":[{"lang":"en","v":"EASTFUL LIMITED (d2005-07-08)"},{"lang":"hk","v":"悅勤有限公司"}],"company_since":"2002-10-30","company_dissolved":"2005-07-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819573","names":[{"lang":"en","v":"EAST BASE LIMITED"},{"lang":"hk","v":"意博有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819764","names":[{"lang":"en","v":"COFYLL DESIGN LIMITED"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819450","names":[{"lang":"en","v":"ELTECH ENGINEERING CONSULTANT MANAGEMENT COMPANY LIMITED"},{"lang":"hk","v":"安泰工程諮詢管理有限公司"}],"company_since":"2002-10-30","company_dissolved":"2009-07-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819814","names":[{"lang":"en","v":"ESKIN INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"益膚國際有限公司"}],"company_since":"2002-10-30","company_dissolved":"2004-02-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819799","names":[{"lang":"en","v":"ETERNITY (ASIA) LIMITED (d2004-06-11)"},{"lang":"hk","v":"均恆(亞洲)有限公司"}],"company_since":"2002-10-30","company_dissolved":"2004-06-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819689","names":[{"lang":"en","v":"EUROMAX CORPORATION LIMITED"},{"lang":"hk","v":"歐美行有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819780","names":[{"lang":"en","v":"CLEANERS DEPOT LIMITED"},{"lang":"hk","v":"洗衣天地有限公司"}],"company_since":"2002-10-30","company_dissolved":"2005-11-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819707","names":[{"lang":"en","v":"EVER REGENT HOLDINGS LIMITED (d2008-03-14)"},{"lang":"hk","v":"恒偉集團有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819497","names":[{"lang":"en","v":"EAST WIN CATERING COMPANY LIMITED"},{"lang":"hk","v":"東成食品有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819716","names":[{"lang":"en","v":"EVEREACH TRADING LIMITED"},{"lang":"hk","v":"怡興貿易有限公司"}],"company_since":"2002-10-30","company_dissolved":"2015-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819515","names":[{"lang":"en","v":"DRAGON HILL INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"龍山國際投資有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819538","names":[{"lang":"en","v":"EXOTIC SHADES INCORPORATED LIMITED"}],"company_since":"2002-10-30","company_dissolved":"2005-11-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819721","names":[{"lang":"en","v":"DRAGON JADE INTERNATIONAL LIMITED (d2005-05-20)"},{"lang":"hk","v":"龍浚國際有限公司"}],"company_since":"2002-10-30","company_dissolved":"2005-05-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819680","names":[{"lang":"en","v":"EXPRESS SOURCES ENTERPRISES LIMITED"},{"lang":"hk","v":"源迅企業有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819765","names":[{"lang":"en","v":"FAI LEE CONSTRUCTION (H.K.) LIMITED"},{"lang":"hk","v":"快利建築(香港)有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819737","names":[{"lang":"en","v":"Fancy Rich Investment Holding Limited"},{"lang":"hk","v":"豐裕投資控股有限公司"}],"company_since":"2002-10-30","company_dissolved":"2010-08-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819595","names":[{"lang":"en","v":"CHARTER TREND LIMITED (d2010-07-23)"},{"lang":"hk","v":"祥多有限公司"}],"company_since":"2002-10-30","company_dissolved":"2010-07-23","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819678","names":[{"lang":"en","v":"FAR EAST RESEARCH INTERNATIONAL CO., LIMITED"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819614","names":[{"lang":"en","v":"EASTWORLD HOLDINGS LIMITED"},{"lang":"hk","v":"東運集團有限公司"}],"company_since":"2002-10-30","company_dissolved":"2013-01-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819801","names":[{"lang":"en","v":"FIRST-BRIGHT WINTECH CO., LIMITED"},{"lang":"hk","v":"勝技有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819526","names":[{"lang":"en","v":"DOLPHIN CARTOON PUBLISHING (GROUP) LIMITED (THE)"},{"lang":"hk","v":"海豚卡通出版(集團)有限公司"}],"company_since":"2002-10-30","company_dissolved":"2009-07-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819631","names":[{"lang":"en","v":"EAST ASIA INTERNATIONAL CORPORATION LIMITED"},{"lang":"hk","v":"東雅國際集團有限公司"}],"company_since":"2002-10-30","company_dissolved":"2011-12-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819547","names":[{"lang":"en","v":"FORTUNE SENSE LIMITED (d2008-08-01)"},{"lang":"hk","v":"豐意有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-08-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819549","names":[{"lang":"en","v":"EAST MART LIMITED"},{"lang":"hk","v":"祐明有限公司"}],"company_since":"2002-10-30","company_dissolved":"2007-02-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819517","names":[{"lang":"en","v":"FRANCE GOLD FOX ASIA INTERNATIONAL FASHION DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"法國金狐狸亞洲國際服飾發展有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819633","names":[{"lang":"en","v":"FRANCE MOTILLITE (HK) INT'L DRESS LIMITED"},{"lang":"hk","v":"法國莫萊特(香港)國際服飾有限公司"}],"company_since":"2002-10-30","company_dissolved":"2015-08-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819778","names":[{"lang":"en","v":"FRANCE SHENGBAILUN HK (INT'L) APPAREL CO., LIMITED"},{"lang":"hk","v":"法國聖百倫香港(國際)服飾有限公司"}],"company_since":"2002-10-30","company_dissolved":"2010-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819484","names":[{"lang":"en","v":"FEEDERS COMPANY LIMITED"},{"lang":"hk","v":"阜德有限公司"}],"company_since":"2002-10-30","company_dissolved":"2009-07-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819510","names":[{"lang":"en","v":"FRANCE V.E.DELURE GARMENT (HK) DEVELOPMENT LIMITED"},{"lang":"hk","v":"法國迪萊服飾(香港)發展有限公司"}],"company_since":"2002-10-30","company_dissolved":"2009-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"819592","names":[{"lang":"en","v":"EAST VANTAGE LIMITED"},{"lang":"hk","v":"誼滙有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819654","names":[{"lang":"en","v":"EASTFAITH ENTERPRISES LIMITED"},{"lang":"hk","v":"怡信企業有限公司"}],"company_since":"2002-10-30","company_dissolved":"2020-03-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819739","names":[{"lang":"en","v":"FUTEBOL DE SALAO LIMITED"}],"company_since":"2002-10-30","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819448","names":[{"lang":"en","v":"GADGETS COMPANY LIMITED"},{"lang":"hk","v":"數碼設計有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-10-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819695","names":[{"lang":"en","v":"GAIN FORD (ASIA) LIMITED"},{"lang":"hk","v":"興盛(亞洲)有限公司"}],"company_since":"2002-10-30","company_dissolved":"2005-09-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819458","names":[{"lang":"en","v":"GEM BRIGHT TRADING LIMITED"},{"lang":"hk","v":"錦燁貿易有限公司"}],"company_since":"2002-10-30","company_dissolved":"2009-11-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819620","names":[{"lang":"en","v":"GENWISE LIMITED (d2004-08-13)"},{"lang":"hk","v":"錦宏有限公司"}],"company_since":"2002-10-30","company_dissolved":"2004-08-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819636","names":[{"lang":"en","v":"GIANT SUCCESS SHOE CO., LIMITED"},{"lang":"hk","v":"巨成鞋業有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819704","names":[{"lang":"en","v":"GLOBAL CHINESE DEVELOPMENT LIMITED"},{"lang":"hk","v":"中暉發展有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819835","names":[{"lang":"en","v":"EVER MASTER INTERNATIONAL GROUP (HONG KONG) CO., LIMITED"},{"lang":"hk","v":"雄越國際集團(香港)有限公司"}],"company_since":"2002-10-30","company_dissolved":"2018-07-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819718","names":[{"lang":"en","v":"GLOBAL DELUXE INVESTMENT LIMITED"},{"lang":"hk","v":"豪逸投資有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-10-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819462","names":[{"lang":"en","v":"GLOBAL PROFIT MOUNTAIN COMPANY LIMITED"},{"lang":"hk","v":"環球山盈有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-06-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819817","names":[{"lang":"en","v":"GLOBAL WIDE INTERNATIONAL LIMITED"},{"lang":"hk","v":"華英國際有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819514","names":[{"lang":"en","v":"EVERGAIN INTERNATIONAL INVESTMENT HOLDINGS LIMITED"},{"lang":"hk","v":"永利國際投資集團有限公司"}],"company_since":"2002-10-30","company_dissolved":"2006-10-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819506","names":[{"lang":"en","v":"GLOBAL-GATE (HOLDING) INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"高寶環球(集團)有限公司"}],"company_since":"2002-10-30","company_dissolved":"2011-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819779","names":[{"lang":"en","v":"EVERWINTEX LIMITED"},{"lang":"hk","v":"長豐中紡有限公司"}],"company_since":"2002-10-30","company_dissolved":"2014-01-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819819","names":[{"lang":"en","v":"GLOBALAND LIMITED"},{"lang":"hk","v":"彩南有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819787","names":[{"lang":"en","v":"GLORYWING INDUSTRIAL LIMITED"},{"lang":"hk","v":"向榮實業有限公司"}],"company_since":"2002-10-30","company_dissolved":"2006-01-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819570","names":[{"lang":"en","v":"GOLD VIEW LIMITED (d2010-01-08)"},{"lang":"hk","v":"鴻惠有限公司"}],"company_since":"2002-10-30","company_dissolved":"2010-01-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819727","names":[{"lang":"en","v":"GOLDEN ELEGANT CORPORATION LIMITED"},{"lang":"hk","v":"金怡發有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819731","names":[{"lang":"en","v":"GOLDEN FLAMINGO TRADING LIMITED"},{"lang":"hk","v":"金暉貿易有限公司"}],"company_since":"2002-10-30","company_dissolved":"2004-07-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819571","names":[{"lang":"en","v":"FIRMAX LIMITED (d2006-09-08)"},{"lang":"hk","v":"輝懋有限公司"}],"company_since":"2002-10-30","company_dissolved":"2006-09-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819826","names":[{"lang":"en","v":"GOLDEN NEON INTERNATIONAL LIMITED"},{"lang":"hk","v":"利豪霓虹燈國際有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819747","names":[{"lang":"en","v":"FORTUNE CENTURY INVESTMENT LIMITED (d2009-03-20)"},{"lang":"hk","v":"安順投資有限公司"}],"company_since":"2002-10-30","company_dissolved":"2009-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819501","names":[{"lang":"en","v":"GOLDEN-KEY TRADING LIMITED"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819726","names":[{"lang":"en","v":"FORTUNE INTERNATIONAL PROPERTY MANAGEMENT CONSULTANTS LIMITED"},{"lang":"hk","v":"創富國際物業管理顧問有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819688","names":[{"lang":"en","v":"FORTUNE SUCCESS CORPORATION LIMITED"},{"lang":"hk","v":"祥成有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819713","names":[{"lang":"en","v":"GOOD DECISION TECHNOLOGIES LIMITED"},{"lang":"hk","v":"志成科技有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819496","names":[{"lang":"en","v":"GOOD ERA INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"美時國際投資有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819667","names":[{"lang":"en","v":"GO CLEAN SERVICES LIMITED (d2010-04-01)"},{"lang":"hk","v":"高見服務有限公司"}],"company_since":"2002-10-30","company_dissolved":"2010-04-01","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819655","names":[{"lang":"en","v":"GOOD JOB INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"澤木國際事業有限公司"}],"company_since":"2002-10-30","company_dissolved":"2011-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819805","names":[{"lang":"en","v":"GOODWOOD HILL LIMITED"}],"company_since":"2002-10-30","company_dissolved":"2015-10-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"819674","names":[{"lang":"en","v":"HAIER GROUP (HONG KONG) CO., LIMITED (d2008-03-14)"},{"lang":"hk","v":"海爾集團(香港)有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819459","names":[{"lang":"en","v":"GRAND DARING (SHARE) COMPANY LIMITED"},{"lang":"hk","v":"均達股份有限公司"}],"company_since":"2002-10-30","company_dissolved":"2004-10-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819611","names":[{"lang":"en","v":"HANFA INDUSTRIAL LIMITED"},{"lang":"hk","v":"晗發實業有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-09-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819525","names":[{"lang":"en","v":"HANG SHING (INTERNATIONAL) TRANSPORTATION LIMITED"},{"lang":"hk","v":"恒盛(國際)貨運有限公司"}],"company_since":"2002-10-30","company_dissolved":"2004-10-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819791","names":[{"lang":"en","v":"HAPPY DATA LIMITED (d2008-03-14)"},{"lang":"hk","v":"訊濠有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819507","names":[{"lang":"en","v":"GRAND HARVEST CREATIVE COMPANY LIMITED"},{"lang":"hk","v":"滴濤創作有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-08-01","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819769","names":[{"lang":"en","v":"HARVEST SMART BECKY AGRIC-BIO TECHNOLOGY LIMITED"},{"lang":"hk","v":"豐智碧全農業生物科技有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819831","names":[{"lang":"en","v":"HEADLINE (WORLDWIDE) PUBLIC RELATIONS CO., LIMITED"},{"lang":"hk","v":"浩朗(國際)公關有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819498","names":[{"lang":"en","v":"GRAND POWER CAR SERVICES LIMITED"},{"lang":"hk","v":"君馬汽車服務有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819732","names":[{"lang":"en","v":"HIMSON INVESTMENT LIMITED"},{"lang":"hk","v":"興誠投資有限公司"}],"company_since":"2002-10-30","company_dissolved":"2019-09-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819550","names":[{"lang":"en","v":"HK GLOBAL LIMITED"},{"lang":"hk","v":"香港有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819634","names":[{"lang":"en","v":"HK XINGLIANCHENG INDUSTRIAL LIMITED"},{"lang":"hk","v":"香港興蓮成實業有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819564","names":[{"lang":"en","v":"GREAT CHANNEL LIMITED (d2017-09-08)"},{"lang":"hk","v":"鉅才有限公司"}],"company_since":"2002-10-30","company_dissolved":"2017-09-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819823","names":[{"lang":"en","v":"HONEST BUSINESS INDUSTRIAL LIMITED"},{"lang":"hk","v":"信通實業有限公司"}],"company_since":"2002-10-30","company_dissolved":"2009-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819745","names":[{"lang":"en","v":"GREAT PROMOTION DEVELOPMENT LIMITED"},{"lang":"hk","v":"晉升發展有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819684","names":[{"lang":"en","v":"HONG KONG BRIGHTER COMPANY LIMITED"},{"lang":"hk","v":"香港光大有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819783","names":[{"lang":"en","v":"HONG KONG FUTSAL ASSOCIATION LIMITED (THE)"}],"company_since":"2002-10-30","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819460","names":[{"lang":"en","v":"HONG KONG HENG JI KING WHALE CULTIVATION HOLDING DEVELOPMENT CO., LIMITED"},{"lang":"hk","v":"香港恒基皇鯨養殖股份發展有限公司"}],"company_since":"2002-10-30","company_dissolved":"2004-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819686","names":[{"lang":"en","v":"GUARDIAN CORPORATION LIMITED (d2009-03-20)"},{"lang":"hk","v":"嘉晉有限公司"}],"company_since":"2002-10-30","company_dissolved":"2009-03-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819682","names":[{"lang":"en","v":"HONG KONG KAI YING INTERNATIONAL LIMITED"},{"lang":"hk","v":"香港凱英國際有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819642","names":[{"lang":"en","v":"HONG KONG LU XI ER YI HAO (ENGLAND) OIL LIMITED"},{"lang":"hk","v":"香港路希爾億豪(英國)油業有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819807","names":[{"lang":"en","v":"H.K. HAO LI LAI (INTERNATIONAL) FASHION TRADING LIMITED"},{"lang":"hk","v":"香港好利來(國際)鞋服商貿有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819520","names":[{"lang":"en","v":"HONG KONG LUNG SING OPTICAL COMPANY LIMITED"},{"lang":"hk","v":"香港龍升光學有限公司"}],"company_since":"2002-10-30","company_dissolved":"2010-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819647","names":[{"lang":"en","v":"HONG KONG SILBO ENTERPRISE COMPANY LIMITED"},{"lang":"hk","v":"香港賽寶企業有限公司"}],"company_since":"2002-10-30","company_dissolved":"2011-04-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819827","names":[{"lang":"en","v":"H.K. HONGDA FASHION LIMITED"},{"lang":"hk","v":"香港宏達服飾有限公司"}],"company_since":"2002-10-30","company_dissolved":"2005-03-11","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819534","names":[{"lang":"en","v":"HONG KONG SMARTWAY INDUSTRIAL CO., LIMITED"},{"lang":"hk","v":"香港速馬威實業有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819605","names":[{"lang":"en","v":"HONG KONG TAIHE MACHINERY CO., LIMITED"},{"lang":"hk","v":"香港泰和机械有限公司"}],"company_since":"2002-10-30","company_dissolved":"2020-11-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819775","names":[{"lang":"en","v":"HONG KONG YA SHI JU FURNITURE GROUP LIMITED"},{"lang":"hk","v":"香港雅世居家具集團有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819833","names":[{"lang":"en","v":"HONG KONG YANHUANG GROUP LIMITED"},{"lang":"hk","v":"香港炎黃集團有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819712","names":[{"lang":"en","v":"HONG KONG ZHONGQIAO DEVELOPMENT LIMITED"},{"lang":"hk","v":"香港中僑發展有限公司"}],"company_since":"2002-10-30","company_dissolved":"2007-06-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819509","names":[{"lang":"en","v":"HAPPY HOLIDAY INTERNATIONAL TOUR LIMITED"},{"lang":"hk","v":"歡欣假期國際旅遊有限公司"}],"company_since":"2002-10-30","company_dissolved":"2019-03-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819734","names":[{"lang":"en","v":"HONGKONG PACIFIC MILLION ASIA LIMITED"},{"lang":"hk","v":"香港富萬亞洲有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819629","names":[{"lang":"en","v":"HONGKONG SHENGWEISHI FURNITURE LIMITED"},{"lang":"hk","v":"香港聖維詩家具有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819706","names":[{"lang":"en","v":"HONOUR SUCCESS (HONG KONG) LIMITED"},{"lang":"hk","v":"信盛(香港)有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819664","names":[{"lang":"en","v":"ICRIS:0819664 (no English name)"},{"lang":"hk","v":"香港格納醫藥投資有限公司"}],"company_since":"2002-10-30","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"819477","names":[{"lang":"en","v":"HING MING HANDBAG MANUFACTURING CO., LIMITED"},{"lang":"hk","v":"慶明手袋有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819661","names":[{"lang":"en","v":"INTERNATIONAL ESTOCK-TRADING SERVICES LIMITED"},{"lang":"hk","v":"國際商貿通服務有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819838","names":[{"lang":"en","v":"IPG Mediabrands (HK) Limited"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819476","names":[{"lang":"en","v":"HOI KEE ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"海記國際工程有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819766","names":[{"lang":"en","v":"ITALY AOYIMILAN INT'L ELECTRICAL APPLIANCES GROUP (HK) LIMITED"},{"lang":"hk","v":"意大利澳意米蘭國際電氣集團(香港)有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819794","names":[{"lang":"en","v":"ITALY S.AFRICAN STAR JEWELLERY INT'L (HK) LIMITED"},{"lang":"hk","v":"意大利南非之星鑽飾珠寶國際(香港)有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819772","names":[{"lang":"en","v":"JAMGON KONGTRUL FOUNDATION LIMITED"}],"company_since":"2002-10-30","company_dissolved":"2019-12-13","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"819580","names":[{"lang":"en","v":"JANSTAR LIMITED"},{"lang":"hk","v":"致昇有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819677","names":[{"lang":"en","v":"JCL MULTI-SOURCES LIMITED"}],"company_since":"2002-10-30","company_dissolved":"2008-11-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819519","names":[{"lang":"en","v":"HONG KONG HATEMAN FASHION INTERNATIONAL GROUP SHARE COMPANY LIMITED"},{"lang":"hk","v":"香港哈特曼服飾國際集團股份有限公司"}],"company_since":"2002-10-30","company_dissolved":"2009-03-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819691","names":[{"lang":"en","v":"JEANWAY CORPORATION LIMITED"},{"lang":"hk","v":"俊慧有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819639","names":[{"lang":"en","v":"JENESIS CONSULTING LIMITED"}],"company_since":"2002-10-30","company_dissolved":"2019-10-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819714","names":[{"lang":"en","v":"JETWIN TOYS (HONG KONG &amp; CHINA) LIMITED"},{"lang":"hk","v":"捷穎玩具製品有限公司"}],"company_since":"2002-10-30","company_dissolved":"2004-08-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819582","names":[{"lang":"en","v":"JI XIANG JEWELLERY LIMITED"},{"lang":"hk","v":"吉祥珠寶有限公司"}],"company_since":"2002-10-30","company_dissolved":"2019-03-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819518","names":[{"lang":"en","v":"HONG KONG KING WAI (INTERNATIONAL) FASHION DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"香港勁威(國際)服飾發展有限公司"}],"company_since":"2002-10-30","company_dissolved":"2009-03-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819808","names":[{"lang":"en","v":"JIE LONG MEDICAL SERVICES LIMITED"}],"company_since":"2002-10-30","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819828","names":[{"lang":"en","v":"JM TECHNOLOGY (H.K.) LIMITED"},{"lang":"hk","v":"九茂科技(香港)有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819702","names":[{"lang":"en","v":"JOIN ROYAL LIMITED"},{"lang":"hk","v":"新聯有限公司"}],"company_since":"2002-10-30","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819795","names":[{"lang":"en","v":"JUMP EVENTS LIMITED"},{"lang":"hk","v":"飛躍市場推廣有限公司"}],"company_since":"2002-10-30","company_dissolved":"2005-11-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819609","names":[{"lang":"en","v":"KEEN OCEAN GROUP LIMITED"},{"lang":"hk","v":"浩海集團有限公司"}],"company_since":"2002-10-30","company_dissolved":"2006-03-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819480","names":[{"lang":"en","v":"HONGKONG 3H INVESTMENT COMPANY LIMITED"},{"lang":"hk","v":"香港榮和誠投資有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819522","names":[{"lang":"en","v":"KOMAK ELECTRICAL COMPANY LIMITED"},{"lang":"hk","v":"高瑪德電業有限公司"}],"company_since":"2002-10-30","company_dissolved":"2011-08-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819840","names":[{"lang":"en","v":"KOON WING ETRADE LIMITED"},{"lang":"hk","v":"群榮網上貿易有限公司"}],"company_since":"2002-10-30","company_dissolved":"2011-10-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819776","names":[{"lang":"en","v":"IG ASIA LIMITED"}],"company_since":"2002-10-30","company_dissolved":"2004-05-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819542","names":[{"lang":"en","v":"KUN HUNG GLASS AND MIRROR PRODUCTS LIMITED"},{"lang":"hk","v":"冠鴻玻璃鏡業有限公司"}],"company_since":"2002-10-30","company_dissolved":"2006-08-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819447","names":[{"lang":"en","v":"IMMANUEL MEDIA GROUP LIMITED"}],"company_since":"2002-10-30","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819530","names":[{"lang":"en","v":"L &amp; N CONSULTANT DEVELOPMENT LIMITED"},{"lang":"hk","v":"利安工程顧問發展有限公司"}],"company_since":"2002-10-30","company_dissolved":"2009-05-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819768","names":[{"lang":"en","v":"INTERNATIONAL NOBLE YACHT MEETING CLUB LIMITED"},{"lang":"hk","v":"國際貴族遊艇會俱樂部有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819836","names":[{"lang":"en","v":"INTINENT INTERNATIONAL LIMITED"},{"lang":"hk","v":"業騰國際有限公司"}],"company_since":"2002-10-30","company_dissolved":"2020-11-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819773","names":[{"lang":"en","v":"LEGACY ASSOCIATION LIMITED"},{"lang":"hk","v":"里程同學會有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"819730","names":[{"lang":"en","v":"LEGEND VANTAGE HOLDINGS LIMITED (d2005-03-18)"},{"lang":"hk","v":"利駿集團有限公司"}],"company_since":"2002-10-30","company_dissolved":"2005-03-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819701","names":[{"lang":"en","v":"LINK RICHEST LIMITED"},{"lang":"hk","v":"隆業有限公司"}],"company_since":"2002-10-30","company_dissolved":"2006-08-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819754","names":[{"lang":"en","v":"LIONWAY TECHNOLOGIES LIMITED"},{"lang":"hk","v":"長威科技有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819813","names":[{"lang":"en","v":"LUEN WAI FISHERY COMPANY LIMITED (d2005-06-30)"},{"lang":"hk","v":"聯威漁業有限公司"}],"company_since":"2002-10-30","company_dissolved":"2005-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819649","names":[{"lang":"en","v":"LUNG CHING BIOLOGY TECHNOLOGY (HONG KONG) HOLDINGS LIMITED"},{"lang":"hk","v":"龍澄生物科技(香港)集團有限公司"}],"company_since":"2002-10-30","company_dissolved":"2006-03-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819648","names":[{"lang":"en","v":"LUNG SING BIOLOGY TECHNOLOGY (HONG KONG) HOLDINGS LIMITED"},{"lang":"hk","v":"龍升生物科技(香港)集團有限公司"}],"company_since":"2002-10-30","company_dissolved":"2004-04-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819781","names":[{"lang":"en","v":"MAINXIN ELECTRONICS LIMITED"},{"lang":"hk","v":"美欣電子有限公司"}],"company_since":"2002-10-30","company_dissolved":"2004-06-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819471","names":[{"lang":"en","v":"MASTER DYNAMIC LIMITED (d2011-02-18)"}],"company_since":"2002-10-30","company_dissolved":"2011-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819755","names":[{"lang":"en","v":"JUMBO PROFITS LIMITED"},{"lang":"hk","v":"讚利有限公司"}],"company_since":"2002-10-30","company_dissolved":"2014-10-31","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819698","names":[{"lang":"en","v":"MAX RICHEST LIMITED"},{"lang":"hk","v":"冠滙有限公司"}],"company_since":"2002-10-30","company_dissolved":"2013-01-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819625","names":[{"lang":"en","v":"MAX UNITED LIMITED (b2002-10-30)"},{"lang":"hk","v":"萬有有限公司"}],"company_since":"2002-10-30","company_dissolved":"2019-06-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819750","names":[{"lang":"en","v":"MAXIMA TRADING LIMITED (d2009-03-20)"},{"lang":"hk","v":"美亞貿易有限公司"}],"company_since":"2002-10-30","company_dissolved":"2009-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819715","names":[{"lang":"en","v":"MEC'S KNITTING FACTORY LIMITED"},{"lang":"hk","v":"萬基織造廠有限公司"}],"company_since":"2002-10-30","company_dissolved":"2006-01-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819672","names":[{"lang":"en","v":"KIM FAT LIMITED"},{"lang":"hk","v":"劍發有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-10-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819815","names":[{"lang":"en","v":"MEDICAL ANALYZERS ASIA LIMITED"}],"company_since":"2002-10-30","company_dissolved":"2011-11-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819600","names":[{"lang":"en","v":"KOWAY (FAR EAST) LIMITED"},{"lang":"hk","v":"港華(遠東)有限公司"}],"company_since":"2002-10-30","company_dissolved":"2012-08-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819744","names":[{"lang":"en","v":"MEGAWAY DEVELOPMENT LIMITED (d2008-03-14)"},{"lang":"hk","v":"銘威發展有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819467","names":[{"lang":"en","v":"METRO FIRST INVESTMENTS LIMITED"},{"lang":"hk","v":"博施投資有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"819789","names":[{"lang":"en","v":"LANFORD INTERNATIONAL LIMITED"},{"lang":"hk","v":"聯鋒國際有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819710","names":[{"lang":"en","v":"MILLION HOMEPAGE LIMITED"},{"lang":"hk","v":"萬鴻有限公司"}],"company_since":"2002-10-30","company_dissolved":"2005-03-11","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819572","names":[{"lang":"en","v":"MULTITEX LIMITED (d2006-07-10)"}],"company_since":"2002-10-30","company_dissolved":"2006-07-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819597","names":[{"lang":"en","v":"Linacare Asia Limited"},{"lang":"hk","v":"嘉蓮娜亞洲有限公司"}],"company_since":"2002-10-30","company_dissolved":"2020-09-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819798","names":[{"lang":"en","v":"MUPPETS PALACE PRODUCTION LIMITED"},{"lang":"hk","v":"布偶王朝製作有限公司"}],"company_since":"2002-10-30","company_dissolved":"2009-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819709","names":[{"lang":"en","v":"MUZI CATERING MANAGEMENT LIMITED"},{"lang":"hk","v":"木子飲食管理有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819500","names":[{"lang":"en","v":"LIVING WORKSHOP LIMITED"},{"lang":"hk","v":"生活工房有限公司"}],"company_since":"2002-10-30","company_dissolved":"2020-11-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819540","names":[{"lang":"en","v":"NEW ART PRODUCTS LIMITED"},{"lang":"hk","v":"盛日國際有限公司"}],"company_since":"2002-10-30","company_dissolved":"2013-08-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819593","names":[{"lang":"en","v":"NEW BRILLIANT LIMITED (d2008-03-28)"},{"lang":"hk","v":"良機有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819581","names":[{"lang":"en","v":"NEW CHALLENGE LIMITED (d2015-09-18)"},{"lang":"hk","v":"利志有限公司"}],"company_since":"2002-10-30","company_dissolved":"2015-09-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"819694","names":[{"lang":"en","v":"MACRO RICHEST LIMITED"},{"lang":"hk","v":"興浩有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819588","names":[{"lang":"en","v":"NEW HERO HOLDINGS LIMITED (d2009-11-20)"},{"lang":"hk","v":"新鴻集團有限公司"}],"company_since":"2002-10-30","company_dissolved":"2009-11-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819804","names":[{"lang":"en","v":"NEW HOMFORD HEALTHY FOOD INTERNATIONAL LIMITED"},{"lang":"hk","v":"新鴻福行保健食品國際有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819627","names":[{"lang":"en","v":"NEW SINO (FAR EAST) LIMITED"},{"lang":"hk","v":"新誠(遠東)有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819811","names":[{"lang":"en","v":"MARISA HOLDING CO., LIMITED"},{"lang":"hk","v":"瑪莉莎股份有限公司"}],"company_since":"2002-10-30","company_dissolved":"2010-03-26","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819566","names":[{"lang":"en","v":"NEW SKY LIMITED (d2013-01-04)"},{"lang":"hk","v":"龍生有限公司"}],"company_since":"2002-10-30","company_dissolved":"2013-01-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819613","names":[{"lang":"en","v":"NEW SYSTEM CONSULTANTS LIMITED (d2008-03-14)"},{"lang":"hk","v":"新誠顧問有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819622","names":[{"lang":"en","v":"NEW TECHNIC LIMITED (d2016-03-11)"},{"lang":"hk","v":"能捷有限公司"}],"company_since":"2002-10-30","company_dissolved":"2016-03-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819513","names":[{"lang":"en","v":"OCEAN BRIGHT INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"海暉國際投資有限公司"}],"company_since":"2002-10-30","company_dissolved":"2010-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819617","names":[{"lang":"en","v":"NEWAY INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"新榮國際集團有限公司"}],"company_since":"2002-10-30","company_dissolved":"2016-03-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819742","names":[{"lang":"en","v":"MEGAFORTUNE CORPORATION LIMITED"},{"lang":"hk","v":"雄發有限公司"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819528","names":[{"lang":"en","v":"OIS ADVANCED LIMITED"}],"company_since":"2002-10-30","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819660","names":[{"lang":"en","v":"OLIVOS (HONG KONG) LIMITED"},{"lang":"hk","v":"澳力富有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819711","names":[{"lang":"en","v":"MEI TIN SIN (H.K.) LIMITED"},{"lang":"hk","v":"美天善(香港)有限公司"}],"company_since":"2002-10-30","company_dissolved":"2006-02-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819478","names":[{"lang":"en","v":"PACIFIC FORMATION (HONG KONG) CO. LIMITED"},{"lang":"hk","v":"寶豐洋行(香港)有限公司"}],"company_since":"2002-10-30","company_dissolved":"2017-07-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819774","names":[{"lang":"en","v":"MIDAS INTERNATIONAL EDUCATION ORGANIZATION LIMITED"},{"lang":"hk","v":"明達國際教育機構有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819624","names":[{"lang":"en","v":"PACIFIC SONIC LIMITED (d2009-10-16)"},{"lang":"hk","v":"沛順有限公司"}],"company_since":"2002-10-30","company_dissolved":"2009-10-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819548","names":[{"lang":"en","v":"MILLION CHOICE LIMITED"},{"lang":"hk","v":"明創有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819770","names":[{"lang":"en","v":"PACIFIC TEAM ENTERPRISES LIMITED"},{"lang":"hk","v":"宏天企業有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"819527","names":[{"lang":"en","v":"PENTA-FIRE ENGINEERING LIMITED"},{"lang":"hk","v":"鵬達工程有限公司"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"819753","names":[{"lang":"en","v":"MRRM Publishing Limited"}],"company_since":"2002-10-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"819523","names":[{"lang":"en","v":"PERFECT PROFESSIONAL SERVICES COMPANY LIMITED"},{"lang":"hk","v":"完美專業服務有限公司"}],"company_since":"2002-10-30","company_dissolved":"2012-06-01","company_type_txt":"Private, ltd by shares"},
undefined,
