undefined,
undefined,
undefined,
undefined,
{"tax_id":"765808","names":[{"lang":"en","v":"CNA MUSIC LIMITED"}],"company_since":"2001-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"765792","names":[{"lang":"en","v":"GAO'S INTERNATIONAL ENTERPRISE LIMITED"},{"lang":"hk","v":"高氏國際企業有限公司"}],"company_since":"2001-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"765861","names":[{"lang":"en","v":"GOLD LINK TRAVEL COMPANY LIMITED"},{"lang":"hk","v":"金寧旅遊有限公司"}],"company_since":"2001-08-06","company_dissolved":"2008-08-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"765920","names":[{"lang":"en","v":"HENG PENG INVESTMENT CONSULTANT LIMITED"},{"lang":"hk","v":"亨鵬投資顧問有限公司"}],"company_since":"2001-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"765788","names":[{"lang":"en","v":"KWOK FUNG TEXTILE GROUP LIMITED"},{"lang":"hk","v":"國豐紡織集團有限公司"}],"company_since":"2001-08-06","company_dissolved":"2004-01-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"765836","names":[{"lang":"en","v":"MEX OFFICE SUPPLIES WHOLESALE LIMITED"},{"lang":"hk","v":"名仕文儀傢俱批發有限公司"}],"company_since":"2001-08-06","company_dissolved":"2008-11-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"765817","names":[{"lang":"en","v":"POPPY PET SUPPLIES WHOLESALES LIMITED"},{"lang":"hk","v":"百寶寵物用品批發有限公司"}],"company_since":"2001-08-06","company_dissolved":"2011-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"765785","names":[{"lang":"en","v":"KOREA MALACHE HOLDING (INTERNATIONAL) FASHION LIMITED"},{"lang":"hk","v":"韓國馬拉車集團(國際)服飾有限公司"}],"company_since":"2001-08-06","company_dissolved":"2006-12-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"765849","names":[{"lang":"en","v":"LAPIS CHINA LIMITED"},{"lang":"hk","v":"拉比思有限公司"}],"company_since":"2001-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"765919","names":[{"lang":"en","v":"MINERVA (HONG KONG) PUBLISHING LIMITED"},{"lang":"hk","v":"鳴鶴(香港)出版事業有限公司"}],"company_since":"2001-08-06","company_dissolved":"2008-08-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"765804","names":[{"lang":"en","v":"FOREST LUMBER INDUSTRIAL COMPANY LIMITED"},{"lang":"hk","v":"森霖木材實業有限公司"}],"company_since":"2001-08-06","company_dissolved":"2011-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"765811","names":[{"lang":"en","v":"NEW CHIN DYEING &amp; FINISHING FACTORY LIMITED"},{"lang":"hk","v":"新展染整廠有限公司"}],"company_since":"2001-08-06","company_dissolved":"2013-10-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"765893","names":[{"lang":"en","v":"ONWARD (INTERNATIONAL) EXHIBITION LIMITED"},{"lang":"hk","v":"康華(國際)展覽有限公司"}],"company_since":"2001-08-06","company_dissolved":"2008-07-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"765917","names":[{"lang":"en","v":"ITALY VALENTINO (H.K.) INT'L DEVELOPMENT LIMITED"},{"lang":"hk","v":"意大利華倫天奴(香港)國際發展有限公司"}],"company_since":"2001-08-06","company_dissolved":"2006-12-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"765855","names":[{"lang":"en","v":"ORIENTAL CENTURY DEVELOPMENT (HK) LIMITED"},{"lang":"hk","v":"新怡東發展(香港)有限公司"}],"company_since":"2001-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"765858","names":[{"lang":"en","v":"PACWOOD TRAVEL (INTERNATIONAL) LIMITED"},{"lang":"hk","v":"百滙旅遊(國際)有限公司"}],"company_since":"2001-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"765878","names":[{"lang":"en","v":"PLYMOUTH FAR EAST LIMITED"}],"company_since":"2001-08-06","company_dissolved":"2004-07-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"765817","names":[{"lang":"en","v":"POPPY PET SUPPLIES WHOLESALES LIMITED"},{"lang":"hk","v":"百寶寵物用品批發有限公司"}],"company_since":"2001-08-06","company_dissolved":"2011-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"765854","names":[{"lang":"en","v":"SAM-HAN SYNTHETIC (HONG KONG) COMPANY LIMITED"}],"company_since":"2001-08-06","company_dissolved":"2009-01-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"765898","names":[{"lang":"en","v":"STAR FORTUNE (HK) LIMITED (d2005-01-14)"},{"lang":"hk","v":"福星洋行(香港)有限公司"}],"company_since":"2001-08-06","company_dissolved":"2005-01-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"765884","names":[{"lang":"en","v":"STONE HEARTS COMPANY LIMITED"}],"company_since":"2001-08-06","company_dissolved":"2006-03-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"765815","names":[{"lang":"en","v":"SUN SPARK SHIPPING COMPANY LIMITED"},{"lang":"hk","v":"進輝船務有限公司"}],"company_since":"2001-08-06","company_dissolved":"2009-04-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"765903","names":[{"lang":"en","v":"T &amp; P ELECTRONICS CO. LIMITED"},{"lang":"hk","v":"天鵬盛電子有限公司"}],"company_since":"2001-08-06","company_dissolved":"2009-01-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"765896","names":[{"lang":"en","v":"SUNSPOT TECH LIMITED"},{"lang":"hk","v":"日美華國際有限公司"}],"company_since":"2001-08-06","company_dissolved":"2003-02-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"765843","names":[{"lang":"en","v":"T.C. LAWSON MARKETING LIMITED"},{"lang":"hk","v":"天時市場推廣有限公司"}],"company_since":"2001-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"765832","names":[{"lang":"en","v":"TEKALL TECHNOLOGY (HONGKONG) CO., LIMITED"},{"lang":"hk","v":"力合科技(香港)有限公司"}],"company_since":"2001-08-06","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"765842","names":[{"lang":"en","v":"T.C. LAWSON ASSETS MANAGEMENT LIMITED"},{"lang":"hk","v":"天時資產管理有限公司"}],"company_since":"2001-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"765844","names":[{"lang":"en","v":"J NET COMPANY LIMITED"}],"company_since":"2001-08-06","company_dissolved":"2015-07-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"765916","names":[{"lang":"en","v":"TILY LIMITED"}],"company_since":"2001-08-06","company_dissolved":"2006-08-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"765797","names":[{"lang":"en","v":"VSELL ENTERPRISE CO., LIMITED"},{"lang":"hk","v":"衡廣企業股份有限公司"}],"company_since":"2001-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"765867","names":[{"lang":"en","v":"ZTAMPZ LIMITED"}],"company_since":"2001-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"765812","names":[{"lang":"en","v":"L PLUS ENGINEERING LIMITED"},{"lang":"hk","v":"略柏工程有限公司"}],"company_since":"2001-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"765849","names":[{"lang":"en","v":"LAPIS CHINA LIMITED"},{"lang":"hk","v":"拉比思有限公司"}],"company_since":"2001-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"765900","names":[{"lang":"en","v":"LEGEND INTERNATIONAL TRADING LIMITED"},{"lang":"hk","v":"麗呈國際有限公司"}],"company_since":"2001-08-06","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"765819","names":[{"lang":"en","v":"LI ON ENTERPRISES (HONG KONG) LIMITED"},{"lang":"hk","v":"利安企業(香港)有限公司"}],"company_since":"2001-08-06","company_dissolved":"2008-01-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"765885","names":[{"lang":"en","v":"LLOYD COPTERS LEASING LIMITED"}],"company_since":"2001-08-06","company_dissolved":"2006-03-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"765874","names":[{"lang":"en","v":"MACOL ENGINEERING CO. LIMITED"},{"lang":"hk","v":"美固工程有限公司"}],"company_since":"2001-08-06","company_dissolved":"2008-01-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"765919","names":[{"lang":"en","v":"MINERVA (HONG KONG) PUBLISHING LIMITED"},{"lang":"hk","v":"鳴鶴(香港)出版事業有限公司"}],"company_since":"2001-08-06","company_dissolved":"2008-08-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"765826","names":[{"lang":"en","v":"MING RI TRADING (HK) LIMITED"},{"lang":"hk","v":"明日貿易(香港)有限公司"}],"company_since":"2001-08-06","company_dissolved":"2006-12-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"765803","names":[{"lang":"en","v":"NCU GROUP LIMITED"},{"lang":"hk","v":"恩喜友集團有限公司"}],"company_since":"2001-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"765810","names":[{"lang":"en","v":"ORACLE COMMUNICATIONS LIMITED (HK)"},{"lang":"hk","v":"天諭聯繫有限公司"}],"company_since":"2001-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"765825","names":[{"lang":"en","v":"PRIMEDECK LIMITED (d2006-12-22)"}],"company_since":"2001-08-06","company_dissolved":"2006-12-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"765908","names":[{"lang":"en","v":"R&amp;DT TECHNOLOGY COMPANY LIMITED"},{"lang":"hk","v":"蘭迪科技有限公司"}],"company_since":"2001-08-06","company_dissolved":"2004-07-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"765796","names":[{"lang":"en","v":"SUN ENGINEERING (TRADING) LIMITED"},{"lang":"hk","v":"嘉盛工程(貿易)有限公司"}],"company_since":"2001-08-06","company_dissolved":"2004-09-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"765853","names":[{"lang":"en","v":"SUN PACIFIC TRADING LIMITED"}],"company_since":"2001-08-06","company_dissolved":"2005-09-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"765906","names":[{"lang":"en","v":"WeiHsien International Holding Group Limited"},{"lang":"hk","v":"鍏鍹國際控股集團有限公司"}],"company_since":"2001-08-06","company_dissolved":"2020-06-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"765795","names":[{"lang":"en","v":"WHITE HORSE INTERNATIONAL LIMITED (d2006-12-22)"},{"lang":"hk","v":"白馬國際有限公司"}],"company_since":"2001-08-06","company_dissolved":"2006-12-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"765911","names":[{"lang":"en","v":"WONG CHIO COMPANY LIMITED"},{"lang":"hk","v":"旺洲股份有限公司"}],"company_since":"2001-08-06","company_dissolved":"2011-09-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"765859","names":[{"lang":"en","v":"WORLDWIDE SUN EXPO LIMITED"},{"lang":"hk","v":"環球新博覽有限公司"}],"company_since":"2001-08-06","company_dissolved":"2005-12-30","company_type_txt":"Private, ltd by shares"},
undefined,
