undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"795512","names":[{"lang":"en","v":"CHINA BOSUN HEALTH FOOD (H.K.) LIMITED"},{"lang":"hk","v":"中國寶桑園健康食品(香港)有限公司"}],"company_since":"2002-04-29","company_dissolved":"2007-09-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"795546","names":[{"lang":"en","v":"CONCERN MARKETING (HK) LIMITED"},{"lang":"hk","v":"永益發展(香港)有限公司"}],"company_since":"2002-04-29","company_dissolved":"2015-09-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"795449","names":[{"lang":"en","v":"EVER YIELD TRADING LIMITED"},{"lang":"hk","v":"源豐貿易有限公司"}],"company_since":"2002-04-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"795526","names":[{"lang":"en","v":"FAME ASCENT INTERNATIONAL LIMITED"},{"lang":"hk","v":"榮陞國際有限公司"}],"company_since":"2002-04-29","company_dissolved":"2015-11-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"795582","names":[{"lang":"en","v":"GLOBAL CONNECTIONS LIMITED (d2007-09-14)"}],"company_since":"2002-04-29","company_dissolved":"2007-09-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"795545","names":[{"lang":"en","v":"CORONET HONG KONG CO. LIMITED"},{"lang":"hk","v":"香港新凱運通有限公司"}],"company_since":"2002-04-29","company_dissolved":"2011-04-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"795516","names":[{"lang":"en","v":"HONG KONG AMFENOL COMPANY LIMITED"},{"lang":"hk","v":"香港安費諾有限公司"}],"company_since":"2002-04-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"795554","names":[{"lang":"en","v":"KAMWAY INVESTMENT LIMITED (d2008-10-17)"},{"lang":"hk","v":"錦威投資有限公司"}],"company_since":"2002-04-29","company_dissolved":"2008-10-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"795555","names":[{"lang":"en","v":"MANDA CAPITAL LIMITED"},{"lang":"hk","v":"文得有限公司"}],"company_since":"2002-04-29","company_dissolved":"2019-11-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"795518","names":[{"lang":"en","v":"KINSBERG (HONG KONG) LIMITED"},{"lang":"hk","v":"帝之堡(香港)有限公司"}],"company_since":"2002-04-29","company_dissolved":"2006-09-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"795604","names":[{"lang":"en","v":"HONGKONG TAIFO JEWELRY &amp; GOLD SHOP CO., LIMITED"},{"lang":"hk","v":"香港大福珠寶金行有限公司"}],"company_since":"2002-04-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"795601","names":[{"lang":"en","v":"NEW HENRY INTERNATIONAL LIMITED (d2008-10-17)"},{"lang":"hk","v":"美亨國際有限公司"}],"company_since":"2002-04-29","company_dissolved":"2008-10-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"795602","names":[{"lang":"en","v":"OCEAN EAGLE MOTORS COMPANY LIMITED"},{"lang":"hk","v":"海銳汽車有限公司"}],"company_since":"2002-04-29","company_dissolved":"2003-06-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"795600","names":[{"lang":"en","v":"ON WAH INTERNATIONAL LIMITED"},{"lang":"hk","v":"安華國際有限公司"}],"company_since":"2002-04-29","company_dissolved":"2007-09-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"795607","names":[{"lang":"en","v":"INTERNATIONAL ART &amp; CULTURE EDUCATIONAL ASSOCIATION LIMITED"},{"lang":"hk","v":"國際文化藝術教育協會有限公司"}],"company_since":"2002-04-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"795470","names":[{"lang":"en","v":"ROUND INDUSTRIAL (HK) COMPANY LIMITED"},{"lang":"hk","v":"容達實業(香港)有限公司"}],"company_since":"2002-04-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"795551","names":[{"lang":"en","v":"SINO ACE INTERNATIONAL LIMITED"},{"lang":"hk","v":"華潤國際有限公司"}],"company_since":"2002-04-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"795605","names":[{"lang":"en","v":"SHANGHAI STAR CONNECTION LIMITED"}],"company_since":"2002-04-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"795440","names":[{"lang":"en","v":"SUCCESS ON CONSULTANTS LIMITED"},{"lang":"hk","v":"順安顧問有限公司"}],"company_since":"2002-04-29","company_dissolved":"2006-05-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"795498","names":[{"lang":"en","v":"TALENT TRIMS &amp; PACKAGING (INT'L) LIMITED"},{"lang":"hk","v":"泰龍(國際)實業有限公司"}],"company_since":"2002-04-29","company_dissolved":"2004-02-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"795486","names":[{"lang":"en","v":"SOUNDMAX ELECTRONICS (HONG KONG) LIMITED"}],"company_since":"2002-04-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
