undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"762823","names":[{"lang":"en","v":"CNEEC GREEN TECHNOLOGY GROUP LIMITED"},{"lang":"hk","v":"上海中電綠科集團有限公司"}],"company_since":"2001-07-11","company_dissolved":"2005-06-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"762782","names":[{"lang":"en","v":"DRAGON GOAL INTERNATIONAL LIMITED (d2003-08-01)"},{"lang":"hk","v":"龍興國際有限公司"}],"company_since":"2001-07-11","company_dissolved":"2003-08-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"762792","names":[{"lang":"en","v":"EAST GLOBAL INVESTMENT LIMITED (d2013-09-27)"},{"lang":"hk","v":"邦豪投資有限公司"}],"company_since":"2001-07-11","company_dissolved":"2013-09-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"762891","names":[{"lang":"en","v":"EEM (HONG KONG) DEVELOPMENT LIMITED"},{"lang":"hk","v":"鱷爾瑪(香港)發展有限公司"}],"company_since":"2001-07-11","company_dissolved":"2006-11-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"763005","names":[{"lang":"en","v":"FULL SPRING (HK) LIMITED"},{"lang":"hk","v":"葆源盛得(香港)有限公司"}],"company_since":"2001-07-11","company_dissolved":"2012-09-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762934","names":[{"lang":"en","v":"GiftsPerfect4U Limited"},{"lang":"hk","v":"合意禮品有限公司"}],"company_since":"2001-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"762994","names":[{"lang":"en","v":"GREATER BEIJING EXPRESSWAYS HOLDINGS LIMITED"},{"lang":"hk","v":"京域高速公路控股有限公司"}],"company_since":"2001-07-11","company_dissolved":"2007-01-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762991","names":[{"lang":"en","v":"HAPPILY LIMITED"},{"lang":"hk","v":"喜萊有限公司"}],"company_since":"2001-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"762969","names":[{"lang":"en","v":"FANCY CHANNEL LIMITED (d2009-02-27)"},{"lang":"hk","v":"嘉通有限公司"}],"company_since":"2001-07-11","company_dissolved":"2009-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762811","names":[{"lang":"en","v":"HK AUDO INT'L GROUP DRESS LIMITED"},{"lang":"hk","v":"香港澳都國際集團服飾有限公司"}],"company_since":"2001-07-11","company_dissolved":"2006-11-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"762865","names":[{"lang":"en","v":"HONG KONG FENG YI INDUSTRIAL COMPANY LIMITED"},{"lang":"hk","v":"香港豐一實業有限公司"}],"company_since":"2001-07-11","company_dissolved":"2006-11-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"762993","names":[{"lang":"en","v":"J-HONG PRECISION COMPANY LIMITED"},{"lang":"hk","v":"日港精密有限公司"}],"company_since":"2001-07-11","company_dissolved":"2005-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"762791","names":[{"lang":"en","v":"JIA XUAN TANG LIMITED"},{"lang":"hk","v":"嘉軒堂有限公司"}],"company_since":"2001-07-11","company_dissolved":"2003-10-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"762873","names":[{"lang":"en","v":"JUN-HAO TRADING CO. LIMITED"},{"lang":"hk","v":"駿壕貿易有限公司"}],"company_since":"2001-07-11","company_dissolved":"2015-07-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"763016","names":[{"lang":"en","v":"LAUREL SOFTWARE LIMITED (d2006-11-24)"},{"lang":"hk","v":"桂冠軟件有限公司"}],"company_since":"2001-07-11","company_dissolved":"2006-11-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"762786","names":[{"lang":"en","v":"LIMIN CLOTHING IMP. &amp; EXP. LIMITED"},{"lang":"hk","v":"黎民服裝進出口有限公司"}],"company_since":"2001-07-11","company_dissolved":"2006-11-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"762950","names":[{"lang":"en","v":"JOIN CHINA DEVELOPMENT LIMITED"},{"lang":"hk","v":"華誠發展有限公司"}],"company_since":"2001-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"762915","names":[{"lang":"en","v":"NEWFAIR CORPORATION LIMITED"},{"lang":"hk","v":"展新有限公司"}],"company_since":"2001-07-11","company_dissolved":"2011-03-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"762906","names":[{"lang":"en","v":"MILLION ZONE LIMITED"},{"lang":"hk","v":"百域有限公司"}],"company_since":"2001-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"762926","names":[{"lang":"en","v":"PC CAT SERVICES LIMITED"}],"company_since":"2001-07-11","company_dissolved":"2003-08-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"762904","names":[{"lang":"en","v":"RICHLUCK CORPORATION LIMITED (d2005-10-07)"},{"lang":"hk","v":"寶瑞有限公司"}],"company_since":"2001-07-11","company_dissolved":"2005-10-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"762806","names":[{"lang":"en","v":"SO KEE LOGISTICS COMPANY LIMITED"},{"lang":"hk","v":"蘇記物流有限公司"}],"company_since":"2001-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"762999","names":[{"lang":"en","v":"SUCCESS NETWORK E-2002 LIMITED"}],"company_since":"2001-07-11","company_dissolved":"2006-11-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"762961","names":[{"lang":"en","v":"SUNTEAM CORPORATION LIMITED"},{"lang":"hk","v":"暉協有限公司"}],"company_since":"2001-07-11","company_dissolved":"2010-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762976","names":[{"lang":"en","v":"SOLAR DEVELOPMENT LIMITED (d2019-04-04)"},{"lang":"hk","v":"日中發展有限公司"}],"company_since":"2001-07-11","company_dissolved":"2019-04-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"763002","names":[{"lang":"en","v":"SWISS EMOTIONS LIMITED"}],"company_since":"2001-07-11","company_dissolved":"2012-12-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"762774","names":[{"lang":"en","v":"YI KENG IMPORT &amp; EXPORT CO., LIMITED"},{"lang":"hk","v":"怡景出入口有限公司"}],"company_since":"2001-07-11","company_dissolved":"2002-09-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"762912","names":[{"lang":"en","v":"VIDEO NETWORK TECHNOLOGY (HK) LIMITED"},{"lang":"hk","v":"視訊網絡科技有限公司"}],"company_since":"2001-07-11","company_dissolved":"2006-11-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762843","names":[{"lang":"en","v":"TRIAMIS TECHNOLOGY GROUP LIMITED"}],"company_since":"2001-07-11","company_dissolved":"2006-06-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762911","names":[{"lang":"en","v":"WINNING ENGINEERING (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"榮利裝飾工程(香港)有限公司"}],"company_since":"2001-07-11","company_dissolved":"2004-02-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"762896","names":[{"lang":"en","v":"CITI-DRAGON LIMITED"},{"lang":"hk","v":"龍都有限公司"}],"company_since":"2001-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"762990","names":[{"lang":"en","v":"DOUBLE COMPANY LIMITED (d2008-09-12)"},{"lang":"hk","v":"得寶興業有限公司"}],"company_since":"2001-07-11","company_dissolved":"2008-09-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"762874","names":[{"lang":"en","v":"FANGDE GOLD REFINEMENT COMPANY LIMITED (d2006-11-24)"},{"lang":"hk","v":"方德黃金精鍊有限公司"}],"company_since":"2001-07-11","company_dissolved":"2006-11-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"762969","names":[{"lang":"en","v":"FANCY CHANNEL LIMITED (d2009-02-27)"},{"lang":"hk","v":"嘉通有限公司"}],"company_since":"2001-07-11","company_dissolved":"2009-02-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"762886","names":[{"lang":"en","v":"COSA LOGISTICS COMPANY LIMITED"}],"company_since":"2001-07-11","company_dissolved":"2008-09-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762923","names":[{"lang":"en","v":"HOK PROGRAM MANAGEMENT (ASIA/PACIFIC) LIMITED"}],"company_since":"2001-07-11","company_dissolved":"2006-11-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"763005","names":[{"lang":"en","v":"FULL SPRING (HK) LIMITED"},{"lang":"hk","v":"葆源盛得(香港)有限公司"}],"company_since":"2001-07-11","company_dissolved":"2012-09-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"763004","names":[{"lang":"en","v":"HONG KONG CHILDREN'S HEART FUND LIMITED (THE)"},{"lang":"hk","v":"香港兒童心臟基金有限公司"}],"company_since":"2001-07-11","company_dissolved":"2015-03-16","company_type_txt":"Ltd by guarantee"},
undefined,
undefined,
{"tax_id":"763006","names":[{"lang":"en","v":"HONG KONG COMPETITIVENESS CENTRE LIMITED"},{"lang":"hk","v":"香港競爭力促進中心有限公司"}],"company_since":"2001-07-11","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"762934","names":[{"lang":"en","v":"GiftsPerfect4U Limited"},{"lang":"hk","v":"合意禮品有限公司"}],"company_since":"2001-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"762865","names":[{"lang":"en","v":"HONG KONG FENG YI INDUSTRIAL COMPANY LIMITED"},{"lang":"hk","v":"香港豐一實業有限公司"}],"company_since":"2001-07-11","company_dissolved":"2006-11-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762841","names":[{"lang":"en","v":"HONG KONG JING HING TRADING COMPANY LIMITED"},{"lang":"hk","v":"香港金鑫貿易有限公司"}],"company_since":"2001-07-11","company_dissolved":"2006-11-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762829","names":[{"lang":"en","v":"HONG KONG JIUCHI INT'L TRADING LIMITED"},{"lang":"hk","v":"香港玖馳國際貿易有限公司"}],"company_since":"2001-07-11","company_dissolved":"2006-11-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762822","names":[{"lang":"en","v":"HONG KONG LONGEVITY HEALTH CARE CO., LIMITED"},{"lang":"hk","v":"香港百年堂保健品有限公司"}],"company_since":"2001-07-11","company_dissolved":"2014-09-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762998","names":[{"lang":"en","v":"HONGKONG BUSINESS REGISTER ASSOCIATION CO. LIMITED"},{"lang":"hk","v":"香港商業註冊協會有限公司"}],"company_since":"2001-07-11","company_dissolved":"2006-11-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762993","names":[{"lang":"en","v":"J-HONG PRECISION COMPANY LIMITED"},{"lang":"hk","v":"日港精密有限公司"}],"company_since":"2001-07-11","company_dissolved":"2005-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762870","names":[{"lang":"en","v":"J. JLK INTERNATIONAL - HOLDINGS LIMITED"}],"company_since":"2001-07-11","company_dissolved":"2004-01-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"763026","names":[{"lang":"en","v":"Jade Property Holdings Limited"},{"lang":"hk","v":"翡翠置業集團有限公司"}],"company_since":"2001-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762867","names":[{"lang":"en","v":"JEFORMAL INDUSTRY (HONG KONG) LIMITED"},{"lang":"hk","v":"迪強實業(香港)有限公司"}],"company_since":"2001-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762791","names":[{"lang":"en","v":"JIA XUAN TANG LIMITED"},{"lang":"hk","v":"嘉軒堂有限公司"}],"company_since":"2001-07-11","company_dissolved":"2003-10-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762950","names":[{"lang":"en","v":"JOIN CHINA DEVELOPMENT LIMITED"},{"lang":"hk","v":"華誠發展有限公司"}],"company_since":"2001-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762908","names":[{"lang":"en","v":"JOY RAINBOW LIMITED (d2003-11-21)"},{"lang":"hk","v":"欣采有限公司"}],"company_since":"2001-07-11","company_dissolved":"2003-11-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"763009","names":[{"lang":"en","v":"JIN - STAR COMPANY LIMITED"},{"lang":"hk","v":"金實達有限公司"}],"company_since":"2001-07-11","company_dissolved":"2019-11-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762873","names":[{"lang":"en","v":"JUN-HAO TRADING CO. LIMITED"},{"lang":"hk","v":"駿壕貿易有限公司"}],"company_since":"2001-07-11","company_dissolved":"2015-07-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762917","names":[{"lang":"en","v":"GRANDTON INVESTMENT MANAGEMENT CO. LIMITED"},{"lang":"hk","v":"廣同投資管理有限公司"}],"company_since":"2001-07-11","company_dissolved":"2016-12-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762968","names":[{"lang":"en","v":"GREAT PALACE LIMITED"},{"lang":"hk","v":"泰軒有限公司"}],"company_since":"2001-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762868","names":[{"lang":"en","v":"H.K. GOLD HAWK INT'L INVESTMENT GROUP LIMITED"},{"lang":"hk","v":"香港金鷹國際投資集團有限公司"}],"company_since":"2001-07-11","company_dissolved":"2006-11-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762836","names":[{"lang":"en","v":"HENG FAI GEOG. &amp; CONST. CO. LIMITED"},{"lang":"hk","v":"恒暉土力工程有限公司"}],"company_since":"2001-07-11","company_dissolved":"2016-03-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762933","names":[{"lang":"en","v":"LONGWORTH INVESTMENT LIMITED"}],"company_since":"2001-07-11","company_dissolved":"2020-01-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762780","names":[{"lang":"en","v":"HUMAN PLASMA PRODUCT SERVICES ASIA LIMITED"}],"company_since":"2001-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762890","names":[{"lang":"en","v":"HUNAN UNITED CERAMIC-WARE MANUFACTURING (HONG KONG) CO., LIMITED"},{"lang":"hk","v":"湖南聯合陶瓷制品(香港)有限公司"}],"company_since":"2001-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762828","names":[{"lang":"en","v":"IC SKY POWER ELECTRON LIMITED"},{"lang":"hk","v":"西安天威電子有限公司"}],"company_since":"2001-07-11","company_dissolved":"2002-09-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762922","names":[{"lang":"en","v":"IGARMENT (HONG KONG) LIMITED"},{"lang":"hk","v":"艾格文(香港)有限公司"}],"company_since":"2001-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762919","names":[{"lang":"en","v":"IMAGINE HONG KONG LIMITED"}],"company_since":"2001-07-11","company_dissolved":"2012-06-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762862","names":[{"lang":"en","v":"NEW SPIRIT ENTERPRISES (H.K.) COMPANY LIMITED"},{"lang":"hk","v":"再勵企業(香港)有限公司"}],"company_since":"2001-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762814","names":[{"lang":"en","v":"INFO (H.K.) INTERNATIONAL ENTERPRISE INC., LIMITED"},{"lang":"hk","v":"英孚(香港)國際企業有限公司"}],"company_since":"2001-07-11","company_dissolved":"2006-11-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762915","names":[{"lang":"en","v":"NEWFAIR CORPORATION LIMITED"},{"lang":"hk","v":"展新有限公司"}],"company_since":"2001-07-11","company_dissolved":"2011-03-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762786","names":[{"lang":"en","v":"LIMIN CLOTHING IMP. &amp; EXP. LIMITED"},{"lang":"hk","v":"黎民服裝進出口有限公司"}],"company_since":"2001-07-11","company_dissolved":"2006-11-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762802","names":[{"lang":"en","v":"INTERNATIONAL FINANCIER (HONG KONG) INTERCHANGE ASSOCIATION LIMITED"},{"lang":"hk","v":"國際金融家(香港)交流協會有限公司"}],"company_since":"2001-07-11","company_dissolved":"2004-01-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762979","names":[{"lang":"en","v":"NEWOOD (H.K.) LIMITED"},{"lang":"hk","v":"新活(香港)有限公司"}],"company_since":"2001-07-11","company_dissolved":"2004-12-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762937","names":[{"lang":"en","v":"ITALY ALLGIRLS GARMENT (H.K.) INT'L LIMITED"},{"lang":"hk","v":"意大利澳歌服飾(香港)國際有限公司"}],"company_since":"2001-07-11","company_dissolved":"2006-11-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762789","names":[{"lang":"en","v":"NISSHO YAMANAKA LIMITED"},{"lang":"hk","v":"山中醫療有限公司"}],"company_since":"2001-07-11","company_dissolved":"2018-03-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762866","names":[{"lang":"en","v":"ITALY BELDES INT'L GROUP LIMITED"},{"lang":"hk","v":"意大利比爾茲國際集團有限公司"}],"company_since":"2001-07-11","company_dissolved":"2008-12-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762958","names":[{"lang":"en","v":"NITEK (HONG KONG) ENTERPRISES LIMITED"},{"lang":"hk","v":"利泰(香港)企業有限公司"}],"company_since":"2001-07-11","company_dissolved":"2018-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762832","names":[{"lang":"en","v":"ITALY CHERLONE HONG KONG COMPANY LIMITED"},{"lang":"hk","v":"意大利卓爾龍香港有限公司"}],"company_since":"2001-07-11","company_dissolved":"2006-09-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762930","names":[{"lang":"en","v":"ITALY FA AO KA SI (HONG KONG) INTERNATIONAL GROUP LIMITED"},{"lang":"hk","v":"意大利法奧卡斯(香港)國際集團有限公司"}],"company_since":"2001-07-11","company_dissolved":"2006-11-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762831","names":[{"lang":"en","v":"NORTHSTREAM HK LIMITED"}],"company_since":"2001-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762803","names":[{"lang":"en","v":"ITALY YVESZEGNOA GARMENT GROUP (H.K.) LIMITED"},{"lang":"hk","v":"意大利伊夫‧傑諾亞服飾集團(香港)有限公司"}],"company_since":"2001-07-11","company_dissolved":"2008-06-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762970","names":[{"lang":"en","v":"OCEAN DISCOVERY LIMITED (d2011-03-11)"},{"lang":"hk","v":"海洋動向有限公司"}],"company_since":"2001-07-11","company_dissolved":"2011-03-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762943","names":[{"lang":"en","v":"NOBEL CREATIVE LIMITED"},{"lang":"hk","v":"益啓有限公司"}],"company_since":"2001-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762954","names":[{"lang":"en","v":"ODM INTERIOR &amp; ASSOCIATE LIMITED"},{"lang":"hk","v":"奧美室內創建有限公司"}],"company_since":"2001-07-11","company_dissolved":"2006-09-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762825","names":[{"lang":"en","v":"OMA INTERNATIONAL LOGISTICS LIMITED"},{"lang":"hk","v":"歐馬國際物流有限公司"}],"company_since":"2001-07-11","company_dissolved":"2007-09-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"763014","names":[{"lang":"en","v":"OMEGA TRADEMARK LIMITED"},{"lang":"hk","v":"歐美品牌有限公司"}],"company_since":"2001-07-11","company_dissolved":"2006-11-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762799","names":[{"lang":"en","v":"ONTOP TRADING LIMITED"},{"lang":"hk","v":"信天貿易有限公司"}],"company_since":"2001-07-11","company_dissolved":"2007-07-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"763015","names":[{"lang":"en","v":"JAS &amp; ASSOCIATES TECHNOLOGIES LIMITED"}],"company_since":"2001-07-11","company_dissolved":"2008-12-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762777","names":[{"lang":"en","v":"ORANGE CLUB LIMITED"},{"lang":"hk","v":"奧文廣告有限公司"}],"company_since":"2001-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762784","names":[{"lang":"en","v":"JET LINK MANUFACTURING LIMITED"},{"lang":"hk","v":"捷興制品有限公司"}],"company_since":"2001-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762856","names":[{"lang":"en","v":"PACIFIC RICHEST LIMITED"},{"lang":"hk","v":"興濤有限公司"}],"company_since":"2001-07-11","company_dissolved":"2007-03-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762992","names":[{"lang":"en","v":"PACIFIC TOWN LIMITED (d2013-04-05)"},{"lang":"hk","v":"太鎮有限公司"}],"company_since":"2001-07-11","company_dissolved":"2013-04-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"762869","names":[{"lang":"en","v":"LIK SHING AUTO PARTS LIMITED"},{"lang":"hk","v":"力成汽車零件有限公司"}],"company_since":"2001-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"762906","names":[{"lang":"en","v":"MILLION ZONE LIMITED"},{"lang":"hk","v":"百域有限公司"}],"company_since":"2001-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762835","names":[{"lang":"en","v":"SAARADESIGN LIMITED"}],"company_since":"2001-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"762965","names":[{"lang":"en","v":"LONG MASTER LIMITED (d2009-04-09)"},{"lang":"hk","v":"遠萬有限公司"}],"company_since":"2001-07-11","company_dissolved":"2009-04-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762928","names":[{"lang":"en","v":"SANFENG INDUSTRIAL HONG KONG LIMITED"},{"lang":"hk","v":"三峰實業香港有限公司"}],"company_since":"2001-07-11","company_dissolved":"2003-10-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762796","names":[{"lang":"en","v":"MAGICON LIMITED (d2007-11-23)"},{"lang":"hk","v":"幻彩影藝有限公司"}],"company_since":"2001-07-11","company_dissolved":"2007-11-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762914","names":[{"lang":"en","v":"RIVERLINK CORPORATION LIMITED (d2004-12-17)"},{"lang":"hk","v":"江揚有限公司"}],"company_since":"2001-07-11","company_dissolved":"2004-12-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762880","names":[{"lang":"en","v":"SEG INTERNATIONAL LIMITED (d2004-01-02)"},{"lang":"hk","v":"賽格國際有限公司"}],"company_since":"2001-07-11","company_dissolved":"2004-01-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762956","names":[{"lang":"en","v":"SERAPHIN CAPITAL (HK) LIMITED"},{"lang":"hk","v":"德健國際財務顧問(香港)有限公司"}],"company_since":"2001-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762852","names":[{"lang":"en","v":"MAINLAND CORPORATION LIMITED (d2005-08-26)"},{"lang":"hk","v":"神州有限公司"}],"company_since":"2001-07-11","company_dissolved":"2005-08-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762768","names":[{"lang":"en","v":"MARK GOLDMAN CONSULTANT LIMITED"}],"company_since":"2001-07-11","company_dissolved":"2011-03-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762879","names":[{"lang":"en","v":"SHIMIZU TRADING COMPANY LIMITED"},{"lang":"hk","v":"山清水貿易有限公司"}],"company_since":"2001-07-11","company_dissolved":"2007-11-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"763007","names":[{"lang":"en","v":"SHU NING PRESENTATION UNIT LIMITED"},{"lang":"hk","v":"樹寧‧現在式單位有限公司"}],"company_since":"2001-07-11","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"762804","names":[{"lang":"en","v":"SHUI FAT GROUP (H.K.) INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"瑞發集團(香港)國際投資有限公司"}],"company_since":"2001-07-11","company_dissolved":"2005-12-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762989","names":[{"lang":"en","v":"SILVER RAINBOW LIMITED"},{"lang":"hk","v":"銀彩興業有限公司"}],"company_since":"2001-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762770","names":[{"lang":"en","v":"SINO MEDICAL HEALTH CENTRE LIMITED"},{"lang":"hk","v":"中華醫療保健中心有限公司"}],"company_since":"2001-07-11","company_dissolved":"2014-04-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762778","names":[{"lang":"en","v":"SKY CONSULTING LIMITED (HK)"},{"lang":"hk","v":"天逸顧問有限公司"}],"company_since":"2001-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"762882","names":[{"lang":"en","v":"SLIMMS RECRUIT LIMITED"},{"lang":"hk","v":"思能人才顧問有限公司"}],"company_since":"2001-07-11","company_dissolved":"2015-12-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"762904","names":[{"lang":"en","v":"RICHLUCK CORPORATION LIMITED (d2005-10-07)"},{"lang":"hk","v":"寶瑞有限公司"}],"company_since":"2001-07-11","company_dissolved":"2005-10-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
