undefined,
{"tax_id":"610317","names":[{"lang":"en","v":"CHAMPION WIDE INVESTMENT LIMITED"},{"lang":"hk","v":"祥偉投資有限公司"}],"company_since":"1997-05-30","company_dissolved":"2001-10-05","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610375","names":[{"lang":"en","v":"CHARTER SUPREME MARKETING LIMITED"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610383","names":[{"lang":"en","v":"CHARTERWEALTH GEOTECHNICS LIMITED"},{"lang":"hk","v":"卓劃土力工程有限公司"}],"company_since":"1997-05-30","company_dissolved":"2003-09-26","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610679","names":[{"lang":"en","v":"CHAU KEE ENGINEERING LIMITED"},{"lang":"hk","v":"就記工程有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610545","names":[{"lang":"en","v":"CHEUNG HING (LAM'S) INVESTMENT LIMITED"},{"lang":"hk","v":"祥興(林氏)置業有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610659","names":[{"lang":"en","v":"CHINA AMPLE HONG KONG LIMITED"},{"lang":"hk","v":"中鍚香港有限公司"}],"company_since":"1997-05-30","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610365","names":[{"lang":"en","v":"CHINA GREATWALL TELECOM HOLDINGS LIMITED"},{"lang":"hk","v":"中國長城電信集團有限公司"}],"company_since":"1997-05-30","company_dissolved":"2001-10-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610397","names":[{"lang":"en","v":"CIPONIC INDUSTRIAL (HK) LIMITED"},{"lang":"hk","v":"普科實業(香港)有限公司"}],"company_since":"1997-05-30","company_dissolved":"2009-12-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610579","names":[{"lang":"en","v":"CITY WIN (HONG KONG) LIMITED"},{"lang":"hk","v":"恆冠(香港)有限公司"}],"company_since":"1997-05-30","company_dissolved":"2012-11-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610667","names":[{"lang":"en","v":"COMPORT NOMINEES LIMITED"},{"lang":"hk","v":"金寶代理人有限公司"}],"company_since":"1997-05-30","company_dissolved":"2016-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610366","names":[{"lang":"en","v":"COMPORT TECHNOLOGY LIMITED"},{"lang":"hk","v":"金煌科技有限公司"}],"company_since":"1997-05-30","company_dissolved":"2006-12-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610312","names":[{"lang":"en","v":"CONBAR LIMITED (d2006-11-10)"}],"company_since":"1997-05-30","company_dissolved":"2006-11-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610511","names":[{"lang":"en","v":"CONWAY TECHNOLOGY (HK) COMPANY LIMITED"},{"lang":"hk","v":"港威科技(香港)有限公司"}],"company_since":"1997-05-30","company_dissolved":"2018-05-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610340","names":[{"lang":"en","v":"DAI WING (H.K.) TRADING LIMITED"},{"lang":"hk","v":"大榮(香港)貿易有限公司"}],"company_since":"1997-05-30","company_dissolved":"2001-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610377","names":[{"lang":"en","v":"DISON (HK) LIMITED"},{"lang":"hk","v":"滌心(香港)有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610482","names":[{"lang":"en","v":"DKI LIMITED"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610494","names":[{"lang":"en","v":"DOUBLE-EIGHT MOTOR CO., LIMITED"},{"lang":"hk","v":"孖8車行有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-12-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610616","names":[{"lang":"en","v":"DRAGON WIN HOLDINGS LIMITED (d2006-01-13)"},{"lang":"hk","v":"龍暉集團有限公司"}],"company_since":"1997-05-30","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610649","names":[{"lang":"en","v":"DYNAMIC CHANCE LIMITED (d2004-11-19)"},{"lang":"hk","v":"遠振有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610446","names":[{"lang":"en","v":"E &amp; A INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"歐安亞國際有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610645","names":[{"lang":"en","v":"EASTERN BRIGHT HOLDINGS LIMITED (d2011-11-18)"},{"lang":"hk","v":"東明集團有限公司"}],"company_since":"1997-05-30","company_dissolved":"2011-11-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610512","names":[{"lang":"en","v":"EASTERN DAY ENGINEERING (H.K.) LIMITED"},{"lang":"hk","v":"東逸工程有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610596","names":[{"lang":"en","v":"EASTERN SUCCESS (HK) LIMITED"},{"lang":"hk","v":"港成行有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610652","names":[{"lang":"en","v":"EASY PROJECT PROPERTIES LIMITED"},{"lang":"hk","v":"裕瀚置業有限公司"}],"company_since":"1997-05-30","company_dissolved":"1999-09-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610305","names":[{"lang":"en","v":"EATEX PROPERTIES LIMITED"},{"lang":"hk","v":"宇達置業有限公司"}],"company_since":"1997-05-30","company_dissolved":"2003-11-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610705","names":[{"lang":"en","v":"EMMANUEL FRUIT AND DESSERT COMPANY LIMITED"},{"lang":"hk","v":"以馬內利鮮果甜品有限公司"}],"company_since":"1997-05-30","company_dissolved":"2001-12-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610322","names":[{"lang":"en","v":"EMPEROR KING LIMITED"},{"lang":"hk","v":"御榮有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610672","names":[{"lang":"en","v":"EUROCAL FAR EAST LIMITED"},{"lang":"hk","v":"優加利亞遠東有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-06-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610500","names":[{"lang":"en","v":"EVER ALLIED DEVELOPMENT LIMITED"},{"lang":"hk","v":"永聯發展有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-03-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610604","names":[{"lang":"en","v":"EVER CENTRE LIMITED"},{"lang":"hk","v":"詠進有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610575","names":[{"lang":"en","v":"EVER FIRST (ASIA) LIMITED"},{"lang":"hk","v":"恒冠(亞洲)有限公司"}],"company_since":"1997-05-30","company_dissolved":"2007-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"610630","names":[{"lang":"en","v":"EXCELLENCE INTEGRATED PROPERTY SERVICES LIMITED"},{"lang":"hk","v":"高卓綜合管業有限公司"}],"company_since":"1997-05-30","company_dissolved":"2014-09-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610609","names":[{"lang":"en","v":"EVER TARGET INTERNATIONAL LIMITED (d2011-09-16)"},{"lang":"hk","v":"凱騰國際有限公司"}],"company_since":"1997-05-30","company_dissolved":"2011-09-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610641","names":[{"lang":"en","v":"FALCON (HONG KONG) LIMITED"},{"lang":"hk","v":"和康(香港)有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610627","names":[{"lang":"en","v":"FORTUNE FORCE DEVELOPMENT LIMITED (d2011-01-07)"},{"lang":"hk","v":"福城發展有限公司"}],"company_since":"1997-05-30","company_dissolved":"2011-01-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610516","names":[{"lang":"en","v":"FULL FAI DEVELOPMENT (HK) COMPANY LIMITED"},{"lang":"hk","v":"富輝發展(香港)有限公司"}],"company_since":"1997-05-30","company_dissolved":"2000-11-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610693","names":[{"lang":"en","v":"CHINA JUMBO HONG KONG LIMITED"},{"lang":"hk","v":"中萌香港有限公司"}],"company_since":"1997-05-30","company_dissolved":"2003-01-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610402","names":[{"lang":"en","v":"FORTUNE WEAL ENTERPRISES LIMITED"},{"lang":"hk","v":"福輝企業有限公司"}],"company_since":"1997-05-30","company_dissolved":"2011-05-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610343","names":[{"lang":"en","v":"DANTSIN TECHNOLOGIES LIMITED"},{"lang":"hk","v":"丹青科技有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610669","names":[{"lang":"en","v":"FREEGRAND LIMITED"},{"lang":"hk","v":"飛宏有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610369","names":[{"lang":"en","v":"FUNG KEE CHONG FOOD PRODUCTS CO. LIMITED"},{"lang":"hk","v":"豐記莊食品有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-08-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610642","names":[{"lang":"en","v":"GALLIUM (HONG KONG) LIMITED (d2003-08-15)"},{"lang":"hk","v":"嘉倫(香港)有限公司"}],"company_since":"1997-05-30","company_dissolved":"2003-08-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610386","names":[{"lang":"en","v":"DENRISE (H.K.) ENTERPRISE CO. LIMITED"},{"lang":"hk","v":"升茂(香港)企業有限公司"}],"company_since":"1997-05-30","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610429","names":[{"lang":"en","v":"GAINTEK ROBOTIC AIRDUCT CLEANING LIMITED"},{"lang":"hk","v":"敬達機械清潔冷氣槽有限公司"}],"company_since":"1997-05-30","company_dissolved":"2011-01-07","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610517","names":[{"lang":"en","v":"FULLY POWER TRADING (HK) LIMITED"},{"lang":"hk","v":"富力貿易(香港)有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-12-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610513","names":[{"lang":"en","v":"GEMTEC ENTERPRISE CO., LIMITED"},{"lang":"hk","v":"心悅科技有限公司"}],"company_since":"1997-05-30","company_dissolved":"2006-10-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610315","names":[{"lang":"en","v":"COSMO LAND AGENCY LIMITED"},{"lang":"hk","v":"高寶地產代理有限公司"}],"company_since":"1997-05-30","company_dissolved":"2014-06-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610593","names":[{"lang":"en","v":"FORD CHANCE LIMITED"},{"lang":"hk","v":"科域有限公司"}],"company_since":"1997-05-30","company_dissolved":"2000-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610634","names":[{"lang":"en","v":"FORD SKY LIMITED"},{"lang":"hk","v":"焯天有限公司"}],"company_since":"1997-05-30","company_dissolved":"2001-10-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610620","names":[{"lang":"en","v":"GOLD TIME REALTY LIMITED"},{"lang":"hk","v":"金卓置業有限公司"}],"company_since":"1997-05-30","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610321","names":[{"lang":"en","v":"EMPEROR LINK LIMITED"},{"lang":"hk","v":"御興有限公司"}],"company_since":"1997-05-30","company_dissolved":"2003-04-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610699","names":[{"lang":"en","v":"EMWAY ELECTRONIC LIMITED"},{"lang":"hk","v":"恒威電子有限公司"}],"company_since":"1997-05-30","company_dissolved":"2008-10-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610503","names":[{"lang":"en","v":"GOLDWELL PROPERTY INVESTMENTS LIMITED"},{"lang":"hk","v":"金華置業投資有限公司"}],"company_since":"1997-05-30","company_dissolved":"2016-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610416","names":[{"lang":"en","v":"GOLDEN WORLDWIDE LIMITED (d2003-12-24)"},{"lang":"hk","v":"金環球有限公司"}],"company_since":"1997-05-30","company_dissolved":"2003-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610635","names":[{"lang":"en","v":"GOMAN ENTERPRISE LIMITED (d2002-02-01)"},{"lang":"hk","v":"高彩企業有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610419","names":[{"lang":"en","v":"GOLDWELL PROPERTY DEVELOPMENT LIMITED"},{"lang":"hk","v":"金華置業發展有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610561","names":[{"lang":"en","v":"EVER FORWARDER LIMITED"},{"lang":"hk","v":"鵬迅有限公司"}],"company_since":"1997-05-30","company_dissolved":"2003-08-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610610","names":[{"lang":"en","v":"GRAND BENEFIT HOLDINGS LIMITED (d2004-11-19)"},{"lang":"hk","v":"廣財集團有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610356","names":[{"lang":"en","v":"GRAND ALLIANCE ASSET MANAGEMENT LIMITED"},{"lang":"hk","v":"浩成資產管理有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610621","names":[{"lang":"en","v":"EVER GAIN REALTY LIMITED"},{"lang":"hk","v":"億潤置業有限公司"}],"company_since":"1997-05-30","company_dissolved":"2013-08-23","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610664","names":[{"lang":"en","v":"GOLDENLIFE HOLDINGS LIMITED"},{"lang":"hk","v":"金富運集團有限公司"}],"company_since":"1997-05-30","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610422","names":[{"lang":"en","v":"GOLDLEAF CORPORATION LIMITED (d2000-09-22)"},{"lang":"hk","v":"金葉行有限公司"}],"company_since":"1997-05-30","company_dissolved":"2000-09-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610605","names":[{"lang":"en","v":"EVER JOINTURE LIMITED"},{"lang":"hk","v":"永盟興業有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610362","names":[{"lang":"en","v":"GRANDSHARP INVESTMENTS LIMITED"},{"lang":"hk","v":"鴻銳投資有限公司"}],"company_since":"1997-05-30","company_dissolved":"2018-12-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610435","names":[{"lang":"en","v":"FITONE LIMITED"},{"lang":"hk","v":"方濤有限公司"}],"company_since":"1997-05-30","company_dissolved":"2001-11-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610320","names":[{"lang":"en","v":"GREAT WIN ENTERPRISES LIMITED (d2004-11-19)"},{"lang":"hk","v":"盛軒企業有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610417","names":[{"lang":"en","v":"GOLDWORLD PROPERTY INVESTMENTS LIMITED"},{"lang":"hk","v":"金偉置業投資有限公司"}],"company_since":"1997-05-30","company_dissolved":"2005-10-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610665","names":[{"lang":"en","v":"H C TELECOM (HK) LIMITED"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610505","names":[{"lang":"en","v":"FOOK HANG HONG KONG LIMITED"},{"lang":"hk","v":"福恒香港有限公司"}],"company_since":"1997-05-30","company_dissolved":"2012-12-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610407","names":[{"lang":"en","v":"H&amp;R BLOCK LIMITED"}],"company_since":"1997-05-30","company_dissolved":"2001-10-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610686","names":[{"lang":"en","v":"EVER PREMIER INTERNATIONAL LIMITED"},{"lang":"hk","v":"永平國際有限公司"}],"company_since":"1997-05-30","company_dissolved":"2003-06-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610431","names":[{"lang":"en","v":"HAMPTON DEVELOPMENT LIMITED"},{"lang":"hk","v":"漢敦發展有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-04-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610675","names":[{"lang":"en","v":"HARVEST GROUP INTERNATIONAL LIMITED (d2002-05-24)"},{"lang":"hk","v":"永盟集團有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-05-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610346","names":[{"lang":"en","v":"HENG TONG HOLDING PHARMACEUTICALS (F.E.) COMPANY LIMITED"},{"lang":"hk","v":"恒通集團藥業(遠東)有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-08-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610689","names":[{"lang":"en","v":"FORTUNA COURT SEAFOOD RESTAURANT LIMITED"},{"lang":"hk","v":"福來臨海鮮酒家有限公司"}],"company_since":"1997-05-30","company_dissolved":"2000-11-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610451","names":[{"lang":"en","v":"HI-PROFILE LIMITED (d2003-12-05)"},{"lang":"hk","v":"高姿態有限公司"}],"company_since":"1997-05-30","company_dissolved":"2003-12-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610701","names":[{"lang":"en","v":"HINTER COMPANY LIMITED"},{"lang":"hk","v":"衍泰有限公司"}],"company_since":"1997-05-30","company_dissolved":"2009-11-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"610541","names":[{"lang":"en","v":"HKMD LIMITED"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610354","names":[{"lang":"en","v":"FREEDOM MACHINERY COMPANY LIMITED"},{"lang":"hk","v":"輝騰工程有限公司"}],"company_since":"1997-05-30","company_dissolved":"2012-03-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610363","names":[{"lang":"en","v":"HOMENICE INVESTMENTS LIMITED"},{"lang":"hk","v":"鴻麗投資有限公司"}],"company_since":"1997-05-30","company_dissolved":"2007-11-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610412","names":[{"lang":"en","v":"GLOBAL WIN DEVELOPMENT LIMITED"},{"lang":"hk","v":"嘉運發展有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610331","names":[{"lang":"en","v":"HOMEWORLD DEVELOPMENT LIMITED"},{"lang":"hk","v":"鴻懋發展有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610348","names":[{"lang":"en","v":"HONG KONG COSMETIC LASER CENTRE LIMITED"},{"lang":"hk","v":"香港激光美容中心有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-12-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610639","names":[{"lang":"en","v":"GO DIRECT LIMITED (d2005-07-22)"}],"company_since":"1997-05-30","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610367","names":[{"lang":"en","v":"GIVE FINE INDUSTRIAL CO., LIMITED"},{"lang":"hk","v":"聖鋒實業有限公司"}],"company_since":"1997-05-30","company_dissolved":"2003-01-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610339","names":[{"lang":"en","v":"HONG KONG GREAT WALL INTERNATIONAL INVESTMENT COMPANY LIMITED"},{"lang":"hk","v":"香港長城國際投資有限公司"}],"company_since":"1997-05-30","company_dissolved":"2019-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610497","names":[{"lang":"en","v":"GOLD FORD LIMITED"},{"lang":"hk","v":"金富有限公司"}],"company_since":"1997-05-30","company_dissolved":"2003-02-07","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610391","names":[{"lang":"en","v":"HONG KONG INSTITUTE FOR MANAGEMENT AND PROFESSIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"香港管理及專業發展有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-11-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"610539","names":[{"lang":"en","v":"FULIWELL COMPANY LIMITED"},{"lang":"hk","v":"全力佳有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610547","names":[{"lang":"en","v":"HONG KONG REALTY INVESTMENT AGENCY LIMITED"},{"lang":"hk","v":"香港地產代理有限公司"}],"company_since":"1997-05-30","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610504","names":[{"lang":"en","v":"GOLDEN NAME INVESTMENTS LIMITED"},{"lang":"hk","v":"金榮投資有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610595","names":[{"lang":"en","v":"EXCEL WOOD LIMITED (d2006-03-24)"},{"lang":"hk","v":"好邦有限公司"}],"company_since":"1997-05-30","company_dissolved":"2006-03-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610631","names":[{"lang":"en","v":"GOLD WAVE INVESTMENT LIMITED (d2007-10-12)"},{"lang":"hk","v":"新洋投資有限公司"}],"company_since":"1997-05-30","company_dissolved":"2007-10-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610550","names":[{"lang":"en","v":"HUA SHI COMPANY LIMITED"},{"lang":"hk","v":"華氏有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610532","names":[{"lang":"en","v":"HUNG YICK INVESTMENTS LIMITED"},{"lang":"hk","v":"鴻億投資有限公司"}],"company_since":"1997-05-30","company_dissolved":"2006-10-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610615","names":[{"lang":"en","v":"EVER SKY HOLDINGS LIMITED (d2006-01-13)"},{"lang":"hk","v":"永天集團有限公司"}],"company_since":"1997-05-30","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610556","names":[{"lang":"en","v":"JADE DYNASTY JEWELLERY COMPANY LIMITED"}],"company_since":"1997-05-30","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610566","names":[{"lang":"en","v":"JADE FRAGRANT COMPANY LIMITED"},{"lang":"hk","v":"廉芬有限公司"}],"company_since":"1997-05-30","company_dissolved":"2015-09-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610565","names":[{"lang":"en","v":"FANHILL LIMITED"},{"lang":"hk","v":"龐軒有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610387","names":[{"lang":"en","v":"KA LEE PO DEVELOPMENT LIMITED"},{"lang":"hk","v":"嘉利保發展有限公司"}],"company_since":"1997-05-30","company_dissolved":"2003-08-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610614","names":[{"lang":"en","v":"FIRST WIN HOLDINGS LIMITED (d2001-01-05)"},{"lang":"hk","v":"恒冠集團有限公司"}],"company_since":"1997-05-30","company_dissolved":"2001-01-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610437","names":[{"lang":"en","v":"KASIA INVESTMENT LIMITED"},{"lang":"hk","v":"騏順投資有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610677","names":[{"lang":"en","v":"HONG KONG FINE BREED PIG FARM LIMITED"},{"lang":"hk","v":"香港良種豬場有限公司"}],"company_since":"1997-05-30","company_dissolved":"2007-02-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610601","names":[{"lang":"en","v":"KELBEST LIMITED"},{"lang":"hk","v":"騏嘉有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-08-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610587","names":[{"lang":"en","v":"FIRST WELL INVESTMENT LIMITED"},{"lang":"hk","v":"浩榮投資有限公司"}],"company_since":"1997-05-30","company_dissolved":"2018-11-16","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610599","names":[{"lang":"en","v":"KELGAIN LIMITED (d2000-07-14)"},{"lang":"hk","v":"騏堅有限公司"}],"company_since":"1997-05-30","company_dissolved":"2000-07-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610600","names":[{"lang":"en","v":"KELSTAR LIMITED (d2002-05-10)"},{"lang":"hk","v":"麒星有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-05-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610436","names":[{"lang":"en","v":"KENSIGHT LIMITED"},{"lang":"hk","v":"鈞景有限公司"}],"company_since":"1997-05-30","company_dissolved":"2008-03-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"610703","names":[{"lang":"en","v":"LA' SWANK COLLECTION LIMITED"},{"lang":"hk","v":"思雲裳時裝批發有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-08-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610433","names":[{"lang":"en","v":"KONG TEI LIMITED"},{"lang":"hk","v":"港地有限公司"}],"company_since":"1997-05-30","company_dissolved":"2009-10-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610335","names":[{"lang":"en","v":"COMPORT ENGINEERING LIMITED"},{"lang":"hk","v":"興寶工程有限公司"}],"company_since":"1997-05-30","company_dissolved":"2006-10-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610564","names":[{"lang":"en","v":"FOKLAND (H.K.) LIMITED"},{"lang":"hk","v":"福霖(香港)有限公司"}],"company_since":"1997-05-30","company_dissolved":"2001-10-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610400","names":[{"lang":"en","v":"LAGRASTA HONG KONG LIMITED"}],"company_since":"1997-05-30","company_dissolved":"2008-11-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610347","names":[{"lang":"en","v":"LEON TEXTILE LIMITED"},{"lang":"hk","v":"領航布業有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610371","names":[{"lang":"en","v":"LESHAN LONG MARCH MEDICINE INDUSTRY COMPANY LIMITED"},{"lang":"hk","v":"樂山長征藥業有限公司"}],"company_since":"1997-05-30","company_dissolved":"2001-11-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610636","names":[{"lang":"en","v":"HANG SING INTERNATIONAL A &amp; V COMPANY LIMITED"},{"lang":"hk","v":"恒星國際影音制作有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610676","names":[{"lang":"en","v":"LIEN MING ENTERPRISES COMPANY LIMITED"},{"lang":"hk","v":"聯銘企業有限公司"}],"company_since":"1997-05-30","company_dissolved":"2018-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610468","names":[{"lang":"en","v":"LINK CHARTER INVESTMENTS LIMITED"},{"lang":"hk","v":"凌綽投資有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610316","names":[{"lang":"en","v":"HILL FAME DEVELOPMENT LIMITED"},{"lang":"hk","v":"祥譽發展有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-02-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610459","names":[{"lang":"en","v":"LINK SCORE ENGINEERING LIMITED"},{"lang":"hk","v":"凌高工程有限公司"}],"company_since":"1997-05-30","company_dissolved":"2016-04-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610558","names":[{"lang":"en","v":"LINK YORK DEVELOPMENT LIMITED"},{"lang":"hk","v":"凌潤發展有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-11-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610469","names":[{"lang":"en","v":"LINK YORK INVESTMENTS LIMITED"},{"lang":"hk","v":"凌潤投資有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610521","names":[{"lang":"en","v":"HO TING COMPANY LIMITED"},{"lang":"hk","v":"豪頲有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-07-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610533","names":[{"lang":"en","v":"HOME BRIGHT INTERNATIONAL LIMITED"},{"lang":"hk","v":"鴻輝國際有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-07-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610461","names":[{"lang":"en","v":"LINKFUL ENGINEERING LIMITED"},{"lang":"hk","v":"凌豐工程有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-12-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610671","names":[{"lang":"en","v":"LOGICA INTERNATIONAL CONSULTING GROUP (HONG KONG) LIMITED"}],"company_since":"1997-05-30","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"610471","names":[{"lang":"en","v":"HONEYCOMB CORE TECHNOLOGIES LIMITED"},{"lang":"hk","v":"芯科技有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610534","names":[{"lang":"en","v":"HOMEWISE INTERNATIONAL LIMITED"},{"lang":"hk","v":"鴻慧國際有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610548","names":[{"lang":"en","v":"LORDIN APPAREL LIMITED"},{"lang":"hk","v":"朗殿服飾有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610393","names":[{"lang":"en","v":"LOVELY HAVEN LIMITED"},{"lang":"hk","v":"來其運有限公司"}],"company_since":"1997-05-30","company_dissolved":"2019-10-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610540","names":[{"lang":"en","v":"LUCKY PIONEERS LIMITED"},{"lang":"hk","v":"吉祥勝有限公司"}],"company_since":"1997-05-30","company_dissolved":"2000-10-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610381","names":[{"lang":"en","v":"LUEN YICK DISPENSARY LIMITED"},{"lang":"hk","v":"聯益藥房有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610380","names":[{"lang":"en","v":"HONG KONG KAI LI LONG INTERNATIONAL HOLDING LIMITED"},{"lang":"hk","v":"香港凱利龍國際集團有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610557","names":[{"lang":"en","v":"LUXE TRINITY DEVELOPMENT LIMITED"},{"lang":"hk","v":"凌隆發展有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610462","names":[{"lang":"en","v":"LUXE TRINITY ENTERPRISES LIMITED"},{"lang":"hk","v":"凌隆企業有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610454","names":[{"lang":"en","v":"LUXE TRINITY LIMITED (d2004-05-07)"},{"lang":"hk","v":"凌隆有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-05-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610487","names":[{"lang":"en","v":"HONG KONG TSZ KWONG BETHEL CHURCH LIMITED"},{"lang":"hk","v":"香港伯特利教會慈光堂有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
{"tax_id":"610456","names":[{"lang":"en","v":"LUXIE HOLDINGS LIMITED"},{"lang":"hk","v":"凌智集團有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-09-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"610306","names":[{"lang":"en","v":"HUGE POINT INDUSTRIES LIMITED"},{"lang":"hk","v":"宏邦實業有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610330","names":[{"lang":"en","v":"HUNG WAH DEVELOPMENT LIMITED"},{"lang":"hk","v":"鴻樺發展有限公司"}],"company_since":"1997-05-30","company_dissolved":"2008-11-07","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610458","names":[{"lang":"en","v":"INVENTIVE WORLD OF SCIENTIST COMPANY LIMITED"},{"lang":"hk","v":"發明天地科技有限公司"}],"company_since":"1997-05-30","company_dissolved":"2001-07-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610302","names":[{"lang":"en","v":"MACY INVESTMENT HOLDING LIMITED"},{"lang":"hk","v":"瑪思投資控股有限公司"}],"company_since":"1997-05-30","company_dissolved":"2010-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610586","names":[{"lang":"en","v":"MANAGEMENT &amp; TECHNOLOGY CONSULTANTS LIMITED"},{"lang":"hk","v":"管理及科技顧問有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610662","names":[{"lang":"en","v":"MANHATTAN HOLDINGS LIMITED"},{"lang":"hk","v":"萬泰控股有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610687","names":[{"lang":"en","v":"IT &amp; T EDUCATION LIMITED"}],"company_since":"1997-05-30","company_dissolved":"2010-06-11","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610478","names":[{"lang":"en","v":"MANIS GIFT LIMITED"}],"company_since":"1997-05-30","company_dissolved":"2018-03-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610398","names":[{"lang":"en","v":"MANLEY TECHNOLOGY LIMITED (d2001-08-24)"}],"company_since":"1997-05-30","company_dissolved":"2001-08-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610681","names":[{"lang":"en","v":"MAPLE HOLDINGS LIMITED (d2002-04-04)"},{"lang":"hk","v":"加昌集團有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-04-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610455","names":[{"lang":"en","v":"MART LINK LIMITED"},{"lang":"hk","v":"凌軒有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610345","names":[{"lang":"en","v":"JUMBO SUCCESS MANUFACTURING CO. LIMITED"},{"lang":"hk","v":"鼎懋實業製品有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610361","names":[{"lang":"en","v":"MAZY DRAGON LIMITED"},{"lang":"hk","v":"雋龍有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610389","names":[{"lang":"en","v":"MID-ORIENT TECHNOLOGY LIMITED"},{"lang":"hk","v":"中遠科技有限公司"}],"company_since":"1997-05-30","company_dissolved":"2000-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610445","names":[{"lang":"en","v":"KENSTAR (HK) LIMITED"},{"lang":"hk","v":"勁星(香港)有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610492","names":[{"lang":"en","v":"MILLENNIUM U.S.A. LIMITED (THE)"},{"lang":"hk","v":"美國天泰有限公司"}],"company_since":"1997-05-30","company_dissolved":"2005-10-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610323","names":[{"lang":"en","v":"KING OF CONGEE &amp; NOODLE LIMITED"},{"lang":"hk","v":"粥麵皇有限公司"}],"company_since":"1997-05-30","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610382","names":[{"lang":"en","v":"MOOSE ENTERPRISE (HK) LIMITED"}],"company_since":"1997-05-30","company_dissolved":"2007-04-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"610376","names":[{"lang":"en","v":"LEADING WAY INTERNATIONAL LIMITED"},{"lang":"hk","v":"凌威國際集團有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610395","names":[{"lang":"en","v":"MOUNTAINVIEW MONTESSORI PLAYGROUP LIMITED"}],"company_since":"1997-05-30","company_dissolved":"2013-09-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610583","names":[{"lang":"en","v":"NEW BASE ENTERPRISES LIMITED (d2001-12-21)"},{"lang":"hk","v":"創域企業有限公司"}],"company_since":"1997-05-30","company_dissolved":"2001-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610333","names":[{"lang":"en","v":"NEW COMPORT INTERNATIONAL LIMITED"},{"lang":"hk","v":"新金寶國際有限公司"}],"company_since":"1997-05-30","company_dissolved":"2006-10-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610463","names":[{"lang":"en","v":"LINK YORK ENTERPRISES LIMITED"},{"lang":"hk","v":"凌潤企業有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-02-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610311","names":[{"lang":"en","v":"NEW DYNASTY (HK) LIMITED"},{"lang":"hk","v":"新晉陽(香港)有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-12-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610466","names":[{"lang":"en","v":"LINK YORK TRADING LIMITED"},{"lang":"hk","v":"凌潤貿易有限公司"}],"company_since":"1997-05-30","company_dissolved":"2001-05-11","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610653","names":[{"lang":"en","v":"NEW PROJECTION PROPERTIES LIMITED"},{"lang":"hk","v":"旭新置業有限公司"}],"company_since":"1997-05-30","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"610457","names":[{"lang":"en","v":"LINKENT TECHNOLOGY LIMITED"},{"lang":"hk","v":"凌隆科技有限公司"}],"company_since":"1997-05-30","company_dissolved":"2003-07-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610640","names":[{"lang":"en","v":"NON.NO GROUP LIMITED"},{"lang":"hk","v":"浪漫露集團有限公司"}],"company_since":"1997-05-30","company_dissolved":"2001-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610394","names":[{"lang":"en","v":"OCEANIC JOYS LIMITED"},{"lang":"hk","v":"洋禧有限公司"}],"company_since":"1997-05-30","company_dissolved":"2007-11-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610384","names":[{"lang":"en","v":"ORBIS TRADING LIMITED (d2004-11-19)"},{"lang":"hk","v":"蒼洋貿易有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610567","names":[{"lang":"en","v":"ORIENTAL MANDARIN (INTERNATIONAL) HOLDINGS LIMITED"},{"lang":"hk","v":"東方文華(國際)控股有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610559","names":[{"lang":"en","v":"LUXE TRINITY INVESTMENTS LIMITED"},{"lang":"hk","v":"凌隆投資有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-02-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610303","names":[{"lang":"en","v":"OVERSEA GROUP LIMITED (THE)"},{"lang":"hk","v":"香港四海集團有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610464","names":[{"lang":"en","v":"LUXE TRINITY TRADING LIMITED"},{"lang":"hk","v":"凌隆貿易有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-02-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610626","names":[{"lang":"en","v":"PACIFIC FAVOUR TRADING LIMITED"},{"lang":"hk","v":"泊汶貿易有限公司"}],"company_since":"1997-05-30","company_dissolved":"2011-12-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610329","names":[{"lang":"en","v":"PARAGON HONG KONG EXPRESS LIMITED"},{"lang":"hk","v":"統華香港運通有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"610326","names":[{"lang":"en","v":"PINE EMPEROR LIMITED"},{"lang":"hk","v":"御峰有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-12-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610465","names":[{"lang":"en","v":"LUXTON TRADING LIMITED"},{"lang":"hk","v":"凌通貿易有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610657","names":[{"lang":"en","v":"PIONEER JOY ENTERPRISES LIMITED"},{"lang":"hk","v":"鴻羚企業有限公司"}],"company_since":"1997-05-30","company_dissolved":"2001-08-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610414","names":[{"lang":"en","v":"PO SING (HK) INDUSTRIAL LIMITED"},{"lang":"hk","v":"堡昇實業有限公司"}],"company_since":"1997-05-30","company_dissolved":"2015-02-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610432","names":[{"lang":"en","v":"LECKY WROUGHT IRON LIMITED"},{"lang":"hk","v":"利克鍛鐵有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610592","names":[{"lang":"en","v":"POLY BUSINESS LIMITED"},{"lang":"hk","v":"恒業行有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610591","names":[{"lang":"en","v":"POLY WAVE LIMITED (d2001-08-10)"},{"lang":"hk","v":"寶昌行有限公司"}],"company_since":"1997-05-30","company_dissolved":"2001-08-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610577","names":[{"lang":"en","v":"POLYFORCE (HONG KONG) LIMITED"},{"lang":"hk","v":"寶昌(香港)有限公司"}],"company_since":"1997-05-30","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610327","names":[{"lang":"en","v":"POLYTEX CLOTHINGS LIMITED"},{"lang":"hk","v":"保利達服裝有限公司"}],"company_since":"1997-05-30","company_dissolved":"2005-05-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610307","names":[{"lang":"en","v":"METRO CROWN INDUSTRIES LIMITED"},{"lang":"hk","v":"明港實業有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610325","names":[{"lang":"en","v":"PRIME CHAMPION LIMITED (d2006-12-29)"},{"lang":"hk","v":"御昌有限公司"}],"company_since":"1997-05-30","company_dissolved":"2006-12-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610336","names":[{"lang":"en","v":"PRINCIPAL TRUST COMPANY (ASIA) LIMITED"},{"lang":"hk","v":"信安信託(亞洲)有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Public, ltd by shares"},
undefined,
undefined,
{"tax_id":"610507","names":[{"lang":"en","v":"PRO-WELL PRECISION PRODUCTS LIMITED"},{"lang":"hk","v":"寶威精密製品有限公司"}],"company_since":"1997-05-30","company_dissolved":"2013-11-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610696","names":[{"lang":"en","v":"MILLENNIUM HOTEL &amp; CATERING MANAGEMENT LIMITED"},{"lang":"hk","v":"佳年酒店飲食管理有限公司"}],"company_since":"1997-05-30","company_dissolved":"2000-12-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610658","names":[{"lang":"en","v":"PROFIT CLASSIC ENTERPRISES LIMITED"},{"lang":"hk","v":"浩錦企業有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-12-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610607","names":[{"lang":"en","v":"PROFIT DRAGON HOLDINGS LIMITED (d2002-09-13)"},{"lang":"hk","v":"怡龍集團有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-09-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"610528","names":[{"lang":"en","v":"MING CHEONG HONG LIMITED"},{"lang":"hk","v":"銘昌行有限公司"}],"company_since":"1997-05-30","company_dissolved":"2018-08-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610526","names":[{"lang":"en","v":"PROFIT ORIGIN INVESTMENT LIMITED"},{"lang":"hk","v":"蘊富投資有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610351","names":[{"lang":"en","v":"PROSPER VIEW HOLDINGS LIMITED"},{"lang":"hk","v":"盛景集團有限公司"}],"company_since":"1997-05-30","company_dissolved":"2000-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610332","names":[{"lang":"en","v":"PROPSON INTERNATIONAL LIMITED"},{"lang":"hk","v":"置成國際有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-10-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610430","names":[{"lang":"en","v":"MACRO-ARCHITECTURE (H.K.) CO., LIMITED"},{"lang":"hk","v":"香港大業建築有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610427","names":[{"lang":"en","v":"NEON FERRY SERVICE COMPANY LIMITED"},{"lang":"hk","v":"新利航船務有限公司"}],"company_since":"1997-05-30","company_dissolved":"2003-04-25","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610510","names":[{"lang":"en","v":"RAINBOW CREATION GROUP LIMITED"},{"lang":"hk","v":"彩虹創建集團有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610680","names":[{"lang":"en","v":"REALTIME MULTI-MEDIA LIMITED"},{"lang":"hk","v":"利訊(多媒體)有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-07-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"610590","names":[{"lang":"en","v":"REGAL FAMOUS LIMITED (d2000-08-04)"},{"lang":"hk","v":"皇迅有限公司"}],"company_since":"1997-05-30","company_dissolved":"2000-08-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610698","names":[{"lang":"en","v":"NIKO-SEM COMPANY LIMITED"},{"lang":"hk","v":"尼克森微電子股份有限公司"}],"company_since":"1997-05-30","company_dissolved":"2014-09-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610415","names":[{"lang":"en","v":"O.H. TECHNOLOGY CO., LIMITED"},{"lang":"hk","v":"享慶科技股份有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610562","names":[{"lang":"en","v":"RETAK PROPERTIES LIMITED"},{"lang":"hk","v":"怡德置業有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"610447","names":[{"lang":"en","v":"REGENT TAX CONSULTANTS LIMITED"},{"lang":"hk","v":"偉正稅務顧問有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610660","names":[{"lang":"en","v":"RICH COSMOS HOLDINGS LIMITED (d2003-02-07)"},{"lang":"hk","v":"怡翠集團有限公司"}],"company_since":"1997-05-30","company_dissolved":"2003-02-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610481","names":[{"lang":"en","v":"PROFIT LINE LIMITED"},{"lang":"hk","v":"鵬倫有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610530","names":[{"lang":"en","v":"RICACORP PROPERTIES (TSUEN WAN) LIMITED"},{"lang":"hk","v":"利嘉閣地產(荃灣)有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-01-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610613","names":[{"lang":"en","v":"NEW SOURCE HOLDINGS LIMITED"},{"lang":"hk","v":"創源集團有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610619","names":[{"lang":"en","v":"RICH LINK REALTY LIMITED"},{"lang":"hk","v":"億聯置業有限公司"}],"company_since":"1997-05-30","company_dissolved":"2009-07-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610563","names":[{"lang":"en","v":"ORIENT PRODUCTS CO. LIMITED"},{"lang":"hk","v":"東方物產有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-08-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610582","names":[{"lang":"en","v":"RICH SOURCE ENTERPRISES LIMITED (d2004-11-19)"},{"lang":"hk","v":"發匯企業有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610618","names":[{"lang":"en","v":"RICH SOURCE REALTY LIMITED"},{"lang":"hk","v":"創源置業有限公司"}],"company_since":"1997-05-30","company_dissolved":"2011-11-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610573","names":[{"lang":"en","v":"RICH TIME (ASIA) LIMITED"},{"lang":"hk","v":"富時(亞洲)有限公司"}],"company_since":"1997-05-30","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610643","names":[{"lang":"en","v":"RIGHT CHAMPION (HONG KONG) LIMITED"},{"lang":"hk","v":"利祥(香港)有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610485","names":[{"lang":"en","v":"OVERSEAS STAR INVESTMENT LIMITED (d2009-10-16)"},{"lang":"hk","v":"遠星投資有限公司"}],"company_since":"1997-05-30","company_dissolved":"2009-10-16","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610426","names":[{"lang":"en","v":"RUN WELL INTERNATIONAL TRANSPORTATION COMPANY LIMITED"},{"lang":"hk","v":"行健國際貨運有限公司"}],"company_since":"1997-05-30","company_dissolved":"2000-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610524","names":[{"lang":"en","v":"PAN SOURCE HOLDINGS LIMITED"},{"lang":"hk","v":"怡浩集團有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610390","names":[{"lang":"en","v":"SAMPO INVESTMENT LIMITED"},{"lang":"hk","v":"善普投資有限公司"}],"company_since":"1997-05-30","company_dissolved":"2000-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610674","names":[{"lang":"en","v":"SAPIN CORPORATION LIMITED"},{"lang":"hk","v":"心達禮品有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"610301","names":[{"lang":"en","v":"SINO DRAGON COMPANY LIMITED"},{"lang":"hk","v":"天龍興業有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610491","names":[{"lang":"en","v":"SKYLINE EXCHANGE LIMITED"},{"lang":"hk","v":"天傲有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-11-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610399","names":[{"lang":"en","v":"SMARCOMM (HK) LIMITED"},{"lang":"hk","v":"數碼通訊(香港)有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610520","names":[{"lang":"en","v":"PO CHEUNG LIMITED"},{"lang":"hk","v":"保祥有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-05-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610682","names":[{"lang":"en","v":"SMARTEX HOLDINGS LIMITED (d2003-03-07)"},{"lang":"hk","v":"明智集團有限公司"}],"company_since":"1997-05-30","company_dissolved":"2003-03-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610308","names":[{"lang":"en","v":"SOLAR WIN (HONG KONG) LIMITED"},{"lang":"hk","v":"日宏(香港)有限公司"}],"company_since":"1997-05-30","company_dissolved":"2001-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610648","names":[{"lang":"en","v":"SOLAREX INTERNATIONAL LIMITED"},{"lang":"hk","v":"日宇國際有限公司"}],"company_since":"1997-05-30","company_dissolved":"2001-08-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610334","names":[{"lang":"en","v":"SPACON ELECTRIC COMPANY LIMITED"},{"lang":"hk","v":"三原電容有限公司"}],"company_since":"1997-05-30","company_dissolved":"2013-11-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610537","names":[{"lang":"en","v":"ORIENTAL FOODS (H.K.) LIMITED"},{"lang":"hk","v":"東方食品(香港)有限公司"}],"company_since":"1997-05-30","company_dissolved":"2001-02-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610476","names":[{"lang":"en","v":"PROFIT PALACE PROPERTIES LIMITED"},{"lang":"hk","v":"鵬安置業有限公司"}],"company_since":"1997-05-30","company_dissolved":"2001-02-23","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610442","names":[{"lang":"en","v":"PROFIT KING (HK) LIMITED"},{"lang":"hk","v":"潤景(香港)有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610396","names":[{"lang":"en","v":"THOMSON (FAR EAST) COMPANY LIMITED"},{"lang":"hk","v":"湯普遜(遠東)有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610444","names":[{"lang":"en","v":"PROFIT LAND (HK) LIMITED"},{"lang":"hk","v":"富島(香港)有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-08-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610493","names":[{"lang":"en","v":"TOANO SMART LIMITED"},{"lang":"hk","v":"東野德斯有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610661","names":[{"lang":"en","v":"Rainbow Asia Holdings Group Limited"},{"lang":"hk","v":"彩虹亞洲控股集團有限公司"}],"company_since":"1997-05-30","company_dissolved":"2013-08-16","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610536","names":[{"lang":"en","v":"TOYOKO-INN.COM/HONGKONG. LIMITED"},{"lang":"hk","v":"東橫酒店(香港)有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610490","names":[{"lang":"en","v":"TRADE RIGHT HONG KONG LIMITED"},{"lang":"hk","v":"益宏香港有限公司"}],"company_since":"1997-05-30","company_dissolved":"2014-04-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610535","names":[{"lang":"en","v":"TRIFFEN HOLDINGS LIMITED"},{"lang":"hk","v":"德鴻集團有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610646","names":[{"lang":"en","v":"REASON HOLDINGS LIMITED (d2002-10-11)"},{"lang":"hk","v":"立勝集團有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-10-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"610572","names":[{"lang":"en","v":"UNITED WELL (ASIA) LIMITED"},{"lang":"hk","v":"匯富(亞洲)有限公司"}],"company_since":"1997-05-30","company_dissolved":"2012-05-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610506","names":[{"lang":"en","v":"VALTRA (HONG KONG) LIMITED"},{"lang":"hk","v":"緯泰(香港)有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610691","names":[{"lang":"en","v":"VICTORY SUPER INVESTMENT LIMITED"},{"lang":"hk","v":"雄悅投資有限公司"}],"company_since":"1997-05-30","company_dissolved":"2003-05-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610551","names":[{"lang":"en","v":"VORTEX LIMITED (HK)"},{"lang":"hk","v":"禾特有限公司"}],"company_since":"1997-05-30","company_dissolved":"2018-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"610424","names":[{"lang":"en","v":"S-MART FASHION (HK) LIMITED"},{"lang":"hk","v":"莎瑪時裝(香港)有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610546","names":[{"lang":"en","v":"WAY MING DEVELOPMENT LIMITED"},{"lang":"hk","v":"慧明發展有限公司"}],"company_since":"1997-05-30","company_dissolved":"2001-02-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610404","names":[{"lang":"en","v":"WEAL CHINA DEVELOPMENT LIMITED"},{"lang":"hk","v":"華基發展有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610644","names":[{"lang":"en","v":"SHERIN (HONG KONG) LIMITED"},{"lang":"hk","v":"瑞興(香港)有限公司"}],"company_since":"1997-05-30","company_dissolved":"2003-02-07","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610571","names":[{"lang":"en","v":"WEALTHY LINK (ASIA) LIMITED"},{"lang":"hk","v":"創聯(亞洲)供應鏈有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610589","names":[{"lang":"en","v":"SINO BRIGHT LIMITED"},{"lang":"hk","v":"龍暉行有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610349","names":[{"lang":"en","v":"WELL ALLIED INTERNATIONAL LIMITED"},{"lang":"hk","v":"祥合國際有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610611","names":[{"lang":"en","v":"WELL ASSETS LIMITED"},{"lang":"hk","v":"韋源有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610357","names":[{"lang":"en","v":"WH CAPITAL MANAGEMENT LIMITED"},{"lang":"hk","v":"康安國際投資有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-11-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"610552","names":[{"lang":"en","v":"SMARTECH MEDIA CO., LIMITED"},{"lang":"hk","v":"港科技術有限公司"}],"company_since":"1997-05-30","company_dissolved":"2019-11-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610647","names":[{"lang":"en","v":"SMARTRON INTERNATIONAL LIMITED"},{"lang":"hk","v":"生祥國際有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-12-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610406","names":[{"lang":"en","v":"WIN WAY LIMITED"},{"lang":"hk","v":"創運有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610663","names":[{"lang":"en","v":"WIN WIN ASSOCIATION LIMITED"},{"lang":"hk","v":"貫達國際有限公司"}],"company_since":"1997-05-30","company_dissolved":"2003-02-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610704","names":[{"lang":"en","v":"WING SHUN METAL LIMITED"},{"lang":"hk","v":"永信五金有限公司"}],"company_since":"1997-05-30","company_dissolved":"2009-07-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"610623","names":[{"lang":"en","v":"WINSTON FASHION LIMITED"},{"lang":"hk","v":"永思登時裝有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-09-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"610409","names":[{"lang":"en","v":"WISE MORE INTERNATIONAL LIMITED"},{"lang":"hk","v":"億利物業國際有限公司"}],"company_since":"1997-05-30","company_dissolved":"2006-03-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610650","names":[{"lang":"en","v":"STARWAY (CHINA-H.K.) LIMITED"},{"lang":"hk","v":"事達(中港)有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610373","names":[{"lang":"en","v":"SUMMIT (INTERNATIONAL) TRADE CO. LIMITED"},{"lang":"hk","v":"浤峰(國際)貿易有限公司"}],"company_since":"1997-05-30","company_dissolved":"2001-10-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610606","names":[{"lang":"en","v":"WORLD HARBOUR HOLDINGS LIMITED (d2002-06-21)"},{"lang":"hk","v":"惠港集團有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-06-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610475","names":[{"lang":"en","v":"WORLD ISLAND PROPERTIES LIMITED"},{"lang":"hk","v":"偉綸置業有限公司"}],"company_since":"1997-05-30","company_dissolved":"2000-11-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610603","names":[{"lang":"en","v":"WORLD JOINTURE LIMITED"},{"lang":"hk","v":"韋駿有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"610509","names":[{"lang":"en","v":"TAKAGI PLASTIC &amp; MOULDING COMPANY LIMITED"},{"lang":"hk","v":"崇技塑膠模具有限公司"}],"company_since":"1997-05-30","company_dissolved":"2003-11-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610379","names":[{"lang":"en","v":"WORLD KINGDOM INVESTMENT LIMITED"},{"lang":"hk","v":"詠國投資有限公司"}],"company_since":"1997-05-30","company_dissolved":"2001-07-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610483","names":[{"lang":"en","v":"WORLD PIONEER INTERNATIONAL LIMITED"},{"lang":"hk","v":"維才國際有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610438","names":[{"lang":"en","v":"WORLD PLAN INVESTMENT LIMITED"},{"lang":"hk","v":"緯霸投資有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"610538","names":[{"lang":"en","v":"TUNG HIP (H.K.) INDUSTRIAL COMPANY LIMITED"},{"lang":"hk","v":"東協(香港)實業有限公司"}],"company_since":"1997-05-30","company_dissolved":"2001-10-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610515","names":[{"lang":"en","v":"TUNG KEE CONSTRUCTION AND DECORATION CO., LIMITED"},{"lang":"hk","v":"棟記建築裝修有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-03-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610522","names":[{"lang":"en","v":"WYLOX CONSTRUCTION COMPANY LIMITED"},{"lang":"hk","v":"澐龍建築工程有限公司"}],"company_since":"1997-05-30","company_dissolved":"2007-06-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"610519","names":[{"lang":"en","v":"YEE TUNG PROPERTY AGENCY COMPANY LIMITED"},{"lang":"hk","v":"怡東地產代理有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610408","names":[{"lang":"en","v":"UNION HARVEST INDUSTRIAL LIMITED (d2004-11-19)"},{"lang":"hk","v":"聯益實業有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610498","names":[{"lang":"en","v":"UNION WEAL ENTERPRISES LIMITED"},{"lang":"hk","v":"聯興企業有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610337","names":[{"lang":"en","v":"YUE SING ENTERPRISES LIMITED (d2014-11-07)"},{"lang":"hk","v":"越星企業有限公司"}],"company_since":"1997-05-30","company_dissolved":"2014-11-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610401","names":[{"lang":"en","v":"UNION WIN INVESTMENT LIMITED (d2004-11-19)"},{"lang":"hk","v":"聯成投資有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610495","names":[{"lang":"en","v":"SOUTHERN HARVEST INTERNATIONAL LIMITED"},{"lang":"hk","v":"南豐國際有限公司"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610690","names":[{"lang":"en","v":"NEW MAJOR ENTERPRISES LIMITED"},{"lang":"hk","v":"濠怡企業有限公司"}],"company_since":"1997-05-30","company_dissolved":"2001-08-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610608","names":[{"lang":"en","v":"W. GREAT WORTH LIMITED"}],"company_since":"1997-05-30","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610697","names":[{"lang":"en","v":"WAHCO LIMITED"},{"lang":"hk","v":"華高創業有限公司"}],"company_since":"1997-05-30","company_dissolved":"2003-01-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"610405","names":[{"lang":"en","v":"WEALTH OCEAN INDUSTRIAL LIMITED (d2003-02-07)"},{"lang":"hk","v":"富海實業有限公司"}],"company_since":"1997-05-30","company_dissolved":"2003-02-07","company_type_txt":"Private, ltd by shares"},
{"tax_id":"610496","names":[{"lang":"en","v":"WEALTH SKY LIMITED (d2004-08-13)"},{"lang":"hk","v":"天利有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-08-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610310","names":[{"lang":"en","v":"WIDEFIELD INTERNATIONAL (HK) LIMITED"},{"lang":"hk","v":"豪毅國際(香港)有限公司"}],"company_since":"1997-05-30","company_dissolved":"2002-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"610309","names":[{"lang":"en","v":"WONDERLAND DEVELOPMENT (HOLDING'S) GROUP LIMITED"},{"lang":"hk","v":"奇奧華納發展控股集團有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610443","names":[{"lang":"en","v":"WORLD CITY (HK) LIMITED"},{"lang":"hk","v":"榮城(香港)有限公司"}],"company_since":"1997-05-30","company_dissolved":"2003-02-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610440","names":[{"lang":"en","v":"WORLD LIAISON INVESTMENT LIMITED"},{"lang":"hk","v":"緯順投資有限公司"}],"company_since":"1997-05-30","company_dissolved":"2008-11-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"610318","names":[{"lang":"en","v":"WORLD PINE ENTERPRISES LIMITED"},{"lang":"hk","v":"祥峰企業有限公司"}],"company_since":"1997-05-30","company_dissolved":"2005-12-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610484","names":[{"lang":"en","v":"WORLD WINNER INTERNATIONAL LIMITED (d2004-11-19)"},{"lang":"hk","v":"緯榮國際有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"610453","names":[{"lang":"en","v":"YI SHENG INTERNATIONAL LIMITED"},{"lang":"hk","v":"益生國際有限公司"}],"company_since":"1997-05-30","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
