{"tax_id":"607982","names":[{"lang":"en","v":"CHAU TAI CHUN METAL FACTORY (FAR EAST) LIMITED"},{"lang":"hk","v":"周大進五金廠(遠東)有限公司"}],"company_since":"1997-05-14","company_dissolved":"2020-05-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607938","names":[{"lang":"en","v":"CHESCO ENGINEERING LIMITED"},{"lang":"hk","v":"志源工程有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607730","names":[{"lang":"en","v":"CHEUNG ON PROPERTY AGENCY LIMITED"},{"lang":"hk","v":"祥安地產代理有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-12-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607868","names":[{"lang":"en","v":"CHEUNG SHING CHEMICAL HOLDINGS (H.K.) COMPANY LIMITED"},{"lang":"hk","v":"長城石化集團(香港)股份有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607781","names":[{"lang":"en","v":"CHI SHING ENGINEERING (H.K.) LIMITED (d2002-03-15)"},{"lang":"hk","v":"志成工程(香港)有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-03-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607894","names":[{"lang":"en","v":"CHINA HAMADA BLOWER LIMITED"},{"lang":"hk","v":"中國濱田送風機有限公司"}],"company_since":"1997-05-14","company_dissolved":"2000-09-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607893","names":[{"lang":"en","v":"CHINA HOTELS PUBLISHER LIMITED"},{"lang":"hk","v":"中國酒店雜誌社有限公司"}],"company_since":"1997-05-14","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607965","names":[{"lang":"en","v":"CHINA OLDENBURG INTERNATIONAL INVESTMENT &amp; DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"中國奧登堡國際投資發展有限公司"}],"company_since":"1997-05-14","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607729","names":[{"lang":"en","v":"CHINA WORLDWIDE TRADING LIMITED (d2002-11-22)"}],"company_since":"1997-05-14","company_dissolved":"2002-11-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607793","names":[{"lang":"en","v":"CHINAKIT TRADING LIMITED"}],"company_since":"1997-05-14","company_dissolved":"2007-01-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607887","names":[{"lang":"en","v":"CHUN SHING HANDBAGS FACTORY LIMITED"},{"lang":"hk","v":"振成手袋廠有限公司"}],"company_since":"1997-05-14","company_dissolved":"2014-09-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607713","names":[{"lang":"en","v":"CHUNG SHING TEXTILES (H.K.) CO. LIMITED"},{"lang":"hk","v":"中興紡織(香港)有限公司"}],"company_since":"1997-05-14","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607993","names":[{"lang":"en","v":"CORSELETTE INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"蔻思莉國際有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-12-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607856","names":[{"lang":"en","v":"CROWN FORTRESS LIMITED (d2003-10-17)"},{"lang":"hk","v":"凱冠有限公司"}],"company_since":"1997-05-14","company_dissolved":"2003-10-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607776","names":[{"lang":"en","v":"D AND C DEVELOPMENT LIMITED"},{"lang":"hk","v":"蔡氏發展有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607863","names":[{"lang":"en","v":"DE MATE DESIGN LIMITED"},{"lang":"hk","v":"廸美室內設計有限公司"}],"company_since":"1997-05-14","company_dissolved":"1999-01-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607930","names":[{"lang":"en","v":"DERNICK TRADING LIMITED"}],"company_since":"1997-05-14","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607748","names":[{"lang":"en","v":"DHE-TSANG MONASTERY FOUNDATION LIMITED"},{"lang":"hk","v":"大藏寺基金會有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
undefined,
undefined,
{"tax_id":"607808","names":[{"lang":"en","v":"DISPLAY ASIA LIMITED"}],"company_since":"1997-05-14","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607905","names":[{"lang":"en","v":"DOUBLE VALUE INVESTMENT LIMITED"},{"lang":"hk","v":"得寶威投資有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-01-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607841","names":[{"lang":"en","v":"DRAGONFIELD MANAGEMENT LIMITED"},{"lang":"hk","v":"龍田管理有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607756","names":[{"lang":"en","v":"EASE ASIA LIMITED (d2003-01-10)"},{"lang":"hk","v":"怡亞有限公司"}],"company_since":"1997-05-14","company_dissolved":"2003-01-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607769","names":[{"lang":"en","v":"EASE GLORY HOLDINGS LIMITED (d2002-06-28)"},{"lang":"hk","v":"怡亮集團有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-06-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607760","names":[{"lang":"en","v":"EASE GREEN LIMITED (d2002-11-22)"},{"lang":"hk","v":"怡綠有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-11-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607765","names":[{"lang":"en","v":"EASE POWER INTERNATIONAL LIMITED"},{"lang":"hk","v":"怡勁國際有限公司"}],"company_since":"1997-05-14","company_dissolved":"2001-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607766","names":[{"lang":"en","v":"EASE STAND INTERNATIONAL LIMITED"},{"lang":"hk","v":"怡企國際有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-04-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607823","names":[{"lang":"en","v":"EASERICH TRADING LIMITED"},{"lang":"hk","v":"怡發貿易有限公司"}],"company_since":"1997-05-14","company_dissolved":"2013-11-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607724","names":[{"lang":"en","v":"EAST FA DO DEVELOPMENT LIMITED"},{"lang":"hk","v":"東方興業發展有限公司"}],"company_since":"1997-05-14","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608009","names":[{"lang":"en","v":"EASTERN ELEGANCE LIMITED (d2007-09-28)"},{"lang":"hk","v":"東麗控股有限公司"}],"company_since":"1997-05-14","company_dissolved":"2007-09-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607763","names":[{"lang":"en","v":"EASY BASIC LIMITED (d2004-11-12)"},{"lang":"hk","v":"怡實有限公司"}],"company_since":"1997-05-14","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607809","names":[{"lang":"en","v":"EASTBOUND NAVIGATION COMPANY LIMITED"},{"lang":"hk","v":"環亞油運有限公司"}],"company_since":"1997-05-14","company_dissolved":"2003-09-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607764","names":[{"lang":"en","v":"EASY COUNT INTERNATIONAL CAPITAL LIMITED"},{"lang":"hk","v":"怡庭國際資本有限公司"}],"company_since":"1997-05-14","company_dissolved":"2008-08-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607761","names":[{"lang":"en","v":"EASY KING LIMITED (d2002-12-20)"},{"lang":"hk","v":"怡帝有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-12-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607759","names":[{"lang":"en","v":"EASY SOUND LIMITED (d2003-01-10)"},{"lang":"hk","v":"怡音有限公司"}],"company_since":"1997-05-14","company_dissolved":"2003-01-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607762","names":[{"lang":"en","v":"EASY TOP LIMITED"},{"lang":"hk","v":"怡尚有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607851","names":[{"lang":"en","v":"EFFORT (HONG KONG) LIMITED"},{"lang":"hk","v":"宇福(香港)有限公司"}],"company_since":"1997-05-14","company_dissolved":"2003-04-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607712","names":[{"lang":"en","v":"EMPORIO SCARPA COMPANY LIMITED"}],"company_since":"1997-05-14","company_dissolved":"2001-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607746","names":[{"lang":"en","v":"ENCHANTED HILLS LIMITED"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607804","names":[{"lang":"en","v":"ENTERPRISE IDENTITY GROUP ASIA/PACIFIC LIMITED"}],"company_since":"1997-05-14","company_dissolved":"2009-07-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608012","names":[{"lang":"en","v":"ESTOREE LIMITED"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607891","names":[{"lang":"en","v":"EVERYWIN MOTORS TRADING COMPANY LIMITED"},{"lang":"hk","v":"利得汽車有限公司"}],"company_since":"1997-05-14","company_dissolved":"2001-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608005","names":[{"lang":"en","v":"EXODUS INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"依則達國際有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607920","names":[{"lang":"en","v":"EXPRESS PRINTING LIMITED (HK)"},{"lang":"hk","v":"益栢印刷有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607754","names":[{"lang":"en","v":"FAVOUR CAPITAL LIMITED (d2001-11-09)"},{"lang":"hk","v":"順京有限公司"}],"company_since":"1997-05-14","company_dissolved":"2001-11-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607797","names":[{"lang":"en","v":"FIRST COME LIMITED"},{"lang":"hk","v":"寶捷倉運有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607710","names":[{"lang":"en","v":"FIRST SINO-ENERGY CORPORATION LIMITED"},{"lang":"hk","v":"第一中華能源股份有限公司"}],"company_since":"1997-05-14","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607917","names":[{"lang":"en","v":"FORDEN PROPERTIES LIMITED"},{"lang":"hk","v":"和祥置業有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607854","names":[{"lang":"en","v":"FORTUNE ASSET DEVELOPMENT LIMITED"},{"lang":"hk","v":"運潤發展有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608031","names":[{"lang":"en","v":"CHENG WANG (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"祥宏(香港)有限公司"}],"company_since":"1997-05-14","company_dissolved":"2004-12-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607807","names":[{"lang":"en","v":"CHENG XIN (CHINA) INDUSTRIAL COMPANY LIMITED"},{"lang":"hk","v":"呈欣(中國)實業有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607812","names":[{"lang":"en","v":"FOUNTAINHEAD TRADING LIMITED"}],"company_since":"1997-05-14","company_dissolved":"2001-07-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607939","names":[{"lang":"en","v":"FRIENDS OF THE ROAD ENTERPRISES LIMITED"},{"lang":"hk","v":"馬路之友企業有限公司"}],"company_since":"1997-05-14","company_dissolved":"2006-06-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607791","names":[{"lang":"en","v":"FULL HOUSE RESTAURANT LIMITED (d2006-01-13)"},{"lang":"hk","v":"譽滿坊甜品美食專門店有限公司"}],"company_since":"1997-05-14","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607975","names":[{"lang":"en","v":"FUNG WON OPTICAL (H.K.) CO., LIMITED"},{"lang":"hk","v":"豐元眼鏡(香港)有限公司"}],"company_since":"1997-05-14","company_dissolved":"2007-09-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607999","names":[{"lang":"en","v":"FUTURE PACIFIC LIMITED"}],"company_since":"1997-05-14","company_dissolved":"2015-05-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607951","names":[{"lang":"en","v":"CHIEF PLUS LIMITED"},{"lang":"hk","v":"帝津有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607911","names":[{"lang":"en","v":"CHINA GRACE HERITAGE LIMITED"},{"lang":"hk","v":"華恩基業有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-12-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607945","names":[{"lang":"en","v":"GAINFAIR (H.K.) LIMITED"},{"lang":"hk","v":"景輝(香港)有限公司"}],"company_since":"1997-05-14","company_dissolved":"2011-11-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607948","names":[{"lang":"en","v":"GAINRICH HOLDINGS LIMITED (d2009-01-16)"},{"lang":"hk","v":"景裕集團有限公司"}],"company_since":"1997-05-14","company_dissolved":"2009-01-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607915","names":[{"lang":"en","v":"GLADSOME PROPERTIES LIMITED"},{"lang":"hk","v":"安逸置業有限公司"}],"company_since":"1997-05-14","company_dissolved":"2001-10-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"607882","names":[{"lang":"en","v":"GLOBAL CONCEPT MANAGEMENT LIMITED"}],"company_since":"1997-05-14","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607733","names":[{"lang":"en","v":"CHINA SOUTHERN PACKING (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"中南包裝(香港)有限公司"}],"company_since":"1997-05-14","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608010","names":[{"lang":"en","v":"GOLD ELEGANT INTERNATIONAL LIMITED (d2003-03-07)"},{"lang":"hk","v":"金達國際有限公司"}],"company_since":"1997-05-14","company_dissolved":"2003-03-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608039","names":[{"lang":"en","v":"GOLDEN KNIGHT SECURITY LIMITED (HK)"},{"lang":"hk","v":"金鋒警衛有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607790","names":[{"lang":"en","v":"GOLDEN SOUTH INTERNATIONAL TRAVEL SERVICES (HK) LIMITED"},{"lang":"hk","v":"金南國際旅遊(香港)有限公司"}],"company_since":"1997-05-14","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607922","names":[{"lang":"en","v":"GRAND PROFIT HOUSE LIMITED"},{"lang":"hk","v":"宏基行有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-09-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607949","names":[{"lang":"en","v":"GRANDTEX HOLDINGS LIMITED (d2002-08-23)"},{"lang":"hk","v":"景達集團有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-08-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607782","names":[{"lang":"en","v":"GREEN BAY SHENZHEN GOLF CLUB COMPANY LIMITED"},{"lang":"hk","v":"深圳碧海灣高爾夫俱樂部有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"607810","names":[{"lang":"en","v":"H T INVESTMENT SERVICES LIMITED"}],"company_since":"1997-05-14","company_dissolved":"2002-11-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608032","names":[{"lang":"en","v":"DELIGHTFUL INTERNATIONAL FOOD CONSULTANTS LIMITED"}],"company_since":"1997-05-14","company_dissolved":"2002-11-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607818","names":[{"lang":"en","v":"HAI YAO HOLDINGS (HK) LIMITED"},{"lang":"hk","v":"海葯集團(香港)有限公司"}],"company_since":"1997-05-14","company_dissolved":"2001-03-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607723","names":[{"lang":"en","v":"HAN HUA HANG BUILDING MATERIAL COMPANY LIMITED"},{"lang":"hk","v":"漢樺行建築材料有限公司"}],"company_since":"1997-05-14","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608018","names":[{"lang":"en","v":"HANG LEI HAT AND GARMENT EMBROIDERY FACTORY LIMITED"},{"lang":"hk","v":"恆利製帽成衣綉花廠有限公司"}],"company_since":"1997-05-14","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607835","names":[{"lang":"en","v":"DOUBLE VALUE INTERNATIONAL LIMITED"},{"lang":"hk","v":"得寶威國際有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-02-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607990","names":[{"lang":"en","v":"HANSOL HONG KONG LIMITED"},{"lang":"hk","v":"韓松香港有限公司"}],"company_since":"1997-05-14","company_dissolved":"2009-09-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607806","names":[{"lang":"en","v":"DRAGON SONIC (H.K.) LIMITED"},{"lang":"hk","v":"龍聲(香港)有限公司"}],"company_since":"1997-05-14","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607973","names":[{"lang":"en","v":"HEI FENG CONSTRUCTION COMPANY LIMITED"},{"lang":"hk","v":"熙鋒建築有限公司"}],"company_since":"1997-05-14","company_dissolved":"2000-01-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607933","names":[{"lang":"en","v":"HONG KONG GUANG CAI SHI YE PROMOTION ASSOCIATION LIMITED"},{"lang":"hk","v":"香港光彩事業促進會有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
undefined,
undefined,
{"tax_id":"608008","names":[{"lang":"en","v":"HONOUR TOP TRADING LIMITED"},{"lang":"hk","v":"安宏貿易有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-12-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607794","names":[{"lang":"en","v":"HUA NENG HONG KONG PROPERTY CO. LIMITED"},{"lang":"hk","v":"華能香港置業有限公司"}],"company_since":"1997-05-14","company_dissolved":"2018-10-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607749","names":[{"lang":"en","v":"HUNG FAT CRANE TRANSPORTATION COMPANY LIMITED"},{"lang":"hk","v":"雄發吊機運輸有限公司"}],"company_since":"1997-05-14","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608015","names":[{"lang":"en","v":"IBC DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"滙致發展有限公司"}],"company_since":"1997-05-14","company_dissolved":"2003-07-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607719","names":[{"lang":"en","v":"INFONET POWER LIMITED"},{"lang":"hk","v":"天訊動力有限公司"}],"company_since":"1997-05-14","company_dissolved":"2004-12-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607912","names":[{"lang":"en","v":"INTERNATIONAL CHINESE WUSHI ASSOCIATION LIMITED"},{"lang":"hk","v":"世界華人武術技擊總會有限公司"}],"company_since":"1997-05-14","company_dissolved":"2003-05-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607995","names":[{"lang":"en","v":"IP WAI COMPANY LIMITED"},{"lang":"hk","v":"業威製品廠有限公司"}],"company_since":"1997-05-14","company_dissolved":"2004-04-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607715","names":[{"lang":"en","v":"JING YUN TRADING COMPANY LIMITED"},{"lang":"hk","v":"景雲貿易有限公司"}],"company_since":"1997-05-14","company_dissolved":"2001-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607736","names":[{"lang":"en","v":"JOHANSON HONG KONG LIMITED"},{"lang":"hk","v":"約翰遜有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608037","names":[{"lang":"en","v":"JUMBERCA (CHINA) LIMITED"},{"lang":"hk","v":"珍寶家(中國)有限公司"}],"company_since":"1997-05-14","company_dissolved":"2010-07-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607909","names":[{"lang":"en","v":"JUMBO CREATION LIMITED"},{"lang":"hk","v":"大製作有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607827","names":[{"lang":"en","v":"JUMBO MASTER DEVELOPMENT LIMITED"},{"lang":"hk","v":"珍霸發展有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607829","names":[{"lang":"en","v":"JUMBO MASTER INVESTMENT LIMITED"},{"lang":"hk","v":"珍霸投資有限公司"}],"company_since":"1997-05-14","company_dissolved":"2010-08-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607837","names":[{"lang":"en","v":"JUMBO POWER HOLDINGS LIMITED"},{"lang":"hk","v":"珍霸集團有限公司"}],"company_since":"1997-05-14","company_dissolved":"2001-07-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607950","names":[{"lang":"en","v":"KARREX INTERNATIONAL LIMITED"},{"lang":"hk","v":"家宏國際有限公司"}],"company_since":"1997-05-14","company_dissolved":"2000-09-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607958","names":[{"lang":"en","v":"FITA INDUSTRIAL LIMITED"},{"lang":"hk","v":"輝達工業有限公司"}],"company_since":"1997-05-14","company_dissolved":"2001-05-25","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607801","names":[{"lang":"en","v":"KAZAMA SEMICONDUCTOR LIMITED"}],"company_since":"1997-05-14","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607874","names":[{"lang":"en","v":"KEISEA FOOTWEAR MANUFACTURING LIMITED"},{"lang":"hk","v":"岐海鞋業有限公司"}],"company_since":"1997-05-14","company_dissolved":"2001-09-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607708","names":[{"lang":"en","v":"KEN YUE INVESTMENT LIMITED"}],"company_since":"1997-05-14","company_dissolved":"2017-09-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607758","names":[{"lang":"en","v":"KIN DON INVESTMENTS LIMITED"},{"lang":"hk","v":"金盾投資有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607757","names":[{"lang":"en","v":"KIN DON PROPERTIES LIMITED"},{"lang":"hk","v":"金盾物業有限公司"}],"company_since":"1997-05-14","company_dissolved":"2001-03-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608023","names":[{"lang":"en","v":"KIN SON GARMENT LIMITED"},{"lang":"hk","v":"堅舜製衣有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607910","names":[{"lang":"en","v":"KING POWER ENTERPRISES (HK) LIMITED"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607943","names":[{"lang":"en","v":"KINGDOM BEST INTERNATIONAL LIMITED (d2003-01-24)"},{"lang":"hk","v":"帝派國際有限公司"}],"company_since":"1997-05-14","company_dissolved":"2003-01-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607941","names":[{"lang":"en","v":"KINGDOM BEST LIMITED (d2010-04-09)"},{"lang":"hk","v":"帝派有限公司"}],"company_since":"1997-05-14","company_dissolved":"2010-04-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607879","names":[{"lang":"en","v":"GAINFAIR HOLDINGS LIMITED"},{"lang":"hk","v":"景星集團有限公司"}],"company_since":"1997-05-14","company_dissolved":"2015-06-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607838","names":[{"lang":"en","v":"GENSON HOLDINGS LIMITED"},{"lang":"hk","v":"精訊集團有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608014","names":[{"lang":"en","v":"KONGTEX (H.K.) LIMITED"},{"lang":"hk","v":"港達(原料)有限公司"}],"company_since":"1997-05-14","company_dissolved":"2001-02-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607970","names":[{"lang":"en","v":"KOON CHIU JEWELLERY (HONG KONG) LIMITED"},{"lang":"hk","v":"冠超珠寶(香港)有限公司"}],"company_since":"1997-05-14","company_dissolved":"2019-01-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607777","names":[{"lang":"en","v":"KUANG LIN INTERNATIONAL TRADING LIMITED"},{"lang":"hk","v":"廣林國際貿易有限公司"}],"company_since":"1997-05-14","company_dissolved":"2014-03-07","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607802","names":[{"lang":"en","v":"LABEL TECH CO. LIMITED"},{"lang":"hk","v":"標籤科技有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607798","names":[{"lang":"en","v":"LAP FAI (GLOBAL) ENTERPRISES COMPANY LIMITED"},{"lang":"hk","v":"立輝(環球)企業有限公司"}],"company_since":"1997-05-14","company_dissolved":"2001-06-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607725","names":[{"lang":"en","v":"LEGEND TRADING (HOLDINGS) CO. LIMITED"},{"lang":"hk","v":"基信洋行(集團)有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608011","names":[{"lang":"en","v":"LIGHTBULB CONSULTANTS LIMITED"},{"lang":"hk","v":"力博顧問有限公司"}],"company_since":"1997-05-14","company_dissolved":"2009-02-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607926","names":[{"lang":"en","v":"LIGHTHOUSE ELEVATOR ENGINEERING LIMITED"},{"lang":"hk","v":"東哲電梯工程有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607767","names":[{"lang":"en","v":"LINK EASY INVESTMENT LIMITED"},{"lang":"hk","v":"怡滙投資有限公司"}],"company_since":"1997-05-14","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608024","names":[{"lang":"en","v":"GREATEST ADVERTISING COMPANY LIMITED"},{"lang":"hk","v":"傑思廣告有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607878","names":[{"lang":"en","v":"LUCKY LOYAL INVESTMENT LIMITED (d2004-11-12)"},{"lang":"hk","v":"利朗投資有限公司"}],"company_since":"1997-05-14","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608017","names":[{"lang":"en","v":"LUEN YEE INDUSTRIAL LIMITED (d2004-11-12)"},{"lang":"hk","v":"聯誼實業有限公司"}],"company_since":"1997-05-14","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607969","names":[{"lang":"en","v":"LYK ENGINEERING SERVICES LIMITED"},{"lang":"hk","v":"浩明工程服務有限公司"}],"company_since":"1997-05-14","company_dissolved":"2008-05-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"607971","names":[{"lang":"en","v":"HIGHLAND REGAL (ASIA) LIMITED"}],"company_since":"1997-05-14","company_dissolved":"2001-07-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607928","names":[{"lang":"en","v":"MATRON (ASIA) INDUSTRIAL COMPANY LIMITED"},{"lang":"hk","v":"美昌(亞洲)實業有限公司"}],"company_since":"1997-05-14","company_dissolved":"2000-12-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607923","names":[{"lang":"en","v":"HING FAI TEXTILE LIMITED"},{"lang":"hk","v":"興輝紡織有限公司"}],"company_since":"1997-05-14","company_dissolved":"2009-10-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607956","names":[{"lang":"en","v":"MAX ELEGANT DEVELOPMENT LIMITED"},{"lang":"hk","v":"萬偉發展有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608003","names":[{"lang":"en","v":"HONG KONG CMS GROUP CO., LIMITED"},{"lang":"hk","v":"香港鈺鼎(集團)有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607900","names":[{"lang":"en","v":"MAY ART FURNITURE COMPANY LIMITED"},{"lang":"hk","v":"美雅傢俬有限公司"}],"company_since":"1997-05-14","company_dissolved":"2004-08-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607805","names":[{"lang":"en","v":"MEGA GEOGI HOLDING LIMITED"},{"lang":"hk","v":"美芝連鎖店集團有限公司"}],"company_since":"1997-05-14","company_dissolved":"2004-09-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607867","names":[{"lang":"en","v":"MEI SANG SOFA COMPANY LIMITED"},{"lang":"hk","v":"美生梳化有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-05-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607897","names":[{"lang":"en","v":"HUA-XING CONSTRUCTION CO., LIMITED"},{"lang":"hk","v":"華興建設建築有限公司"}],"company_since":"1997-05-14","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607780","names":[{"lang":"en","v":"MILLION TECH PROPERTY LIMITED"},{"lang":"hk","v":"萬碧物業有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607963","names":[{"lang":"en","v":"INDUSTRIAL ECONOMY PUBLISHER LIMITED"},{"lang":"hk","v":"產經出版社有限公司"}],"company_since":"1997-05-14","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607824","names":[{"lang":"en","v":"MING SANG METAL MACHINERY FACTORY LIMITED"},{"lang":"hk","v":"明生五金機械工程有限公司"}],"company_since":"1997-05-14","company_dissolved":"2020-01-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608029","names":[{"lang":"en","v":"MONTEREY DESIGN TRADING COMPANY LIMITED"}],"company_since":"1997-05-14","company_dissolved":"2002-01-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607934","names":[{"lang":"en","v":"NEW EXPRESS MODE LIMITED"},{"lang":"hk","v":"新特佳速遞有限公司"}],"company_since":"1997-05-14","company_dissolved":"2003-02-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607750","names":[{"lang":"en","v":"NEW YORK MARBLE COMPANY LIMITED"},{"lang":"hk","v":"紐約石材有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-06-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607888","names":[{"lang":"en","v":"IVY GROUP OF EDUCATION (INTERNATIONAL) LIMITED"},{"lang":"hk","v":"常春藤教育機構(國際)有限公司"}],"company_since":"1997-05-14","company_dissolved":"2005-01-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607865","names":[{"lang":"en","v":"JIAN HUA HONG KONG LIMITED"}],"company_since":"1997-05-14","company_dissolved":"2007-08-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607795","names":[{"lang":"en","v":"NEWAYS INTERNATIONAL LIMITED"},{"lang":"hk","v":"紐威仕國際有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607980","names":[{"lang":"en","v":"JIU ZHOU INTERNATIONAL MEDICINE (HOLDINGS) CO. LIMITED"},{"lang":"hk","v":"九洲國際葯業(集團)有限公司"}],"company_since":"1997-05-14","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607929","names":[{"lang":"en","v":"NICHICA (H.K.) LIMITED"},{"lang":"hk","v":"尼奇卡(香港)有限公司"}],"company_since":"1997-05-14","company_dissolved":"2013-01-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607921","names":[{"lang":"en","v":"GOOD TASTE GROUP LIMITED"},{"lang":"hk","v":"津味集團有限公司"}],"company_since":"1997-05-14","company_dissolved":"2014-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607860","names":[{"lang":"en","v":"NORTH SMART INTERNATIONAL LIMITED"},{"lang":"hk","v":"北津國際有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-07-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608021","names":[{"lang":"en","v":"NOVOCARGO ASIA LIMITED"},{"lang":"hk","v":"卓新航運(亞洲)有限公司"}],"company_since":"1997-05-14","company_dissolved":"2017-04-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607720","names":[{"lang":"en","v":"OCEAN GREAT HOLDINGS LIMITED (d2009-11-06)"},{"lang":"hk","v":"宏洋集團有限公司"}],"company_since":"1997-05-14","company_dissolved":"2009-11-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607954","names":[{"lang":"en","v":"OLIVER (HK) JEWELLERY LIMITED"},{"lang":"hk","v":"愛麗華(香港)珠寶金行有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607785","names":[{"lang":"en","v":"ON LAM COMPANY LIMITED"},{"lang":"hk","v":"銨霖有限公司"}],"company_since":"1997-05-14","company_dissolved":"2003-01-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607747","names":[{"lang":"en","v":"ORGANIZING COMMITTEE OF HONG KONG'S INDUSTRIAL &amp; COMMERCIAL SECTORS FOR THE CELEBRATION OF THE RETURN OF HONG KONG LIMITED"},{"lang":"hk","v":"香港工商界慶祝回歸活動籌備委員會有限公司"}],"company_since":"1997-05-14","company_dissolved":"2001-08-23","company_type_txt":"Ltd by guarantee"},
undefined,
undefined,
{"tax_id":"608004","names":[{"lang":"en","v":"KA YICK CATERING GROUP LIMITED"},{"lang":"hk","v":"加億食品集團有限公司"}],"company_since":"1997-05-14","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607870","names":[{"lang":"en","v":"ORIENTAL SYMPHONY LIMITED"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607907","names":[{"lang":"en","v":"OTTENSTEN HONG KONG LIMITED"}],"company_since":"1997-05-14","company_dissolved":"2011-12-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607998","names":[{"lang":"en","v":"OUTREACH CONSULTANT LIMITED"}],"company_since":"1997-05-14","company_dissolved":"2002-04-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607992","names":[{"lang":"en","v":"KAZU INTERNATIONAL CO., LIMITED"},{"lang":"hk","v":"盛陽(香港)有限公司"}],"company_since":"1997-05-14","company_dissolved":"2003-06-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608001","names":[{"lang":"en","v":"KENIX TRADING LIMITED"},{"lang":"hk","v":"基宜貿易有限公司"}],"company_since":"1997-05-14","company_dissolved":"2008-06-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608030","names":[{"lang":"en","v":"KENINE TRADING COMPANY LIMITED"},{"lang":"hk","v":"堅利貿易有限公司"}],"company_since":"1997-05-14","company_dissolved":"2020-04-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607847","names":[{"lang":"en","v":"PACIFIC FAVOUR ENTERPRISES LIMITED"},{"lang":"hk","v":"泊汶有限公司"}],"company_since":"1997-05-14","company_dissolved":"2013-08-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607771","names":[{"lang":"en","v":"PARACHEM HONG KONG LIMITED"},{"lang":"hk","v":"保國香港有限公司"}],"company_since":"1997-05-14","company_dissolved":"2001-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607709","names":[{"lang":"en","v":"PO FUNG DECORATION MATERIALS LIMITED"},{"lang":"hk","v":"寶豐裝飾材料有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607744","names":[{"lang":"en","v":"PRA GROUP ASIA LIMITED"}],"company_since":"1997-05-14","company_dissolved":"2003-02-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607877","names":[{"lang":"en","v":"PRIMEHOUSE INTERNATIONAL LIMITED"},{"lang":"hk","v":"百勝行國際有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"607889","names":[{"lang":"en","v":"KONG YUNG INTERNATIONAL LIMITED"},{"lang":"hk","v":"港榕國際有限公司"}],"company_since":"1997-05-14","company_dissolved":"2014-09-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607979","names":[{"lang":"en","v":"KONG LUNG WATCHES LIMITED"},{"lang":"hk","v":"港龍錶業有限公司"}],"company_since":"1997-05-14","company_dissolved":"2014-01-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607840","names":[{"lang":"en","v":"PRIMESPOT HOLDINGS LIMITED"},{"lang":"hk","v":"寶沛集團有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607918","names":[{"lang":"en","v":"PROJECT KING PROPERTIES LIMITED"},{"lang":"hk","v":"邦建置業有限公司"}],"company_since":"1997-05-14","company_dissolved":"2001-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608000","names":[{"lang":"en","v":"PuShang Eco-Construction Materials Limited"},{"lang":"hk","v":"甫尚環保建材有限公司"}],"company_since":"1997-05-14","company_dissolved":"2013-07-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607913","names":[{"lang":"en","v":"JUMBO FAMILY LIMITED"},{"lang":"hk","v":"大家庭有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607743","names":[{"lang":"en","v":"Q EVENTS LIMITED (d2006-10-20)"}],"company_since":"1997-05-14","company_dissolved":"2006-10-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607817","names":[{"lang":"en","v":"RAMUS INTERNATIONAL LIMITED"},{"lang":"hk","v":"日茂國際有限公司"}],"company_since":"1997-05-14","company_dissolved":"2012-07-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607925","names":[{"lang":"en","v":"RECREATIONS ENTERPRISES COMPANY LIMITED"},{"lang":"hk","v":"紅海企業有限公司"}],"company_since":"1997-05-14","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608007","names":[{"lang":"en","v":"RELIABLE CORPORATE SERVICES LIMITED"},{"lang":"hk","v":"毅高秘書服務有限公司"}],"company_since":"1997-05-14","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607880","names":[{"lang":"en","v":"RICH EXPRESS DEVELOPMENT LIMITED"},{"lang":"hk","v":"匯裕發展有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607959","names":[{"lang":"en","v":"RNK DEVELOPMENT LIMITED"},{"lang":"hk","v":"威力高有限公司"}],"company_since":"1997-05-14","company_dissolved":"2008-11-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607892","names":[{"lang":"en","v":"LONG CHARIOT INVESTMENT LIMITED"},{"lang":"hk","v":"駿龍威投資有限公司"}],"company_since":"1997-05-14","company_dissolved":"2001-09-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607783","names":[{"lang":"en","v":"SANSHO H.K. CO., LIMITED"},{"lang":"hk","v":"三昌商事有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607737","names":[{"lang":"en","v":"SCS EXPRESS INTERNATIONAL LIMITED"},{"lang":"hk","v":"偉邦國際速遞有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607977","names":[{"lang":"en","v":"SEKORM LIMITED"},{"lang":"hk","v":"世強控股有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608025","names":[{"lang":"en","v":"MAINLAND MARKETING LIMITED (d2002-11-22)"},{"lang":"hk","v":"地域拓展有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-11-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607919","names":[{"lang":"en","v":"SENTRY (HONG KONG) LIMITED"},{"lang":"hk","v":"成智(香港)有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607936","names":[{"lang":"en","v":"MANSON ENGINEERING LIMITED"},{"lang":"hk","v":"明順工程有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607714","names":[{"lang":"en","v":"MASTERSCIENCE INTERNATIONAL COMPANY LIMITED"}],"company_since":"1997-05-14","company_dissolved":"2002-03-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607755","names":[{"lang":"en","v":"SHEEN KIND LIMITED (d2005-06-03)"},{"lang":"hk","v":"順仁有限公司"}],"company_since":"1997-05-14","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608019","names":[{"lang":"en","v":"SHIN WOO (H.K.) LIMITED"},{"lang":"hk","v":"新宇(香港)有限公司"}],"company_since":"1997-05-14","company_dissolved":"2009-12-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607861","names":[{"lang":"en","v":"SHINNING (ASIA) COMPANY LIMITED"},{"lang":"hk","v":"金亮(亞洲)有限公司"}],"company_since":"1997-05-14","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607931","names":[{"lang":"en","v":"MAXSKY INTERNATIONAL LIMITED"},{"lang":"hk","v":"萬天國際有限公司"}],"company_since":"1997-05-14","company_dissolved":"2003-07-25","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607732","names":[{"lang":"en","v":"SHUN MING CONSTRUCTION COMPANY LIMITED"},{"lang":"hk","v":"順銘建築有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607991","names":[{"lang":"en","v":"SINOWIN DECORATION &amp; DESIGN LIMITED"},{"lang":"hk","v":"粵華裝修設計有限公司"}],"company_since":"1997-05-14","company_dissolved":"2001-09-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607845","names":[{"lang":"en","v":"SKY EVER ENTERPRISES LIMITED"},{"lang":"hk","v":"天長企業有限公司"}],"company_since":"1997-05-14","company_dissolved":"2011-03-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607952","names":[{"lang":"en","v":"MIL ASSET MANAGEMENT GROUP LIMITED"},{"lang":"hk","v":"美高產業管理集團有限公司"}],"company_since":"1997-05-14","company_dissolved":"2015-06-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607786","names":[{"lang":"en","v":"SOMMERVILLE TERRACE LIMITED"}],"company_since":"1997-05-14","company_dissolved":"2009-09-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607779","names":[{"lang":"en","v":"MILLION TECH HOLDINGS LIMITED"},{"lang":"hk","v":"萬碧集團有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607988","names":[{"lang":"en","v":"SPDB International Holdings Limited"},{"lang":"hk","v":"浦銀國際控股有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607796","names":[{"lang":"en","v":"SPECIALIFE DESIGN AND PACKAGING LIMITED"},{"lang":"hk","v":"超雅包裝有限公司"}],"company_since":"1997-05-14","company_dissolved":"2010-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607876","names":[{"lang":"en","v":"ST. YALE ACADEMY LIMITED (THE)"},{"lang":"hk","v":"聖業書院有限公司"}],"company_since":"1997-05-14","company_dissolved":"2004-12-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607815","names":[{"lang":"en","v":"SUMMIT WIN INTERNATIONAL LIMITED"},{"lang":"hk","v":"成永國際有限公司"}],"company_since":"1997-05-14","company_dissolved":"2001-07-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607896","names":[{"lang":"en","v":"NEW CROWN DEVELOPMENT LIMITED"},{"lang":"hk","v":"新冠發展有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607974","names":[{"lang":"en","v":"SUN WING STATIONERY MANUFACTURING COMPANY LIMITED"},{"lang":"hk","v":"新榮文具製品有限公司"}],"company_since":"1997-05-14","company_dissolved":"2003-02-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607962","names":[{"lang":"en","v":"SUNTRUST ASIA, LIMITED"}],"company_since":"1997-05-14","company_dissolved":"2011-08-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607716","names":[{"lang":"en","v":"SUPER STAR PROPERTY LIMITED"},{"lang":"hk","v":"星威物業有限公司"}],"company_since":"1997-05-14","company_dissolved":"2015-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607740","names":[{"lang":"en","v":"NICE PEACE FASHION CO., LIMITED"},{"lang":"hk","v":"和欣時裝有限公司"}],"company_since":"1997-05-14","company_dissolved":"2000-12-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608002","names":[{"lang":"en","v":"SYNERGY (FAR EAST) LIMITED"},{"lang":"hk","v":"思力(遠東)有限公司"}],"company_since":"1997-05-14","company_dissolved":"2003-09-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607772","names":[{"lang":"en","v":"T &amp; L INDUSTRIES COMPANY LIMITED"},{"lang":"hk","v":"好友實業有限公司"}],"company_since":"1997-05-14","company_dissolved":"2001-05-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607984","names":[{"lang":"en","v":"NNB TRADING COMPANY LIMITED"}],"company_since":"1997-05-14","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607987","names":[{"lang":"en","v":"TA KWU LING PROPERTY CONSULTANCY LIMITED"},{"lang":"hk","v":"打鼓嶺物業顧問有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-01-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607711","names":[{"lang":"en","v":"TAIWAN SUN TAI FONG FOOTWEAR LIMITED"},{"lang":"hk","v":"台灣新大方鞋業股份有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607997","names":[{"lang":"en","v":"TALENTS MANAGEMENT CONSULTING SERVICES CO. LIMITED"},{"lang":"hk","v":"才俊管理顧問有限公司"}],"company_since":"1997-05-14","company_dissolved":"2005-07-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607961","names":[{"lang":"en","v":"Omnicom Services Asia Pacific Limited"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607855","names":[{"lang":"en","v":"TEAM LUCKY LIMITED (d2003-05-09)"},{"lang":"hk","v":"添樂有限公司"}],"company_since":"1997-05-14","company_dissolved":"2003-05-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607935","names":[{"lang":"en","v":"ORIENTAL HARVEST PROPERTIES LIMITED"},{"lang":"hk","v":"東凱置業有限公司"}],"company_since":"1997-05-14","company_dissolved":"2001-08-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607932","names":[{"lang":"en","v":"TEAMNICE TRAVEL LIMITED"},{"lang":"hk","v":"仟悅旅行社有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607946","names":[{"lang":"en","v":"TEAMSTAR INVESTMENT LIMITED (d2002-05-24)"},{"lang":"hk","v":"添星投資有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-05-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607836","names":[{"lang":"en","v":"TECWIN HOLDINGS LIMITED"},{"lang":"hk","v":"多勝集團有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607862","names":[{"lang":"en","v":"P.T. MANAGEMENT &amp; CONSULTANT LIMITED"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607883","names":[{"lang":"en","v":"TENG LONG INTERNATIONAL (GROUP) COMPANY LIMITED"},{"lang":"hk","v":"騰龍國際(集團)投資有限公司"}],"company_since":"1997-05-14","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607903","names":[{"lang":"en","v":"PACIFIC INTERNATIONAL TRADING LIMITED (d2000-12-22)"},{"lang":"hk","v":"太平洋國際商務有限公司"}],"company_since":"1997-05-14","company_dissolved":"2000-12-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607745","names":[{"lang":"en","v":"TIN WO HONG (SAN SANG) COMPANY LIMITED"},{"lang":"hk","v":"天和行(新生)有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-12-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607957","names":[{"lang":"en","v":"TOP FORTUNE CONSULTANTS LIMITED (d2002-05-24)"},{"lang":"hk","v":"宏通顧問有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-05-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607902","names":[{"lang":"en","v":"PANG MEI CONSTRUCTION COMPANY LIMITED"},{"lang":"hk","v":"鵬美建築有限公司"}],"company_since":"1997-05-14","company_dissolved":"2001-02-02","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607953","names":[{"lang":"en","v":"TOYTRIX COMPANY LIMITED"},{"lang":"hk","v":"具時有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"608022","names":[{"lang":"en","v":"TRIO STAR INDUSTRIAL LIMITED"},{"lang":"hk","v":"三昇實業有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607826","names":[{"lang":"en","v":"PRIMENET DEVELOPMENT LIMITED"},{"lang":"hk","v":"精訊發展有限公司"}],"company_since":"1997-05-14","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607789","names":[{"lang":"en","v":"TWINSTAR PACKAGING LIMITED"},{"lang":"hk","v":"利寶萊國際有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607916","names":[{"lang":"en","v":"TRENON PROPERTIES LIMITED"},{"lang":"hk","v":"全安置業有限公司"}],"company_since":"1997-05-14","company_dissolved":"2001-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607816","names":[{"lang":"en","v":"ULTRA TREND (HONG KONG) LIMITED"},{"lang":"hk","v":"志昌(香港)有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607989","names":[{"lang":"en","v":"SAMSUNG ELECTRO-MECHANICS (H.K.) LIMITED"},{"lang":"hk","v":"三星電機(香港)有限公司"}],"company_since":"1997-05-14","company_dissolved":"2015-08-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607848","names":[{"lang":"en","v":"WESTLANDS HOLDINGS LIMITED (d2005-01-14)"},{"lang":"hk","v":"華蘭控股有限公司"}],"company_since":"1997-05-14","company_dissolved":"2005-01-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607844","names":[{"lang":"en","v":"WIN JUMBO ENTERPRISES LIMITED"},{"lang":"hk","v":"宏鉅企業有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"607784","names":[{"lang":"en","v":"WING YUE CHONG GINSENG GROUP LIMITED"},{"lang":"hk","v":"榮裕莊參茸集團有限公司"}],"company_since":"1997-05-14","company_dissolved":"2006-09-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607908","names":[{"lang":"en","v":"WINFILE LIMITED"},{"lang":"hk","v":"福利珠寶有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-06-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607904","names":[{"lang":"en","v":"WINBOON INVESTMENT LIMITED"},{"lang":"hk","v":"詠邦投資有限公司"}],"company_since":"1997-05-14","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607752","names":[{"lang":"en","v":"STAR OVERSEAS (H.K.) LIMITED"}],"company_since":"1997-05-14","company_dissolved":"2002-06-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607834","names":[{"lang":"en","v":"WINJAZZ LIMITED (d2006-09-22)"},{"lang":"hk","v":"永雋有限公司"}],"company_since":"1997-05-14","company_dissolved":"2006-09-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607842","names":[{"lang":"en","v":"WINPOST HOLDINGS LIMITED"},{"lang":"hk","v":"詠寶集團有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607906","names":[{"lang":"en","v":"WINPOST LIMITED (d2013-01-04)"},{"lang":"hk","v":"永力寶有限公司"}],"company_since":"1997-05-14","company_dissolved":"2013-01-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608026","names":[{"lang":"en","v":"SKYLAND GROUP CO., LIMITED"},{"lang":"hk","v":"方澤集團有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607843","names":[{"lang":"en","v":"WINCORD HOLDINGS LIMITED"},{"lang":"hk","v":"旺景集團有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-12-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607717","names":[{"lang":"en","v":"WUSAN INTERNATIONAL LIMITED"},{"lang":"hk","v":"互生國際有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-04-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607839","names":[{"lang":"en","v":"WINBOON HOLDINGS LIMITED"},{"lang":"hk","v":"詠邦集團有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607937","names":[{"lang":"en","v":"WIN FAVOUR ENGINEERING LIMITED"},{"lang":"hk","v":"宏鋒工程有限公司"}],"company_since":"1997-05-14","company_dissolved":"2001-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607792","names":[{"lang":"en","v":"WORLDHOLD CHINA LIMITED"},{"lang":"hk","v":"域雄中國有限公司"}],"company_since":"1997-05-14","company_dissolved":"2001-02-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607940","names":[{"lang":"en","v":"XENO LIMITED (d2002-07-26)"},{"lang":"hk","v":"富哲有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-07-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607901","names":[{"lang":"en","v":"TARGS (H.K.) TRADING COMPANY LIMITED"},{"lang":"hk","v":"塔基(香港)貿易有限公司"}],"company_since":"1997-05-14","company_dissolved":"2017-02-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607964","names":[{"lang":"en","v":"TEMPE TRADING ASIA LIMITED"},{"lang":"hk","v":"丹比貿易亞洲有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607825","names":[{"lang":"en","v":"YEE SUN TRANSPORTATION LIMITED"},{"lang":"hk","v":"裕新運輸有限公司"}],"company_since":"1997-05-14","company_dissolved":"2003-10-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607751","names":[{"lang":"en","v":"THOMAS LAW &amp; ASSOCIATES LIMITED"},{"lang":"hk","v":"中商行有限公司"}],"company_since":"1997-05-14","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607967","names":[{"lang":"en","v":"YANG GUANG HONG (HOLDINGS) LIMITED"},{"lang":"hk","v":"陽光紅(集團)有限公司"}],"company_since":"1997-05-14","company_dissolved":"2000-07-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607774","names":[{"lang":"en","v":"XUE YING HUA ENTERPRISES LIMITED"},{"lang":"hk","v":"雪櫻花企業有限公司"}],"company_since":"1997-05-14","company_dissolved":"2000-09-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607994","names":[{"lang":"en","v":"PRIMESTAR CORPORATION LIMITED"},{"lang":"hk","v":"高星行有限公司"}],"company_since":"1997-05-14","company_dissolved":"2000-09-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607914","names":[{"lang":"en","v":"WORLD FOCUS PROPERTIES LIMITED"},{"lang":"hk","v":"世福置業有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-07-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607859","names":[{"lang":"en","v":"UMP EYECARE AND OPTOMETRY CENTRE LIMITED"},{"lang":"hk","v":"聯合醫務眼科保健及視光中心有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607857","names":[{"lang":"en","v":"XENO INTERNATIONAL LIMITED"},{"lang":"hk","v":"富哲國際有限公司"}],"company_since":"1997-05-14","company_dissolved":"2004-10-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607787","names":[{"lang":"en","v":"YICK CHEONG COMPANY LIMITED"}],"company_since":"1997-05-14","company_dissolved":"2012-07-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"607881","names":[{"lang":"en","v":"VACLASS INTERNATIONAL LIMITED"},{"lang":"hk","v":"南欣國際有限公司"}],"company_since":"1997-05-14","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607728","names":[{"lang":"en","v":"VIBO TECHNOLOGY LIMITED (d2002-06-07)"},{"lang":"hk","v":"緯邦科技有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-06-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607739","names":[{"lang":"en","v":"WING LAP CONSTRUCTION COMPANY LIMITED"},{"lang":"hk","v":"永立建築工程有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607895","names":[{"lang":"en","v":"YING SHUN TOBACCO (H.K.) LIMITED"},{"lang":"hk","v":"盈信煙草(香港)有限公司"}],"company_since":"1997-05-14","company_dissolved":"2001-05-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607996","names":[{"lang":"en","v":"VOGUE STEP LIMITED"}],"company_since":"1997-05-14","company_dissolved":"2001-11-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607800","names":[{"lang":"en","v":"YONG FU PLASTICS TECHNIQUE DEVELOPMENT LIMITED"},{"lang":"hk","v":"永孚塑膠技術發展有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-09-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607735","names":[{"lang":"en","v":"WAI WAH TOYS COMPANY LIMITED"},{"lang":"hk","v":"惠華玩具有限公司"}],"company_since":"1997-05-14","company_dissolved":"2001-07-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607828","names":[{"lang":"en","v":"WINBOON DEVELOPMENT LIMITED"},{"lang":"hk","v":"詠邦發展有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607858","names":[{"lang":"en","v":"YOSI INTERNATIONAL LIMITED"},{"lang":"hk","v":"裕哲國際有限公司"}],"company_since":"1997-05-14","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607731","names":[{"lang":"en","v":"YOUNGER SHIPPING LIMITED"},{"lang":"hk","v":"揚格船務有限公司"}],"company_since":"1997-05-14","company_dissolved":"2006-09-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607832","names":[{"lang":"en","v":"WINPOLE INVESTMENT LIMITED"},{"lang":"hk","v":"詠寶投資有限公司"}],"company_since":"1997-05-14","company_dissolved":"2014-02-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607819","names":[{"lang":"en","v":"YOSI LIMITED"},{"lang":"hk","v":"裕哲有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607966","names":[{"lang":"en","v":"YU XING INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"渝興國際有限公司"}],"company_since":"1997-05-14","company_dissolved":"1999-11-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"607734","names":[{"lang":"en","v":"YUE GUANG OVERSEAS COMPANY LIMITED"},{"lang":"hk","v":"粵光海外有限公司"}],"company_since":"1997-05-14","company_dissolved":"2009-10-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607885","names":[{"lang":"en","v":"YUE KEE METAL BUILDING MATERIALS &amp; SANITARY WARE COMPANY LIMITED"},{"lang":"hk","v":"如記五金建材潔具有限公司"}],"company_since":"1997-05-14","company_dissolved":"2003-04-25","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607821","names":[{"lang":"en","v":"WELLDONE CONSTRUCTION COMPANY LIMITED"},{"lang":"hk","v":"祥順建築工程有限公司"}],"company_since":"1997-05-14","company_dissolved":"2012-07-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607924","names":[{"lang":"en","v":"WIN CHAMPION TECHNOLOGY LIMITED"},{"lang":"hk","v":"永鎮有限公司"}],"company_since":"1997-05-14","company_dissolved":"2011-03-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607778","names":[{"lang":"en","v":"ZHONG ZHONG HAO FOOD SERVICES COMPANY LIMITED"},{"lang":"hk","v":"盅盅好食品有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-12-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607788","names":[{"lang":"en","v":"TT ELECTRONICS CHINA LIMITED"}],"company_since":"1997-05-14","company_dissolved":"2018-01-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"607978","names":[{"lang":"en","v":"WANG DIFU (H.K.) LIMITED"},{"lang":"hk","v":"萬蒂福(香港)有限公司"}],"company_since":"1997-05-14","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"607768","names":[{"lang":"en","v":"PLOTIO BUILDING MANAGEMENT COMPANY LIMITED"},{"lang":"hk","v":"百利好物業管理有限公司"}],"company_since":"1997-05-14","company_dissolved":"2011-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"608038","names":[{"lang":"en","v":"ULTRAN TECHNOLOGY DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"友傳科技發展有限公司"}],"company_since":"1997-05-14","company_dissolved":"2006-05-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"607960","names":[{"lang":"en","v":"UMA INTERNATIONAL LIMITED"},{"lang":"hk","v":"耀德行有限公司"}],"company_since":"1997-05-14","company_dissolved":"2002-12-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"607822","names":[{"lang":"en","v":"WIN HARVEST TRADING LIMITED (d2001-05-04)"},{"lang":"hk","v":"匯興貿易有限公司"}],"company_since":"1997-05-14","company_dissolved":"2001-05-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"607775","names":[{"lang":"en","v":"XUE YING HUA DEVELOPMENT LIMITED"},{"lang":"hk","v":"雪櫻花發展有限公司"}],"company_since":"1997-05-14","company_dissolved":"2000-09-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"607886","names":[{"lang":"en","v":"WANG TAT TRADING LIMITED"},{"lang":"hk","v":"宏達建材貿易有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"608027","names":[{"lang":"en","v":"YUEN HING HONG PEARL LIMITED"},{"lang":"hk","v":"源興行珍珠有限公司"}],"company_since":"1997-05-14","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
