{"tax_id":"608176","names":[{"lang":"en","v":"CHELSON TRADING LIMITED"},{"lang":"hk","v":"卓盛貿易有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608145","names":[{"lang":"en","v":"CHEMITRON (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"業煒實業(香港)有限公司"}],"company_since":"1997-05-16","company_dissolved":"2017-12-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608267","names":[{"lang":"en","v":"CHIEF FORD LIMITED"},{"lang":"hk","v":"力振有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-08-23","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608332","names":[{"lang":"en","v":"CHINA INTERNET TECHNOLOGY LIMITED"},{"lang":"hk","v":"中國聯網信息科技有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-06-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608107","names":[{"lang":"en","v":"CHINESE CITIES INVESTIGATION AND RESEARCH (HK) LIMITED"},{"lang":"hk","v":"中國城市調查研究(香港)有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-09-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608389","names":[{"lang":"en","v":"CHINESE INTERNATIONAL MARKETING DEVELOPMENT HOLDINGS LIMITED"},{"lang":"hk","v":"中國國際市場發展集團有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608404","names":[{"lang":"en","v":"CHIU CHOW PAT FOODSTUFF TRADING LIMITED"},{"lang":"hk","v":"潮州捌食品貿易有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-11-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608189","names":[{"lang":"en","v":"CIKACHI ELECTRIC (HONG KONG) LIMITED (d2003-01-10)"},{"lang":"hk","v":"松菱電機(香港)有限公司"}],"company_since":"1997-05-16","company_dissolved":"2003-01-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608220","names":[{"lang":"en","v":"CLAYTON CLAYMORE (INTERNATIONAL) LIMITED"},{"lang":"hk","v":"機騰(國際)有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-12-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608095","names":[{"lang":"en","v":"CLEVER WIDE LIMITED"},{"lang":"hk","v":"京浩有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608210","names":[{"lang":"en","v":"COMING WELL LIMITED"},{"lang":"hk","v":"欣來有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608177","names":[{"lang":"en","v":"CONCORD SKY INTERNATIONAL LIMITED"},{"lang":"hk","v":"和宇國際有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608354","names":[{"lang":"en","v":"CONSOLID (CHINA) PROPERTIES LIMITED"},{"lang":"hk","v":"康瑞(中國)置業有限公司"}],"company_since":"1997-05-16","company_dissolved":"2017-12-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608158","names":[{"lang":"en","v":"COSMOS BIG LIMITED"},{"lang":"hk","v":"金利大有限公司"}],"company_since":"1997-05-16","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608156","names":[{"lang":"en","v":"COSMOS MEN LIMITED"},{"lang":"hk","v":"金利文有限公司"}],"company_since":"1997-05-16","company_dissolved":"2011-01-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608116","names":[{"lang":"en","v":"CREATIVE HONOR LIMITED"},{"lang":"hk","v":"創勳有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608327","names":[{"lang":"en","v":"D.B. GROUP CHINA LIMITED"},{"lang":"hk","v":"得寶國際貨運有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608208","names":[{"lang":"en","v":"DAEDALUS HARDWOOD AND TILES LIMITED"}],"company_since":"1997-05-16","company_dissolved":"2001-08-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608258","names":[{"lang":"en","v":"DERUDDER SHIPPING LIMITED"}],"company_since":"1997-05-16","company_dissolved":"2001-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608109","names":[{"lang":"en","v":"DIGITAL CREATION COMPANY LIMITED"},{"lang":"hk","v":"數碼創作有限公司"}],"company_since":"1997-05-16","company_dissolved":"2007-11-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608111","names":[{"lang":"en","v":"DO MO LIMITED"},{"lang":"hk","v":"景雄銷售有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608343","names":[{"lang":"en","v":"DOVE LINK (HK) LIMITED"},{"lang":"hk","v":"迅連推廣發展(香港)有限公司"}],"company_since":"1997-05-16","company_dissolved":"2003-01-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608126","names":[{"lang":"en","v":"DRAGON GOODIES DEVELOPMENT LIMITED"},{"lang":"hk","v":"龍一發展有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608232","names":[{"lang":"en","v":"DRAGON SOURCE DEVELOPMENT LIMITED"},{"lang":"hk","v":"龍港發展有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-05-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608167","names":[{"lang":"en","v":"EAST GLORY (H.K.) LIMITED"},{"lang":"hk","v":"東亮(香港)有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608174","names":[{"lang":"en","v":"EASTERN LANE TRADING LIMITED"},{"lang":"hk","v":"東寧貿易有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608187","names":[{"lang":"en","v":"EASTERN WINNER LIMITED"},{"lang":"hk","v":"港超有限公司"}],"company_since":"1997-05-16","company_dissolved":"2017-09-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608102","names":[{"lang":"en","v":"EVER APEX (HK) LIMITED"},{"lang":"hk","v":"群峰(香港)有限公司"}],"company_since":"1997-05-16","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608249","names":[{"lang":"en","v":"EVERFORD INVESTMENT LIMITED (d2005-05-13)"},{"lang":"hk","v":"恒博投資有限公司"}],"company_since":"1997-05-16","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608101","names":[{"lang":"en","v":"EVERLONG (HK) LIMITED (d2004-11-12)"},{"lang":"hk","v":"朗達(香港)有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608053","names":[{"lang":"en","v":"EXCEL GROUP TRANSPORTATION LIMITED"},{"lang":"hk","v":"協通貨運有限公司"}],"company_since":"1997-05-16","company_dissolved":"2017-07-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608088","names":[{"lang":"en","v":"EXCEL MARK CONSULTANTS LIMITED"},{"lang":"hk","v":"裕順顧問有限公司"}],"company_since":"1997-05-16","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608050","names":[{"lang":"en","v":"EXCEL PROFIT TRADING LIMITED"},{"lang":"hk","v":"正榮貿易有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608244","names":[{"lang":"en","v":"EXCEL SINO LIMITED"},{"lang":"hk","v":"立添有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608123","names":[{"lang":"en","v":"EXCEL SUCCESS CONSULTANTS LIMITED"},{"lang":"hk","v":"栢達顧問有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608054","names":[{"lang":"en","v":"EXCEL SUCCESS ENTERPRISES LIMITED (d2002-06-07)"},{"lang":"hk","v":"本駿企業有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-06-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608415","names":[{"lang":"en","v":"EXCELLENCE YT LIMITED"}],"company_since":"1997-05-16","company_dissolved":"2012-07-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608125","names":[{"lang":"en","v":"EXCEL MARK ENTERPRISES LIMITED"},{"lang":"hk","v":"廸晉企業有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-08-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608329","names":[{"lang":"en","v":"FOCAL PAPER PRODUCTS FACTORY LIMITED"},{"lang":"hk","v":"富濠紙製品廠有限公司"}],"company_since":"1997-05-16","company_dissolved":"2014-09-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608278","names":[{"lang":"en","v":"FORTUNE HONOUR INDUSTRIAL LIMITED"},{"lang":"hk","v":"福誠實業有限公司"}],"company_since":"1997-05-16","company_dissolved":"2003-10-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608072","names":[{"lang":"en","v":"FORTUNE PROPERTY AGENCY LIMITED (d2006-09-22)"},{"lang":"hk","v":"天富地產有限公司"}],"company_since":"1997-05-16","company_dissolved":"2006-09-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608243","names":[{"lang":"en","v":"FORTUNE SKY LIMITED"},{"lang":"hk","v":"傑亮有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608294","names":[{"lang":"en","v":"FSU FREIGHT (H.K.) LIMITED"}],"company_since":"1997-05-16","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608224","names":[{"lang":"en","v":"FULCOM (MARSHAL) COMPANY LIMITED"},{"lang":"hk","v":"富鴻(馬素)有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"608067","names":[{"lang":"en","v":"CHAMPION TAT LIMITED"},{"lang":"hk","v":"貫達有限公司"}],"company_since":"1997-05-16","company_dissolved":"2008-07-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608241","names":[{"lang":"en","v":"FUTURE WAY LIMITED"},{"lang":"hk","v":"廣勤有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608310","names":[{"lang":"en","v":"GALIN DEVELOPMENT LIMITED"},{"lang":"hk","v":"佳凌發展有限公司"}],"company_since":"1997-05-16","company_dissolved":"2008-01-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608308","names":[{"lang":"en","v":"GAMOUR HOLDINGS LIMITED"},{"lang":"hk","v":"佳懋集團有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608276","names":[{"lang":"en","v":"CHIBA DIES HONG KONG CO., LIMITED"}],"company_since":"1997-05-16","company_dissolved":"2015-03-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608313","names":[{"lang":"en","v":"GATER TRADING LIMITED"},{"lang":"hk","v":"佳綽貿易有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608261","names":[{"lang":"en","v":"GATON HOLDINGS LIMITED"},{"lang":"hk","v":"佳通集團有限公司"}],"company_since":"1997-05-16","company_dissolved":"2001-07-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608143","names":[{"lang":"en","v":"CHETAL INTERNATIONAL LIMITED"},{"lang":"hk","v":"志都國際有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-08-23","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608284","names":[{"lang":"en","v":"GENIUS CORPORATION LIMITED (d2006-10-27)"},{"lang":"hk","v":"利俊行有限公司"}],"company_since":"1997-05-16","company_dissolved":"2006-10-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608154","names":[{"lang":"en","v":"GEORGE &amp; ASSOCIATES LIMITED"},{"lang":"hk","v":"全慧設計工程有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608118","names":[{"lang":"en","v":"GEORLI COMPANY LIMITED"},{"lang":"hk","v":"佑寧有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608087","names":[{"lang":"en","v":"GIANT PROFIT ENTERPRISES LIMITED (HK)"},{"lang":"hk","v":"國發企業有限公司"}],"company_since":"1997-05-16","company_dissolved":"2017-12-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608242","names":[{"lang":"en","v":"GOLD HARBOUR LAND DEVELOPMENT LIMITED"},{"lang":"hk","v":"金港地產發展有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-05-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608150","names":[{"lang":"en","v":"GOLDEN GENIUS ENTERPRISES MANAGEMENT LIMITED"},{"lang":"hk","v":"金俊企業管理有限公司"}],"company_since":"1997-05-16","company_dissolved":"2010-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608218","names":[{"lang":"en","v":"GOLDEN STARS LIMITED (d2000-09-22)"},{"lang":"hk","v":"金三星有限公司"}],"company_since":"1997-05-16","company_dissolved":"2000-09-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608105","names":[{"lang":"en","v":"GOOD EASTERN INTERNATIONAL LIMITED"},{"lang":"hk","v":"東韋國際有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608104","names":[{"lang":"en","v":"GOOD EASTERN LIMITED"},{"lang":"hk","v":"東韋有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-03-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608413","names":[{"lang":"en","v":"GOOD GRACE ENGINEERING LIMITED"},{"lang":"hk","v":"志亮工程有限公司"}],"company_since":"1997-05-16","company_dissolved":"2020-11-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608264","names":[{"lang":"en","v":"GRADEN LIMITED"},{"lang":"hk","v":"加通有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608262","names":[{"lang":"en","v":"GRAND CREATION CONSULTANTS LIMITED"},{"lang":"hk","v":"佳創顧問有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608360","names":[{"lang":"en","v":"GRAND OCEAN TECHNOLOGY LIMITED (d2006-01-13)"},{"lang":"hk","v":"佳洋科技有限公司"}],"company_since":"1997-05-16","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608248","names":[{"lang":"en","v":"GRAND WISE (HONG KONG) LIMITED"},{"lang":"hk","v":"利廣(香港)有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608144","names":[{"lang":"en","v":"GRASON INTERNATIONAL LIMITED"},{"lang":"hk","v":"加新國際有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608140","names":[{"lang":"en","v":"EAST COSMOS LIMITED"},{"lang":"hk","v":"東之源有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-11-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608374","names":[{"lang":"en","v":"GREAT EAST PACKAGING (HONG KONG) LIMITED"},{"lang":"hk","v":"偉東包裝製品(香港)有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608366","names":[{"lang":"en","v":"GREAT FAIR ENTERPRISES LIMITED"},{"lang":"hk","v":"宏暉企業有限公司"}],"company_since":"1997-05-16","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608194","names":[{"lang":"en","v":"GREAT JADE INVESTMENTS LIMITED"},{"lang":"hk","v":"宏翠投資有限公司"}],"company_since":"1997-05-16","company_dissolved":"2007-09-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608311","names":[{"lang":"en","v":"GREAT SUPREME TRADING LIMITED"},{"lang":"hk","v":"佳振貿易有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608250","names":[{"lang":"en","v":"GREAT WEAL LIMITED"},{"lang":"hk","v":"博宏有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608221","names":[{"lang":"en","v":"ELITE GLOBAL FLEXITANK LIMITED"},{"lang":"hk","v":"益利環球集裝箱液罐袋有限公司"}],"company_since":"1997-05-16","company_dissolved":"2015-03-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608302","names":[{"lang":"en","v":"GREATWAY TECHNOLOGY LIMITED"},{"lang":"hk","v":"佳威科技有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-07-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608405","names":[{"lang":"en","v":"ENHANCED ASSETS &amp; FACILITIES MANAGEMENT LIMITED"},{"lang":"hk","v":"嘉強資產設施管理有限公司"}],"company_since":"1997-05-16","company_dissolved":"2006-11-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608103","names":[{"lang":"en","v":"GROUP APEX DEVELOPMENT LIMITED"},{"lang":"hk","v":"群峰發展有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608164","names":[{"lang":"en","v":"GUIDE TECH LIMITED (d2002-12-13)"},{"lang":"hk","v":"佳利達有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-12-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608205","names":[{"lang":"en","v":"GUYLINE (ASIA) LIMITED"},{"lang":"hk","v":"皆能(亞洲)有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608403","names":[{"lang":"en","v":"GZTC INTERNATIONAL TOUR COMPANY LIMITED"},{"lang":"hk","v":"廣之旅國際旅遊有限公司"}],"company_since":"1997-05-16","company_dissolved":"2011-11-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608203","names":[{"lang":"en","v":"Heavy2Light Oil Technologies Holdings Limited"}],"company_since":"1997-05-16","company_dissolved":"2013-11-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608255","names":[{"lang":"en","v":"HERO CORPORATION LIMITED (d2002-11-08)"},{"lang":"hk","v":"豪傑行有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-11-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608114","names":[{"lang":"en","v":"HI-TECH DECORATION &amp; CONTRACTING COMPANY LIMITED"},{"lang":"hk","v":"人傑裝飾工程有限公司"}],"company_since":"1997-05-16","company_dissolved":"2003-02-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608152","names":[{"lang":"en","v":"HILTON HOLDINGS LIMITED (HK)"},{"lang":"hk","v":"豪敦集團有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608382","names":[{"lang":"en","v":"HING YIP TRADING LIMITED (d2000-10-13)"},{"lang":"hk","v":"興業(迪賽爾)有限公司"}],"company_since":"1997-05-16","company_dissolved":"2000-10-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608323","names":[{"lang":"en","v":"HKBOOK. COM LIMITED"},{"lang":"hk","v":"香港書網有限公司"}],"company_since":"1997-05-16","company_dissolved":"2001-08-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608055","names":[{"lang":"en","v":"EXCEL SUCCESS INVESTMENT LIMITED (d2001-09-21)"},{"lang":"hk","v":"本駿投資有限公司"}],"company_since":"1997-05-16","company_dissolved":"2001-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608165","names":[{"lang":"en","v":"HONEST EVER INTERNATIONAL LIMITED"},{"lang":"hk","v":"誠恒國際有限公司"}],"company_since":"1997-05-16","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608303","names":[{"lang":"en","v":"FORMULA TWO INVESTMENT LIMITED"}],"company_since":"1997-05-16","company_dissolved":"2020-01-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608362","names":[{"lang":"en","v":"HONG KONG 345 INTERNATIONAL HOTEL EQUIPMENT SUPPLY LIMITED"},{"lang":"hk","v":"香港345國際酒店設備供應有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-11-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608400","names":[{"lang":"en","v":"HONG KONG SUN-POWER INTERNATIONAL LIMITED"},{"lang":"hk","v":"香港聖保利國際有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608128","names":[{"lang":"en","v":"HONG KONG TIAN YI INTERNATIONAL ADVERTISING CO., LIMITED"},{"lang":"hk","v":"香港天藝國際廣告有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-02-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608288","names":[{"lang":"en","v":"FUKUMORI &amp; COMPANY LIMITED"}],"company_since":"1997-05-16","company_dissolved":"2004-11-11","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608204","names":[{"lang":"en","v":"HOPE MING ENTERPRISE LIMITED"},{"lang":"hk","v":"浩茗企業有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-08-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608390","names":[{"lang":"en","v":"HOW JIIN INDUSTRIAL COMPANY LIMITED"},{"lang":"hk","v":"厚錦實業有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-07-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608402","names":[{"lang":"en","v":"HUANG JIA LIGHTING CO., LIMITED"},{"lang":"hk","v":"皇家五金燈飾股份有限公司"}],"company_since":"1997-05-16","company_dissolved":"2012-07-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608409","names":[{"lang":"en","v":"HUNG HING METAL LIMITED"},{"lang":"hk","v":"雄興五金有限公司"}],"company_since":"1997-05-16","company_dissolved":"2003-06-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608315","names":[{"lang":"en","v":"GALIN ENTERPRISES LIMITED"},{"lang":"hk","v":"佳凌企業有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-08-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608395","names":[{"lang":"en","v":"HUNG LEE MOTORS COMPANY LIMITED"},{"lang":"hk","v":"鴻利汽車有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608328","names":[{"lang":"en","v":"HUNG TAI TRADING INTERNATIONAL LIMITED"},{"lang":"hk","v":"鴻泰貿易國際有限公司"}],"company_since":"1997-05-16","company_dissolved":"2001-08-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608120","names":[{"lang":"en","v":"IAP LIMITED (d2010-02-19)"}],"company_since":"1997-05-16","company_dissolved":"2010-02-19","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"608358","names":[{"lang":"en","v":"GATER CONSULTANTS LIMITED"},{"lang":"hk","v":"佳綽顧問有限公司"}],"company_since":"1997-05-16","company_dissolved":"2003-02-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"RT0000108","names":[{"lang":"en","v":"INCORPORATED TRUSTEES OF THE UNIVERSAL CHURCH OF THE KINGDOM OF GOD (THE)"},{"lang":"hk","v":"\n普世神的王國教會受託人法團"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Trust"},
undefined,
{"tax_id":"608407","names":[{"lang":"en","v":"INFOCOMM (HONG KONG) LIMITED"},{"lang":"hk","v":"新資訊傳播(香港)有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608098","names":[{"lang":"en","v":"GAVIE RESTAURANT (HOLDING) LIMITED"},{"lang":"hk","v":"嘉益飲食(集團)有限公司"}],"company_since":"1997-05-16","company_dissolved":"2009-08-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608326","names":[{"lang":"en","v":"INTEROVERSEAS CONSULTANCY LIMITED"},{"lang":"hk","v":"海外聯業顧問有限公司"}],"company_since":"1997-05-16","company_dissolved":"2019-10-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608170","names":[{"lang":"en","v":"INTIMATE CURVES MANUFACTURING LIMITED"},{"lang":"hk","v":"爾之美製衣有限公司"}],"company_since":"1997-05-16","company_dissolved":"2001-04-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608192","names":[{"lang":"en","v":"GDL ASSET MANAGEMENT LIMITED"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608207","names":[{"lang":"en","v":"GEELY FASHION CO. LIMITED"},{"lang":"hk","v":"置利服裝有限公司"}],"company_since":"1997-05-16","company_dissolved":"2001-10-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608090","names":[{"lang":"en","v":"INTRA GOOD TRANSPORTATION LIMITED"},{"lang":"hk","v":"天行貨運有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-06-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608130","names":[{"lang":"en","v":"INTRA PROFIT LIMITED"},{"lang":"hk","v":"迪晉有限公司"}],"company_since":"1997-05-16","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608057","names":[{"lang":"en","v":"INTRA SUCCESS INVESTMENT LIMITED"},{"lang":"hk","v":"建晉投資有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-06-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608058","names":[{"lang":"en","v":"INTRA SUCCESS LIMITED"},{"lang":"hk","v":"本駿有限公司"}],"company_since":"1997-05-16","company_dissolved":"2008-06-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608388","names":[{"lang":"en","v":"iWellness Company Limited"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608096","names":[{"lang":"en","v":"GIANT SPIRIT ENTERPRISES LIMITED"},{"lang":"hk","v":"名人企業有限公司"}],"company_since":"1997-05-16","company_dissolved":"2003-02-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608149","names":[{"lang":"en","v":"JADEWORLD INDUSTRIAL LIMITED"},{"lang":"hk","v":"翠威實業有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608379","names":[{"lang":"en","v":"JBV TENNIS CLUB LIMITED"},{"lang":"hk","v":"津堡匯網球俱樂部有限公司"}],"company_since":"1997-05-16","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608273","names":[{"lang":"en","v":"GOLDEN BRIDGE (HK) INDUSTRIAL LIMITED"},{"lang":"hk","v":"金橋(香港)實業有限公司"}],"company_since":"1997-05-16","company_dissolved":"2001-10-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608265","names":[{"lang":"en","v":"JOINT BUSINESS LIMITED (HK)"},{"lang":"hk","v":"群榮有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608129","names":[{"lang":"en","v":"JOYCE PERFECT LIMITED"},{"lang":"hk","v":"綽名有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608206","names":[{"lang":"en","v":"JUN TECH CURTAIN WALL (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"香港峻達幕墻工程有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608041","names":[{"lang":"en","v":"K. S. LIU &amp; COMPANY, C.P.A. LIMITED"},{"lang":"hk","v":"廖廣生會計師事務所有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608217","names":[{"lang":"en","v":"GOOD CODE LIMITED (d2004-11-12)"},{"lang":"hk","v":"佳典有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608281","names":[{"lang":"en","v":"KAM WAN LAND &amp; HOUSING INFORMATION MEDIA LIMITED"},{"lang":"hk","v":"金灣房地產資訊中介有限公司"}],"company_since":"1997-05-16","company_dissolved":"2001-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608069","names":[{"lang":"en","v":"KAWAY DEVELOPMENT LIMITED"},{"lang":"hk","v":"嘉慧發展有限公司"}],"company_since":"1997-05-16","company_dissolved":"2001-11-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608367","names":[{"lang":"en","v":"KING EMPIRE HOLDINGS LIMITED"},{"lang":"hk","v":"帝皇集團有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608195","names":[{"lang":"en","v":"KINGMARK DEVELOPMENTS LIMITED"},{"lang":"hk","v":"京匯發展有限公司"}],"company_since":"1997-05-16","company_dissolved":"2006-12-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608043","names":[{"lang":"en","v":"GRANDWIND DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"森耀發展有限公司"}],"company_since":"1997-05-16","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608364","names":[{"lang":"en","v":"KWONG YIU HONG LIMITED"},{"lang":"hk","v":"廣耀行有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608200","names":[{"lang":"en","v":"LAKERS &amp; BROTHERS DEVELOPMENT LIMITED"},{"lang":"hk","v":"澤力兄弟發展有限公司"}],"company_since":"1997-05-16","company_dissolved":"2000-09-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608384","names":[{"lang":"en","v":"LAREX LIMITED"},{"lang":"hk","v":"立誼有限公司"}],"company_since":"1997-05-16","company_dissolved":"2015-10-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608040","names":[{"lang":"en","v":"LASZLO KINCS WORLDWIDE MUSIC MINISTRIES LIMITED"}],"company_since":"1997-05-16","company_dissolved":"2010-02-19","company_type_txt":"Ltd by guarantee"},
undefined,
undefined,
{"tax_id":"608163","names":[{"lang":"en","v":"LEADER ART LIMITED (d2004-11-12)"},{"lang":"hk","v":"佳利雅有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608108","names":[{"lang":"en","v":"LEADER ELECTRONICS (H.K.) LIMITED"},{"lang":"hk","v":"港商立達股份有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-03-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608225","names":[{"lang":"en","v":"LONG STRONG LIMITED (d2004-11-12)"},{"lang":"hk","v":"祥昌有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608216","names":[{"lang":"en","v":"LOYAL CLASSIC LIMITED"},{"lang":"hk","v":"金佳信有限公司"}],"company_since":"1997-05-16","company_dissolved":"2001-09-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"608292","names":[{"lang":"en","v":"HAMPTON MERX INTERNATIONAL LIMITED"}],"company_since":"1997-05-16","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608161","names":[{"lang":"en","v":"LOYAL TALENT LIMITED (d2003-02-07)"},{"lang":"hk","v":"金之傑有限公司"}],"company_since":"1997-05-16","company_dissolved":"2003-02-07","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608287","names":[{"lang":"en","v":"LUCKY STAR ENTERPRISES (HK) LIMITED"},{"lang":"hk","v":"福星企業(香港)有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608121","names":[{"lang":"en","v":"LUK YEUNG BAPTIST CHURCH LIMITED"},{"lang":"hk","v":"綠楊浸信會有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"608193","names":[{"lang":"en","v":"M.E.I. (CHINA) LIMITED"},{"lang":"hk","v":"恩義安(中國)有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-03-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608240","names":[{"lang":"en","v":"MACRO TECH LIMITED (d2005-02-04)"},{"lang":"hk","v":"科立有限公司"}],"company_since":"1997-05-16","company_dissolved":"2005-02-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608080","names":[{"lang":"en","v":"HIP SHING ELECTRICAL ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"協成機電工程有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608162","names":[{"lang":"en","v":"MASS BRIGHT LIMITED"},{"lang":"hk","v":"華之光有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-11-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"608168","names":[{"lang":"en","v":"HONEST ALL INTERNATIONAL LIMITED"},{"lang":"hk","v":"誠全國際有限公司"}],"company_since":"1997-05-16","company_dissolved":"2009-01-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608166","names":[{"lang":"en","v":"HONEST DAY INTERNATIONAL LIMITED"},{"lang":"hk","v":"誠日國際有限公司"}],"company_since":"1997-05-16","company_dissolved":"2008-11-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608068","names":[{"lang":"en","v":"MASS WAY ENTERPRISES LIMITED"},{"lang":"hk","v":"嘉慧企業有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608132","names":[{"lang":"en","v":"MAXIMUM SOUND INDUSTRIES CO., LIMITED"},{"lang":"hk","v":"恒進香港有限公司"}],"company_since":"1997-05-16","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608408","names":[{"lang":"en","v":"MAYO WENTE INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"沒有問題國際有限公司"}],"company_since":"1997-05-16","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608097","names":[{"lang":"en","v":"MEDICAL ON CALL SERVICES LIMITED"},{"lang":"hk","v":"上門醫生有限公司"}],"company_since":"1997-05-16","company_dissolved":"2008-10-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608246","names":[{"lang":"en","v":"MIAOSHEN INTERIOR DESIGN &amp; CONSTRUCTION COMPANY LIMITED"},{"lang":"hk","v":"淼森裝飾設計工程有限公司"}],"company_since":"1997-05-16","company_dissolved":"2017-11-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608322","names":[{"lang":"en","v":"MIC INDUSTRIAL (HK) LIMITED"}],"company_since":"1997-05-16","company_dissolved":"2001-11-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608411","names":[{"lang":"en","v":"MICRO ART TECHNOLOGY LIMITED"},{"lang":"hk","v":"晉藝科技有限公司"}],"company_since":"1997-05-16","company_dissolved":"2003-11-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608159","names":[{"lang":"en","v":"LOYAL KNITWEAR MANUFACTORY LIMITED"}],"company_since":"1997-05-16","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608127","names":[{"lang":"en","v":"INTRA GOOD LIMITED"},{"lang":"hk","v":"方中有限公司"}],"company_since":"1997-05-16","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608252","names":[{"lang":"en","v":"NEW GOLDEN POOL LIMITED"},{"lang":"hk","v":"新金泉有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608253","names":[{"lang":"en","v":"NEW WATSON LIMITED"},{"lang":"hk","v":"新華盛有限公司"}],"company_since":"1997-05-16","company_dissolved":"2001-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608148","names":[{"lang":"en","v":"NICE &amp; FINE LIMITED"},{"lang":"hk","v":"利而佳有限公司"}],"company_since":"1997-05-16","company_dissolved":"2013-01-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608084","names":[{"lang":"en","v":"NIPPO INTERNATIONAL LOGISTICS (HK) LIMITED"},{"lang":"hk","v":"日本包裝運輸(香港)有限公司"}],"company_since":"1997-05-16","company_dissolved":"2001-03-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608185","names":[{"lang":"en","v":"NOBLE FORD LIMITED"},{"lang":"hk","v":"帝興有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608314","names":[{"lang":"en","v":"ODYSSEY ASIA PACIFIC COMPANY LIMITED"},{"lang":"hk","v":"佳凌亞太有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-03-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608254","names":[{"lang":"en","v":"KA FUNG CONTRACTING &amp; DESIGN LIMITED"},{"lang":"hk","v":"嘉峰裝飾工程有限公司"}],"company_since":"1997-05-16","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608124","names":[{"lang":"en","v":"KIN SANG ENGINEERING CO., LIMITED"},{"lang":"hk","v":"建生鋼閘有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-12-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608334","names":[{"lang":"en","v":"PIONEER POWER LIMITED (d2004-08-13)"},{"lang":"hk","v":"耀勁有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-08-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608414","names":[{"lang":"en","v":"POLAR FRESH INTERNATIONAL LIMITED"}],"company_since":"1997-05-16","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608079","names":[{"lang":"en","v":"KING YEAR HOLDINGS LIMITED"},{"lang":"hk","v":"漢年集團有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-12-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608234","names":[{"lang":"en","v":"POWER GROUP INVESTMENT LIMITED (d2004-11-12)"},{"lang":"hk","v":"力富投資有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608082","names":[{"lang":"en","v":"PRIMEWOOD HOLDINGS LIMITED"},{"lang":"hk","v":"柏活集團有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608155","names":[{"lang":"en","v":"KO YIP HOLDINGS LIMITED"},{"lang":"hk","v":"高業集團有限公司"}],"company_since":"1997-05-16","company_dissolved":"2006-09-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608059","names":[{"lang":"en","v":"PROFIT CABLE LIMITED"},{"lang":"hk","v":"京崙有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"608290","names":[{"lang":"en","v":"R &amp; K LIMITED (d2002-12-13)"},{"lang":"hk","v":"雅建裝飾工程有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-12-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"608410","names":[{"lang":"en","v":"PROMAN INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"怡浚國際有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-09-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608381","names":[{"lang":"en","v":"REGAL FINANCIAL SERVICES LIMITED (d2000-11-10)"},{"lang":"hk","v":"峻滙金融有限公司"}],"company_since":"1997-05-16","company_dissolved":"2000-11-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608179","names":[{"lang":"en","v":"LEGEND SUN LIMITED (d2008-11-07)"},{"lang":"hk","v":"正陽有限公司"}],"company_since":"1997-05-16","company_dissolved":"2008-11-07","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608092","names":[{"lang":"en","v":"MASTER SPIRIT INVESTMENT LIMITED"},{"lang":"hk","v":"有力投資有限公司"}],"company_since":"1997-05-16","company_dissolved":"2006-09-29","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608186","names":[{"lang":"en","v":"RISE LUCK (CHINA) LIMITED"}],"company_since":"1997-05-16","company_dissolved":"2006-05-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608352","names":[{"lang":"en","v":"REGENT CHARTER HOLDINGS LIMITED"},{"lang":"hk","v":"嘉卓集團有限公司"}],"company_since":"1997-05-16","company_dissolved":"2001-07-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"608183","names":[{"lang":"en","v":"RICH CONCEPT LIMITED (d2014-04-25)"},{"lang":"hk","v":"漢富有限公司"}],"company_since":"1997-05-16","company_dissolved":"2014-04-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608184","names":[{"lang":"en","v":"REGENT SOURCE LIMITED"},{"lang":"hk","v":"思毅有限公司"}],"company_since":"1997-05-16","company_dissolved":"2019-10-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608106","names":[{"lang":"en","v":"MASS WISE INDUSTRIES LIMITED"},{"lang":"hk","v":"宏天實業有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608239","names":[{"lang":"en","v":"MEGA TALENT LIMITED (d2005-01-07)"},{"lang":"hk","v":"藝全有限公司"}],"company_since":"1997-05-16","company_dissolved":"2005-01-07","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608299","names":[{"lang":"en","v":"REGENT SUPERB LIMITED"},{"lang":"hk","v":"潮順有限公司"}],"company_since":"1997-05-16","company_dissolved":"2003-04-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608182","names":[{"lang":"en","v":"RISE FORD LIMITED"},{"lang":"hk","v":"添昌有限公司"}],"company_since":"1997-05-16","company_dissolved":"2001-06-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608175","names":[{"lang":"en","v":"SENCON TRADING LIMITED"},{"lang":"hk","v":"信康貿易有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-08-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608393","names":[{"lang":"en","v":"RONG HUA COPPER (HOLDINGS) LIMITED"},{"lang":"hk","v":"榮華銅業(集團)有限公司"}],"company_since":"1997-05-16","company_dissolved":"2009-04-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608122","names":[{"lang":"en","v":"SIHL TREASURY LIMITED"},{"lang":"hk","v":"上海實業財務管理有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608061","names":[{"lang":"en","v":"SILVER GROWTH ENGINEERING LIMITED"},{"lang":"hk","v":"兆高工程有限公司"}],"company_since":"1997-05-16","company_dissolved":"2001-10-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608293","names":[{"lang":"en","v":"RAYSTONE DEVELOPMENT LIMITED"},{"lang":"hk","v":"雷事通發展有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608060","names":[{"lang":"en","v":"MASS VICTORY (HK) LIMITED"},{"lang":"hk","v":"南海怡福地產代理(香港)有限公司"}],"company_since":"1997-05-16","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608237","names":[{"lang":"en","v":"MODERN FORD LIMITED (d2005-01-07)"},{"lang":"hk","v":"盈福有限公司"}],"company_since":"1997-05-16","company_dissolved":"2005-01-07","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608138","names":[{"lang":"en","v":"SHUN FAT TOUR COMPANY LIMITED"},{"lang":"hk","v":"順發旅運有限公司"}],"company_since":"1997-05-16","company_dissolved":"2001-08-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608151","names":[{"lang":"en","v":"MAXSONCORP ENTERPRISES LIMITED"},{"lang":"hk","v":"萬生行企業有限公司"}],"company_since":"1997-05-16","company_dissolved":"2007-06-29","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608113","names":[{"lang":"en","v":"SAN YOU GROUP (HONG KONG) LIMITED"},{"lang":"hk","v":"三友集團(香港)有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608137","names":[{"lang":"en","v":"RPT INTERNATIONAL LIMITED"},{"lang":"hk","v":"浩派國際有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608226","names":[{"lang":"en","v":"SINO CLASSIC INTERNATIONAL LIMITED"},{"lang":"hk","v":"中吉國際有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608340","names":[{"lang":"en","v":"SINO LONG LIMITED"},{"lang":"hk","v":"華信隆有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608396","names":[{"lang":"en","v":"OVERSEAS OIL &amp; GAS CORPORATION (HONG KONG), LIMITED"},{"lang":"hk","v":"海外油氣(香港)有限公司"}],"company_since":"1997-05-16","company_dissolved":"2017-01-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608306","names":[{"lang":"en","v":"SINO RIGHT HOLDINGS LIMITED (d2002-11-22)"},{"lang":"hk","v":"中緯集團有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-11-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608416","names":[{"lang":"en","v":"PILLER (CHINA) LIMITED"}],"company_since":"1997-05-16","company_dissolved":"2001-09-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608181","names":[{"lang":"en","v":"SINO RISE LIMITED (d2005-01-07)"},{"lang":"hk","v":"金迪有限公司"}],"company_since":"1997-05-16","company_dissolved":"2005-01-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608172","names":[{"lang":"en","v":"PACIFIC METROPOLITAN LIMITED"},{"lang":"hk","v":"太都有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608350","names":[{"lang":"en","v":"SINO-KOREA LIMITED"},{"lang":"hk","v":"中韓有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-12-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608073","names":[{"lang":"en","v":"LONGS KOI INDUSTRY COMPANY LIMITED"},{"lang":"hk","v":"朗盛中港養鯉場有限公司"}],"company_since":"1997-05-16","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608406","names":[{"lang":"en","v":"OCEAN SHEEP LEATHER TRADING LIMITED"},{"lang":"hk","v":"雪洋皮衣貿易有限公司"}],"company_since":"1997-05-16","company_dissolved":"2003-10-31","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608376","names":[{"lang":"en","v":"SINOLONG INTERNATIONAL LIMITED"},{"lang":"hk","v":"華仲國際有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608300","names":[{"lang":"en","v":"REGENT FORTRESS LIMITED"},{"lang":"hk","v":"潮豐有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-11-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608297","names":[{"lang":"en","v":"REGENT GALLENT LIMITED"},{"lang":"hk","v":"潮泰有限公司"}],"company_since":"1997-05-16","company_dissolved":"2001-06-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608372","names":[{"lang":"en","v":"SKY WELL GROUP LIMITED"},{"lang":"hk","v":"天祥集團有限公司"}],"company_since":"1997-05-16","company_dissolved":"2019-02-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608086","names":[{"lang":"en","v":"PROFIT GROWTH INDUSTRIES LIMITED"},{"lang":"hk","v":"有力實業有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608231","names":[{"lang":"en","v":"SMART CHINA DEVELOPMENT LIMITED"},{"lang":"hk","v":"萬華發展有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608091","names":[{"lang":"en","v":"PROFIT GROWTH INVESTMENT LIMITED (d2008-10-31)"},{"lang":"hk","v":"進一投資有限公司"}],"company_since":"1997-05-16","company_dissolved":"2008-10-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608337","names":[{"lang":"en","v":"SMART WEALTH INVESTMENT LIMITED"},{"lang":"hk","v":"駿利投資有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608298","names":[{"lang":"en","v":"REGENTWAY LIMITED (d2002-06-07)"},{"lang":"hk","v":"潮威有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-06-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608359","names":[{"lang":"en","v":"SOFTSPEED SERVICE LIMITED"}],"company_since":"1997-05-16","company_dissolved":"2018-08-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608346","names":[{"lang":"en","v":"RIGHT BEST HOLDINGS LIMITED"},{"lang":"hk","v":"緯佳集團有限公司"}],"company_since":"1997-05-16","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608045","names":[{"lang":"en","v":"SOMEFAITH INVESTMENT COMPANY LIMITED"},{"lang":"hk","v":"森裕投資有限公司"}],"company_since":"1997-05-16","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608270","names":[{"lang":"en","v":"Solution Research &amp; Consultancy Limited (The)"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"608139","names":[{"lang":"en","v":"SOUTHERN GOLD INTERNATIONAL LIMITED"},{"lang":"hk","v":"南津國際有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608081","names":[{"lang":"en","v":"RINGSON LIMITED (d2015-06-19)"},{"lang":"hk","v":"環訊有限公司"}],"company_since":"1997-05-16","company_dissolved":"2015-06-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608169","names":[{"lang":"en","v":"ROYAL BODY CARE (FAR EAST) LIMITED"}],"company_since":"1997-05-16","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608180","names":[{"lang":"en","v":"SPEEDY CHOICE LIMITED (HK)"},{"lang":"hk","v":"迅惠有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608320","names":[{"lang":"en","v":"STUDIO 142 HONG KONG LIMITED"},{"lang":"hk","v":"香港142工作室有限公司"}],"company_since":"1997-05-16","company_dissolved":"2001-10-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608197","names":[{"lang":"en","v":"RELIANCE WHARF TRANSPORTATION COMPANY LIMITED"},{"lang":"hk","v":"通用碼頭運輸有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-10-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608046","names":[{"lang":"en","v":"SUMFULL DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"森富發展有限公司"}],"company_since":"1997-05-16","company_dissolved":"2001-10-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608048","names":[{"lang":"en","v":"SUNNDY PRODUCTION COMPANY LIMITED"},{"lang":"hk","v":"森信製作有限公司"}],"company_since":"1997-05-16","company_dissolved":"2017-01-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608064","names":[{"lang":"en","v":"SILVER JOYCE INVESTMENT LIMITED"},{"lang":"hk","v":"兆欣投資有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608076","names":[{"lang":"en","v":"SUPER WELL TRADING LIMITED"},{"lang":"hk","v":"優越貿易有限公司"}],"company_since":"1997-05-16","company_dissolved":"2000-11-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608202","names":[{"lang":"en","v":"TEMEISI DEVELOPMENT LIMITED"},{"lang":"hk","v":"特美思發展有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608230","names":[{"lang":"en","v":"THORON (KERAMIK) LIMITED"},{"lang":"hk","v":"科諾(寶陶)有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608196","names":[{"lang":"en","v":"THOUSAND INTERNATIONAL LIMITED"},{"lang":"hk","v":"千達國際有限公司"}],"company_since":"1997-05-16","company_dissolved":"2020-01-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608369","names":[{"lang":"en","v":"TIANFEI TRADING LIMITED"}],"company_since":"1997-05-16","company_dissolved":"2020-08-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608063","names":[{"lang":"en","v":"SILVER JOYCE INTERNATIONAL LIMITED"},{"lang":"hk","v":"兆欣國際有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608363","names":[{"lang":"en","v":"TOP CITY PROPERTY CONSULTANTS LIMITED"},{"lang":"hk","v":"天城物業顧問有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608333","names":[{"lang":"en","v":"RICH &amp; WEALTH ENTERPRISES LIMITED"},{"lang":"hk","v":"耀富企業有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608260","names":[{"lang":"en","v":"TOURING PRO MANAGEMENT &amp; CONSULTANCY SERVICES LIMITED"}],"company_since":"1997-05-16","company_dissolved":"2001-03-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608375","names":[{"lang":"en","v":"TOP TRUTH INVESTMENT LIMITED"},{"lang":"hk","v":"耀信投資有限公司"}],"company_since":"1997-05-16","company_dissolved":"2003-01-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608383","names":[{"lang":"en","v":"TRANAX LIMITED"},{"lang":"hk","v":"合立有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-07-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608173","names":[{"lang":"en","v":"Trinity Crown Limited"},{"lang":"hk","v":"有冠有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"608348","names":[{"lang":"en","v":"SINO EXPERT HOLDINGS LIMITED"},{"lang":"hk","v":"中翹集團有限公司"}],"company_since":"1997-05-16","company_dissolved":"2006-07-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608071","names":[{"lang":"en","v":"U-WOON ENTERPRISES LIMITED"},{"lang":"hk","v":"宇垣實業有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608228","names":[{"lang":"en","v":"UNILANE LIMITED"},{"lang":"hk","v":"宇興有限公司"}],"company_since":"1997-05-16","company_dissolved":"2011-04-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"608365","names":[{"lang":"en","v":"SINO CONCORD ENTERPRISES LIMITED"},{"lang":"hk","v":"中康企業有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608394","names":[{"lang":"en","v":"UNIVERSE TRANSPORTATION CO. LIMITED"},{"lang":"hk","v":"環球貨櫃運輸有限公司"}],"company_since":"1997-05-16","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608380","names":[{"lang":"en","v":"VACLASS LIMITED"}],"company_since":"1997-05-16","company_dissolved":"2001-08-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608115","names":[{"lang":"en","v":"VALLEY SOURCE LIMITED"},{"lang":"hk","v":"宏利源有限公司"}],"company_since":"1997-05-16","company_dissolved":"2001-10-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608094","names":[{"lang":"en","v":"VALUE GOOD LIMITED"},{"lang":"hk","v":"品綽有限公司"}],"company_since":"1997-05-16","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608282","names":[{"lang":"en","v":"SILVER APPLE LIMITED (d2004-11-12)"},{"lang":"hk","v":"銀威寶有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608296","names":[{"lang":"en","v":"REGENT PROSPER LIMITED"},{"lang":"hk","v":"潮興有限公司"}],"company_since":"1997-05-16","company_dissolved":"2003-04-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608070","names":[{"lang":"en","v":"VAN TAIK COMPANY LIMITED"},{"lang":"hk","v":"阪泰克有限公司"}],"company_since":"1997-05-16","company_dissolved":"2007-12-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608279","names":[{"lang":"en","v":"RICH GRAND (HONG KONG) LIMITED (d2002-05-10)"},{"lang":"hk","v":"富盛(香港)有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-05-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608356","names":[{"lang":"en","v":"VISION PLANNING CONSULTANTS LIMITED"},{"lang":"hk","v":"弘域城市規劃顧問有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608188","names":[{"lang":"en","v":"VIKTORIA CARGO (H.K.) LIMITED"},{"lang":"hk","v":"永利貨運(香港)有限公司"}],"company_since":"1997-05-16","company_dissolved":"2010-04-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608371","names":[{"lang":"en","v":"VISION REALITY MULTIMEDIA LIMITED"}],"company_since":"1997-05-16","company_dissolved":"2003-02-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"608305","names":[{"lang":"en","v":"WELL HARVEST CONSULTANTS LIMITED"},{"lang":"hk","v":"佳懋顧問有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-10-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608117","names":[{"lang":"en","v":"RAINBOW TREASURE LIMITED (d2004-11-12)"},{"lang":"hk","v":"虹富有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608347","names":[{"lang":"en","v":"WELL KEEN HOLDINGS LIMITED (d2003-01-10)"},{"lang":"hk","v":"緯興集團有限公司"}],"company_since":"1997-05-16","company_dissolved":"2003-01-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608392","names":[{"lang":"en","v":"STANDWINS PROPERTY HOLDINGS LIMITED"},{"lang":"hk","v":"新嘉豐國際物業有限公司"}],"company_since":"1997-05-16","company_dissolved":"2000-12-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608110","names":[{"lang":"en","v":"SUNNY WELL DEVELOPMENT LIMITED (d2010-01-08)"},{"lang":"hk","v":"匯陽發展有限公司"}],"company_since":"1997-05-16","company_dissolved":"2010-01-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608201","names":[{"lang":"en","v":"WING TONG INDUSTRIAL (H.K.) COMPANY LIMITED"},{"lang":"hk","v":"永通實業(香港)有限公司"}],"company_since":"1997-05-16","company_dissolved":"2011-12-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608235","names":[{"lang":"en","v":"WINNER SKY LIMITED (d2003-02-21)"},{"lang":"hk","v":"豪悅有限公司"}],"company_since":"1997-05-16","company_dissolved":"2003-02-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608412","names":[{"lang":"en","v":"WO SANG FRAME PAPER BACK CARD LIMITED"},{"lang":"hk","v":"和生紙品相架背咭有限公司"}],"company_since":"1997-05-16","company_dissolved":"2016-08-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608370","names":[{"lang":"en","v":"WORLDTRANS SHIPPING LIMITED"},{"lang":"hk","v":"環運船務有限公司"}],"company_since":"1997-05-16","company_dissolved":"2013-12-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608345","names":[{"lang":"en","v":"YIU FAI PETROLEUM (HOLDING) LIMITED"},{"lang":"hk","v":"耀輝石油(集團)有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-03-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608331","names":[{"lang":"en","v":"TOP KINGS INTERNATIONAL LIMITED"},{"lang":"hk","v":"龍之傑國際有限公司"}],"company_since":"1997-05-16","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608330","names":[{"lang":"en","v":"TOP KINGS LIMITED"},{"lang":"hk","v":"龍之傑有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-12-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608100","names":[{"lang":"en","v":"TRENDWAY INTERNATIONAL WINE LIMITED"},{"lang":"hk","v":"派域國際酒業有限公司"}],"company_since":"1997-05-16","company_dissolved":"2001-01-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608146","names":[{"lang":"en","v":"TRINITY TALENT INTERNATIONAL LIMITED (d2001-08-24)"},{"lang":"hk","v":"全智國際有限公司"}],"company_since":"1997-05-16","company_dissolved":"2001-08-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608074","names":[{"lang":"en","v":"UNICHANNELS (HONG KONG) LIMITED"}],"company_since":"1997-05-16","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608178","names":[{"lang":"en","v":"UNION HARMONY LIMITED (d2002-10-25)"},{"lang":"hk","v":"宇鴻有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-10-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608317","names":[{"lang":"en","v":"UNION TRINITY INTERNATIONAL LIMITED"},{"lang":"hk","v":"元通國際有限公司"}],"company_since":"1997-05-16","company_dissolved":"2017-10-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"608229","names":[{"lang":"en","v":"UNIVERSAL HEAD LIMITED (d2016-12-30)"},{"lang":"hk","v":"宇鼎有限公司"}],"company_since":"1997-05-16","company_dissolved":"2016-12-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608386","names":[{"lang":"en","v":"UNIVERSAL PREMIER LIMITED"},{"lang":"hk","v":"宇平有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608089","names":[{"lang":"en","v":"VALUE GOOD TRANSPORTATION LIMITED"},{"lang":"hk","v":"天駿貨運有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"608357","names":[{"lang":"en","v":"WEALTHY INTERNATIONAL GROUP LIMITED (d2010-12-24)"},{"lang":"hk","v":"富瀚國際集團有限公司"}],"company_since":"1997-05-16","company_dissolved":"2010-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608277","names":[{"lang":"en","v":"WELL CHINA DEVELOPMENT LIMITED (d2004-11-12)"},{"lang":"hk","v":"中佳發展有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608077","names":[{"lang":"en","v":"WELL LAKE ENTERPRISES LIMITED"},{"lang":"hk","v":"世川企業有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608304","names":[{"lang":"en","v":"WELLMART CONSULTANTS LIMITED"},{"lang":"hk","v":"佳境顧問有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-10-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608401","names":[{"lang":"en","v":"WINGO JEWELLERY COMPANY LIMITED"},{"lang":"hk","v":"永高珠寶有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608342","names":[{"lang":"en","v":"WINQUAD INTERNATIONAL LIMITED"},{"lang":"hk","v":"偉信針織有限公司"}],"company_since":"1997-05-16","company_dissolved":"2001-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"608291","names":[{"lang":"en","v":"YUET FU YUE PROPERTY AGENCY LIMITED"},{"lang":"hk","v":"越富裕地產代理有限公司"}],"company_since":"1997-05-16","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608321","names":[{"lang":"en","v":"YUKON TRADING CO., LIMITED"},{"lang":"hk","v":"雄港貿易有限公司"}],"company_since":"1997-05-16","company_dissolved":"2000-09-01","company_type_txt":"Private, ltd by shares"},
{"tax_id":"608233","names":[{"lang":"en","v":"SKY WELL INVESTMENT LIMITED"},{"lang":"hk","v":"億潤投資有限公司"}],"company_since":"1997-05-16","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"608247","names":[{"lang":"en","v":"ZHUNG TIN CONSTRUCTION INVESTMENT LIMITED"},{"lang":"hk","v":"中天基建投資有限公司"}],"company_since":"1997-05-16","company_dissolved":"2002-12-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"608319","names":[{"lang":"en","v":"WELL KENT TECHNOLOGY LIMITED"},{"lang":"hk","v":"佳勁科技有限公司"}],"company_since":"1997-05-16","company_dissolved":"2006-09-22","company_type_txt":"Private, ltd by shares"},
undefined,
