undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"854548","names":[{"lang":"en","v":"ELECTRICAL ENGINEERING ALUMNI ASSOCIATION OF THE HONG KONG POLYTECHNIC UNIVERSITY LIMITED (THE)"},{"lang":"hk","v":"香港理工大學電機工程同學會有限公司"}],"company_since":"2003-07-23","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"854385","names":[{"lang":"en","v":"FEDERATION OF NEW TERRITORIES YOUTH FOUNDATION LIMITED (THE)"},{"lang":"hk","v":"新界青聯發展基金會有限公司"}],"company_since":"2003-07-23","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"854358","names":[{"lang":"en","v":"FINE OCEAN SHIPPING COMPANY LIMITED"},{"lang":"hk","v":"明海船務有限公司"}],"company_since":"2003-07-23","company_dissolved":"2010-12-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"854451","names":[{"lang":"en","v":"Forever Beau Group Limited"},{"lang":"hk","v":"旖妍醫學美容有限公司"}],"company_since":"2003-07-23","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"854435","names":[{"lang":"en","v":"ELITE TRADER LIMITED (d2014-12-24)"},{"lang":"hk","v":"伊利(香港)有限公司"}],"company_since":"2003-07-23","company_dissolved":"2014-12-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"854470","names":[{"lang":"en","v":"FRANCE SAIRRE FASHION &amp; ACCESSORIES LIMITED"},{"lang":"hk","v":"法國塞荷服飾(集團)有限公司"}],"company_since":"2003-07-23","company_dissolved":"2008-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"854511","names":[{"lang":"en","v":"FREE SQUARE INTERNATIONAL TRADING CO. LIMITED"},{"lang":"hk","v":"自由人國際貿易有限公司"}],"company_since":"2003-07-23","company_dissolved":"2009-07-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"854374","names":[{"lang":"en","v":"FRANCE SUPER LONG INTERNATIONAL GARMENT LIMITED"},{"lang":"hk","v":"法國西貝倫國際服飾有限公司"}],"company_since":"2003-07-23","company_dissolved":"2008-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"854355","names":[{"lang":"en","v":"GEKO TRADING LIMITED (d2008-12-24)"}],"company_since":"2003-07-23","company_dissolved":"2008-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"854342","names":[{"lang":"en","v":"EURO EXOTIC AUTO LIMITED"}],"company_since":"2003-07-23","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"854500","names":[{"lang":"en","v":"FU DIAN INTERNATIONAL INDUSTRIAL INVESTMENT LIMITED"},{"lang":"hk","v":"富滇國際實業投資有限公司"}],"company_since":"2003-07-23","company_dissolved":"2009-12-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"854541","names":[{"lang":"en","v":"FAR ASIA HONG KONG COMPANY LIMITED"},{"lang":"hk","v":"遠亞香港有限公司"}],"company_since":"2003-07-23","company_dissolved":"2013-09-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"854437","names":[{"lang":"en","v":"FULLY STEP LIMITED"},{"lang":"hk","v":"富承有限公司"}],"company_since":"2003-07-23","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"854570","names":[{"lang":"en","v":"GLOBAL CHINESE UNION PRESS LIMITED"},{"lang":"hk","v":"全球華人聯合報有限公司"}],"company_since":"2003-07-23","company_dissolved":"2008-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"854434","names":[{"lang":"en","v":"GOLD SUCCESS PROPERTY MANAGEMENT LIMITED"},{"lang":"hk","v":"金成物業管理有限公司"}],"company_since":"2003-07-23","company_dissolved":"2009-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"854351","names":[{"lang":"en","v":"FRANCE OLD-STYLE CAR GARMENTS (H.K.) CO., LIMITED"},{"lang":"hk","v":"法國老爺車服飾(香港)有限公司"}],"company_since":"2003-07-23","company_dissolved":"2008-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"854535","names":[{"lang":"en","v":"ENRIGHT, SCOTT &amp; ASSOCIATES LIMITED"}],"company_since":"2003-07-23","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"854367","names":[{"lang":"en","v":"GOLDEN LOGISTICS (HK) LIMITED"},{"lang":"hk","v":"金航國際物流(香港)有限公司"}],"company_since":"2003-07-23","company_dissolved":"2008-12-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"854607","names":[{"lang":"en","v":"GRANDTEL 800 TELESERVICES LIMITED"},{"lang":"hk","v":"宏通800咨詢服務有限公司"}],"company_since":"2003-07-23","company_dissolved":"2004-09-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"854561","names":[{"lang":"en","v":"GOLDEN EMPEROR (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"香港金帝實業有限公司"}],"company_since":"2003-07-23","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"854414","names":[{"lang":"en","v":"GOLDEN WEALTHY TRADING LIMITED"},{"lang":"hk","v":"金源貿易有限公司"}],"company_since":"2003-07-23","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"854323","names":[{"lang":"en","v":"GRACE FASHION OF FRANCE (HONG KONG) COMPANY LIMITED (THE) (d2009-12-18)"},{"lang":"hk","v":"法國格蕾絲服裝(香港)集團有限公司"}],"company_since":"2003-07-23","company_dissolved":"2009-12-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"854527","names":[{"lang":"en","v":"HK PANASONIC TECH INT'L LIMITED"},{"lang":"hk","v":"香港松下科技國際有限公司"}],"company_since":"2003-07-23","company_dissolved":"2007-12-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"854440","names":[{"lang":"en","v":"HONEST SMART LIMITED (d2009-10-02)"},{"lang":"hk","v":"誠俊有限公司"}],"company_since":"2003-07-23","company_dissolved":"2009-10-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"854347","names":[{"lang":"en","v":"GUANGZHOU HUALUNSHIJIA INDUSTRIES DEVELOPMENT LIMITED"},{"lang":"hk","v":"廣州華倫世家實業發展有限公司"}],"company_since":"2003-07-23","company_dissolved":"2007-12-07","company_type_txt":"Private, ltd by shares"},
{"tax_id":"854401","names":[{"lang":"en","v":"HONG KONG BENNENG MOTO MANUFACTURING CO., LIMITED"},{"lang":"hk","v":"香港本能摩托製造有限公司"}],"company_since":"2003-07-23","company_dissolved":"2007-12-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"854343","names":[{"lang":"en","v":"HEAD PACIFIC CARGO LIMITED"},{"lang":"hk","v":"領洋貨運有限公司"}],"company_since":"2003-07-23","company_dissolved":"2008-02-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"854554","names":[{"lang":"en","v":"H.K. LONGISCABBARD (DRESS) GROUP LIMITED"},{"lang":"hk","v":"香港蘭斯伯特(服飾)集團有限公司"}],"company_since":"2003-07-23","company_dissolved":"2012-05-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"854389","names":[{"lang":"en","v":"GEONET HONG KONG CO., LIMITED"}],"company_since":"2003-07-23","company_dissolved":"2007-03-23","company_type_txt":"Private, ltd by shares"},
{"tax_id":"854439","names":[{"lang":"en","v":"HERO CHAMP LIMITED"},{"lang":"hk","v":"偉倡有限公司"}],"company_since":"2003-07-23","company_dissolved":"2019-07-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"854524","names":[{"lang":"en","v":"H.K. HONGTAI HOLDINGS LIMITED"},{"lang":"hk","v":"香港鴻泰集團有限公司"}],"company_since":"2003-07-23","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"854545","names":[{"lang":"en","v":"HONG KONG EMPEROR LIGHTING COMPANY LIMITED"},{"lang":"hk","v":"香港帝羅燈飾有限公司"}],"company_since":"2003-07-23","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"854492","names":[{"lang":"en","v":"H.K. KEY-NOBLE INVESTMENT LIMITED"},{"lang":"hk","v":"香港凱諾投資有限公司"}],"company_since":"2003-07-23","company_dissolved":"2017-03-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"854591","names":[{"lang":"en","v":"HK MIKOLAC FUR GARMENT INT'L CO., LIMITED"},{"lang":"hk","v":"香港麥克拉裘皮服飾國際有限公司"}],"company_since":"2003-07-23","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"854532","names":[{"lang":"en","v":"HONG KONG HUI HANG INTERNATIONAL LOGISTICS LIMITED"},{"lang":"hk","v":"香港惠航國際運輸有限公司"}],"company_since":"2003-07-23","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"854447","names":[{"lang":"en","v":"HONG KONG HAI ER SI DUN CLOTHING GROUP LIMITED"},{"lang":"hk","v":"香港海爾斯頓服飾集團有限公司"}],"company_since":"2003-07-23","company_dissolved":"2007-12-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"854604","names":[{"lang":"en","v":"HONG KONG BRIGHT POINT WOMEN LEATHER GOODS COMPANY LIMITED"},{"lang":"hk","v":"香港亮點女人皮革製品有限公司"}],"company_since":"2003-07-23","company_dissolved":"2007-12-07","company_type_txt":"Private, ltd by shares"},
{"tax_id":"854353","names":[{"lang":"en","v":"GREENLIGHT MEDIA LIMITED (d2006-07-28)"},{"lang":"hk","v":"五音傳媒有限公司"}],"company_since":"2003-07-23","company_dissolved":"2006-07-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"854600","names":[{"lang":"en","v":"HONG KONG NAN HUA INTERNATIONAL LIMITED"},{"lang":"hk","v":"香港南華國際有限公司"}],"company_since":"2003-07-23","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"854438","names":[{"lang":"en","v":"GLOBE EXPRESS LIMITED (d2011-03-25)"},{"lang":"hk","v":"寰通有限公司"}],"company_since":"2003-07-23","company_dissolved":"2011-03-25","company_type_txt":"Private, ltd by shares"},
{"tax_id":"854406","names":[{"lang":"en","v":"HONG KONG OCEAN TRANSPORTATION LIMITED"},{"lang":"hk","v":"香港大洋海運有限公司"}],"company_since":"2003-07-23","company_dissolved":"2009-12-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"854506","names":[{"lang":"en","v":"H.K. EIGHT IMMORTALS HALL TRADITIONAL CHINESE MEDICINE FACTORY LIMITED"},{"lang":"hk","v":"香港八仙堂中藥廠有限公司"}],"company_since":"2003-07-23","company_dissolved":"2008-12-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"854348","names":[{"lang":"en","v":"FRANCE VALENTINO CLOTHING &amp; ACCESSORIES CULTURE LIMITED"},{"lang":"hk","v":"法國華倫天奴服飾文化有限公司"}],"company_since":"2003-07-23","company_dissolved":"2008-07-11","company_type_txt":"Private, ltd by shares"},
{"tax_id":"854455","names":[{"lang":"en","v":"HONG KONG LONG AN INTERNATIONAL INDUSTRIAL HOLDINGS LIMITED"},{"lang":"hk","v":"香港龍安國際實業集團股份有限公司"}],"company_since":"2003-07-23","company_dissolved":"2007-12-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"854576","names":[{"lang":"en","v":"HONG KONG EASTERN MOON BIOLOGY ENG. LIMITED"},{"lang":"hk","v":"香港東朔生物工程有限公司"}],"company_since":"2003-07-23","company_dissolved":"2012-02-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"854453","names":[{"lang":"en","v":"HONG KONG SUYOU INTERNATIONAL EXPRESS COMPANY LIMITED"},{"lang":"hk","v":"香港速郵國際快遞有限公司"}],"company_since":"2003-07-23","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"854579","names":[{"lang":"en","v":"H.K. DAIQIAN INTERNATIONAL ENTERPRISE LIMITED"},{"lang":"hk","v":"香港大千國際企業有限公司"}],"company_since":"2003-07-23","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"854475","names":[{"lang":"en","v":"HONGKONG HUAYIN INT'L INVESTMENT GROUP LIMITED"},{"lang":"hk","v":"香港華銀國際投資集團有限公司"}],"company_since":"2003-07-23","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"854452","names":[{"lang":"en","v":"HONGKONG HKCM RESOURCE HOLDINGS LIMITED"},{"lang":"hk","v":"香港華商城資源控股集團有限公司"}],"company_since":"2003-07-23","company_dissolved":"2017-03-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"854437","names":[{"lang":"en","v":"FULLY STEP LIMITED"},{"lang":"hk","v":"富承有限公司"}],"company_since":"2003-07-23","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"854355","names":[{"lang":"en","v":"GEKO TRADING LIMITED (d2008-12-24)"}],"company_since":"2003-07-23","company_dissolved":"2008-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"854368","names":[{"lang":"en","v":"GELEE TRADING LIMITED"},{"lang":"hk","v":"利就貿易有限公司"}],"company_since":"2003-07-23","company_dissolved":"2008-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"854389","names":[{"lang":"en","v":"GEONET HONG KONG CO., LIMITED"}],"company_since":"2003-07-23","company_dissolved":"2007-03-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"854438","names":[{"lang":"en","v":"GLOBE EXPRESS LIMITED (d2011-03-25)"},{"lang":"hk","v":"寰通有限公司"}],"company_since":"2003-07-23","company_dissolved":"2011-03-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"854561","names":[{"lang":"en","v":"GOLDEN EMPEROR (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"香港金帝實業有限公司"}],"company_since":"2003-07-23","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"854351","names":[{"lang":"en","v":"FRANCE OLD-STYLE CAR GARMENTS (H.K.) CO., LIMITED"},{"lang":"hk","v":"法國老爺車服飾(香港)有限公司"}],"company_since":"2003-07-23","company_dissolved":"2008-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"854470","names":[{"lang":"en","v":"FRANCE SAIRRE FASHION &amp; ACCESSORIES LIMITED"},{"lang":"hk","v":"法國塞荷服飾(集團)有限公司"}],"company_since":"2003-07-23","company_dissolved":"2008-12-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"854414","names":[{"lang":"en","v":"GOLDEN WEALTHY TRADING LIMITED"},{"lang":"hk","v":"金源貿易有限公司"}],"company_since":"2003-07-23","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"854385","names":[{"lang":"en","v":"FEDERATION OF NEW TERRITORIES YOUTH FOUNDATION LIMITED (THE)"},{"lang":"hk","v":"新界青聯發展基金會有限公司"}],"company_since":"2003-07-23","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
{"tax_id":"854323","names":[{"lang":"en","v":"GRACE FASHION OF FRANCE (HONG KONG) COMPANY LIMITED (THE) (d2009-12-18)"},{"lang":"hk","v":"法國格蕾絲服裝(香港)集團有限公司"}],"company_since":"2003-07-23","company_dissolved":"2009-12-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"854353","names":[{"lang":"en","v":"GREENLIGHT MEDIA LIMITED (d2006-07-28)"},{"lang":"hk","v":"五音傳媒有限公司"}],"company_since":"2003-07-23","company_dissolved":"2006-07-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"854348","names":[{"lang":"en","v":"FRANCE VALENTINO CLOTHING &amp; ACCESSORIES CULTURE LIMITED"},{"lang":"hk","v":"法國華倫天奴服飾文化有限公司"}],"company_since":"2003-07-23","company_dissolved":"2008-07-11","company_type_txt":"Private, ltd by shares"},
{"tax_id":"854546","names":[{"lang":"en","v":"GUANGDONG MACHINERY (H.K.) LIMITED"}],"company_since":"2003-07-23","company_dissolved":"2007-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"854347","names":[{"lang":"en","v":"GUANGZHOU HUALUNSHIJIA INDUSTRIES DEVELOPMENT LIMITED"},{"lang":"hk","v":"廣州華倫世家實業發展有限公司"}],"company_since":"2003-07-23","company_dissolved":"2007-12-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"854511","names":[{"lang":"en","v":"FREE SQUARE INTERNATIONAL TRADING CO. LIMITED"},{"lang":"hk","v":"自由人國際貿易有限公司"}],"company_since":"2003-07-23","company_dissolved":"2009-07-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"854506","names":[{"lang":"en","v":"H.K. EIGHT IMMORTALS HALL TRADITIONAL CHINESE MEDICINE FACTORY LIMITED"},{"lang":"hk","v":"香港八仙堂中藥廠有限公司"}],"company_since":"2003-07-23","company_dissolved":"2008-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"854524","names":[{"lang":"en","v":"H.K. HONGTAI HOLDINGS LIMITED"},{"lang":"hk","v":"香港鴻泰集團有限公司"}],"company_since":"2003-07-23","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"854500","names":[{"lang":"en","v":"FU DIAN INTERNATIONAL INDUSTRIAL INVESTMENT LIMITED"},{"lang":"hk","v":"富滇國際實業投資有限公司"}],"company_since":"2003-07-23","company_dissolved":"2009-12-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"854492","names":[{"lang":"en","v":"H.K. KEY-NOBLE INVESTMENT LIMITED"},{"lang":"hk","v":"香港凱諾投資有限公司"}],"company_since":"2003-07-23","company_dissolved":"2017-03-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"854343","names":[{"lang":"en","v":"HEAD PACIFIC CARGO LIMITED"},{"lang":"hk","v":"領洋貨運有限公司"}],"company_since":"2003-07-23","company_dissolved":"2008-02-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"854439","names":[{"lang":"en","v":"HERO CHAMP LIMITED"},{"lang":"hk","v":"偉倡有限公司"}],"company_since":"2003-07-23","company_dissolved":"2019-07-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"854591","names":[{"lang":"en","v":"HK MIKOLAC FUR GARMENT INT'L CO., LIMITED"},{"lang":"hk","v":"香港麥克拉裘皮服飾國際有限公司"}],"company_since":"2003-07-23","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"854554","names":[{"lang":"en","v":"H.K. LONGISCABBARD (DRESS) GROUP LIMITED"},{"lang":"hk","v":"香港蘭斯伯特(服飾)集團有限公司"}],"company_since":"2003-07-23","company_dissolved":"2012-05-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"854527","names":[{"lang":"en","v":"HK PANASONIC TECH INT'L LIMITED"},{"lang":"hk","v":"香港松下科技國際有限公司"}],"company_since":"2003-07-23","company_dissolved":"2007-12-07","company_type_txt":"Private, ltd by shares"},
undefined,
