undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"755388","names":[{"lang":"en","v":"CYBER PRO (JORDAN) LIMITED"},{"lang":"hk","v":"網絡高手(佐敦)有限公司"}],"company_since":"2001-05-04","company_dissolved":"2012-07-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"755488","names":[{"lang":"en","v":"E-WAYS HONG KONG LIMITED"},{"lang":"hk","v":"宜威香港有限公司"}],"company_since":"2001-05-04","company_dissolved":"2003-06-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"755444","names":[{"lang":"en","v":"ELDER INTERNATIONAL LIMITED (d2009-05-08)"},{"lang":"hk","v":"榮聯國際有限公司"}],"company_since":"2001-05-04","company_dissolved":"2009-05-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"755484","names":[{"lang":"en","v":"GAIN FORTUNE LIMITED"},{"lang":"hk","v":"景利有限公司"}],"company_since":"2001-05-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"755561","names":[{"lang":"en","v":"EXHIBITION CAPITAL INTERNATIONAL LIMITED"},{"lang":"hk","v":"展都國際展覽有限公司"}],"company_since":"2001-05-04","company_dissolved":"2006-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"755406","names":[{"lang":"en","v":"GLORY CHALLENGE LIMITED (d2003-07-18)"},{"lang":"hk","v":"朗澤有限公司"}],"company_since":"2001-05-04","company_dissolved":"2003-07-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"755404","names":[{"lang":"en","v":"GLORY CHANCE DEVELOPMENT LIMITED"},{"lang":"hk","v":"朗程發展有限公司"}],"company_since":"2001-05-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"755403","names":[{"lang":"en","v":"GLOBAL ESSENCE DEVELOPMENT LIMITED"},{"lang":"hk","v":"浩逸發展有限公司"}],"company_since":"2001-05-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"755451","names":[{"lang":"en","v":"GEM ASIAN ENVIRONMENTAL COMPANY LIMITED"},{"lang":"hk","v":"德亞環保工程有限公司"}],"company_since":"2001-05-04","company_dissolved":"2006-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"755697","names":[{"lang":"en","v":"HK EVERSHINE INDUSTRIAL DEV. LIMITED (d2006-09-15)"},{"lang":"hk","v":"香港恒興實業發展有限公司"}],"company_since":"2001-05-04","company_dissolved":"2006-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"755630","names":[{"lang":"en","v":"HONG KONG KANBAO TECHNOLOGY LIMITED"},{"lang":"hk","v":"香港康寶科技有限公司"}],"company_since":"2001-05-04","company_dissolved":"2003-04-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"755608","names":[{"lang":"en","v":"HONG KONG YIN LIM FASHION (INTERNATIONAL) CO., LIMITED"},{"lang":"hk","v":"香港妍琳時裝(國際)有限公司"}],"company_since":"2001-05-04","company_dissolved":"2016-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"755641","names":[{"lang":"en","v":"HENGSHILI GROUP (HONG KONG) CO., LIMITED"},{"lang":"hk","v":"恒士利集團(香港)有限公司"}],"company_since":"2001-05-04","company_dissolved":"2013-11-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"755710","names":[{"lang":"en","v":"K. COUGAR DECORATION MATERIALS LIMITED"},{"lang":"hk","v":"高格裝飾材料有限公司"}],"company_since":"2001-05-04","company_dissolved":"2010-01-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"755492","names":[{"lang":"en","v":"KCG FUND MANAGEMENT LIMITED"},{"lang":"hk","v":"寶通基金管理有限公司"}],"company_since":"2001-05-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"755376","names":[{"lang":"en","v":"KEEP SUCCESS INVESTMENT LIMITED"},{"lang":"hk","v":"永采投資有限公司"}],"company_since":"2001-05-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"755650","names":[{"lang":"en","v":"MAGIC-PRO IT TRAINING CENTRE LIMITED"},{"lang":"hk","v":"輝煌培訓中心有限公司"}],"company_since":"2001-05-04","company_dissolved":"2003-08-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"755431","names":[{"lang":"en","v":"MULTI TRIUMPH LIMITED (d2012-07-13)"},{"lang":"hk","v":"奔捷有限公司"}],"company_since":"2001-05-04","company_dissolved":"2012-07-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"755563","names":[{"lang":"en","v":"NO SKIDDING TECHNOLOGY (HK) LIMITED"}],"company_since":"2001-05-04","company_dissolved":"2009-09-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"755639","names":[{"lang":"en","v":"ONC INTELLECTUAL PROPERTY SERVICES LIMITED"},{"lang":"hk","v":"安力知識產權服務有限公司"}],"company_since":"2001-05-04","company_dissolved":"2006-05-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"755392","names":[{"lang":"en","v":"NEWEL SYSTEMS LIMITED"}],"company_since":"2001-05-04","company_dissolved":"2006-10-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"755655","names":[{"lang":"en","v":"PRUDENT DESIGN LIMITED"},{"lang":"hk","v":"誠藝建築設計有限公司"}],"company_since":"2001-05-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"755371","names":[{"lang":"en","v":"RISING GARMENT LIMITED"},{"lang":"hk","v":"駿昇製衣有限公司"}],"company_since":"2001-05-04","company_dissolved":"2006-11-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"755664","names":[{"lang":"en","v":"T &amp; L (H.K.) LIMITED"},{"lang":"hk","v":"材庫(香港)有限公司"}],"company_since":"2001-05-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"755558","names":[{"lang":"en","v":"SANG SANG MARINE PRODUCTS TRADING COMPANY LIMITED"},{"lang":"hk","v":"生生海產貿易有限公司"}],"company_since":"2001-05-04","company_dissolved":"2005-12-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"755609","names":[{"lang":"en","v":"WONDER HOUSEHOLD LIMITED"},{"lang":"hk","v":"泓達行有限公司"}],"company_since":"2001-05-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"755449","names":[{"lang":"en","v":"WELL PROFIT CONSTRUCTION &amp; ENGINEERING LIMITED"},{"lang":"hk","v":"華盈建築工程有限公司"}],"company_since":"2001-05-04","company_dissolved":"2005-11-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"755634","names":[{"lang":"en","v":"TUNG FONG TEXTILE COMPANY LIMITED"},{"lang":"hk","v":"東方紡織品有限公司"}],"company_since":"2001-05-04","company_dissolved":"2003-06-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"755522","names":[{"lang":"en","v":"YOUNGPOST INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"益寶國際集團有限公司"}],"company_since":"2001-05-04","company_dissolved":"2006-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"755556","names":[{"lang":"en","v":"FU QIANG IND. (HK) CO., LIMITED"},{"lang":"hk","v":"富強實業(香港)有限公司"}],"company_since":"2001-05-04","company_dissolved":"2007-07-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755595","names":[{"lang":"en","v":"FULBOND BUSINESS SERVICES LIMITED"},{"lang":"hk","v":"福邦企業服務有限公司"}],"company_since":"2001-05-04","company_dissolved":"2013-08-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755571","names":[{"lang":"en","v":"FREE CHANNEL PRODUCTION LIMITED"},{"lang":"hk","v":"天徑制作有限公司"}],"company_since":"2001-05-04","company_dissolved":"2007-11-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755405","names":[{"lang":"en","v":"GLORY CARDINAL LIMITED"},{"lang":"hk","v":"朗權有限公司"}],"company_since":"2001-05-04","company_dissolved":"2011-01-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755406","names":[{"lang":"en","v":"GLORY CHALLENGE LIMITED (d2003-07-18)"},{"lang":"hk","v":"朗澤有限公司"}],"company_since":"2001-05-04","company_dissolved":"2003-07-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755404","names":[{"lang":"en","v":"GLORY CHANCE DEVELOPMENT LIMITED"},{"lang":"hk","v":"朗程發展有限公司"}],"company_since":"2001-05-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755427","names":[{"lang":"en","v":"GO-TO-ASIA CONSULTING LIMITED"},{"lang":"hk","v":"啓程東方諮詢有限公司"}],"company_since":"2001-05-04","company_dissolved":"2018-01-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755436","names":[{"lang":"en","v":"GOLD BEST (CHINA) LIMITED"},{"lang":"hk","v":"金濤(中國)有限公司"}],"company_since":"2001-05-04","company_dissolved":"2010-12-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755495","names":[{"lang":"en","v":"GOLD CHANCES TRADING LIMITED"},{"lang":"hk","v":"金祥貿易有限公司"}],"company_since":"2001-05-04","company_dissolved":"2004-03-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755642","names":[{"lang":"en","v":"GOLD DRINK (HONG KONG) PROVISIONS LIMITED"},{"lang":"hk","v":"甘津(香港)食品有限公司"}],"company_since":"2001-05-04","company_dissolved":"2007-09-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755502","names":[{"lang":"en","v":"GOLDEN GALAXY INDUSTRIAL LIMITED"},{"lang":"hk","v":"豪偉實業有限公司"}],"company_since":"2001-05-04","company_dissolved":"2014-11-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755631","names":[{"lang":"en","v":"GOLDEN RIGHT COMPANY LIMITED"}],"company_since":"2001-05-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755454","names":[{"lang":"en","v":"GOLDEN SUCCESS TECHNOLOGY LIMITED (d2009-09-25)"},{"lang":"hk","v":"朗豪科技有限公司"}],"company_since":"2001-05-04","company_dissolved":"2009-09-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755525","names":[{"lang":"en","v":"GOLDEN WISE PROPERTIES LIMITED (d2004-09-24)"},{"lang":"hk","v":"金威置業有限公司"}],"company_since":"2001-05-04","company_dissolved":"2004-09-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755582","names":[{"lang":"en","v":"GOSHINE LIMITED (d2008-10-10)"},{"lang":"hk","v":"高盛興業有限公司"}],"company_since":"2001-05-04","company_dissolved":"2008-10-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755487","names":[{"lang":"en","v":"GOWELL INTERNATIONAL LIMITED"},{"lang":"hk","v":"浩威國際有限公司"}],"company_since":"2001-05-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755409","names":[{"lang":"en","v":"GRACE CHARTER LIMITED"},{"lang":"hk","v":"欣澤有限公司"}],"company_since":"2001-05-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755540","names":[{"lang":"en","v":"GREAT CAREER LIMITED"},{"lang":"hk","v":"展鴻有限公司"}],"company_since":"2001-05-04","company_dissolved":"2006-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755538","names":[{"lang":"en","v":"GREAT DYNASTY CORPORATION LIMITED"},{"lang":"hk","v":"朝升有限公司"}],"company_since":"2001-05-04","company_dissolved":"2005-10-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755537","names":[{"lang":"en","v":"GREAT MASTER CORPORATION LIMITED"},{"lang":"hk","v":"晉傑有限公司"}],"company_since":"2001-05-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755453","names":[{"lang":"en","v":"GREAT TARGET ENGINEERING LIMITED"},{"lang":"hk","v":"駿耀工程有限公司"}],"company_since":"2001-05-04","company_dissolved":"2006-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755534","names":[{"lang":"en","v":"EXCELLENT FAMOUS DEVELOPMENT LIMITED"},{"lang":"hk","v":"佳懋發展有限公司"}],"company_since":"2001-05-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755651","names":[{"lang":"en","v":"GREATLAKE VENTURES LIMITED"}],"company_since":"2001-05-04","company_dissolved":"2006-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755479","names":[{"lang":"en","v":"GROUPLINK CORPORATION LIMITED"},{"lang":"hk","v":"群訊有限公司"}],"company_since":"2001-05-04","company_dissolved":"2008-10-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"755383","names":[{"lang":"en","v":"EXPERT LIMITED"},{"lang":"hk","v":"藝和有限公司"}],"company_since":"2001-05-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"755432","names":[{"lang":"en","v":"EXTRAWELL INDUSTRIAL LIMITED"},{"lang":"hk","v":"力勤實業有限公司"}],"company_since":"2001-05-04","company_dissolved":"2016-12-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755527","names":[{"lang":"en","v":"GTMC Hong Kong Limited"},{"lang":"hk","v":"來興利旅遊私人有限公司"}],"company_since":"2001-05-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755463","names":[{"lang":"en","v":"FAR EAST MARINE MANAGEMENT COMPANY LIMITED"},{"lang":"hk","v":"遠東海洋顧問社有限公司"}],"company_since":"2001-05-04","company_dissolved":"2011-12-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755686","names":[{"lang":"en","v":"GUANG ZHOU KAIXIN SPIN AND WEAVE COMPANY LIMITED"},{"lang":"hk","v":"廣州凱鑫紡織有限公司"}],"company_since":"2001-05-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755549","names":[{"lang":"en","v":"H.K. FRANCE COSMETICS GROUP LIMITED"},{"lang":"hk","v":"香港法國化妝品集團有限公司"}],"company_since":"2001-05-04","company_dissolved":"2006-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755450","names":[{"lang":"en","v":"FLY WELL CONSTRUCTION &amp; ENGINEERING LIMITED"},{"lang":"hk","v":"飛卓建築工程有限公司"}],"company_since":"2001-05-04","company_dissolved":"2002-08-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755696","names":[{"lang":"en","v":"H.K. SKY-WALL SCIENCE TRADE GROUP LIMITED"},{"lang":"hk","v":"香港天垣科貿集團有限公司"}],"company_since":"2001-05-04","company_dissolved":"2006-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755372","names":[{"lang":"en","v":"FOREMAN DEVELOPMENT LIMITED (d2003-05-16)"},{"lang":"hk","v":"友光發展有限公司"}],"company_since":"2001-05-04","company_dissolved":"2003-05-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755602","names":[{"lang":"en","v":"HAI YUEH ENTERPRISE (H.K.) LIMITED"},{"lang":"hk","v":"海翊企業(香港)有限公司"}],"company_since":"2001-05-04","company_dissolved":"2007-09-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755707","names":[{"lang":"en","v":"FORERUNNER E-PROCUREMENT LIMITED"}],"company_since":"2001-05-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755462","names":[{"lang":"en","v":"HALO SOLUTIONS LIMITED (d2008-06-27)"}],"company_since":"2001-05-04","company_dissolved":"2008-06-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755702","names":[{"lang":"en","v":"FORTUNE TRAVEL SERVICES LIMITED"},{"lang":"hk","v":"富勝旅遊服務有限公司"}],"company_since":"2001-05-04","company_dissolved":"2003-11-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755646","names":[{"lang":"en","v":"HANG PO ENGINEERING CO. LIMITED"},{"lang":"hk","v":"恒保機電工程有限公司"}],"company_since":"2001-05-04","company_dissolved":"2007-04-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755391","names":[{"lang":"en","v":"HAPPY INDUSTRIAL LIMITED"},{"lang":"hk","v":"金鏗實業有限公司"}],"company_since":"2001-05-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755665","names":[{"lang":"en","v":"HANDI LIMITED (d2003-09-11)"}],"company_since":"2001-05-04","company_dissolved":"2003-09-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755373","names":[{"lang":"en","v":"HARVEST BEST DEVELOPMENT LIMITED (d2006-09-15)"},{"lang":"hk","v":"千盛發展有限公司"}],"company_since":"2001-05-04","company_dissolved":"2006-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"755469","names":[{"lang":"en","v":"HEADQUARTERS (HQ) CONCEPTS LIMITED"}],"company_since":"2001-05-04","company_dissolved":"2004-10-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755484","names":[{"lang":"en","v":"GAIN FORTUNE LIMITED"},{"lang":"hk","v":"景利有限公司"}],"company_since":"2001-05-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"755596","names":[{"lang":"en","v":"HENG AN PING YUAN INVEST CORPORATION LIMITED"},{"lang":"hk","v":"恆安平遠投資有限公司"}],"company_since":"2001-05-04","company_dissolved":"2005-08-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755628","names":[{"lang":"en","v":"HENG YU PLASTIC CO. LIMITED"},{"lang":"hk","v":"恆鈺股份有限公司"}],"company_since":"2001-05-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755641","names":[{"lang":"en","v":"HENGSHILI GROUP (HONG KONG) CO., LIMITED"},{"lang":"hk","v":"恒士利集團(香港)有限公司"}],"company_since":"2001-05-04","company_dissolved":"2013-11-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755470","names":[{"lang":"en","v":"HERO HOLDING LIMITED"},{"lang":"hk","v":"英華控股有限公司"}],"company_since":"2001-05-04","company_dissolved":"2005-09-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755697","names":[{"lang":"en","v":"HK EVERSHINE INDUSTRIAL DEV. LIMITED (d2006-09-15)"},{"lang":"hk","v":"香港恒興實業發展有限公司"}],"company_since":"2001-05-04","company_dissolved":"2006-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755418","names":[{"lang":"en","v":"GOLDEN PROFIT GARMENT LIMITED"},{"lang":"hk","v":"金盈製衣有限公司"}],"company_since":"2001-05-04","company_dissolved":"2009-07-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"755403","names":[{"lang":"en","v":"GLOBAL ESSENCE DEVELOPMENT LIMITED"},{"lang":"hk","v":"浩逸發展有限公司"}],"company_since":"2001-05-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"755351","names":[{"lang":"en","v":"HONG KONG EDUCATIONAL RESEARCH ASSOCIATION LIMITED (THE)"},{"lang":"hk","v":"香港教育研究學會有限公司"}],"company_since":"2001-05-04","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"755451","names":[{"lang":"en","v":"GEM ASIAN ENVIRONMENTAL COMPANY LIMITED"},{"lang":"hk","v":"德亞環保工程有限公司"}],"company_since":"2001-05-04","company_dissolved":"2006-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755643","names":[{"lang":"en","v":"HONG KONG JOCKEY CLUB INSTITUTE OF CHINESE MEDICINE LIMITED"},{"lang":"hk","v":"香港賽馬會中藥研究院有限公司"}],"company_since":"2001-05-04","company_dissolved":"2013-07-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755400","names":[{"lang":"en","v":"GENERAL TRINITY HOLDINGS LIMITED"},{"lang":"hk","v":"振通集團有限公司"}],"company_since":"2001-05-04","company_dissolved":"2007-09-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755630","names":[{"lang":"en","v":"HONG KONG KANBAO TECHNOLOGY LIMITED"},{"lang":"hk","v":"香港康寶科技有限公司"}],"company_since":"2001-05-04","company_dissolved":"2003-04-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755448","names":[{"lang":"en","v":"GENTLE CONSULTANTS LIMITED (d2005-09-09)"},{"lang":"hk","v":"晉和顧問有限公司"}],"company_since":"2001-05-04","company_dissolved":"2005-09-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755600","names":[{"lang":"en","v":"GIASIMING (HK) COMPANY LIMITED"},{"lang":"hk","v":"嘉士明(香港)有限公司"}],"company_since":"2001-05-04","company_dissolved":"2004-11-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755412","names":[{"lang":"en","v":"HONG KONG NABER INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"香港納貝國際投資有限公司"}],"company_since":"2001-05-04","company_dissolved":"2006-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755500","names":[{"lang":"en","v":"HONG KONG RECYCLE MATERIALS &amp; RE-PRODUCTION BUSINESS GENERAL ASSOCIATION LIMITED"},{"lang":"hk","v":"香港環保廢料再造業總會有限公司"}],"company_since":"2001-05-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755675","names":[{"lang":"en","v":"HONG KONG SEAVIEW FOOD SHOP LIMITED"},{"lang":"hk","v":"香港海景粥店有限公司"}],"company_since":"2001-05-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755583","names":[{"lang":"en","v":"GLOBAL ISLAND MARINE COMPANY LIMITED"},{"lang":"hk","v":"環島貿易有限公司"}],"company_since":"2001-05-04","company_dissolved":"2011-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755466","names":[{"lang":"en","v":"HONG KONG SI CHUAN CHINESE MEDICINE MODERNIZATION ASSOCIATION LIMITED"},{"lang":"hk","v":"香港四川中葯現代化產業促進會有限公司"}],"company_since":"2001-05-04","company_dissolved":"2011-05-10","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"755422","names":[{"lang":"en","v":"GLOBAL LEADER DEVELOPMENT LIMITED"},{"lang":"hk","v":"才達發展有限公司"}],"company_since":"2001-05-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755474","names":[{"lang":"en","v":"HONG KONG WINLONG HOLDINGS LIMITED"},{"lang":"hk","v":"香港泰宏集團有限公司"}],"company_since":"2001-05-04","company_dissolved":"2006-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755519","names":[{"lang":"en","v":"HONG KONG WU MAY GROUPS CO. LIMITED"},{"lang":"hk","v":"香港五梅集團有限公司"}],"company_since":"2001-05-04","company_dissolved":"2007-09-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"755396","names":[{"lang":"en","v":"HONG KONG YATIN (INTERNATIONAL) GROUP CORPORATION LIMITED"},{"lang":"hk","v":"香港雅鼎(國際)集團有限公司"}],"company_since":"2001-05-04","company_dissolved":"2007-09-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"755608","names":[{"lang":"en","v":"HONG KONG YIN LIM FASHION (INTERNATIONAL) CO., LIMITED"},{"lang":"hk","v":"香港妍琳時裝(國際)有限公司"}],"company_since":"2001-05-04","company_dissolved":"2016-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755565","names":[{"lang":"en","v":"HONGKONG EXCELLENCE &amp; EDGE CO., LIMITED"},{"lang":"hk","v":"香港卓銳有限公司"}],"company_since":"2001-05-04","company_dissolved":"2006-09-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755554","names":[{"lang":"en","v":"HONGKONG SKYFULL INTERNATIONAL LIMITED"},{"lang":"hk","v":"香港天裕國際有限公司"}],"company_since":"2001-05-04","company_dissolved":"2006-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755637","names":[{"lang":"en","v":"HOPE TONG (HONG KONG) LIMITED"},{"lang":"hk","v":"香港望通有限公司"}],"company_since":"2001-05-04","company_dissolved":"2002-09-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755481","names":[{"lang":"en","v":"HOPRICH CORPORATION LIMITED"},{"lang":"hk","v":"浩豐有限公司"}],"company_since":"2001-05-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755389","names":[{"lang":"en","v":"HOPWIN INDUSTRIES LIMITED"},{"lang":"hk","v":"浩旺實業有限公司"}],"company_since":"2001-05-04","company_dissolved":"2014-12-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"755709","names":[{"lang":"en","v":"VR TECHNOLOGY LIMITED"}],"company_since":"2001-05-04","company_dissolved":"2016-09-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755703","names":[{"lang":"en","v":"SHEUNG MOON CONSTRUCTION CIVIL ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"常滿建築土木工程有限公司"}],"company_since":"2001-05-04","company_dissolved":"2006-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"755664","names":[{"lang":"en","v":"T &amp; L (H.K.) LIMITED"},{"lang":"hk","v":"材庫(香港)有限公司"}],"company_since":"2001-05-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"755648","names":[{"lang":"en","v":"SHERWOOD RESOURCES INTERNATIONAL LIMITED"}],"company_since":"2001-05-04","company_dissolved":"2019-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755579","names":[{"lang":"en","v":"WAYAHEAD CONSULTANT LIMITED"},{"lang":"hk","v":"威翹顧問有限公司"}],"company_since":"2001-05-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755591","names":[{"lang":"en","v":"WEARABLE PERIPHERAL LIMITED"}],"company_since":"2001-05-04","company_dissolved":"2006-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755449","names":[{"lang":"en","v":"WELL PROFIT CONSTRUCTION &amp; ENGINEERING LIMITED"},{"lang":"hk","v":"華盈建築工程有限公司"}],"company_since":"2001-05-04","company_dissolved":"2005-11-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755498","names":[{"lang":"en","v":"WELLSUN INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"華信國際投資有限公司"}],"company_since":"2001-05-04","company_dissolved":"2014-03-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755507","names":[{"lang":"en","v":"WELLYOUNG CORPORATION LIMITED"},{"lang":"hk","v":"穎怡有限公司"}],"company_since":"2001-05-04","company_dissolved":"2006-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"755605","names":[{"lang":"en","v":"WING SHING WOODEN PRODUCTS COMPANY LIMITED"},{"lang":"hk","v":"永成木器製品有限公司"}],"company_since":"2001-05-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755397","names":[{"lang":"en","v":"SUPREME APEX MANUFACTURING LIMITED"},{"lang":"hk","v":"頂峰製造有限公司"}],"company_since":"2001-05-04","company_dissolved":"2003-11-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"755610","names":[{"lang":"en","v":"WISDOM WORKSHOP PUBLISHING LIMITED"},{"lang":"hk","v":"智庫出版有限公司"}],"company_since":"2001-05-04","company_dissolved":"2005-01-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755609","names":[{"lang":"en","v":"WONDER HOUSEHOLD LIMITED"},{"lang":"hk","v":"泓達行有限公司"}],"company_since":"2001-05-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"755705","names":[{"lang":"en","v":"QUALITY RE-ENGINEERING HOLDINGS LIMITED"},{"lang":"hk","v":"優質革新控股有限公司"}],"company_since":"2001-05-04","company_dissolved":"2008-10-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"755521","names":[{"lang":"en","v":"ENNYAH DIGI TECHNOLOGIES (HK) LIMITED"},{"lang":"hk","v":"恩雅數位科技(香港)有限公司"}],"company_since":"2001-05-04","company_dissolved":"2009-06-26","company_type_txt":"Private, ltd by shares"},
undefined,
