undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"753183","names":[{"lang":"en","v":"CREATIVE INSPECTION SYSTEM LIMITED"},{"lang":"hk","v":"元豐儀器(香港)有限公司"}],"company_since":"2001-04-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"753162","names":[{"lang":"en","v":"GLORY-ORIENT INDUSTRIAL LIMITED"},{"lang":"hk","v":"廣懋實業有限公司"}],"company_since":"2001-04-06","company_dissolved":"2015-11-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"753205","names":[{"lang":"en","v":"CREATION MASS (HONG KONG) LIMITED"},{"lang":"hk","v":"生茂(香港)有限公司"}],"company_since":"2001-04-06","company_dissolved":"2006-08-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"753125","names":[{"lang":"en","v":"KATIN INTERNATIONAL LIMITED"},{"lang":"hk","v":"啓添國際有限公司"}],"company_since":"2001-04-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"753167","names":[{"lang":"en","v":"LUCKY POLO LIMITED"},{"lang":"hk","v":"眾智有限公司"}],"company_since":"2001-04-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"753122","names":[{"lang":"en","v":"IP-IMPACT LIMITED"},{"lang":"hk","v":"兆行有限公司"}],"company_since":"2001-04-06","company_dissolved":"2010-11-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"753175","names":[{"lang":"en","v":"JADE BEST LIMITED (d2006-08-18)"},{"lang":"hk","v":"名鉅有限公司"}],"company_since":"2001-04-06","company_dissolved":"2006-08-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"753178","names":[{"lang":"en","v":"PARAMEDIA LIMITED (d2009-08-28)"},{"lang":"hk","v":"飛瑞有限公司"}],"company_since":"2001-04-06","company_dissolved":"2009-08-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"753136","names":[{"lang":"en","v":"LOTUS INTERNATIONAL ENTERPRISES LIMITED"},{"lang":"hk","v":"蓮花國際實業有限公司"}],"company_since":"2001-04-06","company_dissolved":"2003-08-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"753200","names":[{"lang":"en","v":"SINLONG INTERNATIONAL TRADE LIMITED"},{"lang":"hk","v":"鑫隆國際貿易有限公司"}],"company_since":"2001-04-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"753134","names":[{"lang":"en","v":"PENGUIN NETWORK SYSTEM LIMITED"},{"lang":"hk","v":"普雷系統有限公司"}],"company_since":"2001-04-06","company_dissolved":"2002-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"753082","names":[{"lang":"en","v":"SMART WIN (ASIA) LIMITED (d2006-08-18)"},{"lang":"hk","v":"卓新(亞洲)有限公司"}],"company_since":"2001-04-06","company_dissolved":"2006-08-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"753201","names":[{"lang":"en","v":"PROFIT WINNER (ASIA) LIMITED"},{"lang":"hk","v":"利佳(亞洲)有限公司"}],"company_since":"2001-04-06","company_dissolved":"2002-08-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"753177","names":[{"lang":"en","v":"PAKFULL LIMITED (d2008-08-01)"},{"lang":"hk","v":"勵榮有限公司"}],"company_since":"2001-04-06","company_dissolved":"2008-08-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"753135","names":[{"lang":"en","v":"SAM YIU COMPANY LIMITED"},{"lang":"hk","v":"三耀有限公司"}],"company_since":"2001-04-06","company_dissolved":"2003-05-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"753221","names":[{"lang":"en","v":"SAMTECH LIMITED (HK)"},{"lang":"hk","v":"漢培有限公司"}],"company_since":"2001-04-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"753214","names":[{"lang":"en","v":"WEALTH ERA (HONG KONG) LIMITED"},{"lang":"hk","v":"富宜(香港)有限公司"}],"company_since":"2001-04-06","company_dissolved":"2008-01-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"753162","names":[{"lang":"en","v":"GLORY-ORIENT INDUSTRIAL LIMITED"},{"lang":"hk","v":"廣懋實業有限公司"}],"company_since":"2001-04-06","company_dissolved":"2015-11-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753208","names":[{"lang":"en","v":"GLOBAL SPECIALTY CHEMICALS, LIMITED"}],"company_since":"2001-04-06","company_dissolved":"2008-05-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753218","names":[{"lang":"en","v":"GOLDEN INFO ASIA LIMITED"},{"lang":"hk","v":"金訊亞洲有限公司"}],"company_since":"2001-04-06","company_dissolved":"2020-09-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753148","names":[{"lang":"en","v":"GOLDEN WEALTHY (HONG KONG) LIMITED"},{"lang":"hk","v":"金豪(香港)有限公司"}],"company_since":"2001-04-06","company_dissolved":"2006-08-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753159","names":[{"lang":"en","v":"GOLDRISE ASIA LIMITED"},{"lang":"hk","v":"金津亞洲有限公司"}],"company_since":"2001-04-06","company_dissolved":"2007-09-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753238","names":[{"lang":"en","v":"GLOURIOUS CREATION LIMITED"},{"lang":"hk","v":"輝煌創建有限公司"}],"company_since":"2001-04-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753091","names":[{"lang":"en","v":"GOTO ELECTRONIC (HONG KONG) CO., LIMITED"},{"lang":"hk","v":"後藤電子(香港)有限公司"}],"company_since":"2001-04-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"753172","names":[{"lang":"en","v":"GRAND ALL LIMITED (d2006-08-18)"},{"lang":"hk","v":"弘來有限公司"}],"company_since":"2001-04-06","company_dissolved":"2006-08-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"753055","names":[{"lang":"en","v":"GRACES LIMITED (d2007-07-06)"},{"lang":"hk","v":"惠深有限公司"}],"company_since":"2001-04-06","company_dissolved":"2007-07-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"753194","names":[{"lang":"en","v":"GRANDRESS TRADING LIMITED"},{"lang":"hk","v":"錦卓貿易有限公司"}],"company_since":"2001-04-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753195","names":[{"lang":"en","v":"GRAND WINNING HOLDINGS LIMITED"},{"lang":"hk","v":"盛豪集團有限公司"}],"company_since":"2001-04-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"753076","names":[{"lang":"en","v":"GLORY WINNING LIMITED"},{"lang":"hk","v":"榮禧有限公司"}],"company_since":"2001-04-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"753244","names":[{"lang":"en","v":"PROMO.COM LIMITED"}],"company_since":"2001-04-06","company_dissolved":"2008-05-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"753144","names":[{"lang":"en","v":"PTB GROUP LIMITED"},{"lang":"hk","v":"金源集團(國際)控股有限公司"}],"company_since":"2001-04-06","company_dissolved":"2006-08-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753132","names":[{"lang":"en","v":"RATHORDAN SERVICES LIMITED"}],"company_since":"2001-04-06","company_dissolved":"2004-06-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753142","names":[{"lang":"en","v":"REGAL CITY INVESTMENT LIMITED"},{"lang":"hk","v":"嘉港投資有限公司"}],"company_since":"2001-04-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753141","names":[{"lang":"en","v":"REGAL WIN INTERNATIONAL LIMITED"},{"lang":"hk","v":"麗興國際有限公司"}],"company_since":"2001-04-06","company_dissolved":"2013-12-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753164","names":[{"lang":"en","v":"RICH GAIN (HK) LIMITED"},{"lang":"hk","v":"得富(香港)有限公司"}],"company_since":"2001-04-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753081","names":[{"lang":"en","v":"RICH GROUP INTERNATIONAL LIMITED (d2003-12-12)"},{"lang":"hk","v":"溢達國際有限公司"}],"company_since":"2001-04-06","company_dissolved":"2003-12-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753186","names":[{"lang":"en","v":"RIMPORTS INTERNATIONAL LIMITED"},{"lang":"hk","v":"瑞普國際有限公司"}],"company_since":"2001-04-06","company_dissolved":"2015-12-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"753228","names":[{"lang":"en","v":"Mastercard Loyalty Solutions Hong Kong Limited"}],"company_since":"2001-04-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"753093","names":[{"lang":"en","v":"ROCK INVESTMENT GROUP LIMITED"}],"company_since":"2001-04-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753149","names":[{"lang":"en","v":"ROYAL WIN (HONG KONG) LIMITED"},{"lang":"hk","v":"冠輝(香港)有限公司"}],"company_since":"2001-04-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753137","names":[{"lang":"en","v":"ROYALTEX TRADING LIMITED"},{"lang":"hk","v":"錦濠貿易有限公司"}],"company_since":"2001-04-06","company_dissolved":"2006-10-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753135","names":[{"lang":"en","v":"SAM YIU COMPANY LIMITED"},{"lang":"hk","v":"三耀有限公司"}],"company_since":"2001-04-06","company_dissolved":"2003-05-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753221","names":[{"lang":"en","v":"SAMTECH LIMITED (HK)"},{"lang":"hk","v":"漢培有限公司"}],"company_since":"2001-04-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753067","names":[{"lang":"en","v":"SAN TIN LUNG DEVELOPMENT LIMITED"},{"lang":"hk","v":"新天隆發展有限公司"}],"company_since":"2001-04-06","company_dissolved":"2009-07-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753107","names":[{"lang":"en","v":"LEGEND ACCESS INVESTMENTS LIMITED"},{"lang":"hk","v":"逸進投資有限公司"}],"company_since":"2001-04-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753180","names":[{"lang":"en","v":"LIFE SPRING HOLISTIC HEALTH CENTRE LIMITED"},{"lang":"hk","v":"清泉自然療法中心有限公司"}],"company_since":"2001-04-06","company_dissolved":"2009-08-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753058","names":[{"lang":"en","v":"LEE CHUNG SURFACE TREATMENT LIMITED"},{"lang":"hk","v":"利眾表面處理有限公司"}],"company_since":"2001-04-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753181","names":[{"lang":"en","v":"LIQUID LIGHT LIMITED (d2004-12-24)"}],"company_since":"2001-04-06","company_dissolved":"2004-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753203","names":[{"lang":"en","v":"SEONG MIN TOY CO., LIMITED"},{"lang":"hk","v":"聖旻玩具有限公司"}],"company_since":"2001-04-06","company_dissolved":"2009-04-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753152","names":[{"lang":"en","v":"SHEEN WIN (HONG KONG) LIMITED"},{"lang":"hk","v":"信永(香港)有限公司"}],"company_since":"2001-04-06","company_dissolved":"2006-08-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753116","names":[{"lang":"en","v":"SHEN LONG SHIPPING COMPANY LIMITED"},{"lang":"hk","v":"申隆船務有限公司"}],"company_since":"2001-04-06","company_dissolved":"2006-08-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753200","names":[{"lang":"en","v":"SINLONG INTERNATIONAL TRADE LIMITED"},{"lang":"hk","v":"鑫隆國際貿易有限公司"}],"company_since":"2001-04-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753216","names":[{"lang":"en","v":"SINO CREATION ASIA LIMITED (d2015-05-08)"},{"lang":"hk","v":"華創亞洲有限公司"}],"company_since":"2001-04-06","company_dissolved":"2015-05-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753110","names":[{"lang":"en","v":"SINO SUPREME ENGINEERING LIMITED"},{"lang":"hk","v":"佳綽工程有限公司"}],"company_since":"2001-04-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753157","names":[{"lang":"en","v":"SINORIDER ASIA LIMITED"},{"lang":"hk","v":"中行亞洲有限公司"}],"company_since":"2001-04-06","company_dissolved":"2006-08-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753068","names":[{"lang":"en","v":"SMART GLOBAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"世貿環球發展有限公司"}],"company_since":"2001-04-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753082","names":[{"lang":"en","v":"SMART WIN (ASIA) LIMITED (d2006-08-18)"},{"lang":"hk","v":"卓新(亞洲)有限公司"}],"company_since":"2001-04-06","company_dissolved":"2006-08-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753086","names":[{"lang":"en","v":"SMARTER HOLDINGS LIMITED"},{"lang":"hk","v":"盛億集團有限公司"}],"company_since":"2001-04-06","company_dissolved":"2006-08-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753072","names":[{"lang":"en","v":"SONEXX TRADERS LIMITED"}],"company_since":"2001-04-06","company_dissolved":"2006-08-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"753092","names":[{"lang":"en","v":"TURNSTONE HONG KONG LIMITED"}],"company_since":"2001-04-06","company_dissolved":"2005-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753166","names":[{"lang":"en","v":"ONE WAY LIMITED (d2002-05-24)"},{"lang":"hk","v":"堅毅有限公司"}],"company_since":"2001-04-06","company_dissolved":"2002-05-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753243","names":[{"lang":"en","v":"ONI SYSTEMS HONG KONG LIMITED"}],"company_since":"2001-04-06","company_dissolved":"2003-06-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753075","names":[{"lang":"en","v":"UNION C-BUTTON CO., LIMITED"},{"lang":"hk","v":"聯光布包鈕機廠有限公司"}],"company_since":"2001-04-06","company_dissolved":"2018-01-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753106","names":[{"lang":"en","v":"UNIQUE CLASS LIMITED"},{"lang":"hk","v":"逸熹有限公司"}],"company_since":"2001-04-06","company_dissolved":"2018-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753069","names":[{"lang":"en","v":"P.H.A. CORPORATION LIMITED"}],"company_since":"2001-04-06","company_dissolved":"2008-09-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753105","names":[{"lang":"en","v":"UNIQUE FIDELITY LIMITED (d2008-12-19)"},{"lang":"hk","v":"逸彰有限公司"}],"company_since":"2001-04-06","company_dissolved":"2008-12-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753177","names":[{"lang":"en","v":"PAKFULL LIMITED (d2008-08-01)"},{"lang":"hk","v":"勵榮有限公司"}],"company_since":"2001-04-06","company_dissolved":"2008-08-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"753201","names":[{"lang":"en","v":"PROFIT WINNER (ASIA) LIMITED"},{"lang":"hk","v":"利佳(亞洲)有限公司"}],"company_since":"2001-04-06","company_dissolved":"2002-08-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"753108","names":[{"lang":"en","v":"UNIQUE WEALTH INVESTMENTS LIMITED"},{"lang":"hk","v":"鈞潤投資有限公司"}],"company_since":"2001-04-06","company_dissolved":"2009-08-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753077","names":[{"lang":"en","v":"POLY LEGEND LIMITED"},{"lang":"hk","v":"奧傑有限公司"}],"company_since":"2001-04-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753113","names":[{"lang":"en","v":"UNITED FINANCE MANAGEMENT LIMITED"},{"lang":"hk","v":"聯合金融管理有限公司"}],"company_since":"2001-04-06","company_dissolved":"2007-03-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753103","names":[{"lang":"en","v":"UPDATE TIME LIMITED"},{"lang":"hk","v":"新時鐘錶有限公司"}],"company_since":"2001-04-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753127","names":[{"lang":"en","v":"V-TRON TECHNOLOGY (INTERNATIONAL) COMPANY LIMITED"},{"lang":"hk","v":"維創國際有限公司"}],"company_since":"2001-04-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753163","names":[{"lang":"en","v":"VICKI SCAFFOLDING COMPANY LIMITED"},{"lang":"hk","v":"榮基棚業有限公司"}],"company_since":"2001-04-06","company_dissolved":"2005-04-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753202","names":[{"lang":"en","v":"WAH SHING AIR-CONDITIONING COMPANY LIMITED"},{"lang":"hk","v":"華盛冷氣工程有限公司"}],"company_since":"2001-04-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753188","names":[{"lang":"en","v":"WANG YIP INTERNATIONAL TRANSPORTATION (H.K.) LIMITED"},{"lang":"hk","v":"宏業國際貨運(香港)有限公司"}],"company_since":"2001-04-06","company_dissolved":"2006-08-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753214","names":[{"lang":"en","v":"WEALTH ERA (HONG KONG) LIMITED"},{"lang":"hk","v":"富宜(香港)有限公司"}],"company_since":"2001-04-06","company_dissolved":"2008-01-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753226","names":[{"lang":"en","v":"WIN KEE (KWONG CHUN) STEEL INDUSTRIAL COMPANY LIMITED"},{"lang":"hk","v":"榮記(廣進)鋼鐵工程有限公司"}],"company_since":"2001-04-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753213","names":[{"lang":"en","v":"WORLDWIDE BASE (HONG KONG) LIMITED"},{"lang":"hk","v":"世基(香港)有限公司"}],"company_since":"2001-04-06","company_dissolved":"2006-08-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753232","names":[{"lang":"en","v":"WSD (H.K.) INTERNATIONAL DRESS LIMITED"},{"lang":"hk","v":"沃斯頓(香港)國際時裝有限公司"}],"company_since":"2001-04-06","company_dissolved":"2007-08-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753167","names":[{"lang":"en","v":"LUCKY POLO LIMITED"},{"lang":"hk","v":"眾智有限公司"}],"company_since":"2001-04-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"753211","names":[{"lang":"en","v":"MANHALL INDUSTRIES LIMITED"},{"lang":"hk","v":"明凱實業有限公司"}],"company_since":"2001-04-06","company_dissolved":"2006-08-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"753246","names":[{"lang":"en","v":"RMBCLICK LIMITED"}],"company_since":"2001-04-06","company_dissolved":"2009-08-28","company_type_txt":"Private, ltd by shares"},
undefined,
