undefined,
{"tax_id":"525810","names":[{"lang":"en","v":"COMSTAR PACIFIC LIMITED"},{"lang":"hk","v":"新亞太有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"525943","names":[{"lang":"en","v":"HORNBY ELECTRONIC COMPANY LIMITED"},{"lang":"hk","v":"康比電子有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525768","names":[{"lang":"en","v":"GRAND GOOD INTERNATIONAL LIMITED (d2004-07-02)"},{"lang":"hk","v":"建煌國際有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-07-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525922","names":[{"lang":"en","v":"HERMON INDUSTRIES LIMITED"},{"lang":"hk","v":"源興盛實業有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"525852","names":[{"lang":"en","v":"HUNDRED FAIR TIMEPIECES LIMITED"},{"lang":"hk","v":"百爾登時計有限公司"}],"company_since":"1995-09-19","company_dissolved":"2010-05-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525809","names":[{"lang":"en","v":"KAISER FINANCE LIMITED (d2003-01-10)"},{"lang":"hk","v":"凱旋財務有限公司"}],"company_since":"1995-09-19","company_dissolved":"2003-01-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525847","names":[{"lang":"en","v":"HONG KONG MARITIME RESCUE &amp; SALVAGE CO., LIMITED"},{"lang":"hk","v":"香港海上救助打撈有限公司"}],"company_since":"1995-09-19","company_dissolved":"2003-06-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"525836","names":[{"lang":"en","v":"KEENTEC CONSULTANTS LIMITED"},{"lang":"hk","v":"鍵達顧問有限公司"}],"company_since":"1995-09-19","company_dissolved":"2001-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525915","names":[{"lang":"en","v":"KENTWICK INTERNATIONAL AIR LIMITED"},{"lang":"hk","v":"嘉盈國際空運有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525755","names":[{"lang":"en","v":"HOTEC OIL PRODUCTS LIMITED"},{"lang":"hk","v":"康力石油產品有限公司"}],"company_since":"1995-09-19","company_dissolved":"2019-07-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525623","names":[{"lang":"en","v":"KINGACE ENTERPRISE LIMITED"},{"lang":"hk","v":"興仕企業有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525639","names":[{"lang":"en","v":"FORTUNE TEAM INDUSTRIES LIMITED"},{"lang":"hk","v":"運添實業有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525756","names":[{"lang":"en","v":"KINGSET INTERNATIONAL LIMITED"},{"lang":"hk","v":"興式國際有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"525658","names":[{"lang":"en","v":"INFOCLIENT TECHNOLOGY LIMITED"}],"company_since":"1995-09-19","company_dissolved":"1999-06-11","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525872","names":[{"lang":"en","v":"GOLD BADGE INTERNATIONAL ENTERPRISE LIMITED"},{"lang":"hk","v":"金章國際企業有限公司"}],"company_since":"1995-09-19","company_dissolved":"2001-04-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"525932","names":[{"lang":"en","v":"FONSILK INVESTMENT LIMITED"},{"lang":"hk","v":"豐兆投資有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525927","names":[{"lang":"en","v":"LEPELLA COMPANY LIMITED"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525912","names":[{"lang":"en","v":"LFCG LIMITED"}],"company_since":"1995-09-19","company_dissolved":"2001-03-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"525934","names":[{"lang":"en","v":"FULL CHANCE FAR EAST LIMITED"},{"lang":"hk","v":"豐盛遠東有限公司"}],"company_since":"1995-09-19","company_dissolved":"2001-04-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525971","names":[{"lang":"en","v":"GREAT NAME INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"偉譽國際投資有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525712","names":[{"lang":"en","v":"GREATWAY ENTERPRISES LIMITED"},{"lang":"hk","v":"天域企業有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525861","names":[{"lang":"en","v":"FULL YIELD INTERNATIONAL ENTERPRISE LIMITED"},{"lang":"hk","v":"豐僑國際企業有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-03-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525763","names":[{"lang":"en","v":"H.K. ZHENG SONG INDUSTRIAL LIMITED"},{"lang":"hk","v":"香港正松實業有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525652","names":[{"lang":"en","v":"H090 Company Limited"}],"company_since":"1995-09-19","company_dissolved":"2017-11-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525936","names":[{"lang":"en","v":"FULLWAY INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"豐威國際發展有限公司"}],"company_since":"1995-09-19","company_dissolved":"2008-06-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525886","names":[{"lang":"en","v":"HANG CHEONG HOLDINGS LIMITED"},{"lang":"hk","v":"恒昌集團有限公司"}],"company_since":"1995-09-19","company_dissolved":"2006-03-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525716","names":[{"lang":"en","v":"HANG TIN ASIA LIMITED"},{"lang":"hk","v":"恒天亞洲有限公司"}],"company_since":"1995-09-19","company_dissolved":"2007-06-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525856","names":[{"lang":"en","v":"HAPPY YEAR LIMITED"},{"lang":"hk","v":"喜寶年有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525974","names":[{"lang":"en","v":"HAPPY YOUNG INVESTMENT LIMITED"},{"lang":"hk","v":"喜揚投資有限公司"}],"company_since":"1995-09-19","company_dissolved":"2001-04-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525710","names":[{"lang":"en","v":"HEIWA TRADING LIMITED"},{"lang":"hk","v":"平和物產貿易有限公司"}],"company_since":"1995-09-19","company_dissolved":"2005-03-11","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525695","names":[{"lang":"en","v":"HELANG INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"河浪國際有限公司"}],"company_since":"1995-09-19","company_dissolved":"2003-04-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525815","names":[{"lang":"en","v":"HKU PROFESSIONAL REAL ESTATE AGENCIES ALUMNI LIMITED"},{"lang":"hk","v":"香港大學地產代理專業校友會有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
{"tax_id":"525778","names":[{"lang":"en","v":"HO'S HOLDINGS COMPANY LIMITED"},{"lang":"hk","v":"何氏企業控股有限公司"}],"company_since":"1995-09-19","company_dissolved":"2005-09-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525641","names":[{"lang":"en","v":"HONEST CITY INDUSTRIES LIMITED"},{"lang":"hk","v":"協城實業有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525955","names":[{"lang":"en","v":"HONG KONG MODERN TECHNOLOGY DEVELOPMENT TRADING LIMITED"},{"lang":"hk","v":"香港現代科技開發經貿有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525943","names":[{"lang":"en","v":"HORNBY ELECTRONIC COMPANY LIMITED"},{"lang":"hk","v":"康比電子有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525859","names":[{"lang":"en","v":"GREAT YEAR INTERNATIONAL ENTERPRISE LIMITED"},{"lang":"hk","v":"偉怡國際企業有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-03-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525972","names":[{"lang":"en","v":"GOLDEN FULL INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"豐益國際投資有限公司"}],"company_since":"1995-09-19","company_dissolved":"2005-09-02","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525852","names":[{"lang":"en","v":"HUNDRED FAIR TIMEPIECES LIMITED"},{"lang":"hk","v":"百爾登時計有限公司"}],"company_since":"1995-09-19","company_dissolved":"2010-05-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525727","names":[{"lang":"en","v":"HUNG CHAM METAL FOUNDRY COMPANY LIMITED"},{"lang":"hk","v":"鴻湛五金冶鍊有限公司"}],"company_since":"1995-09-19","company_dissolved":"1998-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"525866","names":[{"lang":"en","v":"GRACEFUL WELL INDUSTRY LIMITED"},{"lang":"hk","v":"恩華實業有限公司"}],"company_since":"1995-09-19","company_dissolved":"2008-09-25","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525697","names":[{"lang":"en","v":"Infineon Technologies Hong Kong Sales Limited"}],"company_since":"1995-09-19","company_dissolved":"2020-09-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525708","names":[{"lang":"en","v":"IDG INTERNATIONAL MARKETING SERVICES (ASIA) LIMITED"}],"company_since":"1995-09-19","company_dissolved":"2009-11-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525642","names":[{"lang":"en","v":"GRAND EMPIRE INDUSTRIES LIMITED"},{"lang":"hk","v":"弘國實業有限公司"}],"company_since":"1995-09-19","company_dissolved":"2016-03-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525768","names":[{"lang":"en","v":"GRAND GOOD INTERNATIONAL LIMITED (d2004-07-02)"},{"lang":"hk","v":"建煌國際有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-07-02","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525896","names":[{"lang":"en","v":"JINSHA (HONG KONG) LIMITED"},{"lang":"hk","v":"金沙(香港)有限公司"}],"company_since":"1995-09-19","company_dissolved":"1999-11-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525875","names":[{"lang":"en","v":"JOIN HOST ASIA LIMITED"},{"lang":"hk","v":"駿豪亞洲有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-03-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525933","names":[{"lang":"en","v":"JOYCEFUL ENTERPRISE LIMITED"},{"lang":"hk","v":"喜寶來企業有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-07-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525976","names":[{"lang":"en","v":"JOYFUL TOP INTERNATIONAL LIMITED"},{"lang":"hk","v":"喜昇國際有限公司"}],"company_since":"1995-09-19","company_dissolved":"2005-09-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525857","names":[{"lang":"en","v":"GREAT DRAGON INTERNATIONAL DEVELOPMENT LIMITED (d2002-09-27)"},{"lang":"hk","v":"偉龍國際發展有限公司"}],"company_since":"1995-09-19","company_dissolved":"2002-09-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525757","names":[{"lang":"en","v":"KADATLY ENTERPRISE LIMITED"},{"lang":"hk","v":"嘉達利實業有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525809","names":[{"lang":"en","v":"KAISER FINANCE LIMITED (d2003-01-10)"},{"lang":"hk","v":"凱旋財務有限公司"}],"company_since":"1995-09-19","company_dissolved":"2003-01-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525853","names":[{"lang":"en","v":"KEEN DRAGON INTERNATIONAL DEVELOPMENT LIMITED (d2006-08-25)"},{"lang":"hk","v":"嘉龍國際發展有限公司"}],"company_since":"1995-09-19","company_dissolved":"2006-08-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525836","names":[{"lang":"en","v":"KEENTEC CONSULTANTS LIMITED"},{"lang":"hk","v":"鍵達顧問有限公司"}],"company_since":"1995-09-19","company_dissolved":"2001-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525702","names":[{"lang":"en","v":"KEMICON LIMITED (d2004-06-25)"},{"lang":"hk","v":"嘉美康有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-06-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525968","names":[{"lang":"en","v":"KENBO INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"嘉寶國際投資有限公司"}],"company_since":"1995-09-19","company_dissolved":"2005-09-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525929","names":[{"lang":"en","v":"KIND RICH INTERNATIONAL ENTERPRISE LIMITED"},{"lang":"hk","v":"嘉發國際企業有限公司"}],"company_since":"1995-09-19","company_dissolved":"2003-04-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525928","names":[{"lang":"en","v":"KAROSE ASIA LIMITED"},{"lang":"hk","v":"嘉豪亞洲有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525782","names":[{"lang":"en","v":"KINGSMERE GROUP INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"景美集團國際有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525922","names":[{"lang":"en","v":"HERMON INDUSTRIES LIMITED"},{"lang":"hk","v":"源興盛實業有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525696","names":[{"lang":"en","v":"KOOKMIN FINANCE ASIA LIMITED"},{"lang":"hk","v":"國銀金融亞洲有限公司"}],"company_since":"1995-09-19","company_dissolved":"2009-12-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525883","names":[{"lang":"en","v":"KWAN CHUNG INDUSTRIAL CO. LIMITED (d2000-05-26)"},{"lang":"hk","v":"昆仲實業有限公司"}],"company_since":"1995-09-19","company_dissolved":"2000-05-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525927","names":[{"lang":"en","v":"LEPELLA COMPANY LIMITED"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"525847","names":[{"lang":"en","v":"HONG KONG MARITIME RESCUE &amp; SALVAGE CO., LIMITED"},{"lang":"hk","v":"香港海上救助打撈有限公司"}],"company_since":"1995-09-19","company_dissolved":"2003-06-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525681","names":[{"lang":"en","v":"HOOVER TOP DEVELOPMENT LIMITED"},{"lang":"hk","v":"豪創發展有限公司"}],"company_since":"1995-09-19","company_dissolved":"2005-09-02","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525758","names":[{"lang":"en","v":"MARKET 21 LIMITED"},{"lang":"hk","v":"二一墟有限公司"}],"company_since":"1995-09-19","company_dissolved":"2013-12-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525755","names":[{"lang":"en","v":"HOTEC OIL PRODUCTS LIMITED"},{"lang":"hk","v":"康力石油產品有限公司"}],"company_since":"1995-09-19","company_dissolved":"2019-07-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525720","names":[{"lang":"en","v":"MAYFAIR CELLARS (HONG KONG) LIMITED"}],"company_since":"1995-09-19","company_dissolved":"2010-02-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525665","names":[{"lang":"en","v":"MEGERA COMPANY LIMITED"},{"lang":"hk","v":"萬利亞人造革有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-07-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525658","names":[{"lang":"en","v":"INFOCLIENT TECHNOLOGY LIMITED"}],"company_since":"1995-09-19","company_dissolved":"1999-06-11","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525683","names":[{"lang":"en","v":"METRO GOOD DEVELOPMENT LIMITED"},{"lang":"hk","v":"景升發展有限公司"}],"company_since":"1995-09-19","company_dissolved":"2009-11-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525931","names":[{"lang":"en","v":"JELCO LEATHER PRODUCTS LIMITED"},{"lang":"hk","v":"珠麗興(香港)皮飾有限公司"}],"company_since":"1995-09-19","company_dissolved":"2008-08-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525787","names":[{"lang":"en","v":"MINDUN (MYANMAR) CO. LIMITED"},{"lang":"hk","v":"綿登(緬甸)有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525649","names":[{"lang":"en","v":"MINERAL RESOURCES LIMITED (HK)"},{"lang":"hk","v":"礦之源開採有限公司"}],"company_since":"1995-09-19","company_dissolved":"2019-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"525913","names":[{"lang":"en","v":"MONETCO LIMITED"},{"lang":"hk","v":"好好發有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525733","names":[{"lang":"en","v":"MTECH ENGINEERING CO., LIMITED"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525750","names":[{"lang":"en","v":"MULTIWISE INVESTMENT LIMITED"},{"lang":"hk","v":"萬利邦投資有限公司"}],"company_since":"1995-09-19","company_dissolved":"2000-08-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525863","names":[{"lang":"en","v":"JOYCE RICH ENTERPRISE LIMITED"},{"lang":"hk","v":"彩發企業有限公司"}],"company_since":"1995-09-19","company_dissolved":"1999-07-23","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525855","names":[{"lang":"en","v":"JOYFUL TEAM INVESTMENT LIMITED"},{"lang":"hk","v":"喜登投資有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-03-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525679","names":[{"lang":"en","v":"NEW CENTURY INDUSTRIAL INVESTMENT LIMITED"},{"lang":"hk","v":"新世紀實業投資有限公司"}],"company_since":"1995-09-19","company_dissolved":"2011-01-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525837","names":[{"lang":"en","v":"NEW-ASIA OPTICAL COMPANY LIMITED"},{"lang":"hk","v":"新亞光學有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525627","names":[{"lang":"en","v":"NEW BOWLING WATCH COMPANY LIMITED"},{"lang":"hk","v":"新寶寧鐘錶有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525648","names":[{"lang":"en","v":"LUCKY LIQUID BULK LIMITED"}],"company_since":"1995-09-19","company_dissolved":"2000-08-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525711","names":[{"lang":"en","v":"NIKKO ENGINEERING LIMITED (d2011-05-27)"}],"company_since":"1995-09-19","company_dissolved":"2011-05-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525737","names":[{"lang":"en","v":"NOBLE HORLOGERIE COMPANY LIMITED"},{"lang":"hk","v":"豪寶時計有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525969","names":[{"lang":"en","v":"KESWICK INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"嘉榮國際投資有限公司"}],"company_since":"1995-09-19","company_dissolved":"2008-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525623","names":[{"lang":"en","v":"KINGACE ENTERPRISE LIMITED"},{"lang":"hk","v":"興仕企業有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525814","names":[{"lang":"en","v":"KINGS ENTERPRISE (HK) LIMITED"},{"lang":"hk","v":"金仕企業(香港)有限公司"}],"company_since":"1995-09-19","company_dissolved":"2002-03-01","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525882","names":[{"lang":"en","v":"ONE CAPITAL LIMITED (d2008-04-11)"}],"company_since":"1995-09-19","company_dissolved":"2008-04-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525793","names":[{"lang":"en","v":"ONLINE OPTICS LIMITED (d1998-10-09)"}],"company_since":"1995-09-19","company_dissolved":"1998-10-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525958","names":[{"lang":"en","v":"ORIENSTAR FINANCE LIMITED"}],"company_since":"1995-09-19","company_dissolved":"2003-05-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525756","names":[{"lang":"en","v":"KINGSET INTERNATIONAL LIMITED"},{"lang":"hk","v":"興式國際有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525714","names":[{"lang":"en","v":"OVER INTERNATIONAL LIMITED"},{"lang":"hk","v":"天越國際有限公司"}],"company_since":"1995-09-19","company_dissolved":"2011-05-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525980","names":[{"lang":"en","v":"KOBUNSHI INTERNATIONAL LIMITED"},{"lang":"hk","v":"高分子國際有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525765","names":[{"lang":"en","v":"PACIFIC FAME INTERNATIONAL LIMITED (d1999-04-09)"},{"lang":"hk","v":"龍倡國際有限公司"}],"company_since":"1995-09-19","company_dissolved":"1999-04-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525722","names":[{"lang":"en","v":"PACIFICJET INVESTMENT LIMITED"}],"company_since":"1995-09-19","company_dissolved":"2016-02-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525694","names":[{"lang":"en","v":"LANDER INDUSTRIAL LIMITED"},{"lang":"hk","v":"泛達實業有限公司"}],"company_since":"1995-09-19","company_dissolved":"2009-09-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525796","names":[{"lang":"en","v":"PERENNIAL SYSTEM ENGINEERING CO. LIMITED"},{"lang":"hk","v":"榮海系統工程有限公司"}],"company_since":"1995-09-19","company_dissolved":"2000-07-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525892","names":[{"lang":"en","v":"PIONEER PERFECT LIMITED"},{"lang":"hk","v":"銳億有限公司"}],"company_since":"1995-09-19","company_dissolved":"2010-01-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525723","names":[{"lang":"en","v":"PIPE-JACK INTERNATIONAL (H.K.) LIMITED"}],"company_since":"1995-09-19","company_dissolved":"2002-11-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525822","names":[{"lang":"en","v":"PLAY HUT LIMITED (d2004-02-27)"}],"company_since":"1995-09-19","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525912","names":[{"lang":"en","v":"LFCG LIMITED"}],"company_since":"1995-09-19","company_dissolved":"2001-03-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525770","names":[{"lang":"en","v":"LICO METAL TECHNOLOGY LIMITED"},{"lang":"hk","v":"歷高科技有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525785","names":[{"lang":"en","v":"PRIME VIEW EDUCATION CENTRE LIMITED"},{"lang":"hk","v":"景峰教育中心有限公司"}],"company_since":"1995-09-19","company_dissolved":"2006-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525824","names":[{"lang":"en","v":"PRO-PRO LIMITED"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525660","names":[{"lang":"en","v":"PRODUCTION STUDIO WORKSHOP LIMITED"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525630","names":[{"lang":"en","v":"PROSPEROUS INTERNATIONAL (HOLDINGS) LIMITED"},{"lang":"hk","v":"富榮國際(股份)有限公司"}],"company_since":"1995-09-19","company_dissolved":"2002-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525978","names":[{"lang":"en","v":"R &amp; D (HONG KONG) LIMITED"}],"company_since":"1995-09-19","company_dissolved":"2015-07-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525789","names":[{"lang":"en","v":"LUCKFIE COMPANY LIMITED"}],"company_since":"1995-09-19","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525644","names":[{"lang":"en","v":"R. H. TRADING LIMITED"}],"company_since":"1995-09-19","company_dissolved":"2003-03-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525835","names":[{"lang":"en","v":"MADAGASCAR AUSTRALIA TRADING (HONG KONG) LIMITED"}],"company_since":"1995-09-19","company_dissolved":"2004-03-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525742","names":[{"lang":"en","v":"RAIN POWER LIMITED"},{"lang":"hk","v":"雨威有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525930","names":[{"lang":"en","v":"KIND JOYCE INTERNATIONAL ENTERPRISE LIMITED"},{"lang":"hk","v":"嘉悅國際企業有限公司"}],"company_since":"1995-09-19","company_dissolved":"2005-04-01","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525795","names":[{"lang":"en","v":"RAINBOW CITY PACKAGING LIMITED"},{"lang":"hk","v":"彩城包裝有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-07-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525637","names":[{"lang":"en","v":"RAINBOW TRADING LIMITED (d2001-03-23)"},{"lang":"hk","v":"盈寶貿易有限公司"}],"company_since":"1995-09-19","company_dissolved":"2001-03-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525719","names":[{"lang":"en","v":"MANNA INTERNATIONAL LIMITED (d2006-10-20)"},{"lang":"hk","v":"瑪納國際有限公司"}],"company_since":"1995-09-19","company_dissolved":"2006-10-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525705","names":[{"lang":"en","v":"RAMTECH DEVELOPMENT LIMITED"},{"lang":"hk","v":"威美達發展有限公司"}],"company_since":"1995-09-19","company_dissolved":"2003-01-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"525734","names":[{"lang":"en","v":"MASS PROFIT INTERNATIONAL LIMITED (d2003-05-02)"},{"lang":"hk","v":"立迅國際有限公司"}],"company_since":"1995-09-19","company_dissolved":"2003-05-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525772","names":[{"lang":"en","v":"REGAL TIME LIMITED (d2004-02-27)"},{"lang":"hk","v":"億振有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525676","names":[{"lang":"en","v":"MASTER PROOFER COMPANY LIMITED"},{"lang":"hk","v":"萬寶行國際有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525884","names":[{"lang":"en","v":"REGENT PACIFIC HOLDINGS LIMITED"},{"lang":"hk","v":"漢武實業有限公司"}],"company_since":"1995-09-19","company_dissolved":"2005-09-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525894","names":[{"lang":"en","v":"RENFORD LIMITED (HK)"},{"lang":"hk","v":"元福有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525918","names":[{"lang":"en","v":"RICH ART MERCHANDISE (HONG KONG) LIMITED"},{"lang":"hk","v":"旭立實業有限公司"}],"company_since":"1995-09-19","company_dissolved":"2013-04-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525655","names":[{"lang":"en","v":"MEGATEX INTERNATIONAL LIMITED (d2004-02-27)"},{"lang":"hk","v":"天翔國際有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525686","names":[{"lang":"en","v":"RISEBO ENGINEERING (INTERNATIONAL) LIMITED"},{"lang":"hk","v":"寶升工程(國際)有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525813","names":[{"lang":"en","v":"ROYWIN INTERNATIONAL (HOLDINGS) LIMITED"},{"lang":"hk","v":"和運國際(集團)有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525629","names":[{"lang":"en","v":"RUN FA ENGINEERING LIMITED"},{"lang":"hk","v":"潤發工程有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525900","names":[{"lang":"en","v":"SEALDEN LIMITED"},{"lang":"hk","v":"世忠有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525925","names":[{"lang":"en","v":"SAM WO ENTERPRISES (INTERNATIONAL) LIMITED"},{"lang":"hk","v":"三和企業(國際)有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525889","names":[{"lang":"en","v":"SETON LIMITED"},{"lang":"hk","v":"思駿有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"525650","names":[{"lang":"en","v":"SHENNONGSHI PHARMACEUTICAL INDUSTRY (HONG KONG) CO. LIMITED"},{"lang":"hk","v":"神農氏藥業(香港)有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525628","names":[{"lang":"en","v":"SHUI FUNG (WING KAI) TRANSPORTATION COMPANY LIMITED"},{"lang":"hk","v":"瑞豐(永嘉)運輸有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525783","names":[{"lang":"en","v":"SICO CHINA (H.K.) LIMITED"},{"lang":"hk","v":"志高集團中國(香港)有限公司"}],"company_since":"1995-09-19","company_dissolved":"2005-09-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525915","names":[{"lang":"en","v":"KENTWICK INTERNATIONAL AIR LIMITED"},{"lang":"hk","v":"嘉盈國際空運有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525638","names":[{"lang":"en","v":"SINCERE FAITH INTERNATIONAL LIMITED"},{"lang":"hk","v":"先暉國際有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525945","names":[{"lang":"en","v":"SINO BRIGHT INTERNATIONAL INDUSTRIAL LIMITED"},{"lang":"hk","v":"華明國際實業有限公司"}],"company_since":"1995-09-19","company_dissolved":"2015-07-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525747","names":[{"lang":"en","v":"SINO GLOBAL DEVELOPMENT LIMITED (d2002-05-10)"},{"lang":"hk","v":"榮文發展有限公司"}],"company_since":"1995-09-19","company_dissolved":"2002-05-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525718","names":[{"lang":"en","v":"OCEAN SHIPPING LIMITED (THE)"},{"lang":"hk","v":"天海船務有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525713","names":[{"lang":"en","v":"SINO TEXTILE ENTERPRISES LIMITED"},{"lang":"hk","v":"中紡企業有限公司"}],"company_since":"1995-09-19","company_dissolved":"2003-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525921","names":[{"lang":"en","v":"SINO-AM STRATEGIC COMPANY LIMITED"},{"lang":"hk","v":"華美策略有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525823","names":[{"lang":"en","v":"SINON (CHINA) COMPANY LIMITED"},{"lang":"hk","v":"視覺(中國)有限公司"}],"company_since":"1995-09-19","company_dissolved":"2001-02-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525957","names":[{"lang":"en","v":"ORIENTAL NEW INVESTMENTS LIMITED"}],"company_since":"1995-09-19","company_dissolved":"2003-05-02","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525874","names":[{"lang":"en","v":"SMART CENTRE DEVELOPMENT LIMITED"},{"lang":"hk","v":"駿鋒發展有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525890","names":[{"lang":"en","v":"STANDARD KING INVESTIGATION LIMITED"},{"lang":"hk","v":"達建公証調查有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525908","names":[{"lang":"en","v":"PIONEER PERFECT INTERNATIONAL LIMITED"},{"lang":"hk","v":"銳億國際有限公司"}],"company_since":"1995-09-19","company_dissolved":"2003-03-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525667","names":[{"lang":"en","v":"STYLING CITY HOLDINGS LIMITED"},{"lang":"hk","v":"知城集團有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525910","names":[{"lang":"en","v":"SUGAR TOYS LIMITED"},{"lang":"hk","v":"信嘉玩具有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"525821","names":[{"lang":"en","v":"POMPEY LIMITED (d2004-02-27)"},{"lang":"hk","v":"撲比爾有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525816","names":[{"lang":"en","v":"SUN YAT SEN EDUCATION FOUNDATION LIMITED"}],"company_since":"1995-09-19","company_dissolved":"2009-11-06","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"525731","names":[{"lang":"en","v":"T.Z. &amp; W.Y. CHEUNG STOCKS LIMITED (d2007-06-08)"},{"lang":"hk","v":"張紫珊張永銳股票有限公司"}],"company_since":"1995-09-19","company_dissolved":"2007-06-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525899","names":[{"lang":"en","v":"TAGAN LIMITED"},{"lang":"hk","v":"泰光有限公司"}],"company_since":"1995-09-19","company_dissolved":"2003-04-25","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525624","names":[{"lang":"en","v":"TAI SENG PVC LEATHER COMPANY LIMITED"},{"lang":"hk","v":"大生膠皮有限公司"}],"company_since":"1995-09-19","company_dissolved":"2001-05-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525646","names":[{"lang":"en","v":"TAK LOON STEEL COMPANY LIMITED"},{"lang":"hk","v":"德隆鋼鐵有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525726","names":[{"lang":"en","v":"TAKASON INDUSTRIAL COMPANY LIMITED"},{"lang":"hk","v":"德雅信實業有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525880","names":[{"lang":"en","v":"TANKER CONSTRUCTION ENGINEERING LIMITED"},{"lang":"hk","v":"德嘉建築工程有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525811","names":[{"lang":"en","v":"TASHKENT (IRON &amp; STEEL) GROUP LIMITED"},{"lang":"hk","v":"得斯開(鋼業)集團有限公司"}],"company_since":"1995-09-19","company_dissolved":"2003-03-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525781","names":[{"lang":"en","v":"THREE KINGDOMS LIMITED"}],"company_since":"1995-09-19","company_dissolved":"2002-03-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525956","names":[{"lang":"en","v":"TIGER HOLDING LIMITED"},{"lang":"hk","v":"泰格控股有限公司"}],"company_since":"1995-09-19","company_dissolved":"2016-08-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525873","names":[{"lang":"en","v":"TIME FAITH INTERNATIONAL DEVELOPMENT LIMITED (d2002-03-15)"},{"lang":"hk","v":"添暉國際發展有限公司"}],"company_since":"1995-09-19","company_dissolved":"2002-03-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525981","names":[{"lang":"en","v":"TIMTEX INTERNATIONAL LIMITED"},{"lang":"hk","v":"添恆國際有限公司"}],"company_since":"1995-09-19","company_dissolved":"2002-01-11","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525674","names":[{"lang":"en","v":"TIN KUNG CONSTRUCTION COMPANY LIMITED"},{"lang":"hk","v":"天工建設工程有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525842","names":[{"lang":"en","v":"TIN SHING HOLDINGS LIMITED"},{"lang":"hk","v":"天盛集團有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525754","names":[{"lang":"en","v":"SAM FAT OIL COMPANY LIMITED"},{"lang":"hk","v":"新發石油有限公司"}],"company_since":"1995-09-19","company_dissolved":"2019-09-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525891","names":[{"lang":"en","v":"SENNES LIMITED"},{"lang":"hk","v":"勝億有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525870","names":[{"lang":"en","v":"TOP KEEN INDUSTRY LIMITED"},{"lang":"hk","v":"高建實業有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-03-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525877","names":[{"lang":"en","v":"TOP KING TRANSPORTATION LIMITED (d2004-02-27)"},{"lang":"hk","v":"泰興運輸有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525777","names":[{"lang":"en","v":"TOP SUCCESS TRADING LIMITED (d2004-02-27)"},{"lang":"hk","v":"富耀貿易有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525633","names":[{"lang":"en","v":"SHUN TAT CONSTRUCTION COMPANY LIMITED"},{"lang":"hk","v":"信達建築有限公司"}],"company_since":"1995-09-19","company_dissolved":"2005-11-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525661","names":[{"lang":"en","v":"SICHUAN RENSHI ADVERTISING COMPANY LIMITED"},{"lang":"hk","v":"四川人士廣告有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525671","names":[{"lang":"en","v":"TUNG FONG (ASIA) TRADING LIMITED"},{"lang":"hk","v":"東方(亞洲)貿易有限公司"}],"company_since":"1995-09-19","company_dissolved":"2003-07-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525643","names":[{"lang":"en","v":"VICTORY CITY DEVELOPMENT LIMITED"},{"lang":"hk","v":"凱城發展有限公司"}],"company_since":"1995-09-19","company_dissolved":"2003-02-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525907","names":[{"lang":"en","v":"VICTORY PACIFIC INTERNATIONAL LIMITED"},{"lang":"hk","v":"勝億國際有限公司"}],"company_since":"1995-09-19","company_dissolved":"2002-03-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525788","names":[{"lang":"en","v":"WAI HANG CHEONG PETRO-CHEMICALS LIMITED (d2005-09-02)"},{"lang":"hk","v":"偉恒昌石油化工原料有限公司"}],"company_since":"1995-09-19","company_dissolved":"2005-09-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"525746","names":[{"lang":"en","v":"SMARTLINK (H.K.) LIMITED"},{"lang":"hk","v":"利昌(香港)有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-03-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525953","names":[{"lang":"en","v":"WELL EAST INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"偉潤國際投資有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525906","names":[{"lang":"en","v":"STANDARD KING INTERNATIONAL LIMITED"},{"lang":"hk","v":"達建國際有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525962","names":[{"lang":"en","v":"WELL NAME INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"偉明國際投資有限公司"}],"company_since":"1995-09-19","company_dissolved":"2001-04-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525944","names":[{"lang":"en","v":"WELL STRONG ENTERPRISE LIMITED"},{"lang":"hk","v":"華翔企業有限公司"}],"company_since":"1995-09-19","company_dissolved":"2008-06-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525690","names":[{"lang":"en","v":"WELLBACK ENTERPRISES LIMITED"},{"lang":"hk","v":"威來企業有限公司"}],"company_since":"1995-09-19","company_dissolved":"1999-07-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525905","names":[{"lang":"en","v":"SUMMIT TECHNOLOGY LIMITED (d2009-09-18)"},{"lang":"hk","v":"盛美科技有限公司"}],"company_since":"1995-09-19","company_dissolved":"2009-09-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525964","names":[{"lang":"en","v":"WELLINK TELECOMMUNICATIONS LIMITED"},{"lang":"hk","v":"華捷電訊有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525952","names":[{"lang":"en","v":"WELTON INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"偉通國際發展有限公司"}],"company_since":"1995-09-19","company_dissolved":"2005-09-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525920","names":[{"lang":"en","v":"SUPER BRILLIANCE COMPANY LIMITED"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525959","names":[{"lang":"en","v":"WELTOP INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"華登國際發展有限公司"}],"company_since":"1995-09-19","company_dissolved":"1999-04-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525965","names":[{"lang":"en","v":"WELUCK INTERNATIONAL LIMITED"},{"lang":"hk","v":"華祥國際有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525917","names":[{"lang":"en","v":"WELWYN INVESTMENT LIMITED"},{"lang":"hk","v":"華蕙投資有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525761","names":[{"lang":"en","v":"WHITNEY CONSULTANT LIMITED"},{"lang":"hk","v":"勵研顧問有限公司"}],"company_since":"1995-09-19","company_dissolved":"2002-11-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525707","names":[{"lang":"en","v":"WIN ROCK DEVELOPMENT LIMITED"},{"lang":"hk","v":"偉諾發展有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525878","names":[{"lang":"en","v":"WINFORD (H.K.) LIMITED"},{"lang":"hk","v":"永福(香港)有限公司"}],"company_since":"1995-09-19","company_dissolved":"2002-12-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525675","names":[{"lang":"en","v":"WISEBO LIMITED"},{"lang":"hk","v":"偉仕寶有限公司"}],"company_since":"1995-09-19","company_dissolved":"2009-02-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525903","names":[{"lang":"en","v":"WISEFORD (HONG KONG) LIMITED"},{"lang":"hk","v":"惠福(香港)有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525887","names":[{"lang":"en","v":"WISEFORD HOLDINGS LIMITED"},{"lang":"hk","v":"惠福集團有限公司"}],"company_since":"1995-09-19","company_dissolved":"2008-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525735","names":[{"lang":"en","v":"SPEEDY TOP LIMITED (d2010-03-12)"},{"lang":"hk","v":"捷寶有限公司"}],"company_since":"1995-09-19","company_dissolved":"2010-03-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525799","names":[{"lang":"en","v":"WOO SUNG (H.K.) LIMITED"},{"lang":"hk","v":"宇星(香港)有限公司"}],"company_since":"1995-09-19","company_dissolved":"2008-09-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525677","names":[{"lang":"en","v":"WORLD LINK (GROUPS) CO. LIMITED"}],"company_since":"1995-09-19","company_dissolved":"1999-04-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525862","names":[{"lang":"en","v":"WORLD TALENT ASIA LIMITED"},{"lang":"hk","v":"華才亞洲有限公司"}],"company_since":"1995-09-19","company_dissolved":"2015-07-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525879","names":[{"lang":"en","v":"TOP BILLION SHIPPING LIMITED"},{"lang":"hk","v":"東億船務有限公司"}],"company_since":"1995-09-19","company_dissolved":"2018-06-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525663","names":[{"lang":"en","v":"XINWEI CONCEPTS LIMITED"},{"lang":"hk","v":"信爲創建有限公司"}],"company_since":"1995-09-19","company_dissolved":"2005-04-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525739","names":[{"lang":"en","v":"YAT SHUN HONG COMPANY LIMITED"},{"lang":"hk","v":"億信塑膠原料行有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525950","names":[{"lang":"en","v":"YICK QUEEN INDUSTRIAL LIMITED"},{"lang":"hk","v":"億僑實業有限公司"}],"company_since":"1995-09-19","company_dissolved":"2005-11-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"525631","names":[{"lang":"en","v":"TOYMATE FACTORY LIMITED"},{"lang":"hk","v":"新生玩具製品廠有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525846","names":[{"lang":"en","v":"YIU HUNG HING TRADING COMPANY LIMITED"},{"lang":"hk","v":"耀鴻興貿易有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525682","names":[{"lang":"en","v":"SUPREME ACES DEVELOPMENT LIMITED"},{"lang":"hk","v":"豪捷發展有限公司"}],"company_since":"1995-09-19","company_dissolved":"2006-03-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525808","names":[{"lang":"en","v":"TRANS-LINK EXPRESS LIMITED"},{"lang":"hk","v":"縱橫快遞有限公司"}],"company_since":"1995-09-19","company_dissolved":"1998-10-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525666","names":[{"lang":"en","v":"YIU SUN GEM COMPANY LIMITED"},{"lang":"hk","v":"耀燊寶石有限公司"}],"company_since":"1995-09-19","company_dissolved":"2009-10-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525656","names":[{"lang":"en","v":"TRI-TECH METALS COMPANY LIMITED"},{"lang":"hk","v":"藝駿工程有限公司"}],"company_since":"1995-09-19","company_dissolved":"2015-02-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525786","names":[{"lang":"en","v":"TROIS AS ENTERPRISE (MULTI-BAGS) LIMITED"},{"lang":"hk","v":"三冠袋類有限公司"}],"company_since":"1995-09-19","company_dissolved":"2009-02-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"525740","names":[{"lang":"en","v":"WAN YU (HK &amp; MACAU) INVESTMENT COMPANY LIMITED"},{"lang":"hk","v":"環宇(港澳)投資有限公司"}],"company_since":"1995-09-19","company_dissolved":"2002-07-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525961","names":[{"lang":"en","v":"WELL SET INTERNATIONAL INVESTMENT LIMITED (d1999-02-12)"},{"lang":"hk","v":"華置國際投資有限公司"}],"company_since":"1995-09-19","company_dissolved":"1999-02-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525960","names":[{"lang":"en","v":"WELL YICK INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"華億國際投資有限公司"}],"company_since":"1995-09-19","company_dissolved":"2002-09-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"525893","names":[{"lang":"en","v":"WISE FAVOUR LIMITED (d2003-04-04)"},{"lang":"hk","v":"惠福有限公司"}],"company_since":"1995-09-19","company_dissolved":"2003-04-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"525647","names":[{"lang":"en","v":"XIN JIN JIANG PETROCHEMS STORAGE AND TRANSPORTATION (HONG KONG) LIMITED"},{"lang":"hk","v":"新錦江石化儲運(香港)有限公司"}],"company_since":"1995-09-19","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525949","names":[{"lang":"en","v":"YIELD ART ENTERPRISE LIMITED"},{"lang":"hk","v":"億雅企業有限公司"}],"company_since":"1995-09-19","company_dissolved":"2000-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525698","names":[{"lang":"en","v":"YIN-YIU INVESTMENT LIMITED"},{"lang":"hk","v":"嫣嶢投資有限公司"}],"company_since":"1995-09-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"525669","names":[{"lang":"en","v":"ZX LASER PRINTER SERVICE (H.K.) LIMITED"},{"lang":"hk","v":"香港崢翔科技有限公司"}],"company_since":"1995-09-19","company_dissolved":"2002-10-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"525728","names":[{"lang":"en","v":"YUE LONG DEVELOPMENT LIMITED"},{"lang":"hk","v":"粵龍發展有限公司"}],"company_since":"1995-09-19","company_dissolved":"2013-05-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"525898","names":[{"lang":"en","v":"LINTAX LIMITED (d2005-09-23)"},{"lang":"hk","v":"年達有限公司"}],"company_since":"1995-09-19","company_dissolved":"2005-09-23","company_type_txt":"Private, ltd by shares"},
undefined,
