{"tax_id":"715745","names":[{"lang":"en","v":"CHAMPION.COM LIMITED"},{"lang":"hk","v":"冠軍網有限公司"}],"company_since":"2000-05-10","company_dissolved":"2004-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715862","names":[{"lang":"en","v":"CHAMPRISE TRADING LIMITED (d2005-05-13)"},{"lang":"hk","v":"兆昇貿易有限公司"}],"company_since":"2000-05-10","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715604","names":[{"lang":"en","v":"CHINA POINT CYBER TECHNOLOGIES LIMITED"},{"lang":"hk","v":"華寶數碼科技有限公司"}],"company_since":"2000-05-10","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715768","names":[{"lang":"en","v":"CHINA WEST GAS AND OIL LIMITED"},{"lang":"hk","v":"中國西部能源有限公司"}],"company_since":"2000-05-10","company_dissolved":"2019-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715877","names":[{"lang":"en","v":"CHINAECNET CO., LIMITED"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715718","names":[{"lang":"en","v":"CHINASYS TECHNOLOGIES COMPANY LIMITED"},{"lang":"hk","v":"華夏科技有限公司"}],"company_since":"2000-05-10","company_dissolved":"2012-03-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715760","names":[{"lang":"en","v":"CHUN PANG CONSTRUCTION ENGINEERING LIMITED"},{"lang":"hk","v":"晉鵬建築工程有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715694","names":[{"lang":"en","v":"CHUNG KEE MARBLE COMPANY LIMITED"},{"lang":"hk","v":"宗記雲石有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715800","names":[{"lang":"en","v":"CHUNG TAT ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"忠達工程有限公司"}],"company_since":"2000-05-10","company_dissolved":"2016-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715640","names":[{"lang":"en","v":"CLEVER BRIGHT INTERNATIONAL LIMITED"},{"lang":"hk","v":"巧明國際有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715859","names":[{"lang":"en","v":"CLIC INTERNATIONAL LOGISTICS LIMITED"},{"lang":"hk","v":"鼎駿國際物流有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715742","names":[{"lang":"en","v":"COMMSECURE.COM LIMITED"}],"company_since":"2000-05-10","company_dissolved":"2003-12-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715855","names":[{"lang":"en","v":"CHAMPRISE DEVELOPMENT LIMITED"},{"lang":"hk","v":"利誌發展有限公司"}],"company_since":"2000-05-10","company_dissolved":"2017-03-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715886","names":[{"lang":"en","v":"COMSTAR TECHNOLOGY TRADING CO., LIMITED"},{"lang":"hk","v":"天時科技貿易有限公司"}],"company_since":"2000-05-10","company_dissolved":"2002-03-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715834","names":[{"lang":"en","v":"CONTATTO (ASIA PACIFIC) LIMITED"},{"lang":"hk","v":"通電(亞洲太平洋)有限公司"}],"company_since":"2000-05-10","company_dissolved":"2015-06-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715853","names":[{"lang":"en","v":"COSMOS DEVELOPMENT LIMITED (d2005-05-13)"},{"lang":"hk","v":"潤來發展有限公司"}],"company_since":"2000-05-10","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715635","names":[{"lang":"en","v":"CROWE LIMITED (d2010-10-29)"},{"lang":"hk","v":"佳賞有限公司"}],"company_since":"2000-05-10","company_dissolved":"2010-10-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715681","names":[{"lang":"en","v":"CHINA GREEN NATURAL FOODS GROUP LIMITED"},{"lang":"hk","v":"天然素食品企業集團有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715944","names":[{"lang":"en","v":"CYBER INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"維高國際投資有限公司"}],"company_since":"2000-05-10","company_dissolved":"2006-06-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715801","names":[{"lang":"en","v":"CYBER WAVE TECHNOLOGY LIMITED"},{"lang":"hk","v":"盈創數碼科技有限公司"}],"company_since":"2000-05-10","company_dissolved":"2003-01-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715713","names":[{"lang":"en","v":"CHINA TELECOM (HONG KONG) GROUP LIMITED"},{"lang":"hk","v":"中國電信(香港)集團有限公司"}],"company_since":"2000-05-10","company_dissolved":"2012-08-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715714","names":[{"lang":"en","v":"CHINA TELECOM (HONG KONG) LIMITED"},{"lang":"hk","v":"中國電信(香港)有限公司"}],"company_since":"2000-05-10","company_dissolved":"2012-08-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715603","names":[{"lang":"en","v":"CREDITVIEW LIMITED"},{"lang":"hk","v":"志境有限公司"}],"company_since":"2000-05-10","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715588","names":[{"lang":"en","v":"DIGITAL COMMUNITY CHEST LIMITED"}],"company_since":"2000-05-10","company_dissolved":"2011-06-01","company_type_txt":"Ltd by guarantee"},
undefined,
undefined,
{"tax_id":"715911","names":[{"lang":"en","v":"DISTRIBUTION MANAGEMENT SERVICE LIMITED"},{"lang":"hk","v":"盈利物流有限公司"}],"company_since":"2000-05-10","company_dissolved":"2011-06-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715989","names":[{"lang":"en","v":"CHINESE PICTURES ENTERTAINMENT LIMITED"},{"lang":"hk","v":"華夏影視娛樂有限公司"}],"company_since":"2000-05-10","company_dissolved":"2019-11-29","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715611","names":[{"lang":"en","v":"DRAGON GRACE ENTERPRISES LIMITED (d2003-01-17)"},{"lang":"hk","v":"龍恩企業有限公司"}],"company_since":"2000-05-10","company_dissolved":"2003-01-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715780","names":[{"lang":"en","v":"DSG ASIA LIMITED"},{"lang":"hk","v":"浩思亞洲研究顧問有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715783","names":[{"lang":"en","v":"E-AIRPORT INTERNATIONAL LIMITED"},{"lang":"hk","v":"數碼機場國際有限公司"}],"company_since":"2000-05-10","company_dissolved":"2001-09-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715625","names":[{"lang":"en","v":"CITYCOM INVESTMENT LIMITED"},{"lang":"hk","v":"錦城投資有限公司"}],"company_since":"2000-05-10","company_dissolved":"2012-07-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715743","names":[{"lang":"en","v":"E-CREDIT INFORMATION NETWORK (CHINA) LIMITED"},{"lang":"hk","v":"奔騰資訊網絡(中國)有限公司"}],"company_since":"2000-05-10","company_dissolved":"2003-03-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715744","names":[{"lang":"en","v":"E-CREDIT.COM.HK LIMITED"}],"company_since":"2000-05-10","company_dissolved":"2003-04-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715630","names":[{"lang":"en","v":"E-HOUSE PRODUCTION LIMITED"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715968","names":[{"lang":"en","v":"EASTERN WAVES COMPANY LIMITED"},{"lang":"hk","v":"意斯特有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715763","names":[{"lang":"en","v":"COME TRUE ELECTRONICS COMPANY LIMITED"},{"lang":"hk","v":"實現技術電子有限公司"}],"company_since":"2000-05-10","company_dissolved":"2003-03-07","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715943","names":[{"lang":"en","v":"EASTLINK INTERNATIONAL ENTERPRISE LIMITED"},{"lang":"hk","v":"東聯國際企業有限公司"}],"company_since":"2000-05-10","company_dissolved":"2010-08-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715875","names":[{"lang":"en","v":"EASY RANK INTERNATIONAL LIMITED"},{"lang":"hk","v":"卓訊國際有限公司"}],"company_since":"2000-05-10","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715808","names":[{"lang":"en","v":"EASYWIN GROUP LIMITED"},{"lang":"hk","v":"兆盈集團有限公司"}],"company_since":"2000-05-10","company_dissolved":"2003-12-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715731","names":[{"lang":"en","v":"EDWARD ANDREX LIMITED"}],"company_since":"2000-05-10","company_dissolved":"2002-07-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715831","names":[{"lang":"en","v":"ELEMENT DESIGN &amp; CONSTRUCTION LIMITED"},{"lang":"hk","v":"設計元素工程有限公司"}],"company_since":"2000-05-10","company_dissolved":"2003-07-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715723","names":[{"lang":"en","v":"ELTECH COMPANY LIMITED"},{"lang":"hk","v":"艾科股份有限公司"}],"company_since":"2000-05-10","company_dissolved":"2002-11-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715774","names":[{"lang":"en","v":"CONSTAR SHIPPING LIMITED"},{"lang":"hk","v":"港輝船務有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715724","names":[{"lang":"en","v":"CYBER DRAGON DEVELOPMENT LIMITED (d2002-04-12)"},{"lang":"hk","v":"進龍發展有限公司"}],"company_since":"2000-05-10","company_dissolved":"2002-04-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715747","names":[{"lang":"en","v":"ENGINEERING SURVEYS LIMITED (HK)"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715750","names":[{"lang":"en","v":"CYBER DRAGON INVESTMENT LIMITED (d2003-10-31)"},{"lang":"hk","v":"進龍投資有限公司"}],"company_since":"2000-05-10","company_dissolved":"2003-10-31","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715678","names":[{"lang":"en","v":"ERUM (HONG KONG) LIMITED"},{"lang":"hk","v":"怡隆(香港)有限公司"}],"company_since":"2000-05-10","company_dissolved":"2011-03-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715997","names":[{"lang":"en","v":"ESAMSUNG GREATER CHINA CO., LIMITED"}],"company_since":"2000-05-10","company_dissolved":"2013-08-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"715655","names":[{"lang":"en","v":"ETAILPACIFIC, LIMITED"},{"lang":"hk","v":"商營網有限公司"}],"company_since":"2000-05-10","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715824","names":[{"lang":"en","v":"DELISON INFO-COMMUNICATION LIMITED"},{"lang":"hk","v":"德利胜資訊有限公司"}],"company_since":"2000-05-10","company_dissolved":"2002-08-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715676","names":[{"lang":"en","v":"EX123 LIMITED"}],"company_since":"2000-05-10","company_dissolved":"2002-09-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715658","names":[{"lang":"en","v":"DESTINATION LIMITED"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715828","names":[{"lang":"en","v":"EXIMIN (ASIA) LIMITED"},{"lang":"hk","v":"善名(亞洲)有限公司"}],"company_since":"2000-05-10","company_dissolved":"2004-10-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715592","names":[{"lang":"en","v":"FAR EAST TABLEWARE LIMITED"},{"lang":"hk","v":"遠東集團發展有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715874","names":[{"lang":"en","v":"FAIRWOOD INTERNATIONAL LIMITED"},{"lang":"hk","v":"富杰國際有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715685","names":[{"lang":"en","v":"FAST PROFIT (HOLDINGS) PROPERTIES LIMITED"},{"lang":"hk","v":"快利達(集團)房地產有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715610","names":[{"lang":"en","v":"FORTUNE GRACE DEVELOPMENT LIMITED"},{"lang":"hk","v":"恩順發展有限公司"}],"company_since":"2000-05-10","company_dissolved":"2004-10-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715930","names":[{"lang":"en","v":"FULLWIN (CHINA) INDUSTRIAL LIMITED"},{"lang":"hk","v":"滙進(中國)實業有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715848","names":[{"lang":"en","v":"EVERBRIGHT SHIPPING LIMITED"},{"lang":"hk","v":"啟榮船務有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715835","names":[{"lang":"en","v":"GARDEN FOODS LIMITED (HK)"},{"lang":"hk","v":"花園美食有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715863","names":[{"lang":"en","v":"GATEWAY INVESTMENT LIMITED"},{"lang":"hk","v":"進杰投資有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715871","names":[{"lang":"en","v":"GIORGIO ARMANI HONG KONG LIMITED"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715839","names":[{"lang":"en","v":"GLOBAL LINK COMMUNICATIONS LIMITED (d2005-05-13)"}],"company_since":"2000-05-10","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715860","names":[{"lang":"en","v":"EXCEL BEST TRADING LIMITED"},{"lang":"hk","v":"鑫駿貿易有限公司"}],"company_since":"2000-05-10","company_dissolved":"2007-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715636","names":[{"lang":"en","v":"GLOBAL TREND INNOVATIONS LIMITED"},{"lang":"hk","v":"環宇股份有限公司"}],"company_since":"2000-05-10","company_dissolved":"2013-12-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715941","names":[{"lang":"en","v":"EXCEL INTERNATIONAL ENTERPRISE LIMITED"},{"lang":"hk","v":"卓智國際企業有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715949","names":[{"lang":"en","v":"GLORY BUSINESS INTERNATIONAL LIMITED"},{"lang":"hk","v":"盈商國際有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715909","names":[{"lang":"en","v":"GLORY INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"高勝國際投資有限公司"}],"company_since":"2000-05-10","company_dissolved":"2013-07-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715964","names":[{"lang":"en","v":"FAIR MARK LIMITED"},{"lang":"hk","v":"忠正有限公司"}],"company_since":"2000-05-10","company_dissolved":"2017-09-29","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715617","names":[{"lang":"en","v":"GOLD CITY TELECOMMUNICATION HONG KONG LIMITED"},{"lang":"hk","v":"高時通訊香港有限公司"}],"company_since":"2000-05-10","company_dissolved":"2001-10-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715673","names":[{"lang":"en","v":"GOLD POWER STEEL ENGINEERING LIMITED"},{"lang":"hk","v":"金力鋼鐵工程有限公司"}],"company_since":"2000-05-10","company_dissolved":"2002-12-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715633","names":[{"lang":"en","v":"GOLDEN GOODWILL LIMITED"},{"lang":"hk","v":"敦萊有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715851","names":[{"lang":"en","v":"GOLDEN HORSE MANAGEMENT LIMITED"},{"lang":"hk","v":"金馬管理有限公司"}],"company_since":"2000-05-10","company_dissolved":"2010-04-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715756","names":[{"lang":"en","v":"FORMAX HOLDINGS LIMITED"},{"lang":"hk","v":"和美集團有限公司"}],"company_since":"2000-05-10","company_dissolved":"2006-09-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715659","names":[{"lang":"en","v":"GOLDEN SEA GARMENT ACCESSORIES CO., LIMITED"},{"lang":"hk","v":"金海製衣配料有限公司"}],"company_since":"2000-05-10","company_dissolved":"2004-08-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715748","names":[{"lang":"en","v":"FAST PRODUCTION EQUIPMENT MANUFACTURER COMPANY LIMITED"},{"lang":"hk","v":"快達生產設備製造有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715938","names":[{"lang":"en","v":"GOLDEN YEAR INTERNATIONAL ENTERPRISE LIMITED"},{"lang":"hk","v":"金年國際企業有限公司"}],"company_since":"2000-05-10","company_dissolved":"2015-01-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715709","names":[{"lang":"en","v":"FRANCE MELARILA INT'L GROUP LIMITED"},{"lang":"hk","v":"法國梅蘭日蘭國際集團有限公司"}],"company_since":"2000-05-10","company_dissolved":"2008-10-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715969","names":[{"lang":"en","v":"GOLDYARD INTERNATIONAL LIMITED"},{"lang":"hk","v":"金塘國際有限公司"}],"company_since":"2000-05-10","company_dissolved":"2002-09-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715937","names":[{"lang":"en","v":"GOODSINO INTERNATIONAL ENTERPRISE LIMITED"},{"lang":"hk","v":"偉華國際企業有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715773","names":[{"lang":"en","v":"GRANDFUL SHIPPING LIMITED"},{"lang":"hk","v":"昌富船務有限公司"}],"company_since":"2000-05-10","company_dissolved":"2006-04-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715769","names":[{"lang":"en","v":"GRANDWELL (ASIA PACIFIC) LIMITED"},{"lang":"hk","v":"冠威(亞太)有限公司"}],"company_since":"2000-05-10","company_dissolved":"2001-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715680","names":[{"lang":"en","v":"GAOMING SILVER OCEAN GOLF CLUB CO., LIMITED"},{"lang":"hk","v":"高明銀海高爾夫球俱樂部有限公司"}],"company_since":"2000-05-10","company_dissolved":"2011-05-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715629","names":[{"lang":"en","v":"GET AHEAD DEVELOPMENT LIMITED"},{"lang":"hk","v":"德佑發展有限公司"}],"company_since":"2000-05-10","company_dissolved":"2014-11-07","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715696","names":[{"lang":"en","v":"GREENWAY PRODUCTS LIMITED (HK)"},{"lang":"hk","v":"綠之道有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715972","names":[{"lang":"en","v":"GUMWAY LIMITED"},{"lang":"hk","v":"金韋有限公司"}],"company_since":"2000-05-10","company_dissolved":"2005-03-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715939","names":[{"lang":"en","v":"FULLSINO INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"中泰國際發展有限公司"}],"company_since":"2000-05-10","company_dissolved":"2002-07-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715726","names":[{"lang":"en","v":"GLASPAK INTERNATIONAL LIMITED"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715698","names":[{"lang":"en","v":"H.K. LUOLAN ENTERPRISE GROUP LIMITED"},{"lang":"hk","v":"香港羅蘭企業集團有限公司"}],"company_since":"2000-05-10","company_dissolved":"2003-10-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715826","names":[{"lang":"en","v":"H.K. ZHONGGANG PROPERTY DEVELOPMENT LIMITED"},{"lang":"hk","v":"香港中港置業發展有限公司"}],"company_since":"2000-05-10","company_dissolved":"2006-09-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"716007","names":[{"lang":"en","v":"HEALTHCARE PHONE ADVISORY OPERATIONS (HK) LIMITED"},{"lang":"hk","v":"盈康醫護專線(香港)有限公司"}],"company_since":"2000-05-10","company_dissolved":"2003-01-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"716006","names":[{"lang":"en","v":"HEALTHCARE MEDICAL &amp; PARAMEDICAL SERVICES OPERATIONS (HK) LIMITED"},{"lang":"hk","v":"盈康醫療及化驗(香港)有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"716004","names":[{"lang":"en","v":"HEALTHCARE VPN PHARMACY OPERATIONS (HK) LIMITED"},{"lang":"hk","v":"盈康醫療專網藥業(香港)有限公司"}],"company_since":"2000-05-10","company_dissolved":"2003-03-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715876","names":[{"lang":"en","v":"GOLDEN PROSPER INVESTMENT LIMITED (d2006-01-13)"},{"lang":"hk","v":"金茂投資有限公司"}],"company_since":"2000-05-10","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715842","names":[{"lang":"en","v":"HEROMAN INTERNATIONAL (H.K.) LIMITED"},{"lang":"hk","v":"雄兵國際(香港)有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715849","names":[{"lang":"en","v":"HI-TECH SHIPPING LIMITED"},{"lang":"hk","v":"聯昇船務有限公司"}],"company_since":"2000-05-10","company_dissolved":"2008-10-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715990","names":[{"lang":"en","v":"GOOD HARVEST PRODUCTION CO., LIMITED"},{"lang":"hk","v":"金豐製作有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715908","names":[{"lang":"en","v":"GOODGAIN INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"得泰國際發展有限公司"}],"company_since":"2000-05-10","company_dissolved":"2012-12-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715710","names":[{"lang":"en","v":"HK BOSSILE LIGHTING LIMITED"},{"lang":"hk","v":"香港保時利燈飾有限公司"}],"company_since":"2000-05-10","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715924","names":[{"lang":"en","v":"HK CITY OASIS LIMITED"},{"lang":"hk","v":"香港城市綠洲有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715736","names":[{"lang":"en","v":"GRANDWICK HOLDINGS LIMITED (d2006-01-13)"},{"lang":"hk","v":"光偉集團有限公司"}],"company_since":"2000-05-10","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715711","names":[{"lang":"en","v":"HK LONGDO IND. DEV. LIMITED"},{"lang":"hk","v":"香港龍盾實業發展有限公司"}],"company_since":"2000-05-10","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715873","names":[{"lang":"en","v":"HONDAR INTERNATIONAL LIMITED"},{"lang":"hk","v":"啟圖國際有限公司"}],"company_since":"2000-05-10","company_dissolved":"2007-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715822","names":[{"lang":"en","v":"HONG KONG ENVIRONMENTAL INDUSTRY ASSOCIATION LIMITED"},{"lang":"hk","v":"香港環保產業協會有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
undefined,
undefined,
{"tax_id":"715840","names":[{"lang":"en","v":"HIT BANNER GROUP LIMITED"},{"lang":"hk","v":"哈工大八達集團有限公司"}],"company_since":"2000-05-10","company_dissolved":"2001-11-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715827","names":[{"lang":"en","v":"HONG KONG ILINK DEVELOPMENT LIMITED"},{"lang":"hk","v":"宏力拓展有限公司"}],"company_since":"2000-05-10","company_dissolved":"2005-08-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715929","names":[{"lang":"en","v":"HONG KONG PUJIANG HUALIAN LIMITED"},{"lang":"hk","v":"香港浦江華聯有限公司"}],"company_since":"2000-05-10","company_dissolved":"2005-11-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715985","names":[{"lang":"en","v":"HONG KONG SOCIETY FOR CHILDREN'S EDUCATION &amp; ART LIMITED"},{"lang":"hk","v":"香港兒童美術及教育協會有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715804","names":[{"lang":"en","v":"HI-GEAR (H.K.) LIMITED"},{"lang":"hk","v":"開翹(香港)有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715666","names":[{"lang":"en","v":"HUA HENG ENVIRONMENTAL ASSETS LIMITED"},{"lang":"hk","v":"華亨環保產業有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715674","names":[{"lang":"en","v":"HUIJING TRADING LIMITED"},{"lang":"hk","v":"匯錦貿易有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715917","names":[{"lang":"en","v":"HICOM ASSET MANAGEMENT LIMITED"},{"lang":"hk","v":"高訊資產管理有限公司"}],"company_since":"2000-05-10","company_dissolved":"2013-10-25","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715830","names":[{"lang":"en","v":"HUNG FAT TRADING TRANSPORTATION COMPANY LIMITED"},{"lang":"hk","v":"雄發貿易運輸有限公司"}],"company_since":"2000-05-10","company_dissolved":"2010-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715706","names":[{"lang":"en","v":"HWA SUNG ELECTRONICS (H.K.) CO. LIMITED (d2006-05-12)"},{"lang":"hk","v":"華盛電子(香港)有限公司"}],"company_since":"2000-05-10","company_dissolved":"2006-05-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"715916","names":[{"lang":"en","v":"HYDROLAB ASIA LIMITED"}],"company_since":"2000-05-10","company_dissolved":"2003-12-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715708","names":[{"lang":"en","v":"HK FREEZING POINT DRESS INT'L LIMITED (d2010-12-24)"},{"lang":"hk","v":"香港冰點服飾國際有限公司"}],"company_since":"2000-05-10","company_dissolved":"2010-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715996","names":[{"lang":"en","v":"I-HEALTH (ASIA) LIMITED"},{"lang":"hk","v":"健而康有限公司"}],"company_since":"2000-05-10","company_dissolved":"2010-08-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715597","names":[{"lang":"en","v":"HOLYBRIDGE INTERNATIONAL LIMITED"},{"lang":"hk","v":"合力金橋國際有限公司"}],"company_since":"2000-05-10","company_dissolved":"2006-09-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715995","names":[{"lang":"en","v":"I-WORKS DIGITAL MEDIA COMPANY LIMITED"},{"lang":"hk","v":"網通數字媒體有限公司"}],"company_since":"2000-05-10","company_dissolved":"2003-11-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715879","names":[{"lang":"en","v":"I.T TRAVEL LIMITED"},{"lang":"hk","v":"天行旅遊有限公司"}],"company_since":"2000-05-10","company_dissolved":"2008-06-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715722","names":[{"lang":"en","v":"ICM (CHINA) LIMITED"},{"lang":"hk","v":"愛克斯姆(中國)有限公司"}],"company_since":"2000-05-10","company_dissolved":"2008-10-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715650","names":[{"lang":"en","v":"HONG KONG BRAIN CLUB LIMITED"},{"lang":"hk","v":"香港大腦潛能有限公司"}],"company_since":"2000-05-10","company_dissolved":"2007-09-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715781","names":[{"lang":"en","v":"IDEAL TOP FORM LIMITED"}],"company_since":"2000-05-10","company_dissolved":"2002-10-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715832","names":[{"lang":"en","v":"HONG KONG ASIA PACIFIC PHOTOGRAPHY ASSOCIATION COMPANY LIMITED"},{"lang":"hk","v":"香港亞洲攝影雜誌社有限公司"}],"company_since":"2000-05-10","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715841","names":[{"lang":"en","v":"HONG KONG FA DENNIS FASHION (INTERNATIONAL) HOLDING LIMITED"},{"lang":"hk","v":"香港法丹尼服飾(國際)集團有限公司"}],"company_since":"2000-05-10","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715983","names":[{"lang":"en","v":"J.E.S. SECRETARIES AND MANAGEMENT LIMITED"},{"lang":"hk","v":"明誠秘書及管理有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715758","names":[{"lang":"en","v":"JASPER LIMITED (d2005-05-27)"},{"lang":"hk","v":"傑平有限公司"}],"company_since":"2000-05-10","company_dissolved":"2005-05-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715600","names":[{"lang":"en","v":"JETWAY CORPORATION LIMITED"},{"lang":"hk","v":"志程有限公司"}],"company_since":"2000-05-10","company_dissolved":"2003-10-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715613","names":[{"lang":"en","v":"JIN BAO TONG INTERNATIONAL FINANCIAL GROUP CO., LIMITED"},{"lang":"hk","v":"金寶通國際金融集團有限公司"}],"company_since":"2000-05-10","company_dissolved":"2009-10-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715753","names":[{"lang":"en","v":"JOIN TARGET INTERNATIONAL LIMITED"},{"lang":"hk","v":"豪志國際有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715893","names":[{"lang":"en","v":"JOYLINK INTERNATIONAL DEVELOPMENT LIMITED (d2006-09-22)"},{"lang":"hk","v":"嘉滙國際發展有限公司"}],"company_since":"2000-05-10","company_dissolved":"2006-09-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715669","names":[{"lang":"en","v":"KA KIT (INTERNATIONAL) DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"嘉傑(國際)發展有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715595","names":[{"lang":"en","v":"HONG KONG YANG MEN INTERNATIONAL HOLDING LIMITED"},{"lang":"hk","v":"香港楊門國際集團有限公司"}],"company_since":"2000-05-10","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715749","names":[{"lang":"en","v":"HONG KONG INTERNATIONAL ASSOCIATION OF CHINESE MEDICAL PRACTITIONERS LIMITED"},{"lang":"hk","v":"香港國際中醫師聯合總會有限公司"}],"company_since":"2000-05-10","company_dissolved":"2014-09-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715614","names":[{"lang":"en","v":"HONG KONG WEIKE GROUP CO., LIMITED"},{"lang":"hk","v":"香港偉克集團有限公司"}],"company_since":"2000-05-10","company_dissolved":"2006-09-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715950","names":[{"lang":"en","v":"KASIN ENGINEERING LIMITED"},{"lang":"hk","v":"嘉昇工程有限公司"}],"company_since":"2000-05-10","company_dissolved":"2006-07-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715823","names":[{"lang":"en","v":"KEYLANDMARK LIMITED"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715690","names":[{"lang":"en","v":"KIMBERLEY METALWORK LIMITED"},{"lang":"hk","v":"建百利金屬工藝有限公司"}],"company_since":"2000-05-10","company_dissolved":"2007-11-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715766","names":[{"lang":"en","v":"KINDIX LIMITED"},{"lang":"hk","v":"駿薈有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715994","names":[{"lang":"en","v":"I-WORKS DIGITAL CONCEPTS COMPANY LIMITED"},{"lang":"hk","v":"網通數碼創力有限公司"}],"company_since":"2000-05-10","company_dissolved":"2002-08-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715970","names":[{"lang":"en","v":"KING CHINA ENGINEERING LIMITED"},{"lang":"hk","v":"長華工程有限公司"}],"company_since":"2000-05-10","company_dissolved":"2002-10-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715919","names":[{"lang":"en","v":"KINGMA INVESTMENTS (HOLDING) GROUP COMPANY LIMITED"},{"lang":"hk","v":"金馬投資控股(集團)有限公司"}],"company_since":"2000-05-10","company_dissolved":"2012-12-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715649","names":[{"lang":"en","v":"KING WAI CONSULTANCY LIMITED"},{"lang":"hk","v":"經緯顧問有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715664","names":[{"lang":"en","v":"KINGSWORLD FAR EAST LIMITED"},{"lang":"hk","v":"嘉匯遠東有限公司"}],"company_since":"2000-05-10","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715814","names":[{"lang":"en","v":"ISMART MANAGEMENT LIMITED"},{"lang":"hk","v":"智盈管理有限公司"}],"company_since":"2000-05-10","company_dissolved":"2001-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715671","names":[{"lang":"en","v":"JANE DOE HONG KONG LIMITED"}],"company_since":"2000-05-10","company_dissolved":"2011-07-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715884","names":[{"lang":"en","v":"LEEPHARM ENTERPRISES LIMITED"},{"lang":"hk","v":"力達藥業有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715982","names":[{"lang":"en","v":"KEI KEE CONSTRUCTION ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"其記建築工程有限公司"}],"company_since":"2000-05-10","company_dissolved":"2006-10-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715966","names":[{"lang":"en","v":"LINK FORCE HOLDINGS LIMITED"},{"lang":"hk","v":"連力集團有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715865","names":[{"lang":"en","v":"LINKFIELD (HK) LIMITED"},{"lang":"hk","v":"信升(香港)有限公司"}],"company_since":"2000-05-10","company_dissolved":"2010-04-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715958","names":[{"lang":"en","v":"KAREN VALETTA (INTERNATIONAL) LIMITED"},{"lang":"hk","v":"凱倫(國際)有限公司"}],"company_since":"2000-05-10","company_dissolved":"2003-10-31","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715787","names":[{"lang":"en","v":"LORA &amp; FESTA LIMITED"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715991","names":[{"lang":"en","v":"MAG SNAP LIMITED"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715971","names":[{"lang":"en","v":"MARK FAME LIMITED (d2009-10-02)"},{"lang":"hk","v":"鈞譽有限公司"}],"company_since":"2000-05-10","company_dissolved":"2009-10-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715993","names":[{"lang":"en","v":"MATRIX HITECH LIMITED"}],"company_since":"2000-05-10","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715796","names":[{"lang":"en","v":"MEDICAL CONTENT PROVIDER LIMITED"},{"lang":"hk","v":"醫療內容供應有限公司"}],"company_since":"2000-05-10","company_dissolved":"2001-10-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715837","names":[{"lang":"en","v":"MEGATEAM MEDIA LIMITED"},{"lang":"hk","v":"天科傳播網絡有限公司"}],"company_since":"2000-05-10","company_dissolved":"2005-04-01","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715806","names":[{"lang":"en","v":"MEGAWELL ENTERPRISE LIMITED"},{"lang":"hk","v":"順栢企業有限公司"}],"company_since":"2000-05-10","company_dissolved":"2006-01-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715956","names":[{"lang":"en","v":"MENIC MEDIA LIMITED"},{"lang":"hk","v":"萬力多媒體有限公司"}],"company_since":"2000-05-10","company_dissolved":"2008-06-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715653","names":[{"lang":"en","v":"LEGEND NET HOLDINGS LIMITED"},{"lang":"hk","v":"里駿集團有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715790","names":[{"lang":"en","v":"MG TECHNOLOGY LIMITED"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715716","names":[{"lang":"en","v":"MIDLAND MANAGEMENT CONSULTANTS LIMITED"},{"lang":"hk","v":"美聯管理顧問有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715733","names":[{"lang":"en","v":"LEGEND VANTAGE SHIPPING LIMITED"},{"lang":"hk","v":"利永船務有限公司"}],"company_since":"2000-05-10","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715717","names":[{"lang":"en","v":"MIDLAND PROPERTY SERVICES LIMITED (HK)"},{"lang":"hk","v":"美聯地產服務有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715812","names":[{"lang":"en","v":"LEUNG SHING ON ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"梁成安工程有限公司"}],"company_since":"2000-05-10","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715918","names":[{"lang":"en","v":"MILLION SOURCES LIMITED"},{"lang":"hk","v":"科翔有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715836","names":[{"lang":"en","v":"LUNG WAH CLOTH FACTORY LIMITED"},{"lang":"hk","v":"龍華布廠有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715738","names":[{"lang":"en","v":"MODEL TECHNOLOGY LIMITED"},{"lang":"hk","v":"經典科技有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715687","names":[{"lang":"en","v":"MAHARISHI GLOBAL TRADING LIMITED"}],"company_since":"2000-05-10","company_dissolved":"2002-09-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715847","names":[{"lang":"en","v":"MORNING STAR SHIPPING LIMITED"},{"lang":"hk","v":"鴻星船務有限公司"}],"company_since":"2000-05-10","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715890","names":[{"lang":"en","v":"MWH IFI LIMITED"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715661","names":[{"lang":"en","v":"NEW BILLION RICH PRINTING (H.K.) CO. LIMITED"},{"lang":"hk","v":"新億達印刷(香港)有限公司"}],"company_since":"2000-05-10","company_dissolved":"2010-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715624","names":[{"lang":"en","v":"LONG PEAK ENTERPRISES LIMITED"},{"lang":"hk","v":"長峰企業有限公司"}],"company_since":"2000-05-10","company_dissolved":"2005-12-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715881","names":[{"lang":"en","v":"NEW TECHNOLOGY CONSULTANT COMPANY LIMITED"},{"lang":"hk","v":"新科顧問有限公司"}],"company_since":"2000-05-10","company_dissolved":"2017-11-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715910","names":[{"lang":"en","v":"NOAHS ARK INTERNATIONAL LIMITED"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715975","names":[{"lang":"en","v":"NOVA MANAGEMENT CONSULTANTS LIMITED"},{"lang":"hk","v":"至善管理顧問有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715645","names":[{"lang":"en","v":"MEGA LOGISTICS SERVICES LIMITED"},{"lang":"hk","v":"美嘉物流貨運有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715662","names":[{"lang":"en","v":"NOVASPRINT (HK) LIMITED"},{"lang":"hk","v":"榮騰科技(香港)有限公司"}],"company_since":"2000-05-10","company_dissolved":"2006-10-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715789","names":[{"lang":"en","v":"OCEAN ITALIA (H.K.) LIMITED"}],"company_since":"2000-05-10","company_dissolved":"2009-11-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715725","names":[{"lang":"en","v":"OCEAN GROUP DEVELOPMENT LIMITED (d2004-11-26)"},{"lang":"hk","v":"兆海發展有限公司"}],"company_since":"2000-05-10","company_dissolved":"2004-11-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715864","names":[{"lang":"en","v":"MASTER ART INVESTMENT LIMITED"},{"lang":"hk","v":"勤建投資有限公司"}],"company_since":"2000-05-10","company_dissolved":"2006-09-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715616","names":[{"lang":"en","v":"ONKINS &amp; ASSOCIATE LIMITED"},{"lang":"hk","v":"漢基設計有限公司"}],"company_since":"2000-05-10","company_dissolved":"2003-06-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715986","names":[{"lang":"en","v":"ORIGIN (FAR EAST) MARINE TRADING CO. LIMITED"},{"lang":"hk","v":"起源(遠東)海產貿易有限公司"}],"company_since":"2000-05-10","company_dissolved":"2004-09-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715719","names":[{"lang":"en","v":"MIDLAND PROPERTY ADMINISTRATION LIMITED"},{"lang":"hk","v":"美聯地產管理有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715959","names":[{"lang":"en","v":"OUT OF THE BLUE (HONG KONG) LIMITED"},{"lang":"hk","v":"歐寶香港有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"715817","names":[{"lang":"en","v":"PACIFIC ASSETS DEVELOPMENT LIMITED"},{"lang":"hk","v":"時輝發展有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715882","names":[{"lang":"en","v":"PEN POWER TECHNOLOGY (HONG KONG) LIMITED"},{"lang":"hk","v":"蒙恬科技(香港)有限公司"}],"company_since":"2000-05-10","company_dissolved":"2007-02-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715721","names":[{"lang":"en","v":"MIDLAND REALTY (CYBER MALL) LIMITED"},{"lang":"hk","v":"美聯物業(數碼廣場)有限公司"}],"company_since":"2000-05-10","company_dissolved":"2012-10-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715880","names":[{"lang":"en","v":"PILOT PACIFIC LIMITED"},{"lang":"hk","v":"曉洋有限公司"}],"company_since":"2000-05-10","company_dissolved":"2004-08-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715764","names":[{"lang":"en","v":"PLANET.COM LIMITED (d2006-01-13)"},{"lang":"hk","v":"天下網有限公司"}],"company_since":"2000-05-10","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715612","names":[{"lang":"en","v":"POPULAR HERO INTERNATIONAL LIMITED"},{"lang":"hk","v":"眾豪國際有限公司"}],"company_since":"2000-05-10","company_dissolved":"2012-12-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715626","names":[{"lang":"en","v":"POSTCOM PACIFIC LIMITED"},{"lang":"hk","v":"浦平有限公司"}],"company_since":"2000-05-10","company_dissolved":"2009-01-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715891","names":[{"lang":"en","v":"NEW POWER (HONG KONG) LIMITED"},{"lang":"hk","v":"耀良(香港)有限公司"}],"company_since":"2000-05-10","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"716008","names":[{"lang":"en","v":"PREMIUM HEALTHCARE TRADITIONAL CHINESE MEDICINE COMPANY LIMITED"},{"lang":"hk","v":"泛亞全健中醫醫療有限公司"}],"company_since":"2000-05-10","company_dissolved":"2006-02-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715815","names":[{"lang":"en","v":"PRETTY WELL INVESTMENT LIMITED"},{"lang":"hk","v":"鴻越投資有限公司"}],"company_since":"2000-05-10","company_dissolved":"2014-05-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715675","names":[{"lang":"en","v":"PRODUCTSLINK CO., LIMITED"},{"lang":"hk","v":"普寧建材有限公司"}],"company_since":"2000-05-10","company_dissolved":"2003-10-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715637","names":[{"lang":"en","v":"RAINBOW WISH LIMITED (d2013-03-08)"},{"lang":"hk","v":"鍵彩有限公司"}],"company_since":"2000-05-10","company_dissolved":"2013-03-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715670","names":[{"lang":"en","v":"READER'S DIGEST (CHINA) DIRECT MARKETING SERVICE CO., LIMITED"},{"lang":"hk","v":"讀者文摘(中國)直郵服務有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715960","names":[{"lang":"en","v":"REJUVENATING CENTRE LIMITED"},{"lang":"hk","v":"維珍美健中心有限公司"}],"company_since":"2000-05-10","company_dissolved":"2002-11-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715843","names":[{"lang":"en","v":"RICH MARK INDUSTRIES LIMITED"},{"lang":"hk","v":"如意實業有限公司"}],"company_since":"2000-05-10","company_dissolved":"2012-07-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715934","names":[{"lang":"en","v":"RICHMATE GARMENT LIMITED"},{"lang":"hk","v":"富美製衣有限公司"}],"company_since":"2000-05-10","company_dissolved":"2010-12-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715820","names":[{"lang":"en","v":"RICHTONE TRADING LIMITED (d2009-07-22)"},{"lang":"hk","v":"捷駿貿易有限公司"}],"company_since":"2000-05-10","company_dissolved":"2009-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715961","names":[{"lang":"en","v":"PREMIER (BUILDING SUPPLIES &amp; ENGINEERING) COMPANY LIMITED"},{"lang":"hk","v":"創峯(建材工程)有限公司"}],"company_since":"2000-05-10","company_dissolved":"2004-12-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715799","names":[{"lang":"en","v":"RKH CONSULTANTS LIMITED (HK)"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715838","names":[{"lang":"en","v":"S. T. TRAVEL SERVICE COMPANY LIMITED"},{"lang":"hk","v":"三通旅遊有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715594","names":[{"lang":"en","v":"MINDEN HOTELS LIMITED"}],"company_since":"2000-05-10","company_dissolved":"2014-04-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715602","names":[{"lang":"en","v":"PRIMANENT SERVICES LIMITED"},{"lang":"hk","v":"全天候有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715889","names":[{"lang":"en","v":"SALISBURY SECURITIES LIMITED"}],"company_since":"2000-05-10","company_dissolved":"2018-07-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715704","names":[{"lang":"en","v":"SAMPLE TRADERS INTERNATIONAL TRADING LIMITED"},{"lang":"hk","v":"三普國際貿易有限公司"}],"company_since":"2000-05-10","company_dissolved":"2002-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715672","names":[{"lang":"en","v":"PROFESSIONAL SCAFFOLDING ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"專業棚架工程有限公司"}],"company_since":"2000-05-10","company_dissolved":"2012-07-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715888","names":[{"lang":"en","v":"PURE GUARD ENTERPRISE LIMITED"},{"lang":"hk","v":"淨寶企業有限公司"}],"company_since":"2000-05-10","company_dissolved":"2013-03-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715920","names":[{"lang":"en","v":"SCHAETTI (CHINA) LIMITED"},{"lang":"hk","v":"瑞士沙提(中國)有限公司"}],"company_since":"2000-05-10","company_dissolved":"2005-10-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715620","names":[{"lang":"en","v":"R &amp; R HONG KONG LIMITED"},{"lang":"hk","v":"雅彩香港有限公司"}],"company_since":"2000-05-10","company_dissolved":"2007-09-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715703","names":[{"lang":"en","v":"SHING KONG INTERNATIONAL TRADING LIMITED"},{"lang":"hk","v":"誠光國際貿易有限公司"}],"company_since":"2000-05-10","company_dissolved":"2001-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715892","names":[{"lang":"en","v":"REALINK INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"偉得國際投資有限公司"}],"company_since":"2000-05-10","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715707","names":[{"lang":"en","v":"SHUN HING (CHINA) SHIPPING LIMITED"},{"lang":"hk","v":"信興(中國)船務有限公司"}],"company_since":"2000-05-10","company_dissolved":"2010-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715688","names":[{"lang":"en","v":"SHUN SHING ENGINEERING DEVELOPMENT LIMITED"},{"lang":"hk","v":"信誠工程發展有限公司"}],"company_since":"2000-05-10","company_dissolved":"2004-02-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715652","names":[{"lang":"en","v":"SILVER ART MARKETING LIMITED"},{"lang":"hk","v":"銀藝拓展有限公司"}],"company_since":"2000-05-10","company_dissolved":"2001-10-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715697","names":[{"lang":"en","v":"REMIXASIA.COM LIMITED"}],"company_since":"2000-05-10","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715821","names":[{"lang":"en","v":"SINO EXPRESS INVESTMENTS LIMITED"},{"lang":"hk","v":"旭盈投資有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715818","names":[{"lang":"en","v":"SINO YIELD ENTERPRISE LIMITED (d2003-10-31)"},{"lang":"hk","v":"聚豪企業有限公司"}],"company_since":"2000-05-10","company_dissolved":"2003-10-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715693","names":[{"lang":"en","v":"RICH TASTE TRADING LIMITED"},{"lang":"hk","v":"裕品貿易有限公司"}],"company_since":"2000-05-10","company_dissolved":"2015-05-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715797","names":[{"lang":"en","v":"SINOPAC SECURITIES (H.K.) LIMITED"},{"lang":"hk","v":"華信證券(香港)有限公司"}],"company_since":"2000-05-10","company_dissolved":"2005-04-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715935","names":[{"lang":"en","v":"RICHLINK INTERNATIONAL TRADING LIMITED"},{"lang":"hk","v":"富聯國際貿易有限公司"}],"company_since":"2000-05-10","company_dissolved":"2008-10-31","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715932","names":[{"lang":"en","v":"SKY APEX LIMITED (d2006-12-01)"},{"lang":"hk","v":"宏天行有限公司"}],"company_since":"2000-05-10","company_dissolved":"2006-12-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715691","names":[{"lang":"en","v":"SKY DATAMANN (HONG KONG) LIMITED"},{"lang":"hk","v":"天城互聯數據(香港)有限公司"}],"company_since":"2000-05-10","company_dissolved":"2011-05-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715752","names":[{"lang":"en","v":"SKY OCEAN ENTERPRISES LIMITED (d2007-09-28)"},{"lang":"hk","v":"天洋企業有限公司"}],"company_since":"2000-05-10","company_dissolved":"2007-09-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715907","names":[{"lang":"en","v":"SKY RAINBOW GARMENT LIMITED"},{"lang":"hk","v":"天彩製衣有限公司"}],"company_since":"2000-05-10","company_dissolved":"2002-10-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"715779","names":[{"lang":"en","v":"SAINTY TOP GLOBAL LIMITED"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715762","names":[{"lang":"en","v":"SAM YICK ENGINEERING LIMITED"},{"lang":"hk","v":"三益工程有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715700","names":[{"lang":"en","v":"SAWTAN GEMS LIMITED"}],"company_since":"2000-05-10","company_dissolved":"2005-02-01","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715631","names":[{"lang":"en","v":"SOFT OBJECTS (HONG KONG) LIMITED"}],"company_since":"2000-05-10","company_dissolved":"2003-11-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715639","names":[{"lang":"en","v":"SMOOTH LUCK LIMITED"},{"lang":"hk","v":"鍵順有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715878","names":[{"lang":"en","v":"SOFTENABLE TECHNOLOGY LIMITED"},{"lang":"hk","v":"軟能科技有限公司"}],"company_since":"2000-05-10","company_dissolved":"2010-07-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715979","names":[{"lang":"en","v":"SOUNDWELL ELECTRIC COMPANY LIMITED"},{"lang":"hk","v":"三好電子有限公司"}],"company_since":"2000-05-10","company_dissolved":"2001-10-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715667","names":[{"lang":"en","v":"SANG CHEONG HO FASHION LIMITED"},{"lang":"hk","v":"生昌號服飾有限公司"}],"company_since":"2000-05-10","company_dissolved":"2019-03-01","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715757","names":[{"lang":"en","v":"SOUTH EAST TECHNOLOGY LIMITED (d2009-12-11)"},{"lang":"hk","v":"東南科技有限公司"}],"company_since":"2000-05-10","company_dissolved":"2009-12-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715998","names":[{"lang":"en","v":"SOUTHERN ASIA INVESTMENTS AND ASSET MANAGEMENT LIMITED"}],"company_since":"2000-05-10","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715933","names":[{"lang":"en","v":"SILVER INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"銀駿國際投資有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715607","names":[{"lang":"en","v":"SUCCESS INDUSTRIES LIMITED"},{"lang":"hk","v":"成達工業有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715772","names":[{"lang":"en","v":"SUNPOWER PACIFIC LIMITED"},{"lang":"hk","v":"新力太平洋有限公司"}],"company_since":"2000-05-10","company_dissolved":"2015-12-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715771","names":[{"lang":"en","v":"SUNPOWER UNIVERSAL LIMITED"},{"lang":"hk","v":"日達環球有限公司"}],"company_since":"2000-05-10","company_dissolved":"2008-11-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"715765","names":[{"lang":"en","v":"SUPERIOR.COM LIMITED"},{"lang":"hk","v":"卓越網有限公司"}],"company_since":"2000-05-10","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715642","names":[{"lang":"en","v":"SWING INTERNATIONAL LIMITED (d2003-09-11)"},{"lang":"hk","v":"紹榮國際有限公司"}],"company_since":"2000-05-10","company_dissolved":"2003-09-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715618","names":[{"lang":"en","v":"TEENS COMMUNICATIONS LIMITED"}],"company_since":"2000-05-10","company_dissolved":"2001-05-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715957","names":[{"lang":"en","v":"SMART GOLD (C.T.) LIMITED"},{"lang":"hk","v":"萬利高發展有限公司"}],"company_since":"2000-05-10","company_dissolved":"2013-09-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"715598","names":[{"lang":"en","v":"TIGER BUTTON (HONG KONG) LIMITED"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715936","names":[{"lang":"en","v":"TIM EDPLATFORM LIMITED"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715962","names":[{"lang":"en","v":"TIANLI (FAR EAST) ENTERPRISES COMPANY LIMITED"},{"lang":"hk","v":"天利(遠東)企業有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715776","names":[{"lang":"en","v":"SOUTHSTAR HOLDINGS LIMITED"},{"lang":"hk","v":"南達集團有限公司"}],"company_since":"2000-05-10","company_dissolved":"2009-10-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715901","names":[{"lang":"en","v":"TOPGAIN INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"冠利國際投資有限公司"}],"company_since":"2000-05-10","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715770","names":[{"lang":"en","v":"SUNPOWER ASIA LIMITED"},{"lang":"hk","v":"輝力亞洲有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715900","names":[{"lang":"en","v":"TOPHILL INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"聯峰國際發展有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715816","names":[{"lang":"en","v":"SUPER CLASSIC DEVELOPMENT LIMITED"},{"lang":"hk","v":"奔威發展有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715898","names":[{"lang":"en","v":"TOPWEALTH INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"群富國際發展有限公司"}],"company_since":"2000-05-10","company_dissolved":"2013-07-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715819","names":[{"lang":"en","v":"SUPREME TALENT INTERNATIONAL LIMITED"},{"lang":"hk","v":"雄滔國際有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715896","names":[{"lang":"en","v":"TREASURE INTERNATIONAL TRADING LIMITED (d2012-02-10)"},{"lang":"hk","v":"群富國際貿易有限公司"}],"company_since":"2000-05-10","company_dissolved":"2012-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715927","names":[{"lang":"en","v":"SPORTZITE.COM LIMITED"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715621","names":[{"lang":"en","v":"TREASURE RIVER HOLDINGS LIMITED"},{"lang":"hk","v":"河寶集團有限公司"}],"company_since":"2000-05-10","company_dissolved":"2006-09-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715977","names":[{"lang":"en","v":"TREASURE SOURCE INDUSTRIAL LIMITED"},{"lang":"hk","v":"源浩實業有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715628","names":[{"lang":"en","v":"SYNERGY LIMITED (HK)"},{"lang":"hk","v":"凝力有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715608","names":[{"lang":"en","v":"TOY WONDER COMPANY LIMITED"},{"lang":"hk","v":"泓達玩具有限公司"}],"company_since":"2000-05-10","company_dissolved":"2018-07-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715599","names":[{"lang":"en","v":"TRIPLE WILL INTERNATIONAL LIMITED"},{"lang":"hk","v":"志培國際有限公司"}],"company_since":"2000-05-10","company_dissolved":"2013-04-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"715805","names":[{"lang":"en","v":"TEAM BEST ENTERPRISES LIMITED"},{"lang":"hk","v":"長樂企業有限公司"}],"company_since":"2000-05-10","company_dissolved":"2002-08-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"715677","names":[{"lang":"en","v":"THUNDER SKY POWER SOURCE (HK) COMPANY LIMITED"},{"lang":"hk","v":"雷天綠色電動源(香港)有限公司"}],"company_since":"2000-05-10","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715644","names":[{"lang":"en","v":"SURREY HOLDINGS LIMITED (d2006-06-23)"},{"lang":"hk","v":"訊利集團有限公司"}],"company_since":"2000-05-10","company_dissolved":"2006-06-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715899","names":[{"lang":"en","v":"TOPSINO CORPORATION LIMITED (d2004-06-25)"},{"lang":"hk","v":"中冠行有限公司"}],"company_since":"2000-05-10","company_dissolved":"2004-06-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715895","names":[{"lang":"en","v":"WEALTH CHAIN PROPERTIES LIMITED"},{"lang":"hk","v":"群富置業有限公司"}],"company_since":"2000-05-10","company_dissolved":"2004-01-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715852","names":[{"lang":"en","v":"TRANS GLOBAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"合冠發展有限公司"}],"company_since":"2000-05-10","company_dissolved":"2008-12-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715695","names":[{"lang":"en","v":"WEB WORKS INTERNATIONAL LIMITED"}],"company_since":"2000-05-10","company_dissolved":"2003-01-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715627","names":[{"lang":"en","v":"WELL FOREST LIMITED"},{"lang":"hk","v":"譽林有限公司"}],"company_since":"2000-05-10","company_dissolved":"2016-09-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715931","names":[{"lang":"en","v":"TSSI (HONG KONG) LIMITED"},{"lang":"hk","v":"鐵時(香港)有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715953","names":[{"lang":"en","v":"WORLDTRADE CONCEPT LIMITED"},{"lang":"hk","v":"世貿概念有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715715","names":[{"lang":"en","v":"XIONG GANG ENGINEERING LIMITED"},{"lang":"hk","v":"雄罡工程有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715866","names":[{"lang":"en","v":"YOUNEED ELECTRONICS (H.K.) LIMITED"},{"lang":"hk","v":"裕李電子香港有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"715737","names":[{"lang":"en","v":"WEST POINT TECHNOLOGY LIMITED"},{"lang":"hk","v":"滙邦科技有限公司"}],"company_since":"2000-05-10","company_dissolved":"2003-12-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715973","names":[{"lang":"en","v":"WESTMART LIMITED"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715692","names":[{"lang":"en","v":"WICTLE OFFSET PRINTING FACTORY LIMITED"},{"lang":"hk","v":"永豐印刷有限公司"}],"company_since":"2000-05-10","company_dissolved":"2002-06-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"715947","names":[{"lang":"en","v":"ZHEN DA INDUSTRIAL LIMITED"},{"lang":"hk","v":"正大實業有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"715883","names":[{"lang":"en","v":"WING SHUN PRINTING LIMITED"},{"lang":"hk","v":"永順印花有限公司"}],"company_since":"2000-05-10","company_dissolved":"2004-06-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715784","names":[{"lang":"en","v":"YU HOI KEE COMPANY LIMITED"},{"lang":"hk","v":"余海記有限公司"}],"company_since":"2000-05-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715954","names":[{"lang":"en","v":"WORLDLINK INVESTMENT LIMITED"},{"lang":"hk","v":"世聯投資有限公司"}],"company_since":"2000-05-10","company_dissolved":"2003-07-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"716001","names":[{"lang":"en","v":"WORLDMATE (FAR EAST) LIMITED"},{"lang":"hk","v":"滙懋(遠東)有限公司"}],"company_since":"2000-05-10","company_dissolved":"2006-08-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715955","names":[{"lang":"en","v":"WORLDTRADE LINKAGE LIMITED"},{"lang":"hk","v":"日新遠東電訊有限公司"}],"company_since":"2000-05-10","company_dissolved":"2011-05-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"715913","names":[{"lang":"en","v":"YIN XIN COMMUNICATION LIMITED"},{"lang":"hk","v":"銀信通訊有限公司"}],"company_since":"2000-05-10","company_dissolved":"2008-10-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"715976","names":[{"lang":"en","v":"YOU KYOUNG ELECTRONICS CO., LIMITED"},{"lang":"hk","v":"柳輕電子有限公司"}],"company_since":"2000-05-10","company_dissolved":"2005-08-19","company_type_txt":"Private, ltd by shares"},
undefined,
