{"tax_id":"714677","names":[{"lang":"en","v":"CHARTER CAPITAL INTERNATIONAL LIMITED (d2006-09-15)"},{"lang":"hk","v":"志嘉國際有限公司"}],"company_since":"2000-05-03","company_dissolved":"2006-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714534","names":[{"lang":"en","v":"CHARTER CHAIN ENTERPRISES LIMITED"},{"lang":"hk","v":"卓鏗企業有限公司"}],"company_since":"2000-05-03","company_dissolved":"2017-03-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714663","names":[{"lang":"en","v":"CHEEZ GIRL ONLINE LIMITED"}],"company_since":"2000-05-03","company_dissolved":"2002-12-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714499","names":[{"lang":"en","v":"CHI HING DECORATION LIMITED"},{"lang":"hk","v":"志興裝修工程有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714768","names":[{"lang":"en","v":"CHINA (HONG KONG) HUI XIN INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"中國(香港)匯鑫國際投資有限公司"}],"company_since":"2000-05-03","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714586","names":[{"lang":"en","v":"CHINA BRIDGE INVESTMENTS LIMITED"}],"company_since":"2000-05-03","company_dissolved":"2002-11-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714626","names":[{"lang":"en","v":"CHINA CHEMPHARM HONG KONG LIMITED"},{"lang":"hk","v":"康大實業香港有限公司"}],"company_since":"2000-05-03","company_dissolved":"2001-11-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714788","names":[{"lang":"en","v":"CHINA DIGITAL MOVIE CITY COMPANY LIMITED"},{"lang":"hk","v":"中國數碼影城有限公司"}],"company_since":"2000-05-03","company_dissolved":"2013-08-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714556","names":[{"lang":"en","v":"CHINA NEXT GENERATION GROUPS LIMITED"},{"lang":"hk","v":"中國雛鷹集團有限公司"}],"company_since":"2000-05-03","company_dissolved":"2006-01-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714763","names":[{"lang":"en","v":"CHINAGLORY WHARF TRANSPORTATION COMPANY LIMITED"},{"lang":"hk","v":"中榮碼頭運輸有限公司"}],"company_since":"2000-05-03","company_dissolved":"2015-12-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714679","names":[{"lang":"en","v":"CONCEPT2BIZ.COM LIMITED"},{"lang":"hk","v":"新經濟動力有限公司"}],"company_since":"2000-05-03","company_dissolved":"2002-02-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714727","names":[{"lang":"en","v":"CUSTOMI.COM LIMITED"}],"company_since":"2000-05-03","company_dissolved":"2004-10-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714750","names":[{"lang":"en","v":"CYBER LEADER INTERNATIONAL (NOMINEE) LIMITED"},{"lang":"hk","v":"億科國際(代理人)有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714689","names":[{"lang":"en","v":"CYBER SUCCESS INTERNATIONAL LIMITED"},{"lang":"hk","v":"科成國際有限公司"}],"company_since":"2000-05-03","company_dissolved":"2014-02-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714696","names":[{"lang":"en","v":"CYBER WISE LIMITED (d2002-09-13)"},{"lang":"hk","v":"科鉅有限公司"}],"company_since":"2000-05-03","company_dissolved":"2002-09-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714615","names":[{"lang":"en","v":"CYBER YIELD TECHNOLOGY LIMITED"},{"lang":"hk","v":"盈溢科技有限公司"}],"company_since":"2000-05-03","company_dissolved":"2002-08-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714516","names":[{"lang":"en","v":"CYBRIC LIMITED"}],"company_since":"2000-05-03","company_dissolved":"2005-11-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714501","names":[{"lang":"en","v":"D &amp; D LIMITED (d2005-05-06)"}],"company_since":"2000-05-03","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714710","names":[{"lang":"en","v":"DIGITEX GARMENT ACCESSORIES NET LIMITED"},{"lang":"hk","v":"新紡制衣配料網有限公司"}],"company_since":"2000-05-03","company_dissolved":"2016-03-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714616","names":[{"lang":"en","v":"DONJON DEVELOPMENT LIMITED"},{"lang":"hk","v":"主力集團有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714758","names":[{"lang":"en","v":"DOTSWORK LIMITED"}],"company_since":"2000-05-03","company_dissolved":"2008-07-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714602","names":[{"lang":"en","v":"E-AMAH INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"現代瑪姐集團有限公司"}],"company_since":"2000-05-03","company_dissolved":"2010-12-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714612","names":[{"lang":"en","v":"EASY GROWN LIMITED"},{"lang":"hk","v":"怡利豐有限公司"}],"company_since":"2000-05-03","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714731","names":[{"lang":"en","v":"EBROKER SYSTEMS LIMITED"},{"lang":"hk","v":"電子交易系統有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714743","names":[{"lang":"en","v":"EDNOLAND (HK) LIMITED"},{"lang":"hk","v":"教育小天地有限公司"}],"company_since":"2000-05-03","company_dissolved":"2010-10-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714595","names":[{"lang":"en","v":"ETERNAL SUPREME INTERNATIONAL LIMITED"},{"lang":"hk","v":"永尊國際有限公司"}],"company_since":"2000-05-03","company_dissolved":"2016-01-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714505","names":[{"lang":"en","v":"EXATECH TECHNOLOGY COMPANY LIMITED"},{"lang":"hk","v":"昶益富有限公司"}],"company_since":"2000-05-03","company_dissolved":"2002-08-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714745","names":[{"lang":"en","v":"EXCEL TEAM HOLDINGS LIMITED (d2002-09-27)"},{"lang":"hk","v":"卓暉集團有限公司"}],"company_since":"2000-05-03","company_dissolved":"2002-09-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714523","names":[{"lang":"en","v":"CYBERBASE ISYSTEMS LIMITED"},{"lang":"hk","v":"互聯世界科技有限公司"}],"company_since":"2000-05-03","company_dissolved":"2010-05-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714660","names":[{"lang":"en","v":"EXPRESS WEEKLY ONLINE LIMITED"},{"lang":"hk","v":"快周刊在線有限公司"}],"company_since":"2000-05-03","company_dissolved":"2002-12-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714722","names":[{"lang":"en","v":"FAR EAST DEVELOPMENT LIMITED"},{"lang":"hk","v":"遠東創富有限公司"}],"company_since":"2000-05-03","company_dissolved":"2002-02-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714693","names":[{"lang":"en","v":"EXCEL LEADER (HONG KONG) LIMITED"},{"lang":"hk","v":"卓暉(香港)有限公司"}],"company_since":"2000-05-03","company_dissolved":"2002-10-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714503","names":[{"lang":"en","v":"FEDERAL FUND HOLDINGS LIMITED"},{"lang":"hk","v":"聯邦基金控股有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714518","names":[{"lang":"en","v":"EASTERN GATE CAPITAL LIMITED"},{"lang":"hk","v":"東直門融資有限公司"}],"company_since":"2000-05-03","company_dissolved":"2013-04-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714683","names":[{"lang":"en","v":"FOCUS ONE MEDIA HONG KONG LIMITED"}],"company_since":"2000-05-03","company_dissolved":"2006-01-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714759","names":[{"lang":"en","v":"FRANCE VIOLET HONG KONG INTERNATIONAL CO., LIMITED"},{"lang":"hk","v":"法國聖羅蘭香港國際有限公司"}],"company_since":"2000-05-03","company_dissolved":"2006-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714782","names":[{"lang":"en","v":"FULL SPEED TRANS &amp; EXPRESS LIMITED"},{"lang":"hk","v":"全通運輸速遞有限公司"}],"company_since":"2000-05-03","company_dissolved":"2006-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714673","names":[{"lang":"en","v":"GERMANY OUTLONG GROUP (ASIA) LIMITED"},{"lang":"hk","v":"德國奧特龍集團(亞洲)有限公司"}],"company_since":"2000-05-03","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714526","names":[{"lang":"en","v":"GLOBAL UNITED LOGISTIC OCEAN (HK) LIMITED"},{"lang":"hk","v":"環球聯運物流船務香港有限公司"}],"company_since":"2000-05-03","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714486","names":[{"lang":"en","v":"GLOCAL HONG KONG LIMITED"},{"lang":"hk","v":"環球(香港)研究開發有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714671","names":[{"lang":"en","v":"GO-MOBILEDATA LIMITED"},{"lang":"hk","v":"中滙動力有限公司"}],"company_since":"2000-05-03","company_dissolved":"2003-11-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714653","names":[{"lang":"en","v":"EZBUDDY.COM (ASIA) PRIVATE LIMITED"}],"company_since":"2000-05-03","company_dissolved":"2006-01-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714794","names":[{"lang":"en","v":"EZMOOD.COM LIMITED"},{"lang":"hk","v":"意釋貿有限公司"}],"company_since":"2000-05-03","company_dissolved":"2004-07-23","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714690","names":[{"lang":"en","v":"GOLDEN VICTORY INVESTMENT LIMITED (d2006-09-15)"},{"lang":"hk","v":"金裕豐投資有限公司"}],"company_since":"2000-05-03","company_dissolved":"2006-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714682","names":[{"lang":"en","v":"GOODWILL (H.K.) ELECTRONIC LIMITED"},{"lang":"hk","v":"香港吉電行電子有限公司"}],"company_since":"2000-05-03","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714582","names":[{"lang":"en","v":"FASHION GEAR LIMITED"},{"lang":"hk","v":"浩田時裝有限公司"}],"company_since":"2000-05-03","company_dissolved":"2008-07-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714780","names":[{"lang":"en","v":"FILKUEN FINANCE LIMITED"},{"lang":"hk","v":"照權財務有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714527","names":[{"lang":"en","v":"GOTHAM CITY MANAGEMENT LIMITED"},{"lang":"hk","v":"高合城管理有限公司"}],"company_since":"2000-05-03","company_dissolved":"2020-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714581","names":[{"lang":"en","v":"GUANGZHOU ALUMINIUM FLURO-CARBON COATED LIMITED"},{"lang":"hk","v":"廣鋁噴塗專業有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714500","names":[{"lang":"en","v":"FORCEPART ENGINEERING LIMITED"},{"lang":"hk","v":"科栢工程有限公司"}],"company_since":"2000-05-03","company_dissolved":"2005-02-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714568","names":[{"lang":"en","v":"FRANCE SPRINGLAND COSMETICS (HK) LIMITED"},{"lang":"hk","v":"法國春浪化妝品(香港)有限公司"}],"company_since":"2000-05-03","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714643","names":[{"lang":"en","v":"H.K. HUAXIA NATION LOCAL CONDITIONS &amp; CUSTOMS MAGAZINE LIMITED"},{"lang":"hk","v":"香港華夏民族風情刊雜誌有限公司"}],"company_since":"2000-05-03","company_dissolved":"2006-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714700","names":[{"lang":"en","v":"FRANCE TOPAZ HONG KONG INTERNATIONAL CO., LIMITED"},{"lang":"hk","v":"法國都彭香港國際有限公司"}],"company_since":"2000-05-03","company_dissolved":"2004-12-31","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714644","names":[{"lang":"en","v":"H.K. WEIDRGON INDUSTRY INT'L GROUP LIMITED"},{"lang":"hk","v":"香港威龍實業國際集團有限公司"}],"company_since":"2000-05-03","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714756","names":[{"lang":"en","v":"HI-Q FACILITIES CARE LIMITED"},{"lang":"hk","v":"雅喬設備維新有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714562","names":[{"lang":"en","v":"HK CARDINBO (INT'L) GROUP LIMITED"},{"lang":"hk","v":"香港卡登堡(國際)集團有限公司"}],"company_since":"2000-05-03","company_dissolved":"2017-12-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714767","names":[{"lang":"en","v":"FUNG TAT ELECTRICAL ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"豐達機電工程有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714726","names":[{"lang":"en","v":"GENERAL MARINE SHIPPING ENTERPRISES CO., LIMITED"},{"lang":"hk","v":"通運船務企業有限公司"}],"company_since":"2000-05-03","company_dissolved":"2014-09-05","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714578","names":[{"lang":"en","v":"HK HANSEN (INT'L) GROUP DRESS LIMITED"},{"lang":"hk","v":"香港漢森(國際)集團服飾有限公司"}],"company_since":"2000-05-03","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714566","names":[{"lang":"en","v":"HK JOYS COSMETICS INT'L LIMITED"},{"lang":"hk","v":"香港潔麗詩化妝品國際有限公司"}],"company_since":"2000-05-03","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714585","names":[{"lang":"en","v":"GLOBAL MIGRATION CONSULTANTS LIMITED"},{"lang":"hk","v":"穗文移民顧問有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714715","names":[{"lang":"en","v":"HK SHAKESPEARE INT'L DEV. LIMITED"},{"lang":"hk","v":"香港莎士比亞國際發展有限公司"}],"company_since":"2000-05-03","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714549","names":[{"lang":"en","v":"GOLDEN CASTLE TRANSPORTATION COMPANY LIMITED"},{"lang":"hk","v":"金堡貨運有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714681","names":[{"lang":"en","v":"GOLDCOP INT'L GROUP INVESTMENT LIMITED"},{"lang":"hk","v":"金業國際集團投資有限公司"}],"company_since":"2000-05-03","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714507","names":[{"lang":"en","v":"GOLDEN SUN INDUSTRIAL LIMITED"},{"lang":"hk","v":"金日實業有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714646","names":[{"lang":"en","v":"HONG KONG HONG KAI ELECTRON INDUSTRIAL LIMITED"},{"lang":"hk","v":"香港虹凱電子實業有限公司"}],"company_since":"2000-05-03","company_dissolved":"2006-01-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714637","names":[{"lang":"en","v":"HONG KONG SANXIN LIMITED"},{"lang":"hk","v":"香港三信貿易有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714746","names":[{"lang":"en","v":"GOMAX INTERNATIONAL LIMITED"},{"lang":"hk","v":"金豐裕國際有限公司"}],"company_since":"2000-05-03","company_dissolved":"2001-10-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714686","names":[{"lang":"en","v":"GRAND LINK INTERNATIONAL LIMITED"}],"company_since":"2000-05-03","company_dissolved":"2008-09-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714645","names":[{"lang":"en","v":"HONG KONG YOMEBO INTERNATIONAL INDUSTRY LIMITED"},{"lang":"hk","v":"香港伊美堂國際實業有限公司"}],"company_since":"2000-05-03","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714502","names":[{"lang":"en","v":"HONG KONG WORLD PREDICTABLE ASSOCIATION LIMITED"},{"lang":"hk","v":"香港世界預測家協會有限公司"}],"company_since":"2000-05-03","company_dissolved":"2012-07-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714488","names":[{"lang":"en","v":"GOLD FOREX HOLDINGS LIMITED"},{"lang":"hk","v":"金威盈集團有限公司"}],"company_since":"2000-05-03","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714778","names":[{"lang":"en","v":"HONLOCKS PHARMACEUTICAL COMPANY LIMITED"},{"lang":"hk","v":"香港康樂氏製藥有限公司"}],"company_since":"2000-05-03","company_dissolved":"2008-10-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714764","names":[{"lang":"en","v":"HUANG'S MEDICINE (H.K.) LIMITED"},{"lang":"hk","v":"黃家醫圈(香港)藥業有限公司"}],"company_since":"2000-05-03","company_dissolved":"2002-01-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714669","names":[{"lang":"en","v":"ICALL CHINA HOLDINGS CO. LIMITED"}],"company_since":"2000-05-03","company_dissolved":"2016-09-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"714753","names":[{"lang":"en","v":"ICING INTERNATIONAL LIMITED"}],"company_since":"2000-05-03","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714650","names":[{"lang":"en","v":"ICOMMERCE.COM.HK LIMITED"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714793","names":[{"lang":"en","v":"IEMARKET.NET LIMITED"},{"lang":"hk","v":"釋貿商聯科技有限公司"}],"company_since":"2000-05-03","company_dissolved":"2005-09-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714776","names":[{"lang":"en","v":"HK RICHBOSS FURNITURE INT'L GROUP LIMITED"},{"lang":"hk","v":"香港裕寶家俬國際集團有限公司"}],"company_since":"2000-05-03","company_dissolved":"2006-09-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714706","names":[{"lang":"en","v":"INKEL INTERNATIONAL GROUP LIMITED"},{"lang":"hk","v":"英傑國際集團有限公司"}],"company_since":"2000-05-03","company_dissolved":"2009-07-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714792","names":[{"lang":"en","v":"INNOAGE HONG KONG LIMITED"}],"company_since":"2000-05-03","company_dissolved":"2008-09-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714720","names":[{"lang":"en","v":"INTERNATIONAL (HONG KONG) SHEN DA MEDICAL TREATMENT &amp; ELECTRON LIMITED"},{"lang":"hk","v":"國際(香港)信達醫療電子有限公司"}],"company_since":"2000-05-03","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714607","names":[{"lang":"en","v":"INTERNATIONAL BUILDING TECHNOLOGIES LIMITED"},{"lang":"hk","v":"國際建築科技有限公司"}],"company_since":"2000-05-03","company_dissolved":"2005-03-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714605","names":[{"lang":"en","v":"JACKSON DENTAL SUPPLIES LIMITED (d2009-09-25)"},{"lang":"hk","v":"正新牙科器材有限公司"}],"company_since":"2000-05-03","company_dissolved":"2009-09-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714530","names":[{"lang":"en","v":"JC. WATSON TECHNOLOGY COMPANY LIMITED"},{"lang":"hk","v":"寶隆科技有限公司"}],"company_since":"2000-05-03","company_dissolved":"2017-03-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714661","names":[{"lang":"en","v":"JESSICA ONLINE LIMITED"}],"company_since":"2000-05-03","company_dissolved":"2002-05-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714610","names":[{"lang":"en","v":"JIA INTERNATIONAL LIMITED"},{"lang":"hk","v":"智家有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714497","names":[{"lang":"en","v":"HUNG CHEONG PLASTIC LIMITED"},{"lang":"hk","v":"雄昌膠皮有限公司"}],"company_since":"2000-05-03","company_dissolved":"2006-09-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714784","names":[{"lang":"en","v":"JWE COMPANY LIMITED"},{"lang":"hk","v":"崇維企業有限公司"}],"company_since":"2000-05-03","company_dissolved":"2019-10-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714786","names":[{"lang":"en","v":"KAI TAI JEWELLERY POLISHING LIMITED"},{"lang":"hk","v":"啓泰電金有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714664","names":[{"lang":"en","v":"KICK ONLINE LIMITED"}],"company_since":"2000-05-03","company_dissolved":"2003-03-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"714771","names":[{"lang":"en","v":"HONG KONG YUCHAI INTERNATIONAL LIMITED"},{"lang":"hk","v":"香港玉柴國際有限公司"}],"company_since":"2000-05-03","company_dissolved":"2002-03-01","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714773","names":[{"lang":"en","v":"KINGTOP INTERNATIONAL GROUP LIMITED"},{"lang":"hk","v":"尖峰國際集團有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714546","names":[{"lang":"en","v":"KO FAI TRANSPORTATION COMPANY LIMITED"},{"lang":"hk","v":"高輝運輸有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714732","names":[{"lang":"en","v":"KOSMETIK LIMITED"},{"lang":"hk","v":"肌麗延有限公司"}],"company_since":"2000-05-03","company_dissolved":"2016-04-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714718","names":[{"lang":"en","v":"KWONG KEUNG TRANSPORTATION TRADING COMPANY LIMITED"},{"lang":"hk","v":"廣強運輸貿易有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714529","names":[{"lang":"en","v":"INNOVIN LIMITED"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714508","names":[{"lang":"en","v":"LAMINAR INDUSTRY LIMITED"}],"company_since":"2000-05-03","company_dissolved":"2001-05-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714550","names":[{"lang":"en","v":"IPEOPLE CONSULTANTS LIMITED"},{"lang":"hk","v":"科賢顧問有限公司"}],"company_since":"2000-05-03","company_dissolved":"2005-10-07","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714640","names":[{"lang":"en","v":"LANQI INTERNATIONAL (H.K.) LIMITED"},{"lang":"hk","v":"蘭琦國際(香港)有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714698","names":[{"lang":"en","v":"LAP CHUEN SCAFFOLDING LIMITED"},{"lang":"hk","v":"立存棚業有限公司"}],"company_since":"2000-05-03","company_dissolved":"2005-09-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714725","names":[{"lang":"en","v":"LEAPONT METAL MATERIALS COMPANY LIMITED"},{"lang":"hk","v":"聯邦五金材料有限公司"}],"company_since":"2000-05-03","company_dissolved":"2009-03-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714504","names":[{"lang":"en","v":"LEGEND CENTRE LIMITED"},{"lang":"hk","v":"傳奇世界有限公司"}],"company_since":"2000-05-03","company_dissolved":"2006-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714517","names":[{"lang":"en","v":"LEGEND LAND LIMITED (d2005-11-18)"},{"lang":"hk","v":"晉立有限公司"}],"company_since":"2000-05-03","company_dissolved":"2005-11-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714552","names":[{"lang":"en","v":"LEVIN DEVELOPMENTS LIMITED"},{"lang":"hk","v":"力鋒發展有限公司"}],"company_since":"2000-05-03","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714667","names":[{"lang":"en","v":"LISA ONLINE LIMITED"},{"lang":"hk","v":"味道在線有限公司"}],"company_since":"2000-05-03","company_dissolved":"2002-05-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714571","names":[{"lang":"en","v":"JET UNION (HONG KONG) LIMITED"},{"lang":"hk","v":"展潤(香港)有限公司"}],"company_since":"2000-05-03","company_dissolved":"2002-06-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714580","names":[{"lang":"en","v":"LITTAUER TECHNOLOGIES (HONG KONG) LIMITED"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714621","names":[{"lang":"en","v":"LUCKY DEER INDUSTRIAL CO., LIMITED"},{"lang":"hk","v":"瑞陸實業有限公司"}],"company_since":"2000-05-03","company_dissolved":"2012-07-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714596","names":[{"lang":"en","v":"LUCKY TRANSPORTATION COMPANY LIMITED"},{"lang":"hk","v":"佳運運輸有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"714521","names":[{"lang":"en","v":"KAI YIP (HONG KONG) INDUSTRIAL COMPANY LIMITED"},{"lang":"hk","v":"佳業(香港)實業有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714712","names":[{"lang":"en","v":"KEHONG INDUSTRY &amp; COMMERCE LIMITED"},{"lang":"hk","v":"香港科宏實業有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714617","names":[{"lang":"en","v":"MACRO TRADING INTERNATIONAL LIMITED"},{"lang":"hk","v":"宏力國際貿易有限公司"}],"company_since":"2000-05-03","company_dissolved":"2002-07-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714737","names":[{"lang":"en","v":"KENTER SHIPPING COMPANY LIMITED"},{"lang":"hk","v":"廣達船務(香港)有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714662","names":[{"lang":"en","v":"MARIEHK ONLINE LIMITED"}],"company_since":"2000-05-03","company_dissolved":"2002-12-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714734","names":[{"lang":"en","v":"L. C. BRIDGEWISE COMPANY LIMITED"},{"lang":"hk","v":"橋浩有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714761","names":[{"lang":"en","v":"MING LEE SHIP YARD LIMITED"},{"lang":"hk","v":"明利船排廠有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714634","names":[{"lang":"en","v":"MOBIUS INTERNATIONAL LIMITED (d2012-09-07)"},{"lang":"hk","v":"翔和國際有限公司"}],"company_since":"2000-05-03","company_dissolved":"2012-09-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714576","names":[{"lang":"en","v":"N &amp; N INTERNATIONAL LIMITED (d2003-09-05)"},{"lang":"hk","v":"泓欣國際有限公司"}],"company_since":"2000-05-03","company_dissolved":"2003-09-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714506","names":[{"lang":"en","v":"NEW PROSPEROUS ASIA DEVELOPMENT LIMITED"},{"lang":"hk","v":"新亞洲鑫源得開發有限公司"}],"company_since":"2000-05-03","company_dissolved":"2004-03-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714728","names":[{"lang":"en","v":"NEW SILVER DEVELOPMENT (HK) LIMITED"},{"lang":"hk","v":"新聲發展(香港)有限公司"}],"company_since":"2000-05-03","company_dissolved":"2001-09-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714708","names":[{"lang":"en","v":"NEWERTECH INTERNATIONAL LIMITED"},{"lang":"hk","v":"利雅達國際有限公司"}],"company_since":"2000-05-03","company_dissolved":"2003-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714766","names":[{"lang":"en","v":"NEXLAND ASIA LIMITED"}],"company_since":"2000-05-03","company_dissolved":"2006-11-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714555","names":[{"lang":"en","v":"NIKKOSHI (HONG KONG) CO. LIMITED"},{"lang":"hk","v":"尼高希(香港)有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714629","names":[{"lang":"en","v":"ONNY LIMITED"},{"lang":"hk","v":"安愉有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714589","names":[{"lang":"en","v":"ORIENTAL CAPITAL ADVISORS LIMITED"},{"lang":"hk","v":"東方企業資產托管經營(香港)有限公司"}],"company_since":"2000-05-03","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714655","names":[{"lang":"en","v":"PCXPRESS ONLINE LIMITED"},{"lang":"hk","v":"電腦快周在線有限公司"}],"company_since":"2000-05-03","company_dissolved":"2002-12-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714625","names":[{"lang":"en","v":"PETRA CAPITAL (HK) LIMITED"}],"company_since":"2000-05-03","company_dissolved":"2002-10-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714574","names":[{"lang":"en","v":"PHOTO CURE CO., LIMITED"},{"lang":"hk","v":"連陸貿易有限公司"}],"company_since":"2000-05-03","company_dissolved":"2009-10-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714740","names":[{"lang":"en","v":"PIEMONTESE INTERNATIONAL GROUP LIMITED"},{"lang":"hk","v":"皮埃蒙特國際集團有限公司"}],"company_since":"2000-05-03","company_dissolved":"2003-05-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714642","names":[{"lang":"en","v":"MIDLAND LEASING MANAGEMENT (VI) LIMITED"},{"lang":"hk","v":"美聯租務管理(六)有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714559","names":[{"lang":"en","v":"PIK WAH SHELL BUTTON FACTORY LIMITED"},{"lang":"hk","v":"碧華貝殼鈕廠有限公司"}],"company_since":"2000-05-03","company_dissolved":"2014-07-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714787","names":[{"lang":"en","v":"POWERFUL ELECTRICAL ENGINEERING COMPANY LIMITED (d2005-06-30)"},{"lang":"hk","v":"力進機電工程有限公司"}],"company_since":"2000-05-03","company_dissolved":"2005-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714747","names":[{"lang":"en","v":"MUI MUSIC ENTERTAINMENT LIMITED"}],"company_since":"2000-05-03","company_dissolved":"2013-03-01","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714514","names":[{"lang":"en","v":"PRINTEC HONG KONG LIMITED"},{"lang":"hk","v":"大松香港有限公司"}],"company_since":"2000-05-03","company_dissolved":"2006-01-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714573","names":[{"lang":"en","v":"NETEZ TECHNOLOGY LIMITED"},{"lang":"hk","v":"易聯網有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714744","names":[{"lang":"en","v":"PROFIT WIN HOLDINGS LIMITED (d2003-06-06)"},{"lang":"hk","v":"富永集團有限公司"}],"company_since":"2000-05-03","company_dissolved":"2003-06-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714524","names":[{"lang":"en","v":"PRO-FIRE LIMITED"},{"lang":"hk","v":"專業防火有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714790","names":[{"lang":"en","v":"PUBLISHINGONLINE.COM (ASIA) LIMITED"},{"lang":"hk","v":"博文網上出版(亞洲)有限公司"}],"company_since":"2000-05-03","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714714","names":[{"lang":"en","v":"NEW ZONE ENTERPRISE LIMITED"},{"lang":"hk","v":"盈訊拓展企業有限公司"}],"company_since":"2000-05-03","company_dissolved":"2011-01-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714511","names":[{"lang":"en","v":"QM TRANSISTOR COMPANY LIMITED"},{"lang":"hk","v":"敏捷半導體有限公司"}],"company_since":"2000-05-03","company_dissolved":"2002-07-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714699","names":[{"lang":"en","v":"RADIONIC HONG KONG LIMITED"}],"company_since":"2000-05-03","company_dissolved":"2014-09-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714704","names":[{"lang":"en","v":"REGAL PACIFIC TRADING LIMITED"},{"lang":"hk","v":"盈高貿易服務有限公司"}],"company_since":"2000-05-03","company_dissolved":"2002-05-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714796","names":[{"lang":"en","v":"RENEX TECHNOLOGY LIMITED"},{"lang":"hk","v":"夏瑞科技股份有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714760","names":[{"lang":"en","v":"RES LIMITED"},{"lang":"hk","v":"環卓有限公司"}],"company_since":"2000-05-03","company_dissolved":"2009-09-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714670","names":[{"lang":"en","v":"NINE-EIGHT ORIGIN NET LABORATORY LIMITED"},{"lang":"hk","v":"萊茵特原創網絡實驗室有限公司"}],"company_since":"2000-05-03","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714560","names":[{"lang":"en","v":"RIVER TRADING COMPANY LIMITED"},{"lang":"hk","v":"麗華貿易有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714775","names":[{"lang":"en","v":"RONSON INDUSTRIAL COMPANY LIMITED"},{"lang":"hk","v":"昇龍實業有限公司"}],"company_since":"2000-05-03","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714519","names":[{"lang":"en","v":"NEWJOY INDUSTRIAL LIMITED"},{"lang":"hk","v":"新樂實業有限公司"}],"company_since":"2000-05-03","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714588","names":[{"lang":"en","v":"P &amp; L MANAGEMENT LIMITED"},{"lang":"hk","v":"百樂管理有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714601","names":[{"lang":"en","v":"S. A. R. SYSTEM AND ENGINEERING LIMITED"},{"lang":"hk","v":"旭霆專業工程有限公司"}],"company_since":"2000-05-03","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714631","names":[{"lang":"en","v":"SANTOS HK LIMITED"},{"lang":"hk","v":"宏浚香港有限公司"}],"company_since":"2000-05-03","company_dissolved":"2009-12-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714541","names":[{"lang":"en","v":"SANWA ENGINEERING LIMITED"},{"lang":"hk","v":"三和電訊工程有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714739","names":[{"lang":"en","v":"PEARL RIVER DELTA LOGISTICS DEVELOPMENT LIMITED"},{"lang":"hk","v":"珠江三角洲物流發展有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714711","names":[{"lang":"en","v":"SCK (CHINA) LIMITED"}],"company_since":"2000-05-03","company_dissolved":"2001-10-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714755","names":[{"lang":"en","v":"SHING FAI MOTORS COMPANY LIMITED"},{"lang":"hk","v":"盛輝汽車有限公司"}],"company_since":"2000-05-03","company_dissolved":"2004-06-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714633","names":[{"lang":"en","v":"SHUN TAK TECHNOLOGY VENTURES HOLDINGS LIMITED"},{"lang":"hk","v":"信德科技投資有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714597","names":[{"lang":"en","v":"SILVER TARGET PROPERTIES LIMITED"},{"lang":"hk","v":"兆達置業有限公司"}],"company_since":"2000-05-03","company_dissolved":"2004-09-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714622","names":[{"lang":"en","v":"PM INTERNATIONAL LIMITED (d2011-04-11)"},{"lang":"hk","v":"浩宇國際實業有限公司"}],"company_since":"2000-05-03","company_dissolved":"2011-04-11","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714628","names":[{"lang":"en","v":"SINOWIN BAGS FACTORY LIMITED"},{"lang":"hk","v":"星威手袋廠有限公司"}],"company_since":"2000-05-03","company_dissolved":"2006-09-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714692","names":[{"lang":"en","v":"SKY LINK INVESTMENT LIMITED"},{"lang":"hk","v":"廣天投資有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714694","names":[{"lang":"en","v":"SKY PACIFIC (HONG KONG) LIMITED (d2001-11-23)"},{"lang":"hk","v":"盛天(香港)有限公司"}],"company_since":"2000-05-03","company_dissolved":"2001-11-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714749","names":[{"lang":"en","v":"SMART BASE ENTERPRISES LIMITED (d2007-09-14)"},{"lang":"hk","v":"英耀企業有限公司"}],"company_since":"2000-05-03","company_dissolved":"2007-09-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714494","names":[{"lang":"en","v":"QM AUTOMOBILE COMPANY LIMITED"},{"lang":"hk","v":"敏捷電動車有限公司"}],"company_since":"2000-05-03","company_dissolved":"2002-03-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714577","names":[{"lang":"en","v":"SMART KIDS NETWORK LIMITED"},{"lang":"hk","v":"卓智網絡有限公司"}],"company_since":"2000-05-03","company_dissolved":"2003-10-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714684","names":[{"lang":"en","v":"SMART VICTORY HOLDINGS LIMITED"},{"lang":"hk","v":"進豪集團有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714797","names":[{"lang":"en","v":"SOILMEC (H.K.) LIMITED"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"714774","names":[{"lang":"en","v":"SPORT SOURCES (HK) INT'L NETWORK LIMITED"},{"lang":"hk","v":"體育資源(香港)國際網絡有限公司"}],"company_since":"2000-05-03","company_dissolved":"2006-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714632","names":[{"lang":"en","v":"STANDARD CONCORD INVESTMENT LIMITED"},{"lang":"hk","v":"達和投資有限公司"}],"company_since":"2000-05-03","company_dissolved":"2002-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714680","names":[{"lang":"en","v":"STAR TARGET (HONG KONG) LIMITED"},{"lang":"hk","v":"星達(香港)有限公司"}],"company_since":"2000-05-03","company_dissolved":"2001-09-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714652","names":[{"lang":"en","v":"STARTOWN HK LIMITED"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714736","names":[{"lang":"en","v":"SIM FAR EAST LIMITED"}],"company_since":"2000-05-03","company_dissolved":"2011-01-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714513","names":[{"lang":"en","v":"SUM KEE WATER-PIPE DRAINAGE LIMITED"},{"lang":"hk","v":"森記水喉渠務有限公司"}],"company_since":"2000-05-03","company_dissolved":"2012-07-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714751","names":[{"lang":"en","v":"SUN WAH MEDIA HOLDINGS LIMITED"},{"lang":"hk","v":"新華傳媒集團有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714487","names":[{"lang":"en","v":"SUNNYVISION LIMITED"},{"lang":"hk","v":"新力訊有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714522","names":[{"lang":"en","v":"TA SHING PAPER PRODUCTS &amp; PRINTING LIMITED"},{"lang":"hk","v":"達成紙品印刷有限公司"}],"company_since":"2000-05-03","company_dissolved":"2014-09-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714490","names":[{"lang":"en","v":"TECHJET INDUSTRIAL SUPPLIES LIMITED"},{"lang":"hk","v":"德捷工貿有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714688","names":[{"lang":"en","v":"SMART LINK INVESTMENT LIMITED"},{"lang":"hk","v":"志宏投資有限公司"}],"company_since":"2000-05-03","company_dissolved":"2014-06-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714783","names":[{"lang":"en","v":"TECHWIDE TECHNOLOGY LIMITED"},{"lang":"hk","v":"創庫科技有限公司"}],"company_since":"2000-05-03","company_dissolved":"2006-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"714548","names":[{"lang":"en","v":"TENRYU INVESTMENT COMPANY LIMITED"}],"company_since":"2000-05-03","company_dissolved":"2006-01-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714557","names":[{"lang":"en","v":"SPORT-TECH INDUSTRIAL COMPANY LIMITED"},{"lang":"hk","v":"創興運動用品有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714799","names":[{"lang":"en","v":"TRICOR CORPORATE SECRETARY LIMITED"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714600","names":[{"lang":"en","v":"TRUMP POWER (HONG KONG) LIMITED"},{"lang":"hk","v":"正力(香港)有限公司"}],"company_since":"2000-05-03","company_dissolved":"2005-09-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714757","names":[{"lang":"en","v":"TUNG FA INDUSTRIAL (HONG KONG) LIMITED"},{"lang":"hk","v":"同發實業(香港)有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714553","names":[{"lang":"en","v":"STYLE4HOUSE.COM LIMITED"},{"lang":"hk","v":"形世居有限公司"}],"company_since":"2000-05-03","company_dissolved":"2004-06-11","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714609","names":[{"lang":"en","v":"UNI-CYBER INTERNATIONAL LIMITED"},{"lang":"hk","v":"環球數碼國際有限公司"}],"company_since":"2000-05-03","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714742","names":[{"lang":"en","v":"UNIBEAN SYSTEM LIMITED"}],"company_since":"2000-05-03","company_dissolved":"2001-12-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714647","names":[{"lang":"en","v":"UNION FAVOUR (HONG KONG) LIMITED"},{"lang":"hk","v":"和發(香港)有限公司"}],"company_since":"2000-05-03","company_dissolved":"2004-10-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714584","names":[{"lang":"en","v":"UNIVERSAL PATISSERIE MANAGEMENT CONSULTANCY COMPANY LIMITED"},{"lang":"hk","v":"環球飲食烘焙顧問有限公司"}],"company_since":"2000-05-03","company_dissolved":"2011-03-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714730","names":[{"lang":"en","v":"SUPERCATZ PROMOTIONS (HONG KONG) LIMITED"}],"company_since":"2000-05-03","company_dissolved":"2002-04-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714535","names":[{"lang":"en","v":"UP-BUZ INTERNATIONAL HOLDING LIMITED"},{"lang":"hk","v":"建業集團國際控股有限公司"}],"company_since":"2000-05-03","company_dissolved":"2007-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714772","names":[{"lang":"en","v":"SW ASSET MANAGEMENT LIMITED"},{"lang":"hk","v":"新華資產管理有限公司"}],"company_since":"2000-05-03","company_dissolved":"2015-12-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714606","names":[{"lang":"en","v":"SYNCO TECH COMPANY LIMITED"},{"lang":"hk","v":"先高達有限公司"}],"company_since":"2000-05-03","company_dissolved":"2006-06-02","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714777","names":[{"lang":"en","v":"VESCOM HONG KONG LIMITED"},{"lang":"hk","v":"宏歷香港有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714611","names":[{"lang":"en","v":"VINDA INTERNATIONAL LIMITED"},{"lang":"hk","v":"科達國際有限公司"}],"company_since":"2000-05-03","company_dissolved":"2008-10-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714613","names":[{"lang":"en","v":"VISION ON-LINE LIMITED"},{"lang":"hk","v":"裕科互聯有限公司"}],"company_since":"2000-05-03","company_dissolved":"2007-10-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714665","names":[{"lang":"en","v":"THREE WEEKLY ONLINE LIMITED"},{"lang":"hk","v":"三周刊在線有限公司"}],"company_since":"2000-05-03","company_dissolved":"2002-12-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714498","names":[{"lang":"en","v":"WAIS ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"偉斯工程有限公司"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714599","names":[{"lang":"en","v":"WATER LOTUS CHINAWARE MADING LIMITED"},{"lang":"hk","v":"出水蓮陶瓷製作有限公司"}],"company_since":"2000-05-03","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714592","names":[{"lang":"en","v":"TIANJIAN INTERNATIONAL LIMITED (d2008-10-17)"},{"lang":"hk","v":"天鍵國際有限公司"}],"company_since":"2000-05-03","company_dissolved":"2008-10-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714723","names":[{"lang":"en","v":"WEALTH STRONG ENTERPRISES LIMITED"},{"lang":"hk","v":"創成業有限公司"}],"company_since":"2000-05-03","company_dissolved":"2002-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714721","names":[{"lang":"en","v":"TRADEPOWER ENTERPRISES LIMITED"},{"lang":"hk","v":"盈泰企業有限公司"}],"company_since":"2000-05-03","company_dissolved":"2003-03-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714658","names":[{"lang":"en","v":"WHIZ-KIDS ONLINE LIMITED"},{"lang":"hk","v":"兒童快報在線有限公司"}],"company_since":"2000-05-03","company_dissolved":"2002-12-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714791","names":[{"lang":"en","v":"WINETSU.COM LIMITED"}],"company_since":"2000-05-03","company_dissolved":"2005-01-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714542","names":[{"lang":"en","v":"WING KEE CONSTRUCTION ENGINEERING LIMITED"},{"lang":"hk","v":"永基建築工程有限公司"}],"company_since":"2000-05-03","company_dissolved":"2002-04-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714701","names":[{"lang":"en","v":"TTK CORPORATION LIMITED"},{"lang":"hk","v":"盈滙亞洲有限公司"}],"company_since":"2000-05-03","company_dissolved":"2006-09-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714528","names":[{"lang":"en","v":"WIRE INTERNATIONAL INFORMATION TECHNOLOGY CORPORATION LIMITED"},{"lang":"hk","v":"緯亞國際資訊科技有限公司"}],"company_since":"2000-05-03","company_dissolved":"2006-01-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714604","names":[{"lang":"en","v":"WORLDNET INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"和昇國際發展有限公司"}],"company_since":"2000-05-03","company_dissolved":"2004-07-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714639","names":[{"lang":"en","v":"U.S.A. WAIER HOLDINGS LIMITED"},{"lang":"hk","v":"美國威爾集團有限公司"}],"company_since":"2000-05-03","company_dissolved":"2015-12-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714603","names":[{"lang":"en","v":"XMATRIX LIMITED (d2001-10-12)"},{"lang":"hk","v":"雋藝有限公司"}],"company_since":"2000-05-03","company_dissolved":"2001-10-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"714709","names":[{"lang":"en","v":"Y. T. CENTURY INTERNATIONAL LIMITED"},{"lang":"hk","v":"盈天世紀國際有限公司"}],"company_since":"2000-05-03","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714558","names":[{"lang":"en","v":"UNICOMMU ADVERTISING LIMITED"},{"lang":"hk","v":"尊美廣告有限公司"}],"company_since":"2000-05-03","company_dissolved":"2009-06-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"714641","names":[{"lang":"en","v":"YORK ISLAND (CHINA) LIMITED"},{"lang":"hk","v":"沃域(中國)有限公司"}],"company_since":"2000-05-03","company_dissolved":"2006-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"714489","names":[{"lang":"en","v":"ZAMBRA INTERNATIONAL LIMITED"}],"company_since":"2000-05-03","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"714587","names":[{"lang":"en","v":"ZHENG YUAN TANG HERBAL MEDICINE LIMITED"},{"lang":"hk","v":"正元堂醫藥有限公司"}],"company_since":"2000-05-03","company_dissolved":"2008-08-15","company_type_txt":"Private, ltd by shares"},
