undefined,
{"tax_id":"718396","names":[{"lang":"en","v":"CHEERSON INVESTMENT HOLDINGS LIMITED"},{"lang":"hk","v":"智信投資集團有限公司"}],"company_since":"2000-05-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"718386","names":[{"lang":"en","v":"CHINA ART DECORATION FURNITURE LIMITED"},{"lang":"hk","v":"中藝裝修傢具有限公司"}],"company_since":"2000-05-29","company_dissolved":"2014-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718347","names":[{"lang":"en","v":"CHINA HEALTH NET LIMITED"},{"lang":"hk","v":"中國健康網絡有限公司"}],"company_since":"2000-05-29","company_dissolved":"2013-08-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718384","names":[{"lang":"en","v":"CHINA INTERNATIONAL CULTURAL, SPORT &amp; ARTS EXCHANGE ORGANISATION (HK) LIMITED"},{"lang":"hk","v":"中國文體藝術國際交流機構(香港)有限公司"}],"company_since":"2000-05-29","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718357","names":[{"lang":"en","v":"CHINA TRANS LOGISTICS (HONG KONG) LIMITED"},{"lang":"hk","v":"神州物流(香港)有限公司"}],"company_since":"2000-05-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718367","names":[{"lang":"en","v":"CITILINK INVESTMENT LIMITED (d2009-05-04)"}],"company_since":"2000-05-29","company_dissolved":"2009-05-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718345","names":[{"lang":"en","v":"CITY PROPERTY CONSULTANT LIMITED"},{"lang":"hk","v":"全城置業顧問有限公司"}],"company_since":"2000-05-29","company_dissolved":"2002-10-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718333","names":[{"lang":"en","v":"CREDIT REPORT &amp; INFORMATION SYNDICATE LIMITED"}],"company_since":"2000-05-29","company_dissolved":"2002-11-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718306","names":[{"lang":"en","v":"CYBER SOLUTIONS LIMITED (d2005-08-19)"}],"company_since":"2000-05-29","company_dissolved":"2005-08-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718402","names":[{"lang":"en","v":"D2 CONSULTANTS LIMITED (d2007-03-16)"}],"company_since":"2000-05-29","company_dissolved":"2007-03-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718307","names":[{"lang":"en","v":"DOER (HONG KONG) INTERNATIONAL TRADING LIMITED"},{"lang":"hk","v":"道爾(香港)國際貿易有限公司"}],"company_since":"2000-05-29","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718340","names":[{"lang":"en","v":"E WORLD NETWORKS (HONG KONG) LIMITED"},{"lang":"hk","v":"宇盛網絡(香港)有限公司"}],"company_since":"2000-05-29","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718297","names":[{"lang":"en","v":"EASTERN INTERNATIONAL TRAVEL LIMITED"},{"lang":"hk","v":"東儀國際旅遊有限公司"}],"company_since":"2000-05-29","company_dissolved":"2010-02-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718274","names":[{"lang":"en","v":"EAR NOSE &amp; THROAT CENTRE OF HONG KONG LIMITED"},{"lang":"hk","v":"香港耳鼻喉科中心有限公司"}],"company_since":"2000-05-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718381","names":[{"lang":"en","v":"EBZGLOBAL.COM LIMITED"},{"lang":"hk","v":"環球商務有限公司"}],"company_since":"2000-05-29","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718293","names":[{"lang":"en","v":"EHOTEL (HK) LIMITED"}],"company_since":"2000-05-29","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718410","names":[{"lang":"en","v":"ETRANSLATE.COM.HK LIMITED"}],"company_since":"2000-05-29","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718283","names":[{"lang":"en","v":"EVER-R INTERNATIONAL LIMITED"},{"lang":"hk","v":"臻靜國際有限公司"}],"company_since":"2000-05-29","company_dissolved":"2008-11-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718276","names":[{"lang":"en","v":"FAI KEE HANDBAG COMPANY LIMITED"},{"lang":"hk","v":"輝記手袋有限公司"}],"company_since":"2000-05-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718328","names":[{"lang":"en","v":"FESTINA INTERNATIONAL (H.K.) LIMITED"}],"company_since":"2000-05-29","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718291","names":[{"lang":"en","v":"FORTUNE DOOR LIMITED"},{"lang":"hk","v":"富門有限公司"}],"company_since":"2000-05-29","company_dissolved":"2013-08-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718358","names":[{"lang":"en","v":"EVERGREEN INDUSTRIAL INTERNATIONAL LIMITED"},{"lang":"hk","v":"力其國際實業有限公司"}],"company_since":"2000-05-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718321","names":[{"lang":"en","v":"FORTUNE GRADE LIMITED"},{"lang":"hk","v":"富運佳有限公司"}],"company_since":"2000-05-29","company_dissolved":"2011-04-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"718318","names":[{"lang":"en","v":"FULLYGOLD ENTERPRISES LIMITED"},{"lang":"hk","v":"富利高企業有限公司"}],"company_since":"2000-05-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718317","names":[{"lang":"en","v":"DEEMWELL HONG KONG LIMITED"},{"lang":"hk","v":"登威香港有限公司"}],"company_since":"2000-05-29","company_dissolved":"2010-03-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718360","names":[{"lang":"en","v":"G F G (HK) LIMITED"},{"lang":"hk","v":"高科普有限公司"}],"company_since":"2000-05-29","company_dissolved":"2007-11-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718342","names":[{"lang":"en","v":"G-TECH COMPONENTS COMPANY LIMITED"},{"lang":"hk","v":"志德電子有限公司"}],"company_since":"2000-05-29","company_dissolved":"2007-10-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718261","names":[{"lang":"en","v":"GLOBAL CYBER TECHNOLOGIES LIMITED"},{"lang":"hk","v":"寰宇數碼動力有限公司"}],"company_since":"2000-05-29","company_dissolved":"2003-08-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"718380","names":[{"lang":"en","v":"EASTOP INTERNATIONAL (HOLDINGS) LIMITED"},{"lang":"hk","v":"裕通國際(控股)有限公司"}],"company_since":"2000-05-29","company_dissolved":"2002-12-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"718265","names":[{"lang":"en","v":"GLOBAL PROJECTS AND PRODUCTS LIMITED"},{"lang":"hk","v":"高寶德國際有限公司"}],"company_since":"2000-05-29","company_dissolved":"2007-10-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718370","names":[{"lang":"en","v":"GO 2 XPRESS LIMITED"},{"lang":"hk","v":"高速達快遞有限公司"}],"company_since":"2000-05-29","company_dissolved":"2004-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"718270","names":[{"lang":"en","v":"GRACE HOPE TRADING LIMITED"},{"lang":"hk","v":"富恩貿易有限公司"}],"company_since":"2000-05-29","company_dissolved":"2007-10-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718258","names":[{"lang":"en","v":"GRADE POINT DEVELOPMENT LIMITED"},{"lang":"hk","v":"傑邦發展有限公司"}],"company_since":"2000-05-29","company_dissolved":"2008-11-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718256","names":[{"lang":"en","v":"GRANDA (HONG KONG) LIMITED"},{"lang":"hk","v":"建亞(香港)有限公司"}],"company_since":"2000-05-29","company_dissolved":"2004-08-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"718300","names":[{"lang":"en","v":"EURASIA FINANCIAL MERGING LIMITED"},{"lang":"hk","v":"歐亞信貸融資有限公司"}],"company_since":"2000-05-29","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"718284","names":[{"lang":"en","v":"H.K. MARK INTERNATIONAL LIMITED"},{"lang":"hk","v":"港徽國際有限公司"}],"company_since":"2000-05-29","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718352","names":[{"lang":"en","v":"HANG FUNG ENTERPRISES TRADING LIMITED"},{"lang":"hk","v":"恒豐企業貿易有限公司"}],"company_since":"2000-05-29","company_dissolved":"2001-11-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718252","names":[{"lang":"en","v":"HARVEST LINE LIMITED (d2013-02-22)"},{"lang":"hk","v":"隆立有限公司"}],"company_since":"2000-05-29","company_dissolved":"2013-02-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"718400","names":[{"lang":"en","v":"EXPLORER INTERACTIVE ENGLISH CENTER LIMITED"},{"lang":"hk","v":"探索者互動英語教學中心有限公司"}],"company_since":"2000-05-29","company_dissolved":"2012-01-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"718272","names":[{"lang":"en","v":"HENDERSON CPA LIMITED"},{"lang":"hk","v":"達信會計師事務所有限公司"}],"company_since":"2000-05-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718249","names":[{"lang":"en","v":"HO WAN RESTAURANT LIMITED"},{"lang":"hk","v":"好運燒味餐廳有限公司"}],"company_since":"2000-05-29","company_dissolved":"2003-04-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718406","names":[{"lang":"en","v":"EMD LIMITED"}],"company_since":"2000-05-29","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"718247","names":[{"lang":"en","v":"HONG KONG XIRREA (INTERNATIONAL) FASHION GROUP LIMITED"},{"lang":"hk","v":"香港喜萊雅(國際)服飾集團有限公司"}],"company_since":"2000-05-29","company_dissolved":"2004-07-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"718268","names":[{"lang":"en","v":"FILMTECH DESIGN &amp; DECORATION SERVICES LIMITED"}],"company_since":"2000-05-29","company_dissolved":"2007-01-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718351","names":[{"lang":"en","v":"FOOKY FASHION WHOLESALE LIMITED"},{"lang":"hk","v":"富淇時裝批發有限公司"}],"company_since":"2000-05-29","company_dissolved":"2011-12-02","company_type_txt":"Private, ltd by shares"},
{"tax_id":"718378","names":[{"lang":"en","v":"IN STYLE PUBLICATION LIMITED"},{"lang":"hk","v":"時尚文化出版有限公司"}],"company_since":"2000-05-29","company_dissolved":"2008-11-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718350","names":[{"lang":"en","v":"IRICO-TRL INFORMATION ELECTRONICS COMPANY LIMITED"},{"lang":"hk","v":"彩虹皇旗電子資訊有限公司"}],"company_since":"2000-05-29","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"718273","names":[{"lang":"en","v":"JASON MANAGEMENT CONSULTANTS LIMITED"},{"lang":"hk","v":"佳信管理顧問有限公司"}],"company_since":"2000-05-29","company_dissolved":"2020-07-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718287","names":[{"lang":"en","v":"FULLYGRAND TRADING LIMITED"},{"lang":"hk","v":"富利興貿易有限公司"}],"company_since":"2000-05-29","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718338","names":[{"lang":"en","v":"KAM TIN ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"錦鈿工程有限公司"}],"company_since":"2000-05-29","company_dissolved":"2009-02-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718244","names":[{"lang":"en","v":"GERMAN SHEPHERD DOG CLUB OF HONG KONG SAR (MEMBER OF WUSV) LIMITED"},{"lang":"hk","v":"香港特別行政區德國牧羊狗協會有限公司"}],"company_since":"2000-05-29","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
{"tax_id":"718313","names":[{"lang":"en","v":"JOINTCO LIMITED (d2003-10-17)"},{"lang":"hk","v":"俊灝有限公司"}],"company_since":"2000-05-29","company_dissolved":"2003-10-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"718362","names":[{"lang":"en","v":"GOLDTON ELECTRONIC LIMITED (d2005-09-09)"},{"lang":"hk","v":"金通電綫電纜有限公司"}],"company_since":"2000-05-29","company_dissolved":"2005-09-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"718366","names":[{"lang":"en","v":"KO SHUN CHEONG STEEL COIL CENTRE LIMITED"},{"lang":"hk","v":"高順昌鋼板有限公司"}],"company_since":"2000-05-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718375","names":[{"lang":"en","v":"KOMIYA FOODS (CHINA) LIMITED"},{"lang":"hk","v":"小宮食品(中國)株式會社有限公司"}],"company_since":"2000-05-29","company_dissolved":"2014-12-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"718324","names":[{"lang":"en","v":"KONNION LIMITED"},{"lang":"hk","v":"港銓有限公司"}],"company_since":"2000-05-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718279","names":[{"lang":"en","v":"KWAN TAT INTERNATIONAL LIMITED (d2006-10-06)"},{"lang":"hk","v":"坤達國際有限公司"}],"company_since":"2000-05-29","company_dissolved":"2006-10-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718303","names":[{"lang":"en","v":"LEAGUE CASTLE LIMITED (d2005-06-03)"},{"lang":"hk","v":"聯盟堡有限公司"}],"company_since":"2000-05-29","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718281","names":[{"lang":"en","v":"LIJIAAO ENTERPRISES CO., LIMITED"},{"lang":"hk","v":"利嘉奧企業有限公司"}],"company_since":"2000-05-29","company_dissolved":"2008-07-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718385","names":[{"lang":"en","v":"LONE STAR LIGHTING LIMITED"},{"lang":"hk","v":"嘉晟實業有限公司"}],"company_since":"2000-05-29","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718304","names":[{"lang":"en","v":"MATRIX NOVELTIES LIMITED"},{"lang":"hk","v":"明智禮品有限公司"}],"company_since":"2000-05-29","company_dissolved":"2015-06-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"718377","names":[{"lang":"en","v":"MILLION RECREATION DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"億寶康樂發展有限公司"}],"company_since":"2000-05-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718305","names":[{"lang":"en","v":"MILLIBEE LIMITED"}],"company_since":"2000-05-29","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718369","names":[{"lang":"en","v":"MING WONG TEXTILES LIMITED"},{"lang":"hk","v":"明旺布業有限公司"}],"company_since":"2000-05-29","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"718334","names":[{"lang":"en","v":"MULTI-LINKS E &amp; M LIMITED"},{"lang":"hk","v":"萬聯機電有限公司"}],"company_since":"2000-05-29","company_dissolved":"2009-11-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"718397","names":[{"lang":"en","v":"NICEST DECORATION COMPANY LIMITED"},{"lang":"hk","v":"唯美設計裝飾有限公司"}],"company_since":"2000-05-29","company_dissolved":"2011-05-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718271","names":[{"lang":"en","v":"NX TOUCH SYSTEMS LIMITED"},{"lang":"hk","v":"接觸科技股份有限公司"}],"company_since":"2000-05-29","company_dissolved":"2001-05-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"718343","names":[{"lang":"en","v":"ORIENTAL CITY INVESTMENT LIMITED (d2003-02-28)"},{"lang":"hk","v":"東川投資有限公司"}],"company_since":"2000-05-29","company_dissolved":"2003-02-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"718376","names":[{"lang":"en","v":"OSCAR COLLECTIONS (H.K.) LIMITED"},{"lang":"hk","v":"澳斯卡(香港)有限公司"}],"company_since":"2000-05-29","company_dissolved":"2006-10-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"718248","names":[{"lang":"en","v":"KOTA JUTA LIMITED"}],"company_since":"2000-05-29","company_dissolved":"2018-08-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"718255","names":[{"lang":"en","v":"PACIFICNETB2B.COM LIMITED"}],"company_since":"2000-05-29","company_dissolved":"2002-06-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718403","names":[{"lang":"en","v":"PC HOME ONLINE (HK) LIMITED"},{"lang":"hk","v":"網路家庭國際資訊股份有限公司"}],"company_since":"2000-05-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718296","names":[{"lang":"en","v":"PCX CYBERNET LIMITED"}],"company_since":"2000-05-29","company_dissolved":"2003-05-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"718280","names":[{"lang":"en","v":"PERFECT PRINTING SUPPLIES &amp; EQUIPMENT LIMITED"},{"lang":"hk","v":"百美印刷器材有限公司"}],"company_since":"2000-05-29","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718314","names":[{"lang":"en","v":"LOGZERO DESIGN LIMITED"},{"lang":"hk","v":"諾爾設計有限公司"}],"company_since":"2000-05-29","company_dissolved":"2004-10-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718260","names":[{"lang":"en","v":"POSITRON INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"寶幢國際投資有限公司"}],"company_since":"2000-05-29","company_dissolved":"2005-07-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718363","names":[{"lang":"en","v":"MACAUTO INDUSTRIAL (H.K.) COMPANY LIMITED"},{"lang":"hk","v":"駿榮實業(香港)有限公司"}],"company_since":"2000-05-29","company_dissolved":"2004-09-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"718288","names":[{"lang":"en","v":"POWER H.K. TRADING LIMITED"},{"lang":"hk","v":"寶達香港貿易有限公司"}],"company_since":"2000-05-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718285","names":[{"lang":"en","v":"POWERFUL H.K. ENTERPRISES LIMITED"},{"lang":"hk","v":"寶富香港企業有限公司"}],"company_since":"2000-05-29","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"718399","names":[{"lang":"en","v":"METROTRANS EXPRESS LIMITED"},{"lang":"hk","v":"佳駿捷運有限公司"}],"company_since":"2000-05-29","company_dissolved":"2020-09-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"718330","names":[{"lang":"en","v":"LIGHT IN MOTION LIMITED"}],"company_since":"2000-05-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718298","names":[{"lang":"en","v":"PROPS &amp; MERIT I.T. CONSULTANT LIMITED"},{"lang":"hk","v":"栢裕資訊顧問有限公司"}],"company_since":"2000-05-29","company_dissolved":"2002-11-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718259","names":[{"lang":"en","v":"PROSTICKS PUBLICATION LIMITED"},{"lang":"hk","v":"乾坤燭出版有限公司"}],"company_since":"2000-05-29","company_dissolved":"2006-01-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718404","names":[{"lang":"en","v":"QPI LIMITED (HK)"}],"company_since":"2000-05-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"718387","names":[{"lang":"en","v":"MONWAY ELECTRONICS FACTORY LIMITED"},{"lang":"hk","v":"焯鑫電子廠有限公司"}],"company_since":"2000-05-29","company_dissolved":"2001-11-02","company_type_txt":"Private, ltd by shares"},
{"tax_id":"718405","names":[{"lang":"en","v":"R3D2.COM LIMITED"}],"company_since":"2000-05-29","company_dissolved":"2003-07-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"718302","names":[{"lang":"en","v":"Rich Point Investment Holdings Limited"},{"lang":"hk","v":"富滙投資控股有限公司"}],"company_since":"2000-05-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718394","names":[{"lang":"en","v":"RIFLEXPRINT LIMITED"}],"company_since":"2000-05-29","company_dissolved":"2017-10-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"718286","names":[{"lang":"en","v":"RISEFORD ENTERPRISES LIMITED"},{"lang":"hk","v":"登福企業有限公司"}],"company_since":"2000-05-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718361","names":[{"lang":"en","v":"SATOSEN (HONG KONG) LIMITED"},{"lang":"hk","v":"佐道勝(香港)有限公司"}],"company_since":"2000-05-29","company_dissolved":"2007-11-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718250","names":[{"lang":"en","v":"SCITRON LIMITED (d2001-11-02)"},{"lang":"hk","v":"新科朗有限公司"}],"company_since":"2000-05-29","company_dissolved":"2001-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"718301","names":[{"lang":"en","v":"OWAGO (FAR EAST) LIMITED"}],"company_since":"2000-05-29","company_dissolved":"2004-03-05","company_type_txt":"Private, ltd by shares"},
{"tax_id":"718356","names":[{"lang":"en","v":"SIMGLASS (HONG KONG) LIMITED"}],"company_since":"2000-05-29","company_dissolved":"2010-07-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718391","names":[{"lang":"en","v":"STAREASY.COM LIMITED"},{"lang":"hk","v":"星遇模特兒有限公司"}],"company_since":"2000-05-29","company_dissolved":"2008-06-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"718325","names":[{"lang":"en","v":"PAK HOI TECHNOLOGY LIMITED"},{"lang":"hk","v":"百海科技有限公司"}],"company_since":"2000-05-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718349","names":[{"lang":"en","v":"PAKLEE HOLDINGS LIMITED"},{"lang":"hk","v":"百利控股有限公司"}],"company_since":"2000-05-29","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718331","names":[{"lang":"en","v":"PO YEE TONG PHARMACEUTICAL (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"寶義堂藥業(香港)有限公司"}],"company_since":"2000-05-29","company_dissolved":"2018-11-02","company_type_txt":"Private, ltd by shares"},
{"tax_id":"718263","names":[{"lang":"en","v":"SUN SHING FIBRES (H.K.) LIMITED"},{"lang":"hk","v":"新誠紙業(香港)有限公司"}],"company_since":"2000-05-29","company_dissolved":"2001-10-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"718339","names":[{"lang":"en","v":"SUPER-S POLY BAG PRINTING COMPANY LIMITED"},{"lang":"hk","v":"日月星膠袋印刷有限公司"}],"company_since":"2000-05-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"718336","names":[{"lang":"en","v":"PROJECT ADMINISTRATION SERVICES LIMITED (d2004-04-23)"}],"company_since":"2000-05-29","company_dissolved":"2004-04-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718409","names":[{"lang":"en","v":"T6.COMMUNICATIONS LIMITED"},{"lang":"hk","v":"雋陸公關有限公司"}],"company_since":"2000-05-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"718311","names":[{"lang":"en","v":"PRO-INSURANT CONSULTANTS LIMITED"},{"lang":"hk","v":"盈豐保險顧問有限公司"}],"company_since":"2000-05-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"718353","names":[{"lang":"en","v":"TALENT INTERNATIONAL FREIGHT COMPANY LIMITED"},{"lang":"hk","v":"天才國際貨運有限公司"}],"company_since":"2000-05-29","company_dissolved":"2018-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718246","names":[{"lang":"en","v":"TEAM CONCEPT (H.K.) INDUSTRY LIMITED"},{"lang":"hk","v":"天利制作有限公司"}],"company_since":"2000-05-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718278","names":[{"lang":"en","v":"TELEHOUSE INTERNATIONAL HONG KONG LIMITED"},{"lang":"hk","v":"數碼聯網基地有限公司"}],"company_since":"2000-05-29","company_dissolved":"2004-10-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718254","names":[{"lang":"en","v":"TOP NATION (H.K.) LIMITED"},{"lang":"hk","v":"立信(香港)有限公司"}],"company_since":"2000-05-29","company_dissolved":"2008-11-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718312","names":[{"lang":"en","v":"TRI YET INDUSTRIAL (H.K.) LIMITED"},{"lang":"hk","v":"三益實業(香港)有限公司"}],"company_since":"2000-05-29","company_dissolved":"2009-11-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718266","names":[{"lang":"en","v":"TUEN MUN ELECTRIC LIGHTING COMPANY LIMITED"},{"lang":"hk","v":"屯門電器燈飾有限公司"}],"company_since":"2000-05-29","company_dissolved":"2008-09-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718251","names":[{"lang":"en","v":"VASTCO TECHNOLOGIES LIMITED"},{"lang":"hk","v":"永利高科技有限公司"}],"company_since":"2000-05-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718299","names":[{"lang":"en","v":"VENTURE ASIA PUBLISHING (HONG KONG) LIMITED"}],"company_since":"2000-05-29","company_dissolved":"2004-07-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718262","names":[{"lang":"en","v":"WEBSTAR SYSTEMS LIMITED"},{"lang":"hk","v":"網星系統有限公司"}],"company_since":"2000-05-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718245","names":[{"lang":"en","v":"WHITE TWISTER INTERNATIONAL STATIONERY LIMITED"},{"lang":"hk","v":"百豐國際文具有限公司"}],"company_since":"2000-05-29","company_dissolved":"2015-07-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718335","names":[{"lang":"en","v":"WING FUNG FURNITURE DESIGN LIMITED"},{"lang":"hk","v":"永豐傢俬設計有限公司"}],"company_since":"2000-05-29","company_dissolved":"2017-02-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718319","names":[{"lang":"en","v":"WINSON ENTERPRISES LIMITED"},{"lang":"hk","v":"永晉企業有限公司"}],"company_since":"2000-05-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718359","names":[{"lang":"en","v":"YUE FUNG JEWELLERY LIMITED"},{"lang":"hk","v":"玉峰珠寶有限公司"}],"company_since":"2000-05-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718393","names":[{"lang":"en","v":"ZOLON (INTERNATIONAL) LIMITED"},{"lang":"hk","v":"中龍電器(國際)有限公司"}],"company_since":"2000-05-29","company_dissolved":"2005-02-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718344","names":[{"lang":"en","v":"VNA INTERNATIONAL LIMITED"}],"company_since":"2000-05-29","company_dissolved":"2002-10-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"718308","names":[{"lang":"en","v":"ZUI FAT INDUSTRIAL LIMITED"},{"lang":"hk","v":"聚發實業有限公司"}],"company_since":"2000-05-29","company_dissolved":"2015-10-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"718355","names":[{"lang":"en","v":"YESTOCK.COM (HONG KONG) LIMITED"}],"company_since":"2000-05-29","company_dissolved":"2002-06-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"718290","names":[{"lang":"en","v":"WEALTH GRADE LIMITED (d2005-06-03)"},{"lang":"hk","v":"富而佳有限公司"}],"company_since":"2000-05-29","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718315","names":[{"lang":"en","v":"WING FAI FASHION FACTORY (H.K.) LIMITED"},{"lang":"hk","v":"永輝時裝廠(香港)有限公司"}],"company_since":"2000-05-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718267","names":[{"lang":"en","v":"XIANG GANG ZHI PENG INTERNATIONAL ENTERPRISES LIMITED"},{"lang":"hk","v":"香港志鵬國際企業有限公司"}],"company_since":"2000-05-29","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"718332","names":[{"lang":"en","v":"TITAN TECHNOLOGY DEVELOPMENT LIMITED"},{"lang":"hk","v":"鼎力科技有限公司"}],"company_since":"2000-05-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
