undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"759982","names":[{"lang":"en","v":"COSMOS TEAM HOLDING LIMITED"},{"lang":"hk","v":"高瞻集團有限公司"}],"company_since":"2001-06-13","company_dissolved":"2005-09-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"760089","names":[{"lang":"en","v":"GOLDEN WEALTH INTERNATIONAL HOLDING LIMITED (d2006-10-27)"},{"lang":"hk","v":"金豪國際集團有限公司"}],"company_since":"2001-06-13","company_dissolved":"2006-10-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"759966","names":[{"lang":"en","v":"EASTERN WATSON INTERNATIONAL TRADING LIMITED"},{"lang":"hk","v":"東鎭華城國際貿易有限公司"}],"company_since":"2001-06-13","company_dissolved":"2019-03-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"760122","names":[{"lang":"en","v":"HK RICHES INTERNATIONAL LIMITED"},{"lang":"hk","v":"香港瑞馨國際有限公司"}],"company_since":"2001-06-13","company_dissolved":"2006-10-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"760075","names":[{"lang":"en","v":"HK YINMENGJIAO INT'L LIMITED"},{"lang":"hk","v":"香港銀夢嬌國際有限公司"}],"company_since":"2001-06-13","company_dissolved":"2015-06-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"760023","names":[{"lang":"en","v":"GREEN TECHNOLOGY INTERNATIONAL LIMITED (d2006-10-27)"},{"lang":"hk","v":"格潤科技國際有限公司"}],"company_since":"2001-06-13","company_dissolved":"2006-10-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"759997","names":[{"lang":"en","v":"HUNG YAT TRANSPORTATION LIMITED (d2006-10-27)"},{"lang":"hk","v":"洪溢運輸有限公司"}],"company_since":"2001-06-13","company_dissolved":"2006-10-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"760069","names":[{"lang":"en","v":"HIGHRIGHT CORPORATION LIMITED"},{"lang":"hk","v":"正高有限公司"}],"company_since":"2001-06-13","company_dissolved":"2006-10-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"759996","names":[{"lang":"en","v":"JYTON ENTERPRISE GROUP LIMITED"},{"lang":"hk","v":"捷通企業集團有限公司"}],"company_since":"2001-06-13","company_dissolved":"2017-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"760161","names":[{"lang":"en","v":"KINETIC TRADING &amp; ENGINEERING LIMITED"},{"lang":"hk","v":"健力貿易工程有限公司"}],"company_since":"2001-06-13","company_dissolved":"2008-12-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"760010","names":[{"lang":"en","v":"NEW HARMONIOUS INTERNATIONAL (H.K.) CO. LIMITED"},{"lang":"hk","v":"震融國際(香港)有限公司"}],"company_since":"2001-06-13","company_dissolved":"2006-10-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"760029","names":[{"lang":"en","v":"PLASTIC REPUTATION H.K. LIMITED"},{"lang":"hk","v":"塑譽行香港有限公司"}],"company_since":"2001-06-13","company_dissolved":"2013-07-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"760017","names":[{"lang":"en","v":"P.NET COMMERCE LIMITED"}],"company_since":"2001-06-13","company_dissolved":"2005-12-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"760067","names":[{"lang":"en","v":"UMBRA (CHINA) LIMITED"},{"lang":"hk","v":"安柏(中國)有限公司"}],"company_since":"2001-06-13","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"760062","names":[{"lang":"en","v":"YEW SANG HONG BUILDING SERVICES (MAINTENANCE) ENGINEERING LIMITED"},{"lang":"hk","v":"耀生行屋宇設備(保養)工程有限公司"}],"company_since":"2001-06-13","company_dissolved":"2013-12-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"760064","names":[{"lang":"en","v":"TREASURE ERA LIMITED (d2003-12-19)"},{"lang":"hk","v":"多元有限公司"}],"company_since":"2001-06-13","company_dissolved":"2003-12-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"760164","names":[{"lang":"en","v":"YUE SHING CONSTRUCTION ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"裕城建築工程有限公司"}],"company_since":"2001-06-13","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"759964","names":[{"lang":"en","v":"CHINA HONG FA (HONG KONG) TRADING LIMITED"},{"lang":"hk","v":"中國弘發(香港)貿易有限公司"}],"company_since":"2001-06-13","company_dissolved":"2015-06-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760032","names":[{"lang":"en","v":"FRENCH HUAHUA BOY INTERNATIONAL ENTERPRISE CO., LIMITED"},{"lang":"hk","v":"法國花花公子國際企業有限公司"}],"company_since":"2001-06-13","company_dissolved":"2003-01-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760015","names":[{"lang":"en","v":"FUYO FOOD MACHINERY COMPANY LIMITED"},{"lang":"hk","v":"芙蓉食品機械有限公司"}],"company_since":"2001-06-13","company_dissolved":"2006-11-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760024","names":[{"lang":"en","v":"GLAMOUR FAIR (HONG KONG) LIMITED"},{"lang":"hk","v":"保麗(香港)有限公司"}],"company_since":"2001-06-13","company_dissolved":"2008-11-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760101","names":[{"lang":"en","v":"CONSTRUCTION INDUSTRY INSTITUTE (HONG KONG) LIMITED"}],"company_since":"2001-06-13","company_dissolved":"2010-08-12","company_type_txt":"Ltd by guarantee"},
undefined,
undefined,
{"tax_id":"760089","names":[{"lang":"en","v":"GOLDEN WEALTH INTERNATIONAL HOLDING LIMITED (d2006-10-27)"},{"lang":"hk","v":"金豪國際集團有限公司"}],"company_since":"2001-06-13","company_dissolved":"2006-10-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"760075","names":[{"lang":"en","v":"HK YINMENGJIAO INT'L LIMITED"},{"lang":"hk","v":"香港銀夢嬌國際有限公司"}],"company_since":"2001-06-13","company_dissolved":"2015-06-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760016","names":[{"lang":"en","v":"HONG KONG CHEUNG TUNG CLOTHING LIMITED"},{"lang":"hk","v":"香港祥東服裝有限公司"}],"company_since":"2001-06-13","company_dissolved":"2006-10-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"760175","names":[{"lang":"en","v":"HUI REN (HONG KONG) PHARMACEUTICAL CO., LIMITED"},{"lang":"hk","v":"滙仁(香港)葯業有限公司"}],"company_since":"2001-06-13","company_dissolved":"2007-05-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"759997","names":[{"lang":"en","v":"HUNG YAT TRANSPORTATION LIMITED (d2006-10-27)"},{"lang":"hk","v":"洪溢運輸有限公司"}],"company_since":"2001-06-13","company_dissolved":"2006-10-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"759971","names":[{"lang":"en","v":"INFINITY CAPITAL LIMITED (HK)"}],"company_since":"2001-06-13","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760128","names":[{"lang":"en","v":"INFOSOFT LEADER S&amp;T COMPANY LIMITED"},{"lang":"hk","v":"美國英碩力科技有限公司"}],"company_since":"2001-06-13","company_dissolved":"2011-02-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"759967","names":[{"lang":"en","v":"INNOTEX PRECISION LIMITED"},{"lang":"hk","v":"科匯精工有限公司"}],"company_since":"2001-06-13","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"759956","names":[{"lang":"en","v":"INTELLIGENCE CONSULTANTS LIMITED (d2011-02-02)"},{"lang":"hk","v":"宏智顧問有限公司"}],"company_since":"2001-06-13","company_dissolved":"2011-02-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"760068","names":[{"lang":"en","v":"HANGSON SIGNAGE CONTRACTING (HK) LIMITED"},{"lang":"hk","v":"香港恒信標牌工程有限公司"}],"company_since":"2001-06-13","company_dissolved":"2004-11-05","company_type_txt":"Private, ltd by shares"},
{"tax_id":"759959","names":[{"lang":"en","v":"IT SOLUTIONS (HK) LIMITED"},{"lang":"hk","v":"資訊科技方案(香港)有限公司"}],"company_since":"2001-06-13","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760179","names":[{"lang":"en","v":"ISPO WORLD CONGRESS (HK) 2004 COMPANY LIMITED"},{"lang":"hk","v":"國際義肢及矯形會議(香港)2004有限公司"}],"company_since":"2001-06-13","company_dissolved":"2010-02-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760053","names":[{"lang":"en","v":"ITALY BALANCE INT'L GROUP (CHINA) LIMITED"},{"lang":"hk","v":"意大利邦耐國際集團(中國)有限公司"}],"company_since":"2001-06-13","company_dissolved":"2007-10-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760052","names":[{"lang":"en","v":"ITALY DUNHILL (HK) INV. LIMITED"},{"lang":"hk","v":"意大利登喜路(香港)投資有限公司"}],"company_since":"2001-06-13","company_dissolved":"2010-02-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760121","names":[{"lang":"en","v":"ITALY PIERRE CARDIN DRESS GROUP (HK) INT'L LIMITED"},{"lang":"hk","v":"意大利皮爾‧卡丹服飾集團(香港)國際有限公司"}],"company_since":"2001-06-13","company_dissolved":"2006-03-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"759995","names":[{"lang":"en","v":"J.S.P. PACIFIC GROUP COMPANY LIMITED"},{"lang":"hk","v":"滙寶太平洋集團有限公司"}],"company_since":"2001-06-13","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760114","names":[{"lang":"en","v":"JAPAN DATAVAN (H.K.) CO., LIMITED"},{"lang":"hk","v":"香港捷帝威有限公司"}],"company_since":"2001-06-13","company_dissolved":"2011-02-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760081","names":[{"lang":"en","v":"JOY MATTRESS FURNITURE MAKING LIMITED"},{"lang":"hk","v":"佳豪床墊家具制造有限公司"}],"company_since":"2001-06-13","company_dissolved":"2008-11-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760144","names":[{"lang":"en","v":"JSAS (HONG KONG) LIMITED"},{"lang":"hk","v":"騏鼎國際運通有限公司"}],"company_since":"2001-06-13","company_dissolved":"2011-06-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760135","names":[{"lang":"en","v":"JU ZHANG ENTERPRISE COMPANY LIMITED"},{"lang":"hk","v":"巨展企業有限公司"}],"company_since":"2001-06-13","company_dissolved":"2006-10-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760171","names":[{"lang":"en","v":"JUKUN HANG TECHNOLOGY (H.K.) CO., LIMITED"},{"lang":"hk","v":"炬坤行科技(香港)有限公司"}],"company_since":"2001-06-13","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760009","names":[{"lang":"en","v":"GOVERNOR (INT'L) CLOTHING LIMITED"},{"lang":"hk","v":"總督(國際)服飾有限公司"}],"company_since":"2001-06-13","company_dissolved":"2007-10-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760023","names":[{"lang":"en","v":"GREEN TECHNOLOGY INTERNATIONAL LIMITED (d2006-10-27)"},{"lang":"hk","v":"格潤科技國際有限公司"}],"company_since":"2001-06-13","company_dissolved":"2006-10-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760174","names":[{"lang":"en","v":"KAI YING ALBUM ENVELOPE PRODUCTS CO., LIMITED"},{"lang":"hk","v":"佳影相簿信封製品有限公司"}],"company_since":"2001-06-13","company_dissolved":"2009-11-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760156","names":[{"lang":"en","v":"H2 INTERNATIONAL LIMITED (HK)"},{"lang":"hk","v":"興二國際有限公司"}],"company_since":"2001-06-13","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"759999","names":[{"lang":"en","v":"KAM HING INTERNATIONAL SHIPPING LIMITED"},{"lang":"hk","v":"錦興國際船務有限公司"}],"company_since":"2001-06-13","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"759986","names":[{"lang":"en","v":"K. S. ENGINEERING CONSTRUCTION COMPANY LIMITED"},{"lang":"hk","v":"基成建築工程有限公司"}],"company_since":"2001-06-13","company_dissolved":"2008-11-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760115","names":[{"lang":"en","v":"HALCYON HOLDINGS LIMITED (d2006-10-27)"}],"company_since":"2001-06-13","company_dissolved":"2006-10-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760027","names":[{"lang":"en","v":"KAM HING SPINNING INDUSTRIAL LIMITED"},{"lang":"hk","v":"錦興紡織實業有限公司"}],"company_since":"2001-06-13","company_dissolved":"2007-06-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"760122","names":[{"lang":"en","v":"HK RICHES INTERNATIONAL LIMITED"},{"lang":"hk","v":"香港瑞馨國際有限公司"}],"company_since":"2001-06-13","company_dissolved":"2006-10-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"760107","names":[{"lang":"en","v":"HALE AND HEARTY RESOURCES LIMITED"},{"lang":"hk","v":"健康資源有限公司"}],"company_since":"2001-06-13","company_dissolved":"2020-03-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760013","names":[{"lang":"en","v":"KELDIAM LIMITED"},{"lang":"hk","v":"其豐貿易有限公司"}],"company_since":"2001-06-13","company_dissolved":"2016-03-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"759994","names":[{"lang":"en","v":"KENWIN INDUSTRIAL (H.K.) LIMITED"},{"lang":"hk","v":"建榮企業(香港)有限公司"}],"company_since":"2001-06-13","company_dissolved":"2019-04-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"759987","names":[{"lang":"en","v":"KIN SUN CORPORATION LIMITED"}],"company_since":"2001-06-13","company_dissolved":"2006-10-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760161","names":[{"lang":"en","v":"KINETIC TRADING &amp; ENGINEERING LIMITED"},{"lang":"hk","v":"健力貿易工程有限公司"}],"company_since":"2001-06-13","company_dissolved":"2008-12-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760124","names":[{"lang":"en","v":"KOREA GOLDWOLF (HK) INT'L LIMITED"},{"lang":"hk","v":"韓國金狐狸(香港)國際有限公司"}],"company_since":"2001-06-13","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760056","names":[{"lang":"en","v":"FRANCE JOY.TOP WINE (HK) INT'L LIMITED"},{"lang":"hk","v":"法國佳名‧湯酒業(香港)國際有限公司"}],"company_since":"2001-06-13","company_dissolved":"2006-10-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760099","names":[{"lang":"en","v":"KRONOS ASIA LIMITED"}],"company_since":"2001-06-13","company_dissolved":"2020-03-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760091","names":[{"lang":"en","v":"LANEEART GIFT &amp; FLOWER WRAPS CO., LIMITED"},{"lang":"hk","v":"嵐藝包裝材料有限公司"}],"company_since":"2001-06-13","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760098","names":[{"lang":"en","v":"LAW &amp; PARTNERS LIMITED"}],"company_since":"2001-06-13","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"759961","names":[{"lang":"en","v":"LEADER TEXTILES LIMITED"},{"lang":"hk","v":"聯達紡織有限公司"}],"company_since":"2001-06-13","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760018","names":[{"lang":"en","v":"LIANDONE ELECTRONIC EQUIPMENT COMPANY LIMITED"},{"lang":"hk","v":"聯頓電子設備有限公司"}],"company_since":"2001-06-13","company_dissolved":"2013-06-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760170","names":[{"lang":"en","v":"LINGWAY ENGINEERING CONSULTANTS LIMITED"},{"lang":"hk","v":"裕豐工程顧問有限公司"}],"company_since":"2001-06-13","company_dissolved":"2002-03-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"759974","names":[{"lang":"en","v":"HONG KONG GREAT DRAGON INTERNATIONAL TOBACCO LIMITED"},{"lang":"hk","v":"香港萬龍國際煙草有限公司"}],"company_since":"2001-06-13","company_dissolved":"2006-10-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"759975","names":[{"lang":"en","v":"HONG KONG SIN SIN COSMETIC LIMITED"},{"lang":"hk","v":"香港倩倩化粧品有限公司"}],"company_since":"2001-06-13","company_dissolved":"2003-04-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760031","names":[{"lang":"en","v":"NAM KEE TRAVEL CO. LIMITED"},{"lang":"hk","v":"南記旅運有限公司"}],"company_since":"2001-06-13","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760088","names":[{"lang":"en","v":"MEMFUS WONG AUCTIONEERS LIMITED"},{"lang":"hk","v":"黃開基拍賣行有限公司"}],"company_since":"2001-06-13","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"759979","names":[{"lang":"en","v":"HONG KONG TEAM LIGHT INTERNATIONAL LIMITED"},{"lang":"hk","v":"香港天力國際有限公司"}],"company_since":"2001-06-13","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"759965","names":[{"lang":"en","v":"NICEFUL INTERNATIONAL LIMITED"},{"lang":"hk","v":"禮豐國際有限公司"}],"company_since":"2001-06-13","company_dissolved":"2020-07-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760078","names":[{"lang":"en","v":"NOBLE SANITARY EQUIPMENT INT'L (ITALY) LIMITED"},{"lang":"hk","v":"尚品衛浴設備國際(意大利)有限公司"}],"company_since":"2001-06-13","company_dissolved":"2012-11-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760003","names":[{"lang":"en","v":"OLESA KITCHEN WARE HONG KONG INTERNATIONAL CO. LIMITED"},{"lang":"hk","v":"歐麗莎衛廚香港國際有限公司"}],"company_since":"2001-06-13","company_dissolved":"2006-10-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760110","names":[{"lang":"en","v":"ON WAI LIMITED"},{"lang":"hk","v":"安慧有限公司"}],"company_since":"2001-06-13","company_dissolved":"2007-10-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760160","names":[{"lang":"en","v":"HUAH YING INTERNATIONAL LIMITED"},{"lang":"hk","v":"樺穎貿易有限公司"}],"company_since":"2001-06-13","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760137","names":[{"lang":"en","v":"ON WIN INTERNATIONAL HOLDING LIMITED"},{"lang":"hk","v":"安榮國際集團有限公司"}],"company_since":"2001-06-13","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"759977","names":[{"lang":"en","v":"ONWAYS ELECTRICAL HK LIMITED"},{"lang":"hk","v":"香港安姆電器有限公司"}],"company_since":"2001-06-13","company_dissolved":"2006-10-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760185","names":[{"lang":"en","v":"OPTICAL TRADING INTERNATIONAL LIMITED"}],"company_since":"2001-06-13","company_dissolved":"2010-09-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"760183","names":[{"lang":"en","v":"ORIENTAL MAX GROUP LIMITED"},{"lang":"hk","v":"麥斯集團有限公司"}],"company_since":"2001-06-13","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"760017","names":[{"lang":"en","v":"P.NET COMMERCE LIMITED"}],"company_since":"2001-06-13","company_dissolved":"2005-12-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760146","names":[{"lang":"en","v":"PARA PARA FASHION GROUP LIMITED"}],"company_since":"2001-06-13","company_dissolved":"2002-11-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760154","names":[{"lang":"en","v":"PINNACLE CAPITAL LIMITED (HK)"},{"lang":"hk","v":"佰匯融資有限公司"}],"company_since":"2001-06-13","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"759953","names":[{"lang":"en","v":"PINNAFUND INTERNATIONAL INVESTMENTS LIMITED"},{"lang":"hk","v":"佰匯投資有限公司"}],"company_since":"2001-06-13","company_dissolved":"2020-03-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"759958","names":[{"lang":"en","v":"PLAIN SAILING SHIPPING LIMITED"},{"lang":"hk","v":"翔程船務有限公司"}],"company_since":"2001-06-13","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"760010","names":[{"lang":"en","v":"NEW HARMONIOUS INTERNATIONAL (H.K.) CO. LIMITED"},{"lang":"hk","v":"震融國際(香港)有限公司"}],"company_since":"2001-06-13","company_dissolved":"2006-10-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760108","names":[{"lang":"en","v":"SILVER VANTAGE LIMITED"},{"lang":"hk","v":"福銀有限公司"}],"company_since":"2001-06-13","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760086","names":[{"lang":"en","v":"LOCK CHIROPRACTIC LIMITED"},{"lang":"hk","v":"郭振威脊椎神經醫療中心有限公司"}],"company_since":"2001-06-13","company_dissolved":"2006-10-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760005","names":[{"lang":"en","v":"N &amp; T LOGISTICS COMPANY LIMITED"},{"lang":"hk","v":"力通物流有限公司"}],"company_since":"2001-06-13","company_dissolved":"2015-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"759970","names":[{"lang":"en","v":"Y.G.O. COMPANY LIMITED"},{"lang":"hk","v":"運之寶有限公司"}],"company_since":"2001-06-13","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760134","names":[{"lang":"en","v":"YING WO INTERNATIONAL LIMITED"},{"lang":"hk","v":"英和國際有限公司"}],"company_since":"2001-06-13","company_dissolved":"2003-06-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760002","names":[{"lang":"en","v":"YIHCON ELECTRONICS CO., LIMITED"},{"lang":"hk","v":"億泓電子有限公司"}],"company_since":"2001-06-13","company_dissolved":"2015-06-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"760164","names":[{"lang":"en","v":"YUE SHING CONSTRUCTION ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"裕城建築工程有限公司"}],"company_since":"2001-06-13","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"759981","names":[{"lang":"en","v":"YUEN YUEN GROUP COMPANY LIMITED"},{"lang":"hk","v":"源源集團控股有限公司"}],"company_since":"2001-06-13","company_dissolved":"2008-04-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"760040","names":[{"lang":"en","v":"SMARTMAN LIMITED (HK)"},{"lang":"hk","v":"駿文有限公司"}],"company_since":"2001-06-13","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760106","names":[{"lang":"en","v":"SOUTH IN WEST LIMITED"},{"lang":"hk","v":"北望洋有限公司"}],"company_since":"2001-06-13","company_dissolved":"2003-01-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"759976","names":[{"lang":"en","v":"W. H. FONG &amp; COMPANY LIMITED"},{"lang":"hk","v":"方氏有限公司"}],"company_since":"2001-06-13","company_dissolved":"2003-11-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760035","names":[{"lang":"en","v":"WAY FAIR LIMITED"},{"lang":"hk","v":"創忠有限公司"}],"company_since":"2001-06-13","company_dissolved":"2007-10-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760063","names":[{"lang":"en","v":"WAYGOLD CORPORATION LIMITED"},{"lang":"hk","v":"豐鑫有限公司"}],"company_since":"2001-06-13","company_dissolved":"2006-10-27","company_type_txt":"Private, ltd by shares"},
undefined,
