undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"760797","names":[{"lang":"en","v":"CHUAN CHUAN LIMITED"},{"lang":"hk","v":"川川有限公司"}],"company_since":"2001-06-20","company_dissolved":"2009-10-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"760817","names":[{"lang":"en","v":"CONCRETE PIPE PRODUCERS ASSOCIATION OF HONG KONG LIMITED (THE)"},{"lang":"hk","v":"香港混凝土管筒製造商協會有限公司"}],"company_since":"2001-06-20","company_dissolved":"2017-08-10","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"760888","names":[{"lang":"en","v":"CYGNUS SATELLITE LIMITED"},{"lang":"hk","v":"星際衛星有限公司"}],"company_since":"2001-06-20","company_dissolved":"2008-11-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"760796","names":[{"lang":"en","v":"CYPRESS INSURANCE AGENCY LIMITED"},{"lang":"hk","v":"松柏保險代理有限公司"}],"company_since":"2001-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"760742","names":[{"lang":"en","v":"DRACCO COMPANY LIMITED"}],"company_since":"2001-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"760680","names":[{"lang":"en","v":"GOOD MAN BOOK STORE LIMITED"},{"lang":"hk","v":"冠文書局有限公司"}],"company_since":"2001-06-20","company_dissolved":"2005-03-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"760864","names":[{"lang":"en","v":"HLM ASIA GROUP LIMITED"},{"lang":"hk","v":"恒健亞洲集團有限公司"}],"company_since":"2001-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"760961","names":[{"lang":"en","v":"JIFFYCRISP INTERNATIONAL LIMITED"}],"company_since":"2001-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"760996","names":[{"lang":"en","v":"ITALY XILI HARDWARE DRESSING GROUP (HK) LIMITED"},{"lang":"hk","v":"意大利喜力五金裝璜集團(香港)有限公司"}],"company_since":"2001-06-20","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760694","names":[{"lang":"en","v":"LINK CONCEPT INVESTMENT LIMITED"},{"lang":"hk","v":"能捷投資有限公司"}],"company_since":"2001-06-20","company_dissolved":"2011-06-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"760765","names":[{"lang":"en","v":"LINKFUL TRADING LIMITED"},{"lang":"hk","v":"達豐貿易有限公司"}],"company_since":"2001-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"760912","names":[{"lang":"en","v":"JOYCE FAIR LIMITED"},{"lang":"hk","v":"博欣有限公司"}],"company_since":"2001-06-20","company_dissolved":"2004-09-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"760701","names":[{"lang":"en","v":"MAYSUN (HK) LIMITED"},{"lang":"hk","v":"美順(香港)有限公司"}],"company_since":"2001-06-20","company_dissolved":"2003-08-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"761006","names":[{"lang":"en","v":"META4 DESIGN FORUM LIMITED"}],"company_since":"2001-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"760724","names":[{"lang":"en","v":"PANFORD MARBLE COMPANY LIMITED"},{"lang":"hk","v":"聯福雲石有限公司"}],"company_since":"2001-06-20","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"760859","names":[{"lang":"en","v":"POWER PROPERTIES MANAGEMENT LIMITED"},{"lang":"hk","v":"保亞物業管理有限公司"}],"company_since":"2001-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"760895","names":[{"lang":"en","v":"PELICAN COMPONENTS COMPANY LIMITED"}],"company_since":"2001-06-20","company_dissolved":"2012-10-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"760686","names":[{"lang":"en","v":"PRIME LUCK HOLDINGS LIMITED (d2006-11-03)"},{"lang":"hk","v":"益昇集團有限公司"}],"company_since":"2001-06-20","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"760940","names":[{"lang":"en","v":"PROMATE DEVELOPMENT LIMITED"},{"lang":"hk","v":"普麗發展有限公司"}],"company_since":"2001-06-20","company_dissolved":"2005-08-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"760839","names":[{"lang":"en","v":"QUEEN LIGHT CHINA COMPANY LIMITED"},{"lang":"hk","v":"雷雅中國有限公司"}],"company_since":"2001-06-20","company_dissolved":"2008-05-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"760733","names":[{"lang":"en","v":"ROYALION LIMITED"},{"lang":"hk","v":"俊良有限公司"}],"company_since":"2001-06-20","company_dissolved":"2015-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"760789","names":[{"lang":"en","v":"SINCO TECHNOLOGY LIMITED (d2009-04-30)"},{"lang":"hk","v":"迅高科技有限公司"}],"company_since":"2001-06-20","company_dissolved":"2009-04-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"760922","names":[{"lang":"en","v":"SOMRAS LIMITED"}],"company_since":"2001-06-20","company_dissolved":"2004-01-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"760735","names":[{"lang":"en","v":"SHAOLIN-ONLINE LIMITED"},{"lang":"hk","v":"網絡少林有限公司"}],"company_since":"2001-06-20","company_dissolved":"2003-05-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"760727","names":[{"lang":"en","v":"SUPERNIC TECHNOLOGY LIMITED"},{"lang":"hk","v":"卓力科技有限公司"}],"company_since":"2001-06-20","company_dissolved":"2018-02-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"760707","names":[{"lang":"en","v":"SPEED ASIAN LIMITED"},{"lang":"hk","v":"時速有限公司"}],"company_since":"2001-06-20","company_dissolved":"2002-06-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"760713","names":[{"lang":"en","v":"TRADE WINDS EQUIPMENT EXCHANGE LIMITED"}],"company_since":"2001-06-20","company_dissolved":"2005-02-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"760847","names":[{"lang":"en","v":"TRUMP HARVEST INTERNATIONAL LIMITED"},{"lang":"hk","v":"祥豪國際有限公司"}],"company_since":"2001-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"760708","names":[{"lang":"en","v":"VENTURE GLORY LIMITED (d2004-05-21)"},{"lang":"hk","v":"忠原有限公司"}],"company_since":"2001-06-20","company_dissolved":"2004-05-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"760903","names":[{"lang":"en","v":"VICTORY LOGISTICS LIMITED (d2003-01-30)"},{"lang":"hk","v":"盈冠物流有限公司"}],"company_since":"2001-06-20","company_dissolved":"2003-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"760933","names":[{"lang":"en","v":"TRENDY INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"赫基國際投資有限公司"}],"company_since":"2001-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"760751","names":[{"lang":"en","v":"YI FENG ELECTRONICS LIMITED"},{"lang":"hk","v":"億峰電子有限公司"}],"company_since":"2001-06-20","company_dissolved":"2015-06-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760998","names":[{"lang":"en","v":"YIN SHAU TUNG (HONG KONG) MEDICINE COMPANY LIMITED"},{"lang":"hk","v":"延壽堂(香港)葯業有限公司"}],"company_since":"2001-06-20","company_dissolved":"2017-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760817","names":[{"lang":"en","v":"CONCRETE PIPE PRODUCERS ASSOCIATION OF HONG KONG LIMITED (THE)"},{"lang":"hk","v":"香港混凝土管筒製造商協會有限公司"}],"company_since":"2001-06-20","company_dissolved":"2017-08-10","company_type_txt":"Ltd by guarantee"},
undefined,
undefined,
undefined,
{"tax_id":"760705","names":[{"lang":"en","v":"FENCING AND SPORTS DEVELOPMENT LIMITED"},{"lang":"hk","v":"劍擊與康體發展有限公司"}],"company_since":"2001-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"760983","names":[{"lang":"en","v":"FRANCE ALOE INTERNATIONAL GROUP (HK) LIMITED"},{"lang":"hk","v":"法國雅蘭國際集團(香港)有限公司"}],"company_since":"2001-06-20","company_dissolved":"2008-11-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"760959","names":[{"lang":"en","v":"FRANCE CARDEN RANGER DRESSING (INTERNATIONAL) GROUP LIMITED"},{"lang":"hk","v":"法國卡丹雷傑服飾(國際)集團有限公司"}],"company_since":"2001-06-20","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"760992","names":[{"lang":"en","v":"FRANCE SAINT ROLAND DRESS (HK) INT'L LIMITED"},{"lang":"hk","v":"法國聖羅蘭服飾(香港)國際有限公司"}],"company_since":"2001-06-20","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"760927","names":[{"lang":"en","v":"GOLD COIN INTERNATIONAL LIMITED (d2010-02-12)"},{"lang":"hk","v":"金盈國際有限公司"}],"company_since":"2001-06-20","company_dissolved":"2010-02-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760851","names":[{"lang":"en","v":"GOLD SQUIRREL (HONG KONG) GARMENT LIMITED"},{"lang":"hk","v":"金松鼠(香港)服飾有限公司"}],"company_since":"2001-06-20","company_dissolved":"2009-11-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760766","names":[{"lang":"en","v":"GOOD CHOICE DEVELOPMENT LIMITED"},{"lang":"hk","v":"成才發展有限公司"}],"company_since":"2001-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"760680","names":[{"lang":"en","v":"GOOD MAN BOOK STORE LIMITED"},{"lang":"hk","v":"冠文書局有限公司"}],"company_since":"2001-06-20","company_dissolved":"2005-03-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"760764","names":[{"lang":"en","v":"GOOD RISE HOLDINGS LIMITED"},{"lang":"hk","v":"彩昇集團有限公司"}],"company_since":"2001-06-20","company_dissolved":"2020-04-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760907","names":[{"lang":"en","v":"GRADON TECHNOLOGY LIMITED"},{"lang":"hk","v":"佳安科技有限公司"}],"company_since":"2001-06-20","company_dissolved":"2002-04-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760793","names":[{"lang":"en","v":"FEEDS, CEREAL AND COTTON LIMITED"}],"company_since":"2001-06-20","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760836","names":[{"lang":"en","v":"GRAND PEARL FURNITURE INDUSTRIES LIMITED"}],"company_since":"2001-06-20","company_dissolved":"2003-06-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760660","names":[{"lang":"en","v":"GRANDSKY ENGINEERING LIMITED (d2007-11-16)"},{"lang":"hk","v":"天廣工程有限公司"}],"company_since":"2001-06-20","company_dissolved":"2007-11-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760659","names":[{"lang":"en","v":"GREAT STRATEGY TRADING LIMITED"},{"lang":"hk","v":"浩志貿易有限公司"}],"company_since":"2001-06-20","company_dissolved":"2003-11-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760712","names":[{"lang":"en","v":"GREAT WEALTH TELECOM LIMITED"},{"lang":"hk","v":"富大電信有限公司"}],"company_since":"2001-06-20","company_dissolved":"2012-07-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760957","names":[{"lang":"en","v":"GREEN BIRD TECHNOLOGY LIMITED"},{"lang":"hk","v":"晴鳥科技有限公司"}],"company_since":"2001-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760874","names":[{"lang":"en","v":"GUO SHENG INTERNATIONAL LIMITED"},{"lang":"hk","v":"國聖國際有限公司"}],"company_since":"2001-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760865","names":[{"lang":"en","v":"H.K. FEDERATION LBDENXILU INT'L GROUP LIMITED"},{"lang":"hk","v":"香港萊博登喜露國際集團有限公司"}],"company_since":"2001-06-20","company_dissolved":"2003-09-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760879","names":[{"lang":"en","v":"HARRY A. KLEIN ASSOCIATES, (HK) LIMITED"}],"company_since":"2001-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760875","names":[{"lang":"en","v":"HIGHWAY TRANSPORTATION ENGINEERING LIMITED"},{"lang":"hk","v":"利通運輸工程有限公司"}],"company_since":"2001-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760991","names":[{"lang":"en","v":"HK FM HONDA TECH LIMITED"},{"lang":"hk","v":"香港愛孚埃姆本田科技有限公司"}],"company_since":"2001-06-20","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760849","names":[{"lang":"en","v":"HILLARY NECKWEAR &amp; CLOTHES CO., LIMITED"},{"lang":"hk","v":"美加華商國際集團有限公司"}],"company_since":"2001-06-20","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760955","names":[{"lang":"en","v":"DIRSOON LOGISTICS COMPANY LIMITED"},{"lang":"hk","v":"德勝物流(中國)有限公司"}],"company_since":"2001-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760816","names":[{"lang":"en","v":"DOLLARS PRODUCTIVITY TRANSFERENCE SERVICES CENTER LIMITED"},{"lang":"hk","v":"德力生產力轉移服務中心有限公司"}],"company_since":"2001-06-20","company_dissolved":"2010-02-26","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"760805","names":[{"lang":"en","v":"HONG KONG AI KE SEN COMPANY LIMITED"},{"lang":"hk","v":"香港艾科森有限公司"}],"company_since":"2001-06-20","company_dissolved":"2014-01-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760697","names":[{"lang":"en","v":"DRAGON FAR EAST LIMITED (d2008-10-17)"},{"lang":"hk","v":"彩龍遠東有限公司"}],"company_since":"2001-06-20","company_dissolved":"2008-10-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760958","names":[{"lang":"en","v":"HONG KONG ANBOUND GROUP LIMITED"},{"lang":"hk","v":"香港安邦集團有限公司"}],"company_since":"2001-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760641","names":[{"lang":"en","v":"DYNA-HEALTH (HONG KONG) LIMITED"},{"lang":"hk","v":"特能康(香港)有限公司"}],"company_since":"2001-06-20","company_dissolved":"2007-06-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760945","names":[{"lang":"en","v":"HONG KONG ANTIAIDS MEDICINE GROUP LIMITED"},{"lang":"hk","v":"香港安太滋藥業集團有限公司"}],"company_since":"2001-06-20","company_dissolved":"2019-03-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760832","names":[{"lang":"en","v":"HONG KONG ANTIAIDS SALES INTERNATIONAL GROUP LIMITED"},{"lang":"hk","v":"香港安太滋銷售國際集團有限公司"}],"company_since":"2001-06-20","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760848","names":[{"lang":"en","v":"EU HUNG ENTERPRISES CO. LIMITED"},{"lang":"hk","v":"幼鴻企業有限公司"}],"company_since":"2001-06-20","company_dissolved":"2007-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760668","names":[{"lang":"en","v":"EXCEL PROFIT INTERNATIONAL INVESTMENT HOLDINGS LIMITED"},{"lang":"hk","v":"卓利國際投資集團有限公司"}],"company_since":"2001-06-20","company_dissolved":"2005-11-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760902","names":[{"lang":"en","v":"HONG KONG AO DUO AO INTERNATIONAL HOLDING LIMITED"},{"lang":"hk","v":"香港奧多傲國際集團有限公司"}],"company_since":"2001-06-20","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760692","names":[{"lang":"en","v":"EXPRESS INVESTMENTS LIMITED (d2006-07-14)"},{"lang":"hk","v":"捷勤投資有限公司"}],"company_since":"2001-06-20","company_dissolved":"2006-07-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760736","names":[{"lang":"en","v":"HONG KONG ASSETS EXCHANGE LIMITED"},{"lang":"hk","v":"香港產權交易中心有限公司"}],"company_since":"2001-06-20","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760719","names":[{"lang":"en","v":"HONG KONG BAO CHENG INTERNATIONAL CO. LIMITED"},{"lang":"hk","v":"香港寶城國際有限公司"}],"company_since":"2001-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760815","names":[{"lang":"en","v":"HONG KONG ELECTRIC WATER HEATER ASSOCIATION LIMITED"},{"lang":"hk","v":"香港電熱水器同業總會有限公司"}],"company_since":"2001-06-20","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"760759","names":[{"lang":"en","v":"HONG KONG JIN XUAN FURNITURE GROUP LIMITED"},{"lang":"hk","v":"香港金軒傢俱集團有限公司"}],"company_since":"2001-06-20","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760852","names":[{"lang":"en","v":"HONG KONG PROPERTY CONSULTANT ASSOCIATION LIMITED"},{"lang":"hk","v":"香港地產顧問協會有限公司"}],"company_since":"2001-06-20","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760866","names":[{"lang":"en","v":"HONG KONG SPORTS MEDICINE GROUP LIMITED"}],"company_since":"2001-06-20","company_dissolved":"2004-06-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760880","names":[{"lang":"en","v":"HONG KONG SUNSHINE ELECTRON TECHNOLOGY LIMITED"},{"lang":"hk","v":"香港陽光電子科技有限公司"}],"company_since":"2001-06-20","company_dissolved":"2008-01-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760878","names":[{"lang":"en","v":"HONG KONG TIMES CULTURE PUBLISHING CO., LIMITED"},{"lang":"hk","v":"香港時代文化出版社有限公司"}],"company_since":"2001-06-20","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760942","names":[{"lang":"en","v":"HONG KONG WONG KONG KAM SAU TONG CHONGS' ASSOCIATION LIMITED"},{"lang":"hk","v":"香港皇崗錦繡堂莊氏宗親會有限公司"}],"company_since":"2001-06-20","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"760837","names":[{"lang":"en","v":"HONG KONG YORSAN INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"香港永聖國際集團有限公司"}],"company_since":"2001-06-20","company_dissolved":"2007-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760772","names":[{"lang":"en","v":"HOPE WELL (HK) LIMITED"},{"lang":"hk","v":"浩榮(香港)有限公司"}],"company_since":"2001-06-20","company_dissolved":"2006-12-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760758","names":[{"lang":"en","v":"INFO &amp; IDENTIFICATION TECHNOLOGY COMPANY LIMITED"},{"lang":"hk","v":"資訊及認証科技有限公司"}],"company_since":"2001-06-20","company_dissolved":"2005-03-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760850","names":[{"lang":"en","v":"GANGYUAN (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"鋼源(香港)有限公司"}],"company_since":"2001-06-20","company_dissolved":"2004-11-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760700","names":[{"lang":"en","v":"INFO BRIGHT (HK) LIMITED"},{"lang":"hk","v":"英輝(香港)有限公司"}],"company_since":"2001-06-20","company_dissolved":"2006-07-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760774","names":[{"lang":"en","v":"INFO GAIN (HK) LIMITED"},{"lang":"hk","v":"英傑(香港)有限公司"}],"company_since":"2001-06-20","company_dissolved":"2017-01-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760730","names":[{"lang":"en","v":"INFOBEST TRADING LIMITED"},{"lang":"hk","v":"保益貿易有限公司"}],"company_since":"2001-06-20","company_dissolved":"2011-07-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760728","names":[{"lang":"en","v":"INFOSTAR TECHNOLOGY LIMITED"},{"lang":"hk","v":"富佳科技有限公司"}],"company_since":"2001-06-20","company_dissolved":"2014-10-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760744","names":[{"lang":"en","v":"INOTEK LIMITED (d2010-09-17)"},{"lang":"hk","v":"恩德有限公司"}],"company_since":"2001-06-20","company_dissolved":"2010-09-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760685","names":[{"lang":"en","v":"GLOBAL PRINTING EQUIPMENT AND ENGINEERING LIMITED"},{"lang":"hk","v":"高寶印刷器材工程有限公司"}],"company_since":"2001-06-20","company_dissolved":"2017-12-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760718","names":[{"lang":"en","v":"INTERNATIONAL GROUP (HOLDINGS) LIMITED"},{"lang":"hk","v":"國際集團(控股)有限公司"}],"company_since":"2001-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760807","names":[{"lang":"en","v":"IT DEPARTMENT LIMITED"},{"lang":"hk","v":"泓銳科技有限公司"}],"company_since":"2001-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760723","names":[{"lang":"en","v":"ITALTRIM LIMITED"}],"company_since":"2001-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760993","names":[{"lang":"en","v":"ITALY BOSS GROUP (HK) INT'L LIMITED"},{"lang":"hk","v":"意大利波士集團(香港)國際有限公司"}],"company_since":"2001-06-20","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760709","names":[{"lang":"en","v":"ITALY DAUGRES CERAMICHE S.P.A. LIMITED"},{"lang":"hk","v":"意大利道格拉斯陶瓷有限公司"}],"company_since":"2001-06-20","company_dissolved":"2015-07-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760995","names":[{"lang":"en","v":"ITALY ORIENTAL WOODPECKER (HK) INT'L GROUP LIMITED"},{"lang":"hk","v":"意大利東方啄木鳥(香港)國際集團有限公司"}],"company_since":"2001-06-20","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760996","names":[{"lang":"en","v":"ITALY XILI HARDWARE DRESSING GROUP (HK) LIMITED"},{"lang":"hk","v":"意大利喜力五金裝璜集團(香港)有限公司"}],"company_since":"2001-06-20","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760898","names":[{"lang":"en","v":"ITEC PRO LIMITED (d2002-11-22)"},{"lang":"hk","v":"弘智科技有限公司"}],"company_since":"2001-06-20","company_dissolved":"2002-11-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760791","names":[{"lang":"en","v":"JASON TEXTILES (INTERNATIONAL) LIMITED"},{"lang":"hk","v":"捷盛紡織(國際)有限公司"}],"company_since":"2001-06-20","company_dissolved":"2014-10-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760929","names":[{"lang":"en","v":"JESS INVESTMENT LIMITED"},{"lang":"hk","v":"捷思投資有限公司"}],"company_since":"2001-06-20","company_dissolved":"2013-05-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"760930","names":[{"lang":"en","v":"MAJESTY PACKAGING INTERNATIONAL LIMITED"},{"lang":"hk","v":"美捷時包裝國際有限公司"}],"company_since":"2001-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"761006","names":[{"lang":"en","v":"META4 DESIGN FORUM LIMITED"}],"company_since":"2001-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"760882","names":[{"lang":"en","v":"OBY COMPANY LIMITED"},{"lang":"hk","v":"奧比有限公司"}],"company_since":"2001-06-20","company_dissolved":"2003-10-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760856","names":[{"lang":"en","v":"OMNI DEVELOPMENT ASIA LIMITED"}],"company_since":"2001-06-20","company_dissolved":"2008-01-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"760655","names":[{"lang":"en","v":"ORIENT PROJECT ENGINEERING LIMITED"},{"lang":"hk","v":"東鴻工程有限公司"}],"company_since":"2001-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"761003","names":[{"lang":"en","v":"ORLIMA INVESTMENTS LIMITED"},{"lang":"hk","v":"巧明投資有限公司"}],"company_since":"2001-06-20","company_dissolved":"2008-12-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760763","names":[{"lang":"en","v":"ORTEGA REALTY AND DEVELOPMENT CORPORATION (HK) LIMITED"}],"company_since":"2001-06-20","company_dissolved":"2008-12-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760674","names":[{"lang":"en","v":"OSIA TECHNOLOGY LIMITED"}],"company_since":"2001-06-20","company_dissolved":"2009-11-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760863","names":[{"lang":"en","v":"LI ZHONG CHENG XIN CO. LIMITED"},{"lang":"hk","v":"利眾誠信有限公司"}],"company_since":"2001-06-20","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760824","names":[{"lang":"en","v":"PAK LUEN SING TRADING LIMITED"},{"lang":"hk","v":"柏聯昇貿易有限公司"}],"company_since":"2001-06-20","company_dissolved":"2003-10-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760919","names":[{"lang":"en","v":"MING FAI (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"明輝(香港)有限公司"}],"company_since":"2001-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760731","names":[{"lang":"en","v":"METROSTAR CHINA LIMITED (d2003-10-03)"},{"lang":"hk","v":"美達中國有限公司"}],"company_since":"2001-06-20","company_dissolved":"2003-10-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760720","names":[{"lang":"en","v":"MIT JETPRINT IMAGING SERVICE LIMITED"},{"lang":"hk","v":"港印影像服務有限公司"}],"company_since":"2001-06-20","company_dissolved":"2012-09-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760682","names":[{"lang":"en","v":"MOBILE ONE TECHNOLOGY LIMITED"}],"company_since":"2001-06-20","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760941","names":[{"lang":"en","v":"Purse Company (Hong Kong) Limited (The)"},{"lang":"hk","v":"浦昇(香港)有限公司"}],"company_since":"2001-06-20","company_dissolved":"2013-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"760953","names":[{"lang":"en","v":"NEW STAR TECHNOLOGIES LIMITED"},{"lang":"hk","v":"新衛星科技有限公司"}],"company_since":"2001-06-20","company_dissolved":"2017-10-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760733","names":[{"lang":"en","v":"ROYALION LIMITED"},{"lang":"hk","v":"俊良有限公司"}],"company_since":"2001-06-20","company_dissolved":"2015-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"760827","names":[{"lang":"en","v":"PRO-G PACIFIC HOLDINGS LIMITED"}],"company_since":"2001-06-20","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"760877","names":[{"lang":"en","v":"PARAGON MICROELECTRONICS LIMITED"}],"company_since":"2001-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760806","names":[{"lang":"en","v":"PATOHWUN ENTERPRISES LIMITED"}],"company_since":"2001-06-20","company_dissolved":"2005-03-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760813","names":[{"lang":"en","v":"PERFECT LIFE ASIA LIMITED"},{"lang":"hk","v":"優越醫療亞洲有限公司"}],"company_since":"2001-06-20","company_dissolved":"2019-07-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760885","names":[{"lang":"en","v":"PHEBEO LIMITED"},{"lang":"hk","v":"域比有限公司"}],"company_since":"2001-06-20","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760717","names":[{"lang":"en","v":"PHILA CHINA LIMITED"},{"lang":"hk","v":"華郵有限公司"}],"company_since":"2001-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760683","names":[{"lang":"en","v":"SMART TECHNOLOGIES LIMITED"},{"lang":"hk","v":"卓駿科技有限公司"}],"company_since":"2001-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"761014","names":[{"lang":"en","v":"SMARTNET SYSTEM LIMITED"},{"lang":"hk","v":"智能系統有限公司"}],"company_since":"2001-06-20","company_dissolved":"2003-10-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760976","names":[{"lang":"en","v":"SMEC HK LIMITED"}],"company_since":"2001-06-20","company_dissolved":"2008-11-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"760839","names":[{"lang":"en","v":"QUEEN LIGHT CHINA COMPANY LIMITED"},{"lang":"hk","v":"雷雅中國有限公司"}],"company_since":"2001-06-20","company_dissolved":"2008-05-23","company_type_txt":"Private, ltd by shares"},
{"tax_id":"760990","names":[{"lang":"en","v":"SOLAR KING ENTERPRISES LIMITED"},{"lang":"hk","v":"暉景企業有限公司"}],"company_since":"2001-06-20","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760922","names":[{"lang":"en","v":"SOMRAS LIMITED"}],"company_since":"2001-06-20","company_dissolved":"2004-01-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760781","names":[{"lang":"en","v":"SPARK BRIGHT LIMITED"},{"lang":"hk","v":"悅禧有限公司"}],"company_since":"2001-06-20","company_dissolved":"2006-11-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760706","names":[{"lang":"en","v":"SPARK GLORY LIMITED"},{"lang":"hk","v":"祥禧有限公司"}],"company_since":"2001-06-20","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"760654","names":[{"lang":"en","v":"POLYWISE INVESTMENT MANAGEMENT LIMITED"},{"lang":"hk","v":"普傑投資管理有限公司"}],"company_since":"2001-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"760707","names":[{"lang":"en","v":"SPEED ASIAN LIMITED"},{"lang":"hk","v":"時速有限公司"}],"company_since":"2001-06-20","company_dissolved":"2002-06-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"760777","names":[{"lang":"en","v":"SPEEDY POWER LIMITED (d2004-11-19)"},{"lang":"hk","v":"訊速有限公司"}],"company_since":"2001-06-20","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"760873","names":[{"lang":"en","v":"READERS NEWS BY UNIONS NEWS LIMITED"}],"company_since":"2001-06-20","company_dissolved":"2003-03-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"760779","names":[{"lang":"en","v":"TECH SOLUTIONS LIMITED (d2015-07-17)"},{"lang":"hk","v":"致宏物流有限公司"}],"company_since":"2001-06-20","company_dissolved":"2015-07-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"760689","names":[{"lang":"en","v":"WELLUCK DEVELOPMENT LIMITED (d2006-11-03)"},{"lang":"hk","v":"卓弘發展有限公司"}],"company_since":"2001-06-20","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
