{"tax_id":"759044","names":[{"lang":"en","v":"CHINA COMPLANT DEVELOPMENT (H.K.) LIMITED"},{"lang":"hk","v":"中成企業(香港)有限公司"}],"company_since":"2001-06-04","company_dissolved":"2016-01-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"759013","names":[{"lang":"en","v":"CHINA NAIBAO HK SHOES INDUSTRY GROUP LIMITED"},{"lang":"hk","v":"中國耐寶香港鞋業集團有限公司"}],"company_since":"2001-06-04","company_dissolved":"2006-10-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"758927","names":[{"lang":"en","v":"COE &amp; ASSOCIATES DESIGN AND ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"高爾設計工程有限公司"}],"company_since":"2001-06-04","company_dissolved":"2007-08-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"758901","names":[{"lang":"en","v":"DESON PROPERTY MANAGEMENT LIMITED"},{"lang":"hk","v":"迪臣物業管理有限公司"}],"company_since":"2001-06-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"758916","names":[{"lang":"en","v":"GOLD NOBLEMAN DEVELOPMENT LIMITED"},{"lang":"hk","v":"金雅發展有限公司"}],"company_since":"2001-06-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"758896","names":[{"lang":"en","v":"HONG KONG MINHUI INTERNATIONAL TRADING COMPANY LIMITED"},{"lang":"hk","v":"香港民暉國際貿易有限公司"}],"company_since":"2001-06-04","company_dissolved":"2002-12-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"758989","names":[{"lang":"en","v":"ICT INTERNATIONAL CIRCUIT TEST COMPANY LIMITED"},{"lang":"hk","v":"國聯電路有限公司"}],"company_since":"2001-06-04","company_dissolved":"2010-06-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"759001","names":[{"lang":"en","v":"INVESTORS DEVELOPMENT LIMITED"},{"lang":"hk","v":"名力發展有限公司"}],"company_since":"2001-06-04","company_dissolved":"2007-02-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"758926","names":[{"lang":"en","v":"HOP YIK CONSTRUCTION (H.K.) LIMITED"},{"lang":"hk","v":"合益建築(香港)有限公司"}],"company_since":"2001-06-04","company_dissolved":"2005-01-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"758941","names":[{"lang":"en","v":"KS-SYSTEMS (HONG KONG) LIMITED"},{"lang":"hk","v":"佳思系統(香港)有限公司"}],"company_since":"2001-06-04","company_dissolved":"2012-07-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"758899","names":[{"lang":"en","v":"SHARP HERO INTERNATIONAL LIMITED"},{"lang":"hk","v":"成鋒國際有限公司"}],"company_since":"2001-06-04","company_dissolved":"2015-06-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"758933","names":[{"lang":"en","v":"STP PAPER PRODUCT AND PRINTING COMPANY LIMITED"},{"lang":"hk","v":"成泰紙品印刷有限公司"}],"company_since":"2001-06-04","company_dissolved":"2009-10-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"758920","names":[{"lang":"en","v":"SUPER BRILLIANT (FAR EAST) LIMITED"},{"lang":"hk","v":"卓越(遠東)有限公司"}],"company_since":"2001-06-04","company_dissolved":"2006-10-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"758980","names":[{"lang":"en","v":"RICH ASIA BUILDING EQUIPMENTS &amp; TRADING COMPANY LIMITED"},{"lang":"hk","v":"裕亞建材貿易有限公司"}],"company_since":"2001-06-04","company_dissolved":"2007-10-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"758924","names":[{"lang":"en","v":"TOURIANSE INTERNATIONAL LIMITED"}],"company_since":"2001-06-04","company_dissolved":"2008-11-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"758977","names":[{"lang":"en","v":"WINDBEND DEVELOPMENT LIMITED (d2011-06-24)"},{"lang":"hk","v":"益濱發展有限公司"}],"company_since":"2001-06-04","company_dissolved":"2011-06-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758923","names":[{"lang":"en","v":"WISE TECH ENGINEERING LIMITED"},{"lang":"hk","v":"韋德工程有限公司"}],"company_since":"2001-06-04","company_dissolved":"2007-10-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"759031","names":[{"lang":"en","v":"YUANLONG (HONG KONG) INVESTMENT DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"元隆(香港)投資發展有限公司"}],"company_since":"2001-06-04","company_dissolved":"2006-10-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"759026","names":[{"lang":"en","v":"CUP LIMITED (d2009-05-29)"}],"company_since":"2001-06-04","company_dissolved":"2009-05-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"759020","names":[{"lang":"en","v":"EAST POINT MACHINERY EQUIPMENT COMPANY LIMITED"},{"lang":"hk","v":"衡東機械設備有限公司"}],"company_since":"2001-06-04","company_dissolved":"2019-02-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"759033","names":[{"lang":"en","v":"J D COMPANY LIMITED"},{"lang":"hk","v":"精大有限公司"}],"company_since":"2001-06-04","company_dissolved":"2009-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"758941","names":[{"lang":"en","v":"KS-SYSTEMS (HONG KONG) LIMITED"},{"lang":"hk","v":"佳思系統(香港)有限公司"}],"company_since":"2001-06-04","company_dissolved":"2012-07-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758947","names":[{"lang":"en","v":"KSCC LIMITED (d2009-12-24)"}],"company_since":"2001-06-04","company_dissolved":"2009-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758949","names":[{"lang":"en","v":"L-ZONE ENTERPRISE LIMITED"}],"company_since":"2001-06-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"759028","names":[{"lang":"en","v":"LAP TACK SUN TOYS CO., LIMITED"},{"lang":"hk","v":"立德生玩具有限公司"}],"company_since":"2001-06-04","company_dissolved":"2015-12-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"759001","names":[{"lang":"en","v":"INVESTORS DEVELOPMENT LIMITED"},{"lang":"hk","v":"名力發展有限公司"}],"company_since":"2001-06-04","company_dissolved":"2007-02-16","company_type_txt":"Private, ltd by shares"},
{"tax_id":"758967","names":[{"lang":"en","v":"MST PETROLEUM INTERNATIONAL GROUP LIMITED"},{"lang":"hk","v":"埃姆思特石油天然氣國際集團有限公司"}],"company_since":"2001-06-04","company_dissolved":"2008-11-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758919","names":[{"lang":"en","v":"MULTI RESOURCES INDUSTRIAL LIMITED"},{"lang":"hk","v":"廣進實業有限公司"}],"company_since":"2001-06-04","company_dissolved":"2003-01-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758975","names":[{"lang":"en","v":"MUNTERS (HK) LIMITED"}],"company_since":"2001-06-04","company_dissolved":"2007-10-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758945","names":[{"lang":"en","v":"ONWELL (H.K.) LIMITED (d2008-12-19)"},{"lang":"hk","v":"明和(香港)有限公司"}],"company_since":"2001-06-04","company_dissolved":"2008-12-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758946","names":[{"lang":"en","v":"ONWELL INDUSTRIAL LIMITED (d2012-07-27)"},{"lang":"hk","v":"安偉實業有限公司"}],"company_since":"2001-06-04","company_dissolved":"2012-07-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758939","names":[{"lang":"en","v":"ORIENTAL TRANSPORTATION (H.K.) COMPANY LIMITED"},{"lang":"hk","v":"東方貨運有限公司"}],"company_since":"2001-06-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"759014","names":[{"lang":"en","v":"IGNITE CREATIVE LIMITED"},{"lang":"hk","v":"燃點創念有限公司"}],"company_since":"2001-06-04","company_dissolved":"2008-11-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"759030","names":[{"lang":"en","v":"PACIFIC INTERNATIONAL GROUP LIMITED (d2006-09-29)"},{"lang":"hk","v":"利太集團有限公司"}],"company_since":"2001-06-04","company_dissolved":"2006-09-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758972","names":[{"lang":"en","v":"PEI YING EDUCATIONAL INSTITUTION LIMITED"},{"lang":"hk","v":"培英教育機構有限公司"}],"company_since":"2001-06-04","company_dissolved":"2012-07-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758896","names":[{"lang":"en","v":"HONG KONG MINHUI INTERNATIONAL TRADING COMPANY LIMITED"},{"lang":"hk","v":"香港民暉國際貿易有限公司"}],"company_since":"2001-06-04","company_dissolved":"2002-12-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758987","names":[{"lang":"en","v":"PHOENIX NAVIGATION CORPORATION LIMITED"}],"company_since":"2001-06-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"759048","names":[{"lang":"en","v":"PR EVENTS LIMITED"}],"company_since":"2001-06-04","company_dissolved":"2006-10-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758953","names":[{"lang":"en","v":"PROACTIVE ACT CONSULTANTS LIMITED"},{"lang":"hk","v":"銳策顧問有限公司"}],"company_since":"2001-06-04","company_dissolved":"2002-10-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"759019","names":[{"lang":"en","v":"Probest Wireless Technology Limited"},{"lang":"hk","v":"保仕德無綫科技有限公司"}],"company_since":"2001-06-04","company_dissolved":"2016-11-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758905","names":[{"lang":"en","v":"INFINITY LOGISTICS INTERNATIONAL CO., LIMITED"},{"lang":"hk","v":"華盛國際貨運有限公司"}],"company_since":"2001-06-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758899","names":[{"lang":"en","v":"SHARP HERO INTERNATIONAL LIMITED"},{"lang":"hk","v":"成鋒國際有限公司"}],"company_since":"2001-06-04","company_dissolved":"2015-06-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758990","names":[{"lang":"en","v":"INT'L FAMOUS BRAND (H.K.) AGENT SALE PLAN LIMITED"},{"lang":"hk","v":"國際名牌(香港)代理營銷策劃有限公司"}],"company_since":"2001-06-04","company_dissolved":"2007-10-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758971","names":[{"lang":"en","v":"SINO LEGEND APPAREL LIMITED"},{"lang":"hk","v":"華駿製衣有限公司"}],"company_since":"2001-06-04","company_dissolved":"2019-03-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758969","names":[{"lang":"en","v":"SINO UJE LIMITED"}],"company_since":"2001-06-04","company_dissolved":"2015-06-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"759039","names":[{"lang":"en","v":"ITALY AN TONIO PRODI LIMITED"},{"lang":"hk","v":"意大利安東尼奧，普羅帝有限公司"}],"company_since":"2001-06-04","company_dissolved":"2006-10-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758898","names":[{"lang":"en","v":"STAND BRIGHT DEVELOPMENT LIMITED"},{"lang":"hk","v":"建光發展有限公司"}],"company_since":"2001-06-04","company_dissolved":"2020-09-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758933","names":[{"lang":"en","v":"STP PAPER PRODUCT AND PRINTING COMPANY LIMITED"},{"lang":"hk","v":"成泰紙品印刷有限公司"}],"company_since":"2001-06-04","company_dissolved":"2009-10-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758954","names":[{"lang":"en","v":"JA HO JA (HK) TECHNOLOGY DEVELOPMENT LIMITED"},{"lang":"hk","v":"佳和嘉(香港)科技發展有限公司"}],"company_since":"2001-06-04","company_dissolved":"2013-08-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758920","names":[{"lang":"en","v":"SUPER BRILLIANT (FAR EAST) LIMITED"},{"lang":"hk","v":"卓越(遠東)有限公司"}],"company_since":"2001-06-04","company_dissolved":"2006-10-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758930","names":[{"lang":"en","v":"SWISS ROAMER COMPANY LIMITED"},{"lang":"hk","v":"瑞羅國際有限公司"}],"company_since":"2001-06-04","company_dissolved":"2009-03-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758982","names":[{"lang":"en","v":"SZE CHEONG (HK) ENGINEERING LIMITED"},{"lang":"hk","v":"時昌(香港)工程有限公司"}],"company_since":"2001-06-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758907","names":[{"lang":"en","v":"JADE NGAI DECORATION DESIGN ENGINEERING LIMITED"},{"lang":"hk","v":"精藝裝飾設計工程有限公司"}],"company_since":"2001-06-04","company_dissolved":"2004-04-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758968","names":[{"lang":"en","v":"TAK LEE WAI KEE COMPANY LIMITED"},{"lang":"hk","v":"德利維記有限公司"}],"company_since":"2001-06-04","company_dissolved":"2008-11-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"759015","names":[{"lang":"en","v":"THOMAS HARDWARE COMPANY LIMITED"},{"lang":"hk","v":"虹漢實業有限公司"}],"company_since":"2001-06-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758998","names":[{"lang":"en","v":"TIDE INTERNATIONAL (H.K.) COMPANY LIMITED"},{"lang":"hk","v":"泰達國際(香港)有限公司"}],"company_since":"2001-06-04","company_dissolved":"2006-10-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758922","names":[{"lang":"en","v":"TEAMWORKS LIMITED (HK)"},{"lang":"hk","v":"協邦建築工程有限公司"}],"company_since":"2001-06-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758944","names":[{"lang":"en","v":"TOPWORLD ENTERPRISES LIMITED (d2003-09-26)"},{"lang":"hk","v":"達匯企業有限公司"}],"company_since":"2001-06-04","company_dissolved":"2003-09-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758924","names":[{"lang":"en","v":"TOURIANSE INTERNATIONAL LIMITED"}],"company_since":"2001-06-04","company_dissolved":"2008-11-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"759042","names":[{"lang":"en","v":"VC SERVICES LIMITED"},{"lang":"hk","v":"滙盈服務有限公司"}],"company_since":"2001-06-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"758935","names":[{"lang":"en","v":"WORLD BRANDS MANUFACTORY COMPANY LIMITED"},{"lang":"hk","v":"偉品商標製造廠有限公司"}],"company_since":"2001-06-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758940","names":[{"lang":"en","v":"XECON TECHNOLOGY LIMITED"},{"lang":"hk","v":"力拓科技有限公司"}],"company_since":"2001-06-04","company_dissolved":"2009-06-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758893","names":[{"lang":"en","v":"WOODPECKER GROUP LIMITED"},{"lang":"hk","v":"啄木鳥(集團)有限公司"}],"company_since":"2001-06-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"759007","names":[{"lang":"en","v":"MAC LOOK LIMITED"},{"lang":"hk","v":"麗麗設計有限公司"}],"company_since":"2001-06-04","company_dissolved":"2014-06-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758978","names":[{"lang":"en","v":"YICK CHEONG PETROTECH SERVICES (HK) LIMITED"},{"lang":"hk","v":"益昌石油技術服務(香港)有限公司"}],"company_since":"2001-06-04","company_dissolved":"2010-09-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"759031","names":[{"lang":"en","v":"YUANLONG (HONG KONG) INVESTMENT DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"元隆(香港)投資發展有限公司"}],"company_since":"2001-06-04","company_dissolved":"2006-10-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758932","names":[{"lang":"en","v":"Z'S HEALTH AGENCY LIMITED"}],"company_since":"2001-06-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"759017","names":[{"lang":"en","v":"MEI I COMPANY LIMITED"},{"lang":"hk","v":"美毅貿易有限公司"}],"company_since":"2001-06-04","company_dissolved":"2006-10-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"758981","names":[{"lang":"en","v":"ZH-NET ENTERPRISE LIMITED"},{"lang":"hk","v":"海網企業有限公司"}],"company_since":"2001-06-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
