undefined,
{"tax_id":"544278","names":[{"lang":"en","v":"CHIEF ELECTRONICS ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"熾富電子工程有限公司"}],"company_since":"1996-04-11","company_dissolved":"2009-10-23","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544487","names":[{"lang":"en","v":"CHINA BEST INTERNATIONAL (GROUP) LIMITED"},{"lang":"hk","v":"華茂國際(集團)有限公司"}],"company_since":"1996-04-11","company_dissolved":"2017-10-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544287","names":[{"lang":"en","v":"CHINA RESOURCES (VIETNAM) LIMITED"},{"lang":"hk","v":"華潤(越南)有限公司"}],"company_since":"1996-04-11","company_dissolved":"2001-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544362","names":[{"lang":"en","v":"CHINA WATERPROOF ENGINEERING LIMITED"},{"lang":"hk","v":"中國防水工程有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544394","names":[{"lang":"en","v":"CHUN FOOK JEWELLERY LIMITED"},{"lang":"hk","v":"俊福珠寶有限公司"}],"company_since":"1996-04-11","company_dissolved":"2000-12-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544296","names":[{"lang":"en","v":"COME FAST KITCHEN COMPANY LIMITED"},{"lang":"hk","v":"金發小廚有限公司"}],"company_since":"1996-04-11","company_dissolved":"2004-05-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544326","names":[{"lang":"en","v":"CRYSTAL TEAM LIMITED (HK)"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544332","names":[{"lang":"en","v":"DEEP BLUE COMPANY LIMITED"}],"company_since":"1996-04-11","company_dissolved":"2019-09-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544372","names":[{"lang":"en","v":"E TECHNOLOGIES LIMITED"},{"lang":"hk","v":"寰宇科技有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544481","names":[{"lang":"en","v":"EAST KIND CONSULTANTS LIMITED"},{"lang":"hk","v":"益佳顧問有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544482","names":[{"lang":"en","v":"EASTBO (ASIA) LIMITED"},{"lang":"hk","v":"怡寶(亞洲)有限公司"}],"company_since":"1996-04-11","company_dissolved":"1999-07-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544363","names":[{"lang":"en","v":"EATES ELECTRONIC CO., LIMITED"},{"lang":"hk","v":"依達時電子有限公司"}],"company_since":"1996-04-11","company_dissolved":"2005-05-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544255","names":[{"lang":"en","v":"ELITE ORIENTAL INTERNATIONAL LIMITED"},{"lang":"hk","v":"旭東國際有限公司"}],"company_since":"1996-04-11","company_dissolved":"2003-01-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544289","names":[{"lang":"en","v":"EASTERN (HONG KONG) FILM PRODUCTION COMPANY LIMITED (THE)"},{"lang":"hk","v":"正東(香港)電影有限公司"}],"company_since":"1996-04-11","company_dissolved":"2019-03-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544355","names":[{"lang":"en","v":"ESSENCE BEAUTY COMPANY LIMITED"},{"lang":"hk","v":"蕙珊美容有限公司"}],"company_since":"1996-04-11","company_dissolved":"2002-11-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544543","names":[{"lang":"en","v":"ETERNAL RESOURCES TRADING LIMITED"},{"lang":"hk","v":"利昌隆貿易有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544269","names":[{"lang":"en","v":"EVER PROSPERITY COMPANY LIMITED (d2001-02-02)"},{"lang":"hk","v":"善研有限公司"}],"company_since":"1996-04-11","company_dissolved":"2001-02-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544271","names":[{"lang":"en","v":"EVER ELEC. &amp; PORCELAIN INDUSTRY (HK) LIMITED"},{"lang":"hk","v":"閩展電瓷電器實業有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544458","names":[{"lang":"en","v":"EVERANGE INTERNATIONAL LIMITED"},{"lang":"hk","v":"長展國際有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544544","names":[{"lang":"en","v":"EXCEL (HONG KONG) LIMITED (d2007-09-14)"},{"lang":"hk","v":"井村卓越(香港)有限公司"}],"company_since":"1996-04-11","company_dissolved":"2007-09-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544365","names":[{"lang":"en","v":"EXESEL LIMITED"}],"company_since":"1996-04-11","company_dissolved":"2004-10-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544382","names":[{"lang":"en","v":"FAMEWAY GARMENTS LIMITED"},{"lang":"hk","v":"豐美製衣有限公司"}],"company_since":"1996-04-11","company_dissolved":"2003-05-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544472","names":[{"lang":"en","v":"FAST RICH TRADING LIMITED"},{"lang":"hk","v":"發榮貿易有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544366","names":[{"lang":"en","v":"FINE GOOD LIMITED"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544328","names":[{"lang":"en","v":"FLYING EAGLE ASIA LIMITED"},{"lang":"hk","v":"飛鷹亞洲有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544327","names":[{"lang":"en","v":"FLYING EAGLE HOLDINGS LIMITED (d1999-03-12)"},{"lang":"hk","v":"飛鷹集團有限公司"}],"company_since":"1996-04-11","company_dissolved":"1999-03-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544285","names":[{"lang":"en","v":"FOREVER STATE TRADING LIMITED"},{"lang":"hk","v":"浤洲貿易有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544447","names":[{"lang":"en","v":"FORTUNE TASK INTERNATIONAL LIMITED"},{"lang":"hk","v":"豐新國際有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544442","names":[{"lang":"en","v":"GAINOR DEVELOPMENTS LIMITED"},{"lang":"hk","v":"基譽發展有限公司"}],"company_since":"1996-04-11","company_dissolved":"2001-07-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544358","names":[{"lang":"en","v":"GENIUS FAIR DEVELOPMENT LIMITED"},{"lang":"hk","v":"捷洋發展有限公司"}],"company_since":"1996-04-11","company_dissolved":"2005-04-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544398","names":[{"lang":"en","v":"GENIUS KING LIMITED"},{"lang":"hk","v":"尊勝有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544498","names":[{"lang":"en","v":"GIANT HARBOUR INVESTMENT LIMITED"},{"lang":"hk","v":"港霸投資有限公司"}],"company_since":"1996-04-11","company_dissolved":"2013-06-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544547","names":[{"lang":"en","v":"CHUNG FOO GARMENT LIMITED"},{"lang":"hk","v":"中富製衣有限公司"}],"company_since":"1996-04-11","company_dissolved":"2004-01-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544557","names":[{"lang":"en","v":"CONCEPT PROMOTION LIMITED"}],"company_since":"1996-04-11","company_dissolved":"2009-09-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544461","names":[{"lang":"en","v":"GOLD CORE INTERNATIONAL LIMITED"},{"lang":"hk","v":"金理國際有限公司"}],"company_since":"1996-04-11","company_dissolved":"2003-08-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"544495","names":[{"lang":"en","v":"GOOD CAREER FAR EAST LIMITED"},{"lang":"hk","v":"利業遠東有限公司"}],"company_since":"1996-04-11","company_dissolved":"1998-10-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544418","names":[{"lang":"en","v":"GRAND BRIGHT HOLDINGS LIMITED"},{"lang":"hk","v":"宏耀集團有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544324","names":[{"lang":"en","v":"ERGO LIMITED (d2005-10-07)"}],"company_since":"1996-04-11","company_dissolved":"2005-10-07","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544393","names":[{"lang":"en","v":"GREAT CASTLE INTERNATIONAL INDUSTRIES COMPANY LIMITED"},{"lang":"hk","v":"華榮國際實業有限公司"}],"company_since":"1996-04-11","company_dissolved":"2002-05-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544513","names":[{"lang":"en","v":"GREAT SUCCESS INTERNATIONAL MANAGEMENT LIMITED"},{"lang":"hk","v":"偉成國際管理有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544322","names":[{"lang":"en","v":"ETSUKO HONG KONG INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"悅子香港有限公司"}],"company_since":"1996-04-11","company_dissolved":"2003-07-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544370","names":[{"lang":"en","v":"GUIYANG DAGAO REAL ESTATE COMPANY LIMITED"},{"lang":"hk","v":"貴陽達高房地產有限公司"}],"company_since":"1996-04-11","company_dissolved":"2004-05-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544475","names":[{"lang":"en","v":"H.S.D.P. CORPORATION LIMITED"}],"company_since":"1996-04-11","company_dissolved":"2001-01-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544483","names":[{"lang":"en","v":"EXCELLENT INTERNATIONAL TECHNOLOGY LIMITED"},{"lang":"hk","v":"美倫國際科技有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544528","names":[{"lang":"en","v":"HANWAY FAR EAST DEVELOPMENT LIMITED"},{"lang":"hk","v":"恆威遠東發展有限公司"}],"company_since":"1996-04-11","company_dissolved":"2016-08-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"544478","names":[{"lang":"en","v":"HAPPY TRADE GARMENT FACTORY LIMITED"},{"lang":"hk","v":"開洋製衣廠有限公司"}],"company_since":"1996-04-11","company_dissolved":"2005-06-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544525","names":[{"lang":"en","v":"HAR INTERNATIONAL LIMITED"},{"lang":"hk","v":"宏駿國際拓展有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544429","names":[{"lang":"en","v":"HARMONY PROPERTY CONSULTANTS LIMITED"},{"lang":"hk","v":"三和物業顧問有限公司"}],"company_since":"1996-04-11","company_dissolved":"2004-05-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544497","names":[{"lang":"en","v":"FAMOUS GLORY GARMENT LIMITED"},{"lang":"hk","v":"威榮製衣有限公司"}],"company_since":"1996-04-11","company_dissolved":"2002-07-26","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544438","names":[{"lang":"en","v":"HEADSTART LEARNING CENTRE LIMITED"},{"lang":"hk","v":"智達學習中心有限公司"}],"company_since":"1996-04-11","company_dissolved":"2002-11-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544343","names":[{"lang":"en","v":"HONG KONG CHINA TOURISM LIMITED"},{"lang":"hk","v":"香港中國旅遊有限公司"}],"company_since":"1996-04-11","company_dissolved":"2010-11-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544347","names":[{"lang":"en","v":"FIRST REGENT INDUSTRIAL LIMITED"},{"lang":"hk","v":"偉晉實業有限公司"}],"company_since":"1996-04-11","company_dissolved":"2004-10-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544375","names":[{"lang":"en","v":"HONG KONG HUI YUAN FOOD AND DRINK COMPANY LIMITED"},{"lang":"hk","v":"香港匯源食品飲料有限公司"}],"company_since":"1996-04-11","company_dissolved":"2000-08-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544539","names":[{"lang":"en","v":"HONG KONG LEADER INDUSTRY AND COMMERCE LIMITED"},{"lang":"hk","v":"香港立丹有限公司"}],"company_since":"1996-04-11","company_dissolved":"2000-08-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544309","names":[{"lang":"en","v":"HONG YEE (H.K.) LIMITED"},{"lang":"hk","v":"鴻意(香港)有限公司"}],"company_since":"1996-04-11","company_dissolved":"2005-12-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544537","names":[{"lang":"en","v":"FORTUNE PERFECT INTERNATIONAL LIMITED"},{"lang":"hk","v":"祥栢國際有限公司"}],"company_since":"1996-04-11","company_dissolved":"2001-08-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544441","names":[{"lang":"en","v":"HONOUR POWER INVESTMENTS LIMITED"},{"lang":"hk","v":"浩民投資有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544434","names":[{"lang":"en","v":"HUA KANG TANG COMPANY LIMITED"},{"lang":"hk","v":"華康堂有限公司"}],"company_since":"1996-04-11","company_dissolved":"2003-10-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544456","names":[{"lang":"en","v":"FREIGHT EXPERT LIMITED"},{"lang":"hk","v":"富博航運有限公司"}],"company_since":"1996-04-11","company_dissolved":"2008-10-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544426","names":[{"lang":"en","v":"INTELLICORP LIMITED (HK)"},{"lang":"hk","v":"智盈有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544400","names":[{"lang":"en","v":"GENTLE RIGHT LIMITED"},{"lang":"hk","v":"展緯有限公司"}],"company_since":"1996-04-11","company_dissolved":"2004-05-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544386","names":[{"lang":"en","v":"GLOBAL PARTNER TRADE LIMITED"},{"lang":"hk","v":"高寶洋行有限公司"}],"company_since":"1996-04-11","company_dissolved":"2018-08-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544284","names":[{"lang":"en","v":"J.S.C. INVESTMENT LIMITED"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544306","names":[{"lang":"en","v":"GOLD FIELD TEXTURE LIMITED"},{"lang":"hk","v":"金田織造有限公司"}],"company_since":"1996-04-11","company_dissolved":"2001-06-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544552","names":[{"lang":"en","v":"JACOS ENTERPRISES LIMITED"},{"lang":"hk","v":"榮洋企業有限公司"}],"company_since":"1996-04-11","company_dissolved":"2003-04-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544435","names":[{"lang":"en","v":"JOY-WAY INTERNATIONAL GROUP LIMITED"},{"lang":"hk","v":"中惠國際集團有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"544508","names":[{"lang":"en","v":"GOLDSTAGE INTERNATIONAL LIMITED"},{"lang":"hk","v":"金台國際有限公司"}],"company_since":"1996-04-11","company_dissolved":"2002-11-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544252","names":[{"lang":"en","v":"KAI YIP INVESTMENT LIMITED"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544453","names":[{"lang":"en","v":"KANFIL ENTERPRISES COMPANY LIMITED"},{"lang":"hk","v":"金豐實發有限公司"}],"company_since":"1996-04-11","company_dissolved":"2005-04-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544480","names":[{"lang":"en","v":"KEENSON PRODUCTION LIMITED"},{"lang":"hk","v":"佳順製作有限公司"}],"company_since":"1996-04-11","company_dissolved":"2006-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"544286","names":[{"lang":"en","v":"KEN FAI TRANSPORTATION CO., LIMITED"},{"lang":"hk","v":"建輝貨運有限公司"}],"company_since":"1996-04-11","company_dissolved":"2004-05-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544444","names":[{"lang":"en","v":"GRAND PACE LIMITED"},{"lang":"hk","v":"廣利和有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544462","names":[{"lang":"en","v":"GRAND RANGE INTERNATIONAL LIMITED"},{"lang":"hk","v":"廣嘉國際有限公司"}],"company_since":"1996-04-11","company_dissolved":"2002-04-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544452","names":[{"lang":"en","v":"GUANGDONG OVERSEAS (HONG KONG) CONSTRUCTIONS LIMITED"},{"lang":"hk","v":"廣東海外(香港)建設有限公司"}],"company_since":"1996-04-11","company_dissolved":"2008-09-26","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544349","names":[{"lang":"en","v":"KINGSON (H.K.) LIMITED (d2000-08-25)"},{"lang":"hk","v":"景順(香港)有限公司"}],"company_since":"1996-04-11","company_dissolved":"2000-08-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544496","names":[{"lang":"en","v":"KORNWELL INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"高華國際集團有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544369","names":[{"lang":"en","v":"ITOK MEDIA LIMITED"},{"lang":"hk","v":"盈滔媒體有限公司"}],"company_since":"1996-04-11","company_dissolved":"2015-10-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544265","names":[{"lang":"en","v":"L &amp; T COMPUTER SYSTEMS LIMITED"},{"lang":"hk","v":"利東電腦系統有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544299","names":[{"lang":"en","v":"LAM MO CHIU MEMORIAL FUND LIMITED"},{"lang":"hk","v":"林慕超紀念基金會有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"544499","names":[{"lang":"en","v":"LEADER INTERNATIONAL TECHNOLOGY LIMITED"},{"lang":"hk","v":"利達國際科技有限公司"}],"company_since":"1996-04-11","company_dissolved":"2004-05-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544356","names":[{"lang":"en","v":"HARVEST ATTITUDE LIMITED"},{"lang":"hk","v":"豐緯有限公司"}],"company_since":"1996-04-11","company_dissolved":"2013-01-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544353","names":[{"lang":"en","v":"LEATHER PLUS LIMITED (d2002-06-21)"},{"lang":"hk","v":"中瑞皮業有限公司"}],"company_since":"1996-04-11","company_dissolved":"2002-06-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544294","names":[{"lang":"en","v":"LUCKY LAND ELECTRONICS LIMITED"},{"lang":"hk","v":"利隆電子有限公司"}],"company_since":"1996-04-11","company_dissolved":"2013-05-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544414","names":[{"lang":"en","v":"MABLETHORPE LIMITED (d2012-07-13)"}],"company_since":"1996-04-11","company_dissolved":"2012-07-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544526","names":[{"lang":"en","v":"HONG KONG SHENG HE EMBROIDERY COMPANY LIMITED"},{"lang":"hk","v":"香港勝和綉品有限公司"}],"company_since":"1996-04-11","company_dissolved":"2005-04-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544298","names":[{"lang":"en","v":"HONGKONG GOLDEN CARD SYSTEM ENGINEERING COMPANY LIMITED"}],"company_since":"1996-04-11","company_dissolved":"2003-02-07","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544396","names":[{"lang":"en","v":"MANY CHAIN LIMITED"},{"lang":"hk","v":"萬利晉有限公司"}],"company_since":"1996-04-11","company_dissolved":"2007-09-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544266","names":[{"lang":"en","v":"MANY JOY LIMITED"},{"lang":"hk","v":"萬利悅有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544257","names":[{"lang":"en","v":"MEDIA CONSULTANTS LIMITED (d2012-05-11)"},{"lang":"hk","v":"萬達顧問有限公司"}],"company_since":"1996-04-11","company_dissolved":"2012-05-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544527","names":[{"lang":"en","v":"HUGE WING INVESTMENT LIMITED"},{"lang":"hk","v":"巨展投資有限公司"}],"company_since":"1996-04-11","company_dissolved":"2017-05-05","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544391","names":[{"lang":"en","v":"MEGA YEAR LIMITED"},{"lang":"hk","v":"萬利年有限公司"}],"company_since":"1996-04-11","company_dissolved":"2014-06-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544346","names":[{"lang":"en","v":"MIKI FASHION WHOLESALE COMPANY LIMITED"},{"lang":"hk","v":"美琪時裝批發有限公司"}],"company_since":"1996-04-11","company_dissolved":"2009-05-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544262","names":[{"lang":"en","v":"MILLIKEN INVESTMENT LIMITED"},{"lang":"hk","v":"萬建投資有限公司"}],"company_since":"1996-04-11","company_dissolved":"2005-04-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"544381","names":[{"lang":"en","v":"INTERNATIONAL TRADE LIMITED (d2001-10-19)"}],"company_since":"1996-04-11","company_dissolved":"2001-10-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544373","names":[{"lang":"en","v":"INVENSYS FAR EAST LIMITED"}],"company_since":"1996-04-11","company_dissolved":"2013-12-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544258","names":[{"lang":"en","v":"MODERN CAPITAL TRADING LIMITED"},{"lang":"hk","v":"新都貿易有限公司"}],"company_since":"1996-04-11","company_dissolved":"2004-05-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544254","names":[{"lang":"en","v":"IRIS FASHION (H.K.) LIMITED"},{"lang":"hk","v":"愛麗絲時裝(香港)有限公司"}],"company_since":"1996-04-11","company_dissolved":"2004-05-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544464","names":[{"lang":"en","v":"MULTILINE INTERNATIONAL LIMITED (d2010-01-19)"},{"lang":"hk","v":"貿益國際有限公司"}],"company_since":"1996-04-11","company_dissolved":"2010-01-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544390","names":[{"lang":"en","v":"JET YORK INTERNATIONAL LIMITED"},{"lang":"hk","v":"捷洋國際有限公司"}],"company_since":"1996-04-11","company_dissolved":"2020-03-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544477","names":[{"lang":"en","v":"NEW LINE EDUCATIONAL TOYS LIMITED"},{"lang":"hk","v":"智慧王有限公司"}],"company_since":"1996-04-11","company_dissolved":"2015-06-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544554","names":[{"lang":"en","v":"NEW SHARP PROPERTIES LIMITED"},{"lang":"hk","v":"永健置業有限公司"}],"company_since":"1996-04-11","company_dissolved":"2002-07-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544359","names":[{"lang":"en","v":"NOW PROPERTY CONSULTANTS LIMITED"},{"lang":"hk","v":"置家閣地產有限公司"}],"company_since":"1996-04-11","company_dissolved":"2004-08-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544317","names":[{"lang":"en","v":"KA LEE TRADING AND DEVELOPMENT LIMITED"},{"lang":"hk","v":"嘉利貿易發展有限公司"}],"company_since":"1996-04-11","company_dissolved":"2009-01-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544502","names":[{"lang":"en","v":"KALFORD (H.K.) LIMITED"},{"lang":"hk","v":"建峰(香港)有限公司"}],"company_since":"1996-04-11","company_dissolved":"2000-05-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544279","names":[{"lang":"en","v":"ORIOLE ENGINEERING LIMITED"},{"lang":"hk","v":"奧利工程有限公司"}],"company_since":"1996-04-11","company_dissolved":"2005-04-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544379","names":[{"lang":"en","v":"PACIFIC ACE INDUSTRIAL LIMITED"},{"lang":"hk","v":"達雅實業有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544350","names":[{"lang":"en","v":"PACIFIC YORK INTERNATIONAL LIMITED"},{"lang":"hk","v":"達恩國際有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544470","names":[{"lang":"en","v":"PANRICH PROPERTY LIMITED"},{"lang":"hk","v":"博榮置業有限公司"}],"company_since":"1996-04-11","company_dissolved":"2006-04-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544432","names":[{"lang":"en","v":"KENDEX CHEMICALS CO. LIMITED"},{"lang":"hk","v":"堅德化工有限公司"}],"company_since":"1996-04-11","company_dissolved":"1999-05-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544411","names":[{"lang":"en","v":"KENOVA LIMITED (d2005-06-23)"}],"company_since":"1996-04-11","company_dissolved":"2005-06-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544310","names":[{"lang":"en","v":"PLENTYWIN INVESTMENTS COMPANY LIMITED"},{"lang":"hk","v":"寶榮發投資有限公司"}],"company_since":"1996-04-11","company_dissolved":"2015-08-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544360","names":[{"lang":"en","v":"KIN SUN FINANCE (HK) LIMITED"},{"lang":"hk","v":"建新財務(香港)有限公司"}],"company_since":"1996-04-11","company_dissolved":"2001-11-23","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544307","names":[{"lang":"en","v":"POLY LANE ENTERPRISE LIMITED"},{"lang":"hk","v":"寶利興企業有限公司"}],"company_since":"1996-04-11","company_dissolved":"2004-12-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544264","names":[{"lang":"en","v":"KING ELEGANCE LIMITED (d2005-08-19)"},{"lang":"hk","v":"建強有限公司"}],"company_since":"1996-04-11","company_dissolved":"2005-08-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544404","names":[{"lang":"en","v":"POWER PACKING (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"創力包裝(香港)有限公司"}],"company_since":"1996-04-11","company_dissolved":"2014-07-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"544292","names":[{"lang":"en","v":"KWONG KEE RESTAURANT LIMITED"},{"lang":"hk","v":"光記飯店有限公司"}],"company_since":"1996-04-11","company_dissolved":"2001-06-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544385","names":[{"lang":"en","v":"PRODUCTION NO.8 LIMITED"},{"lang":"hk","v":"第捌廠制作有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544492","names":[{"lang":"en","v":"PROFIT GUARD MANAGEMENT LIMITED"},{"lang":"hk","v":"利保管理有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544408","names":[{"lang":"en","v":"PROTECT BUILDING MAINTENANCE LIMITED"},{"lang":"hk","v":"寶德物業保養有限公司"}],"company_since":"1996-04-11","company_dissolved":"2000-09-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544331","names":[{"lang":"en","v":"LANFIT LIMITED"},{"lang":"hk","v":"凌發有限公司"}],"company_since":"1996-04-11","company_dissolved":"2004-05-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544463","names":[{"lang":"en","v":"LOYALUXE INTERNATIONAL LIMITED"},{"lang":"hk","v":"樂誠國際有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544338","names":[{"lang":"en","v":"REGENCY DYNASTY TRADERS LIMITED"},{"lang":"hk","v":"承業貿易有限公司"}],"company_since":"1996-04-11","company_dissolved":"2002-09-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544524","names":[{"lang":"en","v":"LUCKY FORTUNE (HONG KONG) LIMITED"},{"lang":"hk","v":"祥豐(香港)有限公司"}],"company_since":"1996-04-11","company_dissolved":"2004-05-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544416","names":[{"lang":"en","v":"M. T. COMPANY LIMITED"}],"company_since":"1996-04-11","company_dissolved":"2002-03-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544337","names":[{"lang":"en","v":"REGENCY TREASURE TRADERS LIMITED"},{"lang":"hk","v":"承富貿易有限公司"}],"company_since":"1996-04-11","company_dissolved":"2006-08-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544428","names":[{"lang":"en","v":"RICH ETERNAL LIMITED (d2002-03-28)"},{"lang":"hk","v":"裕宜有限公司"}],"company_since":"1996-04-11","company_dissolved":"2002-03-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544268","names":[{"lang":"en","v":"MAN FUNG ELECTRONIC WORLD COMPANY LIMITED"},{"lang":"hk","v":"萬豐電子世界有限公司"}],"company_since":"1996-04-11","company_dissolved":"2003-07-11","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544504","names":[{"lang":"en","v":"RICH FAST (ASIA) LIMITED"},{"lang":"hk","v":"成發(亞洲)有限公司"}],"company_since":"1996-04-11","company_dissolved":"2012-07-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544399","names":[{"lang":"en","v":"RICH EXPERT LIMITED (d1999-05-14)"},{"lang":"hk","v":"富經有限公司"}],"company_since":"1996-04-11","company_dissolved":"1999-05-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544433","names":[{"lang":"en","v":"RICH GLAMOUR INTERIORS LIMITED"},{"lang":"hk","v":"香港華瑞裝飾有限公司"}],"company_since":"1996-04-11","company_dissolved":"2002-11-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544466","names":[{"lang":"en","v":"RICHNESS INTERNATIONAL LIMITED"},{"lang":"hk","v":"發勝國際有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544415","names":[{"lang":"en","v":"MEGA TRAVEL LIMITED (d2003-04-25)"},{"lang":"hk","v":"展旅有限公司"}],"company_since":"1996-04-11","company_dissolved":"2003-04-25","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544330","names":[{"lang":"en","v":"RITZWAY POWER ENTERPRISES LIMITED"},{"lang":"hk","v":"勵寶企業有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544259","names":[{"lang":"en","v":"SANGFAI ELECTRICAL MANUFACTURE LIMITED"},{"lang":"hk","v":"生輝電器制品有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544488","names":[{"lang":"en","v":"SANWIN CONSULTANTS LIMITED (d2004-08-13)"},{"lang":"hk","v":"順榮顧問有限公司"}],"company_since":"1996-04-11","company_dissolved":"2004-08-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544471","names":[{"lang":"en","v":"MULTI-TASK INTERNATIONAL LIMITED"},{"lang":"hk","v":"貿通國際有限公司"}],"company_since":"1996-04-11","company_dissolved":"2006-10-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544297","names":[{"lang":"en","v":"SEASONS SEASONING LIMITED"},{"lang":"hk","v":"四季調味品有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544551","names":[{"lang":"en","v":"SHAREEN DEVELOPMENT LIMITED"},{"lang":"hk","v":"嘉倡發展有限公司"}],"company_since":"1996-04-11","company_dissolved":"2001-08-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544535","names":[{"lang":"en","v":"SHEEN YICK (ASIA) COMPANY LIMITED"},{"lang":"hk","v":"信益(亞洲)有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544436","names":[{"lang":"en","v":"SHEENWARD INTERNATIONAL LIMITED"},{"lang":"hk","v":"盛僑國際有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544501","names":[{"lang":"en","v":"ONTECH INTERNATIONAL TECHNOLOGY LIMITED"},{"lang":"hk","v":"安達國際科技有限公司"}],"company_since":"1996-04-11","company_dissolved":"2007-04-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544380","names":[{"lang":"en","v":"ORIENT GLORY INTERNATIONAL LIMITED (d2005-12-30)"},{"lang":"hk","v":"中信行國際有限公司"}],"company_since":"1996-04-11","company_dissolved":"2005-12-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544451","names":[{"lang":"en","v":"SHUN WOO AUDIO EQUIPMENT INTERNATIONAL LIMITED"},{"lang":"hk","v":"信和音響國際有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544302","names":[{"lang":"en","v":"P F L INDUSTRIES LIMITED (d2004-12-31)"},{"lang":"hk","v":"保膚麗化工有限公司"}],"company_since":"1996-04-11","company_dissolved":"2004-12-31","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544523","names":[{"lang":"en","v":"SINO CONCORD (HONG KONG) LIMITED (d2018-11-02)"},{"lang":"hk","v":"華國(香港)有限公司"}],"company_since":"1996-04-11","company_dissolved":"2018-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544305","names":[{"lang":"en","v":"SIRIUS PACIFIC CONSULTANTS LIMITED"},{"lang":"hk","v":"宙輝有限公司"}],"company_since":"1996-04-11","company_dissolved":"2017-04-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544503","names":[{"lang":"en","v":"SMART INTERNATIONAL BUSINESS DEVELOPMENT (ASIA) LIMITED"}],"company_since":"1996-04-11","company_dissolved":"2015-06-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544505","names":[{"lang":"en","v":"SMART KEY PRODUCTION LIMITED"},{"lang":"hk","v":"寶堅製作有限公司"}],"company_since":"1996-04-11","company_dissolved":"2001-07-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"544301","names":[{"lang":"en","v":"PARKDALE LIMITED (HK)"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544277","names":[{"lang":"en","v":"PHARMACEUTICAL EQUIPMENTS ASIA TRADING LIMITED"}],"company_since":"1996-04-11","company_dissolved":"2002-11-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544333","names":[{"lang":"en","v":"SOUND FORTUNE LIMITED"},{"lang":"hk","v":"上駿有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544468","names":[{"lang":"en","v":"SPARKO (FAR EAST) LIMITED"},{"lang":"hk","v":"世嘉(遠東)有限公司"}],"company_since":"1996-04-11","company_dissolved":"2010-12-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544536","names":[{"lang":"en","v":"SPIDER AD INTERNATIONAL LIMITED"},{"lang":"hk","v":"資諸國際廣告有限公司"}],"company_since":"1996-04-11","company_dissolved":"2009-09-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544479","names":[{"lang":"en","v":"PORTWIN INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"港偉國際投資有限公司"}],"company_since":"1996-04-11","company_dissolved":"2003-03-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544291","names":[{"lang":"en","v":"SPRINGDALE HONG KONG COMPANY LIMITED"},{"lang":"hk","v":"春暉投資有限公司"}],"company_since":"1996-04-11","company_dissolved":"2009-03-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544542","names":[{"lang":"en","v":"PRIMA TRIMS LIMITED"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544274","names":[{"lang":"en","v":"SUN BIG INVESTMENT (H.K.) LIMITED"},{"lang":"hk","v":"新碧投資(香港)有限公司"}],"company_since":"1996-04-11","company_dissolved":"2004-05-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"544315","names":[{"lang":"en","v":"PROSPER ENTERPRISES LIMITED (d2014-05-16)"},{"lang":"hk","v":"古今企業有限公司"}],"company_since":"1996-04-11","company_dissolved":"2014-05-16","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544323","names":[{"lang":"en","v":"SUN SEVEN CO., LIMITED"},{"lang":"hk","v":"日富利有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544514","names":[{"lang":"en","v":"SUNSKY PHARMACEUTICAL LIMITED"},{"lang":"hk","v":"新中天藥業有限公司"}],"company_since":"1996-04-11","company_dissolved":"2005-12-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"544422","names":[{"lang":"en","v":"SUPREME GRAND LIMITED (d2010-01-22)"},{"lang":"hk","v":"順集有限公司"}],"company_since":"1996-04-11","company_dissolved":"2010-01-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544335","names":[{"lang":"en","v":"REGENCY POWER ENTERPRISES LIMITED"},{"lang":"hk","v":"晶寶企業有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544263","names":[{"lang":"en","v":"SYMBOL DESIGN CONSULTANCY &amp; CONTRACTING LIMITED"},{"lang":"hk","v":"思奧設計顧問建造有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544555","names":[{"lang":"en","v":"RICH KING PROPERTIES LIMITED (d2005-12-30)"},{"lang":"hk","v":"盈嘉置業有限公司"}],"company_since":"1996-04-11","company_dissolved":"2005-12-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544450","names":[{"lang":"en","v":"TIGER COMMUNICATIONS INTERNATIONAL LIMITED"},{"lang":"hk","v":"威猛通訊國際有限公司"}],"company_since":"1996-04-11","company_dissolved":"2010-10-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544546","names":[{"lang":"en","v":"TINIC ELECTRONIC COMPANY LIMITED"},{"lang":"hk","v":"天力電子有限公司"}],"company_since":"1996-04-11","company_dissolved":"2011-09-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"544530","names":[{"lang":"en","v":"TOMWILL INTERNATIONAL CONSULTANTS LIMITED"},{"lang":"hk","v":"東惠國際顧問有限公司"}],"company_since":"1996-04-11","company_dissolved":"2004-10-29","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544282","names":[{"lang":"en","v":"TONKA TRADING LIMITED"},{"lang":"hk","v":"通亨貿易有限公司"}],"company_since":"1996-04-11","company_dissolved":"2001-03-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544540","names":[{"lang":"en","v":"TOP HONOUR INDUSTRIAL LIMITED (d2009-09-25)"},{"lang":"hk","v":"宏信實業有限公司"}],"company_since":"1996-04-11","company_dissolved":"2009-09-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544510","names":[{"lang":"en","v":"TOP ARCH (ASIA) LIMITED"},{"lang":"hk","v":"高雅(亞洲)有限公司"}],"company_since":"1996-04-11","company_dissolved":"2004-05-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544371","names":[{"lang":"en","v":"TOP LIMITED (d2004-05-21)"}],"company_since":"1996-04-11","company_dissolved":"2004-05-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"544377","names":[{"lang":"en","v":"TOP POTENTIAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"德培發展有限公司"}],"company_since":"1996-04-11","company_dissolved":"2007-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544325","names":[{"lang":"en","v":"SELAK ENTERPRISES LIMITED"}],"company_since":"1996-04-11","company_dissolved":"2017-09-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544515","names":[{"lang":"en","v":"TOP YIELD HOLDINGS LIMITED (d2008-10-03)"},{"lang":"hk","v":"多益集團有限公司"}],"company_since":"1996-04-11","company_dissolved":"2008-10-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"544550","names":[{"lang":"en","v":"SHARICO DEVELOPMENT LIMITED"},{"lang":"hk","v":"智康發展有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544397","names":[{"lang":"en","v":"TRADE EXPRESS LIMITED"},{"lang":"hk","v":"經商有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544273","names":[{"lang":"en","v":"JUMBO LAND AGENCY LIMITED"},{"lang":"hk","v":"振邦物業有限公司"}],"company_since":"1996-04-11","company_dissolved":"2002-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544275","names":[{"lang":"en","v":"TRANSASIAN PARTNERS LIMITED"}],"company_since":"1996-04-11","company_dissolved":"2007-08-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544403","names":[{"lang":"en","v":"SHING LEE YUEN LIMITED"},{"lang":"hk","v":"成利園有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544443","names":[{"lang":"en","v":"TRANSGREAT LIMITED"},{"lang":"hk","v":"通僑有限公司"}],"company_since":"1996-04-11","company_dissolved":"2004-05-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"544304","names":[{"lang":"en","v":"TREASURE PRINTING LIMITED"},{"lang":"hk","v":"金富印刷有限公司"}],"company_since":"1996-04-11","company_dissolved":"2001-10-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544376","names":[{"lang":"en","v":"SHUN FAT PRINTING COMPANY LIMITED"},{"lang":"hk","v":"信發印刷有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544342","names":[{"lang":"en","v":"TUNG KONG CONSTRUCTION DECORATION ENGINEERING (HK &amp; CHINA) LIMITED"},{"lang":"hk","v":"東江建築裝飾工程(中港)有限公司"}],"company_since":"1996-04-11","company_dissolved":"2004-05-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544454","names":[{"lang":"en","v":"UNI-BRIGHT INTERNATIONAL LIMITED (d2005-12-30)"},{"lang":"hk","v":"愉威國際有限公司"}],"company_since":"1996-04-11","company_dissolved":"2005-12-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544490","names":[{"lang":"en","v":"SMART CAREER (ASIA) LIMITED"},{"lang":"hk","v":"俊業(亞洲)有限公司"}],"company_since":"1996-04-11","company_dissolved":"2017-12-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544256","names":[{"lang":"en","v":"NEW CAPITAL ENGINEERING LIMITED"},{"lang":"hk","v":"新佳工程有限公司"}],"company_since":"1996-04-11","company_dissolved":"2013-06-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544295","names":[{"lang":"en","v":"SMART WELL MANAGEMENT LIMITED"},{"lang":"hk","v":"駿安管理有限公司"}],"company_since":"1996-04-11","company_dissolved":"2001-06-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544534","names":[{"lang":"en","v":"VICTORY CAPITAL HOLDINGS LIMITED (d2003-01-10)"},{"lang":"hk","v":"偉嘉集團有限公司"}],"company_since":"1996-04-11","company_dissolved":"2003-01-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544368","names":[{"lang":"en","v":"WASHING BROTHERS INTERNATIONAL LIMITED"},{"lang":"hk","v":"華誠兄弟國際有限公司"}],"company_since":"1996-04-11","company_dissolved":"2004-10-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"544507","names":[{"lang":"en","v":"STRONG MASTER INDUSTRIAL LIMITED (d2002-02-15)"},{"lang":"hk","v":"英強實業有限公司"}],"company_since":"1996-04-11","company_dissolved":"2002-02-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544440","names":[{"lang":"en","v":"WEALTHGAIN INTERNATIONAL LIMITED"},{"lang":"hk","v":"衛景國際有限公司"}],"company_since":"1996-04-11","company_dissolved":"2020-07-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"544367","names":[{"lang":"en","v":"EXPRESS RICH LIMITED"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544425","names":[{"lang":"en","v":"GRAND ORIGIN LIMITED (d1999-05-14)"},{"lang":"hk","v":"宏巨有限公司"}],"company_since":"1996-04-11","company_dissolved":"1999-05-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544489","names":[{"lang":"en","v":"SUNNY TELECOMMUNICATIONS LIMITED"},{"lang":"hk","v":"新利電訊有限公司"}],"company_since":"1996-04-11","company_dissolved":"2008-09-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544491","names":[{"lang":"en","v":"SUNTECH INTERNATIONAL MANAGEMENT LIMITED"},{"lang":"hk","v":"新達國際管理有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544419","names":[{"lang":"en","v":"SUPERIOR HOLDINGS LIMITED (d2001-09-21)"},{"lang":"hk","v":"宏寶集團有限公司"}],"company_since":"1996-04-11","company_dissolved":"2001-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544506","names":[{"lang":"en","v":"SWIFT CHOICE TRADING LIMITED"},{"lang":"hk","v":"迅彩貿易有限公司"}],"company_since":"1996-04-11","company_dissolved":"2003-01-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544431","names":[{"lang":"en","v":"WILLAND INVESTMENT LIMITED"}],"company_since":"1996-04-11","company_dissolved":"2020-01-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544531","names":[{"lang":"en","v":"WIN HOPE GARMENT LIMITED"},{"lang":"hk","v":"威望製衣有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544290","names":[{"lang":"en","v":"WINFORT GARMENT COMPANY LIMITED"},{"lang":"hk","v":"榮紡貿易有限公司"}],"company_since":"1996-04-11","company_dissolved":"2001-08-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544283","names":[{"lang":"en","v":"TERASAKA SHOKAI (H.K.) LIMITED"},{"lang":"hk","v":"寺坂商會有限公司"}],"company_since":"1996-04-11","company_dissolved":"2005-04-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544529","names":[{"lang":"en","v":"TIMWELL GARMENT LIMITED"},{"lang":"hk","v":"天惠製衣有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544384","names":[{"lang":"en","v":"WINTECK INDUSTRIES LIMITED"},{"lang":"hk","v":"榮得實業有限公司"}],"company_since":"1996-04-11","company_dissolved":"2001-09-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544516","names":[{"lang":"en","v":"Winter Company Limited"},{"lang":"hk","v":"永達中港有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544318","names":[{"lang":"en","v":"UP RIGHT INVESTMENT LIMITED"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544424","names":[{"lang":"en","v":"YORK KENT LIMITED (d2013-12-06)"},{"lang":"hk","v":"溢建有限公司"}],"company_since":"1996-04-11","company_dissolved":"2013-12-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544512","names":[{"lang":"en","v":"TOP POWER PLASTIC LIMITED"},{"lang":"hk","v":"達力塑膠有限公司"}],"company_since":"1996-04-11","company_dissolved":"2004-12-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544511","names":[{"lang":"en","v":"TOP YIELD PRODUCTION LIMITED"},{"lang":"hk","v":"多益製作有限公司"}],"company_since":"1996-04-11","company_dissolved":"2003-10-31","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544261","names":[{"lang":"en","v":"TOPTEN CONSULTANTS LIMITED"}],"company_since":"1996-04-11","company_dissolved":"2001-12-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544457","names":[{"lang":"en","v":"TRANS-NATION LIMITED"},{"lang":"hk","v":"通國有限公司"}],"company_since":"1996-04-11","company_dissolved":"2015-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544361","names":[{"lang":"en","v":"UNION (HK) INTERNATIONAL LIMITED"},{"lang":"hk","v":"中聯集團(香港)國際有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544520","names":[{"lang":"en","v":"UNION CHOICE INTERNATIONAL INDUSTRIAL LIMITED"},{"lang":"hk","v":"聯昌國際實業有限公司"}],"company_since":"1996-04-11","company_dissolved":"2002-11-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544439","names":[{"lang":"en","v":"UNIQUEVER INTERNATIONAL LIMITED"},{"lang":"hk","v":"欣祥國際有限公司"}],"company_since":"1996-04-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"544401","names":[{"lang":"en","v":"WEALTH SIGN INTERNATIONAL LIMITED"},{"lang":"hk","v":"裕采國際有限公司"}],"company_since":"1996-04-11","company_dissolved":"2002-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544388","names":[{"lang":"en","v":"WEALTHY (CHINA) LIMITED (d2001-04-20)"},{"lang":"hk","v":"裕順(中國)有限公司"}],"company_since":"1996-04-11","company_dissolved":"2001-04-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544518","names":[{"lang":"en","v":"WELBOND PLASTIC LIMITED"},{"lang":"hk","v":"威邦塑膠有限公司"}],"company_since":"1996-04-11","company_dissolved":"1999-04-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544340","names":[{"lang":"en","v":"WELCOME JACKSON (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"惠康積臣(香港)有限公司"}],"company_since":"1996-04-11","company_dissolved":"1999-06-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544541","names":[{"lang":"en","v":"WELL ASIAN INTERNATIONAL LIMITED"},{"lang":"hk","v":"佳亞國際有限公司"}],"company_since":"1996-04-11","company_dissolved":"2003-06-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"544517","names":[{"lang":"en","v":"WINCHOICE TECHNOLOGY LIMITED"},{"lang":"hk","v":"威確科技有限公司"}],"company_since":"1996-04-11","company_dissolved":"2002-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544341","names":[{"lang":"en","v":"WINNER FINANCE COMPANY LIMITED"},{"lang":"hk","v":"永利財務有限公司"}],"company_since":"1996-04-11","company_dissolved":"2002-07-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544448","names":[{"lang":"en","v":"GLORY JOIN INTERNATIONAL LIMITED"},{"lang":"hk","v":"鉅中國際有限公司"}],"company_since":"1996-04-11","company_dissolved":"2014-08-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544392","names":[{"lang":"en","v":"WIDE FINANCIAL LIMITED"},{"lang":"hk","v":"廣經有限公司"}],"company_since":"1996-04-11","company_dissolved":"2001-10-19","company_type_txt":"Private, ltd by shares"},
undefined,
