{"tax_id":"544071","names":[{"lang":"en","v":"CHAMPFIELD INTERNATIONAL LIMITED"},{"lang":"hk","v":"冠田國際有限公司"}],"company_since":"1996-04-09","company_dissolved":"2005-03-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544090","names":[{"lang":"en","v":"CHARTER FEDERAL LIMITED"},{"lang":"hk","v":"集發有限公司"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544155","names":[{"lang":"en","v":"CHARTER GILMAN INSURANCE BROKERS LIMITED"},{"lang":"hk","v":"基利民保險顧問有限公司"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544121","names":[{"lang":"en","v":"CHEER HOME FAR EAST LIMITED"},{"lang":"hk","v":"志鳴遠東有限公司"}],"company_since":"1996-04-09","company_dissolved":"2011-09-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544168","names":[{"lang":"en","v":"CHEERANK INTERNATIONAL LIMITED"}],"company_since":"1996-04-09","company_dissolved":"2002-10-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544128","names":[{"lang":"en","v":"CHEMAX (HK) LIMITED"},{"lang":"hk","v":"中化興(香港)有限公司"}],"company_since":"1996-04-09","company_dissolved":"2008-07-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544158","names":[{"lang":"en","v":"CHINWAY LIMITED"},{"lang":"hk","v":"俊威有限公司"}],"company_since":"1996-04-09","company_dissolved":"2004-05-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544215","names":[{"lang":"en","v":"CHUNG KONG INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"中港國際發展有限公司"}],"company_since":"1996-04-09","company_dissolved":"2007-12-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544206","names":[{"lang":"en","v":"CIRCLE HARVEST INTERNATIONAL LIMITED"},{"lang":"hk","v":"球豐國際有限公司"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544100","names":[{"lang":"en","v":"Computech Solutions Services Limited"}],"company_since":"1996-04-09","company_dissolved":"2014-05-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544205","names":[{"lang":"en","v":"COVA HK LIMITED"}],"company_since":"1996-04-09","company_dissolved":"2014-02-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544070","names":[{"lang":"en","v":"CROWN LOT DEVELOPMENT LIMITED"},{"lang":"hk","v":"冠來發展有限公司"}],"company_since":"1996-04-09","company_dissolved":"2002-12-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544195","names":[{"lang":"en","v":"CROWN STEP LIMITED (d2004-03-26)"},{"lang":"hk","v":"金里程有限公司"}],"company_since":"1996-04-09","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544130","names":[{"lang":"en","v":"DELIGHT ART INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"巧藝國際發展有限公司"}],"company_since":"1996-04-09","company_dissolved":"2005-03-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544066","names":[{"lang":"en","v":"DELIGHTED WIN DEVELOPMENT LIMITED"},{"lang":"hk","v":"巧勝發展有限公司"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544092","names":[{"lang":"en","v":"EAST LAND HOLDINGS LIMITED"},{"lang":"hk","v":"東萊集團有限公司"}],"company_since":"1996-04-09","company_dissolved":"2017-11-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544074","names":[{"lang":"en","v":"EASTERN CHANNEL ENTERPRISES LIMITED"},{"lang":"hk","v":"東駿(亞洲)有限公司"}],"company_since":"1996-04-09","company_dissolved":"2004-05-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544137","names":[{"lang":"en","v":"ETERNAL RISE TELECOMMUNICATION COMPANY LIMITED"},{"lang":"hk","v":"永揚電訊有限公司"}],"company_since":"1996-04-09","company_dissolved":"2002-12-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544119","names":[{"lang":"en","v":"EASYDAY INVESTMENT LIMITED"},{"lang":"hk","v":"怡日投資有限公司"}],"company_since":"1996-04-09","company_dissolved":"2001-08-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544045","names":[{"lang":"en","v":"EVER MORE PROFIT INTERNATIONAL INVESTMENT CO., LIMITED"},{"lang":"hk","v":"恒利達國際投資有限公司"}],"company_since":"1996-04-09","company_dissolved":"2002-07-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544104","names":[{"lang":"en","v":"FAI TAK PRINTING EQUIPMENT COMPANY LIMITED"},{"lang":"hk","v":"輝德印刷器材有限公司"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544167","names":[{"lang":"en","v":"FIRST SECURITY TRADE SERVICES LIMITED"}],"company_since":"1996-04-09","company_dissolved":"2004-05-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544160","names":[{"lang":"en","v":"FULL ASIA LIMITED (d1999-04-28)"},{"lang":"hk","v":"滿亞有限公司"}],"company_since":"1996-04-09","company_dissolved":"1999-04-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544221","names":[{"lang":"en","v":"FUNNYTOY INDUSTRIAL (H.K.) CO. LIMITED"},{"lang":"hk","v":"俊英實業(香港)有限公司"}],"company_since":"1996-04-09","company_dissolved":"2000-09-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544193","names":[{"lang":"en","v":"GEMINI AIR FREIGHT LIMITED"},{"lang":"hk","v":"雙星空運有限公司"}],"company_since":"1996-04-09","company_dissolved":"2003-11-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544199","names":[{"lang":"en","v":"GIANT PLAN INVESTMENTS LIMITED"},{"lang":"hk","v":"弘圖投資有限公司"}],"company_since":"1996-04-09","company_dissolved":"2000-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544087","names":[{"lang":"en","v":"GLORY BRILLIANT LIMITED"},{"lang":"hk","v":"高耀有限公司"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544056","names":[{"lang":"en","v":"GOE/JV CHINA CO. LIMITED"}],"company_since":"1996-04-09","company_dissolved":"2004-02-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544171","names":[{"lang":"en","v":"GOOD CENTURY CATERERS LIMITED"},{"lang":"hk","v":"好世紀飲食有限公司"}],"company_since":"1996-04-09","company_dissolved":"2001-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544093","names":[{"lang":"en","v":"GOOD IDEA TECHNOLOGY LIMITED (d2004-05-21)"},{"lang":"hk","v":"創新意科技有限公司"}],"company_since":"1996-04-09","company_dissolved":"2004-05-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544159","names":[{"lang":"en","v":"GRADE PACIFIC LIMITED"},{"lang":"hk","v":"佳輝有限公司"}],"company_since":"1996-04-09","company_dissolved":"2005-12-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544094","names":[{"lang":"en","v":"GREAT NAME INDUSTRIAL LIMITED"},{"lang":"hk","v":"創名實業有限公司"}],"company_since":"1996-04-09","company_dissolved":"2002-08-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544244","names":[{"lang":"en","v":"GUANG YING (H.K.) INTERNATIONAL SHIPPING AND TRANSPORTATION CO. LIMITED"},{"lang":"hk","v":"光英(香港)國際船務運輸有限公司"}],"company_since":"1996-04-09","company_dissolved":"2004-05-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544249","names":[{"lang":"en","v":"HANG WO MARINE PRODUCTS INTERNATIONAL TRADING (H.K.) LIMITED"},{"lang":"hk","v":"香港恒和國際海產品貿易有限公司"}],"company_since":"1996-04-09","company_dissolved":"2006-05-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544076","names":[{"lang":"en","v":"HOMWELL INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"海華國際發展有限公司"}],"company_since":"1996-04-09","company_dissolved":"2001-03-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544196","names":[{"lang":"en","v":"HONBERG LIMITED"},{"lang":"hk","v":"康堡有限公司"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544211","names":[{"lang":"en","v":"Hong Kong Auctions Limited"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544186","names":[{"lang":"en","v":"CHUN HING KONG FENG LIMITED"},{"lang":"hk","v":"振興港鳳有限公司"}],"company_since":"1996-04-09","company_dissolved":"1999-09-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544210","names":[{"lang":"en","v":"HONOUR TRUMP LIMITED"},{"lang":"hk","v":"安澤有限公司"}],"company_since":"1996-04-09","company_dissolved":"2003-05-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544106","names":[{"lang":"en","v":"CEDAR ELECTRONIC (CHINA) LIMITED"},{"lang":"hk","v":"易達電子(中國)有限公司"}],"company_since":"1996-04-09","company_dissolved":"2015-12-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544067","names":[{"lang":"en","v":"HOWE LUCK INTERNATIONAL LIMITED"},{"lang":"hk","v":"巧運國際有限公司"}],"company_since":"1996-04-09","company_dissolved":"2000-04-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"544248","names":[{"lang":"en","v":"DEVELOPMENT ENTERPRISES GROUP (H.K.) LIMITED"},{"lang":"hk","v":"香港拓業實業(集團)有限公司"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544113","names":[{"lang":"en","v":"DOUBLE FULL LIMITED"},{"lang":"hk","v":"聯資有限公司"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544048","names":[{"lang":"en","v":"INFOWARE COMPUTERS LIMITED"},{"lang":"hk","v":"聯智電腦有限公司"}],"company_since":"1996-04-09","company_dissolved":"2019-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544102","names":[{"lang":"en","v":"E &amp; L TRADING COMPANY LIMITED"},{"lang":"hk","v":"嘉彰貿易汽車零件有限公司"}],"company_since":"1996-04-09","company_dissolved":"2016-10-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544053","names":[{"lang":"en","v":"INTRO-TECH TECHNOLOGY SYSTEMS LIMITED"},{"lang":"hk","v":"中達科技系統有限公司"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544204","names":[{"lang":"en","v":"EASTERN RAINBOW INTERNATIONAL LIMITED"},{"lang":"hk","v":"東虹國際有限公司"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544207","names":[{"lang":"en","v":"COMNET LIMITED (d2003-10-10)"}],"company_since":"1996-04-09","company_dissolved":"2003-10-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544072","names":[{"lang":"en","v":"JET LAND INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"捷利國際投資有限公司"}],"company_since":"1996-04-09","company_dissolved":"2004-07-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544047","names":[{"lang":"en","v":"EURASIAN DEVELOPMENT CORPORATION LIMITED"},{"lang":"hk","v":"鷗亞發展有限公司"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544046","names":[{"lang":"en","v":"JODA COMPANY LIMITED"},{"lang":"hk","v":"香港驕達有限公司"}],"company_since":"1996-04-09","company_dissolved":"2002-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"544136","names":[{"lang":"en","v":"EVERBEST SUNTO (HK) ENTERPRISE LIMITED"},{"lang":"hk","v":"順通(香港)企業有限公司"}],"company_since":"1996-04-09","company_dissolved":"2002-05-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544122","names":[{"lang":"en","v":"FDS COMMUNICATIONS LIMITED (d2001-10-26)"}],"company_since":"1996-04-09","company_dissolved":"2001-10-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544247","names":[{"lang":"en","v":"KINGTON COMMUNICATIONS LIMITED (d2008-09-26)"},{"lang":"hk","v":"京通科技有限公司"}],"company_since":"1996-04-09","company_dissolved":"2008-09-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544060","names":[{"lang":"en","v":"FULL GRACE INVESTMENT LIMITED"},{"lang":"hk","v":"裕欣投資有限公司"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544235","names":[{"lang":"en","v":"LINGO DEVELOPMENT LIMITED"},{"lang":"hk","v":"領高發展有限公司"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544161","names":[{"lang":"en","v":"LUCK WORLD INVESTMENT LIMITED"},{"lang":"hk","v":"利世投資有限公司"}],"company_since":"1996-04-09","company_dissolved":"2001-01-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544172","names":[{"lang":"en","v":"GRIFFIN ENVELOPES LIMITED"}],"company_since":"1996-04-09","company_dissolved":"2006-10-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544202","names":[{"lang":"en","v":"LUCKY CRANE INTERNATIONAL LIMITED (d2001-10-19)"},{"lang":"hk","v":"福揚國際有限公司"}],"company_since":"1996-04-09","company_dissolved":"2001-10-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544080","names":[{"lang":"en","v":"HOME CHOICE INTERNATIONAL ENTERPRISES LIMITED"},{"lang":"hk","v":"康彩國際企業有限公司"}],"company_since":"1996-04-09","company_dissolved":"2004-10-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544123","names":[{"lang":"en","v":"HONG KIU HAND BAGS FACTORY LIMITED"},{"lang":"hk","v":"康橋手袋廠有限公司"}],"company_since":"1996-04-09","company_dissolved":"2001-04-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544218","names":[{"lang":"en","v":"M.S. LIMITED"}],"company_since":"1996-04-09","company_dissolved":"2007-07-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544153","names":[{"lang":"en","v":"MA DO SUCCESS LIMITED"},{"lang":"hk","v":"馬到功成有限公司"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544188","names":[{"lang":"en","v":"MANA INVESTMENTS LIMITED"}],"company_since":"1996-04-09","company_dissolved":"2001-05-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544142","names":[{"lang":"en","v":"HONG KONG HAI BO ENTERPRISES COMPANY LIMITED"},{"lang":"hk","v":"香港海波實業有限公司"}],"company_since":"1996-04-09","company_dissolved":"2002-08-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544208","names":[{"lang":"en","v":"MASTER LINDEN FREIGHT FORWARDING CO. LIMITED"},{"lang":"hk","v":"禮頓貨運有限公司"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544126","names":[{"lang":"en","v":"HONG KONG SICHUAN FRIENDSHIP ASSOCIATION COMPANY, LIMITED"},{"lang":"hk","v":"香港-四川聯誼會有限公司"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
undefined,
undefined,
{"tax_id":"544232","names":[{"lang":"en","v":"HONEST WISDOM LIMITED (d2004-10-08)"},{"lang":"hk","v":"康弘有限公司"}],"company_since":"1996-04-09","company_dissolved":"2004-10-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544225","names":[{"lang":"en","v":"HUEYLIN HOLDINGS LIMITED"},{"lang":"hk","v":"滙林集團有限公司"}],"company_since":"1996-04-09","company_dissolved":"2018-02-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544131","names":[{"lang":"en","v":"HUGE PORT (H.K.) LIMITED"},{"lang":"hk","v":"鉅寶(香港)有限公司"}],"company_since":"1996-04-09","company_dissolved":"2004-05-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544233","names":[{"lang":"en","v":"NEW HARVEST ENTERPRISES LIMITED"},{"lang":"hk","v":"豐創企業有限公司"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544152","names":[{"lang":"en","v":"INFINITE LIGHT LIMITED (d2002-03-08)"},{"lang":"hk","v":"照心觀有限公司"}],"company_since":"1996-04-09","company_dissolved":"2002-03-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544073","names":[{"lang":"en","v":"NICE PEAK INTERNATIONAL LIMITED"},{"lang":"hk","v":"麗峰國際有限公司"}],"company_since":"1996-04-09","company_dissolved":"2009-03-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544147","names":[{"lang":"en","v":"INTERNATIONAL ACTIVE LIMITED"},{"lang":"hk","v":"國際鴻發有限公司"}],"company_since":"1996-04-09","company_dissolved":"2005-03-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544237","names":[{"lang":"en","v":"PACIFIC SEED LIMITED"},{"lang":"hk","v":"百利鴻有限公司"}],"company_since":"1996-04-09","company_dissolved":"1999-04-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544165","names":[{"lang":"en","v":"PLEASURE LIMITED (d2002-10-11)"},{"lang":"hk","v":"怡喜有限公司"}],"company_since":"1996-04-09","company_dissolved":"2002-10-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544083","names":[{"lang":"en","v":"JET POST (H.K.) LIMITED"},{"lang":"hk","v":"置寶(香港)有限公司"}],"company_since":"1996-04-09","company_dissolved":"2002-04-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544096","names":[{"lang":"en","v":"KEEN JOYCE DEVELOPMENT LIMITED"},{"lang":"hk","v":"均駿發展有限公司"}],"company_since":"1996-04-09","company_dissolved":"2009-11-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544101","names":[{"lang":"en","v":"POLYVEST INVESTMENT LIMITED"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"544198","names":[{"lang":"en","v":"KING LINK ENTERPRISES LIMITED"},{"lang":"hk","v":"君領企業有限公司"}],"company_since":"1996-04-09","company_dissolved":"1999-04-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544134","names":[{"lang":"en","v":"KING QUEST HOLDINGS LIMITED"},{"lang":"hk","v":"建坤集團有限公司"}],"company_since":"1996-04-09","company_dissolved":"2004-05-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544189","names":[{"lang":"en","v":"PROFIT ORIGIN LIMITED (d2004-05-21)"},{"lang":"hk","v":"企源有限公司"}],"company_since":"1996-04-09","company_dissolved":"2004-05-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544180","names":[{"lang":"en","v":"KOWADO COMPANY LIMITED"},{"lang":"hk","v":"康和堂有限公司"}],"company_since":"1996-04-09","company_dissolved":"2004-05-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544078","names":[{"lang":"en","v":"PROFIT TRADE INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"盈貿國際發展有限公司"}],"company_since":"1996-04-09","company_dissolved":"2004-05-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"544138","names":[{"lang":"en","v":"L &amp; M INVESTMENTS COMPANY LIMITED"}],"company_since":"1996-04-09","company_dissolved":"2009-09-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544097","names":[{"lang":"en","v":"QUEEN ON HOLDINGS LIMITED"},{"lang":"hk","v":"均安集團有限公司"}],"company_since":"1996-04-09","company_dissolved":"2001-11-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544114","names":[{"lang":"en","v":"LINK KING LIMITED (d2003-01-10)"},{"lang":"hk","v":"聯勁有限公司"}],"company_since":"1996-04-09","company_dissolved":"2003-01-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544166","names":[{"lang":"en","v":"R. G. CLYDE (CONSULTANTS) LIMITED"}],"company_since":"1996-04-09","company_dissolved":"2006-08-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544110","names":[{"lang":"en","v":"LINKDAY INTERNATIONAL LIMITED"},{"lang":"hk","v":"聯日國際有限公司"}],"company_since":"1996-04-09","company_dissolved":"1999-07-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544214","names":[{"lang":"en","v":"RAGA LIMITED (HK)"},{"lang":"hk","v":"麗嘉有限公司"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544212","names":[{"lang":"en","v":"REAGAN LIMITED"},{"lang":"hk","v":"益健有限公司"}],"company_since":"1996-04-09","company_dissolved":"2001-07-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544239","names":[{"lang":"en","v":"REGAL STEP INVESTMENTS LIMITED"},{"lang":"hk","v":"豪陞投資有限公司"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544143","names":[{"lang":"en","v":"LPS LIMITED (d2005-04-01)"}],"company_since":"1996-04-09","company_dissolved":"2005-04-01","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544109","names":[{"lang":"en","v":"RICHDAY INTERNATIONAL LIMITED"},{"lang":"hk","v":"裕日國際有限公司"}],"company_since":"1996-04-09","company_dissolved":"1999-02-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"544175","names":[{"lang":"en","v":"SA (HUADONG) COMPANY LIMITED"},{"lang":"hk","v":"中美(華東)有限公司"}],"company_since":"1996-04-09","company_dissolved":"2000-08-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544170","names":[{"lang":"en","v":"LUEN YAT ENTERPRISES COMPANY LIMITED"},{"lang":"hk","v":"聯鎰企業有限公司"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"544103","names":[{"lang":"en","v":"SHEN HUI HOLDINGS (HONG KONG) CO., LIMITED"},{"lang":"hk","v":"深暉集團(香港)有限公司"}],"company_since":"1996-04-09","company_dissolved":"2012-11-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544144","names":[{"lang":"en","v":"MAS (H.K.) LIMITED"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544127","names":[{"lang":"en","v":"SHENG DAN TOBACCO COMPANY LIMITED"},{"lang":"hk","v":"聖誕煙草有限公司"}],"company_since":"1996-04-09","company_dissolved":"2002-11-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544145","names":[{"lang":"en","v":"MAS INTERNATIONAL HOLDINGS LIMITED"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544184","names":[{"lang":"en","v":"SILVER SPOON INVESTMENTS LIMITED (HK)"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544163","names":[{"lang":"en","v":"SINO-AMERICA ASIA LIMITED"},{"lang":"hk","v":"中美亞洲有限公司"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"544226","names":[{"lang":"en","v":"NAIGAI (HONG KONG) LIMITED"},{"lang":"hk","v":"香港內外有限公司"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544222","names":[{"lang":"en","v":"NARI HONG KONG LIMITED"},{"lang":"hk","v":"南瑞(香港)有限公司"}],"company_since":"1996-04-09","company_dissolved":"2002-11-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544117","names":[{"lang":"en","v":"SINOMATE COMMERCE LIMITED"},{"lang":"hk","v":"中西商業有限公司"}],"company_since":"1996-04-09","company_dissolved":"2002-07-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544179","names":[{"lang":"en","v":"TEXON HOT STAMPING COMPANY LIMITED"},{"lang":"hk","v":"德信燙金有限公司"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544169","names":[{"lang":"en","v":"TK MARKETING &amp; TRANSPORTATION LIMITED"},{"lang":"hk","v":"添記商貿運輸有限公司"}],"company_since":"1996-04-09","company_dissolved":"2018-03-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544069","names":[{"lang":"en","v":"TOP EAST ASIA LIMITED"},{"lang":"hk","v":"冠益亞洲有限公司"}],"company_since":"1996-04-09","company_dissolved":"2011-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544124","names":[{"lang":"en","v":"PACIFIC INTERNATIONAL DRAFTING SERVICES LIMITED"}],"company_since":"1996-04-09","company_dissolved":"2001-04-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"544079","names":[{"lang":"en","v":"TRANS HARBOUR (CHINA) LIMITED"},{"lang":"hk","v":"港通(中國)有限公司"}],"company_since":"1996-04-09","company_dissolved":"2003-02-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544224","names":[{"lang":"en","v":"UNIQUE INTERNATIONAL TRADING LIMITED"},{"lang":"hk","v":"純美國際貿易有限公司"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544178","names":[{"lang":"en","v":"POTENTIAL INTERIOR CONTRACTING LIMITED"},{"lang":"hk","v":"駿昇室內工程有限公司"}],"company_since":"1996-04-09","company_dissolved":"2002-04-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544085","names":[{"lang":"en","v":"UNITED WELL HOLDINGS LIMITED (d2002-03-01)"},{"lang":"hk","v":"聯偉集團有限公司"}],"company_since":"1996-04-09","company_dissolved":"2002-03-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544108","names":[{"lang":"en","v":"PRESTIGE (HK) LIMITED (d2005-02-18)"},{"lang":"hk","v":"威信建材(香港)有限公司"}],"company_since":"1996-04-09","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544151","names":[{"lang":"en","v":"PRIME DRAGON (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"巨龍(香港)有限公司"}],"company_since":"1996-04-09","company_dissolved":"2005-03-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544062","names":[{"lang":"en","v":"USEFUL HOUSE LIMITED"},{"lang":"hk","v":"裕發行有限公司"}],"company_since":"1996-04-09","company_dissolved":"2007-11-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544051","names":[{"lang":"en","v":"WAVE SUSHI LIMITED"},{"lang":"hk","v":"浪壽司店有限公司"}],"company_since":"1996-04-09","company_dissolved":"2003-03-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544234","names":[{"lang":"en","v":"PROSPER CENTURY DEVELOPMENT LIMITED"},{"lang":"hk","v":"盛成發展有限公司"}],"company_since":"1996-04-09","company_dissolved":"2002-08-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544081","names":[{"lang":"en","v":"YIELD KING FAR EAST LIMITED"},{"lang":"hk","v":"盈健遠東有限公司"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544075","names":[{"lang":"en","v":"YIELDSON INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"益誠國際發展有限公司"}],"company_since":"1996-04-09","company_dissolved":"2003-03-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544220","names":[{"lang":"en","v":"YUE XIU TELECOMMUNICATIONS LIMITED"},{"lang":"hk","v":"越秀信息有限公司"}],"company_since":"1996-04-09","company_dissolved":"2018-03-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544183","names":[{"lang":"en","v":"ZEUS WORLDWIDE (HONG KONG) LIMITED"}],"company_since":"1996-04-09","company_dissolved":"2001-06-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544240","names":[{"lang":"en","v":"REGAL CREST INDUSTRIES LIMITED"},{"lang":"hk","v":"峰豪實業有限公司"}],"company_since":"1996-04-09","company_dissolved":"2017-09-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544190","names":[{"lang":"en","v":"SA (BEIFAN) COMPANY LIMITED"},{"lang":"hk","v":"中美(北方)有限公司"}],"company_since":"1996-04-09","company_dissolved":"2000-08-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544217","names":[{"lang":"en","v":"SAN HUNG CHEMICAL MATERIALS INTERNATIONAL TRADING (H.K.) LIMITED"},{"lang":"hk","v":"香港新雄國際化工原料貿易有限公司"}],"company_since":"1996-04-09","company_dissolved":"2004-07-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544191","names":[{"lang":"en","v":"SA (HUAZHONG) COMPANY LIMITED"},{"lang":"hk","v":"中美(華中)有限公司"}],"company_since":"1996-04-09","company_dissolved":"2000-08-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544150","names":[{"lang":"en","v":"SAM-A (CHINA) TRADING CO., LIMITED"},{"lang":"hk","v":"三亞(中國)貿易有限公司"}],"company_since":"1996-04-09","company_dissolved":"2002-09-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"544115","names":[{"lang":"en","v":"SINO-AMERICA PACIFIC LIMITED"},{"lang":"hk","v":"中美太平洋有限公司"}],"company_since":"1996-04-09","company_dissolved":"2002-09-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544118","names":[{"lang":"en","v":"SUN INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"大新國際集團有限公司"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"544058","names":[{"lang":"en","v":"TOP SINCERE TECHNOLOGY LIMITED"},{"lang":"hk","v":"高誠科技有限公司"}],"company_since":"1996-04-09","company_dissolved":"2003-07-25","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544054","names":[{"lang":"en","v":"TOP RICH INTERNATIONAL ENTERPRISES LIMITED"},{"lang":"hk","v":"高裕國際企業有限公司"}],"company_since":"1996-04-09","company_dissolved":"2004-10-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544133","names":[{"lang":"en","v":"TOP STRONG HOLDINGS LIMITED"},{"lang":"hk","v":"冠強集團有限公司"}],"company_since":"1996-04-09","company_dissolved":"2005-03-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544135","names":[{"lang":"en","v":"QUICK MIND ENTERPRISES LIMITED"},{"lang":"hk","v":"創思企業有限公司"}],"company_since":"1996-04-09","company_dissolved":"2019-12-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544107","names":[{"lang":"en","v":"TRANSAMERICA TRADING (HK) COMPANY LIMITED"},{"lang":"hk","v":"美港聯合貿易有限公司"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544139","names":[{"lang":"en","v":"TRANSCEND (H.K.) LIMITED"},{"lang":"hk","v":"創見股份有限公司"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544055","names":[{"lang":"en","v":"UNITED POWER INTERNATIONAL ENTERPRISES LIMITED"},{"lang":"hk","v":"聯力國際企業有限公司"}],"company_since":"1996-04-09","company_dissolved":"2005-03-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"544154","names":[{"lang":"en","v":"VIGOROUS PROPERTY MANAGEMENT LIMITED"},{"lang":"hk","v":"勵精物業管理有限公司"}],"company_since":"1996-04-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"544068","names":[{"lang":"en","v":"YING HUANG CORPORATION LIMITED"},{"lang":"hk","v":"瑩恒有限公司"}],"company_since":"1996-04-09","company_dissolved":"2013-11-29","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544049","names":[{"lang":"en","v":"YIU KWONG INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"耀桄國際投資有限公司"}],"company_since":"1996-04-09","company_dissolved":"2005-12-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"544061","names":[{"lang":"en","v":"YOUNG FAIR FAR EAST INVESTMENT LIMITED"},{"lang":"hk","v":"裕輝遠東投資有限公司"}],"company_since":"1996-04-09","company_dissolved":"2004-05-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"544095","names":[{"lang":"en","v":"KEEN CHOICE INDUSTRIAL LIMITED"},{"lang":"hk","v":"均彩實業有限公司"}],"company_since":"1996-04-09","company_dissolved":"2004-01-15","company_type_txt":"Private, ltd by shares"},
undefined,
