{"tax_id":"635575","names":[{"lang":"en","v":"GARRISTINE LIMITED"},{"lang":"hk","v":"嘉域泰有限公司"}],"company_since":"1998-02-04","company_dissolved":"2002-11-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635667","names":[{"lang":"en","v":"GLOBAL KNOWLEDGE STRATEGY LIMITED"},{"lang":"hk","v":"環球知識策略有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635696","names":[{"lang":"en","v":"GOLD ROCK ENTERPRISES LIMITED"},{"lang":"hk","v":"合金企業有限公司"}],"company_since":"1998-02-04","company_dissolved":"2002-09-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635705","names":[{"lang":"en","v":"GOLD SUCCESS ENTERPRISES LIMITED (d2005-09-16)"},{"lang":"hk","v":"卓成企業有限公司"}],"company_since":"1998-02-04","company_dissolved":"2005-09-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635674","names":[{"lang":"en","v":"GOLD TIME HOLDINGS LIMITED (d2003-07-11)"},{"lang":"hk","v":"威盛集團有限公司"}],"company_since":"1998-02-04","company_dissolved":"2003-07-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635693","names":[{"lang":"en","v":"GOLD WALL TRADING LIMITED"},{"lang":"hk","v":"大金貿易有限公司"}],"company_since":"1998-02-04","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635704","names":[{"lang":"en","v":"CYBER SHOP (HONG KONG) LIMITED"},{"lang":"hk","v":"聯通店(香港)有限公司"}],"company_since":"1998-02-04","company_dissolved":"2001-09-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635563","names":[{"lang":"en","v":"GOLDEN WORLD CONSULTANTS LIMITED (d2002-10-25)"},{"lang":"hk","v":"高宏顧問有限公司"}],"company_since":"1998-02-04","company_dissolved":"2002-10-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635671","names":[{"lang":"en","v":"GRAND CENTRAL REAL ESTATE AGENCY LIMITED"},{"lang":"hk","v":"中浩行地產代理有限公司"}],"company_since":"1998-02-04","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635663","names":[{"lang":"en","v":"GRAND PROSPECT DEVELOPMENT LIMITED"},{"lang":"hk","v":"鵬豐發展有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635689","names":[{"lang":"en","v":"DAILY &amp; CO., LIMITED"},{"lang":"hk","v":"大利行企業有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635548","names":[{"lang":"en","v":"GREAT DRAGON ENGINEERING LIMITED (d2003-07-11)"},{"lang":"hk","v":"巨龍工程有限公司"}],"company_since":"1998-02-04","company_dissolved":"2003-07-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635552","names":[{"lang":"en","v":"GREAT SOURCES LIMITED (d2003-03-21)"},{"lang":"hk","v":"源浩有限公司"}],"company_since":"1998-02-04","company_dissolved":"2003-03-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635658","names":[{"lang":"en","v":"DDG LIMITED (d2002-10-25)"}],"company_since":"1998-02-04","company_dissolved":"2002-10-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635694","names":[{"lang":"en","v":"GROUP PROFIT TRADING LIMITED (d2002-10-04)"},{"lang":"hk","v":"合金貿易有限公司"}],"company_since":"1998-02-04","company_dissolved":"2002-10-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635644","names":[{"lang":"en","v":"HANSOM FASHION INTERNATIONAL (GROUP) LIMITED"},{"lang":"hk","v":"幸運服裝國際(集團)有限公司"}],"company_since":"1998-02-04","company_dissolved":"2001-03-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635615","names":[{"lang":"en","v":"HANSOM INVESTMENTS LIMITED"},{"lang":"hk","v":"幸運投資有限公司"}],"company_since":"1998-02-04","company_dissolved":"2001-03-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635550","names":[{"lang":"en","v":"EARNINGS DEVELOPMENT LIMITED"},{"lang":"hk","v":"盈豐發展有限公司"}],"company_since":"1998-02-04","company_dissolved":"2007-06-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635697","names":[{"lang":"en","v":"HIM KEN INDUSTRIAL LIMITED"},{"lang":"hk","v":"謙勤實業有限公司"}],"company_since":"1998-02-04","company_dissolved":"2001-11-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635539","names":[{"lang":"en","v":"HING LUNG CIVIL CONSTRUCTION COMPANY LIMITED"},{"lang":"hk","v":"興隆土力工程有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635736","names":[{"lang":"en","v":"HKP CORPORATION LIMITED"},{"lang":"hk","v":"峻益(香港)有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635613","names":[{"lang":"en","v":"EAST CHINA COMPUTER CORP. LIMITED"},{"lang":"hk","v":"華東電腦股份有限公司"}],"company_since":"1998-02-04","company_dissolved":"2003-05-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635699","names":[{"lang":"en","v":"EAST TOP (HOLDINGS) LIMITED"},{"lang":"hk","v":"東正(集團)有限公司"}],"company_since":"1998-02-04","company_dissolved":"2005-02-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635594","names":[{"lang":"en","v":"HONG KONG CONVENIENCE LIMITED"},{"lang":"hk","v":"香港便利有限公司"}],"company_since":"1998-02-04","company_dissolved":"2009-06-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635554","names":[{"lang":"en","v":"EASTWOOD HOLDINGS LIMITED (d2005-02-04)"},{"lang":"hk","v":"東茂集團有限公司"}],"company_since":"1998-02-04","company_dissolved":"2005-02-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635579","names":[{"lang":"en","v":"HONG KONG PORAKINT INTERNATIONAL GROUP LIMITED"},{"lang":"hk","v":"香港拜麗德國際集團有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635651","names":[{"lang":"en","v":"HUNG CHEONG HONG INTERNATIONAL LIMITED"},{"lang":"hk","v":"鴻昌行國際有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635610","names":[{"lang":"en","v":"IN-COM TECHNOLOGY COMPANY LIMITED"},{"lang":"hk","v":"天域電腦科技有限公司"}],"company_since":"1998-02-04","company_dissolved":"2007-06-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635560","names":[{"lang":"en","v":"EMPIRE DEVELOPMENT LIMITED (THE)"},{"lang":"hk","v":"德煌發展有限公司"}],"company_since":"1998-02-04","company_dissolved":"2010-07-02","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635734","names":[{"lang":"en","v":"INFINITY (DEVELOPMENT) TRADING LIMITED"},{"lang":"hk","v":"永恒(發展)貿易有限公司"}],"company_since":"1998-02-04","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635639","names":[{"lang":"en","v":"HUNG YAT CAR PARK COMPANY LIMITED"},{"lang":"hk","v":"鴻日停車場有限公司"}],"company_since":"1998-02-04","company_dissolved":"2011-12-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635687","names":[{"lang":"en","v":"ENTERTAINMENT LOGISTICS INTERNATIONAL LIMITED (d2015-11-20)"}],"company_since":"1998-02-04","company_dissolved":"2015-11-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635659","names":[{"lang":"en","v":"J &amp; D (ASIA) LIMITED (d2002-05-24)"},{"lang":"hk","v":"捷登(亞洲)有限公司"}],"company_since":"1998-02-04","company_dissolved":"2002-05-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635540","names":[{"lang":"en","v":"JOYFUL TREND LIMITED"},{"lang":"hk","v":"愉意有限公司"}],"company_since":"1998-02-04","company_dissolved":"2019-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635573","names":[{"lang":"en","v":"JP INC LIMITED (d2005-02-04)"},{"lang":"hk","v":"進明出版社有限公司"}],"company_since":"1998-02-04","company_dissolved":"2005-02-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635733","names":[{"lang":"en","v":"EXCEL RISE INTERNATIONAL LIMITED"},{"lang":"hk","v":"卓昇國際有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635566","names":[{"lang":"en","v":"FAITHFUL KING MANAGEMENT LIMITED"},{"lang":"hk","v":"輝傑管理有限公司"}],"company_since":"1998-02-04","company_dissolved":"2006-09-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635713","names":[{"lang":"en","v":"KAM WING (H.K.) FASHION LIMITED"},{"lang":"hk","v":"錦榮(香港)服裝有限公司"}],"company_since":"1998-02-04","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635677","names":[{"lang":"en","v":"KATAR TRADING LIMITED"},{"lang":"hk","v":"嘉達利貿易有限公司"}],"company_since":"1998-02-04","company_dissolved":"2007-06-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635578","names":[{"lang":"en","v":"KAU KEE CONSTRUCTION WORKS LIMITED"},{"lang":"hk","v":"球記土木裝飾工程有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635654","names":[{"lang":"en","v":"FALCO ELECTRICAL CONTRACTING COMPANY LIMITED"},{"lang":"hk","v":"運通電器工程有限公司"}],"company_since":"1998-02-04","company_dissolved":"2003-11-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635715","names":[{"lang":"en","v":"KING BLASTER INDUSTRIES LIMITED"},{"lang":"hk","v":"惠金實業有限公司"}],"company_since":"1998-02-04","company_dissolved":"2003-01-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635569","names":[{"lang":"en","v":"LAMMARK KNITWEAR COMPANY LIMITED"},{"lang":"hk","v":"滙邦針織有限公司"}],"company_since":"1998-02-04","company_dissolved":"2007-05-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635565","names":[{"lang":"en","v":"FOREST INVESTMENTS LIMITED (d2006-02-03)"},{"lang":"hk","v":"林茂投資有限公司"}],"company_since":"1998-02-04","company_dissolved":"2006-02-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635632","names":[{"lang":"en","v":"LONG PROSPECT TRADING LIMITED"},{"lang":"hk","v":"鴻祥貿易有限公司"}],"company_since":"1998-02-04","company_dissolved":"2002-09-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635564","names":[{"lang":"en","v":"LOYALTY ENTERPRISE LIMITED"},{"lang":"hk","v":"立天企業有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635553","names":[{"lang":"en","v":"LPM ENGINEERING LIMITED"},{"lang":"hk","v":"香港斜坡工程有限公司"}],"company_since":"1998-02-04","company_dissolved":"2004-04-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635612","names":[{"lang":"en","v":"FUHING INTERNATIONAL HOLDING CO. LIMITED"},{"lang":"hk","v":"富興國際集團有限公司"}],"company_since":"1998-02-04","company_dissolved":"2001-07-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635572","names":[{"lang":"en","v":"MARVEL ENTERPRISES LIMITED"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635599","names":[{"lang":"en","v":"FUNAN (HONG KONG) LIMITED"},{"lang":"hk","v":"佛南(香港)有限公司"}],"company_since":"1998-02-04","company_dissolved":"2004-09-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635585","names":[{"lang":"en","v":"G &amp; M INTERNATIONAL LIMITED"},{"lang":"hk","v":"錢國環球有限公司"}],"company_since":"1998-02-04","company_dissolved":"2000-12-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635655","names":[{"lang":"en","v":"MEGO CONSTRUCTION (CHINA) LIMITED"},{"lang":"hk","v":"美高建設(中國)有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635602","names":[{"lang":"en","v":"MIRACLE LUCK LIMITED"},{"lang":"hk","v":"濠達有限公司"}],"company_since":"1998-02-04","company_dissolved":"2012-02-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"635695","names":[{"lang":"en","v":"GOLD WALL ENTERPRISES LIMITED"},{"lang":"hk","v":"惠金企業有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635709","names":[{"lang":"en","v":"NEW KIU YUE LIMITED"},{"lang":"hk","v":"新喬宇有限公司"}],"company_since":"1998-02-04","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635595","names":[{"lang":"en","v":"GAINING FASHION CO., LIMITED"},{"lang":"hk","v":"佳德時裝有限公司"}],"company_since":"1998-02-04","company_dissolved":"2001-11-16","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635735","names":[{"lang":"en","v":"NEW VIGOR INTERNATIONAL ENTERPRISES CO. LIMITED"},{"lang":"hk","v":"燊燊貿易有限公司"}],"company_since":"1998-02-04","company_dissolved":"2003-02-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635675","names":[{"lang":"en","v":"NOBLE BRIGHT DEVELOPMENT LIMITED"},{"lang":"hk","v":"耀暉發展有限公司"}],"company_since":"1998-02-04","company_dissolved":"2019-09-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635708","names":[{"lang":"en","v":"NOBLE KING INTERNATIONAL LIMITED"},{"lang":"hk","v":"威煌國際有限公司"}],"company_since":"1998-02-04","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635620","names":[{"lang":"en","v":"NUTRITIONAL FOOD PRODUCTION COMPANY LIMITED"},{"lang":"hk","v":"營養膳有限公司"}],"company_since":"1998-02-04","company_dissolved":"2005-02-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635536","names":[{"lang":"en","v":"OEMAX INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"美斯國際發展有限公司"}],"company_since":"1998-02-04","company_dissolved":"2000-08-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635718","names":[{"lang":"en","v":"OPEN GROUP INVESTMENT LIMITED"},{"lang":"hk","v":"八合投資有限公司"}],"company_since":"1998-02-04","company_dissolved":"2003-07-25","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635676","names":[{"lang":"en","v":"OR PARTNER INTEGRATED INFORMATION SYSTEMS ASIA-PACIFIC LIMITED"},{"lang":"hk","v":"歐雅集成信息系統亞太有限公司"}],"company_since":"1998-02-04","company_dissolved":"2006-01-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635720","names":[{"lang":"en","v":"HANG TUNG RESOURCES FINANCE LIMITED"},{"lang":"hk","v":"恆通財務有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635650","names":[{"lang":"en","v":"OWEN MEANY LIMITED"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635726","names":[{"lang":"en","v":"PAULINE AIRPORT FLORIST LIMITED"},{"lang":"hk","v":"佩妍機場花廊有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635625","names":[{"lang":"en","v":"HLT CONSTRUCTION COMPANY LIMITED"},{"lang":"hk","v":"興利達建築有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635642","names":[{"lang":"en","v":"PENDRAGON CORDYCEPS PRODUCTS (HK) LIMITED"},{"lang":"hk","v":"奔龍蟲草製品(香港)有限公司"}],"company_since":"1998-02-04","company_dissolved":"2002-11-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635609","names":[{"lang":"en","v":"HONEST RELIANCE INVESTMENTS LIMITED"},{"lang":"hk","v":"誠熙投資有限公司"}],"company_since":"1998-02-04","company_dissolved":"2001-01-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635635","names":[{"lang":"en","v":"HONG KONG CHUANG YE INTERNATIONAL INVESTMENT GROUP LIMITED"},{"lang":"hk","v":"香港創業國際投資集團有限公司"}],"company_since":"1998-02-04","company_dissolved":"2007-04-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635641","names":[{"lang":"en","v":"PENDRAGON MARKETING (HK) LIMITED"},{"lang":"hk","v":"奔龍市場推廣(香港)有限公司"}],"company_since":"1998-02-04","company_dissolved":"2002-11-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635682","names":[{"lang":"en","v":"PINNACLE (FAR EAST) LIMITED"},{"lang":"hk","v":"穎材(遠東)有限公司"}],"company_since":"1998-02-04","company_dissolved":"2001-07-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635646","names":[{"lang":"en","v":"INSUWORLD MANAGEMENT LIMITED"},{"lang":"hk","v":"宏保管理有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635574","names":[{"lang":"en","v":"INTERSTAR HONG KONG COMPANY LIMITED"},{"lang":"hk","v":"星座國際香港有限公司"}],"company_since":"1998-02-04","company_dissolved":"2009-09-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635549","names":[{"lang":"en","v":"QUICK RETURN HOLDINGS LIMITED"},{"lang":"hk","v":"迅豐集團有限公司"}],"company_since":"1998-02-04","company_dissolved":"2019-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635581","names":[{"lang":"en","v":"K-MARK INVESTMENT LIMITED"}],"company_since":"1998-02-04","company_dissolved":"2010-07-02","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635607","names":[{"lang":"en","v":"RIGHT HORSE INVESTMENTS LIMITED"},{"lang":"hk","v":"滙雄投資有限公司"}],"company_since":"1998-02-04","company_dissolved":"2002-07-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635541","names":[{"lang":"en","v":"SHARP VICTORY DEVELOPMENT LIMITED"},{"lang":"hk","v":"致運發展有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635684","names":[{"lang":"en","v":"SHIBATA INVESTMENT CONSULTANTS COMPANY LIMITED"},{"lang":"hk","v":"柴田投資顧問有限公司"}],"company_since":"1998-02-04","company_dissolved":"2003-08-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635537","names":[{"lang":"en","v":"SIMON FEN HIN COMPANY LIMITED"},{"lang":"hk","v":"森文宏興有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"635672","names":[{"lang":"en","v":"SINO WISDOM LIMITED (d2001-07-13)"},{"lang":"hk","v":"華振有限公司"}],"company_since":"1998-02-04","company_dissolved":"2001-07-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635603","names":[{"lang":"en","v":"SMART CHAMPION HOLDINGS LIMITED (d2005-02-04)"},{"lang":"hk","v":"威譽集團有限公司"}],"company_since":"1998-02-04","company_dissolved":"2005-02-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635638","names":[{"lang":"en","v":"LEGEND ENTERTAINMENT LIMITED (d2003-11-14)"}],"company_since":"1998-02-04","company_dissolved":"2003-11-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635707","names":[{"lang":"en","v":"SKY FOND INTERNATIONAL LIMITED"},{"lang":"hk","v":"天豐國際有限公司"}],"company_since":"1998-02-04","company_dissolved":"2006-06-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635627","names":[{"lang":"en","v":"LINK FORTUNE HOLDINGS LIMITED"},{"lang":"hk","v":"利財集團有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635601","names":[{"lang":"en","v":"LONG RAY HONG KONG LIMITED"},{"lang":"hk","v":"朗惠香港有限公司"}],"company_since":"1998-02-04","company_dissolved":"2011-11-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635665","names":[{"lang":"en","v":"STAR RESOURCES DEVELOPMENT LIMITED"},{"lang":"hk","v":"星源發展(香港)有限公司"}],"company_since":"1998-02-04","company_dissolved":"2007-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635662","names":[{"lang":"en","v":"HONOUR POWER DEVELOPMENT LIMITED"},{"lang":"hk","v":"誠譽發展有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635592","names":[{"lang":"en","v":"SUNNY CHOICE DEVELOPMENT LIMITED (d2007-06-15)"},{"lang":"hk","v":"彩藝發展有限公司"}],"company_since":"1998-02-04","company_dissolved":"2007-06-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635591","names":[{"lang":"en","v":"SUPER TALENT ENTERPRISES LIMITED"},{"lang":"hk","v":"智濠企業有限公司"}],"company_since":"1998-02-04","company_dissolved":"2002-08-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635678","names":[{"lang":"en","v":"MAXFLIGHT (ASIA) CORPORATION LIMITED"}],"company_since":"1998-02-04","company_dissolved":"2017-10-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635619","names":[{"lang":"en","v":"SURE BRIGHT INTERNATIONAL LIMITED (d2002-06-21)"},{"lang":"hk","v":"耀生國際有限公司"}],"company_since":"1998-02-04","company_dissolved":"2002-06-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635727","names":[{"lang":"en","v":"MEGA PEAK LIMITED (d2007-10-18)"},{"lang":"hk","v":"順峰有限公司"}],"company_since":"1998-02-04","company_dissolved":"2007-10-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635624","names":[{"lang":"en","v":"SURE PROSPECT INTERNATIONAL LIMITED"},{"lang":"hk","v":"昌潤國際有限公司"}],"company_since":"1998-02-04","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635660","names":[{"lang":"en","v":"SURE SUCCESS INTERNATIONAL LIMITED (d2003-06-20)"},{"lang":"hk","v":"盛志國際有限公司"}],"company_since":"1998-02-04","company_dissolved":"2003-06-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635593","names":[{"lang":"en","v":"MEGA RETURN INVESTMENTS LIMITED"},{"lang":"hk","v":"詠利投資有限公司"}],"company_since":"1998-02-04","company_dissolved":"2002-03-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635721","names":[{"lang":"en","v":"TAI HING COMPUTER KNITTING FACTORY LIMITED"},{"lang":"hk","v":"大興電腦針織廠有限公司"}],"company_since":"1998-02-04","company_dissolved":"2020-04-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635589","names":[{"lang":"en","v":"TAI YIP (INT'L) LOGISTIC LIMITED"},{"lang":"hk","v":"泰業國際物流有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635542","names":[{"lang":"en","v":"NEW DIGITAL TECHNOLOGY LIMITED"},{"lang":"hk","v":"安達斯數字系統有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635634","names":[{"lang":"en","v":"TELFORE INTERNATIONAL LIMITED"},{"lang":"hk","v":"霆科國際有限公司"}],"company_since":"1998-02-04","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635714","names":[{"lang":"en","v":"TOYO ELECTRIC (HK) ENTERPRISE CO. LIMITED"},{"lang":"hk","v":"通用電器(香港)企業有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635583","names":[{"lang":"en","v":"UNIVERSAL EXPORTS LIMITED (HK)"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635568","names":[{"lang":"en","v":"WAI LUNG TRADING LIMITED"},{"lang":"hk","v":"偉隆貿易有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635587","names":[{"lang":"en","v":"WALLY ENTERPRISES LIMITED"},{"lang":"hk","v":"華力置業有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635611","names":[{"lang":"en","v":"PENDRAGON LICENCES (HK) LIMITED"},{"lang":"hk","v":"奔龍牌照(香港)有限公司"}],"company_since":"1998-02-04","company_dissolved":"2002-11-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635732","names":[{"lang":"en","v":"WEALTHY PARK LIMITED"},{"lang":"hk","v":"利發行有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635640","names":[{"lang":"en","v":"PENDRAGON SMARTRADE (HK) LIMITED"},{"lang":"hk","v":"奔龍商情(香港)有限公司"}],"company_since":"1998-02-04","company_dissolved":"2002-11-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635551","names":[{"lang":"en","v":"WELL CHANCE SHIPPING LIMITED"},{"lang":"hk","v":"滙進船務有限公司"}],"company_since":"1998-02-04","company_dissolved":"2005-02-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635558","names":[{"lang":"en","v":"WIDE INVESTMENTS LIMITED (d2005-12-09)"},{"lang":"hk","v":"廣弘投資有限公司"}],"company_since":"1998-02-04","company_dissolved":"2005-12-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"635681","names":[{"lang":"en","v":"WIN CIRCLE POULTRY SERVICES LIMITED"},{"lang":"hk","v":"宏勝家禽服務有限公司"}],"company_since":"1998-02-04","company_dissolved":"2001-10-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635630","names":[{"lang":"en","v":"WIN PROSPECT INVESTMENT LIMITED"},{"lang":"hk","v":"得昌投資有限公司"}],"company_since":"1998-02-04","company_dissolved":"2010-02-05","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635666","names":[{"lang":"en","v":"WIN PROSPECT LIMITED (d2003-03-21)"},{"lang":"hk","v":"運佳有限公司"}],"company_since":"1998-02-04","company_dissolved":"2003-03-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635668","names":[{"lang":"en","v":"WING FUNG ENTERPRISE SHAREHOLDINGS LIMITED"},{"lang":"hk","v":"永豐企業股份有限公司"}],"company_since":"1998-02-04","company_dissolved":"2003-10-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635698","names":[{"lang":"en","v":"WING KEI TRANSPORTATION COMPANY LIMITED"},{"lang":"hk","v":"榮基運輸(中港)有限公司"}],"company_since":"1998-02-04","company_dissolved":"2011-09-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635600","names":[{"lang":"en","v":"WING KIN INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"榮建國際集團有限公司"}],"company_since":"1998-02-04","company_dissolved":"2016-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635545","names":[{"lang":"en","v":"REPUBLIC ENTERPRISES LIMITED (d2005-02-04)"},{"lang":"hk","v":"新陽企業有限公司"}],"company_since":"1998-02-04","company_dissolved":"2005-02-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635543","names":[{"lang":"en","v":"WING KWONG SEWING MACHINE CO. LIMITED"},{"lang":"hk","v":"永光針車行有限公司"}],"company_since":"1998-02-04","company_dissolved":"2016-04-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635580","names":[{"lang":"en","v":"WING LOK PRINTING COMPANY LIMITED"},{"lang":"hk","v":"永樂印刷有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635556","names":[{"lang":"en","v":"WINNER BASE HOLDINGS LIMITED (d2005-02-04)"},{"lang":"hk","v":"威基集團有限公司"}],"company_since":"1998-02-04","company_dissolved":"2005-02-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635623","names":[{"lang":"en","v":"WINRICH GROUP LIMITED"},{"lang":"hk","v":"深豐集團有限公司"}],"company_since":"1998-02-04","company_dissolved":"2002-06-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635728","names":[{"lang":"en","v":"YEARGO TRANSPORTATION LIMITED"},{"lang":"hk","v":"意高運輸有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635606","names":[{"lang":"en","v":"YOUTHFUL INVESTMENTS LIMITED"},{"lang":"hk","v":"盈豐投資有限公司"}],"company_since":"1998-02-04","company_dissolved":"2001-03-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635577","names":[{"lang":"en","v":"ZANG &amp; HOLT ASSOCIATES LIMITED"},{"lang":"hk","v":"星河聯合有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635608","names":[{"lang":"en","v":"TIGER HOLDINGS LIMITED (HK)"},{"lang":"hk","v":"虎威集團有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635604","names":[{"lang":"en","v":"TOP IDEA HOLDINGS LIMITED"},{"lang":"hk","v":"綽藝集團有限公司"}],"company_since":"1998-02-04","company_dissolved":"2002-08-02","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635597","names":[{"lang":"en","v":"UNO Tech (Holdings) Limited"},{"lang":"hk","v":"盈創力(控股)有限公司"}],"company_since":"1998-02-04","company_dissolved":"2008-09-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635723","names":[{"lang":"en","v":"WEBSUBJECT SYSTEM LIMITED"},{"lang":"hk","v":"華網系統有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635645","names":[{"lang":"en","v":"SUNDAY COMPUTER LIMITED"},{"lang":"hk","v":"新地電腦有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"635658","names":[{"lang":"en","v":"DDG LIMITED (d2002-10-25)"}],"company_since":"1998-02-04","company_dissolved":"2002-10-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"635705","names":[{"lang":"en","v":"GOLD SUCCESS ENTERPRISES LIMITED (d2005-09-16)"},{"lang":"hk","v":"卓成企業有限公司"}],"company_since":"1998-02-04","company_dissolved":"2005-09-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"635663","names":[{"lang":"en","v":"GRAND PROSPECT DEVELOPMENT LIMITED"},{"lang":"hk","v":"鵬豐發展有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"635635","names":[{"lang":"en","v":"HONG KONG CHUANG YE INTERNATIONAL INVESTMENT GROUP LIMITED"},{"lang":"hk","v":"香港創業國際投資集團有限公司"}],"company_since":"1998-02-04","company_dissolved":"2007-04-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635627","names":[{"lang":"en","v":"LINK FORTUNE HOLDINGS LIMITED"},{"lang":"hk","v":"利財集團有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635632","names":[{"lang":"en","v":"LONG PROSPECT TRADING LIMITED"},{"lang":"hk","v":"鴻祥貿易有限公司"}],"company_since":"1998-02-04","company_dissolved":"2002-09-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635572","names":[{"lang":"en","v":"MARVEL ENTERPRISES LIMITED"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"635678","names":[{"lang":"en","v":"MAXFLIGHT (ASIA) CORPORATION LIMITED"}],"company_since":"1998-02-04","company_dissolved":"2017-10-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635662","names":[{"lang":"en","v":"HONOUR POWER DEVELOPMENT LIMITED"},{"lang":"hk","v":"誠譽發展有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635727","names":[{"lang":"en","v":"MEGA PEAK LIMITED (d2007-10-18)"},{"lang":"hk","v":"順峰有限公司"}],"company_since":"1998-02-04","company_dissolved":"2007-10-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635553","names":[{"lang":"en","v":"LPM ENGINEERING LIMITED"},{"lang":"hk","v":"香港斜坡工程有限公司"}],"company_since":"1998-02-04","company_dissolved":"2004-04-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635593","names":[{"lang":"en","v":"MEGA RETURN INVESTMENTS LIMITED"},{"lang":"hk","v":"詠利投資有限公司"}],"company_since":"1998-02-04","company_dissolved":"2002-03-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635655","names":[{"lang":"en","v":"MEGO CONSTRUCTION (CHINA) LIMITED"},{"lang":"hk","v":"美高建設(中國)有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635610","names":[{"lang":"en","v":"IN-COM TECHNOLOGY COMPANY LIMITED"},{"lang":"hk","v":"天域電腦科技有限公司"}],"company_since":"1998-02-04","company_dissolved":"2007-06-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635602","names":[{"lang":"en","v":"MIRACLE LUCK LIMITED"},{"lang":"hk","v":"濠達有限公司"}],"company_since":"1998-02-04","company_dissolved":"2012-02-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635559","names":[{"lang":"en","v":"MORROW STAR HOLDINGS LIMITED"},{"lang":"hk","v":"明星集團有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635542","names":[{"lang":"en","v":"NEW DIGITAL TECHNOLOGY LIMITED"},{"lang":"hk","v":"安達斯數字系統有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635734","names":[{"lang":"en","v":"INFINITY (DEVELOPMENT) TRADING LIMITED"},{"lang":"hk","v":"永恒(發展)貿易有限公司"}],"company_since":"1998-02-04","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635735","names":[{"lang":"en","v":"NEW VIGOR INTERNATIONAL ENTERPRISES CO. LIMITED"},{"lang":"hk","v":"燊燊貿易有限公司"}],"company_since":"1998-02-04","company_dissolved":"2003-02-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635675","names":[{"lang":"en","v":"NOBLE BRIGHT DEVELOPMENT LIMITED"},{"lang":"hk","v":"耀暉發展有限公司"}],"company_since":"1998-02-04","company_dissolved":"2019-09-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635708","names":[{"lang":"en","v":"NOBLE KING INTERNATIONAL LIMITED"},{"lang":"hk","v":"威煌國際有限公司"}],"company_since":"1998-02-04","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635620","names":[{"lang":"en","v":"NUTRITIONAL FOOD PRODUCTION COMPANY LIMITED"},{"lang":"hk","v":"營養膳有限公司"}],"company_since":"1998-02-04","company_dissolved":"2005-02-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635574","names":[{"lang":"en","v":"INTERSTAR HONG KONG COMPANY LIMITED"},{"lang":"hk","v":"星座國際香港有限公司"}],"company_since":"1998-02-04","company_dissolved":"2009-09-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635718","names":[{"lang":"en","v":"OPEN GROUP INVESTMENT LIMITED"},{"lang":"hk","v":"八合投資有限公司"}],"company_since":"1998-02-04","company_dissolved":"2003-07-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635659","names":[{"lang":"en","v":"J &amp; D (ASIA) LIMITED (d2002-05-24)"},{"lang":"hk","v":"捷登(亞洲)有限公司"}],"company_since":"1998-02-04","company_dissolved":"2002-05-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635676","names":[{"lang":"en","v":"OR PARTNER INTEGRATED INFORMATION SYSTEMS ASIA-PACIFIC LIMITED"},{"lang":"hk","v":"歐雅集成信息系統亞太有限公司"}],"company_since":"1998-02-04","company_dissolved":"2006-01-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635540","names":[{"lang":"en","v":"JOYFUL TREND LIMITED"},{"lang":"hk","v":"愉意有限公司"}],"company_since":"1998-02-04","company_dissolved":"2019-02-01","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635726","names":[{"lang":"en","v":"PAULINE AIRPORT FLORIST LIMITED"},{"lang":"hk","v":"佩妍機場花廊有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635643","names":[{"lang":"en","v":"PENDRAGON AUTOMATION SYSTEMS (HK) LIMITED"},{"lang":"hk","v":"奔龍自動化系統(香港)有限公司"}],"company_since":"1998-02-04","company_dissolved":"2002-11-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635573","names":[{"lang":"en","v":"JP INC LIMITED (d2005-02-04)"},{"lang":"hk","v":"進明出版社有限公司"}],"company_since":"1998-02-04","company_dissolved":"2005-02-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635581","names":[{"lang":"en","v":"K-MARK INVESTMENT LIMITED"}],"company_since":"1998-02-04","company_dissolved":"2010-07-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635710","names":[{"lang":"en","v":"KA WANG HANDBAG COMPANY LIMITED"},{"lang":"hk","v":"嘉宏手袋有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635669","names":[{"lang":"en","v":"POLY MINE LIMITED"},{"lang":"hk","v":"寶捷有限公司"}],"company_since":"1998-02-04","company_dissolved":"2004-12-31","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635713","names":[{"lang":"en","v":"KAM WING (H.K.) FASHION LIMITED"},{"lang":"hk","v":"錦榮(香港)服裝有限公司"}],"company_since":"1998-02-04","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635730","names":[{"lang":"en","v":"POWER CONCORD LIMITED"},{"lang":"hk","v":"成卓有限公司"}],"company_since":"1998-02-04","company_dissolved":"2012-08-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635677","names":[{"lang":"en","v":"KATAR TRADING LIMITED"},{"lang":"hk","v":"嘉達利貿易有限公司"}],"company_since":"1998-02-04","company_dissolved":"2007-06-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635578","names":[{"lang":"en","v":"KAU KEE CONSTRUCTION WORKS LIMITED"},{"lang":"hk","v":"球記土木裝飾工程有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635590","names":[{"lang":"en","v":"REGAL CHAIN LIMITED"},{"lang":"hk","v":"儷盟有限公司"}],"company_since":"1998-02-04","company_dissolved":"2011-09-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635545","names":[{"lang":"en","v":"REPUBLIC ENTERPRISES LIMITED (d2005-02-04)"},{"lang":"hk","v":"新陽企業有限公司"}],"company_since":"1998-02-04","company_dissolved":"2005-02-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635690","names":[{"lang":"en","v":"PROFIT MOUNTAIN ENTERPRISES LIMITED"},{"lang":"hk","v":"潤山企業有限公司"}],"company_since":"1998-02-04","company_dissolved":"2005-10-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635607","names":[{"lang":"en","v":"RIGHT HORSE INVESTMENTS LIMITED"},{"lang":"hk","v":"滙雄投資有限公司"}],"company_since":"1998-02-04","company_dissolved":"2002-07-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635684","names":[{"lang":"en","v":"SHIBATA INVESTMENT CONSULTANTS COMPANY LIMITED"},{"lang":"hk","v":"柴田投資顧問有限公司"}],"company_since":"1998-02-04","company_dissolved":"2003-08-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635537","names":[{"lang":"en","v":"SIMON FEN HIN COMPANY LIMITED"},{"lang":"hk","v":"森文宏興有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635672","names":[{"lang":"en","v":"SINO WISDOM LIMITED (d2001-07-13)"},{"lang":"hk","v":"華振有限公司"}],"company_since":"1998-02-04","company_dissolved":"2001-07-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635707","names":[{"lang":"en","v":"SKY FOND INTERNATIONAL LIMITED"},{"lang":"hk","v":"天豐國際有限公司"}],"company_since":"1998-02-04","company_dissolved":"2006-06-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635603","names":[{"lang":"en","v":"SMART CHAMPION HOLDINGS LIMITED (d2005-02-04)"},{"lang":"hk","v":"威譽集團有限公司"}],"company_since":"1998-02-04","company_dissolved":"2005-02-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635729","names":[{"lang":"en","v":"SOUTH WING MACHINERY COMPANY LIMITED"},{"lang":"hk","v":"南榮機械有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635557","names":[{"lang":"en","v":"STARLUX INVESTMENTS LIMITED (d2009-08-21)"},{"lang":"hk","v":"星河投資有限公司"}],"company_since":"1998-02-04","company_dissolved":"2009-08-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635570","names":[{"lang":"en","v":"SUN CHAIN (HONG KONG) LIMITED"},{"lang":"hk","v":"森昌(香港)有限公司"}],"company_since":"1998-02-04","company_dissolved":"2003-05-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635591","names":[{"lang":"en","v":"SUPER TALENT ENTERPRISES LIMITED"},{"lang":"hk","v":"智濠企業有限公司"}],"company_since":"1998-02-04","company_dissolved":"2002-08-23","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635619","names":[{"lang":"en","v":"SURE BRIGHT INTERNATIONAL LIMITED (d2002-06-21)"},{"lang":"hk","v":"耀生國際有限公司"}],"company_since":"1998-02-04","company_dissolved":"2002-06-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635624","names":[{"lang":"en","v":"SURE PROSPECT INTERNATIONAL LIMITED"},{"lang":"hk","v":"昌潤國際有限公司"}],"company_since":"1998-02-04","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635660","names":[{"lang":"en","v":"SURE SUCCESS INTERNATIONAL LIMITED (d2003-06-20)"},{"lang":"hk","v":"盛志國際有限公司"}],"company_since":"1998-02-04","company_dissolved":"2003-06-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635721","names":[{"lang":"en","v":"TAI HING COMPUTER KNITTING FACTORY LIMITED"},{"lang":"hk","v":"大興電腦針織廠有限公司"}],"company_since":"1998-02-04","company_dissolved":"2020-04-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635589","names":[{"lang":"en","v":"TAI YIP (INT'L) LOGISTIC LIMITED"},{"lang":"hk","v":"泰業國際物流有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635626","names":[{"lang":"en","v":"TECHNOLOGY CAPITAL (H.K.) LIMITED"},{"lang":"hk","v":"科技資本(香港)有限公司"}],"company_since":"1998-02-04","company_dissolved":"2014-03-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635616","names":[{"lang":"en","v":"N.I.K.S. COMPANY LIMITED"},{"lang":"hk","v":"香港森光有限公司"}],"company_since":"1998-02-04","company_dissolved":"2005-06-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635583","names":[{"lang":"en","v":"UNIVERSAL EXPORTS LIMITED (HK)"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635597","names":[{"lang":"en","v":"UNO Tech (Holdings) Limited"},{"lang":"hk","v":"盈創力(控股)有限公司"}],"company_since":"1998-02-04","company_dissolved":"2008-09-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635653","names":[{"lang":"en","v":"TRAVEL PRODUCTS EUROPE LIMITED"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635584","names":[{"lang":"en","v":"VISION BUILDING MATERIALS LIMITED"},{"lang":"hk","v":"偉信建業有限公司"}],"company_since":"1998-02-04","company_dissolved":"2011-11-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635712","names":[{"lang":"en","v":"VIVIDWORKS LIMITED"}],"company_since":"1998-02-04","company_dissolved":"2004-09-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635568","names":[{"lang":"en","v":"WAI LUNG TRADING LIMITED"},{"lang":"hk","v":"偉隆貿易有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635587","names":[{"lang":"en","v":"WALLY ENTERPRISES LIMITED"},{"lang":"hk","v":"華力置業有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635732","names":[{"lang":"en","v":"WEALTHY PARK LIMITED"},{"lang":"hk","v":"利發行有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635723","names":[{"lang":"en","v":"WEBSUBJECT SYSTEM LIMITED"},{"lang":"hk","v":"華網系統有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635551","names":[{"lang":"en","v":"WELL CHANCE SHIPPING LIMITED"},{"lang":"hk","v":"滙進船務有限公司"}],"company_since":"1998-02-04","company_dissolved":"2005-02-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635558","names":[{"lang":"en","v":"WIDE INVESTMENTS LIMITED (d2005-12-09)"},{"lang":"hk","v":"廣弘投資有限公司"}],"company_since":"1998-02-04","company_dissolved":"2005-12-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635630","names":[{"lang":"en","v":"WIN PROSPECT INVESTMENT LIMITED"},{"lang":"hk","v":"得昌投資有限公司"}],"company_since":"1998-02-04","company_dissolved":"2010-02-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635666","names":[{"lang":"en","v":"WIN PROSPECT LIMITED (d2003-03-21)"},{"lang":"hk","v":"運佳有限公司"}],"company_since":"1998-02-04","company_dissolved":"2003-03-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635668","names":[{"lang":"en","v":"WING FUNG ENTERPRISE SHAREHOLDINGS LIMITED"},{"lang":"hk","v":"永豐企業股份有限公司"}],"company_since":"1998-02-04","company_dissolved":"2003-10-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"635698","names":[{"lang":"en","v":"WING KEI TRANSPORTATION COMPANY LIMITED"},{"lang":"hk","v":"榮基運輸(中港)有限公司"}],"company_since":"1998-02-04","company_dissolved":"2011-09-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635642","names":[{"lang":"en","v":"PENDRAGON CORDYCEPS PRODUCTS (HK) LIMITED"},{"lang":"hk","v":"奔龍蟲草製品(香港)有限公司"}],"company_since":"1998-02-04","company_dissolved":"2002-11-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635700","names":[{"lang":"en","v":"TIEN SHAN (H.K.) ENTERPRISE CO. LIMITED"},{"lang":"hk","v":"天山香港實業股份有限公司"}],"company_since":"1998-02-04","company_dissolved":"2006-07-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635600","names":[{"lang":"en","v":"WING KIN INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"榮建國際集團有限公司"}],"company_since":"1998-02-04","company_dissolved":"2016-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635577","names":[{"lang":"en","v":"ZANG &amp; HOLT ASSOCIATES LIMITED"},{"lang":"hk","v":"星河聯合有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"635546","names":[{"lang":"en","v":"STRATEGY HOLDINGS INTERNATIONAL LIMITED"},{"lang":"hk","v":"天策集團國際有限公司"}],"company_since":"1998-02-04","company_dissolved":"2016-09-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"635596","names":[{"lang":"en","v":"SUN HUNG WAN TRANSPORTATION COMPANY LIMITED"},{"lang":"hk","v":"新鴻運貨運有限公司"}],"company_since":"1998-02-04","company_dissolved":"2007-09-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635645","names":[{"lang":"en","v":"SUNDAY COMPUTER LIMITED"},{"lang":"hk","v":"新地電腦有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635628","names":[{"lang":"en","v":"TA HING RESTAURANT &amp; TA HING SEAFOOD RESTAURANT LIMITED"},{"lang":"hk","v":"大興餐廳大興海鮮酒家有限公司"}],"company_since":"1998-02-04","company_dissolved":"2008-09-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635634","names":[{"lang":"en","v":"TELFORE INTERNATIONAL LIMITED"},{"lang":"hk","v":"霆科國際有限公司"}],"company_since":"1998-02-04","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635608","names":[{"lang":"en","v":"TIGER HOLDINGS LIMITED (HK)"},{"lang":"hk","v":"虎威集團有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635714","names":[{"lang":"en","v":"TOYO ELECTRIC (HK) ENTERPRISE CO. LIMITED"},{"lang":"hk","v":"通用電器(香港)企業有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635598","names":[{"lang":"en","v":"UNO Tech Enterprises Limited"},{"lang":"hk","v":"盈創力實業有限公司"}],"company_since":"1998-02-04","company_dissolved":"2008-09-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635724","names":[{"lang":"en","v":"VASSAR INTERNATIONAL LIMITED (d2002-04-19)"},{"lang":"hk","v":"華廈科電有限公司"}],"company_since":"1998-02-04","company_dissolved":"2002-04-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635618","names":[{"lang":"en","v":"WAI LAM DECORATION COMPANY LIMITED"},{"lang":"hk","v":"偉林裝修有限公司"}],"company_since":"1998-02-04","company_dissolved":"2003-06-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"635622","names":[{"lang":"en","v":"WELL RICH GROUP LIMITED"},{"lang":"hk","v":"威富集團有限公司"}],"company_since":"1998-02-04","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"635543","names":[{"lang":"en","v":"WING KWONG SEWING MACHINE CO. LIMITED"},{"lang":"hk","v":"永光針車行有限公司"}],"company_since":"1998-02-04","company_dissolved":"2016-04-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635580","names":[{"lang":"en","v":"WING LOK PRINTING COMPANY LIMITED"},{"lang":"hk","v":"永樂印刷有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635556","names":[{"lang":"en","v":"WINNER BASE HOLDINGS LIMITED (d2005-02-04)"},{"lang":"hk","v":"威基集團有限公司"}],"company_since":"1998-02-04","company_dissolved":"2005-02-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635623","names":[{"lang":"en","v":"WINRICH GROUP LIMITED"},{"lang":"hk","v":"深豐集團有限公司"}],"company_since":"1998-02-04","company_dissolved":"2002-06-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635728","names":[{"lang":"en","v":"YEARGO TRANSPORTATION LIMITED"},{"lang":"hk","v":"意高運輸有限公司"}],"company_since":"1998-02-04","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"635547","names":[{"lang":"en","v":"WEALTHY STAR HOLDINGS LIMITED (d2015-04-30)"},{"lang":"hk","v":"宏星集團有限公司"}],"company_since":"1998-02-04","company_dissolved":"2015-04-30","company_type_txt":"Private, ltd by shares"},
