undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"856386","names":[{"lang":"en","v":"CHINA PALACE LIMITED"},{"lang":"hk","v":"華庭有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856198","names":[{"lang":"en","v":"CHINESE WINNING LIMITED (d2019-04-26)"},{"lang":"hk","v":"成中有限公司"}],"company_since":"2003-08-06","company_dissolved":"2019-04-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856347","names":[{"lang":"en","v":"CHONG KIN ENGINEERING LIMITED"},{"lang":"hk","v":"創健工程有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856235","names":[{"lang":"en","v":"CHUNG HING PRECISION WATCHES COMPANY LIMITED"},{"lang":"hk","v":"中興精密錶業有限公司"}],"company_since":"2003-08-06","company_dissolved":"2019-04-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856231","names":[{"lang":"en","v":"CHUNGYIP INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"松葉國際有限公司"}],"company_since":"2003-08-06","company_dissolved":"2009-12-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856440","names":[{"lang":"en","v":"CIRCUIT SOLUTIONS HONG KONG LIMITED"}],"company_since":"2003-08-06","company_dissolved":"2005-10-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856361","names":[{"lang":"en","v":"CITIBEST DEVELOPMENT LIMITED"},{"lang":"hk","v":"煒栢發展有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856358","names":[{"lang":"en","v":"CITIBEST ENGINEERING LIMITED (d2007-12-28)"},{"lang":"hk","v":"信威工程有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-12-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856320","names":[{"lang":"en","v":"CHILDREN'S INSTITUTE OF HONG KONG LIMITED (THE)"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
{"tax_id":"856356","names":[{"lang":"en","v":"CHINA MINITOWN HOLDINGS LIMITED"},{"lang":"hk","v":"中國小城鎮控股有限公司"}],"company_since":"2003-08-06","company_dissolved":"2019-05-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856312","names":[{"lang":"en","v":"CAYIE INTERNATIONAL GROUP LIMITED"},{"lang":"hk","v":"凱羿國際集團有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856351","names":[{"lang":"en","v":"CHARTERED ENVIRONMENTALIST LIMITED"},{"lang":"hk","v":"環保工程顧問有限公司"}],"company_since":"2003-08-06","company_dissolved":"2012-05-02","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856135","names":[{"lang":"en","v":"CLEM ENTERPRISES LIMITED"},{"lang":"hk","v":"卡麗文有限公司"}],"company_since":"2003-08-06","company_dissolved":"2009-12-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856074","names":[{"lang":"en","v":"CREATIVE FORWARD LIMITED"},{"lang":"hk","v":"步創昇有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856304","names":[{"lang":"en","v":"CLOVER COLLECTIONS LIMITED (d2008-03-20)"},{"lang":"hk","v":"歌達有限公司"}],"company_since":"2003-08-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856098","names":[{"lang":"en","v":"CRISTALLO COMPANY LIMITED (d2009-12-18)"}],"company_since":"2003-08-06","company_dissolved":"2009-12-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856124","names":[{"lang":"en","v":"CMC INTERNATIONAL INDUSTRIES LIMITED"},{"lang":"hk","v":"中原國際機器有限公司"}],"company_since":"2003-08-06","company_dissolved":"2019-04-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856457","names":[{"lang":"en","v":"CONFLUENCE TEA COMPANY LIMITED"},{"lang":"hk","v":"方圓茶滙有限公司"}],"company_since":"2003-08-06","company_dissolved":"2010-06-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856365","names":[{"lang":"en","v":"DIM LINK ENGINEERING LIMITED"},{"lang":"hk","v":"添明工程有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856163","names":[{"lang":"en","v":"CONECTL LIMITED"}],"company_since":"2003-08-06","company_dissolved":"2010-07-16","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856313","names":[{"lang":"en","v":"EAST TEXTILE (HONG KONG) LIMITED"},{"lang":"hk","v":"東方紡織品(香港)有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856311","names":[{"lang":"en","v":"EAGLE CENTURY DEVELOPMENT LIMITED"},{"lang":"hk","v":"鷹誌發展有限公司"}],"company_since":"2003-08-06","company_dissolved":"2004-12-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856359","names":[{"lang":"en","v":"EAST BRIGHT CHINESE MEDICAL ACUPUNTCTURE HEALING CTR. CO LIMITED"},{"lang":"hk","v":"東明中醫針炙治療中心有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-03-16","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856117","names":[{"lang":"en","v":"CRYSTAL ELECTRONICS INDUSTRIAL LIMITED"},{"lang":"hk","v":"銳晶電子有限公司"}],"company_since":"2003-08-06","company_dissolved":"2008-04-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"856382","names":[{"lang":"en","v":"E-KNOWLEDGE LEARNING INSTITUTE LIMITED"},{"lang":"hk","v":"尚學堂教育有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856325","names":[{"lang":"en","v":"ETERNAL (HK) INDUSTRIAL CO., LIMITED"},{"lang":"hk","v":"永恒(香港)實業有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"856332","names":[{"lang":"en","v":"COYOWEY TECHNOLOGY (H.K.) CO., LIMITED"},{"lang":"hk","v":"冠華科技(香港)有限公司"}],"company_since":"2003-08-06","company_dissolved":"2009-01-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856197","names":[{"lang":"en","v":"EASTERN RICHLY LIMITED"},{"lang":"hk","v":"東永有限公司"}],"company_since":"2003-08-06","company_dissolved":"2008-03-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856153","names":[{"lang":"en","v":"CHINA ORIENTAL CULTURE &amp; TECHNOLOGIES LIMITED"},{"lang":"hk","v":"中國東方文化科技有限公司"}],"company_since":"2003-08-06","company_dissolved":"2009-01-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856308","names":[{"lang":"en","v":"EASYTEK ELECTRONIC CO., LIMITED"},{"lang":"hk","v":"易科電子股份有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856461","names":[{"lang":"en","v":"FAITHFUL PRODUCTS (HK) LIMITED"},{"lang":"hk","v":"裕信實業(香港)有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856360","names":[{"lang":"en","v":"EVERTIME HOLDINGS LIMITED"},{"lang":"hk","v":"佳泰集團有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856203","names":[{"lang":"en","v":"EXCEL ELEGANT LIMITED (d2007-12-21)"},{"lang":"hk","v":"卓麗有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856449","names":[{"lang":"en","v":"EURO-XP CO., LIMITED"},{"lang":"hk","v":"歐陸世家有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856424","names":[{"lang":"en","v":"EUROCO INTERNATIONAL FREIGHT (HK) LIMITED"},{"lang":"hk","v":"朗歐國際貨運(香港)有限公司"}],"company_since":"2003-08-06","company_dissolved":"2004-06-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856374","names":[{"lang":"en","v":"FAME BRILLIANT LIMITED"},{"lang":"hk","v":"輝譽有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856126","names":[{"lang":"en","v":"FAI PO GROUP LIMITED"},{"lang":"hk","v":"輝寶集團有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856376","names":[{"lang":"en","v":"FINEGOLD CORPORATION LIMITED"},{"lang":"hk","v":"耀金有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856183","names":[{"lang":"en","v":"FAVOR HONOR INDUSTRIAL COMPANY LIMITED"},{"lang":"hk","v":"恩榮實業有限公司"}],"company_since":"2003-08-06","company_dissolved":"2014-12-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856225","names":[{"lang":"en","v":"FARCO TECHNOLOGY LIMITED"},{"lang":"hk","v":"科豪科技有限公司"}],"company_since":"2003-08-06","company_dissolved":"2015-07-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856107","names":[{"lang":"en","v":"Excellent Diamonds Limited"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856286","names":[{"lang":"en","v":"FINEGRAND LIMITED"},{"lang":"hk","v":"浩亮有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856236","names":[{"lang":"en","v":"FEI DA ASIA HOLDINGS LIMITED"},{"lang":"hk","v":"飛達亞洲集團有限公司"}],"company_since":"2003-08-06","company_dissolved":"2014-04-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856260","names":[{"lang":"en","v":"EXCEL PLANNING LIMITED"},{"lang":"hk","v":"卓斯有限公司"}],"company_since":"2003-08-06","company_dissolved":"2008-02-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856131","names":[{"lang":"en","v":"FIRST CAMBODIA AIRLINES (HK) LIMITED"},{"lang":"hk","v":"柬埔寨第一航空(香港)有限公司"}],"company_since":"2003-08-06","company_dissolved":"2006-02-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856326","names":[{"lang":"en","v":"CITIBEST LIMITED (d2007-12-21)"}],"company_since":"2003-08-06","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856289","names":[{"lang":"en","v":"FAME GLORY CORPORATION LIMITED (d2016-02-05)"},{"lang":"hk","v":"裕銘有限公司"}],"company_since":"2003-08-06","company_dissolved":"2016-02-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856418","names":[{"lang":"en","v":"FINE MERIT LIMITED"},{"lang":"hk","v":"德亮有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856357","names":[{"lang":"en","v":"EVERLINK INTERNATIONAL LIMITED"},{"lang":"hk","v":"協基國際有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"856326","names":[{"lang":"en","v":"CITIBEST LIMITED (d2007-12-21)"}],"company_since":"2003-08-06","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856135","names":[{"lang":"en","v":"CLEM ENTERPRISES LIMITED"},{"lang":"hk","v":"卡麗文有限公司"}],"company_since":"2003-08-06","company_dissolved":"2009-12-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"856386","names":[{"lang":"en","v":"CHINA PALACE LIMITED"},{"lang":"hk","v":"華庭有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856332","names":[{"lang":"en","v":"COYOWEY TECHNOLOGY (H.K.) CO., LIMITED"},{"lang":"hk","v":"冠華科技(香港)有限公司"}],"company_since":"2003-08-06","company_dissolved":"2009-01-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856074","names":[{"lang":"en","v":"CREATIVE FORWARD LIMITED"},{"lang":"hk","v":"步創昇有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856098","names":[{"lang":"en","v":"CRISTALLO COMPANY LIMITED (d2009-12-18)"}],"company_since":"2003-08-06","company_dissolved":"2009-12-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856117","names":[{"lang":"en","v":"CRYSTAL ELECTRONICS INDUSTRIAL LIMITED"},{"lang":"hk","v":"銳晶電子有限公司"}],"company_since":"2003-08-06","company_dissolved":"2008-04-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856347","names":[{"lang":"en","v":"CHONG KIN ENGINEERING LIMITED"},{"lang":"hk","v":"創健工程有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856382","names":[{"lang":"en","v":"E-KNOWLEDGE LEARNING INSTITUTE LIMITED"},{"lang":"hk","v":"尚學堂教育有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856235","names":[{"lang":"en","v":"CHUNG HING PRECISION WATCHES COMPANY LIMITED"},{"lang":"hk","v":"中興精密錶業有限公司"}],"company_since":"2003-08-06","company_dissolved":"2019-04-26","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856311","names":[{"lang":"en","v":"EAGLE CENTURY DEVELOPMENT LIMITED"},{"lang":"hk","v":"鷹誌發展有限公司"}],"company_since":"2003-08-06","company_dissolved":"2004-12-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856313","names":[{"lang":"en","v":"EAST TEXTILE (HONG KONG) LIMITED"},{"lang":"hk","v":"東方紡織品(香港)有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856197","names":[{"lang":"en","v":"EASTERN RICHLY LIMITED"},{"lang":"hk","v":"東永有限公司"}],"company_since":"2003-08-06","company_dissolved":"2008-03-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856198","names":[{"lang":"en","v":"CHINESE WINNING LIMITED (d2019-04-26)"},{"lang":"hk","v":"成中有限公司"}],"company_since":"2003-08-06","company_dissolved":"2019-04-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856440","names":[{"lang":"en","v":"CIRCUIT SOLUTIONS HONG KONG LIMITED"}],"company_since":"2003-08-06","company_dissolved":"2005-10-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856430","names":[{"lang":"en","v":"EASY GO ENVIRONMENTAL SERVICE LIMITED"},{"lang":"hk","v":"怡高環保服務有限公司"}],"company_since":"2003-08-06","company_dissolved":"2004-10-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856308","names":[{"lang":"en","v":"EASYTEK ELECTRONIC CO., LIMITED"},{"lang":"hk","v":"易科電子股份有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856411","names":[{"lang":"en","v":"EF Language Solutions Hong Kong Limited"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856358","names":[{"lang":"en","v":"CITIBEST ENGINEERING LIMITED (d2007-12-28)"},{"lang":"hk","v":"信威工程有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-12-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856449","names":[{"lang":"en","v":"EURO-XP CO., LIMITED"},{"lang":"hk","v":"歐陸世家有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856424","names":[{"lang":"en","v":"EUROCO INTERNATIONAL FREIGHT (HK) LIMITED"},{"lang":"hk","v":"朗歐國際貨運(香港)有限公司"}],"company_since":"2003-08-06","company_dissolved":"2004-06-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856378","names":[{"lang":"en","v":"EVERBRIGHT DEVELOPMENT INTERNATIONAL LIMITED"},{"lang":"hk","v":"光大發展國際有限公司"}],"company_since":"2003-08-06","company_dissolved":"2011-01-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856357","names":[{"lang":"en","v":"EVERLINK INTERNATIONAL LIMITED"},{"lang":"hk","v":"協基國際有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856360","names":[{"lang":"en","v":"EVERTIME HOLDINGS LIMITED"},{"lang":"hk","v":"佳泰集團有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856124","names":[{"lang":"en","v":"CMC INTERNATIONAL INDUSTRIES LIMITED"},{"lang":"hk","v":"中原國際機器有限公司"}],"company_since":"2003-08-06","company_dissolved":"2019-04-26","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856203","names":[{"lang":"en","v":"EXCEL ELEGANT LIMITED (d2007-12-21)"},{"lang":"hk","v":"卓麗有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856260","names":[{"lang":"en","v":"EXCEL PLANNING LIMITED"},{"lang":"hk","v":"卓斯有限公司"}],"company_since":"2003-08-06","company_dissolved":"2008-02-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"856325","names":[{"lang":"en","v":"ETERNAL (HK) INDUSTRIAL CO., LIMITED"},{"lang":"hk","v":"永恒(香港)實業有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856424","names":[{"lang":"en","v":"EUROCO INTERNATIONAL FREIGHT (HK) LIMITED"},{"lang":"hk","v":"朗歐國際貨運(香港)有限公司"}],"company_since":"2003-08-06","company_dissolved":"2004-06-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856074","names":[{"lang":"en","v":"CREATIVE FORWARD LIMITED"},{"lang":"hk","v":"步創昇有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-09-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856357","names":[{"lang":"en","v":"EVERLINK INTERNATIONAL LIMITED"},{"lang":"hk","v":"協基國際有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856203","names":[{"lang":"en","v":"EXCEL ELEGANT LIMITED (d2007-12-21)"},{"lang":"hk","v":"卓麗有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856260","names":[{"lang":"en","v":"EXCEL PLANNING LIMITED"},{"lang":"hk","v":"卓斯有限公司"}],"company_since":"2003-08-06","company_dissolved":"2008-02-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856107","names":[{"lang":"en","v":"Excellent Diamonds Limited"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"856304","names":[{"lang":"en","v":"CLOVER COLLECTIONS LIMITED (d2008-03-20)"},{"lang":"hk","v":"歌達有限公司"}],"company_since":"2003-08-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856382","names":[{"lang":"en","v":"E-KNOWLEDGE LEARNING INSTITUTE LIMITED"},{"lang":"hk","v":"尚學堂教育有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"856074","names":[{"lang":"en","v":"CREATIVE FORWARD LIMITED"},{"lang":"hk","v":"步創昇有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-09-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856357","names":[{"lang":"en","v":"EVERLINK INTERNATIONAL LIMITED"},{"lang":"hk","v":"協基國際有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856360","names":[{"lang":"en","v":"EVERTIME HOLDINGS LIMITED"},{"lang":"hk","v":"佳泰集團有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856260","names":[{"lang":"en","v":"EXCEL PLANNING LIMITED"},{"lang":"hk","v":"卓斯有限公司"}],"company_since":"2003-08-06","company_dissolved":"2008-02-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856461","names":[{"lang":"en","v":"FAITHFUL PRODUCTS (HK) LIMITED"},{"lang":"hk","v":"裕信實業(香港)有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856382","names":[{"lang":"en","v":"E-KNOWLEDGE LEARNING INSTITUTE LIMITED"},{"lang":"hk","v":"尚學堂教育有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856190","names":[{"lang":"en","v":"FENTIUM SYSTEMS LIMITED"},{"lang":"hk","v":"飛騰系統有限公司"}],"company_since":"2003-08-06","company_dissolved":"2010-04-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856313","names":[{"lang":"en","v":"EAST TEXTILE (HONG KONG) LIMITED"},{"lang":"hk","v":"東方紡織品(香港)有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856418","names":[{"lang":"en","v":"FINE MERIT LIMITED"},{"lang":"hk","v":"德亮有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856287","names":[{"lang":"en","v":"FINEGAIN CORPORATION LIMITED"},{"lang":"hk","v":"曉達有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856376","names":[{"lang":"en","v":"FINEGOLD CORPORATION LIMITED"},{"lang":"hk","v":"耀金有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856286","names":[{"lang":"en","v":"FINEGRAND LIMITED"},{"lang":"hk","v":"浩亮有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856308","names":[{"lang":"en","v":"EASYTEK ELECTRONIC CO., LIMITED"},{"lang":"hk","v":"易科電子股份有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856131","names":[{"lang":"en","v":"FIRST CAMBODIA AIRLINES (HK) LIMITED"},{"lang":"hk","v":"柬埔寨第一航空(香港)有限公司"}],"company_since":"2003-08-06","company_dissolved":"2006-02-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856196","names":[{"lang":"en","v":"FIRST LINKER LIMITED"},{"lang":"hk","v":"滙協有限公司"}],"company_since":"2003-08-06","company_dissolved":"2016-08-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856259","names":[{"lang":"en","v":"FORCE UNION LIMITED"},{"lang":"hk","v":"力邦有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856325","names":[{"lang":"en","v":"ETERNAL (HK) INDUSTRIAL CO., LIMITED"},{"lang":"hk","v":"永恒(香港)實業有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856339","names":[{"lang":"en","v":"FORTH RIGHT TEXTILES (HK) LIMITED"},{"lang":"hk","v":"福民紡織(香港)有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856132","names":[{"lang":"en","v":"FORTIS DEVELOPMENT LIMITED"},{"lang":"hk","v":"科迪發展有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856310","names":[{"lang":"en","v":"FORWARD BOOK CO LIMITED"},{"lang":"hk","v":"科華圖書出版有限公司"}],"company_since":"2003-08-06","company_dissolved":"2005-10-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856430","names":[{"lang":"en","v":"EASY GO ENVIRONMENTAL SERVICE LIMITED"},{"lang":"hk","v":"怡高環保服務有限公司"}],"company_since":"2003-08-06","company_dissolved":"2004-10-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856449","names":[{"lang":"en","v":"EURO-XP CO., LIMITED"},{"lang":"hk","v":"歐陸世家有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856424","names":[{"lang":"en","v":"EUROCO INTERNATIONAL FREIGHT (HK) LIMITED"},{"lang":"hk","v":"朗歐國際貨運(香港)有限公司"}],"company_since":"2003-08-06","company_dissolved":"2004-06-11","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856406","names":[{"lang":"en","v":"FRANCE DOUDILU (HONGKONG) FASHION DEVELOPMENT LIMITED"},{"lang":"hk","v":"法國都迪路(香港)服飾發展有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856378","names":[{"lang":"en","v":"EVERBRIGHT DEVELOPMENT INTERNATIONAL LIMITED"},{"lang":"hk","v":"光大發展國際有限公司"}],"company_since":"2003-08-06","company_dissolved":"2011-01-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856411","names":[{"lang":"en","v":"EF Language Solutions Hong Kong Limited"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856443","names":[{"lang":"en","v":"FRANCE MICHELLE INT'L CLOTHING LIMITED"},{"lang":"hk","v":"法國蜜雪兒國際時裝有限公司"}],"company_since":"2003-08-06","company_dissolved":"2011-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856121","names":[{"lang":"en","v":"FRANCE MSNU GARMENT GROUP LIMITED"},{"lang":"hk","v":"法國夢仕奴服飾集團有限公司"}],"company_since":"2003-08-06","company_dissolved":"2006-09-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856203","names":[{"lang":"en","v":"EXCEL ELEGANT LIMITED (d2007-12-21)"},{"lang":"hk","v":"卓麗有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856107","names":[{"lang":"en","v":"Excellent Diamonds Limited"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856152","names":[{"lang":"en","v":"FRANCE QISHI PAUL CLOTHING (INTERNATIONAL) LIMITED"},{"lang":"hk","v":"法國奇仕保羅服飾(國際)有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856126","names":[{"lang":"en","v":"FAI PO GROUP LIMITED"},{"lang":"hk","v":"輝寶集團有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856174","names":[{"lang":"en","v":"FRANCE XIAOYAOHE (HONG KONG) CLOTHING &amp; ACCESSORIES LIMITED"},{"lang":"hk","v":"法國逍遙鶴(香港)服飾有限公司"}],"company_since":"2003-08-06","company_dissolved":"2008-07-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856374","names":[{"lang":"en","v":"FAME BRILLIANT LIMITED"},{"lang":"hk","v":"輝譽有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856148","names":[{"lang":"en","v":"FRENCH INTERNATIONAL BRAND GROUP COMPANY LIMITED"},{"lang":"hk","v":"法國國際品牌集團有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856400","names":[{"lang":"en","v":"FULCRA INVESTMENT MANAGEMENT LIMITED"},{"lang":"hk","v":"泓佳投資管理有限公司"}],"company_since":"2003-08-06","company_dissolved":"2019-04-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856289","names":[{"lang":"en","v":"FAME GLORY CORPORATION LIMITED (d2016-02-05)"},{"lang":"hk","v":"裕銘有限公司"}],"company_since":"2003-08-06","company_dissolved":"2016-02-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856225","names":[{"lang":"en","v":"FARCO TECHNOLOGY LIMITED"},{"lang":"hk","v":"科豪科技有限公司"}],"company_since":"2003-08-06","company_dissolved":"2015-07-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856393","names":[{"lang":"en","v":"FURN CONSULT LIMITED"},{"lang":"hk","v":"創意傢具顧問有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-05-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"856195","names":[{"lang":"en","v":"GLOBAL SUCCEED LIMITED"},{"lang":"hk","v":"寶倡有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856288","names":[{"lang":"en","v":"FINE TRADE LIMITED (d2007-07-27)"},{"lang":"hk","v":"貿暉有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-07-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856237","names":[{"lang":"en","v":"GO FILM DISTRIBUTION LIMITED"}],"company_since":"2003-08-06","company_dissolved":"2008-10-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856182","names":[{"lang":"en","v":"GOLD FORTUNE (H.K.) INTERNATIONAL LIMITED"},{"lang":"hk","v":"金富(香港)國際有限公司"}],"company_since":"2003-08-06","company_dissolved":"2009-01-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856337","names":[{"lang":"en","v":"GOLDEN FUJI HOLDINGS (HONG KONG) LIMITED"},{"lang":"hk","v":"金富士控股(香港)有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856087","names":[{"lang":"en","v":"GOLDEN LAKE TECHNOLOGY LIMITED"}],"company_since":"2003-08-06","company_dissolved":"2009-01-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856385","names":[{"lang":"en","v":"GOLDEN PARTNER LIMITED"},{"lang":"hk","v":"金侶有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856228","names":[{"lang":"en","v":"GOLDFOX GARMENT (FAR EAST) INT'L CO., LIMITED"},{"lang":"hk","v":"金狐狸服飾(遠東)國際有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856137","names":[{"lang":"en","v":"G T WILL (H.K.) COMPANY LIMITED"},{"lang":"hk","v":"高日電子(香港)有限公司"}],"company_since":"2003-08-06","company_dissolved":"2015-12-31","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856136","names":[{"lang":"en","v":"GOODHOPE UNION LIMITED"},{"lang":"hk","v":"采協有限公司"}],"company_since":"2003-08-06","company_dissolved":"2016-07-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"856335","names":[{"lang":"en","v":"GRANDISON (ASIA) COMMUNICATIONS LIMITED"},{"lang":"hk","v":"精一(亞洲)傳播有限公司"}],"company_since":"2003-08-06","company_dissolved":"2009-12-31","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856155","names":[{"lang":"en","v":"H.K. VIOLET WINDY DRESS (INT'L) LIMITED"},{"lang":"hk","v":"香港紫雅文迪服飾(國際)有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856346","names":[{"lang":"en","v":"GRANDWAY GLOBAL DEVELOPMENT CO., LIMITED"},{"lang":"hk","v":"科匯國際發展有限公司"}],"company_since":"2003-08-06","company_dissolved":"2014-07-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856364","names":[{"lang":"en","v":"HENMENG PROMOTION LIMITED"},{"lang":"hk","v":"軒茗推廣有限公司"}],"company_since":"2003-08-06","company_dissolved":"2009-12-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856223","names":[{"lang":"en","v":"GREATER CHINA ECONOMIC REGION MAGAZINES LIMITED"},{"lang":"hk","v":"大中華經濟圈雜誌社有限公司"}],"company_since":"2003-08-06","company_dissolved":"2020-06-05","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856267","names":[{"lang":"en","v":"HK MING LEE CO. LIMITED"},{"lang":"hk","v":"香港明利有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856422","names":[{"lang":"en","v":"HOME EDUCATION CENTRE COMPANY LIMITED (THE)"},{"lang":"hk","v":"家教坊有限公司"}],"company_since":"2003-08-06","company_dissolved":"2005-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856392","names":[{"lang":"en","v":"HONG KONG BAO LAN DI SI FURNITURE LIMITED"},{"lang":"hk","v":"香港寶蘭帝斯家具有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856355","names":[{"lang":"en","v":"GUANGZHOU ESAI CULTURE COMMUNICATION COMPANY LIMITED"},{"lang":"hk","v":"東日影業有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856114","names":[{"lang":"en","v":"HONG KONG BILLION (INTERNATIONAL) INVESTMENT LIMITED"},{"lang":"hk","v":"香港億豐(國際)投資有限公司"}],"company_since":"2003-08-06","company_dissolved":"2019-04-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856433","names":[{"lang":"en","v":"HONG KONG EAST-IDEAL INT'L INVESTMENT LIMITED"},{"lang":"hk","v":"香港東方理想國際投資有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856166","names":[{"lang":"en","v":"HONG KONG FEI LI PU ELECTRIC INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"香港飛利浦電器國際集團有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-07-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856300","names":[{"lang":"en","v":"HONG KONG GENTLEMAN MUSICAL INSTRUMENT PRODUCTION LIMITED"},{"lang":"hk","v":"香港紳士樂器製造有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856363","names":[{"lang":"en","v":"HONG KONG HEALTH AND BEAUTY UNION LIMITED (d2006-06-16)"},{"lang":"hk","v":"香港健康美容同業有限公司"}],"company_since":"2003-08-06","company_dissolved":"2006-06-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856207","names":[{"lang":"en","v":"HONG KONG HUANYUAN GROUP COMPANY LIMITED"},{"lang":"hk","v":"香港環源集團有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-01-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856268","names":[{"lang":"en","v":"HONG KONG INTERNATIONAL EXPO LIMITED"},{"lang":"hk","v":"香港國際展覽有限公司"}],"company_since":"2003-08-06","company_dissolved":"2011-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856318","names":[{"lang":"en","v":"HONG KONG JILIN COMPANY LIMITED"},{"lang":"hk","v":"香港巨霖有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856103","names":[{"lang":"en","v":"GREATING INTERNATIONAL LIMITED (d2007-12-21)"},{"lang":"hk","v":"鈞盛國際有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856156","names":[{"lang":"en","v":"H.K. LONGYUAN (INT'L) INDUSTRY LIMITED"},{"lang":"hk","v":"香港隆源(國際)實業有限公司"}],"company_since":"2003-08-06","company_dissolved":"2012-11-16","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856176","names":[{"lang":"en","v":"HONG KONG NEPAL EMPLOYMENT PLACEMENT ASSOCIATION LIMITED"},{"lang":"hk","v":"香港尼泊爾僱傭聯會有限公司"}],"company_since":"2003-08-06","company_dissolved":"2006-10-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856394","names":[{"lang":"en","v":"H.K. MEIXUNDA ELECTRONICS CO., LIMITED"},{"lang":"hk","v":"香港美訊達電子有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856239","names":[{"lang":"en","v":"H.K. SIEMENTS ELECTRIC APPLIANCE LIMITED"},{"lang":"hk","v":"香港西門子電器有限公司"}],"company_since":"2003-08-06","company_dissolved":"2012-12-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856435","names":[{"lang":"en","v":"HONG KONG SUN TIN WAH KNITTING MANUFACTURING CO. LIMITED"},{"lang":"hk","v":"香港新天華織造有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"856340","names":[{"lang":"en","v":"HONG KONG WOOD PRODUCTS LIMITED"},{"lang":"hk","v":"香港木制品有限公司"}],"company_since":"2003-08-06","company_dissolved":"2009-04-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856164","names":[{"lang":"en","v":"HONG KONG YU BO JIAN YE ORGANISM ENGINEERING CO., LIMITED"},{"lang":"hk","v":"香港玉博建業生物工程有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856395","names":[{"lang":"en","v":"HIMALAYA ENTERTAINMENT LIMITED"},{"lang":"hk","v":"喜馬拉亞娛樂有限公司"}],"company_since":"2003-08-06","company_dissolved":"2015-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856120","names":[{"lang":"en","v":"HK (ASIA) INT'L LIMITED"},{"lang":"hk","v":"華坤(亞洲)國際有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856122","names":[{"lang":"en","v":"H.K. WOODPECKER GARMENT INT'L SHARES LIMITED"},{"lang":"hk","v":"香港啄木鳥服飾國際股份有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856349","names":[{"lang":"en","v":"HONGKONG TIANYUANTANG GROUP INTERNATIONAL CO., LIMITED"},{"lang":"hk","v":"香港天元堂集團國際有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856096","names":[{"lang":"en","v":"HSA LIMITED (d2015-07-17)"}],"company_since":"2003-08-06","company_dissolved":"2015-07-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856125","names":[{"lang":"en","v":"HSS - HONG KONG, SHANDONG &amp; SINGAPORE DIAMOND POLISHING &amp; SORTING LIMITED"}],"company_since":"2003-08-06","company_dissolved":"2013-10-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856442","names":[{"lang":"en","v":"HSU BANG ENTERPRISE CO., LIMITED"},{"lang":"hk","v":"旭邦企業有限公司"}],"company_since":"2003-08-06","company_dissolved":"2011-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856417","names":[{"lang":"en","v":"HUGE BASE LIMITED (d2009-09-25)"},{"lang":"hk","v":"鉅基有限公司"}],"company_since":"2003-08-06","company_dissolved":"2009-09-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856294","names":[{"lang":"en","v":"HONGKONG YUBEIER FASHION INT'L GROUP LIMITED"},{"lang":"hk","v":"香港雨貝爾服飾國際集團有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856186","names":[{"lang":"en","v":"HONG KONG LILANG (INTERNATIONAL) COSMETICS LIMITED"},{"lang":"hk","v":"香港力朗(國際)化妝品有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-12-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856438","names":[{"lang":"en","v":"IGTC - INTERNATIONAL GLASS TRADING COMPANY (1992) LIMITED"}],"company_since":"2003-08-06","company_dissolved":"2009-01-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856142","names":[{"lang":"en","v":"HONG KONG PRONTO INDUSTRY COMPANY LIMITED"},{"lang":"hk","v":"香港百浪多實業有限公司"}],"company_since":"2003-08-06","company_dissolved":"2008-04-25","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856247","names":[{"lang":"en","v":"INFINITY PROPERTY MANAGEMENT LIMITED (HK)"},{"lang":"hk","v":"博藝物業管理有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"856199","names":[{"lang":"en","v":"HONG KONG UNITED ACCEPTANCE INVESTMENT LIMITED"},{"lang":"hk","v":"香港齊力諾投資有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856212","names":[{"lang":"en","v":"INNOVA TECHNOLOGY (HK) LIMITED"},{"lang":"hk","v":"怡諾威(香港)股份有限公司"}],"company_since":"2003-08-06","company_dissolved":"2009-01-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856307","names":[{"lang":"en","v":"INTEL ASIA HOLDING LIMITED"},{"lang":"hk","v":"英特爾亞洲控股有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856314","names":[{"lang":"en","v":"HONGKONG FASHION GARMENT LIMITED"},{"lang":"hk","v":"香港時尚時裝有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856295","names":[{"lang":"en","v":"INTERCHINA POWER INVESTMENT COMPANY LIMITED"},{"lang":"hk","v":"國中能源投資有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856232","names":[{"lang":"en","v":"HONGKONG HE LI JIA METAL ELECTRIC PRODUCT LIMITED"},{"lang":"hk","v":"香港合利佳五金電業制品有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-01-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856434","names":[{"lang":"en","v":"ITALY BONY INTERNATIONAL GROUP COMPANY LIMITED"},{"lang":"hk","v":"意大利博妮國際集團有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856167","names":[{"lang":"en","v":"ITALY MAMEYA (INTERNATIONAL) SHOES &amp; FASHION LIMITED"},{"lang":"hk","v":"意大利瑪米婭(國際)鞋服有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856334","names":[{"lang":"en","v":"HONGTAI INTERNATIONAL (HK) LIMITED"},{"lang":"hk","v":"宏泰國際(香港)有限公司"}],"company_since":"2003-08-06","company_dissolved":"2004-09-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856242","names":[{"lang":"en","v":"ITALY VALENTINO (ASIA &amp; PACIFIC) HOLDINGS LIMITED"},{"lang":"hk","v":"意大利華倫天奴(亞太)控股有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856091","names":[{"lang":"en","v":"J PRODUCT LIMITED"}],"company_since":"2003-08-06","company_dissolved":"2009-04-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856178","names":[{"lang":"en","v":"JAPAN CAREFUL INT'L GROUP (HK) LIMITED"},{"lang":"hk","v":"日本凱豐國際集團(香港)有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856192","names":[{"lang":"en","v":"JAPAN FULLS APPLE GARMENT CO., LIMITED"},{"lang":"hk","v":"日本富士‧蘋果服飾有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856169","names":[{"lang":"en","v":"JBL COLLINS CORPORATE ADVISORY SERVICES LIMITED"},{"lang":"hk","v":"德高楊企業顧問有限公司"}],"company_since":"2003-08-06","company_dissolved":"2004-10-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856396","names":[{"lang":"en","v":"JIN XING INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"金星國際控股有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856227","names":[{"lang":"en","v":"JINGFENG TECHNOLOGY DEVELOPMENT (HK) CO., LIMITED"},{"lang":"hk","v":"晶峰科技發展(香港)有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856266","names":[{"lang":"en","v":"HUNG FAT DECORATIONS LIMITED"},{"lang":"hk","v":"鴻發承志有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856168","names":[{"lang":"en","v":"JOINFAST INTERNATIONAL (HK) LIMITED"},{"lang":"hk","v":"香港伽誠國際有限公司"}],"company_since":"2003-08-06","company_dissolved":"2018-05-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856281","names":[{"lang":"en","v":"JOYFAME CORPORATION LIMITED"},{"lang":"hk","v":"嘉譽有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"856157","names":[{"lang":"en","v":"KEYRING PRODUCTION LIMITED"},{"lang":"hk","v":"時來製作有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856149","names":[{"lang":"en","v":"KING BUSINESS INTERNATIONAL (H.K.) CO., LIMITED"},{"lang":"hk","v":"弘業國際(香港)有限公司"}],"company_since":"2003-08-06","company_dissolved":"2005-02-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"856303","names":[{"lang":"en","v":"KML INNOVATION COMPANY LIMITED"},{"lang":"hk","v":"創新機械有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-01-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856080","names":[{"lang":"en","v":"INTEND LIMITED"},{"lang":"hk","v":"閃亮傢俬裝修工程有限公司"}],"company_since":"2003-08-06","company_dissolved":"2010-01-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856088","names":[{"lang":"en","v":"LANCS INTERNATIONAL (H.K.) LIMITED"},{"lang":"hk","v":"蘭皙國際(香港)有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856108","names":[{"lang":"en","v":"LDD ENTERPRISES COMPANY LIMITED"},{"lang":"hk","v":"互通實業有限公司"}],"company_since":"2003-08-06","company_dissolved":"2008-01-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856184","names":[{"lang":"en","v":"ITALY GOOD STYLE (HK) INT'L GROUP LIMITED"},{"lang":"hk","v":"意大利佳派(香港)國際集團有限公司"}],"company_since":"2003-08-06","company_dissolved":"2009-01-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856222","names":[{"lang":"en","v":"ITALY KADAN WANG INT'L FINERY (HK) LIMITED"},{"lang":"hk","v":"意大利卡丹王國際服飾(香港)有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856279","names":[{"lang":"en","v":"LEAD MERIT LIMITED"},{"lang":"hk","v":"領德有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856278","names":[{"lang":"en","v":"LEADEASY CORPORATION LIMITED"},{"lang":"hk","v":"達領有限公司"}],"company_since":"2003-08-06","company_dissolved":"2008-08-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856379","names":[{"lang":"en","v":"LEGAL PERSON MAGAZINE ADVERTISING &amp; PUBLISHING (HK) LIMITED"},{"lang":"hk","v":"法人文化傳播(香港)有限公司"}],"company_since":"2003-08-06","company_dissolved":"2004-07-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856366","names":[{"lang":"en","v":"LEONIS LIMITED"}],"company_since":"2003-08-06","company_dissolved":"2012-05-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856110","names":[{"lang":"en","v":"LIGHTNING SEMICONDUCTOR DEVICES LIMITED"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856095","names":[{"lang":"en","v":"LOCALIZATION PROCUREMENT OFFICE (HK) LIMITED"},{"lang":"hk","v":"現地化採購中心(香港)有限公司"}],"company_since":"2003-08-06","company_dissolved":"2009-04-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856429","names":[{"lang":"en","v":"JJ DESIGNS HK LIMITED"}],"company_since":"2003-08-06","company_dissolved":"2004-10-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856403","names":[{"lang":"en","v":"LR HOLDINGS LIMITED"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856147","names":[{"lang":"en","v":"JUZHENG SILK (HK) TRADING CO., LIMITED"},{"lang":"hk","v":"癸承絲綢(香港)貿易有限公司"}],"company_since":"2003-08-06","company_dissolved":"2019-03-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856420","names":[{"lang":"en","v":"LUCK FAME LIMITED (d2011-04-08)"},{"lang":"hk","v":"祥譽有限公司"}],"company_since":"2003-08-06","company_dissolved":"2011-04-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856171","names":[{"lang":"en","v":"KANGAROO (FRANCE) INT'L GROUP LIMITED"},{"lang":"hk","v":"法國袋鼠國際集團有限公司"}],"company_since":"2003-08-06","company_dissolved":"2008-07-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856078","names":[{"lang":"en","v":"LUEN HENG INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"聯亨國際投資有限公司"}],"company_since":"2003-08-06","company_dissolved":"2020-08-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856280","names":[{"lang":"en","v":"KING TRADE LIMITED (d2012-03-30)"},{"lang":"hk","v":"貿威有限公司"}],"company_since":"2003-08-06","company_dissolved":"2012-03-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856350","names":[{"lang":"en","v":"M. MAGTAGUE INVESTMENT LIMITED"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856331","names":[{"lang":"en","v":"LZD TECHNOLOGY LIMITED"},{"lang":"hk","v":"陸道科技有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856172","names":[{"lang":"en","v":"M6 BAG COMPANY LIMITED"}],"company_since":"2003-08-06","company_dissolved":"2005-01-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856118","names":[{"lang":"en","v":"MAGIC HOME SERVICE LIMITED"},{"lang":"hk","v":"美居家居服務有限公司"}],"company_since":"2003-08-06","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856330","names":[{"lang":"en","v":"MAGIC INDUSTRIAL LIMITED"},{"lang":"hk","v":"創奇實業有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856319","names":[{"lang":"en","v":"KOWAYTEX LIMITED"},{"lang":"hk","v":"高滙達有限公司"}],"company_since":"2003-08-06","company_dissolved":"2009-07-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856254","names":[{"lang":"en","v":"MICROBES ASIA LIMITED"}],"company_since":"2003-08-06","company_dissolved":"2014-11-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856316","names":[{"lang":"en","v":"MIVMIV FASHION (H. K.) CO., LIMITED"},{"lang":"hk","v":"喵喵服飾(香港)有限公司"}],"company_since":"2003-08-06","company_dissolved":"2013-10-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856081","names":[{"lang":"en","v":"LEADTEK INTERNATIONAL LIMITED"},{"lang":"hk","v":"昊信國際有限公司"}],"company_since":"2003-08-06","company_dissolved":"2008-10-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856102","names":[{"lang":"en","v":"MODERN LUCKY INTERNATIONAL LIMITED"},{"lang":"hk","v":"新運通國際有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856104","names":[{"lang":"en","v":"MODERN LUCKY INVESTMENTS LIMITED"},{"lang":"hk","v":"新運投資有限公司"}],"company_since":"2003-08-06","company_dissolved":"2016-09-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856399","names":[{"lang":"en","v":"MODERN TIME ELECTRONIC TECHNOLOGY (H.K.) COMPANY LIMITED"},{"lang":"hk","v":"匯通電子科技(香港)有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856275","names":[{"lang":"en","v":"MORE SMART LIMITED (d2006-04-21)"},{"lang":"hk","v":"駿茂有限公司"}],"company_since":"2003-08-06","company_dissolved":"2006-04-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856333","names":[{"lang":"en","v":"LONG HENG COOKWARE COMPANY LIMITED"},{"lang":"hk","v":"龍恒五金廚具製品有限公司"}],"company_since":"2003-08-06","company_dissolved":"2017-04-07","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856343","names":[{"lang":"en","v":"MOVIE PETROLEUM (CHINA) LIMITED"},{"lang":"hk","v":"美威石油(中國)有限公司"}],"company_since":"2003-08-06","company_dissolved":"2011-10-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"856402","names":[{"lang":"en","v":"NCP HOLDINGS LIMITED (HK)"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856146","names":[{"lang":"en","v":"LUSUS RECREATION CONSULTING LIMITED"}],"company_since":"2003-08-06","company_dissolved":"2008-10-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856141","names":[{"lang":"en","v":"NEW GROWTH ENTERPRISE LIMITED"},{"lang":"hk","v":"新展企業有限公司"}],"company_since":"2003-08-06","company_dissolved":"2009-06-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856336","names":[{"lang":"en","v":"MI (HK) LIMITED"},{"lang":"hk","v":"德國創意設計有限公司"}],"company_since":"2003-08-06","company_dissolved":"2009-06-26","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856383","names":[{"lang":"en","v":"NIKA GROUP LIMITED (d2009-06-05)"}],"company_since":"2003-08-06","company_dissolved":"2009-06-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"856450","names":[{"lang":"en","v":"OCEAN SINCERE (H.K.) DEVELOPMENT LIMITED"},{"lang":"hk","v":"海誠(香港)發展有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856425","names":[{"lang":"en","v":"OFFICE 21 LIMITED"},{"lang":"hk","v":"21世紀顧問有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856099","names":[{"lang":"en","v":"MODERN LUCKY HOLDINGS LIMITED"},{"lang":"hk","v":"新運通集團有限公司"}],"company_since":"2003-08-06","company_dissolved":"2019-01-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856270","names":[{"lang":"en","v":"ONIMEX (CHINA) LIMITED"},{"lang":"hk","v":"安麗美妍(中國)有限公司"}],"company_since":"2003-08-06","company_dissolved":"2015-09-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856348","names":[{"lang":"en","v":"PIERCADAN (ITALY) HOLDINGS LIMITED"},{"lang":"hk","v":"意大利皮爾卡丹股份有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856274","names":[{"lang":"en","v":"MORELUCK CORPORATION LIMITED"},{"lang":"hk","v":"添裕有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856200","names":[{"lang":"en","v":"PRIZE (HK) CO., LIMITED"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856076","names":[{"lang":"en","v":"NAM FUNG INVESTMENT LIMITED"},{"lang":"hk","v":"嵐豐投資有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856271","names":[{"lang":"en","v":"NEOMAN BUS (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"猛獅巴士(香港)有限公司"}],"company_since":"2003-08-06","company_dissolved":"2006-07-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856306","names":[{"lang":"en","v":"PRUDENCE INVESTMENT HOLDING COMPANY LIMITED"},{"lang":"hk","v":"慎昌投資控股有限公司"}],"company_since":"2003-08-06","company_dissolved":"2016-04-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856322","names":[{"lang":"en","v":"QUARTZ HOUSE CO. LIMITED"},{"lang":"hk","v":"千石緣有限公司"}],"company_since":"2003-08-06","company_dissolved":"2009-08-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"856139","names":[{"lang":"en","v":"R &amp; R DESIGN STUDIO CO., LIMITED"},{"lang":"hk","v":"萊斯設計工程有限公司"}],"company_since":"2003-08-06","company_dissolved":"2009-01-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856341","names":[{"lang":"en","v":"PRO CONTROL HK LIMITED"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"856324","names":[{"lang":"en","v":"NEW SUNSHINE (H.K.) CO., LIMITED"},{"lang":"hk","v":"新陽光(香港)有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-11-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856202","names":[{"lang":"en","v":"RICH POWER ELECTRONICS COMPANY LIMITED"},{"lang":"hk","v":"安澤電子有限公司"}],"company_since":"2003-08-06","company_dissolved":"2008-11-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"856238","names":[{"lang":"en","v":"OCEAN HARVEST INVESTMENTS (HONG KONG) LIMITED"},{"lang":"hk","v":"海豐投資(香港)有限公司"}],"company_since":"2003-08-06","company_dissolved":"2012-01-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856189","names":[{"lang":"en","v":"PL CONCEPT LIMITED"}],"company_since":"2003-08-06","company_dissolved":"2009-12-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856220","names":[{"lang":"en","v":"PO WA ENGINEERING CO., LIMITED"},{"lang":"hk","v":"保華工程有限公司"}],"company_since":"2003-08-06","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856191","names":[{"lang":"en","v":"ROYAL PACIFIC INVESTMENT LIMITED (d2009-01-09)"}],"company_since":"2003-08-06","company_dissolved":"2009-01-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"856296","names":[{"lang":"en","v":"Ruima Technology (HK) Co. Limited"},{"lang":"hk","v":"瑞瑪科技(香港)有限公司"}],"company_since":"2003-08-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856134","names":[{"lang":"en","v":"PRIME GOLD JEWELLERY MANUFACTURING LIMITED"},{"lang":"hk","v":"金貝珠寶製造有限公司"}],"company_since":"2003-08-06","company_dissolved":"2007-12-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"856083","names":[{"lang":"en","v":"S. JANE ASIA COMPANY LIMITED"},{"lang":"hk","v":"潔瑩亞洲有限公司"}],"company_since":"2003-08-06","company_dissolved":"2005-12-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"856460","names":[{"lang":"en","v":"SAN MIAN FENG COMPANY LIMITED"},{"lang":"hk","v":"三面丰有限公司"}],"company_since":"2003-08-06","company_dissolved":"2009-06-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
