{"tax_id":"519717","names":[{"lang":"en","v":"COE INDUSTRIAL COMPANY LIMITED"},{"lang":"hk","v":"坤銘實業有限公司"}],"company_since":"1995-07-11","company_dissolved":"2005-12-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519937","names":[{"lang":"en","v":"CONSULTING PARTNERSHIP (HONG KONG) LIMITED (THE)"}],"company_since":"1995-07-11","company_dissolved":"2008-04-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519853","names":[{"lang":"en","v":"CRAFT FISHING SUPPLY LIMITED"}],"company_since":"1995-07-11","company_dissolved":"2002-07-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519888","names":[{"lang":"en","v":"CREEKS INTERNATIONAL LIMITED"}],"company_since":"1995-07-11","company_dissolved":"2008-05-23","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519874","names":[{"lang":"en","v":"DISTINCT LIMITED (d2002-12-20)"},{"lang":"hk","v":"創立有限公司"}],"company_since":"1995-07-11","company_dissolved":"2002-12-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519862","names":[{"lang":"en","v":"DELTA ENERGY SYSTEMS (HONG KONG) LIMITED"},{"lang":"hk","v":"台達電源系統(香港)有限公司"}],"company_since":"1995-07-11","company_dissolved":"2006-07-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519897","names":[{"lang":"en","v":"CRETE HONG KONG LIMITED"}],"company_since":"1995-07-11","company_dissolved":"2000-07-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519709","names":[{"lang":"en","v":"DYNAMAX INDUSTRIAL COMPANY LIMITED"},{"lang":"hk","v":"飛豪實業有限公司"}],"company_since":"1995-07-11","company_dissolved":"2000-10-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519763","names":[{"lang":"en","v":"EXPRESS CAKE SHOP LIMITED"},{"lang":"hk","v":"聯系通餅店有限公司"}],"company_since":"1995-07-11","company_dissolved":"2017-03-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519792","names":[{"lang":"en","v":"EVERCHARM HOLDINGS LIMITED"},{"lang":"hk","v":"永創集團有限公司"}],"company_since":"1995-07-11","company_dissolved":"2009-03-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519908","names":[{"lang":"en","v":"FAMERISE COMPANY LIMITED"},{"lang":"hk","v":"譽高有限公司"}],"company_since":"1995-07-11","company_dissolved":"1999-03-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519747","names":[{"lang":"en","v":"EXPRESS INVESTMENT LIMITED"},{"lang":"hk","v":"聯系通投資有限公司"}],"company_since":"1995-07-11","company_dissolved":"2018-03-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519746","names":[{"lang":"en","v":"EXPRESS HOLDINGS LIMITED (HK)"},{"lang":"hk","v":"聯系通集團有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519762","names":[{"lang":"en","v":"EXPRESS FOOD CO. LIMITED"},{"lang":"hk","v":"聯系通食品有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519756","names":[{"lang":"en","v":"EVANGELICAL CHURCH OF CHRIST LIMITED (THE)"},{"lang":"hk","v":"基信會基立堂有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"519827","names":[{"lang":"en","v":"FARBERON LIMITED"},{"lang":"hk","v":"百利隆洋行有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519791","names":[{"lang":"en","v":"EVERCHARM (H.K.) LIMITED (d2003-01-24)"},{"lang":"hk","v":"永創(香港)有限公司"}],"company_since":"1995-07-11","company_dissolved":"2003-01-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519854","names":[{"lang":"en","v":"FEDA UNITED EXPRESS LIMITED"},{"lang":"hk","v":"快達聯運(香港)有限公司"}],"company_since":"1995-07-11","company_dissolved":"2015-03-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519797","names":[{"lang":"en","v":"FIRSTWAY CONSULTANTS LIMITED"},{"lang":"hk","v":"豐威顧問有限公司"}],"company_since":"1995-07-11","company_dissolved":"2004-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519824","names":[{"lang":"en","v":"FITLADY HOSIERY FACTORY LIMITED"},{"lang":"hk","v":"安蒂絲襪廠有限公司"}],"company_since":"1995-07-11","company_dissolved":"2013-12-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519841","names":[{"lang":"en","v":"FOUNTAIN INDUSTRIES (FAR EAST) LIMITED"},{"lang":"hk","v":"峰騰實業(遠東)有限公司"}],"company_since":"1995-07-11","company_dissolved":"1999-07-23","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519757","names":[{"lang":"en","v":"FLEUR DE BERGE LIMITED"}],"company_since":"1995-07-11","company_dissolved":"2003-02-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519929","names":[{"lang":"en","v":"FOOT SPECIALIST FOOTCARE &amp; PRODUCTS COMPANY LIMITED"},{"lang":"hk","v":"足康保足部護理產品有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519719","names":[{"lang":"en","v":"FUNDERFUL WORLD LIMITED"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519844","names":[{"lang":"en","v":"FUK WING LIMITED"},{"lang":"hk","v":"福永輪呔有限公司"}],"company_since":"1995-07-11","company_dissolved":"1998-10-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519836","names":[{"lang":"en","v":"GLORY JEWELRY DESIGNS LIMITED"},{"lang":"hk","v":"鵬程珠寶有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519926","names":[{"lang":"en","v":"GOLDEN APPLE INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"金果國際投資有限公司"}],"company_since":"1995-07-11","company_dissolved":"2013-04-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519835","names":[{"lang":"en","v":"GOLDEN TIGER INVESTMENT DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"金虎投資發展有限公司"}],"company_since":"1995-07-11","company_dissolved":"2004-07-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519945","names":[{"lang":"en","v":"GOLDSPHERE INDUSTRIES COMPANY LIMITED"},{"lang":"hk","v":"佳豪電子有限公司"}],"company_since":"1995-07-11","company_dissolved":"2019-03-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519863","names":[{"lang":"en","v":"GOLDSTAR ENTERPRISES LIMITED (d2013-10-25)"},{"lang":"hk","v":"永星企業有限公司"}],"company_since":"1995-07-11","company_dissolved":"2013-10-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519804","names":[{"lang":"en","v":"GRAND SUCCESS HOLDINGS LIMITED"},{"lang":"hk","v":"嘉成集團有限公司"}],"company_since":"1995-07-11","company_dissolved":"2018-03-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519944","names":[{"lang":"en","v":"GRANDING TECHNOLOGY LIMITED (d2004-02-06)"},{"lang":"hk","v":"大興科技有限公司"}],"company_since":"1995-07-11","company_dissolved":"2004-02-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519935","names":[{"lang":"en","v":"GRANEW COMPANY LIMITED"},{"lang":"hk","v":"新穎德有限公司"}],"company_since":"1995-07-11","company_dissolved":"2005-04-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519909","names":[{"lang":"en","v":"GRANVEST COMPANY LIMITED"},{"lang":"hk","v":"嘉豐達投資有限公司"}],"company_since":"1995-07-11","company_dissolved":"2009-06-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519936","names":[{"lang":"en","v":"GUANGZHOU INTERNATIONAL FURNITURE AND LIGHTING TRADE FAIR LIMITED"},{"lang":"hk","v":"廣州國際傢俬燈飾展覽會有限公司"}],"company_since":"1995-07-11","company_dissolved":"2001-05-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519736","names":[{"lang":"en","v":"HALIC INTERNATIONAL LIMITED"}],"company_since":"1995-07-11","company_dissolved":"2004-12-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"519767","names":[{"lang":"en","v":"HI YEN INTERNATIONAL LIMITED"},{"lang":"hk","v":"海印國際有限公司"}],"company_since":"1995-07-11","company_dissolved":"2019-03-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519772","names":[{"lang":"en","v":"DUNWORLD ADVERTISING PRODUCTION &amp; PRINTING LIMITED"},{"lang":"hk","v":"登滙廣告製作及印刷有限公司"}],"company_since":"1995-07-11","company_dissolved":"2003-05-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519942","names":[{"lang":"en","v":"HOLDER CONSTRUCTION &amp; ENGINEERING CO. LIMITED"},{"lang":"hk","v":"浩達建築工程有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"519925","names":[{"lang":"en","v":"FONG CHUNG SOCIAL SERVICE CENTRE LIMITED"},{"lang":"hk","v":"坊衆社會服務中心有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
{"tax_id":"519755","names":[{"lang":"en","v":"HONG KONG INSTITUTE FOR INFRASTRUCTURE DEVELOPMENT LIMITED (THE)"},{"lang":"hk","v":"香港基礎建設學會有限公司"}],"company_since":"1995-07-11","company_dissolved":"2011-07-08","company_type_txt":"Ltd by guarantee"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"519784","names":[{"lang":"en","v":"KAM KIU INTERNATIONAL DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"金橋國際發展有限公司"}],"company_since":"1995-07-11","company_dissolved":"2004-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519730","names":[{"lang":"en","v":"ENDLESS CREATION CORPORATION LIMITED"},{"lang":"hk","v":"無盡創意有限公司"}],"company_since":"1995-07-11","company_dissolved":"1999-01-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519894","names":[{"lang":"en","v":"KEYLINK EXPRESS LIMITED"},{"lang":"hk","v":"嘉威旅運有限公司"}],"company_since":"1995-07-11","company_dissolved":"2001-08-31","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519749","names":[{"lang":"en","v":"HONG KONG NEW ASIA-PACIFIC INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"香港新亞太國際有限公司"}],"company_since":"1995-07-11","company_dissolved":"2004-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519806","names":[{"lang":"en","v":"JOINT MECHANO CONSTRUCTION ENGINEERING LIMITED"},{"lang":"hk","v":"中美建設工程有限公司"}],"company_since":"1995-07-11","company_dissolved":"2001-11-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519877","names":[{"lang":"en","v":"J&amp;E INTERNATIONAL NETWORK LIMITED"}],"company_since":"1995-07-11","company_dissolved":"2004-06-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519832","names":[{"lang":"en","v":"LANCRUSIER DEVELOPMENT CO., LIMITED"},{"lang":"hk","v":"藍箭發展有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519729","names":[{"lang":"en","v":"HUGE MIGHT FOOD SYSTEMS LIMITED"},{"lang":"hk","v":"力固食品系列有限公司"}],"company_since":"1995-07-11","company_dissolved":"2003-01-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519753","names":[{"lang":"en","v":"GLOBAL IDENTITY (HK) COMPANY LIMITED"},{"lang":"hk","v":"環球滙點(香港)有限公司"}],"company_since":"1995-07-11","company_dissolved":"1999-06-11","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519805","names":[{"lang":"en","v":"LAND BASE TRADING LIMITED"},{"lang":"hk","v":"隆基貿易有限公司"}],"company_since":"1995-07-11","company_dissolved":"2004-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519931","names":[{"lang":"en","v":"HUA XING POWER INTERNATIONAL ECONOMIC &amp; TRADE CO., LIMITED"},{"lang":"hk","v":"華興電力國際經貿有限公司"}],"company_since":"1995-07-11","company_dissolved":"1999-02-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519907","names":[{"lang":"en","v":"MAIN HOLDINGS LIMITED (HK)"},{"lang":"hk","v":"仲明創建有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519890","names":[{"lang":"en","v":"CONVERGE MACHINERY COMPANY LIMITED"},{"lang":"hk","v":"康滙聚機電有限公司"}],"company_since":"1995-07-11","company_dissolved":"2016-04-29","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519782","names":[{"lang":"en","v":"MAX CHEERS COMPANY LIMITED"},{"lang":"hk","v":"至怡有限公司"}],"company_since":"1995-07-11","company_dissolved":"2001-08-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519845","names":[{"lang":"en","v":"JOYCE ACCESSORIES CO., LIMITED"},{"lang":"hk","v":"嬌順企業股份有限公司"}],"company_since":"1995-07-11","company_dissolved":"2018-01-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519813","names":[{"lang":"en","v":"GRANFORT LIMITED (HK)"},{"lang":"hk","v":"金福達有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519800","names":[{"lang":"en","v":"ETERNAL BRILLIANT (H.K.) LIMITED"},{"lang":"hk","v":"永通耀香港有限公司"}],"company_since":"1995-07-11","company_dissolved":"2004-01-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519911","names":[{"lang":"en","v":"KEENTACT COMPANY LIMITED"},{"lang":"hk","v":"健得投資有限公司"}],"company_since":"1995-07-11","company_dissolved":"2001-08-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519723","names":[{"lang":"en","v":"MEDIA PROJECT PLANNING COMPANY LIMITED"},{"lang":"hk","v":"傳媒策劃製作有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519916","names":[{"lang":"en","v":"MASTER UNITY LIMITED"},{"lang":"hk","v":"一聯有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"519882","names":[{"lang":"en","v":"MAXWELL KNITTING FACTORY COMPANY LIMITED"},{"lang":"hk","v":"時運毛織廠有限公司"}],"company_since":"1995-07-11","company_dissolved":"2020-05-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519759","names":[{"lang":"en","v":"Implant Prosthodontics Centre Limited"},{"lang":"hk","v":"植齒修復中心有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519809","names":[{"lang":"en","v":"MOON LEUNG WO JADE AND JEWELRY COMPANY LIMITED"},{"lang":"hk","v":"滿良和玉器首飾有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519906","names":[{"lang":"en","v":"E &amp; V JEWELLERY (HK) LIMITED"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519795","names":[{"lang":"en","v":"PACIFIC TIME (H.K.) LIMITED"},{"lang":"hk","v":"協泰(香港)有限公司"}],"company_since":"1995-07-11","company_dissolved":"2004-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519923","names":[{"lang":"en","v":"PARKS CONTRACTING COMPANY LIMITED"},{"lang":"hk","v":"栢溢名基策略發展有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519848","names":[{"lang":"en","v":"P-UNION LIMITED"},{"lang":"hk","v":"栢和有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519856","names":[{"lang":"en","v":"KALUN HOLDINGS LIMITED"},{"lang":"hk","v":"嘉倫控股有限公司"}],"company_since":"1995-07-11","company_dissolved":"2004-12-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519798","names":[{"lang":"en","v":"ON FAITH HOLDINGS LIMITED"},{"lang":"hk","v":"安信集團有限公司"}],"company_since":"1995-07-11","company_dissolved":"2012-08-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519811","names":[{"lang":"en","v":"PERFECT ACHIEVEMENT LIMITED"}],"company_since":"1995-07-11","company_dissolved":"2002-07-05","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519922","names":[{"lang":"en","v":"PARKS SUPPLIES (CHINA) COMPANY LIMITED"},{"lang":"hk","v":"栢溢康體設備(中國)有限公司"}],"company_since":"1995-07-11","company_dissolved":"2020-09-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519766","names":[{"lang":"en","v":"POLYROID ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"保利來工程有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519919","names":[{"lang":"en","v":"PLAN COMPANY LIMITED (THE)"},{"lang":"hk","v":"大鵬有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519769","names":[{"lang":"en","v":"NEWGEN WEAVING FACTORY LIMITED"},{"lang":"hk","v":"里程織廠有限公司"}],"company_since":"1995-07-11","company_dissolved":"2001-12-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519921","names":[{"lang":"en","v":"PTM OCEAN LINE LIMITED"},{"lang":"hk","v":"栢廸航運有限公司"}],"company_since":"1995-07-11","company_dissolved":"2004-01-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519840","names":[{"lang":"en","v":"LONG JIANG INTERNATIONAL LIMITED"},{"lang":"hk","v":"隆江國際有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519771","names":[{"lang":"en","v":"PROSPER JEWELLERY COMPANY LIMITED"},{"lang":"hk","v":"穎寶珠寶有限公司"}],"company_since":"1995-07-11","company_dissolved":"2000-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519855","names":[{"lang":"en","v":"ORIENTAL HERO INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"東浩國際投資有限公司"}],"company_since":"1995-07-11","company_dissolved":"2002-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519752","names":[{"lang":"en","v":"R. P. S. EXPRESS LIMITED"},{"lang":"hk","v":"洛百新速遞有限公司"}],"company_since":"1995-07-11","company_dissolved":"2000-08-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519728","names":[{"lang":"en","v":"OMASU INTERNATIONAL LIMITED"}],"company_since":"1995-07-11","company_dissolved":"2002-12-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519732","names":[{"lang":"en","v":"HONG KONG DA FANG GROUP INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"香港大方集團國際有限公司"}],"company_since":"1995-07-11","company_dissolved":"2004-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519901","names":[{"lang":"en","v":"REFORM PUBLISHING CO. LIMITED"},{"lang":"hk","v":"改革出版有限公司"}],"company_since":"1995-07-11","company_dissolved":"2012-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519708","names":[{"lang":"en","v":"INTERNATIONAL HOUSE OF DISTINCTION (HONG KONG) LIMITED"},{"lang":"hk","v":"國際淨水工程(香港)有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519779","names":[{"lang":"en","v":"MANNATECH INTERNATIONAL LIMITED (d2004-01-30)"}],"company_since":"1995-07-11","company_dissolved":"2004-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519764","names":[{"lang":"en","v":"HONG KONG GOLDEN STONE INDUSTRIAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"香港金崇立實業發展有限公司"}],"company_since":"1995-07-11","company_dissolved":"2005-07-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519880","names":[{"lang":"en","v":"ROBERT FU YI MING MEMORIAL CHARITY FOUNDATION LIMITED"},{"lang":"hk","v":"傅一民紀念慈善基金有限公司"}],"company_since":"1995-07-11","company_dissolved":"2019-03-22","company_type_txt":"Ltd by guarantee"},
undefined,
undefined,
{"tax_id":"519740","names":[{"lang":"en","v":"HONG KONG GOLDEN FUTURE TRANSPORTATION LIMITED"},{"lang":"hk","v":"香港祥和航運有限公司"}],"company_since":"1995-07-11","company_dissolved":"2005-07-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519913","names":[{"lang":"en","v":"RELAXING HOLIDAY COMPANY LIMITED"},{"lang":"hk","v":"逍遙假期有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519920","names":[{"lang":"en","v":"S &amp; L GROUPS LIMITED"},{"lang":"hk","v":"駿領集團有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519934","names":[{"lang":"en","v":"PERFECT HARMONY COMPANY LIMITED"},{"lang":"hk","v":"寶和佳有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"519819","names":[{"lang":"en","v":"P SNAPS HONG KONG LIMITED"}],"company_since":"1995-07-11","company_dissolved":"2020-01-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519823","names":[{"lang":"en","v":"SAMMING COMPANY LIMITED"},{"lang":"hk","v":"豫光有限公司"}],"company_since":"1995-07-11","company_dissolved":"2003-02-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519751","names":[{"lang":"en","v":"HONG KONG GREAT DRAGON INDUSTRIAL LIMITED"},{"lang":"hk","v":"香港巨龍實業有限公司"}],"company_since":"1995-07-11","company_dissolved":"2000-11-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519899","names":[{"lang":"en","v":"OMAHA NATIONAL ELECTRIC LIMITED"}],"company_since":"1995-07-11","company_dissolved":"2003-01-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519807","names":[{"lang":"en","v":"HONE JEOH INDUSTRIAL CO. LIMITED"},{"lang":"hk","v":"崧大實業有限公司"}],"company_since":"1995-07-11","company_dissolved":"2005-11-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519738","names":[{"lang":"en","v":"PERFECT POWER WORLDWIDE LIMITED"},{"lang":"hk","v":"效展環球投資有限公司"}],"company_since":"1995-07-11","company_dissolved":"2002-08-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519831","names":[{"lang":"en","v":"SANDEN ELECTRONICS (HK) LIMITED"},{"lang":"hk","v":"三電電子(香港)有限公司"}],"company_since":"1995-07-11","company_dissolved":"2007-06-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519852","names":[{"lang":"en","v":"DENIFER DEVELOPMENT (SHANGHAI) LIMITED"},{"lang":"hk","v":"敦寧發展(上海)有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519872","names":[{"lang":"en","v":"SEVEN SEAS DEVELOPMENT LIMITED"},{"lang":"hk","v":"七海發展有限公司"}],"company_since":"1995-07-11","company_dissolved":"2005-03-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519704","names":[{"lang":"en","v":"ECO-TECHNIQUE (H.K.) CORPORATION LIMITED"},{"lang":"hk","v":"意好(香港)有限公司"}],"company_since":"1995-07-11","company_dissolved":"2004-01-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519930","names":[{"lang":"en","v":"LIFE DEVOTEE LIMITED"},{"lang":"hk","v":"修明學會有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519786","names":[{"lang":"en","v":"SECTAX NOMINEE SERVICES LIMITED"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519754","names":[{"lang":"en","v":"SCI SECRETARIES LIMITED"},{"lang":"hk","v":"穗文顧問有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519846","names":[{"lang":"en","v":"HONG KONG SUCCESS ENTERPRISES LIMITED"},{"lang":"hk","v":"香港成功企業有限公司"}],"company_since":"1995-07-11","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519871","names":[{"lang":"en","v":"SEVEN SEAS ENTERPRISES LIMITED"},{"lang":"hk","v":"七海企業有限公司"}],"company_since":"1995-07-11","company_dissolved":"2018-05-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519865","names":[{"lang":"en","v":"SEVEN GLOBAL ENTERPRISES LIMITED"},{"lang":"hk","v":"七寶企業有限公司"}],"company_since":"1995-07-11","company_dissolved":"2005-07-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519775","names":[{"lang":"en","v":"INTERNATIONAL FUND OF CHINA (H.K.) DEVELOPMENT LIMITED"},{"lang":"hk","v":"中華國際基金(香港)拓展有限公司"}],"company_since":"1995-07-11","company_dissolved":"2004-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519869","names":[{"lang":"en","v":"SEVEN STAR DEVELOPMENT LIMITED (d2001-01-05)"},{"lang":"hk","v":"七星發展有限公司"}],"company_since":"1995-07-11","company_dissolved":"2001-01-05","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519947","names":[{"lang":"en","v":"NEW RESOURCES (CHINA) TRADE COMPANY LIMITED"},{"lang":"hk","v":"新瑞豐(中國)貿易有限公司"}],"company_since":"1995-07-11","company_dissolved":"2004-06-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519724","names":[{"lang":"en","v":"HUNDRED FAIR (HOLDINGS) LIMITED"},{"lang":"hk","v":"百爾登(集團)有限公司"}],"company_since":"1995-07-11","company_dissolved":"2011-04-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519870","names":[{"lang":"en","v":"SEVEN STAR INVESTMENT LIMITED"},{"lang":"hk","v":"七星投資有限公司"}],"company_since":"1995-07-11","company_dissolved":"2000-06-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519808","names":[{"lang":"en","v":"HUNG TANG (C.HK) CONTAINER TRANSPORTATION LIMITED"},{"lang":"hk","v":"雄騰(中港)貨櫃運輸有限公司"}],"company_since":"1995-07-11","company_dissolved":"2004-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519896","names":[{"lang":"en","v":"SHANGHAI DAJIE GLASS CRAFTS (HK) CO., LIMITED"},{"lang":"hk","v":"上海達捷玻璃藝術品(香港)有限公司"}],"company_since":"1995-07-11","company_dissolved":"2006-02-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519928","names":[{"lang":"en","v":"KING'S RESTAURANT LIMITED (d2010-09-24)"}],"company_since":"1995-07-11","company_dissolved":"2010-09-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519796","names":[{"lang":"en","v":"PACIFIC TIME HOLDINGS LIMITED"},{"lang":"hk","v":"協泰集團有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519898","names":[{"lang":"en","v":"SHINY MARBLE ENGINEERING LIMITED"},{"lang":"hk","v":"雙利雲石工程有限公司"}],"company_since":"1995-07-11","company_dissolved":"2003-01-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"519770","names":[{"lang":"en","v":"SINO CONCEPT INDUSTRIAL LIMITED"},{"lang":"hk","v":"創念實業有限公司"}],"company_since":"1995-07-11","company_dissolved":"2009-12-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519739","names":[{"lang":"en","v":"JTEC COMPANY LIMITED"}],"company_since":"1995-07-11","company_dissolved":"2002-06-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519733","names":[{"lang":"en","v":"PETO TRADING LIMITED (d1997-09-13)"}],"company_since":"1995-07-11","company_dissolved":"1997-09-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519830","names":[{"lang":"en","v":"IZUMI ELECTRIC INTERNATIONAL LIMITED"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519910","names":[{"lang":"en","v":"EILIAN COMPANY LIMITED"},{"lang":"hk","v":"愛安利有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519780","names":[{"lang":"en","v":"PREMIUM ASSETS COMPANY LIMITED"},{"lang":"hk","v":"優源有限公司"}],"company_since":"1995-07-11","company_dissolved":"2004-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519816","names":[{"lang":"en","v":"SMARTLOCK ASIA LIMITED"},{"lang":"hk","v":"勝能亞洲有限公司"}],"company_since":"1995-07-11","company_dissolved":"2004-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519801","names":[{"lang":"en","v":"SINOTIME HOLDINGS LIMITED (d2000-05-19)"},{"lang":"hk","v":"盛泰集團有限公司"}],"company_since":"1995-07-11","company_dissolved":"2000-05-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"519701","names":[{"lang":"en","v":"SMART ADVANCE INTERNATIONAL LIMITED"},{"lang":"hk","v":"佑昇國際有限公司"}],"company_since":"1995-07-11","company_dissolved":"2020-07-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519900","names":[{"lang":"en","v":"SOUTH 22 COMPANY LIMITED"},{"lang":"hk","v":"兆恒22有限公司"}],"company_since":"1995-07-11","company_dissolved":"2003-04-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519839","names":[{"lang":"en","v":"SOUTH AMERICAN ENTERPRISES LIMITED"},{"lang":"hk","v":"南美企業有限公司"}],"company_since":"1995-07-11","company_dissolved":"2003-10-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519860","names":[{"lang":"en","v":"PAK SHING (H.K.) DEVELOPMENT LIMITED"},{"lang":"hk","v":"百誠(香港)發展有限公司"}],"company_since":"1995-07-11","company_dissolved":"2001-02-02","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519822","names":[{"lang":"en","v":"STAR FLASH LIMITED"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519790","names":[{"lang":"en","v":"STARWISE LIMITED (d2015-08-14)"},{"lang":"hk","v":"星志有限公司"}],"company_since":"1995-07-11","company_dissolved":"2015-08-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519838","names":[{"lang":"en","v":"STH INTERNATIONAL (HK) LIMITED"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519902","names":[{"lang":"en","v":"SUN YUEN CHEONG CAFE (B) LIMITED"},{"lang":"hk","v":"新源昌燒臘餐廳(B)有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519876","names":[{"lang":"en","v":"MEDCOM LIMITED (HK)"},{"lang":"hk","v":"健訊有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519849","names":[{"lang":"en","v":"SUPER SUN INTERNATIONAL ENTERPRISES LIMITED"},{"lang":"hk","v":"賽日國際企業集團有限公司"}],"company_since":"1995-07-11","company_dissolved":"2004-02-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519889","names":[{"lang":"en","v":"LEADING EXPERT INVESTMENT LIMITED"},{"lang":"hk","v":"利達堡投資有限公司"}],"company_since":"1995-07-11","company_dissolved":"2004-02-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519820","names":[{"lang":"en","v":"SUTANGO COMPANY LIMITED"}],"company_since":"1995-07-11","company_dissolved":"2001-04-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519821","names":[{"lang":"en","v":"SUNNY QUEEN COMPANY LIMITED"}],"company_since":"1995-07-11","company_dissolved":"2000-06-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519718","names":[{"lang":"en","v":"SWEET COME TRAVEL LIMITED"},{"lang":"hk","v":"瑞錦旅遊有限公司"}],"company_since":"1995-07-11","company_dissolved":"2001-04-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519748","names":[{"lang":"en","v":"MASSIMO GRITTI INTERNATIONAL LIMITED"}],"company_since":"1995-07-11","company_dissolved":"2014-07-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519788","names":[{"lang":"en","v":"TAK MING CONSTRUCTION LIMITED"},{"lang":"hk","v":"德明建築有限公司"}],"company_since":"1995-07-11","company_dissolved":"1999-02-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519750","names":[{"lang":"en","v":"TAKWAY (HONG KONG) ELECTRONIC INDUSTRIAL LIMITED"},{"lang":"hk","v":"德威(香港)電子實業有限公司"}],"company_since":"1995-07-11","company_dissolved":"2004-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519858","names":[{"lang":"en","v":"TALENT EAGLE MOTOR SERVICES LIMITED"},{"lang":"hk","v":"駿傲汽車服務有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519834","names":[{"lang":"en","v":"TECHWIN SYSTEM DEVELOPMENT LIMITED"},{"lang":"hk","v":"科冠系統發展有限公司"}],"company_since":"1995-07-11","company_dissolved":"2007-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519721","names":[{"lang":"en","v":"TIME INTERNATIONAL ENTERPRISES LIMITED"},{"lang":"hk","v":"尖端國際企業有限公司"}],"company_since":"1995-07-11","company_dissolved":"2006-02-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519918","names":[{"lang":"en","v":"TIN HONG COMPANY LIMITED"},{"lang":"hk","v":"天航有限公司"}],"company_since":"1995-07-11","company_dissolved":"2002-06-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519881","names":[{"lang":"en","v":"TITLE INHERIT DEVELOPMENT LIMITED"},{"lang":"hk","v":"承爵發展有限公司"}],"company_since":"1995-07-11","company_dissolved":"2000-06-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519915","names":[{"lang":"en","v":"PACLAND COMPANY LIMITED"},{"lang":"hk","v":"太運有限公司"}],"company_since":"1995-07-11","company_dissolved":"2004-02-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519714","names":[{"lang":"en","v":"TOP SELECT (H.K.) LIMITED"}],"company_since":"1995-07-11","company_dissolved":"2011-03-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519793","names":[{"lang":"en","v":"TOP STANDARD (H.K.) LIMITED (d2007-02-09)"},{"lang":"hk","v":"達信(香港)有限公司"}],"company_since":"1995-07-11","company_dissolved":"2007-02-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"519783","names":[{"lang":"en","v":"MARK LINK SYSTEMS LIMITED"},{"lang":"hk","v":"富凌系統有限公司"}],"company_since":"1995-07-11","company_dissolved":"1998-12-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519914","names":[{"lang":"en","v":"TRI-COOP TRADING COMPANY LIMITED"}],"company_since":"1995-07-11","company_dissolved":"2002-07-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519710","names":[{"lang":"en","v":"SATISFACTORY PRINTING &amp; DYEING FACTORY (CHINA) LIMITED"},{"lang":"hk","v":"利業染廠(中國)有限公司"}],"company_since":"1995-07-11","company_dissolved":"2006-02-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519873","names":[{"lang":"en","v":"TSAIR SHUENN MACHINERY INDUSTRY (H.K.) COMPANY LIMITED"},{"lang":"hk","v":"財順機械工業香港有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519765","names":[{"lang":"en","v":"TUNG HING HOLDING COMPANY LIMITED"},{"lang":"hk","v":"同興控股有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519866","names":[{"lang":"en","v":"UNION REGENT INDUSTRIES LIMITED"},{"lang":"hk","v":"聯安輝實業有限公司"}],"company_since":"1995-07-11","company_dissolved":"2019-03-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519799","names":[{"lang":"en","v":"UNITED MOBILE COMMUNICATION COMPANY LIMITED"},{"lang":"hk","v":"聯合移動通訊有限公司"}],"company_since":"1995-07-11","company_dissolved":"2017-09-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519818","names":[{"lang":"en","v":"VICTOR LIGHT LIMITED"}],"company_since":"1995-07-11","company_dissolved":"2015-03-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519868","names":[{"lang":"en","v":"SEVEN STAR ENTERPRISES LIMITED (d2004-02-06)"},{"lang":"hk","v":"七星企業有限公司"}],"company_since":"1995-07-11","company_dissolved":"2004-02-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519847","names":[{"lang":"en","v":"VINTAGE INDUSTRIES LIMITED"},{"lang":"hk","v":"永達時實業有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519794","names":[{"lang":"en","v":"VISION TECHNOLOGY INTERNATIONAL LIMITED"},{"lang":"hk","v":"偉智科技管理顧問有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519887","names":[{"lang":"en","v":"WAI WELL CONSTRUCTION ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"偉聯營造工程有限公司"}],"company_since":"1995-07-11","company_dissolved":"2008-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519884","names":[{"lang":"en","v":"SEVEN STAR GARMENTS LIMITED"},{"lang":"hk","v":"七星製衣有限公司"}],"company_since":"1995-07-11","company_dissolved":"2004-02-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519777","names":[{"lang":"en","v":"WING CHI COMPANY LIMITED"},{"lang":"hk","v":"永誌有限公司"}],"company_since":"1995-07-11","company_dissolved":"2001-04-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"519867","names":[{"lang":"en","v":"SEVEN STAR INTERNATIONAL LIMITED (d2002-02-22)"},{"lang":"hk","v":"七星國際有限公司"}],"company_since":"1995-07-11","company_dissolved":"2002-02-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519912","names":[{"lang":"en","v":"NEW UNIVERSE HOLDINGS LIMITED"},{"lang":"hk","v":"新宇控股有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519774","names":[{"lang":"en","v":"WING LUEN MARINE PRODUCTS COMPANY LIMITED"},{"lang":"hk","v":"永聯海產有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519725","names":[{"lang":"en","v":"WON TUNG COMMUNICATION LIMITED"},{"lang":"hk","v":"運通電訊有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519803","names":[{"lang":"en","v":"WORLDCO HOLDINGS LIMITED (d2008-05-02)"},{"lang":"hk","v":"偉昌集團有限公司"}],"company_since":"1995-07-11","company_dissolved":"2008-05-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519883","names":[{"lang":"en","v":"WORLDLY-NAMED ENTERPRISES LIMITED"},{"lang":"hk","v":"威揚名企業有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"519891","names":[{"lang":"en","v":"SHINE TRADING COMPANY LIMITED (d2001-01-12)"},{"lang":"hk","v":"勝光貿易有限公司"}],"company_since":"1995-07-11","company_dissolved":"2001-01-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519924","names":[{"lang":"en","v":"SHEK LEI PUI KWUN YAM MIU COMPANY LIMITED"},{"lang":"hk","v":"石梨貝觀音廟有限公司"}],"company_since":"1995-07-11","company_dissolved":"2009-11-06","company_type_txt":"Ltd by guarantee"},
{"tax_id":"519703","names":[{"lang":"en","v":"YEEYANKA MARINE SERVICES COMPANY LIMITED"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519878","names":[{"lang":"en","v":"YUK SANG INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"煜生國際有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"519833","names":[{"lang":"en","v":"SME CONSULTANTS INTERNATIONAL LIMITED"},{"lang":"hk","v":"中健國際顧問有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519781","names":[{"lang":"en","v":"RENOWN COMPANY LIMITED"},{"lang":"hk","v":"盛名有限公司"}],"company_since":"1995-07-11","company_dissolved":"2004-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519892","names":[{"lang":"en","v":"LI'S BROTHERS LIMITED"},{"lang":"hk","v":"李氏兄弟有限公司"}],"company_since":"1995-07-11","company_dissolved":"2002-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"519895","names":[{"lang":"en","v":"TEX REACH DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"德至發展有限公司"}],"company_since":"1995-07-11","company_dissolved":"2004-02-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"519943","names":[{"lang":"en","v":"TOPKING TECHNOLOGY LIMITED"},{"lang":"hk","v":"天興科技有限公司"}],"company_since":"1995-07-11","company_dissolved":"2004-02-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"519817","names":[{"lang":"en","v":"WINNY BRIGHT LIMITED"}],"company_since":"1995-07-11","company_dissolved":"2000-10-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519810","names":[{"lang":"en","v":"WONG WAH KI BUILDING ENGINEERING LIMITED (d2004-07-23)"},{"lang":"hk","v":"黃華記建築工程有限公司"}],"company_since":"1995-07-11","company_dissolved":"2004-07-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"519712","names":[{"lang":"en","v":"XINGLIN INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"興林國際發展有限公司"}],"company_since":"1995-07-11","company_dissolved":"2003-02-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519711","names":[{"lang":"en","v":"ZHANJIANG CLANSMEN ASSOCIATION LIMITED"},{"lang":"hk","v":"湛江旅港同鄉會有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
{"tax_id":"519893","names":[{"lang":"en","v":"NEW ASIA INTERNATIONAL FINANCE CORPORATION LIMITED"},{"lang":"hk","v":"新亞國際財務有限公司"}],"company_since":"1995-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519837","names":[{"lang":"en","v":"PACIFIC (ASIA) LIGHTING &amp; TRADING COMPANY LIMITED"},{"lang":"hk","v":"山河照明器材有限公司"}],"company_since":"1995-07-11","company_dissolved":"2000-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"519802","names":[{"lang":"en","v":"WORLDCO (H.K.) LIMITED (d2002-03-15)"},{"lang":"hk","v":"偉昌(香港)有限公司"}],"company_since":"1995-07-11","company_dissolved":"2002-03-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519814","names":[{"lang":"en","v":"COMFORD LIMITED"},{"lang":"hk","v":"金福特有限公司"}],"company_since":"1995-07-11","company_dissolved":"2002-11-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"519851","names":[{"lang":"en","v":"PARK LAI INDUSTRIAL CO. LIMITED"},{"lang":"hk","v":"柏勵實業有限公司"}],"company_since":"1995-07-11","company_dissolved":"2004-06-18","company_type_txt":"Private, ltd by shares"},
