{"tax_id":"650304","names":[{"lang":"en","v":"CYCLES MARKETING LIMITED"},{"lang":"hk","v":"智高推廣有限公司"}],"company_since":"1998-07-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650360","names":[{"lang":"en","v":"EA MACHINERY EQUIPMENT COMPANY LIMITED"},{"lang":"hk","v":"歐亞機械設備有限公司"}],"company_since":"1998-07-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650297","names":[{"lang":"en","v":"EASTERLY HOLDINGS LIMITED"},{"lang":"hk","v":"東利集團有限公司"}],"company_since":"1998-07-20","company_dissolved":"2006-12-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650233","names":[{"lang":"en","v":"ELEGANT CHOICE LIMITED (b1998-07-20)"},{"lang":"hk","v":"良耀有限公司"}],"company_since":"1998-07-20","company_dissolved":"2015-05-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650253","names":[{"lang":"en","v":"EMINENT PROFESSIONAL ENGINEERS LIMITED"},{"lang":"hk","v":"樺城工程有限公司"}],"company_since":"1998-07-20","company_dissolved":"2005-11-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650230","names":[{"lang":"en","v":"EVER YOUNG LIMITED (d2010-01-08)"},{"lang":"hk","v":"永宜有限公司"}],"company_since":"1998-07-20","company_dissolved":"2010-01-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650355","names":[{"lang":"en","v":"EVERGREEN INDUSTRIAL CORPORATION LIMITED"},{"lang":"hk","v":"維淦實業有限公司"}],"company_since":"1998-07-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650241","names":[{"lang":"en","v":"EXCEL TIME ENTERPRISES LIMITED"},{"lang":"hk","v":"豪佳企業有限公司"}],"company_since":"1998-07-20","company_dissolved":"2009-08-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650320","names":[{"lang":"en","v":"EXPRESS HONOR DEVELOPMENT LIMITED (d2005-07-22)"},{"lang":"hk","v":"誠迅發展有限公司"}],"company_since":"1998-07-20","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650304","names":[{"lang":"en","v":"CYCLES MARKETING LIMITED"},{"lang":"hk","v":"智高推廣有限公司"}],"company_since":"1998-07-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650360","names":[{"lang":"en","v":"EA MACHINERY EQUIPMENT COMPANY LIMITED"},{"lang":"hk","v":"歐亞機械設備有限公司"}],"company_since":"1998-07-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650297","names":[{"lang":"en","v":"EASTERLY HOLDINGS LIMITED"},{"lang":"hk","v":"東利集團有限公司"}],"company_since":"1998-07-20","company_dissolved":"2006-12-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650233","names":[{"lang":"en","v":"ELEGANT CHOICE LIMITED (b1998-07-20)"},{"lang":"hk","v":"良耀有限公司"}],"company_since":"1998-07-20","company_dissolved":"2015-05-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650253","names":[{"lang":"en","v":"EMINENT PROFESSIONAL ENGINEERS LIMITED"},{"lang":"hk","v":"樺城工程有限公司"}],"company_since":"1998-07-20","company_dissolved":"2005-11-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650230","names":[{"lang":"en","v":"EVER YOUNG LIMITED (d2010-01-08)"},{"lang":"hk","v":"永宜有限公司"}],"company_since":"1998-07-20","company_dissolved":"2010-01-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650355","names":[{"lang":"en","v":"EVERGREEN INDUSTRIAL CORPORATION LIMITED"},{"lang":"hk","v":"維淦實業有限公司"}],"company_since":"1998-07-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650277","names":[{"lang":"en","v":"FRIENDSHIP CORPORATION LIMITED (d2005-07-22)"},{"lang":"hk","v":"友僑有限公司"}],"company_since":"1998-07-20","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650238","names":[{"lang":"en","v":"GATEWAY MERCHANDISING COMPANY LIMITED"}],"company_since":"1998-07-20","company_dissolved":"2015-07-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650279","names":[{"lang":"en","v":"GENERATION NEXT COMPANY LIMITED"},{"lang":"hk","v":"世紀創富有限公司"}],"company_since":"1998-07-20","company_dissolved":"2001-02-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650330","names":[{"lang":"en","v":"GENTWAY HONG KONG LIMITED"},{"lang":"hk","v":"駿怡香港有限公司"}],"company_since":"1998-07-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650343","names":[{"lang":"en","v":"GADLEE INDUSTRIES LIMITED"},{"lang":"hk","v":"加利寶實業有限公司"}],"company_since":"1998-07-20","company_dissolved":"2001-01-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650246","names":[{"lang":"en","v":"GOOD HOST MOTOR VEHICLE TRADING LIMITED"},{"lang":"hk","v":"粵佳汽車貿易有限公司"}],"company_since":"1998-07-20","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650255","names":[{"lang":"en","v":"GRAND CONCORD INTERNATIONAL SHIPPING LIMITED"},{"lang":"hk","v":"勁和國際船務有限公司"}],"company_since":"1998-07-20","company_dissolved":"2000-12-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650308","names":[{"lang":"en","v":"GRANDMASS SYSTEMS LIMITED"},{"lang":"hk","v":"盛創系統有限公司"}],"company_since":"1998-07-20","company_dissolved":"2001-04-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650239","names":[{"lang":"en","v":"GREAT ROYAL LIMITED (d2003-02-28)"},{"lang":"hk","v":"威遠有限公司"}],"company_since":"1998-07-20","company_dissolved":"2003-02-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650296","names":[{"lang":"en","v":"GUANGDA XINSHENG (HK) LIMITED"},{"lang":"hk","v":"光大新生(香港)有限公司"}],"company_since":"1998-07-20","company_dissolved":"2002-08-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650328","names":[{"lang":"en","v":"HEEPSON HOLDINGS LIMITED"},{"lang":"hk","v":"協新集團有限公司"}],"company_since":"1998-07-20","company_dissolved":"2003-04-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650316","names":[{"lang":"en","v":"HIPPON ENTERPRISE LIMITED"},{"lang":"hk","v":"興安企業有限公司"}],"company_since":"1998-07-20","company_dissolved":"2001-02-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650351","names":[{"lang":"en","v":"HIRASHO HONG KONG LIMITED"},{"lang":"hk","v":"平章香港有限公司"}],"company_since":"1998-07-20","company_dissolved":"2014-11-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650340","names":[{"lang":"en","v":"HOI WAI METAL MANUFACTORY COMPANY LIMITED"},{"lang":"hk","v":"海威五金製品有限公司"}],"company_since":"1998-07-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650331","names":[{"lang":"en","v":"HONG KONG CRITICAL COMPONENTS MANUFACTURERS ASSOCIATION LIMITED"},{"lang":"hk","v":"香港關鍵性零部件製造業協會有限公司"}],"company_since":"1998-07-20","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
undefined,
undefined,
{"tax_id":"650270","names":[{"lang":"en","v":"FORTUNE WELL MANUFACTURING LIMITED"},{"lang":"hk","v":"福進製作有限公司"}],"company_since":"1998-07-20","company_dissolved":"2001-08-31","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650301","names":[{"lang":"en","v":"HUSTON DEVELOPMENT LIMITED (d2003-02-28)"},{"lang":"hk","v":"豪迅發展有限公司"}],"company_since":"1998-07-20","company_dissolved":"2003-02-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650352","names":[{"lang":"en","v":"HONG KONG ZHIJINHUA FILMS ART INSTITUTION LIMITED"},{"lang":"hk","v":"香港紫荊花影藝有限公司"}],"company_since":"1998-07-20","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650257","names":[{"lang":"en","v":"HONG KONG STORAGE LIMITED"},{"lang":"hk","v":"香港儲物室有限公司"}],"company_since":"1998-07-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650303","names":[{"lang":"en","v":"JANFAIR TRADING LIMITED"},{"lang":"hk","v":"駿輝貿易有限公司"}],"company_since":"1998-07-20","company_dissolved":"2003-02-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650287","names":[{"lang":"en","v":"JOIN WORLD HOLDINGS LIMITED"},{"lang":"hk","v":"合裕集團有限公司"}],"company_since":"1998-07-20","company_dissolved":"2005-11-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650272","names":[{"lang":"en","v":"JVNF (HK) TRADING LIMITED"},{"lang":"hk","v":"駿發(香港)貿易有限公司"}],"company_since":"1998-07-20","company_dissolved":"2011-03-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650362","names":[{"lang":"en","v":"KGI SECURITIES (KOREA) INTERNATIONAL LIMITED"}],"company_since":"1998-07-20","company_dissolved":"2007-05-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650341","names":[{"lang":"en","v":"KING STAR GROUPS LIMITED"},{"lang":"hk","v":"康大集團有限公司"}],"company_since":"1998-07-20","company_dissolved":"2002-10-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650359","names":[{"lang":"en","v":"LENOVO QDI LIMITED"},{"lang":"hk","v":"聯想電子有限公司"}],"company_since":"1998-07-20","company_dissolved":"2007-03-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650345","names":[{"lang":"en","v":"HUAHUI INDUSTRIAL (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"華匯實業(香港)有限公司"}],"company_since":"1998-07-20","company_dissolved":"2003-05-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650236","names":[{"lang":"en","v":"LOYAL HOST LIMITED"},{"lang":"hk","v":"立鴻有限公司"}],"company_since":"1998-07-20","company_dissolved":"2002-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650237","names":[{"lang":"en","v":"LOYAL WISH LIMITED (d2002-02-22)"},{"lang":"hk","v":"宜志有限公司"}],"company_since":"1998-07-20","company_dissolved":"2002-02-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650241","names":[{"lang":"en","v":"EXCEL TIME ENTERPRISES LIMITED"},{"lang":"hk","v":"豪佳企業有限公司"}],"company_since":"1998-07-20","company_dissolved":"2009-08-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650320","names":[{"lang":"en","v":"EXPRESS HONOR DEVELOPMENT LIMITED (d2005-07-22)"},{"lang":"hk","v":"誠迅發展有限公司"}],"company_since":"1998-07-20","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650356","names":[{"lang":"en","v":"M T DYEING FACTORY LIMITED"},{"lang":"hk","v":"銘登染廠有限公司"}],"company_since":"1998-07-20","company_dissolved":"2003-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650244","names":[{"lang":"en","v":"MIZU INDUSTRIES LIMITED"}],"company_since":"1998-07-20","company_dissolved":"2002-03-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650289","names":[{"lang":"en","v":"NAIVE FLORIST AND GIFTS LIMITED"}],"company_since":"1998-07-20","company_dissolved":"2001-01-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650288","names":[{"lang":"en","v":"NEW BRIGHT HOLDINGS LIMITED (d2005-07-22)"},{"lang":"hk","v":"耀雅集團有限公司"}],"company_since":"1998-07-20","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650281","names":[{"lang":"en","v":"NOBLE ASIA DEVELOPMENT LIMITED"},{"lang":"hk","v":"冠寶發展有限公司"}],"company_since":"1998-07-20","company_dissolved":"2016-03-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650292","names":[{"lang":"en","v":"NOBLE DRAGON TRADING LIMITED (d2000-12-15)"},{"lang":"hk","v":"新龍貿易有限公司"}],"company_since":"1998-07-20","company_dissolved":"2000-12-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650282","names":[{"lang":"en","v":"FIRST PACIFIC CORPORATION LIMITED (d2005-07-22)"},{"lang":"hk","v":"亞太商業有限公司"}],"company_since":"1998-07-20","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650261","names":[{"lang":"en","v":"PACBELL SOURCING LIMITED"}],"company_since":"1998-07-20","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650332","names":[{"lang":"en","v":"PANORAMIC CONSULTING LIMITED (HK)"},{"lang":"hk","v":"全景信息諮詢有限公司"}],"company_since":"1998-07-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650342","names":[{"lang":"en","v":"OCL INTERNATIONAL LIMITED"}],"company_since":"1998-07-20","company_dissolved":"2003-03-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650274","names":[{"lang":"en","v":"PAR-FAI (CHINA) LIMITED"},{"lang":"hk","v":"佰輝(中國)有限公司"}],"company_since":"1998-07-20","company_dissolved":"2010-06-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650358","names":[{"lang":"en","v":"ITALY BO'S WAI GARMENTS GROUP LIMITED"},{"lang":"hk","v":"意大利堡芝威服飾集團有限公司"}],"company_since":"1998-07-20","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650334","names":[{"lang":"en","v":"PERFECT SHARP APPAREL LIMITED"}],"company_since":"1998-07-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650302","names":[{"lang":"en","v":"FRANYARD DEVELOPMENT LIMITED"},{"lang":"hk","v":"福億發展有限公司"}],"company_since":"1998-07-20","company_dissolved":"2001-09-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650293","names":[{"lang":"en","v":"POLY BEST PACIFIC LIMITED"},{"lang":"hk","v":"利寶太平洋有限公司"}],"company_since":"1998-07-20","company_dissolved":"2003-03-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650250","names":[{"lang":"en","v":"PRECISION MICROWAVE (H.K.) LIMITED"},{"lang":"hk","v":"精確微波(香港)有限公司"}],"company_since":"1998-07-20","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650290","names":[{"lang":"en","v":"RICH TEAM TRADING LIMITED"},{"lang":"hk","v":"廣利貿易有限公司"}],"company_since":"1998-07-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650306","names":[{"lang":"en","v":"RICHLAND CONTRACTORS LIMITED"},{"lang":"hk","v":"利林建造有限公司"}],"company_since":"1998-07-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650317","names":[{"lang":"en","v":"RICHVIEW DEVELOPMENT LIMITED (d2004-07-16)"},{"lang":"hk","v":"裕景發展有限公司"}],"company_since":"1998-07-20","company_dissolved":"2004-07-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650348","names":[{"lang":"en","v":"ROCKY GROUP LIMITED"},{"lang":"hk","v":"樂群有限公司"}],"company_since":"1998-07-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650285","names":[{"lang":"en","v":"ROYAL BUSINESS INVESTMENT LIMITED"},{"lang":"hk","v":"冠業投資有限公司"}],"company_since":"1998-07-20","company_dissolved":"2006-07-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650321","names":[{"lang":"en","v":"GIANT CHINA INVESTMENT LIMITED"},{"lang":"hk","v":"漢英投資有限公司"}],"company_since":"1998-07-20","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650299","names":[{"lang":"en","v":"ROYAL SMART INVESTMENT LIMITED"},{"lang":"hk","v":"緯嘉投資有限公司"}],"company_since":"1998-07-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650324","names":[{"lang":"en","v":"ROYAL SUN INVESTMENT LIMITED"},{"lang":"hk","v":"亨耀投資有限公司"}],"company_since":"1998-07-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650327","names":[{"lang":"en","v":"GIANT LUCK HOLDINGS LIMITED"},{"lang":"hk","v":"順廣集團有限公司"}],"company_since":"1998-07-20","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650298","names":[{"lang":"en","v":"GOLD ANCHOR INVESTMENT LIMITED"},{"lang":"hk","v":"君安投資有限公司"}],"company_since":"1998-07-20","company_dissolved":"2013-05-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650280","names":[{"lang":"en","v":"SAPNA INTERNATIONAL (H.K.) LIMITED"}],"company_since":"1998-07-20","company_dissolved":"2017-04-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650254","names":[{"lang":"en","v":"GOLDEN CEDAR GARMENT ACCESSORIES INTERNATIONAL LIMITED"},{"lang":"hk","v":"金柏製衣配料國際有限公司"}],"company_since":"1998-07-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650329","names":[{"lang":"en","v":"GOOD HERO HONG KONG LIMITED"},{"lang":"hk","v":"耀鴻香港有限公司"}],"company_since":"1998-07-20","company_dissolved":"2000-09-29","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650295","names":[{"lang":"en","v":"SINO MASTER IMPORT &amp; EXPORT LIMITED"},{"lang":"hk","v":"中貿進出口有限公司"}],"company_since":"1998-07-20","company_dissolved":"2000-07-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650291","names":[{"lang":"en","v":"SMART LEADER TRADING LIMITED (d2002-01-04)"},{"lang":"hk","v":"卓耀貿易有限公司"}],"company_since":"1998-07-20","company_dissolved":"2002-01-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650310","names":[{"lang":"en","v":"SPECIAL YIELD INVESTMENT LIMITED"},{"lang":"hk","v":"超昇投資有限公司"}],"company_since":"1998-07-20","company_dissolved":"2001-06-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650235","names":[{"lang":"en","v":"FUMI HONG KONG LIMITED"},{"lang":"hk","v":"富美香港有限公司"}],"company_since":"1998-07-20","company_dissolved":"2007-01-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650273","names":[{"lang":"en","v":"TAK HING FAT FURNITURE COMPANY LIMITED"},{"lang":"hk","v":"德興發傢俬有限公司"}],"company_since":"1998-07-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650263","names":[{"lang":"en","v":"TIDETIME LIXUN LIMITED"},{"lang":"hk","v":"泰德立訊有限公司"}],"company_since":"1998-07-20","company_dissolved":"2013-05-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650339","names":[{"lang":"en","v":"TOPBIZ LIMITED (d2002-01-11)"}],"company_since":"1998-07-20","company_dissolved":"2002-01-11","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650245","names":[{"lang":"en","v":"TORAYCODO COLORANTS INDUSTRY COMPANY LIMITED"},{"lang":"hk","v":"特麗可得實業有限公司"}],"company_since":"1998-07-20","company_dissolved":"2009-01-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650309","names":[{"lang":"en","v":"HMI STONEWORK LIMITED"},{"lang":"hk","v":"恆和國際石業有限公司"}],"company_since":"1998-07-20","company_dissolved":"2006-09-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650269","names":[{"lang":"en","v":"TORONTO FUR &amp; LEATHER (H.K.) LIMITED"},{"lang":"hk","v":"多倫多皮草(香港)有限公司"}],"company_since":"1998-07-20","company_dissolved":"2009-01-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650336","names":[{"lang":"en","v":"VENTURA PRODUCTS INTERNATIONAL HONG KONG LIMITED"}],"company_since":"1998-07-20","company_dissolved":"2001-08-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"650265","names":[{"lang":"en","v":"WAI CHING (TECHNOLOGY) COMPANY LIMITED"},{"lang":"hk","v":"偉程(科技)有限公司"}],"company_since":"1998-07-20","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650363","names":[{"lang":"en","v":"HONG KONG KE'S INTERNATIONAL TRADING LIMITED"},{"lang":"hk","v":"香港柯氏國際貿易有限公司"}],"company_since":"1998-07-20","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650333","names":[{"lang":"en","v":"HONG KONG MEI JIA MEI DI CLEANING PRODUCTS INTERNATIONAL HOLDING LIMITED"},{"lang":"hk","v":"香港美加美迪潔具國際集團有限公司"}],"company_since":"1998-07-20","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650284","names":[{"lang":"en","v":"WEALTHY TECH INVESTMENT LIMITED"},{"lang":"hk","v":"豐裕投資有限公司"}],"company_since":"1998-07-20","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650350","names":[{"lang":"en","v":"WELLOCK HONG KONG LIMITED (d2004-01-02)"},{"lang":"hk","v":"華樂香港有限公司"}],"company_since":"1998-07-20","company_dissolved":"2004-01-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650259","names":[{"lang":"en","v":"HONGKONG DIVEDRAGON PHARMACEUTICAL CO., LIMITED"},{"lang":"hk","v":"香港潛龍藥業有限公司"}],"company_since":"1998-07-20","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650268","names":[{"lang":"en","v":"WILSON INTERIOR CONTRACTING COMPANY LIMITED"},{"lang":"hk","v":"麗豪設計工程有限公司"}],"company_since":"1998-07-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650242","names":[{"lang":"en","v":"YEE SING ENTERPRISES COMPANY LIMITED"},{"lang":"hk","v":"怡昇實業有限公司"}],"company_since":"1998-07-20","company_dissolved":"2001-10-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650311","names":[{"lang":"en","v":"HOMFAIR HOLDINGS LIMITED"},{"lang":"hk","v":"漢輝集團有限公司"}],"company_since":"1998-07-20","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"650322","names":[{"lang":"en","v":"MAN SHING ENGINEERING (H. K.) LIMITED"},{"lang":"hk","v":"萬承工程(香港)有限公司"}],"company_since":"1998-07-20","company_dissolved":"2001-03-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650346","names":[{"lang":"en","v":"SUPER BRAVE LIMITED"},{"lang":"hk","v":"昭榮有限公司"}],"company_since":"1998-07-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650344","names":[{"lang":"en","v":"TOP TREASURE TRADING LIMITED (d2008-12-24)"},{"lang":"hk","v":"寶健貿易有限公司"}],"company_since":"1998-07-20","company_dissolved":"2008-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
