{"tax_id":"650024","names":[{"lang":"en","v":"CREST LINE INTERNATIONAL LIMITED"},{"lang":"hk","v":"高航國際有限公司"}],"company_since":"1998-07-17","company_dissolved":"2001-03-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650080","names":[{"lang":"en","v":"CS LAI MARINE CONSULTANT COMPANY LIMITED"},{"lang":"hk","v":"黎澤生海事顧問有限公司"}],"company_since":"1998-07-17","company_dissolved":"2001-11-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650196","names":[{"lang":"en","v":"DELUXE WAY HOLDINGS LIMITED"},{"lang":"hk","v":"豪發集團有限公司"}],"company_since":"1998-07-17","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650218","names":[{"lang":"en","v":"DESON TECHNOLOGY COMPANY LIMITED"},{"lang":"hk","v":"迪臣科技有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650184","names":[{"lang":"en","v":"DOMUS INTERNATIONAL LIMITED (HK)"},{"lang":"hk","v":"國際道明有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650108","names":[{"lang":"en","v":"DYNAMICS COMPUTER TECHNOLOGY LIMITED"},{"lang":"hk","v":"動力電腦科技有限公司"}],"company_since":"1998-07-17","company_dissolved":"2003-09-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650024","names":[{"lang":"en","v":"CREST LINE INTERNATIONAL LIMITED"},{"lang":"hk","v":"高航國際有限公司"}],"company_since":"1998-07-17","company_dissolved":"2001-03-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650080","names":[{"lang":"en","v":"CS LAI MARINE CONSULTANT COMPANY LIMITED"},{"lang":"hk","v":"黎澤生海事顧問有限公司"}],"company_since":"1998-07-17","company_dissolved":"2001-11-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650196","names":[{"lang":"en","v":"DELUXE WAY HOLDINGS LIMITED"},{"lang":"hk","v":"豪發集團有限公司"}],"company_since":"1998-07-17","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650143","names":[{"lang":"en","v":"EATSUN ENTERPRISE LIMITED"},{"lang":"hk","v":"食神飲食集團有限公司"}],"company_since":"1998-07-17","company_dissolved":"2018-11-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650202","names":[{"lang":"en","v":"EMSARU LIMITED"},{"lang":"hk","v":"翠湖有限公司"}],"company_since":"1998-07-17","company_dissolved":"2005-12-16","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650160","names":[{"lang":"en","v":"ENVIROPOWER LIMITED"},{"lang":"hk","v":"環保動力有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650018","names":[{"lang":"en","v":"EVER SHINE MATERIALS &amp; TRADING LIMITED"},{"lang":"hk","v":"恆輝原料貿易有限公司"}],"company_since":"1998-07-17","company_dissolved":"2013-03-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650226","names":[{"lang":"en","v":"EVER TOP HOLDINGS LIMITED"},{"lang":"hk","v":"恒卓集團有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650220","names":[{"lang":"en","v":"EVERFLOW HOLDING LIMITED"},{"lang":"hk","v":"恒滔集團有限公司"}],"company_since":"1998-07-17","company_dissolved":"2017-12-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650204","names":[{"lang":"en","v":"FORTUNE WELL (FAR EAST) LIMITED"},{"lang":"hk","v":"福進(遠東)有限公司"}],"company_since":"1998-07-17","company_dissolved":"2001-08-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650046","names":[{"lang":"en","v":"FRESH MEAT SHOP LIMITED"},{"lang":"hk","v":"新鮮肉食店有限公司"}],"company_since":"1998-07-17","company_dissolved":"2017-03-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650032","names":[{"lang":"en","v":"GALEO LIMITED (d2003-01-24)"},{"lang":"hk","v":"中法貿易有限公司"}],"company_since":"1998-07-17","company_dissolved":"2003-01-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650072","names":[{"lang":"en","v":"GARFULEY (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"嘉富利(香港)有限公司"}],"company_since":"1998-07-17","company_dissolved":"2004-10-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650192","names":[{"lang":"en","v":"GIL MEDIA PRODUCTIONS LIMITED"},{"lang":"hk","v":"佳利媒體製品有限公司"}],"company_since":"1998-07-17","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650073","names":[{"lang":"en","v":"GLAD FORTUNE RESOURCES LIMITED"},{"lang":"hk","v":"佳富資源有限公司"}],"company_since":"1998-07-17","company_dissolved":"2005-04-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650034","names":[{"lang":"en","v":"GLOBAL ENTERPRISES COMPANY LIMITED"},{"lang":"hk","v":"新環球企業有限公司"}],"company_since":"1998-07-17","company_dissolved":"2008-06-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650229","names":[{"lang":"en","v":"GOLD SOURCE (ASIA) LIMITED"},{"lang":"hk","v":"金源(亞洲)有限公司"}],"company_since":"1998-07-17","company_dissolved":"2009-05-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650036","names":[{"lang":"en","v":"GOLDEN HIGHLAND ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"浩禾工程有限公司"}],"company_since":"1998-07-17","company_dissolved":"2001-11-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650207","names":[{"lang":"en","v":"GOLDEN LION INTERNATIONAL TRADING LIMITED"},{"lang":"hk","v":"美勝貿易有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650066","names":[{"lang":"en","v":"GOOD LIFE PRODUCTIONS LIMITED"}],"company_since":"1998-07-17","company_dissolved":"2007-06-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650145","names":[{"lang":"en","v":"GREAT LAKE LIMITED"},{"lang":"hk","v":"悅湖有限公司"}],"company_since":"1998-07-17","company_dissolved":"2012-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650087","names":[{"lang":"en","v":"HANSON SHIPPING COMPANY LIMITED (d2012-11-09)"},{"lang":"hk","v":"恒駿船務有限公司"}],"company_since":"1998-07-17","company_dissolved":"2012-11-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650153","names":[{"lang":"en","v":"HOI CHI PO LIMITED"},{"lang":"hk","v":"海之寶有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650117","names":[{"lang":"en","v":"HONG KONG CHUNG YUEN INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"香港中遠國際有限公司"}],"company_since":"1998-07-17","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650015","names":[{"lang":"en","v":"HONG KONG (HUNAN) TRAVEL SERVICE LIMITED"},{"lang":"hk","v":"香港(湖南)旅遊有限公司"}],"company_since":"1998-07-17","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650075","names":[{"lang":"en","v":"HOLD STAR (HONG KONG) LIMITED"},{"lang":"hk","v":"浩星(香港)有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650193","names":[{"lang":"en","v":"HONG KONG CONRAD HI-TECH PARK LIMITED"},{"lang":"hk","v":"香港安力科技園有限公司"}],"company_since":"1998-07-17","company_dissolved":"2018-04-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650209","names":[{"lang":"en","v":"HONG KONG EASELONG (INTERNATIONAL) LIMITED"},{"lang":"hk","v":"香港英朗(國際)有限公司"}],"company_since":"1998-07-17","company_dissolved":"2005-09-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650224","names":[{"lang":"en","v":"HONG KONG GOLDEN INTERNATIONAL INVESTMENT DEVELOPMENT LIMITED"},{"lang":"hk","v":"香港鑫正國際投資發展有限公司"}],"company_since":"1998-07-17","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650114","names":[{"lang":"en","v":"HONG KONG JIA FU PROPERTY MANAGEMENT LIMITED"},{"lang":"hk","v":"香港嘉福置業管理有限公司"}],"company_since":"1998-07-17","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650049","names":[{"lang":"en","v":"FWL TECHNOLOGIES ASIA LIMITED"}],"company_since":"1998-07-17","company_dissolved":"2007-11-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649986","names":[{"lang":"en","v":"HOPSON ENGINEERING LIMITED (d2012-03-09)"},{"lang":"hk","v":"合信工程有限公司"}],"company_since":"1998-07-17","company_dissolved":"2012-03-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"649988","names":[{"lang":"en","v":"HOPWAY TECHNOLOGIES LIMITED"},{"lang":"hk","v":"合威科技有限公司"}],"company_since":"1998-07-17","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650227","names":[{"lang":"en","v":"HUNG SHING (HONG KONG) HANDBAGS MFG CO. LIMITED"},{"lang":"hk","v":"鴻鑫(香港)手袋廠有限公司"}],"company_since":"1998-07-17","company_dissolved":"2004-07-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650217","names":[{"lang":"en","v":"INFINITY SYSTEM INTEGRATION LIMITED"},{"lang":"hk","v":"深遠系統有限公司"}],"company_since":"1998-07-17","company_dissolved":"2011-03-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650169","names":[{"lang":"en","v":"INTEGRATED TECHNOLOGY EXPRESS LIMITED"},{"lang":"hk","v":"聯陽(香港)有限公司"}],"company_since":"1998-07-17","company_dissolved":"2002-01-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650184","names":[{"lang":"en","v":"DOMUS INTERNATIONAL LIMITED (HK)"},{"lang":"hk","v":"國際道明有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650161","names":[{"lang":"en","v":"JADEWAY TRADING LIMITED (d2005-09-09)"},{"lang":"hk","v":"致威貿易有限公司"}],"company_since":"1998-07-17","company_dissolved":"2005-09-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650127","names":[{"lang":"en","v":"INTERACTION GROUP COMPANY LIMITED (THE)"}],"company_since":"1998-07-17","company_dissolved":"2006-12-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650108","names":[{"lang":"en","v":"DYNAMICS COMPUTER TECHNOLOGY LIMITED"},{"lang":"hk","v":"動力電腦科技有限公司"}],"company_since":"1998-07-17","company_dissolved":"2003-09-26","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650130","names":[{"lang":"en","v":"KA JADE DEVELOPMENT LIMITED"},{"lang":"hk","v":"嘉翠發展有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650039","names":[{"lang":"en","v":"KAI LONG HOLDINGS LIMITED"},{"lang":"hk","v":"凱龍集團股份有限公司"}],"company_since":"1998-07-17","company_dissolved":"2003-09-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650057","names":[{"lang":"en","v":"KAM BO ELECTRONICS (GROUP) COMPANY LIMITED"},{"lang":"hk","v":"金寶電子(集團)有限公司"}],"company_since":"1998-07-17","company_dissolved":"2008-06-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650131","names":[{"lang":"en","v":"KEEN HUNG INVESTMENT LIMITED"},{"lang":"hk","v":"健鴻投資有限公司"}],"company_since":"1998-07-17","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650180","names":[{"lang":"en","v":"EARNTON TRADING (H.K.) COMPANY LIMITED"},{"lang":"hk","v":"潤天貿易(香港)有限公司"}],"company_since":"1998-07-17","company_dissolved":"2018-06-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650225","names":[{"lang":"en","v":"KOWLOON STORAGE LIMITED"},{"lang":"hk","v":"九龍儲物室有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650141","names":[{"lang":"en","v":"KWONG FLY LIMITED"},{"lang":"hk","v":"廣飛有限公司"}],"company_since":"1998-07-17","company_dissolved":"2007-11-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649992","names":[{"lang":"en","v":"EASY HARBOUR DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"怡港發展有限公司"}],"company_since":"1998-07-17","company_dissolved":"2001-01-05","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650082","names":[{"lang":"en","v":"LEIF LOWE INVESTMENT LIMITED"},{"lang":"hk","v":"順榮仕投資有限公司"}],"company_since":"1998-07-17","company_dissolved":"2011-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"649989","names":[{"lang":"en","v":"LICO CONSULTANTS LIMITED"},{"lang":"hk","v":"利高顧問有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650194","names":[{"lang":"en","v":"LIH HAAN INDUSTRY LIMITED"},{"lang":"hk","v":"力瀚企業有限公司"}],"company_since":"1998-07-17","company_dissolved":"2004-11-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650142","names":[{"lang":"en","v":"LINKPO RICH LIMITED"},{"lang":"hk","v":"利寶富有限公司"}],"company_since":"1998-07-17","company_dissolved":"2004-04-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649987","names":[{"lang":"en","v":"LUCKY WAY SHIPPING LIMITED"},{"lang":"hk","v":"利威船務有限公司"}],"company_since":"1998-07-17","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649985","names":[{"lang":"en","v":"LUCKY WIN CONSULTANTS LIMITED (d2005-06-03)"},{"lang":"hk","v":"利成顧問有限公司"}],"company_since":"1998-07-17","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650084","names":[{"lang":"en","v":"LUCKY WOOD ASIA LIMITED"},{"lang":"hk","v":"好彩木業有限公司"}],"company_since":"1998-07-17","company_dissolved":"2015-07-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650183","names":[{"lang":"en","v":"LUCKY-STAR SHIPPING LIMITED"},{"lang":"hk","v":"運星船務有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650126","names":[{"lang":"en","v":"FOREVER ASSETS PROPERTY LIMITED"},{"lang":"hk","v":"億佳物業有限公司"}],"company_since":"1998-07-17","company_dissolved":"2004-12-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650013","names":[{"lang":"en","v":"MARUBENI ASIAN POWER LIMITED"}],"company_since":"1998-07-17","company_dissolved":"2011-11-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650048","names":[{"lang":"en","v":"MAXER INTERNATIONAL JEWELLERY COMPANY LIMITED"},{"lang":"hk","v":"萬星國際珠寶有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650076","names":[{"lang":"en","v":"MAXVENTURE INVESTMENT LIMITED"},{"lang":"hk","v":"逸濠投資有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650106","names":[{"lang":"en","v":"FULL KIN GARMENT LIMITED"},{"lang":"hk","v":"富建製衣有限公司"}],"company_since":"1998-07-17","company_dissolved":"2002-03-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650031","names":[{"lang":"en","v":"LEONARD S.A. LIMITED"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649996","names":[{"lang":"en","v":"MIS TECHNOLOGIES CENTRE (HK) LIMITED"},{"lang":"hk","v":"智囊團科技中心(香港)有限公司"}],"company_since":"1998-07-17","company_dissolved":"2009-06-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650186","names":[{"lang":"en","v":"MULTI-MARKET HOLDINGS LIMITED"},{"lang":"hk","v":"萬茂集團有限公司"}],"company_since":"1998-07-17","company_dissolved":"2005-12-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650140","names":[{"lang":"en","v":"NATION GOOD HOLDINGS LIMITED"},{"lang":"hk","v":"國悅集團有限公司"}],"company_since":"1998-07-17","company_dissolved":"2002-11-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650189","names":[{"lang":"en","v":"NEW CENTURY CORPORATION LIMITED (d2006-12-29)"},{"lang":"hk","v":"新時代創業有限公司"}],"company_since":"1998-07-17","company_dissolved":"2006-12-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650040","names":[{"lang":"en","v":"GREAT STAR INDUSTRIAL LIMITED (d2010-08-06)"},{"lang":"hk","v":"永星實業有限公司"}],"company_since":"1998-07-17","company_dissolved":"2010-08-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650078","names":[{"lang":"en","v":"NEWDEX INDUSTRIES LIMITED"},{"lang":"hk","v":"新羚實業有限公司"}],"company_since":"1998-07-17","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650159","names":[{"lang":"en","v":"ON EAGLE LIMITED"},{"lang":"hk","v":"安鷹有限公司"}],"company_since":"1998-07-17","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650090","names":[{"lang":"en","v":"HAPPY DYNASTY HOLDINGS LIMITED"},{"lang":"hk","v":"凱霆有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650154","names":[{"lang":"en","v":"P &amp; L INTERNATIONAL INVESTMENT AND ENGINEERING LIMITED"}],"company_since":"1998-07-17","company_dissolved":"2008-07-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650022","names":[{"lang":"en","v":"PACIFIC BOND (H.K.) LIMITED"},{"lang":"hk","v":"榮裕(香港)有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650171","names":[{"lang":"en","v":"PACIFIC UNITED INVESTMENTS LIMITED (d2009-02-27)"},{"lang":"hk","v":"太平洋聯合投資有限公司"}],"company_since":"1998-07-17","company_dissolved":"2009-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650035","names":[{"lang":"en","v":"PC WINNER INTERNATIONAL INC. LIMITED"},{"lang":"hk","v":"永炘國際有限公司"}],"company_since":"1998-07-17","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650199","names":[{"lang":"en","v":"HAPPY GRACE LIMITED (d2012-01-06)"},{"lang":"hk","v":"欣頌有限公司"}],"company_since":"1998-07-17","company_dissolved":"2012-01-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"649999","names":[{"lang":"en","v":"PIPEWORKS TECHNOLOGY LIMITED"}],"company_since":"1998-07-17","company_dissolved":"2008-10-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650219","names":[{"lang":"en","v":"OSCAR TOYS COMPANY LIMITED"},{"lang":"hk","v":"彩聯玩具有限公司"}],"company_since":"1998-07-17","company_dissolved":"2003-05-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650134","names":[{"lang":"en","v":"POWER CHARM (ASIA) LIMITED"},{"lang":"hk","v":"寶創亞洲有限公司"}],"company_since":"1998-07-17","company_dissolved":"2006-12-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650113","names":[{"lang":"en","v":"PRO'8 TECHNOLOGIES LIMITED"},{"lang":"hk","v":"普勤科技智業有限公司"}],"company_since":"1998-07-17","company_dissolved":"2015-07-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"650099","names":[{"lang":"en","v":"SANJIU CAPITAL LIMITED"},{"lang":"hk","v":"三九資本有限公司"}],"company_since":"1998-07-17","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650195","names":[{"lang":"en","v":"SHOU WANG (H.K.) LIMITED"},{"lang":"hk","v":"獸王(香港)有限公司"}],"company_since":"1998-07-17","company_dissolved":"2003-05-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"650005","names":[{"lang":"en","v":"SMILE CLINIC LIMITED"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650210","names":[{"lang":"en","v":"SOUTH PACIFIC ISLAND GROUP LIMITED"},{"lang":"hk","v":"南太平洋島(集團)有限公司"}],"company_since":"1998-07-17","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650147","names":[{"lang":"en","v":"SOUTH UNIVERSE LIMITED"},{"lang":"hk","v":"南湖有限公司"}],"company_since":"1998-07-17","company_dissolved":"2008-06-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650139","names":[{"lang":"en","v":"STAR EMPIRE GROUP LIMITED"},{"lang":"hk","v":"星帝集團有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650001","names":[{"lang":"en","v":"SUNNY'S ENTERPRISES COMPANY LIMITED"},{"lang":"hk","v":"華晴企業有限公司"}],"company_since":"1998-07-17","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650068","names":[{"lang":"en","v":"SUPER-T LIMITED (d2000-09-15)"},{"lang":"hk","v":"超級組有限公司"}],"company_since":"1998-07-17","company_dissolved":"2000-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650091","names":[{"lang":"en","v":"TAI LUEN SCAFFOLDING COMPANY LIMITED"},{"lang":"hk","v":"大聯棚業有限公司"}],"company_since":"1998-07-17","company_dissolved":"2005-12-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650123","names":[{"lang":"en","v":"TERON INTERNATIONAL LIMITED"}],"company_since":"1998-07-17","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650135","names":[{"lang":"en","v":"TOKENDO LIMITED"},{"lang":"hk","v":"東健堂有限公司"}],"company_since":"1998-07-17","company_dissolved":"2001-07-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650166","names":[{"lang":"en","v":"TOP ROYAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"智豪發展有限公司"}],"company_since":"1998-07-17","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650165","names":[{"lang":"en","v":"TOP PERFECT DEVELOPMENT LIMITED (d2005-07-22)"},{"lang":"hk","v":"德致發展有限公司"}],"company_since":"1998-07-17","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649993","names":[{"lang":"en","v":"TRICOWELL MARINE CONSULTANT COMPANY LIMITED"},{"lang":"hk","v":"昌維海事顧問有限公司"}],"company_since":"1998-07-17","company_dissolved":"2005-02-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650149","names":[{"lang":"en","v":"POLYTECH MANAGEMENT LIMITED"},{"lang":"hk","v":"寶達管理有限公司"}],"company_since":"1998-07-17","company_dissolved":"2012-07-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650112","names":[{"lang":"en","v":"PIONEER CONDUCTOR RUBBER (HONG KONG) INDUSTRY CO., LIMITED"},{"lang":"hk","v":"先鋒精密橡膠(香港)有限公司"}],"company_since":"1998-07-17","company_dissolved":"2003-05-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650083","names":[{"lang":"en","v":"TUNG NAM MOTOR HOLDINGS LIMITED"},{"lang":"hk","v":"東南汽車集團有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650088","names":[{"lang":"en","v":"PRECIOUS (HK) LIMITED (d2006-02-10)"}],"company_since":"1998-07-17","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650158","names":[{"lang":"en","v":"PRIME HERO LIMITED (d2006-02-10)"},{"lang":"hk","v":"澤雄有限公司"}],"company_since":"1998-07-17","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650129","names":[{"lang":"en","v":"UNION WIDE HOLDINGS LIMITED (d2007-03-30)"},{"lang":"hk","v":"協偉集團有限公司"}],"company_since":"1998-07-17","company_dissolved":"2007-03-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649995","names":[{"lang":"en","v":"UNITED BEST (HK) INDUSTRIAL CO. LIMITED"},{"lang":"hk","v":"聯益(香港)實業有限公司"}],"company_since":"1998-07-17","company_dissolved":"2008-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"650172","names":[{"lang":"en","v":"RICH TRADING COMPANY LIMITED"}],"company_since":"1998-07-17","company_dissolved":"2018-06-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650079","names":[{"lang":"en","v":"PROFIT EASE INDUSTRIES LIMITED"},{"lang":"hk","v":"富浚實業有限公司"}],"company_since":"1998-07-17","company_dissolved":"2002-05-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650148","names":[{"lang":"en","v":"UNITED NATIONS LIMITED (HK)"},{"lang":"hk","v":"國際有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650111","names":[{"lang":"en","v":"UNIVERSAL SUCCESS ENTERPRISES LIMITED"},{"lang":"hk","v":"有暉企業有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650037","names":[{"lang":"en","v":"RECKON HONG KONG LIMITED"},{"lang":"hk","v":"財捷香港有限公司"}],"company_since":"1998-07-17","company_dissolved":"2003-01-29","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650070","names":[{"lang":"en","v":"VERITAS INVESTMENT LIMITED"},{"lang":"hk","v":"威瑞達投資有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650017","names":[{"lang":"en","v":"VINDEX DEVELOPMENT LIMITED"},{"lang":"hk","v":"榮德發展有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650007","names":[{"lang":"en","v":"VIVID INTERNATIONAL LIMITED (d2005-05-13)"}],"company_since":"1998-07-17","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650119","names":[{"lang":"en","v":"W&amp;J INTERNATIONAL EXPRESS LIMITED"},{"lang":"hk","v":"永捷國際速遞有限公司"}],"company_since":"1998-07-17","company_dissolved":"2003-01-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650012","names":[{"lang":"en","v":"WANG YIP WIRE MANUFACTORY LIMITED"},{"lang":"hk","v":"宏業電線廠有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"650167","names":[{"lang":"en","v":"WESTLINK ENTERPRISE LIMITED"},{"lang":"hk","v":"威聯企業有限公司"}],"company_since":"1998-07-17","company_dissolved":"2005-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650177","names":[{"lang":"en","v":"WHOLE HEALTH INTERNATIONAL GROUP LIMITED"},{"lang":"hk","v":"億康藥業國際集團有限公司"}],"company_since":"1998-07-17","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650104","names":[{"lang":"en","v":"ROOFER INTERNATIONAL LIMITED"},{"lang":"hk","v":"路華國際有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650107","names":[{"lang":"en","v":"RICHTONE SHIPPING LIMITED"},{"lang":"hk","v":"億達船務有限公司"}],"company_since":"1998-07-17","company_dissolved":"2002-06-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650124","names":[{"lang":"en","v":"WILL TOP RESOURCES LIMITED"},{"lang":"hk","v":"威鋒資源有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650041","names":[{"lang":"en","v":"WIN INTERNATIONAL INVESTMENTS LIMITED"},{"lang":"hk","v":"永興國際投資有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"650020","names":[{"lang":"en","v":"SHEK LAM DEVELOPMENT LIMITED"},{"lang":"hk","v":"石林發展有限公司"}],"company_since":"1998-07-17","company_dissolved":"2000-12-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650216","names":[{"lang":"en","v":"WIN UNITED HOLDINGS LIMITED"},{"lang":"hk","v":"永高聯合集團有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650014","names":[{"lang":"en","v":"SHING DAI INVESTMENT (CHINA) LIMITED"},{"lang":"hk","v":"聖大投資(中國)有限公司"}],"company_since":"1998-07-17","company_dissolved":"2002-08-23","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650059","names":[{"lang":"en","v":"WINBLE FOOTWEAR (HK) COMPANY LIMITED"},{"lang":"hk","v":"匯寶鞋業(香港)有限公司"}],"company_since":"1998-07-17","company_dissolved":"2002-10-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650101","names":[{"lang":"en","v":"SHUN DA CONTAINER SERVICES COMPANY LIMITED"},{"lang":"hk","v":"順達貨櫃服務有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650191","names":[{"lang":"en","v":"WING CHEONG ELECTRICAL APPLIANCE (HK) LIMITED"},{"lang":"hk","v":"榮昌電業(香港)有限公司"}],"company_since":"1998-07-17","company_dissolved":"2000-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649994","names":[{"lang":"en","v":"SILVER EAST INTERNATIONAL LIMITED (d2005-07-22)"},{"lang":"hk","v":"銀東國際有限公司"}],"company_since":"1998-07-17","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650081","names":[{"lang":"en","v":"WING SHING JEWELLERY TRADING (H.K.) LIMITED"},{"lang":"hk","v":"永盛珠寶貿易(香港)有限公司"}],"company_since":"1998-07-17","company_dissolved":"2003-05-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650061","names":[{"lang":"en","v":"WINNER H.K. INDUSTRIAL LIMITED"},{"lang":"hk","v":"永華香港實業有限公司"}],"company_since":"1998-07-17","company_dissolved":"2015-07-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"650044","names":[{"lang":"en","v":"WINSON KINGDOM LIMITED"},{"lang":"hk","v":"永新興業有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650063","names":[{"lang":"en","v":"WINSTAR OVERSEAS LIMITED"},{"lang":"hk","v":"永達海外有限公司"}],"company_since":"1998-07-17","company_dissolved":"2013-10-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650212","names":[{"lang":"en","v":"SINO FORCE INTERNATIONAL LIMITED"},{"lang":"hk","v":"港福國際有限公司"}],"company_since":"1998-07-17","company_dissolved":"2018-04-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650045","names":[{"lang":"en","v":"WINTRADE &amp; ASSOCIATES LIMITED"},{"lang":"hk","v":"永貿有限公司"}],"company_since":"1998-07-17","company_dissolved":"2014-01-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650168","names":[{"lang":"en","v":"SOCIETY FOR PROTECTION OF THE HARBOUR"},{"lang":"hk","v":"保護海港協會"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"650033","names":[{"lang":"en","v":"WORLDTONE TRADING COMPANY LIMITED"},{"lang":"hk","v":"世界通貿易有限公司"}],"company_since":"1998-07-17","company_dissolved":"2012-11-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650074","names":[{"lang":"en","v":"SOLAR CRYSTAL ENTERPRISES LIMITED"},{"lang":"hk","v":"日晶企業有限公司"}],"company_since":"1998-07-17","company_dissolved":"2003-11-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650214","names":[{"lang":"en","v":"WORLDWIDE BROKERAGE LIMITED"},{"lang":"hk","v":"環球證券有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650086","names":[{"lang":"en","v":"WUI HIU HONG KONG LIMITED"},{"lang":"hk","v":"匯梟香港有限公司"}],"company_since":"1998-07-17","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650026","names":[{"lang":"en","v":"YELLOW CRANE R&amp;D CO., LIMITED"},{"lang":"hk","v":"黃鶴研究開發有限公司"}],"company_since":"1998-07-17","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650003","names":[{"lang":"en","v":"ZIPPY CREATIVE CENTRE LIMITED"}],"company_since":"1998-07-17","company_dissolved":"2006-02-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"650174","names":[{"lang":"en","v":"SUPER BRIGHT INDUSTRIAL (HK) COMPANY LIMITED"},{"lang":"hk","v":"盛輝實業(香港)有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650097","names":[{"lang":"en","v":"SUN BO FURNITURE DEVELOPMENT CO. LIMITED"},{"lang":"hk","v":"新寶傢具發展有限公司"}],"company_since":"1998-07-17","company_dissolved":"2009-12-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649998","names":[{"lang":"en","v":"SUPERLINK ELECTRONIC LIMITED"},{"lang":"hk","v":"香港華訊電子有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650052","names":[{"lang":"en","v":"TIAN XIANG ENGINEERING CONSULTANTS LIMITED"},{"lang":"hk","v":"天翔工程顧問有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650085","names":[{"lang":"en","v":"LI MING INDUSTRIES LIMITED"},{"lang":"hk","v":"麗名實業有限公司"}],"company_since":"1998-07-17","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650105","names":[{"lang":"en","v":"TIMFUL GARMENT LIMITED"},{"lang":"hk","v":"昇豐製衣有限公司"}],"company_since":"1998-07-17","company_dissolved":"2004-10-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649984","names":[{"lang":"en","v":"TOPLINK MANAGEMENT LIMITED (d2009-12-04)"},{"lang":"hk","v":"榮利管理有限公司"}],"company_since":"1998-07-17","company_dissolved":"2009-12-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650098","names":[{"lang":"en","v":"R &amp; A CONCEPT LIMITED (d2006-02-10)"}],"company_since":"1998-07-17","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"649997","names":[{"lang":"en","v":"TREND TEXTILES LIMITED"},{"lang":"hk","v":"流行織物有限公司"}],"company_since":"1998-07-17","company_dissolved":"2005-12-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650125","names":[{"lang":"en","v":"UNITED SKY CORPORATION LIMITED"},{"lang":"hk","v":"天合資源有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"650121","names":[{"lang":"en","v":"WELLTEC PRODUCTS (HK) LIMITED"},{"lang":"hk","v":"華大製品(香港)有限公司"}],"company_since":"1998-07-17","company_dissolved":"2009-09-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"650064","names":[{"lang":"en","v":"WIN &amp; GRAND LIMITED"},{"lang":"hk","v":"永皓有限公司"}],"company_since":"1998-07-17","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"650173","names":[{"lang":"en","v":"WAH CHEONG INVESTMENTS LIMITED"}],"company_since":"1998-07-17","company_dissolved":"2003-04-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"650042","names":[{"lang":"en","v":"WINWOOD HOLDINGS LIMITED (d2004-02-06)"},{"lang":"hk","v":"永威集團有限公司"}],"company_since":"1998-07-17","company_dissolved":"2004-02-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"650056","names":[{"lang":"en","v":"ZENTEK INTERNATIONAL CO. LIMITED"}],"company_since":"1998-07-17","company_dissolved":"2014-01-17","company_type_txt":"Private, ltd by shares"},
undefined,
