{"tax_id":"649396","names":[{"lang":"en","v":"CROWN TARGET CONSULTANTS LIMITED"},{"lang":"hk","v":"冠達顧問有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649537","names":[{"lang":"en","v":"DASHIN SECURITIES HOLDINGS (H.K.) LIMITED"},{"lang":"hk","v":"大信証券集團(香港)有限公司"}],"company_since":"1998-07-10","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649532","names":[{"lang":"en","v":"DE RODEO HUMAN RESOURCES LIMITED"},{"lang":"hk","v":"快加好人力資源有限公司"}],"company_since":"1998-07-10","company_dissolved":"2015-03-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649432","names":[{"lang":"en","v":"DENHALL LIMITED (d2003-11-21)"},{"lang":"hk","v":"添浩有限公司"}],"company_since":"1998-07-10","company_dissolved":"2003-11-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649391","names":[{"lang":"en","v":"DERWICK LIMITED (HK)"},{"lang":"hk","v":"德惠有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649417","names":[{"lang":"en","v":"DICKSON OVERSEAS LIMITED"},{"lang":"hk","v":"達生海外有限公司"}],"company_since":"1998-07-10","company_dissolved":"2009-08-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649489","names":[{"lang":"en","v":"DISTRIBUTION SERVICES (SHENCAI) LIMITED"}],"company_since":"1998-07-10","company_dissolved":"2003-08-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649288","names":[{"lang":"en","v":"EAST KIYOHARA CO., LIMITED"},{"lang":"hk","v":"清原香港有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649528","names":[{"lang":"en","v":"EFFICOM TECHNOLOGY LIMITED"}],"company_since":"1998-07-10","company_dissolved":"2001-08-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649483","names":[{"lang":"en","v":"ELEGANT VANTAGE LIMITED (d2000-10-27)"},{"lang":"hk","v":"勝潤有限公司"}],"company_since":"1998-07-10","company_dissolved":"2000-10-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649287","names":[{"lang":"en","v":"ELEKTRO LIMITED"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649318","names":[{"lang":"en","v":"EMPEROR INVESTMENT SERVICES LIMITED"},{"lang":"hk","v":"英皇投資服務有限公司"}],"company_since":"1998-07-10","company_dissolved":"2014-12-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649394","names":[{"lang":"en","v":"ETERNAL CROWN ENTERPRISES LIMITED"},{"lang":"hk","v":"永光企業有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649420","names":[{"lang":"en","v":"ETERNAL TRADING LIMITED (d2001-03-09)"},{"lang":"hk","v":"衡輝貿易有限公司"}],"company_since":"1998-07-10","company_dissolved":"2001-03-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649555","names":[{"lang":"en","v":"EURO-TREND HONG KONG LIMITED"},{"lang":"hk","v":"裕天香港有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649332","names":[{"lang":"en","v":"EVE FLORA (H.K.) CO., LIMITED"},{"lang":"hk","v":"伊科娜香港有限公司"}],"company_since":"1998-07-10","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649534","names":[{"lang":"en","v":"EVER OCEAN ENTERPRISES LIMITED"},{"lang":"hk","v":"恒海企業有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649419","names":[{"lang":"en","v":"EVERCHINA LOGISTIC COMPANY LIMITED"},{"lang":"hk","v":"永中物流有限公司"}],"company_since":"1998-07-10","company_dissolved":"2001-03-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649498","names":[{"lang":"en","v":"EVERTIME INDUSTRIAL LIMITED (d2007-03-02)"},{"lang":"hk","v":"榮泰實業有限公司"}],"company_since":"1998-07-10","company_dissolved":"2007-03-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649510","names":[{"lang":"en","v":"EXCEL LEGEND DEVELOPMENT LIMITED (d2000-09-22)"},{"lang":"hk","v":"裕峰發展有限公司"}],"company_since":"1998-07-10","company_dissolved":"2000-09-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649284","names":[{"lang":"en","v":"EXPERTWAY DEVELOPMENTS LIMITED"}],"company_since":"1998-07-10","company_dissolved":"2004-02-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649478","names":[{"lang":"en","v":"FAITHFUL YEAR LIMITED (d2003-02-21)"},{"lang":"hk","v":"敬年有限公司"}],"company_since":"1998-07-10","company_dissolved":"2003-02-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649327","names":[{"lang":"en","v":"FAITHLINK INTERNATIONAL LIMITED"},{"lang":"hk","v":"誠立國際有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649273","names":[{"lang":"en","v":"FAMOUS WORLD INDUSTRIAL LIMITED"},{"lang":"hk","v":"名華實業有限公司"}],"company_since":"1998-07-10","company_dissolved":"2018-06-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649516","names":[{"lang":"en","v":"FANG LEI TRADING LIMITED"},{"lang":"hk","v":"丰蕾貿易有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649314","names":[{"lang":"en","v":"FISHERTON HOLDINGS LIMITED"},{"lang":"hk","v":"中順水產集團有限公司"}],"company_since":"1998-07-10","company_dissolved":"2009-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649477","names":[{"lang":"en","v":"FITNESS GYM COMPANY LIMITED (THE)"},{"lang":"hk","v":"健體健身中心有限公司"}],"company_since":"1998-07-10","company_dissolved":"2008-02-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649467","names":[{"lang":"en","v":"FOOKSMART LIMITED"},{"lang":"hk","v":"豐億有限公司"}],"company_since":"1998-07-10","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649463","names":[{"lang":"en","v":"FU WING FURNITURE &amp; WOODEN PRODUCTS LIMITED"},{"lang":"hk","v":"富榮傢具木器製品有限公司"}],"company_since":"1998-07-10","company_dissolved":"2012-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649337","names":[{"lang":"en","v":"FU YUAN INTERNATIONAL ENGINEERING (HONG KONG) CO., LIMITED"},{"lang":"hk","v":"福元國際工程(香港)有限公司"}],"company_since":"1998-07-10","company_dissolved":"2006-01-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649336","names":[{"lang":"en","v":"FULL ELEGANT LIMITED (d2019-11-22)"},{"lang":"hk","v":"富厚有限公司"}],"company_since":"1998-07-10","company_dissolved":"2019-11-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649360","names":[{"lang":"en","v":"FULL FORTUNE JEWELRY AND GOLD LIMITED"},{"lang":"hk","v":"寶豐珠寶金行有限公司"}],"company_since":"1998-07-10","company_dissolved":"2014-05-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649378","names":[{"lang":"en","v":"FULL JOY CONSULTANCY LIMITED"},{"lang":"hk","v":"盈悅顧問有限公司"}],"company_since":"1998-07-10","company_dissolved":"2003-03-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649424","names":[{"lang":"en","v":"FUN &amp; RUN MARKETING SERVICE LIMITED"},{"lang":"hk","v":"方與圓文化事業有限公司"}],"company_since":"1998-07-10","company_dissolved":"2005-09-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649304","names":[{"lang":"en","v":"FUNG NEI HOUSE JAPANESE RESTAURANT COMPANY LIMITED"},{"lang":"hk","v":"蓬萊屋日本料理有限公司"}],"company_since":"1998-07-10","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649295","names":[{"lang":"en","v":"G B INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"嘉寶國際建材有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649435","names":[{"lang":"en","v":"GENA LIMITED (d2005-07-15)"},{"lang":"hk","v":"精亞有限公司"}],"company_since":"1998-07-10","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649497","names":[{"lang":"en","v":"GENTO LIMITED (d2017-12-15)"},{"lang":"hk","v":"堅豪有限公司"}],"company_since":"1998-07-10","company_dissolved":"2017-12-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649383","names":[{"lang":"en","v":"GLOBAL INFORMATION SYSTEM COMPANY LIMITED"},{"lang":"hk","v":"滙訊系統有限公司"}],"company_since":"1998-07-10","company_dissolved":"2004-04-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649299","names":[{"lang":"en","v":"GOLDEN GLORY WORLD COMPANY LIMITED"},{"lang":"hk","v":"金瑩國際股份有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649272","names":[{"lang":"en","v":"GOLDKEEN TRANSPORTATION (HK) COMPANY LIMITED"},{"lang":"hk","v":"金僑貨運(香港)有限公司"}],"company_since":"1998-07-10","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649421","names":[{"lang":"en","v":"GOLDSPARK TRADING LIMITED"},{"lang":"hk","v":"金輝行貿易有限公司"}],"company_since":"1998-07-10","company_dissolved":"2000-11-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649416","names":[{"lang":"en","v":"GOLDWOOD ASIA LIMITED"},{"lang":"hk","v":"浩威亞洲有限公司"}],"company_since":"1998-07-10","company_dissolved":"2016-12-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649537","names":[{"lang":"en","v":"DASHIN SECURITIES HOLDINGS (H.K.) LIMITED"},{"lang":"hk","v":"大信証券集團(香港)有限公司"}],"company_since":"1998-07-10","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649532","names":[{"lang":"en","v":"DE RODEO HUMAN RESOURCES LIMITED"},{"lang":"hk","v":"快加好人力資源有限公司"}],"company_since":"1998-07-10","company_dissolved":"2015-03-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649432","names":[{"lang":"en","v":"DENHALL LIMITED (d2003-11-21)"},{"lang":"hk","v":"添浩有限公司"}],"company_since":"1998-07-10","company_dissolved":"2003-11-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649396","names":[{"lang":"en","v":"CROWN TARGET CONSULTANTS LIMITED"},{"lang":"hk","v":"冠達顧問有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649391","names":[{"lang":"en","v":"DERWICK LIMITED (HK)"},{"lang":"hk","v":"德惠有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649417","names":[{"lang":"en","v":"DICKSON OVERSEAS LIMITED"},{"lang":"hk","v":"達生海外有限公司"}],"company_since":"1998-07-10","company_dissolved":"2009-08-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"649489","names":[{"lang":"en","v":"DISTRIBUTION SERVICES (SHENCAI) LIMITED"}],"company_since":"1998-07-10","company_dissolved":"2003-08-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649288","names":[{"lang":"en","v":"EAST KIYOHARA CO., LIMITED"},{"lang":"hk","v":"清原香港有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649528","names":[{"lang":"en","v":"EFFICOM TECHNOLOGY LIMITED"}],"company_since":"1998-07-10","company_dissolved":"2001-08-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649287","names":[{"lang":"en","v":"ELEKTRO LIMITED"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649318","names":[{"lang":"en","v":"EMPEROR INVESTMENT SERVICES LIMITED"},{"lang":"hk","v":"英皇投資服務有限公司"}],"company_since":"1998-07-10","company_dissolved":"2014-12-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649420","names":[{"lang":"en","v":"ETERNAL TRADING LIMITED (d2001-03-09)"},{"lang":"hk","v":"衡輝貿易有限公司"}],"company_since":"1998-07-10","company_dissolved":"2001-03-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649555","names":[{"lang":"en","v":"EURO-TREND HONG KONG LIMITED"},{"lang":"hk","v":"裕天香港有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649419","names":[{"lang":"en","v":"EVERCHINA LOGISTIC COMPANY LIMITED"},{"lang":"hk","v":"永中物流有限公司"}],"company_since":"1998-07-10","company_dissolved":"2001-03-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649498","names":[{"lang":"en","v":"EVERTIME INDUSTRIAL LIMITED (d2007-03-02)"},{"lang":"hk","v":"榮泰實業有限公司"}],"company_since":"1998-07-10","company_dissolved":"2007-03-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649327","names":[{"lang":"en","v":"FAITHLINK INTERNATIONAL LIMITED"},{"lang":"hk","v":"誠立國際有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649273","names":[{"lang":"en","v":"FAMOUS WORLD INDUSTRIAL LIMITED"},{"lang":"hk","v":"名華實業有限公司"}],"company_since":"1998-07-10","company_dissolved":"2018-06-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649516","names":[{"lang":"en","v":"FANG LEI TRADING LIMITED"},{"lang":"hk","v":"丰蕾貿易有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649477","names":[{"lang":"en","v":"FITNESS GYM COMPANY LIMITED (THE)"},{"lang":"hk","v":"健體健身中心有限公司"}],"company_since":"1998-07-10","company_dissolved":"2008-02-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649463","names":[{"lang":"en","v":"FU WING FURNITURE &amp; WOODEN PRODUCTS LIMITED"},{"lang":"hk","v":"富榮傢具木器製品有限公司"}],"company_since":"1998-07-10","company_dissolved":"2012-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649337","names":[{"lang":"en","v":"FU YUAN INTERNATIONAL ENGINEERING (HONG KONG) CO., LIMITED"},{"lang":"hk","v":"福元國際工程(香港)有限公司"}],"company_since":"1998-07-10","company_dissolved":"2006-01-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649336","names":[{"lang":"en","v":"FULL ELEGANT LIMITED (d2019-11-22)"},{"lang":"hk","v":"富厚有限公司"}],"company_since":"1998-07-10","company_dissolved":"2019-11-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649360","names":[{"lang":"en","v":"FULL FORTUNE JEWELRY AND GOLD LIMITED"},{"lang":"hk","v":"寶豐珠寶金行有限公司"}],"company_since":"1998-07-10","company_dissolved":"2014-05-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649378","names":[{"lang":"en","v":"FULL JOY CONSULTANCY LIMITED"},{"lang":"hk","v":"盈悅顧問有限公司"}],"company_since":"1998-07-10","company_dissolved":"2003-03-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649424","names":[{"lang":"en","v":"FUN &amp; RUN MARKETING SERVICE LIMITED"},{"lang":"hk","v":"方與圓文化事業有限公司"}],"company_since":"1998-07-10","company_dissolved":"2005-09-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649304","names":[{"lang":"en","v":"FUNG NEI HOUSE JAPANESE RESTAURANT COMPANY LIMITED"},{"lang":"hk","v":"蓬萊屋日本料理有限公司"}],"company_since":"1998-07-10","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649295","names":[{"lang":"en","v":"G B INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"嘉寶國際建材有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649435","names":[{"lang":"en","v":"GENA LIMITED (d2005-07-15)"},{"lang":"hk","v":"精亞有限公司"}],"company_since":"1998-07-10","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649497","names":[{"lang":"en","v":"GENTO LIMITED (d2017-12-15)"},{"lang":"hk","v":"堅豪有限公司"}],"company_since":"1998-07-10","company_dissolved":"2017-12-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649383","names":[{"lang":"en","v":"GLOBAL INFORMATION SYSTEM COMPANY LIMITED"},{"lang":"hk","v":"滙訊系統有限公司"}],"company_since":"1998-07-10","company_dissolved":"2004-04-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649299","names":[{"lang":"en","v":"GOLDEN GLORY WORLD COMPANY LIMITED"},{"lang":"hk","v":"金瑩國際股份有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649414","names":[{"lang":"en","v":"GOLDWOOD PACIFIC LIMITED (d2000-11-10)"},{"lang":"hk","v":"金輝太平洋有限公司"}],"company_since":"1998-07-10","company_dissolved":"2000-11-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649282","names":[{"lang":"en","v":"GREAT INTERNATIONAL LIMITED (d2002-08-16)"},{"lang":"hk","v":"偉宏國際有限公司"}],"company_since":"1998-07-10","company_dissolved":"2002-08-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649270","names":[{"lang":"en","v":"GREATBEST INTERNATIONAL LIMITED"},{"lang":"hk","v":"嘉培國際有限公司"}],"company_since":"1998-07-10","company_dissolved":"2008-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649439","names":[{"lang":"en","v":"GUANG SHAN METAL IMPORT &amp; EXPORT CO., LIMITED"},{"lang":"hk","v":"廣汕五金進出口有限公司"}],"company_since":"1998-07-10","company_dissolved":"2006-01-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649380","names":[{"lang":"en","v":"HAIBAO INTERNATIONAL TRADE (HONG KONG) LIMITED"},{"lang":"hk","v":"海寶國際貿易(香港)有限公司"}],"company_since":"1998-07-10","company_dissolved":"2017-03-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649482","names":[{"lang":"en","v":"HAMTECH LIMITED (d2000-11-10)"},{"lang":"hk","v":"恆國有限公司"}],"company_since":"1998-07-10","company_dissolved":"2000-11-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649384","names":[{"lang":"en","v":"HANWAY INTERNATIONAL DECORATION ENGINEERING (HONG KONG) LIMITED"},{"lang":"hk","v":"恒威國際裝飾工程(香港)有限公司"}],"company_since":"1998-07-10","company_dissolved":"2003-05-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649374","names":[{"lang":"en","v":"HAPPY PLAN INTERNATIONAL LIMITED"},{"lang":"hk","v":"康暉國際有限公司"}],"company_since":"1998-07-10","company_dissolved":"2002-02-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649527","names":[{"lang":"en","v":"HARMONY ELECTRONICS CORPORATION LIMITED"},{"lang":"hk","v":"友和電子股份有限公司"}],"company_since":"1998-07-10","company_dissolved":"2010-01-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649341","names":[{"lang":"en","v":"HENMAEK TRADING LIMITED"},{"lang":"hk","v":"亨邁洋行有限公司"}],"company_since":"1998-07-10","company_dissolved":"2002-09-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649362","names":[{"lang":"en","v":"HILL POWER LIMITED"},{"lang":"hk","v":"潤源有限公司"}],"company_since":"1998-07-10","company_dissolved":"2003-10-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649481","names":[{"lang":"en","v":"HILL VIEW LIMITED"},{"lang":"hk","v":"昇萬有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649298","names":[{"lang":"en","v":"HING LEE DEVELOPMENT LIMITED"},{"lang":"hk","v":"興利發展(亞洲)有限公司"}],"company_since":"1998-07-10","company_dissolved":"2005-08-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649406","names":[{"lang":"en","v":"HK HYDRAULIC POWER (CHINA) DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"香港水電(中國)發展有限公司"}],"company_since":"1998-07-10","company_dissolved":"2002-12-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649300","names":[{"lang":"en","v":"HOMELY PLACE COMPANY LIMITED"}],"company_since":"1998-07-10","company_dissolved":"2002-12-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649443","names":[{"lang":"en","v":"HONG KONG FU TA COMPANY LIMITED"},{"lang":"hk","v":"香港富達有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649446","names":[{"lang":"en","v":"HONG KONG HAI MING (INTERNATIONAL) INVESTMENT COMPANY LIMITED"},{"lang":"hk","v":"香港海明(國際)投資有限公司"}],"company_since":"1998-07-10","company_dissolved":"2002-07-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"649409","names":[{"lang":"en","v":"HONG KONG HUA XIA INTERNATIONAL GROUP CO., LIMITED"},{"lang":"hk","v":"香港華夏國際集團有限公司"}],"company_since":"1998-07-10","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"649453","names":[{"lang":"en","v":"HONG KONG MODEL HELICOPTER ASSOCIATION LIMITED"},{"lang":"hk","v":"香港模型直昇機會有限公司"}],"company_since":"1998-07-10","company_dissolved":"2010-03-12","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"649305","names":[{"lang":"en","v":"HONG KONG SHENGHAO GROUP LIMITED"},{"lang":"hk","v":"香港升豪集團有限公司"}],"company_since":"1998-07-10","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649394","names":[{"lang":"en","v":"ETERNAL CROWN ENTERPRISES LIMITED"},{"lang":"hk","v":"永光企業有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"649291","names":[{"lang":"en","v":"HONG KONG WIRELESS DIGITAL CENTER COMMUNICATION TECHNOLOGY LIMITED"},{"lang":"hk","v":"香港威迪森通信技術有限公司"}],"company_since":"1998-07-10","company_dissolved":"2007-11-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649332","names":[{"lang":"en","v":"EVE FLORA (H.K.) CO., LIMITED"},{"lang":"hk","v":"伊科娜香港有限公司"}],"company_since":"1998-07-10","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649293","names":[{"lang":"en","v":"HOP SHING (FAR EAST) LIMITED"},{"lang":"hk","v":"合成工程(遠東)有限公司"}],"company_since":"1998-07-10","company_dissolved":"2011-10-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649534","names":[{"lang":"en","v":"EVER OCEAN ENTERPRISES LIMITED"},{"lang":"hk","v":"恒海企業有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649284","names":[{"lang":"en","v":"EXPERTWAY DEVELOPMENTS LIMITED"}],"company_since":"1998-07-10","company_dissolved":"2004-02-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649401","names":[{"lang":"en","v":"HUANG WEI TRADING LIMITED"},{"lang":"hk","v":"皇威貿易有限公司"}],"company_since":"1998-07-10","company_dissolved":"2013-01-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649510","names":[{"lang":"en","v":"EXCEL LEGEND DEVELOPMENT LIMITED (d2000-09-22)"},{"lang":"hk","v":"裕峰發展有限公司"}],"company_since":"1998-07-10","company_dissolved":"2000-09-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"649434","names":[{"lang":"en","v":"JONES RICH LIMITED"},{"lang":"hk","v":"仲裕有限公司"}],"company_since":"1998-07-10","company_dissolved":"2006-01-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649349","names":[{"lang":"en","v":"HUA QI GROUP (H.K.) LIMITED"},{"lang":"hk","v":"華起集團(香港)有限公司"}],"company_since":"1998-07-10","company_dissolved":"2019-03-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649410","names":[{"lang":"en","v":"JUBILEE OVERSEAS LIMITED"}],"company_since":"1998-07-10","company_dissolved":"1999-08-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649359","names":[{"lang":"en","v":"K. K. H. TRADING LIMITED"},{"lang":"hk","v":"嘉嘉灝貿易有限公司"}],"company_since":"1998-07-10","company_dissolved":"2004-04-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649472","names":[{"lang":"en","v":"KAI YIP ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"基業機電工程有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649314","names":[{"lang":"en","v":"FISHERTON HOLDINGS LIMITED"},{"lang":"hk","v":"中順水產集團有限公司"}],"company_since":"1998-07-10","company_dissolved":"2009-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649430","names":[{"lang":"en","v":"KAPO WATCH MANUFACTURING LIMITED"},{"lang":"hk","v":"嘉寶錶業有限公司"}],"company_since":"1998-07-10","company_dissolved":"2014-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649541","names":[{"lang":"en","v":"KASER INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"加兆國際集團有限公司"}],"company_since":"1998-07-10","company_dissolved":"1999-05-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649272","names":[{"lang":"en","v":"GOLDKEEN TRANSPORTATION (HK) COMPANY LIMITED"},{"lang":"hk","v":"金僑貨運(香港)有限公司"}],"company_since":"1998-07-10","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649277","names":[{"lang":"en","v":"KELMAX INVESTMENT LIMITED"},{"lang":"hk","v":"嘉美投資有限公司"}],"company_since":"1998-07-10","company_dissolved":"2001-11-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649474","names":[{"lang":"en","v":"KINGS DRAGON LIMITED"},{"lang":"hk","v":"景麟有限公司"}],"company_since":"1998-07-10","company_dissolved":"2009-02-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649388","names":[{"lang":"en","v":"KING FAVOUR LIMITED (d2017-12-08)"},{"lang":"hk","v":"景昌有限公司"}],"company_since":"1998-07-10","company_dissolved":"2017-12-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649557","names":[{"lang":"en","v":"KPS CONSULTANTS (HK) LIMITED"}],"company_since":"1998-07-10","company_dissolved":"2000-11-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649407","names":[{"lang":"en","v":"KUEN KEE CORRUGATED PAPER CO. LIMITED"},{"lang":"hk","v":"權記瓦通紙盒有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649548","names":[{"lang":"en","v":"LAI SING INVESTMENT LIMITED"},{"lang":"hk","v":"黎昇置業有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649488","names":[{"lang":"en","v":"LANDTIME LIMITED (HK)"},{"lang":"hk","v":"時榮有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649418","names":[{"lang":"en","v":"GOLDWOOD HONG KONG LIMITED"},{"lang":"hk","v":"金威行香港有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"649491","names":[{"lang":"en","v":"LANDTOP HOLDINGS LIMITED"},{"lang":"hk","v":"利億集團有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649416","names":[{"lang":"en","v":"GOLDWOOD ASIA LIMITED"},{"lang":"hk","v":"浩威亞洲有限公司"}],"company_since":"1998-07-10","company_dissolved":"2016-12-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"649493","names":[{"lang":"en","v":"LANDWELL HOLDINGS LIMITED (d2006-01-27)"},{"lang":"hk","v":"利和集團有限公司"}],"company_since":"1998-07-10","company_dissolved":"2006-01-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649269","names":[{"lang":"en","v":"LEADER EXPRESS (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"速利航速遞(香港)有限公司"}],"company_since":"1998-07-10","company_dissolved":"2008-07-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649286","names":[{"lang":"en","v":"LENWA INTERNATIONAL LIMITED"}],"company_since":"1998-07-10","company_dissolved":"2009-08-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649437","names":[{"lang":"en","v":"GRADEN DEVELOPMENT LIMITED"},{"lang":"hk","v":"嘉中發展有限公司"}],"company_since":"1998-07-10","company_dissolved":"2000-08-25","company_type_txt":"Private, ltd by shares"},
{"tax_id":"649382","names":[{"lang":"en","v":"LHI TECHNOLOGY (HK) COMPANY LIMITED"}],"company_since":"1998-07-10","company_dissolved":"2009-06-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649495","names":[{"lang":"en","v":"LICO TECHNOLOGIES LIMITED"},{"lang":"hk","v":"利豪科技有限公司"}],"company_since":"1998-07-10","company_dissolved":"2010-06-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649387","names":[{"lang":"en","v":"LEADSON LIMITED"},{"lang":"hk","v":"立順有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649375","names":[{"lang":"en","v":"GREAT FORCE TRADING LIMITED (d2005-07-15)"},{"lang":"hk","v":"建力貿易有限公司"}],"company_since":"1998-07-10","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"649274","names":[{"lang":"en","v":"LT FURNITURE &amp; DECORATION MATERIAL COMPANY LIMITED"},{"lang":"hk","v":"龍騰傢俬裝飾材料有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649393","names":[{"lang":"en","v":"MARVEL STAR DEVELOPMENT LIMITED"},{"lang":"hk","v":"鉅星發展有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649309","names":[{"lang":"en","v":"MEI KEI (H.K.) LIMITED"},{"lang":"hk","v":"美基(香港)有限公司"}],"company_since":"1998-07-10","company_dissolved":"2007-04-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649473","names":[{"lang":"en","v":"GREAT HARBOUR LIMITED (d2002-10-04)"},{"lang":"hk","v":"港大有限公司"}],"company_since":"1998-07-10","company_dissolved":"2002-10-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"649357","names":[{"lang":"en","v":"METAL WALL &amp; CONTRACTING COMPANY LIMITED"},{"lang":"hk","v":"建材企業(香港)有限公司"}],"company_since":"1998-07-10","company_dissolved":"2007-05-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649524","names":[{"lang":"en","v":"MASTER UNIQUE LIMITED (d2006-11-24)"},{"lang":"hk","v":"港億有限公司"}],"company_since":"1998-07-10","company_dissolved":"2006-11-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"649523","names":[{"lang":"en","v":"MONEY LUCK LIMITED"},{"lang":"hk","v":"冠立有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"649454","names":[{"lang":"en","v":"MV DESTINATION MANAGEMENT LIMITED"},{"lang":"hk","v":"集思顧問有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649496","names":[{"lang":"en","v":"NICEVIEW DEVELOPMENT LIMITED"},{"lang":"hk","v":"利景發展有限公司"}],"company_since":"1998-07-10","company_dissolved":"2010-10-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649531","names":[{"lang":"en","v":"NETIC COMPANY LIMITED"},{"lang":"hk","v":"絡泰集成有限公司"}],"company_since":"1998-07-10","company_dissolved":"2002-11-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649373","names":[{"lang":"en","v":"OCEANUS ENGINEERING INC. INTERNATIONAL LIMITED"}],"company_since":"1998-07-10","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649556","names":[{"lang":"en","v":"ORIENT FINANCE LIMITED (d2004-01-09)"}],"company_since":"1998-07-10","company_dissolved":"2004-01-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649329","names":[{"lang":"en","v":"OUTSTANDING WORLD LIMITED"},{"lang":"hk","v":"立眾有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649442","names":[{"lang":"en","v":"P&amp;Ls Steel Structures Applied Technology Co., Limited"},{"lang":"hk","v":"百安力鋼結構應用科技有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649500","names":[{"lang":"en","v":"PACIFIC ELEGANT LIMITED"},{"lang":"hk","v":"順恩有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649402","names":[{"lang":"en","v":"HONG KONG COSMOS INTERNATIONAL FASHION LIMITED"},{"lang":"hk","v":"香港歌仕樂國際服飾有限公司"}],"company_since":"1998-07-10","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"649501","names":[{"lang":"en","v":"PACIFIC ON INDUSTRIAL LIMITED"},{"lang":"hk","v":"順安實業有限公司"}],"company_since":"1998-07-10","company_dissolved":"2001-01-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649485","names":[{"lang":"en","v":"PACIFIC POWER LIMITED (d2003-01-30)"},{"lang":"hk","v":"順權有限公司"}],"company_since":"1998-07-10","company_dissolved":"2003-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"649403","names":[{"lang":"en","v":"HONG KONG LUO FU LUO LUN FASHION LIMITED"},{"lang":"hk","v":"香港羅夫羅倫服飾有限公司"}],"company_since":"1998-07-10","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"649301","names":[{"lang":"en","v":"PAUL TRADING COMPANY LIMITED"},{"lang":"hk","v":"廣輝洋行有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649308","names":[{"lang":"en","v":"PEARL POND LIMITED"},{"lang":"hk","v":"寶珠湖有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649339","names":[{"lang":"en","v":"HONG KONG TOP SILVER ENTERPRISE LIMITED"},{"lang":"hk","v":"香港特銀企業有限公司"}],"company_since":"1998-07-10","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649546","names":[{"lang":"en","v":"HONG KONG YANNAN ECONOMY &amp; TRADE CO., LIMITED"},{"lang":"hk","v":"香港延南經濟貿易有限公司"}],"company_since":"1998-07-10","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"649395","names":[{"lang":"en","v":"POCON TRADING LIMITED"},{"lang":"hk","v":"寶光貿易有限公司"}],"company_since":"1998-07-10","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649354","names":[{"lang":"en","v":"POWER MASTER TECHNOLOGY LIMITED"},{"lang":"hk","v":"乃升科技有限公司"}],"company_since":"1998-07-10","company_dissolved":"2018-11-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649285","names":[{"lang":"en","v":"PRIMEMARK GROUP LIMITED"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649289","names":[{"lang":"en","v":"HUA MAO WORLD (H.K.) COMPANY, LIMITED"},{"lang":"hk","v":"華貿世界(香港)有限公司"}],"company_since":"1998-07-10","company_dissolved":"2002-09-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"649321","names":[{"lang":"en","v":"PROFIT WORLD INDUSTRIAL LIMITED"},{"lang":"hk","v":"利匯實業有限公司"}],"company_since":"1998-07-10","company_dissolved":"2004-06-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649400","names":[{"lang":"en","v":"PULSAR ASIA LIMITED (d2001-05-25)"}],"company_since":"1998-07-10","company_dissolved":"2001-05-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"649559","names":[{"lang":"en","v":"HOST FULL OFFICE FURNITURE LIMITED"},{"lang":"hk","v":"浩豐商用傢俬有限公司"}],"company_since":"1998-07-10","company_dissolved":"2006-01-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649471","names":[{"lang":"en","v":"IDEAL CUT LIMITED"}],"company_since":"1998-07-10","company_dissolved":"2002-06-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"649381","names":[{"lang":"en","v":"INSCORE HONG KONG COMPANY LIMITED"},{"lang":"hk","v":"碁泰香港有限公司"}],"company_since":"1998-07-10","company_dissolved":"2004-03-05","company_type_txt":"Private, ltd by shares"},
{"tax_id":"649436","names":[{"lang":"en","v":"RICH HEAD INVESTMENT LIMITED"},{"lang":"hk","v":"裕凱投資有限公司"}],"company_since":"1998-07-10","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649386","names":[{"lang":"en","v":"JBK LIMITED"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649465","names":[{"lang":"en","v":"RICH TONE LIMITED (d2003-12-05)"},{"lang":"hk","v":"輝通有限公司"}],"company_since":"1998-07-10","company_dissolved":"2003-12-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649450","names":[{"lang":"en","v":"RIGHT BILLION LIMITED"},{"lang":"hk","v":"億韋有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649326","names":[{"lang":"en","v":"RICH UNION TRADING LIMITED"},{"lang":"hk","v":"耀富貿易有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649330","names":[{"lang":"en","v":"ROYAL FAITH LIMITED"},{"lang":"hk","v":"暉榮有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649415","names":[{"lang":"en","v":"ROYALKING UNIVERSAL LIMITED"},{"lang":"hk","v":"華興環球有限公司"}],"company_since":"1998-07-10","company_dissolved":"2017-03-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649539","names":[{"lang":"en","v":"SCC MARKETERS INTERNATIONAL LIMITED"},{"lang":"hk","v":"瑞芝祥有限公司"}],"company_since":"1998-07-10","company_dissolved":"2007-04-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649323","names":[{"lang":"en","v":"ROYAL HARBOUR LIMITED"},{"lang":"hk","v":"晉港有限公司"}],"company_since":"1998-07-10","company_dissolved":"2009-06-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649460","names":[{"lang":"en","v":"KENTWOOD HOLDINGS LIMITED (d2002-07-12)"},{"lang":"hk","v":"建浩集團有限公司"}],"company_since":"1998-07-10","company_dissolved":"2002-07-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"649499","names":[{"lang":"en","v":"SHANGHAI XINXIN SPORTS DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"上海新新體育發展有限公司"}],"company_since":"1998-07-10","company_dissolved":"2014-09-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649509","names":[{"lang":"en","v":"SHARP GAIN LIMITED (d2003-03-21)"},{"lang":"hk","v":"順智有限公司"}],"company_since":"1998-07-10","company_dissolved":"2003-03-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649520","names":[{"lang":"en","v":"ROYAL CENTURY LIMITED (d2010-01-08)"},{"lang":"hk","v":"源嘉有限公司"}],"company_since":"1998-07-10","company_dissolved":"2010-01-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649307","names":[{"lang":"en","v":"SHINE LEGEND LIMITED (d2004-03-05)"},{"lang":"hk","v":"豪冠有限公司"}],"company_since":"1998-07-10","company_dissolved":"2004-03-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649280","names":[{"lang":"en","v":"SINO VICTORY ENTERPRISES LIMITED"},{"lang":"hk","v":"華凱企業有限公司"}],"company_since":"1998-07-10","company_dissolved":"2010-04-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649344","names":[{"lang":"en","v":"SIU WAH STEEL WORK COMPANY LIMITED"},{"lang":"hk","v":"兆華鋼鐵工程有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649325","names":[{"lang":"en","v":"Skyline Worldwide Limited (d2012-08-03)"},{"lang":"hk","v":"錦圖環球有限公司"}],"company_since":"1998-07-10","company_dissolved":"2012-08-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649369","names":[{"lang":"en","v":"SMART PEOPLE LIMITED (d2001-01-12)"},{"lang":"hk","v":"佳將有限公司"}],"company_since":"1998-07-10","company_dissolved":"2001-01-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649505","names":[{"lang":"en","v":"SK DESIGN AND CONSTRUCTION LIMITED"},{"lang":"hk","v":"師建室內設計工程有限公司"}],"company_since":"1998-07-10","company_dissolved":"2006-11-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649392","names":[{"lang":"en","v":"STANDARD SUPREME INVESTMENT LIMITED"},{"lang":"hk","v":"德尊投資有限公司"}],"company_since":"1998-07-10","company_dissolved":"2006-12-29","company_type_txt":"Private, ltd by shares"},
{"tax_id":"649281","names":[{"lang":"en","v":"STARCON INTERNATIONAL LIMITED (d2005-06-03)"},{"lang":"hk","v":"星港國際有限公司"}],"company_since":"1998-07-10","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649283","names":[{"lang":"en","v":"STEEL POINT INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"炘立國際有限公司"}],"company_since":"1998-07-10","company_dissolved":"2006-01-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649324","names":[{"lang":"en","v":"Success Securities Limited"},{"lang":"hk","v":"實德證券有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649507","names":[{"lang":"en","v":"SUCCESS VIEW (HONG KONG) LIMITED (d2006-11-24)"},{"lang":"hk","v":"滙通(香港)有限公司"}],"company_since":"1998-07-10","company_dissolved":"2006-11-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"649333","names":[{"lang":"en","v":"SUMMER PLACE LIMITED"},{"lang":"hk","v":"森雅有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649431","names":[{"lang":"en","v":"SANESON LIMITED"},{"lang":"hk","v":"生信有限公司"}],"company_since":"1998-07-10","company_dissolved":"2007-02-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649447","names":[{"lang":"en","v":"RICH TOP PROPERTIES CONSULTANTS LIMITED"},{"lang":"hk","v":"置峰物業顧問有限公司"}],"company_since":"1998-07-10","company_dissolved":"2001-11-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649297","names":[{"lang":"en","v":"TNL LIMITED (d2003-02-21)"}],"company_since":"1998-07-10","company_dissolved":"2003-02-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649538","names":[{"lang":"en","v":"RIGHT BILLION INDUSTRIES LIMITED"},{"lang":"hk","v":"億韋實業有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"649506","names":[{"lang":"en","v":"TIPTOP LIMITED"},{"lang":"hk","v":"旭創有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649553","names":[{"lang":"en","v":"TOMORROW ENTERPRISE LIMITED (d2005-07-15)"},{"lang":"hk","v":"耀明企業有限公司"}],"company_since":"1998-07-10","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649494","names":[{"lang":"en","v":"TOP HARVEST INTERNATIONAL LIMITED (d2006-11-24)"},{"lang":"hk","v":"立恒國際有限公司"}],"company_since":"1998-07-10","company_dissolved":"2006-11-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649361","names":[{"lang":"en","v":"TOP-TAL LIMITED"},{"lang":"hk","v":"先卓有限公司"}],"company_since":"1998-07-10","company_dissolved":"2016-09-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"649320","names":[{"lang":"en","v":"TRADING TARGET LIMITED"},{"lang":"hk","v":"達德有限公司"}],"company_since":"1998-07-10","company_dissolved":"2006-11-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649452","names":[{"lang":"en","v":"TZE LOI COMPUTER SYSTEMS LIMITED"},{"lang":"hk","v":"子來電腦系統有限公司"}],"company_since":"1998-07-10","company_dissolved":"2003-01-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"649515","names":[{"lang":"en","v":"ROYAL HILTON LIMITED"},{"lang":"hk","v":"富怡有限公司"}],"company_since":"1998-07-10","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"649519","names":[{"lang":"en","v":"ROYAL CREATION LIMITED (d2004-04-16)"},{"lang":"hk","v":"建源有限公司"}],"company_since":"1998-07-10","company_dissolved":"2004-04-16","company_type_txt":"Private, ltd by shares"},
{"tax_id":"649551","names":[{"lang":"en","v":"UNION FOCUS INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"聯暉國際投資有限公司"}],"company_since":"1998-07-10","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649487","names":[{"lang":"en","v":"UNISON LIMITED (d2005-12-02)"}],"company_since":"1998-07-10","company_dissolved":"2005-12-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649358","names":[{"lang":"en","v":"VANCO TECHNOLOGY LIMITED"},{"lang":"hk","v":"高勝科技有限公司"}],"company_since":"1998-07-10","company_dissolved":"2015-06-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"649334","names":[{"lang":"en","v":"UNIQUE WIN LIMITED"},{"lang":"hk","v":"百裕有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"649426","names":[{"lang":"en","v":"VANWAY PHARMACEUTICAL HOLDINGS LIMITED"},{"lang":"hk","v":"宏威製藥集團有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649511","names":[{"lang":"en","v":"ROYAL VANTAGE LIMITED"},{"lang":"hk","v":"富建有限公司"}],"company_since":"1998-07-10","company_dissolved":"2010-03-26","company_type_txt":"Private, ltd by shares"},
{"tax_id":"649513","names":[{"lang":"en","v":"ROYAL RICH LIMITED (d2002-07-26)"},{"lang":"hk","v":"富萊有限公司"}],"company_since":"1998-07-10","company_dissolved":"2002-07-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649397","names":[{"lang":"en","v":"VASSAR CHINESE HERBAL BIOPHARMACEUTICAL CO. LIMITED"},{"lang":"hk","v":"華夏漢方生物藥業有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"649550","names":[{"lang":"en","v":"VECTOR ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"威捷建築工程有限公司"}],"company_since":"1998-07-10","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649441","names":[{"lang":"en","v":"VICTORY CONCEPT ENGINEERING LIMITED"},{"lang":"hk","v":"偉港工程有限公司"}],"company_since":"1998-07-10","company_dissolved":"2007-12-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649512","names":[{"lang":"en","v":"ROYAL SMART LIMITED"},{"lang":"hk","v":"明運有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"649399","names":[{"lang":"en","v":"WAI MAN LABEL MANUFACTURING COMPANY LIMITED"},{"lang":"hk","v":"惠文商標製品有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649353","names":[{"lang":"en","v":"WAI TONG INTERNATIONAL TRANSPORT LIMITED"},{"lang":"hk","v":"偉通國際貨運有限公司"}],"company_since":"1998-07-10","company_dissolved":"2014-11-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649370","names":[{"lang":"en","v":"WELL TALENT CORPORATION LIMITED (d2002-05-10)"},{"lang":"hk","v":"才威有限公司"}],"company_since":"1998-07-10","company_dissolved":"2002-05-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649347","names":[{"lang":"en","v":"VANGUARD LOGISTICS SERVICES (HONG KONG) LIMITED"},{"lang":"hk","v":"維佳物流有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649278","names":[{"lang":"en","v":"WELL TRUMP DEVELOPMENT LIMITED"},{"lang":"hk","v":"滙駿發展有限公司"}],"company_since":"1998-07-10","company_dissolved":"2007-08-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"649412","names":[{"lang":"en","v":"Wellstone Credit Finance Limited"},{"lang":"hk","v":"利高達信貸財務有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649376","names":[{"lang":"en","v":"WESTIN INDUSTRIAL LIMITED"},{"lang":"hk","v":"惠生實業有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649451","names":[{"lang":"en","v":"WISE EVER DEVELOPMENT LIMITED"},{"lang":"hk","v":"恒慧發展有限公司"}],"company_since":"1998-07-10","company_dissolved":"2003-02-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649429","names":[{"lang":"en","v":"SINO FAME SHOES COMPANY LIMITED"},{"lang":"hk","v":"信懋行(鞋業)有限公司"}],"company_since":"1998-07-10","company_dissolved":"2003-04-25","company_type_txt":"Private, ltd by shares"},
{"tax_id":"649322","names":[{"lang":"en","v":"WISEPOOL CORPORATION LIMITED"},{"lang":"hk","v":"澤威有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649479","names":[{"lang":"en","v":"WINNING TREASURE INTERNATIONAL LIMITED"},{"lang":"hk","v":"凱富國際有限公司"}],"company_since":"1998-07-10","company_dissolved":"2002-11-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649405","names":[{"lang":"en","v":"WONJUNG ELECTRONICS (HK) LIMITED"},{"lang":"hk","v":"元井電子(香港)有限公司"}],"company_since":"1998-07-10","company_dissolved":"2000-12-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649275","names":[{"lang":"en","v":"WORLD ALPHA LIMITED"},{"lang":"hk","v":"世亞有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"649445","names":[{"lang":"en","v":"WORLD GENERAL HOLDINGS CORPORATION LIMITED"},{"lang":"hk","v":"世通控股股份有限公司"}],"company_since":"1998-07-10","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649411","names":[{"lang":"en","v":"SIX FOREST BIO-SCIENCE INSTITUTE LIMITED"},{"lang":"hk","v":"六林生物科學研究所有限公司"}],"company_since":"1998-07-10","company_dissolved":"2009-05-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"649552","names":[{"lang":"en","v":"WUI XING CIVIL ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"滙成土木工程有限公司"}],"company_since":"1998-07-10","company_dissolved":"2007-06-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649312","names":[{"lang":"en","v":"YAT HANG ENGINEERING COMPANY LIMITED (d2008-09-26)"},{"lang":"hk","v":"日亨工程有限公司"}],"company_since":"1998-07-10","company_dissolved":"2008-09-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649490","names":[{"lang":"en","v":"SMART ON DEVELOPMENT LIMITED (d2005-07-15)"},{"lang":"hk","v":"和安發展有限公司"}],"company_since":"1998-07-10","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"649311","names":[{"lang":"en","v":"YEUNG TAT COMPANY LIMITED"},{"lang":"hk","v":"陽達貿易有限公司"}],"company_since":"1998-07-10","company_dissolved":"2018-04-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649503","names":[{"lang":"en","v":"YIELD CHANCE LIMITED (d2007-02-02)"},{"lang":"hk","v":"金邁有限公司"}],"company_since":"1998-07-10","company_dissolved":"2007-02-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649540","names":[{"lang":"en","v":"SMART WAVE DEVELOPMENT LIMITED (d2006-11-24)"},{"lang":"hk","v":"威濤發展有限公司"}],"company_since":"1998-07-10","company_dissolved":"2006-11-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649338","names":[{"lang":"en","v":"YING FONG INTERNATIONAL INVESTMENT &amp; DEVELOPMENT LIMITED"},{"lang":"hk","v":"英方國際投資發展有限公司"}],"company_since":"1998-07-10","company_dissolved":"2013-02-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649404","names":[{"lang":"en","v":"SOUTH EAST ASIA LOGISTICS LIMITED"}],"company_since":"1998-07-10","company_dissolved":"2006-01-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649530","names":[{"lang":"en","v":"SPEC CHEMICAL INDUSTRY (H.K.) COMPANY LIMITED"},{"lang":"hk","v":"深圳石化化工(香港)有限公司"}],"company_since":"1998-07-10","company_dissolved":"2000-10-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"649276","names":[{"lang":"en","v":"YIU SING ENGINEERING (HK) COMPANY LIMITED"},{"lang":"hk","v":"耀成工程(香港)有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"649475","names":[{"lang":"en","v":"SUPER GUARD LIMITED"},{"lang":"hk","v":"寶衛有限公司"}],"company_since":"1998-07-10","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649385","names":[{"lang":"en","v":"SUPERTEX (HONG KONG) LIMITED"},{"lang":"hk","v":"香港凱托有限公司"}],"company_since":"1998-07-10","company_dissolved":"2000-12-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649486","names":[{"lang":"en","v":"SYNERGY BIOTECHNOLOGY ENTERPRISES LIMITED"},{"lang":"hk","v":"一元生物科技企業有限公司"}],"company_since":"1998-07-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649350","names":[{"lang":"en","v":"TIMES ENTERTAINMENT DISTRIBUTION LIMITED"},{"lang":"hk","v":"時代娛樂發行有限公司"}],"company_since":"1998-07-10","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649433","names":[{"lang":"en","v":"SUN KONG FERRY SERVICES COMPANY LIMITED"},{"lang":"hk","v":"新港小輪有限公司"}],"company_since":"1998-07-10","company_dissolved":"2000-11-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649522","names":[{"lang":"en","v":"PERFECT VANTAGE LIMITED (d2004-04-14)"},{"lang":"hk","v":"好時有限公司"}],"company_since":"1998-07-10","company_dissolved":"2004-04-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"649335","names":[{"lang":"en","v":"TECK WO LIMITED"},{"lang":"hk","v":"華億有限公司"}],"company_since":"1998-07-10","company_dissolved":"2001-10-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649554","names":[{"lang":"en","v":"WAFER ADVANCED TECHNOLOGIES LIMITED"},{"lang":"hk","v":"威發先進科技有限公司"}],"company_since":"1998-07-10","company_dissolved":"2010-02-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"649464","names":[{"lang":"en","v":"WINKON CHEMICALS LIMITED"},{"lang":"hk","v":"望江化工有限公司"}],"company_since":"1998-07-10","company_dissolved":"2019-04-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"649448","names":[{"lang":"en","v":"WISE EVER INVESTMENT LIMITED"},{"lang":"hk","v":"慧恒投資有限公司"}],"company_since":"1998-07-10","company_dissolved":"2011-07-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"649427","names":[{"lang":"en","v":"YIN KEE RESTAURANT LIMITED"},{"lang":"hk","v":"燕記茶餐廳有限公司"}],"company_since":"1998-07-10","company_dissolved":"2001-07-27","company_type_txt":"Private, ltd by shares"},
