{"tax_id":"814557","names":[{"lang":"en","v":"CHADDIL COMPANY LIMITED"},{"lang":"hk","v":"沙仕年健康產品有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814612","names":[{"lang":"en","v":"CHAINPOST LIMITED"},{"lang":"hk","v":"暢寶有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814720","names":[{"lang":"en","v":"CHAMP'S WAY INDUSTRIAL (HK) LIMITED"},{"lang":"hk","v":"澤滙實業(香港)有限公司"}],"company_since":"2002-09-18","company_dissolved":"2011-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814680","names":[{"lang":"en","v":"CHARTER GROUP INT'L LIMITED"},{"lang":"hk","v":"卓軒國際集團有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814442","names":[{"lang":"en","v":"CHENGTA FOOTWEAR (HK) CO., LIMITED"},{"lang":"hk","v":"誠踏鞋服(香港)有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814569","names":[{"lang":"en","v":"CHINA ROYAL INVESTMENT LIMITED (d2005-05-13)"},{"lang":"hk","v":"中興投資有限公司"}],"company_since":"2002-09-18","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814392","names":[{"lang":"en","v":"CHINA TRAFFIC INTERNATIONAL ENGINEERING (HK) CORPORATION LIMITED"},{"lang":"hk","v":"中通國際工程(香港)有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814484","names":[{"lang":"en","v":"CHINA TRAVEL WESTERN INVESTMENT (HOLDINGS) HK LIMITED"},{"lang":"hk","v":"香港中旅西部投資(集團)有限公司"}],"company_since":"2002-09-18","company_dissolved":"2009-02-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814533","names":[{"lang":"en","v":"CHINAMED PRODUCTS (CHINA) LIMITED"},{"lang":"hk","v":"中療醫療製品廠(中國)有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814521","names":[{"lang":"en","v":"CLARON HOLDINGS LIMITED"},{"lang":"hk","v":"嘉康集團有限公司"}],"company_since":"2002-09-18","company_dissolved":"2005-01-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814471","names":[{"lang":"en","v":"COFFEE WONG TRAINING &amp; CONSULTANCY LIMITED"},{"lang":"hk","v":"咖啡黃培訓及顧問有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-05-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814556","names":[{"lang":"en","v":"CONSOL PETROCHEMICAL COMPANY LIMITED"}],"company_since":"2002-09-18","company_dissolved":"2015-11-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814535","names":[{"lang":"en","v":"CONTROL SCIENTIFIC INSTRUMENT HK CO., LIMITED"},{"lang":"hk","v":"康創科儀香港有限公司"}],"company_since":"2002-09-18","company_dissolved":"2018-02-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"814662","names":[{"lang":"en","v":"COVA APPAREL LIMITED"},{"lang":"hk","v":"錦潤製衣有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814499","names":[{"lang":"en","v":"D-MATE LIMITED"},{"lang":"hk","v":"迪美集團有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814639","names":[{"lang":"en","v":"DALIAN JIAN FENG ENGINEERING MACHINE CO., LIMITED"},{"lang":"hk","v":"大連堅峰工程機械有限公司"}],"company_since":"2002-09-18","company_dissolved":"2006-12-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814717","names":[{"lang":"en","v":"DANSON MARINE CO., LIMITED (d2008-02-01)"},{"lang":"hk","v":"國航船務有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814629","names":[{"lang":"en","v":"DAYA SANI-WARE CO., LIMITED"},{"lang":"hk","v":"香港佳誠貿易有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"814542","names":[{"lang":"en","v":"DAYDREAMER CARTOON ACADEMY LIMITED"},{"lang":"hk","v":"夢卡通學院有限公司"}],"company_since":"2002-09-18","company_dissolved":"2011-05-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"814620","names":[{"lang":"en","v":"DIGITAL WORLDWIDE COMMUNICATIONS LIMITED"},{"lang":"hk","v":"國際通訊有限公司"}],"company_since":"2002-09-18","company_dissolved":"2010-05-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814518","names":[{"lang":"en","v":"CHINA GLOBAL PUBLIC RELATIONS (HK) LIMITED"},{"lang":"hk","v":"中國環球公共關係(香港)有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814433","names":[{"lang":"en","v":"CHINA QIHUANG MEDICINE HOLDING SHARES LIMITED"},{"lang":"hk","v":"中國岐黃中醫中藥集團股份有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"814509","names":[{"lang":"en","v":"DR. ANTHONY NG &amp; CO., LIMITED"},{"lang":"hk","v":"吳允中醫生醫務所有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814674","names":[{"lang":"en","v":"DRAGON ERA INTERNATIONAL LIMITED"},{"lang":"hk","v":"久龍國際有限公司"}],"company_since":"2002-09-18","company_dissolved":"2004-09-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814623","names":[{"lang":"en","v":"DRAGON LOYAL INVESTMENT LIMITED"},{"lang":"hk","v":"龍盈投資有限公司"}],"company_since":"2002-09-18","company_dissolved":"2012-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814695","names":[{"lang":"en","v":"EARLY STAR LIMITED"},{"lang":"hk","v":"晨星有限公司"}],"company_since":"2002-09-18","company_dissolved":"2010-02-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"814616","names":[{"lang":"en","v":"EASTCHINA GATEWAY INTERNATIONAL LIMITED"},{"lang":"hk","v":"華東國際有限公司"}],"company_since":"2002-09-18","company_dissolved":"2013-02-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814672","names":[{"lang":"en","v":"CHINA GOODWILL INTERNATIONAL HOLDINGS CO., LIMITED"},{"lang":"hk","v":"中國好時國際旅游集團有限公司"}],"company_since":"2002-09-18","company_dissolved":"2017-11-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"814385","names":[{"lang":"en","v":"ECO-SERVE.COM LIMITED"},{"lang":"hk","v":"爾高-環保有限公司"}],"company_since":"2002-09-18","company_dissolved":"2016-04-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814673","names":[{"lang":"en","v":"CHINESE CREATIVE LIMITED"},{"lang":"hk","v":"中創有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-10-31","company_type_txt":"Private, ltd by shares"},
{"tax_id":"814430","names":[{"lang":"en","v":"EASTLOC ENGINEERING AND PRODUCTS CO., LIMITED"},{"lang":"hk","v":"銘泰實業(香港)有限公司"}],"company_since":"2002-09-18","company_dissolved":"2018-05-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"814491","names":[{"lang":"en","v":"EMILY HOLDINGS LIMITED (HK)"},{"lang":"hk","v":"安萬利集團有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814375","names":[{"lang":"en","v":"CHIVIN (CHINA) TRANSPORTATION LIMITED"},{"lang":"hk","v":"志榮(中國)貨運有限公司"}],"company_since":"2002-09-18","company_dissolved":"2011-05-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814519","names":[{"lang":"en","v":"EPU GLOBAL LIMITED"},{"lang":"hk","v":"怡富環球有限公司"}],"company_since":"2002-09-18","company_dissolved":"2004-05-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"814474","names":[{"lang":"en","v":"CONNEXASIA LIMITED"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814407","names":[{"lang":"en","v":"ETERNAL PROSPER TRADING LIMITED"},{"lang":"hk","v":"均恆貿易有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814448","names":[{"lang":"en","v":"CHUNG MAU PLASTIC MATERIAL COMPANY LIMITED"},{"lang":"hk","v":"松茂塑料有限公司"}],"company_since":"2002-09-18","company_dissolved":"2007-07-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"814386","names":[{"lang":"en","v":"CnC Marine (HK) Limited"}],"company_since":"2002-09-18","company_dissolved":"2016-06-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"814698","names":[{"lang":"en","v":"EVER BRILLIANT INTERNATIONAL INDUSTRIAL LIMITED"},{"lang":"hk","v":"逸輝國際實業有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814647","names":[{"lang":"en","v":"EVER DRAGON TECHNOLOGY LIMITED"},{"lang":"hk","v":"恒龍科技有限公司"}],"company_since":"2002-09-18","company_dissolved":"2004-07-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814573","names":[{"lang":"en","v":"EVER WINNING ENTERPRISES LIMITED"},{"lang":"hk","v":"永泰企業有限公司"}],"company_since":"2002-09-18","company_dissolved":"2011-05-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814665","names":[{"lang":"en","v":"EVERBRIGHT MANUFACTURING COMPANY LIMITED"},{"lang":"hk","v":"恒暉製品有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"814405","names":[{"lang":"en","v":"EVERCOM TRADING COMPANY LIMITED"},{"lang":"hk","v":"恒匯貿易發展有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"814693","names":[{"lang":"en","v":"EVERITE LIMITED"},{"lang":"hk","v":"衡益有限公司"}],"company_since":"2002-09-18","company_dissolved":"2017-05-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814384","names":[{"lang":"en","v":"EVOLVE INDUSTRIES (CHINA) LIMITED"},{"lang":"hk","v":"浩派產品開發有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814682","names":[{"lang":"en","v":"CYBER ADVANCE TECHNOLOGIES LIMITED"},{"lang":"hk","v":"新數碼科技有限公司"}],"company_since":"2002-09-18","company_dissolved":"2012-03-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814503","names":[{"lang":"en","v":"CYLL INTERNATIONAL TRADE CO., LIMITED"},{"lang":"hk","v":"西爾國際貿易有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-08-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814604","names":[{"lang":"en","v":"EXCEL POWER HOLDINGS LIMITED"},{"lang":"hk","v":"佳力集團有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814694","names":[{"lang":"en","v":"CHANCE ON LIMITED (d2004-02-27)"},{"lang":"hk","v":"祥安有限公司"}],"company_since":"2002-09-18","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"814463","names":[{"lang":"en","v":"EXTRA WEALTH LIMITED (d2010-04-16)"},{"lang":"hk","v":"萬利豐有限公司"}],"company_since":"2002-09-18","company_dissolved":"2010-04-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814516","names":[{"lang":"en","v":"FAMOUS PROFESSIONAL CAR CARE CENTRE LIMITED"},{"lang":"hk","v":"名車專業汽車護理中心有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814515","names":[{"lang":"en","v":"FLUENT ASSET LIMITED"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814703","names":[{"lang":"en","v":"FLY DRAGON TRANSPORTATION LIMITED (d2004-12-31)"},{"lang":"hk","v":"展龍運輸有限公司"}],"company_since":"2002-09-18","company_dissolved":"2004-12-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814558","names":[{"lang":"en","v":"CHINA EDUCATION DEV (H.K.) LIMITED"},{"lang":"hk","v":"中國教育發展(香港)有限公司"}],"company_since":"2002-09-18","company_dissolved":"2020-04-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"814576","names":[{"lang":"en","v":"FORD REGENT LIMITED"},{"lang":"hk","v":"恒高有限公司"}],"company_since":"2002-09-18","company_dissolved":"2009-02-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"814634","names":[{"lang":"en","v":"DRAGON FAME LIMITED (d2008-02-01)"},{"lang":"hk","v":"仁龍有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"814453","names":[{"lang":"en","v":"FREEDOM (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"福來登(香港)有限公司"}],"company_since":"2002-09-18","company_dissolved":"2006-08-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"814667","names":[{"lang":"en","v":"FRESHTREKS LIMITED"}],"company_since":"2002-09-18","company_dissolved":"2010-02-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"814562","names":[{"lang":"en","v":"FU FAI DECORATION MATERIAL CO LIMITED"},{"lang":"hk","v":"富暉汽車美化用品有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814486","names":[{"lang":"en","v":"FUK CHEUNG PROPERTIES DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"福祥物業發展有限公司"}],"company_since":"2002-09-18","company_dissolved":"2012-03-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"814524","names":[{"lang":"en","v":"ENTER CONCEPT LIMITED"},{"lang":"hk","v":"安泰興業有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"814583","names":[{"lang":"en","v":"GAIN FOREVER INVESTMENT LIMITED"},{"lang":"hk","v":"恒豐投資有限公司"}],"company_since":"2002-09-18","company_dissolved":"2004-05-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814582","names":[{"lang":"en","v":"GAIN FOREVER LIMITED"},{"lang":"hk","v":"永基有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814450","names":[{"lang":"en","v":"FRANCE OI YE MA CLOTHING INTERNATIONAL GROUP COMPANY LIMITED"},{"lang":"hk","v":"法國愛爾馬服飾國際集團有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814544","names":[{"lang":"en","v":"GAMMON E&amp;M LIMITED"},{"lang":"hk","v":"金門機電工程有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814422","names":[{"lang":"en","v":"GANGSIN INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"港鑫國際投資有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814605","names":[{"lang":"en","v":"GAO SHING FUNG LIMITED"},{"lang":"hk","v":"高成豐有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-03-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"814566","names":[{"lang":"en","v":"FOREVER CREATIVE INTERNATIONAL LIMITED (b2002-09-18)"},{"lang":"hk","v":"永昌國際有限公司"}],"company_since":"2002-09-18","company_dissolved":"2014-03-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"814472","names":[{"lang":"en","v":"GLOBAL DILIGENCE LIMITED"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814377","names":[{"lang":"en","v":"GLOBAL EMBROIDERY LIMITED"},{"lang":"hk","v":"環球刺綉有限公司"}],"company_since":"2002-09-18","company_dissolved":"2013-12-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814625","names":[{"lang":"en","v":"GLOBAL KINGDOM CORPORATION LIMITED"},{"lang":"hk","v":"嘉鈞有限公司"}],"company_since":"2002-09-18","company_dissolved":"2005-12-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814523","names":[{"lang":"en","v":"GOLDEN BUSINESS LIMITED"},{"lang":"hk","v":"金興業有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814534","names":[{"lang":"en","v":"GOLDEN SUN INDUSTRIAL INT'L CO., LIMITED"},{"lang":"hk","v":"金陽實業國際有限公司"}],"company_since":"2002-09-18","company_dissolved":"2011-05-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"814502","names":[{"lang":"en","v":"FRANCE BIG THREE ENTERPRISE LIMITED"},{"lang":"hk","v":"法國貝格斯瑞企業有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-02-01","company_type_txt":"Private, ltd by shares"},
{"tax_id":"814607","names":[{"lang":"en","v":"GOLDSWAY INTERNATIONAL LIMITED"},{"lang":"hk","v":"好時威國際有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814716","names":[{"lang":"en","v":"GOOD TIME METAL PRINTING FACTORY LIMITED"},{"lang":"hk","v":"喜時印鐵廠有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"814658","names":[{"lang":"en","v":"GOURMETS PARADISE LIMITED"},{"lang":"hk","v":"食家菜會館有限公司"}],"company_since":"2002-09-18","company_dissolved":"2011-05-06","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"814501","names":[{"lang":"en","v":"GREAT BENEFIT (FASHION) INDUSTRIAL LIMITED (d2008-02-01)"},{"lang":"hk","v":"增城(時裝)實業有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814455","names":[{"lang":"en","v":"GREAT EFFORT BUSINESS DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"鴻力實業發展有限公司"}],"company_since":"2002-09-18","company_dissolved":"2012-03-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814696","names":[{"lang":"en","v":"GREAT GALAXY LIMITED (d2005-05-13)"},{"lang":"hk","v":"博豐有限公司"}],"company_since":"2002-09-18","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"814456","names":[{"lang":"en","v":"FRANCE WILD DUCK (INT'L) DRESS LIMITED"},{"lang":"hk","v":"法國野鴨(國際)服飾有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-08-01","company_type_txt":"Private, ltd by shares"},
{"tax_id":"814630","names":[{"lang":"en","v":"GREAT GIANT ENGINEERING LIMITED"},{"lang":"hk","v":"弘力工程有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814536","names":[{"lang":"en","v":"H.K. ALICKA INT'L FURNITURE LIMITED"},{"lang":"hk","v":"香港歐麗佳國際家具有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814559","names":[{"lang":"en","v":"H.K. RED EAGLE INT'L FURNITURE HOLDINGS LIMITED"},{"lang":"hk","v":"香港大紅鷹國際家具集團有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814664","names":[{"lang":"en","v":"HAIZHU BEER (HK) COMPANY LIMITED"},{"lang":"hk","v":"海珠啤酒(香港)有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814618","names":[{"lang":"en","v":"HARBOUR PACIFIC INVESTMENT LIMITED"},{"lang":"hk","v":"港發投資有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814457","names":[{"lang":"en","v":"HK INT'L FINANCIAL INVESTMENT ETERNAL LIMITED"},{"lang":"hk","v":"香港國際金融投資永恒有限公司"}],"company_since":"2002-09-18","company_dissolved":"2006-12-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814458","names":[{"lang":"en","v":"HK SILVER INDUSTRIAL INV. DEV. LIMITED"},{"lang":"hk","v":"香港時利和實業投資發展有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814609","names":[{"lang":"en","v":"HK SOUTH SEAS.NEW HOME FURNITURE INT'L GROUP LIMITED"},{"lang":"hk","v":"香港南洋‧新家園家私國際集團有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814610","names":[{"lang":"en","v":"HK TOPONE INT'L DECORATIVE ENGINEERING LIMITED"},{"lang":"hk","v":"香港叙華國際裝飾工程有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-08-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814608","names":[{"lang":"en","v":"HK WARM JOY INT'L GROUP DRESS LIMITED"},{"lang":"hk","v":"香港萬喬國際集團服飾有限公司"}],"company_since":"2002-09-18","company_dissolved":"2005-10-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814548","names":[{"lang":"en","v":"HOI FUK LOGISTICS LIMITED"},{"lang":"hk","v":"海福物流有限公司"}],"company_since":"2002-09-18","company_dissolved":"2006-05-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"814540","names":[{"lang":"en","v":"GOLD APPLE ASIA ALUMINIUM COMPANY LIMITED (d2006-06-02)"},{"lang":"hk","v":"平果亞洲鋁業有限公司"}],"company_since":"2002-09-18","company_dissolved":"2006-06-02","company_type_txt":"Private, ltd by shares"},
{"tax_id":"814483","names":[{"lang":"en","v":"HONG KONG BOLSDEAR INTERNATIONAL GROUP LIMITED"},{"lang":"hk","v":"香港博斯迪爾國際集團有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814414","names":[{"lang":"en","v":"HONG KONG COTTON COMPANY LIMITED"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"814465","names":[{"lang":"en","v":"GOLDRISE DEVELOPMENT LIMITED"},{"lang":"hk","v":"冠高發展有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814464","names":[{"lang":"en","v":"GOOD VISION INFOTECH COMPANY LIMITED"},{"lang":"hk","v":"展望科訊有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"814714","names":[{"lang":"en","v":"HONG KONG HUA CHANG INDUSTRIAL LIMITED"},{"lang":"hk","v":"香港華昌實業有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814589","names":[{"lang":"en","v":"HONG KONG KEENFUL INVESTMENT LIMITED"},{"lang":"hk","v":"香港勤道投資有限公司"}],"company_since":"2002-09-18","company_dissolved":"2009-04-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814388","names":[{"lang":"en","v":"HONG KONG MINI BOSS FOODS LIMITED"},{"lang":"hk","v":"香港小博士食品有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814731","names":[{"lang":"en","v":"HONG KONG MOUNTAIN BIKE ASSOCIATION LIMITED"}],"company_since":"2002-09-18","company_dissolved":"2008-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814451","names":[{"lang":"en","v":"HONG KONG NEW WINDOW ADVERTISING BROADCASTING COMPANY LIMITED"},{"lang":"hk","v":"香港新視窗廣告傳播有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"814402","names":[{"lang":"en","v":"GUARANTEE SALES LIMITED"},{"lang":"hk","v":"飛昇國際企業有限公司"}],"company_since":"2002-09-18","company_dissolved":"2014-03-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"814660","names":[{"lang":"en","v":"HONG KONG YONG NIAN TAIJI QUAN SHE LIMITED"},{"lang":"hk","v":"香港永年太極拳社有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"814511","names":[{"lang":"en","v":"GROUP INTELLECT TECHNOLOGY LIMITED"},{"lang":"hk","v":"超智盈科技有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"814726","names":[{"lang":"en","v":"HONG KONG YOUYINI CLOTHING &amp; ACCESSORIES LIMITED"},{"lang":"hk","v":"香港游依妮服飾有限公司"}],"company_since":"2002-09-18","company_dissolved":"2009-02-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814653","names":[{"lang":"en","v":"HONG KONG ELIM PRESBYTERIAN CHURCH LIMITED"},{"lang":"hk","v":"香港以琳教會有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"814638","names":[{"lang":"en","v":"H &amp; S MEMORY LIMITED"},{"lang":"hk","v":"恆星禮品有限公司"}],"company_since":"2002-09-18","company_dissolved":"2012-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814537","names":[{"lang":"en","v":"HONG KONG ZIQIN FASHION LIMITED"},{"lang":"hk","v":"香港紫琴服飾有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"814395","names":[{"lang":"en","v":"HONG TAI HOLDINGS COMPANY LIMITED"},{"lang":"hk","v":"宏泰控股有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814452","names":[{"lang":"en","v":"H.K. SUNWIN INTERNATIONAL TRADING LIMITED"},{"lang":"hk","v":"香港湘源國際貿易有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-02-01","company_type_txt":"Private, ltd by shares"},
{"tax_id":"814424","names":[{"lang":"en","v":"HONGKONG LIFEFORCE INDUSTRIAL CO., LIMITED (d2015-01-30)"},{"lang":"hk","v":"香港生命力實業有限公司"}],"company_since":"2002-09-18","company_dissolved":"2015-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"814684","names":[{"lang":"en","v":"HAPPY CONCEPT CORPORATION LIMITED"},{"lang":"hk","v":"欣意有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"814423","names":[{"lang":"en","v":"HONGKONG SONG FUNE INDUSTRIAL LIMITED"},{"lang":"hk","v":"香港崧峯實業有限公司"}],"company_since":"2002-09-18","company_dissolved":"2016-02-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"814657","names":[{"lang":"en","v":"HK FIB LIMITED"}],"company_since":"2002-09-18","company_dissolved":"2009-11-20","company_type_txt":"Ltd by guarantee"},
{"tax_id":"814723","names":[{"lang":"en","v":"HUA TIAN (HONG KONG) INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"華天(香港)國際投資有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-05-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814648","names":[{"lang":"en","v":"HUNG FAI TRANSPORTATION &amp; LOGISTICS LIMITED"},{"lang":"hk","v":"鴻暉(全運)有限公司"}],"company_since":"2002-09-18","company_dissolved":"2019-03-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"814654","names":[{"lang":"en","v":"HKU ALUMNI ASSOCIATION FOR CHINA STUDY LIMITED"},{"lang":"hk","v":"香港大學國事校友會有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
{"tax_id":"814485","names":[{"lang":"en","v":"HUNG KEE VEGETABLES LIMITED"},{"lang":"hk","v":"洪記蔬菜有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"814532","names":[{"lang":"en","v":"HON SHING ELECTRONIC TECHNOLOGY (HK) LIMITED"},{"lang":"hk","v":"韓城電子科技(香港)有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-06-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"814394","names":[{"lang":"en","v":"IBT CORPORATION LIMITED"},{"lang":"hk","v":"日本索尼電機株式會社有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-01-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814644","names":[{"lang":"en","v":"ICOR (ASIA) LIMITED"}],"company_since":"2002-09-18","company_dissolved":"2010-02-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814469","names":[{"lang":"en","v":"INGENI DEVELOPMENT LIMITED"}],"company_since":"2002-09-18","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"814391","names":[{"lang":"en","v":"INTERNATIONAL FOOD AND BEVERAGE ASSOCIATION GROUP LIMITED"},{"lang":"hk","v":"國際餐飲協會集團有限公司"}],"company_since":"2002-09-18","company_dissolved":"2010-02-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814725","names":[{"lang":"en","v":"INTERNATIONAL RISK (BRAND PROTECTION) LIMITED"}],"company_since":"2002-09-18","company_dissolved":"2007-01-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814429","names":[{"lang":"en","v":"ITALY BOSSLINE (INTERNATIONAL) CLOTHING COMPANY LIMITED"},{"lang":"hk","v":"意大利波士萊恩(國際)服飾有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814704","names":[{"lang":"en","v":"ITALY KINDNESS INT'L GROUP (HK) LIMITED"},{"lang":"hk","v":"意大利凱特萊思國際集團(香港)有限公司"}],"company_since":"2002-09-18","company_dissolved":"2011-05-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814671","names":[{"lang":"en","v":"JANLINK LIMITED (d2009-02-06)"},{"lang":"hk","v":"聯安有限公司"}],"company_since":"2002-09-18","company_dissolved":"2009-02-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814681","names":[{"lang":"en","v":"JASON INVESTMENT LIMITED"},{"lang":"hk","v":"志誠投資有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814507","names":[{"lang":"en","v":"JIN YING PENG (SHENZHEN) TRANSPORTATION LIMITED"},{"lang":"hk","v":"深圳市金鷹鵬貨運有限公司"}],"company_since":"2002-09-18","company_dissolved":"2004-09-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814378","names":[{"lang":"en","v":"JOHRIC NETWORK TECHNOLOGY LIMITED"},{"lang":"hk","v":"專域網絡有限公司"}],"company_since":"2002-09-18","company_dissolved":"2005-08-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814606","names":[{"lang":"en","v":"JOINT VENTURES INVESTMENT LIMITED"},{"lang":"hk","v":"安盟投資有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814412","names":[{"lang":"en","v":"JOYSMART HOLDINGS LIMITED"},{"lang":"hk","v":"彩駿集團有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814498","names":[{"lang":"en","v":"KAI CHUK TAK LOGISTICS LIMITED"},{"lang":"hk","v":"佳速達物流有限公司"}],"company_since":"2002-09-18","company_dissolved":"2007-04-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814374","names":[{"lang":"en","v":"KAM TSUEN SHING FOOD &amp; RESTAURANT LIMITED"},{"lang":"hk","v":"金荃盛食物有限公司"}],"company_since":"2002-09-18","company_dissolved":"2004-05-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"814599","names":[{"lang":"en","v":"KAM LEE SAND AND STONE CONTRACTORS CO. LIMITED"},{"lang":"hk","v":"金利沙石工程有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814482","names":[{"lang":"en","v":"KIMURA KOGYO (H.K.) COMPANY LIMITED"},{"lang":"hk","v":"木村(香港)有限公司"}],"company_since":"2002-09-18","company_dissolved":"2016-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814668","names":[{"lang":"en","v":"KINGDOM LEADER LIMITED"},{"lang":"hk","v":"嘉業有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814531","names":[{"lang":"en","v":"KONG YAT ELEVATOR COMPANY LIMITED"},{"lang":"hk","v":"港日電梯有限公司"}],"company_since":"2002-09-18","company_dissolved":"2006-10-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814574","names":[{"lang":"en","v":"KINGDOM LEADING LIMITED"},{"lang":"hk","v":"豪晟有限公司"}],"company_since":"2002-09-18","company_dissolved":"2011-03-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"814435","names":[{"lang":"en","v":"HYRO (HONG KONG) LIMITED"}],"company_since":"2002-09-18","company_dissolved":"2011-02-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814490","names":[{"lang":"en","v":"KWOK KAM ELECTRIC CO LIMITED"},{"lang":"hk","v":"國鑫電子業有限公司"}],"company_since":"2002-09-18","company_dissolved":"2011-04-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814415","names":[{"lang":"en","v":"LANPURE GROUP COMPANY LIMITED"},{"lang":"hk","v":"藍普集團有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"814663","names":[{"lang":"en","v":"LEADER COMPANY (1993) LIMITED"},{"lang":"hk","v":"利達(1993)有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814624","names":[{"lang":"en","v":"KONRICH INVESTMENT LIMITED"},{"lang":"hk","v":"康力投資有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814496","names":[{"lang":"en","v":"LAUENDER (H.K.) COMPANY LIMITED"},{"lang":"hk","v":"發道(香港)有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-09-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814715","names":[{"lang":"en","v":"LEFA LOGISTICS &amp; TRADING COMPANY LIMITED"},{"lang":"hk","v":"利發物流有限公司"}],"company_since":"2002-09-18","company_dissolved":"2014-08-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814495","names":[{"lang":"en","v":"LIANXING CRAFTS (HONG KONG) CO., LIMITED"},{"lang":"hk","v":"連興藝品(香港)有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"814709","names":[{"lang":"en","v":"LT WORLD-WIDE LIMITED"},{"lang":"hk","v":"明泰環球有限公司"}],"company_since":"2002-09-18","company_dissolved":"2016-10-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814636","names":[{"lang":"en","v":"LUCKY WIN LIMITED (d2003-11-07)"},{"lang":"hk","v":"運俊有限公司"}],"company_since":"2002-09-18","company_dissolved":"2003-11-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814645","names":[{"lang":"en","v":"MAKE PERFECT DEVELOPMENT LIMITED"},{"lang":"hk","v":"成美發展有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814505","names":[{"lang":"en","v":"MASH &amp; SASH CONCEPTS LIMITED"},{"lang":"hk","v":"昇毅公關有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814419","names":[{"lang":"en","v":"MASTERPIECE INTERNATIONAL LIMITED (d2008-03-28)"},{"lang":"hk","v":"雋思國際有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-03-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814727","names":[{"lang":"en","v":"MEGU INTERNATIONAL LIMITED"},{"lang":"hk","v":"瀛港國際有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-02-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814567","names":[{"lang":"en","v":"MIB DESIGN LIMITED"},{"lang":"hk","v":"康宏創意有限公司"}],"company_since":"2002-09-18","company_dissolved":"2006-03-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814619","names":[{"lang":"en","v":"MICHAEL PUMPS LIMITED"},{"lang":"hk","v":"美高泵行有限公司"}],"company_since":"2002-09-18","company_dissolved":"2010-02-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814461","names":[{"lang":"en","v":"KEEN SHUN INDUSTRIAL LIMITED"},{"lang":"hk","v":"乾順實業有限公司"}],"company_since":"2002-09-18","company_dissolved":"2003-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814400","names":[{"lang":"en","v":"MINI DOG (GROUP) LIMITED"},{"lang":"hk","v":"迷你多(集團)有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814692","names":[{"lang":"en","v":"KING BRAND LIMITED (d2008-02-01)"},{"lang":"hk","v":"名牌有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814622","names":[{"lang":"en","v":"MILLION VICTORY HONG KONG LIMITED"},{"lang":"hk","v":"萬勝香港有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814380","names":[{"lang":"en","v":"MIYAKO COMPANY LIMITED"},{"lang":"hk","v":"都之味有限公司"}],"company_since":"2002-09-18","company_dissolved":"2004-08-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814584","names":[{"lang":"en","v":"KINGDOM GROUP INTERNATIONAL LIMITED"},{"lang":"hk","v":"帝豪國際有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814661","names":[{"lang":"en","v":"MODERN ASIA CONSULTANCY LIMITED"},{"lang":"hk","v":"現代亞洲顧問有限公司"}],"company_since":"2002-09-18","company_dissolved":"2008-08-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814706","names":[{"lang":"en","v":"MYER PHOTO &amp; AUDIO COMPANY LIMITED"},{"lang":"hk","v":"明利影音科技有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814640","names":[{"lang":"en","v":"NEW COAST INVESTMENT DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"新海岸投資發展有限公司"}],"company_since":"2002-09-18","company_dissolved":"2005-01-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814508","names":[{"lang":"en","v":"NEW WAY GROUP (HONG KONG) CO., LIMITED"},{"lang":"hk","v":"新路集團(香港)有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814383","names":[{"lang":"en","v":"NEWLAND CHEMCOLOR (H.K.) CO., LIMITED"},{"lang":"hk","v":"新源化工(香港)有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814579","names":[{"lang":"en","v":"NOBLE SMART ENTERPRISES LIMITED"},{"lang":"hk","v":"創興企業有限公司"}],"company_since":"2002-09-18","company_dissolved":"2012-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"814404","names":[{"lang":"en","v":"IDT Telecom Asia Pacific Limited"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"814479","names":[{"lang":"en","v":"PARTNERS CAPITAL SECURITIES LIMITED"},{"lang":"hk","v":"博大證券有限公司"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814529","names":[{"lang":"en","v":"PACIFIC LIFE TRADE SERVICES, LIMITED"}],"company_since":"2002-09-18","company_dissolved":"2012-02-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814459","names":[{"lang":"en","v":"PARENT SELECT LIMITED"},{"lang":"hk","v":"父母精選有限公司"}],"company_since":"2002-09-18","company_dissolved":"2013-12-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814476","names":[{"lang":"en","v":"OLN CORPORATE SERVICES LIMITED"}],"company_since":"2002-09-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814677","names":[{"lang":"en","v":"OVERSEAS EMPIRE LIMITED (d2009-04-17)"},{"lang":"hk","v":"僑峰有限公司"}],"company_since":"2002-09-18","company_dissolved":"2009-04-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"814656","names":[{"lang":"en","v":"PEARL RIVER DELTA FOUNDATION LIMITED"},{"lang":"hk","v":"珠三角基金會有限公司"}],"company_since":"2002-09-18","company_dissolved":"2005-02-18","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"814417","names":[{"lang":"en","v":"PACEBLADE TECHNOLOGY (HK) LIMITED"},{"lang":"hk","v":"訊品科技(香港)有限公司"}],"company_since":"2002-09-18","company_dissolved":"2005-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
