{"tax_id":"812464","names":[{"lang":"en","v":"CGA (H.K.) LIMITED"},{"lang":"hk","v":"尚華(香港)有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812491","names":[{"lang":"en","v":"CHAN MING PLANK MOULD ENGINEERING LIMITED"},{"lang":"hk","v":"陳明板模工程有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812538","names":[{"lang":"en","v":"CHARIS CHILDREN'S WORKSHOP LIMITED"},{"lang":"hk","v":"天恩兒童工作坊有限公司"}],"company_since":"2002-09-02","company_dissolved":"2005-12-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812643","names":[{"lang":"en","v":"CHINA BOND MANUFACTURING LIMITED"},{"lang":"hk","v":"朗盈制品有限公司"}],"company_since":"2002-09-02","company_dissolved":"2007-01-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812533","names":[{"lang":"en","v":"CHINA INTERNATIONAL OVERSEAS-CHINESE INVESTMENT GROUP (ASIA) LIMITED"},{"lang":"hk","v":"中國國際華僑投資集團(亞洲)有限公司"}],"company_since":"2002-09-02","company_dissolved":"2008-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812554","names":[{"lang":"en","v":"CHINA INTERNATIONAL TRADING INVESTMENT SHARING LIMITED"},{"lang":"hk","v":"中國國際貿易投資股份有限公司"}],"company_since":"2002-09-02","company_dissolved":"2008-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812595","names":[{"lang":"en","v":"CHUN SHING TRANSPORT COMPANY LIMITED"},{"lang":"hk","v":"振成貨運有限公司"}],"company_since":"2002-09-02","company_dissolved":"2016-12-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812618","names":[{"lang":"en","v":"CHUNG WAN INDUSTRIAL COMPANY (FAR EAST) LIMITED"},{"lang":"hk","v":"中環實業(遠東)有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812532","names":[{"lang":"en","v":"CONTINENTAL OIL &amp; FUEL COMPANY LIMITED"},{"lang":"hk","v":"大地石油有限公司"}],"company_since":"2002-09-02","company_dissolved":"2008-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812639","names":[{"lang":"en","v":"DEKSON INTERNATIONAL LIMITED"},{"lang":"hk","v":"得勤國際有限公司"}],"company_since":"2002-09-02","company_dissolved":"2004-09-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812568","names":[{"lang":"en","v":"CHAMPION TRADERS DEVELOPMENT LIMITED"},{"lang":"hk","v":"冠貿控股有限公司"}],"company_since":"2002-09-02","company_dissolved":"2008-01-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"812540","names":[{"lang":"en","v":"DELTON CAPITAL COMPANY LIMITED"},{"lang":"hk","v":"三能資本有限公司"}],"company_since":"2002-09-02","company_dissolved":"2010-01-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812640","names":[{"lang":"en","v":"DESAY (HONG KONG) LIMITED"},{"lang":"hk","v":"德賽(香港)有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"812627","names":[{"lang":"en","v":"DK LIMITED (d2009-01-30)"}],"company_since":"2002-09-02","company_dissolved":"2009-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812583","names":[{"lang":"en","v":"DOLCHE INVESTMENT INTERNATIONAL LIMITED"}],"company_since":"2002-09-02","company_dissolved":"2004-02-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812590","names":[{"lang":"en","v":"DOUBLE SUN HOLDINGS (H.K.) LIMITED"},{"lang":"hk","v":"重陽堂集團(香港)有限公司"}],"company_since":"2002-09-02","company_dissolved":"2008-05-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812585","names":[{"lang":"en","v":"CHIU KEE SCAFFOLDING LIMITED"},{"lang":"hk","v":"照記棚業工程有限公司"}],"company_since":"2002-09-02","company_dissolved":"2012-11-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"812418","names":[{"lang":"en","v":"CROWN BEST (HONG KONG) LIMITED"},{"lang":"hk","v":"冠鴻(香港)有限公司"}],"company_since":"2002-09-02","company_dissolved":"2011-02-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812463","names":[{"lang":"en","v":"CHUN HING WATCH DIAL FACTORY LIMITED"},{"lang":"hk","v":"振興錶面廠有限公司"}],"company_since":"2002-09-02","company_dissolved":"2007-12-07","company_type_txt":"Private, ltd by shares"},
{"tax_id":"812542","names":[{"lang":"en","v":"DREAMWORKS COMPANY LIMITED"},{"lang":"hk","v":"童夢有限公司"}],"company_since":"2002-09-02","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812591","names":[{"lang":"en","v":"EAST CONTINENTAL INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"東洲國際投資有限公司"}],"company_since":"2002-09-02","company_dissolved":"2009-06-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812581","names":[{"lang":"en","v":"EASTERN LAKE CARTON &amp; PRINTING COMPANY LIMITED"},{"lang":"hk","v":"東湖啤盒印刷有限公司"}],"company_since":"2002-09-02","company_dissolved":"2003-06-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812630","names":[{"lang":"en","v":"CHUNG KEE (WAI CHUEN) TRANSPORT COMPANY LIMITED"},{"lang":"hk","v":"鍾記(韋泉)貨運有限公司"}],"company_since":"2002-09-02","company_dissolved":"2008-07-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"812597","names":[{"lang":"en","v":"EUROASIA GROUP (H.K.) LIMITED"},{"lang":"hk","v":"歐亞集團(香港)有限公司"}],"company_since":"2002-09-02","company_dissolved":"2011-04-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812482","names":[{"lang":"en","v":"EUROASIA PLASTIC TRADING LIMITED"},{"lang":"hk","v":"歐亞興利貿易有限公司"}],"company_since":"2002-09-02","company_dissolved":"2008-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812607","names":[{"lang":"en","v":"CHIU CHUN GLOBAL EXPLORATION ELECTRICITY POWER SAVER LIMITED"},{"lang":"hk","v":"朝進世界拓展環電節能有限公司"}],"company_since":"2002-09-02","company_dissolved":"2006-08-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812523","names":[{"lang":"en","v":"EVER FORTUNE ENTERPRISE (H.K.) CO., LIMITED (d2009-12-18)"},{"lang":"hk","v":"恆運企業(香港)有限公司"}],"company_since":"2002-09-02","company_dissolved":"2009-12-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812649","names":[{"lang":"en","v":"CODA ENGINEERING CONSULTANT LIMITED"},{"lang":"hk","v":"高達工程顧問有限公司"}],"company_since":"2002-09-02","company_dissolved":"2018-04-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812562","names":[{"lang":"en","v":"COMMANDSAVE WORKSHOP LIMITED"}],"company_since":"2002-09-02","company_dissolved":"2008-01-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"812574","names":[{"lang":"en","v":"EVERGOOD CAPITAL (ASIA) LIMITED"},{"lang":"hk","v":"華寶(亞洲)有限公司"}],"company_since":"2002-09-02","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812439","names":[{"lang":"en","v":"EXCELLENT INTERNATIONAL CRAFTS LIMITED"},{"lang":"hk","v":"極品工藝國際有限公司"}],"company_since":"2002-09-02","company_dissolved":"2004-04-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812417","names":[{"lang":"en","v":"CONCORD LOGISTICS DEVELOPMENT GROUP LIMITED"},{"lang":"hk","v":"和諧物流建設集團有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812646","names":[{"lang":"en","v":"FAITH PROSPER LIMITED"},{"lang":"hk","v":"忠盛有限公司"}],"company_since":"2002-09-02","company_dissolved":"2015-12-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812560","names":[{"lang":"en","v":"FORTUNE A INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"晉大創富國際有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812548","names":[{"lang":"en","v":"FORTUNE INVESTMENT &amp; MANAGEMENT CORPORATION LIMITED"},{"lang":"hk","v":"富誠投資管理有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812452","names":[{"lang":"en","v":"CSD &amp; PARTNERS LIMITED"},{"lang":"hk","v":"廣斯策略有限公司"}],"company_since":"2002-09-02","company_dissolved":"2005-03-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812614","names":[{"lang":"en","v":"FRANCE BOSS INT'L GROUP (HK) INDUSTRIAL LIMITED"},{"lang":"hk","v":"法國波士國際集團(香港)實業有限公司"}],"company_since":"2002-09-02","company_dissolved":"2010-01-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812617","names":[{"lang":"en","v":"FRANCE FULL PROFIT INT'L GARMENT (HOLDINGS) LIMITED"},{"lang":"hk","v":"法國富利來國際服飾(集團)有限公司"}],"company_since":"2002-09-02","company_dissolved":"2005-10-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812596","names":[{"lang":"en","v":"FUNG SHING INDUSTRIAL COMPANY LIMITED"},{"lang":"hk","v":"豐盛實業(股份)有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812579","names":[{"lang":"en","v":"G &amp; O LIMITED"},{"lang":"hk","v":"金海洋旭日有限公司"}],"company_since":"2002-09-02","company_dissolved":"2014-07-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812458","names":[{"lang":"en","v":"GASS INTERNATIONAL LIMITED"},{"lang":"hk","v":"嘉宜國際有限公司"}],"company_since":"2002-09-02","company_dissolved":"2008-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812623","names":[{"lang":"en","v":"GENNOX PHARMA LIMITED"},{"lang":"hk","v":"濟樂藥業有限公司"}],"company_since":"2002-09-02","company_dissolved":"2008-12-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812552","names":[{"lang":"en","v":"GERMANY BSP ARCHITECTS &amp; ENGINEERS LIMITED"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812537","names":[{"lang":"en","v":"DOLCHE HOLDINGS LIMITED"}],"company_since":"2002-09-02","company_dissolved":"2004-02-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"812570","names":[{"lang":"en","v":"GLOBAL LOGISTICS SERVICE LIMITED"}],"company_since":"2002-09-02","company_dissolved":"2008-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812494","names":[{"lang":"en","v":"CHI MEI (HK) LIMITED"},{"lang":"hk","v":"琦美有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"812528","names":[{"lang":"en","v":"GLOBAL RISE (HONG KONG) DEVELOPMENT LIMITED"},{"lang":"hk","v":"高昇(香港)發展有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812420","names":[{"lang":"en","v":"GREATIME AUTOS LIMITED"},{"lang":"hk","v":"偉馳汽車有限公司"}],"company_since":"2002-09-02","company_dissolved":"2015-09-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812645","names":[{"lang":"en","v":"GUANGJI MEDICAL EQUIPMENT TECHNICAL SERVICE COMPANY LIMITED"},{"lang":"hk","v":"廣濟醫療器械技術服務有限公司"}],"company_since":"2002-09-02","company_dissolved":"2005-02-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812624","names":[{"lang":"en","v":"DRAGON SEA ENERGY &amp; CHEMICALS COMPANY LIMITED"},{"lang":"hk","v":"龍海國際能源化工有限公司"}],"company_since":"2002-09-02","company_dissolved":"2007-01-26","company_type_txt":"Private, ltd by shares"},
{"tax_id":"812511","names":[{"lang":"en","v":"H ASIA LIMITED"},{"lang":"hk","v":"哈瑞亞洲有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812424","names":[{"lang":"en","v":"H.K. EAST-BEST INTERNATIONAL LIMITED"},{"lang":"hk","v":"香港隆盛國際有限公司"}],"company_since":"2002-09-02","company_dissolved":"2008-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812558","names":[{"lang":"en","v":"H.K. VIC TECHNOLOGY INT'L LIMITED"},{"lang":"hk","v":"香港威克科技國際有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812526","names":[{"lang":"en","v":"H.K. WEIFUSHIJIA INT'L FASHION LIMITED"},{"lang":"hk","v":"香港微服世家國際服飾有限公司"}],"company_since":"2002-09-02","company_dissolved":"2008-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812497","names":[{"lang":"en","v":"H.K. YIXIN METAL INDUSTRIAL LIMITED"},{"lang":"hk","v":"香港億鑫金屬實業有限公司"}],"company_since":"2002-09-02","company_dissolved":"2018-05-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812479","names":[{"lang":"en","v":"HIP SANG INDUSTRIAL &amp; TRADING LIMITED"},{"lang":"hk","v":"協生工貿有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812419","names":[{"lang":"en","v":"HISONIC AUDIO LIMITED"},{"lang":"hk","v":"高盛電子有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812505","names":[{"lang":"en","v":"HK 100 YUAN PANTS DRESS GROUP LIMITED"},{"lang":"hk","v":"香港百圓褲業服飾集團有限公司"}],"company_since":"2002-09-02","company_dissolved":"2010-05-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812638","names":[{"lang":"en","v":"HK JEEJA ELECTRON INDUSTRY CO., LIMITED"},{"lang":"hk","v":"香港金積嘉電子工業有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812503","names":[{"lang":"en","v":"HK LONGRISE (INT'L) DRESS LIMITED"},{"lang":"hk","v":"香港龍騰(國際)服飾有限公司"}],"company_since":"2002-09-02","company_dissolved":"2008-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812480","names":[{"lang":"en","v":"HK WARREN CARTON FASHIONS HOLDINGS LIMITED"},{"lang":"hk","v":"香港華倫卡丹服飾集團有限公司"}],"company_since":"2002-09-02","company_dissolved":"2004-10-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812599","names":[{"lang":"en","v":"HO FUNG STEEL CO., LIMITED"},{"lang":"hk","v":"浩豐鋼鐵有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812576","names":[{"lang":"en","v":"HO YEUNG ENTERPRISE LIMITED"},{"lang":"hk","v":"灝洋企業有限公司"}],"company_since":"2002-09-02","company_dissolved":"2004-10-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812435","names":[{"lang":"en","v":"HONG KONG DEECHON FURNITURE GROUP LIMITED"},{"lang":"hk","v":"香港迪創家具集團有限公司"}],"company_since":"2002-09-02","company_dissolved":"2006-09-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812622","names":[{"lang":"en","v":"HONG KONG DIAMOND TOOL CO. LIMITED"},{"lang":"hk","v":"香港金剛石工具有限公司"}],"company_since":"2002-09-02","company_dissolved":"2011-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812413","names":[{"lang":"en","v":"HONG KONG DONG LI XING INTERNATIONAL LIMITED"},{"lang":"hk","v":"香港東立興國際有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"812433","names":[{"lang":"en","v":"HONG KONG FU LAI DI SI FURNITURE GROUP LIMITED"},{"lang":"hk","v":"香港弗萊帝斯傢俱集團有限公司"}],"company_since":"2002-09-02","company_dissolved":"2008-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812587","names":[{"lang":"en","v":"HONG KONG HONGLI INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"香港紅麗國際集團有限公司"}],"company_since":"2002-09-02","company_dissolved":"2010-01-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812524","names":[{"lang":"en","v":"HONG KONG JIAFENG INVESTMENT DEVELOPMENT CO., LIMITED"},{"lang":"hk","v":"香港佳峰投資發展有限公司"}],"company_since":"2002-09-02","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812474","names":[{"lang":"en","v":"HONG KONG MAX GLORY SHOES LIMITED"},{"lang":"hk","v":"香港匯洋鞋業有限公司"}],"company_since":"2002-09-02","company_dissolved":"2008-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812635","names":[{"lang":"en","v":"HONG KONG NO. ONE TRADING LIMITED"},{"lang":"hk","v":"香港第一村貿易有限公司"}],"company_since":"2002-09-02","company_dissolved":"2008-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812536","names":[{"lang":"en","v":"GUARDIAN ENTERPRISES LIMITED (HK)"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"812555","names":[{"lang":"en","v":"HONG KONG TENG YUAN GROUP INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"香港騰源集團國際投資有限公司"}],"company_since":"2002-09-02","company_dissolved":"2008-05-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812519","names":[{"lang":"en","v":"HONG KONG YAO GUANG LIGHTING GROUP COMPANY LIMITED"},{"lang":"hk","v":"香港瑤光燈飾集團有限公司"}],"company_since":"2002-09-02","company_dissolved":"2008-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812431","names":[{"lang":"en","v":"HONGKONG ELEOM ELECTRONIC CO., LIMITED"},{"lang":"hk","v":"香港艾利姆電子有限公司"}],"company_since":"2002-09-02","company_dissolved":"2008-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812647","names":[{"lang":"en","v":"HONG ZHONG SYSTEMS &amp; SOLUTIONS (HK) LIMITED"},{"lang":"hk","v":"宏中科技(香港)有限公司"}],"company_since":"2002-09-02","company_dissolved":"2017-05-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812572","names":[{"lang":"en","v":"HONGKONG JIN GUO FASHION LEATHER INTERNATIONAL LIMITED (d2008-01-18)"},{"lang":"hk","v":"香港金果服飾皮具國際有限公司"}],"company_since":"2002-09-02","company_dissolved":"2008-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812652","names":[{"lang":"en","v":"HONOUR PROFIT INVESTMENT LIMITED"},{"lang":"hk","v":"麟盈投資有限公司"}],"company_since":"2002-09-02","company_dissolved":"2008-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812486","names":[{"lang":"en","v":"HANBANG INVESTMENT (HK) COMPANY LIMITED"},{"lang":"hk","v":"香港漢邦投資有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"812484","names":[{"lang":"en","v":"HOP SHING CIVIL ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"合成建造工程有限公司"}],"company_since":"2002-09-02","company_dissolved":"2020-03-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812631","names":[{"lang":"en","v":"Horizon21 (Hong Kong) Limited"}],"company_since":"2002-09-02","company_dissolved":"2011-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812453","names":[{"lang":"en","v":"HEALTH DIGIT (H.K.) LIMITED"},{"lang":"hk","v":"數康生物科技(香港)有限公司"}],"company_since":"2002-09-02","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"812496","names":[{"lang":"en","v":"HUAMENG INT'L INVESTMENT GROUP LIMITED"},{"lang":"hk","v":"華蒙國際投資集團有限公司"}],"company_since":"2002-09-02","company_dissolved":"2010-01-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812502","names":[{"lang":"en","v":"HK KATHY INT'L GROUP LIMITED"},{"lang":"hk","v":"香港凱西國際集團有限公司"}],"company_since":"2002-09-02","company_dissolved":"2008-05-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812449","names":[{"lang":"en","v":"II CONCEPT LIMITED"}],"company_since":"2002-09-02","company_dissolved":"2014-05-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812473","names":[{"lang":"en","v":"ITALY ROME HOLIDAY (INTERNATIONAL) GROUP CO., LIMITED"},{"lang":"hk","v":"意大利羅馬假日(國際)集團有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812469","names":[{"lang":"en","v":"ITALY XUE ZHONG HONG (INTERNATIONAL) FINERY LIMITED"},{"lang":"hk","v":"意大利雪中紅(國際)服飾有限公司"}],"company_since":"2002-09-02","company_dissolved":"2005-06-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812472","names":[{"lang":"en","v":"J B INTERNATIONAL TRADING COMPANY LIMITED"}],"company_since":"2002-09-02","company_dissolved":"2015-03-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"812470","names":[{"lang":"en","v":"JAPAN SAN MU FINERY (INTERNATIONAL) HOLDINGS LIMITED"},{"lang":"hk","v":"日本三木服飾(國際)股份有限公司"}],"company_since":"2002-09-02","company_dissolved":"2008-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812629","names":[{"lang":"en","v":"HO MAN HOLDINGS LIMITED"}],"company_since":"2002-09-02","company_dissolved":"2008-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812588","names":[{"lang":"en","v":"GEM INTERNATIONAL (HONG KONG) LIMITED"},{"lang":"hk","v":"吉義美國際(香港)有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"812490","names":[{"lang":"en","v":"KAM TONG CONSTRUCTION &amp; ENGINEERING LIMITED"},{"lang":"hk","v":"錦瑭建業工程有限公司"}],"company_since":"2002-09-02","company_dissolved":"2003-12-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812434","names":[{"lang":"en","v":"HONG KONG BLUE SKY ENTERPRISE GROUP LIMITED"},{"lang":"hk","v":"香港藍天企業集團有限公司"}],"company_since":"2002-09-02","company_dissolved":"2008-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812500","names":[{"lang":"en","v":"KANISHI MINILABS LIMITED"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812501","names":[{"lang":"en","v":"KANISHI TRADING COMPANY LIMITED"},{"lang":"hk","v":"嘉利仕貿易有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812422","names":[{"lang":"en","v":"KANT INDUSTRIAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"康德實業發展有限公司"}],"company_since":"2002-09-02","company_dissolved":"2020-04-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812517","names":[{"lang":"en","v":"KEEWAY ENVIRONMENTAL HI-TECH ENERGY DEVELOPMENT (HK) COMPANY LIMITED"},{"lang":"hk","v":"奇威環保科技能源開發(香港)有限公司"}],"company_since":"2002-09-02","company_dissolved":"2008-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812544","names":[{"lang":"en","v":"GOLDWELL PEAK TECHNOLOGY CO LIMITED"},{"lang":"hk","v":"金井鋒科技有限公司"}],"company_since":"2002-09-02","company_dissolved":"2005-02-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"812520","names":[{"lang":"en","v":"KEN WELL (SERVICES) ENGINEERING LIMITED"},{"lang":"hk","v":"建科工程有限公司"}],"company_since":"2002-09-02","company_dissolved":"2006-05-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812459","names":[{"lang":"en","v":"HONG KONG LOYAL INTERNATIONAL TRADE LIMITED"},{"lang":"hk","v":"香港榮恩國際貿易有限公司"}],"company_since":"2002-09-02","company_dissolved":"2019-03-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812565","names":[{"lang":"en","v":"KODAR MANUFACTORY COMPANY LIMITED"},{"lang":"hk","v":"高達製造廠有限公司"}],"company_since":"2002-09-02","company_dissolved":"2012-01-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"812625","names":[{"lang":"en","v":"GREENTOWN ENTERPRISES LIMITED"},{"lang":"hk","v":"廣通企業發展有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812412","names":[{"lang":"en","v":"MAJOR FILMS PRODUCTION LIMITED"},{"lang":"hk","v":"賣座電影制作有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812475","names":[{"lang":"en","v":"MAR KEE LOGISTICS LIMITED"},{"lang":"hk","v":"孖記物流有限公司"}],"company_since":"2002-09-02","company_dissolved":"2008-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812521","names":[{"lang":"en","v":"MAX BRIGHT ELECTRONICS LIMITED"},{"lang":"hk","v":"茂隆電子有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812656","names":[{"lang":"en","v":"MATHSLAB CO., LIMITED"},{"lang":"hk","v":"數學專門店有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812509","names":[{"lang":"en","v":"HOOVER DAM TECHNOLOGY ASIA LIMITED"},{"lang":"hk","v":"浩信亞洲有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"812628","names":[{"lang":"en","v":"MAXVALUE CAPITAL LIMITED"},{"lang":"hk","v":"恆智策略有限公司"}],"company_since":"2002-09-02","company_dissolved":"2007-02-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812636","names":[{"lang":"en","v":"MEI SHING RESTAURANT DESIGN LIMITED"},{"lang":"hk","v":"美城飲食業設計廔有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812615","names":[{"lang":"en","v":"MILLION RICH TRADING (H.K.) LIMITED"},{"lang":"hk","v":"億富貿易(香港)有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812569","names":[{"lang":"en","v":"MING TAI WHOLESALING COMPANY LIMITED"},{"lang":"hk","v":"明泰批發有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812553","names":[{"lang":"en","v":"Miracle Marketing Limited (d2015-01-09)"},{"lang":"hk","v":"奇創市場策劃有限公司"}],"company_since":"2002-09-02","company_dissolved":"2015-01-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812616","names":[{"lang":"en","v":"MMT CREATIONS COMPANY LIMITED"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812516","names":[{"lang":"en","v":"MULTI-PLUS BUILDING MATERIALS COMPANY LIMITED"},{"lang":"hk","v":"萬盈世富建材有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812575","names":[{"lang":"en","v":"NETECH LIMITED"},{"lang":"hk","v":"立達科技有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812456","names":[{"lang":"en","v":"NEW REACH CO. LIMITED"},{"lang":"hk","v":"創新峰有限公司"}],"company_since":"2002-09-02","company_dissolved":"2008-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812467","names":[{"lang":"en","v":"ORIENTAL TRANSPORT LIMITED"},{"lang":"hk","v":"東方旅運有限公司"}],"company_since":"2002-09-02","company_dissolved":"2006-07-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812499","names":[{"lang":"en","v":"OZONE GLASS DESIGN (CHINA) LIMITED"},{"lang":"hk","v":"澳中玻璃設計(中國)有限公司"}],"company_since":"2002-09-02","company_dissolved":"2014-05-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812571","names":[{"lang":"en","v":"P &amp; H GROUP LIMITED (d2015-01-09)"},{"lang":"hk","v":"亞獅集團有限公司"}],"company_since":"2002-09-02","company_dissolved":"2015-01-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812531","names":[{"lang":"en","v":"P &amp; H SWEATER MANUFACTURING LIMITED"},{"lang":"hk","v":"永駿毛織有限公司"}],"company_since":"2002-09-02","company_dissolved":"2010-09-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812427","names":[{"lang":"en","v":"PEARL TEXTILES INTERNATIONAL LIMITED"},{"lang":"hk","v":"保達紡織國際有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812423","names":[{"lang":"en","v":"POWA ELECTRONICS CO., LIMITED"},{"lang":"hk","v":"寶源電子有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812407","names":[{"lang":"en","v":"POWER &amp; CONSTRUCTION MANAGEMENT (PCM) LIMITED"}],"company_since":"2002-09-02","company_dissolved":"2005-05-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812414","names":[{"lang":"en","v":"POWER UNIVERSE LIMITED (d2005-05-27)"},{"lang":"hk","v":"承宇有限公司"}],"company_since":"2002-09-02","company_dissolved":"2005-05-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812563","names":[{"lang":"en","v":"PRIME IMP &amp; EXP CORPORATION LIMITED"},{"lang":"hk","v":"普萊姆進出口有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812650","names":[{"lang":"en","v":"PROPSER GLORIOUS LIMITED"},{"lang":"hk","v":"紳貴有限公司"}],"company_since":"2002-09-02","company_dissolved":"2008-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812409","names":[{"lang":"en","v":"RANE LIMITED (d2008-01-25)"}],"company_since":"2002-09-02","company_dissolved":"2008-01-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812584","names":[{"lang":"en","v":"RONG TAI ENTERPRISES LIMITED"},{"lang":"hk","v":"榮泰洋行有限公司"}],"company_since":"2002-09-02","company_dissolved":"2012-06-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812578","names":[{"lang":"en","v":"SAFERICH SECRETARIAL LIMITED"},{"lang":"hk","v":"安豐秘書服務有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812506","names":[{"lang":"en","v":"SALESWIN (H.K.) INTERNATIONAL LIMITED"},{"lang":"hk","v":"賽馳(香港)國際貿易有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812655","names":[{"lang":"en","v":"SAR BUSINESS &amp; FINANCIAL SERVICES LIMITED"},{"lang":"hk","v":"創意商業財務諮詢有限公司"}],"company_since":"2002-09-02","company_dissolved":"2008-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812487","names":[{"lang":"en","v":"SDA LIMITED (HK)"},{"lang":"hk","v":"銀龍(亞洲)有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812634","names":[{"lang":"en","v":"SERP FASTPRINT LIMITED"}],"company_since":"2002-09-02","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812455","names":[{"lang":"en","v":"SHENGDI ENTERPRISE GROUP LIMITED"},{"lang":"hk","v":"森地企業集團有限公司"}],"company_since":"2002-09-02","company_dissolved":"2013-10-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812457","names":[{"lang":"en","v":"NATURAL SPACE INVESTMENT &amp; HOLDING GROUP (HONG KONG) LIMITED"},{"lang":"hk","v":"自然空間投資控股集團(香港)有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812471","names":[{"lang":"en","v":"SINO TRADE DEVELOPING CO., LIMITED"},{"lang":"hk","v":"華威貿易發展有限公司"}],"company_since":"2002-09-02","company_dissolved":"2015-07-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812582","names":[{"lang":"en","v":"SOUND WELL TECHNOLOGY (ASIA) LIMITED"},{"lang":"hk","v":"星威科技(亞洲)有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812632","names":[{"lang":"en","v":"NOBLE ENVIRONMENTAL SOLUTIONS LIMITED"}],"company_since":"2002-09-02","company_dissolved":"2017-05-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"812466","names":[{"lang":"en","v":"SOUTH SEA TEXTILE COMPANY LIMITED"},{"lang":"hk","v":"南海布業有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812602","names":[{"lang":"en","v":"SPINAL HEALTH PRODUCTS CO., LIMITED"},{"lang":"hk","v":"脊健用品有限公司"}],"company_since":"2002-09-02","company_dissolved":"2004-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812461","names":[{"lang":"en","v":"STAR PROGRAMME LIMITED"}],"company_since":"2002-09-02","company_dissolved":"2004-02-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812550","names":[{"lang":"en","v":"PARKCO PLASTIC &amp; METAL MANUFACTURING LIMITED"},{"lang":"hk","v":"栢高塑膠五金製品有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"812437","names":[{"lang":"en","v":"SPRING CRAFTS TRADING LIMITED"},{"lang":"hk","v":"春江工藝品進出口有限公司"}],"company_since":"2002-09-02","company_dissolved":"2004-04-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812495","names":[{"lang":"en","v":"PERFECT ROASTED GOOSE HOTPOT RESTAURANT LIMITED"},{"lang":"hk","v":"一品燒鵝火鍋酒家有限公司"}],"company_since":"2002-09-02","company_dissolved":"2009-06-26","company_type_txt":"Private, ltd by shares"},
{"tax_id":"812653","names":[{"lang":"en","v":"Sun Wah Investment (Hong Kong) Limited"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812442","names":[{"lang":"en","v":"SUN WO HING (HOLDINGS) COMPANY LIMITED"},{"lang":"hk","v":"新和興(集團)有限公司"}],"company_since":"2002-09-02","company_dissolved":"2012-11-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812580","names":[{"lang":"en","v":"SUN YUEN TUNG DEVELOPMENT LIMITED"},{"lang":"hk","v":"新源通發展有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812547","names":[{"lang":"en","v":"SUNSHINE DECORATION PRODUCTS MANUFACTORY LIMITED"},{"lang":"hk","v":"永城裝飾製品有限公司"}],"company_since":"2002-09-02","company_dissolved":"2008-09-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812648","names":[{"lang":"en","v":"SUPREME PROFITS LIMITED"},{"lang":"hk","v":"盈御有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812620","names":[{"lang":"en","v":"TAK YUN INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"德潤國際發展有限公司"}],"company_since":"2002-09-02","company_dissolved":"2008-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812610","names":[{"lang":"en","v":"TECHNOLTRONICS INTERNATIONAL CO., LIMITED"},{"lang":"hk","v":"訊科創建有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812426","names":[{"lang":"en","v":"TOMORROW INTERNATIONAL TRADE CO., LIMITED"},{"lang":"hk","v":"銘日國際貿易有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812510","names":[{"lang":"en","v":"TOP ON (H.K.) LIMITED"},{"lang":"hk","v":"德安飲食有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812626","names":[{"lang":"en","v":"RTI INTERNATIONAL CO., LIMITED"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"812478","names":[{"lang":"en","v":"TOUCH BEAUTY &amp; BODY WORKS LIMITED"},{"lang":"hk","v":"蝶川美容坊有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812425","names":[{"lang":"en","v":"TOPSTAR INTERTRADE LIMITED"},{"lang":"hk","v":"上官國際貿易有限公司"}],"company_since":"2002-09-02","company_dissolved":"2007-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812477","names":[{"lang":"en","v":"TREASURE LAND (HK) INTERNATIONAL LIMITED"},{"lang":"hk","v":"寶田(香港)國際有限公司"}],"company_since":"2002-09-02","company_dissolved":"2007-02-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812539","names":[{"lang":"en","v":"TRINITY ACCOUNTANCY LIMITED"},{"lang":"hk","v":"全永註冊會計有限公司"}],"company_since":"2002-09-02","company_dissolved":"2008-01-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812460","names":[{"lang":"en","v":"TSUN TAT ASIA SYSTEM COMPANY LIMITED"},{"lang":"hk","v":"俊達亞洲系統有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812637","names":[{"lang":"en","v":"SCE (HK) INTERNATIONAL CO., LIMITED"},{"lang":"hk","v":"華南國際(香港)有限公司"}],"company_since":"2002-09-02","company_dissolved":"2004-09-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"812421","names":[{"lang":"en","v":"UNION TOUGH INTERNATIONAL LIMITED"},{"lang":"hk","v":"匯剛國際有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812611","names":[{"lang":"en","v":"UNIVERSAL CULTURE DEVELOPMENT LIMITED"},{"lang":"hk","v":"環球文化發展有限公司"}],"company_since":"2002-09-02","company_dissolved":"2009-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812488","names":[{"lang":"en","v":"VERTEX (ASIA) LIMITED"},{"lang":"hk","v":"啟達(亞洲)有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812507","names":[{"lang":"en","v":"VIAQUO HONG KONG LIMITED"}],"company_since":"2002-09-02","company_dissolved":"2004-08-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812522","names":[{"lang":"en","v":"VISIONS BALLOONS LIMITED"}],"company_since":"2002-09-02","company_dissolved":"2007-06-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812641","names":[{"lang":"en","v":"TANNY TRADING (HONG KONG) LIMITED"},{"lang":"hk","v":"添利貿易(香港)有限公司"}],"company_since":"2002-09-02","company_dissolved":"2005-07-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812462","names":[{"lang":"en","v":"VOLANTE SYSTEMS (HONG KONG) LIMITED"},{"lang":"hk","v":"科達系統有限公司"}],"company_since":"2002-09-02","company_dissolved":"2012-02-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812605","names":[{"lang":"en","v":"SOUTH EAST ASIA WOMEN RECREATION CLUB LIMITED"},{"lang":"hk","v":"東南亞婦女互助聯誼會有限公司"}],"company_since":"2002-09-02","company_dissolved":"2011-05-20","company_type_txt":"Ltd by guarantee"},
{"tax_id":"812606","names":[{"lang":"en","v":"WAH TUNG ENTERPRISE INTERNATIONAL LIMITED"},{"lang":"hk","v":"華通企業國際有限公司"}],"company_since":"2002-09-02","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812451","names":[{"lang":"en","v":"WAI FUNG HARDWARE CO., LIMITED"},{"lang":"hk","v":"慧豐五金有限公司"}],"company_since":"2002-09-02","company_dissolved":"2005-02-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812577","names":[{"lang":"en","v":"WAN STONE INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"泓堅國際投資有限公司"}],"company_since":"2002-09-02","company_dissolved":"2010-04-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812498","names":[{"lang":"en","v":"WELL TRADE EXPRESS LIMITED"},{"lang":"hk","v":"威進快件有限公司"}],"company_since":"2002-09-02","company_dissolved":"2003-10-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812438","names":[{"lang":"en","v":"WING HANG INTERNATIONAL CRAFTS TRADING LIMITED"},{"lang":"hk","v":"永興(國際)工藝品貿易有限公司"}],"company_since":"2002-09-02","company_dissolved":"2004-04-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812567","names":[{"lang":"en","v":"WING TAI PRINTING FACTORY LIMITED"},{"lang":"hk","v":"榮泰印刷廠有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812535","names":[{"lang":"en","v":"WINNER (ASIA) ENTERPRISES LIMITED"},{"lang":"hk","v":"合勝(亞洲)企業有限公司"}],"company_since":"2002-09-02","company_dissolved":"2017-05-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812642","names":[{"lang":"en","v":"WISDOM FIRMLY HOLDINGS LIMITED"},{"lang":"hk","v":"毅智控股有限公司"}],"company_since":"2002-09-02","company_dissolved":"2009-06-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812561","names":[{"lang":"en","v":"WO SANG PRUDENTIAL EDUCATION FOUNDATION LIMITED"},{"lang":"hk","v":"和生慎德教育基金有限公司"}],"company_since":"2002-09-02","company_dissolved":"2015-03-23","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"812546","names":[{"lang":"en","v":"WORLD GLOBAL TECHNICAL SERVICES LIMITED"},{"lang":"hk","v":"榮高電腦服務有限公司"}],"company_since":"2002-09-02","company_dissolved":"2007-06-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812557","names":[{"lang":"en","v":"WORLD GLORY STEVEDORE LIMITED"},{"lang":"hk","v":"華鴻裝卸有限公司"}],"company_since":"2002-09-02","company_dissolved":"2010-01-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812592","names":[{"lang":"en","v":"WORLD RELIANCE MONEY EXCHANGE LIMITED"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812534","names":[{"lang":"en","v":"YEE SHING INTERNATIONAL LIMITED"},{"lang":"hk","v":"頤盛國際有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812564","names":[{"lang":"en","v":"XIN YE HOUSEWARE LIMITED"},{"lang":"hk","v":"興業家品有限公司"}],"company_since":"2002-09-02","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812621","names":[{"lang":"en","v":"YING FUNG SAN (HONG KONG) CO. LIMITED"},{"lang":"hk","v":"盈豐三(香港)有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812541","names":[{"lang":"en","v":"YOUNG CREATIVE TRADING LIMITED"}],"company_since":"2002-09-02","company_dissolved":"2009-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812633","names":[{"lang":"en","v":"YoungCom Biotech Limited"},{"lang":"hk","v":"陽康生物科技有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812465","names":[{"lang":"en","v":"YUK SING METAL &amp; PLASTIC MFY LIMITED"},{"lang":"hk","v":"旭昇五金塑膠製品廠有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812441","names":[{"lang":"en","v":"YUN HANG TRADING COMPANY LIMITED"},{"lang":"hk","v":"潤恒貿易有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812436","names":[{"lang":"en","v":"ZHANG ENTERPRISES INTERNATIONAL CRAFTS LIMITED"},{"lang":"hk","v":"張家(國際)工藝品有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"812593","names":[{"lang":"en","v":"WANGLI PAPER PRODUCTS LIMITED"},{"lang":"hk","v":"旺利紙品有限公司"}],"company_since":"2002-09-02","company_dissolved":"2018-05-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812651","names":[{"lang":"en","v":"WIDE GAINS LIMITED"},{"lang":"hk","v":"至廣有限公司"}],"company_since":"2002-09-02","company_dissolved":"2009-07-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"812445","names":[{"lang":"en","v":"WORLD TRADING GROUP LIMITED"},{"lang":"hk","v":"五洲貿易行有限公司"}],"company_since":"2002-09-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"812415","names":[{"lang":"en","v":"WPB-HYPERSONIC HONG KONG LIMITED"},{"lang":"hk","v":"丞熙有限公司"}],"company_since":"2002-09-02","company_dissolved":"2010-02-03","company_type_txt":"Private, ltd by shares"},
undefined,
