{"tax_id":"682872","names":[{"lang":"en","v":"CHUN MING AIR-CONDITION ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"駿明冷氣工程有限公司"}],"company_since":"1999-07-21","company_dissolved":"2019-11-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682793","names":[{"lang":"en","v":"CHUNG HING AUTOMATION LIMITED"},{"lang":"hk","v":"中興自動化有限公司"}],"company_since":"1999-07-21","company_dissolved":"2001-01-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683028","names":[{"lang":"en","v":"CITY HEALTHCARE LIMITED (d2001-07-20)"}],"company_since":"1999-07-21","company_dissolved":"2001-07-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682929","names":[{"lang":"en","v":"CITY WORKSHOP CONTRACTING LIMITED"},{"lang":"hk","v":"城工店裝飾有限公司"}],"company_since":"1999-07-21","company_dissolved":"2004-10-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682772","names":[{"lang":"en","v":"COLOSSAL TARGET INVESTMENTS LIMITED"},{"lang":"hk","v":"光泰投資有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682816","names":[{"lang":"en","v":"CREATIVE TECH LIMITED (HK)"},{"lang":"hk","v":"科凌有限公司"}],"company_since":"1999-07-21","company_dissolved":"2018-04-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683000","names":[{"lang":"en","v":"CREATOR WOODEN CRAFT MANUFACTURE LIMITED"},{"lang":"hk","v":"創藝木器禮品製造有限公司"}],"company_since":"1999-07-21","company_dissolved":"2018-01-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682890","names":[{"lang":"en","v":"CRESTWAY ENGINEERING LIMITED"},{"lang":"hk","v":"嘉德工程有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682808","names":[{"lang":"en","v":"CYBERSETTLE.COM. (HONG KONG) LIMITED"}],"company_since":"1999-07-21","company_dissolved":"2007-08-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682966","names":[{"lang":"en","v":"DADI I-SERVICES LIMITED"},{"lang":"hk","v":"大地網絡服務有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682909","names":[{"lang":"en","v":"DADI MEDIA LIMITED"},{"lang":"hk","v":"大地傳播有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682750","names":[{"lang":"en","v":"DANER INTERNATIONAL (HONG KONG) LIMITED"}],"company_since":"1999-07-21","company_dissolved":"2012-08-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683005","names":[{"lang":"en","v":"DELTA ENTERPRISE FAR EAST LIMITED"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683020","names":[{"lang":"en","v":"DIGITAL LIMITED"},{"lang":"hk","v":"數碼有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683029","names":[{"lang":"en","v":"EAST STAR STATIONERY CO. LIMITED"},{"lang":"hk","v":"東星文具有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682811","names":[{"lang":"en","v":"EAST-WEST CAPITAL MARKETS LIMITED"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682775","names":[{"lang":"en","v":"EASTERN JADE INTERNATIONAL LIMITED"},{"lang":"hk","v":"溢翠國際有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682795","names":[{"lang":"en","v":"EHEALTHCAREASIA.COM LIMITED"},{"lang":"hk","v":"亞洲醫療互聯網站有限公司"}],"company_since":"1999-07-21","company_dissolved":"2020-07-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682781","names":[{"lang":"en","v":"ELETTROPLASTICA (HONG KONG) LIMITED"}],"company_since":"1999-07-21","company_dissolved":"2003-05-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682976","names":[{"lang":"en","v":"ENGTECH ENGINEERING LIMITED (d2003-04-04)"},{"lang":"hk","v":"安泰工程顧問有限公司"}],"company_since":"1999-07-21","company_dissolved":"2003-04-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682854","names":[{"lang":"en","v":"ENVIRONMENTALCARE LIMITED"},{"lang":"hk","v":"愛環保有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682937","names":[{"lang":"en","v":"EWINK TRADING LIMITED"},{"lang":"hk","v":"一一貿易有限公司"}],"company_since":"1999-07-21","company_dissolved":"2000-11-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682825","names":[{"lang":"en","v":"EXCEL LINK (HONG KONG) LIMITED"},{"lang":"hk","v":"卓興(香港)有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-12-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682885","names":[{"lang":"en","v":"EXCEL MANAGEMENT LIMITED (HK)"},{"lang":"hk","v":"捷富管理有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682834","names":[{"lang":"en","v":"EXCEL TECH DEVELOPMENT LIMITED"},{"lang":"hk","v":"科卓發展有限公司"}],"company_since":"1999-07-21","company_dissolved":"2013-12-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682867","names":[{"lang":"en","v":"EXCEL WEALTHY INVESTMENT LIMITED"},{"lang":"hk","v":"卓興投資有限公司"}],"company_since":"1999-07-21","company_dissolved":"2013-07-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682835","names":[{"lang":"en","v":"EXCELLENT TECH INVESTMENT LIMITED"},{"lang":"hk","v":"科創投資有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682763","names":[{"lang":"en","v":"EXTRA BILLION PROFITS LIMITED"},{"lang":"hk","v":"逾億有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682995","names":[{"lang":"en","v":"FAST PACE TRADING (HONG KONG) LIMITED"}],"company_since":"1999-07-21","company_dissolved":"2011-02-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682780","names":[{"lang":"en","v":"FEDON (H.K.) LIMITED"}],"company_since":"1999-07-21","company_dissolved":"2002-11-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682913","names":[{"lang":"en","v":"FEE LUN SAFETY INSTRUMENT LIMITED"},{"lang":"hk","v":"飛龍安全儀器有限公司"}],"company_since":"1999-07-21","company_dissolved":"2003-11-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683003","names":[{"lang":"en","v":"FNF CORPORATE SERVICES LIMITED"},{"lang":"hk","v":"正德商業服務有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682943","names":[{"lang":"en","v":"FOO SHING CIVIL ENGINEERING CO., LIMITED"},{"lang":"hk","v":"富成土木工程有限公司"}],"company_since":"1999-07-21","company_dissolved":"2003-04-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682836","names":[{"lang":"en","v":"FOREVER VICTORY INVESTMENT LIMITED (d2009-02-13)"},{"lang":"hk","v":"恒進投資有限公司"}],"company_since":"1999-07-21","company_dissolved":"2009-02-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682990","names":[{"lang":"en","v":"FRONT AGE CONSULTING GROUP (HK) LIMITED"},{"lang":"hk","v":"盈邦顧問集團(香港)有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682979","names":[{"lang":"en","v":"FU YUAN TANG PHARMACEUTICAL (HONG KONG) LIMITED"},{"lang":"hk","v":"扶元堂藥業(香港)有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682953","names":[{"lang":"en","v":"FUSHIDA (H.K) SHOES &amp; PLASTICS CO., LIMITED"},{"lang":"hk","v":"富士達(香港)鞋塑有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682784","names":[{"lang":"en","v":"G.I.L. ART &amp; DESIGN CONSULTANTS (SHANGHAI) LIMITED"}],"company_since":"1999-07-21","company_dissolved":"2000-09-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682991","names":[{"lang":"en","v":"GENERAL WOODS LIMITED"}],"company_since":"1999-07-21","company_dissolved":"2002-06-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683018","names":[{"lang":"en","v":"GLOBAL FOUNDATION LIMITED"},{"lang":"hk","v":"環宇基業有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682778","names":[{"lang":"en","v":"GLORIOUS SILVER ASSETS LIMITED"},{"lang":"hk","v":"銀輝資產有限公司"}],"company_since":"1999-07-21","company_dissolved":"2003-05-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682935","names":[{"lang":"en","v":"GLORY FOUNDATION LIMITED"},{"lang":"hk","v":"宏遠基業有限公司"}],"company_since":"1999-07-21","company_dissolved":"2012-06-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682989","names":[{"lang":"en","v":"GOLD CAPE CO. LIMITED"},{"lang":"hk","v":"金島遊戲機城有限公司"}],"company_since":"1999-07-21","company_dissolved":"2000-10-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682892","names":[{"lang":"en","v":"GOLD CONFORT (HONG KONG) LIMITED"},{"lang":"hk","v":"金藝(香港)有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682896","names":[{"lang":"en","v":"GOLDCHAMP INTERNATIONAL LIMITED"},{"lang":"hk","v":"世昌國際有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682957","names":[{"lang":"en","v":"GOLDEN STAINLESS STEEL CO. LIMITED"},{"lang":"hk","v":"金得五金有限公司"}],"company_since":"1999-07-21","company_dissolved":"2011-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682893","names":[{"lang":"en","v":"GOLDTEX SHOES MANUFACTURE LIMITED"},{"lang":"hk","v":"金濤鞋業有限公司"}],"company_since":"1999-07-21","company_dissolved":"2003-11-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682967","names":[{"lang":"en","v":"GOOD BELL INDUSTRIAL COMPANY LIMITED"},{"lang":"hk","v":"圳滙實業有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682824","names":[{"lang":"en","v":"GRAND PROFIT (HONG KONG) LIMITED (d2011-03-18)"},{"lang":"hk","v":"泛聯(香港)有限公司"}],"company_since":"1999-07-21","company_dissolved":"2011-03-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682856","names":[{"lang":"en","v":"CHUNG SING JITUAN (HONG KONG) LIMITED"},{"lang":"hk","v":"中新集團(香港)有限公司"}],"company_since":"1999-07-21","company_dissolved":"2002-06-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682817","names":[{"lang":"en","v":"GREAT CREATIVE LIMITED (d2006-02-10)"},{"lang":"hk","v":"創浚有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682746","names":[{"lang":"en","v":"GUANG FA ELECTRONICS (H.K.) COMPANY LIMITED"},{"lang":"hk","v":"港發電子(香港)有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-12-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682843","names":[{"lang":"en","v":"GUO KANG SHIPPING LIMITED"},{"lang":"hk","v":"國康船務有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682875","names":[{"lang":"en","v":"GUO WEI SHIPPING LIMITED"},{"lang":"hk","v":"國威船務有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682878","names":[{"lang":"en","v":"HAKUEI REALESTATE COMPANY (HONG KONG) LIMITED"}],"company_since":"1999-07-21","company_dissolved":"2000-12-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682807","names":[{"lang":"en","v":"HARRISON ASSETS LIMITED"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682766","names":[{"lang":"en","v":"HELLOASIA (HK) LIMITED"}],"company_since":"1999-07-21","company_dissolved":"2007-11-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682908","names":[{"lang":"en","v":"DIGITAL ISLAND (HONG KONG), LIMITED"}],"company_since":"1999-07-21","company_dissolved":"2009-12-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682838","names":[{"lang":"en","v":"HO WING KEE ALUMINIUM COPPER IRON LIMITED"},{"lang":"hk","v":"何榮記銅鐵有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683006","names":[{"lang":"en","v":"HOLE-IN-1 CAFE' COMPANY LIMITED"}],"company_since":"1999-07-21","company_dissolved":"2009-01-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682760","names":[{"lang":"en","v":"E-TQCM CONSULTANTS LIMITED"},{"lang":"hk","v":"衡健顧問有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682927","names":[{"lang":"en","v":"HOME'S PARTNER LIMITED"},{"lang":"hk","v":"家之選有限公司"}],"company_since":"1999-07-21","company_dissolved":"2004-06-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682755","names":[{"lang":"en","v":"HONG KONG (NG TUNG TONG) BIO-PHARMACY CO. LIMITED"},{"lang":"hk","v":"香港(五同堂)生物葯業有限公司"}],"company_since":"1999-07-21","company_dissolved":"2018-07-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682996","names":[{"lang":"en","v":"HONG KONG FASHION COSTUME HOLDINGS LIMITED"},{"lang":"hk","v":"香港時尚服飾集團有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682845","names":[{"lang":"en","v":"HONG KONG HAN NI SHI INTERNATIONAL GROUP LIMITED"},{"lang":"hk","v":"香港漠尼仕國際集團有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682994","names":[{"lang":"en","v":"HONG KONG INSTITUTE OF ACCOUNTING STUDIES LIMITED"},{"lang":"hk","v":"香港會計教育協會有限公司"}],"company_since":"1999-07-21","company_dissolved":"2010-01-15","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"682946","names":[{"lang":"en","v":"HONG KONG KAMBERRY ADVERTISING COMPANY LIMITED"},{"lang":"hk","v":"香港金必利廣告有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682739","names":[{"lang":"en","v":"HONG KONG SOUTH SEA DEVELOPMENT LIMITED"},{"lang":"hk","v":"香港南海發展有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682898","names":[{"lang":"en","v":"HONG KONG TRAVEL AGENTS LIMITED"},{"lang":"hk","v":"香港旅行社有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682936","names":[{"lang":"en","v":"HONOR FORTUNE TRADING LIMITED"},{"lang":"hk","v":"富瀚貿易有限公司"}],"company_since":"1999-07-21","company_dissolved":"2000-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682912","names":[{"lang":"en","v":"EON GRADE BUILDING MATERIALS LIMITED"},{"lang":"hk","v":"意高建材有限公司"}],"company_since":"1999-07-21","company_dissolved":"2002-06-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682977","names":[{"lang":"en","v":"HOP HING FOOD TRADING LIMITED"},{"lang":"hk","v":"合興食品貿易有限公司"}],"company_since":"1999-07-21","company_dissolved":"2008-07-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683024","names":[{"lang":"en","v":"I-MAXX LIMITED"}],"company_since":"1999-07-21","company_dissolved":"2009-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682765","names":[{"lang":"en","v":"ILLUSTRIOUS CAREER LIMITED"},{"lang":"hk","v":"益家有限公司"}],"company_since":"1999-07-21","company_dissolved":"2003-02-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682819","names":[{"lang":"en","v":"EAST TECH LIMITED (d2006-12-08)"},{"lang":"hk","v":"英迪有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-12-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682776","names":[{"lang":"en","v":"IMPRESSIVE ACTION HOLDINGS LIMITED"},{"lang":"hk","v":"拓動控股有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682858","names":[{"lang":"en","v":"IN HOUSE (HK) LIMITED"}],"company_since":"1999-07-21","company_dissolved":"2007-11-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"682865","names":[{"lang":"en","v":"EXCELLENT TECH INTERNATIONAL LIMITED"},{"lang":"hk","v":"科卓國際有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682905","names":[{"lang":"en","v":"INCAP INVESTMENT LIMITED"},{"lang":"hk","v":"宏基泰投資有限公司"}],"company_since":"1999-07-21","company_dissolved":"2007-09-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682931","names":[{"lang":"en","v":"INKSANE LIMITED"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"682762","names":[{"lang":"en","v":"EXCLUSIVE OASIS PROPERTIES LIMITED"},{"lang":"hk","v":"綠洲物業有限公司"}],"company_since":"1999-07-21","company_dissolved":"2002-08-23","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682814","names":[{"lang":"en","v":"EXPERT INTERNATIONAL TRADE LIMITED"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682906","names":[{"lang":"en","v":"INVENTEC BESTA (H.K.) CO., LIMITED"},{"lang":"hk","v":"無敵科技(香港)有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-03-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682752","names":[{"lang":"en","v":"ITALY FRANKLY COSTUME (ASIA) DEVELOPMENT LIMITED"},{"lang":"hk","v":"意大利弗朗特服飾(亞洲)發展有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682794","names":[{"lang":"en","v":"F-SECURE (GREATER CHINA) LIMITED"},{"lang":"hk","v":"安防訊基(大中華)有限公司"}],"company_since":"1999-07-21","company_dissolved":"2004-10-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682753","names":[{"lang":"en","v":"ITALY SILKMAN INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"意大利絲可漫國際集團有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682952","names":[{"lang":"en","v":"JETHROUGH DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"飛越發展有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682828","names":[{"lang":"en","v":"JOIN TECH TRADING LIMITED (d2002-08-16)"},{"lang":"hk","v":"滙科貿易有限公司"}],"company_since":"1999-07-21","company_dissolved":"2002-08-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682832","names":[{"lang":"en","v":"JOINT TECH INTERNATIONAL LIMITED"},{"lang":"hk","v":"科創國際有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682956","names":[{"lang":"en","v":"JOINT WIN ENTERPRISE LIMITED"},{"lang":"hk","v":"鏘樺企業有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682887","names":[{"lang":"en","v":"GLOBAL BUSINESS TRANSLATION LIMITED"},{"lang":"hk","v":"環宇翻譯有限公司"}],"company_since":"1999-07-21","company_dissolved":"2004-03-05","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683021","names":[{"lang":"en","v":"K. K. SERVICE COMPANY LIMITED"},{"lang":"hk","v":"威威服務有限公司"}],"company_since":"1999-07-21","company_dissolved":"2002-05-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683007","names":[{"lang":"en","v":"KAM WONG RESTAURANT COMPANY LIMITED"},{"lang":"hk","v":"金旺茶餐廳有限公司"}],"company_since":"1999-07-21","company_dissolved":"2001-02-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682916","names":[{"lang":"en","v":"KEEN YUEN LIMITED"},{"lang":"hk","v":"建遠有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682744","names":[{"lang":"en","v":"KEK INDUSTRIAL LIMITED"},{"lang":"hk","v":"彩翔工業有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682840","names":[{"lang":"en","v":"KIN FUNG TEXTILES INDUSTRIAL LIMITED"},{"lang":"hk","v":"建豐紡織實業有限公司"}],"company_since":"1999-07-21","company_dissolved":"2007-02-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682770","names":[{"lang":"en","v":"GOLD GRANDEUR INVESTMENTS LIMITED"},{"lang":"hk","v":"金頂投資有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682900","names":[{"lang":"en","v":"KING FAME INTERNATIONAL LIMITED (d2006-02-10)"},{"lang":"hk","v":"卓譽國際有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682863","names":[{"lang":"en","v":"GOLD WORLD TRADING LIMITED"},{"lang":"hk","v":"金景貿易有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682899","names":[{"lang":"en","v":"KING PRIDE LIMITED"},{"lang":"hk","v":"京毅有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682986","names":[{"lang":"en","v":"KINGLY MANAGEMENT LIMITED"},{"lang":"hk","v":"金利管理有限公司"}],"company_since":"1999-07-21","company_dissolved":"2017-10-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682769","names":[{"lang":"en","v":"GOLDEN HARP INVESTMENTS LIMITED"},{"lang":"hk","v":"金夏投資有限公司"}],"company_since":"1999-07-21","company_dissolved":"2011-06-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682873","names":[{"lang":"en","v":"KONIC INDUSTRIAL COMPANY LIMITED"},{"lang":"hk","v":"科力工業有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683022","names":[{"lang":"en","v":"LEE CHEONG CONSTRUCTION &amp; BUILDING MATERIALS LIMITED"},{"lang":"hk","v":"利昌工程建材有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682884","names":[{"lang":"en","v":"GRANDLEX TECHNOLOGY LIMITED"},{"lang":"hk","v":"嘉利科技有限公司"}],"company_since":"1999-07-21","company_dissolved":"2001-12-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682853","names":[{"lang":"en","v":"LEZARD DESIGN &amp; CONTRACTING CO., LIMITED"},{"lang":"hk","v":"色譯藝術裝飾有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682969","names":[{"lang":"en","v":"GREAT EPOCH LIMITED"},{"lang":"hk","v":"紀福有限公司"}],"company_since":"1999-07-21","company_dissolved":"2007-11-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682918","names":[{"lang":"en","v":"LUCKY TALENT INVESTMENT LIMITED (d2006-12-08)"},{"lang":"hk","v":"祥傑投資有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-12-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682949","names":[{"lang":"en","v":"MAGICURE LIMITED"},{"lang":"hk","v":"奇康有限公司"}],"company_since":"1999-07-21","company_dissolved":"2008-07-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682868","names":[{"lang":"en","v":"MAN CHEONG MACHINE ELECTRICAL CO., LIMITED"},{"lang":"hk","v":"萬昌機械電器有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683034","names":[{"lang":"en","v":"H.K. TENGJIALI CONSTRUCTION ENGINEERING LIMITED"},{"lang":"hk","v":"香港騰嘉利建築工程有限公司"}],"company_since":"1999-07-21","company_dissolved":"2002-02-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682740","names":[{"lang":"en","v":"MBA BERKELEY BURKE FINANCIAL SERVICES LIMITED"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682941","names":[{"lang":"en","v":"MAPLEDEN CONSULTANCY LIMITED"},{"lang":"hk","v":"湛楓顧問有限公司"}],"company_since":"1999-07-21","company_dissolved":"2014-04-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"682743","names":[{"lang":"en","v":"HEINEMANN B. V. LIMITED"}],"company_since":"1999-07-21","company_dissolved":"2001-01-05","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682745","names":[{"lang":"en","v":"MEDIA CAPITAL LIMITED (HK)"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682847","names":[{"lang":"en","v":"HING WAH ENGINEERING DEVELOPMENT CO LIMITED"},{"lang":"hk","v":"興華工程發展有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683004","names":[{"lang":"en","v":"MILECOM SCIENCE &amp; TECHNOLOGY CO. LIMITED"},{"lang":"hk","v":"香港邁立肯科技有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683008","names":[{"lang":"en","v":"MILLTEK COMPANY SERVICES LIMITED"}],"company_since":"1999-07-21","company_dissolved":"2009-01-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683009","names":[{"lang":"en","v":"MTE INTERNATIONAL LIMITED"},{"lang":"hk","v":"豐盛國際集團有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683001","names":[{"lang":"en","v":"MY PORTFOLIO LIMITED (d2008-04-18)"}],"company_since":"1999-07-21","company_dissolved":"2008-04-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682798","names":[{"lang":"en","v":"NATURE TECHNOLOGY DEVELOPMENT LIMITED"},{"lang":"hk","v":"三川科技拓展有限公司"}],"company_since":"1999-07-21","company_dissolved":"2010-03-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682748","names":[{"lang":"en","v":"NET-TRANS AGENCIES (ASIA) LIMITED"},{"lang":"hk","v":"迅航船務(亞洲)有限公司"}],"company_since":"1999-07-21","company_dissolved":"2016-02-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682963","names":[{"lang":"en","v":"NEW BILLION INVESTMENTS LIMITED"},{"lang":"hk","v":"綽億投資有限公司"}],"company_since":"1999-07-21","company_dissolved":"2016-10-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682813","names":[{"lang":"en","v":"NEW'S DIAMOND CO., LIMITED"},{"lang":"hk","v":"麗鑽鑽石(配托)有限公司"}],"company_since":"1999-07-21","company_dissolved":"2009-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682735","names":[{"lang":"en","v":"NGO KEE (ZEN PACIFIC) CONSTRUCTION COMPANY LIMITED"},{"lang":"hk","v":"鶴記(亞太)營造有限公司"}],"company_since":"1999-07-21","company_dissolved":"2003-01-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682779","names":[{"lang":"en","v":"LIVING LEARNING CULTURE &amp; EDUCATION COMPANY LIMITED"},{"lang":"hk","v":"活學文教有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682948","names":[{"lang":"en","v":"OI TAK LUNG PRINTING EQUIPMENT COMPANY LIMITED"},{"lang":"hk","v":"愛德龍印刷器材有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682768","names":[{"lang":"en","v":"IMMENSE VALUE INVESTMENTS LIMITED"},{"lang":"hk","v":"質量投資有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682855","names":[{"lang":"en","v":"OMICRON electronics Asia Limited"},{"lang":"hk","v":"歐米克朗電子儀器亞洲有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682901","names":[{"lang":"en","v":"ORIENTAL ART MANAGEMENT CONSULTANTS LIMITED"},{"lang":"hk","v":"藝廣顧問有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682879","names":[{"lang":"en","v":"OVERSEAS UNION TRADING COMPANY LIMITED"},{"lang":"hk","v":"海聯太平洋貿易有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"682883","names":[{"lang":"en","v":"JETWELL TECHNOLOGY LIMITED"},{"lang":"hk","v":"溢新科技有限公司"}],"company_since":"1999-07-21","company_dissolved":"2003-04-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682822","names":[{"lang":"en","v":"POLY WIN (ASIA) LIMITED"},{"lang":"hk","v":"寶成(亞洲)有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682742","names":[{"lang":"en","v":"JIE YU CONSTRUCTION (HONG KONG) LIMITED"},{"lang":"hk","v":"集裕建築(香港)有限公司"}],"company_since":"1999-07-21","company_dissolved":"2008-12-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682866","names":[{"lang":"en","v":"POLY WINNER INVESTMENT LIMITED"},{"lang":"hk","v":"寶明投資有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682894","names":[{"lang":"en","v":"POPSKILL ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"玲瓏工程有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682764","names":[{"lang":"en","v":"PRECIOUS ROSE LIMITED (d2002-11-22)"},{"lang":"hk","v":"珍皇有限公司"}],"company_since":"1999-07-21","company_dissolved":"2002-11-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682974","names":[{"lang":"en","v":"JUNCTION PEST CONTROL LIMITED"},{"lang":"hk","v":"卓傑滅蟲有限公司"}],"company_since":"1999-07-21","company_dissolved":"2016-01-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682803","names":[{"lang":"en","v":"PRO-STAMP INTERNATIONAL (H.K.) LIMITED"},{"lang":"hk","v":"采印國際香港有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683016","names":[{"lang":"en","v":"K T AUTO PARTS LIMITED"},{"lang":"hk","v":"啓德汽車零件有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682934","names":[{"lang":"en","v":"PROGRESSIVE FOUNDATION LIMITED"},{"lang":"hk","v":"鴻圖基業有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-12-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682796","names":[{"lang":"en","v":"K-LAND LIMITED (d2003-12-24)"},{"lang":"hk","v":"凱霖有限公司"}],"company_since":"1999-07-21","company_dissolved":"2003-12-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683030","names":[{"lang":"en","v":"PUI SUM PAINTING AND DECORATION LIMITED"},{"lang":"hk","v":"培深油漆裝飾有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682785","names":[{"lang":"en","v":"RECOM INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"瑞科國際發展有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683002","names":[{"lang":"en","v":"RICH CITI INTERNATIONAL LIMITED"},{"lang":"hk","v":"城富國際有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682756","names":[{"lang":"en","v":"RICH FOOD INTERNATIONAL LIMITED"},{"lang":"hk","v":"威富食品國際有限公司"}],"company_since":"1999-07-21","company_dissolved":"2001-05-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682777","names":[{"lang":"en","v":"ROBSON CONSULTANTS LIMITED"},{"lang":"hk","v":"卓臣顧問有限公司"}],"company_since":"1999-07-21","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682839","names":[{"lang":"en","v":"ROYAL VISION INTERNATIONAL LIMITED"},{"lang":"hk","v":"普宏國際有限公司"}],"company_since":"1999-07-21","company_dissolved":"2011-03-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682880","names":[{"lang":"en","v":"S.I.T.C. LIMITED"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682992","names":[{"lang":"en","v":"LE CARRE D'AMONT LIMITED"}],"company_since":"1999-07-21","company_dissolved":"2011-03-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682891","names":[{"lang":"en","v":"S.Y. CHENG LIMITED"}],"company_since":"1999-07-21","company_dissolved":"2002-12-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682789","names":[{"lang":"en","v":"LEMONGROVE LIMITED"}],"company_since":"1999-07-21","company_dissolved":"2018-03-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682786","names":[{"lang":"en","v":"Sai Wan Contracting Limited"},{"lang":"hk","v":"世運工程有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682904","names":[{"lang":"en","v":"LI YANG BROADCASTING &amp; ADVERTISING (HK) LIMITED"},{"lang":"hk","v":"香港李揚傳媒廣告有限公司"}],"company_since":"1999-07-21","company_dissolved":"2010-02-26","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682734","names":[{"lang":"en","v":"Savills Residence Limited"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682915","names":[{"lang":"en","v":"SENSE LIMITED"},{"lang":"hk","v":"仲順有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682925","names":[{"lang":"en","v":"LUCKY SHARP LIMITED"},{"lang":"hk","v":"駿曜實業有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682914","names":[{"lang":"en","v":"MAPICS HONG KONG, LIMITED"}],"company_since":"1999-07-21","company_dissolved":"2007-02-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682971","names":[{"lang":"en","v":"SINO 2000 LIMITED"},{"lang":"hk","v":"中國2000有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682962","names":[{"lang":"en","v":"SINO CHEER ENTERPRISES LIMITED"},{"lang":"hk","v":"彩欣企業有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682921","names":[{"lang":"en","v":"SINO COSMOS INTERNATIONAL LIMITED (d2006-02-10)"},{"lang":"hk","v":"華進國際有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682920","names":[{"lang":"en","v":"SINO SUPREME HOLDINGS LIMITED"},{"lang":"hk","v":"華超集團有限公司"}],"company_since":"1999-07-21","company_dissolved":"2001-12-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683035","names":[{"lang":"en","v":"SIX PLUS (GROUP) COMPANY LIMITED"},{"lang":"hk","v":"六和(集團)有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682829","names":[{"lang":"en","v":"SKY LINK TRADING LIMITED (d2007-01-19)"},{"lang":"hk","v":"天卓貿易有限公司"}],"company_since":"1999-07-21","company_dissolved":"2007-01-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682922","names":[{"lang":"en","v":"MULTIPLEX ASIAN EXPORT LIMITED"}],"company_since":"1999-07-21","company_dissolved":"2001-05-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682848","names":[{"lang":"en","v":"SOUTH CHINA MARINE LIMITED (d2000-09-15)"},{"lang":"hk","v":"南華航運有限公司"}],"company_since":"1999-07-21","company_dissolved":"2000-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682881","names":[{"lang":"en","v":"SPACE RETAILS HOLDINGS LIMITED"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682774","names":[{"lang":"en","v":"SPLENDID TRIUMPH INTERNATIONAL LIMITED"},{"lang":"hk","v":"詩彩國際有限公司"}],"company_since":"1999-07-21","company_dissolved":"2001-05-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682738","names":[{"lang":"en","v":"SPY CONCEPTS LIMITED"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682961","names":[{"lang":"en","v":"STAND UP CORPORATION LIMITED"}],"company_since":"1999-07-21","company_dissolved":"2008-11-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682944","names":[{"lang":"en","v":"MING LEE HANDBAG COMPANY LIMITED"},{"lang":"hk","v":"明利手袋有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682968","names":[{"lang":"en","v":"START ADVERTISING COMPANY LIMITED"},{"lang":"hk","v":"新藝廣告有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682907","names":[{"lang":"en","v":"ORIENTAL ELECTRIC INVESTMENT COMPANY LIMITED"},{"lang":"hk","v":"東方電力投資有限公司"}],"company_since":"1999-07-21","company_dissolved":"2001-11-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683014","names":[{"lang":"en","v":"SUN MICRO MOTOR TECHNOLOGY LIMITED"},{"lang":"hk","v":"新生電機科技有限公司"}],"company_since":"1999-07-21","company_dissolved":"2018-01-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682973","names":[{"lang":"en","v":"SUNSHINE GLOBAL LIMITED (d2009-01-16)"}],"company_since":"1999-07-21","company_dissolved":"2009-01-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682791","names":[{"lang":"en","v":"PILOT ELECTRONIC (HONG KONG) LIMITED"},{"lang":"hk","v":"百樂電子(香港)有限公司"}],"company_since":"1999-07-21","company_dissolved":"2020-05-29","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682983","names":[{"lang":"en","v":"SUNSTAR CONTAINER LINE LIMITED"},{"lang":"hk","v":"信達環球貨運有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682919","names":[{"lang":"en","v":"PLUS LUCKY INTERNATIONAL LIMITED"},{"lang":"hk","v":"祥嘉國際有限公司"}],"company_since":"1999-07-21","company_dissolved":"2019-01-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682831","names":[{"lang":"en","v":"SUPER TECH ENTERPRISES LIMITED"},{"lang":"hk","v":"卓科企業有限公司"}],"company_since":"1999-07-21","company_dissolved":"2005-09-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682730","names":[{"lang":"en","v":"SWALLOW TRADING COMPANY LIMITED (d2003-12-19)"},{"lang":"hk","v":"詩華貿易有限公司"}],"company_since":"1999-07-21","company_dissolved":"2003-12-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682982","names":[{"lang":"en","v":"POLYLION LIMITED (d2010-08-13)"},{"lang":"hk","v":"百利亨有限公司"}],"company_since":"1999-07-21","company_dissolved":"2010-08-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682965","names":[{"lang":"en","v":"TCM SPECIALTY CLINIC LIMITED (THE)"},{"lang":"hk","v":"疑難雜症治療中心有限公司"}],"company_since":"1999-07-21","company_dissolved":"2003-11-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682809","names":[{"lang":"en","v":"TEKA INDUSTRIAL (HK) COMPANY LIMITED"},{"lang":"hk","v":"達嘉實業(香港)有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682850","names":[{"lang":"en","v":"PURELAX LIMITED"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682876","names":[{"lang":"en","v":"TELEUNITED LIMITED"},{"lang":"hk","v":"電裕有限公司"}],"company_since":"1999-07-21","company_dissolved":"2016-11-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"682895","names":[{"lang":"en","v":"REEDS BAKERY CHAIN LIMITED"},{"lang":"hk","v":"蘆葦飽餅廊有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682926","names":[{"lang":"en","v":"TINLAM INTERNATIONAL (HK) COMPANY LIMITED"},{"lang":"hk","v":"田林國際(香港)有限公司"}],"company_since":"1999-07-21","company_dissolved":"2008-12-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682857","names":[{"lang":"en","v":"RHOBA FINANCIAL SERVICES LIMITED"},{"lang":"hk","v":"浩霸理財有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682844","names":[{"lang":"en","v":"TOP FORTUNE FOOD COMPANY LIMITED"},{"lang":"hk","v":"福滿記食品有限公司"}],"company_since":"1999-07-21","company_dissolved":"2002-11-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682837","names":[{"lang":"en","v":"TOP WEALTHY INVESTMENT LIMITED"},{"lang":"hk","v":"富進投資有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682842","names":[{"lang":"en","v":"TOTAL PRODUCTS LIMITED"},{"lang":"hk","v":"滔滔製品有限公司"}],"company_since":"1999-07-21","company_dissolved":"2020-09-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682805","names":[{"lang":"en","v":"TREMENDOUS TREASURE HOLDINGS LIMITED"},{"lang":"hk","v":"多寶控股有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683036","names":[{"lang":"en","v":"ROYAL FAITH TEXTILES (H.K.) COMPANY LIMITED"},{"lang":"hk","v":"億豪紡織品進出口有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-06-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682761","names":[{"lang":"en","v":"TRENDSETTERS MANUFACTURING LIMITED"},{"lang":"hk","v":"儕達貿易有限公司"}],"company_since":"1999-07-21","company_dissolved":"2008-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"682972","names":[{"lang":"en","v":"PARKFIELD HOLDINGS LIMITED (d2004-08-27)"},{"lang":"hk","v":"栢信集團有限公司"}],"company_since":"1999-07-21","company_dissolved":"2004-08-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682790","names":[{"lang":"en","v":"TRES CORONAS LIMITED"}],"company_since":"1999-07-21","company_dissolved":"2002-04-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682874","names":[{"lang":"en","v":"UNION CHANCE GROUP (MANUFACTURING) LIMITED"},{"lang":"hk","v":"齊樟集團(製造)有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682924","names":[{"lang":"en","v":"UNION TREND HOLDINGS LIMITED"},{"lang":"hk","v":"昌聯集團有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682988","names":[{"lang":"en","v":"VESCORNO LIMITED"},{"lang":"hk","v":"維高國際企業有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682731","names":[{"lang":"en","v":"SANITY (ASIA) LIMITED"},{"lang":"hk","v":"信利達(亞洲)有限公司"}],"company_since":"1999-07-21","company_dissolved":"2002-07-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683012","names":[{"lang":"en","v":"WAH TUNG CRANE TRANSPORT COMPANY LIMITED"}],"company_since":"1999-07-21","company_dissolved":"2001-09-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682938","names":[{"lang":"en","v":"WALLET &amp; BELT LIMITED"}],"company_since":"1999-07-21","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"682930","names":[{"lang":"en","v":"SIMCOE (PACIFIC) COMPANY LIMITED"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682860","names":[{"lang":"en","v":"WECH INTERNATIONAL LIMITED"},{"lang":"hk","v":"榮雋國際有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682782","names":[{"lang":"en","v":"WELFORD INVESTMENTS LIMITED (d2001-09-28)"}],"company_since":"1999-07-21","company_dissolved":"2001-09-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682959","names":[{"lang":"en","v":"SIMON LIMITED (d2006-02-10)"},{"lang":"hk","v":"世茂有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682897","names":[{"lang":"en","v":"WELL CENTURY HOLDINGS LIMITED (d2012-03-09)"},{"lang":"hk","v":"世榮集團有限公司"}],"company_since":"1999-07-21","company_dissolved":"2012-03-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682758","names":[{"lang":"en","v":"SINCERE INVESTMENT (HONG KONG) LIMITED"},{"lang":"hk","v":"訊匯投資(香港)有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682754","names":[{"lang":"en","v":"WELLHEAD FAR EAST LIMITED"},{"lang":"hk","v":"鴻圖森遠東有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682902","names":[{"lang":"en","v":"WIN EXPRESS DEVELOPMENT LIMITED (d2005-02-11)"},{"lang":"hk","v":"裕迅發展有限公司"}],"company_since":"1999-07-21","company_dissolved":"2005-02-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682923","names":[{"lang":"en","v":"SINO BASIC ENTERPRISES LIMITED (d2002-07-19)"},{"lang":"hk","v":"華遠企業有限公司"}],"company_since":"1999-07-21","company_dissolved":"2002-07-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682970","names":[{"lang":"en","v":"WIN JUMBO DEVELOPMENT LIMITED"},{"lang":"hk","v":"廣業發展有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682917","names":[{"lang":"en","v":"WIN JUMBO INTERNATIONAL LIMITED (d2000-12-01)"},{"lang":"hk","v":"廣業國際有限公司"}],"company_since":"1999-07-21","company_dissolved":"2000-12-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682958","names":[{"lang":"en","v":"WING CHEUNG ENTERPRISES LIMITED"},{"lang":"hk","v":"永翔企業有限公司"}],"company_since":"1999-07-21","company_dissolved":"2003-03-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683013","names":[{"lang":"en","v":"WEALTHY ART (HONG KONG) ENGINEERING CO. LIMITED"},{"lang":"hk","v":"華利(香港)工程有限公司"}],"company_since":"1999-07-21","company_dissolved":"2003-06-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682759","names":[{"lang":"en","v":"WING KWONG TRADING LIMITED"},{"lang":"hk","v":"榮光貿易有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"682889","names":[{"lang":"en","v":"SKY POWER CONSTRUCTION LIMITED"},{"lang":"hk","v":"力天營造有限公司"}],"company_since":"1999-07-21","company_dissolved":"2015-07-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"682792","names":[{"lang":"en","v":"WISDOM INTERNATIONAL GROUP LIMITED (d2006-02-10)"},{"lang":"hk","v":"匯智國際集團有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683032","names":[{"lang":"en","v":"SOUND INDUSTRIAL LIMITED"},{"lang":"hk","v":"新海實業有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682960","names":[{"lang":"en","v":"WORLD BRIGHT ENGINEERING LIMITED"},{"lang":"hk","v":"兆輝工程有限公司"}],"company_since":"1999-07-21","company_dissolved":"2002-10-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682826","names":[{"lang":"en","v":"ROYAL LEADER HOLDINGS LIMITED"},{"lang":"hk","v":"駿昇集團有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"682903","names":[{"lang":"en","v":"WORLD HONOUR ENTERPRISES LIMITED"},{"lang":"hk","v":"譽永企業有限公司"}],"company_since":"1999-07-21","company_dissolved":"2002-05-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682882","names":[{"lang":"en","v":"SPACE CONCEPT (ASIA) LIMITED"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683019","names":[{"lang":"en","v":"WORLD WIDE IMPORTS (HONG KONG) LIMITED"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682859","names":[{"lang":"en","v":"WINTECH CONSTRUCTION MATERIAL COMPANY LIMITED"},{"lang":"hk","v":"永達水喉建材有限公司"}],"company_since":"1999-07-21","company_dissolved":"2002-02-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682877","names":[{"lang":"en","v":"ZHENGDELI ENTERPRISE (HONG KONG) LIMITED"},{"lang":"hk","v":"正得利企業(香港)有限公司"}],"company_since":"1999-07-21","company_dissolved":"2007-11-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"682806","names":[{"lang":"en","v":"SUN GROWTH HOLDINGS LIMITED"},{"lang":"hk","v":"新高農業(集團)有限公司"}],"company_since":"1999-07-21","company_dissolved":"2007-03-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682827","names":[{"lang":"en","v":"SUPER TECH HOLDINGS LIMITED"},{"lang":"hk","v":"卓科集團有限公司"}],"company_since":"1999-07-21","company_dissolved":"2008-07-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682933","names":[{"lang":"en","v":"SYSTEM DESIGN COMPANY LIMITED"}],"company_since":"1999-07-21","company_dissolved":"2004-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682818","names":[{"lang":"en","v":"TECH FOCUS LIMITED (HK)"},{"lang":"hk","v":"迪成有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682998","names":[{"lang":"en","v":"TIGER ASIA CAPITAL (H.K.) LIMITED"},{"lang":"hk","v":"泰富金融有限公司"}],"company_since":"1999-07-21","company_dissolved":"2006-03-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"682871","names":[{"lang":"en","v":"UNION GROUP ELECTRONIC COMPANY LIMITED"},{"lang":"hk","v":"鴻聯電子有限公司"}],"company_since":"1999-07-21","company_dissolved":"2013-12-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682823","names":[{"lang":"en","v":"WAYSTRONG ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"滙昌建築工程有限公司"}],"company_since":"1999-07-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682800","names":[{"lang":"en","v":"WING LEE INTERNATIONAL (H.K.) FUND UNION LIMITED"},{"lang":"hk","v":"榮利國際(香港)基金會有限公司"}],"company_since":"1999-07-21","company_dissolved":"2003-03-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"682984","names":[{"lang":"en","v":"WINTOP UNIVERSAL LIMITED"},{"lang":"hk","v":"永泰環球有限公司"}],"company_since":"1999-07-21","company_dissolved":"2001-05-25","company_type_txt":"Private, ltd by shares"},
