{"tax_id":"683556","names":[{"lang":"en","v":"CHING FAI COMPANY LIMITED"},{"lang":"hk","v":"青暉有限公司"}],"company_since":"1999-07-28","company_dissolved":"2015-12-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683532","names":[{"lang":"en","v":"CHINT HOLDINGS (H.K.) LIMITED"},{"lang":"hk","v":"正泰集團(香港)有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683491","names":[{"lang":"en","v":"CHOI KEE CONSTRUCTION (HK) COMPANY LIMITED"},{"lang":"hk","v":"蔡記建築有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683507","names":[{"lang":"en","v":"CHUNG MEI HANDICRAFT COMPANY LIMITED"},{"lang":"hk","v":"中美工藝有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-02-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683550","names":[{"lang":"en","v":"CITY HOLDINGS LIMITED (HK)"},{"lang":"hk","v":"城市(集團)有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683614","names":[{"lang":"en","v":"CLASSIC JADE HOLDINGS LIMITED"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683582","names":[{"lang":"en","v":"CLASSIFIED EXPERTS LIMITED"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683662","names":[{"lang":"en","v":"CLEAR CHANNEL HONG KONG LIMITED"}],"company_since":"1999-07-28","company_dissolved":"2018-06-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683578","names":[{"lang":"en","v":"CO-OP MANAGEMENT LIMITED"},{"lang":"hk","v":"高岳管理有限公司"}],"company_since":"1999-07-28","company_dissolved":"2011-04-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683666","names":[{"lang":"en","v":"CONCEPT 2000 LIMITED (HK)"},{"lang":"hk","v":"概念2000有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683638","names":[{"lang":"en","v":"CONCORD PLACE LIMITED"},{"lang":"hk","v":"太協有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683663","names":[{"lang":"en","v":"COSUN SYSTEMS LIMITED"},{"lang":"hk","v":"科信系統有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683601","names":[{"lang":"en","v":"CPD ADVANCEMENT CENTRE LIMITED"},{"lang":"hk","v":"高科技進修中心有限公司"}],"company_since":"1999-07-28","company_dissolved":"2012-03-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683565","names":[{"lang":"en","v":"CRANSWICK INTERNATIONAL LIMITED"}],"company_since":"1999-07-28","company_dissolved":"2002-12-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683542","names":[{"lang":"en","v":"CREATIVE EDUCATIONAL CENTRE COMPANY LIMITED"},{"lang":"hk","v":"旭日教育中心有限公司"}],"company_since":"1999-07-28","company_dissolved":"2015-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683561","names":[{"lang":"en","v":"DAO CAO PRODUCTIONS LIMITED"},{"lang":"hk","v":"稻草綜合製作有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683670","names":[{"lang":"en","v":"DRAGON AUTOMOBILES COMPANY LIMITED"},{"lang":"hk","v":"灝龍汽車有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683529","names":[{"lang":"en","v":"DUPONT TEIJIN FILMS CHINA LIMITED"},{"lang":"hk","v":"杜邦帝人薄膜中國有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683752","names":[{"lang":"en","v":"CL ELECTRONIC TECHNOLOGY LIMITED"},{"lang":"hk","v":"日達電子科技有限公司"}],"company_since":"1999-07-28","company_dissolved":"2007-06-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683562","names":[{"lang":"en","v":"EBIS INTERNATIONAL (HONG KONG) LIMITED"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683728","names":[{"lang":"en","v":"ELEGANT CLEANING SERVICES COMPANY LIMITED"},{"lang":"hk","v":"麗雅清潔服務有限公司"}],"company_since":"1999-07-28","company_dissolved":"2010-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683633","names":[{"lang":"en","v":"ET TRADE LIMITED"},{"lang":"hk","v":"交易通有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683707","names":[{"lang":"en","v":"EURO MAC PRINTING EQUIPMENTS LIMITED"},{"lang":"hk","v":"富藝佳印材設備有限公司"}],"company_since":"1999-07-28","company_dissolved":"2011-04-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683519","names":[{"lang":"en","v":"EURONET LIMITED (HK)"}],"company_since":"1999-07-28","company_dissolved":"2017-06-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683658","names":[{"lang":"en","v":"EVER WINNING LIMITED"},{"lang":"hk","v":"朝榮有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683733","names":[{"lang":"en","v":"EVERBRIGHT GROUPS LIMITED"},{"lang":"hk","v":"樂天集團發展有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683603","names":[{"lang":"en","v":"EZ LAND (HK) COMPANY LIMITED"},{"lang":"hk","v":"一新(香港)有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683484","names":[{"lang":"en","v":"FORTUNE SPARK LIMITED (d2003-12-05)"},{"lang":"hk","v":"運耀有限公司"}],"company_since":"1999-07-28","company_dissolved":"2003-12-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683530","names":[{"lang":"en","v":"FRANCE OULIN.SIMAN FASHION HOLDINGS (H.K.) COSTUME LIMITED"},{"lang":"hk","v":"法國澳林‧詩曼洋服集團(香港)服飾有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683732","names":[{"lang":"en","v":"FU LEE DECORATION &amp; ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"富利裝修工程有限公司"}],"company_since":"1999-07-28","company_dissolved":"2011-08-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683496","names":[{"lang":"en","v":"FULL CONCORD HOLDINGS LIMITED"},{"lang":"hk","v":"福匯集團有限公司"}],"company_since":"1999-07-28","company_dissolved":"2007-01-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683518","names":[{"lang":"en","v":"FUTURE AIR CONDITIONER ENGINEERING CO. LIMITED"},{"lang":"hk","v":"富達冷氣工程有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683723","names":[{"lang":"en","v":"GENERAL TOP LIMITED"},{"lang":"hk","v":"偉尊有限公司"}],"company_since":"1999-07-28","company_dissolved":"2019-08-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683552","names":[{"lang":"en","v":"GIANT CITY CONCRETE LIMITED"},{"lang":"hk","v":"城大混凝土有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683699","names":[{"lang":"en","v":"GLO-WIN INTERNATIONAL LIMITED"},{"lang":"hk","v":"高盛環球電子有限公司"}],"company_since":"1999-07-28","company_dissolved":"2009-01-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683600","names":[{"lang":"en","v":"GLOBAL EVENTS MARKETING SERVICES LIMITED"}],"company_since":"1999-07-28","company_dissolved":"2003-10-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683717","names":[{"lang":"en","v":"GLOBAL MANAGEMENT LIMITED (d2006-02-10)"},{"lang":"hk","v":"環球管理有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683648","names":[{"lang":"en","v":"GLOBAL RESOURCES (H.K.) LIMITED"},{"lang":"hk","v":"華信中策(香港)有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683569","names":[{"lang":"en","v":"GOLD DUCK (H.K.) CO. LIMITED"}],"company_since":"1999-07-28","company_dissolved":"2002-09-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683535","names":[{"lang":"en","v":"GOLD EXPRESS DEVELOPMENTS LIMITED"}],"company_since":"1999-07-28","company_dissolved":"2002-10-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683547","names":[{"lang":"en","v":"GOLDEN NET LIMITED (d2007-11-10)"},{"lang":"hk","v":"金聯興業有限公司"}],"company_since":"1999-07-28","company_dissolved":"2007-11-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683617","names":[{"lang":"en","v":"GOLDEN TECH TECHNOLOGY CENTRE LIMITED"}],"company_since":"1999-07-28","company_dissolved":"2002-10-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683486","names":[{"lang":"en","v":"GRANDLY INVESTMENTS LIMITED (d2008-03-07)"},{"lang":"hk","v":"運利投資有限公司"}],"company_since":"1999-07-28","company_dissolved":"2008-03-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683504","names":[{"lang":"en","v":"GREAT CHANCE ENTERPRISES LIMITED (d2005-08-26)"}],"company_since":"1999-07-28","company_dissolved":"2005-08-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683551","names":[{"lang":"en","v":"HANSKOK LIMITED"},{"lang":"hk","v":"漢國興業有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-12-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683697","names":[{"lang":"en","v":"HARISON LIMITED (d2001-03-30)"},{"lang":"hk","v":"協盛有限公司"}],"company_since":"1999-07-28","company_dissolved":"2001-03-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683632","names":[{"lang":"en","v":"HONG KONG HUAN YU LIGHTING LIMITED"},{"lang":"hk","v":"香港環宇燈飾照明有限公司"}],"company_since":"1999-07-28","company_dissolved":"2004-02-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683564","names":[{"lang":"en","v":"HONG KONG ZHEN YUAN INDUSTRIAL LIMITED"},{"lang":"hk","v":"香港震源實業有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683481","names":[{"lang":"en","v":"HONOUR MARINE SAFETY EQUIPMENT COMPANY LIMITED"},{"lang":"hk","v":"海安安全用品有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683747","names":[{"lang":"en","v":"HOP SHING-FARMLINK FRESH DISTRIBUTION LIMITED"},{"lang":"hk","v":"合成-快力克有限公司"}],"company_since":"1999-07-28","company_dissolved":"2003-11-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683722","names":[{"lang":"en","v":"HOST BONUS INTERNATIONAL LIMITED"},{"lang":"hk","v":"浩富國際有限公司"}],"company_since":"1999-07-28","company_dissolved":"2002-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683524","names":[{"lang":"en","v":"HOUR HOUSE IND. LIMITED"},{"lang":"hk","v":"寶高創建實業有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-01-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683516","names":[{"lang":"en","v":"I. LEARNING LIMITED"}],"company_since":"1999-07-28","company_dissolved":"2002-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683528","names":[{"lang":"en","v":"ICONNECTASIA.COM LIMITED"},{"lang":"hk","v":"互聯亞洲有限公司"}],"company_since":"1999-07-28","company_dissolved":"2017-04-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683708","names":[{"lang":"en","v":"ICRIS:0683708 (no English name)"},{"lang":"hk","v":"反斗奇冰有限公司"}],"company_since":"1999-07-28","company_dissolved":"2003-07-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683739","names":[{"lang":"en","v":"INFORMASIA HOLDINGS LIMITED"}],"company_since":"1999-07-28","company_dissolved":"2017-03-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683585","names":[{"lang":"en","v":"ITA BRIGHT PAINTS HK LIMITED"},{"lang":"hk","v":"香港益輝塗料有限公司"}],"company_since":"1999-07-28","company_dissolved":"2001-01-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683536","names":[{"lang":"en","v":"ITEX ASIA LIMITED"}],"company_since":"1999-07-28","company_dissolved":"2017-05-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683641","names":[{"lang":"en","v":"EASE FULL FINANCE LIMITED"},{"lang":"hk","v":"怡豐財務有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683525","names":[{"lang":"en","v":"ITSA HONG KONG LIMITED"}],"company_since":"1999-07-28","company_dissolved":"2016-08-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683667","names":[{"lang":"en","v":"EASY BASE ENTERPRISES LIMITED"},{"lang":"hk","v":"怡興企業有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683497","names":[{"lang":"en","v":"J-TECH CORPORATION LIMITED"},{"lang":"hk","v":"高昇電子有限公司"}],"company_since":"1999-07-28","company_dissolved":"2012-12-05","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683558","names":[{"lang":"en","v":"EDI RESOURCES CENTRE LIMITED"},{"lang":"hk","v":"聯通系統有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683622","names":[{"lang":"en","v":"JAPAN BUSINESS EDUCATION COMPANY LIMITED"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683581","names":[{"lang":"en","v":"COTRONIC INDUSTRIAL MANUFACTORY LIMITED"},{"lang":"hk","v":"群力實業製造有限公司"}],"company_since":"1999-07-28","company_dissolved":"2015-05-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683629","names":[{"lang":"en","v":"JETTA INTERNATIONAL LOGISTIC LIMITED"},{"lang":"hk","v":"捷達國際貨運有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683539","names":[{"lang":"en","v":"JIN RONG DEVELOPMENT LIMITED (d2006-12-08)"},{"lang":"hk","v":"晶鎔發展有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-12-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683580","names":[{"lang":"en","v":"JLG EQUIPMENT SERVICES LIMITED"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683541","names":[{"lang":"en","v":"JONATHAN BAILEY AND LPT LIMITED"}],"company_since":"1999-07-28","company_dissolved":"2007-06-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683651","names":[{"lang":"en","v":"KELLEY PRODUCTION COMPANY LIMITED"},{"lang":"hk","v":"林佩佩演藝製作有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683650","names":[{"lang":"en","v":"FUKONG ELECTRONICS (H.K.) CO., LIMITED"},{"lang":"hk","v":"福岡電話生產(香港)有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683494","names":[{"lang":"en","v":"KENT HOLIDAYS COMPANY LIMITED"},{"lang":"hk","v":"健運假日有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683546","names":[{"lang":"en","v":"KEYDATA (H.K.) COMPANY LIMITED"}],"company_since":"1999-07-28","company_dissolved":"2017-01-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683696","names":[{"lang":"en","v":"KINGSHALL LIMITED (HK)"},{"lang":"hk","v":"景豪有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683584","names":[{"lang":"en","v":"KINGSPINE CONSTRUCTION LIMITED"},{"lang":"hk","v":"正德建築有限公司"}],"company_since":"1999-07-28","company_dissolved":"2004-10-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683615","names":[{"lang":"en","v":"KNIGHTSBRIDGE GROUP LIMITED (d2006-12-15)"}],"company_since":"1999-07-28","company_dissolved":"2006-12-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683572","names":[{"lang":"en","v":"KWOK ON ELECTRONICS LIMITED"},{"lang":"hk","v":"國安電子工程有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683510","names":[{"lang":"en","v":"LAMMEDIA LIMITED"},{"lang":"hk","v":"聯亞傳媒有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683583","names":[{"lang":"en","v":"LEADERSHIP CLUB, LIMITED"},{"lang":"hk","v":"領導動力咨詢有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683720","names":[{"lang":"en","v":"LEGEND RICH ENTERPRISES LIMITED"},{"lang":"hk","v":"利廣企業有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683573","names":[{"lang":"en","v":"LEIANDA COMPANY LIMITED"},{"lang":"hk","v":"雷安達有限公司"}],"company_since":"1999-07-28","company_dissolved":"2002-02-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683727","names":[{"lang":"en","v":"LEO (H.K.) TRADING COMPANY LIMITED"},{"lang":"hk","v":"利安(香港)貿易有限公司"}],"company_since":"1999-07-28","company_dissolved":"2001-11-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683689","names":[{"lang":"en","v":"LESCHACO (HONG KONG) LIMITED"},{"lang":"hk","v":"力運物流有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683623","names":[{"lang":"en","v":"LIAN CHENG ELECTRONIC (H.K.) COMPANY LIMITED"},{"lang":"hk","v":"聯誠電業(香港)有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683613","names":[{"lang":"en","v":"GOLDENSEA TECHNOLOGY LIMITED"},{"lang":"hk","v":"金海科技有限公司"}],"company_since":"1999-07-28","company_dissolved":"2003-12-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683522","names":[{"lang":"en","v":"LING NAM HERBALIST KOON LIMITED"},{"lang":"hk","v":"嶺南中醫館有限公司"}],"company_since":"1999-07-28","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683643","names":[{"lang":"en","v":"LIU HE (HONG KONG) LIMITED"},{"lang":"hk","v":"六合(香港)有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-01-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683544","names":[{"lang":"en","v":"LIVE CONSTRUCTION LIMITED (HK)"},{"lang":"hk","v":"建生建築有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683647","names":[{"lang":"en","v":"GUO YE GOLDEN BRIDGE TECHNOLOGY LIMITED"},{"lang":"hk","v":"國葉金橋科技有限公司"}],"company_since":"1999-07-28","company_dissolved":"2004-01-02","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683680","names":[{"lang":"en","v":"LUCKY RIVER LIMITED (d2009-11-13)"},{"lang":"hk","v":"福河有限公司"}],"company_since":"1999-07-28","company_dissolved":"2009-11-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683687","names":[{"lang":"en","v":"Lumen Technologies Hong Kong Limited"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683724","names":[{"lang":"en","v":"M B HONG KONG LIMITED"}],"company_since":"1999-07-28","company_dissolved":"2017-01-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683602","names":[{"lang":"en","v":"MACAU AND HONG KONG TSE SHAN CHEUNG-LUNG TIN KIT YEE TONG NA CHA FA PAU ASSOCIATION LIMITED"},{"lang":"hk","v":"澳門香港柿山長龍田結義堂哪咤花炮會有限公司"}],"company_since":"1999-07-28","company_dissolved":"2009-11-13","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"683740","names":[{"lang":"en","v":"HARMONY SECURITY SERVICES LIMITED"},{"lang":"hk","v":"家祥警衛及物業管理有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683748","names":[{"lang":"en","v":"MANWOOD LIMITED (HK)"},{"lang":"hk","v":"文活有限公司"}],"company_since":"1999-07-28","company_dissolved":"2019-04-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683598","names":[{"lang":"en","v":"MATRIX ASIA LIMITED (d2001-07-13)"}],"company_since":"1999-07-28","company_dissolved":"2001-07-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683483","names":[{"lang":"en","v":"HONEST TEAM TRADING (H.K.) LIMITED"},{"lang":"hk","v":"誠添貿易(香港)有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683487","names":[{"lang":"en","v":"MAXKIN INTERNATIONAL LIMITED"},{"lang":"hk","v":"萬鈞國際有限公司"}],"company_since":"1999-07-28","company_dissolved":"2019-06-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683592","names":[{"lang":"en","v":"HONG KONG EDUCATION LIMITED (d2008-05-23)"},{"lang":"hk","v":"語林區有限公司"}],"company_since":"1999-07-28","company_dissolved":"2008-05-23","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683493","names":[{"lang":"en","v":"MEDIKIT COMPANY LIMITED"},{"lang":"hk","v":"體驗有限公司"}],"company_since":"1999-07-28","company_dissolved":"2002-10-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683520","names":[{"lang":"en","v":"HONG KONG GODPAPA GIFTS WORKSHOP LIMITED"},{"lang":"hk","v":"香港雙知藝坊有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683644","names":[{"lang":"en","v":"MODERN PROPERTY MANAGEMENT COMPANY LIMITED"},{"lang":"hk","v":"現代物業管理有限公司"}],"company_since":"1999-07-28","company_dissolved":"2019-03-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683577","names":[{"lang":"en","v":"HONG KONG INTERNATIONAL CHINESE MEDICINE OF CHINESE MEDICAL SCIENCE CULTURE LIMITED"},{"lang":"hk","v":"香港國際中醫藥文化有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683706","names":[{"lang":"en","v":"MORPHOSIS CONSULTANTS LIMITED"}],"company_since":"1999-07-28","company_dissolved":"2007-11-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683566","names":[{"lang":"en","v":"GIGAMIND LEARNING CENTRE LIMITED"},{"lang":"hk","v":"激活學習中心有限公司"}],"company_since":"1999-07-28","company_dissolved":"2012-09-07","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683599","names":[{"lang":"en","v":"NAM PO FOOTWEAR LIMITED"},{"lang":"hk","v":"南寶鞋業有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683597","names":[{"lang":"en","v":"NEW WAYS MEDIA NETWORK LIMITED"},{"lang":"hk","v":"新路傳媒網絡有限公司"}],"company_since":"1999-07-28","company_dissolved":"2018-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683718","names":[{"lang":"en","v":"NICEBASE (H.K.) LIMITED"},{"lang":"hk","v":"利栢(香港)有限公司"}],"company_since":"1999-07-28","company_dissolved":"2003-09-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683567","names":[{"lang":"en","v":"NINTAUS ELECTRONICS COMPANY LIMITED"},{"lang":"hk","v":"金正電子有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-01-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683685","names":[{"lang":"en","v":"OCEAN FUTURE ENTERPRISES LIMITED"},{"lang":"hk","v":"海恒企業有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683505","names":[{"lang":"en","v":"OCEAN STAR ASSETS LIMITED"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683635","names":[{"lang":"en","v":"ON HO ELECTRICAL ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"安濠電機工程有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683587","names":[{"lang":"en","v":"ORIENTAL GREEN BIO TECHNOLOGY CO. LIMITED"},{"lang":"hk","v":"東方綠色生物科技有限公司"}],"company_since":"1999-07-28","company_dissolved":"2007-12-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683627","names":[{"lang":"en","v":"MEGA WORKSHOP COMPANY LIMITED"},{"lang":"hk","v":"羡一工作室有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683657","names":[{"lang":"en","v":"ORIENTAL NICE LIMITED (d2016-02-19)"},{"lang":"hk","v":"東怡有限公司"}],"company_since":"1999-07-28","company_dissolved":"2016-02-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683501","names":[{"lang":"en","v":"ORIENTAL TRADING GROUP LIMITED"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683645","names":[{"lang":"en","v":"PERFECT TRANS &amp; TRAVEL SERVICE INC. LIMITED"},{"lang":"hk","v":"完美交通旅遊服務有限公司"}],"company_since":"1999-07-28","company_dissolved":"2001-10-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683678","names":[{"lang":"en","v":"JOYHIGH LOGISTICS LIMITED"},{"lang":"hk","v":"怡高物流有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-01-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683548","names":[{"lang":"en","v":"PERFECT VIEW LIMITED (d2006-02-10)"},{"lang":"hk","v":"銓景有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683509","names":[{"lang":"en","v":"K-TECH DEVICES (HONG KONG) LIMITED"},{"lang":"hk","v":"日本微電科技(香港)有限公司"}],"company_since":"1999-07-28","company_dissolved":"2003-10-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683712","names":[{"lang":"en","v":"GRAND OCEAN INVESTMENTS LIMITED"},{"lang":"hk","v":"弘洋投資有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683649","names":[{"lang":"en","v":"K. MASTER (H.K.) LIMITED"},{"lang":"hk","v":"凱瑪斯特(香港)有限公司"}],"company_since":"1999-07-28","company_dissolved":"2000-12-01","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683478","names":[{"lang":"en","v":"PHYSICS DEVELOPMENT LIMITED"},{"lang":"hk","v":"邦利發展(香港)有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683611","names":[{"lang":"en","v":"POWER NET HOLDINGS LIMITED"},{"lang":"hk","v":"詠聯集團有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683646","names":[{"lang":"en","v":"KALIQUE LIMITED"}],"company_since":"1999-07-28","company_dissolved":"2005-01-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683540","names":[{"lang":"en","v":"POYING COMPANY LIMITED"},{"lang":"hk","v":"保盈行有限公司"}],"company_since":"1999-07-28","company_dissolved":"2003-10-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683653","names":[{"lang":"en","v":"PRE-SCHOOL HABITAT CO. LIMITED"},{"lang":"hk","v":"學之園有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683640","names":[{"lang":"en","v":"PRIME FORCE LIMITED"},{"lang":"hk","v":"弘雄有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683626","names":[{"lang":"en","v":"PRIME TALENT (H.K.) LIMITED"},{"lang":"hk","v":"專業至誠(香港)有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683575","names":[{"lang":"en","v":"REACH WIN (PUBLISHER) LIMITED"},{"lang":"hk","v":"得訊(出版)有限公司"}],"company_since":"1999-07-28","company_dissolved":"2002-01-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683545","names":[{"lang":"en","v":"REALITY EXPRESS (HK) CO. LIMITED"},{"lang":"hk","v":"聯合運輸(香港)有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-12-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683618","names":[{"lang":"en","v":"RECHARGE TECHNOLOGY GROUP LIMITED"},{"lang":"hk","v":"回健寶集團有限公司"}],"company_since":"1999-07-28","company_dissolved":"2002-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683625","names":[{"lang":"en","v":"RED FOX LIMITED"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683616","names":[{"lang":"en","v":"RED RIVER AGENTS LIMITED"}],"company_since":"1999-07-28","company_dissolved":"2017-06-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683681","names":[{"lang":"en","v":"RICH RAINBOW LIMITED (d2009-06-05)"},{"lang":"hk","v":"豐虹有限公司"}],"company_since":"1999-07-28","company_dissolved":"2009-06-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683482","names":[{"lang":"en","v":"ROCKFORD LIMITED (d2016-11-11)"}],"company_since":"1999-07-28","company_dissolved":"2016-11-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683471","names":[{"lang":"en","v":"ROSS BUSINESS INSTITUTE LIMITED (THE)"},{"lang":"hk","v":"樂思商學協會有限公司"}],"company_since":"1999-07-28","company_dissolved":"2012-04-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683621","names":[{"lang":"en","v":"LIOW GU ELECTRONICS INDUSTRY COMPANY LIMITED"},{"lang":"hk","v":"六股電子工業股份有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683473","names":[{"lang":"en","v":"ROYAL GLORY INTERNATIONAL LIMITED"},{"lang":"hk","v":"英輝國際有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683511","names":[{"lang":"en","v":"SCIENCE HEALTH TCM NETWORKS LIMITED"},{"lang":"hk","v":"科健中醫網絡有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683506","names":[{"lang":"en","v":"SEAHORSE ENTERPRISES LIMITED (d2006-02-10)"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683474","names":[{"lang":"en","v":"SEAL PARTNERS (HONG KONG) LIMITED"},{"lang":"hk","v":"宏思財務顧問(香港)有限公司"}],"company_since":"1999-07-28","company_dissolved":"2001-02-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683612","names":[{"lang":"en","v":"MAX SOURCE DEVELOPMENT LIMITED"},{"lang":"hk","v":"源溢發展有限公司"}],"company_since":"1999-07-28","company_dissolved":"2011-04-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683715","names":[{"lang":"en","v":"SHANGHAI AIDI TRADING (H.K.) CO., LIMITED"},{"lang":"hk","v":"旺森(香港)貿易有限公司"}],"company_since":"1999-07-28","company_dissolved":"2002-01-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"683604","names":[{"lang":"en","v":"SHUI FOOK JEWELLERY LIMITED"},{"lang":"hk","v":"瑞福珠寶首飾有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683637","names":[{"lang":"en","v":"SINO ARTS LIMITED (d2006-02-10)"},{"lang":"hk","v":"中藝興業有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683669","names":[{"lang":"en","v":"SINOEURO HOLDINGS LIMITED"},{"lang":"hk","v":"華歐集團有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"683605","names":[{"lang":"en","v":"NATURAL VEGETARIAN CO. LIMITED"},{"lang":"hk","v":"雅竹齋廚有限公司"}],"company_since":"1999-07-28","company_dissolved":"2020-01-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683679","names":[{"lang":"en","v":"SOUTH MACHINERY &amp; EQUIPMENT (HK) CO. LIMITED"},{"lang":"hk","v":"南方機械設備(香港)有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683489","names":[{"lang":"en","v":"STARFISH TRADING H.K. CO. LIMITED"}],"company_since":"1999-07-28","company_dissolved":"2008-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683750","names":[{"lang":"en","v":"NUCLEUS ELECTRONICS (HONG KONG) LIMITED"},{"lang":"hk","v":"核動電子香港有限公司"}],"company_since":"1999-07-28","company_dissolved":"2016-03-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683488","names":[{"lang":"en","v":"STARPRESS HOLDINGS LIMITED"},{"lang":"hk","v":"達比集團有限公司"}],"company_since":"1999-07-28","company_dissolved":"2009-01-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683574","names":[{"lang":"en","v":"SUN CAPITAL DEVELOPMENT LIMITED (d2001-12-21)"},{"lang":"hk","v":"昇晟有限公司"}],"company_since":"1999-07-28","company_dissolved":"2001-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683563","names":[{"lang":"en","v":"SUN WAH FURNITURE &amp; DESIGN LIMITED"},{"lang":"hk","v":"新華傢俬設計有限公司"}],"company_since":"1999-07-28","company_dissolved":"2004-06-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683560","names":[{"lang":"en","v":"SUNRISE IMPORT &amp; EXPORT COMPANY LIMITED"},{"lang":"hk","v":"日昇出入口有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683703","names":[{"lang":"en","v":"SUPERB GREAT LIMITED (d2006-02-10)"},{"lang":"hk","v":"康盛有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683502","names":[{"lang":"en","v":"TELEVERSE INTERNATIONAL LIMITED"},{"lang":"hk","v":"電宇國際有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-01-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683675","names":[{"lang":"en","v":"TEXMART LIMITED"},{"lang":"hk","v":"漢興針織製衣有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"683652","names":[{"lang":"en","v":"ORIENTRIDGE PROPERTY AGENCY LIMITED"},{"lang":"hk","v":"東竣物業代理有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683538","names":[{"lang":"en","v":"THUNDERBOLT HOLDINGS LIMITED"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683498","names":[{"lang":"en","v":"PACIFIC MEDICAL (HONG KONG) COMPANY LIMITED"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683503","names":[{"lang":"en","v":"Pacific Primary Health Care IT Limited"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683475","names":[{"lang":"en","v":"TIMES SHIPPING AGENCY LIMITED"},{"lang":"hk","v":"現代船務代理有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683710","names":[{"lang":"en","v":"TOP TREE LIMITED (HK)"},{"lang":"hk","v":"凌木有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683628","names":[{"lang":"en","v":"TOPS ADVERTISING INTERNATIONAL CO., LIMITED"},{"lang":"hk","v":"冠群廣告國際有限公司"}],"company_since":"1999-07-28","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683620","names":[{"lang":"en","v":"PERKINS COFFEE LIMITED (d2006-02-10)"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683590","names":[{"lang":"en","v":"PERSSONS ELBYRA LIMITED"}],"company_since":"1999-07-28","company_dissolved":"2012-01-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683688","names":[{"lang":"en","v":"TPA SOCIAL SERVICES LIMITED"},{"lang":"hk","v":"敬拜會社會服務有限公司"}],"company_since":"1999-07-28","company_dissolved":"2017-01-13","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"683531","names":[{"lang":"en","v":"TRIDECO ENTERPRISES LIMITED"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683692","names":[{"lang":"en","v":"TRUMP CENTURY LIMITED"},{"lang":"hk","v":"駿成有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-04-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683749","names":[{"lang":"en","v":"PRETTY GOLD LIMITED (d2012-05-04)"},{"lang":"hk","v":"金韻有限公司"}],"company_since":"1999-07-28","company_dissolved":"2012-05-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683557","names":[{"lang":"en","v":"U.N.I. TRANSPORTATION CONSULTANTS LIMITED"},{"lang":"hk","v":"宏泰交通顧問有限公司"}],"company_since":"1999-07-28","company_dissolved":"2003-12-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683586","names":[{"lang":"en","v":"UNDERWOOD DESIGN STUDIO LIMITED"},{"lang":"hk","v":"木下設計有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683631","names":[{"lang":"en","v":"RAC TECHNOLOGY LIMITED"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683660","names":[{"lang":"en","v":"VANESSA BRIG LIMITED"},{"lang":"hk","v":"韻珀姬有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683713","names":[{"lang":"en","v":"VIXION SSP LIMITED"},{"lang":"hk","v":"遠見財策有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683725","names":[{"lang":"en","v":"WATER WAY ENTERPRISES LIMITED"},{"lang":"hk","v":"曄昇有限公司"}],"company_since":"1999-07-28","company_dissolved":"2003-11-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"683555","names":[{"lang":"en","v":"ROXYTRONIC INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"洛仕創力國際有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683485","names":[{"lang":"en","v":"WIN FORTUNE INDUSTRIAL LIMITED (d2001-07-20)"},{"lang":"hk","v":"運亨實業有限公司"}],"company_since":"1999-07-28","company_dissolved":"2001-07-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683655","names":[{"lang":"en","v":"WING KEI STRUCTURAL METALWORKS COMPANY LIMITED"},{"lang":"hk","v":"永基金屬結構工程有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683579","names":[{"lang":"en","v":"SEYI (H.K.) LIMITED"},{"lang":"hk","v":"協易(香港)有限公司"}],"company_since":"1999-07-28","company_dissolved":"2004-01-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683636","names":[{"lang":"en","v":"WISE ACTIVE LIMITED (d2006-02-10)"},{"lang":"hk","v":"穎聯有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683672","names":[{"lang":"en","v":"XINKER ELECTRONIC COMPANY LIMITED"},{"lang":"hk","v":"新科電子科技有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"683751","names":[{"lang":"en","v":"YORK FINE INTERNATIONAL LIMITED"},{"lang":"hk","v":"旭輝國際有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683513","names":[{"lang":"en","v":"ZHANG GUANG 101 GROUP COMPANY LIMITED"},{"lang":"hk","v":"章光101集團有限公司"}],"company_since":"1999-07-28","company_dissolved":"2011-05-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"683607","names":[{"lang":"en","v":"STARMAN LIMITED (HK)"},{"lang":"hk","v":"達文有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683527","names":[{"lang":"en","v":"STP HOLDING, L.L.C. LIMITED"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683490","names":[{"lang":"en","v":"TIAN CHENG (H.K.) INDUSTRIES CO., LIMITED"},{"lang":"hk","v":"香港添誠實業有限公司"}],"company_since":"1999-07-28","company_dissolved":"2002-12-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683543","names":[{"lang":"en","v":"TL2 (H.K.) LIMITED"}],"company_since":"1999-07-28","company_dissolved":"2006-02-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683523","names":[{"lang":"en","v":"TOWADA NATURAL HEALTH FOOD COMPANY LIMITED"},{"lang":"hk","v":"十和田天然健康食品有限公司"}],"company_since":"1999-07-28","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683515","names":[{"lang":"en","v":"TRACK CONSULTING (HK) LIMITED"}],"company_since":"1999-07-28","company_dissolved":"2008-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683743","names":[{"lang":"en","v":"TUFTECH FLOORING LIMITED"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"683695","names":[{"lang":"en","v":"UNITED PRECISION MACHINE LIMITED"},{"lang":"hk","v":"聯思精密機器有限公司"}],"company_since":"1999-07-28","company_dissolved":"2017-03-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"683705","names":[{"lang":"en","v":"WELL FACTORY TRADING COMPANY LIMITED"},{"lang":"hk","v":"威成貿易發展有限公司"}],"company_since":"1999-07-28","company_dissolved":"2001-12-07","company_type_txt":"Private, ltd by shares"},
{"tax_id":"683521","names":[{"lang":"en","v":"WELL BAND SHIPPING DEVELOPMENT CO., LIMITED"},{"lang":"hk","v":"偉邦航運發展有限公司"}],"company_since":"1999-07-28","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"683719","names":[{"lang":"en","v":"WIN BASIC INVESTMENT LIMITED"},{"lang":"hk","v":"廣基投資有限公司"}],"company_since":"1999-07-28","company_dissolved":"2008-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"683726","names":[{"lang":"en","v":"XI ZHOU ENTERPRISES HONG KONG LIMITED"},{"lang":"hk","v":"西洲實業香港有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"683559","names":[{"lang":"en","v":"ROVERING INTERNATIONAL LOGISTICS (H.K.) COMPANY LIMITED"},{"lang":"hk","v":"羅福林國際物流(香港)有限公司"}],"company_since":"1999-07-28","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
