{"tax_id":"726934","names":[{"lang":"en","v":"CHE-CHE CONCEPT LIMITED"},{"lang":"hk","v":"畫一創作有限公司"}],"company_since":"2000-08-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"727099","names":[{"lang":"en","v":"Dadi Holdings Limited"},{"lang":"hk","v":"大地控股有限公司"}],"company_since":"2000-08-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"726842","names":[{"lang":"en","v":"CHINA FLOURISH (MZDY) INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"中華興旺國際發展有限公司"}],"company_since":"2000-08-09","company_dissolved":"2011-04-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"726961","names":[{"lang":"en","v":"CHINA FORTUNE TRADING LIMITED (d2006-02-17)"},{"lang":"hk","v":"祥華貿易有限公司"}],"company_since":"2000-08-09","company_dissolved":"2006-02-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"726902","names":[{"lang":"en","v":"DELTA ENTERPRISES COMPANY LIMITED"},{"lang":"hk","v":"遠達企業有限公司"}],"company_since":"2000-08-09","company_dissolved":"2007-03-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"727011","names":[{"lang":"en","v":"DIGITAL CASTING COMPANY LIMITED"},{"lang":"hk","v":"藝能資庫有限公司"}],"company_since":"2000-08-09","company_dissolved":"2004-01-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"727002","names":[{"lang":"en","v":"CITY LOGISTICS LIMITED"},{"lang":"hk","v":"城市物流管理有限公司"}],"company_since":"2000-08-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"726997","names":[{"lang":"en","v":"Digital SMATV and Security System Association (DSSA) Limited"},{"lang":"hk","v":"衛星數碼電視及安防系統商會有限公司"}],"company_since":"2000-08-09","company_dissolved":"2016-04-15","company_type_txt":"Ltd by guarantee"},
undefined,
undefined,
{"tax_id":"727133","names":[{"lang":"en","v":"DIGITAL WINNER LIMITED (d2003-06-20)"},{"lang":"hk","v":"科思有限公司"}],"company_since":"2000-08-09","company_dissolved":"2003-06-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"726844","names":[{"lang":"en","v":"COMINT HONG KONG LIMITED"}],"company_since":"2000-08-09","company_dissolved":"2012-10-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"727119","names":[{"lang":"en","v":"DIRECT IMPORT SOLUTION LIMITED"},{"lang":"hk","v":"連全(香港)有限公司"}],"company_since":"2000-08-09","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"726912","names":[{"lang":"en","v":"DOUBLE FORTUNE HONG KONG LIMITED"},{"lang":"hk","v":"富萬香港有限公司"}],"company_since":"2000-08-09","company_dissolved":"2002-09-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"727147","names":[{"lang":"en","v":"E-FILMING LIMITED"},{"lang":"hk","v":"盈藝製作有限公司"}],"company_since":"2000-08-09","company_dissolved":"2003-01-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"726983","names":[{"lang":"en","v":"DYNASTY PACIFIC LIMITED (d2004-12-17)"},{"lang":"hk","v":"豪爵有限公司"}],"company_since":"2000-08-09","company_dissolved":"2004-12-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"726896","names":[{"lang":"en","v":"EARNSON INTERNATIONAL LIMITED"},{"lang":"hk","v":"軒信國際有限公司"}],"company_since":"2000-08-09","company_dissolved":"2006-02-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"726804","names":[{"lang":"en","v":"EAST ASIA INTERNATIONAL TRADING LIMITED (d2003-02-28)"},{"lang":"hk","v":"東亞國際貿易有限公司"}],"company_since":"2000-08-09","company_dissolved":"2003-02-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"726770","names":[{"lang":"en","v":"EASTLINK MARINE SERVICES LIMITED"},{"lang":"hk","v":"東航海事服務有限公司"}],"company_since":"2000-08-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"726806","names":[{"lang":"en","v":"ELEGANT CURTAINS &amp; DECORATION COMPANY LIMITED"},{"lang":"hk","v":"優雅窗簾裝飾有限公司"}],"company_since":"2000-08-09","company_dissolved":"2002-06-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"726777","names":[{"lang":"en","v":"CHINESE NEWTIME LIMITED"},{"lang":"hk","v":"中文新時代有限公司"}],"company_since":"2000-08-09","company_dissolved":"2003-03-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"727063","names":[{"lang":"en","v":"DUDLEY LAWSON INTERNATIONAL LIMITED"},{"lang":"hk","v":"德利迅國際有限公司"}],"company_since":"2000-08-09","company_dissolved":"2009-07-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"727055","names":[{"lang":"en","v":"FLYING COLT LIMITED (d2010-01-08)"},{"lang":"hk","v":"飛駒有限公司"}],"company_since":"2000-08-09","company_dissolved":"2010-01-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"726795","names":[{"lang":"en","v":"GLORY BRILLIANT ENTERPRISE LIMITED"},{"lang":"hk","v":"光揚企業有限公司"}],"company_since":"2000-08-09","company_dissolved":"2002-05-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"726924","names":[{"lang":"en","v":"GLORY SUCCESS HOLDINGS LIMITED (d2003-09-11)"},{"lang":"hk","v":"威成集團有限公司"}],"company_since":"2000-08-09","company_dissolved":"2003-09-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"727049","names":[{"lang":"en","v":"FORTUNE BUILDER (FAR EAST) LIMITED"},{"lang":"hk","v":"時富(遠東)有限公司"}],"company_since":"2000-08-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"726906","names":[{"lang":"en","v":"FORTUNE KEY LIMITED (d2003-05-09)"},{"lang":"hk","v":"福嘉有限公司"}],"company_since":"2000-08-09","company_dissolved":"2003-05-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"726919","names":[{"lang":"en","v":"GOLDEN RISE LIMITED"},{"lang":"hk","v":"鴻彩有限公司"}],"company_since":"2000-08-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"726953","names":[{"lang":"en","v":"GOLD HOPE INVESTMENT MANAGEMENT COMPANY LIMITED"},{"lang":"hk","v":"金旺投資管理有限公司"}],"company_since":"2000-08-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"726835","names":[{"lang":"en","v":"GAEA (HK) Limited"},{"lang":"hk","v":"佳雅(香港)有限公司"}],"company_since":"2000-08-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"726801","names":[{"lang":"en","v":"FULL LOYAL INDUSTRIAL LIMITED"},{"lang":"hk","v":"富煌實業有限公司"}],"company_since":"2000-08-09","company_dissolved":"2019-07-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"726832","names":[{"lang":"en","v":"FUZZYINDEX LIMITED"}],"company_since":"2000-08-09","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"726802","names":[{"lang":"en","v":"FORTUNE BRIGHT INDUSTRIAL LIMITED"},{"lang":"hk","v":"瑞暉實業有限公司"}],"company_since":"2000-08-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"727130","names":[{"lang":"en","v":"GL Group Limited"}],"company_since":"2000-08-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"727062","names":[{"lang":"en","v":"GLOBE PACIFIC LIMITED (d2006-02-17)"},{"lang":"hk","v":"鴻源行有限公司"}],"company_since":"2000-08-09","company_dissolved":"2006-02-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"726880","names":[{"lang":"en","v":"GLOBE WIRELESS (HONG KONG) LIMITED"}],"company_since":"2000-08-09","company_dissolved":"2015-07-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"726796","names":[{"lang":"en","v":"GLORY BRIGHT ENTERPRISE LIMITED"},{"lang":"hk","v":"展佳企業有限公司"}],"company_since":"2000-08-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"726948","names":[{"lang":"en","v":"GUO BANG (HK) ASSET MANAGEMENT LIMITED"},{"lang":"hk","v":"國邦(香港)資產管理有限公司"}],"company_since":"2000-08-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"726949","names":[{"lang":"en","v":"GRACEFUL LIMITED (d2019-08-16)"},{"lang":"hk","v":"適利有限公司"}],"company_since":"2000-08-09","company_dissolved":"2019-08-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"726781","names":[{"lang":"en","v":"HILLGLORY ENTERPRISE LIMITED"},{"lang":"hk","v":"山裕企業有限公司"}],"company_since":"2000-08-09","company_dissolved":"2005-06-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"727079","names":[{"lang":"en","v":"H.K. HONG JI GROUP SHARES LIMITED"},{"lang":"hk","v":"香港鴻吉集團股份有限公司"}],"company_since":"2000-08-09","company_dissolved":"2006-04-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"727016","names":[{"lang":"en","v":"HONG KONG PLEASING BIRD HOLDINGS LIMITED"},{"lang":"hk","v":"香港報喜鳥股份有限公司"}],"company_since":"2000-08-09","company_dissolved":"2006-02-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"727019","names":[{"lang":"en","v":"HONG KONG ENG HUNG TRADING CO., LIMITED"},{"lang":"hk","v":"香港鷹鴻貿易有限公司"}],"company_since":"2000-08-09","company_dissolved":"2006-02-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"727114","names":[{"lang":"en","v":"HONG KONG XINGMA INT'L FASHION LIMITED"},{"lang":"hk","v":"香港星馬國際服飾有限公司"}],"company_since":"2000-08-09","company_dissolved":"2006-02-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"726837","names":[{"lang":"en","v":"HIGH PERFORMANCE CULTURE LIMITED"},{"lang":"hk","v":"優質文化有限公司"}],"company_since":"2000-08-09","company_dissolved":"2008-01-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"726972","names":[{"lang":"en","v":"HONG KONG DENTAL CLINIC LIMITED"},{"lang":"hk","v":"香港牙科中心有限公司"}],"company_since":"2000-08-09","company_dissolved":"2009-01-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"726963","names":[{"lang":"en","v":"HOPSON DEVELOPMENT LIMITED (d2009-02-20)"},{"lang":"hk","v":"浩新發展有限公司"}],"company_since":"2000-08-09","company_dissolved":"2009-02-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"726845","names":[{"lang":"en","v":"I.T.G. INTERNATIONAL LIMITED"},{"lang":"hk","v":"易通科技國際有限公司"}],"company_since":"2000-08-09","company_dissolved":"2003-12-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"727012","names":[{"lang":"en","v":"ICON INTERNATIONAL (ASIA) LIMITED"}],"company_since":"2000-08-09","company_dissolved":"2006-12-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"726959","names":[{"lang":"en","v":"HOMBEST INVESTMENT LIMITED"},{"lang":"hk","v":"雄溢投資有限公司"}],"company_since":"2000-08-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"727095","names":[{"lang":"en","v":"HONEST ABILITY PHARMA LIMITED"},{"lang":"hk","v":"金源藥業有限公司"}],"company_since":"2000-08-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"727008","names":[{"lang":"en","v":"IMPEX LOGISTICS (HK) LIMITED"},{"lang":"hk","v":"港迅物流有限公司"}],"company_since":"2000-08-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"727116","names":[{"lang":"en","v":"HONG KONG CHANG YING TECHNOLOGY LIMITED"},{"lang":"hk","v":"香港長盈科技有限公司"}],"company_since":"2000-08-09","company_dissolved":"2006-02-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"726783","names":[{"lang":"en","v":"INFO-WISE INTERNATIONAL LIMITED"},{"lang":"hk","v":"智訊國際有限公司"}],"company_since":"2000-08-09","company_dissolved":"2004-11-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"727066","names":[{"lang":"en","v":"HONEST LINK (HONG KONG) LIMITED"},{"lang":"hk","v":"誠滙(香港)有限公司"}],"company_since":"2000-08-09","company_dissolved":"2002-05-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"727129","names":[{"lang":"en","v":"JOINT ASIA TRADING LIMITED"},{"lang":"hk","v":"萬亞貿易有限公司"}],"company_since":"2000-08-09","company_dissolved":"2002-12-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"726826","names":[{"lang":"en","v":"JOINT WEALTH INDUSTRIAL LIMITED (d2009-12-18)"},{"lang":"hk","v":"協裕實業有限公司"}],"company_since":"2000-08-09","company_dissolved":"2009-12-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"726782","names":[{"lang":"en","v":"IPES BRENTWOOD LIMITED"}],"company_since":"2000-08-09","company_dissolved":"2012-11-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"726829","names":[{"lang":"en","v":"JOINT PROFIT INDUSTRIAL LIMITED"},{"lang":"hk","v":"利源實業有限公司"}],"company_since":"2000-08-09","company_dissolved":"2006-06-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"726894","names":[{"lang":"en","v":"JIN TONG SERVICES LIMITED"},{"lang":"hk","v":"鎮通清潔有限公司"}],"company_since":"2000-08-09","company_dissolved":"2006-12-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"727118","names":[{"lang":"en","v":"HONG KONG TONG XIN TAI CHINA HONG KONG PROPERTY CONSULTANTS LIMITED"},{"lang":"hk","v":"香港同鑫泰中港物業有限公司"}],"company_since":"2000-08-09","company_dissolved":"2006-02-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"727022","names":[{"lang":"en","v":"LEUNG HONG KEE STONE MILL LIMITED"},{"lang":"hk","v":"梁康記石廠有限公司"}],"company_since":"2000-08-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"726857","names":[{"lang":"en","v":"MACAU MEDIA (HK) CO., LIMITED"},{"lang":"hk","v":"澳衛傳媒(香港)有限公司"}],"company_since":"2000-08-09","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"727105","names":[{"lang":"en","v":"NATIONAL FAMOUS LIMITED"},{"lang":"hk","v":"國忠有限公司"}],"company_since":"2000-08-09","company_dissolved":"2006-02-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"727017","names":[{"lang":"en","v":"MAGGI SEASONING GROUP (HONG KONG) FOOD CO., LIMITED"},{"lang":"hk","v":"美極鮮集團(香港)食品有限公司"}],"company_since":"2000-08-09","company_dissolved":"2010-01-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"726822","names":[{"lang":"en","v":"NEWEAST INTERNATIONAL INVESTMENT HOLDINGS LIMITED"},{"lang":"hk","v":"東新國際投資集團有限公司"}],"company_since":"2000-08-09","company_dissolved":"2006-02-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"727036","names":[{"lang":"en","v":"MAXX IMMUNOTECH LIMITED"},{"lang":"hk","v":"曼盛免疫技術有限公司"}],"company_since":"2000-08-09","company_dissolved":"2011-04-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"726850","names":[{"lang":"en","v":"NEWAVE (HONG KONG) LIMITED"}],"company_since":"2000-08-09","company_dissolved":"2012-09-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"727043","names":[{"lang":"en","v":"LEGEND BUILD INTERNATIONAL LIMITED"},{"lang":"hk","v":"佳賓國際有限公司"}],"company_since":"2000-08-09","company_dissolved":"2003-03-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"726821","names":[{"lang":"en","v":"ORIENT BEST INTERNATIONAL LIMITED"},{"lang":"hk","v":"東麗行國際有限公司"}],"company_since":"2000-08-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"726823","names":[{"lang":"en","v":"MILLION RIVER TRADING LIMITED (d2002-05-03)"},{"lang":"hk","v":"萬江貿易有限公司"}],"company_since":"2000-08-09","company_dissolved":"2002-05-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"727069","names":[{"lang":"en","v":"PACIFIC BASE (H.K.) LIMITED"},{"lang":"hk","v":"駿基(香港)有限公司"}],"company_since":"2000-08-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"726960","names":[{"lang":"en","v":"PERFECT YIELD INVESTMENT LIMITED"},{"lang":"hk","v":"潤旺投資有限公司"}],"company_since":"2000-08-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"726931","names":[{"lang":"en","v":"PLATEAU (H.K.) CO., LIMITED"}],"company_since":"2000-08-09","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"726863","names":[{"lang":"en","v":"MUTUAL GOOD DEVELOPMENT LIMITED"},{"lang":"hk","v":"互信發展有限公司"}],"company_since":"2000-08-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"726914","names":[{"lang":"en","v":"MEDIALINK ENTERPRISES LIMITED"},{"lang":"hk","v":"匯聯企業有限公司"}],"company_since":"2000-08-09","company_dissolved":"2006-02-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"726890","names":[{"lang":"en","v":"POWERNET TELECOM LIMITED"},{"lang":"hk","v":"寶訊電信有限公司"}],"company_since":"2000-08-09","company_dissolved":"2015-07-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"726824","names":[{"lang":"en","v":"MILLION CROWN HOLDINGS LIMITED (d2004-08-27)"},{"lang":"hk","v":"百冠集團有限公司"}],"company_since":"2000-08-09","company_dissolved":"2004-08-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"727090","names":[{"lang":"en","v":"PROJECTAIMS LIMITED"},{"lang":"hk","v":"寶智堅思管理咨詢有限公司"}],"company_since":"2000-08-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"726998","names":[{"lang":"en","v":"RACON CAMERA COMPANY LIMITED"},{"lang":"hk","v":"博康相機有限公司"}],"company_since":"2000-08-09","company_dissolved":"2012-04-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"726807","names":[{"lang":"en","v":"PAK TAT ELECTRIC ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"百達電業工程有限公司"}],"company_since":"2000-08-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"727077","names":[{"lang":"en","v":"NEW SCIENTIFIC CHEMICAL ENTERPRISE LIMITED"},{"lang":"hk","v":"新科化工企業有限公司"}],"company_since":"2000-08-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"726870","names":[{"lang":"en","v":"ROLLING STAR INVESTMENT LIMITED"},{"lang":"hk","v":"創寶(國際)投資有限公司"}],"company_since":"2000-08-09","company_dissolved":"2006-02-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"726841","names":[{"lang":"en","v":"SINO TECH MACHINERY (HK) LIMITED"},{"lang":"hk","v":"東泰機械工業(香港)有限公司"}],"company_since":"2000-08-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"726905","names":[{"lang":"en","v":"SINOLINK CORPORATION LIMITED"},{"lang":"hk","v":"中凌有限公司"}],"company_since":"2000-08-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"727082","names":[{"lang":"en","v":"SMARTRADE TECHNOLOGY (H.K.) LIMITED"},{"lang":"hk","v":"精貿科技(香港)有限公司"}],"company_since":"2000-08-09","company_dissolved":"2007-03-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"727039","names":[{"lang":"en","v":"SOLVE PORT INTEGRATION LIMITED"},{"lang":"hk","v":"科拓(系統)有限公司"}],"company_since":"2000-08-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"726774","names":[{"lang":"en","v":"ROYAL TRUTH TRAVEL LIMITED"},{"lang":"hk","v":"建中世紀旅運有限公司"}],"company_since":"2000-08-09","company_dissolved":"2006-12-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"726920","names":[{"lang":"en","v":"SPORTS CORP LIMITED"}],"company_since":"2000-08-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"727091","names":[{"lang":"en","v":"RUSIFEN GARMENTS INTERNATIONAL LIMITED"},{"lang":"hk","v":"汝斯芬國際服飾有限公司"}],"company_since":"2000-08-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"726962","names":[{"lang":"en","v":"SUNRAYS DEVELOPMENT LIMITED"},{"lang":"hk","v":"新光發展有限公司"}],"company_since":"2000-08-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"726925","names":[{"lang":"en","v":"SUPER HARBOUR DEVELOPMENT LIMITED (d2006-02-17)"},{"lang":"hk","v":"順港發展有限公司"}],"company_since":"2000-08-09","company_dissolved":"2006-02-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"727009","names":[{"lang":"en","v":"SAN-AI CORPORATION (HONG KONG) LIMITED"},{"lang":"hk","v":"三愛(香港)有限公司"}],"company_since":"2000-08-09","company_dissolved":"2005-10-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"726982","names":[{"lang":"en","v":"SUPERBOSS LIMITED (d2003-04-17)"},{"lang":"hk","v":"紳豪有限公司"}],"company_since":"2000-08-09","company_dissolved":"2003-04-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"726840","names":[{"lang":"en","v":"SYMBOL DESIGN DISPLAY COMPANY LIMITED"},{"lang":"hk","v":"思奧展示有限公司"}],"company_since":"2000-08-09","company_dissolved":"2010-01-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"727032","names":[{"lang":"en","v":"SHENTON INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"神通國際有限公司"}],"company_since":"2000-08-09","company_dissolved":"2018-05-25","company_type_txt":"Private, ltd by shares"},
{"tax_id":"726964","names":[{"lang":"en","v":"TEAMSON TECHNOLOGIES LIMITED"},{"lang":"hk","v":"天信科技有限公司"}],"company_since":"2000-08-09","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"726993","names":[{"lang":"en","v":"SIMPLY HEALTHY LIMITED (d2006-12-22)"},{"lang":"hk","v":"達雅美康有限公司"}],"company_since":"2000-08-09","company_dissolved":"2006-12-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"726817","names":[{"lang":"en","v":"TOP ORIENT INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"東冠國際集團有限公司"}],"company_since":"2000-08-09","company_dissolved":"2012-11-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"726884","names":[{"lang":"en","v":"WING WAH STEEL WORKS, LIMITED"},{"lang":"hk","v":"榮華鉄廠有限公司"}],"company_since":"2000-08-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"726861","names":[{"lang":"en","v":"TUNG YUEN TRANSPORTATION COMPANY LIMITED"},{"lang":"hk","v":"東源貨運有限公司"}],"company_since":"2000-08-09","company_dissolved":"2006-12-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"726812","names":[{"lang":"en","v":"WIDE BRILLIANT TRADING LIMITED"},{"lang":"hk","v":"浩亮貿易有限公司"}],"company_since":"2000-08-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"726868","names":[{"lang":"en","v":"VIZTEL SOLUTIONS (HK) LIMITED"},{"lang":"hk","v":"匯通(亞太)科技有限公司"}],"company_since":"2000-08-09","company_dissolved":"2015-07-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"726808","names":[{"lang":"en","v":"CLEVER VIEW TRADING LIMITED"}],"company_since":"2000-08-09","company_dissolved":"2004-07-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"726968","names":[{"lang":"en","v":"EVERNEW HONG KONG LIMITED"},{"lang":"hk","v":"創恒香港有限公司"}],"company_since":"2000-08-09","company_dissolved":"2015-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"726964","names":[{"lang":"en","v":"TEAMSON TECHNOLOGIES LIMITED"},{"lang":"hk","v":"天信科技有限公司"}],"company_since":"2000-08-09","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"727078","names":[{"lang":"en","v":"LANQIN CLEANING INSTRUMENTS LIMITED"},{"lang":"hk","v":"浪琴潔具有限公司"}],"company_since":"2000-08-09","company_dissolved":"2009-07-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"726829","names":[{"lang":"en","v":"JOINT PROFIT INDUSTRIAL LIMITED"},{"lang":"hk","v":"利源實業有限公司"}],"company_since":"2000-08-09","company_dissolved":"2006-06-23","company_type_txt":"Private, ltd by shares"},
