{"tax_id":"850421","names":[{"lang":"en","v":"CENTURY SKY LIMITED"},{"lang":"hk","v":"榮生有限公司"}],"company_since":"2003-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850526","names":[{"lang":"en","v":"CENTURY WISE DEVELOPMENT LIMITED"},{"lang":"hk","v":"忠威發展有限公司"}],"company_since":"2003-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850563","names":[{"lang":"en","v":"CHAMPION YEAR INTERNATIONAL LIMITED (d2007-06-22)"},{"lang":"hk","v":"駿宜國際有限公司"}],"company_since":"2003-06-20","company_dissolved":"2007-06-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850558","names":[{"lang":"en","v":"CENTRAL CHINA CONSULTANTS LIMITED"},{"lang":"hk","v":"華中顧問有限公司"}],"company_since":"2003-06-20","company_dissolved":"2008-10-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850590","names":[{"lang":"en","v":"CHINA DRAGON ENTERPRISES LIMITED"},{"lang":"hk","v":"中龍企業有限公司"}],"company_since":"2003-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850533","names":[{"lang":"en","v":"CHINA HUAN BO HAI INVESTMENT DEVELOPMENT GROUP LIMITED"},{"lang":"hk","v":"中國環渤海投資開發集團有限公司"}],"company_since":"2003-06-20","company_dissolved":"2011-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850705","names":[{"lang":"en","v":"CHINA SATELLITE COMMUNICATIONS (HONG KONG) CORPORATION LIMITED"},{"lang":"hk","v":"中國衛星通信(香港)有限公司"}],"company_since":"2003-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850528","names":[{"lang":"en","v":"CHINA SUPER CULTURE &amp; ART LIMITED"},{"lang":"hk","v":"華夏翰林文化藝術有限公司"}],"company_since":"2003-06-20","company_dissolved":"2007-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850580","names":[{"lang":"en","v":"CHINESE ESSENCE HEALTH MANAGEMENT LIMITED"},{"lang":"hk","v":"德善健康管理有限公司"}],"company_since":"2003-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850495","names":[{"lang":"en","v":"CHUNG LIP LOGISTICS LIMITED"},{"lang":"hk","v":"中立物流有限公司"}],"company_since":"2003-06-20","company_dissolved":"2008-11-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850521","names":[{"lang":"en","v":"CLASSIC GOLD INVESTMENT LIMITED"},{"lang":"hk","v":"金典投資有限公司"}],"company_since":"2003-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850402","names":[{"lang":"en","v":"CMT CHINAVALUE CAPITAL ADVISORS LIMITED"}],"company_since":"2003-06-20","company_dissolved":"2013-10-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850498","names":[{"lang":"en","v":"CRESCENT PETROLEUM LIMITED"}],"company_since":"2003-06-20","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850582","names":[{"lang":"en","v":"CT SECRETARIAL SERVICES CO., LIMITED"},{"lang":"hk","v":"智達秘書服務有限公司"}],"company_since":"2003-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850716","names":[{"lang":"en","v":"D F J COMPANY LIMITED"},{"lang":"hk","v":"三俊有限公司"}],"company_since":"2003-06-20","company_dissolved":"2015-10-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850437","names":[{"lang":"en","v":"CHINA BEAUTY &amp; COSMETICS LIMITED"},{"lang":"hk","v":"中國美容化妝品有限公司"}],"company_since":"2003-06-20","company_dissolved":"2010-10-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850718","names":[{"lang":"en","v":"DAYAN INTERNATIONAL COLLECTION LIMITED"},{"lang":"hk","v":"大洋國際收藏品有限公司"}],"company_since":"2003-06-20","company_dissolved":"2007-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850575","names":[{"lang":"en","v":"DELLOGS ENGINEERING LIMITED"},{"lang":"hk","v":"德勵工程有限公司"}],"company_since":"2003-06-20","company_dissolved":"2011-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850585","names":[{"lang":"en","v":"CHINA FORTUNE LIMITED"},{"lang":"hk","v":"富利勤(中國)有限公司"}],"company_since":"2003-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850401","names":[{"lang":"en","v":"DION GLOBAL SOLUTIONS (HK) LIMITED"}],"company_since":"2003-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850603","names":[{"lang":"en","v":"DREAM LINK LIMITED"},{"lang":"hk","v":"捷領環球有限公司"}],"company_since":"2003-06-20","company_dissolved":"2013-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850637","names":[{"lang":"en","v":"DREAMAZZ LIMITED"}],"company_since":"2003-06-20","company_dissolved":"2010-07-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850536","names":[{"lang":"en","v":"CHINA SUN DEVELOPMENT LIMITED (d2013-09-13)"},{"lang":"hk","v":"中信發展有限公司"}],"company_since":"2003-06-20","company_dissolved":"2013-09-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850494","names":[{"lang":"en","v":"DUEWIN INTERNATIONAL LIMITED"},{"lang":"hk","v":"德蘊國際有限公司"}],"company_since":"2003-06-20","company_dissolved":"2017-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850435","names":[{"lang":"en","v":"E-BRIGHT GREETING CARDS &amp; PAPER PRODUCTS CO. LIMITED"},{"lang":"hk","v":"日月明賀咭紙品有限公司"}],"company_since":"2003-06-20","company_dissolved":"2010-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850715","names":[{"lang":"en","v":"E.D.M. EUROPEAN DIRECT MARKETING LIMITED"}],"company_since":"2003-06-20","company_dissolved":"2008-11-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850571","names":[{"lang":"en","v":"CHINESE MEDICINE INFORMATICS (HK) LIMITED"},{"lang":"hk","v":"香港中醫藥信息有限公司"}],"company_since":"2003-06-20","company_dissolved":"2019-03-29","company_type_txt":"Private, ltd by shares"},
{"tax_id":"850497","names":[{"lang":"en","v":"E.W.I. INDUSTRIAL LIMITED"},{"lang":"hk","v":"東成國際實業有限公司"}],"company_since":"2003-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850453","names":[{"lang":"en","v":"CITY SENSE PROJECTS LIMITED"},{"lang":"hk","v":"卓兆設計工程有限公司"}],"company_since":"2003-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"850660","names":[{"lang":"en","v":"EASTERN SHIPPING (HK) COMPANY LIMITED"},{"lang":"hk","v":"東方船務有限公司"}],"company_since":"2003-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850661","names":[{"lang":"en","v":"EASTKINGDOM GANCHINTEA LIMITED"},{"lang":"hk","v":"東宏企業甘青茶有限公司"}],"company_since":"2003-06-20","company_dissolved":"2009-11-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850499","names":[{"lang":"en","v":"CONCORD ALLIANCE INVESTMENT LIMITED"}],"company_since":"2003-06-20","company_dissolved":"2007-11-23","company_type_txt":"Private, ltd by shares"},
{"tax_id":"850446","names":[{"lang":"en","v":"ELEGANCY INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"楚格國際有限公司"}],"company_since":"2003-06-20","company_dissolved":"2011-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850600","names":[{"lang":"en","v":"ENTRANCE (ASIA) LIMITED"},{"lang":"hk","v":"安進(亞洲)有限公司"}],"company_since":"2003-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850471","names":[{"lang":"en","v":"ETERNAL INDUSTRIES LIMITED"},{"lang":"hk","v":"恒光實業有限公司"}],"company_since":"2003-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850474","names":[{"lang":"en","v":"CROWN INDUSTRIES LIMITED (d2010-09-10)"},{"lang":"hk","v":"廣泰實業有限公司"}],"company_since":"2003-06-20","company_dissolved":"2010-09-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"850419","names":[{"lang":"en","v":"FAST CHOICE LIMITED (d2007-11-02)"},{"lang":"hk","v":"快智有限公司"}],"company_since":"2003-06-20","company_dissolved":"2007-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"850562","names":[{"lang":"en","v":"FORTUNE CENTURY HOLDINGS LIMITED"},{"lang":"hk","v":"盛豐集團有限公司"}],"company_since":"2003-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850578","names":[{"lang":"en","v":"DELA LIMITED (HK)"}],"company_since":"2003-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850525","names":[{"lang":"en","v":"FORTUNE GALLERY LIMITED (d2004-04-02)"},{"lang":"hk","v":"順嘉有限公司"}],"company_since":"2003-06-20","company_dissolved":"2004-04-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850652","names":[{"lang":"en","v":"DEPT. 8 MERCHANDISE CORPORATION LIMITED"},{"lang":"hk","v":"八部國際有限公司"}],"company_since":"2003-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850690","names":[{"lang":"en","v":"CREATE (H.K.) TRADING CO., LIMITED"},{"lang":"hk","v":"克萊特(香港)貿易有限公司"}],"company_since":"2003-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"850509","names":[{"lang":"en","v":"FORTUNE TIME CORPORATION LIMITED"},{"lang":"hk","v":"豐日有限公司"}],"company_since":"2003-06-20","company_dissolved":"2010-01-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850642","names":[{"lang":"en","v":"DONG AN HONG KONG ENTERPRISE GROUP LIMITED"},{"lang":"hk","v":"東安香港企業集團有限公司"}],"company_since":"2003-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"850512","names":[{"lang":"en","v":"FORTUNE YIELD CORPORATION LIMITED (d2004-04-02)"},{"lang":"hk","v":"順益有限公司"}],"company_since":"2003-06-20","company_dissolved":"2004-04-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850551","names":[{"lang":"en","v":"GIAN SING INDUSTRIAL LIMITED"},{"lang":"hk","v":"建成實業發展有限公司"}],"company_since":"2003-06-20","company_dissolved":"2010-03-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850500","names":[{"lang":"en","v":"EASTERN PROGRESS INVESTMENT LIMITED"}],"company_since":"2003-06-20","company_dissolved":"2008-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850491","names":[{"lang":"en","v":"EASTERN UNION INTERNATIONAL SHIPPING CO., LIMITED"},{"lang":"hk","v":"東聯國際船務有限公司"}],"company_since":"2003-06-20","company_dissolved":"2016-11-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850454","names":[{"lang":"en","v":"GLOBEMARK LIMITED (d2014-02-28)"},{"lang":"hk","v":"鉅貿有限公司"}],"company_since":"2003-06-20","company_dissolved":"2014-02-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"850428","names":[{"lang":"en","v":"GOLD LEGEND LIMITED (d2004-10-15)"},{"lang":"hk","v":"金麗有限公司"}],"company_since":"2003-06-20","company_dissolved":"2004-10-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850595","names":[{"lang":"en","v":"FORD LINK GROUPS LIMITED"},{"lang":"hk","v":"福聯股份有限公司"}],"company_since":"2003-06-20","company_dissolved":"2004-06-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"850559","names":[{"lang":"en","v":"GOLD REACH CORPORATION LIMITED"},{"lang":"hk","v":"晉達有限公司"}],"company_since":"2003-06-20","company_dissolved":"2010-06-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850606","names":[{"lang":"en","v":"FORE ASIA, LIMITED"}],"company_since":"2003-06-20","company_dissolved":"2010-04-16","company_type_txt":"Private, ltd by shares"},
{"tax_id":"850431","names":[{"lang":"en","v":"GOLDEN EASE LIMITED (d2010-08-27)"},{"lang":"hk","v":"君業有限公司"}],"company_since":"2003-06-20","company_dissolved":"2010-08-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850520","names":[{"lang":"en","v":"GOLDEN FIELD HOLDINGS LIMITED"},{"lang":"hk","v":"金發集團有限公司"}],"company_since":"2003-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"850484","names":[{"lang":"en","v":"GOLDSTAR TECHNOLOGY LIMITED (d2007-11-30)"},{"lang":"hk","v":"國誠科技有限公司"}],"company_since":"2003-06-20","company_dissolved":"2007-11-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850632","names":[{"lang":"en","v":"FRENCH TOP INTERNATIONAL DEVELOPMENT CO., LIMITED"},{"lang":"hk","v":"法國頂點國際發展有限公司"}],"company_since":"2003-06-20","company_dissolved":"2011-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850710","names":[{"lang":"en","v":"FUNG TAT DISPENSARY (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"豐達西葯房(香港)有限公司"}],"company_since":"2003-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"850567","names":[{"lang":"en","v":"GUANG HONG INTERNATIONAL (HK) LIMITED"},{"lang":"hk","v":"廣弘國際(香港)有限公司"}],"company_since":"2003-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850670","names":[{"lang":"en","v":"GUANG HUA INTERNATIONAL FINANCE GROUP (HONG KONG) CO. LIMITED"},{"lang":"hk","v":"光華國際金融集團(香港)有限公司"}],"company_since":"2003-06-20","company_dissolved":"2007-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"850523","names":[{"lang":"en","v":"GLORY HARBOUR LIMITED (d2011-04-01)"},{"lang":"hk","v":"采鴻國際發展有限公司"}],"company_since":"2003-06-20","company_dissolved":"2011-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850519","names":[{"lang":"en","v":"GOLDHALL ENGINEERING LIMITED (d2007-11-09)"},{"lang":"hk","v":"金豪工程有限公司"}],"company_since":"2003-06-20","company_dissolved":"2007-11-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850468","names":[{"lang":"en","v":"GOLDLEY INDUSTRIES LIMITED"},{"lang":"hk","v":"金隆實業有限公司"}],"company_since":"2003-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"850599","names":[{"lang":"en","v":"GRAND FAITH INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"能誠國際投資有限公司"}],"company_since":"2003-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"850503","names":[{"lang":"en","v":"HONG KONG HAI NA (INTERNATIONAL) COSMETOLOGY GROUP LIMITED"},{"lang":"hk","v":"香港海納(國際)美容集團有限公司"}],"company_since":"2003-06-20","company_dissolved":"2011-08-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"850681","names":[{"lang":"en","v":"HONG KONG TRIKA ELECTRICAL APPLIANCE INTERNATIONAL LIMITED"},{"lang":"hk","v":"香港川崎電氣國際有限公司"}],"company_since":"2003-06-20","company_dissolved":"2008-11-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850555","names":[{"lang":"en","v":"H.K. DOUPENG (INT'L) DRESS LIMITED"},{"lang":"hk","v":"香港都澎(國際)服飾有限公司"}],"company_since":"2003-06-20","company_dissolved":"2008-11-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"850633","names":[{"lang":"en","v":"HONGKONG HAPPY INTERNATIONAL LIMITED"},{"lang":"hk","v":"香港喜派國際有限公司"}],"company_since":"2003-06-20","company_dissolved":"2015-06-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850598","names":[{"lang":"en","v":"GOLDEN DOLPHINE TECHNOLOGY LIMITED"},{"lang":"hk","v":"金海豚科技有限公司"}],"company_since":"2003-06-20","company_dissolved":"2007-08-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"850689","names":[{"lang":"en","v":"H.K. HUALONG INTERNATIONAL TRADE LIMITED"},{"lang":"hk","v":"香港華隆國際貿易有限公司"}],"company_since":"2003-06-20","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850694","names":[{"lang":"en","v":"HANGZHOU MT.COOL (H.K.) LIMITED"},{"lang":"hk","v":"杭州清凉峰(香港)有限公司"}],"company_since":"2003-06-20","company_dissolved":"2011-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"850530","names":[{"lang":"en","v":"FENTAT INTERNATIONAL LIMITED"},{"lang":"hk","v":"玢達國際有限公司"}],"company_since":"2003-06-20","company_dissolved":"2006-11-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"850668","names":[{"lang":"en","v":"ZHENGDA INTERNATIONAL LIMITED (d2010-06-25)"},{"lang":"hk","v":"正大國際有限公司"}],"company_since":"2003-06-20","company_dissolved":"2010-06-25","company_type_txt":"Private, ltd by shares"},
