{"tax_id":"850094","names":[{"lang":"en","v":"CHARTPOWER FOOD LIMITED"},{"lang":"hk","v":"速力食品有限公司"}],"company_since":"2003-06-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850146","names":[{"lang":"en","v":"CHINA AIDS INFO LIMITED"},{"lang":"hk","v":"中國艾滋病資訊有限公司"}],"company_since":"2003-06-18","company_dissolved":"2014-05-31","company_type_txt":"Ltd by guarantee"},
{"tax_id":"850120","names":[{"lang":"en","v":"CHINA GREAT WALL PUBLISHING CO. LIMITED"},{"lang":"hk","v":"中國長城出版有限公司"}],"company_since":"2003-06-18","company_dissolved":"2009-12-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850314","names":[{"lang":"en","v":"CHINA HONG KONG REN DE PHARMACEUTICAL (GROUP) LIMITED"},{"lang":"hk","v":"中國香港仁德制藥(集團)有限公司"}],"company_since":"2003-06-18","company_dissolved":"2008-11-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850299","names":[{"lang":"en","v":"CHINA INTERNATIONAL BOOKS PUBLISHING LIMITED"},{"lang":"hk","v":"中國國際圖書出版有限公司"}],"company_since":"2003-06-18","company_dissolved":"2013-09-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850157","names":[{"lang":"en","v":"CHINESE TAOISM MEDICAL ASSOCIATION LIMITED"},{"lang":"hk","v":"中華道教傳統醫學研究會有限公司"}],"company_since":"2003-06-18","company_dissolved":"2004-05-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850153","names":[{"lang":"en","v":"CITY DESIGNS &amp; PRODUCTION LIMITED"},{"lang":"hk","v":"城市設計製作有限公司"}],"company_since":"2003-06-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850337","names":[{"lang":"en","v":"CITY EAGLE LIMITED"},{"lang":"hk","v":"城宜有限公司"}],"company_since":"2003-06-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850277","names":[{"lang":"en","v":"COLORLAND MULTIMEDIA LIMITED"},{"lang":"hk","v":"彩菱多媒体有限公司"}],"company_since":"2003-06-18","company_dissolved":"2008-10-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850188","names":[{"lang":"en","v":"CONGEE CITY (H.K.) LIMITED"},{"lang":"hk","v":"粥城(香港)有限公司"}],"company_since":"2003-06-18","company_dissolved":"2007-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850218","names":[{"lang":"en","v":"CONWAY &amp; CONWAY HOLDING LIMITED"}],"company_since":"2003-06-18","company_dissolved":"2007-08-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850265","names":[{"lang":"en","v":"DECEMBER ENGINEERING LIMITED"}],"company_since":"2003-06-18","company_dissolved":"2007-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850195","names":[{"lang":"en","v":"DELUXE WIN TRADING LIMITED"},{"lang":"hk","v":"富詠貿易有限公司"}],"company_since":"2003-06-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850121","names":[{"lang":"en","v":"DIONYSUS CONSULTING AND DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"迪安氏顧問發展有限公司"}],"company_since":"2003-06-18","company_dissolved":"2011-04-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850353","names":[{"lang":"en","v":"DIRECT SOURCING COMPANY LIMITED"}],"company_since":"2003-06-18","company_dissolved":"2015-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850395","names":[{"lang":"en","v":"DM CONSULTANCY LIMITED (d2007-11-02)"},{"lang":"hk","v":"達碼顧問有限公司"}],"company_since":"2003-06-18","company_dissolved":"2007-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850302","names":[{"lang":"en","v":"DMC PRODUCTS LIMITED"}],"company_since":"2003-06-18","company_dissolved":"2017-12-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850190","names":[{"lang":"en","v":"DOTA (INTERNATIONAL) CO. LIMITED"},{"lang":"hk","v":"藤田(國際)有限公司"}],"company_since":"2003-06-18","company_dissolved":"2005-11-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850081","names":[{"lang":"en","v":"EAA STEEL (CHINA) LIMITED"},{"lang":"hk","v":"歐美亞鋼鐵(中國)有限公司"}],"company_since":"2003-06-18","company_dissolved":"2015-07-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850076","names":[{"lang":"en","v":"CHINA TELECOMMUNICATION GROUP CO., LIMITED"},{"lang":"hk","v":"中華通訊集團有限公司"}],"company_since":"2003-06-18","company_dissolved":"2007-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850339","names":[{"lang":"en","v":"CHINA UNION LIMITED (d2006-02-24)"},{"lang":"hk","v":"創盈有限公司"}],"company_since":"2003-06-18","company_dissolved":"2006-02-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850145","names":[{"lang":"en","v":"CHINESE COMMERCIAL &amp; CULTURAL TRAVEL COMPANY LIMITED"},{"lang":"hk","v":"華僑商務文化旅行社有限公司"}],"company_since":"2003-06-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850360","names":[{"lang":"en","v":"ECON MARINE TRADING &amp; ENGINEERING CO., LIMITED"},{"lang":"hk","v":"易康海洋貿易及工程有限公司"}],"company_since":"2003-06-18","company_dissolved":"2012-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850396","names":[{"lang":"en","v":"ELDERLY HOME OF HOLY MOTHER OF WAH SHAN ASSOCIATION LIMITED"},{"lang":"hk","v":"華山聖母護老院有限公司"}],"company_since":"2003-06-18","company_dissolved":"2011-05-06","company_type_txt":"Ltd by guarantee"},
undefined,
undefined,
{"tax_id":"850340","names":[{"lang":"en","v":"Elevate Partners Limited"},{"lang":"hk","v":"達標諮詢有限公司"}],"company_since":"2003-06-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850156","names":[{"lang":"en","v":"EMDOOR INTERNATIONAL CO., LIMITED"},{"lang":"hk","v":"億道國際有限公司"}],"company_since":"2003-06-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850347","names":[{"lang":"en","v":"EQUINOX VENTURES LIMITED (d2007-11-02)"}],"company_since":"2003-06-18","company_dissolved":"2007-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850166","names":[{"lang":"en","v":"EURO MARINE CO. LIMITED"},{"lang":"hk","v":"歐航海運有限公司"}],"company_since":"2003-06-18","company_dissolved":"2018-06-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850074","names":[{"lang":"en","v":"EURO STAR (H.K.) LIMITED"}],"company_since":"2003-06-18","company_dissolved":"2015-07-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"850148","names":[{"lang":"en","v":"DIMENSION CATERING MANAGEMENT LIMITED"},{"lang":"hk","v":"四方飲食管理有限公司"}],"company_since":"2003-06-18","company_dissolved":"2006-12-29","company_type_txt":"Private, ltd by shares"},
{"tax_id":"850291","names":[{"lang":"en","v":"FAMOUS CUISINE LIMITED"},{"lang":"hk","v":"譽廚有限公司"}],"company_since":"2003-06-18","company_dissolved":"2008-12-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850315","names":[{"lang":"en","v":"FASHION CLUB INTERNATIONAL LIMITED"},{"lang":"hk","v":"時裝俱樂部有限公司"}],"company_since":"2003-06-18","company_dissolved":"2010-02-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850181","names":[{"lang":"en","v":"FOODVISION INTERNATIONAL LIMITED"}],"company_since":"2003-06-18","company_dissolved":"2008-04-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850114","names":[{"lang":"en","v":"FORD IN HOLDINGS LIMITED"},{"lang":"hk","v":"福臨集團有限公司"}],"company_since":"2003-06-18","company_dissolved":"2010-01-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850328","names":[{"lang":"en","v":"CHEER HOPE LIMITED"},{"lang":"hk","v":"志凱有限公司"}],"company_since":"2003-06-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850325","names":[{"lang":"en","v":"Forever Best Health International Investment Group Limited"},{"lang":"hk","v":"九健超國際投資集團有限公司"}],"company_since":"2003-06-18","company_dissolved":"2015-07-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850384","names":[{"lang":"en","v":"EAST FAMOUS INDUSTRIES LIMITED"},{"lang":"hk","v":"英輝實業有限公司"}],"company_since":"2003-06-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850343","names":[{"lang":"en","v":"EAST POWER LIMITED"},{"lang":"hk","v":"東寶有限公司"}],"company_since":"2003-06-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"850167","names":[{"lang":"en","v":"FORMOSA PLASTICS LOGISTICS (HONG KONG) CORPORATION LIMITED"},{"lang":"hk","v":"台塑物流(香港)股份有限公司"}],"company_since":"2003-06-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850183","names":[{"lang":"en","v":"FRANCE DIWEILONG FASHION (HONG KONG) INTERNATIONAL LIMITED"},{"lang":"hk","v":"法國狄威龍服飾(香港)國際有限公司"}],"company_since":"2003-06-18","company_dissolved":"2007-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850119","names":[{"lang":"en","v":"EL.AN (EURO-ASIA INTERNATIONAL) COMPANY LIMITED"}],"company_since":"2003-06-18","company_dissolved":"2014-08-29","company_type_txt":"Private, ltd by shares"},
{"tax_id":"850177","names":[{"lang":"en","v":"FRANCE GUTIANWANG INT'L GROUP (HONG KONG) CLOTHING &amp; ACCESSORIES LIMITED"},{"lang":"hk","v":"法國古天王國際集團(香港)服飾有限公司"}],"company_since":"2003-06-18","company_dissolved":"2007-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850205","names":[{"lang":"en","v":"FRANCE LOUIS.BOSS (HK) FASHION CO. LIMITED"},{"lang":"hk","v":"法國路易波士(香港)服飾有限公司"}],"company_since":"2003-06-18","company_dissolved":"2007-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850116","names":[{"lang":"en","v":"FRANCE SAISHANG FASHION (HK) INTERNATIONAL LIMITED"},{"lang":"hk","v":"法國塞尚服飾(香港)國際有限公司"}],"company_since":"2003-06-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850310","names":[{"lang":"en","v":"ELEMENT MODELS LIMITED"}],"company_since":"2003-06-18","company_dissolved":"2009-11-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"850216","names":[{"lang":"en","v":"FRIENDLY SUN LIMITED"},{"lang":"hk","v":"朗曦有限公司"}],"company_since":"2003-06-18","company_dissolved":"2005-09-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850383","names":[{"lang":"en","v":"FULLMARK LIMITED"},{"lang":"hk","v":"豐文有限公司"}],"company_since":"2003-06-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850176","names":[{"lang":"en","v":"EPOCH INTERNATIONAL LIMITED (d2008-11-28)"},{"lang":"hk","v":"泰初國際有限公司"}],"company_since":"2003-06-18","company_dissolved":"2008-11-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"850275","names":[{"lang":"en","v":"GENEWAY INTERNATIONAL TRADING CO., LIMITED"},{"lang":"hk","v":"基慧國際貿易有限公司"}],"company_since":"2003-06-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850259","names":[{"lang":"en","v":"EVENTPEOPLE LIMITED"}],"company_since":"2003-06-18","company_dissolved":"2007-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850137","names":[{"lang":"en","v":"GIANT LINK TRADING LIMITED (d2007-11-02)"},{"lang":"hk","v":"首榮貿易有限公司"}],"company_since":"2003-06-18","company_dissolved":"2007-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850118","names":[{"lang":"en","v":"EVERCHEM PLASTICS LIMITED"},{"lang":"hk","v":"百科塑料有限公司"}],"company_since":"2003-06-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"850133","names":[{"lang":"en","v":"GLOBAL CONSULTANTS (CHINA) LIMITED"},{"lang":"hk","v":"環球顧問(中國)有限公司"}],"company_since":"2003-06-18","company_dissolved":"2007-06-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"850393","names":[{"lang":"en","v":"EZHOME HOLDINGS LIMITED"},{"lang":"hk","v":"易事家集團有限公司"}],"company_since":"2003-06-18","company_dissolved":"2004-09-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850225","names":[{"lang":"en","v":"FAIRY DREAM COSMETIC (H.K.) LIMITED"},{"lang":"hk","v":"麗人夢化妝品(香港)有限公司"}],"company_since":"2003-06-18","company_dissolved":"2007-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850138","names":[{"lang":"en","v":"GRANDTECH TECHNOLOGY LIMITED (d2012-06-15)"},{"lang":"hk","v":"亞柏創科技有限公司"}],"company_since":"2003-06-18","company_dissolved":"2012-06-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850356","names":[{"lang":"en","v":"FORLINK TECHNOLOGIES (HONG KONG) LIMITED"},{"lang":"hk","v":"時力科技(香港)有限公司"}],"company_since":"2003-06-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"850352","names":[{"lang":"en","v":"GROUP BRIGHT DEVELOPMENT LIMITED (d2009-11-13)"}],"company_since":"2003-06-18","company_dissolved":"2009-11-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850103","names":[{"lang":"en","v":"FRANCE LUOYI WEIDEN (HONG KONG) GROUP LIMITED"},{"lang":"hk","v":"法國路易‧威登服飾(香港)集團有限公司"}],"company_since":"2003-06-18","company_dissolved":"2007-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850264","names":[{"lang":"en","v":"FULL MONEY (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"富滿(香港)有限公司"}],"company_since":"2003-06-18","company_dissolved":"2008-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850128","names":[{"lang":"en","v":"H.K. GALAXY INTERNATIONAL TRADING LIMITED"},{"lang":"hk","v":"香港銀河國際商貿有限公司"}],"company_since":"2003-06-18","company_dissolved":"2008-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850351","names":[{"lang":"en","v":"H.K. JINGHAO COMMERCE INFORMATION NETWORK LIMITED"},{"lang":"hk","v":"香港景顥商務信息網絡有限公司"}],"company_since":"2003-06-18","company_dissolved":"2007-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850175","names":[{"lang":"en","v":"H.K. JOYWORM FURNITURE INDUSTRY LIMITED"},{"lang":"hk","v":"香港嘉華家俬實業有限公司"}],"company_since":"2003-06-18","company_dissolved":"2007-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"850089","names":[{"lang":"en","v":"GLOBAL MANUFACTURING LIMITED (HK)"},{"lang":"hk","v":"環球生產有限公司"}],"company_since":"2003-06-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850341","names":[{"lang":"en","v":"GOLD SYSTEM LIMITED (d2009-04-30)"},{"lang":"hk","v":"金兆有限公司"}],"company_since":"2003-06-18","company_dissolved":"2009-04-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"850088","names":[{"lang":"en","v":"HOI LEE ENTERPRISE (CHINA) LIMITED"},{"lang":"hk","v":"凱利企業(中國)有限公司"}],"company_since":"2003-06-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850376","names":[{"lang":"en","v":"HOI SHUN DEVELOPMENT LIMITED"},{"lang":"hk","v":"海信發展有限公司"}],"company_since":"2003-06-18","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850380","names":[{"lang":"en","v":"GREAT ALLIANCE HOLDINGS LIMITED"},{"lang":"hk","v":"滙康集團有限公司"}],"company_since":"2003-06-18","company_dissolved":"2015-12-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"850228","names":[{"lang":"en","v":"GREENRICH RESOURCES (HK) LIMITED"},{"lang":"hk","v":"綠林實業有限公司"}],"company_since":"2003-06-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"850300","names":[{"lang":"en","v":"GREEN LEAF GARDEN RESTAURANT (HOLDINGS) LIMITED"},{"lang":"hk","v":"綠茵花園餐廳(集團)有限公司"}],"company_since":"2003-06-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"850297","names":[{"lang":"en","v":"HONG KONG HENGLI INDUSTRY LIMITED"},{"lang":"hk","v":"香港恒立實業有限公司"}],"company_since":"2003-06-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"850358","names":[{"lang":"en","v":"HONG KONG JIN LIU FU HOLDINGS LIMITED"},{"lang":"hk","v":"香港金六福集團有限公司"}],"company_since":"2003-06-18","company_dissolved":"2007-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"850140","names":[{"lang":"en","v":"HONG KONG PINGYUAN PHARMACEUTICAL PROCESS SYSTEMS LIMITED"},{"lang":"hk","v":"香港平原製藥工藝系統有限公司"}],"company_since":"2003-06-18","company_dissolved":"2017-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"850301","names":[{"lang":"en","v":"HARVEST FRANCO LIMITED"},{"lang":"hk","v":"泓聲國際企業有限公司"}],"company_since":"2003-06-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850390","names":[{"lang":"en","v":"HENCO TECHNOLOGY LIMITED"},{"lang":"hk","v":"恒港科技有限公司"}],"company_since":"2003-06-18","company_dissolved":"2006-05-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850227","names":[{"lang":"en","v":"HONGKONG DEBAO INDUSTRIAL LIMITED"},{"lang":"hk","v":"香港得保實業有限公司"}],"company_since":"2003-06-18","company_dissolved":"2007-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850257","names":[{"lang":"en","v":"HOME CLEANING COMPANY LIMITED (d2007-11-02)"},{"lang":"hk","v":"清潔家有限公司"}],"company_since":"2003-06-18","company_dissolved":"2007-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"850247","names":[{"lang":"en","v":"JARRY CO., LIMITED"},{"lang":"hk","v":"金杰利有限公司"}],"company_since":"2003-06-18","company_dissolved":"2017-02-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"850106","names":[{"lang":"en","v":"HONKA INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"弘嘉國際貿易有限公司"}],"company_since":"2003-06-18","company_dissolved":"2007-11-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"850250","names":[{"lang":"en","v":"SIN TAI CO., LIMITED (d2017-09-29)"},{"lang":"hk","v":"莘泰有限公司"}],"company_since":"2003-06-18","company_dissolved":"2017-09-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"850209","names":[{"lang":"en","v":"MAKSWELL LIMITED"},{"lang":"hk","v":"麥氏和有限公司"}],"company_since":"2003-06-18","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
