{"tax_id":"848780","names":[{"lang":"en","v":"CELESTIN INTEGRATED MICRO-SYSTEM (HONG KONG) LIMITED"},{"lang":"hk","v":"青石集成微系統(香港)有限公司"}],"company_since":"2003-06-05","company_dissolved":"2009-11-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848783","names":[{"lang":"en","v":"CELESTIN LIMITED"},{"lang":"hk","v":"青石有限公司"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848862","names":[{"lang":"en","v":"CENTURY CHAMPION CORPORATION LIMITED"},{"lang":"hk","v":"升昌有限公司"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848966","names":[{"lang":"en","v":"CHAN'S (HK) INDUSTRIAL COMPANY LIMITED"},{"lang":"hk","v":"陳氏(香港)實業有限公司"}],"company_since":"2003-06-05","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"848835","names":[{"lang":"en","v":"CHEERWAY LIMITED"},{"lang":"hk","v":"誌榮有限公司"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"848872","names":[{"lang":"en","v":"CHINA CENTURY TRENDY ENTERPRISE (GROUP) LIMITED"},{"lang":"hk","v":"中國世紀風企業(集團)有限公司"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848729","names":[{"lang":"en","v":"CHINA INTERNATIONAL AIRCRAFT EQUIPMENT LIMITED"},{"lang":"hk","v":"中國國際航空器材有限公司"}],"company_since":"2003-06-05","company_dissolved":"2012-01-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848817","names":[{"lang":"en","v":"CHINA JIAFU INTERNATIONAL GROUP LIMITED"},{"lang":"hk","v":"中國佳福國際集團有限公司"}],"company_since":"2003-06-05","company_dissolved":"2008-11-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848723","names":[{"lang":"en","v":"CHINA PROFESSOR HONG GROUP LIMITED"},{"lang":"hk","v":"中國康師傅集團有限公司"}],"company_since":"2003-06-05","company_dissolved":"2008-07-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848800","names":[{"lang":"en","v":"CHINA WEALTH ENTERPRIZE COMPANY LIMITED"},{"lang":"hk","v":"萬倡國際有限公司"}],"company_since":"2003-06-05","company_dissolved":"2012-09-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848850","names":[{"lang":"en","v":"CHINESE MEDICINE PRACTITIONERS ASSOCIATION OF HONG KONG LIMITED (THE)"},{"lang":"hk","v":"香港執業中醫師協會有限公司"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848765","names":[{"lang":"en","v":"CHINA EASTERN GOLD MINING HOLDING COMPANY LIMITED"},{"lang":"hk","v":"中國東方黃金開發控股有限公司"}],"company_since":"2003-06-05","company_dissolved":"2005-10-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848728","names":[{"lang":"en","v":"CITILINE INVESTMENT LIMITED"},{"lang":"hk","v":"城聯投資有限公司"}],"company_since":"2003-06-05","company_dissolved":"2014-11-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848748","names":[{"lang":"en","v":"CITY FURNITURE LIMITED"},{"lang":"hk","v":"城市家具有限公司"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"848847","names":[{"lang":"en","v":"CHAMPION CHINA ASIA LIMITED"},{"lang":"hk","v":"冠華亞洲有限公司"}],"company_since":"2003-06-05","company_dissolved":"2015-04-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"848990","names":[{"lang":"en","v":"CLIFFORD HUMAN RESOURCES LIMITED"},{"lang":"hk","v":"祈福人力資源有限公司"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"848688","names":[{"lang":"en","v":"CHAPTER LIMITED (HK)"},{"lang":"hk","v":"捷思有限公司"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"848841","names":[{"lang":"en","v":"CSS ENTERPRISES LIMITED"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848958","names":[{"lang":"en","v":"D852 INTERACTIVE (HK) LIMITED"}],"company_since":"2003-06-05","company_dissolved":"2005-02-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"848747","names":[{"lang":"en","v":"CHEN FENG TECHNOLOGY LIMITED"},{"lang":"hk","v":"宸鋒科技有限公司"}],"company_since":"2003-06-05","company_dissolved":"2008-12-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"848959","names":[{"lang":"en","v":"DANIEL HECHTER LIMITED"},{"lang":"hk","v":"丹尼愛特有限公司"}],"company_since":"2003-06-05","company_dissolved":"2007-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"848771","names":[{"lang":"en","v":"CHINA (WWE) INVESTMENT HOLDINGS LIMITED (d2007-10-18)"},{"lang":"hk","v":"中國世婦博投資集團有限公司"}],"company_since":"2003-06-05","company_dissolved":"2007-10-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"848792","names":[{"lang":"en","v":"DB LINK PROPERTY LIMITED"},{"lang":"hk","v":"愉景網絡地產有限公司"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"848661","names":[{"lang":"en","v":"DELIGHTFUL COMPANY LIMITED"},{"lang":"hk","v":"致彩軒有限公司"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848759","names":[{"lang":"en","v":"DICKINSON GARMENT GROUP LIMITED"},{"lang":"hk","v":"德璟泰有限公司"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848842","names":[{"lang":"en","v":"DOUBLE HORSES INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"雙馬國際集團有限公司"}],"company_since":"2003-06-05","company_dissolved":"2007-10-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"848846","names":[{"lang":"en","v":"CHINA WORLDWIDE INTERNATIONAL LIMITED"},{"lang":"hk","v":"華威國際有限公司"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"848931","names":[{"lang":"en","v":"EAGLE INTERNATIONAL TRADING DEVELOPMENT LIMITED"},{"lang":"hk","v":"飛鷹國際貿易發展有限公司"}],"company_since":"2003-06-05","company_dissolved":"2009-10-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"848716","names":[{"lang":"en","v":"CHINA YACHTING COMMUNICATIONS LIMITED"},{"lang":"hk","v":"優游出版有限公司"}],"company_since":"2003-06-05","company_dissolved":"2009-12-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848974","names":[{"lang":"en","v":"CHOICY ELECTRONIC (HONGKONG) LIMITED"},{"lang":"hk","v":"創世紀電子(香港)有限公司"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"848940","names":[{"lang":"en","v":"ENWEI GROUP TRADING COMPANY LIMITED"},{"lang":"hk","v":"恩威集團貿易有限公司"}],"company_since":"2003-06-05","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"848739","names":[{"lang":"en","v":"CLEAR GLASS LIMITED (d2007-09-21)"},{"lang":"hk","v":"透明茶道有限公司"}],"company_since":"2003-06-05","company_dissolved":"2007-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848989","names":[{"lang":"en","v":"CLIFFORD REAL ESTATE AGENCY (HONG KONG) LIMITED"},{"lang":"hk","v":"祈福地產代理(香港)有限公司"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848782","names":[{"lang":"en","v":"COMP MEDIA &amp; ADVERTISING LIMITED"},{"lang":"hk","v":"康悅媒體廣告有限公司"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"848809","names":[{"lang":"en","v":"EXPERTECH CONSULTING LIMITED"}],"company_since":"2003-06-05","company_dissolved":"2008-11-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"848810","names":[{"lang":"en","v":"CONILL PROPERTIES MANAGEMENT CONSULTANT LIMITED"},{"lang":"hk","v":"寶利物業管理顧問有限公司"}],"company_since":"2003-06-05","company_dissolved":"2007-10-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848860","names":[{"lang":"en","v":"CREATIVE ENERGY RESOURCES CO., LIMITED"}],"company_since":"2003-06-05","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"848715","names":[{"lang":"en","v":"FABRICA (HK) COMPANY LIMITED"},{"lang":"hk","v":"布藝坊(香港)有限公司"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848923","names":[{"lang":"en","v":"FAST REACH EXPRESS LIMITED"},{"lang":"hk","v":"速達(中港)快運有限公司"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"848868","names":[{"lang":"en","v":"DAIFAX ENTERPRISES LIMITED"},{"lang":"hk","v":"大發企業有限公司"}],"company_since":"2003-06-05","company_dissolved":"2006-12-29","company_type_txt":"Private, ltd by shares"},
{"tax_id":"848874","names":[{"lang":"en","v":"FIFTIES LIMITED (THE)"},{"lang":"hk","v":"五十年代有限公司"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848806","names":[{"lang":"en","v":"FINANCIAL DYNAMICS LIMITED"}],"company_since":"2003-06-05","company_dissolved":"2015-06-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"848901","names":[{"lang":"en","v":"FLOS INTERNATIONAL LIMITED"},{"lang":"hk","v":"孚朗(國際)有限公司"}],"company_since":"2003-06-05","company_dissolved":"2008-09-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848635","names":[{"lang":"en","v":"FOREST ACE LIMITED (d2006-02-10)"},{"lang":"hk","v":"木林有限公司"}],"company_since":"2003-06-05","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848675","names":[{"lang":"en","v":"FORESTAR LIMITED (d2009-04-30)"},{"lang":"hk","v":"林威有限公司"}],"company_since":"2003-06-05","company_dissolved":"2009-04-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"848875","names":[{"lang":"en","v":"DRAGON LION GARMENT MANUFACTORING LIMITED"},{"lang":"hk","v":"龍獅製衣有限公司"}],"company_since":"2003-06-05","company_dissolved":"2015-06-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"848681","names":[{"lang":"en","v":"FORTRESS CAPITAL LIMITED (d2016-04-15)"},{"lang":"hk","v":"福名有限公司"}],"company_since":"2003-06-05","company_dissolved":"2016-04-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"848906","names":[{"lang":"en","v":"DRAGON PALACE CHINESE RESTAURANT LIMITED"},{"lang":"hk","v":"龍軒酒家有限公司"}],"company_since":"2003-06-05","company_dissolved":"2012-04-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"848699","names":[{"lang":"en","v":"FORTUNE TAKE INTERNATIONAL LIMITED"},{"lang":"hk","v":"行福國際有限公司"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"848887","names":[{"lang":"en","v":"DRAGON SENSE INDUSTRIAL LIMITED"},{"lang":"hk","v":"龍昇實業有限公司"}],"company_since":"2003-06-05","company_dissolved":"2009-10-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"848670","names":[{"lang":"en","v":"FORWARD LIMITED"},{"lang":"hk","v":"智科有限公司"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"848682","names":[{"lang":"en","v":"EASTERN ACCORD LIMITED (d2014-11-21)"},{"lang":"hk","v":"東鑫有限公司"}],"company_since":"2003-06-05","company_dissolved":"2014-11-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"848965","names":[{"lang":"en","v":"FRANCE DUPONT INT'L GARMENT HOLDINGS LIMITED"},{"lang":"hk","v":"法國都彭國際服飾集團有限公司"}],"company_since":"2003-06-05","company_dissolved":"2016-01-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"848794","names":[{"lang":"en","v":"ELLIE FOOTWEAR COMPANY LIMITED"},{"lang":"hk","v":"億利億鞋塑有限公司"}],"company_since":"2003-06-05","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848718","names":[{"lang":"en","v":"EMPIRE ORNAMENT AND JEWELLERY LIMITED"},{"lang":"hk","v":"帝國首飾及珠寶有限公司"}],"company_since":"2003-06-05","company_dissolved":"2007-02-16","company_type_txt":"Private, ltd by shares"},
{"tax_id":"848772","names":[{"lang":"en","v":"CHENGDAFU INTERNATIONAL GROUP LIMITED"},{"lang":"hk","v":"成大福國際集團有限公司"}],"company_since":"2003-06-05","company_dissolved":"2007-10-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"848798","names":[{"lang":"en","v":"FRESH BEAUTY (H.K.) HOLDINGS CO., LIMITED"},{"lang":"hk","v":"新姿麗(香港)國際集團股份責任有限公司"}],"company_since":"2003-06-05","company_dissolved":"2007-10-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848634","names":[{"lang":"en","v":"FUJIMORI INTERNATIONAL CORP. LIMITED"},{"lang":"hk","v":"滕森美企業有限公司"}],"company_since":"2003-06-05","company_dissolved":"2007-10-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"848689","names":[{"lang":"en","v":"FULL GLOBAL LIMITED"},{"lang":"hk","v":"世丰有限公司"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848755","names":[{"lang":"en","v":"EURO - CHINA SOCKS LIMITED"},{"lang":"hk","v":"裕來有限公司"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848938","names":[{"lang":"en","v":"FUNNY TRADING COMPANY LIMITED"},{"lang":"hk","v":"友成貿易有限公司"}],"company_since":"2003-06-05","company_dissolved":"2007-10-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"848873","names":[{"lang":"en","v":"GATEWAY GARMENT LIMITED"},{"lang":"hk","v":"日昇製衣有限公司"}],"company_since":"2003-06-05","company_dissolved":"2010-03-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848653","names":[{"lang":"en","v":"EVER TIME LIMITED (d2010-09-30)"},{"lang":"hk","v":"太恒有限公司"}],"company_since":"2003-06-05","company_dissolved":"2010-09-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"848732","names":[{"lang":"en","v":"GENUTEK ELECTRONICS COMPANY LIMITED"},{"lang":"hk","v":"易發電子有限公司"}],"company_since":"2003-06-05","company_dissolved":"2007-01-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"848724","names":[{"lang":"en","v":"FADTECH LIMITED"},{"lang":"hk","v":"富生科技有限公司"}],"company_since":"2003-06-05","company_dissolved":"2011-01-07","company_type_txt":"Private, ltd by shares"},
{"tax_id":"848643","names":[{"lang":"en","v":"GOAL LAND LIMITED"},{"lang":"hk","v":"訊高有限公司"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848907","names":[{"lang":"en","v":"GOLDBEST INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"金德國際集團有限公司"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"848877","names":[{"lang":"en","v":"FINEVER INTERNATIONAL LIMITED"},{"lang":"hk","v":"惠遠國際(香港)有限公司"}],"company_since":"2003-06-05","company_dissolved":"2008-11-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"848968","names":[{"lang":"en","v":"GOLDEN PROFIT ENTERPRISES (HK) LIMITED"},{"lang":"hk","v":"高科企業(香港)有限公司"}],"company_since":"2003-06-05","company_dissolved":"2019-04-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"848837","names":[{"lang":"en","v":"GOLDEN SHORE LIMITED"},{"lang":"hk","v":"金岸有限公司"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"848665","names":[{"lang":"en","v":"FORTUNE WING LIMITED (d2007-10-18)"},{"lang":"hk","v":"丰榮有限公司"}],"company_since":"2003-06-05","company_dissolved":"2007-10-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848674","names":[{"lang":"en","v":"GOODY LIMITED (HK)"},{"lang":"hk","v":"佳頂有限公司"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848645","names":[{"lang":"en","v":"FOUNTAIN FIELD LIMITED (d2005-02-18)"},{"lang":"hk","v":"泉康有限公司"}],"company_since":"2003-06-05","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"848650","names":[{"lang":"en","v":"GRAND DAY LIMITED (HK)"},{"lang":"hk","v":"宏日有限公司"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"848969","names":[{"lang":"en","v":"GRAND FORTUNE ENGINEERING LIMITED (d2015-06-19)"},{"lang":"hk","v":"宏遠工程有限公司"}],"company_since":"2003-06-05","company_dissolved":"2015-06-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848830","names":[{"lang":"en","v":"GRAND HOST CORPORATION LIMITED"},{"lang":"hk","v":"欣浩有限公司"}],"company_since":"2003-06-05","company_dissolved":"2004-09-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"848669","names":[{"lang":"en","v":"GRANT PROFIT LIMITED (d2009-11-20)"},{"lang":"hk","v":"盈斯有限公司"}],"company_since":"2003-06-05","company_dissolved":"2009-11-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"848802","names":[{"lang":"en","v":"GREENBACK LIMITED"}],"company_since":"2003-06-05","company_dissolved":"2020-04-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"848753","names":[{"lang":"en","v":"FULL LUCK WATCH CASE MANUFACTORY LIMITED"},{"lang":"hk","v":"富力錶製品廠有限公司"}],"company_since":"2003-06-05","company_dissolved":"2005-08-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848917","names":[{"lang":"en","v":"GANG CHENG HARDWARE PRODUCTS LIMITED"},{"lang":"hk","v":"鋼城五金製品有限公司"}],"company_since":"2003-06-05","company_dissolved":"2018-01-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"848871","names":[{"lang":"en","v":"HANFAX TRADING LIMITED"},{"lang":"hk","v":"恒發貿易有限公司"}],"company_since":"2003-06-05","company_dissolved":"2019-02-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"848867","names":[{"lang":"en","v":"HERO CENTURY HOLDINGS LIMITED"},{"lang":"hk","v":"雄昇集團有限公司"}],"company_since":"2003-06-05","company_dissolved":"2006-03-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"848713","names":[{"lang":"en","v":"GOLDEN STAR INTERNATIONAL LOGISTICS COMPANY LIMITED"},{"lang":"hk","v":"金星國際物流有限公司"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848740","names":[{"lang":"en","v":"HK FLOWER-RAIN INT'L LEATHER CO., LIMITED"},{"lang":"hk","v":"香港花雨露國際皮具有限公司"}],"company_since":"2003-06-05","company_dissolved":"2008-11-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"848845","names":[{"lang":"en","v":"HOMWELL LIMITED"},{"lang":"hk","v":"漢仁有限公司"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848657","names":[{"lang":"en","v":"HONESTY CORPORATION LIMITED (d2006-05-17)"},{"lang":"hk","v":"誠丰有限公司"}],"company_since":"2003-06-05","company_dissolved":"2006-05-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848668","names":[{"lang":"en","v":"GREAT TANK LIMITED (d2010-02-12)"},{"lang":"hk","v":"鼎丰有限公司"}],"company_since":"2003-06-05","company_dissolved":"2010-02-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"848621","names":[{"lang":"en","v":"HONG KONG CONSTRUCTION SUB-CONTRACTORS ASSOCIATION LIMITED"},{"lang":"hk","v":"香港建造業分包商聯會有限公司"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
undefined,
undefined,
undefined,
{"tax_id":"848978","names":[{"lang":"en","v":"HONG KONG HAO BAI NIAN FURNITURE INTERNATIONAL GROUP LIMITED"},{"lang":"hk","v":"香港好百年家具國際集團有限公司"}],"company_since":"2003-06-05","company_dissolved":"2008-11-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"848979","names":[{"lang":"en","v":"HONG KONG HAO JIA WOOD GROUP LIMITED"},{"lang":"hk","v":"香港豪嘉木業集團有限公司"}],"company_since":"2003-06-05","company_dissolved":"2009-10-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848926","names":[{"lang":"en","v":"HANWAY INTERNATIONAL (HONG KONG) INVESTMENT COMPANY LIMITED"},{"lang":"hk","v":"恒威國際(香港)投資有限公司"}],"company_since":"2003-06-05","company_dissolved":"2016-11-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"848656","names":[{"lang":"en","v":"HONG KONG HONG CHAU UNION DEVELOPMENT LIMITED"},{"lang":"hk","v":"香港康州聯合發展有限公司"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"848826","names":[{"lang":"en","v":"HARVEST RAINBOW INDUSTRIAL LIMITED"},{"lang":"hk","v":"豐行實業有限公司"}],"company_since":"2003-06-05","company_dissolved":"2013-04-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848859","names":[{"lang":"en","v":"HONG KONG KUNHUI INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"香港坤暉國際有限公司"}],"company_since":"2003-06-05","company_dissolved":"2014-10-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"848939","names":[{"lang":"en","v":"HIP MING ENGINEERING COMPANY LIMITED (d2005-08-05)"},{"lang":"hk","v":"協鳴工程有限公司"}],"company_since":"2003-06-05","company_dissolved":"2005-08-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"848760","names":[{"lang":"en","v":"HONG KONG SUN IMAGE MANAGEMENT CO., LIMITED"},{"lang":"hk","v":"香港日恒傳訊有限公司"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"848869","names":[{"lang":"en","v":"HONOUR LINK ENTERPRISES LIMITED (d2009-11-20)"},{"lang":"hk","v":"信寧企業有限公司"}],"company_since":"2003-06-05","company_dissolved":"2009-11-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"848849","names":[{"lang":"en","v":"HOP SHING DYEING COMPANY LIMITED"},{"lang":"hk","v":"合盛染色有限公司"}],"company_since":"2003-06-05","company_dissolved":"2011-01-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"848920","names":[{"lang":"en","v":"FRANKLIN SHIPPING (HK) COMPANY LIMITED"},{"lang":"hk","v":"富林海運(香港)有限公司"}],"company_since":"2003-06-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
