{"tax_id":"847567","names":[{"lang":"en","v":"CHINA WORLD SECRETARIES LIMITED"},{"lang":"hk","v":"華世秘書服務有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847678","names":[{"lang":"en","v":"CINESE HOTEL GROUP INTERNATIONAL MANAGEMENT LIMITED"},{"lang":"hk","v":"富盈酒店集團國際管理有限公司"}],"company_since":"2003-05-21","company_dissolved":"2014-11-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847666","names":[{"lang":"en","v":"COLUMBIA SPORTSWEAR COMPANY (HONG KONG) LIMITED"},{"lang":"hk","v":"美商哥倫比亞運動服裝(香港)有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847656","names":[{"lang":"en","v":"COOPERATIONS LIMITED"}],"company_since":"2003-05-21","company_dissolved":"2008-06-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847732","names":[{"lang":"en","v":"DE-RICH INT'L (HK) MANAGEMENT CONSULTANTS CO. LIMITED"},{"lang":"hk","v":"德瑞斯國際(香港)管理咨詢有限公司"}],"company_since":"2003-05-21","company_dissolved":"2008-04-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847719","names":[{"lang":"en","v":"CHINA FAR EAST INTERNATIONAL INVESTMENT AND DEVELOPMENT GROUP LIMITED"},{"lang":"hk","v":"中國遠東國際投資開發集團有限公司"}],"company_since":"2003-05-21","company_dissolved":"2007-10-05","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847542","names":[{"lang":"en","v":"DIRECT SPORTS ASIA LIMITED"}],"company_since":"2003-05-21","company_dissolved":"2008-01-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847722","names":[{"lang":"en","v":"CHINA FINANCIAL GROUP HOLDINGS LIMITED (d2005-07-15)"},{"lang":"hk","v":"豐華集團有限公司"}],"company_since":"2003-05-21","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847630","names":[{"lang":"en","v":"DONG FA INDUSTRIAL LIMITED"},{"lang":"hk","v":"東發實業有限公司"}],"company_since":"2003-05-21","company_dissolved":"2008-10-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847700","names":[{"lang":"en","v":"EASTERN ELECTRONICS GROUP LIMITED"},{"lang":"hk","v":"東豐電子集團有限公司"}],"company_since":"2003-05-21","company_dissolved":"2013-04-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847577","names":[{"lang":"en","v":"ELDERSHOP LIMITED (HK)"},{"lang":"hk","v":"愛德心有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847609","names":[{"lang":"en","v":"CHINA INTERNATIONAL FOUNDATION FOR ENTREPRENEURS LIMITED"},{"lang":"hk","v":"中國企業家國際基金會有限公司"}],"company_since":"2003-05-21","company_dissolved":"2011-05-06","company_type_txt":"Ltd by guarantee"},
{"tax_id":"847641","names":[{"lang":"en","v":"EVENT HORIZON MANAGEMENT CONSULTANTS LIMITED"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847659","names":[{"lang":"en","v":"CHINA INVESTOR RELATIONS RESEARCH DEVELOPMENT CO., LIMITED"},{"lang":"hk","v":"中國投資者關係研究發展有限公司"}],"company_since":"2003-05-21","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847702","names":[{"lang":"en","v":"EXEO LIMITED (d2007-04-13)"}],"company_since":"2003-05-21","company_dissolved":"2007-04-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847676","names":[{"lang":"en","v":"CINESE GROUP LIMITED"},{"lang":"hk","v":"中國富盈集團有限公司"}],"company_since":"2003-05-21","company_dissolved":"2014-11-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847713","names":[{"lang":"en","v":"FORTUNE GROUP (CHINA) LIMITED"},{"lang":"hk","v":"富勤集團(中國)有限公司"}],"company_since":"2003-05-21","company_dissolved":"2020-01-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847677","names":[{"lang":"en","v":"CINESE PROPERTY DEVELOPMENT LIMITED"},{"lang":"hk","v":"富盈地產發展有限公司"}],"company_since":"2003-05-21","company_dissolved":"2014-11-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847681","names":[{"lang":"en","v":"FRANCE TENDRILLED VINE &amp; SPRING BIOLOGICAL TECHNOLOGY (H.K.) CO., LIMITED"},{"lang":"hk","v":"法國春之蔓生物科技(香港)有限公司"}],"company_since":"2003-05-21","company_dissolved":"2007-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847657","names":[{"lang":"en","v":"CREATE DEVELOPMENT &amp; ENERGY PTE LIMITED"}],"company_since":"2003-05-21","company_dissolved":"2009-12-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847743","names":[{"lang":"en","v":"CHINA LINK OVERSEAS COMPANY LIMITED"},{"lang":"hk","v":"優質燒烤爐具有限公司"}],"company_since":"2003-05-21","company_dissolved":"2019-12-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847606","names":[{"lang":"en","v":"GERMANY KIT YEE LOT INT'L GROUP LIMITED"},{"lang":"hk","v":"德國潔爾樂國際集團有限公司"}],"company_since":"2003-05-21","company_dissolved":"2008-10-31","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847540","names":[{"lang":"en","v":"GLOBAL FINANCIAL PRESS LIMITED"},{"lang":"hk","v":"環球財經印刷有限公司"}],"company_since":"2003-05-21","company_dissolved":"2009-11-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847553","names":[{"lang":"en","v":"DIGITAL DISPLAY LIMITED"},{"lang":"hk","v":"數碼展視有限公司"}],"company_since":"2003-05-21","company_dissolved":"2006-01-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847594","names":[{"lang":"en","v":"GOLDEN RIVER ENTERPRISES (HONG KONG) CO., LIMITED"},{"lang":"hk","v":"金河實業(香港)有限公司"}],"company_since":"2003-05-21","company_dissolved":"2012-06-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847544","names":[{"lang":"en","v":"DRAGON WIN ENGINEERING WORKS LIMITED"},{"lang":"hk","v":"龍運工程有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847682","names":[{"lang":"en","v":"H &amp; T INTERNATIONAL MOVERS CO., LIMITED"},{"lang":"hk","v":"華聯通國際搬運有限公司"}],"company_since":"2003-05-21","company_dissolved":"2005-10-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847710","names":[{"lang":"en","v":"EAST SYNERGY LIMITED"},{"lang":"hk","v":"怡協電子有限公司"}],"company_since":"2003-05-21","company_dissolved":"2016-12-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847637","names":[{"lang":"en","v":"HANFORD CHEMICAL COMPANY LIMITED"},{"lang":"hk","v":"漢科化工有限公司"}],"company_since":"2003-05-21","company_dissolved":"2018-12-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847590","names":[{"lang":"en","v":"HANG KWONG PLASTIC MOULDINGS PRODUCT COMPANY LIMITED"},{"lang":"hk","v":"恒光塑膠製品有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847545","names":[{"lang":"en","v":"EVER SHINE INTERNATIONAL ENTERPRISES LIMITED"},{"lang":"hk","v":"焯恒國際實業有限公司"}],"company_since":"2003-05-21","company_dissolved":"2008-10-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847734","names":[{"lang":"en","v":"EVERGLOW INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"永騏國際有限公司"}],"company_since":"2003-05-21","company_dissolved":"2007-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847675","names":[{"lang":"en","v":"HK GLOBAL INFORMATION PUBLISHING LIMITED"},{"lang":"hk","v":"香港環球資訊出版社有限公司"}],"company_since":"2003-05-21","company_dissolved":"2008-10-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847587","names":[{"lang":"en","v":"HK SKY INTERNATIONAL INVESTMENT COMPANY LIMITED"},{"lang":"hk","v":"香港聚天國際投資有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847726","names":[{"lang":"en","v":"FIT FOR LIFE HEALTHCARE PRODUCT LIMITED"},{"lang":"hk","v":"健之源保健產品有限公司"}],"company_since":"2003-05-21","company_dissolved":"2007-08-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847585","names":[{"lang":"en","v":"HONG KONG CHUANGZHAO LIMITED"},{"lang":"hk","v":"香港創兆有限公司"}],"company_since":"2003-05-21","company_dissolved":"2007-12-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"847749","names":[{"lang":"en","v":"HONG KONG HAI RUN GROUP COMPANY LIMITED"},{"lang":"hk","v":"香港海潤集團有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847578","names":[{"lang":"en","v":"FRANCE DEFINITE INT'L GROUP (HK) COSMETICS LIMITED"},{"lang":"hk","v":"法國蒂法妮國際集團(香港)化妝品有限公司"}],"company_since":"2003-05-21","company_dissolved":"2012-08-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847548","names":[{"lang":"en","v":"HONG KONG PCF INDUSTRIAL LIMITED"},{"lang":"hk","v":"香港鵬誠飛實業有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847613","names":[{"lang":"en","v":"HONG KONG XINYUN FURNITURE HOLDINGS LIMITED"},{"lang":"hk","v":"香港新韻傢具集團有限公司"}],"company_since":"2003-05-21","company_dissolved":"2010-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847744","names":[{"lang":"en","v":"FREE INTERNATIONAL (HK) LIMITED"},{"lang":"hk","v":"富微國際(香港)有限公司"}],"company_since":"2003-05-21","company_dissolved":"2008-06-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847626","names":[{"lang":"en","v":"HONGKONG FORTUNE ARCHITECTURE LIGHTING DESIGN LIMITED"},{"lang":"hk","v":"香港富潤成建築藝術照明設計有限公司"}],"company_since":"2003-05-21","company_dissolved":"2018-09-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"847735","names":[{"lang":"en","v":"HOPEONE DEVELOPMENT INTERNATIONAL LIMITED"},{"lang":"hk","v":"喜望發展國際有限公司"}],"company_since":"2003-05-21","company_dissolved":"2007-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847655","names":[{"lang":"en","v":"GREEN LEAF GARDEN RESTAURANT LIMITED"},{"lang":"hk","v":"綠茵花園餐廳有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847708","names":[{"lang":"en","v":"INK SOCIETY LIMITED (THE)"},{"lang":"hk","v":"水墨會有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
{"tax_id":"847728","names":[{"lang":"en","v":"INTERNATIONAL FASHIONS LIMITED"},{"lang":"hk","v":"聯邦針織時裝有限公司"}],"company_since":"2003-05-21","company_dissolved":"2012-05-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847569","names":[{"lang":"en","v":"INTERPRODUCT HONG KONG LIMITED"}],"company_since":"2003-05-21","company_dissolved":"2011-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"847584","names":[{"lang":"en","v":"ITALY VIOLIN (H.K.) INTERNATIONAL GROUP CO., LIMITED"},{"lang":"hk","v":"意大利梵爾琳(香港)國際集團有限公司"}],"company_since":"2003-05-21","company_dissolved":"2007-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847689","names":[{"lang":"en","v":"HENSEN SYSTEM ENGINEERING LIMITED"},{"lang":"hk","v":"豪信系統工程有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847616","names":[{"lang":"en","v":"JAPAN YIBEN CO., LIMITED"},{"lang":"hk","v":"日本乙本株式會社有限公司"}],"company_since":"2003-05-21","company_dissolved":"2012-08-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847547","names":[{"lang":"en","v":"HEPTA ARTOUS ICTHUDIA LIMITED"},{"lang":"hk","v":"七餅小魚有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847586","names":[{"lang":"en","v":"JISHI SHARE LIMITED"},{"lang":"hk","v":"吉時股份有限公司"}],"company_since":"2003-05-21","company_dissolved":"2012-08-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847653","names":[{"lang":"en","v":"K &amp; TRA INTERNATIONAL CO., LIMITED"},{"lang":"hk","v":"大韓國際有限公司"}],"company_since":"2003-05-21","company_dissolved":"2020-01-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847706","names":[{"lang":"en","v":"KAI YU TRANSPORTATION LIMITED"},{"lang":"hk","v":"佳裕貨運有限公司"}],"company_since":"2003-05-21","company_dissolved":"2015-06-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847543","names":[{"lang":"en","v":"KAISHI TECHNOLOGY DEVELOPMENT LIMITED"},{"lang":"hk","v":"凱碩科技發展有限公司"}],"company_since":"2003-05-21","company_dissolved":"2007-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847629","names":[{"lang":"en","v":"KAM HING CHINA-HONG KONG TOUR AND TRANSPORTATION LIMITED"},{"lang":"hk","v":"金興中港旅運有限公司"}],"company_since":"2003-05-21","company_dissolved":"2007-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847593","names":[{"lang":"en","v":"KENKO (HONG KONG) LIMITED"}],"company_since":"2003-05-21","company_dissolved":"2008-09-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847560","names":[{"lang":"en","v":"HONG KONG YI HAO FURNITURE GROUP LIMITED"},{"lang":"hk","v":"香港億豪家具集團有限公司"}],"company_since":"2003-05-21","company_dissolved":"2006-04-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847551","names":[{"lang":"en","v":"KENORA LIMITED (d2010-07-16)"}],"company_since":"2003-05-21","company_dissolved":"2010-07-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847579","names":[{"lang":"en","v":"HONG KONG YONGJIN SHIPPING LIMITED (d2007-10-05)"},{"lang":"hk","v":"香港永進海運有限公司"}],"company_since":"2003-05-21","company_dissolved":"2007-10-05","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847607","names":[{"lang":"en","v":"KINGFLOWER THREAD (HK) CO., LIMITED"},{"lang":"hk","v":"花蝶線業(香港)有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847552","names":[{"lang":"en","v":"KOMOKA LIMITED (d2012-08-10)"}],"company_since":"2003-05-21","company_dissolved":"2012-08-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847741","names":[{"lang":"en","v":"LAGAS (H.K.) LIMITED"},{"lang":"hk","v":"來卡斯(香港)有限公司"}],"company_since":"2003-05-21","company_dissolved":"2016-12-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847730","names":[{"lang":"en","v":"LAND INTERNATIONAL TRADING CO., LIMITED"},{"lang":"hk","v":"大地國際貿易有限公司"}],"company_since":"2003-05-21","company_dissolved":"2006-07-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847716","names":[{"lang":"en","v":"LEXUSTAR LIMITED"},{"lang":"hk","v":"豪星有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847603","names":[{"lang":"en","v":"LINK-SUN (HONG KONG) ELECTRONICS LIMITED"},{"lang":"hk","v":"淩翔(香港)電子有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847596","names":[{"lang":"en","v":"ITALY CARMEN COSMETICS (H.K.) INT'L LIMITED"},{"lang":"hk","v":"意大利卡文化妝品(香港)國際有限公司"}],"company_since":"2003-05-21","company_dissolved":"2007-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847721","names":[{"lang":"en","v":"LUKE'S WAYNE LIMITED"},{"lang":"hk","v":"樂泰中有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847724","names":[{"lang":"en","v":"JAYA PROPERTIES LIMITED (HK)"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847731","names":[{"lang":"en","v":"INNO-CENTRIC LIMITED"}],"company_since":"2003-05-21","company_dissolved":"2009-01-02","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847572","names":[{"lang":"en","v":"MATCHONE CAFE LIMITED"}],"company_since":"2003-05-21","company_dissolved":"2009-08-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847742","names":[{"lang":"en","v":"JIAN RONG (HK) TRADING CO. LIMITED"},{"lang":"hk","v":"建榮(香港)貿易有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847701","names":[{"lang":"en","v":"MDMI TECHNOLOGIES (HONG KONG) LIMITED"},{"lang":"hk","v":"微創醫療器械科技(香港)有限公司"}],"company_since":"2003-05-21","company_dissolved":"2019-02-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847712","names":[{"lang":"en","v":"MICROEPOWER TECHNOLOGY COMPANY LIMITED"},{"lang":"hk","v":"東耀科技股份有限公司"}],"company_since":"2003-05-21","company_dissolved":"2010-12-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847600","names":[{"lang":"en","v":"MING HING TELECOM ENGINEERING LIMITED"},{"lang":"hk","v":"明興電訊工程有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847574","names":[{"lang":"en","v":"MODERN X-RAY &amp; MEDICAL LABORATORY LIMITED"},{"lang":"hk","v":"現代醫學X光化驗所有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847717","names":[{"lang":"en","v":"MULTI-BILLION LIMITED"},{"lang":"hk","v":"萬億行有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847563","names":[{"lang":"en","v":"KWOK KING ENTERPRISE (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"國勁企業(香港)有限公司"}],"company_since":"2003-05-21","company_dissolved":"2008-06-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847694","names":[{"lang":"en","v":"OCEAN EAST ENTERPRISES LIMITED"},{"lang":"hk","v":"東海企業有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847619","names":[{"lang":"en","v":"OILA INT'L GROUP LIMITED"},{"lang":"hk","v":"奧妮國際集團有限公司"}],"company_since":"2003-05-21","company_dissolved":"2007-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847614","names":[{"lang":"en","v":"ONE TREE HILL INTERNATIONAL LIMITED"},{"lang":"hk","v":"壹樹山國際有限公司"}],"company_since":"2003-05-21","company_dissolved":"2007-11-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847554","names":[{"lang":"en","v":"OXIA GROUP LIMITED"}],"company_since":"2003-05-21","company_dissolved":"2013-08-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847557","names":[{"lang":"en","v":"LONGFA DEVELOPMENT LIMITED"},{"lang":"hk","v":"龍發發展有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847546","names":[{"lang":"en","v":"PENTE ARTOUS DUO ICTHUAS LIMITED"},{"lang":"hk","v":"五餅二魚有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847746","names":[{"lang":"en","v":"PO: SELECTED COMPANY LIMITED"},{"lang":"hk","v":"普思力特有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847643","names":[{"lang":"en","v":"PRAISE &amp; GRACE (HK) LIMITED"},{"lang":"hk","v":"境輝投資有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847658","names":[{"lang":"en","v":"PRO-ACTIV FASHION LIMITED"}],"company_since":"2003-05-21","company_dissolved":"2006-08-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847573","names":[{"lang":"en","v":"PRUDENT SECRETARIES LIMITED"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847555","names":[{"lang":"en","v":"QINGDAO CAISHENG TRADING CO., LIMITED"},{"lang":"hk","v":"青島才盛貿易有限公司"}],"company_since":"2003-05-21","company_dissolved":"2007-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847674","names":[{"lang":"en","v":"MODERN CHINA RESTAURANT MANAGEMENT COMPANY LIMITED"},{"lang":"hk","v":"金滿庭集團管理有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847704","names":[{"lang":"en","v":"RISH JAVA INT'L (HK) INVESTMENT HOLDING CO. LIMITED"},{"lang":"hk","v":"瑞實渣華國際(香港)投資集團有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847635","names":[{"lang":"en","v":"RR ENTERPRISES LIMITED (d2009-10-16)"},{"lang":"hk","v":"奇薈企業有限公司"}],"company_since":"2003-05-21","company_dissolved":"2009-10-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"847589","names":[{"lang":"en","v":"National Sonic.Com Limited"},{"lang":"hk","v":"香港立生卓德投資有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847645","names":[{"lang":"en","v":"MY NETWORK GROUP LIMITED"},{"lang":"hk","v":"我的網絡谷有限公司"}],"company_since":"2003-05-21","company_dissolved":"2006-02-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847618","names":[{"lang":"en","v":"RUNHIGH INVESTMENT CO., LIMITED"},{"lang":"hk","v":"榮恒投資有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847575","names":[{"lang":"en","v":"SAFE OCEAN LIMITED (d2006-12-22)"},{"lang":"hk","v":"棟洋有限公司"}],"company_since":"2003-05-21","company_dissolved":"2006-12-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847665","names":[{"lang":"en","v":"SEAMATCH SOLUTIONS LIMITED"}],"company_since":"2003-05-21","company_dissolved":"2013-09-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847564","names":[{"lang":"en","v":"NORTHCROFT CONSTRUCTION SERVICES LIMITED"},{"lang":"hk","v":"羅富國測量師咨詢有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847664","names":[{"lang":"en","v":"SENSE-TECH LIMITED"},{"lang":"hk","v":"香港盛達科技有限公司"}],"company_since":"2003-05-21","company_dissolved":"2006-10-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847628","names":[{"lang":"en","v":"SHERETON YARN SPINNING LIMITED"},{"lang":"hk","v":"瑞駿毛紡有限公司"}],"company_since":"2003-05-21","company_dissolved":"2018-01-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"847634","names":[{"lang":"en","v":"PEARL LAGOON LIMITED"},{"lang":"hk","v":"銆勵有限公司"}],"company_since":"2003-05-21","company_dissolved":"2018-01-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847688","names":[{"lang":"en","v":"SINO CENTURY H.K. LIMITED"},{"lang":"hk","v":"華順香港有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847715","names":[{"lang":"en","v":"SINO DRAGON INDUSTRIAL LIMITED (d2007-10-05)"},{"lang":"hk","v":"華龍實業有限公司"}],"company_since":"2003-05-21","company_dissolved":"2007-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847566","names":[{"lang":"en","v":"SKY MARBLE (HK) LIMITED"},{"lang":"hk","v":"天材互動教育玩具有限公司"}],"company_since":"2003-05-21","company_dissolved":"2018-09-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847669","names":[{"lang":"en","v":"PROFESSOR WALTER H.L.WAN (D. MIN) MEMORIAL FUND LIMITED"},{"lang":"hk","v":"尹慶樑教授紀念基金有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
{"tax_id":"847576","names":[{"lang":"en","v":"SMART CHOICE ENGINEERING LIMITED"},{"lang":"hk","v":"祥鍕建造工程有限公司"}],"company_since":"2003-05-21","company_dissolved":"2009-04-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"847621","names":[{"lang":"en","v":"SUNBOW (ASIA) COMPANY LIMITED"},{"lang":"hk","v":"日虹(亞洲)有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847568","names":[{"lang":"en","v":"TAI KOON YUEN SHANGHAI RESTAURANT LIMITED"},{"lang":"hk","v":"大觀園上海飯店有限公司"}],"company_since":"2003-05-21","company_dissolved":"2014-09-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847707","names":[{"lang":"en","v":"TAI SI BUDDHA LIMITED"},{"lang":"hk","v":"大士菩薩有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
undefined,
undefined,
{"tax_id":"847636","names":[{"lang":"en","v":"TAIWAN SOFTWARE MANUFACTORY (TWSM) LIMITED"},{"lang":"hk","v":"台灣軟體製造股份有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847627","names":[{"lang":"en","v":"TAXI-TOP (CHINA) CO., LIMITED"},{"lang":"hk","v":"德事拓璞(中國)有限公司"}],"company_since":"2003-05-21","company_dissolved":"2009-10-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"847703","names":[{"lang":"en","v":"TIANSHI ANDE (CHINA) INVESTMENTS LIMITED"},{"lang":"hk","v":"天實安德(中國)投資有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847748","names":[{"lang":"en","v":"TIMES SOURCES LIMITED"},{"lang":"hk","v":"時代資訊有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847640","names":[{"lang":"en","v":"TONY SOFA COMPANY LIMITED"},{"lang":"hk","v":"東尼梳化有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"847684","names":[{"lang":"en","v":"W2 NAIL BEAUTY LIMITED"}],"company_since":"2003-05-21","company_dissolved":"2006-09-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847696","names":[{"lang":"en","v":"WAH MEI KIN LIMITED"},{"lang":"hk","v":"華美健有限公司"}],"company_since":"2003-05-21","company_dissolved":"2007-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847690","names":[{"lang":"en","v":"SKYLUX INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"天豪國際集團有限公司"}],"company_since":"2003-05-21","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847646","names":[{"lang":"en","v":"SUN GROWTH INTERNATIONAL LIMITED"},{"lang":"hk","v":"新高樺國際有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847687","names":[{"lang":"en","v":"WISDOM HERO INVESTMENT LIMITED"},{"lang":"hk","v":"智豪投資有限公司"}],"company_since":"2003-05-21","company_dissolved":"2008-10-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"847714","names":[{"lang":"en","v":"ZAC HK CO., LIMITED"}],"company_since":"2003-05-21","company_dissolved":"2012-03-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"847733","names":[{"lang":"en","v":"GOLDEN EAGLE INDUSTRIAL (CHINA) LIMITED"},{"lang":"hk","v":"金鷹實業(中國)有限公司"}],"company_since":"2003-05-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847642","names":[{"lang":"en","v":"HONGKONG (JAPAN) LANBADA FASHION GROUP LIMITED"},{"lang":"hk","v":"香港(日本)蘭巴達服飾集團有限公司"}],"company_since":"2003-05-21","company_dissolved":"2007-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
