undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"847486","names":[{"lang":"en","v":"COSMEDIA STUDIOS GROUP (HK) LIMITED"},{"lang":"hk","v":"中天電視廣播企業(香港)有限公司"}],"company_since":"2003-05-19","company_dissolved":"2010-11-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847421","names":[{"lang":"en","v":"FINE WEALTH LIMITED (d2008-02-15)"},{"lang":"hk","v":"鴻輝有限公司"}],"company_since":"2003-05-19","company_dissolved":"2008-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"847530","names":[{"lang":"en","v":"GERMANY CARDYDONY INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"德國凱迪東尼國際有限公司"}],"company_since":"2003-05-19","company_dissolved":"2011-03-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847518","names":[{"lang":"en","v":"GERMANY OU LEI SHI (HONG KONG) INTERNATIONAL LIMITED"},{"lang":"hk","v":"德國歐雷士(香港)國際有限公司"}],"company_since":"2003-05-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847418","names":[{"lang":"en","v":"EAON COMMUNICATIONS LIMITED"}],"company_since":"2003-05-19","company_dissolved":"2019-02-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847483","names":[{"lang":"en","v":"EASY CREATION LIMITED (d2007-09-28)"},{"lang":"hk","v":"展順有限公司"}],"company_since":"2003-05-19","company_dissolved":"2007-09-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847423","names":[{"lang":"en","v":"GO LOGISTICS LIMITED (d2008-10-31)"},{"lang":"hk","v":"高溢物流有限公司"}],"company_since":"2003-05-19","company_dissolved":"2008-10-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847453","names":[{"lang":"en","v":"GOODCOLORS TECHNOLOGY DEVELOPMENT LIMITED (d2015-06-19)"},{"lang":"hk","v":"雋佳科技發展有限公司"}],"company_since":"2003-05-19","company_dissolved":"2015-06-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847429","names":[{"lang":"en","v":"GOWELL INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"金色永康國際投資有限公司"}],"company_since":"2003-05-19","company_dissolved":"2013-08-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847452","names":[{"lang":"en","v":"H.K. FENG JIA TRADING LIMITED"},{"lang":"hk","v":"香港豐嘉貿易有限公司"}],"company_since":"2003-05-19","company_dissolved":"2008-10-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847442","names":[{"lang":"en","v":"H.K. SCIENCE POPULARIZATION LIMITED"},{"lang":"hk","v":"香港科普有限公司"}],"company_since":"2003-05-19","company_dissolved":"2019-04-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847515","names":[{"lang":"en","v":"EVERLUXE INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"華尚國際控股有限公司"}],"company_since":"2003-05-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847511","names":[{"lang":"en","v":"HARMONY (H.K.) TRADING LIMITED"},{"lang":"hk","v":"嘉和(香港)貿易有限公司"}],"company_since":"2003-05-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847501","names":[{"lang":"en","v":"HK GIANTRICH INTERNATIONAL (GROUPS) LIMITED"},{"lang":"hk","v":"香港富勤國際(集團)有限公司"}],"company_since":"2003-05-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"847491","names":[{"lang":"en","v":"FEDA ELECTRONICS COMPANY LIMITED"},{"lang":"hk","v":"飛達電子科技有限公司"}],"company_since":"2003-05-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847537","names":[{"lang":"en","v":"HONG KONG BATTLE FURNITURE GROUP COMPANY LIMITED"},{"lang":"hk","v":"香港栢拓傢俱集團有限公司"}],"company_since":"2003-05-19","company_dissolved":"2016-01-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847492","names":[{"lang":"en","v":"HONG KONG INTERNATIONAL DIRECT SALES INSTITUTE LIMITED (THE)"},{"lang":"hk","v":"香港國際直銷學院有限公司"}],"company_since":"2003-05-19","company_dissolved":"2006-10-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"847514","names":[{"lang":"en","v":"FIRSTPOWER TECHNOLOGY (HK) CO., LIMITED"},{"lang":"hk","v":"一電實業(香港)有限公司"}],"company_since":"2003-05-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847516","names":[{"lang":"en","v":"HONG KONG LE QIN XUAN FURNITURE GROUP LIMITED"},{"lang":"hk","v":"香港樂琴軒傢俱集團有限公司"}],"company_since":"2003-05-19","company_dissolved":"2007-09-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847448","names":[{"lang":"en","v":"HONG KONG MARY KELLY INTERNATIONAL FASHION LIMITED"},{"lang":"hk","v":"香港瑪麗嘉兒國際時裝有限公司"}],"company_since":"2003-05-19","company_dissolved":"2013-11-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"847416","names":[{"lang":"en","v":"GAINFUL PLASTICS MANUFACTORY LIMITED"},{"lang":"hk","v":"景富塑膠製品有限公司"}],"company_since":"2003-05-19","company_dissolved":"2020-01-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847536","names":[{"lang":"en","v":"HONG KONG MI SAI YA INTERNATIONAL GROUP LIMITED"},{"lang":"hk","v":"香港迷賽亞國際集團有限公司"}],"company_since":"2003-05-19","company_dissolved":"2007-09-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847517","names":[{"lang":"en","v":"HONG KONG SHUANG XIANG FURNITURE INTERNATIONAL GROUP LIMITED"},{"lang":"hk","v":"香港雙象傢俱國際集團有限公司"}],"company_since":"2003-05-19","company_dissolved":"2008-10-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847457","names":[{"lang":"en","v":"HONGKONG LECHENG ELECTRONIC CO., LIMITED"},{"lang":"hk","v":"香港樂誠電子有限公司"}],"company_since":"2003-05-19","company_dissolved":"2016-12-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847414","names":[{"lang":"en","v":"HOSKYN CHILD ASIA LIMITED"}],"company_since":"2003-05-19","company_dissolved":"2018-01-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847422","names":[{"lang":"en","v":"GLOBE LOGISTICS LIMITED (d2007-09-28)"},{"lang":"hk","v":"寰豐物流有限公司"}],"company_since":"2003-05-19","company_dissolved":"2007-09-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847404","names":[{"lang":"en","v":"HYGIENIC INTERNATIONAL GROUP COMPANY LIMITED"},{"lang":"hk","v":"衛康國際集團有限公司"}],"company_since":"2003-05-19","company_dissolved":"2012-08-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847499","names":[{"lang":"en","v":"IBERASIA LIMITED"}],"company_since":"2003-05-19","company_dissolved":"2008-10-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847440","names":[{"lang":"en","v":"INTERNATIONAL DESKTOP PUBLISHING ASSOCIATION LIMITED"},{"lang":"hk","v":"國際桌面出版協會有限公司"}],"company_since":"2003-05-19","company_dissolved":"2007-09-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847465","names":[{"lang":"en","v":"J &amp; J PROPERTY CONSULTANTS LIMITED (HK)"},{"lang":"hk","v":"富豪地產代理有限公司"}],"company_since":"2003-05-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847468","names":[{"lang":"en","v":"J.A. FABRIC CO., LIMITED"},{"lang":"hk","v":"漢昌布業有限公司"}],"company_since":"2003-05-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847487","names":[{"lang":"en","v":"HK KWONG YU INT'L INVESTMENT LIMITED"},{"lang":"hk","v":"香港光宇國際投資有限公司"}],"company_since":"2003-05-19","company_dissolved":"2012-08-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847432","names":[{"lang":"en","v":"KDNC TECHNOLOGY LIMITED"},{"lang":"hk","v":"愷豐科技有限公司"}],"company_since":"2003-05-19","company_dissolved":"2008-10-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847535","names":[{"lang":"en","v":"KONG TIN ENGINEERING LIMITED"},{"lang":"hk","v":"港電工程有限公司"}],"company_since":"2003-05-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847485","names":[{"lang":"en","v":"KONGWAY LOGISTICS LIMITED (d2008-12-12)"},{"lang":"hk","v":"港運物流有限公司"}],"company_since":"2003-05-19","company_dissolved":"2008-12-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"847531","names":[{"lang":"en","v":"LAUDERHILL LIMITED"}],"company_since":"2003-05-19","company_dissolved":"2010-09-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847403","names":[{"lang":"en","v":"LOK FUNG ENGINEERING LIMITED"},{"lang":"hk","v":"樂豐工程有限公司"}],"company_since":"2003-05-19","company_dissolved":"2009-10-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847396","names":[{"lang":"en","v":"MANSART COMPANY LIMITED"},{"lang":"hk","v":"萬藝金屬製品有限公司"}],"company_since":"2003-05-19","company_dissolved":"2010-12-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847424","names":[{"lang":"en","v":"MILLION WEALTHY LIMITED (d2007-09-28)"},{"lang":"hk","v":"百福有限公司"}],"company_since":"2003-05-19","company_dissolved":"2007-09-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847523","names":[{"lang":"en","v":"HONGKONG HUAHAI HOLDINGS LIMITED"},{"lang":"hk","v":"香港華海集團有限公司"}],"company_since":"2003-05-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847446","names":[{"lang":"en","v":"NATURAL POWER ENVIRONMENTAL CONSULTANTS LIMITED"},{"lang":"hk","v":"環美環保顧問有限公司"}],"company_since":"2003-05-19","company_dissolved":"2009-07-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847520","names":[{"lang":"en","v":"NETWORKSHANGHAI CO., LIMITED"},{"lang":"hk","v":"香港聯盈數碼有限公司"}],"company_since":"2003-05-19","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847409","names":[{"lang":"en","v":"HYTECHNOLOGY (INT'L) LIMITED"}],"company_since":"2003-05-19","company_dissolved":"2010-03-26","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847417","names":[{"lang":"en","v":"NEW FORTUNE METALS &amp; MINERALS CO., LIMITED"},{"lang":"hk","v":"新亞富金屬礦產有限公司"}],"company_since":"2003-05-19","company_dissolved":"2009-10-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847411","names":[{"lang":"en","v":"PADPRINTER MACHINERY COMPANY LIMITED"},{"lang":"hk","v":"穎輝機器設備有限公司"}],"company_since":"2003-05-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847415","names":[{"lang":"en","v":"PAK LOONG TONG GINSENG COMPANY LIMITED"},{"lang":"hk","v":"百隆堂參茸行有限公司"}],"company_since":"2003-05-19","company_dissolved":"2008-11-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847462","names":[{"lang":"en","v":"MILLION GLORY INTERNATIONAL INVESTMENT COMPANY LIMITED"},{"lang":"hk","v":"萬勝國際投資有限公司"}],"company_since":"2003-05-19","company_dissolved":"2008-08-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847443","names":[{"lang":"en","v":"JANUS CONSULTANCY LIMITED (HK)"},{"lang":"hk","v":"精思顧問有限公司"}],"company_since":"2003-05-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847479","names":[{"lang":"en","v":"REDPOINT COMMUNICATIONS LIMITED (d2008-03-20)"},{"lang":"hk","v":"紅宇電訊有限公司"}],"company_since":"2003-05-19","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847397","names":[{"lang":"en","v":"JC NON-WOVEN ARTICLES LIMITED"},{"lang":"hk","v":"正暉無紡布用品有限公司"}],"company_since":"2003-05-19","company_dissolved":"2010-10-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847502","names":[{"lang":"en","v":"JUSTKING ENTERPRISE GROUP LIMITED"},{"lang":"hk","v":"鑫易企業集團有限公司"}],"company_since":"2003-05-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847449","names":[{"lang":"en","v":"SAMSON MAK CONSULTANTS LIMITED"},{"lang":"hk","v":"麥耀祥顧問有限公司"}],"company_since":"2003-05-19","company_dissolved":"2007-09-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847513","names":[{"lang":"en","v":"KNIGHT KING TECHNOLOGY LIMITED"},{"lang":"hk","v":"岡杰科技有限公司"}],"company_since":"2003-05-19","company_dissolved":"2007-09-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847538","names":[{"lang":"en","v":"SHUN NING HONG LIMITED"},{"lang":"hk","v":"順寧行有限公司"}],"company_since":"2003-05-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847408","names":[{"lang":"en","v":"SHUNJIE INTERNATIONAL GROUP (HONGKONG) HOLDING CO., LIMITED"},{"lang":"hk","v":"舜傑國際集團(香港)控股有限公司"}],"company_since":"2003-05-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847480","names":[{"lang":"en","v":"SOME PUBLISHING LIMITED"},{"lang":"hk","v":"蘇梅出版有限公司"}],"company_since":"2003-05-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847427","names":[{"lang":"en","v":"SOUTH-WEST THROUGH TRANSPORT (CHINA) COMPANY LIMITED"},{"lang":"hk","v":"西南全程物流(中國)有限公司"}],"company_since":"2003-05-19","company_dissolved":"2008-09-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847481","names":[{"lang":"en","v":"MEDI-TOP (CHINA) INDUSTRY COMPANY LIMITED"},{"lang":"hk","v":"美拓(中國)實業有限公司"}],"company_since":"2003-05-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847488","names":[{"lang":"en","v":"STOCKS &amp; STOCKS LIMITED"},{"lang":"hk","v":"庫存營運有限公司"}],"company_since":"2003-05-19","company_dissolved":"2008-10-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847407","names":[{"lang":"en","v":"SUNLUCK GARMENTS MFG. CO., LIMITED"},{"lang":"hk","v":"吉日制衣有限公司"}],"company_since":"2003-05-19","company_dissolved":"2014-11-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847400","names":[{"lang":"en","v":"SUNNY SUN INTERNATIONAL CORP. LIMITED"}],"company_since":"2003-05-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847401","names":[{"lang":"en","v":"SUSTAINABLE DEVELOPMENT PRODUCTS LIMITED"}],"company_since":"2003-05-19","company_dissolved":"2016-11-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847519","names":[{"lang":"en","v":"TASTE OF HONG KONG LIMITED (d2008-07-11)"},{"lang":"hk","v":"香港手信有限公司"}],"company_since":"2003-05-19","company_dissolved":"2008-07-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847425","names":[{"lang":"en","v":"TEAMLUCK CORPORATION LIMITED"},{"lang":"hk","v":"福群有限公司"}],"company_since":"2003-05-19","company_dissolved":"2007-09-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847490","names":[{"lang":"en","v":"PDS TECHNOLOGY LIMITED"},{"lang":"hk","v":"創鑠科技有限公司"}],"company_since":"2003-05-19","company_dissolved":"2008-11-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847495","names":[{"lang":"en","v":"PREMIUM RESOURCES LIMITED (d2011-05-27)"},{"lang":"hk","v":"禮星有限公司"}],"company_since":"2003-05-19","company_dissolved":"2011-05-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847500","names":[{"lang":"en","v":"TERESA TENG FOUNDATION HONG KONG LIMITED"},{"lang":"hk","v":"鄧麗君文教協進會香港有限公司"}],"company_since":"2003-05-19","company_dissolved":"2011-11-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"847470","names":[{"lang":"en","v":"REED ENERGY LIMITED (d2009-10-09)"}],"company_since":"2003-05-19","company_dissolved":"2009-10-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847412","names":[{"lang":"en","v":"TIMING TRADING (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"達銘貿易(香港)有限公司"}],"company_since":"2003-05-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847399","names":[{"lang":"en","v":"RONGZHI INTERNATIONAL INVESTMENT (H.K.) LIMITED"},{"lang":"hk","v":"榮志國際投資(香港)有限公司"}],"company_since":"2003-05-19","company_dissolved":"2012-08-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847434","names":[{"lang":"en","v":"SEN JIE CHINA LOGISTICS LIMITED"},{"lang":"hk","v":"森捷中國物流有限公司"}],"company_since":"2003-05-19","company_dissolved":"2018-11-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847505","names":[{"lang":"en","v":"VADCOM INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"亞通世信國際控股有限公司"}],"company_since":"2003-05-19","company_dissolved":"2007-07-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847503","names":[{"lang":"en","v":"VIGORIA (INT'L) MACHINERY LIMITED"},{"lang":"hk","v":"維高(國際)機械有限公司"}],"company_since":"2003-05-19","company_dissolved":"2011-01-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847475","names":[{"lang":"en","v":"WILTEK TECHNOLOGY COMPANY LIMITED"},{"lang":"hk","v":"匯達電子有限公司"}],"company_since":"2003-05-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847510","names":[{"lang":"en","v":"Win Town Financial Service Group Limited"},{"lang":"hk","v":"運通金融服務集團有限公司"}],"company_since":"2003-05-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847426","names":[{"lang":"en","v":"WINLINE CORPORATION LIMITED"},{"lang":"hk","v":"凱通有限公司"}],"company_since":"2003-05-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847451","names":[{"lang":"en","v":"ST-MART INTERNATIONAL COMPANY LIMITED (d2012-08-03)"},{"lang":"hk","v":"聖瑪特實業有限公司"}],"company_since":"2003-05-19","company_dissolved":"2012-08-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847459","names":[{"lang":"en","v":"WMSVISION ASIA LIMITED"},{"lang":"hk","v":"威馬施物流軟件亞洲有限公司"}],"company_since":"2003-05-19","company_dissolved":"2008-10-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847534","names":[{"lang":"en","v":"WORLDTOP TECHNOLOGY NETWORK COMPANY LIMITED"},{"lang":"hk","v":"迅通科技網絡有限公司"}],"company_since":"2003-05-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847493","names":[{"lang":"en","v":"Y. H. GLOBAL (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"英霞環球(香港)有限公司"}],"company_since":"2003-05-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847522","names":[{"lang":"en","v":"YAMATO FAR EAST DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"大和遠東發展有限公司"}],"company_since":"2003-05-19","company_dissolved":"2005-07-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847413","names":[{"lang":"en","v":"YICK KA (H.K.) TRADING COMPANY LIMITED"},{"lang":"hk","v":"億佳(香港)貿易有限公司"}],"company_since":"2003-05-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847406","names":[{"lang":"en","v":"TENS CORPORATION LIMITED (d2008-05-30)"},{"lang":"hk","v":"全胜國際有限公司"}],"company_since":"2003-05-19","company_dissolved":"2008-05-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"847471","names":[{"lang":"en","v":"YIHUA (HK) INTERNATIONAL CO., LIMITED"},{"lang":"hk","v":"怡華(香港)國際有限公司"}],"company_since":"2003-05-19","company_dissolved":"2008-10-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847533","names":[{"lang":"en","v":"YONGYE INT'L BUSINESS TRADING LIMITED"},{"lang":"hk","v":"永業國際商貿有限公司"}],"company_since":"2003-05-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847504","names":[{"lang":"en","v":"YUET FUNG ENGINEERING LIMITED"},{"lang":"hk","v":"越豐工程有限公司"}],"company_since":"2003-05-19","company_dissolved":"2009-12-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"847402","names":[{"lang":"en","v":"TRANPO TRACK ENGINEERING LIMITED"}],"company_since":"2003-05-19","company_dissolved":"2006-02-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847410","names":[{"lang":"en","v":"TRICO INDUSTRIAL COMPANY LIMITED"}],"company_since":"2003-05-19","company_dissolved":"2009-10-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847482","names":[{"lang":"en","v":"UNIVERSAL HOLDINGS INVESTMENT LIMITED"},{"lang":"hk","v":"環宇控股投資有限公司"}],"company_since":"2003-05-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"847497","names":[{"lang":"en","v":"XING TONG CULTURE &amp; MEDIA LIMITED"},{"lang":"hk","v":"行通文化傳播有限公司"}],"company_since":"2003-05-19","company_dissolved":"2008-10-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"847447","names":[{"lang":"en","v":"YICK SHING TRANSPORTATION CO., LIMITED"},{"lang":"hk","v":"益盛運輸有限公司"}],"company_since":"2003-05-19","company_dissolved":"2011-02-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"847532","names":[{"lang":"en","v":"GLOBALCHEM INVESTMENT LIMITED"},{"lang":"hk","v":"高寶化工投資有限公司"}],"company_since":"2003-05-19","company_dissolved":"2008-01-25","company_type_txt":"Private, ltd by shares"},
undefined,
