undefined,
{"tax_id":"785539","names":[{"lang":"en","v":"CERALAC ASIA LIMITED"}],"company_since":"2002-02-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"785419","names":[{"lang":"en","v":"CHARLINGTON LIMITED (d2004-06-30)"}],"company_since":"2002-02-06","company_dissolved":"2004-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"785640","names":[{"lang":"en","v":"CIC Capital Management Limited"},{"lang":"hk","v":"泓昇融資管理有限公司"}],"company_since":"2002-02-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"785437","names":[{"lang":"en","v":"FRANCE LOUI JENO GARMENT INT'L LIMITED"},{"lang":"hk","v":"法國路易‧傑奴服飾國際有限公司"}],"company_since":"2002-02-06","company_dissolved":"2007-06-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"785521","names":[{"lang":"en","v":"GARDEN WORLD CORPORATION LIMITED"},{"lang":"hk","v":"嘉偉有限公司"}],"company_since":"2002-02-06","company_dissolved":"2008-11-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"785353","names":[{"lang":"en","v":"FULL UNION LOGISTICS LIMITED"},{"lang":"hk","v":"富邦貨運有限公司"}],"company_since":"2002-02-06","company_dissolved":"2013-08-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"785403","names":[{"lang":"en","v":"H.K. INOL (INTERNATIONAL) DEVELOP LIMITED"},{"lang":"hk","v":"香港依諾(國際)發展有限公司"}],"company_since":"2002-02-06","company_dissolved":"2013-07-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"785435","names":[{"lang":"en","v":"HONGKONG EASPEER INTERNATIONAL FASHION CO., LIMITED"},{"lang":"hk","v":"香港伊思佩爾國際時裝有限公司"}],"company_since":"2002-02-06","company_dissolved":"2007-06-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"785573","names":[{"lang":"en","v":"HOWE ON ENGINEERING LIMITED"},{"lang":"hk","v":"浩安工程有限公司"}],"company_since":"2002-02-06","company_dissolved":"2011-09-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"785357","names":[{"lang":"en","v":"IT SUPPLIES ASIA LIMITED"}],"company_since":"2002-02-06","company_dissolved":"2005-07-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"785626","names":[{"lang":"en","v":"ITALY BACONIAN.VALENTINO INTERNATIONAL (H.K.) GARMENT LIMITED"},{"lang":"hk","v":"意大利培根‧華倫天奴國際(香港)服飾有限公司"}],"company_since":"2002-02-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"785543","names":[{"lang":"en","v":"JCM METAL &amp; PLASTIC LIMITED"},{"lang":"hk","v":"晶暉五金塑膠有限公司"}],"company_since":"2002-02-06","company_dissolved":"2014-11-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"785595","names":[{"lang":"en","v":"HONWELL INTERNATIONAL INDUSTRIAL LIMITED"},{"lang":"hk","v":"康華國際實業有限公司"}],"company_since":"2002-02-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"785355","names":[{"lang":"en","v":"LEADERSHIP INC LIMITED"},{"lang":"hk","v":"立德管理顧問有限公司"}],"company_since":"2002-02-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"785558","names":[{"lang":"en","v":"MEGA SHEEN HOLDINGS LIMITED"},{"lang":"hk","v":"大盛集團有限公司"}],"company_since":"2002-02-06","company_dissolved":"2009-10-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"785371","names":[{"lang":"en","v":"MUSIC NATION PUBLISHING COMPANY LIMITED"},{"lang":"hk","v":"大國文化音樂版權有限公司"}],"company_since":"2002-02-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"785422","names":[{"lang":"en","v":"MZ HOLDINGS LIMITED (d2014-11-14)"}],"company_since":"2002-02-06","company_dissolved":"2014-11-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"785381","names":[{"lang":"en","v":"KEYFAST TRAINING (HK) LIMITED"}],"company_since":"2002-02-06","company_dissolved":"2009-07-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"785378","names":[{"lang":"en","v":"ORIENT DELON CORPORATION (HONG KONG) LIMITED"},{"lang":"hk","v":"華東企業(香港)有限公司"}],"company_since":"2002-02-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"785561","names":[{"lang":"en","v":"PATTESON LIMITED"},{"lang":"hk","v":"百達先有限公司"}],"company_since":"2002-02-06","company_dissolved":"2002-11-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"785358","names":[{"lang":"en","v":"PBI MATERIALS HANDLING LIMITED"}],"company_since":"2002-02-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"785344","names":[{"lang":"en","v":"LEE TANG'S TRADING LIMITED"}],"company_since":"2002-02-06","company_dissolved":"2009-11-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"785414","names":[{"lang":"en","v":"PRATTISON GARMENT LIMITED"}],"company_since":"2002-02-06","company_dissolved":"2012-06-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"785454","names":[{"lang":"en","v":"SANG LIK ENGINEERING LIMITED"},{"lang":"hk","v":"三力工程有限公司"}],"company_since":"2002-02-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"785445","names":[{"lang":"en","v":"SATELLITE LIMITED (d2016-06-03)"},{"lang":"hk","v":"衛星導航有限公司"}],"company_since":"2002-02-06","company_dissolved":"2016-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"785601","names":[{"lang":"en","v":"PURENATURAL PRODUCTS (HK) LIMITED"},{"lang":"hk","v":"恆健藥業(香港)有限公司"}],"company_since":"2002-02-06","company_dissolved":"2005-03-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"785633","names":[{"lang":"en","v":"SHENG TIN HONG INTERNATIONAL TRADING LIMITED"},{"lang":"hk","v":"勝天行國際商貿有限公司"}],"company_since":"2002-02-06","company_dissolved":"2016-09-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"785446","names":[{"lang":"en","v":"TAI SANG PEARLS &amp; GEMS CO. LIMITED"},{"lang":"hk","v":"大生珍珠寶石有限公司"}],"company_since":"2002-02-06","company_dissolved":"2007-06-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"785460","names":[{"lang":"en","v":"SEE SPORT LIMITED"},{"lang":"hk","v":"悅目有限公司"}],"company_since":"2002-02-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"785509","names":[{"lang":"en","v":"SHEEN UNIVERSE LIMITED"},{"lang":"hk","v":"欣宇有限公司"}],"company_since":"2002-02-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"785404","names":[{"lang":"en","v":"TOSUN DEVELOPMENT LIMITED"},{"lang":"hk","v":"道盛發展有限公司"}],"company_since":"2002-02-06","company_dissolved":"2012-02-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"785345","names":[{"lang":"en","v":"TREASURE ENVIRONMENT (CHINA) LIMITED"},{"lang":"hk","v":"富恒環保(中國)有限公司"}],"company_since":"2002-02-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"785447","names":[{"lang":"en","v":"SUPERIOR MOTORS (GROUP) LIMITED"},{"lang":"hk","v":"天一汽車(集團)有限公司"}],"company_since":"2002-02-06","company_dissolved":"2019-08-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"785426","names":[{"lang":"en","v":"VISAGE ASIA LIMITED"}],"company_since":"2002-02-06","company_dissolved":"2019-01-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"785572","names":[{"lang":"en","v":"TITRON INTERNATIONAL LIMITED"},{"lang":"hk","v":"德隆環球有限公司"}],"company_since":"2002-02-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"785577","names":[{"lang":"en","v":"X-TREME LIMITED"}],"company_since":"2002-02-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
