{"tax_id":"616852","names":[{"lang":"en","v":"CHAMPION UNION MOTORS LIMITED"},{"lang":"hk","v":"永昇車行有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616802","names":[{"lang":"en","v":"CHEONG MING LIMITED"},{"lang":"hk","v":"昌銘有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616807","names":[{"lang":"en","v":"CHEONG YUE BUILDING MATERIALS SUPPLY LIMITED"},{"lang":"hk","v":"創裕五金建築材料有限公司"}],"company_since":"1997-07-11","company_dissolved":"2006-11-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616569","names":[{"lang":"en","v":"CHILDREN'S PARADISE FOUNDATION LIMITED"},{"lang":"hk","v":"兒童樂園基金會有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"616884","names":[{"lang":"en","v":"CHINA DEVELOPMENT SECURITIES LIMITED"},{"lang":"hk","v":"中國發展証券有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-04-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616583","names":[{"lang":"en","v":"CHINA OVERSEAS EDUCATION CENTRE LIMITED (d2001-08-10)"},{"lang":"hk","v":"中國海外教育中心有限公司"}],"company_since":"1997-07-11","company_dissolved":"2001-08-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616726","names":[{"lang":"en","v":"CHINA SHUTTLE SERVICE COMPANY LIMITED"},{"lang":"hk","v":"華崧實業有限公司"}],"company_since":"1997-07-11","company_dissolved":"2000-08-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616617","names":[{"lang":"en","v":"CHINA SOURCES INDUSTRIAL &amp; DEVELOPMENT CO., LIMITED"},{"lang":"hk","v":"華源興業有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616679","names":[{"lang":"en","v":"CHUNG HING (HK) LEATHER TRADING CO. LIMITED"},{"lang":"hk","v":"香港中興皮革貿易有限公司"}],"company_since":"1997-07-11","company_dissolved":"2001-10-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616877","names":[{"lang":"en","v":"CITIBRIDGE FINANCE LIMITED (d2012-11-02)"},{"lang":"hk","v":"橋建財務有限公司"}],"company_since":"1997-07-11","company_dissolved":"2012-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616836","names":[{"lang":"en","v":"CITIBINGO FINANCE LIMITED"},{"lang":"hk","v":"城益財務有限公司"}],"company_since":"1997-07-11","company_dissolved":"2018-09-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616701","names":[{"lang":"en","v":"CITY BUSINESS ENTERPRISES LIMITED (d2003-04-04)"},{"lang":"hk","v":"港隆企業有限公司"}],"company_since":"1997-07-11","company_dissolved":"2003-04-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616627","names":[{"lang":"en","v":"CITY MEDIA &amp; PRODUCTION LIMITED"},{"lang":"hk","v":"都市傳媒及製作有限公司"}],"company_since":"1997-07-11","company_dissolved":"2003-06-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616642","names":[{"lang":"en","v":"CITY PROFIT ENTERPRISES LIMITED"},{"lang":"hk","v":"港倡企業有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616792","names":[{"lang":"en","v":"CITY PROFIT TRADING LIMITED (d2000-12-22)"},{"lang":"hk","v":"廣協貿易有限公司"}],"company_since":"1997-07-11","company_dissolved":"2000-12-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616606","names":[{"lang":"en","v":"CITY SINO DEVELOPMENT LIMITED (d2005-07-15)"},{"lang":"hk","v":"永正發展有限公司"}],"company_since":"1997-07-11","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616570","names":[{"lang":"en","v":"COMMERCENET CHINA LIMITED"}],"company_since":"1997-07-11","company_dissolved":"2006-11-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616609","names":[{"lang":"en","v":"CONTROLGAS ASIA LIMITED"},{"lang":"hk","v":"漢漕克斯亞洲有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616798","names":[{"lang":"en","v":"CREATEX ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"創亞工業器材工程有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616553","names":[{"lang":"en","v":"DESIGN STYLE LIMITED"},{"lang":"hk","v":"時尚設計工程有限公司"}],"company_since":"1997-07-11","company_dissolved":"2003-02-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616660","names":[{"lang":"en","v":"DRAGON BRIGHT (HONG KONG) TRADING LIMITED"},{"lang":"hk","v":"龍臻(香港)貿易有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616603","names":[{"lang":"en","v":"DRAGON FIELD ENTERPRISES LIMITED"},{"lang":"hk","v":"龍裕企業有限公司"}],"company_since":"1997-07-11","company_dissolved":"2011-02-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616751","names":[{"lang":"en","v":"EASTERN CREATION (HONG KONG) LIMITED"},{"lang":"hk","v":"東創(香港)有限公司"}],"company_since":"1997-07-11","company_dissolved":"2000-08-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616856","names":[{"lang":"en","v":"ELAINE HARALD &amp; CO. LIMITED"}],"company_since":"1997-07-11","company_dissolved":"2007-11-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616819","names":[{"lang":"en","v":"ELECTRONIC WORKERS LIMITED"},{"lang":"hk","v":"電工人科技有限公司"}],"company_since":"1997-07-11","company_dissolved":"2002-01-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616557","names":[{"lang":"en","v":"EMPIRE CHINA FAR EAST TRADING LIMITED"},{"lang":"hk","v":"帝國中國遠東貿易有限公司"}],"company_since":"1997-07-11","company_dissolved":"2002-11-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616652","names":[{"lang":"en","v":"EQUALITY SERVICES LIMITED (d2004-12-17)"},{"lang":"hk","v":"恒正顧問有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-12-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616575","names":[{"lang":"en","v":"ESEN DEVELOPMENT LIMITED (d2005-07-15)"},{"lang":"hk","v":"裕軒發展有限公司"}],"company_since":"1997-07-11","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616737","names":[{"lang":"en","v":"ETERNAL BEST INVESTMENT LIMITED (d2004-12-17)"},{"lang":"hk","v":"恆飛投資有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-12-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616715","names":[{"lang":"en","v":"ETERNAL PROGRESS LIMITED"},{"lang":"hk","v":"恆御有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616846","names":[{"lang":"en","v":"ETERNAL SUMMIT DEVELOPMENT LIMITED"},{"lang":"hk","v":"恆逸發展有限公司"}],"company_since":"1997-07-11","company_dissolved":"2006-07-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616898","names":[{"lang":"en","v":"ETERNAL SUMMIT INVESTMENTS LIMITED"},{"lang":"hk","v":"恆逸投資有限公司"}],"company_since":"1997-07-11","company_dissolved":"2006-02-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616718","names":[{"lang":"en","v":"ETERNAL SUPERB LIMITED"},{"lang":"hk","v":"恆樺有限公司"}],"company_since":"1997-07-11","company_dissolved":"2000-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616902","names":[{"lang":"en","v":"EULOGIA PRODUCTIONS LIMITED"},{"lang":"hk","v":"裕泰隆製作有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616891","names":[{"lang":"en","v":"EVER LORD LIMITED"},{"lang":"hk","v":"恒倡有限公司"}],"company_since":"1997-07-11","company_dissolved":"2002-11-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616634","names":[{"lang":"en","v":"EVERFIT DEVELOPMENTS LIMITED"},{"lang":"hk","v":"永顯發展有限公司"}],"company_since":"1997-07-11","company_dissolved":"2002-06-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616844","names":[{"lang":"en","v":"EVERGAIN GLOBAL ENTERPRISE LIMITED"},{"lang":"hk","v":"年豐國際貿易有限公司"}],"company_since":"1997-07-11","company_dissolved":"2007-01-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616823","names":[{"lang":"en","v":"EXCELTRON INDUSTRIAL LIMITED"},{"lang":"hk","v":"怡通實業有限公司"}],"company_since":"1997-07-11","company_dissolved":"2001-12-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616848","names":[{"lang":"en","v":"FAIR HONEST INTERNATIONAL LIMITED"},{"lang":"hk","v":"均鴻國際有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616538","names":[{"lang":"en","v":"CHRISTIAN COMMUNITY LIMITED"}],"company_since":"1997-07-11","company_dissolved":"2009-11-06","company_type_txt":"Ltd by guarantee"},
{"tax_id":"616909","names":[{"lang":"en","v":"FAIRVIEW OCEAN TRADING LIMITED"},{"lang":"hk","v":"芳川行貿易有限公司"}],"company_since":"1997-07-11","company_dissolved":"2003-07-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616835","names":[{"lang":"en","v":"CITIBREEZE FINANCE LIMITED"},{"lang":"hk","v":"城和財務有限公司"}],"company_since":"1997-07-11","company_dissolved":"2014-12-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616921","names":[{"lang":"en","v":"CITIPLUS FINANCE COMPANY LIMITED"},{"lang":"hk","v":"城志財務有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616886","names":[{"lang":"en","v":"FIRST FORTUNE LIMITED (d2004-12-10)"},{"lang":"hk","v":"香港至達有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616794","names":[{"lang":"en","v":"FIRST WIN DEVELOPMENT LIMITED"},{"lang":"hk","v":"運豐發展有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616602","names":[{"lang":"en","v":"CITY GAIN HOLDINGS LIMITED (d2001-02-16)"},{"lang":"hk","v":"億港集團有限公司"}],"company_since":"1997-07-11","company_dissolved":"2001-02-16","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616626","names":[{"lang":"en","v":"FORETECK INTERNATIONAL CO., LIMITED"},{"lang":"hk","v":"科泰克國際有限公司"}],"company_since":"1997-07-11","company_dissolved":"2002-05-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616667","names":[{"lang":"en","v":"COMFORT INTERNATIONAL TRADING COMPANY, LIMITED"},{"lang":"hk","v":"宜昌貿易有限公司"}],"company_since":"1997-07-11","company_dissolved":"2013-03-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616615","names":[{"lang":"en","v":"FORWARD ELECTRONICS COMMERCIAL LIMITED"},{"lang":"hk","v":"科威電子有限公司"}],"company_since":"1997-07-11","company_dissolved":"2013-09-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616539","names":[{"lang":"en","v":"CONSERVATIVE BAPTIST MING YAN CHURCH, LIMITED"},{"lang":"hk","v":"浸信宣道會明恩堂有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
{"tax_id":"616548","names":[{"lang":"en","v":"FORCER TRADING LIMITED (d2004-12-17)"},{"lang":"hk","v":"港帝貿易有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-12-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616808","names":[{"lang":"en","v":"FUSE COMMUNICATIONS LIMITED"}],"company_since":"1997-07-11","company_dissolved":"2004-04-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616887","names":[{"lang":"en","v":"COUNTRY CAPITAL MANAGEMENT LIMITED (d2002-11-08)"},{"lang":"hk","v":"國都管理有限公司"}],"company_since":"1997-07-11","company_dissolved":"2002-11-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616636","names":[{"lang":"en","v":"GENLINK INTERNATIONAL LIMITED"},{"lang":"hk","v":"鎭聯國際有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616632","names":[{"lang":"en","v":"GLOBAL BAY LIMITED (d2002-08-30)"},{"lang":"hk","v":"啓馬有限公司"}],"company_since":"1997-07-11","company_dissolved":"2002-08-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616592","names":[{"lang":"en","v":"GLOBAL FACTOR LIMITED"},{"lang":"hk","v":"浦興有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616691","names":[{"lang":"en","v":"DIAMOND MAX LIMITED (d2005-07-15)"},{"lang":"hk","v":"鑽樂有限公司"}],"company_since":"1997-07-11","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616628","names":[{"lang":"en","v":"GLORY CENTURY (CHINA) LIMITED"},{"lang":"hk","v":"安成(中國)有限公司"}],"company_since":"1997-07-11","company_dissolved":"2000-12-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616871","names":[{"lang":"en","v":"GOAL FORTUNE LIMITED"},{"lang":"hk","v":"錦旺有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616750","names":[{"lang":"en","v":"EASTERN EXPRESS (HONG KONG) LIMITED"},{"lang":"hk","v":"東展(香港)有限公司"}],"company_since":"1997-07-11","company_dissolved":"2002-11-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616618","names":[{"lang":"en","v":"GOLD DYNAMIC INTERNATIONAL LIMITED"},{"lang":"hk","v":"金利華國際有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616611","names":[{"lang":"en","v":"GOLD FIRST INVESTMENT LIMITED"},{"lang":"hk","v":"金優投資有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616789","names":[{"lang":"en","v":"GOLD FOCUS INDUSTRIAL LIMITED"},{"lang":"hk","v":"金順實業有限公司"}],"company_since":"1997-07-11","company_dissolved":"2000-12-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616668","names":[{"lang":"en","v":"GOLD GLOBAL ASIA LIMITED"},{"lang":"hk","v":"金世亞洲有限公司"}],"company_since":"1997-07-11","company_dissolved":"2017-12-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616707","names":[{"lang":"en","v":"GOLD SYSTEM LIMITED (d2002-05-03)"},{"lang":"hk","v":"金港利有限公司"}],"company_since":"1997-07-11","company_dissolved":"2002-05-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616740","names":[{"lang":"en","v":"GOLDEN GARMENT FACTORY LIMITED"},{"lang":"hk","v":"豐盛製衣廠有限公司"}],"company_since":"1997-07-11","company_dissolved":"2000-09-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616716","names":[{"lang":"en","v":"GOLDEN KENT LIMITED (d2004-02-13)"},{"lang":"hk","v":"金競有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-02-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616706","names":[{"lang":"en","v":"GOLDEN LORD LIMITED (d2004-12-17)"},{"lang":"hk","v":"金港富有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-12-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616719","names":[{"lang":"en","v":"ETERNALANE LIMITED"},{"lang":"hk","v":"恆嶺有限公司"}],"company_since":"1997-07-11","company_dissolved":"2000-11-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616735","names":[{"lang":"en","v":"EVER DIRECTION DEVELOPMENT LIMITED (d2002-01-04)"},{"lang":"hk","v":"恆麗發展有限公司"}],"company_since":"1997-07-11","company_dissolved":"2002-01-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616893","names":[{"lang":"en","v":"GOLDEN PALARIS HOLDINGS LIMITED"},{"lang":"hk","v":"金寶來通商控股有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616694","names":[{"lang":"en","v":"EVERFUN INVESTMENTS LIMITED"},{"lang":"hk","v":"恆趣投資有限公司"}],"company_since":"1997-07-11","company_dissolved":"2010-04-01","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616788","names":[{"lang":"en","v":"GOLDEN TIME (ASIA) LIMITED (d2003-02-07)"},{"lang":"hk","v":"金信(亞洲)有限公司"}],"company_since":"1997-07-11","company_dissolved":"2003-02-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616690","names":[{"lang":"en","v":"GOLDSTICK LIMITED (d2001-04-20)"},{"lang":"hk","v":"金竹有限公司"}],"company_since":"1997-07-11","company_dissolved":"2001-04-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616635","names":[{"lang":"en","v":"GOLDWOOD INVESTMENTS LIMITED (d1999-08-29)"},{"lang":"hk","v":"金活投資有限公司"}],"company_since":"1997-07-11","company_dissolved":"1999-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616919","names":[{"lang":"en","v":"FAIRMONT HOLDINGS CO., LIMITED"},{"lang":"hk","v":"輝茂集團有限公司"}],"company_since":"1997-07-11","company_dissolved":"2002-10-25","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616799","names":[{"lang":"en","v":"GOOD DEVELOPMENTS LIMITED (HK)"},{"lang":"hk","v":"琦豐發展有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"616817","names":[{"lang":"en","v":"GRAND MALL INVESTMENTS LIMITED"},{"lang":"hk","v":"宏域投資有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616784","names":[{"lang":"en","v":"FIRST MADISON TRADING LIMITED"}],"company_since":"1997-07-11","company_dissolved":"2003-10-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616865","names":[{"lang":"en","v":"GRAND PROFIT DEVELOPMENT LIMITED"},{"lang":"hk","v":"利怡發展有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616860","names":[{"lang":"en","v":"GRAND STRONG INVESTMENT LIMITED (d2004-01-09)"},{"lang":"hk","v":"志康投資有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-01-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616700","names":[{"lang":"en","v":"GRAND SYSTEM ENTERPRISES LIMITED"},{"lang":"hk","v":"創浩企業有限公司"}],"company_since":"1997-07-11","company_dissolved":"2002-10-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"616703","names":[{"lang":"en","v":"FOREVER WEALTH DEVELOPMENT LIMITED (d2002-09-27)"},{"lang":"hk","v":"恒裕發展有限公司"}],"company_since":"1997-07-11","company_dissolved":"2002-09-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616595","names":[{"lang":"en","v":"FORTUNE BAY DEVELOPMENTS LIMITED"},{"lang":"hk","v":"進昌發展有限公司"}],"company_since":"1997-07-11","company_dissolved":"2002-11-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616629","names":[{"lang":"en","v":"GREENLAND LANDSCAPE ENGINEERING LIMITED"}],"company_since":"1997-07-11","company_dissolved":"2000-07-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616885","names":[{"lang":"en","v":"FORTUNE PATH LIMITED (d2004-12-10)"},{"lang":"hk","v":"富企有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616577","names":[{"lang":"en","v":"GROUP TARGET TRADING LIMITED"},{"lang":"hk","v":"集謙貿易有限公司"}],"company_since":"1997-07-11","company_dissolved":"2012-04-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"616540","names":[{"lang":"en","v":"FREEWAY INTERNATIONAL TRADING COMPANY LIMITED"},{"lang":"hk","v":"富惠利實業有限公司"}],"company_since":"1997-07-11","company_dissolved":"2001-10-26","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616725","names":[{"lang":"en","v":"FREEMAN UNDERWRITERS LIMITED"},{"lang":"hk","v":"自民保險顧問有限公司"}],"company_since":"1997-07-11","company_dissolved":"2006-12-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616742","names":[{"lang":"en","v":"GLOBAL EXPERT ENTERPRISES LIMITED"},{"lang":"hk","v":"跨域企業有限公司"}],"company_since":"1997-07-11","company_dissolved":"2005-03-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616689","names":[{"lang":"en","v":"HOME &amp; HEALTH CARE HOLDINGS LIMITED"},{"lang":"hk","v":"安康通控股有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616696","names":[{"lang":"en","v":"GLOBAL WEAL INTERNATIONAL LIMITED"},{"lang":"hk","v":"加匯國際有限公司"}],"company_since":"1997-07-11","company_dissolved":"2000-06-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616791","names":[{"lang":"en","v":"GOLD CHAMPION ENTERPRISES LIMITED (d2003-02-21)"},{"lang":"hk","v":"金凌企業有限公司"}],"company_since":"1997-07-11","company_dissolved":"2003-02-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616918","names":[{"lang":"en","v":"HONEST RELIANCE LIMITED"},{"lang":"hk","v":"誠熙有限公司"}],"company_since":"1997-07-11","company_dissolved":"2003-03-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616623","names":[{"lang":"en","v":"HONEST SILVER LIMITED"},{"lang":"hk","v":"銀譽有限公司"}],"company_since":"1997-07-11","company_dissolved":"2011-08-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616587","names":[{"lang":"en","v":"GOLD GUIDE INVESTMENT LIMITED"},{"lang":"hk","v":"金佳投資有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-12-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616710","names":[{"lang":"en","v":"GOLD TALENT GROUP LIMITED (d2004-12-17)"},{"lang":"hk","v":"金滔集團有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-12-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616677","names":[{"lang":"en","v":"HONG KONG SOMEN INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"香港初人國際集團有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-12-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616874","names":[{"lang":"en","v":"HONG TAK ESTATE AGENCY LIMITED"},{"lang":"hk","v":"康德物業代理有限公司"}],"company_since":"1997-07-11","company_dissolved":"2003-03-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"616907","names":[{"lang":"en","v":"HONORLUXE LIMITED"},{"lang":"hk","v":"鴻量有限公司"}],"company_since":"1997-07-11","company_dissolved":"2003-12-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616752","names":[{"lang":"en","v":"GOLDEN JOINT ENTERPRISES LIMITED"},{"lang":"hk","v":"金雋企業有限公司"}],"company_since":"1997-07-11","company_dissolved":"2006-11-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616747","names":[{"lang":"en","v":"HONOUR UNITY LIMITED"},{"lang":"hk","v":"鴻愉有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"616763","names":[{"lang":"en","v":"HOSAN INVESTMENTS LIMITED"},{"lang":"hk","v":"河山投資有限公司"}],"company_since":"1997-07-11","company_dissolved":"2001-06-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616849","names":[{"lang":"en","v":"GOLDEN MAX LIMITED (d2002-11-28)"},{"lang":"hk","v":"金量有限公司"}],"company_since":"1997-07-11","company_dissolved":"2002-11-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616912","names":[{"lang":"en","v":"HOU KING (METAL) LIMITED"},{"lang":"hk","v":"灝景(五金)有限公司"}],"company_since":"1997-07-11","company_dissolved":"2002-10-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616682","names":[{"lang":"en","v":"GOLDEN ORIENT (GROUP) DEVELOPMENT LIMITED"},{"lang":"hk","v":"金安集團發展有限公司"}],"company_since":"1997-07-11","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616914","names":[{"lang":"en","v":"HUGE BENEFIT DEVELOPMENT LIMITED"},{"lang":"hk","v":"宏益發展有限公司"}],"company_since":"1997-07-11","company_dissolved":"2001-12-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616867","names":[{"lang":"en","v":"GOLDEN ROAD LIMITED (d2002-07-05)"}],"company_since":"1997-07-11","company_dissolved":"2002-07-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616614","names":[{"lang":"en","v":"HUTECH ENTERPRISES LIMITED"},{"lang":"hk","v":"厚達企業有限公司"}],"company_since":"1997-07-11","company_dissolved":"2002-04-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616922","names":[{"lang":"en","v":"INTERACTIVE DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"互動發展有限公司"}],"company_since":"1997-07-11","company_dissolved":"2012-06-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616723","names":[{"lang":"en","v":"GOMATECH DEVELOPMENT (HK) LIMITED"},{"lang":"hk","v":"香港創統科技發展有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-12-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616586","names":[{"lang":"en","v":"GOOD MASTER ENTERPRISES LIMITED"},{"lang":"hk","v":"金勝企業有限公司"}],"company_since":"1997-07-11","company_dissolved":"2002-09-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616880","names":[{"lang":"en","v":"INTERACTIVE PROPERTIES COMPANY LIMITED"},{"lang":"hk","v":"互動物業有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"616883","names":[{"lang":"en","v":"GRAND CHANCE INVESTMENT LIMITED (d2005-07-15)"},{"lang":"hk","v":"登極投資有限公司"}],"company_since":"1997-07-11","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616837","names":[{"lang":"en","v":"JEC INTERNATIONAL (HK) CO. LIMITED"},{"lang":"hk","v":"永華國際(香港)有限公司"}],"company_since":"1997-07-11","company_dissolved":"2007-11-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616818","names":[{"lang":"en","v":"GRAND MART DEVELOPMENT LIMITED"},{"lang":"hk","v":"宏域發展有限公司"}],"company_since":"1997-07-11","company_dissolved":"2007-07-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616858","names":[{"lang":"en","v":"JOINERS COMPANY LIMITED"},{"lang":"hk","v":"經倫有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-08-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616582","names":[{"lang":"en","v":"HONG KONG NAN TAI TRADING COMPANY LIMITED"},{"lang":"hk","v":"香港南泰貿易有限公司"}],"company_since":"1997-07-11","company_dissolved":"2011-03-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616812","names":[{"lang":"en","v":"KAM LUEN SECURITIES LIMITED"},{"lang":"hk","v":"金鑾證券有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616713","names":[{"lang":"en","v":"KANDIN HOLDINGS LIMITED"},{"lang":"hk","v":"金典集團有限公司"}],"company_since":"1997-07-11","company_dissolved":"2015-07-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"616869","names":[{"lang":"en","v":"GREAT SPACE (HONG KONG) INVESTMENT AND DEVELOPMENT CO., LIMITED"},{"lang":"hk","v":"香港弘宇投資發展有限公司"}],"company_since":"1997-07-11","company_dissolved":"2006-11-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616699","names":[{"lang":"en","v":"GRAND SYSTEM HOLDINGS LIMITED"},{"lang":"hk","v":"創浩集團有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-12-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616800","names":[{"lang":"en","v":"KING ASIA DEVELOPMENTS LIMITED"},{"lang":"hk","v":"敬賢發展有限公司"}],"company_since":"1997-07-11","company_dissolved":"2001-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616643","names":[{"lang":"en","v":"KING TACT INTERNATIONAL LIMITED"},{"lang":"hk","v":"皇達國際有限公司"}],"company_since":"1997-07-11","company_dissolved":"2006-04-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616758","names":[{"lang":"en","v":"KINGS FOOTWEAR LIMITED"},{"lang":"hk","v":"皇城鞋業有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"616780","names":[{"lang":"en","v":"H.K. SCAFFRAME SYSTEM LIMITED"},{"lang":"hk","v":"加豐棚架有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"616908","names":[{"lang":"en","v":"KROTA SEA-LAND TRANSPORTATION LIMITED"}],"company_since":"1997-07-11","company_dissolved":"2003-11-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616910","names":[{"lang":"en","v":"HIN HUNG DEVELOPMENT CO., LIMITED"},{"lang":"hk","v":"顯鴻發展有限公司"}],"company_since":"1997-07-11","company_dissolved":"2003-04-25","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616681","names":[{"lang":"en","v":"LAWDION REAL ESTATE LIMITED"},{"lang":"hk","v":"諾林地產有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616855","names":[{"lang":"en","v":"HIN HUNG HOLDINGS (H.K.) CO., LIMITED"},{"lang":"hk","v":"顯鴻控股(香港)有限公司"}],"company_since":"1997-07-11","company_dissolved":"2003-04-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616840","names":[{"lang":"en","v":"HON KEE NOODLE FACTORY LIMITED"},{"lang":"hk","v":"漢記粉麵廠有限公司"}],"company_since":"1997-07-11","company_dissolved":"2009-12-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616727","names":[{"lang":"en","v":"LI ZHONG INTERNATIONAL LIMITED"},{"lang":"hk","v":"立眾國際有限公司"}],"company_since":"1997-07-11","company_dissolved":"2002-12-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616655","names":[{"lang":"en","v":"LINDENBAUM INTERNATIONAL LIMITED"},{"lang":"hk","v":"大丸精肉店有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616926","names":[{"lang":"en","v":"HONORLUX DEVELOPMENT INTERNATIONAL LIMITED"},{"lang":"hk","v":"集浩發展國際有限公司"}],"company_since":"1997-07-11","company_dissolved":"2002-03-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"616624","names":[{"lang":"en","v":"LOYAL FIELD INTERNATIONAL LIMITED"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616564","names":[{"lang":"en","v":"HONG KONG INTERNATIONAL ENERGY DEVELOPMENT LIMITED"},{"lang":"hk","v":"香港國際能源發展有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616584","names":[{"lang":"en","v":"LOYAL REGENT INVESTMENT LIMITED"},{"lang":"hk","v":"銀朗投資有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616649","names":[{"lang":"en","v":"MANDO INTERNATIONAL LIMITED"},{"lang":"hk","v":"車中龍國際有限公司"}],"company_since":"1997-07-11","company_dissolved":"2009-04-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616680","names":[{"lang":"en","v":"MARC &amp; CHANTAL DESIGN LIMITED"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616686","names":[{"lang":"en","v":"MAT CARGO SERVICES LIMITED"},{"lang":"hk","v":"萬里貨運有限公司"}],"company_since":"1997-07-11","company_dissolved":"2019-07-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616826","names":[{"lang":"en","v":"INNOPAC PACKAGING SERVICES LIMITED"},{"lang":"hk","v":"鷹亮包裝系統服務有限公司"}],"company_since":"1997-07-11","company_dissolved":"2001-02-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616656","names":[{"lang":"en","v":"HORIZON CORPORATION (ASIA) LIMITED"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616683","names":[{"lang":"en","v":"MEGA FIRST MACHINERY COMPANY LIMITED"},{"lang":"hk","v":"萬利卓機械有限公司"}],"company_since":"1997-07-11","company_dissolved":"2003-02-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616875","names":[{"lang":"en","v":"MERLIN TOOLS COMPANY LIMITED (THE)"},{"lang":"hk","v":"武慶有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616760","names":[{"lang":"en","v":"HUGE WIDE INTERNATIONAL LIMITED"},{"lang":"hk","v":"宏煒國際有限公司"}],"company_since":"1997-07-11","company_dissolved":"2002-08-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616872","names":[{"lang":"en","v":"METRO JOY LIMITED (d2004-12-10)"},{"lang":"hk","v":"錦浚有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616905","names":[{"lang":"en","v":"HUMPHREY &amp; PARTNERS MEDICAL SERVICES LIMITED"},{"lang":"hk","v":"綜合醫務集團有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616894","names":[{"lang":"en","v":"MILLION STAR ASSETS LIMITED (d2003-10-03)"},{"lang":"hk","v":"萬星資產有限公司"}],"company_since":"1997-07-11","company_dissolved":"2003-10-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616841","names":[{"lang":"en","v":"INTERACTIVE FINANCE COMPANY LIMITED"},{"lang":"hk","v":"互動財務有限公司"}],"company_since":"1997-07-11","company_dissolved":"2006-10-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616571","names":[{"lang":"en","v":"MIX FAIR LABELS COMPANY LIMITED"},{"lang":"hk","v":"美和商標有限公司"}],"company_since":"1997-07-11","company_dissolved":"2002-11-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616661","names":[{"lang":"en","v":"MOLECULAR TECHNOLOGY INNOMED LIMITED"},{"lang":"hk","v":"創念分子科技有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616541","names":[{"lang":"en","v":"JAY COMPANY LIMITED"}],"company_since":"1997-07-11","company_dissolved":"2002-05-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616762","names":[{"lang":"en","v":"NATIONAL PROFIT INVESTMENT LIMITED"},{"lang":"hk","v":"利城投資有限公司"}],"company_since":"1997-07-11","company_dissolved":"2008-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"616616","names":[{"lang":"en","v":"KAM KEE WATCH CO. (INTERNATIONAL) LIMITED"},{"lang":"hk","v":"錦記表行(國際)有限公司"}],"company_since":"1997-07-11","company_dissolved":"2005-10-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616574","names":[{"lang":"en","v":"NEFFUL LIMITED"},{"lang":"hk","v":"香港妮芙露有限公司"}],"company_since":"1997-07-11","company_dissolved":"2003-05-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616640","names":[{"lang":"en","v":"NEW FOND HOLDINGS LIMITED (d2001-02-16)"},{"lang":"hk","v":"新鋒集團有限公司"}],"company_since":"1997-07-11","company_dissolved":"2001-02-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616702","names":[{"lang":"en","v":"KENBOND INTERNATIONAL LIMITED"},{"lang":"hk","v":"建倡國際有限公司"}],"company_since":"1997-07-11","company_dissolved":"2002-07-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616847","names":[{"lang":"en","v":"KING PROFIT (ASIA) LIMITED (d2003-04-04)"},{"lang":"hk","v":"均潤(亞洲)有限公司"}],"company_since":"1997-07-11","company_dissolved":"2003-04-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616825","names":[{"lang":"en","v":"KING WAI METAL COMPANY LIMITED"},{"lang":"hk","v":"經緯金屬壓鑄製品廠有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616803","names":[{"lang":"en","v":"KOLL ASIA PACIFIC INVESTMENT MANAGEMENT"}],"company_since":"1997-07-11","company_dissolved":"2002-04-26","company_type_txt":"Private unlimited company"},
undefined,
{"tax_id":"616591","names":[{"lang":"en","v":"OCEAN VALUE LIMITED"},{"lang":"hk","v":"海都有限公司"}],"company_since":"1997-07-11","company_dissolved":"2005-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616543","names":[{"lang":"en","v":"KONG TUNG MOTORS CO. LIMITED"},{"lang":"hk","v":"港通車行有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616787","names":[{"lang":"en","v":"ONNY SOLE AGENCY COMPANY LIMITED"},{"lang":"hk","v":"安利總代理有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-12-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616870","names":[{"lang":"en","v":"OPTECK INTERNATIONAL LIMITED"},{"lang":"hk","v":"傲視國際有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616651","names":[{"lang":"en","v":"KOREA INVESTMENT &amp; SECURITIES ASIA LIMITED"},{"lang":"hk","v":"韓國投資證券亞洲有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616654","names":[{"lang":"en","v":"LAWRENCE CHAN INVESTMENTS &amp; MANAGEMENT CONSULTANTS LIMITED"},{"lang":"hk","v":"陳景鴻投資及行政顧問有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-12-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616547","names":[{"lang":"en","v":"ORIENTAL STAR LIMITED (HK)"},{"lang":"hk","v":"東方企業有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"616899","names":[{"lang":"en","v":"LEADER (ASIA) LIMITED"},{"lang":"hk","v":"利成(亞洲)有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616853","names":[{"lang":"en","v":"PACIFIC TECHNOLOGY COMPANY (H.K.) LIMITED"},{"lang":"hk","v":"柏思域科技有限公司"}],"company_since":"1997-07-11","company_dissolved":"2001-08-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616832","names":[{"lang":"en","v":"PAM PACIFIC PROPERTIES LIMITED (d2005-07-15)"},{"lang":"hk","v":"華揚地產有限公司"}],"company_since":"1997-07-11","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"616685","names":[{"lang":"en","v":"LONG HING COLOUR PRINTING LIMITED"},{"lang":"hk","v":"龍興彩印紙品股份有限公司"}],"company_since":"1997-07-11","company_dissolved":"2014-01-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616665","names":[{"lang":"en","v":"LOYAL ASIAN INVESTMENT LIMITED"},{"lang":"hk","v":"銀亞投資有限公司"}],"company_since":"1997-07-11","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616917","names":[{"lang":"en","v":"Lucky Auspicious Trading Limited"},{"lang":"hk","v":"善吉貿易有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616878","names":[{"lang":"en","v":"PLANETIME ENTERPRISES COMPANY LIMITED"},{"lang":"hk","v":"恆時企業有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616724","names":[{"lang":"en","v":"M. W. PROFESSIONAL SWIMMING POOL SERVICE LIMITED"},{"lang":"hk","v":"明華專業泳池管理有限公司"}],"company_since":"1997-07-11","company_dissolved":"2005-11-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616920","names":[{"lang":"en","v":"PLANETOP INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"運行國際有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616881","names":[{"lang":"en","v":"PLANETOP PROPERTIES COMPANY LIMITED"},{"lang":"hk","v":"運行物業有限公司"}],"company_since":"1997-07-11","company_dissolved":"2020-07-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616783","names":[{"lang":"en","v":"MAXWEAL ENTERPRISES LIMITED"},{"lang":"hk","v":"萬佳企業有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-12-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616605","names":[{"lang":"en","v":"POLY RAY DEVELOPMENT LIMITED"},{"lang":"hk","v":"寶時發展有限公司"}],"company_since":"1997-07-11","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"616793","names":[{"lang":"en","v":"POWER GROUP DEVELOPMENT LIMITED (d2003-03-07)"},{"lang":"hk","v":"金力發展有限公司"}],"company_since":"1997-07-11","company_dissolved":"2003-03-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616745","names":[{"lang":"en","v":"MEIJI TRADING LIMITED"},{"lang":"hk","v":"美智貿易有限公司"}],"company_since":"1997-07-11","company_dissolved":"2009-06-05","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616842","names":[{"lang":"en","v":"PRAWIT COMPANY LIMITED"},{"lang":"hk","v":"漢全有限公司"}],"company_since":"1997-07-11","company_dissolved":"2006-11-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616676","names":[{"lang":"en","v":"HONG KONG KWAN LAM BAMBOO &amp; WOODEN ARTS CRAFTS I/E LIMITED"},{"lang":"hk","v":"香港君臨竹木工藝進出口有限公司"}],"company_since":"1997-07-11","company_dissolved":"2002-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616775","names":[{"lang":"en","v":"PRIME STATE LIMITED (d2004-12-17)"},{"lang":"hk","v":"譽豪有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-12-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616662","names":[{"lang":"en","v":"MILITANT ENTERPRISES LIMITED"},{"lang":"hk","v":"華晟企業有限公司"}],"company_since":"1997-07-11","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"616866","names":[{"lang":"en","v":"PROFITWAY DEVELOPMENT LIMITED"},{"lang":"hk","v":"利正發展有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616565","names":[{"lang":"en","v":"PROGRESS PACKAGING INDUSTRIAL CO. LIMITED"},{"lang":"hk","v":"勵群包裝實業有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"616814","names":[{"lang":"en","v":"NATURAL LOYAL LIMITED"},{"lang":"hk","v":"逸來有限公司"}],"company_since":"1997-07-11","company_dissolved":"2003-07-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616781","names":[{"lang":"en","v":"REGAL PART INTERNATIONAL LIMITED"},{"lang":"hk","v":"皇牌國際有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-07-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616767","names":[{"lang":"en","v":"REGENT STEP DEVELOPMENT LIMITED (d2001-10-12)"},{"lang":"hk","v":"駿富發展有限公司"}],"company_since":"1997-07-11","company_dissolved":"2001-10-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616774","names":[{"lang":"en","v":"REX HONOUR LIMITED"},{"lang":"hk","v":"立康有限公司"}],"company_since":"1997-07-11","company_dissolved":"2016-03-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616705","names":[{"lang":"en","v":"NEW GOLD LIMITED"},{"lang":"hk","v":"金浩有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616688","names":[{"lang":"en","v":"RICHTRON LIMITED"},{"lang":"hk","v":"財聲有限公司"}],"company_since":"1997-07-11","company_dissolved":"2001-02-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616556","names":[{"lang":"en","v":"NIKKOH TRADING (HK) CO. LIMITED"}],"company_since":"1997-07-11","company_dissolved":"2005-04-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616559","names":[{"lang":"en","v":"ROCKY KITCHEN &amp; BATH LIMITED"},{"lang":"hk","v":"樂家廚櫃潔具有限公司"}],"company_since":"1997-07-11","company_dissolved":"2008-06-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616672","names":[{"lang":"en","v":"SEA PLENTY MARINE ENTERPRISE CORP. LIMITED"},{"lang":"hk","v":"海盛航業股份有限公司"}],"company_since":"1997-07-11","company_dissolved":"2002-09-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616821","names":[{"lang":"en","v":"SHAPE PATCH (HONG KONG) LIMITED"},{"lang":"hk","v":"儷人行有限公司"}],"company_since":"1997-07-11","company_dissolved":"2010-06-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616868","names":[{"lang":"en","v":"ORIENT JADE INTERNATIONAL LIMITED"},{"lang":"hk","v":"東翠國際有限公司"}],"company_since":"1997-07-11","company_dissolved":"2000-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616542","names":[{"lang":"en","v":"ORIENTAL RELIANCE LIMITED"},{"lang":"hk","v":"信灝有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-12-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616581","names":[{"lang":"en","v":"ORIENTAL RESOURCE INTERNATIONAL DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"東源國際發展有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616828","names":[{"lang":"en","v":"SHUI TAI CONSTRUCTION ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"順泰建築工程有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616663","names":[{"lang":"en","v":"SILVER ALLIANCE LIMITED (d2009-11-27)"},{"lang":"hk","v":"銀正有限公司"}],"company_since":"1997-07-11","company_dissolved":"2009-11-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"616809","names":[{"lang":"en","v":"PANASIA GROUP LIMITED"},{"lang":"hk","v":"榮陽集團有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616578","names":[{"lang":"en","v":"SILVER EPOCH INTERNATIONAL LIMITED"},{"lang":"hk","v":"銀紀國際有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616612","names":[{"lang":"en","v":"SILVER FAR INTERNATIONAL LIMITED"},{"lang":"hk","v":"銀遠國際有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-12-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616882","names":[{"lang":"en","v":"PARTY ELECTRONIC COMPANY LIMITED"},{"lang":"hk","v":"柏迪電子有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616646","names":[{"lang":"en","v":"PEAK LINK LIMITED"},{"lang":"hk","v":"柏聯行有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616924","names":[{"lang":"en","v":"PLANETOP INVESTMENT COMPANY LIMITED"},{"lang":"hk","v":"運行投資有限公司"}],"company_since":"1997-07-11","company_dissolved":"2020-10-16","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616625","names":[{"lang":"en","v":"SILVER NOBEL INTERNATIONAL LIMITED"},{"lang":"hk","v":"銀爵國際有限公司"}],"company_since":"1997-07-11","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616601","names":[{"lang":"en","v":"POWER BASE HOLDINGS LIMITED"},{"lang":"hk","v":"力豪集團有限公司"}],"company_since":"1997-07-11","company_dissolved":"2017-08-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616607","names":[{"lang":"en","v":"POWER TARGET LIMITED (d2019-11-08)"},{"lang":"hk","v":"凌致有限公司"}],"company_since":"1997-07-11","company_dissolved":"2019-11-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616620","names":[{"lang":"en","v":"SILVER SENSE INVESTMENT LIMITED"},{"lang":"hk","v":"銀順投資有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-12-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616572","names":[{"lang":"en","v":"SINO INDUSTRIAL ENTERPRISES LIMITED"},{"lang":"hk","v":"中興行企業有限公司"}],"company_since":"1997-07-11","company_dissolved":"2009-04-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"616563","names":[{"lang":"en","v":"PRIME MASTER ENGINEERING &amp; SUPPLY LIMITED"},{"lang":"hk","v":"一本工程有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616639","names":[{"lang":"en","v":"SKY WORLD (ASIA) LIMITED (d2002-10-11)"},{"lang":"hk","v":"天源(亞洲)有限公司"}],"company_since":"1997-07-11","company_dissolved":"2002-10-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"616843","names":[{"lang":"en","v":"STAMPS EXCHANGE OF CHINA LIMITED (THE)"},{"lang":"hk","v":"中國郵票聯合交易所有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-12-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616859","names":[{"lang":"en","v":"STAR MART LIMITED"}],"company_since":"1997-07-11","company_dissolved":"2012-06-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"616854","names":[{"lang":"en","v":"STRATCOM, LIMITED"}],"company_since":"1997-07-11","company_dissolved":"2007-04-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"616806","names":[{"lang":"en","v":"SUN RISE TRADING (HK) LIMITED"},{"lang":"hk","v":"日晶貿易(香港)有限公司"}],"company_since":"1997-07-11","company_dissolved":"2006-12-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616695","names":[{"lang":"en","v":"SUNBAY LIMITED (d2003-02-21)"},{"lang":"hk","v":"錦澤有限公司"}],"company_since":"1997-07-11","company_dissolved":"2003-02-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"616903","names":[{"lang":"en","v":"SHEEN UNICORN LIMITED"},{"lang":"hk","v":"順愉有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616824","names":[{"lang":"en","v":"SHENG JIE DECORATION, DESIGN AND CONSTRUCTION LIMITED"},{"lang":"hk","v":"昇杰裝飾設計工程有限公司"}],"company_since":"1997-07-11","company_dissolved":"2000-11-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616733","names":[{"lang":"en","v":"TOP KIND INTERNATIONAL LIMITED (d2005-08-26)"},{"lang":"hk","v":"藝寶國際有限公司"}],"company_since":"1997-07-11","company_dissolved":"2005-08-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616596","names":[{"lang":"en","v":"SHINETOWN INVESTMENTS LIMITED"},{"lang":"hk","v":"信京投資有限公司"}],"company_since":"1997-07-11","company_dissolved":"2010-06-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616567","names":[{"lang":"en","v":"SILVER BEST LIMITED (d2011-12-09)"},{"lang":"hk","v":"銀景有限公司"}],"company_since":"1997-07-11","company_dissolved":"2011-12-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616693","names":[{"lang":"en","v":"TOWNWELL INVESTMENTS LIMITED (d2011-03-25)"},{"lang":"hk","v":"建益投資有限公司"}],"company_since":"1997-07-11","company_dissolved":"2011-03-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616568","names":[{"lang":"en","v":"SILVER ACCESS INTERNATIONAL LIMITED"},{"lang":"hk","v":"銀京國際有限公司"}],"company_since":"1997-07-11","company_dissolved":"2005-10-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616753","names":[{"lang":"en","v":"SHEEN CONCORD (HONG KONG) LIMITED"},{"lang":"hk","v":"順廣(香港)有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-12-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"616782","names":[{"lang":"en","v":"RITEK CONSULTANTS LIMITED"},{"lang":"hk","v":"澤基顧問有限公司"}],"company_since":"1997-07-11","company_dissolved":"2005-12-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616906","names":[{"lang":"en","v":"TRINITY PRESTIGE LIMITED"},{"lang":"hk","v":"通沛有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"616892","names":[{"lang":"en","v":"TRIUMPH (HK) FINANCIAL CONSULTING LIMITED"},{"lang":"hk","v":"安瑞達(香港)財務顧問有限公司"}],"company_since":"1997-07-11","company_dissolved":"2013-09-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616671","names":[{"lang":"en","v":"SILVER FULL INVESTMENT LIMITED"},{"lang":"hk","v":"銀滿投資有限公司"}],"company_since":"1997-07-11","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616641","names":[{"lang":"en","v":"RICH FOND ENTERPRISES LIMITED"},{"lang":"hk","v":"富鋒企業有限公司"}],"company_since":"1997-07-11","company_dissolved":"2001-03-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616610","names":[{"lang":"en","v":"SILVER GLOBAL INVESTMENT LIMITED"},{"lang":"hk","v":"銀世投資有限公司"}],"company_since":"1997-07-11","company_dissolved":"2010-06-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616827","names":[{"lang":"en","v":"RICH &amp; HARVEST INTERNATIONAL LIMITED"},{"lang":"hk","v":"豐群國際有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-12-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616647","names":[{"lang":"en","v":"ULTRA ACTIVE TECHNOLOGY LIMITED"},{"lang":"hk","v":"超敏科技有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"616850","names":[{"lang":"en","v":"UNION ETERNITY INVESTMENTS LIMITED"},{"lang":"hk","v":"永愉投資有限公司"}],"company_since":"1997-07-11","company_dissolved":"2007-11-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616815","names":[{"lang":"en","v":"UNION PRIVILEGE LIMITED"},{"lang":"hk","v":"沛愉有限公司"}],"company_since":"1997-07-11","company_dissolved":"2013-02-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616670","names":[{"lang":"en","v":"SILVER NOBEL LIMITED"},{"lang":"hk","v":"銀覇有限公司"}],"company_since":"1997-07-11","company_dissolved":"2003-12-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616721","names":[{"lang":"en","v":"VANCO (ASIA) LIMITED (d2004-12-17)"},{"lang":"hk","v":"宏高(亞洲)有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-12-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616864","names":[{"lang":"en","v":"VIEW BRIGHT HOLDINGS LIMITED"},{"lang":"hk","v":"利暉集團有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616900","names":[{"lang":"en","v":"VIVIAN (ASIA) LIMITED"},{"lang":"hk","v":"利宏(亞洲)有限公司"}],"company_since":"1997-07-11","company_dissolved":"2001-10-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616561","names":[{"lang":"en","v":"SILVERTONE ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"銀通工程有限公司"}],"company_since":"1997-07-11","company_dissolved":"2009-02-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616675","names":[{"lang":"en","v":"WAH SHING MOTORS (CHINA) TRADING COMPANY LIMITED"},{"lang":"hk","v":"華城汽車(中國)貿易有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"616704","names":[{"lang":"en","v":"SKY CHANCE INVESTMENT LIMITED (d2000-12-15)"},{"lang":"hk","v":"天匯投資有限公司"}],"company_since":"1997-07-11","company_dissolved":"2000-12-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616585","names":[{"lang":"en","v":"SILVER VENTURE INTERNATIONAL LIMITED (d2000-08-18)"},{"lang":"hk","v":"銀傑國際有限公司"}],"company_since":"1997-07-11","company_dissolved":"2000-08-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616732","names":[{"lang":"en","v":"WAVE TARGET DEVELOPMENT LIMITED (d2004-12-17)"},{"lang":"hk","v":"盛龍發展有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-12-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"616653","names":[{"lang":"en","v":"WEB BUSINESS LIMITED"},{"lang":"hk","v":"域事達網絡有限公司"}],"company_since":"1997-07-11","company_dissolved":"2003-02-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616839","names":[{"lang":"en","v":"SPARK PRODUCTION COMPANY LIMITED"},{"lang":"hk","v":"振邦影業有限公司"}],"company_since":"1997-07-11","company_dissolved":"2007-03-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616731","names":[{"lang":"en","v":"WINTON GRANT INTERNATIONAL LIMITED"},{"lang":"hk","v":"新達國際有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616692","names":[{"lang":"en","v":"SUI CHANG CHINA LIMITED"},{"lang":"hk","v":"瑞祥中國有限公司"}],"company_since":"1997-07-11","company_dissolved":"2001-10-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616889","names":[{"lang":"en","v":"SUNGDO (H.K.) INTERNATIONAL LIMITED"}],"company_since":"1997-07-11","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616925","names":[{"lang":"en","v":"WONDERFUL WINE COMPANY LIMITED"},{"lang":"hk","v":"鴻軒中西酒行有限公司"}],"company_since":"1997-07-11","company_dissolved":"2002-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616757","names":[{"lang":"en","v":"TAK SHUN CONTRACTING LIMITED"},{"lang":"hk","v":"德信建設有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616838","names":[{"lang":"en","v":"XIONG YI WU INDUSTRY CO., LIMITED"},{"lang":"hk","v":"熊毅武實業有限公司"}],"company_since":"1997-07-11","company_dissolved":"2006-06-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616580","names":[{"lang":"en","v":"YANG GANG CASTING CORPORATION LIMITED"},{"lang":"hk","v":"揚鋼鑄造股份有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-12-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616765","names":[{"lang":"en","v":"TOP FAME DEVELOPMENT LIMITED (d2004-12-17)"},{"lang":"hk","v":"泰洋發展有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-12-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"616657","names":[{"lang":"en","v":"YU HSIANG INDUSTRIAL CO. LIMITED"},{"lang":"hk","v":"宇翔工業有限公司"}],"company_since":"1997-07-11","company_dissolved":"2004-12-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"616554","names":[{"lang":"en","v":"TEAM POWER ELECTRIC MANUFACTURING COMPANY LIMITED"},{"lang":"hk","v":"添寶電器製造有限公司"}],"company_since":"1997-07-11","company_dissolved":"2002-09-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616650","names":[{"lang":"en","v":"YUAN ZI COMPANY LIMITED"},{"lang":"hk","v":"元子有限公司"}],"company_since":"1997-07-11","company_dissolved":"2006-02-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616674","names":[{"lang":"en","v":"YUEN HING HONG ENTERPRISES COMPANY LIMITED"},{"lang":"hk","v":"源興行企業有限公司"}],"company_since":"1997-07-11","company_dissolved":"2002-08-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"616741","names":[{"lang":"en","v":"TAK YICK ELECTRICAL &amp; MECHANICAL ENGINEERING LIMITED"},{"lang":"hk","v":"德益機電工程有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"616796","names":[{"lang":"en","v":"TIFON LIMITED"},{"lang":"hk","v":"迪鋒有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616698","names":[{"lang":"en","v":"TOP CHANCE (HONG KONG) LIMITED (d2003-03-21)"},{"lang":"hk","v":"永源(香港)有限公司"}],"company_since":"1997-07-11","company_dissolved":"2003-03-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"616779","names":[{"lang":"en","v":"SUPRA DEVELOPMENTS LIMITED"},{"lang":"hk","v":"至尊發展有限公司"}],"company_since":"1997-07-11","company_dissolved":"2013-09-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"616590","names":[{"lang":"en","v":"RAINFIELD LIMITED (d2001-06-15)"},{"lang":"hk","v":"虹輝有限公司"}],"company_since":"1997-07-11","company_dissolved":"2001-06-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"616904","names":[{"lang":"en","v":"WANSON (ASIA) LIMITED"},{"lang":"hk","v":"宏順(亞洲)有限公司"}],"company_since":"1997-07-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
