{"tax_id":"705877","names":[{"lang":"en","v":"Chatham Group Holdings Company Limited"},{"lang":"hk","v":"昇御集團控股有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706054","names":[{"lang":"en","v":"CHEER UNITED LIMITED (d2008-10-31)"},{"lang":"hk","v":"志晉有限公司"}],"company_since":"2000-03-01","company_dissolved":"2008-10-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705990","names":[{"lang":"en","v":"CHERVON SERVICES LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2014-05-11","company_type_txt":"Private, ltd by shares"},
{"tax_id":"705886","names":[{"lang":"en","v":"CHEUK WAH INNOVATION ELECTRONICS LIMITED"},{"lang":"hk","v":"卓華開創電子有限公司"}],"company_since":"2000-03-01","company_dissolved":"2003-11-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705983","names":[{"lang":"en","v":"CHEUNG KAI WAN TRAVEL CO., LIMITED"},{"lang":"hk","v":"長佳運旅遊有限公司"}],"company_since":"2000-03-01","company_dissolved":"2003-03-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705827","names":[{"lang":"en","v":"CHI SHING TRANSPORT COMPANY LIMITED"},{"lang":"hk","v":"志成運輸有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705788","names":[{"lang":"en","v":"CHIKO TECHNOLOGY LIMITED"},{"lang":"hk","v":"捷高科技有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705911","names":[{"lang":"en","v":"CHINA APPLIANCES.COM (HK) LIMITED"},{"lang":"hk","v":"中國家電網(香港)有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706039","names":[{"lang":"en","v":"CHINA HILL INTERNATIONAL LIMITED (d2003-09-05)"},{"lang":"hk","v":"創恒國際有限公司"}],"company_since":"2000-03-01","company_dissolved":"2003-09-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706212","names":[{"lang":"en","v":"CHINA NONFERROUS METALS CYBERNETIC BUSINESS (H.K.) LIMITED"},{"lang":"hk","v":"中國有色金屬(香港)電子商務有限公司"}],"company_since":"2000-03-01","company_dissolved":"2006-03-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705757","names":[{"lang":"en","v":"CHINA PHARMACEUTICAL CO. LIMITED"},{"lang":"hk","v":"中國醫藥網有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-12-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705991","names":[{"lang":"en","v":"CHINA SHANGHAI HUMAN RESOURCES CO., LIMITED"},{"lang":"hk","v":"中國上海人力資源有限公司"}],"company_since":"2000-03-01","company_dissolved":"2002-08-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705941","names":[{"lang":"en","v":"CHINA TOP OVERSEAS COMPANY LIMITED"},{"lang":"hk","v":"中遠石化國際(海外)有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706166","names":[{"lang":"en","v":"CHINAMARKET.NET LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2002-03-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706070","names":[{"lang":"en","v":"CN2U MULTI-MEDIA COMPANY LIMITED"},{"lang":"hk","v":"中國門多媒體有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-01-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706068","names":[{"lang":"en","v":"CN2U TECHNOLOGY COMPANY LIMITED"},{"lang":"hk","v":"中國門科技有限公司"}],"company_since":"2000-03-01","company_dissolved":"2006-07-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705834","names":[{"lang":"en","v":"CONTROL AUTOMATION LIMITED (HK)"},{"lang":"hk","v":"卓程儀控有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705850","names":[{"lang":"en","v":"CYBER CHAMPION LIMITED (d2002-11-15)"},{"lang":"hk","v":"惠科有限公司"}],"company_since":"2000-03-01","company_dissolved":"2002-11-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705805","names":[{"lang":"en","v":"CHINA PIONEER (HONG KONG) LIMITED (d2003-03-28)"},{"lang":"hk","v":"國昌(香港)有限公司"}],"company_since":"2000-03-01","company_dissolved":"2003-03-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"705831","names":[{"lang":"en","v":"CYBER DRAGON TRADING LIMITED"},{"lang":"hk","v":"康龍貿易有限公司"}],"company_since":"2000-03-01","company_dissolved":"2003-12-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705824","names":[{"lang":"en","v":"CYBER SINO LIMITED"},{"lang":"hk","v":"科中有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-12-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705999","names":[{"lang":"en","v":"CYBER SMART INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"科訊國際發展有限公司"}],"company_since":"2000-03-01","company_dissolved":"2009-07-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705825","names":[{"lang":"en","v":"CYBER VICTORY LIMITED"},{"lang":"hk","v":"科廣有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706077","names":[{"lang":"en","v":"CYBERCONVERGENCE CORPORATION LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2002-06-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"706215","names":[{"lang":"en","v":"CYBERENGINEERING COMPANY LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2002-10-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"706185","names":[{"lang":"en","v":"CORIDORAS COMPUTER &amp; SOFTWARE TECHNOLOGY LIMITED"},{"lang":"hk","v":"高力氏軟件技術有限公司"}],"company_since":"2000-03-01","company_dissolved":"2008-08-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"706085","names":[{"lang":"en","v":"CYBERNATION EDUCATION TECHNOLOGY COMPANY LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2003-10-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705900","names":[{"lang":"en","v":"CPA Global (Asia) Limited"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"706083","names":[{"lang":"en","v":"CYBERNATION ENGINEERING TECHNOLOGY COMPANY LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2003-06-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"706020","names":[{"lang":"en","v":"CHUNG WING FRUITS COMPANY LIMITED"},{"lang":"hk","v":"鍾榮欄有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706066","names":[{"lang":"en","v":"CHINAMAX INDUSTRIES LIMITED (d2005-04-29)"},{"lang":"hk","v":"中貿實業有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-04-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706179","names":[{"lang":"en","v":"DAWAY LIMITED (d2004-06-18)"},{"lang":"hk","v":"登偉有限公司"}],"company_since":"2000-03-01","company_dissolved":"2004-06-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705864","names":[{"lang":"en","v":"CYPRESS TECHNOLOGY LIMITED (d2007-07-13)"},{"lang":"hk","v":"科栢技術有限公司"}],"company_since":"2000-03-01","company_dissolved":"2007-07-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705918","names":[{"lang":"en","v":"CREATIVE PRO (ASIA) LIMITED"},{"lang":"hk","v":"盈卓(亞洲)有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"706080","names":[{"lang":"en","v":"CYBERNATION ENTERTAINMENT COMPANY LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2002-10-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705980","names":[{"lang":"en","v":"DIGIT GLOBAL LIMITED (d2007-09-28)"},{"lang":"hk","v":"德毅誠有限公司"}],"company_since":"2000-03-01","company_dissolved":"2007-09-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705888","names":[{"lang":"en","v":"DIGITAL DOCUMENT LIMITED"},{"lang":"hk","v":"數碼倉庫有限公司"}],"company_since":"2000-03-01","company_dissolved":"2001-08-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705738","names":[{"lang":"en","v":"CROWN STAR LIMITED (d2005-12-16)"},{"lang":"hk","v":"君星有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-12-16","company_type_txt":"Private, ltd by shares"},
{"tax_id":"705819","names":[{"lang":"en","v":"DIGITAL SINO LIMITED"},{"lang":"hk","v":"訊迪有限公司"}],"company_since":"2000-03-01","company_dissolved":"2015-10-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706099","names":[{"lang":"en","v":"CONCEPT T LIMITED"},{"lang":"hk","v":"宏羲有限公司"}],"company_since":"2000-03-01","company_dissolved":"2017-04-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706076","names":[{"lang":"en","v":"CYBERCONVERGENCE (HOLDINGS) LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2002-06-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705810","names":[{"lang":"en","v":"CYBER BASE DEVELOPMENT LIMITED"},{"lang":"hk","v":"興域發展有限公司"}],"company_since":"2000-03-01","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705946","names":[{"lang":"en","v":"CYBER CAPITAL LIMITED (HK)"},{"lang":"hk","v":"世博融資有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"705814","names":[{"lang":"en","v":"DRAGON TARGET DEVELOPMENT LIMITED"},{"lang":"hk","v":"龍卓發展有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706078","names":[{"lang":"en","v":"DULIDE DONGNAN GONCI DBA TRANSSERVICE COMPANY LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706114","names":[{"lang":"en","v":"E-CHINA-B2B.COM LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2001-08-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705847","names":[{"lang":"en","v":"CYBER DATA LIMITED"},{"lang":"hk","v":"倡訊有限公司"}],"company_since":"2000-03-01","company_dissolved":"2002-06-07","company_type_txt":"Private, ltd by shares"},
{"tax_id":"705874","names":[{"lang":"en","v":"E-WIN GOAL LIMITED"},{"lang":"hk","v":"盈運高有限公司"}],"company_since":"2000-03-01","company_dissolved":"2001-04-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706112","names":[{"lang":"en","v":"E.CREDITMANAGEMENT.COM LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2015-02-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705826","names":[{"lang":"en","v":"CYBER HERO LIMITED"},{"lang":"hk","v":"科雄有限公司"}],"company_since":"2000-03-01","company_dissolved":"2001-03-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"706079","names":[{"lang":"en","v":"CYBERNATION BUILDING TECHNOLOGY COMPANY LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2003-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705908","names":[{"lang":"en","v":"EASTERN SOFTNET LIMITED"},{"lang":"hk","v":"中港網絡系統有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706172","names":[{"lang":"en","v":"EAST FINE LIMITED (d2004-04-30)"},{"lang":"hk","v":"東發有限公司"}],"company_since":"2000-03-01","company_dissolved":"2004-04-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706101","names":[{"lang":"en","v":"ECAUCTIONET.COM LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2005-05-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705964","names":[{"lang":"en","v":"CYBER LEADER TECHNOLOGY LIMITED (d2001-05-11)"},{"lang":"hk","v":"維領科技有限公司"}],"company_since":"2000-03-01","company_dissolved":"2001-05-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706150","names":[{"lang":"en","v":"ELEGANT SKY LIMITED (HK)"},{"lang":"hk","v":"彩天有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705924","names":[{"lang":"en","v":"ELLE CHOI PRODUCTION LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2007-12-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706186","names":[{"lang":"en","v":"EDA ELECTRICAL WORKS ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"意達電業工程有限公司"}],"company_since":"2000-03-01","company_dissolved":"2008-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706075","names":[{"lang":"en","v":"CYBERCONVERGENCE LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2002-06-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"705927","names":[{"lang":"en","v":"CYBERLINK GROUP LIMITED (d2002-10-25)"},{"lang":"hk","v":"百盛高科有限公司"}],"company_since":"2000-03-01","company_dissolved":"2002-10-25","company_type_txt":"Private, ltd by shares"},
{"tax_id":"706071","names":[{"lang":"en","v":"EMATCHHUB.COM LIMITED"},{"lang":"hk","v":"易網合有限公司"}],"company_since":"2000-03-01","company_dissolved":"2002-07-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706206","names":[{"lang":"en","v":"EON LIGHT LIMITED"},{"lang":"hk","v":"殷暉有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-12-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706144","names":[{"lang":"en","v":"EUROPE ASIA VENTURE LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2003-12-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705838","names":[{"lang":"en","v":"EVER HONOUR (ASIA) LIMITED"},{"lang":"hk","v":"興信(亞洲)有限公司"}],"company_since":"2000-03-01","company_dissolved":"2015-05-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"706171","names":[{"lang":"en","v":"EXCEL CHINA LIMITED"},{"lang":"hk","v":"秀華有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705840","names":[{"lang":"en","v":"EXCEL FUTURE (HONG KONG) LIMITED"},{"lang":"hk","v":"中卓(香港)有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705797","names":[{"lang":"en","v":"EXCEL LEADER (ASIA) LIMITED (d2010-10-29)"},{"lang":"hk","v":"卓駿(亞洲)有限公司"}],"company_since":"2000-03-01","company_dissolved":"2010-10-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705853","names":[{"lang":"en","v":"EXCEL WIN ENGINEERING LIMITED"},{"lang":"hk","v":"榮卓工程有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705732","names":[{"lang":"en","v":"EXPLOREMAN CHINA PRODUCTS DEVELOPMENT LIMITED"},{"lang":"hk","v":"毅科中華產品有限公司"}],"company_since":"2000-03-01","company_dissolved":"2004-08-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705789","names":[{"lang":"en","v":"FINTON TECHNOLOGY LIMITED"},{"lang":"hk","v":"永通科技有限公司"}],"company_since":"2000-03-01","company_dissolved":"2004-04-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705791","names":[{"lang":"en","v":"FIVEBEE LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2001-07-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705804","names":[{"lang":"en","v":"FOREVER SMART (HONG KONG) LIMITED"},{"lang":"hk","v":"卓駿(香港)有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"705816","names":[{"lang":"en","v":"FOREVER SMART INVESTMENT LIMITED"},{"lang":"hk","v":"永裕豐投資有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705807","names":[{"lang":"en","v":"FOREVER SUCCESS (HONG KONG) LIMITED (d2005-09-02)"},{"lang":"hk","v":"億成(香港)有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-09-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705823","names":[{"lang":"en","v":"FOREVER TARGET LIMITED (d2001-02-02)"},{"lang":"hk","v":"永裕豐有限公司"}],"company_since":"2000-03-01","company_dissolved":"2001-02-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705836","names":[{"lang":"en","v":"FORTUNE SCORE DEVELOPMENT LIMITED"},{"lang":"hk","v":"福高發展有限公司"}],"company_since":"2000-03-01","company_dissolved":"2018-12-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"706026","names":[{"lang":"en","v":"FOXLINK TECHNOLOGY LIMITED"},{"lang":"hk","v":"富士臨科技有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705817","names":[{"lang":"en","v":"EXCEL CONCEPT INVESTMENT LIMITED (d2006-07-14)"},{"lang":"hk","v":"興雅投資有限公司"}],"company_since":"2000-03-01","company_dissolved":"2006-07-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"706102","names":[{"lang":"en","v":"FREIGHT MANAGEMENT COMPANY LIMITED"},{"lang":"hk","v":"浩翔貨運有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705858","names":[{"lang":"en","v":"EXCEL CONCEPT TRADING LIMITED"},{"lang":"hk","v":"卓駿貿易有限公司"}],"company_since":"2000-03-01","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"705893","names":[{"lang":"en","v":"Friedmann Pacific Asset Management (Hong Kong) Limited"},{"lang":"hk","v":"富泰資產管理(香港)有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706137","names":[{"lang":"en","v":"FRONTWIN TECHNOLOGY COMPANY LIMITED"},{"lang":"hk","v":"科域數碼有限公司"}],"company_since":"2000-03-01","company_dissolved":"2001-11-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706104","names":[{"lang":"en","v":"FUDGE DISTRIBUTION H.K. LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2006-07-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706140","names":[{"lang":"en","v":"FULL HOPE ENTERPRISES LIMITED (d2011-05-06)"},{"lang":"hk","v":"福濠企業有限公司"}],"company_since":"2000-03-01","company_dissolved":"2011-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706000","names":[{"lang":"en","v":"FULL PROFIT ENGINEERING LIMITED (d2003-02-21)"},{"lang":"hk","v":"盛潤工程有限公司"}],"company_since":"2000-03-01","company_dissolved":"2003-02-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705849","names":[{"lang":"en","v":"FULLWIN TRADING (HK) LIMITED (d2003-04-11)"},{"lang":"hk","v":"富榮貿易(香港)有限公司"}],"company_since":"2000-03-01","company_dissolved":"2003-04-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"705799","names":[{"lang":"en","v":"FUNG KIU MANUFACTORY LIMITED"},{"lang":"hk","v":"豐僑腰帶手袋廠有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"706176","names":[{"lang":"en","v":"EXPRESSO WINGS LIMITED"},{"lang":"hk","v":"捷迅航空有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706036","names":[{"lang":"en","v":"G P MOTOR ENGINEERING COMPANY LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2005-03-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705975","names":[{"lang":"en","v":"FAI KWONG COMPANY LIMITED"},{"lang":"hk","v":"輝廣有限公司"}],"company_since":"2000-03-01","company_dissolved":"2018-02-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"706157","names":[{"lang":"en","v":"FINE EXPERT LIMITED"},{"lang":"hk","v":"輝安有限公司"}],"company_since":"2000-03-01","company_dissolved":"2012-05-11","company_type_txt":"Private, ltd by shares"},
{"tax_id":"705769","names":[{"lang":"en","v":"GLENBROOK HONG KONG LIMITED"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705842","names":[{"lang":"en","v":"FOREVER GROUP DEVELOPMENT LIMITED"},{"lang":"hk","v":"永裕豐發展有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"706169","names":[{"lang":"en","v":"GLOBAL POINT LIMITED (d2000-12-08)"},{"lang":"hk","v":"興堡有限公司"}],"company_since":"2000-03-01","company_dissolved":"2000-12-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705737","names":[{"lang":"en","v":"GLOBAL IDEA LIMITED (b2000-03-01)"},{"lang":"hk","v":"環創有限公司"}],"company_since":"2000-03-01","company_dissolved":"2016-04-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705928","names":[{"lang":"en","v":"GLOBE-IT EDUCATION LIMITED"},{"lang":"hk","v":"地球資訊科技教育有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-08-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705802","names":[{"lang":"en","v":"FOREVER SUCCESS (ASIA) LIMITED (d2005-02-18)"},{"lang":"hk","v":"順成(亞洲)有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"706192","names":[{"lang":"en","v":"GOLD CHANNEL LIMITED (d2006-07-14)"},{"lang":"hk","v":"銳金有限公司"}],"company_since":"2000-03-01","company_dissolved":"2006-07-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706167","names":[{"lang":"en","v":"GOLD CURRENT LIMITED (d2009-12-04)"},{"lang":"hk","v":"金基業有限公司"}],"company_since":"2000-03-01","company_dissolved":"2009-12-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"705835","names":[{"lang":"en","v":"FORLON HIGHLIGHT COMPANY LIMITED"},{"lang":"hk","v":"科隆精益電腦加工有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"706209","names":[{"lang":"en","v":"GOLD EXPRESS TRAVEL LIMITED"},{"lang":"hk","v":"金迅旅遊有限公司"}],"company_since":"2000-03-01","company_dissolved":"2008-08-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705844","names":[{"lang":"en","v":"GOLDEN FUTURE DEVELOPMENT LIMITED"},{"lang":"hk","v":"金新發展有限公司"}],"company_since":"2000-03-01","company_dissolved":"2013-04-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705887","names":[{"lang":"en","v":"GOLDFINDER (HK) LIMITED"},{"lang":"hk","v":"金快達有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706201","names":[{"lang":"en","v":"FOUNDERS CO. LIMITED"},{"lang":"hk","v":"志創有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-12-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705782","names":[{"lang":"en","v":"GRADE CHAMPION INVESTMENT LIMITED"},{"lang":"hk","v":"傑駿投資有限公司"}],"company_since":"2000-03-01","company_dissolved":"2012-08-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705724","names":[{"lang":"en","v":"G &amp; C PRECISION CASTING LIMITED"},{"lang":"hk","v":"冠雄精密鑄造有限公司"}],"company_since":"2000-03-01","company_dissolved":"2003-11-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705731","names":[{"lang":"en","v":"GRAND HARVEST INTERNATIONAL TECHNOLOGY LIMITED"},{"lang":"hk","v":"金豐國際科技有限公司"}],"company_since":"2000-03-01","company_dissolved":"2001-09-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705733","names":[{"lang":"en","v":"GAIN FORTUNE INVESTMENTS LIMITED (d2008-03-07)"},{"lang":"hk","v":"溢福投資有限公司"}],"company_since":"2000-03-01","company_dissolved":"2008-03-07","company_type_txt":"Private, ltd by shares"},
{"tax_id":"706107","names":[{"lang":"en","v":"GRAND CROWN INTERNATIONAL LIMITED"},{"lang":"hk","v":"永高國際有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"706129","names":[{"lang":"en","v":"GREAT CHINA FOOD AND BEVERAGES HOLDINGS LIMITED"},{"lang":"hk","v":"大中華飲食集團有限公司"}],"company_since":"2000-03-01","company_dissolved":"2006-07-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706208","names":[{"lang":"en","v":"GOODWAY TECHNOLOGY LIMITED"},{"lang":"hk","v":"展志科技有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706156","names":[{"lang":"en","v":"HALLCARD.COM LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2002-03-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706015","names":[{"lang":"en","v":"HANCO CONSULTING ENGINEERS LIMITED"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706160","names":[{"lang":"en","v":"HARVEST LAND LIMITED (d2010-04-16)"},{"lang":"hk","v":"凱領有限公司"}],"company_since":"2000-03-01","company_dissolved":"2010-04-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706096","names":[{"lang":"en","v":"HEALTHPASS HOLDINGS LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2003-10-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705963","names":[{"lang":"en","v":"HEALTHPASS INFORMATION TECHNOLOGY LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2003-10-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705960","names":[{"lang":"en","v":"HENG SHEN TRADING LIMITED"},{"lang":"hk","v":"恒燊貿易有限公司"}],"company_since":"2000-03-01","company_dissolved":"2008-01-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706207","names":[{"lang":"en","v":"HING WONG TAT INTERNATIONAL ENTERPRISES (HONG KONG) LIMITED"},{"lang":"hk","v":"興旺達國際企業(香港)有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705926","names":[{"lang":"en","v":"HK SKY NEWS LIMITED"},{"lang":"hk","v":"天網新聞有限公司"}],"company_since":"2000-03-01","company_dissolved":"2003-10-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705923","names":[{"lang":"en","v":"HK SKY TV LIMITED"},{"lang":"hk","v":"天網影視有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-09-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705801","names":[{"lang":"en","v":"GRAND HONOUR (ASIA) LIMITED"},{"lang":"hk","v":"裕信(亞洲)有限公司"}],"company_since":"2000-03-01","company_dissolved":"2015-05-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705868","names":[{"lang":"en","v":"HOLMAX INTERNATIONAL LIMITED"},{"lang":"hk","v":"皓展實業有限公司"}],"company_since":"2000-03-01","company_dissolved":"2007-07-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705857","names":[{"lang":"en","v":"HONG KONG BENLI YAT FAI TRANSPORTATION LIMITED"},{"lang":"hk","v":"香港奔力一輝運輸有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"705945","names":[{"lang":"en","v":"HONG KONG CHIN MON PUBLICATION LIMITED"},{"lang":"hk","v":"香港展望出版社有限公司"}],"company_since":"2000-03-01","company_dissolved":"2007-11-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705746","names":[{"lang":"en","v":"HONG KONG DRAGON INTERNATIONAL LIMITED"},{"lang":"hk","v":"香港天子龍國際有限公司"}],"company_since":"2000-03-01","company_dissolved":"2006-07-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706017","names":[{"lang":"en","v":"HONG KONG FOOTBALL ACADEMY LIMITED (THE)"},{"lang":"hk","v":"香港足球訓練學校有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705904","names":[{"lang":"en","v":"HONG KONG GRAPES YARD APPAREL ACCESSORIES LIMITED"},{"lang":"hk","v":"香港葡萄園服飾有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706007","names":[{"lang":"en","v":"HONG KONG HOI CHERK LOK FULL HOLDING COMPANY LIMITED"},{"lang":"hk","v":"香港海卓諾夫控股有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-12-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705756","names":[{"lang":"en","v":"HAPPY LOUNGE LIMITED"},{"lang":"hk","v":"歡樂歌廊有限公司"}],"company_since":"2000-03-01","company_dissolved":"2010-10-29","company_type_txt":"Private, ltd by shares"},
{"tax_id":"705870","names":[{"lang":"en","v":"HONG KONG HONCITY INT'L TRAVEL INVESTMENT CONSULTANT CO., LIMITED"},{"lang":"hk","v":"香港康城國際旅游投資移民顧問有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-06-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705894","names":[{"lang":"en","v":"HONG KONG NEW ASIA DIGEST LIMITED"},{"lang":"hk","v":"香港新亞文摘有限公司"}],"company_since":"2000-03-01","company_dissolved":"2006-07-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705719","names":[{"lang":"en","v":"GREEN STAR GROUP HOLDINGS LIMITED"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705880","names":[{"lang":"en","v":"HONG KONG SHUNDELI CERAMIC ENTERPRISE LIMITED"},{"lang":"hk","v":"香港順得利陶瓷企業有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706188","names":[{"lang":"en","v":"HONG YIP INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"康業國際投資有限公司"}],"company_since":"2000-03-01","company_dissolved":"2015-05-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"706175","names":[{"lang":"en","v":"HONGKONGMARKET.NET LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2002-03-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"706205","names":[{"lang":"en","v":"HIGH RISE INTERNATIONAL LIMITED"},{"lang":"hk","v":"高欣國際有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"705982","names":[{"lang":"en","v":"HENRY AND ASSOCIATES PROPERTY DEVELOPMENT LIMITED"},{"lang":"hk","v":"盈豐創建地產發展有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706022","names":[{"lang":"en","v":"HOTUNG SECURITIES INTERNATIONAL H.K. LIMITED"},{"lang":"hk","v":"和通證券香港有限公司"}],"company_since":"2000-03-01","company_dissolved":"2008-08-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706122","names":[{"lang":"en","v":"HOUSTON DEVELOPMENT LIMITED"},{"lang":"hk","v":"厚信拓展有限公司"}],"company_since":"2000-03-01","company_dissolved":"2012-03-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705901","names":[{"lang":"en","v":"HRP (HONG KONG) LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2017-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705934","names":[{"lang":"en","v":"HURRAY (H.K.) CO., LIMITED"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705942","names":[{"lang":"en","v":"HO LEE CONSTRUCTION (HK) LIMITED"},{"lang":"hk","v":"和利建築(香港)有限公司"}],"company_since":"2000-03-01","company_dissolved":"2002-11-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705940","names":[{"lang":"en","v":"HO LEE CORPORATION (HK) LIMITED"},{"lang":"hk","v":"和利企業(香港)有限公司"}],"company_since":"2000-03-01","company_dissolved":"2003-10-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"705755","names":[{"lang":"en","v":"I M C INTERIOR DESIGN &amp; CONTRACTING LIMITED"},{"lang":"hk","v":"葦澄裝飾工程有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705780","names":[{"lang":"en","v":"I-BAGZ.COM LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2003-08-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"706042","names":[{"lang":"en","v":"HONCORP INTERNATIONAL LIMITED (d2002-08-02)"},{"lang":"hk","v":"合港國際有限公司"}],"company_since":"2000-03-01","company_dissolved":"2002-08-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706063","names":[{"lang":"en","v":"HONEST SINO LIMITED"},{"lang":"hk","v":"豪粵有限公司"}],"company_since":"2000-03-01","company_dissolved":"2017-12-01","company_type_txt":"Private, ltd by shares"},
{"tax_id":"706165","names":[{"lang":"en","v":"I-DIRECTMARKET.COM LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2002-03-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706103","names":[{"lang":"en","v":"I-FEMME LIMITED (d2003-10-03)"}],"company_since":"2000-03-01","company_dissolved":"2003-10-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"705778","names":[{"lang":"en","v":"HONG KONG BUILDING COMPANY LIMITED"},{"lang":"hk","v":"香港建屋有限公司"}],"company_since":"2000-03-01","company_dissolved":"2004-01-02","company_type_txt":"Private, ltd by shares"},
{"tax_id":"706216","names":[{"lang":"en","v":"I-SURF.COM (HK) LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2011-08-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706086","names":[{"lang":"en","v":"ICRIS:0706086 (no English name)"},{"lang":"hk","v":"國際道信有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706213","names":[{"lang":"en","v":"IDNA TECHNOLOGY LIMITED"},{"lang":"hk","v":"基因信息科技有限公司"}],"company_since":"2000-03-01","company_dissolved":"2003-04-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705723","names":[{"lang":"en","v":"HONG KONG JU LONG INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"香港聚龍集團國際有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705973","names":[{"lang":"en","v":"IN TECHNOLOGY COMPANY LIMITED"},{"lang":"hk","v":"現科有限公司"}],"company_since":"2000-03-01","company_dissolved":"2012-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706014","names":[{"lang":"en","v":"INFO OCEAN TECHNOLOGY LIMITED"},{"lang":"hk","v":"訊海科技有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"706089","names":[{"lang":"en","v":"INFO-KING INTERNATIONAL ENTERPRISE LIMITED"},{"lang":"hk","v":"科訊國際企業有限公司"}],"company_since":"2000-03-01","company_dissolved":"2015-10-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"706067","names":[{"lang":"en","v":"INSCASH (HK) LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705773","names":[{"lang":"en","v":"INTELLIGENT DYNAMIC SOFTWARE LIMITED"},{"lang":"hk","v":"智動能軟件有限公司"}],"company_since":"2000-03-01","company_dissolved":"2001-10-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705977","names":[{"lang":"en","v":"INTERNATIONAL ALLIANCE EXHIBITIONS LIMITED"},{"lang":"hk","v":"國際聯盟展覽有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705970","names":[{"lang":"en","v":"INTERNATIONAL BUYING SERVICES (H.K.) LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2007-07-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706203","names":[{"lang":"en","v":"INTERNATIONAL AUCTION &amp; LOGISTICS NETWORK (CHINA) LIMITED"},{"lang":"hk","v":"國際拍賣物流網絡(中國)有限公司"}],"company_since":"2000-03-01","company_dissolved":"2007-07-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"706069","names":[{"lang":"en","v":"INVESTPRC CONSULTANCY COMPANY LIMITED"},{"lang":"hk","v":"中商企業咨詢顧問有限公司"}],"company_since":"2000-03-01","company_dissolved":"2004-09-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"706126","names":[{"lang":"en","v":"JET HONEST LIMITED (d2007-05-25)"},{"lang":"hk","v":"誠漢有限公司"}],"company_since":"2000-03-01","company_dissolved":"2007-05-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706053","names":[{"lang":"en","v":"JENNEX TECHNOLOGY LIMITED"},{"lang":"hk","v":"智龍科技有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706073","names":[{"lang":"en","v":"JEWELLWORLD.COM LIMITED (HK)"},{"lang":"hk","v":"珠寶世界(香港)有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705907","names":[{"lang":"en","v":"JIAN HAO TRADING LIMITED"},{"lang":"hk","v":"健皓貿易有限公司"}],"company_since":"2000-03-01","company_dissolved":"2010-10-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"706195","names":[{"lang":"en","v":"JOINT EASE LIMITED (d2020-06-19)"},{"lang":"hk","v":"錦怡有限公司"}],"company_since":"2000-03-01","company_dissolved":"2020-06-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705851","names":[{"lang":"en","v":"K&amp;I GROUP LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2005-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706095","names":[{"lang":"en","v":"INFO SKY TECHNOLOGY LIMITED"},{"lang":"hk","v":"訊天科技有限公司"}],"company_since":"2000-03-01","company_dissolved":"2002-12-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"705906","names":[{"lang":"en","v":"K&amp;M INTERNATIONAL FAR EAST (HK) LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2005-12-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706109","names":[{"lang":"en","v":"KING ASIA INTERNATIONAL LIMITED"},{"lang":"hk","v":"建聲國際有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706056","names":[{"lang":"en","v":"KING CENTURY TECHNOLOGY CORPORATION LIMITED"},{"lang":"hk","v":"超世紀科技集團有限公司"}],"company_since":"2000-03-01","company_dissolved":"2003-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705767","names":[{"lang":"en","v":"KING DRAGON INDUSTRIES 2K LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2015-05-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705873","names":[{"lang":"en","v":"KING WAH GROUP LIMITED"},{"lang":"hk","v":"瓊華集團有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706110","names":[{"lang":"en","v":"KING HOLDINGS LIMITED (d2009-07-24)"},{"lang":"hk","v":"建怡國際集團(控股)有限公司"}],"company_since":"2000-03-01","company_dissolved":"2009-07-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"706123","names":[{"lang":"en","v":"KINGS ART JEWELLERY (INTERNATIONAL) LIMITED"},{"lang":"hk","v":"皇庭珠寶(國際)有限公司"}],"company_since":"2000-03-01","company_dissolved":"2019-10-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705943","names":[{"lang":"en","v":"KINGSPOWER BULLION LIMITED"},{"lang":"hk","v":"盈旺金業有限公司"}],"company_since":"2000-03-01","company_dissolved":"2018-01-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705929","names":[{"lang":"en","v":"KINGSWIN ASIA LIMITED (d2015-02-13)"},{"lang":"hk","v":"新順景有限公司"}],"company_since":"2000-03-01","company_dissolved":"2015-02-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705764","names":[{"lang":"en","v":"J &amp; K (H.K.) ENTERPRISES LIMITED"},{"lang":"hk","v":"威新(香港)企業有限公司"}],"company_since":"2000-03-01","company_dissolved":"2011-03-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"705953","names":[{"lang":"en","v":"KOD HONG KONG LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2018-12-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"705869","names":[{"lang":"en","v":"KOK THAI GARAGE LIMITED"},{"lang":"hk","v":"國泰車房有限公司"}],"company_since":"2000-03-01","company_dissolved":"2001-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705779","names":[{"lang":"en","v":"JBE INTERNATIONAL MARKETING (HK) LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2002-02-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"705995","names":[{"lang":"en","v":"KUK JE TONG SHIN ASIA LIMITED"},{"lang":"hk","v":"國際通信亞洲有限公司"}],"company_since":"2000-03-01","company_dissolved":"2018-11-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705915","names":[{"lang":"en","v":"LA CASETTA LIMITED (d2003-05-16)"}],"company_since":"2000-03-01","company_dissolved":"2003-05-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706031","names":[{"lang":"en","v":"LADY INTERNATIONAL LIMITED"},{"lang":"hk","v":"麗的國際有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705916","names":[{"lang":"en","v":"LAMPLUX CO. LIMITED (d2009-10-30)"},{"lang":"hk","v":"采藝國際有限公司"}],"company_since":"2000-03-01","company_dissolved":"2009-10-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705902","names":[{"lang":"en","v":"JRP (HONG KONG) LIMITED"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"706162","names":[{"lang":"en","v":"LANDTRADE LIMITED (d2007-03-16)"},{"lang":"hk","v":"利同有限公司"}],"company_since":"2000-03-01","company_dissolved":"2007-03-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706108","names":[{"lang":"en","v":"LANDWAY INTERNATIONAL LIMITED"},{"lang":"hk","v":"力榮國際有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705796","names":[{"lang":"en","v":"LCM INTERNATIONAL INVESTMENTS LIMITED"},{"lang":"hk","v":"大乘國際投資有限公司"}],"company_since":"2000-03-01","company_dissolved":"2010-10-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"706125","names":[{"lang":"en","v":"Kerry Distribution Services (Hong Kong) Limited"},{"lang":"hk","v":"嘉里配送服務(香港)有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705962","names":[{"lang":"en","v":"LEXON HOLDINGS LIMITED"},{"lang":"hk","v":"力信集團有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"706021","names":[{"lang":"en","v":"LIAN INDUSTRIAL CO., LIMITED"},{"lang":"hk","v":"皓昕實業有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705730","names":[{"lang":"en","v":"LIMIN CORPORATION LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2012-09-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706163","names":[{"lang":"en","v":"KING EXCELLENT LIMITED (d2004-04-23)"},{"lang":"hk","v":"浩能有限公司"}],"company_since":"2000-03-01","company_dissolved":"2004-04-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705909","names":[{"lang":"en","v":"KING-E ENTERPRISES LIMITED"},{"lang":"hk","v":"信毅企業有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"706084","names":[{"lang":"en","v":"M &amp; S REAL ESTATE AGENCY LIMITED"},{"lang":"hk","v":"鳳城物業代理有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-04-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706082","names":[{"lang":"en","v":"M &amp; S INVESTMENT CONSULTANTS LIMITED"},{"lang":"hk","v":"山天投資有限公司"}],"company_since":"2000-03-01","company_dissolved":"2003-10-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706154","names":[{"lang":"en","v":"MACAUMARKET.NET LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2002-03-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706118","names":[{"lang":"en","v":"MAGNISTAR LIMITED"},{"lang":"hk","v":"銀勝有限公司"}],"company_since":"2000-03-01","company_dissolved":"2011-09-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"706198","names":[{"lang":"en","v":"KINGCLASSIC MARINE LIMITED"},{"lang":"hk","v":"嘉盛遊艇有限公司"}],"company_since":"2000-03-01","company_dissolved":"2002-08-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705806","names":[{"lang":"en","v":"KOD INTERNATIONAL LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2018-12-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"706065","names":[{"lang":"en","v":"MASTON INDUSTRIES LIMITED (d2005-02-18)"},{"lang":"hk","v":"百盛實業有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705866","names":[{"lang":"en","v":"KONG LEE TOOLING LIMITED"},{"lang":"hk","v":"港利模具有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705958","names":[{"lang":"en","v":"MEZZOMEDIA LIMITED"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"705931","names":[{"lang":"en","v":"MOONLIGHT PEARL (INTERNATIONAL) LIMITED"},{"lang":"hk","v":"月廣明珍珠(國際)有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705903","names":[{"lang":"en","v":"LAM CHIU IRON WORKS COMPANY LIMITED"},{"lang":"hk","v":"林潮鐵器工程有限公司"}],"company_since":"2000-03-01","company_dissolved":"2013-06-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"705795","names":[{"lang":"en","v":"MUSIC DOWNLOAD LIMITED"},{"lang":"hk","v":"音樂大路有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706187","names":[{"lang":"en","v":"MULTIYIELD LIMITED"},{"lang":"hk","v":"茂堯有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705949","names":[{"lang":"en","v":"NATURAL HERBS RESEARCH LIMITED"},{"lang":"hk","v":"天然藥草研究有限公司"}],"company_since":"2000-03-01","company_dissolved":"2012-12-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705820","names":[{"lang":"en","v":"NCJ COMPANY LIMITED"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"706141","names":[{"lang":"en","v":"NEOTRIDENT TECHNOLOGY LIMITED"},{"lang":"hk","v":"創騰科技有限公司"}],"company_since":"2000-03-01","company_dissolved":"2018-03-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706132","names":[{"lang":"en","v":"NETLINK LIMITED (d2004-04-30)"},{"lang":"hk","v":"網頁有限公司"}],"company_since":"2000-03-01","company_dissolved":"2004-04-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706136","names":[{"lang":"en","v":"NETSHOP LIMITED (d2002-01-25)"},{"lang":"hk","v":"力心有限公司"}],"company_since":"2000-03-01","company_dissolved":"2002-01-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705808","names":[{"lang":"en","v":"NETSCREEN TECHNOLOGIES ASIA PACIFIC LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2002-05-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706204","names":[{"lang":"en","v":"NETSHOPPING INTERNATIONAL LIMITED"},{"lang":"hk","v":"立創國際有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705871","names":[{"lang":"en","v":"NEW CITY ENGINEERING (H.K.) LIMITED"},{"lang":"hk","v":"新城市工程(香港)有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-09-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706128","names":[{"lang":"en","v":"NEW STANDARD TECHNOLOGIES LIMITED (d2002-02-08)"},{"lang":"hk","v":"新怡科技有限公司"}],"company_since":"2000-03-01","company_dissolved":"2002-02-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705774","names":[{"lang":"en","v":"NGAI SING INTERIOR DECORATION CO. LIMITED"},{"lang":"hk","v":"藝成室內裝飾有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705899","names":[{"lang":"en","v":"NICOLE ELECTRONICS INDUSTRIAL LIMITED"},{"lang":"hk","v":"樂可電子實業有限公司"}],"company_since":"2000-03-01","company_dissolved":"2012-08-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705986","names":[{"lang":"en","v":"NOE SPECIAL CONCEPTS (ASIA) COMPANY LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2010-10-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705741","names":[{"lang":"en","v":"ON WING TRANSPORTATION LIMITED"},{"lang":"hk","v":"安榮運輸有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"706134","names":[{"lang":"en","v":"OPENASIA LIMITED"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706043","names":[{"lang":"en","v":"OPTIME LIMITED (d2002-10-11)"}],"company_since":"2000-03-01","company_dissolved":"2002-10-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705985","names":[{"lang":"en","v":"ORIENTAL LEGENDS LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2004-02-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706051","names":[{"lang":"en","v":"OVERSEA EDUCATION LIMITED"},{"lang":"hk","v":"海外教育有限公司"}],"company_since":"2000-03-01","company_dissolved":"2019-03-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705860","names":[{"lang":"en","v":"PACIFIC PLANNER INTERNATIONAL LIMITED"},{"lang":"hk","v":"榮建國際有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705839","names":[{"lang":"en","v":"PACIFIC TARGET (HONG KONG) LIMITED"},{"lang":"hk","v":"海盛(香港)有限公司"}],"company_since":"2000-03-01","company_dissolved":"2007-09-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705867","names":[{"lang":"en","v":"NETPOINT CREATIONS LIMITED"},{"lang":"hk","v":"歷邦創富有限公司"}],"company_since":"2000-03-01","company_dissolved":"2004-07-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"706111","names":[{"lang":"en","v":"PARAKING TECHNOLOGY LIMITED"},{"lang":"hk","v":"栢基科技有限公司"}],"company_since":"2000-03-01","company_dissolved":"2001-12-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705889","names":[{"lang":"en","v":"PARIBAS PACIFIC INDUSTRIAL LIMITED"},{"lang":"hk","v":"百利達亞洲實業有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705837","names":[{"lang":"en","v":"PARTEK TRAVEL SERVICE COMPANY LIMITED"},{"lang":"hk","v":"百達(香港)旅行社有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705861","names":[{"lang":"en","v":"PEAKWIN INTERNATIONAL LIMITED"},{"lang":"hk","v":"柏宏國際有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-04-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705770","names":[{"lang":"en","v":"PENTAIR PACIFIC RIM, LIMITED"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706013","names":[{"lang":"en","v":"PIONEER TECHNOLOGY LIMITED (d2005-07-08)"},{"lang":"hk","v":"先驅科技有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-07-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705760","names":[{"lang":"en","v":"PLAYGO ART &amp; CRAFT MANUFACTORY LIMITED"},{"lang":"hk","v":"貝樂高玩具有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705828","names":[{"lang":"en","v":"POLY BEST ENGINEERING LIMITED"},{"lang":"hk","v":"誠寶工程有限公司"}],"company_since":"2000-03-01","company_dissolved":"2002-01-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705771","names":[{"lang":"en","v":"NTEC ASSOCIATES LIMITED"},{"lang":"hk","v":"恩達技術顧問有限公司"}],"company_since":"2000-03-01","company_dissolved":"2006-01-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705818","names":[{"lang":"en","v":"POLY WEALTHY LIMITED"},{"lang":"hk","v":"三偉有限公司"}],"company_since":"2000-03-01","company_dissolved":"2007-07-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705878","names":[{"lang":"en","v":"POWER-TRANSPORT INTERNATIONAL SHIPPING CO., LIMITED"},{"lang":"hk","v":"威運國際船務有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-12-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"706030","names":[{"lang":"en","v":"POWERWAVE TECHNOLOGY HOLDINGS LIMITED"},{"lang":"hk","v":"鑫洋科技控股有限公司"}],"company_since":"2000-03-01","company_dissolved":"2004-09-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706105","names":[{"lang":"en","v":"PROMITEX LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2008-09-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"706145","names":[{"lang":"en","v":"ORIENTAL CHINESE MEDICINE LIMITED"},{"lang":"hk","v":"東方中醫葯有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"705968","names":[{"lang":"en","v":"PYRAMID TECHNOLOGY COMPANY LIMITED"},{"lang":"hk","v":"聚智科技有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705726","names":[{"lang":"en","v":"R &amp; T Corporate Services Limited"},{"lang":"hk","v":"卓富德企業服務有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706023","names":[{"lang":"en","v":"RCM MANUFACTURING (HK) LIMITED"},{"lang":"hk","v":"信誠實業(香港)有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705913","names":[{"lang":"en","v":"RICH MILLENNIUM COMPANY LIMITED"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"705821","names":[{"lang":"en","v":"ROYAL ASIAN LIMITED"},{"lang":"hk","v":"誠緯有限公司"}],"company_since":"2000-03-01","company_dissolved":"2012-04-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706074","names":[{"lang":"en","v":"PARK AVENUE INTERNATIONAL LIMITED"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706159","names":[{"lang":"en","v":"PATENT LIMITED"},{"lang":"hk","v":"百達利有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"705747","names":[{"lang":"en","v":"SACHA TASTE LIMITED"},{"lang":"hk","v":"沙茶風味有限公司"}],"company_since":"2000-03-01","company_dissolved":"2002-09-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705882","names":[{"lang":"en","v":"SAN WO DRAINAGE SERVICES COMPANY LIMITED"},{"lang":"hk","v":"三和渠務工程有限公司"}],"company_since":"2000-03-01","company_dissolved":"2015-11-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705745","names":[{"lang":"en","v":"SANDY TELECOM (H.K.) COMPANY LIMITED"},{"lang":"hk","v":"森迪通信(香港)有限公司"}],"company_since":"2000-03-01","company_dissolved":"2003-08-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706055","names":[{"lang":"en","v":"SANSEGAL LIMITED"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705912","names":[{"lang":"en","v":"PO CHUEN EMBROIDERY CO LIMITED"},{"lang":"hk","v":"寶泉刺綉有限公司"}],"company_since":"2000-03-01","company_dissolved":"2010-02-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705812","names":[{"lang":"en","v":"RUBICON PROFESSIONAL SERVICES LIMITED (d2005-12-16)"}],"company_since":"2000-03-01","company_dissolved":"2005-12-16","company_type_txt":"Private, ltd by shares"},
{"tax_id":"705783","names":[{"lang":"en","v":"SCORE RIGHT INVESTMENT LIMITED"},{"lang":"hk","v":"志立投資有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705725","names":[{"lang":"en","v":"SCHOLARS OVERSEAS STUDY LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2010-08-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705971","names":[{"lang":"en","v":"POWER D INTERNATIONAL LIMITED"},{"lang":"hk","v":"力迪國際有限公司"}],"company_since":"2000-03-01","company_dissolved":"2007-11-23","company_type_txt":"Private, ltd by shares"},
{"tax_id":"705784","names":[{"lang":"en","v":"SENCO INVESTMENT LIMITED (d2004-11-19)"},{"lang":"hk","v":"成和投資有限公司"}],"company_since":"2000-03-01","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"706113","names":[{"lang":"en","v":"SENTEX LIMITED (HK)"},{"lang":"hk","v":"瑞成有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"706081","names":[{"lang":"en","v":"SESAMI.COM (HK) LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2003-03-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706196","names":[{"lang":"en","v":"SETWING INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"金泳國際有限公司"}],"company_since":"2000-03-01","company_dissolved":"2006-07-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706211","names":[{"lang":"en","v":"SHANCREST SERVICES LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2001-02-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706138","names":[{"lang":"en","v":"SHARP BASE PAPER PRODUCT COMPANY LIMITED"},{"lang":"hk","v":"銳基紙品有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705735","names":[{"lang":"en","v":"SHARP STAR LIMITED (d2005-06-30)"},{"lang":"hk","v":"城星有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706120","names":[{"lang":"en","v":"SHI CHANG INDUSTRIAL CO., LIMITED"},{"lang":"hk","v":"士昌實業有限公司"}],"company_since":"2000-03-01","company_dissolved":"2016-09-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705854","names":[{"lang":"en","v":"ROYAL PACIFIC ENGINEERING LIMITED"},{"lang":"hk","v":"海盛工程有限公司"}],"company_since":"2000-03-01","company_dissolved":"2008-06-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"706057","names":[{"lang":"en","v":"SILVER VICTORY LIMITED (d2005-01-07)"},{"lang":"hk","v":"僑富有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-01-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705833","names":[{"lang":"en","v":"ROYAL TRADE INTERNATIONAL LIMITED (d2006-07-14)"},{"lang":"hk","v":"康業國際有限公司"}],"company_since":"2000-03-01","company_dissolved":"2006-07-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"706153","names":[{"lang":"en","v":"SIM LIM (CHINA ASSETS) INVESTMENTS LIMITED"},{"lang":"hk","v":"森林(中國項目)投資有限公司"}],"company_since":"2000-03-01","company_dissolved":"2002-01-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705966","names":[{"lang":"en","v":"SINO INTERNATIONAL INVESTMENT HOLDINGS LIMITED"},{"lang":"hk","v":"中港國際投資集團有限公司"}],"company_since":"2000-03-01","company_dissolved":"2018-12-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"706094","names":[{"lang":"en","v":"SINOLINK TECHNOLOGY DEVELOPMENT LIMITED (d2004-05-14)"},{"lang":"hk","v":"中聯科技發展有限公司"}],"company_since":"2000-03-01","company_dissolved":"2004-05-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705891","names":[{"lang":"en","v":"SARSAR AROMA LIMITED"},{"lang":"hk","v":"雅舍香薰有限公司"}],"company_since":"2000-03-01","company_dissolved":"2001-07-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"706011","names":[{"lang":"en","v":"SINOSKY TECHNOLOGY DEVELOPMENT LIMITED"},{"lang":"hk","v":"中天科技發展有限公司"}],"company_since":"2000-03-01","company_dissolved":"2015-05-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706093","names":[{"lang":"en","v":"SKYTOP TECHNOLOGY LIMITED"},{"lang":"hk","v":"立天科技有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705848","names":[{"lang":"en","v":"ROYAL BUSINESS LIMITED"},{"lang":"hk","v":"明忠有限公司"}],"company_since":"2000-03-01","company_dissolved":"2003-05-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705798","names":[{"lang":"en","v":"SMART GROUP (ASIA) LIMITED"},{"lang":"hk","v":"邦彥(亞洲)有限公司"}],"company_since":"2000-03-01","company_dissolved":"2013-04-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"706119","names":[{"lang":"en","v":"SENWAY INDUSTRIES LIMITED"},{"lang":"hk","v":"信華實業有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"705939","names":[{"lang":"en","v":"SPORT PHOTO COMPANY LIMITED"},{"lang":"hk","v":"晶悅國際有限公司"}],"company_since":"2000-03-01","company_dissolved":"2006-07-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705898","names":[{"lang":"en","v":"SRP (HONG KONG) LIMITED"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705793","names":[{"lang":"en","v":"STANDARD SPIRIT TECHNOLOGY LIMITED"},{"lang":"hk","v":"德益科技有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706181","names":[{"lang":"en","v":"STAR ASIAN LIMITED (d2010-10-29)"},{"lang":"hk","v":"星亞有限公司"}],"company_since":"2000-03-01","company_dissolved":"2010-10-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706193","names":[{"lang":"en","v":"STAREASTNET.COM LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2003-01-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706115","names":[{"lang":"en","v":"STARLINE LIMITED (HK)"},{"lang":"hk","v":"昇彩有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705772","names":[{"lang":"en","v":"STARZ IMAGE (HK) LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2005-12-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705938","names":[{"lang":"en","v":"STEELAHEAD LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2017-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"706045","names":[{"lang":"en","v":"SUCCESS HOPE INTERNATIONAL LIMITED"},{"lang":"hk","v":"世康國際有限公司"}],"company_since":"2000-03-01","company_dissolved":"2015-05-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"705775","names":[{"lang":"en","v":"SUN LUEN HOP FOODS LIMITED"},{"lang":"hk","v":"新聯合食品有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-12-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705884","names":[{"lang":"en","v":"SUNFULL INDUSTRIAL LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2002-07-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705727","names":[{"lang":"en","v":"SUNNY BRIDGE INTERNATIONAL LIMITED"},{"lang":"hk","v":"橋煇國際有限公司"}],"company_since":"2000-03-01","company_dissolved":"2004-03-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"706117","names":[{"lang":"en","v":"SUPPLIER ASIA LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2008-06-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"705776","names":[{"lang":"en","v":"SUPREME CHAMPION DEVELOPMENT (HONG KONG) LIMITED"},{"lang":"hk","v":"承傑發展(香港)有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705744","names":[{"lang":"en","v":"SURE ADVANCE PCB LIMITED"},{"lang":"hk","v":"確良綫路板有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706098","names":[{"lang":"en","v":"SURPLUS INTERNATIONAL INVESTMENT HOLDINGS LIMITED (d2003-01-30)"},{"lang":"hk","v":"盈富國際投資集團有限公司"}],"company_since":"2000-03-01","company_dissolved":"2003-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"706010","names":[{"lang":"en","v":"SKYFAIR TECHNOLOGY DEVELOPMENT LIMITED"},{"lang":"hk","v":"創天科技發展有限公司"}],"company_since":"2000-03-01","company_dissolved":"2003-07-25","company_type_txt":"Private, ltd by shares"},
{"tax_id":"705895","names":[{"lang":"en","v":"T-ADVANCE COMPANY LIMITED"},{"lang":"hk","v":"天域研創有限公司"}],"company_since":"2000-03-01","company_dissolved":"2002-11-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706183","names":[{"lang":"en","v":"TAK ON BABY TOYS LIMITED"},{"lang":"hk","v":"德安嬰兒玩具有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705792","names":[{"lang":"en","v":"STD TECHNOLOGY HOLDING LIMITED"},{"lang":"hk","v":"高標準科技控股有限公司"}],"company_since":"2000-03-01","company_dissolved":"2007-07-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"706088","names":[{"lang":"en","v":"TDSOFT ASIA LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2004-04-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705742","names":[{"lang":"en","v":"SOLARWEAR INTERNATIONAL LIMITED"},{"lang":"hk","v":"國際太陽能服裝有限公司"}],"company_since":"2000-03-01","company_dissolved":"2002-11-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705961","names":[{"lang":"en","v":"TECH-EX DOT COM LIMITED"},{"lang":"hk","v":"科訊網世界有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705759","names":[{"lang":"en","v":"SPHERE HEALTHCARE (HK) LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2015-12-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"706044","names":[{"lang":"en","v":"TECHNIC INTERNATIONAL LIMITED"},{"lang":"hk","v":"達益國際有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705841","names":[{"lang":"en","v":"TECHNOLOGY GATEWAY INTERNATIONAL LIMITED"},{"lang":"hk","v":"科技之窗國際有限公司"}],"company_since":"2000-03-01","company_dissolved":"2003-11-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705981","names":[{"lang":"en","v":"TENDER COMPUTER TECHNOLOGY LIMITED"},{"lang":"hk","v":"騰達電腦科技有限公司"}],"company_since":"2000-03-01","company_dissolved":"2004-11-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705993","names":[{"lang":"en","v":"THEOFREBRIEL GROWTH LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2005-08-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"706180","names":[{"lang":"en","v":"STAR WISDOM LIMITED (d2007-07-13)"},{"lang":"hk","v":"誠偉有限公司"}],"company_since":"2000-03-01","company_dissolved":"2007-07-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"705952","names":[{"lang":"en","v":"TIAN EN MEDIPHARM (H.K.) LIMITED"},{"lang":"hk","v":"香港天恩葯醫有限公司"}],"company_since":"2000-03-01","company_dissolved":"2001-12-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706001","names":[{"lang":"en","v":"TOP CYBER INTERNATIONAL ENTERPRISE LIMITED"},{"lang":"hk","v":"科達國際企業有限公司"}],"company_since":"2000-03-01","company_dissolved":"2002-12-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706009","names":[{"lang":"en","v":"TOP GALAXY TECHNOLOGY LIMITED"},{"lang":"hk","v":"星河科技有限公司"}],"company_since":"2000-03-01","company_dissolved":"2001-05-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706178","names":[{"lang":"en","v":"TOP SUPREME LIMITED (d2016-04-29)"},{"lang":"hk","v":"泰新有限公司"}],"company_since":"2000-03-01","company_dissolved":"2016-04-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705987","names":[{"lang":"en","v":"TORO HOLDINGS LIMITED (d2005-02-18)"}],"company_since":"2000-03-01","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706003","names":[{"lang":"en","v":"TOPGAIN INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"冠利國際發展有限公司"}],"company_since":"2000-03-01","company_dissolved":"2002-08-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706130","names":[{"lang":"en","v":"TOYOBI JEWELLERY COMPANY LIMITED"},{"lang":"hk","v":"丰美珠寶有限公司"}],"company_since":"2000-03-01","company_dissolved":"2001-12-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706220","names":[{"lang":"en","v":"TRAVELNET ASIA PACIFIC LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2005-12-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706004","names":[{"lang":"en","v":"TREASURE INTERNATIONAL DEVELOPMENT LIMITED (d2005-12-16)"},{"lang":"hk","v":"健富國際發展有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-12-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705944","names":[{"lang":"en","v":"TALY (H.K.) LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2018-12-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"705974","names":[{"lang":"en","v":"TRICOSAL LIMITED"},{"lang":"hk","v":"賽高素有限公司"}],"company_since":"2000-03-01","company_dissolved":"2014-01-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706005","names":[{"lang":"en","v":"TRIUMPH INTERNATIONAL ENTERPRISE LIMITED (d2001-10-26)"},{"lang":"hk","v":"勝達國際企業有限公司"}],"company_since":"2000-03-01","company_dissolved":"2001-10-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705728","names":[{"lang":"en","v":"TROY INFORMATION TECH INTERNATIONAL LIMITED"},{"lang":"hk","v":"創信技術國際有限公司"}],"company_since":"2000-03-01","company_dissolved":"2010-04-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705777","names":[{"lang":"en","v":"TUMMERS (ASIA) MACHINERY LIMITED"},{"lang":"hk","v":"荷蘭湯馬斯(亞洲)機械有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705787","names":[{"lang":"en","v":"U-CYBER (HONG KONG) LIMITED"},{"lang":"hk","v":"航宇(香港)有限公司"}],"company_since":"2000-03-01","company_dissolved":"2008-07-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705794","names":[{"lang":"en","v":"UNION SHEEN ENGINEERING LIMITED"},{"lang":"hk","v":"和昇工程有限公司"}],"company_since":"2000-03-01","company_dissolved":"2012-11-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706158","names":[{"lang":"en","v":"UNION TECH LIMITED (d2005-12-16)"},{"lang":"hk","v":"譽達有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-12-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"706064","names":[{"lang":"en","v":"UNITED LINK INDUSTRIES LIMITED"},{"lang":"hk","v":"裕龍實業有限公司"}],"company_since":"2000-03-01","company_dissolved":"2017-08-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"706002","names":[{"lang":"en","v":"TOP ETERNAL ENGINEERING LIMITED"},{"lang":"hk","v":"高恒工程有限公司"}],"company_since":"2000-03-01","company_dissolved":"2003-03-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"705811","names":[{"lang":"en","v":"UNIVERSAL ENVIRONMENT CLEANING SERVICES COMPANY LIMITED"},{"lang":"hk","v":"環球環境清潔服務有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"706090","names":[{"lang":"en","v":"TOP WILL ENGINEERING LIMITED"},{"lang":"hk","v":"佳志工程有限公司"}],"company_since":"2000-03-01","company_dissolved":"2002-05-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"705937","names":[{"lang":"en","v":"V-SOURCE HONG KONG LIMITED"},{"lang":"hk","v":"易索有限公司"}],"company_since":"2000-03-01","company_dissolved":"2003-03-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705951","names":[{"lang":"en","v":"VALUE LOGISTICS MANAGEMENT LIMITED"},{"lang":"hk","v":"維利多物流管理有限公司"}],"company_since":"2000-03-01","company_dissolved":"2009-07-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"705872","names":[{"lang":"en","v":"VALUE-ADDED PARENTS PUBLICATION COMPANY LIMITED"},{"lang":"hk","v":"增值父母出版社有限公司"}],"company_since":"2000-03-01","company_dissolved":"2013-06-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706106","names":[{"lang":"en","v":"VASTON INTERNATIONAL LIMITED (d2003-05-16)"},{"lang":"hk","v":"偉通國際有限公司"}],"company_since":"2000-03-01","company_dissolved":"2003-05-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"706217","names":[{"lang":"en","v":"Vertex Systems Services Limited"}],"company_since":"2000-03-01","company_dissolved":"2013-07-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705996","names":[{"lang":"en","v":"VIKING (HK) BIOLOGY COMPANY LIMITED"},{"lang":"hk","v":"東興高新生物有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"706035","names":[{"lang":"en","v":"VINCE INTERNATIONAL LIMITED"},{"lang":"hk","v":"芸訊國際有限公司"}],"company_since":"2000-03-01","company_dissolved":"2011-07-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705989","names":[{"lang":"en","v":"TOA KWONG TOA TEH ASSOCIATION LIMITED"},{"lang":"hk","v":"道光道德會有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
{"tax_id":"706024","names":[{"lang":"en","v":"VISION DYNAMICS CYBERTECH LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2001-08-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705935","names":[{"lang":"en","v":"WAH LINES LIMITED"},{"lang":"hk","v":"華立船務有限公司"}],"company_since":"2000-03-01","company_dissolved":"2002-07-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705750","names":[{"lang":"en","v":"WAI YEE CONSULTANCY LIMITED"},{"lang":"hk","v":"偉宜顧問有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"706006","names":[{"lang":"en","v":"WEALTH INTERNATIONAL ENTERPRISE LIMITED"},{"lang":"hk","v":"富健國際企業有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706184","names":[{"lang":"en","v":"WEALTHY LINK INDUSTRIAL COMPANY LIMITED"},{"lang":"hk","v":"驊徽實業有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-12-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706033","names":[{"lang":"en","v":"Webstar Technology Limited"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"706161","names":[{"lang":"en","v":"WEDDINGSTREET.NET LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2003-10-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706155","names":[{"lang":"en","v":"UNISOFT LIMITED (d2005-02-18)"},{"lang":"hk","v":"宏科有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"706127","names":[{"lang":"en","v":"WELL CHARM ENGINEERING LIMITED (d2001-10-05)"},{"lang":"hk","v":"華創工程有限公司"}],"company_since":"2000-03-01","company_dissolved":"2001-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706210","names":[{"lang":"en","v":"WELL CONCORD DESIGN &amp; ENGINEERING LIMITED"},{"lang":"hk","v":"廣域設計及工程有限公司"}],"company_since":"2000-03-01","company_dissolved":"2016-10-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"706034","names":[{"lang":"en","v":"UNITED STAR ENTERTAINMENT LIMITED"},{"lang":"hk","v":"駿星娛樂有限公司"}],"company_since":"2000-03-01","company_dissolved":"2006-07-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706038","names":[{"lang":"en","v":"WILSON ENTERPRISES (HOLDINGS) LIMITED"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706173","names":[{"lang":"en","v":"WIN EARTH LIMITED"},{"lang":"hk","v":"滙賢有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"705754","names":[{"lang":"en","v":"WINGS FAR EAST TRADING LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2005-11-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706092","names":[{"lang":"en","v":"UNITED POWER TECHNOLOGY LIMITED (d2005-12-16)"},{"lang":"hk","v":"滙能科技有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-12-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706046","names":[{"lang":"en","v":"WINLINK INTERNATIONAL LIMITED (d2002-05-31)"},{"lang":"hk","v":"和裕國際有限公司"}],"company_since":"2000-03-01","company_dissolved":"2002-05-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705997","names":[{"lang":"en","v":"VEGLA PACKAGING (HONG KONG) LIMITED"}],"company_since":"2000-03-01","company_dissolved":"2006-07-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"705978","names":[{"lang":"en","v":"WINTIN PROPERTY LIMITED"},{"lang":"hk","v":"運添物業有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-04-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706142","names":[{"lang":"en","v":"WISDOM SEA GROUP LIMITED"},{"lang":"hk","v":"慧海集團有限公司"}],"company_since":"2000-03-01","company_dissolved":"2009-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705955","names":[{"lang":"en","v":"VIRTUAL MEDIA LIMITED (d2005-02-18)"}],"company_since":"2000-03-01","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"706174","names":[{"lang":"en","v":"WISE SQUARE LIMITED (d2002-08-16)"},{"lang":"hk","v":"滙時有限公司"}],"company_since":"2000-03-01","company_dissolved":"2002-08-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706061","names":[{"lang":"en","v":"WISELINK LIMITED (d2015-05-08)"},{"lang":"hk","v":"慧林有限公司"}],"company_since":"2000-03-01","company_dissolved":"2015-05-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705822","names":[{"lang":"en","v":"WORLDWIDE FUTURE LIMITED"},{"lang":"hk","v":"偉華香港有限公司"}],"company_since":"2000-03-01","company_dissolved":"2010-02-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706202","names":[{"lang":"en","v":"WORLDWIDE NETWORK LIMITED (d2005-12-16)"},{"lang":"hk","v":"全球聯網有限公司"}],"company_since":"2000-03-01","company_dissolved":"2005-12-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706100","names":[{"lang":"en","v":"XIANG GANG AN TAI COMPANY LIMITED"},{"lang":"hk","v":"香港安泰有限公司"}],"company_since":"2000-03-01","company_dissolved":"2006-07-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"705892","names":[{"lang":"en","v":"YEE CHEONG DEVELOPMENT INTERNATIONAL LIMITED"},{"lang":"hk","v":"宜昌發展國際有限公司"}],"company_since":"2000-03-01","company_dissolved":"2006-07-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"706168","names":[{"lang":"en","v":"WISE QUEEN LIMITED"},{"lang":"hk","v":"欣強有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"706041","names":[{"lang":"en","v":"WORLD LEGEND INTERNATIONAL LIMITED (d2004-11-12)"},{"lang":"hk","v":"世龍國際有限公司"}],"company_since":"2000-03-01","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705969","names":[{"lang":"en","v":"XIANG GANG MI QI COMPANY LIMITED"},{"lang":"hk","v":"香港迷奇有限公司"}],"company_since":"2000-03-01","company_dissolved":"2006-07-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"705917","names":[{"lang":"en","v":"YG CYBER HOLDINGS LIMITED"},{"lang":"hk","v":"盈森集團有限公司"}],"company_since":"2000-03-01","company_dissolved":"2009-07-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"706149","names":[{"lang":"en","v":"ZENCO TEXTILES LIMITED"},{"lang":"hk","v":"東暉紡織有限公司"}],"company_since":"2000-03-01","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
