{"tax_id":"677676","names":[{"lang":"en","v":"CROWN YIELD INDUSTRIAL LIMITED"},{"lang":"hk","v":"冠億實業有限公司"}],"company_since":"1999-06-02","company_dissolved":"2004-04-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677561","names":[{"lang":"en","v":"DENWAY AV TECHNOLOGY LIMITED"},{"lang":"hk","v":"德和音像科技有限公司"}],"company_since":"1999-06-02","company_dissolved":"2003-11-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677682","names":[{"lang":"en","v":"DRAGONTECH PHARMACEUTICALS LIMITED"},{"lang":"hk","v":"港龍葯業有限公司"}],"company_since":"1999-06-02","company_dissolved":"2003-11-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677661","names":[{"lang":"en","v":"E.T. MEDIA PRODUCTION LIMITED"},{"lang":"hk","v":"異地傳播有限公司"}],"company_since":"1999-06-02","company_dissolved":"2003-11-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677620","names":[{"lang":"en","v":"EASTERN FIELD INVESTMENT LIMITED (d2009-07-10)"},{"lang":"hk","v":"東田投資有限公司"}],"company_since":"1999-06-02","company_dissolved":"2009-07-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677607","names":[{"lang":"en","v":"EDUCATION UK LIMITED"}],"company_since":"1999-06-02","company_dissolved":"2020-04-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677667","names":[{"lang":"en","v":"ENACT COMPANY LIMITED"},{"lang":"hk","v":"展現有限公司"}],"company_since":"1999-06-02","company_dissolved":"2003-12-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677462","names":[{"lang":"en","v":"EPOWER INTEGRATED SOLUTIONS LIMITED"}],"company_since":"1999-06-02","company_dissolved":"2003-09-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677496","names":[{"lang":"en","v":"EVER SHINE PRODUCTS LIMITED"},{"lang":"hk","v":"恆彩製品有限公司"}],"company_since":"1999-06-02","company_dissolved":"2007-12-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677672","names":[{"lang":"en","v":"CYBERAD ASIA LIMITED"},{"lang":"hk","v":"網業廣告有限公司"}],"company_since":"1999-06-02","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677586","names":[{"lang":"en","v":"EVER TECH DEVELOPMENT LIMITED"},{"lang":"hk","v":"恒科發展有限公司"}],"company_since":"1999-06-02","company_dissolved":"2001-10-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677678","names":[{"lang":"en","v":"EVERISE PROPERTIES LIMITED"},{"lang":"hk","v":"永升置業有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677602","names":[{"lang":"en","v":"EXCEL BEST INVESTMENTS LIMITED"},{"lang":"hk","v":"益田投資有限公司"}],"company_since":"1999-06-02","company_dissolved":"2018-02-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677583","names":[{"lang":"en","v":"EXCELLENT LEADER LIMITED"},{"lang":"hk","v":"業煒有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677719","names":[{"lang":"en","v":"FINE LEGEND LIMITED"},{"lang":"hk","v":"旭策有限公司"}],"company_since":"1999-06-02","company_dissolved":"2018-03-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677630","names":[{"lang":"en","v":"CHOICELAND LIMITED"},{"lang":"hk","v":"采置有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677612","names":[{"lang":"en","v":"FONG WAH TRANSPORT CO. LIMITED"},{"lang":"hk","v":"芳華貨運有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677515","names":[{"lang":"en","v":"FORCE WIN LIMITED"},{"lang":"hk","v":"盛力有限公司"}],"company_since":"1999-06-02","company_dissolved":"2004-03-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677709","names":[{"lang":"en","v":"FORTUNE ISLAND RESOURCES LIMITED"},{"lang":"hk","v":"富島資源有限公司"}],"company_since":"1999-06-02","company_dissolved":"2003-12-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677616","names":[{"lang":"en","v":"FUJICON TECHNOLOGY (H.K.) LIMITED"},{"lang":"hk","v":"富之光科技(香港)有限公司"}],"company_since":"1999-06-02","company_dissolved":"2003-11-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677710","names":[{"lang":"en","v":"FUNRICH LIMITED"},{"lang":"hk","v":"豐富有限公司"}],"company_since":"1999-06-02","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677479","names":[{"lang":"en","v":"COBRA ASSOCIATES LIMITED (d2006-10-13)"}],"company_since":"1999-06-02","company_dissolved":"2006-10-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677540","names":[{"lang":"en","v":"GATEWAY TRADING LIMITED (d2002-09-13)"},{"lang":"hk","v":"堅宏貿易有限公司"}],"company_since":"1999-06-02","company_dissolved":"2002-09-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677702","names":[{"lang":"en","v":"GENERATION FAMOUS SHOES &amp; LEATHER LIMITED"},{"lang":"hk","v":"世紀名鞋皮具有限公司"}],"company_since":"1999-06-02","company_dissolved":"2007-01-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677464","names":[{"lang":"en","v":"GENIUS PRODUCTIONS (HONG KONG) LIMITED"},{"lang":"hk","v":"明智製作(香港)有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677463","names":[{"lang":"en","v":"GERMAN DULUX COATING GROUP LIMITED"},{"lang":"hk","v":"德國多樂士製漆集團有限公司"}],"company_since":"1999-06-02","company_dissolved":"2016-02-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677738","names":[{"lang":"en","v":"GLOBAL TIME CORPORATION LIMITED"},{"lang":"hk","v":"嘉泰有限公司"}],"company_since":"1999-06-02","company_dissolved":"2019-06-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677718","names":[{"lang":"en","v":"GOLD CUP LIMITED (d2001-08-10)"},{"lang":"hk","v":"遠智有限公司"}],"company_since":"1999-06-02","company_dissolved":"2001-08-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677666","names":[{"lang":"en","v":"CONCORD STAR ENTERPRISES LIMITED"},{"lang":"hk","v":"和星企業有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677523","names":[{"lang":"en","v":"GOLDEN TECH HOLDINGS LIMITED (d2001-09-21)"},{"lang":"hk","v":"科技集團有限公司"}],"company_since":"1999-06-02","company_dissolved":"2001-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677550","names":[{"lang":"en","v":"GP INDUSTRIES (HONG KONG) LIMITED"},{"lang":"hk","v":"智博實業(香港)有限公司"}],"company_since":"1999-06-02","company_dissolved":"2014-07-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"677603","names":[{"lang":"en","v":"GRAND HARVEST ELECTRONIC &amp; TECHNOLOGY LIMITED"},{"lang":"hk","v":"傑成電子科技有限公司"}],"company_since":"1999-06-02","company_dissolved":"2004-12-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677490","names":[{"lang":"en","v":"COREX TRADING LIMITED"}],"company_since":"1999-06-02","company_dissolved":"2013-08-16","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677503","names":[{"lang":"en","v":"GRANDDESIGN PRODUCTION COMPANY LIMITED"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677477","names":[{"lang":"en","v":"GRATEFUL (FIJI) LIMITED"},{"lang":"hk","v":"愉峯(斐濟)有限公司"}],"company_since":"1999-06-02","company_dissolved":"2001-01-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677689","names":[{"lang":"en","v":"GREAT MARGIN DEVELOPMENT LIMITED"},{"lang":"hk","v":"豐宏發展有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677615","names":[{"lang":"en","v":"GREAT SHANGHAI WATCH &amp; JEWELLERY COMPANY LIMITED"},{"lang":"hk","v":"大上海鐘錶珠寶有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"677712","names":[{"lang":"en","v":"HALGON LIMITED"},{"lang":"hk","v":"豪港有限公司"}],"company_since":"1999-06-02","company_dissolved":"2004-02-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677720","names":[{"lang":"en","v":"DELUXE GLORY LIMITED"},{"lang":"hk","v":"運鵬有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677565","names":[{"lang":"en","v":"HANWAH VIDEO LIMITED"},{"lang":"hk","v":"恒華影視有限公司"}],"company_since":"1999-06-02","company_dissolved":"2010-10-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677525","names":[{"lang":"en","v":"DIAJEWEL LIMITED"}],"company_since":"1999-06-02","company_dissolved":"2010-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677505","names":[{"lang":"en","v":"E SENTRONICS CORPORATION LIMITED"},{"lang":"hk","v":"宜信電子股份有限公司"}],"company_since":"1999-06-02","company_dissolved":"2002-06-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677657","names":[{"lang":"en","v":"HENG HUAT QUARRY (HK) LIMITED"},{"lang":"hk","v":"興發石業(香港)有限公司"}],"company_since":"1999-06-02","company_dissolved":"2010-02-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677701","names":[{"lang":"en","v":"HIP SHING ENAMEL COMPANY LIMITED"},{"lang":"hk","v":"協成琺瑯有限公司"}],"company_since":"1999-06-02","company_dissolved":"2020-07-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677533","names":[{"lang":"en","v":"EASYWIN ENTERPRISE INTERNATIONAL LIMITED"},{"lang":"hk","v":"毅進企業有限公司"}],"company_since":"1999-06-02","company_dissolved":"2009-07-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677551","names":[{"lang":"en","v":"HONG KONG AVIATION LEASE &amp; FINANCE COMPANY LIMITED"},{"lang":"hk","v":"香港宇航租賃融資有限公司"}],"company_since":"1999-06-02","company_dissolved":"2008-11-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677484","names":[{"lang":"en","v":"HONG KONG FLOCK HOLDINGS LIMITED"},{"lang":"hk","v":"香港成群集團有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677474","names":[{"lang":"en","v":"FOUR SEAS CORPORATE TRAVEL LIMITED"},{"lang":"hk","v":"四海公司旅運有限公司"}],"company_since":"1999-06-02","company_dissolved":"2005-04-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677577","names":[{"lang":"en","v":"EMART TECHNOLOGY LIMITED"},{"lang":"hk","v":"網龍科技有限公司"}],"company_since":"1999-06-02","company_dissolved":"2002-10-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677500","names":[{"lang":"en","v":"HONG KONG WING KWONG BETHEL CHURCH LIMITED"},{"lang":"hk","v":"香港伯特利教會榮光堂有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
undefined,
undefined,
{"tax_id":"677646","names":[{"lang":"en","v":"CITY LINK ENGINEERING LIMITED"},{"lang":"hk","v":"新城工程有限公司"}],"company_since":"1999-06-02","company_dissolved":"2001-02-16","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677652","names":[{"lang":"en","v":"HONG KONG YUE TONG LIMITED"},{"lang":"hk","v":"香港裕通置業有限公司"}],"company_since":"1999-06-02","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677574","names":[{"lang":"en","v":"HUNG KONG MACHINERY (H.K.) LIMITED"},{"lang":"hk","v":"雄港機械(香港)有限公司"}],"company_since":"1999-06-02","company_dissolved":"2006-10-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677595","names":[{"lang":"en","v":"IDEATOP LIMITED"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677731","names":[{"lang":"en","v":"FAST COMPANY LIMITED"},{"lang":"hk","v":"快得有限公司"}],"company_since":"1999-06-02","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677545","names":[{"lang":"en","v":"INTERNATIONAL KOONG-SHENG-MIAW HOLDINGS LIMITED"},{"lang":"hk","v":"國際孔聖廟集團有限公司"}],"company_since":"1999-06-02","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677671","names":[{"lang":"en","v":"HONG KONG SHUI HUA (GROUP) INVESTMENTS CO., LIMITED"},{"lang":"hk","v":"香港瑞華(集團)投資有限公司"}],"company_since":"1999-06-02","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677663","names":[{"lang":"en","v":"JACO FAR EAST LIMITED"},{"lang":"hk","v":"俊高遠東有限公司"}],"company_since":"1999-06-02","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677481","names":[{"lang":"en","v":"JAPAN BOAT OCTOPUS BALL CO., LIMITED"},{"lang":"hk","v":"日船章魚小丸子有限公司"}],"company_since":"1999-06-02","company_dissolved":"2003-09-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677606","names":[{"lang":"en","v":"FOOK LEE UNION MAINTENANCE ENGINEERING LIMITED"},{"lang":"hk","v":"福利華聯保養工程有限公司"}],"company_since":"1999-06-02","company_dissolved":"2008-10-31","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677655","names":[{"lang":"en","v":"JIN NING COMPANY LIMITED"},{"lang":"hk","v":"津寧有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677581","names":[{"lang":"en","v":"FORCE STAR LIMITED"},{"lang":"hk","v":"力卓有限公司"}],"company_since":"1999-06-02","company_dissolved":"2002-03-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677516","names":[{"lang":"en","v":"JOINT RICH (ASIA) LIMITED (d2004-05-28)"},{"lang":"hk","v":"裕聯(亞洲)有限公司"}],"company_since":"1999-06-02","company_dissolved":"2004-05-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677656","names":[{"lang":"en","v":"KAI HING TRANSPORTATION ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"嘉慶運輸工程有限公司"}],"company_since":"1999-06-02","company_dissolved":"2003-11-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677564","names":[{"lang":"en","v":"KAM LEE LUNG INTERNATIONAL LIMITED"},{"lang":"hk","v":"錦利隆國際有限公司"}],"company_since":"1999-06-02","company_dissolved":"2004-03-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677494","names":[{"lang":"en","v":"FREEWAY TRADING LIMITED (d2005-06-03)"}],"company_since":"1999-06-02","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677660","names":[{"lang":"en","v":"IMAGINATIVE DESIGN OPERATION CO. LIMITED"},{"lang":"hk","v":"天行科技有限公司"}],"company_since":"1999-06-02","company_dissolved":"2011-01-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677627","names":[{"lang":"en","v":"KING PRAISE LIMITED"},{"lang":"hk","v":"啓詠有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677508","names":[{"lang":"en","v":"KWONG HING TEXTILES LIMITED"},{"lang":"hk","v":"廣興紡織品有限公司"}],"company_since":"1999-06-02","company_dissolved":"2004-02-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677549","names":[{"lang":"en","v":"LAD PRINTING COMPANY LIMITED"},{"lang":"hk","v":"廣毅印刷有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677692","names":[{"lang":"en","v":"LAU WING HUM INTERNATIONAL FOUNDATION INC. LIMITED"},{"lang":"hk","v":"劉永鑫國際基金會有限公司"}],"company_since":"1999-06-02","company_dissolved":"2010-02-19","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"677502","names":[{"lang":"en","v":"LEARNABILITY (HK) COMPANY LIMITED"},{"lang":"hk","v":"能力達有限公司"}],"company_since":"1999-06-02","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677711","names":[{"lang":"en","v":"LETTER-I CORPORATION LIMITED (THE)"}],"company_since":"1999-06-02","company_dissolved":"2005-04-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677664","names":[{"lang":"en","v":"LAPTON LIMITED"},{"lang":"hk","v":"立敦有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677542","names":[{"lang":"en","v":"LIK PENG TECHNOLOGY LIMITED"},{"lang":"hk","v":"力鵬科技有限公司"}],"company_since":"1999-06-02","company_dissolved":"2004-08-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677509","names":[{"lang":"en","v":"LIMITLESS INTERNATIONAL LIMITED (d2005-06-03)"}],"company_since":"1999-06-02","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677715","names":[{"lang":"en","v":"LINKSOLUTIONS LIMITED"},{"lang":"hk","v":"領先方案有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677686","names":[{"lang":"en","v":"LINKSON DEVELOPMENT LIMITED (d2003-01-30)"},{"lang":"hk","v":"良信發展有限公司"}],"company_since":"1999-06-02","company_dissolved":"2003-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677543","names":[{"lang":"en","v":"LIPPO INDUSTRIAL LIMITED"},{"lang":"hk","v":"大豐實業有限公司"}],"company_since":"1999-06-02","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677478","names":[{"lang":"en","v":"MAK CHUNG MAN QIGONG MASTER LIMITED"},{"lang":"hk","v":"麥鐘文氣功師有限公司"}],"company_since":"1999-06-02","company_dissolved":"2011-11-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677460","names":[{"lang":"en","v":"GRAND MEDICAL COMPANY LIMITED"},{"lang":"hk","v":"弘利葯業有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677472","names":[{"lang":"en","v":"Management Resources Consultants (Asia) Limited"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677589","names":[{"lang":"en","v":"GRAND PACIFIC TECHNOLOGY LIMITED"},{"lang":"hk","v":"遠東科技有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677705","names":[{"lang":"en","v":"LEYLAND MANAGEMENT LIMITED (d2003-08-01)"},{"lang":"hk","v":"利來管理服務有限公司"}],"company_since":"1999-06-02","company_dissolved":"2003-08-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677618","names":[{"lang":"en","v":"MASTER INK COMPANY LIMITED"},{"lang":"hk","v":"萬事達墨水有限公司"}],"company_since":"1999-06-02","company_dissolved":"2020-07-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677604","names":[{"lang":"en","v":"MASTERFORD INVESTMENT LIMITED"},{"lang":"hk","v":"茂達投資有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677679","names":[{"lang":"en","v":"MAXON HONG KONG LIMITED (d2003-06-13)"},{"lang":"hk","v":"萬訊香港有限公司"}],"company_since":"1999-06-02","company_dissolved":"2003-06-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677623","names":[{"lang":"en","v":"MAYTAC HOLDINGS LIMITED"},{"lang":"hk","v":"萬達集團有限公司"}],"company_since":"1999-06-02","company_dissolved":"2006-04-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"677736","names":[{"lang":"en","v":"GREEN PEBBLES COMPANY LIMITED"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677675","names":[{"lang":"en","v":"GREAT YIELD ENTERPRISE LIMITED"},{"lang":"hk","v":"廣溢企業有限公司"}],"company_since":"1999-06-02","company_dissolved":"2005-09-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677621","names":[{"lang":"en","v":"MACROWN INVESTMENT LIMITED"},{"lang":"hk","v":"萬冠投資有限公司"}],"company_since":"1999-06-02","company_dissolved":"2014-10-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677536","names":[{"lang":"en","v":"MEGA MAX DEVELOPMENT LIMITED"},{"lang":"hk","v":"誌盛發展有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677625","names":[{"lang":"en","v":"MILIJOYCE INTERNATIONAL LIMITED"},{"lang":"hk","v":"百喜國際有限公司"}],"company_since":"1999-06-02","company_dissolved":"2001-08-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677471","names":[{"lang":"en","v":"MILLENNIUM LABORATORIES LIMITED"},{"lang":"hk","v":"創世紀藥業有限公司"}],"company_since":"1999-06-02","company_dissolved":"2001-04-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677714","names":[{"lang":"en","v":"HARVEST MILLION LIMITED (d2005-06-03)"},{"lang":"hk","v":"凱億有限公司"}],"company_since":"1999-06-02","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677486","names":[{"lang":"en","v":"MINKFAIR INSURANCE BROKERS LIMITED"},{"lang":"hk","v":"美輝保險顧問有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677639","names":[{"lang":"en","v":"MODERN CHAMPION LIMITED (d2006-01-13)"},{"lang":"hk","v":"添英有限公司"}],"company_since":"1999-06-02","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"677541","names":[{"lang":"en","v":"MODERN LINK TRADING LIMITED (d2006-10-13)"},{"lang":"hk","v":"茂通貿易有限公司"}],"company_since":"1999-06-02","company_dissolved":"2006-10-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677511","names":[{"lang":"en","v":"HENDA POWER (HONG KONG) LIMITED"},{"lang":"hk","v":"恒達電源(香港)有限公司"}],"company_since":"1999-06-02","company_dissolved":"2011-01-07","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677535","names":[{"lang":"en","v":"NEW CREATION INTERNATIONAL LIMITED (d2001-06-22)"},{"lang":"hk","v":"鴻越國際有限公司"}],"company_since":"1999-06-02","company_dissolved":"2001-06-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677521","names":[{"lang":"en","v":"NEW WELL ENGINEERING LIMITED (d2005-06-03)"},{"lang":"hk","v":"耀豐工程有限公司"}],"company_since":"1999-06-02","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677691","names":[{"lang":"en","v":"HONG KONG FUKIEN SANMING ASSOCIATION LIMITED"},{"lang":"hk","v":"香港福建三明聯會有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
{"tax_id":"677698","names":[{"lang":"en","v":"ONTARY DEVELOPMENT LIMITED"},{"lang":"hk","v":"安泰利發展有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677491","names":[{"lang":"en","v":"ORIANA ENTERPRISES LIMITED (d2002-05-31)"}],"company_since":"1999-06-02","company_dissolved":"2002-05-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677556","names":[{"lang":"en","v":"HONG KONG RILI INVESTMENTS LIMITED"},{"lang":"hk","v":"香港日利投資有限公司"}],"company_since":"1999-06-02","company_dissolved":"2000-06-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677489","names":[{"lang":"en","v":"ORIANA MANAGEMENT LIMITED (d2006-10-13)"}],"company_since":"1999-06-02","company_dissolved":"2006-10-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677610","names":[{"lang":"en","v":"HONG KONG SCHOOL NET LIMITED (THE)"},{"lang":"hk","v":"香港學校網絡有限公司"}],"company_since":"1999-06-02","company_dissolved":"2016-03-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677693","names":[{"lang":"en","v":"ORIENT SECURITIES HOLDINGS LIMITED"},{"lang":"hk","v":"東方滙財證券控股有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677662","names":[{"lang":"en","v":"PACIFIC SOURCE ENTERPRISES LIMITED"},{"lang":"hk","v":"太源企業有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677557","names":[{"lang":"en","v":"HONG KONG YUE TONG DECORATION LIMITED"},{"lang":"hk","v":"香港裕通裝修裝飾有限公司"}],"company_since":"1999-06-02","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677631","names":[{"lang":"en","v":"PACIFIC THREAD LIMITED"},{"lang":"hk","v":"太平洋線廠有限公司"}],"company_since":"1999-06-02","company_dissolved":"2020-05-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677703","names":[{"lang":"en","v":"PAK LEE LUNG INT'L INVESTMENT LIMITED"},{"lang":"hk","v":"百利隆國際投資有限公司"}],"company_since":"1999-06-02","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"677688","names":[{"lang":"en","v":"PEAK WORLD DEVELOPMENT LIMITED"},{"lang":"hk","v":"華鋒發展有限公司"}],"company_since":"1999-06-02","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677529","names":[{"lang":"en","v":"INNO TECH PROMOTION (HK) LIMITED"},{"lang":"hk","v":"全天候的士廣告(香港)有限公司"}],"company_since":"1999-06-02","company_dissolved":"2008-11-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677492","names":[{"lang":"en","v":"PECULIAR PRODUCTS &amp; PRODUCTION LIMITED"},{"lang":"hk","v":"特區首選影視製作有限公司"}],"company_since":"1999-06-02","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677497","names":[{"lang":"en","v":"PEONY C&amp;A LIMITED"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677669","names":[{"lang":"en","v":"POWERFUL (SAN TIN) BROTHERS WEAVING LIMITED"},{"lang":"hk","v":"寶威(三田)兄弟織有限公司"}],"company_since":"1999-06-02","company_dissolved":"2009-06-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"677559","names":[{"lang":"en","v":"PETROCHEMICAL PROJECTS (CHINA) LIMITED"},{"lang":"hk","v":"石化項目中國股份有限公司"}],"company_since":"1999-06-02","company_dissolved":"2019-05-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677528","names":[{"lang":"en","v":"POWER VIEW INTERNATIONAL INVESTMENT (HOLDINGS) LIMITED"},{"lang":"hk","v":"栢景國際投資(集團)有限公司"}],"company_since":"1999-06-02","company_dissolved":"2002-02-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"677683","names":[{"lang":"en","v":"POPULAR WAY ENGINEERING LIMITED"},{"lang":"hk","v":"興順工程有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677717","names":[{"lang":"en","v":"POWERLINK ASIA COMPANY LIMITED"},{"lang":"hk","v":"通訊力亞洲有限公司"}],"company_since":"1999-06-02","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677532","names":[{"lang":"en","v":"PIONEER INDUSTRIES LIMITED (d2005-06-03)"},{"lang":"hk","v":"潤泰實業有限公司"}],"company_since":"1999-06-02","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677700","names":[{"lang":"en","v":"PRINCEWELL FINANCIAL SERVICES LIMITED"}],"company_since":"1999-06-02","company_dissolved":"2006-12-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677567","names":[{"lang":"en","v":"RED KIDS GROUP (HONG KONG) LIMITED (d2005-06-03)"},{"lang":"hk","v":"紅孩兒集團(香港)有限公司"}],"company_since":"1999-06-02","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677733","names":[{"lang":"en","v":"PRASTAR LIMITED"},{"lang":"hk","v":"佰達有限公司"}],"company_since":"1999-06-02","company_dissolved":"2008-04-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677648","names":[{"lang":"en","v":"PRECIOUS METALS TRADING LIMITED"}],"company_since":"1999-06-02","company_dissolved":"2009-07-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677633","names":[{"lang":"en","v":"JOIN ASIA TECHNOLOGY LIMITED"},{"lang":"hk","v":"聯亞科技有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677507","names":[{"lang":"en","v":"HEASET TECHNOLOGY LIMITED"},{"lang":"hk","v":"恒森科技有限公司"}],"company_since":"1999-06-02","company_dissolved":"2008-09-26","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677668","names":[{"lang":"en","v":"RED SIX LIMITED (HK)"},{"lang":"hk","v":"風鈴貿易有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677650","names":[{"lang":"en","v":"KIN CHOW DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"建洲發展有限公司"}],"company_since":"1999-06-02","company_dissolved":"2011-06-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677638","names":[{"lang":"en","v":"RICHEST PACIFIC LIMITED"},{"lang":"hk","v":"鉅豐有限公司"}],"company_since":"1999-06-02","company_dissolved":"2007-05-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677513","names":[{"lang":"en","v":"RICHEST WINNER LIMITED"},{"lang":"hk","v":"榮裕有限公司"}],"company_since":"1999-06-02","company_dissolved":"2004-01-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677466","names":[{"lang":"en","v":"RMA GROUP LIMITED"}],"company_since":"1999-06-02","company_dissolved":"2001-11-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677483","names":[{"lang":"en","v":"LEIGH-MARDON (HONG KONG) LIMITED"}],"company_since":"1999-06-02","company_dissolved":"2006-01-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677637","names":[{"lang":"en","v":"ROYAL PROSPER LIMITED"},{"lang":"hk","v":"鋒明有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677632","names":[{"lang":"en","v":"SAPPORO HOUSE LIMITED"},{"lang":"hk","v":"札幌村有限公司"}],"company_since":"1999-06-02","company_dissolved":"2003-06-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677555","names":[{"lang":"en","v":"SHERBOURNE INTERNATIONAL LIMITED (d2004-03-26)"}],"company_since":"1999-06-02","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677534","names":[{"lang":"en","v":"SINO EXPRESS TRADING LIMITED (d2005-06-03)"},{"lang":"hk","v":"盈捷貿易有限公司"}],"company_since":"1999-06-02","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677628","names":[{"lang":"en","v":"LOYAL SUPREME LIMITED"},{"lang":"hk","v":"敬超有限公司"}],"company_since":"1999-06-02","company_dissolved":"2002-01-25","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677554","names":[{"lang":"en","v":"SIXTECH (HK) COMPANY LIMITED"},{"lang":"hk","v":"六科(香港)有限公司"}],"company_since":"1999-06-02","company_dissolved":"2011-02-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677651","names":[{"lang":"en","v":"SKYFORCE TECHNICAL SERVICES LIMITED"},{"lang":"hk","v":"天科技術服務有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677584","names":[{"lang":"en","v":"SPARKLE SHIPPING, GODOWN, WHARF &amp; TRANSP. CO., LIMITED"},{"lang":"hk","v":"柏高船務倉碼運輸有限公司"}],"company_since":"1999-06-02","company_dissolved":"2013-08-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677704","names":[{"lang":"en","v":"SPD TRADING LIMITED (d2004-12-17)"},{"lang":"hk","v":"上海金茂國際貿易(香港)有限公司"}],"company_since":"1999-06-02","company_dissolved":"2004-12-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677681","names":[{"lang":"en","v":"MAYSON ASIA LIMITED"},{"lang":"hk","v":"萬勝亞洲有限公司"}],"company_since":"1999-06-02","company_dissolved":"2005-11-11","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677592","names":[{"lang":"en","v":"SPEED FORD LIMITED (d2000-11-10)"},{"lang":"hk","v":"進永有限公司"}],"company_since":"1999-06-02","company_dissolved":"2000-11-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677517","names":[{"lang":"en","v":"SPEED SUCCESS INVESTMENT LIMITED"},{"lang":"hk","v":"明成投資有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677636","names":[{"lang":"en","v":"SPEED VICTORY LIMITED"},{"lang":"hk","v":"榮焯有限公司"}],"company_since":"1999-06-02","company_dissolved":"2001-07-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677730","names":[{"lang":"en","v":"SPEEDMATE LIMITED (d2006-02-10)"},{"lang":"hk","v":"快達美有限公司"}],"company_since":"1999-06-02","company_dissolved":"2006-02-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677728","names":[{"lang":"en","v":"IPP LIMITED (d2009-12-24)"}],"company_since":"1999-06-02","company_dissolved":"2009-12-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677591","names":[{"lang":"en","v":"STAR CREATIVE LIMITED"},{"lang":"hk","v":"星進有限公司"}],"company_since":"1999-06-02","company_dissolved":"2001-10-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677587","names":[{"lang":"en","v":"STAR FORTUNE DEVELOPMENT LIMITED (d2001-01-12)"},{"lang":"hk","v":"星裕發展有限公司"}],"company_since":"1999-06-02","company_dissolved":"2001-01-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677697","names":[{"lang":"en","v":"STARCROWN TRADING LIMITED"},{"lang":"hk","v":"星冠貿易有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677470","names":[{"lang":"en","v":"MILLENNIUM PHARMACEUTICAL HOLDING LIMITED"},{"lang":"hk","v":"創世紀醫藥集團有限公司"}],"company_since":"1999-06-02","company_dissolved":"2010-12-02","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677729","names":[{"lang":"en","v":"STARMATE TRADING LIMITED"},{"lang":"hk","v":"達美貿易有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677526","names":[{"lang":"en","v":"STARWORLD TECHNOLOGY LIMITED (d2008-11-14)"},{"lang":"hk","v":"達威科技有限公司"}],"company_since":"1999-06-02","company_dissolved":"2008-11-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677575","names":[{"lang":"en","v":"Stepup International Limited"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677624","names":[{"lang":"en","v":"STRONGWILL HOLDINGS LIMITED"},{"lang":"hk","v":"毅益集團有限公司"}],"company_since":"1999-06-02","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677617","names":[{"lang":"en","v":"NEW LEONARD FURNITURE COMPANY LIMITED"},{"lang":"hk","v":"新利來傢具有限公司"}],"company_since":"1999-06-02","company_dissolved":"2004-11-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677576","names":[{"lang":"en","v":"SUNSHINE KNITTING FACTORY COMPANY LIMITED"},{"lang":"hk","v":"陽光針織廠有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677498","names":[{"lang":"en","v":"NT HOUSING DEVELOPMENT CONSULTANT LIMITED"},{"lang":"hk","v":"卓餘新界屋宇發展顧問有限公司"}],"company_since":"1999-06-02","company_dissolved":"2012-01-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677552","names":[{"lang":"en","v":"SYNCLINK TRANSPORTATION (H.K.) CO., LIMITED"},{"lang":"hk","v":"正聯(香港)股份有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677614","names":[{"lang":"en","v":"TAKASHI HOLDINGS LIMITED"},{"lang":"hk","v":"智隆集團有限公司"}],"company_since":"1999-06-02","company_dissolved":"2001-08-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677635","names":[{"lang":"en","v":"TALENT FINE LIMITED (d2008-11-14)"},{"lang":"hk","v":"百和有限公司"}],"company_since":"1999-06-02","company_dissolved":"2008-11-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677737","names":[{"lang":"en","v":"TEAMATES COMPANY LIMITED"},{"lang":"hk","v":"奧域高有限公司"}],"company_since":"1999-06-02","company_dissolved":"2013-08-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677643","names":[{"lang":"en","v":"PACIFIC CHAMPION INVESTMENT LIMITED"},{"lang":"hk","v":"佳明投資有限公司"}],"company_since":"1999-06-02","company_dissolved":"2007-08-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677467","names":[{"lang":"en","v":"TechPower Development Limited"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677708","names":[{"lang":"en","v":"TELECOM CONVENIENCE STORE LIMITED"},{"lang":"hk","v":"電訊便利店有限公司"}],"company_since":"1999-06-02","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677514","names":[{"lang":"en","v":"PACIFIC CREATIVE LIMITED (d2001-05-18)"},{"lang":"hk","v":"煌裕有限公司"}],"company_since":"1999-06-02","company_dissolved":"2001-05-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677613","names":[{"lang":"en","v":"THERMO ENGINEERING AND CONSULTANTS LIMITED"},{"lang":"hk","v":"暉武工程有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677480","names":[{"lang":"en","v":"TIDEWATER DESIGNS INTERNATIONAL (HK) COMPANY LIMITED"}],"company_since":"1999-06-02","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677690","names":[{"lang":"en","v":"TIFFANY INVESTMENTS LIMITED (d2003-12-05)"},{"lang":"hk","v":"雅妍投資有限公司"}],"company_since":"1999-06-02","company_dissolved":"2003-12-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677599","names":[{"lang":"en","v":"TOP LINE INTERNATIONAL LIMITED"},{"lang":"hk","v":"宏洲國際有限公司"}],"company_since":"1999-06-02","company_dissolved":"2004-12-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677544","names":[{"lang":"en","v":"TOPBASE (HK) INVESTMENT LIMITED"},{"lang":"hk","v":"力昇(香港)股份有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677598","names":[{"lang":"en","v":"TOPSTYLE INTERNATIONAL LIMITED"},{"lang":"hk","v":"善美國際有限公司"}],"company_since":"1999-06-02","company_dissolved":"2004-01-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677611","names":[{"lang":"en","v":"TOTAL LOGISTICS SERVICES LIMITED (d2008-07-04)"},{"lang":"hk","v":"香港物流中心有限公司"}],"company_since":"1999-06-02","company_dissolved":"2008-07-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677520","names":[{"lang":"en","v":"PIONEER PLAN INTERNATIONAL LIMITED"},{"lang":"hk","v":"豐進國際有限公司"}],"company_since":"1999-06-02","company_dissolved":"2006-07-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677653","names":[{"lang":"en","v":"TRIMEN BUSINESS CONSULTING LIMITED"},{"lang":"hk","v":"三民商業顧問有限公司"}],"company_since":"1999-06-02","company_dissolved":"2000-06-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677504","names":[{"lang":"en","v":"TSANG YUEN HOLDINGS COMPANY LIMITED"},{"lang":"hk","v":"曾遠集團有限公司"}],"company_since":"1999-06-02","company_dissolved":"2000-10-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677634","names":[{"lang":"en","v":"UNION WORLD 2000 LIMITED"},{"lang":"hk","v":"寰球2000有限公司"}],"company_since":"1999-06-02","company_dissolved":"2002-01-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677519","names":[{"lang":"en","v":"UNITED DRAGON INTERNATIONAL LIMITED (d2006-01-13)"},{"lang":"hk","v":"龍俊國際有限公司"}],"company_since":"1999-06-02","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677487","names":[{"lang":"en","v":"UNITED OVERSEAS TECHNOLOGY LIMITED"},{"lang":"hk","v":"聯僑科技有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677579","names":[{"lang":"en","v":"UNITED WIN ENTERPRISES LIMITED"},{"lang":"hk","v":"聯成企業有限公司"}],"company_since":"1999-06-02","company_dissolved":"2001-07-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677597","names":[{"lang":"en","v":"REGALUXE (HK) LIMITED"},{"lang":"hk","v":"捷能(香港)有限公司"}],"company_since":"1999-06-02","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677560","names":[{"lang":"en","v":"UNIVERSAL CHAMPION VIDEO LIMITED"},{"lang":"hk","v":"冠宇影視有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677572","names":[{"lang":"en","v":"UTMOST ASIA LIMITED"}],"company_since":"1999-06-02","company_dissolved":"2012-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677644","names":[{"lang":"en","v":"RICH FUND INTERNATIONAL LIMITED (d2005-06-03)"},{"lang":"hk","v":"豐佳國際有限公司"}],"company_since":"1999-06-02","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677475","names":[{"lang":"en","v":"VASFORD INTERNATIONAL LIMITED"},{"lang":"hk","v":"威福國際有限公司"}],"company_since":"1999-06-02","company_dissolved":"2012-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677578","names":[{"lang":"en","v":"VISION TELECOMMUNICATIONS LIMITED"},{"lang":"hk","v":"滙科企業有限公司"}],"company_since":"1999-06-02","company_dissolved":"2012-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677654","names":[{"lang":"en","v":"W &amp; W TECHNICAL COMPANY LIMITED"},{"lang":"hk","v":"永榮電機工程有限公司"}],"company_since":"1999-06-02","company_dissolved":"2006-05-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677518","names":[{"lang":"en","v":"ROYAL LEADER INVESTMENT LIMITED (d2005-06-03)"},{"lang":"hk","v":"美順投資有限公司"}],"company_since":"1999-06-02","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677642","names":[{"lang":"en","v":"ROYAL WEALTH INVESTMENT LIMITED"},{"lang":"hk","v":"利昌投資有限公司"}],"company_since":"1999-06-02","company_dissolved":"2012-01-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677674","names":[{"lang":"en","v":"WAI CHEONG HONG COMPANY LIMITED"},{"lang":"hk","v":"偉昌行運輸有限公司"}],"company_since":"1999-06-02","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677626","names":[{"lang":"en","v":"WELLMAX INTERNATIONAL LIMITED (d2000-09-29)"},{"lang":"hk","v":"威力國際有限公司"}],"company_since":"1999-06-02","company_dissolved":"2000-09-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677609","names":[{"lang":"en","v":"SCHUTTE &amp; PANZER (FAR EAST) LIMITED"},{"lang":"hk","v":"瑞達潘徹(遠東)有限公司"}],"company_since":"1999-06-02","company_dissolved":"2010-12-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677665","names":[{"lang":"en","v":"WIDE PEACE LIMITED (d2008-11-14)"},{"lang":"hk","v":"浩和有限公司"}],"company_since":"1999-06-02","company_dissolved":"2008-11-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677531","names":[{"lang":"en","v":"SHING LEE ENGINEERING CONTAINER COMPANY LIMITED"},{"lang":"hk","v":"成利工程貨運有限公司"}],"company_since":"1999-06-02","company_dissolved":"2014-10-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677601","names":[{"lang":"en","v":"WINSON INVESTMENTS LIMITED (d2010-06-25)"},{"lang":"hk","v":"勤信投資有限公司"}],"company_since":"1999-06-02","company_dissolved":"2010-06-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677468","names":[{"lang":"en","v":"WORLD PRO KENNEX HONG KONG LIMITED"}],"company_since":"1999-06-02","company_dissolved":"2006-10-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677461","names":[{"lang":"en","v":"WORLD RENOWNED WINE TRANSNATIONAL GROUP HONG KONG KING WINE BUSINESS LIMITED"},{"lang":"hk","v":"世界名酒名飲跨國集團香港天王酒業有限公司"}],"company_since":"1999-06-02","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677569","names":[{"lang":"en","v":"SKT DESIGNS LIMITED (d2006-01-13)"}],"company_since":"1999-06-02","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677590","names":[{"lang":"en","v":"WORLD TRADE 2000 LIMITED"},{"lang":"hk","v":"創業2000有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677573","names":[{"lang":"en","v":"XIAN AERO-TRADE INTERNATIONAL (HK) LIMITED"},{"lang":"hk","v":"西航國際(香港)有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677482","names":[{"lang":"en","v":"YING KEE CONSTRUCTION COMPANY LIMITED"},{"lang":"hk","v":"營記建築有限公司"}],"company_since":"1999-06-02","company_dissolved":"2009-10-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677680","names":[{"lang":"en","v":"YOUNGWAY ASIA LIMITED"},{"lang":"hk","v":"盈威亞洲有限公司"}],"company_since":"1999-06-02","company_dissolved":"2002-03-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677547","names":[{"lang":"en","v":"YUANTONG SHIPPING (HONG KONG) CO., LIMITED"},{"lang":"hk","v":"圓通船務(香港)有限公司"}],"company_since":"1999-06-02","company_dissolved":"2007-12-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677459","names":[{"lang":"en","v":"YUE FUNG FASHION WHOLESALE COMPANY LIMITED"}],"company_since":"1999-06-02","company_dissolved":"2000-06-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677605","names":[{"lang":"en","v":"WIDETECH INVESTMENTS LIMITED"},{"lang":"hk","v":"奔駿投資有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"677524","names":[{"lang":"en","v":"SUNNY KINGDOM LIMITED (d2005-06-03)"},{"lang":"hk","v":"新榮興業有限公司"}],"company_since":"1999-06-02","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"677568","names":[{"lang":"en","v":"STRONG JEWELRY (H.K.) COMPANY LIMITED"},{"lang":"hk","v":"宗宗珠寶(香港)有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677647","names":[{"lang":"en","v":"TIAN RUN (HONG KONG) INDUSTRIAL LIMITED (d2006-01-13)"},{"lang":"hk","v":"天潤(香港)實業有限公司"}],"company_since":"1999-06-02","company_dissolved":"2006-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677571","names":[{"lang":"en","v":"TOP EXPRESS MACHINERY &amp; EQUIPMENT LIMITED"},{"lang":"hk","v":"萬匯機械設備有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677622","names":[{"lang":"en","v":"TREASURE STATE HOLDINGS LIMITED"},{"lang":"hk","v":"邦富集團有限公司"}],"company_since":"1999-06-02","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677649","names":[{"lang":"en","v":"UNITED PROSPERITY CONSTRUCTION COMPANY LIMITED"},{"lang":"hk","v":"聯永豐建築有限公司"}],"company_since":"1999-06-02","company_dissolved":"2012-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677600","names":[{"lang":"en","v":"VCOM MEDIA (H.K.) LIMITED"},{"lang":"hk","v":"深域多媒體有限公司"}],"company_since":"1999-06-02","company_dissolved":"2014-10-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"677501","names":[{"lang":"en","v":"WAH SHING CANDLE CO. LIMITED"},{"lang":"hk","v":"華盛燭業製品有限公司"}],"company_since":"1999-06-02","company_dissolved":"2012-09-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"677735","names":[{"lang":"en","v":"WIEMER LEATHERGOODS MFG. CO. LIMITED"},{"lang":"hk","v":"威馬皮具製造有限公司"}],"company_since":"1999-06-02","company_dissolved":"2007-09-14","company_type_txt":"Private, ltd by shares"},
undefined,
