undefined,
undefined,
{"tax_id":"746161","names":[{"lang":"en","v":"CONSTANT PIONEER INTERNATIONAL GROUP (HONG KONG) LIMITED"},{"lang":"hk","v":"康絲柏妮國際集團(香港)有限公司"}],"company_since":"2001-02-05","company_dissolved":"2010-07-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"746101","names":[{"lang":"en","v":"GLORY ROYAL LIMITED"},{"lang":"hk","v":"嘉廷有限公司"}],"company_since":"2001-02-05","company_dissolved":"2002-01-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"746153","names":[{"lang":"en","v":"HELIOSS COMMUNICATIONS ASIA LIMITED"}],"company_since":"2001-02-05","company_dissolved":"2002-12-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"746131","names":[{"lang":"en","v":"HOORAY CONSULTING LIMITED"},{"lang":"hk","v":"好盈顧問有限公司"}],"company_since":"2001-02-05","company_dissolved":"2007-08-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"746142","names":[{"lang":"en","v":"HONG KONG GREAT MAN INTERNATIONAL EDUCATION (HOLDINGS) LIMITED (d2016-07-15)"},{"lang":"hk","v":"香港偉才國際教育(集團)有限公司"}],"company_since":"2001-02-05","company_dissolved":"2016-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"746102","names":[{"lang":"en","v":"MAC PROFIT LIMITED"},{"lang":"hk","v":"賀盈有限公司"}],"company_since":"2001-02-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"746129","names":[{"lang":"en","v":"ROCHET HONG KONG LIMITED"}],"company_since":"2001-02-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"746115","names":[{"lang":"en","v":"SAMMEI BAKERY COMPANY LIMITED"},{"lang":"hk","v":"森美麵包西餅有限公司"}],"company_since":"2001-02-05","company_dissolved":"2009-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"746127","names":[{"lang":"en","v":"SUN SPARK ENVIRONMENTAL SERVICES LIMITED (d2008-10-03)"},{"lang":"hk","v":"裕輝環保服務有限公司"}],"company_since":"2001-02-05","company_dissolved":"2008-10-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"746133","names":[{"lang":"en","v":"TANGENT POINT INTERNATIONAL LIMITED"},{"lang":"hk","v":"騰晉國際有限公司"}],"company_since":"2001-02-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"746128","names":[{"lang":"en","v":"R &amp; A TRADING LIMITED (d2006-08-04)"}],"company_since":"2001-02-05","company_dissolved":"2006-08-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"746142","names":[{"lang":"en","v":"HONG KONG GREAT MAN INTERNATIONAL EDUCATION (HOLDINGS) LIMITED (d2016-07-15)"},{"lang":"hk","v":"香港偉才國際教育(集團)有限公司"}],"company_since":"2001-02-05","company_dissolved":"2016-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"746155","names":[{"lang":"en","v":"WINLUCK INC. LIMITED"},{"lang":"hk","v":"凝彩永樂有限公司"}],"company_since":"2001-02-05","company_dissolved":"2010-06-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"746085","names":[{"lang":"en","v":"WISECO MANAGEMENT LIMITED (d2016-08-26)"},{"lang":"hk","v":"威潤管理有限公司"}],"company_since":"2001-02-05","company_dissolved":"2016-08-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"746165","names":[{"lang":"en","v":"WORLD LINK CPA LIMITED"},{"lang":"hk","v":"華普天健(香港)會計師事務所有限公司"}],"company_since":"2001-02-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"746145","names":[{"lang":"en","v":"XIANG YUAN PRECISION DIE CASTING CO. LIMITED"},{"lang":"hk","v":"祥遠精密壓鑄有限公司"}],"company_since":"2001-02-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"746151","names":[{"lang":"en","v":"XIN SONG BUSSAN (HK) COMPANY LIMITED"},{"lang":"hk","v":"新松物產(香港)有限公司"}],"company_since":"2001-02-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"746134","names":[{"lang":"en","v":"YEUNG PUI METAL FOUNDATION ENGINEERING LIMITED"},{"lang":"hk","v":"楊沛鐵器地基工程有限公司"}],"company_since":"2001-02-05","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
