undefined,
{"tax_id":"653080","names":[{"lang":"en","v":"FUBANG DECORATING ENGINEERING CO., LIMITED"},{"lang":"hk","v":"富邦裝飾工程有限公司"}],"company_since":"1998-08-26","company_dissolved":"2005-08-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"653078","names":[{"lang":"en","v":"FUBANG OFFICE FURNITURE CO., LIMITED"},{"lang":"hk","v":"富邦商用家具有限公司"}],"company_since":"1998-08-26","company_dissolved":"2003-06-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653031","names":[{"lang":"en","v":"FULL FORTUNE ENGINEERING LIMITED"},{"lang":"hk","v":"國濠工程有限公司"}],"company_since":"1998-08-26","company_dissolved":"2009-10-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653207","names":[{"lang":"en","v":"GLORY FAME INVESTMENT LIMITED"},{"lang":"hk","v":"嘉耀投資有限公司"}],"company_since":"1998-08-26","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653186","names":[{"lang":"en","v":"GOLD LEADER CONSULTANTS LIMITED (d2005-08-12)"}],"company_since":"1998-08-26","company_dissolved":"2005-08-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653130","names":[{"lang":"en","v":"GOLDEN LIGHT INDUSTRIES LIMITED"}],"company_since":"1998-08-26","company_dissolved":"2007-01-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653219","names":[{"lang":"en","v":"GRANDMAX ENTERPRISES LIMITED (d2010-05-20)"},{"lang":"hk","v":"嘉明企業有限公司"}],"company_since":"1998-08-26","company_dissolved":"2010-05-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653188","names":[{"lang":"en","v":"HAPPY GAIN INVESTMENTS LIMITED"}],"company_since":"1998-08-26","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653110","names":[{"lang":"en","v":"HINGFAT INDUSTRIES (FAR EAST) CO. LIMITED"},{"lang":"hk","v":"興發實業(遠東)有限公司"}],"company_since":"1998-08-26","company_dissolved":"2011-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653213","names":[{"lang":"en","v":"HINWAY HOLDINGS LIMITED"},{"lang":"hk","v":"興匯集團有限公司"}],"company_since":"1998-08-26","company_dissolved":"2005-08-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653174","names":[{"lang":"en","v":"HOE LEONG MACHINERY (H.K.) LIMITED"},{"lang":"hk","v":"和隆機械(香港)有限公司"}],"company_since":"1998-08-26","company_dissolved":"2015-03-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653170","names":[{"lang":"en","v":"HOI WAN FOOD &amp; BEVERAGE LIMITED"},{"lang":"hk","v":"海運飲食有限公司"}],"company_since":"1998-08-26","company_dissolved":"2016-01-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653089","names":[{"lang":"en","v":"HARMONY LIGHTING INTERNATIONAL LIMITED"},{"lang":"hk","v":"合泊國際燈飾有限公司"}],"company_since":"1998-08-26","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653097","names":[{"lang":"en","v":"HONG KONG JIANG NAN ELECTROSTATIC DEFENSE TECHNOLOGY LIMITED"},{"lang":"hk","v":"香港江南靜電防護技術有限公司"}],"company_since":"1998-08-26","company_dissolved":"2005-08-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653086","names":[{"lang":"en","v":"GIFT MART INDUSTRIAL LIMITED"},{"lang":"hk","v":"天栢製品實業有限公司"}],"company_since":"1998-08-26","company_dissolved":"2010-12-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653070","names":[{"lang":"en","v":"HONG KONG K. C. COMPANY LIMITED"},{"lang":"hk","v":"香港雙龍有限公司"}],"company_since":"1998-08-26","company_dissolved":"2019-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"653147","names":[{"lang":"en","v":"FORTUNE UNITED CONSULTANTS LIMITED"},{"lang":"hk","v":"祥和顧問有限公司"}],"company_since":"1998-08-26","company_dissolved":"2000-08-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653093","names":[{"lang":"en","v":"HONG KONG LUCK STAR LIMITED"},{"lang":"hk","v":"香港良辰有限公司"}],"company_since":"1998-08-26","company_dissolved":"2020-06-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653024","names":[{"lang":"en","v":"HONG KONG SOCIETY OF CERTIFIED INSURANCE PRACTITIONERS LIMITED (THE)"},{"lang":"hk","v":"香港保險師公會有限公司"}],"company_since":"1998-08-26","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
undefined,
undefined,
undefined,
{"tax_id":"653165","names":[{"lang":"en","v":"HONG YOUNG FASHIONS LIMITED"},{"lang":"hk","v":"康洋時裝有限公司"}],"company_since":"1998-08-26","company_dissolved":"2010-03-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"653204","names":[{"lang":"en","v":"HONG KONG STARLIGHT INDUSTRIAL INTERNATIONAL LIMITED"},{"lang":"hk","v":"香港星光實業國際有限公司"}],"company_since":"1998-08-26","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653197","names":[{"lang":"en","v":"ECON TRADING LIMITED"},{"lang":"hk","v":"宜康貿易有限公司"}],"company_since":"1998-08-26","company_dissolved":"2004-04-23","company_type_txt":"Private, ltd by shares"},
{"tax_id":"653073","names":[{"lang":"en","v":"HUAN QIU PUBLICATION LIMITED"},{"lang":"hk","v":"環球出版社有限公司"}],"company_since":"1998-08-26","company_dissolved":"2005-08-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"653132","names":[{"lang":"en","v":"HIGH DRAGON RESOURCES LIMITED"}],"company_since":"1998-08-26","company_dissolved":"2012-06-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653046","names":[{"lang":"en","v":"IMPERION LIMITED (HK)"}],"company_since":"1998-08-26","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653092","names":[{"lang":"en","v":"HONGKONG CHINA SCIENCE INTELLIGENT NETWORK SYSTEM LIMITED"},{"lang":"hk","v":"香港中科智能網絡系統有限公司"}],"company_since":"1998-08-26","company_dissolved":"2001-06-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653037","names":[{"lang":"en","v":"E-EX.COM LIMITED"}],"company_since":"1998-08-26","company_dissolved":"2005-05-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"653075","names":[{"lang":"en","v":"K &amp; 9 DEVELOPMENT LIMITED"},{"lang":"hk","v":"柯恩耐發展有限公司"}],"company_since":"1998-08-26","company_dissolved":"2016-03-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653124","names":[{"lang":"en","v":"EUROCRANE MATERIAL HANDLING ENGINEERING LIMITED"},{"lang":"hk","v":"歐洲起重設備有限公司"}],"company_since":"1998-08-26","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"653071","names":[{"lang":"en","v":"KAI LEE SYSTEM CO., LIMITED"},{"lang":"hk","v":"佳利系統有限公司"}],"company_since":"1998-08-26","company_dissolved":"2005-05-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"653062","names":[{"lang":"en","v":"FELICITY LIMITED"},{"lang":"hk","v":"富樂事有限公司"}],"company_since":"1998-08-26","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653172","names":[{"lang":"en","v":"KIMBERLEY AIR SEA FORWARDERS LIMITED"},{"lang":"hk","v":"金巴利貨運有限公司"}],"company_since":"1998-08-26","company_dissolved":"2001-09-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653153","names":[{"lang":"en","v":"FESDON INTERNATIONAL LIMITED"},{"lang":"hk","v":"發祥國際有限公司"}],"company_since":"1998-08-26","company_dissolved":"2005-08-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"653180","names":[{"lang":"en","v":"GOLDEN CHEMICALS LIMITED"},{"lang":"hk","v":"金島化工有限公司"}],"company_since":"1998-08-26","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"653195","names":[{"lang":"en","v":"MATSUZAKAYA COMPANY, LIMITED"},{"lang":"hk","v":"松坂屋有限公司"}],"company_since":"1998-08-26","company_dissolved":"2013-03-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653209","names":[{"lang":"en","v":"GOODMAX TRADING LIMITED"},{"lang":"hk","v":"裕明貿易有限公司"}],"company_since":"1998-08-26","company_dissolved":"2008-01-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"653142","names":[{"lang":"en","v":"HARMONY WORLD DEVELOPMENT LIMITED"},{"lang":"hk","v":"亨世發展有限公司"}],"company_since":"1998-08-26","company_dissolved":"2003-03-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653133","names":[{"lang":"en","v":"NEW DAWN LIMITED"}],"company_since":"1998-08-26","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"653178","names":[{"lang":"en","v":"NEUTRIEN INTERNATIONAL LIMITED"},{"lang":"hk","v":"賜多力國際有限公司"}],"company_since":"1998-08-26","company_dissolved":"2006-02-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653095","names":[{"lang":"en","v":"NIPPON CURTAIN WALL ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"力港幕牆安裝工程有限公司"}],"company_since":"1998-08-26","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653200","names":[{"lang":"en","v":"OCEAN RICH INVESTMENT (HK) LIMITED"},{"lang":"hk","v":"海富投資(香港)有限公司"}],"company_since":"1998-08-26","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653203","names":[{"lang":"en","v":"ORBI (HK) LIMITED"}],"company_since":"1998-08-26","company_dissolved":"2013-09-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"653123","names":[{"lang":"en","v":"PRO-BRIGHT KNITTING FACTORY LIMITED"},{"lang":"hk","v":"明輝針織廠有限公司"}],"company_since":"1998-08-26","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"653047","names":[{"lang":"en","v":"INVESTLINK INTERNATIONAL LIMITED"},{"lang":"hk","v":"盛隆國際股份有限公司"}],"company_since":"1998-08-26","company_dissolved":"2011-04-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"653048","names":[{"lang":"en","v":"JUM QUALITY MANAGEMENT LIMITED"}],"company_since":"1998-08-26","company_dissolved":"2016-06-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"653081","names":[{"lang":"en","v":"SATYA ENGINEERING CO., LIMITED"},{"lang":"hk","v":"聖藝工程有限公司"}],"company_since":"1998-08-26","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"653104","names":[{"lang":"en","v":"KINGWOOD FAREAST ENGINEERING LIMITED"},{"lang":"hk","v":"利威遠東工程有限公司"}],"company_since":"1998-08-26","company_dissolved":"2005-08-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653085","names":[{"lang":"en","v":"KINGWOOD PACIFIC LIMITED"},{"lang":"hk","v":"利威太平洋有限公司"}],"company_since":"1998-08-26","company_dissolved":"2008-09-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"653042","names":[{"lang":"en","v":"SINCERE ENGINEERING (HONG KONG) LIMITED"},{"lang":"hk","v":"先達工程(香港)有限公司"}],"company_since":"1998-08-26","company_dissolved":"2004-01-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653211","names":[{"lang":"en","v":"LANBO ENTERPRISES LIMITED (d2005-08-12)"},{"lang":"hk","v":"順寶企業有限公司"}],"company_since":"1998-08-26","company_dissolved":"2005-08-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"653154","names":[{"lang":"en","v":"EVER VICEROY INTERNATIONAL LIMITED"},{"lang":"hk","v":"長偉國際有限公司"}],"company_since":"1998-08-26","company_dissolved":"2005-08-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653116","names":[{"lang":"en","v":"SMART LEGEND ENTERPRISE LIMITED"},{"lang":"hk","v":"鴻力企業有限公司"}],"company_since":"1998-08-26","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"653055","names":[{"lang":"en","v":"SOUTH CAPITAL NOMINEES LIMITED"},{"lang":"hk","v":"南方中天代理有限公司"}],"company_since":"1998-08-26","company_dissolved":"2020-06-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"653151","names":[{"lang":"en","v":"SUNCON ENGINEERING LIMITED"},{"lang":"hk","v":"信光工程有限公司"}],"company_since":"1998-08-26","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653034","names":[{"lang":"en","v":"SUNWAY COATING EQUIPMENT (H.K.) COMPANY LIMITED"},{"lang":"hk","v":"生惠塗裝設備(香港)有限公司"}],"company_since":"1998-08-26","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"653190","names":[{"lang":"en","v":"NEW TIGER PROPERTIES LIMITED"}],"company_since":"1998-08-26","company_dissolved":"2008-04-11","company_type_txt":"Private, ltd by shares"},
{"tax_id":"653143","names":[{"lang":"en","v":"EVERGLAD ENTERPRISES LIMITED"},{"lang":"hk","v":"長建企業有限公司"}],"company_since":"1998-08-26","company_dissolved":"2015-04-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"653060","names":[{"lang":"en","v":"SUNRISE ESTATE AGENCY (TSUEN WAN) LIMITED"},{"lang":"hk","v":"惠利物業代理(荃灣)有限公司"}],"company_since":"1998-08-26","company_dissolved":"2015-01-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"653111","names":[{"lang":"en","v":"TIANYIN SOFTWARE (HONG KONG) LIMITED"},{"lang":"hk","v":"天音軟件(香港)有限公司"}],"company_since":"1998-08-26","company_dissolved":"2005-08-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"653032","names":[{"lang":"en","v":"UNI-ACE UNDERWATER SERVICES (H.K.) LIMITED"},{"lang":"hk","v":"毅聯海底服務(香港)有限公司"}],"company_since":"1998-08-26","company_dissolved":"2005-08-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"653210","names":[{"lang":"en","v":"UNIBO TRADING LIMITED"},{"lang":"hk","v":"裕寶貿易有限公司"}],"company_since":"1998-08-26","company_dissolved":"2016-05-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"653221","names":[{"lang":"en","v":"UNILAND INTERNATIONAL LIMITED (d2005-08-12)"},{"lang":"hk","v":"裕立國際有限公司"}],"company_since":"1998-08-26","company_dissolved":"2005-08-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"653208","names":[{"lang":"en","v":"United Securities Limited"},{"lang":"hk","v":"團結證券有限公司"}],"company_since":"1998-08-26","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"653146","names":[{"lang":"en","v":"VICTORY UNITED TRADING LIMITED"},{"lang":"hk","v":"凱悅貿易有限公司"}],"company_since":"1998-08-26","company_dissolved":"2004-06-25","company_type_txt":"Private, ltd by shares"},
{"tax_id":"653113","names":[{"lang":"en","v":"TETLY GARMENT MANUFACTURING COMPANY LIMITED"},{"lang":"hk","v":"德利安實業有限公司"}],"company_since":"1998-08-26","company_dissolved":"2003-03-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653118","names":[{"lang":"en","v":"UTOPIA (FAR EAST) ENTERPRISE LIMITED"},{"lang":"hk","v":"裕都(遠東)企業有限公司"}],"company_since":"1998-08-26","company_dissolved":"2005-04-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"653187","names":[{"lang":"en","v":"VISION TEXTILES LIMITED"}],"company_since":"1998-08-26","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653175","names":[{"lang":"en","v":"W.K. CHEUNG &amp; ASSOCIATES LIMITED"},{"lang":"hk","v":"張惠強建築工程顧問有限公司"}],"company_since":"1998-08-26","company_dissolved":"2014-02-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"653076","names":[{"lang":"en","v":"WANG FUNG LIMITED"},{"lang":"hk","v":"宏豐(粵港)有限公司"}],"company_since":"1998-08-26","company_dissolved":"2005-08-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"653100","names":[{"lang":"en","v":"WINDION LIMITED"},{"lang":"hk","v":"永德隆有限公司"}],"company_since":"1998-08-26","company_dissolved":"2010-01-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"653087","names":[{"lang":"en","v":"WORLD TAI JI YANG SHENG SCIENCE ASSOCIATION LIMITED"},{"lang":"hk","v":"世界太極養生科學聯合會有限公司"}],"company_since":"1998-08-26","company_dissolved":"2011-04-29","company_type_txt":"Ltd by guarantee"},
undefined,
undefined,
{"tax_id":"653128","names":[{"lang":"en","v":"WARWICK ASSET MANAGEMENT LIMITED"}],"company_since":"1998-08-26","company_dissolved":"2007-08-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"653176","names":[{"lang":"en","v":"YATLEY CANTEEN LIMITED"},{"lang":"hk","v":"日利食堂有限公司"}],"company_since":"1998-08-26","company_dissolved":"2009-03-27","company_type_txt":"Private, ltd by shares"},
undefined,
