undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"634395","names":[{"lang":"en","v":"EXCELLENCE STEEL FURNITURE FACTORY LIMITED"},{"lang":"hk","v":"卓越鋼具有限公司"}],"company_since":"1998-01-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"634343","names":[{"lang":"en","v":"HIN KEE COMPANY LIMITED (d2002-09-06)"},{"lang":"hk","v":"顯記夾板門廠有限公司"}],"company_since":"1998-01-09","company_dissolved":"2002-09-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"634387","names":[{"lang":"en","v":"LANSON ENTERPRISES LIMITED (d2009-08-14)"},{"lang":"hk","v":"興信企業有限公司"}],"company_since":"1998-01-09","company_dissolved":"2009-08-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"634366","names":[{"lang":"en","v":"INSTITUTIONAL FUNDS ADVISORS LIMITED"}],"company_since":"1998-01-09","company_dissolved":"2002-07-26","company_type_txt":"Private, ltd by shares"},
{"tax_id":"634352","names":[{"lang":"en","v":"MATSUOKA (CHINA) INVESTMENTS CO., LIMITED"},{"lang":"hk","v":"松岡(中國)投資有限公司"}],"company_since":"1998-01-09","company_dissolved":"2002-05-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"634397","names":[{"lang":"en","v":"MICHAEL J DESIGN LIMITED"},{"lang":"hk","v":"水木設計有限公司"}],"company_since":"1998-01-09","company_dissolved":"2015-08-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"634270","names":[{"lang":"en","v":"MIDAS GOLD MANAGEMENT LIMITED"},{"lang":"hk","v":"迪金管理有限公司"}],"company_since":"1998-01-09","company_dissolved":"2003-04-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"634340","names":[{"lang":"en","v":"MY FAVOURITE RESTAURANT LIMITED"},{"lang":"hk","v":"我所至愛餐廳有限公司"}],"company_since":"1998-01-09","company_dissolved":"2007-05-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"634410","names":[{"lang":"en","v":"NISSAI HONG KONG COMPANY LIMITED"},{"lang":"hk","v":"日彩香港有限公司"}],"company_since":"1998-01-09","company_dissolved":"2009-05-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"634272","names":[{"lang":"en","v":"INTREPID GOLD INTERNATIONAL LIMITED"},{"lang":"hk","v":"遠跨國際有限公司"}],"company_since":"1998-01-09","company_dissolved":"2003-09-11","company_type_txt":"Private, ltd by shares"},
{"tax_id":"634407","names":[{"lang":"en","v":"INTELLIK TECHNOLOGY (H.K.) CO., LIMITED"},{"lang":"hk","v":"昱展(香港)科技發展有限公司"}],"company_since":"1998-01-09","company_dissolved":"2005-12-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"634284","names":[{"lang":"en","v":"JADESON TRADING LIMITED (d2005-11-04)"},{"lang":"hk","v":"集誠貿易有限公司"}],"company_since":"1998-01-09","company_dissolved":"2005-11-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"634363","names":[{"lang":"en","v":"ORIENT CERAMIC INTERNATIONAL COMPANY LIMITED"}],"company_since":"1998-01-09","company_dissolved":"2013-06-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"634380","names":[{"lang":"en","v":"ORION INTEGRATED INFORMATION SYSTEM CO., LIMITED"},{"lang":"hk","v":"亞利安集成信息系統有限公司"}],"company_since":"1998-01-09","company_dissolved":"2007-05-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"634393","names":[{"lang":"en","v":"ORKNEY ENVIRONMENTAL TECHNOLOGY LIMITED"},{"lang":"hk","v":"奧科納爾環保科技有限公司"}],"company_since":"1998-01-09","company_dissolved":"2015-04-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"634392","names":[{"lang":"en","v":"LUK KA DEVELOPMENT LIMITED"},{"lang":"hk","v":"力嘉發展有限公司"}],"company_since":"1998-01-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"634274","names":[{"lang":"en","v":"PARTS CENTRAL (AUTOMOBILE) GLOBAL LIMITED"},{"lang":"hk","v":"百勝滙自動車零配件有限公司"}],"company_since":"1998-01-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"634281","names":[{"lang":"en","v":"KARREX HOLDINGS LIMITED"},{"lang":"hk","v":"加益集團有限公司"}],"company_since":"1998-01-09","company_dissolved":"2000-10-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"634305","names":[{"lang":"en","v":"PECKEN LIMITED"},{"lang":"hk","v":"柏恆有限公司"}],"company_since":"1998-01-09","company_dissolved":"2018-12-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"634325","names":[{"lang":"en","v":"PHOENIX (HONG KONG) LIMITED"},{"lang":"hk","v":"鳳凰(香港)有限公司"}],"company_since":"1998-01-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"634301","names":[{"lang":"en","v":"KITCO DEVELOPMENT LIMITED"},{"lang":"hk","v":"傑浩發展有限公司"}],"company_since":"1998-01-09","company_dissolved":"2002-09-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"634331","names":[{"lang":"en","v":"POWER OCEAN ENGINEERING LIMITED (d2003-10-24)"},{"lang":"hk","v":"力洋工程有限公司"}],"company_since":"1998-01-09","company_dissolved":"2003-10-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"634406","names":[{"lang":"en","v":"PRO WINE &amp; SPIRITS LIMITED"},{"lang":"hk","v":"敬業酒莊有限公司"}],"company_since":"1998-01-09","company_dissolved":"2005-01-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"634269","names":[{"lang":"en","v":"R &amp; T CONSULTANTS LIMITED"}],"company_since":"1998-01-09","company_dissolved":"2004-09-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"634344","names":[{"lang":"en","v":"PACIFIC CAPITAL GROUP LIMITED (d2004-01-21)"}],"company_since":"1998-01-09","company_dissolved":"2004-01-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"634308","names":[{"lang":"en","v":"KOSHING INVESTMENT LIMITED"},{"lang":"hk","v":"高成投資有限公司"}],"company_since":"1998-01-09","company_dissolved":"2005-01-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"634334","names":[{"lang":"en","v":"LAERIC (H.K.) LIMITED"}],"company_since":"1998-01-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"634375","names":[{"lang":"en","v":"SDI ASIA PACIFIC LIMITED"}],"company_since":"1998-01-09","company_dissolved":"2002-07-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"634320","names":[{"lang":"en","v":"SEE SUN LABEL &amp; ADV. CO. LIMITED"},{"lang":"hk","v":"時新商標廣告有限公司"}],"company_since":"1998-01-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"634267","names":[{"lang":"en","v":"SHEEN TECHNOLOGY ENTERPRISES COMPANY LIMITED"},{"lang":"hk","v":"興順科技企業有限公司"}],"company_since":"1998-01-09","company_dissolved":"2006-05-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"634278","names":[{"lang":"en","v":"SILVER RICH (HONG KONG) LIMITED"},{"lang":"hk","v":"兆富(香港)有限公司"}],"company_since":"1998-01-09","company_dissolved":"2000-12-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"634283","names":[{"lang":"en","v":"STANDARD ASIA INTERNATIONAL LIMITED"},{"lang":"hk","v":"達亞國際有限公司"}],"company_since":"1998-01-09","company_dissolved":"2005-01-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"634297","names":[{"lang":"en","v":"LANDSON INTERNATIONAL LIMITED (d2007-06-29)"},{"lang":"hk","v":"立信國際有限公司"}],"company_since":"1998-01-09","company_dissolved":"2007-06-29","company_type_txt":"Private, ltd by shares"},
{"tax_id":"634357","names":[{"lang":"en","v":"SUN NGAI MANUFACTORY LIMITED"},{"lang":"hk","v":"新毅製品廠有限公司"}],"company_since":"1998-01-09","company_dissolved":"2018-04-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"634374","names":[{"lang":"en","v":"SUNNET CULTURE DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"尚南文化事業發展有限公司"}],"company_since":"1998-01-09","company_dissolved":"2011-09-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"634372","names":[{"lang":"en","v":"LEADING WORLD LIMITED (d2017-09-22)"},{"lang":"hk","v":"冠樺有限公司"}],"company_since":"1998-01-09","company_dissolved":"2017-09-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"634318","names":[{"lang":"en","v":"LEGEND PRC LIMITED"},{"lang":"hk","v":"理程港中有限公司"}],"company_since":"1998-01-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"634377","names":[{"lang":"en","v":"TING KOK ROAD PROPERTY DEVELOPMENT CO. LIMITED"},{"lang":"hk","v":"汀角路地產發展有限公司"}],"company_since":"1998-01-09","company_dissolved":"2011-04-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"634402","names":[{"lang":"en","v":"TOP GREAT INDUSTRIES LIMITED"},{"lang":"hk","v":"統大實業有限公司"}],"company_since":"1998-01-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"634292","names":[{"lang":"en","v":"TRADESMART LIMITED (d2003-08-29)"},{"lang":"hk","v":"貿駿有限公司"}],"company_since":"1998-01-09","company_dissolved":"2003-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"634368","names":[{"lang":"en","v":"LOTUS INTERNATIONAL HOLDING LIMITED (d2008-05-23)"},{"lang":"hk","v":"駿達國際集團有限公司"}],"company_since":"1998-01-09","company_dissolved":"2008-05-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"634391","names":[{"lang":"en","v":"LOTUS OFFICE SUPPLIES LIMITED"},{"lang":"hk","v":"駿達洋行有限公司"}],"company_since":"1998-01-09","company_dissolved":"2005-08-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"634404","names":[{"lang":"en","v":"WAN FANG SHIPPING ENTERPRISE CO. LIMITED"},{"lang":"hk","v":"萬方船務企業有限公司"}],"company_since":"1998-01-09","company_dissolved":"2012-08-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"634389","names":[{"lang":"en","v":"WARPSPEED LIMITED (d2005-12-02)"},{"lang":"hk","v":"和訊電腦有限公司"}],"company_since":"1998-01-09","company_dissolved":"2005-12-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"634355","names":[{"lang":"en","v":"MAJESTIC GROUP LIMITED (HK)"},{"lang":"hk","v":"萬致達集團有限公司"}],"company_since":"1998-01-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"634317","names":[{"lang":"en","v":"WUI SHING INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"匯誠國際發展有限公司"}],"company_since":"1998-01-09","company_dissolved":"2018-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"634314","names":[{"lang":"en","v":"WELLSTAR GROUP COMPANY LIMITED"},{"lang":"hk","v":"華星組合有限公司"}],"company_since":"1998-01-09","company_dissolved":"2009-01-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"634335","names":[{"lang":"en","v":"YIN ZHONG INTERNATIONAL LIMITED"},{"lang":"hk","v":"銀眾國際有限公司"}],"company_since":"1998-01-09","company_dissolved":"2006-05-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"634328","names":[{"lang":"en","v":"YIU KIN CRANE LORRIES TRANSPORTATION LIMITED"},{"lang":"hk","v":"耀堅吊車運輸有限公司"}],"company_since":"1998-01-09","company_dissolved":"2006-05-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"634273","names":[{"lang":"en","v":"MARKHAM ASSOCIATES LIMITED (d2002-08-23)"},{"lang":"hk","v":"萬克有限公司"}],"company_since":"1998-01-09","company_dissolved":"2002-08-23","company_type_txt":"Private, ltd by shares"},
{"tax_id":"634411","names":[{"lang":"en","v":"ZHONG HONG (OVERSEAS) HOLDINGS LIMITED"},{"lang":"hk","v":"中宏(海外)控股有限公司"}],"company_since":"1998-01-09","company_dissolved":"2002-06-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"634337","names":[{"lang":"en","v":"YUK MING COMPANY LIMITED (d2010-04-09)"},{"lang":"hk","v":"旭明有限公司"}],"company_since":"1998-01-09","company_dissolved":"2010-04-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"634365","names":[{"lang":"en","v":"PALKE INDUSTRIAL LIMITED"},{"lang":"hk","v":"普奇實業有限公司"}],"company_since":"1998-01-09","company_dissolved":"2015-10-02","company_type_txt":"Private, ltd by shares"},
{"tax_id":"634323","names":[{"lang":"en","v":"PARKWIN HOTEL MANAGEMENT COMPANY LIMITED"},{"lang":"hk","v":"百榮酒店管理有限公司"}],"company_since":"1998-01-09","company_dissolved":"2017-02-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"634313","names":[{"lang":"en","v":"P &amp; D (HONG KONG) LIMITED"}],"company_since":"1998-01-09","company_dissolved":"2007-05-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"634306","names":[{"lang":"en","v":"PO WING KNITTING FACTORY LIMITED"},{"lang":"hk","v":"寶榮織造廠有限公司"}],"company_since":"1998-01-09","company_dissolved":"2013-03-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"634288","names":[{"lang":"en","v":"RICO INVESTMENT LIMITED (d2005-01-21)"},{"lang":"hk","v":"益高投資有限公司"}],"company_since":"1998-01-09","company_dissolved":"2005-01-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"634361","names":[{"lang":"en","v":"SUN ZONE INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"三正國際投資有限公司"}],"company_since":"1998-01-09","company_dissolved":"2001-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"634354","names":[{"lang":"en","v":"SUNWISE ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"鴻鍵工程有限公司"}],"company_since":"1998-01-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"634353","names":[{"lang":"en","v":"SUPER BEST STATE PLASTIC PRODUCTS FACTORY LIMITED"},{"lang":"hk","v":"旭州股份有限公司"}],"company_since":"1998-01-09","company_dissolved":"2007-05-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"634303","names":[{"lang":"en","v":"TECHNOWORKS LIMITED"},{"lang":"hk","v":"科訊威有限公司"}],"company_since":"1998-01-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"634367","names":[{"lang":"en","v":"UNICOPE THERMAL PRODUCTS LIMITED"},{"lang":"hk","v":"聯達冷凝製品有限公司"}],"company_since":"1998-01-09","company_dissolved":"2015-08-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"634329","names":[{"lang":"en","v":"WELL HONEST (HONG KONG) LIMITED (d2005-01-14)"},{"lang":"hk","v":"威誠(香港)有限公司"}],"company_since":"1998-01-09","company_dissolved":"2005-01-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"634347","names":[{"lang":"en","v":"WISE BABY (HONG KONG) MEDICAL CO., LIMITED"},{"lang":"hk","v":"惠寶(香港)醫療有限公司"}],"company_since":"1998-01-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"634378","names":[{"lang":"en","v":"YOUR SHOW TECHNOLOGY LIMITED"},{"lang":"hk","v":"友秀科技有限公司"}],"company_since":"1998-01-09","company_dissolved":"2010-09-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"634349","names":[{"lang":"en","v":"ONE.TEL LIMITED"},{"lang":"hk","v":"一電通電話有限公司"}],"company_since":"1998-01-09","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
