{"tax_id":"531297","names":[{"lang":"en","v":"COMFULL SHOES MFG CO., LIMITED"},{"lang":"hk","v":"金豐盛鞋業有限公司"}],"company_since":"1995-11-21","company_dissolved":"2001-02-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531230","names":[{"lang":"en","v":"COMMLINK TECHNOLOGY LIMITED"},{"lang":"hk","v":"通聯科技有限公司"}],"company_since":"1995-11-21","company_dissolved":"2010-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531188","names":[{"lang":"en","v":"CONFUCIAN CULTURE PUBLISHING COMPANY LIMITED"},{"lang":"hk","v":"孔子文化出版有限公司"}],"company_since":"1995-11-21","company_dissolved":"2008-05-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531109","names":[{"lang":"en","v":"CONTINENTAL LAND LIMITED (d2009-04-09)"},{"lang":"hk","v":"立洲有限公司"}],"company_since":"1995-11-21","company_dissolved":"2009-04-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531143","names":[{"lang":"en","v":"COUNTRY TOP PROPERTIES LIMITED"},{"lang":"hk","v":"港達置業有限公司"}],"company_since":"1995-11-21","company_dissolved":"2009-05-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531223","names":[{"lang":"en","v":"CROWN SOURCE ENTERPRISES LIMITED"},{"lang":"hk","v":"冠源企業有限公司"}],"company_since":"1995-11-21","company_dissolved":"2008-04-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531182","names":[{"lang":"en","v":"DATA PROCESSING SERVICES LIMITED"},{"lang":"hk","v":"資料服務有限公司"}],"company_since":"1995-11-21","company_dissolved":"2019-07-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531357","names":[{"lang":"en","v":"DOLOVEC (HONG KONG) LIMITED"},{"lang":"hk","v":"德保健(香港)有限公司"}],"company_since":"1995-11-21","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531183","names":[{"lang":"en","v":"Draco Digital Limited (d2012-05-04)"},{"lang":"hk","v":"天龍數碼有限公司"}],"company_since":"1995-11-21","company_dissolved":"2012-05-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531318","names":[{"lang":"en","v":"EAGLE ENGINEERING (CHINA) LIMITED"},{"lang":"hk","v":"藝高建設(中國)有限公司"}],"company_since":"1995-11-21","company_dissolved":"2003-05-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531052","names":[{"lang":"en","v":"EL GRANDE (QUARRY BAY) CO. LIMITED"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531112","names":[{"lang":"en","v":"ENCO DEVELOPMENT LIMITED"},{"lang":"hk","v":"雅浩發展有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531111","names":[{"lang":"en","v":"ENCO INVESTMENT LIMITED"},{"lang":"hk","v":"雅浩投資有限公司"}],"company_since":"1995-11-21","company_dissolved":"2003-07-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531337","names":[{"lang":"en","v":"EVER BRIGHT CONTAINER TRANSPORT LIMITED"},{"lang":"hk","v":"恒暉貨櫃運輸有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531167","names":[{"lang":"en","v":"EVER OCEAN INTERNATIONAL LIMITED (d2000-06-09)"},{"lang":"hk","v":"恆海國際有限公司"}],"company_since":"1995-11-21","company_dissolved":"2000-06-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531164","names":[{"lang":"en","v":"EXCEL GLORY CONSTRUCTIONS LIMITED"},{"lang":"hk","v":"其信工程有限公司"}],"company_since":"1995-11-21","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531342","names":[{"lang":"en","v":"FAR EAST CERAMATE SERVICES LIMITED (THE)"}],"company_since":"1995-11-21","company_dissolved":"1998-12-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531142","names":[{"lang":"en","v":"FIRST INFINITY CERAMICS MANUFACTURING COMPANY LIMITED"},{"lang":"hk","v":"安山陶瓷製作有限公司"}],"company_since":"1995-11-21","company_dissolved":"2020-01-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531252","names":[{"lang":"en","v":"FORCE ONE INVESTMENTS LIMITED"},{"lang":"hk","v":"力一投資有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531136","names":[{"lang":"en","v":"FOREVER EQUIPMENT SUPPLIES &amp; SERVICES LIMITED"},{"lang":"hk","v":"富恒設備供應及服務有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531289","names":[{"lang":"en","v":"FORTUNE SEA INTERNATIONAL LIMITED (d2004-03-26)"},{"lang":"hk","v":"寶思國際有限公司"}],"company_since":"1995-11-21","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531179","names":[{"lang":"en","v":"FUJI AUTOMATIC EQUIPMENT (HONG KONG) LIMITED"},{"lang":"hk","v":"富士自動化設備(香港)有限公司"}],"company_since":"1995-11-21","company_dissolved":"2001-04-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531294","names":[{"lang":"en","v":"FULLTEC DEVELOPMENT LIMITED"},{"lang":"hk","v":"富利得發展有限公司"}],"company_since":"1995-11-21","company_dissolved":"2008-04-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531255","names":[{"lang":"en","v":"FUNG TAK LAU SEAFOOD RESTAURANT (KWAI CHUNG) LIMITED"},{"lang":"hk","v":"鳳德樓海鮮酒家(葵涌)有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531296","names":[{"lang":"en","v":"FURICA LIMITED"},{"lang":"hk","v":"富利嘉有限公司"}],"company_since":"1995-11-21","company_dissolved":"2014-05-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531137","names":[{"lang":"en","v":"GAMMON CHINA LIMITED"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531243","names":[{"lang":"en","v":"GAREK ENTERPRISE COMPANY LIMITED"},{"lang":"hk","v":"佳麗企業有限公司"}],"company_since":"1995-11-21","company_dissolved":"1999-04-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531280","names":[{"lang":"en","v":"GENUINE GLORY INTERNATIONAL LIMITED"},{"lang":"hk","v":"嘉揚國際有限公司"}],"company_since":"1995-11-21","company_dissolved":"2002-04-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531161","names":[{"lang":"en","v":"GIBSON HONG KONG LIMITED"}],"company_since":"1995-11-21","company_dissolved":"2007-12-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531066","names":[{"lang":"en","v":"GLOBAL LINK GROUP OF COMPANY LIMITED"},{"lang":"hk","v":"精萃集團有限公司"}],"company_since":"1995-11-21","company_dissolved":"2006-10-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531077","names":[{"lang":"en","v":"GLORY FRIENDSHIP LIMITED"},{"lang":"hk","v":"浩誼有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531162","names":[{"lang":"en","v":"CO-PROFIT FOOTWEAR MANUFACTURING LIMITED"},{"lang":"hk","v":"盟裕鞋業製造有限公司"}],"company_since":"1995-11-21","company_dissolved":"2010-05-07","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531151","names":[{"lang":"en","v":"GOLDEN POST LIMITED"},{"lang":"hk","v":"金寶時有限公司"}],"company_since":"1995-11-21","company_dissolved":"2004-08-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531044","names":[{"lang":"en","v":"COMMASIA HOLDINGS LIMITED"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531133","names":[{"lang":"en","v":"GOLDEN SPARK TRADING LIMITED"},{"lang":"hk","v":"金運通貿易有限公司"}],"company_since":"1995-11-21","company_dissolved":"2000-10-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531075","names":[{"lang":"en","v":"GOLDEN TROPHY HOLDINGS LIMITED"},{"lang":"hk","v":"顯聰控股有限公司"}],"company_since":"1995-11-21","company_dissolved":"2009-09-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531367","names":[{"lang":"en","v":"COPROMETRO INDUSTRY LIMITED"},{"lang":"hk","v":"日域工業有限公司"}],"company_since":"1995-11-21","company_dissolved":"2005-11-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531286","names":[{"lang":"en","v":"GOLDFLOW INTERNATIONAL LIMITED"},{"lang":"hk","v":"金富運國際有限公司"}],"company_since":"1995-11-21","company_dissolved":"2000-10-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531194","names":[{"lang":"en","v":"GOLDYEAR INDUSTRIAL LIMITED"},{"lang":"hk","v":"金運年實業有限公司"}],"company_since":"1995-11-21","company_dissolved":"2020-01-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531065","names":[{"lang":"en","v":"GOODABLE INTERNATIONAL LIMITED"},{"lang":"hk","v":"亮利國際有限公司"}],"company_since":"1995-11-21","company_dissolved":"2002-07-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531153","names":[{"lang":"en","v":"GRACEFUL HOME MERCHANDISE COMPANY LIMITED"},{"lang":"hk","v":"嘉豐行有限公司"}],"company_since":"1995-11-21","company_dissolved":"2019-03-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531070","names":[{"lang":"en","v":"DEJA HONG KONG LIMITED"},{"lang":"hk","v":"戴捷香港有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531149","names":[{"lang":"en","v":"GOLDEN SPARK ENTERPRISES LIMITED"},{"lang":"hk","v":"金運通企業有限公司"}],"company_since":"1995-11-21","company_dissolved":"2000-10-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531171","names":[{"lang":"en","v":"GRAND CORN DEVELOPMENTS LIMITED"},{"lang":"hk","v":"其康發展有限公司"}],"company_since":"1995-11-21","company_dissolved":"1998-11-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531224","names":[{"lang":"en","v":"DYNAMIC CRANE ENTERPRISES LIMITED"},{"lang":"hk","v":"泰揚企業有限公司"}],"company_since":"1995-11-21","company_dissolved":"2002-04-26","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531310","names":[{"lang":"en","v":"GRAND SONIC INTERNATIONAL LIMITED"},{"lang":"hk","v":"譽昌國際有限公司"}],"company_since":"1995-11-21","company_dissolved":"2001-01-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531253","names":[{"lang":"en","v":"GRANDLY TRADING LIMITED"},{"lang":"hk","v":"祥基貿易有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531348","names":[{"lang":"en","v":"GRIFFITHS &amp; CO., (HK) LIMITED"},{"lang":"hk","v":"達理恩移民教育法律顧問有限公司"}],"company_since":"1995-11-21","company_dissolved":"2005-03-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531336","names":[{"lang":"en","v":"GUI HONG STAINLESS STEEL PRECISION CASTING COMPANY LIMITED"},{"lang":"hk","v":"桂鴻不銹鋼精密鑄造有限公司"}],"company_since":"1995-11-21","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531147","names":[{"lang":"en","v":"EVERLITE (CHINA) SHIPPING LIMITED"},{"lang":"hk","v":"恒暉(中國)航運有限公司"}],"company_since":"1995-11-21","company_dissolved":"2005-11-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531209","names":[{"lang":"en","v":"H.K.R.T. COMPANY LIMITED"},{"lang":"hk","v":"香港RT大基有限公司"}],"company_since":"1995-11-21","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531198","names":[{"lang":"en","v":"H.F.I.T.D.C. (HONG KONG) LIMITED"},{"lang":"hk","v":"湖南省招商對外貿易發展(香港)有限公司"}],"company_since":"1995-11-21","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531168","names":[{"lang":"en","v":"HARVESON INTERNATIONAL LIMITED"},{"lang":"hk","v":"興民國際有限公司"}],"company_since":"1995-11-21","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531219","names":[{"lang":"en","v":"HONEST C COMPANY LIMITED"},{"lang":"hk","v":"賀爾賀斯有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531239","names":[{"lang":"en","v":"FIRST PACIFIC DAVIES (GUANGZHOU) LIMITED"}],"company_since":"1995-11-21","company_dissolved":"2001-03-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531148","names":[{"lang":"en","v":"FOREIGN ALLIANCE INDUSTRY DEVELOPMENT (HK) CO. LIMITED"},{"lang":"hk","v":"海外聯誼實業(香港)投資有限公司"}],"company_since":"1995-11-21","company_dissolved":"2001-09-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531119","names":[{"lang":"en","v":"HONEST DRAGON TRADING LIMITED"},{"lang":"hk","v":"誠龍貿易有限公司"}],"company_since":"1995-11-21","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531355","names":[{"lang":"en","v":"HONG KONG DONG CHANG (GROUP) LIMITED (d2003-04-25)"},{"lang":"hk","v":"香港東昌(集團)有限公司"}],"company_since":"1995-11-21","company_dissolved":"2003-04-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"531074","names":[{"lang":"en","v":"HONGYU ENTERPRISE GROUP (HK) LIMITED"},{"lang":"hk","v":"宏宇企業集團(香港)有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531054","names":[{"lang":"en","v":"HOWAN DESIGN ENGINEERING LIMITED (d2012-05-25)"},{"lang":"hk","v":"創基設計工程有限公司"}],"company_since":"1995-11-21","company_dissolved":"2012-05-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531233","names":[{"lang":"en","v":"HYFA BUSINESS LOGISTICS LIMITED"},{"lang":"hk","v":"英發商業物流有限公司"}],"company_since":"1995-11-21","company_dissolved":"2007-07-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531184","names":[{"lang":"en","v":"HYPERNET INTERNATIONAL (HONG KONG) LIMITED"},{"lang":"hk","v":"百富利國際(香港)有限公司"}],"company_since":"1995-11-21","company_dissolved":"2011-12-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531063","names":[{"lang":"en","v":"GENERAL STRONG LIMITED"},{"lang":"hk","v":"通昌有限公司"}],"company_since":"1995-11-21","company_dissolved":"2001-03-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531176","names":[{"lang":"en","v":"IN 2 ASIA SERVICES LIMITED"}],"company_since":"1995-11-21","company_dissolved":"2004-04-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531258","names":[{"lang":"en","v":"INFOWORLD LIMITED (d2006-04-13)"},{"lang":"hk","v":"研偉有限公司"}],"company_since":"1995-11-21","company_dissolved":"2006-04-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531090","names":[{"lang":"en","v":"GLORY ELEGANCE LIMITED (d1999-01-22)"},{"lang":"hk","v":"浩藝有限公司"}],"company_since":"1995-11-21","company_dissolved":"1999-01-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531085","names":[{"lang":"en","v":"JARDINE M&amp;E CONTRACTING (CHINA) LIMITED"},{"lang":"hk","v":"怡和工程(中國)有限公司"}],"company_since":"1995-11-21","company_dissolved":"2011-02-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531313","names":[{"lang":"en","v":"GOLDEN H.K. ELECTRONICS LIMITED"}],"company_since":"1995-11-21","company_dissolved":"2000-05-25","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531046","names":[{"lang":"en","v":"JARDINE M&amp;E CONTRACTING LIMITED"},{"lang":"hk","v":"怡和工程有限公司"}],"company_since":"1995-11-21","company_dissolved":"2011-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531089","names":[{"lang":"en","v":"JOHNWAY INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"莊盛國際有限公司"}],"company_since":"1995-11-21","company_dissolved":"2016-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531265","names":[{"lang":"en","v":"JUMBO BEVERAGE LIMITED"},{"lang":"hk","v":"珍寶飲品有限公司"}],"company_since":"1995-11-21","company_dissolved":"2004-08-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531248","names":[{"lang":"en","v":"KA MENG (FAR EAST) LIMITED"},{"lang":"hk","v":"嘉明(遠東)有限公司"}],"company_since":"1995-11-21","company_dissolved":"2001-04-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531193","names":[{"lang":"en","v":"KANO RUBBER (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"加納橡膠(香港)有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531256","names":[{"lang":"en","v":"GRAND &amp; GRAND LIMITED"},{"lang":"hk","v":"祥弘有限公司"}],"company_since":"1995-11-21","company_dissolved":"2006-04-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531128","names":[{"lang":"en","v":"KARMAX ASIA LIMITED"},{"lang":"hk","v":"嘉美亞洲有限公司"}],"company_since":"1995-11-21","company_dissolved":"2008-12-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531317","names":[{"lang":"en","v":"KEEN WISE INTERNATIONAL HOLDINGS LIMITED"}],"company_since":"1995-11-21","company_dissolved":"2001-10-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531220","names":[{"lang":"en","v":"KEY ACCESS LIMITED (d2004-08-13)"},{"lang":"hk","v":"啓晉有限公司"}],"company_since":"1995-11-21","company_dissolved":"2004-08-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531174","names":[{"lang":"en","v":"KIA MOTORS (HONG KONG) LIMITED"},{"lang":"hk","v":"起亞汽車(香港)有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531282","names":[{"lang":"en","v":"GRAND SONIC LIMITED (d2004-08-13)"},{"lang":"hk","v":"宏昇電子有限公司"}],"company_since":"1995-11-21","company_dissolved":"2004-08-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531264","names":[{"lang":"en","v":"KIN WAH TRANSPORTATION COMPANY LIMITED"},{"lang":"hk","v":"建華旅運有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531257","names":[{"lang":"en","v":"GRANDICK LIMITED"},{"lang":"hk","v":"祥得有限公司"}],"company_since":"1995-11-21","company_dissolved":"2002-03-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531180","names":[{"lang":"en","v":"KINGDOM CONSULTANT SERVICES LIMITED"}],"company_since":"1995-11-21","company_dissolved":"1999-07-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531129","names":[{"lang":"en","v":"GRANVILLE CONTRACTORS LIMITED"},{"lang":"hk","v":"均輝承造有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531156","names":[{"lang":"en","v":"KINGSBERG MACHINERY LIMITED"},{"lang":"hk","v":"勁寶機械有限公司"}],"company_since":"1995-11-21","company_dissolved":"2002-08-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"531203","names":[{"lang":"en","v":"GREATEST PRODUCTIONS LIMITED"},{"lang":"hk","v":"基隆實業有限公司"}],"company_since":"1995-11-21","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531225","names":[{"lang":"en","v":"LESTON ENTERPRISES LIMITED"},{"lang":"hk","v":"勵登企業有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531059","names":[{"lang":"en","v":"HALLISON LIMITED"},{"lang":"hk","v":"浩聲有限公司"}],"company_since":"1995-11-21","company_dissolved":"2007-05-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531363","names":[{"lang":"en","v":"LEUNG CHI MACHINE TRADING LIMITED"},{"lang":"hk","v":"良智機器貿易有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531045","names":[{"lang":"en","v":"HEEPSON MARBLE (H.K.) CO., LIMITED"},{"lang":"hk","v":"軒信雲石(香港)有限公司"}],"company_since":"1995-11-21","company_dissolved":"2004-11-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531141","names":[{"lang":"en","v":"LUCKY SENIOR DEVELOPMENT LIMITED"},{"lang":"hk","v":"福隆發展有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531118","names":[{"lang":"en","v":"HONEST DRAGON INTERNATIONAL LIMITED"},{"lang":"hk","v":"誠龍國際有限公司"}],"company_since":"1995-11-21","company_dissolved":"2002-05-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531076","names":[{"lang":"en","v":"M.B.I. TRADING LIMITED"},{"lang":"hk","v":"萬寶來貿易有限公司"}],"company_since":"1995-11-21","company_dissolved":"2005-11-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531214","names":[{"lang":"en","v":"MAN WING (HONG KONG) LIMITED"},{"lang":"hk","v":"文榮(香港)有限公司"}],"company_since":"1995-11-21","company_dissolved":"1998-12-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531115","names":[{"lang":"en","v":"MAX CONCORD LIMITED (d2000-09-15)"},{"lang":"hk","v":"明欣有限公司"}],"company_since":"1995-11-21","company_dissolved":"2000-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531285","names":[{"lang":"en","v":"HONG KONG SEWING MACHINE ASSOCIATION LIMITED"},{"lang":"hk","v":"香港針車業商會有限公司"}],"company_since":"1995-11-21","company_dissolved":"2020-04-13","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"531325","names":[{"lang":"en","v":"HONG KONG TAI SAM TOBACCO INDUSTRY COMPANY LIMITED"},{"lang":"hk","v":"香港大生煙草業有限公司"}],"company_since":"1995-11-21","company_dissolved":"2004-08-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531139","names":[{"lang":"en","v":"MIGHTY HORSE INTERNATIONAL ENTERPRISE (H.K.) LIMITED"},{"lang":"hk","v":"豪駿國際企業(香港)有限公司"}],"company_since":"1995-11-21","company_dissolved":"2003-10-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"531073","names":[{"lang":"en","v":"MINGYU WOOD MANUFACTURES (HK) LIMITED"},{"lang":"hk","v":"明宇木業(香港)有限公司"}],"company_since":"1995-11-21","company_dissolved":"1999-05-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531334","names":[{"lang":"en","v":"MINTEL (H.K.) LIMITED"}],"company_since":"1995-11-21","company_dissolved":"2014-10-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531227","names":[{"lang":"en","v":"MULTIFIT ENTERPRISES LIMITED"},{"lang":"hk","v":"廣勝企業有限公司"}],"company_since":"1995-11-21","company_dissolved":"2004-05-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531163","names":[{"lang":"en","v":"HONIC CONSTRUCTIONS LIMITED"},{"lang":"hk","v":"鴻力工程有限公司"}],"company_since":"1995-11-21","company_dissolved":"2007-02-02","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531311","names":[{"lang":"en","v":"N W LEE MEDICAL PRACTICE LIMITED"}],"company_since":"1995-11-21","company_dissolved":"2002-04-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531335","names":[{"lang":"en","v":"IMAGETEK INTERNATIONAL LIMITED"},{"lang":"hk","v":"影捷科技國際有限公司"}],"company_since":"1995-11-21","company_dissolved":"2015-10-02","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531234","names":[{"lang":"en","v":"NATIONMARK SERVICE CENTRE LIMITED"},{"lang":"hk","v":"邦迅維修中心有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531300","names":[{"lang":"en","v":"LEE TAK PO GARMENT MANUFACTURING COMPANY LIMITED"},{"lang":"hk","v":"利德寶製衣有限公司"}],"company_since":"1995-11-21","company_dissolved":"2001-05-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531105","names":[{"lang":"en","v":"INFOSONICS INDUSTRIAL (HK) LIMITED"}],"company_since":"1995-11-21","company_dissolved":"2004-08-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531245","names":[{"lang":"en","v":"NEW HONEST LIMITED (d2001-05-18)"},{"lang":"hk","v":"新鴻興有限公司"}],"company_since":"1995-11-21","company_dissolved":"2001-05-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531303","names":[{"lang":"en","v":"NEW KOREA COMPANY LIMITED"},{"lang":"hk","v":"新韓貿易有限公司"}],"company_since":"1995-11-21","company_dissolved":"2006-04-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531229","names":[{"lang":"en","v":"NEW MODERN TECHNOLOGY LIMITED"},{"lang":"hk","v":"優摩登有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531202","names":[{"lang":"en","v":"JOWLE (HK) TECHNOLOGY COMPANY LIMITED"},{"lang":"hk","v":"加煒(香港)有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531277","names":[{"lang":"en","v":"NEW VENTURE INDUSTRIAL LIMITED (d2004-03-26)"},{"lang":"hk","v":"浩新實業有限公司"}],"company_since":"1995-11-21","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531068","names":[{"lang":"en","v":"NEW CITY LASER &amp; VIDEO COMPANY LIMITED"},{"lang":"hk","v":"新城鐳射錄影有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"531191","names":[{"lang":"en","v":"KA HING MOTORS COMPANY LIMITED"},{"lang":"hk","v":"嘉興汽車有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531246","names":[{"lang":"en","v":"KAISER LION INTERNATIONAL (HK) LIMITED"},{"lang":"hk","v":"嘉麟國際(香港)有限公司"}],"company_since":"1995-11-21","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531298","names":[{"lang":"en","v":"PACIFIC LONG INTERNATIONAL LIMITED"},{"lang":"hk","v":"思朗國際有限公司"}],"company_since":"1995-11-21","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531145","names":[{"lang":"en","v":"PACIFIC THEME INTERNATIONAL LIMITED"},{"lang":"hk","v":"達思國際有限公司"}],"company_since":"1995-11-21","company_dissolved":"2018-05-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531241","names":[{"lang":"en","v":"PACIFIC THEME LIMITED"},{"lang":"hk","v":"朗思有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531331","names":[{"lang":"en","v":"PAN WIN REALTY (COMMERCIAL) LIMITED"},{"lang":"hk","v":"栢聯地產(商業)有限公司"}],"company_since":"1995-11-21","company_dissolved":"2002-11-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531099","names":[{"lang":"en","v":"PARAFUL (INTERNATIONAL) COMPANY LIMITED"},{"lang":"hk","v":"廣記(國際)有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531361","names":[{"lang":"en","v":"PAUL MAITLAND LIMITED (d2004-03-26)"}],"company_since":"1995-11-21","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531307","names":[{"lang":"en","v":"PEMAL INDUSTRIAL MACHINE COMPANY LIMITED"},{"lang":"hk","v":"良機工業有限公司"}],"company_since":"1995-11-21","company_dissolved":"2020-10-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531132","names":[{"lang":"en","v":"KONG SHUN LOGISTICS LIMITED"},{"lang":"hk","v":"港順物流有限公司"}],"company_since":"1995-11-21","company_dissolved":"2004-05-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531279","names":[{"lang":"en","v":"PERFECT RELIANCE DEVELOPMENT LIMITED"},{"lang":"hk","v":"健匯發展有限公司"}],"company_since":"1995-11-21","company_dissolved":"2004-08-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531131","names":[{"lang":"en","v":"KWONG WAH METAL AND PLASTIC MANUFACTORY LIMITED"},{"lang":"hk","v":"光華五金塑膠製品廠有限公司"}],"company_since":"1995-11-21","company_dissolved":"2004-04-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531080","names":[{"lang":"en","v":"PIERO GUIDI (HONG KONG) LIMITED"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531047","names":[{"lang":"en","v":"LAGON LIMITED (d2003-06-20)"},{"lang":"hk","v":"朗樂有限公司"}],"company_since":"1995-11-21","company_dissolved":"2003-06-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531079","names":[{"lang":"en","v":"PLOYWIN INVESTMENTS COMPANY LIMITED"},{"lang":"hk","v":"多威利投資有限公司"}],"company_since":"1995-11-21","company_dissolved":"2006-06-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531260","names":[{"lang":"en","v":"PO YEUNG COMPANY LIMITED"},{"lang":"hk","v":"寶揚製衣有限公司"}],"company_since":"1995-11-21","company_dissolved":"2000-05-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531293","names":[{"lang":"en","v":"POLIGOOD INVESTMENT LIMITED"},{"lang":"hk","v":"百利佳投資有限公司"}],"company_since":"1995-11-21","company_dissolved":"2008-07-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531095","names":[{"lang":"en","v":"LINK GREAT LIMITED (d2003-04-11)"},{"lang":"hk","v":"上聯有限公司"}],"company_since":"1995-11-21","company_dissolved":"2003-04-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531269","names":[{"lang":"en","v":"POLYTEAM ENTERPRISES LIMITED"},{"lang":"hk","v":"百利添企業有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"531104","names":[{"lang":"en","v":"LUCKY SENIOR HOLDINGS LIMITED"},{"lang":"hk","v":"福隆集團有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531259","names":[{"lang":"en","v":"PROSPER PALACE LIMITED"},{"lang":"hk","v":"盛緯有限公司"}],"company_since":"1995-11-21","company_dissolved":"2007-07-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531211","names":[{"lang":"en","v":"PROSPER PETRONUM (HONG KONG) LIMITED"}],"company_since":"1995-11-21","company_dissolved":"2003-03-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531323","names":[{"lang":"en","v":"PROWIDE COMPANY LIMITED"},{"lang":"hk","v":"寶驊有限公司"}],"company_since":"1995-11-21","company_dissolved":"2003-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531072","names":[{"lang":"en","v":"R CHENG PROPERTY CONSULTANTS LIMITED"},{"lang":"hk","v":"鄭偉文測量師行有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531114","names":[{"lang":"en","v":"RENICO LIMITED (d1998-07-03)"}],"company_since":"1995-11-21","company_dissolved":"1998-07-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531343","names":[{"lang":"en","v":"MIKO-KINGS INSTRUMENTS LIMITED"},{"lang":"hk","v":"力高儀器有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531196","names":[{"lang":"en","v":"RICHABLE LIMITED (d1998-12-18)"},{"lang":"hk","v":"富裕寶有限公司"}],"company_since":"1995-11-21","company_dissolved":"1998-12-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531292","names":[{"lang":"en","v":"RICHGAIN INTERNATIONAL LIMITED"},{"lang":"hk","v":"富利盈國際有限公司"}],"company_since":"1995-11-21","company_dissolved":"2006-04-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"531362","names":[{"lang":"en","v":"ORIENTAL SUNRISE REAL ESTATE LIMITED"},{"lang":"hk","v":"東日置業有限公司"}],"company_since":"1995-11-21","company_dissolved":"1998-11-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531096","names":[{"lang":"en","v":"NAN TIAN (HONG KONG) FOOD STUFF COMPANY LIMITED"},{"lang":"hk","v":"南天(香港)食品有限公司"}],"company_since":"1995-11-21","company_dissolved":"1999-05-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531308","names":[{"lang":"en","v":"RICHTOP SUCCESS ENTERPRISES LIMITED"},{"lang":"hk","v":"鼎峰企業有限公司"}],"company_since":"1995-11-21","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531083","names":[{"lang":"en","v":"RONDEX LIMITED (d1999-12-03)"},{"lang":"hk","v":"朗程有限公司"}],"company_since":"1995-11-21","company_dissolved":"1999-12-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531050","names":[{"lang":"en","v":"ROYAL LAURENCE INC. H.K. LIMITED"}],"company_since":"1995-11-21","company_dissolved":"2000-12-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531365","names":[{"lang":"en","v":"SAFE GLORY ECONOMIC DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"安榮經貿發展有限公司"}],"company_since":"1995-11-21","company_dissolved":"2000-11-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531304","names":[{"lang":"en","v":"S &amp; A INTERNATIONAL TRADING COMPANY LIMITED"}],"company_since":"1995-11-21","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531048","names":[{"lang":"en","v":"SARTEX LIMITED (d2006-04-13)"},{"lang":"hk","v":"瑞東有限公司"}],"company_since":"1995-11-21","company_dissolved":"2006-04-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531088","names":[{"lang":"en","v":"SHEEN EXPRESS LIMITED (d2004-08-13)"},{"lang":"hk","v":"源捷有限公司"}],"company_since":"1995-11-21","company_dissolved":"2004-08-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531197","names":[{"lang":"en","v":"NEW REGULAR LIMITED"},{"lang":"hk","v":"新華高有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531353","names":[{"lang":"en","v":"SHEN GANG GROUP LIMITED"},{"lang":"hk","v":"瀋港集團有限公司"}],"company_since":"1995-11-21","company_dissolved":"2008-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531364","names":[{"lang":"en","v":"ORIENTAL HEAVEN GROUP LIMITED"},{"lang":"hk","v":"東天集團有限公司"}],"company_since":"1995-11-21","company_dissolved":"1998-11-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531228","names":[{"lang":"en","v":"OVATION INTERNATIONAL LIMITED (d1998-09-04)"},{"lang":"hk","v":"傲威信國際有限公司"}],"company_since":"1995-11-21","company_dissolved":"1998-09-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531312","names":[{"lang":"en","v":"PACIFIC STAR INVESTMENTS LIMITED (HK)"},{"lang":"hk","v":"星悅投資有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531329","names":[{"lang":"en","v":"PAN WIN REALTY (INDUSTRIAL) LIMITED"},{"lang":"hk","v":"栢聯地產(工業)有限公司"}],"company_since":"1995-11-21","company_dissolved":"2002-11-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531092","names":[{"lang":"en","v":"SINO CRYSTAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"華晶發展有限公司"}],"company_since":"1995-11-21","company_dissolved":"2017-03-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531314","names":[{"lang":"en","v":"SINO RELIANCE ENTERPRISE LIMITED"},{"lang":"hk","v":"信承企業有限公司"}],"company_since":"1995-11-21","company_dissolved":"2018-06-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531276","names":[{"lang":"en","v":"PARASON ENTERPRISE LIMITED"},{"lang":"hk","v":"柏倫企業有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531123","names":[{"lang":"en","v":"SINOBREW LIMITED"},{"lang":"hk","v":"中釀有限公司"}],"company_since":"1995-11-21","company_dissolved":"2002-11-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531055","names":[{"lang":"en","v":"SHEEN GROUP LIMITED (d2005-11-04)"},{"lang":"hk","v":"源合有限公司"}],"company_since":"1995-11-21","company_dissolved":"2005-11-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531340","names":[{"lang":"en","v":"SINOWAI RESOURCES COMPANY LIMITED"},{"lang":"hk","v":"中威工業資源有限公司"}],"company_since":"1995-11-21","company_dissolved":"2015-06-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531110","names":[{"lang":"en","v":"SINTEC INTERNATIONAL LIMITED"},{"lang":"hk","v":"思達國際有限公司"}],"company_since":"1995-11-21","company_dissolved":"2012-06-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531154","names":[{"lang":"en","v":"SLOPE ENGINEERING LIMITED"},{"lang":"hk","v":"斜坡工程有限公司"}],"company_since":"1995-11-21","company_dissolved":"2009-05-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531244","names":[{"lang":"en","v":"SHINE MOON INTERNATIONAL LIMITED"},{"lang":"hk","v":"興貿國際股份有限公司"}],"company_since":"1995-11-21","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531091","names":[{"lang":"en","v":"SMART HOUSE LIMITED (d2002-05-24)"},{"lang":"hk","v":"俊庭有限公司"}],"company_since":"1995-11-21","company_dissolved":"2002-05-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531268","names":[{"lang":"en","v":"POLYTEAM DEVELOPMENT LIMITED"},{"lang":"hk","v":"百利添發展有限公司"}],"company_since":"1995-11-21","company_dissolved":"2019-04-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531144","names":[{"lang":"en","v":"SMARTCOM-WEIYI INVESTMENTS LIMITED"}],"company_since":"1995-11-21","company_dissolved":"2005-11-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531290","names":[{"lang":"en","v":"PRECISION THERAPY ASIA LIMITED"}],"company_since":"1995-11-21","company_dissolved":"2001-08-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531098","names":[{"lang":"en","v":"SOFTSPEED CONSULTANT LIMITED"},{"lang":"hk","v":"快意科技顧問有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531346","names":[{"lang":"en","v":"PROLIN ENTERPRISES LIMITED"},{"lang":"hk","v":"寶寧企業有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531330","names":[{"lang":"en","v":"Q P INDUSTRIAL LIMITED"},{"lang":"hk","v":"雋思實業有限公司"}],"company_since":"1995-11-21","company_dissolved":"2016-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531192","names":[{"lang":"en","v":"SUN MINISTER CORP., LIMITED"},{"lang":"hk","v":"順民企業股份有限公司"}],"company_since":"1995-11-21","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531215","names":[{"lang":"en","v":"SUN ROUTE ELECTRIC CO. LIMITED"},{"lang":"hk","v":"大江電熱機械股份有限公司"}],"company_since":"1995-11-21","company_dissolved":"2001-12-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531360","names":[{"lang":"en","v":"REX INDUSTRIES HONG KONG COMPANY LIMITED"},{"lang":"hk","v":"力克士香港有限公司"}],"company_since":"1995-11-21","company_dissolved":"2001-07-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531086","names":[{"lang":"en","v":"SUNMEX LIMITED (d2003-04-25)"},{"lang":"hk","v":"新文有限公司"}],"company_since":"1995-11-21","company_dissolved":"2003-04-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531087","names":[{"lang":"en","v":"SUNNY CASTLE LIMITED (d2001-11-23)"},{"lang":"hk","v":"新都城有限公司"}],"company_since":"1995-11-21","company_dissolved":"2001-11-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531152","names":[{"lang":"en","v":"SUPER NICEFUL LIMITED"},{"lang":"hk","v":"特麗寶有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"531093","names":[{"lang":"en","v":"SUPREME HI-TECH. PRODUCTS WORLD LIMITED"},{"lang":"hk","v":"崇尊科技產品國際有限公司"}],"company_since":"1995-11-21","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531106","names":[{"lang":"en","v":"RMG INTERNATIONAL (HK) LIMITED"},{"lang":"hk","v":"英亞國際貨運(香港)有限公司"}],"company_since":"1995-11-21","company_dissolved":"2002-06-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531324","names":[{"lang":"en","v":"TA CHUNG SHIPPING (CHINA) COMPANY LIMITED"},{"lang":"hk","v":"大中船務(中國)有限公司"}],"company_since":"1995-11-21","company_dissolved":"2016-10-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531157","names":[{"lang":"en","v":"TAI SUN WAI FISHING VILLAGE MANAGEMENT CO. LIMITED"},{"lang":"hk","v":"大生圍漁村管理有限公司"}],"company_since":"1995-11-21","company_dissolved":"2005-11-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531061","names":[{"lang":"en","v":"HOI TUNG TRANSPORTATION LIMITED"},{"lang":"hk","v":"海通通運有限公司"}],"company_since":"1995-11-21","company_dissolved":"2013-01-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531056","names":[{"lang":"en","v":"SERENA LIMITED (d2008-04-03)"},{"lang":"hk","v":"源藝有限公司"}],"company_since":"1995-11-21","company_dissolved":"2008-04-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531226","names":[{"lang":"en","v":"TEK MAP LIMITED"},{"lang":"hk","v":"金露科技有限公司"}],"company_since":"1995-11-21","company_dissolved":"2011-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531042","names":[{"lang":"en","v":"SHELLESON ENTERPRISES LIMITED"},{"lang":"hk","v":"源誠企業有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531049","names":[{"lang":"en","v":"SHINE CONCORD LIMITED"},{"lang":"hk","v":"瑞港有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531181","names":[{"lang":"en","v":"TOPPING TRADING COMPANY LIMITED"},{"lang":"hk","v":"冠品貿易有限公司"}],"company_since":"1995-11-21","company_dissolved":"2018-05-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531166","names":[{"lang":"en","v":"TOTAL WIN INVESTMENTS LIMITED"},{"lang":"hk","v":"通榮投資有限公司"}],"company_since":"1995-11-21","company_dissolved":"2004-04-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"531158","names":[{"lang":"en","v":"TOWER ENERGY SYSTEMS CO., LIMITED"},{"lang":"hk","v":"大華能源系統有限公司"}],"company_since":"1995-11-21","company_dissolved":"2006-12-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531272","names":[{"lang":"en","v":"SHINYO TRADING CO., LIMITED"},{"lang":"hk","v":"秦陽貿易有限公司"}],"company_since":"1995-11-21","company_dissolved":"2003-07-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531207","names":[{"lang":"en","v":"TRICOMM LIMITED"},{"lang":"hk","v":"三高洋行有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531094","names":[{"lang":"en","v":"TRUTH STAR INTERNATIONAL LIMITED"},{"lang":"hk","v":"信星國際有限公司"}],"company_since":"1995-11-21","company_dissolved":"2005-11-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531341","names":[{"lang":"en","v":"UNION SMART DESIGN &amp; ENGINEERING LIMITED"},{"lang":"hk","v":"合俊設計工程有限公司"}],"company_since":"1995-11-21","company_dissolved":"2011-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"531271","names":[{"lang":"en","v":"SINTEC LIMITED"},{"lang":"hk","v":"思迪有限公司"}],"company_since":"1995-11-21","company_dissolved":"2018-08-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531274","names":[{"lang":"en","v":"VALOR BRIGHT PAPER PRODUCTS LIMITED"},{"lang":"hk","v":"旭暉紙品有限公司"}],"company_since":"1995-11-21","company_dissolved":"2003-02-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531107","names":[{"lang":"en","v":"VICTOR PEI INTERNATIONAL ARCHITECTURAL CONSULTANTS (HK) LIMITED"},{"lang":"hk","v":"貝聿儔國際建築顧問(香港)有限公司"}],"company_since":"1995-11-21","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531178","names":[{"lang":"en","v":"VISION-PRO INDUSTRIAL LIMITED"},{"lang":"hk","v":"衛信實業有限公司"}],"company_since":"1995-11-21","company_dissolved":"2020-04-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531130","names":[{"lang":"en","v":"VITA HANDBAG MATERIAL SUPPLIES LIMITED"},{"lang":"hk","v":"永達手袋原料有限公司"}],"company_since":"1995-11-21","company_dissolved":"2007-06-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531122","names":[{"lang":"en","v":"WAI SUN TRANSPORTATION COMPANY LIMITED"},{"lang":"hk","v":"維新旅運有限公司"}],"company_since":"1995-11-21","company_dissolved":"2004-10-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531301","names":[{"lang":"en","v":"SMITH &amp; TOWNSEND ASIA LIMITED"},{"lang":"hk","v":"駿豐證券有限公司"}],"company_since":"1995-11-21","company_dissolved":"2013-08-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531316","names":[{"lang":"en","v":"SOLAR STAR DEVELOPMENT LIMITED"},{"lang":"hk","v":"星銳發展有限公司"}],"company_since":"1995-11-21","company_dissolved":"2005-11-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"531281","names":[{"lang":"en","v":"SPOT MEDIA CONCEPT LIMITED"}],"company_since":"1995-11-21","company_dissolved":"2004-08-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531347","names":[{"lang":"en","v":"SPARKDATA INTERNATIONAL LIMITED"},{"lang":"hk","v":"耀訊國際有限公司"}],"company_since":"1995-11-21","company_dissolved":"2004-08-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531319","names":[{"lang":"en","v":"WILY INDUSTRIAL LIMITED"},{"lang":"hk","v":"耀利實業有限公司"}],"company_since":"1995-11-21","company_dissolved":"2003-05-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531287","names":[{"lang":"en","v":"SUN FUNG GARMENT FACTORY LIMITED"},{"lang":"hk","v":"新豐製衣廠有限公司"}],"company_since":"1995-11-21","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531060","names":[{"lang":"en","v":"Win Wind Investment (Holdings) Limited"},{"lang":"hk","v":"萬贏投資控股有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531187","names":[{"lang":"en","v":"WING TAT TYRE COMPANY LIMITED"},{"lang":"hk","v":"永達膠輪有限公司"}],"company_since":"1995-11-21","company_dissolved":"2012-04-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531238","names":[{"lang":"en","v":"WINSTAR (H.K.) LIMITED"},{"lang":"hk","v":"永星(香港)有限公司"}],"company_since":"1995-11-21","company_dissolved":"2004-10-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531222","names":[{"lang":"en","v":"SUPER PILOT LIMITED"},{"lang":"hk","v":"領超有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531057","names":[{"lang":"en","v":"YANMEX LIMITED"},{"lang":"hk","v":"源明有限公司"}],"company_since":"1995-11-21","company_dissolved":"2018-03-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531263","names":[{"lang":"en","v":"YING FUNG METAL FACTORY LIMITED"},{"lang":"hk","v":"盈豐金屬製品有限公司"}],"company_since":"1995-11-21","company_dissolved":"1999-04-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531097","names":[{"lang":"en","v":"YING SHENG FOODSTUFFS (HK) LIMITED"},{"lang":"hk","v":"銀盛食品(香港)有限公司"}],"company_since":"1995-11-21","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531208","names":[{"lang":"en","v":"ZENITH ASIA LIMITED"},{"lang":"hk","v":"先力亞洲有限公司"}],"company_since":"1995-11-21","company_dissolved":"2019-11-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531359","names":[{"lang":"en","v":"TONG YANG GLOBAL (H.K.) LIMITED"},{"lang":"hk","v":"東洋環宇(香港)有限公司"}],"company_since":"1995-11-21","company_dissolved":"1999-02-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531351","names":[{"lang":"en","v":"ZENLOG (NOMINEE) LIMITED"},{"lang":"hk","v":"匯中(代理人)有限公司"}],"company_since":"1995-11-21","company_dissolved":"2002-08-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531232","names":[{"lang":"en","v":"TOP MODERN TRADING LIMITED"},{"lang":"hk","v":"第一現代貿易有限公司"}],"company_since":"1995-11-21","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531213","names":[{"lang":"en","v":"TRADE ALUMINIUM LIMITED (d2004-03-26)"}],"company_since":"1995-11-21","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531069","names":[{"lang":"en","v":"UNITED BASIC LASER &amp; VIDEO COMPANY LIMITED"},{"lang":"hk","v":"聯基鐳射錄影有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"531358","names":[{"lang":"en","v":"UNIVERSAL BROS. (H.K.) LIMITED"},{"lang":"hk","v":"環球兄弟(香港)有限公司"}],"company_since":"1995-11-21","company_dissolved":"2000-06-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531242","names":[{"lang":"en","v":"WAVEPEARL WARPING FACTORY LIMITED"},{"lang":"hk","v":"浪寶經紗廠有限公司"}],"company_since":"1995-11-21","company_dissolved":"2015-06-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531266","names":[{"lang":"en","v":"WAYTECHSON COMPANY LIMITED"},{"lang":"hk","v":"威達信實業有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531200","names":[{"lang":"en","v":"WELL RELIANCE CONSTRUCTION COMPANY LIMITED"},{"lang":"hk","v":"偉信建築有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531199","names":[{"lang":"en","v":"WELL UNION SERVICES LIMITED"},{"lang":"hk","v":"浩安聯運有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531165","names":[{"lang":"en","v":"WHOLLICOM INVESTMENTS LIMITED"},{"lang":"hk","v":"浩廣投資有限公司"}],"company_since":"1995-11-21","company_dissolved":"2003-11-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531067","names":[{"lang":"en","v":"WIN TREASURE INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"力寶威國際有限公司"}],"company_since":"1995-11-21","company_dissolved":"2013-03-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"531140","names":[{"lang":"en","v":"WELLIN INTERNATIONAL INDUSTRIAL LIMITED"},{"lang":"hk","v":"偉聯國際實業有限公司"}],"company_since":"1995-11-21","company_dissolved":"2007-11-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"531267","names":[{"lang":"en","v":"WINSTAR TRADING LIMITED (d2001-08-24)"},{"lang":"hk","v":"永星貿易有限公司"}],"company_since":"1995-11-21","company_dissolved":"2001-08-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"531320","names":[{"lang":"en","v":"YIU KWAN COMPANY LIMITED"},{"lang":"hk","v":"耀群有限公司"}],"company_since":"1995-11-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531352","names":[{"lang":"en","v":"ZENLOG FINANCE LIMITED"},{"lang":"hk","v":"匯中財務有限公司"}],"company_since":"1995-11-21","company_dissolved":"2002-10-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531138","names":[{"lang":"en","v":"HONG KONG NINE AND NINE SATELLITE LIMITED"},{"lang":"hk","v":"香港九九衞星通訊有限公司"}],"company_since":"1995-11-21","company_dissolved":"2005-11-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531134","names":[{"lang":"en","v":"GOLDFLOW ENTERPRISES LIMITED"},{"lang":"hk","v":"金富運企業有限公司"}],"company_since":"1995-11-21","company_dissolved":"1999-05-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"531051","names":[{"lang":"en","v":"SHUI HIP (INTERNATIONAL) COMPANY LIMITED"},{"lang":"hk","v":"瑞勰國際有限公司"}],"company_since":"1995-11-21","company_dissolved":"2007-05-04","company_type_txt":"Private, ltd by shares"},
undefined,
