undefined,
undefined,
undefined,
{"tax_id":"666321","names":[{"lang":"en","v":"CHING WELL INTERNATIONAL LIMITED"},{"lang":"hk","v":"慶虹國際有限公司"}],"company_since":"1999-01-29","company_dissolved":"2012-10-26","company_type_txt":"Private, ltd by shares"},
{"tax_id":"666444","names":[{"lang":"en","v":"FLYING DRAGON ENTERPRISES (HONG KONG) LIMITED"},{"lang":"hk","v":"騰飛企業(香港)有限公司"}],"company_since":"1999-01-29","company_dissolved":"2010-06-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666408","names":[{"lang":"en","v":"FMC INTERNATIONAL LIMITED (d2001-08-10)"}],"company_since":"1999-01-29","company_dissolved":"2001-08-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666381","names":[{"lang":"en","v":"CHU MING (ENGINEERING) TRANSPORTATION CO., LIMITED"},{"lang":"hk","v":"朱明(工程)運輸有限公司"}],"company_since":"1999-01-29","company_dissolved":"2005-12-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"666385","names":[{"lang":"en","v":"FUTURA CONSULTANT LIMITED"},{"lang":"hk","v":"創思顧問有限公司"}],"company_since":"1999-01-29","company_dissolved":"2003-06-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"666442","names":[{"lang":"en","v":"G &amp; C COMPANY LIMITED (d2002-06-21)"}],"company_since":"1999-01-29","company_dissolved":"2002-06-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666323","names":[{"lang":"en","v":"GEMS (H.K.) LIMITED"}],"company_since":"1999-01-29","company_dissolved":"2002-10-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"666288","names":[{"lang":"en","v":"CHWOROWSKY LIMITED"}],"company_since":"1999-01-29","company_dissolved":"2009-07-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"666399","names":[{"lang":"en","v":"GENERAL-TECH INNOVATIVE COMPANY LIMITED"},{"lang":"hk","v":"展達創新科技有限公司"}],"company_since":"1999-01-29","company_dissolved":"2010-06-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"666294","names":[{"lang":"en","v":"GOLDEN BELL ENTERPRISE LIMITED (d2003-11-07)"},{"lang":"hk","v":"金鐘企業有限公司"}],"company_since":"1999-01-29","company_dissolved":"2003-11-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666305","names":[{"lang":"en","v":"GOLDFIELD (HONG KONG) LIMITED (d2003-03-21)"},{"lang":"hk","v":"金豪貿易(香港)有限公司"}],"company_since":"1999-01-29","company_dissolved":"2003-03-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"666319","names":[{"lang":"en","v":"CYBER CINEPLEX (CHINA) LIMITED"},{"lang":"hk","v":"中國數碼廳有限公司"}],"company_since":"1999-01-29","company_dissolved":"2012-12-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666403","names":[{"lang":"en","v":"GW LIMITED (d2002-02-22)"}],"company_since":"1999-01-29","company_dissolved":"2002-02-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"666350","names":[{"lang":"en","v":"HIRSCHBERG SCHUTZ &amp; COMPANY LIMITED"},{"lang":"hk","v":"赫世伯國際有限公司"}],"company_since":"1999-01-29","company_dissolved":"2008-06-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666439","names":[{"lang":"en","v":"HIT DIAMOND COMPANY LIMITED"},{"lang":"hk","v":"恆寶珠寶集團有限公司"}],"company_since":"1999-01-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"666418","names":[{"lang":"en","v":"DANCE MASTER ENTERTAINMENT CLUB LIMITED"},{"lang":"hk","v":"尊舞會有限公司"}],"company_since":"1999-01-29","company_dissolved":"2010-06-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666360","names":[{"lang":"en","v":"HONG KONG SHOKU HO LIMITED"},{"lang":"hk","v":"香港食寶有限公司"}],"company_since":"1999-01-29","company_dissolved":"2010-06-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666352","names":[{"lang":"en","v":"COMFORT INSURANCE MANAGEMENT AGENCY LIMITED"},{"lang":"hk","v":"嘉滙保險代理有限公司"}],"company_since":"1999-01-29","company_dissolved":"2005-12-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666354","names":[{"lang":"en","v":"HONGKONG LIANXUN TECHNOLOGY LIMITED"},{"lang":"hk","v":"香港聯迅科技有限公司"}],"company_since":"1999-01-29","company_dissolved":"2012-01-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"666447","names":[{"lang":"en","v":"J &amp; H LIMITED (d2001-12-28)"}],"company_since":"1999-01-29","company_dissolved":"2001-12-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"666286","names":[{"lang":"en","v":"J.S. MARKETING LIMITED (d2007-06-08)"},{"lang":"hk","v":"樹生國際有限公司"}],"company_since":"1999-01-29","company_dissolved":"2007-06-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"666316","names":[{"lang":"en","v":"JOJU (H.K.) INVESTMENT DEVELOPMENT LIMITED"},{"lang":"hk","v":"卓眾(香港)投資發展有限公司"}],"company_since":"1999-01-29","company_dissolved":"2005-02-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"666289","names":[{"lang":"en","v":"DIAMOND TALENT LIMITED"},{"lang":"hk","v":"毅利有限公司"}],"company_since":"1999-01-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"666430","names":[{"lang":"en","v":"DISTRIBUTION NETWORK ASSOCIATES (DNA) LIMITED"},{"lang":"hk","v":"動力網有限公司"}],"company_since":"1999-01-29","company_dissolved":"2008-06-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666393","names":[{"lang":"en","v":"KAR LEE CAFE LIMITED"},{"lang":"hk","v":"嘉利茶餐廳有限公司"}],"company_since":"1999-01-29","company_dissolved":"2001-09-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666407","names":[{"lang":"en","v":"JOYFUL MONEY (H.K.) DEVELOPMENT CO., LIMITED"},{"lang":"hk","v":"豫洋(香港)發展有限公司"}],"company_since":"1999-01-29","company_dissolved":"2005-02-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666302","names":[{"lang":"en","v":"E &amp; A CLEANING SERVICES HONG KONG COMPANY LIMITED"},{"lang":"hk","v":"怡雅清潔服務有限公司"}],"company_since":"1999-01-29","company_dissolved":"2009-09-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666421","names":[{"lang":"en","v":"L &amp; Q (HONGKONG) TRADING LIMITED"},{"lang":"hk","v":"魯青(香港)貿易有限公司"}],"company_since":"1999-01-29","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666383","names":[{"lang":"en","v":"CITYPHARM LIMITED"},{"lang":"hk","v":"城市醫療藥業有限公司"}],"company_since":"1999-01-29","company_dissolved":"2000-10-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"666369","names":[{"lang":"en","v":"HONG KONG HUA MEI PROPERTY LIMITED"},{"lang":"hk","v":"香港華美置業有限公司"}],"company_since":"1999-01-29","company_dissolved":"2005-02-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"666315","names":[{"lang":"en","v":"KONG KAI ENTERPRISES LIMITED"}],"company_since":"1999-01-29","company_dissolved":"2012-06-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"666348","names":[{"lang":"en","v":"LA1 COMPANY LIMITED"}],"company_since":"1999-01-29","company_dissolved":"2006-06-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"666395","names":[{"lang":"en","v":"EAST BRIDGE ENGINEERING AND TRADING COMPANY LIMITED"},{"lang":"hk","v":"東橋工程貿易有限公司"}],"company_since":"1999-01-29","company_dissolved":"2002-04-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"666318","names":[{"lang":"en","v":"LASTING BLOOM LIMITED"}],"company_since":"1999-01-29","company_dissolved":"2005-03-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666366","names":[{"lang":"en","v":"EIDOS LIMITED"}],"company_since":"1999-01-29","company_dissolved":"2005-02-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"666296","names":[{"lang":"en","v":"PACIFIC MICROELECTRONICS (HK) LIMITED"},{"lang":"hk","v":"亞太微電子(香港)有限公司"}],"company_since":"1999-01-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666330","names":[{"lang":"en","v":"OCTOTECH CHINA LIMITED"},{"lang":"hk","v":"八達中國有限公司"}],"company_since":"1999-01-29","company_dissolved":"2006-04-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666299","names":[{"lang":"en","v":"PACIFIC GRAND TRADING LIMITED (d2002-03-28)"},{"lang":"hk","v":"恒廣貿易有限公司"}],"company_since":"1999-01-29","company_dissolved":"2002-03-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"666379","names":[{"lang":"en","v":"PACIFIC PRINTING &amp; PACKAGING LIMITED"},{"lang":"hk","v":"柏輝印刷包裝有限公司"}],"company_since":"1999-01-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666370","names":[{"lang":"en","v":"MASUINNO CORPORATION LIMITED"},{"lang":"hk","v":"政德有限公司"}],"company_since":"1999-01-29","company_dissolved":"2001-12-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666384","names":[{"lang":"en","v":"FASHION HOUSE LIMITED (HK)"},{"lang":"hk","v":"新穎坊時裝有限公司"}],"company_since":"1999-01-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"666361","names":[{"lang":"en","v":"MIDDLE AGE DESIGN AND ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"中世紀設計裝飾工程有限公司"}],"company_since":"1999-01-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666329","names":[{"lang":"en","v":"PAN ASIA LIMITED"},{"lang":"hk","v":"汎亞有限公司"}],"company_since":"1999-01-29","company_dissolved":"2005-02-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666310","names":[{"lang":"en","v":"ONLINE VISION COMPANY LIMITED"},{"lang":"hk","v":"互景科技有限公司"}],"company_since":"1999-01-29","company_dissolved":"2000-08-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666338","names":[{"lang":"en","v":"EURO VENT LIMITED"},{"lang":"hk","v":"歐羅空調設備有限公司"}],"company_since":"1999-01-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666405","names":[{"lang":"en","v":"FOOTMAX INTERNATIONAL ENTERPRISES LIMITED"},{"lang":"hk","v":"福邁斯國際實業有限公司"}],"company_since":"1999-01-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"666412","names":[{"lang":"en","v":"PORYAN INDUSTRIAL COMPANY LIMITED"},{"lang":"hk","v":"百欣工業有限公司"}],"company_since":"1999-01-29","company_dissolved":"2013-07-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"666304","names":[{"lang":"en","v":"NORDIC LINK LIMITED (d2003-04-04)"}],"company_since":"1999-01-29","company_dissolved":"2003-04-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666355","names":[{"lang":"en","v":"LEAD PROSPECT LIMITED"}],"company_since":"1999-01-29","company_dissolved":"2000-09-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666371","names":[{"lang":"en","v":"LINK (C.B.C.) LIMITED"}],"company_since":"1999-01-29","company_dissolved":"2009-06-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666293","names":[{"lang":"en","v":"PACIFIC EARTH TRADING LIMITED"},{"lang":"hk","v":"恒洋貿易有限公司"}],"company_since":"1999-01-29","company_dissolved":"2018-04-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666401","names":[{"lang":"en","v":"EAST-WEST STRATEGIC DEVELOPMENT COMMISSION LIMITED"},{"lang":"hk","v":"國際發展策略局有限公司"}],"company_since":"1999-01-29","company_dissolved":"2012-03-08","company_type_txt":"Ltd by guarantee"},
{"tax_id":"666387","names":[{"lang":"en","v":"MARINE RESOURCES ENGINEERING LIMITED"},{"lang":"hk","v":"海洋資源工程有限公司"}],"company_since":"1999-01-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666301","names":[{"lang":"en","v":"MILLION SCORE LIMITED (d2007-09-21)"},{"lang":"hk","v":"茂成有限公司"}],"company_since":"1999-01-29","company_dissolved":"2007-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666415","names":[{"lang":"en","v":"NEW ART (BMS) LIMITED"},{"lang":"hk","v":"新藝建業有限公司"}],"company_since":"1999-01-29","company_dissolved":"2014-01-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666428","names":[{"lang":"en","v":"MONTE CARLO ADVERTISING PRODUCTION LIMITED"},{"lang":"hk","v":"蒙地卡羅廣告製作有限公司"}],"company_since":"1999-01-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666307","names":[{"lang":"en","v":"PRIME CORPORATE LIMITED (d2000-09-22)"},{"lang":"hk","v":"泰利行有限公司"}],"company_since":"1999-01-29","company_dissolved":"2000-09-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666287","names":[{"lang":"en","v":"RAPID SUCCESS LIMITED (d2004-07-16)"},{"lang":"hk","v":"駿龍有限公司"}],"company_since":"1999-01-29","company_dissolved":"2004-07-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666414","names":[{"lang":"en","v":"ETERNAL BASE LIMITED (d2001-07-20)"},{"lang":"hk","v":"恒基興業有限公司"}],"company_since":"1999-01-29","company_dissolved":"2001-07-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"666313","names":[{"lang":"en","v":"NEW PRIME LIMITED (d2007-06-08)"},{"lang":"hk","v":"新姿有限公司"}],"company_since":"1999-01-29","company_dissolved":"2007-06-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666424","names":[{"lang":"en","v":"FINEX DISC PROCESSING LIMITED"},{"lang":"hk","v":"科力光碟製作有限公司"}],"company_since":"1999-01-29","company_dissolved":"2011-08-26","company_type_txt":"Private, ltd by shares"},
{"tax_id":"666359","names":[{"lang":"en","v":"GLOBE NETWORK LIMITED"}],"company_since":"1999-01-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"666356","names":[{"lang":"en","v":"REPUBLIC ALLIANCE LIMITED"},{"lang":"hk","v":"共和聯合有限公司"}],"company_since":"1999-01-29","company_dissolved":"2003-10-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666308","names":[{"lang":"en","v":"ROYAL SINO LIMITED (d2007-06-08)"},{"lang":"hk","v":"朗中有限公司"}],"company_since":"1999-01-29","company_dissolved":"2007-06-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666357","names":[{"lang":"en","v":"ROSTAR COMPANY LIMITED"},{"lang":"hk","v":"和緯有限公司"}],"company_since":"1999-01-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666295","names":[{"lang":"en","v":"PACIFIC CAPITAL INTERNATIONAL LIMITED"},{"lang":"hk","v":"來利資本國際有限公司"}],"company_since":"1999-01-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666373","names":[{"lang":"en","v":"SAI KA INDUSTRIAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"世嘉實業發展有限公司"}],"company_since":"1999-01-29","company_dissolved":"2012-07-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666325","names":[{"lang":"en","v":"SHENZHEN SINOTRANS (H.K.) CO., LIMITED"},{"lang":"hk","v":"深圳外運(香港)有限公司"}],"company_since":"1999-01-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666440","names":[{"lang":"en","v":"HALMA INVESTMENTS LIMITED"}],"company_since":"1999-01-29","company_dissolved":"2003-07-11","company_type_txt":"Private, ltd by shares"},
{"tax_id":"666334","names":[{"lang":"en","v":"SLD HOLDINGS LIMITED (HK)"}],"company_since":"1999-01-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"666435","names":[{"lang":"en","v":"SHING CHEONG NATIVE FOOD WHOLESALE LIMITED"},{"lang":"hk","v":"盛昌土產食品批發有限公司"}],"company_since":"1999-01-29","company_dissolved":"2001-04-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666349","names":[{"lang":"en","v":"SITA RECYCLING ASIA LIMITED"}],"company_since":"1999-01-29","company_dissolved":"2007-11-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666434","names":[{"lang":"en","v":"SAIGO CREATION LIMITED"},{"lang":"hk","v":"世高創建有限公司"}],"company_since":"1999-01-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"666347","names":[{"lang":"en","v":"GOOD CENTURY INDUSTRIAL LIMITED"},{"lang":"hk","v":"金時代實業有限公司"}],"company_since":"1999-01-29","company_dissolved":"2001-04-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"666363","names":[{"lang":"en","v":"Savills Valuation and Professional Services Limited"},{"lang":"hk","v":"第一太平戴維斯估值及專業顧問有限公司"}],"company_since":"1999-01-29","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
