undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"665626","names":[{"lang":"en","v":"GRUPPO CONCIARIO VENETO (ASIA) LIMITED"}],"company_since":"1999-01-22","company_dissolved":"2007-06-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"665643","names":[{"lang":"en","v":"DU-ACROSS (HK) CO LIMITED"},{"lang":"hk","v":"渡(香港)有限公司"}],"company_since":"1999-01-22","company_dissolved":"2007-06-01","company_type_txt":"Private, ltd by shares"},
{"tax_id":"665628","names":[{"lang":"en","v":"DORING INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"多嶺國際有限公司"}],"company_since":"1999-01-22","company_dissolved":"2001-03-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"665812","names":[{"lang":"en","v":"HAN CHUNG TRADING LIMITED"},{"lang":"hk","v":"瀚中貿易有限公司"}],"company_since":"1999-01-22","company_dissolved":"2004-06-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"665833","names":[{"lang":"en","v":"EMERI ENTERPRISE COMPANY LIMITED"}],"company_since":"1999-01-22","company_dissolved":"2008-06-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"665815","names":[{"lang":"en","v":"HENFIELD INVESTMENTS LIMITED (d2001-04-20)"},{"lang":"hk","v":"鴻輝投資有限公司"}],"company_since":"1999-01-22","company_dissolved":"2001-04-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"665800","names":[{"lang":"en","v":"HENFORD TRADING LIMITED (d2001-12-14)"},{"lang":"hk","v":"恒鋒貿易有限公司"}],"company_since":"1999-01-22","company_dissolved":"2001-12-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"665745","names":[{"lang":"en","v":"HENNESON INDUSTRIES LIMITED"},{"lang":"hk","v":"恒勝實業有限公司"}],"company_since":"1999-01-22","company_dissolved":"2011-04-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"665645","names":[{"lang":"en","v":"DONG CHUN INTERNATIONAL (HOLDINGS) LIMITED"},{"lang":"hk","v":"東駿國際(控股)有限公司"}],"company_since":"1999-01-22","company_dissolved":"2003-04-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"665710","names":[{"lang":"en","v":"HONEST TAX REPRESENTATIVES LIMITED"},{"lang":"hk","v":"忠誠稅務代表有限公司"}],"company_since":"1999-01-22","company_dissolved":"2015-06-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"665793","names":[{"lang":"en","v":"FOODGEARS INDUSTRIAL INTERNATIONAL LIMITED"},{"lang":"hk","v":"福基國際工業股份有限公司"}],"company_since":"1999-01-22","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"665823","names":[{"lang":"en","v":"HONG KONG CHING WIN PUBLISHING COMPANY LIMITED"},{"lang":"hk","v":"香港青文出版社有限公司"}],"company_since":"1999-01-22","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"665622","names":[{"lang":"en","v":"HONG KONG INTERNATIONAL AIHUA GROUP HOLDINGS LIMITED"},{"lang":"hk","v":"香港愛華國際集團控股有限公司"}],"company_since":"1999-01-22","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"665751","names":[{"lang":"en","v":"HONGKONG PRESTIGE INDUSTRY LIMITED"},{"lang":"hk","v":"香港信一實業有限公司"}],"company_since":"1999-01-22","company_dissolved":"2005-01-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"665802","names":[{"lang":"en","v":"HYKOR GROUP LIMITED"},{"lang":"hk","v":"海闊集團有限公司"}],"company_since":"1999-01-22","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"665835","names":[{"lang":"en","v":"FRENCH WINE PARADOX LIMITED"}],"company_since":"1999-01-22","company_dissolved":"2005-12-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"665813","names":[{"lang":"en","v":"I-CENTURY CORPORATION LIMITED"},{"lang":"hk","v":"恆禾數碼資訊有限公司"}],"company_since":"1999-01-22","company_dissolved":"2008-06-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"665717","names":[{"lang":"en","v":"FERTILE LAND HOLDINGS LIMITED"}],"company_since":"1999-01-22","company_dissolved":"2003-08-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"665731","names":[{"lang":"en","v":"FLYWAY DEVELOPMENT INDUSTRIAL CO., LIMITED"},{"lang":"hk","v":"高威發展實業有限公司"}],"company_since":"1999-01-22","company_dissolved":"2002-02-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"665756","names":[{"lang":"en","v":"J &amp; C TRADING LIMITED (d2009-01-30)"}],"company_since":"1999-01-22","company_dissolved":"2009-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"665677","names":[{"lang":"en","v":"JALISCO LIMITED (d2005-12-09)"}],"company_since":"1999-01-22","company_dissolved":"2005-12-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"665670","names":[{"lang":"en","v":"JANFULL (GROUP) LIMITED"},{"lang":"hk","v":"晉富(集團)股份有限公司"}],"company_since":"1999-01-22","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"665820","names":[{"lang":"en","v":"FUHUI SHIPPING LIMITED"},{"lang":"hk","v":"富匯海運有限公司"}],"company_since":"1999-01-22","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"665712","names":[{"lang":"en","v":"JANFULL (TIANJIN) INVESTMENTS LIMITED"},{"lang":"hk","v":"晉富(天津)投資有限公司"}],"company_since":"1999-01-22","company_dissolved":"2003-11-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"665672","names":[{"lang":"en","v":"FUGRO SURVEY MANAGEMENT LIMITED"}],"company_since":"1999-01-22","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"665827","names":[{"lang":"en","v":"FACULTY OF SECRETARIES AND ADMINISTRATORS (H.K.) LIMITED"},{"lang":"hk","v":"特許企業秘書及行政人員公會有限公司"}],"company_since":"1999-01-22","company_dissolved":"2001-01-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"665635","names":[{"lang":"en","v":"JEDA PACIFIC (INTERNATIONAL) COMPANY LIMITED"},{"lang":"hk","v":"即達太平洋(國際)有限公司"}],"company_since":"1999-01-22","company_dissolved":"2007-05-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"665754","names":[{"lang":"en","v":"JFK HOLDING COMPANY LIMITED"}],"company_since":"1999-01-22","company_dissolved":"2017-12-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"665728","names":[{"lang":"en","v":"FULLYTEX CHEMICAL LIMITED"},{"lang":"hk","v":"富利達化工有限公司"}],"company_since":"1999-01-22","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"665691","names":[{"lang":"en","v":"JEXON INDUSTRIES LIMITED"},{"lang":"hk","v":"駿勝實業有限公司"}],"company_since":"1999-01-22","company_dissolved":"2012-01-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"665764","names":[{"lang":"en","v":"JOHARI DEVELOPMENT LIMITED"},{"lang":"hk","v":"瀚源發展有限公司"}],"company_since":"1999-01-22","company_dissolved":"2001-06-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"665822","names":[{"lang":"en","v":"DING LI XING INDUSTRIAL (H.K.) LIMITED"},{"lang":"hk","v":"鼎力興實業香港有限公司"}],"company_since":"1999-01-22","company_dissolved":"2005-01-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"665727","names":[{"lang":"en","v":"JIU SHUN WOOD PRODUCTS LIMITED"},{"lang":"hk","v":"九順木業有限公司"}],"company_since":"1999-01-22","company_dissolved":"2003-01-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"665734","names":[{"lang":"en","v":"KAM HUNG CONSTRUCTION COMPANY LIMITED"},{"lang":"hk","v":"錦鴻建築有限公司"}],"company_since":"1999-01-22","company_dissolved":"2009-03-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"665848","names":[{"lang":"en","v":"KING GLORY INTERNATIONAL LIMITED (d2001-06-08)"},{"lang":"hk","v":"佳康國際有限公司"}],"company_since":"1999-01-22","company_dissolved":"2001-06-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"665836","names":[{"lang":"en","v":"L &amp; L ADVERTISING CO. LIMITED"},{"lang":"hk","v":"香港旭日廣告有限公司"}],"company_since":"1999-01-22","company_dissolved":"2011-12-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"665709","names":[{"lang":"en","v":"GOLDEN ELECTRONIC INDUSTRY (H.K.) LIMITED"},{"lang":"hk","v":"國坤電子實業(香港)有限公司"}],"company_since":"1999-01-22","company_dissolved":"2005-01-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"665723","names":[{"lang":"en","v":"L &amp; S (HONG KONG) INFORMATION SCIENCE &amp; TECHNOLOGY LIMITED"},{"lang":"hk","v":"瑞利仕(香港)信息科技有限公司"}],"company_since":"1999-01-22","company_dissolved":"2004-01-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"665665","names":[{"lang":"en","v":"L.T. PROPERTIES LIMITED"},{"lang":"hk","v":"峻峰地產有限公司"}],"company_since":"1999-01-22","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"665683","names":[{"lang":"en","v":"MARINE LORD HOLDINGS LIMITED"},{"lang":"hk","v":"海威集團發展有限公司"}],"company_since":"1999-01-22","company_dissolved":"2001-12-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"665668","names":[{"lang":"en","v":"MAN HUNG INVESTMENTS LIMITED"},{"lang":"hk","v":"文雄投資有限公司"}],"company_since":"1999-01-22","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"665660","names":[{"lang":"en","v":"GOOD CHINA SHIPPING LIMITED"},{"lang":"hk","v":"華通船務(中國)有限公司"}],"company_since":"1999-01-22","company_dissolved":"2002-07-05","company_type_txt":"Private, ltd by shares"},
{"tax_id":"665829","names":[{"lang":"en","v":"EURO FLOORING INTERNATIONAL (H.K.) LIMITED"},{"lang":"hk","v":"歐陸地板(香港)有限公司"}],"company_since":"1999-01-22","company_dissolved":"2005-01-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"665641","names":[{"lang":"en","v":"LUCKY RICH LIMITED (d2001-06-01)"},{"lang":"hk","v":"兆運有限公司"}],"company_since":"1999-01-22","company_dissolved":"2001-06-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"665673","names":[{"lang":"en","v":"FUSION (HONG KONG) LIMITED (d2018-03-09)"}],"company_since":"1999-01-22","company_dissolved":"2018-03-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"665830","names":[{"lang":"en","v":"MAGICAL STRENGTH LIMITED"}],"company_since":"1999-01-22","company_dissolved":"2003-06-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"665651","names":[{"lang":"en","v":"MAX FORUM DEVELOPMENT LIMITED"},{"lang":"hk","v":"溢富發展有限公司"}],"company_since":"1999-01-22","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"665719","names":[{"lang":"en","v":"LAKSI GROUP LIMITED"}],"company_since":"1999-01-22","company_dissolved":"2018-11-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"665713","names":[{"lang":"en","v":"MATSUTA LIGHTING CO. LIMITED (d2000-08-18)"},{"lang":"hk","v":"旺興達照明有限公司"}],"company_since":"1999-01-22","company_dissolved":"2000-08-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"665648","names":[{"lang":"en","v":"H.K. GAXING INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"香港嘉誠國際集團有限公司"}],"company_since":"1999-01-22","company_dissolved":"2005-01-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"665689","names":[{"lang":"en","v":"KINPIRIT (HK) LIMITED"},{"lang":"hk","v":"凱普瑞(香港)有限公司"}],"company_since":"1999-01-22","company_dissolved":"2010-12-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"665795","names":[{"lang":"en","v":"KINGWAY TRADING LIMITED"},{"lang":"hk","v":"建華貿易有限公司"}],"company_since":"1999-01-22","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"665633","names":[{"lang":"en","v":"FU JING GRANITE LIMITED"},{"lang":"hk","v":"福京貿易有限公司"}],"company_since":"1999-01-22","company_dissolved":"2005-12-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"665655","names":[{"lang":"en","v":"L &amp; L FASHION LIMITED"},{"lang":"hk","v":"千對子時裝有限公司"}],"company_since":"1999-01-22","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"665676","names":[{"lang":"en","v":"GOLDEN STAR MANAGEMENT LIMITED (d2002-04-12)"}],"company_since":"1999-01-22","company_dissolved":"2002-04-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"665684","names":[{"lang":"en","v":"GEMINTAKE WORLDWIDE TRADE AGENCY CO. LIMITED"},{"lang":"hk","v":"巨盟達環球商貿代理有限公司"}],"company_since":"1999-01-22","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"665819","names":[{"lang":"en","v":"HALLMART LIMITED (d2011-12-02)"}],"company_since":"1999-01-22","company_dissolved":"2011-12-02","company_type_txt":"Private, ltd by shares"},
{"tax_id":"665646","names":[{"lang":"en","v":"KAM YUEN TOYS MANUFACTORY LIMITED"},{"lang":"hk","v":"金源玩具製品廠有限公司"}],"company_since":"1999-01-22","company_dissolved":"2015-06-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"665697","names":[{"lang":"en","v":"MEGA GROUP LIMITED (d2006-06-02)"},{"lang":"hk","v":"美加集團有限公司"}],"company_since":"1999-01-22","company_dissolved":"2006-06-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"665797","names":[{"lang":"en","v":"KINGSFIELD TRADING LIMITED (d2001-06-01)"},{"lang":"hk","v":"僑豐貿易有限公司"}],"company_since":"1999-01-22","company_dissolved":"2001-06-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"665808","names":[{"lang":"en","v":"GEN TECH PROOFING COMPANY LIMITED"},{"lang":"hk","v":"精觀打稿有限公司"}],"company_since":"1999-01-22","company_dissolved":"2002-07-05","company_type_txt":"Private, ltd by shares"},
{"tax_id":"665722","names":[{"lang":"en","v":"MICRO-CARE 21 ENTERPRISES LIMITED"},{"lang":"hk","v":"康健21企業有限公司"}],"company_since":"1999-01-22","company_dissolved":"2002-10-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"665654","names":[{"lang":"en","v":"GENTEX (HONG KONG) LIMITED"},{"lang":"hk","v":"正德(香港)有限公司"}],"company_since":"1999-01-22","company_dissolved":"2008-09-26","company_type_txt":"Private, ltd by shares"},
{"tax_id":"665639","names":[{"lang":"en","v":"GRAND ASCENT LIMITED (d2001-12-28)"},{"lang":"hk","v":"裕新有限公司"}],"company_since":"1999-01-22","company_dissolved":"2001-12-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"665681","names":[{"lang":"en","v":"MICRO-CARE 21 GLOBAL LIMITED"},{"lang":"hk","v":"康健21環球有限公司"}],"company_since":"1999-01-22","company_dissolved":"2006-06-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"665682","names":[{"lang":"en","v":"MICRO-CARE 21 COMPANY LIMITED"},{"lang":"hk","v":"康健21有限公司"}],"company_since":"1999-01-22","company_dissolved":"2006-06-02","company_type_txt":"Private, ltd by shares"},
{"tax_id":"665721","names":[{"lang":"en","v":"MICRO-CARE 21 WORLDWIDE LIMITED"},{"lang":"hk","v":"康健21萬國有限公司"}],"company_since":"1999-01-22","company_dissolved":"2002-10-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"665631","names":[{"lang":"en","v":"MICRO-CARE 21 INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"康健21國際控股有限公司"}],"company_since":"1999-01-22","company_dissolved":"2006-06-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"665845","names":[{"lang":"en","v":"ME ELECTRONIC PRODUCTS LIMITED"},{"lang":"hk","v":"瑋滔環保產品有限公司"}],"company_since":"1999-01-22","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"665630","names":[{"lang":"en","v":"MICRO-CARE 21 MARKETING LIMITED"},{"lang":"hk","v":"康健21市場策略有限公司"}],"company_since":"1999-01-22","company_dissolved":"2002-06-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"665769","names":[{"lang":"en","v":"MLM INTERNATIONAL LIMITED"}],"company_since":"1999-01-22","company_dissolved":"2005-01-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"665763","names":[{"lang":"en","v":"HENKY DEVELOPMENT LIMITED (d2005-01-28)"},{"lang":"hk","v":"康橋發展有限公司"}],"company_since":"1999-01-22","company_dissolved":"2005-01-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"665817","names":[{"lang":"en","v":"MING GALLERY COMPANY LIMITED"},{"lang":"hk","v":"明成館有限公司"}],"company_since":"1999-01-22","company_dissolved":"2004-12-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"665667","names":[{"lang":"en","v":"MAX CROWN LIMITED (d2000-09-22)"},{"lang":"hk","v":"鴻豐泰有限公司"}],"company_since":"1999-01-22","company_dissolved":"2000-09-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"665805","names":[{"lang":"en","v":"MODERN CITY PROPERTY SERVICES LIMITED"},{"lang":"hk","v":"新城市服務有限公司"}],"company_since":"1999-01-22","company_dissolved":"2016-02-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"665847","names":[{"lang":"en","v":"NEW TALENT DEVELOPMENT LIMITED (d2007-06-01)"},{"lang":"hk","v":"新駿發展有限公司"}],"company_since":"1999-01-22","company_dissolved":"2007-06-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"665675","names":[{"lang":"en","v":"OREGON SCIENTIFIC ASIA PACIFIC LIMITED"},{"lang":"hk","v":"歐西亞(亞太)有限公司"}],"company_since":"1999-01-22","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"665669","names":[{"lang":"en","v":"HONG KONG BESTA ELECTRONIC CO. LIMITED"},{"lang":"hk","v":"香港百事達電子有限公司"}],"company_since":"1999-01-22","company_dissolved":"2005-01-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"665849","names":[{"lang":"en","v":"HONA INTERNATIONAL LIMITED (d2009-06-19)"},{"lang":"hk","v":"凱藝國際有限公司"}],"company_since":"1999-01-22","company_dissolved":"2009-06-19","company_type_txt":"Private, ltd by shares"},
