undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"627682","names":[{"lang":"en","v":"GREAT BOSS INDUSTRIAL LIMITED"},{"lang":"hk","v":"偉漢實業有限公司"}],"company_since":"1997-10-22","company_dissolved":"2018-07-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"627649","names":[{"lang":"en","v":"HANG TAT (CHINA &amp; H.K.) TRANSPORTATION COMPANY LIMITED"},{"lang":"hk","v":"恒達(中港)運輸有限公司"}],"company_since":"1997-10-22","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"627239","names":[{"lang":"en","v":"GRAND BLESS LIMITED"},{"lang":"hk","v":"天詠有限公司"}],"company_since":"1997-10-22","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"627338","names":[{"lang":"en","v":"CHONG YUK TAI HOLDINGS LIMITED"},{"lang":"hk","v":"中昱泰控股有限公司"}],"company_since":"1997-10-22","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"627264","names":[{"lang":"en","v":"KENOX ENTERPRISES LIMITED"},{"lang":"hk","v":"嘉安企業有限公司"}],"company_since":"1997-10-22","company_dissolved":"2005-05-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"627381","names":[{"lang":"en","v":"KENEX INVESTMENTS LIMITED"},{"lang":"hk","v":"嘉欣投資有限公司"}],"company_since":"1997-10-22","company_dissolved":"2008-05-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"627217","names":[{"lang":"en","v":"HAO MEI ALUMINIUM COMPANY LIMITED"},{"lang":"hk","v":"豪美鋁業有限公司"}],"company_since":"1997-10-22","company_dissolved":"2015-09-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"627497","names":[{"lang":"en","v":"KENFORD HOLDINGS LIMITED (d2009-05-26)"},{"lang":"hk","v":"建暉集團有限公司"}],"company_since":"1997-10-22","company_dissolved":"2009-05-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"627243","names":[{"lang":"en","v":"JOINT EFFORT DEVELOPMENT LIMITED"},{"lang":"hk","v":"俊宜發展有限公司"}],"company_since":"1997-10-22","company_dissolved":"2005-10-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"627444","names":[{"lang":"en","v":"KWONG TANG PLUMBING WORKS COMPANY LIMITED"},{"lang":"hk","v":"廣騰水喉潔具渠務工程有限公司"}],"company_since":"1997-10-22","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"627490","names":[{"lang":"en","v":"F &amp; J GALLERY LIMITED"},{"lang":"hk","v":"梵淨藝坊有限公司"}],"company_since":"1997-10-22","company_dissolved":"2012-04-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"627436","names":[{"lang":"en","v":"Hong Kong e-Platform Limited"}],"company_since":"1997-10-22","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"627525","names":[{"lang":"en","v":"JAM LIMITED (d2006-03-24)"}],"company_since":"1997-10-22","company_dissolved":"2006-03-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"627280","names":[{"lang":"en","v":"KELSON ENTERPRISES LIMITED"},{"lang":"hk","v":"建成企業有限公司"}],"company_since":"1997-10-22","company_dissolved":"2007-03-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"627688","names":[{"lang":"en","v":"HOMKO INTERNATIONAL TOBACCO HOLDINGS LIMITED"},{"lang":"hk","v":"鴻高國際煙草集團有限公司"}],"company_since":"1997-10-22","company_dissolved":"2006-03-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"627518","names":[{"lang":"en","v":"LTG AIR ENGINEERING LIMITED"},{"lang":"hk","v":"德國工業冷氣有限公司"}],"company_since":"1997-10-22","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"627319","names":[{"lang":"en","v":"JENWAY DEVELOPMENT LIMITED (d2001-02-09)"},{"lang":"hk","v":"晉威發展有限公司"}],"company_since":"1997-10-22","company_dissolved":"2001-02-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"627318","names":[{"lang":"en","v":"JONEX DEVELOPMENT LIMITED"},{"lang":"hk","v":"俊勝發展有限公司"}],"company_since":"1997-10-22","company_dissolved":"2005-10-07","company_type_txt":"Private, ltd by shares"},
{"tax_id":"627323","names":[{"lang":"en","v":"JENWAY INDUSTRIES LIMITED"},{"lang":"hk","v":"俊滙實業有限公司"}],"company_since":"1997-10-22","company_dissolved":"2009-03-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"627260","names":[{"lang":"en","v":"LUXWELL ENTERPRISES LIMITED"},{"lang":"hk","v":"立偉企業有限公司"}],"company_since":"1997-10-22","company_dissolved":"2002-06-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"627678","names":[{"lang":"en","v":"JETEAST FAR EAST LIMITED"},{"lang":"hk","v":"捷益遠東有限公司"}],"company_since":"1997-10-22","company_dissolved":"2000-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"627366","names":[{"lang":"en","v":"MANFIELD TESTING LABORATORY LIMITED"},{"lang":"hk","v":"萬輝測試實驗室有限公司"}],"company_since":"1997-10-22","company_dissolved":"2003-03-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"627350","names":[{"lang":"en","v":"MAPLE FIELD LIMITED"},{"lang":"hk","v":"青樺有限公司"}],"company_since":"1997-10-22","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"627393","names":[{"lang":"en","v":"LONG HONEST LIMITED"},{"lang":"hk","v":"朗安有限公司"}],"company_since":"1997-10-22","company_dissolved":"2005-10-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"627650","names":[{"lang":"en","v":"JET SIGNAL COMPANY LIMITED (d2003-12-05)"},{"lang":"hk","v":"澤訊有限公司"}],"company_since":"1997-10-22","company_dissolved":"2003-12-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"627613","names":[{"lang":"en","v":"MAXEN TRADING LIMITED"},{"lang":"hk","v":"萬業貿易有限公司"}],"company_since":"1997-10-22","company_dissolved":"2008-08-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"627638","names":[{"lang":"en","v":"JUMBO GRAND INTERNATIONAL LIMITED (d2000-01-22)"},{"lang":"hk","v":"創恒國際有限公司"}],"company_since":"1997-10-22","company_dissolved":"2000-01-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"627503","names":[{"lang":"en","v":"MAXKING TECHNOLOGY LIMITED (d2005-10-14)"},{"lang":"hk","v":"萬基科技有限公司"}],"company_since":"1997-10-22","company_dissolved":"2005-10-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"627656","names":[{"lang":"en","v":"HANG TAT TRANSPORTATION DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"恒達運輸發展有限公司"}],"company_since":"1997-10-22","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"627671","names":[{"lang":"en","v":"MEXON (HONG KONG) LIMITED"},{"lang":"hk","v":"馬頌祈(香港)有限公司"}],"company_since":"1997-10-22","company_dissolved":"2008-12-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"627240","names":[{"lang":"en","v":"GREAT MASCOT LIMITED"},{"lang":"hk","v":"天瑞有限公司"}],"company_since":"1997-10-22","company_dissolved":"2003-06-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"627479","names":[{"lang":"en","v":"KARLSON INVESTMENTS LIMITED"},{"lang":"hk","v":"啟信投資有限公司"}],"company_since":"1997-10-22","company_dissolved":"2003-03-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"627404","names":[{"lang":"en","v":"HONG KONG APACHE FOOTWEAR LIMITED"},{"lang":"hk","v":"香港萬邦鞋業有限公司"}],"company_since":"1997-10-22","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"627315","names":[{"lang":"en","v":"NATON DEVELOPMENT LIMITED"},{"lang":"hk","v":"立信發展有限公司"}],"company_since":"1997-10-22","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"627664","names":[{"lang":"en","v":"KARLWAY INTERNATIONAL LIMITED"},{"lang":"hk","v":"嘉禾國際有限公司"}],"company_since":"1997-10-22","company_dissolved":"2006-03-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"627221","names":[{"lang":"en","v":"HONG KONG DE LAI HOLDINGS LIMITED"},{"lang":"hk","v":"香港德萊集團有限公司"}],"company_since":"1997-10-22","company_dissolved":"2010-09-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"627456","names":[{"lang":"en","v":"NATION MILLION INDUSTRIAL LIMITED"},{"lang":"hk","v":"業萬實業有限公司"}],"company_since":"1997-10-22","company_dissolved":"2006-03-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"627309","names":[{"lang":"en","v":"KARSON ENTERPRISES LIMITED (d2008-03-20)"},{"lang":"hk","v":"啟信企業有限公司"}],"company_since":"1997-10-22","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"627513","names":[{"lang":"en","v":"N Y N DEVELOPMENT LIMITED"},{"lang":"hk","v":"楠潤發展有限公司"}],"company_since":"1997-10-22","company_dissolved":"2005-10-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"627693","names":[{"lang":"en","v":"IWM (HONG KONG) LIMITED"},{"lang":"hk","v":"美淇淋(香港)有限公司"}],"company_since":"1997-10-22","company_dissolved":"2005-10-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"627604","names":[{"lang":"en","v":"GUANGDA NINGTAI (ASIA) COMPANY, LIMITED"},{"lang":"hk","v":"光大寧泰(亞洲)有限公司"}],"company_since":"1997-10-22","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"627416","names":[{"lang":"en","v":"LINKWISE HOLDINGS LIMITED"},{"lang":"hk","v":"滙耀集團有限公司"}],"company_since":"1997-10-22","company_dissolved":"2007-03-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"627691","names":[{"lang":"en","v":"LION WAVE LIMITED (d2002-03-22)"},{"lang":"hk","v":"獅浪有限公司"}],"company_since":"1997-10-22","company_dissolved":"2002-03-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"627558","names":[{"lang":"en","v":"JADIS LIMITED (d2001-05-04)"},{"lang":"hk","v":"龍翠有限公司"}],"company_since":"1997-10-22","company_dissolved":"2001-05-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"627327","names":[{"lang":"en","v":"KENSWICK INVESTMENTS LIMITED (d2003-01-24)"},{"lang":"hk","v":"建榮投資有限公司"}],"company_since":"1997-10-22","company_dissolved":"2003-01-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"627538","names":[{"lang":"en","v":"JETGOOD WHETSTONE LIMITED"},{"lang":"hk","v":"捷豪思通有限公司"}],"company_since":"1997-10-22","company_dissolved":"2001-10-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"627541","names":[{"lang":"en","v":"QUITO TECHNOLOGY CO. LIMITED"},{"lang":"hk","v":"基多科技有限公司"}],"company_since":"1997-10-22","company_dissolved":"2002-03-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"627676","names":[{"lang":"en","v":"LIGHTHOUSE DEVELOPMENT LIMITED"},{"lang":"hk","v":"堅亮發展有限公司"}],"company_since":"1997-10-22","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"627365","names":[{"lang":"en","v":"RICH STAR GARMENTS LIMITED"},{"lang":"hk","v":"裕星製衣有限公司"}],"company_since":"1997-10-22","company_dissolved":"2004-04-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"627454","names":[{"lang":"en","v":"KINGSMEN (NORTH ASIA) LIMITED"},{"lang":"hk","v":"金明(北亞)有限公司"}],"company_since":"1997-10-22","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"627225","names":[{"lang":"en","v":"SUPERFLAG PRINTING AND COMMUNICATION LIMITED"},{"lang":"hk","v":"超企印刷及傳訊有限公司"}],"company_since":"1997-10-22","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"627455","names":[{"lang":"en","v":"Sunlink mSolutions Limited"},{"lang":"hk","v":"科浪移動有限公司"}],"company_since":"1997-10-22","company_dissolved":"2018-06-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"627628","names":[{"lang":"en","v":"SMEP LIMITED"}],"company_since":"1997-10-22","company_dissolved":"2003-06-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"627376","names":[{"lang":"en","v":"SUNFAITH INTERNATIONAL LIMITED"},{"lang":"hk","v":"日誠國際有限公司"}],"company_since":"1997-10-22","company_dissolved":"2005-10-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"627329","names":[{"lang":"en","v":"WORLDKY INVESTMENTS LIMITED"},{"lang":"hk","v":"滙基投資有限公司"}],"company_since":"1997-10-22","company_dissolved":"2002-05-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"627391","names":[{"lang":"en","v":"SURE BEST HOLDINGS LIMITED (d2005-10-07)"},{"lang":"hk","v":"超盛集團有限公司"}],"company_since":"1997-10-22","company_dissolved":"2005-10-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"627352","names":[{"lang":"en","v":"WORLD SALES LIMITED (d2002-10-11)"},{"lang":"hk","v":"韋潤有限公司"}],"company_since":"1997-10-22","company_dissolved":"2002-10-11","company_type_txt":"Private, ltd by shares"},
{"tax_id":"627232","names":[{"lang":"en","v":"T &amp; G INVESTMENTS LIMITED (d2005-10-07)"},{"lang":"hk","v":"天正投資有限公司"}],"company_since":"1997-10-22","company_dissolved":"2005-10-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
