{"tax_id":"687954","names":[{"lang":"en","v":"CITIRICH (H.K.) LIMITED"},{"lang":"hk","v":"冠盈(香港)有限公司"}],"company_since":"1999-09-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"688020","names":[{"lang":"en","v":"CLUB DE LOTTO LIMITED"},{"lang":"hk","v":"樂都會有限公司"}],"company_since":"1999-09-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"688096","names":[{"lang":"en","v":"CONCORD CITIES LIMITED"},{"lang":"hk","v":"太城有限公司"}],"company_since":"1999-09-10","company_dissolved":"2018-04-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"688079","names":[{"lang":"en","v":"CONCORD DEVELOPMENT LIMITED"},{"lang":"hk","v":"裕豐發展有限公司"}],"company_since":"1999-09-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"688028","names":[{"lang":"en","v":"CONDAX INDUSTRIAL LIMITED"},{"lang":"hk","v":"港德實業有限公司"}],"company_since":"1999-09-10","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"688185","names":[{"lang":"en","v":"CoolLite International Holdings Limited"},{"lang":"hk","v":"科耐照明國際控股有限公司"}],"company_since":"1999-09-10","company_dissolved":"2018-05-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"688146","names":[{"lang":"en","v":"COTTONFIELD TEXTILE HONG KONG LIMITED"}],"company_since":"1999-09-10","company_dissolved":"2010-02-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"688106","names":[{"lang":"en","v":"DENBY COMPANY LIMITED"},{"lang":"hk","v":"丹比有限公司"}],"company_since":"1999-09-10","company_dissolved":"2009-04-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"688164","names":[{"lang":"en","v":"E-SMART LIMITED"},{"lang":"hk","v":"誌聰有限公司"}],"company_since":"1999-09-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"688067","names":[{"lang":"en","v":"EDWARD TECHNOLOGY LIMITED"},{"lang":"hk","v":"雅華科技有限公司"}],"company_since":"1999-09-10","company_dissolved":"2006-03-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"687987","names":[{"lang":"en","v":"ELECTRA APPLIANCES MANUFACTURING LIMITED"}],"company_since":"1999-09-10","company_dissolved":"2002-07-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"688119","names":[{"lang":"en","v":"EVER NICE TECHNOLOGY LIMITED (d2003-02-21)"},{"lang":"hk","v":"永進科技有限公司"}],"company_since":"1999-09-10","company_dissolved":"2003-02-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"687969","names":[{"lang":"en","v":"FAMOUS WINNER HOLDINGS LIMITED"},{"lang":"hk","v":"確威集團有限公司"}],"company_since":"1999-09-10","company_dissolved":"2012-12-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"688187","names":[{"lang":"en","v":"FINANCEASIA.COM LIMITED"}],"company_since":"1999-09-10","company_dissolved":"2011-12-16","company_type_txt":"Private, ltd by shares"},
{"tax_id":"687973","names":[{"lang":"en","v":"FIRST HARVEST INVESTMENT LIMITED"},{"lang":"hk","v":"辰豐投資有限公司"}],"company_since":"1999-09-10","company_dissolved":"2010-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"688109","names":[{"lang":"en","v":"GALAXY SHIPPING LIMITED (d2004-09-15)"},{"lang":"hk","v":"天洋船務有限公司"}],"company_since":"1999-09-10","company_dissolved":"2004-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"688083","names":[{"lang":"en","v":"GLOBAL SUCCESS TRADING LIMITED"},{"lang":"hk","v":"昇豐貿易有限公司"}],"company_since":"1999-09-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"688138","names":[{"lang":"en","v":"CLIMAX TRADING LIMITED (d2006-03-03)"},{"lang":"hk","v":"永毅貿易有限公司"}],"company_since":"1999-09-10","company_dissolved":"2006-03-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"687961","names":[{"lang":"en","v":"GOLD LUCKY HOLDINGS LIMITED (d2006-03-03)"},{"lang":"hk","v":"金富順集團有限公司"}],"company_since":"1999-09-10","company_dissolved":"2006-03-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"688122","names":[{"lang":"en","v":"GOLD TREASURE INTERNATIONAL JEWELLERY COMPANY LIMITED"},{"lang":"hk","v":"金寶國際珠寶有限公司"}],"company_since":"1999-09-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"688118","names":[{"lang":"en","v":"GOLDEN EAST TECHNOLOGY LIMITED"},{"lang":"hk","v":"金億科技有限公司"}],"company_since":"1999-09-10","company_dissolved":"2007-03-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"687981","names":[{"lang":"en","v":"COMSYS LIMITED (d2011-05-20)"}],"company_since":"1999-09-10","company_dissolved":"2011-05-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"688163","names":[{"lang":"en","v":"GOOD HEALTH PRODUCTS (H.K.) LIMITED"},{"lang":"hk","v":"好健康產品(香港)有限公司"}],"company_since":"1999-09-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"688006","names":[{"lang":"en","v":"GRANDABLE LIMITED"},{"lang":"hk","v":"鈞浩有限公司"}],"company_since":"1999-09-10","company_dissolved":"2006-03-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"688162","names":[{"lang":"en","v":"GREAT TIME HOLDINGS LIMITED"},{"lang":"hk","v":"順時集團有限公司"}],"company_since":"1999-09-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"687948","names":[{"lang":"en","v":"DIRECT SALES MARKETING DEVELOPMENT CO., LIMITED"},{"lang":"hk","v":"網戶直銷發展有限公司"}],"company_since":"1999-09-10","company_dissolved":"2006-03-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"688123","names":[{"lang":"en","v":"GREENWOOD (H.K.) LIMITED"},{"lang":"hk","v":"青木(香港)有限公司"}],"company_since":"1999-09-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"688045","names":[{"lang":"en","v":"HAUS COMMUNICATIONS LIMITED"}],"company_since":"1999-09-10","company_dissolved":"2005-08-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"688074","names":[{"lang":"en","v":"HO KING CATERING COMPANY LIMITED"},{"lang":"hk","v":"好景飲食有限公司"}],"company_since":"1999-09-10","company_dissolved":"2006-03-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"688043","names":[{"lang":"en","v":"E-COMMERCE INVESTMENT LIMITED"}],"company_since":"1999-09-10","company_dissolved":"2007-01-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"688056","names":[{"lang":"en","v":"HONG KONG CYBERTECHNIC PROPERTY SERVICES LIMITED"},{"lang":"hk","v":"香港數碼商貿物業服務有限公司"}],"company_since":"1999-09-10","company_dissolved":"2004-12-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"688085","names":[{"lang":"en","v":"HONG KONG NETCOM LIMITED"},{"lang":"hk","v":"香港綱訊有限公司"}],"company_since":"1999-09-10","company_dissolved":"2005-04-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"687996","names":[{"lang":"en","v":"EMART ENTERPRISE LIMITED"}],"company_since":"1999-09-10","company_dissolved":"2002-08-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"688051","names":[{"lang":"en","v":"EXCEL SKY TECHNOLOGY LIMITED"},{"lang":"hk","v":"卓天科技有限公司"}],"company_since":"1999-09-10","company_dissolved":"2006-03-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"687949","names":[{"lang":"en","v":"EXPRESS (AIR CARGO) TRANSPORTATION LIMITED"},{"lang":"hk","v":"信達運輸有限公司"}],"company_since":"1999-09-10","company_dissolved":"2002-02-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"688183","names":[{"lang":"en","v":"HYSAN TRADING MEDICINE LIMITED"},{"lang":"hk","v":"海山行藥業有限公司"}],"company_since":"1999-09-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"688075","names":[{"lang":"en","v":"FENG SHII INDUSTRIAL CO. LIMITED"},{"lang":"hk","v":"豐璽工業有限公司"}],"company_since":"1999-09-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"688167","names":[{"lang":"en","v":"IRLAM LIMITED (d2010-02-05)"}],"company_since":"1999-09-10","company_dissolved":"2010-02-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"688031","names":[{"lang":"en","v":"FOREVER VICTORY INTERNATIONAL LIMITED"},{"lang":"hk","v":"皓暉國際有限公司"}],"company_since":"1999-09-10","company_dissolved":"2010-02-05","company_type_txt":"Private, ltd by shares"},
{"tax_id":"688037","names":[{"lang":"en","v":"JOYVIEW LIMITED (d2005-07-29)"}],"company_since":"1999-09-10","company_dissolved":"2005-07-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"688025","names":[{"lang":"en","v":"KA LOK FOOK (FOOD) COMPANY LIMITED"},{"lang":"hk","v":"家樂福(食品)有限公司"}],"company_since":"1999-09-10","company_dissolved":"2003-07-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"687983","names":[{"lang":"en","v":"KINGSWAY INFORMATION NETWORK LIMITED"},{"lang":"hk","v":"滙富資訊網絡有限公司"}],"company_since":"1999-09-10","company_dissolved":"2004-02-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"687970","names":[{"lang":"en","v":"GENERAL RICH LIMITED (d2007-08-17)"},{"lang":"hk","v":"順均有限公司"}],"company_since":"1999-09-10","company_dissolved":"2007-08-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"688117","names":[{"lang":"en","v":"GLOBAL ACCESS FINANCE LIMITED"},{"lang":"hk","v":"華浩財務有限公司"}],"company_since":"1999-09-10","company_dissolved":"2005-06-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"688131","names":[{"lang":"en","v":"L.A. CONSULTING AND TRADING LIMITED"}],"company_since":"1999-09-10","company_dissolved":"2005-04-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"688068","names":[{"lang":"en","v":"KWONG HING WEAVING DYEING &amp; PRINTING FTY. LIMITED"},{"lang":"hk","v":"廣興紡織印染廠有限公司"}],"company_since":"1999-09-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"687992","names":[{"lang":"en","v":"LASSCO INTERNATIONAL LIMITED"}],"company_since":"1999-09-10","company_dissolved":"2006-03-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"688078","names":[{"lang":"en","v":"LEGEND INDUSTRIES LIMITED (d2002-12-13)"},{"lang":"hk","v":"利駿實業有限公司"}],"company_since":"1999-09-10","company_dissolved":"2002-12-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"687974","names":[{"lang":"en","v":"LOYAL BEST INVESTMENT LIMITED (d2007-01-19)"},{"lang":"hk","v":"忠邦投資有限公司"}],"company_since":"1999-09-10","company_dissolved":"2007-01-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"688152","names":[{"lang":"en","v":"NANLI (HONG KONG) INTERNATIONAL ENGINEERING LIMITED"},{"lang":"hk","v":"南利(香港)國際工程有限公司"}],"company_since":"1999-09-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"688180","names":[{"lang":"en","v":"NIKKON ENGINEERING AND CONSULTANTS LIMITED"},{"lang":"hk","v":"永毅工程及顧問有限公司"}],"company_since":"1999-09-10","company_dissolved":"2017-08-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"688133","names":[{"lang":"en","v":"ORIENT LOGISTICS LIMITED (d2001-01-12)"},{"lang":"hk","v":"東捷貨運有限公司"}],"company_since":"1999-09-10","company_dissolved":"2001-01-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"688073","names":[{"lang":"en","v":"HONG KONG JEDY HOLDINGS LIMITED"},{"lang":"hk","v":"香港剪帝集團有限公司"}],"company_since":"1999-09-10","company_dissolved":"2006-03-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"687947","names":[{"lang":"en","v":"PAULOWNIA RESEARCH &amp; DEVELOPMENT COMPANY OF CHINA LIMITED"},{"lang":"hk","v":"中國泡桐科研開展有限公司"}],"company_since":"1999-09-10","company_dissolved":"2008-01-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"688114","names":[{"lang":"en","v":"HONG KONG SATE (COSTUME) INT'L HOLDINGS LIMITED"},{"lang":"hk","v":"香港颯特(服飾)國際集團有限公司"}],"company_since":"1999-09-10","company_dissolved":"2006-03-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"688070","names":[{"lang":"en","v":"PROGRAMTECH LIMITED (d2011-04-01)"}],"company_since":"1999-09-10","company_dissolved":"2011-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"688033","names":[{"lang":"en","v":"Q-TECH CORP. (HK) LIMITED"},{"lang":"hk","v":"量子科技(香港)有限公司"}],"company_since":"1999-09-10","company_dissolved":"2001-02-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"688143","names":[{"lang":"en","v":"I.PIC HONGKONG LIMITED"}],"company_since":"1999-09-10","company_dissolved":"2013-12-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"688182","names":[{"lang":"en","v":"MAXNER (H.K.) ENTERPRISE CO. LIMITED"}],"company_since":"1999-09-10","company_dissolved":"2009-01-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"688026","names":[{"lang":"en","v":"RED FIRE DOT INTERNATIONAL GOURMET LIMITED"},{"lang":"hk","v":"紅火點國際美食有限公司"}],"company_since":"1999-09-10","company_dissolved":"2006-08-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"688076","names":[{"lang":"en","v":"INTERNET TECHNOLOGIES GROUP (HK) LIMITED"}],"company_since":"1999-09-10","company_dissolved":"2003-09-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"688094","names":[{"lang":"en","v":"SESAME &amp; BEANS COMPANY LIMITED"},{"lang":"hk","v":"芝蔴綠豆甜品屋有限公司"}],"company_since":"1999-09-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"688059","names":[{"lang":"en","v":"MATCH-MAKER LIMITED"},{"lang":"hk","v":"同制工作室有限公司"}],"company_since":"1999-09-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"688157","names":[{"lang":"en","v":"SUNEVISION IHON LIMITED"}],"company_since":"1999-09-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"688184","names":[{"lang":"en","v":"TEAMBEST MANUFACTURING CO., LIMITED"},{"lang":"hk","v":"添佳製衣織造有限公司"}],"company_since":"1999-09-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"688044","names":[{"lang":"en","v":"TEDDER CHAIN &amp; HEAVY EQUIPMENT CO. LIMITED"},{"lang":"hk","v":"高欣鏈條重機有限公司"}],"company_since":"1999-09-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"688134","names":[{"lang":"en","v":"TOP STAR GROUP LIMITED (d2018-08-17)"},{"lang":"hk","v":"盈發集團有限公司"}],"company_since":"1999-09-10","company_dissolved":"2018-08-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"688011","names":[{"lang":"en","v":"PO SHAN ELECTRONIC COMPANY LIMITED"},{"lang":"hk","v":"寶山電子製品有限公司"}],"company_since":"1999-09-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"688048","names":[{"lang":"en","v":"TREASURE DESIGN &amp; CONTRACTING LIMITED"},{"lang":"hk","v":"焯越建造工程有限公司"}],"company_since":"1999-09-10","company_dissolved":"2004-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"687979","names":[{"lang":"en","v":"ROYAL FAITH FAR EAST LIMITED"},{"lang":"hk","v":"兆暉遠東有限公司"}],"company_since":"1999-09-10","company_dissolved":"2004-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"687978","names":[{"lang":"en","v":"WEBLINK INTERNATIONAL LIMITED (d2006-03-03)"},{"lang":"hk","v":"聯添國際有限公司"}],"company_since":"1999-09-10","company_dissolved":"2006-03-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"687980","names":[{"lang":"en","v":"SINO INSURE LIMITED"},{"lang":"hk","v":"中保網有限公司"}],"company_since":"1999-09-10","company_dissolved":"2005-03-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"688023","names":[{"lang":"en","v":"WINSOME (MANUFACTURER) CO. LIMITED"},{"lang":"hk","v":"虹裳有限公司"}],"company_since":"1999-09-10","company_dissolved":"2016-01-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"688018","names":[{"lang":"en","v":"SUMBER COMPANY LIMITED"}],"company_since":"1999-09-10","company_dissolved":"2019-08-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"688158","names":[{"lang":"en","v":"SUNEVISION SUPER E-NETWORK LIMITED"}],"company_since":"1999-09-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"688089","names":[{"lang":"en","v":"TOPEARN LIMITED (d2006-03-03)"},{"lang":"hk","v":"禾利有限公司"}],"company_since":"1999-09-10","company_dissolved":"2006-03-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"688053","names":[{"lang":"en","v":"TSZ HAU HOME OF AGED LIMITED (d2002-05-17)"},{"lang":"hk","v":"慈孝安老院有限公司"}],"company_since":"1999-09-10","company_dissolved":"2002-05-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"688178","names":[{"lang":"en","v":"VICTORIA TOWN LIMITED"},{"lang":"hk","v":"維鎮有限公司"}],"company_since":"1999-09-10","company_dissolved":"2006-03-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"688062","names":[{"lang":"en","v":"VISTA JEWELRY LIMITED"},{"lang":"hk","v":"顯琛珠寶有限公司"}],"company_since":"1999-09-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"687959","names":[{"lang":"en","v":"WALL INTERNATIONAL ASIA LIMITED (d2003-01-03)"},{"lang":"hk","v":"華爾國際亞洲有限公司"}],"company_since":"1999-09-10","company_dissolved":"2003-01-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"688019","names":[{"lang":"en","v":"WELLDONE INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"匯華國際股份有限公司"}],"company_since":"1999-09-10","company_dissolved":"2008-01-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"688065","names":[{"lang":"en","v":"WELLWAY ENGINEERING LIMITED (d2008-11-08)"},{"lang":"hk","v":"富利華工程有限公司"}],"company_since":"1999-09-10","company_dissolved":"2008-11-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"687964","names":[{"lang":"en","v":"WELSLEY HOLDINGS LIMITED"},{"lang":"hk","v":"韋利集團有限公司"}],"company_since":"1999-09-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"688066","names":[{"lang":"en","v":"WIDELINK TECHNOLOGY LIMITED"},{"lang":"hk","v":"華聯科技有限公司"}],"company_since":"1999-09-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"688150","names":[{"lang":"en","v":"PO HING CONSULTANCY LIMITED"},{"lang":"hk","v":"寶興顧問有限公司"}],"company_since":"1999-09-10","company_dissolved":"2011-12-16","company_type_txt":"Private, ltd by shares"},
{"tax_id":"687999","names":[{"lang":"en","v":"INSTITUT ESTHETIQUE DE SUISSE LIMITED"},{"lang":"hk","v":"儀特絲專業美容有限公司"}],"company_since":"1999-09-10","company_dissolved":"2007-01-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"688091","names":[{"lang":"en","v":"UNION STATE LIMITED"},{"lang":"hk","v":"聯盛有限公司"}],"company_since":"1999-09-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
