undefined,
{"tax_id":"689619","names":[{"lang":"en","v":"CYBERMIND TECHNOLOGY LIMITED"},{"lang":"hk","v":"智聯網科技有限公司"}],"company_since":"1999-09-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"689607","names":[{"lang":"en","v":"E-BAG DESIGN ASIA LIMITED"}],"company_since":"1999-09-27","company_dissolved":"2002-03-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"689633","names":[{"lang":"en","v":"EASTMOUNT PROPERTY AGENCY LIMITED"},{"lang":"hk","v":"東豪地產代理有限公司"}],"company_since":"1999-09-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"689661","names":[{"lang":"en","v":"EVER SMART CONSTRUCTION ENGINEERING LIMITED"},{"lang":"hk","v":"永明建築工程有限公司"}],"company_since":"1999-09-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"689696","names":[{"lang":"en","v":"GB21 (HONG KONG) LIMITED"}],"company_since":"1999-09-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"689687","names":[{"lang":"en","v":"GRANDMART INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"萬宏國際投資有限公司"}],"company_since":"1999-09-27","company_dissolved":"2006-03-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"689685","names":[{"lang":"en","v":"ETERNAL INTERNATIONAL DEVELOPMENT LIMITED (d2006-03-10)"},{"lang":"hk","v":"恒光國際發展有限公司"}],"company_since":"1999-09-27","company_dissolved":"2006-03-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"689618","names":[{"lang":"en","v":"CON PAK INTERNATIONAL CO., LIMITED"},{"lang":"hk","v":"康百國際有限公司"}],"company_since":"1999-09-27","company_dissolved":"2003-11-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"689585","names":[{"lang":"en","v":"ENERGYLINK LIMITED (HK)"}],"company_since":"1999-09-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"689657","names":[{"lang":"en","v":"EXPLORER ENTERPRISE LIMITED"},{"lang":"hk","v":"敖士實業有限公司"}],"company_since":"1999-09-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"689625","names":[{"lang":"en","v":"FAMMED GROUP LIMITED"}],"company_since":"1999-09-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"689638","names":[{"lang":"en","v":"MICRONET LIMITED (d2006-02-03)"},{"lang":"hk","v":"微網科技有限公司"}],"company_since":"1999-09-27","company_dissolved":"2006-02-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"689591","names":[{"lang":"en","v":"GLORY HARVEST DESIGN AND ENGINEERING LIMITED (d2004-01-21)"},{"lang":"hk","v":"旭豐工程有限公司"}],"company_since":"1999-09-27","company_dissolved":"2004-01-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"689692","names":[{"lang":"en","v":"NGAI YIP STEEL WORK ENGINEERING LIMITED"},{"lang":"hk","v":"毅業鋼鐵工程有限公司"}],"company_since":"1999-09-27","company_dissolved":"2000-11-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"689599","names":[{"lang":"en","v":"PRIME ASIA PETROLEUM AND CHEMICALS LIMITED"},{"lang":"hk","v":"泛亞石油化工有限公司"}],"company_since":"1999-09-27","company_dissolved":"2006-03-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"689663","names":[{"lang":"en","v":"GREAT RISE CONSTRUCTION ENGINEERING LIMITED (d2003-08-29)"},{"lang":"hk","v":"鍵泰建築工程有限公司"}],"company_since":"1999-09-27","company_dissolved":"2003-08-29","company_type_txt":"Private, ltd by shares"},
{"tax_id":"689655","names":[{"lang":"en","v":"PROFIT MOTORS COMPANY LIMITED"},{"lang":"hk","v":"盈匯汽車有限公司"}],"company_since":"1999-09-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"689683","names":[{"lang":"en","v":"GPI CLUB LIMITED"},{"lang":"hk","v":"皇寶會有限公司"}],"company_since":"1999-09-27","company_dissolved":"2006-03-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"689658","names":[{"lang":"en","v":"HISTRONG INFO COMPANY LIMITED"},{"lang":"hk","v":"香港航創科技有限公司"}],"company_since":"1999-09-27","company_dissolved":"2004-04-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"689688","names":[{"lang":"en","v":"HONDA YOKO LIMITED"},{"lang":"hk","v":"本多洋行有限公司"}],"company_since":"1999-09-27","company_dissolved":"2006-03-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"689642","names":[{"lang":"en","v":"HONG KONG INTERNATIONAL BIO-HERB DEVELOPMENT LIMITED"},{"lang":"hk","v":"香港國際生化發展有限公司"}],"company_since":"1999-09-27","company_dissolved":"2006-03-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"689636","names":[{"lang":"en","v":"SHUN ON (CHINA HK) CARGO SERVICES LIMITED"},{"lang":"hk","v":"順安(中港)貨運有限公司"}],"company_since":"1999-09-27","company_dissolved":"2002-11-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"689665","names":[{"lang":"en","v":"SKYLINE CONSTRUCTION ENGINEERING LIMITED"},{"lang":"hk","v":"天駿建築工程有限公司"}],"company_since":"1999-09-27","company_dissolved":"2008-12-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"689617","names":[{"lang":"en","v":"HONG YI INVESTMENT (HK) LIMITED"},{"lang":"hk","v":"洪藝投資(香港)有限公司"}],"company_since":"1999-09-27","company_dissolved":"2012-06-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"689690","names":[{"lang":"en","v":"SKYMART INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"天駿國際發展有限公司"}],"company_since":"1999-09-27","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"689664","names":[{"lang":"en","v":"KA SHUN CONSTRUCTION ENGINEERING LIMITED"},{"lang":"hk","v":"嘉信建築工程有限公司"}],"company_since":"1999-09-27","company_dissolved":"2000-10-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"689605","names":[{"lang":"en","v":"TEXCON FAR EAST LIMITED"}],"company_since":"1999-09-27","company_dissolved":"2016-08-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"689613","names":[{"lang":"en","v":"KWOK CHEONG HONG ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"國昌行工程有限公司"}],"company_since":"1999-09-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"689624","names":[{"lang":"en","v":"LEE MAN FINANCE LIMITED"},{"lang":"hk","v":"利民財務有限公司"}],"company_since":"1999-09-27","company_dissolved":"2010-05-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"689606","names":[{"lang":"en","v":"MAXDO HOTEL MANAGEMENT COMPANY LIMITED"},{"lang":"hk","v":"萬都酒店管理有限公司"}],"company_since":"1999-09-27","company_dissolved":"2001-11-23","company_type_txt":"Private, ltd by shares"},
{"tax_id":"689600","names":[{"lang":"en","v":"WELL HOST INVESTMENT LIMITED"},{"lang":"hk","v":"旺浩投資有限公司"}],"company_since":"1999-09-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"689597","names":[{"lang":"en","v":"WINNER CASTLE LIMITED"},{"lang":"hk","v":"永利發有限公司"}],"company_since":"1999-09-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"689630","names":[{"lang":"en","v":"DANIEL TONG CHARTERED ARCHITECT &amp; ASSOCIATES LIMITED"},{"lang":"hk","v":"唐建康建築師有限公司"}],"company_since":"1999-09-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"689678","names":[{"lang":"en","v":"XITI LIMITED"}],"company_since":"1999-09-27","company_dissolved":"2003-02-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"689676","names":[{"lang":"en","v":"NGAN SING AIR-CONDITIONING ENGINEERING &amp; TRADING LIMITED"},{"lang":"hk","v":"銀星冷氣工程貿易有限公司"}],"company_since":"1999-09-27","company_dissolved":"2002-11-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"689578","names":[{"lang":"en","v":"XIN HUA WORLDWIDE INDUSTRIAL INVESTMENT LIMITED"},{"lang":"hk","v":"新華國際實業投資有限公司"}],"company_since":"1999-09-27","company_dissolved":"2002-01-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"689673","names":[{"lang":"en","v":"GOLDRICH INDUSTRIAL (HONG KONG) CO. LIMITED"},{"lang":"hk","v":"益豐實業(香港)有限公司"}],"company_since":"1999-09-27","company_dissolved":"2012-08-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"689596","names":[{"lang":"en","v":"PRIME WEALTHY LIMITED"},{"lang":"hk","v":"世錦有限公司"}],"company_since":"1999-09-27","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
