{"tax_id":"720124","names":[{"lang":"en","v":"CHINA PDA LIMITED"}],"company_since":"2000-06-12","company_dissolved":"2002-11-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"719922","names":[{"lang":"en","v":"CHINA VISION INTERNATIONAL LIMITED (d2006-01-20)"},{"lang":"hk","v":"捷穎國際有限公司"}],"company_since":"2000-06-12","company_dissolved":"2006-01-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720086","names":[{"lang":"en","v":"CHINA WESTERN INTERNATIONAL INVESTMENT HOLDINGS LIMITED"},{"lang":"hk","v":"中國西部國際投資集團有限公司"}],"company_since":"2000-06-12","company_dissolved":"2005-06-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"720056","names":[{"lang":"en","v":"CHUN WO CONSTRUCTION (TAIWAN) LIMITED"},{"lang":"hk","v":"俊和建築(台灣)有限公司"}],"company_since":"2000-06-12","company_dissolved":"2016-04-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"719917","names":[{"lang":"en","v":"CONNEX INTERNATIONAL LIMITED (d2007-10-26)"},{"lang":"hk","v":"高賢國際有限公司"}],"company_since":"2000-06-12","company_dissolved":"2007-10-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720109","names":[{"lang":"en","v":"CORDLIFE (HONG KONG) LIMITED"},{"lang":"hk","v":"康盛人生(香港)有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"719980","names":[{"lang":"en","v":"DIGITAL CHANNEL PARTNERS (HK) LIMITED"}],"company_since":"2000-06-12","company_dissolved":"2006-01-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720129","names":[{"lang":"en","v":"DTZ E-VALUATION COMPANY LIMITED"},{"lang":"hk","v":"易估價有限公司"}],"company_since":"2000-06-12","company_dissolved":"2011-01-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720125","names":[{"lang":"en","v":"E-QARS LIMITED"}],"company_since":"2000-06-12","company_dissolved":"2010-01-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"719940","names":[{"lang":"en","v":"CHINA EASE LIMITED (d2005-07-22)"},{"lang":"hk","v":"達意有限公司"}],"company_since":"2000-06-12","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"719985","names":[{"lang":"en","v":"EAST GLORY ASIA LIMITED"},{"lang":"hk","v":"東捷亞洲有限公司"}],"company_since":"2000-06-12","company_dissolved":"2000-12-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720025","names":[{"lang":"en","v":"EAST TEAM INTERNATIONAL DEVELOPMENT (NOMINEE) LIMITED"},{"lang":"hk","v":"東盟國際發展(代理人)有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"719928","names":[{"lang":"en","v":"EASTLAND (HONG KONG) LIMITED"},{"lang":"hk","v":"億利(香港)有限公司"}],"company_since":"2000-06-12","company_dissolved":"2009-11-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"719964","names":[{"lang":"en","v":"EASY MING COMPANY LIMITED"},{"lang":"hk","v":"依士明有限公司"}],"company_since":"2000-06-12","company_dissolved":"2005-06-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720018","names":[{"lang":"en","v":"CHINA RAILWAY ENGINEERING (HONG KONG) LIMITED"},{"lang":"hk","v":"中國鐵路工程(香港)有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720006","names":[{"lang":"en","v":"EC PRINTING LIMITED"},{"lang":"hk","v":"永輝快印有限公司"}],"company_since":"2000-06-12","company_dissolved":"2002-12-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720069","names":[{"lang":"en","v":"ECOAT ELECTROPLATING FINISHING CO. LIMITED"},{"lang":"hk","v":"伊高特表面處理有限公司"}],"company_since":"2000-06-12","company_dissolved":"2012-06-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720082","names":[{"lang":"en","v":"CHINA VISTA LIMITED"},{"lang":"hk","v":"中煌有限公司"}],"company_since":"2000-06-12","company_dissolved":"2005-06-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"720027","names":[{"lang":"en","v":"EVERWELL INTERNATIONAL ENTERPRISE LIMITED"},{"lang":"hk","v":"裕永國際企業有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720011","names":[{"lang":"en","v":"FAME GLORY ASIA LIMITED"},{"lang":"hk","v":"溢興亞洲有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"719913","names":[{"lang":"en","v":"FERREX HOLDING LIMITED"},{"lang":"hk","v":"科力控股有限公司"}],"company_since":"2000-06-12","company_dissolved":"2007-10-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720080","names":[{"lang":"en","v":"FINE WEB TECHNOLOGY LIMITED"},{"lang":"hk","v":"鋒威科技有限公司"}],"company_since":"2000-06-12","company_dissolved":"2003-04-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720130","names":[{"lang":"en","v":"CITYETAIL.COM LIMITED"}],"company_since":"2000-06-12","company_dissolved":"2003-08-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"719945","names":[{"lang":"en","v":"FLAMING GARMENT LIMITED"},{"lang":"hk","v":"禧昇製衣有限公司"}],"company_since":"2000-06-12","company_dissolved":"2002-08-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"719981","names":[{"lang":"en","v":"CHINA CAPITAL GROUP LIMITED (d2006-10-20)"}],"company_since":"2000-06-12","company_dissolved":"2006-10-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720034","names":[{"lang":"en","v":"COMSTRA LIMITED"}],"company_since":"2000-06-12","company_dissolved":"2006-01-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720028","names":[{"lang":"en","v":"FULL WIN INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"豐勝國際發展有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"719906","names":[{"lang":"en","v":"FUNG YUE TAT (H.K.) LIMITED"},{"lang":"hk","v":"豐裕達(香港)有限公司"}],"company_since":"2000-06-12","company_dissolved":"2005-11-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720020","names":[{"lang":"en","v":"FUTURE PARTNERS HONG KONG CO., LIMITED"},{"lang":"hk","v":"未來協力香港投資有限公司"}],"company_since":"2000-06-12","company_dissolved":"2008-11-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720062","names":[{"lang":"en","v":"G-LOK MOTORS LIMITED"},{"lang":"hk","v":"知樂汽車有限公司"}],"company_since":"2000-06-12","company_dissolved":"2002-08-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"719915","names":[{"lang":"en","v":"GIANT CITY HOLDINGS LIMITED"},{"lang":"hk","v":"鉅城集團有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720012","names":[{"lang":"en","v":"GOLD HARVEST ASIA LIMITED"},{"lang":"hk","v":"金多亞洲有限公司"}],"company_since":"2000-06-12","company_dissolved":"2012-09-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"719946","names":[{"lang":"en","v":"EASY TECHNOLOGY (HK) LIMITED (d2012-06-29)"},{"lang":"hk","v":"億時科技有限公司"}],"company_since":"2000-06-12","company_dissolved":"2012-06-29","company_type_txt":"Private, ltd by shares"},
{"tax_id":"720030","names":[{"lang":"en","v":"GOOD CENTURY INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"紀聯國際發展有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"719907","names":[{"lang":"en","v":"FAST EV INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"發思特電動車國際有限公司"}],"company_since":"2000-06-12","company_dissolved":"2007-10-26","company_type_txt":"Private, ltd by shares"},
{"tax_id":"720031","names":[{"lang":"en","v":"GOODFAIR INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"益通國際投資有限公司"}],"company_since":"2000-06-12","company_dissolved":"2007-01-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720013","names":[{"lang":"en","v":"GOODPINE ASIA LIMITED"},{"lang":"hk","v":"富柏亞洲有限公司"}],"company_since":"2000-06-12","company_dissolved":"2007-10-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720042","names":[{"lang":"en","v":"Great Unicorn Printing Co. Limited"},{"lang":"hk","v":"偉麟印刷有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"719986","names":[{"lang":"en","v":"FORTUNE BRIGHT ASIA LIMITED"},{"lang":"hk","v":"裕耀亞洲有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"719966","names":[{"lang":"en","v":"HANG FUNG PIPES (INTERNATIONAL) COMPANY LIMITED"},{"lang":"hk","v":"恆豐喉業(國際)有限公司"}],"company_since":"2000-06-12","company_dissolved":"2016-02-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"719948","names":[{"lang":"en","v":"HANG CHEONG PLASTIC &amp; METAL MANUFACTORY LIMITED"},{"lang":"hk","v":"恒昌塑膠五金製品廠有限公司"}],"company_since":"2000-06-12","company_dissolved":"2012-08-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720068","names":[{"lang":"en","v":"FORTUNE SOURCES INTERNATIONAL LIMITED"},{"lang":"hk","v":"軒葉國際有限公司"}],"company_since":"2000-06-12","company_dissolved":"2006-01-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"719927","names":[{"lang":"en","v":"HEALTHTEST SYSTEMS LIMITED"},{"lang":"hk","v":"康檢系統有限公司"}],"company_since":"2000-06-12","company_dissolved":"2016-12-02","company_type_txt":"Private, ltd by shares"},
{"tax_id":"720059","names":[{"lang":"en","v":"HONG KONG COMFORT INTERNATIONAL TRAVEL SERVICE LIMITED"},{"lang":"hk","v":"香港康輝國際旅行社有限公司"}],"company_since":"2000-06-12","company_dissolved":"2008-01-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"719963","names":[{"lang":"en","v":"HONG KONG EXCELLENT GARMENT HOLDINGS LIMITED"},{"lang":"hk","v":"香港愛西來服飾集團有限公司"}],"company_since":"2000-06-12","company_dissolved":"2005-06-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720050","names":[{"lang":"en","v":"GALEON DE FORTUNA LIMITED"},{"lang":"hk","v":"船福有限公司"}],"company_since":"2000-06-12","company_dissolved":"2006-01-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720048","names":[{"lang":"en","v":"HONG KONG WIN BRIGHT INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"香港勝輝國際發展有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720000","names":[{"lang":"en","v":"HONG KONG YAN DE LI INVESTMENT DEVELOPMENT LIMITED"},{"lang":"hk","v":"香港因特利投資發展有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720005","names":[{"lang":"en","v":"GOLDBO RICH COMPANY LIMITED"},{"lang":"hk","v":"錦臻貿易有限公司"}],"company_since":"2000-06-12","company_dissolved":"2001-08-31","company_type_txt":"Private, ltd by shares"},
{"tax_id":"719943","names":[{"lang":"en","v":"HOSTAR LIMITED (d2003-12-24)"},{"lang":"hk","v":"合成有限公司"}],"company_since":"2000-06-12","company_dissolved":"2003-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720085","names":[{"lang":"en","v":"HUA XING INTERNATIONAL NETWORK (HONG KONG) LIMITED"},{"lang":"hk","v":"華星國際網絡(香港)有限公司"}],"company_since":"2000-06-12","company_dissolved":"2005-06-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720004","names":[{"lang":"en","v":"HUANG LUNG TECHNOLOGIES LIMITED"},{"lang":"hk","v":"宏元科技有限公司"}],"company_since":"2000-06-12","company_dissolved":"2020-05-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720033","names":[{"lang":"en","v":"I-SKY ELECTRONIC LIMITED"},{"lang":"hk","v":"天科電子有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"720127","names":[{"lang":"en","v":"IBASE MEDIA LIMITED"}],"company_since":"2000-06-12","company_dissolved":"2003-11-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"720098","names":[{"lang":"en","v":"GOOD HOPE ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"樂意工程有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"720131","names":[{"lang":"en","v":"ICFOX SERVICES LIMITED"}],"company_since":"2000-06-12","company_dissolved":"2014-07-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720041","names":[{"lang":"en","v":"GREATER CHINA AQUACULTURE CONSULTANT LIMITED"},{"lang":"hk","v":"大中華海產技術顧問有限公司"}],"company_since":"2000-06-12","company_dissolved":"2006-10-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"720132","names":[{"lang":"en","v":"ICFOX TECHNOLOGY LIMITED"},{"lang":"hk","v":"建狐科技有限公司"}],"company_since":"2000-06-12","company_dissolved":"2002-03-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720032","names":[{"lang":"en","v":"INFO-CONCEPT INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"建訊國際發展有限公司"}],"company_since":"2000-06-12","company_dissolved":"2008-07-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720113","names":[{"lang":"en","v":"HANTON (H.K.) LIMITED"},{"lang":"hk","v":"恒東(香港)有限公司"}],"company_since":"2000-06-12","company_dissolved":"2005-06-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"719977","names":[{"lang":"en","v":"INNO TEXTILE (H.K.) LIMITED"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"719905","names":[{"lang":"en","v":"J &amp; W DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"君盈拓展有限公司"}],"company_since":"2000-06-12","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720107","names":[{"lang":"en","v":"HONG KONG EXCEL INTERNATIONAL BEAUTY &amp; HAIRSTYLING COLLEGE LIMITED"},{"lang":"hk","v":"香港超妍國際美容美髮學院有限公司"}],"company_since":"2000-06-12","company_dissolved":"2007-10-05","company_type_txt":"Private, ltd by shares"},
{"tax_id":"719918","names":[{"lang":"en","v":"JANWAY INTERNATIONAL LIMITED (d2004-05-07)"},{"lang":"hk","v":"展華國際有限公司"}],"company_since":"2000-06-12","company_dissolved":"2004-05-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"719954","names":[{"lang":"en","v":"HONG KONG KA KA EXPRESS COMPANY LIMITED"},{"lang":"hk","v":"香港家家快遞有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"719949","names":[{"lang":"en","v":"HONG KONG RICH DRAGON INTERNATIONAL HOLDING LIMITED"},{"lang":"hk","v":"香港富龍國際集團有限公司"}],"company_since":"2000-06-12","company_dissolved":"2005-06-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"719976","names":[{"lang":"en","v":"JILONG INTERNATIONAL PHARMACEUTICALS LIMITED"},{"lang":"hk","v":"吉龍國際藥業有限公司"}],"company_since":"2000-06-12","company_dissolved":"2003-01-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720060","names":[{"lang":"en","v":"JING FU COMPANY LIMITED"},{"lang":"hk","v":"今富有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"719908","names":[{"lang":"en","v":"JINHUI INTERNATIONAL (H.K.) LIMITED"},{"lang":"hk","v":"香港錦滙國際有限公司"}],"company_since":"2000-06-12","company_dissolved":"2006-01-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720087","names":[{"lang":"en","v":"JOYBO INTERNATIONAL LIMITED (HK)"},{"lang":"hk","v":"悅寶國際有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"719968","names":[{"lang":"en","v":"LAETITIA GARMENT LIMITED"},{"lang":"hk","v":"利得製衣有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720126","names":[{"lang":"en","v":"HOTELIWEB INTERNATIONAL LIMITED"}],"company_since":"2000-06-12","company_dissolved":"2002-04-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"719939","names":[{"lang":"en","v":"LAND UNITED LIMITED (d2011-09-23)"},{"lang":"hk","v":"盛際有限公司"}],"company_since":"2000-06-12","company_dissolved":"2011-09-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"719971","names":[{"lang":"en","v":"I T CITY INTERNATIONAL LIMITED"},{"lang":"hk","v":"城訊科技國際有限公司"}],"company_since":"2000-06-12","company_dissolved":"2014-09-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"719972","names":[{"lang":"en","v":"LI HING SHING GARMENT FACTORY LIMITED"},{"lang":"hk","v":"利興盛製衣有限公司"}],"company_since":"2000-06-12","company_dissolved":"2011-01-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720067","names":[{"lang":"en","v":"HONG KONG FINANCIAL PUBLISHING LIMITED"},{"lang":"hk","v":"香港金融出版社有限公司"}],"company_since":"2000-06-12","company_dissolved":"2005-06-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720065","names":[{"lang":"en","v":"LUCKY CHANNEL (H.K.) LIMITED"},{"lang":"hk","v":"永業(香港)有限公司"}],"company_since":"2000-06-12","company_dissolved":"2006-01-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720133","names":[{"lang":"en","v":"ICFOX MANAGEMENT LIMITED"},{"lang":"hk","v":"建狐管理有限公司"}],"company_since":"2000-06-12","company_dissolved":"2002-03-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"720117","names":[{"lang":"en","v":"LUCKY WIN (H.K.) LIMITED (d2005-06-24)"},{"lang":"hk","v":"立明(香港)有限公司"}],"company_since":"2000-06-12","company_dissolved":"2005-06-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720123","names":[{"lang":"en","v":"IHIVE H.K. LIMITED"}],"company_since":"2000-06-12","company_dissolved":"2003-10-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"720075","names":[{"lang":"en","v":"MANVILLE HOLDINGS LIMITED"},{"lang":"hk","v":"明惠集團有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"719997","names":[{"lang":"en","v":"MB MANAGEMENT CONSULTANTS LIMITED"}],"company_since":"2000-06-12","company_dissolved":"2004-04-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"720103","names":[{"lang":"en","v":"J T TOURS LIMITED"},{"lang":"hk","v":"捷達旅遊有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"720100","names":[{"lang":"en","v":"J CONCEPTS INDUSTRIAL LIMITED"},{"lang":"hk","v":"駿念實業有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"719912","names":[{"lang":"en","v":"MULTI PRO MANAGEMENT &amp; CONSULTANTS LIMITED"},{"lang":"hk","v":"才富管理策劃顧問有限公司"}],"company_since":"2000-06-12","company_dissolved":"2006-04-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720024","names":[{"lang":"en","v":"NEW CHINA MD DOT COM CORPORATION LIMITED"},{"lang":"hk","v":"新中華醫藥網有限公司"}],"company_since":"2000-06-12","company_dissolved":"2009-11-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720122","names":[{"lang":"en","v":"NEW DELUXE INVESTMENT LIMITED"},{"lang":"hk","v":"德協投資有限公司"}],"company_since":"2000-06-12","company_dissolved":"2005-06-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720115","names":[{"lang":"en","v":"NEW SMART DEVELOPMENT LIMITED"},{"lang":"hk","v":"協順發展有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"719925","names":[{"lang":"en","v":"NEWTEX INTERNATIONAL LIMITED"},{"lang":"hk","v":"立雄國際有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"719952","names":[{"lang":"en","v":"NU NU ASIA COMPANY LIMITED"}],"company_since":"2000-06-12","company_dissolved":"2006-01-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"719982","names":[{"lang":"en","v":"NUTRIWORLD ASIA LIMITED"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"719974","names":[{"lang":"en","v":"LONG KI ENGINEERING LIMITED"},{"lang":"hk","v":"朗棋工程有限公司"}],"company_since":"2000-06-12","company_dissolved":"2010-06-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"719979","names":[{"lang":"en","v":"OCEAN OFFICE MACHINES COMPANY LIMITED"},{"lang":"hk","v":"海洋商業機器有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720055","names":[{"lang":"en","v":"ORIGIN PRODUCTION LIMITED"},{"lang":"hk","v":"浩智(中國)有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"719953","names":[{"lang":"en","v":"PARTHUSCEVA TECHNOLOGIES LIMITED"}],"company_since":"2000-06-12","company_dissolved":"2004-06-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"719947","names":[{"lang":"en","v":"MULTI CURRENCY FOREIGN EXCHANGE LIMITED (d2006-01-20)"}],"company_since":"2000-06-12","company_dissolved":"2006-01-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720072","names":[{"lang":"en","v":"POWER CONCORD INVESTMENT LIMITED"},{"lang":"hk","v":"力和投資有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"719961","names":[{"lang":"en","v":"PRICENETHONGKONG.COM, LIMITED"}],"company_since":"2000-06-12","company_dissolved":"2003-05-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"720008","names":[{"lang":"en","v":"PURPLE CATERPILLAR LIMITED"}],"company_since":"2000-06-12","company_dissolved":"2003-11-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720057","names":[{"lang":"en","v":"PROTECT TECHNOLOGIES LIMITED"},{"lang":"hk","v":"普迪科技有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720119","names":[{"lang":"en","v":"NEW HARVEST (H.K.) LIMITED (d2013-04-26)"},{"lang":"hk","v":"新潤(香港)有限公司"}],"company_since":"2000-06-12","company_dissolved":"2013-04-26","company_type_txt":"Private, ltd by shares"},
{"tax_id":"719975","names":[{"lang":"en","v":"RENDERTEC MARKETING (HK) LIMITED"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720053","names":[{"lang":"en","v":"QS HOLDINGS LIMITED"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720063","names":[{"lang":"en","v":"RENFORD INVESTMENT (H.K.) LIMITED"},{"lang":"hk","v":"年豐投資(香港)有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"719919","names":[{"lang":"en","v":"RICH UNITED INTERNATIONAL LIMITED (d2004-06-04)"},{"lang":"hk","v":"富揚國際有限公司"}],"company_since":"2000-06-12","company_dissolved":"2004-06-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720037","names":[{"lang":"en","v":"RICHEST INTERNATIONAL ENTERPRISE LIMITED (d2005-10-07)"},{"lang":"hk","v":"超富國際企業有限公司"}],"company_since":"2000-06-12","company_dissolved":"2005-10-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720077","names":[{"lang":"en","v":"RIGHT ESSENSE HOLDINGS LIMITED"},{"lang":"hk","v":"正怡集團有限公司"}],"company_since":"2000-06-12","company_dissolved":"2002-02-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720044","names":[{"lang":"en","v":"SCORE LOGISTICS LIMITED"},{"lang":"hk","v":"高志物流有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720083","names":[{"lang":"en","v":"SENVA LIMITED (d2006-09-22)"},{"lang":"hk","v":"軒發有限公司"}],"company_since":"2000-06-12","company_dissolved":"2006-09-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720074","names":[{"lang":"en","v":"SHEEN HARVEST HOLDINGS LIMITED"},{"lang":"hk","v":"信凱集團有限公司"}],"company_since":"2000-06-12","company_dissolved":"2016-08-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720036","names":[{"lang":"en","v":"ORIENT CONCEPT INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"香港領域電腦(中國)有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"719989","names":[{"lang":"en","v":"ORIENT CROWN ASIA LIMITED"},{"lang":"hk","v":"冠東亞洲有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"720093","names":[{"lang":"en","v":"SHUN SENG HOP YICK ENTERPRISES LIMITED"},{"lang":"hk","v":"順成合益企業有限公司"}],"company_since":"2000-06-12","company_dissolved":"2017-11-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"719993","names":[{"lang":"en","v":"NUCLEARSOFT TECHNOLOGY LIMITED"},{"lang":"hk","v":"核子軟件程式有限公司"}],"company_since":"2000-06-12","company_dissolved":"2007-11-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"719995","names":[{"lang":"en","v":"SING TAT EMBROIDERY FACTORY LIMITED"},{"lang":"hk","v":"星達機綉廠有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720066","names":[{"lang":"en","v":"ORIENTAL GLORY (H.K.) LIMITED (d2005-06-24)"},{"lang":"hk","v":"新僑(香港)有限公司"}],"company_since":"2000-06-12","company_dissolved":"2005-06-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"720064","names":[{"lang":"en","v":"SKY &amp; EARTH TECHNOLOGY LIMITED"},{"lang":"hk","v":"大雄生物科技有限公司"}],"company_since":"2000-06-12","company_dissolved":"2006-10-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"719965","names":[{"lang":"en","v":"SINTA INTERNATIONAL ENTERPRISE COMPANY LIMITED"},{"lang":"hk","v":"星塔國際企業有限公司"}],"company_since":"2000-06-12","company_dissolved":"2007-10-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"719990","names":[{"lang":"en","v":"SKY SURPLUS ASIA LIMITED"},{"lang":"hk","v":"天盈亞洲有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720105","names":[{"lang":"en","v":"P &amp; A ENGINEERING SERVICES (HK) LIMITED"},{"lang":"hk","v":"盈策機電工程(香港)有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"720038","names":[{"lang":"en","v":"SKY WEALTH INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"天富國際投資有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"719960","names":[{"lang":"en","v":"PACIFIC GATE INTERNATIONAL LIMITED (d2001-09-14)"},{"lang":"hk","v":"晉洋國際有限公司"}],"company_since":"2000-06-12","company_dissolved":"2001-09-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"720106","names":[{"lang":"en","v":"RICHES GOLD FUAN (H.K.) BIO-CHEMICAL ENGINEERING LIMITED"},{"lang":"hk","v":"金億富安(香港)生化工程有限公司"}],"company_since":"2000-06-12","company_dissolved":"2006-01-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"719969","names":[{"lang":"en","v":"PEACE (HK) CO., LIMITED"},{"lang":"hk","v":"平和通商(香港)有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720128","names":[{"lang":"en","v":"Pengtai Greater China Company Limited"},{"lang":"hk","v":"三星鵬泰有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"719996","names":[{"lang":"en","v":"SUDAN NEW TECHNOLOGY CO., LIMITED"},{"lang":"hk","v":"蘇丹新技術有限公司"}],"company_since":"2000-06-12","company_dissolved":"2006-10-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"719962","names":[{"lang":"en","v":"SUNBRIGHT INTERNATIONAL GROUP LIMITED"},{"lang":"hk","v":"靈光國際集團有限公司"}],"company_since":"2000-06-12","company_dissolved":"2008-05-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"719921","names":[{"lang":"en","v":"NAX (HONG KONG) LIMITED"},{"lang":"hk","v":"添源國際有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"719920","names":[{"lang":"en","v":"TECHFIELD INTERNATIONAL LIMITED"},{"lang":"hk","v":"達豐國際有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720114","names":[{"lang":"en","v":"TOP APEX INDUSTRIAL LIMITED"},{"lang":"hk","v":"安柏實業有限公司"}],"company_since":"2000-06-12","company_dissolved":"2009-11-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720116","names":[{"lang":"en","v":"UNICO DEVELOPMENT LIMITED (d2005-06-24)"},{"lang":"hk","v":"成豪發展有限公司"}],"company_since":"2000-06-12","company_dissolved":"2005-06-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720099","names":[{"lang":"en","v":"UNICORN CONSTRUCTION &amp; CONSULTANCY COMPANY LIMITED"},{"lang":"hk","v":"麒麟建築及顧問有限公司"}],"company_since":"2000-06-12","company_dissolved":"2007-10-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"719955","names":[{"lang":"en","v":"UNITEX HOLDINGS COMPANY LIMITED"}],"company_since":"2000-06-12","company_dissolved":"2006-08-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720046","names":[{"lang":"en","v":"WEALTH ON INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"超富國際發展有限公司"}],"company_since":"2000-06-12","company_dissolved":"2001-12-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720089","names":[{"lang":"en","v":"SUN WING ENTERPRISE (HONG KONG) LIMITED"},{"lang":"hk","v":"新榮實業(香港)有限公司"}],"company_since":"2000-06-12","company_dissolved":"2006-11-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720071","names":[{"lang":"en","v":"TOGO INVESTMENTS LIMITED"},{"lang":"hk","v":"圖高投資有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"719991","names":[{"lang":"en","v":"TOP CASTLE ASIA LIMITED"},{"lang":"hk","v":"高堡亞洲有限公司"}],"company_since":"2000-06-12","company_dissolved":"2002-11-01","company_type_txt":"Private, ltd by shares"},
{"tax_id":"719916","names":[{"lang":"en","v":"WISE EXPRESS INTERNATIONAL LIMITED"},{"lang":"hk","v":"偉茂國際有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"719942","names":[{"lang":"en","v":"TOP GLOBE LIMITED (d2007-01-12)"},{"lang":"hk","v":"高宜有限公司"}],"company_since":"2000-06-12","company_dissolved":"2007-01-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"720091","names":[{"lang":"en","v":"WONDERFUL DESIGN LIMITED"},{"lang":"hk","v":"茗科設計有限公司"}],"company_since":"2000-06-12","company_dissolved":"2006-10-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720043","names":[{"lang":"en","v":"TOPGLORY INTERNATIONAL ENTERPRISE LIMITED"},{"lang":"hk","v":"亨達國際企業有限公司"}],"company_since":"2000-06-12","company_dissolved":"2006-10-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720045","names":[{"lang":"en","v":"TREASURE SKY INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"富天國際投資有限公司"}],"company_since":"2000-06-12","company_dissolved":"2005-06-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"720049","names":[{"lang":"en","v":"YAU LUEN GLOVE FACTORY COMPANY LIMITED"},{"lang":"hk","v":"友聯手套廠有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720021","names":[{"lang":"en","v":"YEUNG YEUNG COMPANY LIMITED"},{"lang":"hk","v":"揚揚有限公司"}],"company_since":"2000-06-12","company_dissolved":"2019-05-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"719944","names":[{"lang":"en","v":"WPQ LIMITED"},{"lang":"hk","v":"網中贏有限公司"}],"company_since":"2000-06-12","company_dissolved":"2008-03-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"719998","names":[{"lang":"en","v":"UNION EXPRESS INTERNATIONAL TRADING LIMITED"},{"lang":"hk","v":"聯通國際貿易有限公司"}],"company_since":"2000-06-12","company_dissolved":"2002-06-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"720108","names":[{"lang":"en","v":"Z W INTERNATIONAL EDULINK LIMITED"},{"lang":"hk","v":"智達國際教育交流中心有限公司"}],"company_since":"2000-06-12","company_dissolved":"2007-10-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720047","names":[{"lang":"en","v":"WEALTH ON INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"添富國際投資有限公司"}],"company_since":"2000-06-12","company_dissolved":"2006-01-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"719959","names":[{"lang":"en","v":"ZERO TIME PRODUCT DESIGN INTERNATIONAL LIMITED"},{"lang":"hk","v":"凌時產品設計國際有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720101","names":[{"lang":"en","v":"ZING ASIA LIMITED (d2006-10-27)"}],"company_since":"2000-06-12","company_dissolved":"2006-10-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"719992","names":[{"lang":"en","v":"WELL SUCCESS ASIA LIMITED"},{"lang":"hk","v":"有成亞洲有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720079","names":[{"lang":"en","v":"WIN CHAMPION PROPERTIES LIMITED"},{"lang":"hk","v":"永祥置業有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"719958","names":[{"lang":"en","v":"WINDSOR ASIA LIMITED"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"719931","names":[{"lang":"en","v":"WINET TRADING LIMITED"},{"lang":"hk","v":"滙隆貿易有限公司"}],"company_since":"2000-06-12","company_dissolved":"2008-11-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"719973","names":[{"lang":"en","v":"WING YUE TEXTILE COMPANY LIMITED"},{"lang":"hk","v":"永愉紡織有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"719924","names":[{"lang":"en","v":"WINKEN INTERNATIONAL LIMITED (d2007-08-17)"},{"lang":"hk","v":"永景國際有限公司"}],"company_since":"2000-06-12","company_dissolved":"2007-08-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720007","names":[{"lang":"en","v":"WINNING PRESENTATIONS LIMITED (HK)"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"719930","names":[{"lang":"en","v":"WORLD POINT TRADING LIMITED"},{"lang":"hk","v":"永邦貿易有限公司"}],"company_since":"2000-06-12","company_dissolved":"2020-04-29","company_type_txt":"Private, ltd by shares"},
{"tax_id":"719914","names":[{"lang":"en","v":"WORLD BILLION DEVELOPMENT LIMITED"},{"lang":"hk","v":"世邦發展有限公司"}],"company_since":"2000-06-12","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720111","names":[{"lang":"en","v":"YINSON KNITTING LIMITED"},{"lang":"hk","v":"盈順針織有限公司"}],"company_since":"2000-06-12","company_dissolved":"2010-08-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720017","names":[{"lang":"en","v":"WIN GLORY ASIA LIMITED (d2006-01-06)"},{"lang":"hk","v":"怡勝亞洲有限公司"}],"company_since":"2000-06-12","company_dissolved":"2006-01-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
