{"tax_id":"721179","names":[{"lang":"en","v":"CHINA INTERNATIONAL INVESTMENTS CONSULTANTS LIMITED (d2005-03-18)"},{"lang":"hk","v":"中國國際投資顧問有限公司"}],"company_since":"2000-06-21","company_dissolved":"2005-03-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721113","names":[{"lang":"en","v":"CHINA ASSOCIATION OF DOG-OWNERS LIMITED"},{"lang":"hk","v":"中國犬業聯合會俱樂部有限公司"}],"company_since":"2000-06-21","company_dissolved":"2006-01-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721235","names":[{"lang":"en","v":"CHINA WAY GLOBAL ENTERPRISES LIMITED"},{"lang":"hk","v":"華威環球企業有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721118","names":[{"lang":"en","v":"CHINTECH ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"中科設備有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721029","names":[{"lang":"en","v":"Chouraqui Boating Company Limited (The)"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720996","names":[{"lang":"en","v":"CINTAC INDUSTRIES LIMITED"}],"company_since":"2000-06-21","company_dissolved":"2011-02-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721201","names":[{"lang":"en","v":"CINTEX LIMITED (d2002-03-08)"},{"lang":"hk","v":"絲藝社有限公司"}],"company_since":"2000-06-21","company_dissolved":"2002-03-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721150","names":[{"lang":"en","v":"CM CONCEPT (HK) LIMITED"},{"lang":"hk","v":"潤迅概念(香港)有限公司"}],"company_since":"2000-06-21","company_dissolved":"2015-10-23","company_type_txt":"Private, ltd by shares"},
{"tax_id":"721027","names":[{"lang":"en","v":"CONTEX INTERNATIONAL ENTERPRISES COMPANY LIMITED"},{"lang":"hk","v":"康泰國際實業有限公司"}],"company_since":"2000-06-21","company_dissolved":"2020-05-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721154","names":[{"lang":"en","v":"CULT-INFINITY ENTERTAINMENT LIMITED"},{"lang":"hk","v":"世紀創意文化藝術有限公司"}],"company_since":"2000-06-21","company_dissolved":"2005-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721040","names":[{"lang":"en","v":"DONG MING WATCH COMPANY LIMITED"},{"lang":"hk","v":"東明鐘錶有限公司"}],"company_since":"2000-06-21","company_dissolved":"2019-03-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721024","names":[{"lang":"en","v":"DRAGON CHARM TRADING COMPANY LIMITED"},{"lang":"hk","v":"龍點睛貿易有限公司"}],"company_since":"2000-06-21","company_dissolved":"2007-09-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721142","names":[{"lang":"en","v":"CHINA CHEUNG FUNG HOLDINGS LIMITED"},{"lang":"hk","v":"中國長豐集團有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"721098","names":[{"lang":"en","v":"DRAMARAMA CHILDREN'S THEATRE LIMITED"}],"company_since":"2000-06-21","company_dissolved":"2009-04-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"721109","names":[{"lang":"en","v":"DRIVERS AND RIDERS RACING ASSOCIATION LIMITED"},{"lang":"hk","v":"賽車員協會有限公司"}],"company_since":"2000-06-21","company_dissolved":"2010-02-19","company_type_txt":"Ltd by guarantee"},
{"tax_id":"721108","names":[{"lang":"en","v":"CHINA FEI TENG EDUCATIONAL FOUNDATION LIMITED"},{"lang":"hk","v":"中國飛騰教育基金有限公司"}],"company_since":"2000-06-21","company_dissolved":"2014-11-21","company_type_txt":"Ltd by guarantee"},
{"tax_id":"721166","names":[{"lang":"en","v":"E-TONE CREATIVE CO., LIMITED"},{"lang":"hk","v":"意動創作有限公司"}],"company_since":"2000-06-21","company_dissolved":"2016-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721169","names":[{"lang":"en","v":"CHINA WINDOW NET LIMITED"},{"lang":"hk","v":"中國窗有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"721043","names":[{"lang":"en","v":"EASTIME CONSTRUCTION EQUIPMENT ENGINEERING LIMITED"},{"lang":"hk","v":"東泰建機工程有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721240","names":[{"lang":"en","v":"CHINAMOTION NETCOM HOLDINGS (CHINA) LIMITED"},{"lang":"hk","v":"潤迅網絡通信控股(中國)有限公司"}],"company_since":"2000-06-21","company_dissolved":"2005-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721180","names":[{"lang":"en","v":"CHINESE MEDICINE - MAN WAH BONESETTER LIMITED"},{"lang":"hk","v":"中華中醫葯-民華醫館有限公司"}],"company_since":"2000-06-21","company_dissolved":"2015-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721175","names":[{"lang":"en","v":"CHINACARE (HONG KONG) LIMITED"},{"lang":"hk","v":"中華關懷(香港)有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721060","names":[{"lang":"en","v":"EVER SMART GROUP LIMITED (d2005-09-23)"},{"lang":"hk","v":"先德集團有限公司"}],"company_since":"2000-06-21","company_dissolved":"2005-09-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721149","names":[{"lang":"en","v":"EVERVIEW HOLDINGS LIMITED (d2005-06-30)"},{"lang":"hk","v":"福景集團有限公司"}],"company_since":"2000-06-21","company_dissolved":"2005-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721004","names":[{"lang":"en","v":"EXCELLENT STAR INVESTMENTS LIMITED"},{"lang":"hk","v":"益運達投資有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721204","names":[{"lang":"en","v":"CONCORD HARMONY LIMITED"},{"lang":"hk","v":"旺和有限公司"}],"company_since":"2000-06-21","company_dissolved":"2006-03-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"721079","names":[{"lang":"en","v":"F &amp; F (HK) LIMITED"}],"company_since":"2000-06-21","company_dissolved":"2010-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721136","names":[{"lang":"en","v":"FAKE PREVENTION TECHNOLOGY H.K.S.A.R. LIMITED"},{"lang":"hk","v":"中國香港特別行政區防偽技術有限公司"}],"company_since":"2000-06-21","company_dissolved":"2001-09-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"721221","names":[{"lang":"en","v":"FANCY RAINBOW LIMITED (d2002-08-09)"},{"lang":"hk","v":"維彩有限公司"}],"company_since":"2000-06-21","company_dissolved":"2002-08-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721192","names":[{"lang":"en","v":"FIRST TREND INVESTMENT LIMITED"},{"lang":"hk","v":"傑昌投資有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721111","names":[{"lang":"en","v":"CO-OP (HOLDINGS) LIMITED"},{"lang":"hk","v":"合建(控股)有限公司"}],"company_since":"2000-06-21","company_dissolved":"2009-06-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"721208","names":[{"lang":"en","v":"FORTUNE EMPEROR LIMITED"},{"lang":"hk","v":"福皇有限公司"}],"company_since":"2000-06-21","company_dissolved":"2011-04-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"721074","names":[{"lang":"en","v":"GLOBAL PROFIT (ASIA) LIMITED"},{"lang":"hk","v":"駿天(亞洲)有限公司"}],"company_since":"2000-06-21","company_dissolved":"2015-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721217","names":[{"lang":"en","v":"GLOBE EXPRESS LIMITED (d2002-10-04)"},{"lang":"hk","v":"順世有限公司"}],"company_since":"2000-06-21","company_dissolved":"2002-10-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721219","names":[{"lang":"en","v":"GLOBE KINGDOM LIMITED (d2001-11-16)"},{"lang":"hk","v":"寰邦有限公司"}],"company_since":"2000-06-21","company_dissolved":"2001-11-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721078","names":[{"lang":"en","v":"GLORY SMART (HK) LIMITED"},{"lang":"hk","v":"駿天(香港)有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721228","names":[{"lang":"en","v":"EVER CONCORD LINES LIMITED"},{"lang":"hk","v":"確悅有限公司"}],"company_since":"2000-06-21","company_dissolved":"2006-11-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"721103","names":[{"lang":"en","v":"GLOSS CAPITAL LIMITED"},{"lang":"hk","v":"澤有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721168","names":[{"lang":"en","v":"GNETT.COM LIMITED"},{"lang":"hk","v":"至叻網有限公司"}],"company_since":"2000-06-21","company_dissolved":"2006-01-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720976","names":[{"lang":"en","v":"GOLD LINKER LIMITED"},{"lang":"hk","v":"金怡順有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721206","names":[{"lang":"en","v":"GOLDEN RESOURCES LIMITED (d2013-09-06)"},{"lang":"hk","v":"金源有限公司"}],"company_since":"2000-06-21","company_dissolved":"2013-09-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721236","names":[{"lang":"en","v":"GOLF TRAVEL LIMITED (d2017-03-24)"},{"lang":"hk","v":"高球旅遊有限公司"}],"company_since":"2000-06-21","company_dissolved":"2017-03-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721007","names":[{"lang":"en","v":"FANTASIA ADVERTISING LIMITED (d2001-11-16)"}],"company_since":"2000-06-21","company_dissolved":"2001-11-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721182","names":[{"lang":"en","v":"GULF TREASURE LIMITED (d2002-12-13)"},{"lang":"hk","v":"海灣實業有限公司"}],"company_since":"2000-06-21","company_dissolved":"2002-12-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721158","names":[{"lang":"en","v":"H.K. JIA FENG INTERNATIONAL TRADING LIMITED"},{"lang":"hk","v":"香港佳豐國際貿易有限公司"}],"company_since":"2000-06-21","company_dissolved":"2004-05-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721184","names":[{"lang":"en","v":"HANDI DESIGN LIMITED"},{"lang":"hk","v":"恆達建築師事務所有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720992","names":[{"lang":"en","v":"FORTUNE VENTURE MANAGEMENT LIMITED"}],"company_since":"2000-06-21","company_dissolved":"2004-03-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"720998","names":[{"lang":"en","v":"HANDPHONESHOP (HONG KONG) LIMITED"}],"company_since":"2000-06-21","company_dissolved":"2010-02-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721056","names":[{"lang":"en","v":"FOUNDER IASPEC (NB) LIMITED"},{"lang":"hk","v":"方正永泰(自然美)有限公司"}],"company_since":"2000-06-21","company_dissolved":"2005-02-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721126","names":[{"lang":"en","v":"GIKON INTERNATIONAL LIMITED"},{"lang":"hk","v":"澤科國際有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"721036","names":[{"lang":"en","v":"HARMONY PRODUCTION LIMITED (d2001-11-09)"},{"lang":"hk","v":"協調製作有限公司"}],"company_since":"2000-06-21","company_dissolved":"2001-11-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721121","names":[{"lang":"en","v":"HDV PRODUCTIONS LIMITED"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721187","names":[{"lang":"en","v":"HK SOLIN (INT'L) GROUP DRESS LIMITED"},{"lang":"hk","v":"香港獸林(國際)集團服飾有限公司"}],"company_since":"2000-06-21","company_dissolved":"2005-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721194","names":[{"lang":"en","v":"HKWEAR INTERNATIONAL LIMITED"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721137","names":[{"lang":"en","v":"HLC INTERNATIONAL (H.K.) COMPANY LIMITED"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721001","names":[{"lang":"en","v":"HONG KONG CONTINUING PROFESSIONAL DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"香港持續專業發展有限公司"}],"company_since":"2000-06-21","company_dissolved":"2006-11-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721161","names":[{"lang":"en","v":"GOLDEN PROSPECT GARMENT (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"明成製衣(香港)有限公司"}],"company_since":"2000-06-21","company_dissolved":"2018-11-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"721010","names":[{"lang":"en","v":"HONG KONG ROAD OPERATION INVESTMENT LIMITED"},{"lang":"hk","v":"香港路業投資有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721122","names":[{"lang":"en","v":"HONGKONG ZUNGCENG WEIYIB INTERNATIONAL GROUP CO., LIMITED"},{"lang":"hk","v":"香港中創偉業國際集團有限公司"}],"company_since":"2000-06-21","company_dissolved":"2005-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721064","names":[{"lang":"en","v":"GOODWELL ENTERPRISE LIMITED (d2006-11-03)"},{"lang":"hk","v":"先德企業有限公司"}],"company_since":"2000-06-21","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"721230","names":[{"lang":"en","v":"HUANGLONG FEI TECHNOLOGY (H.K.) HOLDING LIMITED"},{"lang":"hk","v":"皇龍飛科技(香港)集團有限公司"}],"company_since":"2000-06-21","company_dissolved":"2005-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721144","names":[{"lang":"en","v":"ICHIBAN PROPERTY LIMITED"},{"lang":"hk","v":"一番物業有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"721135","names":[{"lang":"en","v":"GREAT CHINA FASHIONS LIMITED"},{"lang":"hk","v":"大中華時裝有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"721151","names":[{"lang":"en","v":"HARVEST WORLD LIMITED"},{"lang":"hk","v":"萬利達有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"721115","names":[{"lang":"en","v":"J-WILL CORPORATION LIMITED"}],"company_since":"2000-06-21","company_dissolved":"2009-02-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720987","names":[{"lang":"en","v":"JAS ENTERPRISE LIMITED (HK)"},{"lang":"hk","v":"心悅企業有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721157","names":[{"lang":"en","v":"HIH ENTERPRISES COMPANY LIMITED"}],"company_since":"2000-06-21","company_dissolved":"2005-06-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"721076","names":[{"lang":"en","v":"JENFORD FAR EAST LIMITED"},{"lang":"hk","v":"駿福遠東有限公司"}],"company_since":"2000-06-21","company_dissolved":"2004-11-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721190","names":[{"lang":"en","v":"HK WEAVER LIMITED"},{"lang":"hk","v":"創富國際控股有限公司"}],"company_since":"2000-06-21","company_dissolved":"2004-03-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721188","names":[{"lang":"en","v":"JULI INT'L GROUP LIMITED"},{"lang":"hk","v":"巨力國際集團有限公司"}],"company_since":"2000-06-21","company_dissolved":"2005-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721198","names":[{"lang":"en","v":"KAI JING CONSTRUCTION CONTRACTING LIMITED"},{"lang":"hk","v":"佳景建築工程有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720960","names":[{"lang":"en","v":"HONG KONG YI ZHU XIN MEDICINE LIMITED"},{"lang":"hk","v":"香港奕竹鑫葯業有限公司"}],"company_since":"2000-06-21","company_dissolved":"2005-06-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"721183","names":[{"lang":"en","v":"KAM YUEN BAKERY LIMITED"},{"lang":"hk","v":"金源西餅麵包有限公司"}],"company_since":"2000-06-21","company_dissolved":"2004-11-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721233","names":[{"lang":"en","v":"KIN WING MOTOR ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"健榮汽車工程有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720961","names":[{"lang":"en","v":"KP LAB LIMITED"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721052","names":[{"lang":"en","v":"KWONG MING HONG OIL COMPANY LIMITED"},{"lang":"hk","v":"光明行石油有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721009","names":[{"lang":"en","v":"LEE TACK PLASTIC &amp; METAL MANUFACTORY LIMITED"},{"lang":"hk","v":"利德塑膠五金製品廠有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721133","names":[{"lang":"en","v":"INTERNATIONAL GARMENTS GROUP (BANGLADESH) LIMITED"},{"lang":"hk","v":"國際製衣集團(孟加拉)有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721014","names":[{"lang":"en","v":"LUCKY CHOICE TRADING LIMITED"},{"lang":"hk","v":"彩源貿易有限公司"}],"company_since":"2000-06-21","company_dissolved":"2017-04-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"721186","names":[{"lang":"en","v":"JUSTICE INT'L TRANSPORTATION LIMITED"},{"lang":"hk","v":"捷達時國際貨運有限公司"}],"company_since":"2000-06-21","company_dissolved":"2005-06-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"721092","names":[{"lang":"en","v":"MAGNA CONCEPT COMPANY LIMITED"},{"lang":"hk","v":"萬理創建有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721020","names":[{"lang":"en","v":"MAN ON FIRE CONSULTANT LIMITED"},{"lang":"hk","v":"萬安消防顧問有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721080","names":[{"lang":"en","v":"JENFORD (HK) LIMITED"},{"lang":"hk","v":"駿福(香港)有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720975","names":[{"lang":"en","v":"KARMA JEWELS (HK) LIMITED"},{"lang":"hk","v":"珂瑪(香港)有限公司"}],"company_since":"2000-06-21","company_dissolved":"2003-10-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"721209","names":[{"lang":"en","v":"MILLION RAINBOW LIMITED (d2007-06-28)"},{"lang":"hk","v":"彩萬有限公司"}],"company_since":"2000-06-21","company_dissolved":"2007-06-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720968","names":[{"lang":"en","v":"MING KEE BUILDING LIMITED (d2011-02-18)"},{"lang":"hk","v":"明記建築有限公司"}],"company_since":"2000-06-21","company_dissolved":"2011-02-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721242","names":[{"lang":"en","v":"NGAI SHING ENTERPRISE COMPANY LIMITED"},{"lang":"hk","v":"藝成企業有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"721105","names":[{"lang":"en","v":"OAKZONE-HANJIN SYSTEM (HONG KONG) LIMITED"},{"lang":"hk","v":"沃田韓進系統(香港)有限公司"}],"company_since":"2000-06-21","company_dissolved":"2006-01-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721213","names":[{"lang":"en","v":"OCEAN ONE LIMITED (HK)"},{"lang":"hk","v":"海立有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721086","names":[{"lang":"en","v":"LINTEC TECHNOLOGY (FAR EAST) COMPANY LIMITED"}],"company_since":"2000-06-21","company_dissolved":"2005-07-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"721025","names":[{"lang":"en","v":"KAHL &amp; LAIS LIMITED"}],"company_since":"2000-06-21","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720969","names":[{"lang":"en","v":"LONGS INTERNATIONAL LIMITED"},{"lang":"hk","v":"朗士國際有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721231","names":[{"lang":"en","v":"LUCKY OCEAN (HONG KONG) LIMITED"},{"lang":"hk","v":"怡洋(香港)有限公司"}],"company_since":"2000-06-21","company_dissolved":"2004-09-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721143","names":[{"lang":"en","v":"PEARL SPORTS LIMITED"},{"lang":"hk","v":"明珠體育用品有限公司"}],"company_since":"2000-06-21","company_dissolved":"2008-11-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721130","names":[{"lang":"en","v":"PEN - FAITH MARITIME CONSULTANT &amp; SERVICE CO., LIMITED"},{"lang":"hk","v":"泛信海事咨詢服務有限公司"}],"company_since":"2000-06-21","company_dissolved":"2005-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"721123","names":[{"lang":"en","v":"PIER KADAN DRESS (HONG KONG) INTERNATIONAL HOLDING LIMITED"},{"lang":"hk","v":"皮爾卡丹服飾(香港)國際集團有限公司"}],"company_since":"2000-06-21","company_dissolved":"2007-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721189","names":[{"lang":"en","v":"POWER MERCHANT COMPANY LIMITED"},{"lang":"hk","v":"動力飲食有限公司"}],"company_since":"2000-06-21","company_dissolved":"2013-02-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"721003","names":[{"lang":"en","v":"REGAL STAR TECHNOLOGY LIMITED"},{"lang":"hk","v":"君達科技有限公司"}],"company_since":"2000-06-21","company_dissolved":"2012-04-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721119","names":[{"lang":"en","v":"NETSKY TECHNOLOGY LIMITED"},{"lang":"hk","v":"天域互動有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721127","names":[{"lang":"en","v":"RELIANCE MACHINERY &amp; EQUIPMENT LIMITED"},{"lang":"hk","v":"永信機械設備有限公司"}],"company_since":"2000-06-21","company_dissolved":"2015-07-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721153","names":[{"lang":"en","v":"NICO CREATION LIMITED"},{"lang":"hk","v":"麗圖國際拓展有限公司"}],"company_since":"2000-06-21","company_dissolved":"2002-08-02","company_type_txt":"Private, ltd by shares"},
{"tax_id":"720986","names":[{"lang":"en","v":"RELIANCE MEDIA INTERNATIONAL LIMITED"},{"lang":"hk","v":"誠信國際實業有限公司"}],"company_since":"2000-06-21","company_dissolved":"2012-10-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721100","names":[{"lang":"en","v":"RIGHT CHOICE OVERSEAS EMPLOYMENT CENTRE LIMITED"},{"lang":"hk","v":"卓達海外僱傭中心有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"720978","names":[{"lang":"en","v":"OVER2K.COM LIMITED"}],"company_since":"2000-06-21","company_dissolved":"2006-01-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"721164","names":[{"lang":"en","v":"SAGENT (HONG KONG) LIMITED"}],"company_since":"2000-06-21","company_dissolved":"2004-02-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721039","names":[{"lang":"en","v":"PACIFIC COMMUNICATIONS TECHNOLOGY LIMITED"},{"lang":"hk","v":"鉅宏通訊科技有限公司"}],"company_since":"2000-06-21","company_dissolved":"2006-01-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721072","names":[{"lang":"en","v":"SINO PERFECT (ASIA) LIMITED"},{"lang":"hk","v":"信昌(亞洲)有限公司"}],"company_since":"2000-06-21","company_dissolved":"2001-08-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720967","names":[{"lang":"en","v":"SHI FANG ARCHITECTURAL DESIGN COMPANY LIMITED"},{"lang":"hk","v":"十方建築設計有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721176","names":[{"lang":"en","v":"SINO-PACIFIC INTERNATIONAL TECHNOLOGY DEVELOPMENT LIMITED"},{"lang":"hk","v":"中天國際科技發展有限公司"}],"company_since":"2000-06-21","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721220","names":[{"lang":"en","v":"SMART HARVEST LIMITED"},{"lang":"hk","v":"裕康有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"721034","names":[{"lang":"en","v":"SAM TONE LIMITED"},{"lang":"hk","v":"湘通有限公司"}],"company_since":"2000-06-21","company_dissolved":"2005-02-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"721205","names":[{"lang":"en","v":"SEDON LIMITED"},{"lang":"hk","v":"兆雄有限公司"}],"company_since":"2000-06-21","company_dissolved":"2005-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721197","names":[{"lang":"en","v":"SHENG DUN GROUP (H.K.) INT'L GARMENT LIMITED"},{"lang":"hk","v":"聖盾集團(香港)國際服飾有限公司"}],"company_since":"2000-06-21","company_dissolved":"2005-06-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"721112","names":[{"lang":"en","v":"SMART HORSE MACHINERY &amp; ELECTRICAL ENGINEERING LIMITED"},{"lang":"hk","v":"駿馬機電工程有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721077","names":[{"lang":"en","v":"SPORT ELEMENTS LIMITED"},{"lang":"hk","v":"互聯達有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721089","names":[{"lang":"en","v":"SMD TOYS &amp; EXPANSION GIFTS (H.K.) LIMITED"},{"lang":"hk","v":"拓展─明大玩具禮品(香港)有限公司"}],"company_since":"2000-06-21","company_dissolved":"2013-08-30","company_type_txt":"Private, ltd by shares"},
{"tax_id":"720993","names":[{"lang":"en","v":"SOUTH CHINA TRADERS LIMITED"}],"company_since":"2000-06-21","company_dissolved":"2005-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"721023","names":[{"lang":"en","v":"SICALCO S. A. LIMITED"},{"lang":"hk","v":"西卡克晶砂產業有限公司"}],"company_since":"2000-06-21","company_dissolved":"2011-02-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"721099","names":[{"lang":"en","v":"S.E.A. MARKETING LIMITED"}],"company_since":"2000-06-21","company_dissolved":"2006-01-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720995","names":[{"lang":"en","v":"SILICON CREATION LIMITED"},{"lang":"hk","v":"先力創建有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721084","names":[{"lang":"en","v":"SING PO TIMER COMPANY LIMITED"},{"lang":"hk","v":"聲寶時計有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721021","names":[{"lang":"en","v":"SENNU FASHION (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"森奴服飾(香港)有限公司"}],"company_since":"2000-06-21","company_dissolved":"2006-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721046","names":[{"lang":"en","v":"SINO FRENCH WATER DEVELOPMENT (SIPING) COMPANY LIMITED"},{"lang":"hk","v":"中法水務投資(四平)有限公司"}],"company_since":"2000-06-21","company_dissolved":"2020-09-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721011","names":[{"lang":"en","v":"TALENT NET DEVELOPMENT LIMITED"},{"lang":"hk","v":"智博發展有限公司"}],"company_since":"2000-06-21","company_dissolved":"2007-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721226","names":[{"lang":"en","v":"THOUSAND VANTAGE LIMITED (d2005-03-24)"},{"lang":"hk","v":"千財有限公司"}],"company_since":"2000-06-21","company_dissolved":"2005-03-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"721129","names":[{"lang":"en","v":"SNC CONSULTATION AND SERVICES LIMITED"},{"lang":"hk","v":"卓民顧問服務有限公司"}],"company_since":"2000-06-21","company_dissolved":"2002-05-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721068","names":[{"lang":"en","v":"TOPMOND TRADING LIMITED"},{"lang":"hk","v":"力捷貿易有限公司"}],"company_since":"2000-06-21","company_dissolved":"2018-08-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"721101","names":[{"lang":"en","v":"STATE FUND CYBERWORKS COMPANY LIMITED"},{"lang":"hk","v":"國豐數碼設備有限公司"}],"company_since":"2000-06-21","company_dissolved":"2002-04-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721097","names":[{"lang":"en","v":"TRIANA INVESTMENTS LIMITED"}],"company_since":"2000-06-21","company_dissolved":"2008-12-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"721172","names":[{"lang":"en","v":"SYNAPSEWORLD LIMITED"}],"company_since":"2000-06-21","company_dissolved":"2002-01-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"720999","names":[{"lang":"en","v":"WASSER INVESTMENTS LIMITED"}],"company_since":"2000-06-21","company_dissolved":"2003-10-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720990","names":[{"lang":"en","v":"TAKEUCHI INDUSTRY (HONG KONG) CO., LIMITED"},{"lang":"hk","v":"竹內工業(香港)有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721178","names":[{"lang":"en","v":"THUK WING GARMENT MANUFACTURER LIMITED"},{"lang":"hk","v":"德榮製衣有限公司"}],"company_since":"2000-06-21","company_dissolved":"2009-01-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721171","names":[{"lang":"en","v":"Syneos Health Holdings (Hong Kong) Limited"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721120","names":[{"lang":"en","v":"TINE TRAVEL INTERNATIONAL CO LIMITED"},{"lang":"hk","v":"天力國際旅遊有限公司"}],"company_since":"2000-06-21","company_dissolved":"2010-03-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721116","names":[{"lang":"en","v":"TONGDA GROUP INTERNATIONAL LIMITED"},{"lang":"hk","v":"通達集團國際有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"721035","names":[{"lang":"en","v":"WEATHERLAND INVESTMENTS LIMITED"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"721241","names":[{"lang":"en","v":"TOP IMAGE INDUSTRIAL LIMITED"},{"lang":"hk","v":"威美實業有限公司"}],"company_since":"2000-06-21","company_dissolved":"2001-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721223","names":[{"lang":"en","v":"TOP MASTER CORPORATION LIMITED"},{"lang":"hk","v":"鼎業有限公司"}],"company_since":"2000-06-21","company_dissolved":"2017-01-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"721048","names":[{"lang":"en","v":"XML ASIA LIMITED"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"720985","names":[{"lang":"en","v":"Y NUMERIC SYSTEMS LIMITED"},{"lang":"hk","v":"數自通系統有限公司"}],"company_since":"2000-06-21","company_dissolved":"2001-11-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"721012","names":[{"lang":"en","v":"YODAO (HONG KONG) LIMITED"},{"lang":"hk","v":"郵道(香港)有限公司"}],"company_since":"2000-06-21","company_dissolved":"2006-01-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721196","names":[{"lang":"en","v":"YUWOO ENTERPRISES (HK) LIMITED"},{"lang":"hk","v":"裕和企業(香港)有限公司"}],"company_since":"2000-06-21","company_dissolved":"2004-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"721041","names":[{"lang":"en","v":"UNIWAY (ASIA PACIFIC) COMPANY LIMITED"},{"lang":"hk","v":"聯威(亞太)有限公司"}],"company_since":"2000-06-21","company_dissolved":"2003-01-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721026","names":[{"lang":"en","v":"UNITED GLORY KNITTING LIMITED"},{"lang":"hk","v":"聯昌針織有限公司"}],"company_since":"2000-06-21","company_dissolved":"2009-11-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"721239","names":[{"lang":"en","v":"WAI YIP GAS ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"偉業氣體工程有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"721051","names":[{"lang":"en","v":"ZEPPELIN TECH CAPITAL LIMITED"},{"lang":"hk","v":"卓凌科技融資有限公司"}],"company_since":"2000-06-21","company_dissolved":"2018-03-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"721233","names":[{"lang":"en","v":"KIN WING MOTOR ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"健榮汽車工程有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"721242","names":[{"lang":"en","v":"NGAI SHING ENTERPRISE COMPANY LIMITED"},{"lang":"hk","v":"藝成企業有限公司"}],"company_since":"2000-06-21","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
