{"tax_id":"839823","names":[{"lang":"en","v":"CENTURY POWER TECHNOLOGY (GROUP) LIMITED"},{"lang":"hk","v":"世動科技(集團)有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839655","names":[{"lang":"en","v":"CHAMPION UNION (CHINA) COMPANY LIMITED"},{"lang":"hk","v":"毅豐聯合(中國)有限公司"}],"company_since":"2003-03-19","company_dissolved":"2016-12-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839801","names":[{"lang":"en","v":"CHAPLUCK INVESTMENTS LIMITED"},{"lang":"hk","v":"祥煌投資有限公司"}],"company_since":"2003-03-19","company_dissolved":"2011-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839902","names":[{"lang":"en","v":"CHEER POWER TECHNOLOGY DEVELOPMENT LIMITED"},{"lang":"hk","v":"展毅科技發展有限公司"}],"company_since":"2003-03-19","company_dissolved":"2005-04-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839614","names":[{"lang":"en","v":"CHEERFUL ENTERPRISES TRADING LIMITED"},{"lang":"hk","v":"綵豐貿易有限公司"}],"company_since":"2003-03-19","company_dissolved":"2006-05-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839696","names":[{"lang":"en","v":"CHINA CONNECTOR LIMITED"},{"lang":"hk","v":"濠中有限公司"}],"company_since":"2003-03-19","company_dissolved":"2010-04-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839680","names":[{"lang":"en","v":"CHINA FOCUS INTERNATIONAL LIMITED (d2006-09-29)"},{"lang":"hk","v":"華科國際有限公司"}],"company_since":"2003-03-19","company_dissolved":"2006-09-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839763","names":[{"lang":"en","v":"CHINA LINE DEVELOPMENT LIMITED (d2010-10-15)"},{"lang":"hk","v":"中略發展有限公司"}],"company_since":"2003-03-19","company_dissolved":"2010-10-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839898","names":[{"lang":"en","v":"CHINA POWER TECHNOLOGY DEVELOPMENT LIMITED"},{"lang":"hk","v":"華權科技發展有限公司"}],"company_since":"2003-03-19","company_dissolved":"2013-05-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839983","names":[{"lang":"en","v":"CHINA RICHLY TRADING LIMITED"},{"lang":"hk","v":"宏華貿易有限公司"}],"company_since":"2003-03-19","company_dissolved":"2004-04-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839966","names":[{"lang":"en","v":"CEEDEN INTERNATIONAL TRADING COMPANY LIMITED"},{"lang":"hk","v":"尚宏國際貿易有限公司"}],"company_since":"2003-03-19","company_dissolved":"2009-06-05","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839813","names":[{"lang":"en","v":"CHINA SOFTWARE INVESTMENT (ASIA) LIMITED"},{"lang":"hk","v":"中國軟件投資(亞洲)有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839897","names":[{"lang":"en","v":"CHINA STEP TECHNOLOGY DEVELOPMENT LIMITED"},{"lang":"hk","v":"上華科技發展有限公司"}],"company_since":"2003-03-19","company_dissolved":"2006-12-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839945","names":[{"lang":"en","v":"CHINA VANTAGE CONSULTANTS LIMITED (d2009-06-26)"},{"lang":"hk","v":"益華顧問有限公司"}],"company_since":"2003-03-19","company_dissolved":"2009-06-26","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839896","names":[{"lang":"en","v":"CHINA SUCCESS TECHNOLOGY DEVELOPMENT LIMITED (d2004-08-13)"},{"lang":"hk","v":"中成科技發展有限公司"}],"company_since":"2003-03-19","company_dissolved":"2004-08-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839673","names":[{"lang":"en","v":"CENTAK HOLDINGS LIMITED"},{"lang":"hk","v":"中德控股有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-05-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839760","names":[{"lang":"en","v":"CHINAPLUS DESIGN CONSULTANT (H.K.) LIMITED"},{"lang":"hk","v":"紅流設計顧問有限公司"}],"company_since":"2003-03-19","company_dissolved":"2005-03-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839982","names":[{"lang":"en","v":"CHINAPORT SHIPPING LIMITED"},{"lang":"hk","v":"中寶船務有限公司"}],"company_since":"2003-03-19","company_dissolved":"2009-12-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839694","names":[{"lang":"en","v":"CHINESE DEVELOPMENT GROUP LIMITED"},{"lang":"hk","v":"新華發展集團有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839697","names":[{"lang":"en","v":"CHINESE FOCUS LIMITED"},{"lang":"hk","v":"兆綽有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839752","names":[{"lang":"en","v":"CHANG HAO SHIPPING COMPANY LIMITED"},{"lang":"hk","v":"昌浩船務有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839879","names":[{"lang":"en","v":"CHINESE SMARTER LIMITED"},{"lang":"hk","v":"志合有限公司"}],"company_since":"2003-03-19","company_dissolved":"2005-08-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839743","names":[{"lang":"en","v":"CHP INTERNATIONAL COMPANY LIMITED"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839687","names":[{"lang":"en","v":"CHAMPION GLOBAL HOLDINGS LIMITED"},{"lang":"hk","v":"彩暉環球控股有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839650","names":[{"lang":"en","v":"CINEWORLD INTERNATIONAL LIMITED (d2009-06-26)"}],"company_since":"2003-03-19","company_dissolved":"2009-06-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839923","names":[{"lang":"en","v":"COM UNITED INDUSTRIAL LIMITED"},{"lang":"hk","v":"康聯工貿有限公司"}],"company_since":"2003-03-19","company_dissolved":"2007-11-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839576","names":[{"lang":"en","v":"CHINA DA HENG GROUP (HK) LIMITED"},{"lang":"hk","v":"中國大恒集團(香港)有限公司"}],"company_since":"2003-03-19","company_dissolved":"2014-08-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839695","names":[{"lang":"en","v":"CREATION DEVELOPMENT GROUP LIMITED"},{"lang":"hk","v":"創新發展投資有限公司"}],"company_since":"2003-03-19","company_dissolved":"2015-05-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"839576","names":[{"lang":"en","v":"CHINA DA HENG GROUP (HK) LIMITED"},{"lang":"hk","v":"中國大恒集團(香港)有限公司"}],"company_since":"2003-03-19","company_dissolved":"2014-08-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839680","names":[{"lang":"en","v":"CHINA FOCUS INTERNATIONAL LIMITED (d2006-09-29)"},{"lang":"hk","v":"華科國際有限公司"}],"company_since":"2003-03-19","company_dissolved":"2006-09-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839899","names":[{"lang":"en","v":"CHINA MIND TECHNOLOGY DEVELOPMENT LIMITED"},{"lang":"hk","v":"中思科技發展有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839898","names":[{"lang":"en","v":"CHINA POWER TECHNOLOGY DEVELOPMENT LIMITED"},{"lang":"hk","v":"華權科技發展有限公司"}],"company_since":"2003-03-19","company_dissolved":"2013-05-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839752","names":[{"lang":"en","v":"CHANG HAO SHIPPING COMPANY LIMITED"},{"lang":"hk","v":"昌浩船務有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839897","names":[{"lang":"en","v":"CHINA STEP TECHNOLOGY DEVELOPMENT LIMITED"},{"lang":"hk","v":"上華科技發展有限公司"}],"company_since":"2003-03-19","company_dissolved":"2006-12-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839896","names":[{"lang":"en","v":"CHINA SUCCESS TECHNOLOGY DEVELOPMENT LIMITED (d2004-08-13)"},{"lang":"hk","v":"中成科技發展有限公司"}],"company_since":"2003-03-19","company_dissolved":"2004-08-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839945","names":[{"lang":"en","v":"CHINA VANTAGE CONSULTANTS LIMITED (d2009-06-26)"},{"lang":"hk","v":"益華顧問有限公司"}],"company_since":"2003-03-19","company_dissolved":"2009-06-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839943","names":[{"lang":"en","v":"CHEER GAIN GARMENT FACTORY (HONG KONG) LIMITED"},{"lang":"hk","v":"千達製衣廠(香港)有限公司"}],"company_since":"2003-03-19","company_dissolved":"2014-01-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"839694","names":[{"lang":"en","v":"CHINESE DEVELOPMENT GROUP LIMITED"},{"lang":"hk","v":"新華發展集團有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"839834","names":[{"lang":"en","v":"CHEONG FAI HOME PRODUCTS LIMITED"},{"lang":"hk","v":"昌輝家庭用品有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839872","names":[{"lang":"en","v":"CHINESE INVESTMENT ENTERPRISES LIMITED"},{"lang":"hk","v":"新華投資企業有限公司"}],"company_since":"2003-03-19","company_dissolved":"2009-02-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839879","names":[{"lang":"en","v":"CHINESE SMARTER LIMITED"},{"lang":"hk","v":"志合有限公司"}],"company_since":"2003-03-19","company_dissolved":"2005-08-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839984","names":[{"lang":"en","v":"CHINESE TRADING GROUP LIMITED"},{"lang":"hk","v":"中華貿易集團有限公司"}],"company_since":"2003-03-19","company_dissolved":"2018-12-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839696","names":[{"lang":"en","v":"CHINA CONNECTOR LIMITED"},{"lang":"hk","v":"濠中有限公司"}],"company_since":"2003-03-19","company_dissolved":"2010-04-23","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839907","names":[{"lang":"en","v":"CHUNG DA ELECTRONIC (H.K.) LIMITED"},{"lang":"hk","v":"創達電子(香港)有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839650","names":[{"lang":"en","v":"CINEWORLD INTERNATIONAL LIMITED (d2009-06-26)"}],"company_since":"2003-03-19","company_dissolved":"2009-06-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839871","names":[{"lang":"en","v":"CHINA HOLDINGS DEVELOPMENT LIMITED"},{"lang":"hk","v":"中國集團發展有限公司"}],"company_since":"2003-03-19","company_dissolved":"2006-03-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839923","names":[{"lang":"en","v":"COM UNITED INDUSTRIAL LIMITED"},{"lang":"hk","v":"康聯工貿有限公司"}],"company_since":"2003-03-19","company_dissolved":"2007-11-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839740","names":[{"lang":"en","v":"CP RESOURCES COMPANY LIMITED"}],"company_since":"2003-03-19","company_dissolved":"2006-10-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839763","names":[{"lang":"en","v":"CHINA LINE DEVELOPMENT LIMITED (d2010-10-15)"},{"lang":"hk","v":"中略發展有限公司"}],"company_since":"2003-03-19","company_dissolved":"2010-10-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839695","names":[{"lang":"en","v":"CREATION DEVELOPMENT GROUP LIMITED"},{"lang":"hk","v":"創新發展投資有限公司"}],"company_since":"2003-03-19","company_dissolved":"2015-05-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839797","names":[{"lang":"en","v":"CRYSTAL DESIGN HOUSE (FAR EAST) INTERNATIONAL CORPORATION LIMITED"},{"lang":"hk","v":"盈采(遠東)國際集團有限公司"}],"company_since":"2003-03-19","company_dissolved":"2009-08-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839894","names":[{"lang":"en","v":"DAILY KING TECHNOLOGY DEVELOPMENT LIMITED"},{"lang":"hk","v":"日毅科技發展有限公司"}],"company_since":"2003-03-19","company_dissolved":"2009-08-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839983","names":[{"lang":"en","v":"CHINA RICHLY TRADING LIMITED"},{"lang":"hk","v":"宏華貿易有限公司"}],"company_since":"2003-03-19","company_dissolved":"2004-04-02","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839621","names":[{"lang":"en","v":"DASING SHOES LIMITED"},{"lang":"hk","v":"達昇鞋業有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839612","names":[{"lang":"en","v":"DAVID TOYS AND GIFTS COMPANY LIMITED"},{"lang":"hk","v":"益得玩具禮品有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-04-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839813","names":[{"lang":"en","v":"CHINA SOFTWARE INVESTMENT (ASIA) LIMITED"},{"lang":"hk","v":"中國軟件投資(亞洲)有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839931","names":[{"lang":"en","v":"DAYS (H.K.) INT'L DRESS LIMITED"},{"lang":"hk","v":"德仕(香港)國際服飾有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839700","names":[{"lang":"en","v":"DESIGN TEN DESIGN LIMITED"},{"lang":"hk","v":"設計廳設計有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"840005","names":[{"lang":"en","v":"CHEUNG MAN FIRE ENGINEERING CONSULTANT CO., LIMITED"},{"lang":"hk","v":"張文消防工程顧問有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"839697","names":[{"lang":"en","v":"CHINESE FOCUS LIMITED"},{"lang":"hk","v":"兆綽有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839959","names":[{"lang":"en","v":"EARTH-LINK ENGINEERING (HK) LIMITED"},{"lang":"hk","v":"盈基工程(香港)有限公司"}],"company_since":"2003-03-19","company_dissolved":"2010-11-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839963","names":[{"lang":"en","v":"EARTH-LINK TECHNOLOGY (HK) LIMITED"},{"lang":"hk","v":"盈基企業(香港)有限公司"}],"company_since":"2003-03-19","company_dissolved":"2010-11-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839574","names":[{"lang":"en","v":"EAGLE SPEED (HOLDINGS) LIMITED"},{"lang":"hk","v":"鵬程(控股)有限公司"}],"company_since":"2003-03-19","company_dissolved":"2005-09-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839743","names":[{"lang":"en","v":"CHP INTERNATIONAL COMPANY LIMITED"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839930","names":[{"lang":"en","v":"EAST RAINBOW INT'L GROUP LIMITED"},{"lang":"hk","v":"東方虹國際集團有限公司"}],"company_since":"2003-03-19","company_dissolved":"2010-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839998","names":[{"lang":"en","v":"CHUN TAT (CHINA HONG KONG) TRANS LIMITED"},{"lang":"hk","v":"駿達(中港)貨運有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839978","names":[{"lang":"en","v":"EASTERN FUND CORPORATION LIMITED"},{"lang":"hk","v":"東資有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839643","names":[{"lang":"en","v":"EASTERN GREAT WALL INTERNATIONAL LIMITED"},{"lang":"hk","v":"長城(東和)國際有限公司"}],"company_since":"2003-03-19","company_dissolved":"2005-03-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839885","names":[{"lang":"en","v":"EASTERN LEADING LIMITED"},{"lang":"hk","v":"建啓有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-02-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"839582","names":[{"lang":"en","v":"EURO WEDDING SERVICES COMPANY LIMITED"},{"lang":"hk","v":"歐陸婚紗攝影有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839990","names":[{"lang":"en","v":"EVER GAINER LIMITED"},{"lang":"hk","v":"永富達有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839843","names":[{"lang":"en","v":"EVER SHINE TRADING (ASIA) LIMITED"},{"lang":"hk","v":"栢輝貿易(亞洲)有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839677","names":[{"lang":"en","v":"EVER SMARTLY LIMITED"},{"lang":"hk","v":"永聯昌有限公司"}],"company_since":"2003-03-19","company_dissolved":"2009-08-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"839992","names":[{"lang":"en","v":"EXCEL BRIGHT INDUSTRIAL LIMITED"},{"lang":"hk","v":"興輝實業有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-02-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839853","names":[{"lang":"en","v":"FACTOTUM (HONG KONG) LIMITED"}],"company_since":"2003-03-19","company_dissolved":"2016-03-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839926","names":[{"lang":"en","v":"FAR EAST INTERNATIONAL TOURISM IM/EX LIMITED"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839713","names":[{"lang":"en","v":"EASY ON LOGISTICS LIMITED"},{"lang":"hk","v":"裕安物流有限公司"}],"company_since":"2003-03-19","company_dissolved":"2013-08-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839958","names":[{"lang":"en","v":"EARTH-LINK WASTE MANAGEMENT (HK) LIMITED"},{"lang":"hk","v":"盈基廢料處理(香港)有限公司"}],"company_since":"2003-03-19","company_dissolved":"2010-11-26","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839957","names":[{"lang":"en","v":"FINE WAY (CHINA) LIMITED (d2006-10-20)"},{"lang":"hk","v":"威明(中國)有限公司"}],"company_since":"2003-03-19","company_dissolved":"2006-10-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"839971","names":[{"lang":"en","v":"EASYBUSY LIMITED"},{"lang":"hk","v":"順發有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839624","names":[{"lang":"en","v":"ELITE TARGET INVESTMENT LIMITED"},{"lang":"hk","v":"正馳投資有限公司"}],"company_since":"2003-03-19","company_dissolved":"2012-01-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839602","names":[{"lang":"en","v":"FLEXICARE MEDICAL ASIA LIMITED"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839985","names":[{"lang":"en","v":"FOREVER CHINA TRADING LIMITED"},{"lang":"hk","v":"榮華貿易有限公司"}],"company_since":"2003-03-19","company_dissolved":"2019-11-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839888","names":[{"lang":"en","v":"FOREVER HERO LIMITED"},{"lang":"hk","v":"英傑有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839873","names":[{"lang":"en","v":"FOREVER INVESTMENT GROUP LIMITED (d2008-08-29)"},{"lang":"hk","v":"恒豐投資國際有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839714","names":[{"lang":"en","v":"EASY ON TRANSPORTATION LIMITED"},{"lang":"hk","v":"裕安運輸有限公司"}],"company_since":"2003-03-19","company_dissolved":"2012-07-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839790","names":[{"lang":"en","v":"FOUNDER NETWORK LIMITED"},{"lang":"hk","v":"方正網絡有限公司"}],"company_since":"2003-03-19","company_dissolved":"2012-04-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839893","names":[{"lang":"en","v":"EVER CREATION TECHNOLOGY DEVELOPMENT LIMITED"},{"lang":"hk","v":"恒創科技發展有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839967","names":[{"lang":"en","v":"FRANCE BIAONU CLOTHING GROUP FAREAST LIMITED"},{"lang":"hk","v":"法國彪奴服裝集團遠東有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839592","names":[{"lang":"en","v":"FRANCE GOLDEN.BAND DRESS LIMITED"},{"lang":"hk","v":"法國高登‧邦德服飾有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839717","names":[{"lang":"en","v":"FULL CREATION (CHINA) LIMITED"},{"lang":"hk","v":"創豐(中國)有限公司"}],"company_since":"2003-03-19","company_dissolved":"2010-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839781","names":[{"lang":"en","v":"GEO-TECH SOLUTIONS CO. LIMITED"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839827","names":[{"lang":"en","v":"FARTAI (CHINA) LIMITED"},{"lang":"hk","v":"科泰(中國)有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839946","names":[{"lang":"en","v":"FAST CONSULTANTS LIMITED (HK)"},{"lang":"hk","v":"高捷顧問有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839941","names":[{"lang":"en","v":"FINE IMAGE LIMITED (d2008-08-29)"},{"lang":"hk","v":"拓耀有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839859","names":[{"lang":"en","v":"GLOBAL ALUMINIUM HOLDINGS LIMITED"},{"lang":"hk","v":"高得寶控股有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-01-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839669","names":[{"lang":"en","v":"GLOBAL CITY TRADING LIMITED (d2007-05-18)"},{"lang":"hk","v":"興港貿易有限公司"}],"company_since":"2003-03-19","company_dissolved":"2007-05-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839715","names":[{"lang":"en","v":"FINE OCEAN LOGISTICS LIMITED"},{"lang":"hk","v":"海明物流有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839856","names":[{"lang":"en","v":"GLORIA TRANSPORTATION COMPANY LIMITED"},{"lang":"hk","v":"榮基貨運有限公司"}],"company_since":"2003-03-19","company_dissolved":"2006-11-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839702","names":[{"lang":"en","v":"GOLD &amp; MILE (ASIA) LIMITED"}],"company_since":"2003-03-19","company_dissolved":"2013-03-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839882","names":[{"lang":"en","v":"FIRST CREATIVE LIMITED (d2009-04-17)"},{"lang":"hk","v":"鴻信有限公司"}],"company_since":"2003-03-19","company_dissolved":"2009-04-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839652","names":[{"lang":"en","v":"GOLD PACK LIMITED"},{"lang":"hk","v":"金栢有限公司"}],"company_since":"2003-03-19","company_dissolved":"2010-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839995","names":[{"lang":"en","v":"GOLD POWER TECHNOLOGY DEVELOPMENT LIMITED"},{"lang":"hk","v":"金毅科技發展有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"839906","names":[{"lang":"en","v":"FORTUNE AND HARMONY INTERNATIONAL LIMITED"},{"lang":"hk","v":"瑞祥和國際有限公司"}],"company_since":"2003-03-19","company_dissolved":"2009-08-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839857","names":[{"lang":"en","v":"GOLDEN BRIDGE PROPERTY (CHINA) AGENCY CONSULTANT LIMITED"},{"lang":"hk","v":"金橋物業(中國)代理顧問有限公司"}],"company_since":"2003-03-19","company_dissolved":"2005-08-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839877","names":[{"lang":"en","v":"FORTUNE INVESTMENT GROUP LIMITED (HK)"},{"lang":"hk","v":"永利投資集團有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839699","names":[{"lang":"en","v":"GOLDEN GROUP (ASIA) LIMITED"},{"lang":"hk","v":"金進(亞洲)有限公司"}],"company_since":"2003-03-19","company_dissolved":"2012-04-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839878","names":[{"lang":"en","v":"GOLDEN INVESTMENT INTERNATIONAL LIMITED"},{"lang":"hk","v":"金豐投資國際有限公司"}],"company_since":"2003-03-19","company_dissolved":"2018-12-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839791","names":[{"lang":"en","v":"GOLDEN MASTERTEAM NETWORK (INT'L) LIMITED"},{"lang":"hk","v":"鏘域國際有限公司"}],"company_since":"2003-03-19","company_dissolved":"2009-08-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839756","names":[{"lang":"en","v":"GOLDHILL INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"金峰國際集團有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839718","names":[{"lang":"en","v":"GOOD TIME FINANCE LIMITED"},{"lang":"hk","v":"天時財務有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839836","names":[{"lang":"en","v":"GOOD TRANS LOGISTICS COMPANY LIMITED"},{"lang":"hk","v":"佳運物流有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839910","names":[{"lang":"en","v":"FULLBEST INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"富嘉國際集團有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839664","names":[{"lang":"en","v":"GATEWAY FORTUNE INVESTMENT LIMITED"},{"lang":"hk","v":"佳運投資有限公司"}],"company_since":"2003-03-19","company_dissolved":"2007-04-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839874","names":[{"lang":"en","v":"GOLDEN GAINER LIMITED"},{"lang":"hk","v":"金富豪有限公司"}],"company_since":"2003-03-19","company_dissolved":"2009-05-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839835","names":[{"lang":"en","v":"GERMAN LM LIFT MANUFACTURING GMBH COMPANY LIMITED"},{"lang":"hk","v":"德國莫尼克電梯製造有限公司"}],"company_since":"2003-03-19","company_dissolved":"2015-05-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839719","names":[{"lang":"en","v":"GRAND OCEAN LOGISTICS LIMITED"},{"lang":"hk","v":"宏海物流有限公司"}],"company_since":"2003-03-19","company_dissolved":"2013-11-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839665","names":[{"lang":"en","v":"GREAT CHINA INTERNATIONAL LOGISTICS LIMITED"},{"lang":"hk","v":"大中華國際物流有限公司"}],"company_since":"2003-03-19","company_dissolved":"2009-08-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839775","names":[{"lang":"en","v":"GREAT LEADER TRADING LIMITED (d2012-04-20)"},{"lang":"hk","v":"永峰貿易有限公司"}],"company_since":"2003-03-19","company_dissolved":"2012-04-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839812","names":[{"lang":"en","v":"GREEN INNOTECH ENTERPRISE LIMITED"},{"lang":"hk","v":"柏森企業有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839688","names":[{"lang":"en","v":"GOLD RICHLY DEVELOPMENT LIMITED"},{"lang":"hk","v":"金利佳發展有限公司"}],"company_since":"2003-03-19","company_dissolved":"2013-05-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839909","names":[{"lang":"en","v":"GREENTECH (HONG KONG) LIMITED"},{"lang":"hk","v":"翠慧科技(香港)有限公司"}],"company_since":"2003-03-19","company_dissolved":"2004-08-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839778","names":[{"lang":"en","v":"GOLD YEAR LIMITED (d2004-08-13)"},{"lang":"hk","v":"金耀有限公司"}],"company_since":"2003-03-19","company_dissolved":"2004-08-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839642","names":[{"lang":"en","v":"H.K. SUNNY (INT'L) FINERY DEVELOPMENT LIMITED"},{"lang":"hk","v":"香港紳綺(國際)服飾發展有限公司"}],"company_since":"2003-03-19","company_dissolved":"2012-04-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839864","names":[{"lang":"en","v":"HANG SON (INTERNATIONAL) DEVELOPMENT CO., LIMITED"},{"lang":"hk","v":"恒森(國際)發展有限公司"}],"company_since":"2003-03-19","company_dissolved":"2013-05-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"839918","names":[{"lang":"en","v":"GOLDEN YEAR HOLDINGS LIMITED"},{"lang":"hk","v":"金景集團有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839977","names":[{"lang":"en","v":"HERO POWER LIMITED (d2008-08-29)"},{"lang":"hk","v":"匯雄有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839785","names":[{"lang":"en","v":"HE SHENG CULTURE AND COMMUNICATION (HK) CO., LIMITED (d2004-09-03)"},{"lang":"hk","v":"禾盛文化傳播(香港)有限公司"}],"company_since":"2003-03-19","company_dissolved":"2004-09-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839721","names":[{"lang":"en","v":"HIGH HARVEST (CHINA) LIMITED"},{"lang":"hk","v":"高豐(中國)有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"839981","names":[{"lang":"en","v":"GRACEWELL LIMITED (HK)"},{"lang":"hk","v":"恩偉有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839993","names":[{"lang":"en","v":"GRAND DRAGON TECHNOLOGY DEVELOPMENT LIMITED"},{"lang":"hk","v":"浩龍科技發展有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"840010","names":[{"lang":"en","v":"HOME INTERIOR'S LIMITED"},{"lang":"hk","v":"家創作室內設計有限公司"}],"company_since":"2003-03-19","company_dissolved":"2015-10-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839884","names":[{"lang":"en","v":"GRAND LINKER ENTERPRISES LIMITED"},{"lang":"hk","v":"宏聯企業有限公司"}],"company_since":"2003-03-19","company_dissolved":"2012-04-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839647","names":[{"lang":"en","v":"HON WING PAPER PRODUCTS COMPANY LIMITED"},{"lang":"hk","v":"漢榮紙品實業有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839653","names":[{"lang":"en","v":"GRAND SUN LIMITED"},{"lang":"hk","v":"駿陽有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839784","names":[{"lang":"en","v":"GRASSICAL BUILDING MATERIALS (ENGINEERING) LIMITED"},{"lang":"hk","v":"格式高建築材料(工程)有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839786","names":[{"lang":"en","v":"HONG KONG HIDDEN LAKE ENTERPRISE COMPANY LIMITED"},{"lang":"hk","v":"香港瀚潤實業有限公司"}],"company_since":"2003-03-19","company_dissolved":"2010-01-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839766","names":[{"lang":"en","v":"HONG KONG ICE ACTIVITIES ASSOCIATION LIMITED"},{"lang":"hk","v":"香港冰上運動總會有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"839900","names":[{"lang":"en","v":"HONG KONG LI ANG GENE POWER COMPANY LIMITED"},{"lang":"hk","v":"香港里昂基因動力有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839631","names":[{"lang":"en","v":"HONG KONG MILLION HONOUR INTERNATIONAL LIMITED"},{"lang":"hk","v":"香港億榮國際有限公司"}],"company_since":"2003-03-19","company_dissolved":"2012-04-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"839839","names":[{"lang":"en","v":"GRP VI LIMITED"},{"lang":"hk","v":"滙江廣景有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839754","names":[{"lang":"en","v":"HONG KONG WING LUNG WAI FASHION LIMITED"},{"lang":"hk","v":"香港永龍威服裝有限公司"}],"company_since":"2003-03-19","company_dissolved":"2012-04-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839751","names":[{"lang":"en","v":"HONG KONG ZHONGSEN INTERNATIONAL FINANCE MANAGEMENT LIMITED"},{"lang":"hk","v":"香港衆森國際財務管理有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839620","names":[{"lang":"en","v":"HONG LEONG CARPARK LIMITED"},{"lang":"hk","v":"豐隆停車場有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839682","names":[{"lang":"en","v":"HARBOUR VICTORY LIMITED (d2012-06-15)"},{"lang":"hk","v":"凱港有限公司"}],"company_since":"2003-03-19","company_dissolved":"2012-06-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839840","names":[{"lang":"en","v":"HONSEC INTERNATIONAL LIMITED"},{"lang":"hk","v":"瀚斯國際有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839979","names":[{"lang":"en","v":"HOUSTON CENTURY INTERNATIONAL LIMITED"},{"lang":"hk","v":"浩升國際有限公司"}],"company_since":"2003-03-19","company_dissolved":"2016-12-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"839632","names":[{"lang":"en","v":"HIN WAN BUS MANAGEMENT LIMITED"},{"lang":"hk","v":"顯運巴士管理有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839818","names":[{"lang":"en","v":"HUGE CHINA TECHNOLOGY DEVELOPMENT LIMITED"},{"lang":"hk","v":"鉅華科技發展有限公司"}],"company_since":"2003-03-19","company_dissolved":"2005-07-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839968","names":[{"lang":"en","v":"HK EURASIA MEDICAL TECH INT'L GROUP LIMITED"},{"lang":"hk","v":"香港歐亞醫學技術國際集團有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839722","names":[{"lang":"en","v":"HUGE SMART (CHINA) LIMITED"},{"lang":"hk","v":"浩俊(中國)有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839606","names":[{"lang":"en","v":"HOMESMART COMPANY LIMITED"},{"lang":"hk","v":"家智有限公司"}],"company_since":"2003-03-19","company_dissolved":"2012-09-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839626","names":[{"lang":"en","v":"HUNTER POWER INTERNATIONAL LIMITED"},{"lang":"hk","v":"衡權國際有限公司"}],"company_since":"2003-03-19","company_dissolved":"2005-12-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839628","names":[{"lang":"en","v":"HONG KONG CHINART (OMNITRON) INDUSTRIAL COMPANY LIMITED"},{"lang":"hk","v":"香港中藝(奧創)實業有限公司"}],"company_since":"2003-03-19","company_dissolved":"2016-02-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"840011","names":[{"lang":"en","v":"IN AND OUT FOOTWEAR LIMITED"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839794","names":[{"lang":"en","v":"INDEX INTERNATIONAL (H.K.) CO. LIMITED"},{"lang":"hk","v":"殷域國際有限公司"}],"company_since":"2003-03-19","company_dissolved":"2009-08-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839593","names":[{"lang":"en","v":"ITALY HENGDESIWO DRESS LIMITED"},{"lang":"hk","v":"意大利亨德斯沃服飾有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"840003","names":[{"lang":"en","v":"HONG KONG MAIDA TRADE CO., LIMITED"},{"lang":"hk","v":"香港邁達貿易有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839880","names":[{"lang":"en","v":"J.B. INTERNATIONAL SOURCING LIMITED"}],"company_since":"2003-03-19","company_dissolved":"2013-05-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839962","names":[{"lang":"en","v":"HONG KONG NORTH INTERNATIONAL INVESTMENT &amp; DEVELOPMENT LIMITED"},{"lang":"hk","v":"香港北方國際投資發展有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839955","names":[{"lang":"en","v":"JELE (HONGKONG) OPTICAL ELECTRONIC TECHNOLOGY LIMITED"},{"lang":"hk","v":"香港捷朗光電科技有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-09-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839676","names":[{"lang":"en","v":"JET POWER LIMITED"},{"lang":"hk","v":"宏勝有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839573","names":[{"lang":"en","v":"HONG KONG YAN HOI TECHNOLOGY HOLDINGS LIMITED"},{"lang":"hk","v":"香港欣凱科技股份有限公司"}],"company_since":"2003-03-19","company_dissolved":"2018-12-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839883","names":[{"lang":"en","v":"EASTERN LINKER LIMITED"},{"lang":"hk","v":"利昌行有限公司"}],"company_since":"2003-03-19","company_dissolved":"2006-08-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839905","names":[{"lang":"en","v":"HONGBANG (CHINA) LIMITED"},{"lang":"hk","v":"宏邦(中國)有限公司"}],"company_since":"2003-03-19","company_dissolved":"2009-10-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839586","names":[{"lang":"en","v":"HONGKONG LANGXIANG FURNITURE INT'L GROUP LIMITED"},{"lang":"hk","v":"香港朗香家私國際集團有限公司"}],"company_since":"2003-03-19","company_dissolved":"2015-05-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839723","names":[{"lang":"en","v":"JOY SEA LOGISTICS LIMITED"},{"lang":"hk","v":"海怡物流有限公司"}],"company_since":"2003-03-19","company_dissolved":"2010-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839589","names":[{"lang":"en","v":"JOPLIN ADVISORS, LIMITED"},{"lang":"hk","v":"卓英諮詢有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"840015","names":[{"lang":"en","v":"Hot In A Pot Group Limited"},{"lang":"hk","v":"滾得棧飲食集團有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839833","names":[{"lang":"en","v":"JUNLONG INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"均朗國際控股有限公司"}],"company_since":"2003-03-19","company_dissolved":"2009-07-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839619","names":[{"lang":"en","v":"HONG KONG BAINIANLI GROUP LIMITED"},{"lang":"hk","v":"香港百年利集團有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"839793","names":[{"lang":"en","v":"KAI SHING INVESTMENT (H.K.) LIMITED"},{"lang":"hk","v":"啓成投資(香港)有限公司"}],"company_since":"2003-03-19","company_dissolved":"2004-08-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"839782","names":[{"lang":"en","v":"KAMFUL LIMITED"},{"lang":"hk","v":"泰宏有限公司"}],"company_since":"2003-03-19","company_dissolved":"2013-06-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839937","names":[{"lang":"en","v":"KEEPTIME INDUSTRIAL (ASIA) CO., LIMITED (d2013-08-16)"},{"lang":"hk","v":"凱泰實業(亞洲)有限公司"}],"company_since":"2003-03-19","company_dissolved":"2013-08-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839594","names":[{"lang":"en","v":"ITALY VALENSINA INT'L (HK) LIMITED"},{"lang":"hk","v":"意大利華倫聖羅國際(香港)有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839724","names":[{"lang":"en","v":"KING OCEAN SHIPPING LIMITED (d2008-08-29)"},{"lang":"hk","v":"宏海船務有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839645","names":[{"lang":"en","v":"KONG SENG PHARMACY (H.K.) CO. LIMITED"},{"lang":"hk","v":"廣生藥業(香港)有限公司"}],"company_since":"2003-03-19","company_dissolved":"2004-08-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839706","names":[{"lang":"en","v":"JESMAN LIMITED (d2008-11-21)"},{"lang":"hk","v":"俊獅有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-11-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839891","names":[{"lang":"en","v":"LAND MASTER (BEIJING) &amp; ASSOCIATES LIMITED"},{"lang":"hk","v":"伯樂行(北京)物業顧問有限公司"}],"company_since":"2003-03-19","company_dissolved":"2005-12-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839598","names":[{"lang":"en","v":"JFP (HOLDINGS) COMPANY LIMITED"},{"lang":"hk","v":"正鋒奔馬(控股)有限公司"}],"company_since":"2003-03-19","company_dissolved":"2004-05-07","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839964","names":[{"lang":"en","v":"LAURENTIA TECHNOLOGIES LIMITED"},{"lang":"hk","v":"羅倫科技有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839960","names":[{"lang":"en","v":"JIK ACCOUNTING SERVICES LIMITED"},{"lang":"hk","v":"精誠會計事務所有限公司"}],"company_since":"2003-03-19","company_dissolved":"2004-09-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839725","names":[{"lang":"en","v":"LEADWAY LOGISTICS LIMITED (d2017-10-20)"},{"lang":"hk","v":"領裕物流有限公司"}],"company_since":"2003-03-19","company_dissolved":"2017-10-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839726","names":[{"lang":"en","v":"LEADWELL FREIGHT SERVICES LIMITED"},{"lang":"hk","v":"恆裕貨運有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839727","names":[{"lang":"en","v":"LEADWELL TRANSPORTATION LIMITED"},{"lang":"hk","v":"領裕運輸有限公司"}],"company_since":"2003-03-19","company_dissolved":"2018-11-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839609","names":[{"lang":"en","v":"LIBRA INTERNATIONAL DEVELOPMENT CO., LIMITED"},{"lang":"hk","v":"天誠國際貿易發展有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"839846","names":[{"lang":"en","v":"K &amp; K LOGISTIC LIMITED"},{"lang":"hk","v":"山崎物流有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839933","names":[{"lang":"en","v":"LONG VICTORY HK INVESTMENT LIMITED"},{"lang":"hk","v":"長頡香港有限公司"}],"company_since":"2003-03-19","company_dissolved":"2018-05-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839595","names":[{"lang":"en","v":"LONGYEAR PUBLISHING CO., LIMITED"},{"lang":"hk","v":"龍一出版有限公司"}],"company_since":"2003-03-19","company_dissolved":"2010-11-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839708","names":[{"lang":"en","v":"LOYAL FRIEND METAL FACTORY LIMITED"},{"lang":"hk","v":"忠暉五金廠有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839986","names":[{"lang":"en","v":"JOIN WINNING (HONG KONG) LIMITED"},{"lang":"hk","v":"聯暉(香港)有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839613","names":[{"lang":"en","v":"JUNWEI INTERNATIONAL LIMITED"},{"lang":"hk","v":"君緯國際有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839603","names":[{"lang":"en","v":"KAISER (CHINA) LIMITED"},{"lang":"hk","v":"中碩有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839975","names":[{"lang":"en","v":"LUNG HEUNG WING COMPANY LIMITED"},{"lang":"hk","v":"龍向榮有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839742","names":[{"lang":"en","v":"KESWAY INVESTMENTS LIMITED"},{"lang":"hk","v":"祺嘉投資有限公司"}],"company_since":"2003-03-19","company_dissolved":"2007-06-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839587","names":[{"lang":"en","v":"Maidens International Limited"},{"lang":"hk","v":"仙采國際有限公司"}],"company_since":"2003-03-19","company_dissolved":"2010-08-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"839831","names":[{"lang":"en","v":"KIN MEI IRON WORKS CO., LIMITED"},{"lang":"hk","v":"堅美鋼鐵工程有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839649","names":[{"lang":"en","v":"MASSWAY SHIPPING COMPANY LIMITED"},{"lang":"hk","v":"進裕船務有限公司"}],"company_since":"2003-03-19","company_dissolved":"2012-04-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"840022","names":[{"lang":"en","v":"MBR SERVICES LIMITED"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839817","names":[{"lang":"en","v":"LEAD STATE TECHNOLOGY DEVELOPMENT LIMITED"},{"lang":"hk","v":"利邦科技發展有限公司"}],"company_since":"2003-03-19","company_dissolved":"2004-11-19","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839861","names":[{"lang":"en","v":"MEET LIMITED (d2012-04-20)"},{"lang":"hk","v":"匯域有限公司"}],"company_since":"2003-03-19","company_dissolved":"2012-04-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839974","names":[{"lang":"en","v":"LEADING PACIFIC LIMITED (d2008-08-29)"},{"lang":"hk","v":"星海有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839863","names":[{"lang":"en","v":"MING FUNG FRUIT MERCHANT (INTERNATIONAL) LIMITED"},{"lang":"hk","v":"明豐果欄(國際)有限公司"}],"company_since":"2003-03-19","company_dissolved":"2015-05-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"839608","names":[{"lang":"en","v":"LI'S MARINE PRODUCTS LIMITED"},{"lang":"hk","v":"李氏海產有限公司"}],"company_since":"2003-03-19","company_dissolved":"2011-01-25","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"839578","names":[{"lang":"en","v":"NEW EAST OCEAN INTERNATIONAL CO., LIMITED"},{"lang":"hk","v":"新東洋國際有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839940","names":[{"lang":"en","v":"LOYAL STATE CORPORATION LIMITED (d2008-08-29)"},{"lang":"hk","v":"良邦有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839729","names":[{"lang":"en","v":"LOYAL WILL (CHINA) LIMITED"},{"lang":"hk","v":"鴻志(中國)有限公司"}],"company_since":"2003-03-19","company_dissolved":"2005-12-02","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839811","names":[{"lang":"en","v":"NEW POINT TECHNOLOGY DEVELOPMENT LIMITED"},{"lang":"hk","v":"拓新科技發展有限公司"}],"company_since":"2003-03-19","company_dissolved":"2010-11-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"840009","names":[{"lang":"en","v":"MAINTOP INTERNATIONAL LOGISTICS LIMITED"},{"lang":"hk","v":"威達國際物流有限公司"}],"company_since":"2003-03-19","company_dissolved":"2009-08-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"840014","names":[{"lang":"en","v":"MAINTOP MANAGEMENT LIMITED (d2006-03-10)"},{"lang":"hk","v":"明達管理有限公司"}],"company_since":"2003-03-19","company_dissolved":"2006-03-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839815","names":[{"lang":"en","v":"MASTER WAY TECHNOLOGY DEVELOPMENT LIMITED"},{"lang":"hk","v":"萬威科技發展有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839671","names":[{"lang":"en","v":"OPPO INTERNATIONAL GROUP HONG KONG LIMITED"},{"lang":"hk","v":"奧寶國際集團香港有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839842","names":[{"lang":"en","v":"MESSAGE (WING SHUN) AIR-CONDITIONING ENGINEERING CO LIMITED"},{"lang":"hk","v":"瞬息(永順)冷氣工程有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839776","names":[{"lang":"en","v":"PACIFIC GAINER TRADING LIMITED"},{"lang":"hk","v":"盛寶貿易有限公司"}],"company_since":"2003-03-19","company_dissolved":"2006-04-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839597","names":[{"lang":"en","v":"MOMENTUM54 LIMITED (d2019-12-20)"}],"company_since":"2003-03-19","company_dissolved":"2019-12-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839615","names":[{"lang":"en","v":"MONLEND INTERNATIONAL (HONG KONG) LIMITED (d2008-08-29)"},{"lang":"hk","v":"夢倫國際(香港)有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839847","names":[{"lang":"en","v":"PACIFIC LINKER (HK) LIMITED"},{"lang":"hk","v":"金東遠(香港)有限公司"}],"company_since":"2003-03-19","company_dissolved":"2009-08-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839707","names":[{"lang":"en","v":"MONOPOLY INTERNATIONAL LIMITED (d2013-10-25)"},{"lang":"hk","v":"天煌國際有限公司"}],"company_since":"2003-03-19","company_dissolved":"2013-10-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839640","names":[{"lang":"en","v":"PACIFIC SOFTWARE HOLDING LIMITED"},{"lang":"hk","v":"太平洋軟件控股有限公司"}],"company_since":"2003-03-19","company_dissolved":"2017-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839761","names":[{"lang":"en","v":"MULTI-PHARM INDUSTRIAL LIMITED"},{"lang":"hk","v":"倍合實業有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839828","names":[{"lang":"en","v":"PALOMA INDUSTRIAL CO., LIMITED"},{"lang":"hk","v":"帕羅瑪實業有限公司"}],"company_since":"2003-03-19","company_dissolved":"2013-05-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839890","names":[{"lang":"en","v":"PENFUL LIMITED"},{"lang":"hk","v":"柏偉有限公司"}],"company_since":"2003-03-19","company_dissolved":"2004-12-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839860","names":[{"lang":"en","v":"Poly Modern TCM Research Institute Limited"},{"lang":"hk","v":"國大精研有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839969","names":[{"lang":"en","v":"POTENTIAL POWER (HK) INVESTMENT DEVELOPMENT LIMITED"},{"lang":"hk","v":"有潛(香港)投資發展有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"839659","names":[{"lang":"en","v":"ORIENT HEALTH &amp; FITNESS COMPANY LIMITED"},{"lang":"hk","v":"鎧鋒健身器材有限公司"}],"company_since":"2003-03-19","company_dissolved":"2016-09-23","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839796","names":[{"lang":"en","v":"OCEAN GAIN LOGISTICS LIMITED"},{"lang":"hk","v":"海達物流有限公司"}],"company_since":"2003-03-19","company_dissolved":"2009-08-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839730","names":[{"lang":"en","v":"OCEAN CHINA TRANSPORTATION LIMITED"},{"lang":"hk","v":"中海運輸有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839580","names":[{"lang":"en","v":"NEWONG LIMITED"}],"company_since":"2003-03-19","company_dissolved":"2015-11-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839648","names":[{"lang":"en","v":"MONTURY COMPANY LIMITED"},{"lang":"hk","v":"啓楓(中國)有限公司"}],"company_since":"2003-03-19","company_dissolved":"2012-04-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839799","names":[{"lang":"en","v":"R-GIRL INTERNATIONAL (HK) LIMITED"}],"company_since":"2003-03-19","company_dissolved":"2009-10-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"840013","names":[{"lang":"en","v":"PACIFIC LANE INVESTMENT LIMITED (d2007-06-22)"},{"lang":"hk","v":"長億投資有限公司"}],"company_since":"2003-03-19","company_dissolved":"2007-06-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839611","names":[{"lang":"en","v":"NSHUN INTERNATIONAL GROUP CO., LIMITED"},{"lang":"hk","v":"鴻順國際集團有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839656","names":[{"lang":"en","v":"REALAM INTERNATIONAL LIMITED"},{"lang":"hk","v":"滙林國際有限公司"}],"company_since":"2003-03-19","company_dissolved":"2006-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839789","names":[{"lang":"en","v":"REGAL LEADING LIMITED"},{"lang":"hk","v":"雄成有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839886","names":[{"lang":"en","v":"REGAL WINNER INVESTMENT LIMITED (d2004-08-20)"},{"lang":"hk","v":"創榮投資有限公司"}],"company_since":"2003-03-19","company_dissolved":"2004-08-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839911","names":[{"lang":"en","v":"REVE DE SOURBY LIMITED"}],"company_since":"2003-03-19","company_dissolved":"2007-08-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839771","names":[{"lang":"en","v":"RICHEST REGENT LIMITED"},{"lang":"hk","v":"冠強有限公司"}],"company_since":"2003-03-19","company_dissolved":"2010-02-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839731","names":[{"lang":"en","v":"RISE PROFIT (CHINA) LIMITED"},{"lang":"hk","v":"利陞(中國)有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839774","names":[{"lang":"en","v":"PRECISE GROUP LIMITED (d2007-07-13)"},{"lang":"hk","v":"悅卓有限公司"}],"company_since":"2003-03-19","company_dissolved":"2007-07-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839704","names":[{"lang":"en","v":"PRECISION (HK) LIMITED"},{"lang":"hk","v":"浩豐(香港)有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839837","names":[{"lang":"en","v":"SAYAMA INDUSTRIAL LIMITED"},{"lang":"hk","v":"狹山實業有限公司"}],"company_since":"2003-03-19","company_dissolved":"2005-12-16","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839758","names":[{"lang":"en","v":"SAYS I.T. COMPANY LIMITED"},{"lang":"hk","v":"交收信息科技有限公司"}],"company_since":"2003-03-19","company_dissolved":"2005-11-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839633","names":[{"lang":"en","v":"SBC SECRETARIAL LIMITED"}],"company_since":"2003-03-19","company_dissolved":"2016-08-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839629","names":[{"lang":"en","v":"SEA FLIGHT INTERNATIONAL LIMITED"},{"lang":"hk","v":"海翔國際有限公司"}],"company_since":"2003-03-19","company_dissolved":"2009-08-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"839875","names":[{"lang":"en","v":"R. A. K. CERAMICS (HONG KONG) LIMITED"},{"lang":"hk","v":"哈伊馬角(香港)陶瓷有限公司"}],"company_since":"2003-03-19","company_dissolved":"2010-07-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839772","names":[{"lang":"en","v":"SINO GAINER LIMITED (d2006-02-17)"},{"lang":"hk","v":"帝浩有限公司"}],"company_since":"2003-03-19","company_dissolved":"2006-02-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839927","names":[{"lang":"en","v":"POWER PROFESSIONAL PRODUCTION (HK) LIMITED"},{"lang":"hk","v":"博雅專業制作(香港)有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839976","names":[{"lang":"en","v":"REGAL CENTURY HOLDINGS LIMITED"},{"lang":"hk","v":"偉明集團有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839972","names":[{"lang":"en","v":"SINO PRIME LIMITED"},{"lang":"hk","v":"中樂有限公司"}],"company_since":"2003-03-19","company_dissolved":"2017-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839732","names":[{"lang":"en","v":"SINO VANTAGE (CHINA) LIMITED"},{"lang":"hk","v":"益華(中國)有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839934","names":[{"lang":"en","v":"SINOPEN PROFESSIONAL WRITING &amp; TRANSLATION SERVICES LIMITED"},{"lang":"hk","v":"神來筆專業撰譯服務有限公司"}],"company_since":"2003-03-19","company_dissolved":"2004-08-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"839764","names":[{"lang":"en","v":"SKYWORTH COMPANY LIMITED"},{"lang":"hk","v":"創思興業有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839596","names":[{"lang":"en","v":"S.A.N.C. LIMITED"}],"company_since":"2003-03-19","company_dissolved":"2006-06-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839987","names":[{"lang":"en","v":"SMART GAINER (HONG KONG) LIMITED"},{"lang":"hk","v":"佳裕(香港)有限公司"}],"company_since":"2003-03-19","company_dissolved":"2010-04-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839667","names":[{"lang":"en","v":"SMARTLY RICH LIMITED"},{"lang":"hk","v":"永利裕有限公司"}],"company_since":"2003-03-19","company_dissolved":"2014-08-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"839698","names":[{"lang":"en","v":"SOUTHERN AMOEBA STRATEGIC COMPANY LIMITED"},{"lang":"hk","v":"南方阿米巴傳訊有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"839916","names":[{"lang":"en","v":"SILVER LINK INTERNATIONAL LIMITED"},{"lang":"hk","v":"銀業國際有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839681","names":[{"lang":"en","v":"STAR INTEGRATED PROPERTY CONSULTANT LIMITED"},{"lang":"hk","v":"星光物業顧問行有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839806","names":[{"lang":"en","v":"STATE CONCEPT TECHNOLOGY DEVELOPMENT LIMITED"},{"lang":"hk","v":"啟邦科技發展有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839670","names":[{"lang":"en","v":"STRONG FUTURE LIMITED"},{"lang":"hk","v":"發裕有限公司"}],"company_since":"2003-03-19","company_dissolved":"2009-08-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839735","names":[{"lang":"en","v":"SUCCESS STAR (CHINA) LIMITED (d2008-08-29)"},{"lang":"hk","v":"鴻星(中國)有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"839808","names":[{"lang":"en","v":"SKY KING TECHNOLOGY GROUP LIMITED"},{"lang":"hk","v":"天毅科技集團有限公司"}],"company_since":"2003-03-19","company_dissolved":"2011-09-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839939","names":[{"lang":"en","v":"SMART FOREST LIMITED (d2006-08-11)"},{"lang":"hk","v":"駿林有限公司"}],"company_since":"2003-03-19","company_dissolved":"2006-08-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839658","names":[{"lang":"en","v":"SMART GAINER LIMITED (d2006-09-22)"},{"lang":"hk","v":"智銳有限公司"}],"company_since":"2003-03-19","company_dissolved":"2006-09-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839583","names":[{"lang":"en","v":"TAIWAN JINNY FASHION INT'L GROUP LIMITED"},{"lang":"hk","v":"臺灣今麗服飾國際集團有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839599","names":[{"lang":"en","v":"TANGENT ADVERTISING LIMITED"},{"lang":"hk","v":"前進廣告有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"839635","names":[{"lang":"en","v":"TERRYSTAR COMPANY LIMITED"},{"lang":"hk","v":"鑫之凱實業有限公司"}],"company_since":"2003-03-19","company_dissolved":"2017-11-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839965","names":[{"lang":"en","v":"Sun Ray (Partners) Limited"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839675","names":[{"lang":"en","v":"TONEAST LIMITED"},{"lang":"hk","v":"通利有限公司"}],"company_since":"2003-03-19","company_dissolved":"2005-08-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"839738","names":[{"lang":"en","v":"TOP LOYAL (CHINA) LIMITED"},{"lang":"hk","v":"高鴻(中國)有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"839820","names":[{"lang":"en","v":"T E T INTERNATIONAL (HK) LIMITED"},{"lang":"hk","v":"天一天國際(香港)有限公司"}],"company_since":"2003-03-19","company_dissolved":"2006-08-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"839850","names":[{"lang":"en","v":"TREASURE FRONTIER SYSTEM CO., LIMITED"},{"lang":"hk","v":"遠見有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839938","names":[{"lang":"en","v":"TALENT FULL LIMITED (d2006-12-01)"},{"lang":"hk","v":"豐廸有限公司"}],"company_since":"2003-03-19","company_dissolved":"2006-12-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"839588","names":[{"lang":"en","v":"VICTORIA HEALTH PLUS BEAUTY LIMITED"},{"lang":"hk","v":"維苑保健美容有限公司"}],"company_since":"2003-03-19","company_dissolved":"2006-03-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"839605","names":[{"lang":"en","v":"TECHKING HOLDINGS LIMITED"},{"lang":"hk","v":"德建控股有限公司"}],"company_since":"2003-03-19","company_dissolved":"2008-08-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"839746","names":[{"lang":"en","v":"WELL SUCCESS TECHNOLOGY DEVELOPMENT LIMITED"},{"lang":"hk","v":"益成科技發展有限公司"}],"company_since":"2003-03-19","company_dissolved":"2009-10-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"839660","names":[{"lang":"en","v":"WAVE FRONT ENTERPRISE (HK) LIMITED"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"839956","names":[{"lang":"en","v":"WELTEC ENGINEERING &amp; CONSULTANT LIMITED"},{"lang":"hk","v":"華泰工程及顧問有限公司"}],"company_since":"2003-03-19","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"839600","names":[{"lang":"en","v":"WORLDWIDE INVESTMENT SPECIALIST CORPORATION LIMITED"}],"company_since":"2003-03-19","company_dissolved":"2005-06-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"839678","names":[{"lang":"en","v":"PENTA-CONTINENTAL LIMITED"},{"lang":"hk","v":"五洲有限公司"}],"company_since":"2003-03-19","company_dissolved":"2006-08-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
