{"tax_id":"836972","names":[{"lang":"en","v":"CC LAND (HK) CO. LIMITED"}],"company_since":"2003-03-10","company_dissolved":"2008-08-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837159","names":[{"lang":"en","v":"CHAMPION ONE INTERNATIONAL LIMITED (d2012-04-13)"}],"company_since":"2003-03-10","company_dissolved":"2012-04-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"836978","names":[{"lang":"en","v":"CHANWELL HOLDINGS LIMITED"},{"lang":"hk","v":"昌匯控股有限公司"}],"company_since":"2003-03-10","company_dissolved":"2016-12-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837061","names":[{"lang":"en","v":"CHEERFUL INVESTMENT LIMITED (d2017-03-10)"},{"lang":"hk","v":"澤豐投資有限公司"}],"company_since":"2003-03-10","company_dissolved":"2017-03-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837096","names":[{"lang":"en","v":"CHINA FORTUNE INVESTMENT CORPORATION LIMITED"},{"lang":"hk","v":"潤華投資(香港)有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837000","names":[{"lang":"en","v":"CHINA HOLDINGS ENTERPRISES LIMITED"},{"lang":"hk","v":"中國集團企業有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837007","names":[{"lang":"en","v":"CHINA LINKER INTERNATIONAL LIMITED"},{"lang":"hk","v":"永中國際有限公司"}],"company_since":"2003-03-10","company_dissolved":"2006-04-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837018","names":[{"lang":"en","v":"China Primary Oil Gas Resources Usage and Development Holdings Limited"},{"lang":"hk","v":"中基油氣資源開發利用控股有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837009","names":[{"lang":"en","v":"CHINA REGENT ENTERPRISES LIMITED (d2008-08-15)"},{"lang":"hk","v":"中興企業有限公司"}],"company_since":"2003-03-10","company_dissolved":"2008-08-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837054","names":[{"lang":"en","v":"CHINA SINOTONE NETCOM LIMITED"},{"lang":"hk","v":"中國視聆通網絡通信有限公司"}],"company_since":"2003-03-10","company_dissolved":"2012-04-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837045","names":[{"lang":"en","v":"CHINA TING TEXTILE &amp; KNITWEAR (H.K.) LIMITED"},{"lang":"hk","v":"華鼎紡織‧針織品(香港)有限公司"}],"company_since":"2003-03-10","company_dissolved":"2008-09-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837144","names":[{"lang":"en","v":"CHONG SUN PAPER PRODUCTS COMPANY LIMITED"},{"lang":"hk","v":"創新紙品有限公司"}],"company_since":"2003-03-10","company_dissolved":"2004-08-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837125","names":[{"lang":"en","v":"CHUEN LEE INVESTMENT HOLDING LIMITED"},{"lang":"hk","v":"全利投資控股有限公司"}],"company_since":"2003-03-10","company_dissolved":"2014-09-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837039","names":[{"lang":"en","v":"CHUNG HING INTERNATIONAL TRADING LIMITED"},{"lang":"hk","v":"中興國際貿易有限公司"}],"company_since":"2003-03-10","company_dissolved":"2004-09-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"836988","names":[{"lang":"en","v":"CITIPEAK INTERNATIONAL TRADING LIMITED"},{"lang":"hk","v":"明成國際貿易有限公司"}],"company_since":"2003-03-10","company_dissolved":"2008-08-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"836994","names":[{"lang":"en","v":"CN TRADING LIMITED"}],"company_since":"2003-03-10","company_dissolved":"2006-07-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837034","names":[{"lang":"en","v":"CONWELL INTERNATIONAL LIMITED"},{"lang":"hk","v":"豐偉國際有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"836996","names":[{"lang":"en","v":"CREATIVE DEVELOPMENT ENTERPRISES LIMITED"},{"lang":"hk","v":"創新發展企業有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837139","names":[{"lang":"en","v":"CYBER SYSTEM COMPUTER LIMITED"},{"lang":"hk","v":"科藝電腦系統有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837162","names":[{"lang":"en","v":"CYBEX HONG KONG LIMITED"}],"company_since":"2003-03-10","company_dissolved":"2019-09-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837059","names":[{"lang":"en","v":"DERTEX DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"毅豐開發有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837131","names":[{"lang":"en","v":"DESIGN TEN MARCOM LIMITED"},{"lang":"hk","v":"設計傳達有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837136","names":[{"lang":"en","v":"CENTURY BEAUTY INTERNATIONAL LIMITED"},{"lang":"hk","v":"世紀風采國際有限公司"}],"company_since":"2003-03-10","company_dissolved":"2017-07-07","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837138","names":[{"lang":"en","v":"DIVE THE WORLD LIMITED"},{"lang":"hk","v":"潛水世界縱橫有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"837153","names":[{"lang":"en","v":"FINE GLOBAL LIMITED (d2008-08-15)"},{"lang":"hk","v":"迅譽有限公司"}],"company_since":"2003-03-10","company_dissolved":"2008-08-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837143","names":[{"lang":"en","v":"FILM WORKSHOP (CHINA) COMPANY LIMITED"},{"lang":"hk","v":"電影工作室(中國)有限公司"}],"company_since":"2003-03-10","company_dissolved":"2010-05-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837098","names":[{"lang":"en","v":"DRAGONWOOD INTERNATIONAL MANUFACTURING CO. LIMITED"},{"lang":"hk","v":"活龍國際高級傢俱製品有限公司"}],"company_since":"2003-03-10","company_dissolved":"2006-03-31","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837016","names":[{"lang":"en","v":"FIRST SMARTER LIMITED"},{"lang":"hk","v":"卓柏有限公司"}],"company_since":"2003-03-10","company_dissolved":"2004-09-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837150","names":[{"lang":"en","v":"FOUR SEASONS GROUP LIMITED"},{"lang":"hk","v":"科辰制品集團有限公司"}],"company_since":"2003-03-10","company_dissolved":"2020-09-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837044","names":[{"lang":"en","v":"FRANCE DUNHILL INTERNATIONAL (HONG KONG) HABILATORY &amp; LEATHER CO., LIMITED"},{"lang":"hk","v":"法國登喜路國際(香港)服飾皮具有限公司"}],"company_since":"2003-03-10","company_dissolved":"2007-06-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837114","names":[{"lang":"en","v":"FRANCE HONGZUILANG (HONG KONG) INTERNATIONAL FASHION LIMITED"},{"lang":"hk","v":"法國紅嘴狼(香港)國際服飾有限公司"}],"company_since":"2003-03-10","company_dissolved":"2006-06-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837031","names":[{"lang":"en","v":"EASTERN GALLERY LIMITED"},{"lang":"hk","v":"東方藝苑有限公司"}],"company_since":"2003-03-10","company_dissolved":"2007-10-26","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837103","names":[{"lang":"en","v":"FROM LIGHTS LIMITED"}],"company_since":"2003-03-10","company_dissolved":"2011-08-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837030","names":[{"lang":"en","v":"FRONT-TECH HK CO., LIMITED"},{"lang":"hk","v":"香港豐達有限公司"}],"company_since":"2003-03-10","company_dissolved":"2012-04-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837043","names":[{"lang":"en","v":"EASTERN TEAM LIMITED (d2007-07-27)"},{"lang":"hk","v":"怡協有限公司"}],"company_since":"2003-03-10","company_dissolved":"2007-07-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837066","names":[{"lang":"en","v":"GARDEN RESTAURANT (HOLDINGS) LIMITED"},{"lang":"hk","v":"花園餐廳(集團)有限公司"}],"company_since":"2003-03-10","company_dissolved":"2015-07-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837109","names":[{"lang":"en","v":"GERMANY COMPTON GROUP LIMITED"},{"lang":"hk","v":"德國康普頓集團有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837080","names":[{"lang":"en","v":"GERMANY SUONI ELECTRIC HOLDINGS (HONG KONG) LIMITED"},{"lang":"hk","v":"德國索妮電器集團(香港)有限公司"}],"company_since":"2003-03-10","company_dissolved":"2006-03-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837155","names":[{"lang":"en","v":"GLOBAL EMPIRE TRADING LIMITED (HK)"},{"lang":"hk","v":"鵬盛貿易有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837011","names":[{"lang":"en","v":"GLOBAL HONOUR (ASIA) LIMITED"},{"lang":"hk","v":"冠信(亞洲)有限公司"}],"company_since":"2003-03-10","company_dissolved":"2005-08-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837165","names":[{"lang":"en","v":"EMSONS COMPANY LIMITED"},{"lang":"hk","v":"嘉禾有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"836985","names":[{"lang":"en","v":"GOLD LAND INTERNATIONAL (HK) COMPANY LIMITED"},{"lang":"hk","v":"金域國際(香港)有限公司"}],"company_since":"2003-03-10","company_dissolved":"2019-03-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837008","names":[{"lang":"en","v":"ENGINEERING SERVICE PARTNER LIMITED"}],"company_since":"2003-03-10","company_dissolved":"2009-05-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"836999","names":[{"lang":"en","v":"GOLDEN INVESTMENT GROUP LIMITED (d2008-11-07)"},{"lang":"hk","v":"金豐投資企業有限公司"}],"company_since":"2003-03-10","company_dissolved":"2008-11-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837085","names":[{"lang":"en","v":"GOLDEN MILESTONE INTERNATIONAL LIMITED"},{"lang":"hk","v":"金里程國際有限公司"}],"company_since":"2003-03-10","company_dissolved":"2006-01-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837050","names":[{"lang":"en","v":"ESUN INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"依純國際貿易有限公司"}],"company_since":"2003-03-10","company_dissolved":"2005-07-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837117","names":[{"lang":"en","v":"GOLDEN WISHES ENTERPRISE LIMITED"},{"lang":"hk","v":"金希企業有限公司"}],"company_since":"2003-03-10","company_dissolved":"2009-07-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837056","names":[{"lang":"en","v":"GOLDMATE INVESTMENT LIMITED (d2010-08-20)"},{"lang":"hk","v":"美萬投資有限公司"}],"company_since":"2003-03-10","company_dissolved":"2010-08-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"836968","names":[{"lang":"en","v":"GRAND RIVER INTERIOR DESIGN &amp; CONTRACTING CO., LIMITED"},{"lang":"hk","v":"匯川室內設計及工程有限公司"}],"company_since":"2003-03-10","company_dissolved":"2009-04-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837106","names":[{"lang":"en","v":"GORIGHT ELECTRICAL LIMITED"},{"lang":"hk","v":"高威電業有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837035","names":[{"lang":"en","v":"EUROPE INTERNATIONAL EDU AGENCE CENTER ABROAD DEVELOPMENT LIMITED"},{"lang":"hk","v":"歐洲國際教育交流中心海外發展有限公司"}],"company_since":"2003-03-10","company_dissolved":"2008-08-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837070","names":[{"lang":"en","v":"GU CHO TONG CO. LIMITED"},{"lang":"hk","v":"甘草堂有限公司"}],"company_since":"2003-03-10","company_dissolved":"2016-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837076","names":[{"lang":"en","v":"HB HEATING SYSTEMS LIMITED (d2011-01-19)"},{"lang":"hk","v":"哈曼電熱系統有限公司"}],"company_since":"2003-03-10","company_dissolved":"2011-01-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837169","names":[{"lang":"en","v":"HICHARMS LIMITED"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837028","names":[{"lang":"en","v":"HK RICHES ENTERPRISE GROUP INT'L IMP. &amp; EXP. TRADING LIMITED"},{"lang":"hk","v":"香港瑞賽企業集團國際進出口貿易有限公司"}],"company_since":"2003-03-10","company_dissolved":"2010-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837119","names":[{"lang":"en","v":"HONG KONG (USA) HAOER PRINCE CLOTHING &amp; ACCESSORIES LIMITED"},{"lang":"hk","v":"香港(美國)豪爾王子服飾有限公司"}],"company_since":"2003-03-10","company_dissolved":"2009-07-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837079","names":[{"lang":"en","v":"HONG KONG EIMEIR INTERNATIONAL FASHION LIMITED"},{"lang":"hk","v":"香港伊美爾國際服飾有限公司"}],"company_since":"2003-03-10","company_dissolved":"2008-08-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837060","names":[{"lang":"en","v":"HONG KONG GOLDEN WISE INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"香港金海投資有限公司"}],"company_since":"2003-03-10","company_dissolved":"2012-09-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837123","names":[{"lang":"en","v":"HONG KONG INSTITUTE OF PRESCHOOL EDUCATION LIMITED (THE)"},{"lang":"hk","v":"香港學前教育學院有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837025","names":[{"lang":"en","v":"HONG KONG KA YUM INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"香港嘉鑫國際集團有限公司"}],"company_since":"2003-03-10","company_dissolved":"2008-08-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837064","names":[{"lang":"en","v":"HONG KONG CENTRE FOR PSYCHOLOGICAL MEDICINE LIMITED"},{"lang":"hk","v":"香港心理醫學中心有限公司"}],"company_since":"2003-03-10","company_dissolved":"2012-04-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"836982","names":[{"lang":"en","v":"HONG KONG KENTFORD LIMITED"},{"lang":"hk","v":"香港健福有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837158","names":[{"lang":"en","v":"ELECTRONIC PAYMENT SERVICES COMPANY (HONG KONG) LIMITED"},{"lang":"hk","v":"迅通電子服務(香港)有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"837044","names":[{"lang":"en","v":"FRANCE DUNHILL INTERNATIONAL (HONG KONG) HABILATORY &amp; LEATHER CO., LIMITED"},{"lang":"hk","v":"法國登喜路國際(香港)服飾皮具有限公司"}],"company_since":"2003-03-10","company_dissolved":"2007-06-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837114","names":[{"lang":"en","v":"FRANCE HONGZUILANG (HONG KONG) INTERNATIONAL FASHION LIMITED"},{"lang":"hk","v":"法國紅嘴狼(香港)國際服飾有限公司"}],"company_since":"2003-03-10","company_dissolved":"2006-06-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837043","names":[{"lang":"en","v":"EASTERN TEAM LIMITED (d2007-07-27)"},{"lang":"hk","v":"怡協有限公司"}],"company_since":"2003-03-10","company_dissolved":"2007-07-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837030","names":[{"lang":"en","v":"FRONT-TECH HK CO., LIMITED"},{"lang":"hk","v":"香港豐達有限公司"}],"company_since":"2003-03-10","company_dissolved":"2012-04-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837158","names":[{"lang":"en","v":"ELECTRONIC PAYMENT SERVICES COMPANY (HONG KONG) LIMITED"},{"lang":"hk","v":"迅通電子服務(香港)有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837155","names":[{"lang":"en","v":"GLOBAL EMPIRE TRADING LIMITED (HK)"},{"lang":"hk","v":"鵬盛貿易有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837011","names":[{"lang":"en","v":"GLOBAL HONOUR (ASIA) LIMITED"},{"lang":"hk","v":"冠信(亞洲)有限公司"}],"company_since":"2003-03-10","company_dissolved":"2005-08-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837050","names":[{"lang":"en","v":"ESUN INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"依純國際貿易有限公司"}],"company_since":"2003-03-10","company_dissolved":"2005-07-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"836985","names":[{"lang":"en","v":"GOLD LAND INTERNATIONAL (HK) COMPANY LIMITED"},{"lang":"hk","v":"金域國際(香港)有限公司"}],"company_since":"2003-03-10","company_dissolved":"2019-03-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837035","names":[{"lang":"en","v":"EUROPE INTERNATIONAL EDU AGENCE CENTER ABROAD DEVELOPMENT LIMITED"},{"lang":"hk","v":"歐洲國際教育交流中心海外發展有限公司"}],"company_since":"2003-03-10","company_dissolved":"2008-08-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837143","names":[{"lang":"en","v":"FILM WORKSHOP (CHINA) COMPANY LIMITED"},{"lang":"hk","v":"電影工作室(中國)有限公司"}],"company_since":"2003-03-10","company_dissolved":"2010-05-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837117","names":[{"lang":"en","v":"GOLDEN WISHES ENTERPRISE LIMITED"},{"lang":"hk","v":"金希企業有限公司"}],"company_since":"2003-03-10","company_dissolved":"2009-07-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837056","names":[{"lang":"en","v":"GOLDMATE INVESTMENT LIMITED (d2010-08-20)"},{"lang":"hk","v":"美萬投資有限公司"}],"company_since":"2003-03-10","company_dissolved":"2010-08-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837153","names":[{"lang":"en","v":"FINE GLOBAL LIMITED (d2008-08-15)"},{"lang":"hk","v":"迅譽有限公司"}],"company_since":"2003-03-10","company_dissolved":"2008-08-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837106","names":[{"lang":"en","v":"GORIGHT ELECTRICAL LIMITED"},{"lang":"hk","v":"高威電業有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"836968","names":[{"lang":"en","v":"GRAND RIVER INTERIOR DESIGN &amp; CONTRACTING CO., LIMITED"},{"lang":"hk","v":"匯川室內設計及工程有限公司"}],"company_since":"2003-03-10","company_dissolved":"2009-04-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837010","names":[{"lang":"en","v":"GRAND WINNING CONSULTANTS LIMITED"},{"lang":"hk","v":"宏佳顧問有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837033","names":[{"lang":"en","v":"GREAT NATION LIMITED (HK)"},{"lang":"hk","v":"宇萬有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837070","names":[{"lang":"en","v":"GU CHO TONG CO. LIMITED"},{"lang":"hk","v":"甘草堂有限公司"}],"company_since":"2003-03-10","company_dissolved":"2016-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837077","names":[{"lang":"en","v":"HANG FUNG CHUN INDUSTRIES LIMITED"},{"lang":"hk","v":"恒豐駿實業有限公司"}],"company_since":"2003-03-10","company_dissolved":"2005-09-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837076","names":[{"lang":"en","v":"HB HEATING SYSTEMS LIMITED (d2011-01-19)"},{"lang":"hk","v":"哈曼電熱系統有限公司"}],"company_since":"2003-03-10","company_dissolved":"2011-01-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837103","names":[{"lang":"en","v":"FROM LIGHTS LIMITED"}],"company_since":"2003-03-10","company_dissolved":"2011-08-05","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837036","names":[{"lang":"en","v":"FAR EAST PAPER PRODUCTS FACTORY LIMITED"},{"lang":"hk","v":"遠東紙品廠有限公司"}],"company_since":"2003-03-10","company_dissolved":"2019-01-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837169","names":[{"lang":"en","v":"HICHARMS LIMITED"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837032","names":[{"lang":"en","v":"HO KEI ENGINEERING CO. LIMITED"},{"lang":"hk","v":"豪基工程有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837066","names":[{"lang":"en","v":"GARDEN RESTAURANT (HOLDINGS) LIMITED"},{"lang":"hk","v":"花園餐廳(集團)有限公司"}],"company_since":"2003-03-10","company_dissolved":"2015-07-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837119","names":[{"lang":"en","v":"HONG KONG (USA) HAOER PRINCE CLOTHING &amp; ACCESSORIES LIMITED"},{"lang":"hk","v":"香港(美國)豪爾王子服飾有限公司"}],"company_since":"2003-03-10","company_dissolved":"2009-07-31","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837109","names":[{"lang":"en","v":"GERMANY COMPTON GROUP LIMITED"},{"lang":"hk","v":"德國康普頓集團有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837064","names":[{"lang":"en","v":"HONG KONG CENTRE FOR PSYCHOLOGICAL MEDICINE LIMITED"},{"lang":"hk","v":"香港心理醫學中心有限公司"}],"company_since":"2003-03-10","company_dissolved":"2012-04-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837079","names":[{"lang":"en","v":"HONG KONG EIMEIR INTERNATIONAL FASHION LIMITED"},{"lang":"hk","v":"香港伊美爾國際服飾有限公司"}],"company_since":"2003-03-10","company_dissolved":"2008-08-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837060","names":[{"lang":"en","v":"HONG KONG GOLDEN WISE INTERNATIONAL INVESTMENT LIMITED"},{"lang":"hk","v":"香港金海投資有限公司"}],"company_since":"2003-03-10","company_dissolved":"2012-09-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837080","names":[{"lang":"en","v":"GERMANY SUONI ELECTRIC HOLDINGS (HONG KONG) LIMITED"},{"lang":"hk","v":"德國索妮電器集團(香港)有限公司"}],"company_since":"2003-03-10","company_dissolved":"2006-03-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837123","names":[{"lang":"en","v":"HONG KONG INSTITUTE OF PRESCHOOL EDUCATION LIMITED (THE)"},{"lang":"hk","v":"香港學前教育學院有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"836958","names":[{"lang":"en","v":"HONG KONG POULTRY (KAMEI CHICKEN) DEVELOPMENT LIMITED"},{"lang":"hk","v":"香港家禽(嘉美雞)發展有限公司"}],"company_since":"2003-03-10","company_dissolved":"2017-08-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837074","names":[{"lang":"en","v":"HONG KONG R&amp;D INTERNATIONAL TRADE CO., LIMITED"},{"lang":"hk","v":"香港爾迪國際貿易有限公司"}],"company_since":"2003-03-10","company_dissolved":"2018-03-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837071","names":[{"lang":"en","v":"HUNG FAI BOTTLE COMPANY LIMITED"},{"lang":"hk","v":"鴻輝吹瓶有限公司"}],"company_since":"2003-03-10","company_dissolved":"2004-09-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837140","names":[{"lang":"en","v":"HUNG MING ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"鴻鳴工程有限公司"}],"company_since":"2003-03-10","company_dissolved":"2015-12-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837129","names":[{"lang":"en","v":"GREAT HARVEST (GROUP) LIMITED"},{"lang":"hk","v":"炬豐(集團)有限公司"}],"company_since":"2003-03-10","company_dissolved":"2010-11-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837147","names":[{"lang":"en","v":"HUNG WAH TRANSPORTATION LIMITED"},{"lang":"hk","v":"鴻華運輸有限公司"}],"company_since":"2003-03-10","company_dissolved":"2007-01-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837167","names":[{"lang":"en","v":"I-PAPER PRODUCTS LIMITED"},{"lang":"hk","v":"創盈紙品製作有限公司"}],"company_since":"2003-03-10","company_dissolved":"2009-07-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837022","names":[{"lang":"en","v":"IMPACT DESIGN WORKSHOP LIMITED"},{"lang":"hk","v":"思萃設計工坊有限公司"}],"company_since":"2003-03-10","company_dissolved":"2006-10-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"836977","names":[{"lang":"en","v":"INFOBIZ MANAGEMENT LIMITED"},{"lang":"hk","v":"資訊企業管理有限公司"}],"company_since":"2003-03-10","company_dissolved":"2010-08-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"837133","names":[{"lang":"en","v":"KAI SHARP LIMITED"},{"lang":"hk","v":"鎧銳有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837120","names":[{"lang":"en","v":"HONG KONG OUTELAISI FURNITURE (INTERNATIONAL) GROUP COMPANY LIMITED"},{"lang":"hk","v":"香港歐特萊斯家俬(國際)集團有限公司"}],"company_since":"2003-03-10","company_dissolved":"2010-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"836992","names":[{"lang":"en","v":"KWONG'S ACCOUNTING SERVICES COMPANY LIMITED"},{"lang":"hk","v":"鄺氏會計服務事務所有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837146","names":[{"lang":"en","v":"LAMA STRATEGICS LIMITED"},{"lang":"hk","v":"藍瑪策略有限公司"}],"company_since":"2003-03-10","company_dissolved":"2004-04-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"836967","names":[{"lang":"en","v":"INNOVATION GIFTS &amp; PRINT PREMIUM LIMITED"},{"lang":"hk","v":"創意印刷禮品有限公司"}],"company_since":"2003-03-10","company_dissolved":"2006-09-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837073","names":[{"lang":"en","v":"LIAN FENG TEXTILES (H.K.) CO., LIMITED"},{"lang":"hk","v":"聯峰紡織(香港)有限公司"}],"company_since":"2003-03-10","company_dissolved":"2015-02-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837069","names":[{"lang":"en","v":"LING'S GROUP HOLDINGS LIMITED"},{"lang":"hk","v":"玲瓏集團控股有限公司"}],"company_since":"2003-03-10","company_dissolved":"2015-05-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837062","names":[{"lang":"en","v":"LONG-TERM RICH INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"富恒國際發展有限公司"}],"company_since":"2003-03-10","company_dissolved":"2007-12-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837029","names":[{"lang":"en","v":"LUCKYWELL PETROCHEMICAL HONG KONG LIMITED"},{"lang":"hk","v":"香港瑞豐國旺石化有限公司"}],"company_since":"2003-03-10","company_dissolved":"2017-10-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"836976","names":[{"lang":"en","v":"INTERNATIONAL ART EDUCATIONAL CENTRE LIMITED"},{"lang":"hk","v":"國際藝術中心有限公司"}],"company_since":"2003-03-10","company_dissolved":"2012-04-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837083","names":[{"lang":"en","v":"ITALY . CRYSTAL CROCODILE GROUP LIMITED"},{"lang":"hk","v":"意大利‧水晶鱷集團有限公司"}],"company_since":"2003-03-10","company_dissolved":"2008-08-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837135","names":[{"lang":"en","v":"MANDARIN INTERNATIONAL TRADING LIMITED (d2010-10-22)"},{"lang":"hk","v":"文華國際貿易有限公司"}],"company_since":"2003-03-10","company_dissolved":"2010-10-22","company_type_txt":"Private, ltd by shares"},
{"tax_id":"836979","names":[{"lang":"en","v":"MAO LIN TRADING LIMITED"},{"lang":"hk","v":"茂琳貿易有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"836998","names":[{"lang":"en","v":"MEGA CENTURY DEVELOPMENT LIMITED"},{"lang":"hk","v":"聯鋒發展有限公司"}],"company_since":"2003-03-10","company_dissolved":"2009-08-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837041","names":[{"lang":"en","v":"MILAN STATION (TST) LIMITED"},{"lang":"hk","v":"米蘭站(尖沙咀)有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837164","names":[{"lang":"en","v":"MILLION LONG INVESTMENT LIMITED"},{"lang":"hk","v":"萬祥投資有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"837115","names":[{"lang":"en","v":"ITALY . WOODPECKER GROUP LIMITED"},{"lang":"hk","v":"意大利‧啄木鳥集團有限公司"}],"company_since":"2003-03-10","company_dissolved":"2008-08-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837042","names":[{"lang":"en","v":"JOIN WEALTHY (ASIA) LIMITED"},{"lang":"hk","v":"聯豐(亞洲)有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837040","names":[{"lang":"en","v":"MODERN CHINA (INTERNATIONAL) SHIPPING LIMITED"},{"lang":"hk","v":"中域(國際)船務有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837078","names":[{"lang":"en","v":"OCEAN WHITE INTERNATIONAL LIMITED"},{"lang":"hk","v":"奧遜威爾國際有限公司"}],"company_since":"2003-03-10","company_dissolved":"2012-09-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837097","names":[{"lang":"en","v":"ONWARDS CONSULTANT LIMITED"},{"lang":"hk","v":"駿程顧問有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837065","names":[{"lang":"en","v":"KANEUMI TSUSO LIMITED"},{"lang":"hk","v":"金海通商有限公司"}],"company_since":"2003-03-10","company_dissolved":"2008-08-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837112","names":[{"lang":"en","v":"ORIENT (HONG KONG) MANUFACTURING LIMITED"},{"lang":"hk","v":"光耀(香港)有限公司"}],"company_since":"2003-03-10","company_dissolved":"2009-05-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837107","names":[{"lang":"en","v":"ORIENT TECHNOLOGY (HONG KONG) ELECTRONIC LIMITED"},{"lang":"hk","v":"東方科技(香港)電子有限公司"}],"company_since":"2003-03-10","company_dissolved":"2009-03-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837161","names":[{"lang":"en","v":"ORION LIMITED"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"837002","names":[{"lang":"en","v":"PANASIA INTERNATIONAL GROUP LIMITED"},{"lang":"hk","v":"泛亞國際投資有限公司"}],"company_since":"2003-03-10","company_dissolved":"2006-04-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"836974","names":[{"lang":"en","v":"PATON DEVELOPMENT LIMITED"},{"lang":"hk","v":"香港柏安發展有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"837121","names":[{"lang":"en","v":"M &amp; M ASSOCIATES LIMITED (d2010-06-11)"}],"company_since":"2003-03-10","company_dissolved":"2010-06-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837075","names":[{"lang":"en","v":"PERFECT TRAVEL SERVICES LIMITED"},{"lang":"hk","v":"喜訊旅遊有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837172","names":[{"lang":"en","v":"PREFERRED EQUITY UNDERWRITERS LIMITED"}],"company_since":"2003-03-10","company_dissolved":"2014-02-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837132","names":[{"lang":"en","v":"QIMA Technical Services (HK) Limited"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"836965","names":[{"lang":"en","v":"REGAL INTERNATIONAL INVESTMENTS LIMITED"},{"lang":"hk","v":"宏冠國際投資有限公司"}],"company_since":"2003-03-10","company_dissolved":"2004-07-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"836990","names":[{"lang":"en","v":"NASMOTECH LIMITED"}],"company_since":"2003-03-10","company_dissolved":"2010-12-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837014","names":[{"lang":"en","v":"ROYAL LINKER LIMITED (d2004-09-24)"},{"lang":"hk","v":"聯建有限公司"}],"company_since":"2003-03-10","company_dissolved":"2004-09-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837012","names":[{"lang":"en","v":"ROYAL WELL (ASIA) LIMITED"},{"lang":"hk","v":"龍裕(亞洲)有限公司"}],"company_since":"2003-03-10","company_dissolved":"2015-03-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"836997","names":[{"lang":"en","v":"NEW CHINESE DEVELOPMENT LIMITED"},{"lang":"hk","v":"新中華發展有限公司"}],"company_since":"2003-03-10","company_dissolved":"2008-04-16","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837118","names":[{"lang":"en","v":"ROYMAN LIMITED (HK)"},{"lang":"hk","v":"樂敏有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837055","names":[{"lang":"en","v":"NICEWAY INVESTMENT LIMITED (d2006-11-17)"},{"lang":"hk","v":"力宏投資有限公司"}],"company_since":"2003-03-10","company_dissolved":"2006-11-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837084","names":[{"lang":"en","v":"SANPU ENTERPRISES (HONGKONG) LIMITED"},{"lang":"hk","v":"三浦企業(香港)有限公司"}],"company_since":"2003-03-10","company_dissolved":"2008-08-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837156","names":[{"lang":"en","v":"SHARP TALENT INVESTMENTS LIMITED"},{"lang":"hk","v":"康琪投資有限公司"}],"company_since":"2003-03-10","company_dissolved":"2015-08-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837046","names":[{"lang":"en","v":"SHUI SENG HONG LIMITED"},{"lang":"hk","v":"穗生行有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837081","names":[{"lang":"en","v":"SHUOTAI BIOTECHNOLOGY HOLDINGS COMPANY LIMITED"},{"lang":"hk","v":"碩泰生科(控股)有限公司"}],"company_since":"2003-03-10","company_dissolved":"2016-12-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837087","names":[{"lang":"en","v":"PALO ALTO COMPANY LIMITED"}],"company_since":"2003-03-10","company_dissolved":"2013-12-13","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837090","names":[{"lang":"en","v":"SIQI (GROUP) LIMITED"},{"lang":"hk","v":"斯祺(集團)有限公司"}],"company_since":"2003-03-10","company_dissolved":"2008-08-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"837141","names":[{"lang":"en","v":"PENINSULA SOURCING LIMITED"},{"lang":"hk","v":"半島採購有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837130","names":[{"lang":"en","v":"PACIFIC OCEAN (ASIA) DEVELOPMENT CO. LIMITED"},{"lang":"hk","v":"四海發展(亞洲)有限公司"}],"company_since":"2003-03-10","company_dissolved":"2009-07-31","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837003","names":[{"lang":"en","v":"SPEEDY BEST INTERNATIONAL LIMITED (d2009-09-04)"},{"lang":"hk","v":"迅興國際有限公司"}],"company_since":"2003-03-10","company_dissolved":"2009-09-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837092","names":[{"lang":"en","v":"PENKO LIMITED"},{"lang":"hk","v":"正豪有限公司"}],"company_since":"2003-03-10","company_dissolved":"2006-06-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837017","names":[{"lang":"en","v":"SPEEDY GLOBAL LIMITED (d2010-09-30)"},{"lang":"hk","v":"迅創有限公司"}],"company_since":"2003-03-10","company_dissolved":"2010-09-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"836980","names":[{"lang":"en","v":"SUCCESS RUN BINDING &amp; PRODUCTION LIMITED"},{"lang":"hk","v":"成運制本有限公司"}],"company_since":"2003-03-10","company_dissolved":"2004-11-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837024","names":[{"lang":"en","v":"SONEX INTERNATIONAL LIMITED (d2006-12-15)"}],"company_since":"2003-03-10","company_dissolved":"2006-12-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837006","names":[{"lang":"en","v":"SUN SHENG FUNG INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"新成豐國際控股有限公司"}],"company_since":"2003-03-10","company_dissolved":"2019-12-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"836987","names":[{"lang":"en","v":"SUN SHUI HING ROASTED FOODS LIMITED"},{"lang":"hk","v":"新瑞興燒味有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837134","names":[{"lang":"en","v":"RED TOP GROUP (H.K.) LIMITED"},{"lang":"hk","v":"紅頂集團(香港)有限公司"}],"company_since":"2003-03-10","company_dissolved":"2014-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837038","names":[{"lang":"en","v":"TAK SHING TRADING DEVELOPMENT LIMITED"},{"lang":"hk","v":"德成貿易發展有限公司"}],"company_since":"2003-03-10","company_dissolved":"2014-07-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"836989","names":[{"lang":"en","v":"TAKEDA PRECISION (HONG KONG) CO., LIMITED"},{"lang":"hk","v":"竹田精密(香港)有限公司"}],"company_since":"2003-03-10","company_dissolved":"2008-05-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"836986","names":[{"lang":"en","v":"TAO'S (HONG KONG) PAINTS DEVELOPMENT LIMITED"},{"lang":"hk","v":"陶氏(香港)塗料開發有限公司"}],"company_since":"2003-03-10","company_dissolved":"2009-08-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837157","names":[{"lang":"en","v":"TEXCOTE INVESTMENTS LIMITED"},{"lang":"hk","v":"權俊投資有限公司"}],"company_since":"2003-03-10","company_dissolved":"2009-07-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837170","names":[{"lang":"en","v":"TU SHAY LIMITED"}],"company_since":"2003-03-10","company_dissolved":"2010-10-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837148","names":[{"lang":"en","v":"TUNG SING PACKING &amp; PRINTING COMPANY LIMITED"},{"lang":"hk","v":"東升包裝印刷有限公司"}],"company_since":"2003-03-10","company_dissolved":"2006-07-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837094","names":[{"lang":"en","v":"TWINSTARS STUDIO LIMITED"},{"lang":"hk","v":"星耀攝影製作室有限公司"}],"company_since":"2003-03-10","company_dissolved":"2005-12-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"836966","names":[{"lang":"en","v":"SIN KWONG VEGETARIAN LIMITED"},{"lang":"hk","v":"善光齋有限公司"}],"company_since":"2003-03-10","company_dissolved":"2009-04-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"836971","names":[{"lang":"en","v":"UNIGLOBE PRODUCTIONS LIMITED"},{"lang":"hk","v":"影球影視文化有限公司"}],"company_since":"2003-03-10","company_dissolved":"2006-03-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837151","names":[{"lang":"en","v":"VANTAGE MASTER LIMITED"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837053","names":[{"lang":"en","v":"SINOAUST TRADING COMPANY LIMITED"},{"lang":"hk","v":"瑞澤通貿易有限公司"}],"company_since":"2003-03-10","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837051","names":[{"lang":"en","v":"VMT BUSINESS CONSULTANTS CO., LIMITED"}],"company_since":"2003-03-10","company_dissolved":"2008-08-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837004","names":[{"lang":"en","v":"SKY LINKER INTERNATIONAL LIMITED (d2009-07-31)"},{"lang":"hk","v":"天新國際有限公司"}],"company_since":"2003-03-10","company_dissolved":"2009-07-31","company_type_txt":"Private, ltd by shares"},
{"tax_id":"836960","names":[{"lang":"en","v":"WAH KWUN ENTERPRISES COMPANY LIMITED"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837023","names":[{"lang":"en","v":"WAI YIP (CHINA) LIMITED"},{"lang":"hk","v":"偉業(中國)有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"836961","names":[{"lang":"en","v":"WANG HING HONG COMPANY LIMITED"}],"company_since":"2003-03-10","company_dissolved":"2006-07-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837163","names":[{"lang":"en","v":"WINFORWARD LIMITED"},{"lang":"hk","v":"慶科有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"836970","names":[{"lang":"en","v":"Wing Mau Holdings Limited"},{"lang":"hk","v":"永貿集團有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837019","names":[{"lang":"en","v":"SUNRISE INTERNATIONAL INVESTMENT (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"旭遠國際投資(香港)有限公司"}],"company_since":"2003-03-10","company_dissolved":"2008-02-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837052","names":[{"lang":"en","v":"WORLD FENG JEWELLERY (HONGKONG) COMPANY LIMITED"},{"lang":"hk","v":"世豐珠寶(香港)有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837021","names":[{"lang":"en","v":"XIN RUI TONG INTERNATIONAL GROUP (HK) CO., LIMITED"},{"lang":"hk","v":"鑫瑞通國際集團(香港)有限公司"}],"company_since":"2003-03-10","company_dissolved":"2009-07-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837095","names":[{"lang":"en","v":"YICK SHING (H.K.) LIMITED"},{"lang":"hk","v":"億盛(香港)有限公司"}],"company_since":"2003-03-10","company_dissolved":"2004-08-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"836964","names":[{"lang":"en","v":"YIP SING TRADING LIMITED"},{"lang":"hk","v":"業成行貿易有限公司"}],"company_since":"2003-03-10","company_dissolved":"2008-02-29","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"836962","names":[{"lang":"en","v":"TOP INTERNATIONAL ENTERPRISES LIMITED"},{"lang":"hk","v":"國際第一企業有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"837154","names":[{"lang":"en","v":"ZARTA &amp; COMPANY LIMITED"},{"lang":"hk","v":"富滙鐘錶手飾有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"837026","names":[{"lang":"en","v":"ULTRA CREATIVITY INTERNATIONAL TRADING LIMITED"},{"lang":"hk","v":"創捷國際貿易有限公司"}],"company_since":"2003-03-10","company_dissolved":"2008-08-15","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"837020","names":[{"lang":"en","v":"VICTORIA V INTERNATIONAL LIMITED"},{"lang":"hk","v":"維依有限公司"}],"company_since":"2003-03-10","company_dissolved":"2004-06-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"837108","names":[{"lang":"en","v":"WEDDING COMPANY LIMITED (THE)"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"836993","names":[{"lang":"en","v":"WINMAX ASIA ENTERPRISES LIMITED"},{"lang":"hk","v":"宏美亞洲企業有限公司"}],"company_since":"2003-03-10","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"836963","names":[{"lang":"en","v":"WOODLAND INVESTMENTS COMPANY LIMITED"},{"lang":"hk","v":"和順投資有限公司"}],"company_since":"2003-03-10","company_dissolved":"2010-07-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"836959","names":[{"lang":"en","v":"YUNG TAI TRADING LIMITED"}],"company_since":"2003-03-10","company_dissolved":"2017-04-21","company_type_txt":"Private, ltd by shares"},
undefined,
