{"tax_id":"821189","names":[{"lang":"en","v":"CHARTERLINK INTERNATIONAL INDUSTRIAL LIMITED"},{"lang":"hk","v":"卓聯國際實業有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821219","names":[{"lang":"en","v":"CHINA BILLION INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"中億國際發展有限公司"}],"company_since":"2002-11-11","company_dissolved":"2011-10-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821150","names":[{"lang":"en","v":"CHINA CREATION INTERNATIONAL (HK) LIMITED"},{"lang":"hk","v":"創華國際(香港)有限公司"}],"company_since":"2002-11-11","company_dissolved":"2010-09-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821151","names":[{"lang":"en","v":"CHINA CONCEPT INTERNATIONAL TRADING LIMITED"},{"lang":"hk","v":"創華國際貿易有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821188","names":[{"lang":"en","v":"CHINA OCEAN INTERNATIONAL DEVELOPMENT HOLDINGS LIMITED"},{"lang":"hk","v":"中海國際發展集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821148","names":[{"lang":"en","v":"CHINA SPREAD HOLDINGS LIMITED"},{"lang":"hk","v":"華拓集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"2015-01-09","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821147","names":[{"lang":"en","v":"CITI-DRAGON (CHINA) LIMITED"},{"lang":"hk","v":"龍城(中國)有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821186","names":[{"lang":"en","v":"CITILINK INDUSTRIAL ALLIANCE LIMITED"},{"lang":"hk","v":"城際產業聯盟股份有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821226","names":[{"lang":"en","v":"CONNOR &amp; CLAY LIMITED"},{"lang":"hk","v":"匡勤有限公司"}],"company_since":"2002-11-11","company_dissolved":"2016-07-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821246","names":[{"lang":"en","v":"CONTINENTAL INTERNATIONAL BUSINESS COMPANY LIMITED"},{"lang":"hk","v":"新大陸國際商務有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821187","names":[{"lang":"en","v":"CREATIVE TEAM INTERNATIONAL INDUSTRIAL LIMITED"},{"lang":"hk","v":"創藝國際實業有限公司"}],"company_since":"2002-11-11","company_dissolved":"2011-11-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821199","names":[{"lang":"en","v":"CTC GARMENT LIMITED"},{"lang":"hk","v":"基遜製衣有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821251","names":[{"lang":"en","v":"DISCOVERY MEDICAL LABORATORY LIMITED"},{"lang":"hk","v":"科研醫療化驗所有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821234","names":[{"lang":"en","v":"EASCO INVESTMENT LIMITED"},{"lang":"hk","v":"宇高投資有限公司"}],"company_since":"2002-11-11","company_dissolved":"2015-08-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821241","names":[{"lang":"en","v":"EASTERN JET DEVELOPMENT LIMITED"},{"lang":"hk","v":"怡駿發展有限公司"}],"company_since":"2002-11-11","company_dissolved":"2004-11-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821261","names":[{"lang":"en","v":"EFESART LIMITED"}],"company_since":"2002-11-11","company_dissolved":"2012-12-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821224","names":[{"lang":"en","v":"EMPEROR ASIA INVESTMENTS LIMITED"},{"lang":"hk","v":"尚豐投資有限公司"}],"company_since":"2002-11-11","company_dissolved":"2018-03-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821185","names":[{"lang":"en","v":"EASTON INTERNATIONAL INVESTMENT ENTERPRISE LIMITED"},{"lang":"hk","v":"東升國際投資企業有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821297","names":[{"lang":"en","v":"CHANGSHUN INTERNATIONAL LOGISTICS COMPANY LIMITED"},{"lang":"hk","v":"長順國際物流有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821099","names":[{"lang":"en","v":"ETERNAL ASSET LIMITED (d2010-07-02)"},{"lang":"hk","v":"暐恒有限公司"}],"company_since":"2002-11-11","company_dissolved":"2010-07-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821144","names":[{"lang":"en","v":"EVER BRIGHT (HONG KONG) LIMITED"},{"lang":"hk","v":"恒光(香港)有限公司"}],"company_since":"2002-11-11","company_dissolved":"2016-09-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821296","names":[{"lang":"en","v":"CHINA DECISION RESOURCE NEWS TRADE GROUP LIMITED"},{"lang":"hk","v":"中國決策參考報社報業集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821235","names":[{"lang":"en","v":"EVER LEGEND ENGINEERING LIMITED"},{"lang":"hk","v":"永駿工程有限公司"}],"company_since":"2002-11-11","company_dissolved":"2015-04-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821149","names":[{"lang":"en","v":"CHINA GROUP TECHNOLOGY LIMITED (d2004-03-26)"},{"lang":"hk","v":"華盟科技有限公司"}],"company_since":"2002-11-11","company_dissolved":"2004-03-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821269","names":[{"lang":"en","v":"CHINA REJUVENATION COMPANY LIMITED"},{"lang":"hk","v":"中國返老還童有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-03-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821233","names":[{"lang":"en","v":"FAR EAST CONTINENTAL SHIPPING LINE LIMITED"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821242","names":[{"lang":"en","v":"FIRST PACIFIC CONSULTANTS LIMITED"},{"lang":"hk","v":"豐恒顧問有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-03-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821265","names":[{"lang":"en","v":"CIRCLE SKY MEDIA LIMITED"}],"company_since":"2002-11-11","company_dissolved":"2005-06-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821259","names":[{"lang":"en","v":"FORWARD JEWELLERY CO. LIMITED"},{"lang":"hk","v":"滙進珠寶有限公司"}],"company_since":"2002-11-11","company_dissolved":"2004-04-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821095","names":[{"lang":"en","v":"FORWARD SERVICE LIMITED"},{"lang":"hk","v":"富盈服務有限公司"}],"company_since":"2002-11-11","company_dissolved":"2004-09-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821100","names":[{"lang":"en","v":"FOUNTAIN SERVICES LIMITED (d2009-05-22)"},{"lang":"hk","v":"方同有限公司"}],"company_since":"2002-11-11","company_dissolved":"2009-05-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821202","names":[{"lang":"en","v":"FRANCE POLYSSA (H.K.) LIMITED"},{"lang":"hk","v":"法國寶麗宣(香港)有限公司"}],"company_since":"2002-11-11","company_dissolved":"2011-11-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821142","names":[{"lang":"en","v":"FULL BASE CONSULTANTS LIMITED"},{"lang":"hk","v":"啟基顧問有限公司"}],"company_since":"2002-11-11","company_dissolved":"2005-10-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821087","names":[{"lang":"en","v":"COSMOS STAR NETWORK ECONOMICS &amp; CO-OPERATIVE DEVELOPMENT H.K. LIMITED"},{"lang":"hk","v":"宇宙星網絡經濟合作發展香港有限公司"}],"company_since":"2002-11-11","company_dissolved":"2010-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821205","names":[{"lang":"en","v":"FULL GLOBAL INVESTMENT LIMITED"},{"lang":"hk","v":"佳寶投資有限公司"}],"company_since":"2002-11-11","company_dissolved":"2009-03-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821139","names":[{"lang":"en","v":"FULLTEAM INTERNATIONAL (HK) LIMITED"},{"lang":"hk","v":"丰盛國際(香港)有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821218","names":[{"lang":"en","v":"DRAGON CITY INTERNATIONAL INDUSTRIAL LIMITED"},{"lang":"hk","v":"龍城國際實業有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821146","names":[{"lang":"en","v":"DRAGON HILL ASIA LIMITED"},{"lang":"hk","v":"龍山亞洲有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821240","names":[{"lang":"en","v":"GLOBAL LAND HOLDINGS LIMITED (d2005-05-27)"},{"lang":"hk","v":"嘉南集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"2005-05-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821216","names":[{"lang":"en","v":"GLOBE TRADE INTERNATIONAL INVESTMENT ENTERPRISE LIMITED"},{"lang":"hk","v":"世貿國際投資企業有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-03-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821137","names":[{"lang":"en","v":"GOLD HILL ASIA LIMITED"},{"lang":"hk","v":"金峰亞洲有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821203","names":[{"lang":"en","v":"GAINWAY TECHNOLOGIES LIMITED"},{"lang":"hk","v":"豐威科技有限公司"}],"company_since":"2002-11-11","company_dissolved":"2015-03-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821136","names":[{"lang":"en","v":"GOOD HONEST HOLDINGS LIMITED (d2004-05-28)"},{"lang":"hk","v":"誠佳集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"2004-05-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821231","names":[{"lang":"en","v":"ENGMA (CHINA) CO., LIMITED"},{"lang":"hk","v":"英格瑪(中國)有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821290","names":[{"lang":"en","v":"GREAT SUN INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"偉光國際集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821299","names":[{"lang":"en","v":"H.K. HUACHENG INT'L INV. PROPERLIES LIMITED"},{"lang":"hk","v":"香港華誠國際投資置業有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821181","names":[{"lang":"en","v":"GREAT RISE INTERNATIONAL ENTERPRISE LIMITED (d2009-07-17)"},{"lang":"hk","v":"偉昇國際企業有限公司"}],"company_since":"2002-11-11","company_dissolved":"2009-07-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821253","names":[{"lang":"en","v":"H.K. BILLIONWIN INT'L HOLDINGS LIMITED"},{"lang":"hk","v":"香港億聯國際集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821252","names":[{"lang":"en","v":"H.K. HUAYANG MEDICINE INT'L HOLDINGS LIMITED"},{"lang":"hk","v":"香港華洋藥業國際集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"2005-04-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821103","names":[{"lang":"en","v":"GREAT MERGE LIMITED"},{"lang":"hk","v":"偉濬有限公司"}],"company_since":"2002-11-11","company_dissolved":"2007-08-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821182","names":[{"lang":"en","v":"GRAND PACIFIC INTERNATIONAL DEVELOPMENT HOLDINGS LIMITED"},{"lang":"hk","v":"太平洋國際發展集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821102","names":[{"lang":"en","v":"Hansom Eastern International Trading (Group) Limited"},{"lang":"hk","v":"恒盛東方國際貿易(集團)有限公司"}],"company_since":"2002-11-11","company_dissolved":"2019-05-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821239","names":[{"lang":"en","v":"GRAND SMART INTERNATIONAL LIMITED"},{"lang":"hk","v":"彩英國際有限公司"}],"company_since":"2002-11-11","company_dissolved":"2015-08-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821105","names":[{"lang":"en","v":"GRAND GLORY INTERNATIONAL LIMITED (d2004-10-21)"},{"lang":"hk","v":"勁滔國際有限公司"}],"company_since":"2002-11-11","company_dissolved":"2004-10-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"821231","names":[{"lang":"en","v":"ENGMA (CHINA) CO., LIMITED"},{"lang":"hk","v":"英格瑪(中國)有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821217","names":[{"lang":"en","v":"EVER CREATION INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"恒創國際發展有限公司"}],"company_since":"2002-11-11","company_dissolved":"2004-09-10","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821095","names":[{"lang":"en","v":"FORWARD SERVICE LIMITED"},{"lang":"hk","v":"富盈服務有限公司"}],"company_since":"2002-11-11","company_dissolved":"2004-09-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821099","names":[{"lang":"en","v":"ETERNAL ASSET LIMITED (d2010-07-02)"},{"lang":"hk","v":"暐恒有限公司"}],"company_since":"2002-11-11","company_dissolved":"2010-07-02","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821202","names":[{"lang":"en","v":"FRANCE POLYSSA (H.K.) LIMITED"},{"lang":"hk","v":"法國寶麗宣(香港)有限公司"}],"company_since":"2002-11-11","company_dissolved":"2011-11-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821142","names":[{"lang":"en","v":"FULL BASE CONSULTANTS LIMITED"},{"lang":"hk","v":"啟基顧問有限公司"}],"company_since":"2002-11-11","company_dissolved":"2005-10-14","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821205","names":[{"lang":"en","v":"FULL GLOBAL INVESTMENT LIMITED"},{"lang":"hk","v":"佳寶投資有限公司"}],"company_since":"2002-11-11","company_dissolved":"2009-03-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821140","names":[{"lang":"en","v":"FULLSKY INTERNATIONAL TRADING LIMITED"},{"lang":"hk","v":"天丰國際貿易有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821235","names":[{"lang":"en","v":"EVER LEGEND ENGINEERING LIMITED"},{"lang":"hk","v":"永駿工程有限公司"}],"company_since":"2002-11-11","company_dissolved":"2015-04-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821184","names":[{"lang":"en","v":"EVERWELL INTERNATIONAL INVESTMENT ENTERPRISE LIMITED"},{"lang":"hk","v":"永隆國際投資企業有限公司"}],"company_since":"2002-11-11","company_dissolved":"2009-06-05","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821240","names":[{"lang":"en","v":"GLOBAL LAND HOLDINGS LIMITED (d2005-05-27)"},{"lang":"hk","v":"嘉南集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"2005-05-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821143","names":[{"lang":"en","v":"EXCEL POWER TECHNOLOGY LIMITED"},{"lang":"hk","v":"綽能科技有限公司"}],"company_since":"2002-11-11","company_dissolved":"2017-07-12","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821204","names":[{"lang":"en","v":"GLOBAL UNION ENTERPRISES LIMITED (d2010-10-15)"}],"company_since":"2002-11-11","company_dissolved":"2010-10-15","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821141","names":[{"lang":"en","v":"FAITH LOYAL (HONG KONG) LIMITED"},{"lang":"hk","v":"信源(香港)有限公司"}],"company_since":"2002-11-11","company_dissolved":"2012-06-01","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821137","names":[{"lang":"en","v":"GOLD HILL ASIA LIMITED"},{"lang":"hk","v":"金峰亞洲有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
{"tax_id":"821259","names":[{"lang":"en","v":"FORWARD JEWELLERY CO. LIMITED"},{"lang":"hk","v":"滙進珠寶有限公司"}],"company_since":"2002-11-11","company_dissolved":"2004-04-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821182","names":[{"lang":"en","v":"GRAND PACIFIC INTERNATIONAL DEVELOPMENT HOLDINGS LIMITED"},{"lang":"hk","v":"太平洋國際發展集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821105","names":[{"lang":"en","v":"GRAND GLORY INTERNATIONAL LIMITED (d2004-10-21)"},{"lang":"hk","v":"勁滔國際有限公司"}],"company_since":"2002-11-11","company_dissolved":"2004-10-21","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821233","names":[{"lang":"en","v":"FAR EAST CONTINENTAL SHIPPING LINE LIMITED"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821193","names":[{"lang":"en","v":"GRANDY KINDNESS FOOD WASTE TECHNOLOGY LIMITED"},{"lang":"hk","v":"泓惠廚餘科技有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-06-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821262","names":[{"lang":"en","v":"GREAT FORWARD LOGISTICS COMPANY LIMITED"},{"lang":"hk","v":"福運順物流管理有限公司"}],"company_since":"2002-11-11","company_dissolved":"2006-07-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"821264","names":[{"lang":"en","v":"FORE E. COMPANY LIMITED (d2011-11-18)"},{"lang":"hk","v":"科儀工程有限公司"}],"company_since":"2002-11-11","company_dissolved":"2011-11-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821192","names":[{"lang":"en","v":"GRAND DYNAMIC GROUP LIMITED"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821242","names":[{"lang":"en","v":"FIRST PACIFIC CONSULTANTS LIMITED"},{"lang":"hk","v":"豐恒顧問有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-03-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821103","names":[{"lang":"en","v":"GREAT MERGE LIMITED"},{"lang":"hk","v":"偉濬有限公司"}],"company_since":"2002-11-11","company_dissolved":"2007-08-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821290","names":[{"lang":"en","v":"GREAT SUN INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"偉光國際集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821237","names":[{"lang":"en","v":"FULL CAPITAL ENTERPRISES LIMITED (d2010-02-26)"},{"lang":"hk","v":"添富企業有限公司"}],"company_since":"2002-11-11","company_dissolved":"2010-02-26","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821253","names":[{"lang":"en","v":"H.K. BILLIONWIN INT'L HOLDINGS LIMITED"},{"lang":"hk","v":"香港億聯國際集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821299","names":[{"lang":"en","v":"H.K. HUACHENG INT'L INV. PROPERLIES LIMITED"},{"lang":"hk","v":"香港華誠國際投資置業有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"821138","names":[{"lang":"en","v":"FULLWAY INTERNATIONAL TRADING LIMITED (d2005-04-01)"},{"lang":"hk","v":"丰盛國際貿易有限公司"}],"company_since":"2002-11-11","company_dissolved":"2005-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821203","names":[{"lang":"en","v":"GAINWAY TECHNOLOGIES LIMITED"},{"lang":"hk","v":"豐威科技有限公司"}],"company_since":"2002-11-11","company_dissolved":"2015-03-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821206","names":[{"lang":"en","v":"Hermes Partners International Limited"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821263","names":[{"lang":"en","v":"HK KINGLAND INT'L GROUP LIMITED"},{"lang":"hk","v":"香港金大陸國際集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821091","names":[{"lang":"en","v":"HO PO CRANE LORRIES TRANSPORTATION LIMITED"},{"lang":"hk","v":"濠寶吊車運輸有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821129","names":[{"lang":"en","v":"HONESTY CORPORATE MANAGEMENT LIMITED"},{"lang":"hk","v":"誠信企業管理有限公司"}],"company_since":"2002-11-11","company_dissolved":"2013-04-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821278","names":[{"lang":"en","v":"HONG HU CRAFT HONG KONG LIMITED"},{"lang":"hk","v":"鴻鵠工藝香港有限公司"}],"company_since":"2002-11-11","company_dissolved":"2010-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"821294","names":[{"lang":"en","v":"HONG KONG EAST PEARL GROUP CO., LIMITED"},{"lang":"hk","v":"香港億思得珍珠集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"2017-01-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821135","names":[{"lang":"en","v":"GRAND DIGITAL INFORMATION (HK) LIMITED"}],"company_since":"2002-11-11","company_dissolved":"2007-01-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821136","names":[{"lang":"en","v":"GOOD HONEST HOLDINGS LIMITED (d2004-05-28)"},{"lang":"hk","v":"誠佳集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"2004-05-28","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821227","names":[{"lang":"en","v":"HONG KONG EDUCATION RESEARCH &amp; INTERCHANGE CENTRE LIMITED"},{"lang":"hk","v":"香港教育研究交流中心有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821295","names":[{"lang":"en","v":"HONG KONG KING FAI FINANCE GROUP INVESTMENT LIMITED"},{"lang":"hk","v":"香港景輝財務集團投資有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821232","names":[{"lang":"en","v":"HONG KONG LAOYECHE (YUN SHENG) INTERNATIONAL GROUP CO., LIMITED"},{"lang":"hk","v":"香港老爺車(云盛)國際集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821283","names":[{"lang":"en","v":"HONG KONG OKAYAMA CO., LIMITED"},{"lang":"hk","v":"香港岡山有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821086","names":[{"lang":"en","v":"HONG KONG PAEDIATRIC SOCIETY (THE)"},{"lang":"hk","v":"香港兒科醫學會"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"821268","names":[{"lang":"en","v":"HONG KONG SHE QUN INTERNATIONAL FURNITURE GROUP LIMITED"},{"lang":"hk","v":"香港社群國際傢俱集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821222","names":[{"lang":"en","v":"HONG KONG STRATEGIST ASSOCIATION LIMITED"},{"lang":"hk","v":"香港策劃師協會有限公司"}],"company_since":"2002-11-11","company_dissolved":"2015-04-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821239","names":[{"lang":"en","v":"GRAND SMART INTERNATIONAL LIMITED"},{"lang":"hk","v":"彩英國際有限公司"}],"company_since":"2002-11-11","company_dissolved":"2015-08-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821250","names":[{"lang":"en","v":"HONG KONG TIENTSIN (GROUP) LIMITED"},{"lang":"hk","v":"香港天津(集團)有限公司"}],"company_since":"2002-11-11","company_dissolved":"2018-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821097","names":[{"lang":"en","v":"HONG YICK GROUP COMPANY LIMITED"},{"lang":"hk","v":"香溢集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"2006-03-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821255","names":[{"lang":"en","v":"HONGKONG EVERNEW INT'L MEDICINE GROUP LIMITED"},{"lang":"hk","v":"香港永新國際藥業集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"2010-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821207","names":[{"lang":"en","v":"HONGKONG SINOLINK INTERNATIONAL GROUP LIMITED"},{"lang":"hk","v":"香港中聯國際集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"2009-03-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821200","names":[{"lang":"en","v":"HONGKONG YINDU VIDEO FILM CO., LIMITED"},{"lang":"hk","v":"香港銀都影視有限公司"}],"company_since":"2002-11-11","company_dissolved":"2018-06-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821134","names":[{"lang":"en","v":"HUGE DRAGON (CHINA) LIMITED"},{"lang":"hk","v":"巨龍(中國)有限公司"}],"company_since":"2002-11-11","company_dissolved":"2016-08-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821181","names":[{"lang":"en","v":"GREAT RISE INTERNATIONAL ENTERPRISE LIMITED (d2009-07-17)"},{"lang":"hk","v":"偉昇國際企業有限公司"}],"company_since":"2002-11-11","company_dissolved":"2009-07-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821256","names":[{"lang":"en","v":"HUMAND ELECTRONICS (HK) CO., LIMITED"},{"lang":"hk","v":"輝安達電器(香港)有限公司"}],"company_since":"2002-11-11","company_dissolved":"2005-06-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821132","names":[{"lang":"en","v":"In-T Workshop Limited"},{"lang":"hk","v":"彥築設計工程有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821198","names":[{"lang":"en","v":"INFO TELECOM LIMITED"},{"lang":"hk","v":"航科信通科技有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821248","names":[{"lang":"en","v":"INNOVISION TECHNOLOGIES (H.K.) CO., LIMITED"},{"lang":"hk","v":"華夏創新信息技術(香港)有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-05-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821252","names":[{"lang":"en","v":"H.K. HUAYANG MEDICINE INT'L HOLDINGS LIMITED"},{"lang":"hk","v":"香港華洋藥業國際集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"2005-04-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821230","names":[{"lang":"en","v":"ITALY AN FEI ER INTERNATIONAL LIMITED"},{"lang":"hk","v":"意大利安斐爾國際有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821102","names":[{"lang":"en","v":"Hansom Eastern International Trading (Group) Limited"},{"lang":"hk","v":"恒盛東方國際貿易(集團)有限公司"}],"company_since":"2002-11-11","company_dissolved":"2019-05-10","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821238","names":[{"lang":"en","v":"JOINTIME INDUSTRIAL LIMITED"},{"lang":"hk","v":"合泰實業有限公司"}],"company_since":"2002-11-11","company_dissolved":"2016-12-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821220","names":[{"lang":"en","v":"HARROGATE CONTRACTUAL CONSULTANTS LIMITED"}],"company_since":"2002-11-11","company_dissolved":"2005-06-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821175","names":[{"lang":"en","v":"JP-ORIENTAL INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"嘉平世東國際集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821094","names":[{"lang":"en","v":"K &amp; T JEWELLERY MANUFACTURER COMPANY LIMITED"},{"lang":"hk","v":"勤達珠寶製造有限公司"}],"company_since":"2002-11-11","company_dissolved":"2009-04-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821249","names":[{"lang":"en","v":"KAWI PACIFIC LIMITED"},{"lang":"hk","v":"嘉匯太平洋有限公司"}],"company_since":"2002-11-11","company_dissolved":"2011-11-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821293","names":[{"lang":"en","v":"KEI YUNG CO., LIMITED"},{"lang":"hk","v":"綺緣有限公司"}],"company_since":"2002-11-11","company_dissolved":"2011-02-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821229","names":[{"lang":"en","v":"HONG KONG AI DI (SAN XIN) FURNITURE GROUP LIMITED"},{"lang":"hk","v":"香港愛迪(三鑫)傢俬集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821133","names":[{"lang":"en","v":"KEY CONCEPT ASIA LIMITED"},{"lang":"hk","v":"啟創亞洲有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821131","names":[{"lang":"en","v":"KING BRIGHT CONSULTANTS LIMITED"},{"lang":"hk","v":"耀輝顧問有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821130","names":[{"lang":"en","v":"KING DRAGON (CHINA) LIMITED (d2004-04-16)"},{"lang":"hk","v":"威龍(中國)有限公司"}],"company_since":"2002-11-11","company_dissolved":"2004-04-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821101","names":[{"lang":"en","v":"KODIA COMPANY LIMITED"}],"company_since":"2002-11-11","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821090","names":[{"lang":"en","v":"LEUNG CHI PLASTERING CONSTRUCTION COMPANY LIMITED"},{"lang":"hk","v":"梁枝泥水工程有限公司"}],"company_since":"2002-11-11","company_dissolved":"2012-01-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821128","names":[{"lang":"en","v":"LONG HARVEST (HONG KONG) LIMITED"},{"lang":"hk","v":"長溢(香港)有限公司"}],"company_since":"2002-11-11","company_dissolved":"2005-01-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821280","names":[{"lang":"en","v":"KAI KANG METAL &amp; PLASTIC COMPANY LIMITED"},{"lang":"hk","v":"凱慷五金塑膠有限公司"}],"company_since":"2002-11-11","company_dissolved":"2013-06-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821215","names":[{"lang":"en","v":"LONG HARVEST INTERNATIONAL ENTERPRISE LIMITED"},{"lang":"hk","v":"長盛國際企業有限公司"}],"company_since":"2002-11-11","company_dissolved":"2006-10-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"821286","names":[{"lang":"en","v":"NORTH TEAM INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"兆聯國際集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821213","names":[{"lang":"en","v":"OC INDUSTRIAL SUPPLIES CO., LIMITED"},{"lang":"hk","v":"華拓國際實業有限公司"}],"company_since":"2002-11-11","company_dissolved":"2011-11-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821180","names":[{"lang":"en","v":"LOYAL VIEW INTERNATIONAL LIMITED (d2008-04-03)"}],"company_since":"2002-11-11","company_dissolved":"2008-04-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821277","names":[{"lang":"en","v":"PLENTIFUL INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"豐滙國際發展有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821176","names":[{"lang":"en","v":"POLY HARVEST INTERNATIONAL DEVELOPMENT HOLDINGS LIMITED"},{"lang":"hk","v":"百利豐國際發展集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"2016-07-08","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821291","names":[{"lang":"en","v":"LUBIN ENVIRONMENTAL PROTECTION EQUIPMENT (HK) COMPANY LIMITED"},{"lang":"hk","v":"鷺濱環保設備(香港)有限公司"}],"company_since":"2002-11-11","company_dissolved":"2007-02-23","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821174","names":[{"lang":"en","v":"POLYTEK INTERNATIONAL DEVELOPMENT HOLDINGS LIMITED"},{"lang":"hk","v":"百富達國際發展集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"2016-07-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821126","names":[{"lang":"en","v":"POWER CONCEPT MANAGEMENT LIMITED"},{"lang":"hk","v":"創力管理有限公司"}],"company_since":"2002-11-11","company_dissolved":"2006-05-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821191","names":[{"lang":"en","v":"PRO-CENTRIC GROUP LIMITED"},{"lang":"hk","v":"太豐世紀集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821195","names":[{"lang":"en","v":"MASTER PRO TRADING LIMITED"},{"lang":"hk","v":"聰敏貿易有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821124","names":[{"lang":"en","v":"RAINBOW DRAGON HOLDINGS LIMITED"},{"lang":"hk","v":"彩龍集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-03-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821123","names":[{"lang":"en","v":"RAINBOW HILL (HONG KONG) LIMITED"},{"lang":"hk","v":"彩峰(香港)有限公司"}],"company_since":"2002-11-11","company_dissolved":"2009-07-03","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821197","names":[{"lang":"en","v":"RESOURCE (RSR) LIMITED"},{"lang":"hk","v":"資源有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821214","names":[{"lang":"en","v":"MASTER WAY INTERNATIONAL ENTERPRISE LIMITED"},{"lang":"hk","v":"萬通國際企業有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821279","names":[{"lang":"en","v":"REVIVO ENTERPRISES LIMITED"},{"lang":"hk","v":"力威企業有限公司"}],"company_since":"2002-11-11","company_dissolved":"2013-12-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821209","names":[{"lang":"en","v":"SFO LIGHTING (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"索菲照明(香港)有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821104","names":[{"lang":"en","v":"MILESTONE MEDIAWARE SOLUTIONS LIMITED"},{"lang":"hk","v":"里程視介軟件有限公司"}],"company_since":"2002-11-11","company_dissolved":"2010-04-01","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821173","names":[{"lang":"en","v":"SINO STATE INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"中邦國際發展有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821178","names":[{"lang":"en","v":"MILLION KING INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"萬強國際發展有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821274","names":[{"lang":"en","v":"SINO WELLON INVESTMENT INT'L LIMITED"},{"lang":"hk","v":"中信華安投資國際有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821121","names":[{"lang":"en","v":"SINOSKY INTERNATIONAL TRADING LIMITED (d2005-09-16)"},{"lang":"hk","v":"天華國際貿易有限公司"}],"company_since":"2002-11-11","company_dissolved":"2005-09-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821210","names":[{"lang":"en","v":"SKY FAITH INTERNATIONAL INDUSTRIAL LIMITED"},{"lang":"hk","v":"天信國際實業有限公司"}],"company_since":"2002-11-11","company_dissolved":"2005-03-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821254","names":[{"lang":"en","v":"SKY INTERIOR DESIGN LIMITED"},{"lang":"hk","v":"天設計有限公司"}],"company_since":"2002-11-11","company_dissolved":"2009-03-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821120","names":[{"lang":"en","v":"SKY ON ASIA LIMITED"},{"lang":"hk","v":"天進亞洲有限公司"}],"company_since":"2002-11-11","company_dissolved":"2019-08-16","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821292","names":[{"lang":"en","v":"KAGO INDUSTRIAL (HK) LIMITED"},{"lang":"hk","v":"奇高實業(香港)有限公司"}],"company_since":"2002-11-11","company_dissolved":"2012-12-28","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821177","names":[{"lang":"en","v":"OPEAN CHINA INTERNATIONAL DEVELOPMENT HOLDINGS LIMITED"},{"lang":"hk","v":"華拓國際發展集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"2020-11-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821225","names":[{"lang":"en","v":"New Silk Route Holdings Limited"},{"lang":"hk","v":"新絲綢之路控股有限公司"}],"company_since":"2002-11-11","company_dissolved":"2010-09-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821117","names":[{"lang":"en","v":"SKYWAY INTERNATIONAL TRADING LIMITED"},{"lang":"hk","v":"順天國際貿易有限公司"}],"company_since":"2002-11-11","company_dissolved":"2009-05-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821092","names":[{"lang":"en","v":"SMART KIDS COLLECTIONS CO LIMITED"},{"lang":"hk","v":"火車頭時裝精品有限公司"}],"company_since":"2002-11-11","company_dissolved":"2004-07-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821212","names":[{"lang":"en","v":"POLY HARVEST INTERNATIONAL INVESTMENT ENTERPRISE LIMITED"},{"lang":"hk","v":"永利豐國際投資企業有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821116","names":[{"lang":"en","v":"SOUTH BASE (CHINA) LIMITED"},{"lang":"hk","v":"南基(中國)有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821236","names":[{"lang":"en","v":"STAR KINETIC LIMITED (d2007-05-11)"},{"lang":"hk","v":"星德有限公司"}],"company_since":"2002-11-11","company_dissolved":"2007-05-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821285","names":[{"lang":"en","v":"PROFESSIONAL INTERNATIONAL HOLDINGS LIMITED (d2005-04-01)"},{"lang":"hk","v":"專業國際集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"2005-04-01","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821114","names":[{"lang":"en","v":"SUNNY FORTUNE ASIA LIMITED"},{"lang":"hk","v":"瑞輝亞洲有限公司"}],"company_since":"2002-11-11","company_dissolved":"2004-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821096","names":[{"lang":"en","v":"QINZUN INTERNATIONAL GROUP CO., LIMITED"},{"lang":"hk","v":"秦尊國際集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"2009-03-27","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821168","names":[{"lang":"en","v":"TAI PANG INTERNATIONAL INVESTMENT ENTERPRISE LIMITED"},{"lang":"hk","v":"太平國際投資企業有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821284","names":[{"lang":"en","v":"TAKANE PRECISION HONG KONG LIMITED"},{"lang":"hk","v":"高根精工香港有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821211","names":[{"lang":"en","v":"SINO GIANT INTERNATIONAL ENTERPRISE LIMITED"},{"lang":"hk","v":"巨華國際企業有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821112","names":[{"lang":"en","v":"TEAM EVER HOLDINGS LIMITED"},{"lang":"hk","v":"滙恒集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821122","names":[{"lang":"en","v":"SINO PROFIT INTERNATIONAL (HK) LIMITED"},{"lang":"hk","v":"華利國際(香港)有限公司"}],"company_since":"2002-11-11","company_dissolved":"2011-08-05","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821093","names":[{"lang":"en","v":"TIAN YU DI ENTERTAINMENT GROUP LIMITED"},{"lang":"hk","v":"天與地娛樂集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-08-08","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821167","names":[{"lang":"en","v":"TIME FAITH INTERNATIONAL DEVELOPMENT LIMITED (d2008-03-20)"},{"lang":"hk","v":"時信國際發展有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821172","names":[{"lang":"en","v":"SINO TRADE INTERNATIONAL DEVELOPMENT HOLDINGS LIMITED"},{"lang":"hk","v":"華貿國際發展集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"2005-05-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821244","names":[{"lang":"en","v":"SKILCRAFTS INTERNATIONAL LIMITED"}],"company_since":"2002-11-11","company_dissolved":"2010-10-15","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821190","names":[{"lang":"en","v":"TOURMALINE HOLDINGS LIMITED (d2011-12-02)"}],"company_since":"2002-11-11","company_dissolved":"2011-12-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821298","names":[{"lang":"en","v":"TurboCATS Limited"},{"lang":"hk","v":"賽益達有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821171","names":[{"lang":"en","v":"SKY PROFIT INTERNATIONAL INVESTMENT ENTERPRISE LIMITED"},{"lang":"hk","v":"天利國際投資企業有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821152","names":[{"lang":"en","v":"TWIN WORLD DISTRIBUTION LIMITED"},{"lang":"hk","v":"盈滙堂分銷有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-10-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821170","names":[{"lang":"en","v":"SKYCOM INTERNATIONAL DEVELOPMENT HOLDINGS LIMITED"},{"lang":"hk","v":"天來國際發展集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"2010-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821119","names":[{"lang":"en","v":"SKYFAITH INTERNATIONAL (HK) LIMITED"},{"lang":"hk","v":"天信國際(香港)有限公司"}],"company_since":"2002-11-11","company_dissolved":"2015-09-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821109","names":[{"lang":"en","v":"UNITED PROFIT INTERNATIONAL (HK) LIMITED"},{"lang":"hk","v":"滙利國際(香港)有限公司"}],"company_since":"2002-11-11","company_dissolved":"2006-12-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821089","names":[{"lang":"en","v":"VINTECH ACCOUNTING SERVICES LIMITED"},{"lang":"hk","v":"寶時會計服務有限公司"}],"company_since":"2002-11-11","company_dissolved":"2020-05-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821273","names":[{"lang":"en","v":"WAH TUNG MATERIAL LIMITED"},{"lang":"hk","v":"華東原料有限公司"}],"company_since":"2002-11-11","company_dissolved":"2013-03-17","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821115","names":[{"lang":"en","v":"SOUTH BASE ASIA LIMITED (d2010-04-01)"},{"lang":"hk","v":"南基亞洲有限公司"}],"company_since":"2002-11-11","company_dissolved":"2010-04-01","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821272","names":[{"lang":"en","v":"WAI FONG INTERNATIONAL DEVELOPMENT GROUP (H.K.) COMPANY LIMITED"},{"lang":"hk","v":"匯芳國際貿易發展(香港)有限公司"}],"company_since":"2002-11-11","company_dissolved":"2004-04-23","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821169","names":[{"lang":"en","v":"SOUTH KING INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"南威國際發展有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821260","names":[{"lang":"en","v":"WEALTH INVESTMENT &amp; DEVELOPMENT LIMITED"},{"lang":"hk","v":"裕富投資發展有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821208","names":[{"lang":"en","v":"SUN NGAI PLASTIC MANUFACTORY LIMITED"},{"lang":"hk","v":"新藝塑膠廠有限公司"}],"company_since":"2002-11-11","company_dissolved":"2011-03-25","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821164","names":[{"lang":"en","v":"WEALTH POWER INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"寶力國際發展有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-07-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821113","names":[{"lang":"en","v":"SUPER TALENT TECHNOLOGY LIMITED"},{"lang":"hk","v":"超綽科技有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821098","names":[{"lang":"en","v":"WELL BLOOM INTERNATIONAL LIMITED"},{"lang":"hk","v":"進裕洋行國際有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821271","names":[{"lang":"en","v":"T &amp; N ASSOCIATES LIMITED (d2008-03-20)"},{"lang":"hk","v":"正簡有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"821282","names":[{"lang":"en","v":"TAK KEE PAPER PRODUCTS (GROUP) LIMITED"},{"lang":"hk","v":"德記紙業(集團)有限公司"}],"company_since":"2002-11-11","company_dissolved":"2017-10-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"821107","names":[{"lang":"en","v":"WIN SKY (CHINA) LIMITED"},{"lang":"hk","v":"天勝(中國)有限公司"}],"company_since":"2002-11-11","company_dissolved":"2016-12-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821247","names":[{"lang":"en","v":"WINNING BRIDGE ENGINEERING LIMITED"},{"lang":"hk","v":"橋勝工程有限公司"}],"company_since":"2002-11-11","company_dissolved":"2015-01-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821106","names":[{"lang":"en","v":"WTSM (WORLD TRADING STOCK MANAGEMENT) LIMITED"},{"lang":"hk","v":"世貿倉儲管理有限公司"}],"company_since":"2002-11-11","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"821110","names":[{"lang":"en","v":"TRIUMPH SKY HOLDINGS LIMITED"},{"lang":"hk","v":"天勝集團有限公司"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821301","names":[{"lang":"en","v":"TWINKSON INVESTMENTS LIMITED"}],"company_since":"2002-11-11","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821088","names":[{"lang":"en","v":"WANG ON TONG LIMITED"},{"lang":"hk","v":"宏安堂有限公司"}],"company_since":"2002-11-11","company_dissolved":"2015-04-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821163","names":[{"lang":"en","v":"WEALTHY OCEAN INTERNATIONAL INVESTMENT ENTERPRISE LIMITED"},{"lang":"hk","v":"海富國際投資企業有限公司"}],"company_since":"2002-11-11","company_dissolved":"2004-06-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821161","names":[{"lang":"en","v":"WELL FORTUNE INTERNATIONAL INVESTMENT ENTERPRISE LIMITED"},{"lang":"hk","v":"百富達國際投資企業有限公司"}],"company_since":"2002-11-11","company_dissolved":"2019-09-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821108","names":[{"lang":"en","v":"WIDE BASE CONSULTANTS LIMITED"},{"lang":"hk","v":"弘基顧問有限公司"}],"company_since":"2002-11-11","company_dissolved":"2018-07-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821162","names":[{"lang":"en","v":"WIN PROFIT INTERNATIONAL ENTERPRISE LIMITED"},{"lang":"hk","v":"凱利國際企業有限公司"}],"company_since":"2002-11-11","company_dissolved":"2009-04-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"821160","names":[{"lang":"en","v":"WINSKY INTERNATIONAL INDUSTRIAL LIMITED"},{"lang":"hk","v":"天勝國際實業有限公司"}],"company_since":"2002-11-11","company_dissolved":"2007-12-28","company_type_txt":"Private, ltd by shares"},
