{"tax_id":"820604","names":[{"lang":"en","v":"CHINA INTEGRATED EXECUTION PRODUCTION (H.K) INT'L COMPANY LIMITED"},{"lang":"hk","v":"中華綜合娛樂製作(香港)國際有限公司"}],"company_since":"2002-11-06","company_dissolved":"2018-04-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820667","names":[{"lang":"en","v":"CHINA UNION INVESTMENTS LIMITED (d2008-01-25)"},{"lang":"hk","v":"中略投資有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-01-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820730","names":[{"lang":"en","v":"CHINALINK LOGISTICS LIMITED"},{"lang":"hk","v":"運通(中港)物流有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820497","names":[{"lang":"en","v":"CHINAPILOT ENTERPRISES INTERNATIONAL LIMITED"}],"company_since":"2002-11-06","company_dissolved":"2018-07-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820593","names":[{"lang":"en","v":"CHUN SHING LOGISTICS COMPANY LIMITED"},{"lang":"hk","v":"鎮成物流有限公司"}],"company_since":"2002-11-06","company_dissolved":"2009-12-31","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820535","names":[{"lang":"en","v":"COLOUR XCHANGE PRODUCTS (HONG KONG) LIMITED"},{"lang":"hk","v":"藝思製品(香港)有限公司"}],"company_since":"2002-11-06","company_dissolved":"2004-11-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820629","names":[{"lang":"en","v":"CREATIVE CHINA INTERNATIONAL LIMITED"},{"lang":"hk","v":"智華國際有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820532","names":[{"lang":"en","v":"CREATIVE FUN EDUCATION LIMITED"},{"lang":"hk","v":"紛紛教育有限公司"}],"company_since":"2002-11-06","company_dissolved":"2009-12-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820476","names":[{"lang":"en","v":"CREPAY LIMITED"}],"company_since":"2002-11-06","company_dissolved":"2015-08-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820693","names":[{"lang":"en","v":"DAYLIGHT TRADING HK LIMITED"}],"company_since":"2002-11-06","company_dissolved":"2010-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820489","names":[{"lang":"en","v":"DECORICH INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"美泰國際股份有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820598","names":[{"lang":"en","v":"DRAGON MODELS (HOLDING) LIMITED"},{"lang":"hk","v":"威龍模型(集團)有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"820615","names":[{"lang":"en","v":"ECOPOWER INDUSTRIAL LIMITED"},{"lang":"hk","v":"毅強實業有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820663","names":[{"lang":"en","v":"EASTCO GROUP LIMITED"},{"lang":"hk","v":"儀高集團有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820703","names":[{"lang":"en","v":"EMDRAGON TECHNOLOGY COMPANY LIMITED"},{"lang":"hk","v":"研智科技有限公司"}],"company_since":"2002-11-06","company_dissolved":"2010-05-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820732","names":[{"lang":"en","v":"CHINA INN HOTEL CHAIN COMPANY LIMITED"},{"lang":"hk","v":"華夏客棧酒店連鎖有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-08-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820508","names":[{"lang":"en","v":"EURO TREAT LIMITED"},{"lang":"hk","v":"歐陸丰味有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820478","names":[{"lang":"en","v":"CHOICEST INVESTMENT LIMITED"},{"lang":"hk","v":"凱斯特投資有限公司"}],"company_since":"2002-11-06","company_dissolved":"2004-01-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820455","names":[{"lang":"en","v":"EVER PEAK (ASIA) LIMITED (d2005-08-12)"}],"company_since":"2002-11-06","company_dissolved":"2005-08-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820679","names":[{"lang":"en","v":"CHUNG WAI TRADING (FAR EAST) LIMITED"},{"lang":"hk","v":"中偉貿易(遠東)有限公司"}],"company_since":"2002-11-06","company_dissolved":"2004-04-16","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820471","names":[{"lang":"en","v":"EXCELLENT CREATION (HK) LIMITED"},{"lang":"hk","v":"創新珠寶有限公司"}],"company_since":"2002-11-06","company_dissolved":"2009-10-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820682","names":[{"lang":"en","v":"EXTRAVERT LIMITED (d2013-01-11)"}],"company_since":"2002-11-06","company_dissolved":"2013-01-11","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820563","names":[{"lang":"en","v":"CLUB CO. LIMITED (THE)"}],"company_since":"2002-11-06","company_dissolved":"2005-07-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820584","names":[{"lang":"en","v":"F-1 MERCHANDISING AND PROMOTION (HK) LIMITED"}],"company_since":"2002-11-06","company_dissolved":"2011-11-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820527","names":[{"lang":"en","v":"FAIR HERO DEVELOPMENT LIMITED"},{"lang":"hk","v":"香港雄輝發展有限公司"}],"company_since":"2002-11-06","company_dissolved":"2017-08-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820586","names":[{"lang":"en","v":"COCO ENTERPRISE (H.K.) CO., LIMITED"},{"lang":"hk","v":"可可企業(香港)有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820636","names":[{"lang":"en","v":"FIRST CALL CONSULTING LIMITED"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820638","names":[{"lang":"en","v":"FLEA KING LIMITED"},{"lang":"hk","v":"跳蚤王有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-07-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820669","names":[{"lang":"en","v":"FLY DRAGON DEVELOPMENT LIMITED"},{"lang":"hk","v":"騰龍發展有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820589","names":[{"lang":"en","v":"CONTOUR HONG KONG LIMITED"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820660","names":[{"lang":"en","v":"CONVOY ASIA LIMITED"},{"lang":"hk","v":"康宏亞洲有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820725","names":[{"lang":"en","v":"COPO BIO TECHNOLOGIES CO., LIMITED"},{"lang":"hk","v":"科寶生物工程有限公司"}],"company_since":"2002-11-06","company_dissolved":"2009-08-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820709","names":[{"lang":"en","v":"FRANCE YORK HON SITE KA (H.K.) FASHION COMPANY LIMITED"},{"lang":"hk","v":"法國約翰世家(香港)服飾有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820714","names":[{"lang":"en","v":"FRANCE YASHI GROUP (H.K.) CO., LIMITED"},{"lang":"hk","v":"法國雅詩集團(香港)有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820605","names":[{"lang":"en","v":"FREMERY SHIPPING LIMITED"},{"lang":"hk","v":"華隆航運有限公司"}],"company_since":"2002-11-06","company_dissolved":"2015-08-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820653","names":[{"lang":"en","v":"FU WING WA FOOD HOLDINGS LIMITED"},{"lang":"hk","v":"富榮華食品集團有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820671","names":[{"lang":"en","v":"FUSION HOLDINGS LIMITED (HK)"},{"lang":"hk","v":"富信控股有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820656","names":[{"lang":"en","v":"GAMA TECHNOLOGY LIMITED"},{"lang":"hk","v":"基碼科技有限公司"}],"company_since":"2002-11-06","company_dissolved":"2012-01-06","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820526","names":[{"lang":"en","v":"CSURE GLOBAL TOOLING IMPORT &amp; EXPORT (HK) LIMITED"},{"lang":"hk","v":"華信機械模具貿易(香港)有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820620","names":[{"lang":"en","v":"CYBER FORTUNE CORPORATION LIMITED"},{"lang":"hk","v":"紹豐有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820546","names":[{"lang":"en","v":"GARBER (HK) LIMITED"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820668","names":[{"lang":"en","v":"DRAGON CITY (HONG KONG) LIMITED"},{"lang":"hk","v":"龍城(香港)有限公司"}],"company_since":"2002-11-06","company_dissolved":"2005-12-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820590","names":[{"lang":"en","v":"GLOBALWARE SOLUTIONS (HONG KONG) LIMITED"}],"company_since":"2002-11-06","company_dissolved":"2013-04-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820510","names":[{"lang":"en","v":"GERMANY DUOMEI INTERNATIONAL GROUP (HK) LIMITED"},{"lang":"hk","v":"德國多美國際集團(香港)有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820621","names":[{"lang":"en","v":"DYNAMIC CAREER LIMITED"},{"lang":"hk","v":"展業有限公司"}],"company_since":"2002-11-06","company_dissolved":"2006-07-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820539","names":[{"lang":"en","v":"GOLDEN OCEAN LIMITED (b2002-11-06)"},{"lang":"hk","v":"金海(遠東)有限公司"}],"company_since":"2002-11-06","company_dissolved":"2018-07-13","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820649","names":[{"lang":"en","v":"E M J CORPORATION LIMITED"},{"lang":"hk","v":"鹽光企業有限公司"}],"company_since":"2002-11-06","company_dissolved":"2010-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820585","names":[{"lang":"en","v":"GREAT TECH ASIA LIMITED"},{"lang":"hk","v":"科偉亞洲有限公司"}],"company_since":"2002-11-06","company_dissolved":"2003-10-03","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820494","names":[{"lang":"en","v":"GROWTH INVESTMENTS MANAGEMENT LIMITED"},{"lang":"hk","v":"增長投資有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820721","names":[{"lang":"en","v":"EFATAR ACRON LIMITED"}],"company_since":"2002-11-06","company_dissolved":"2004-06-04","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820523","names":[{"lang":"en","v":"H.K. GONGXILU INT'L INDUSTRIAL LIMITED"},{"lang":"hk","v":"香港恭喜路國際實業有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820567","names":[{"lang":"en","v":"CHINA TIGER CAPITAL MANAGEMENT LIMITED"},{"lang":"hk","v":"泰極資產管理有限公司"}],"company_since":"2002-11-06","company_dissolved":"2015-12-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820640","names":[{"lang":"en","v":"HING TAT FIBREGLASS PRODUCTS LIMITED"},{"lang":"hk","v":"興達玻纖製品有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820553","names":[{"lang":"en","v":"HK INTERNATIONAL PERFUME GROUP TECHNOLOGY DEVELOPMENT CO., LIMITED"},{"lang":"hk","v":"香港國際香科集團科技發展有限公司"}],"company_since":"2002-11-06","company_dissolved":"2011-02-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820529","names":[{"lang":"en","v":"HK TOPDO MARKETING COMMUNICATION CO., LIMITED"},{"lang":"hk","v":"香港太度營銷傳播有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820614","names":[{"lang":"en","v":"HIGHPOINT TECHNOLOGIES LIMITED"},{"lang":"hk","v":"駿昇科技有限公司"}],"company_since":"2002-11-06","company_dissolved":"2005-09-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820486","names":[{"lang":"en","v":"HK DAILY GROUP INT'L DEV. LIMITED"},{"lang":"hk","v":"香港每日集團國際發展有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820643","names":[{"lang":"en","v":"HANG LEE TRANSPORTATION ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"恒利搬機工程有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820452","names":[{"lang":"en","v":"HMC INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"海明國際管理顧問服務有限公司"}],"company_since":"2002-11-06","company_dissolved":"2011-08-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820652","names":[{"lang":"en","v":"HING FAT CONSTRUCTION COMPANY LIMITED"},{"lang":"hk","v":"興發裝飾工程有限公司"}],"company_since":"2002-11-06","company_dissolved":"2018-01-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820664","names":[{"lang":"en","v":"HANSON (HONG KONG) LIMITED"},{"lang":"hk","v":"康臣(香港)有限公司"}],"company_since":"2002-11-06","company_dissolved":"2004-03-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820587","names":[{"lang":"en","v":"HOI JAN CLUB LIMITED"},{"lang":"hk","v":"海雀會有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820706","names":[{"lang":"en","v":"HAPPY ACADEMY LIMITED (d2006-06-02)"},{"lang":"hk","v":"開心學堂有限公司"}],"company_since":"2002-11-06","company_dissolved":"2006-06-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"820721","names":[{"lang":"en","v":"EFATAR ACRON LIMITED"}],"company_since":"2002-11-06","company_dissolved":"2004-06-04","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820703","names":[{"lang":"en","v":"EMDRAGON TECHNOLOGY COMPANY LIMITED"},{"lang":"hk","v":"研智科技有限公司"}],"company_since":"2002-11-06","company_dissolved":"2010-05-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820508","names":[{"lang":"en","v":"EURO TREAT LIMITED"},{"lang":"hk","v":"歐陸丰味有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820628","names":[{"lang":"en","v":"EUSTON INTERNATIONAL LIMITED"},{"lang":"hk","v":"裕信國際有限公司"}],"company_since":"2002-11-06","company_dissolved":"2009-06-19","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820526","names":[{"lang":"en","v":"CSURE GLOBAL TOOLING IMPORT &amp; EXPORT (HK) LIMITED"},{"lang":"hk","v":"華信機械模具貿易(香港)有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820620","names":[{"lang":"en","v":"CYBER FORTUNE CORPORATION LIMITED"},{"lang":"hk","v":"紹豐有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820682","names":[{"lang":"en","v":"EXTRAVERT LIMITED (d2013-01-11)"}],"company_since":"2002-11-06","company_dissolved":"2013-01-11","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820584","names":[{"lang":"en","v":"F-1 MERCHANDISING AND PROMOTION (HK) LIMITED"}],"company_since":"2002-11-06","company_dissolved":"2011-11-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820527","names":[{"lang":"en","v":"FAIR HERO DEVELOPMENT LIMITED"},{"lang":"hk","v":"香港雄輝發展有限公司"}],"company_since":"2002-11-06","company_dissolved":"2017-08-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820489","names":[{"lang":"en","v":"DECORICH INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"美泰國際股份有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820636","names":[{"lang":"en","v":"FIRST CALL CONSULTING LIMITED"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820668","names":[{"lang":"en","v":"DRAGON CITY (HONG KONG) LIMITED"},{"lang":"hk","v":"龍城(香港)有限公司"}],"company_since":"2002-11-06","company_dissolved":"2005-12-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820598","names":[{"lang":"en","v":"DRAGON MODELS (HOLDING) LIMITED"},{"lang":"hk","v":"威龍模型(集團)有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820621","names":[{"lang":"en","v":"DYNAMIC CAREER LIMITED"},{"lang":"hk","v":"展業有限公司"}],"company_since":"2002-11-06","company_dissolved":"2006-07-14","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820656","names":[{"lang":"en","v":"GAMA TECHNOLOGY LIMITED"},{"lang":"hk","v":"基碼科技有限公司"}],"company_since":"2002-11-06","company_dissolved":"2012-01-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820705","names":[{"lang":"en","v":"GAVEKAL CAPITAL LIMITED"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820649","names":[{"lang":"en","v":"E M J CORPORATION LIMITED"},{"lang":"hk","v":"鹽光企業有限公司"}],"company_since":"2002-11-06","company_dissolved":"2010-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820615","names":[{"lang":"en","v":"ECOPOWER INDUSTRIAL LIMITED"},{"lang":"hk","v":"毅強實業有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820572","names":[{"lang":"en","v":"EMERGIS CAPITAL LIMITED"},{"lang":"hk","v":"瑞熙發展投資有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820671","names":[{"lang":"en","v":"FUSION HOLDINGS LIMITED (HK)"},{"lang":"hk","v":"富信控股有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820590","names":[{"lang":"en","v":"GLOBALWARE SOLUTIONS (HONG KONG) LIMITED"}],"company_since":"2002-11-06","company_dissolved":"2013-04-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820539","names":[{"lang":"en","v":"GOLDEN OCEAN LIMITED (b2002-11-06)"},{"lang":"hk","v":"金海(遠東)有限公司"}],"company_since":"2002-11-06","company_dissolved":"2018-07-13","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820672","names":[{"lang":"en","v":"GOLDLION INVESTMENTS LIMITED"},{"lang":"hk","v":"金利來投資有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-07-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820455","names":[{"lang":"en","v":"EVER PEAK (ASIA) LIMITED (d2005-08-12)"}],"company_since":"2002-11-06","company_dissolved":"2005-08-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820471","names":[{"lang":"en","v":"EXCELLENT CREATION (HK) LIMITED"},{"lang":"hk","v":"創新珠寶有限公司"}],"company_since":"2002-11-06","company_dissolved":"2009-10-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820494","names":[{"lang":"en","v":"GROWTH INVESTMENTS MANAGEMENT LIMITED"},{"lang":"hk","v":"增長投資有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820534","names":[{"lang":"en","v":"EXCELLENT MANAGEMENT OF FUND COMPANY LIMITED"},{"lang":"hk","v":"宏豐管理基金有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820523","names":[{"lang":"en","v":"H.K. GONGXILU INT'L INDUSTRIAL LIMITED"},{"lang":"hk","v":"香港恭喜路國際實業有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820697","names":[{"lang":"en","v":"H.K. LIGONG COOLING APPARATUS MAKING LIMITED"},{"lang":"hk","v":"香港李工冷凍設備制造有限公司"}],"company_since":"2002-11-06","company_dissolved":"2010-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820664","names":[{"lang":"en","v":"HANSON (HONG KONG) LIMITED"},{"lang":"hk","v":"康臣(香港)有限公司"}],"company_since":"2002-11-06","company_dissolved":"2004-03-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820706","names":[{"lang":"en","v":"HAPPY ACADEMY LIMITED (d2006-06-02)"},{"lang":"hk","v":"開心學堂有限公司"}],"company_since":"2002-11-06","company_dissolved":"2006-06-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820477","names":[{"lang":"en","v":"HELICON RESOURCES LIMITED"},{"lang":"hk","v":"和利豐實業有限公司"}],"company_since":"2002-11-06","company_dissolved":"2005-09-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820642","names":[{"lang":"en","v":"FRANCE LOUISIBAICK (CHINA) LIMITED"},{"lang":"hk","v":"法國路易柏高(中國)有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820714","names":[{"lang":"en","v":"FRANCE YASHI GROUP (H.K.) CO., LIMITED"},{"lang":"hk","v":"法國雅詩集團(香港)有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820709","names":[{"lang":"en","v":"FRANCE YORK HON SITE KA (H.K.) FASHION COMPANY LIMITED"},{"lang":"hk","v":"法國約翰世家(香港)服飾有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820653","names":[{"lang":"en","v":"FU WING WA FOOD HOLDINGS LIMITED"},{"lang":"hk","v":"富榮華食品集團有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820486","names":[{"lang":"en","v":"HK DAILY GROUP INT'L DEV. LIMITED"},{"lang":"hk","v":"香港每日集團國際發展有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820553","names":[{"lang":"en","v":"HK INTERNATIONAL PERFUME GROUP TECHNOLOGY DEVELOPMENT CO., LIMITED"},{"lang":"hk","v":"香港國際香科集團科技發展有限公司"}],"company_since":"2002-11-06","company_dissolved":"2011-02-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820529","names":[{"lang":"en","v":"HK TOPDO MARKETING COMMUNICATION CO., LIMITED"},{"lang":"hk","v":"香港太度營銷傳播有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820452","names":[{"lang":"en","v":"HMC INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"海明國際管理顧問服務有限公司"}],"company_since":"2002-11-06","company_dissolved":"2011-08-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820587","names":[{"lang":"en","v":"HOI JAN CLUB LIMITED"},{"lang":"hk","v":"海雀會有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820712","names":[{"lang":"en","v":"HONG KONG BAO LI LAI INTERNATIONAL CO., LIMITED"},{"lang":"hk","v":"香港寶利來國際有限公司"}],"company_since":"2002-11-06","company_dissolved":"2014-07-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820525","names":[{"lang":"en","v":"GAOLING INTERNATIONAL MEDICAL APPARATUS AND INSTRUMENTS LIMITED"},{"lang":"hk","v":"高靈國際醫療器械有限公司"}],"company_since":"2002-11-06","company_dissolved":"2004-06-25","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820674","names":[{"lang":"en","v":"HONG KONG CENTURY LOPAN GROUP COMPANY LIMITED"},{"lang":"hk","v":"香港世紀魯班集團有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820546","names":[{"lang":"en","v":"GARBER (HK) LIMITED"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820632","names":[{"lang":"en","v":"HONG KONG CHENGSHUN FOOD LIMITED"},{"lang":"hk","v":"香港成順食品有限公司"}],"company_since":"2002-11-06","company_dissolved":"2007-10-18","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820583","names":[{"lang":"en","v":"HONG KONG HANG FUNG MOTORS COMPANY LIMITED"},{"lang":"hk","v":"香港恒豐汽車有限公司"}],"company_since":"2002-11-06","company_dissolved":"2010-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820695","names":[{"lang":"en","v":"HONG KONG HIGH QUALITY ELECTRICAL ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"香港優質電機工程有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820639","names":[{"lang":"en","v":"HONG KONG INTERNATIONAL VENTURES LIMITED"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820510","names":[{"lang":"en","v":"GERMANY DUOMEI INTERNATIONAL GROUP (HK) LIMITED"},{"lang":"hk","v":"德國多美國際集團(香港)有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820605","names":[{"lang":"en","v":"FREMERY SHIPPING LIMITED"},{"lang":"hk","v":"華隆航運有限公司"}],"company_since":"2002-11-06","company_dissolved":"2015-08-14","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820552","names":[{"lang":"en","v":"HONG KONG NEW SKY DEVELOPMENT CO., LIMITED"},{"lang":"hk","v":"香港新天發展有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820449","names":[{"lang":"en","v":"HONG KONG NORTH WEST EXPRESS LIMITED"},{"lang":"hk","v":"香港西北航運快線有限公司"}],"company_since":"2002-11-06","company_dissolved":"2018-01-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820701","names":[{"lang":"en","v":"HONG KONG PACIFIC MARBLE (ENG) LIMITED"},{"lang":"hk","v":"香港匯才雲石(工程)有限公司"}],"company_since":"2002-11-06","company_dissolved":"2006-10-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820720","names":[{"lang":"en","v":"HONG KONG PAK TAI ECONOMIC DEVELOPMENT LIMITED"},{"lang":"hk","v":"香港百泰經濟發展有限公司"}],"company_since":"2002-11-06","company_dissolved":"2004-08-06","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820585","names":[{"lang":"en","v":"GREAT TECH ASIA LIMITED"},{"lang":"hk","v":"科偉亞洲有限公司"}],"company_since":"2002-11-06","company_dissolved":"2003-10-03","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820646","names":[{"lang":"en","v":"HONG KONG STATELY INT'L ORNAMENT CONSTRUCTION LIMITED"},{"lang":"hk","v":"香港堂皇國際裝飾工程有限公司"}],"company_since":"2002-11-06","company_dissolved":"2009-07-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820686","names":[{"lang":"en","v":"HONG KONG TONG SHI ENTERPRISE (INT'L) GROUP DEVELOPMENT COMPANY LIMITED"},{"lang":"hk","v":"香港童氏企業(國際)集團發展有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820711","names":[{"lang":"en","v":"Hong Kong Tongen Holding Group Co., Limited"},{"lang":"hk","v":"香港同恩控股集團有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820517","names":[{"lang":"en","v":"HONG KONG YAT SING DEVELOPMENT LIMITED"},{"lang":"hk","v":"香港日星發展有限公司"}],"company_since":"2002-11-06","company_dissolved":"2017-04-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820588","names":[{"lang":"en","v":"H.K. YUYING FASHION LIMITED"},{"lang":"hk","v":"香港宇瑩服飾有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820469","names":[{"lang":"en","v":"HONGKONG BESTAIR INTERNATIONAL CO., LIMITED"},{"lang":"hk","v":"香港伯仕德國際有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820726","names":[{"lang":"en","v":"H.K. ZHENXING INT'L FURNITURE LIMITED"},{"lang":"hk","v":"香港振興國際家具有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820540","names":[{"lang":"en","v":"HONGKONG IM ALONE FASHION CO., LIMITED"},{"lang":"hk","v":"香港依夢來服飾有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820643","names":[{"lang":"en","v":"HANG LEE TRANSPORTATION ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"恒利搬機工程有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820708","names":[{"lang":"en","v":"HOP LUN INTERNATIONAL FASHION LIMITED"},{"lang":"hk","v":"合隆國際服裝有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820614","names":[{"lang":"en","v":"HIGHPOINT TECHNOLOGIES LIMITED"},{"lang":"hk","v":"駿昇科技有限公司"}],"company_since":"2002-11-06","company_dissolved":"2005-09-02","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820599","names":[{"lang":"en","v":"HUADU HONGJI INDUSTRIAL (HONG KONG) LIMITED"},{"lang":"hk","v":"花都宏基實業(香港)有限公司"}],"company_since":"2002-11-06","company_dissolved":"2007-11-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820652","names":[{"lang":"en","v":"HING FAT CONSTRUCTION COMPANY LIMITED"},{"lang":"hk","v":"興發裝飾工程有限公司"}],"company_since":"2002-11-06","company_dissolved":"2018-01-12","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820466","names":[{"lang":"en","v":"HUNG LEE ENGINEERING &amp; DECO LIMITED"},{"lang":"hk","v":"鴻利裝飾工程有限公司"}],"company_since":"2002-11-06","company_dissolved":"2010-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820640","names":[{"lang":"en","v":"HING TAT FIBREGLASS PRODUCTS LIMITED"},{"lang":"hk","v":"興達玻纖製品有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820464","names":[{"lang":"en","v":"HONGKONG ZHENHUA ECONOMY &amp; TRADING TECHNOLOGY (GROUP) LIMITED"},{"lang":"hk","v":"香港振華經貿科技(集團)有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820690","names":[{"lang":"en","v":"IMPERIAL GROUP INVESTMENTS LIMITED"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820637","names":[{"lang":"en","v":"IMPORT CLUB COMPANY LIMITED"},{"lang":"hk","v":"駿雅進出口有限公司"}],"company_since":"2002-11-06","company_dissolved":"2006-09-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820595","names":[{"lang":"en","v":"IMT METAL (ASIA) LIMITED"},{"lang":"hk","v":"英特金屬(亞洲)有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820670","names":[{"lang":"en","v":"INFO DEVELOPMENT LIMITED"},{"lang":"hk","v":"資富發展有限公司"}],"company_since":"2002-11-06","company_dissolved":"2012-09-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820576","names":[{"lang":"en","v":"HONGKONG OU LAI SHI FURNITURE INT'L GROUP LIMITED"},{"lang":"hk","v":"香港歐萊仕家私國際集團有限公司"}],"company_since":"2002-11-06","company_dissolved":"2011-11-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820648","names":[{"lang":"en","v":"INFOMATRIX INVESTMENT (H.K.) COMPANY LIMITED"},{"lang":"hk","v":"盈豐商務(香港)有限公司"}],"company_since":"2002-11-06","company_dissolved":"2004-09-17","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820519","names":[{"lang":"en","v":"IMI ASIA LIMITED"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
undefined,
undefined,
{"tax_id":"820439","names":[{"lang":"en","v":"KAI LI INVESTMENT LIMITED"},{"lang":"hk","v":"凱利投資股份有限公司"}],"company_since":"2002-11-06","company_dissolved":"2012-04-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820530","names":[{"lang":"en","v":"KAKA STATIONERY (HONG KONG) COMPANY LIMITED"},{"lang":"hk","v":"嘉嘉文具(香港)有限公司"}],"company_since":"2002-11-06","company_dissolved":"2007-10-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820665","names":[{"lang":"en","v":"KATO (HONG KONG) LIMITED"},{"lang":"hk","v":"啟濤(香港)有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820515","names":[{"lang":"en","v":"JALERM INDUSTRIES LIMITED"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820557","names":[{"lang":"en","v":"KEF COMPANY LIMITED"},{"lang":"hk","v":"凱富雅有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820644","names":[{"lang":"en","v":"KELFO INTERNATIONAL INDUSTRIAL CO., LIMITED"},{"lang":"hk","v":"嘉福國際實業有限公司"}],"company_since":"2002-11-06","company_dissolved":"2007-03-02","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820462","names":[{"lang":"en","v":"JANZTAI INT'L GROUP (HK) LIMITED"},{"lang":"hk","v":"健之態國際集團(香港)有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-08-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820460","names":[{"lang":"en","v":"KEYNOR (H.K.) COMPANY LIMITED"}],"company_since":"2002-11-06","company_dissolved":"2011-09-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820707","names":[{"lang":"en","v":"KOO KEE ENGINEERING COMPANY LIMITED"},{"lang":"hk","v":"古記工程有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820715","names":[{"lang":"en","v":"JINCHENG GROUP (H.K.) LIMITED"},{"lang":"hk","v":"金誠集團(香港)有限公司"}],"company_since":"2002-11-06","company_dissolved":"2010-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820446","names":[{"lang":"en","v":"JINDEN INVESTMENT LIMITED"},{"lang":"hk","v":"金嶝投資有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820480","names":[{"lang":"en","v":"LA JACQUES MODE LIMITED"}],"company_since":"2002-11-06","company_dissolved":"2014-08-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820611","names":[{"lang":"en","v":"LE WON GROUP LIMITED"},{"lang":"hk","v":"來富集團有限公司"}],"company_since":"2002-11-06","company_dissolved":"2006-07-21","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820662","names":[{"lang":"en","v":"LEE YOUNG GROUP LIMITED"},{"lang":"hk","v":"李楊集團有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820560","names":[{"lang":"en","v":"JINPENG SPECIAL BIOLOGICAL COMPANY LIMITED"},{"lang":"hk","v":"金鵬特種生物工程有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820564","names":[{"lang":"en","v":"Liberty Hills Hong Kong Limited"},{"lang":"hk","v":"自由丘有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-01-04","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820713","names":[{"lang":"en","v":"LIFU (H.K.) JEWELRY GROUP LIMITED"},{"lang":"hk","v":"立福(香港)珠寶集團有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820456","names":[{"lang":"en","v":"LIGHTSPEED EXPRESS COMPANY LIMITED"},{"lang":"hk","v":"光速快遞有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820634","names":[{"lang":"en","v":"LINA INTERNATIONAL COMPANY LIMITED"},{"lang":"hk","v":"蓮娜國際有限公司"}],"company_since":"2002-11-06","company_dissolved":"2016-08-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820493","names":[{"lang":"en","v":"LINCOTRADE CORPORATION (CHINA) LIMITED"}],"company_since":"2002-11-06","company_dissolved":"2007-01-12","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820630","names":[{"lang":"en","v":"JUBILEE ENTERPRISES LIMITED (d2014-03-21)"},{"lang":"hk","v":"駿利企業有限公司"}],"company_since":"2002-11-06","company_dissolved":"2014-03-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820533","names":[{"lang":"en","v":"LONG SURE INDUSTRIES LIMITED"},{"lang":"hk","v":"良信實業有限公司"}],"company_since":"2002-11-06","company_dissolved":"2011-04-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820451","names":[{"lang":"en","v":"LOVE OCEAN CO. LIMITED"},{"lang":"hk","v":"愛海有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820625","names":[{"lang":"en","v":"LOYAL EAGLE CORPORATION LIMITED"},{"lang":"hk","v":"豪鷹有限公司"}],"company_since":"2002-11-06","company_dissolved":"2015-08-07","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820659","names":[{"lang":"en","v":"KE DEVELOPMENT (ASIA) CO. LIMITED"},{"lang":"hk","v":"創溢拓展(亞洲)有限公司"}],"company_since":"2002-11-06","company_dissolved":"2004-09-24","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820618","names":[{"lang":"en","v":"LOYALE DEVELOPMENT LIMITED"},{"lang":"hk","v":"利宜發展有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820677","names":[{"lang":"en","v":"MAN PO ENVIRONMENT TECHNOLOGIES CO., LIMITED"},{"lang":"hk","v":"文寶環保科技有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820578","names":[{"lang":"en","v":"MAPPA LIMITED (d2008-03-20)"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820550","names":[{"lang":"en","v":"MAX ZONE (HK) LIMITED"},{"lang":"hk","v":"協域(香港)有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820654","names":[{"lang":"en","v":"MCKENZIE &amp; ASSOCIATES REHABILITATION SERVICES LIMITED"},{"lang":"hk","v":"麥堅時復康服務中心有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820657","names":[{"lang":"en","v":"KING OF PET CLUB LIMITED"},{"lang":"hk","v":"銀鈴寵物專業美容會舍有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820601","names":[{"lang":"en","v":"MEIR HSIN INTERNATIONAL (H.K.) CO., LIMITED"},{"lang":"hk","v":"美欣國際(香港)有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820702","names":[{"lang":"en","v":"MELUX INTERNATIONAL INVESTMENT COMPANY LIMITED"},{"lang":"hk","v":"美林(香港)國際投資有限公司"}],"company_since":"2002-11-06","company_dissolved":"2018-10-05","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820733","names":[{"lang":"en","v":"KOREA DAIBU INTERNATIONAL TRADING LIMITED"},{"lang":"hk","v":"韓國大富國際貿易有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-08-08","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820603","names":[{"lang":"en","v":"MICHELE WATCH (FAR EAST) LIMITED"}],"company_since":"2002-11-06","company_dissolved":"2007-06-30","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820681","names":[{"lang":"en","v":"KST SHIPPING LIMITED"},{"lang":"hk","v":"鑫燊堂船務有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-05-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820558","names":[{"lang":"en","v":"MIND YOUR LANGUAGE LIMITED (HK)"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820507","names":[{"lang":"en","v":"MIRACLE INTERNATIONAL HOLDINGS LIMITED"},{"lang":"hk","v":"美瑞嘉國際集團有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820536","names":[{"lang":"en","v":"MULTI-CONCEPTS MARKETING CONSULTANTS LIMITED"},{"lang":"hk","v":"衆念新思市場顧問有限公司"}],"company_since":"2002-11-06","company_dissolved":"2016-01-29","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820495","names":[{"lang":"en","v":"NEOSUN (GROUP) INTERNATIONAL INVESTMENT LIMITED (d2005-09-23)"},{"lang":"hk","v":"日新(集團)國際投資有限公司"}],"company_since":"2002-11-06","company_dissolved":"2005-09-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820569","names":[{"lang":"en","v":"NEPTUNE MARINE PRODUCTS COMPANY LIMITED"},{"lang":"hk","v":"海皇海產有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820522","names":[{"lang":"en","v":"OKADE DIGITAL ELECTRONICS LIMITED"},{"lang":"hk","v":"岡祺數碼電子有限公司"}],"company_since":"2002-11-06","company_dissolved":"2013-05-10","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820524","names":[{"lang":"en","v":"OLYS-DIGITAL CO., LIMITED"},{"lang":"hk","v":"奧林斯科技有限公司"}],"company_since":"2002-11-06","company_dissolved":"2012-03-16","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820470","names":[{"lang":"en","v":"LIEO INDUSTRIAL COMPANY LIMITED"},{"lang":"hk","v":"力侑實業有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820561","names":[{"lang":"en","v":"PACIFIC GAME TECHNOLOGY (HOLDING) LIMITED"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820545","names":[{"lang":"en","v":"PACTRADE HONG KONG LIMITED"}],"company_since":"2002-11-06","company_dissolved":"2018-07-06","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820496","names":[{"lang":"en","v":"PEARL RIVER BASIN ENVIRONMENTAL PROTECTION (HONG KONG) LIMITED"},{"lang":"hk","v":"珠江流域環保(香港)有限公司"}],"company_since":"2002-11-06","company_dissolved":"2009-03-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820509","names":[{"lang":"en","v":"PFLAUM (CHINA) BUILDING SYSTEMS CO., LIMITED"},{"lang":"hk","v":"康賽中國有限公司"}],"company_since":"2002-11-06","company_dissolved":"2016-05-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820735","names":[{"lang":"en","v":"LOGISTIC TECHNOLOGY LIMITED"},{"lang":"hk","v":"邏輯科技有限公司"}],"company_since":"2002-11-06","company_dissolved":"2015-09-11","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820727","names":[{"lang":"en","v":"PHENIX HONG KONG LIMITED"},{"lang":"hk","v":"鳳凰光電香港有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820450","names":[{"lang":"en","v":"PINSTRIPE HONG KONG LIMITED"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820729","names":[{"lang":"en","v":"PLANT SYSTEMS (HK) LIMITED"},{"lang":"hk","v":"香港工程設備有限公司"}],"company_since":"2002-11-06","company_dissolved":"2010-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820562","names":[{"lang":"en","v":"PLUS ALPHA LIMITED"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820445","names":[{"lang":"en","v":"LOYAL FORTUNE INVESTMENT LIMITED (d2004-01-09)"},{"lang":"hk","v":"鴻福投資有限公司"}],"company_since":"2002-11-06","company_dissolved":"2004-01-09","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820498","names":[{"lang":"en","v":"PMC POOL MANAGEMENT LIMITED"},{"lang":"hk","v":"沛溢泳池管理有限公司"}],"company_since":"2002-11-06","company_dissolved":"2011-11-18","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820481","names":[{"lang":"en","v":"PREMIER INDUSTRIES (HK) LIMITED"},{"lang":"hk","v":"先迪實業(香港)有限公司"}],"company_since":"2002-11-06","company_dissolved":"2009-04-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820555","names":[{"lang":"en","v":"PRESIDENT TEX LIMITED"},{"lang":"hk","v":"成發(中港)有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820575","names":[{"lang":"en","v":"PRO-ENVIROTEC LIMITED"},{"lang":"hk","v":"安德環科有限公司"}],"company_since":"2002-11-06","company_dissolved":"2012-07-20","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820622","names":[{"lang":"en","v":"PROFIT WINNERS LIMITED (d2019-04-18)"},{"lang":"hk","v":"盈威有限公司"}],"company_since":"2002-11-06","company_dissolved":"2019-04-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820454","names":[{"lang":"en","v":"PWHH DESIGN (HK) LIMITED"},{"lang":"hk","v":"香港鵬文惠華設計有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820505","names":[{"lang":"en","v":"RADIANT TRAVEL LIMITED"},{"lang":"hk","v":"星耀旅運有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820641","names":[{"lang":"en","v":"RED SUN INTERNATIONAL TRADE CO., LIMITED"},{"lang":"hk","v":"瑞盛國際貿易有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820441","names":[{"lang":"en","v":"REGICAL HOLDINGS COMPANY LIMITED"},{"lang":"hk","v":"吉高控股有限公司"}],"company_since":"2002-11-06","company_dissolved":"2009-03-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820736","names":[{"lang":"en","v":"RIMCAPITAL ADVISORS (HONG KONG) LIMITED"}],"company_since":"2002-11-06","company_dissolved":"2005-07-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820537","names":[{"lang":"en","v":"S B C LIMITED"},{"lang":"hk","v":"俬保斯有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820617","names":[{"lang":"en","v":"ONESTOP TECHNOLOGIES INTERNATIONAL LIMITED"},{"lang":"hk","v":"國際萬斯達科技有限公司"}],"company_since":"2002-11-06","company_dissolved":"2010-04-01","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820651","names":[{"lang":"en","v":"S.I.R.A. INTERNATIONAL LIMITED"}],"company_since":"2002-11-06","company_dissolved":"2017-05-26","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820700","names":[{"lang":"en","v":"ORIENTAL GREAT ACHIEVEMENTS (CHINA) INVESTMENT HOLDING CO., LIMITED"},{"lang":"hk","v":"東方偉業(中國)投資控股有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820577","names":[{"lang":"en","v":"SABRE INTERNATIONAL (HK) LIMITED"}],"company_since":"2002-11-06","company_dissolved":"2009-03-27","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820635","names":[{"lang":"en","v":"P &amp; G CONSULTANTS LIMITED"},{"lang":"hk","v":"展瑋顧問有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820650","names":[{"lang":"en","v":"SAM YAU WOOL KNITTING CO., LIMITED"},{"lang":"hk","v":"三友毛織有限公司"}],"company_since":"2002-11-06","company_dissolved":"2006-04-28","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820723","names":[{"lang":"en","v":"SAN LUH SHIPPING (HK) CO. LIMITED"},{"lang":"hk","v":"三陸船務(香港)有限公司"}],"company_since":"2002-11-06","company_dissolved":"2013-02-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820501","names":[{"lang":"en","v":"SAVORY &amp; TASTY FOOD AND BEVERAGE (HK) LIMITED"},{"lang":"hk","v":"香港和味濃餐飲調料有限公司"}],"company_since":"2002-11-06","company_dissolved":"2014-09-26","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820559","names":[{"lang":"en","v":"SEA POWER GROUP (HOLDINGS) CO., LIMITED"},{"lang":"hk","v":"海豐集團(控股)有限公司"}],"company_since":"2002-11-06","company_dissolved":"2010-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820609","names":[{"lang":"en","v":"SERENA &amp; SPENSER HOLDING LIMITED"},{"lang":"hk","v":"楓葉情有限公司"}],"company_since":"2002-11-06","company_dissolved":"2013-06-07","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820704","names":[{"lang":"en","v":"SHENZHEN INTERNATIONAL INVESTMENT CO. LIMITED"},{"lang":"hk","v":"深業國際投資策劃有限公司"}],"company_since":"2002-11-06","company_dissolved":"2010-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820722","names":[{"lang":"en","v":"SHING HING HONG INVESTMENT LIMITED"},{"lang":"hk","v":"誠興行投資有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820511","names":[{"lang":"en","v":"SHUI HING LUNG CO., LIMITED"},{"lang":"hk","v":"瑞興隆有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820438","names":[{"lang":"en","v":"SHUN YEUNG LUI CHO SIN TEEN COMPANY LIMITED"},{"lang":"hk","v":"純陽呂祖仙壇有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Ltd by guarantee"},
undefined,
{"tax_id":"820554","names":[{"lang":"en","v":"LANDING MASTER PARTNERS INTELLECTUAL PROPERTY LIMITED"},{"lang":"hk","v":"隆天聯鼎知識產權有限公司"}],"company_since":"2002-11-06","company_dissolved":"2009-10-09","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820623","names":[{"lang":"en","v":"PREMIER TRAVEL SERVICES COMPANY LIMITED"},{"lang":"hk","v":"卓越假期旅運有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820596","names":[{"lang":"en","v":"SNACK PORTAL GROUP COMPANY LIMITED"},{"lang":"hk","v":"食贏堡集團有限公司"}],"company_since":"2002-11-06","company_dissolved":"2005-04-22","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820685","names":[{"lang":"en","v":"SOLARI DESIGN &amp; FURNITURE LIMITED"},{"lang":"hk","v":"昇輝設計(傢具)有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820710","names":[{"lang":"en","v":"SOLARI FURNITURE &amp; DESIGN LIMITED"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820461","names":[{"lang":"en","v":"QUINTESSENCE OF CHINESE CULTURE MEDIA (GROUP) LIMITED (THE)"},{"lang":"hk","v":"國粹傳媒(集團)有限公司"}],"company_since":"2002-11-06","company_dissolved":"2017-09-01","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820568","names":[{"lang":"en","v":"SOPHORA HONG KONG COMPANY LIMITED"},{"lang":"hk","v":"索福拉香港有限公司"}],"company_since":"2002-11-06","company_dissolved":"2006-06-02","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820680","names":[{"lang":"en","v":"SQC CO LIMITED"}],"company_since":"2002-11-06","company_dissolved":"2010-04-01","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820500","names":[{"lang":"en","v":"RONGSHIDA INDUSTRIAL CO., LIMITED"},{"lang":"hk","v":"榮世達產業有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820696","names":[{"lang":"en","v":"STONESAGE LIMITED"},{"lang":"hk","v":"青睿有限公司"}],"company_since":"2002-11-06","company_dissolved":"2013-08-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820728","names":[{"lang":"en","v":"ROYAL LOGISTICS LIMITED (d2004-06-18)"},{"lang":"hk","v":"榮達物流有限公司"}],"company_since":"2002-11-06","company_dissolved":"2004-06-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820724","names":[{"lang":"en","v":"SUNNYNDOFARMA CORP., LIMITED"}],"company_since":"2002-11-06","company_dissolved":"2009-01-23","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820734","names":[{"lang":"en","v":"SUNPOWER (HONG KONG) INTERNATIONAL LIMITED"},{"lang":"hk","v":"中聖國際有限公司"}],"company_since":"2002-11-06","company_dissolved":"2005-04-22","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820549","names":[{"lang":"en","v":"SUNRENN INTERNATIONAL TECHNOLOGY LIMITED"},{"lang":"hk","v":"太陽雨國際科技股份有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820516","names":[{"lang":"en","v":"SURETECH PROJECTS CONSULTANTS LIMITED"},{"lang":"hk","v":"利東工程顧問有限公司"}],"company_since":"2002-11-06","company_dissolved":"2020-09-25","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820607","names":[{"lang":"en","v":"SWISS GUGGI PRECIOUS WATCH (HONG KONG) LIMITED"},{"lang":"hk","v":"瑞士古琦精密計時(香港)有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820541","names":[{"lang":"en","v":"T.F.F. (H.K.) INTERNATIONAL GROUP LIMITED (d2004-07-16)"},{"lang":"hk","v":"凱飛特(香港)國際集團有限公司"}],"company_since":"2002-11-06","company_dissolved":"2004-07-16","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820684","names":[{"lang":"en","v":"TENWELL INTERNATIONAL LIMITED"},{"lang":"hk","v":"天地華國際有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820699","names":[{"lang":"en","v":"SHANGHAI TONGHUI MEDICAL TECHNOLOGY (H.K.) LIMITED"},{"lang":"hk","v":"上海通匯醫療科技(香港)有限公司"}],"company_since":"2002-11-06","company_dissolved":"2004-12-17","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820472","names":[{"lang":"en","v":"THOUSAND COLOUR FURNITURES LIMITED"},{"lang":"hk","v":"千色家居有限公司"}],"company_since":"2002-11-06","company_dissolved":"2004-07-30","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820465","names":[{"lang":"en","v":"TIP-TOP INTERNATIONAL DEVELOPMENT LIMITED"},{"lang":"hk","v":"帝拓國際發展有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820543","names":[{"lang":"en","v":"UDC LIMITED (HK)"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
undefined,
{"tax_id":"820676","names":[{"lang":"en","v":"UNICORP INDUSTRIAL COMPANY LIMITED"},{"lang":"hk","v":"聯企實業有限公司"}],"company_since":"2002-11-06","company_dissolved":"2011-06-24","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820613","names":[{"lang":"en","v":"UNIFAITH ENGINEERING LIMITED"},{"lang":"hk","v":"信聯工程有限公司"}],"company_since":"2002-11-06","company_dissolved":"2005-03-24","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820689","names":[{"lang":"en","v":"ULTIMATE TRADING LIMITED (d2015-03-27)"},{"lang":"hk","v":"宏歷貿易有限公司"}],"company_since":"2002-11-06","company_dissolved":"2015-03-27","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820566","names":[{"lang":"en","v":"SKS INTERNATIONAL LIMITED (d2004-06-11)"},{"lang":"hk","v":"水口山國際有限公司"}],"company_since":"2002-11-06","company_dissolved":"2004-06-11","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820473","names":[{"lang":"en","v":"SILVER &amp; RAINBOW INTERNATIONAL TRADING LIMITED"},{"lang":"hk","v":"銀虹國際貿易有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820719","names":[{"lang":"en","v":"SIGFEN 1 PTE LIMITED"}],"company_since":"2002-11-06","company_dissolved":"2012-09-21","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820606","names":[{"lang":"en","v":"VA TECH TRANSMISSION &amp; DISTRIBUTION GMBH &amp; CO KEG LIMITED"},{"lang":"hk","v":"維奧技術輸配電有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820512","names":[{"lang":"en","v":"VEE CARE (ASIA) LIMITED"},{"lang":"hk","v":"威康亞洲有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
undefined,
{"tax_id":"820716","names":[{"lang":"en","v":"SPEEDMAX LOGISTICS (INTERNATIONAL) LIMITED"},{"lang":"hk","v":"滙達物流(國際)有限公司"}],"company_since":"2002-11-06","company_dissolved":"2008-03-20","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820647","names":[{"lang":"en","v":"SPS FAR EAST LIMITED"},{"lang":"hk","v":"安全紙業及器材有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820600","names":[{"lang":"en","v":"STANDARD CERTIFICATION (HONG KONG) LIMITED"},{"lang":"hk","v":"德國圖林根技術監督(香港)有限公司"}],"company_since":"2002-11-06","company_dissolved":"2004-03-19","company_type_txt":"Private, ltd by shares"},
undefined,
{"tax_id":"820612","names":[{"lang":"en","v":"STARZ GROUP INVESTMENT LIMITED"},{"lang":"hk","v":"滙星集團投資有限公司"}],"company_since":"2002-11-06","company_dissolved":"2011-11-18","company_type_txt":"Private, ltd by shares"},
{"tax_id":"820474","names":[{"lang":"en","v":"WAF LOGISTICS LIMITED"},{"lang":"hk","v":"緯富物流有限公司"}],"company_since":"2002-11-06","company_dissolved":"","company_type_txt":"Private, ltd by shares"},
undefined,
